.TH "Source/Lib/Common/FileSystems/Models/AncestorDirectory.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Common/FileSystems/Models/AncestorDirectory.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.AncestorDirectory\fP"
.br
.RI "This class exists alongside the \fBIAbsolutePath\fP type\&. This is intentional, as if one treats an ancestor directory as an \fBIAbsolutePath\fP, then far more "metadata" gets created\&.
.br

.br
\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
