.TH "Source/Lib/CompilerServices/DotNetSolution/Models/Associated/AssociatedEntryGroup.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/CompilerServices/DotNetSolution/Models/Associated/AssociatedEntryGroup.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.CompilerServices\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.CompilerServices\&.DotNetSolution\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Associated\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "record \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Associated\&.AssociatedEntryGroup\fP"
.br
.ti -1c
.RI "record ImmutableArray< \fBIAssociatedEntry\fP > \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Associated\&.associatedEntryList\fP"
.br
.ti -1c
.RI "record ImmutableArray< \fBIAssociatedEntry\fP > \fBCloseAssociatedGroupToken\fP \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Associated\&.closeAssociatedGroupToken\fP"
.br
.ti -1c
.RI "OpenAssociatedGroupToken \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Associated\&.OpenAssociatedGroupToken\fP\fR [get]\fP"
.br
.ti -1c
.RI "ImmutableArray< \fBIAssociatedEntry\fP > \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Associated\&.AssociatedEntryList\fP\fR [get]\fP"
.br
.ti -1c
.RI "CloseAssociatedGroupToken \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Associated\&.CloseAssociatedGroupToken\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBAssociatedEntryKind\fP \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Associated\&.AssociatedEntryKind\fP\fR [get]\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
