.TH "Source/Tests/Ide/Basis/Terminals/States Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Tests/Ide/Basis/Terminals/States Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBTerminalStateActionsTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBTerminalStateMainTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBTerminalStateReducerTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBTerminalWasModifiedStateActionsTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBTerminalWasModifiedStateMainTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBTerminalWasModifiedStateReducerTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBWellKnownTerminalStateActionsTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBWellKnownTerminalStateMainTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBWellKnownTerminalStateReducerTests\&.cs\fP"
.br
.in -1c
