.TH "Source/Lib/Extensions/Extensions.Git/Displays Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Extensions/Extensions.Git/Displays Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBGitAddRepoDisplay\&.razor\&.cs\fP"
.br
.ti -1c
.RI "file \fBGitBranchCheckoutDisplay\&.razor\&.cs\fP"
.br
.ti -1c
.RI "file \fBGitChangesContextMenu\&.razor\&.cs\fP"
.br
.ti -1c
.RI "file \fBGitChangesDisplay\&.razor\&.cs\fP"
.br
.ti -1c
.RI "file \fBGitChangesTreeViewDisplay\&.razor\&.cs\fP"
.br
.ti -1c
.RI "file \fBGitControlsDisplay\&.razor\&.cs\fP"
.br
.ti -1c
.RI "file \fBGitDiffDisplay\&.razor\&.cs\fP"
.br
.ti -1c
.RI "file \fBGitDisplay\&.razor\&.cs\fP"
.br
.ti -1c
.RI "file \fBGitInteractiveIconDisplay\&.razor\&.cs\fP"
.br
.ti -1c
.RI "file \fBGitOriginDisplay\&.razor\&.cs\fP"
.br
.ti -1c
.RI "file \fBTreeViewGitFileDisplay\&.razor\&.cs\fP"
.br
.ti -1c
.RI "file \fBTreeViewGitFileGroupDisplay\&.razor\&.cs\fP"
.br
.in -1c
