.TH "Source/Lib/TextEditor/Decorations/Models Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/TextEditor/Decorations/Models Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDecorationMapperRegistryDefault \&.cs\fP"
.br
.ti -1c
.RI "file \fBIDecorationMapper\&.cs\fP"
.br
.ti -1c
.RI "file \fBIDecorationMapperRegistry\&.cs\fP"
.br
.ti -1c
.RI "file \fBITextEditorRegistryWrap\&.cs\fP"
.br
.ti -1c
.RI "file \fBTextEditorDecorationMapperDefault\&.cs\fP"
.br
.ti -1c
.RI "file \fBTextEditorPresentationModel\&.cs\fP"
.br
.ti -1c
.RI "file \fBTextEditorPresentationModelCalculation\&.cs\fP"
.br
.ti -1c
.RI "file \fBTextEditorRegistryWrap\&.cs\fP"
.br
.ti -1c
.RI "file \fBTextEditorTextModification\&.cs\fP"
.br
.in -1c
