.TH "Source/Lib/Extensions/Extensions.Git/Models Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Extensions/Extensions.Git/Models Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBGitCliOutputParser\&.cs\fP"
.br
.ti -1c
.RI "file \fBGitDirtyReason\&.cs\fP"
.br
.ti -1c
.RI "file \fBGitFacts\&.cs\fP"
.br
.ti -1c
.RI "file \fBGitFile\&.cs\fP"
.br
.ti -1c
.RI "file \fBGitIdeApi\&.cs\fP"
.br
.ti -1c
.RI "file \fBGitRepo\&.cs\fP"
.br
.ti -1c
.RI "file \fBGitTask\&.cs\fP"
.br
.ti -1c
.RI "file \fBGitTreeViewKeyboardEventHandler\&.cs\fP"
.br
.ti -1c
.RI "file \fBGitTreeViewMouseEventHandler\&.cs\fP"
.br
.ti -1c
.RI "file \fBTreeViewGitFile\&.cs\fP"
.br
.ti -1c
.RI "file \fBTreeViewGitFileGroup\&.cs\fP"
.br
.in -1c
