.TH "Source/Lib/TextEditor/Commands/Models/Vims Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/TextEditor/Commands/Models/Vims Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBTextEditorCommandVimFacts\&.Motions\&.Commands\&.cs\fP"
.br
.ti -1c
.RI "file \fBTextEditorCommandVimFacts\&.Motions\&.Functions\&.cs\fP"
.br
.ti -1c
.RI "file \fBTextEditorCommandVimFacts\&.Verbs\&.Commands\&.cs\fP"
.br
.ti -1c
.RI "file \fBTextEditorCommandVimFacts\&.Verbs\&.Functions\&.cs\fP"
.br
.in -1c
