.TH "Source/Tests/Common/Basis/WatchWindows Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Tests/Common/Basis/WatchWindows Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBModels\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBIPersonTest\&.cs\fP"
.br
.ti -1c
.RI "file \fBPersonTest\&.cs\fP"
.br
.ti -1c
.RI "file \fBWatchWindowsTestsHelper\&.cs\fP"
.br
.in -1c
