.TH "Source/Lib/Extensions/Extensions.Git/States Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Extensions/Extensions.Git/States Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBGitState\&.Actions\&.cs\fP"
.br
.ti -1c
.RI "file \fBGitState\&.Effector\&.cs\fP"
.br
.ti -1c
.RI "file \fBGitState\&.Main\&.cs\fP"
.br
.ti -1c
.RI "file \fBGitState\&.Reducer\&.cs\fP"
.br
.in -1c
