.TH "Source/Lib/Ide/Ide.RazorLib/AppDatas/Models Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Ide/Ide.RazorLib/AppDatas/Models Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDoNothingAppDataService\&.cs\fP"
.br
.ti -1c
.RI "file \fBIAppData\&.cs\fP"
.br
.ti -1c
.RI "file \fBIAppDataService\&.cs\fP"
.br
.ti -1c
.RI "file \fBIdeAppData\&.cs\fP"
.br
.ti -1c
.RI "file \fBNativeAppDataService\&.cs\fP"
.br
.in -1c
