.TH "Source/Tests/TextEditor/Basis/CompilerServices/GenericLexer/SyntaxObjects Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Tests/TextEditor/Basis/CompilerServices/GenericLexer/SyntaxObjects Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBGenericCommentMultiLineSyntaxTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBGenericCommentSingleLineSyntaxTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBGenericDeliminationExtendedSyntaxTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBGenericDocumentSyntaxTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBGenericFunctionSyntaxTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBGenericKeywordSyntaxTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBGenericPreprocessorDirectiveSyntaxTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBGenericStringSyntaxTests\&.cs\fP"
.br
.in -1c
