.TH "Docs/Common Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Docs/Common Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBFeatures\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Luthetus\&.Common"
.PP
.SH "Demo:"
.PP
https://luthetus.github.io/Luthetus.Ide/
.SH "Introduction"
.PP
\fI\fB\fBLuthetus\&.Common\fP\fP\fP is a general case component library using the \fRBlazor UI Framework\fP for \fR\&.NET\fP
.SH "Goal"
.PP
The aim of \fBLuthetus\&.Common\fP is to contain Blazor components that I frequently use across a variety of projects, yet are not overly cumbersome\&.

.PP
One can make use of this Text Editor by referencing the Nuget Package or cloning the source code and referencing it directly\&.
.SH "Getting started"
.PP
.IP "\(bu" 2
Video format: \fRYouTube video\fP
.IP "\(bu" 2
Markdown format: \fBinstallation\&.md\fP
.PP
.SH "Installation"
.PP
You can download the latest release NuGet packages from the official \fBLuthetus\&.Common\fP NuGet pages\&.

.PP
.IP "\(bu" 2
https://www.nuget.org/packages/Luthetus.Common/
.PP
.SH "Features"
.PP
.IP "\(bu" 2
\fBDialog\fP
.IP "\(bu" 2
\fBDropdown\fP
.IP "\(bu" 2
\fBIcons\fP
.IP "\(bu" 2
\fBMenu\fP
.IP "\(bu" 2
\fBNotification\fP
.IP "\(bu" 2
\fBResizableColumn\fP
.IP "\(bu" 2
\fBResizableDisplay\fP
.IP "\(bu" 2
\fBResizableRow\fP
.IP "\(bu" 2
\fBTheme\fP
.IP "\(bu" 2
\fBTreeView\fP
.IP "\(bu" 2
\fBWatchWindow\fP
.PP
.SH "Release notes / Changelog"
.PP
See the \fBchangelog\&.md\fP for release history\&.
.SH "Roadmap"
.PP
See the \fBroadmap\&.md\fP for planned future updates\&.
.SH "Licence"
.PP
\fRMIT\fP 
