.TH "Source/Lib/Common/Widgets/States Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Common/Widgets/States Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBWidgetState\&.Actions\&.cs\fP"
.br
.ti -1c
.RI "file \fBWidgetState\&.Effector\&.cs\fP"
.br
.ti -1c
.RI "file \fBWidgetState\&.Main\&.cs\fP"
.br
.ti -1c
.RI "file \fBWidgetState\&.Reducer\&.cs\fP"
.br
.in -1c
