.TH "Source/Tests/Ide/Basis/CodeSearches/States Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Tests/Ide/Basis/CodeSearches/States Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCodeSearchStateActionsTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBCodeSearchStateEffectorTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBCodeSearchStateMainTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBCodeSearchStateReducerTests\&.cs\fP"
.br
.in -1c
