.TH "Source/Lib/TextEditor/Diffs/Models Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/TextEditor/Diffs/Models Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBDiffPresentationFacts\&.cs\fP"
.br
.ti -1c
.RI "file \fBITextEditorDiffApi\&.cs\fP"
.br
.ti -1c
.RI "file \fBTextEditorDiffApi\&.cs\fP"
.br
.ti -1c
.RI "file \fBTextEditorDiffCell\&.cs\fP"
.br
.ti -1c
.RI "file \fBTextEditorDiffDecorationKind\&.cs\fP"
.br
.ti -1c
.RI "file \fBTextEditorDiffDecorationMapper\&.cs\fP"
.br
.ti -1c
.RI "file \fBTextEditorDiffModel\&.cs\fP"
.br
.ti -1c
.RI "file \fBTextEditorDiffModelModifier\&.cs\fP"
.br
.ti -1c
.RI "file \fBTextEditorDiffResult\&.cs\fP"
.br
.in -1c
