.TH "Source/Lib/Common/UnitTesting Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Common/UnitTesting Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCommonUnitTestHelper\&.cs\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This folder contains an implementation of all the \fBLuthetus\&.Common\fP services that one can use when writing a unit test\&.

.PP
Unit tests themselves do NOT belong in this folder\&. 
