.TH "Source/Lib/CompilerServices/Json Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/CompilerServices/Json Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBDecoration\fP"
.br
.ti -1c
.RI "directory \fBFacts\fP"
.br
.ti -1c
.RI "directory \fBSyntaxActors\fP"
.br
.ti -1c
.RI "directory \fBSyntaxEnums\fP"
.br
.ti -1c
.RI "directory \fBSyntaxObjects\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBIJsonSyntax\&.cs\fP"
.br
.ti -1c
.RI "file \fBJsonCompilerService\&.cs\fP"
.br
.ti -1c
.RI "file \fBJsonResource\&.cs\fP"
.br
.ti -1c
.RI "file \fBJsonSyntaxUnit\&.cs\fP"
.br
.in -1c
