.TH "Source/Lib/Common/Menus/Displays Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Common/Menus/Displays Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBMenuDisplay\&.razor\&.cs\fP"
.br
.ti -1c
.RI "file \fBMenuOptionDisplay\&.razor\&.cs\fP"
.br
.in -1c
