.TH "Source/Lib/Common/BackgroundTasks/Models Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Common/BackgroundTasks/Models Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBBackgroundTask\&.cs\fP"
.br
.ti -1c
.RI "file \fBBackgroundTaskQueue\&.cs\fP"
.br
.ti -1c
.RI "file \fBBackgroundTaskService\&.cs\fP"
.br
.ti -1c
.RI "file \fBBackgroundTaskServiceSynchronous\&.cs\fP"
.br
.ti -1c
.RI "file \fBBackgroundTaskWorker\&.cs\fP"
.br
.ti -1c
.RI "file \fBBlockingBackgroundTaskWorker\&.cs\fP"
.br
.ti -1c
.RI "file \fBCommonBackgroundTaskApi\&.cs\fP"
.br
.ti -1c
.RI "file \fBContinuousBackgroundTaskWorker\&.cs\fP"
.br
.ti -1c
.RI "file \fBIBackgroundTask\&.cs\fP"
.br
.ti -1c
.RI "file \fBIBackgroundTaskQueue\&.cs\fP"
.br
.ti -1c
.RI "file \fBIBackgroundTaskService\&.cs\fP"
.br
.in -1c
