.TH "Source/Lib/CompilerServices/Python/Facts Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/CompilerServices/Python/Facts Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBPythonLanguageFacts\&.Keywords\&.cs\fP"
.br
.ti -1c
.RI "file \fBPythonLanguageFacts\&.Main\&.cs\fP"
.br
.ti -1c
.RI "file \fBPythonLanguageFacts\&.PreprocessorDirectives\&.cs\fP"
.br
.ti -1c
.RI "file \fBPythonLanguageFacts\&.Punctuation\&.cs\fP"
.br
.ti -1c
.RI "file \fBPythonLanguageFacts\&.Whitespace\&.cs\fP"
.br
.in -1c
