.TH "Source/Lib/CompilerServices/DotNetSolution/Facts Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/CompilerServices/DotNetSolution/Facts Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBGlobal\&.cs\fP"
.br
.ti -1c
.RI "file \fBGlobalSection\&.cs\fP"
.br
.ti -1c
.RI "file \fBGlobalSectionExtensibilityGlobals\&.cs\fP"
.br
.ti -1c
.RI "file \fBGlobalSectionNestedProjects\&.cs\fP"
.br
.ti -1c
.RI "file \fBGlobalSectionProjectConfigurationPlatforms\&.cs\fP"
.br
.ti -1c
.RI "file \fBGlobalSectionSolutionConfigurationPlatforms\&.cs\fP"
.br
.ti -1c
.RI "file \fBGlobalSectionSolutionProperties\&.cs\fP"
.br
.ti -1c
.RI "file \fBHeader\&.cs\fP"
.br
.ti -1c
.RI "file \fBMain\&.cs\fP"
.br
.ti -1c
.RI "file \fBProject\&.cs\fP"
.br
.in -1c
