.TH "Source/Lib/Extensions/Extensions.DotNet/DotNetSolutions/Models/Internals Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Extensions/Extensions.DotNet/DotNetSolutions/Models/Internals Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBISolutionVisualizationDrawing\&.cs\fP"
.br
.ti -1c
.RI "file \fBISolutionVisualizationDrawingCircle\&.cs\fP"
.br
.ti -1c
.RI "file \fBISolutionVisualizationDrawingLine\&.cs\fP"
.br
.ti -1c
.RI "file \fBSolutionVisualizationConnection\&.cs\fP"
.br
.ti -1c
.RI "file \fBSolutionVisualizationDimensions\&.cs\fP"
.br
.ti -1c
.RI "file \fBSolutionVisualizationDrawingCircle\&.cs\fP"
.br
.ti -1c
.RI "file \fBSolutionVisualizationDrawingKind\&.cs\fP"
.br
.ti -1c
.RI "file \fBSolutionVisualizationDrawingLine\&.cs\fP"
.br
.ti -1c
.RI "file \fBSolutionVisualizationItemKind\&.cs\fP"
.br
.ti -1c
.RI "file \fBSolutionVisualizationModel\&.cs\fP"
.br
.in -1c
