.TH "Source/Lib/Common/Icons/Displays/Codicon Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Common/Icons/Displays/Codicon Directory Reference
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Codicon refers to (microsoft / vscode-codicons) and the source repository can be found at https://github.com/microsoft/vscode-codicons 
