.TH "Source/Lib/Ide/Host.BlazorWebAssembly/wwwroot/css/open-iconic Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Ide/Host.BlazorWebAssembly/wwwroot/css/open-iconic Directory Reference
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 

.SS "Open Iconic is the open source sibling of \fRIconic\fP\&. It is a hyper-legible collection of 223 icons with a tiny footprint---ready to use with Bootstrap and Foundation\&. \fRView the collection\fP"
.SH "What's in Open Iconic?"
.PP
.IP "\(bu" 2
223 icons designed to be legible down to 8 pixels
.IP "\(bu" 2
Super-light SVG files - 61\&.8 for the entire set
.IP "\(bu" 2
SVG sprite---the modern replacement for icon fonts
.IP "\(bu" 2
Webfont (EOT, OTF, SVG, TTF, WOFF), PNG and WebP formats
.IP "\(bu" 2
Webfont stylesheets (including versions for Bootstrap and Foundation) in CSS, LESS, SCSS and Stylus formats
.IP "\(bu" 2
PNG and WebP raster images in 8px, 16px, 24px, 32px, 48px and 64px\&.
.PP
.SH "Getting Started"
.PP
.SS "For code samples and everything else you need to get started with Open Iconic, check out our \fRIcons\fP and \fRReference\fP sections\&."
.SS "General Usage"
.SS "Using Open Iconic's SVGs"
We like SVGs and we think they're the way to display icons on the web\&. Since Open Iconic are just basic SVGs, we suggest you display them like you would any other image (don't forget the \fRalt\fP attribute)\&.

.PP
.PP
.nf
<img src="/open\-iconic/svg/icon\-name\&.svg" alt="icon name">
.fi
.PP
.SS "Using Open Iconic's SVG Sprite"
Open Iconic also comes in a SVG sprite which allows you to display all the icons in the set with a single request\&. It's like an icon font, without being a hack\&.

.PP
Adding an icon from an SVG sprite is a little different than what you're used to, but it's still a piece of cake\&. \fITip: To make your icons easily style able, we suggest adding a general class to the\fP \fR<svg>\fP \fItag and a unique class name for each different icon in the\fP \fR<use>\fP \fItag\&.\fP 
.br

.PP
.PP
.nf
<svg class="icon">
  <use xlink:href="open\-iconic\&.svg#account\-login" class="icon\-account\-login"></use>
</svg>
.fi
.PP

.PP
Sizing icons only needs basic CSS\&. All the icons are in a square format, so just set the \fR<svg>\fP tag with equal width and height dimensions\&.

.PP
.PP
.nf
\&.icon {
  width: 16px;
  height: 16px;
}
.fi
.PP

.PP
Coloring icons is even easier\&. All you need to do is set the \fRfill\fP rule on the \fR<use>\fP tag\&.

.PP
.PP
.nf
\&.icon\-account\-login {
  fill: #f00;
}
.fi
.PP

.PP
To learn more about SVG Sprites, read \fRChris Coyier's guide\fP\&.
.SS "Using Open Iconic's Icon Font\&.\&.\&."
.SS "…with Bootstrap"
You can find our Bootstrap stylesheets in \fRfont/css/open-iconic-bootstrap\&.{css, less, scss, styl}\fP

.PP
.PP
.nf
<link href="/open\-iconic/font/css/open\-iconic\-bootstrap\&.css" rel="stylesheet">
.fi
.PP

.PP
.PP
.nf
<span class="oi oi\-icon\-name" title="icon name" aria\-hidden="true"></span>
.fi
.PP
.SS "…with Foundation"
You can find our Foundation stylesheets in \fRfont/css/open-iconic-foundation\&.{css, less, scss, styl}\fP

.PP
.PP
.nf
<link href="/open\-iconic/font/css/open\-iconic\-foundation\&.css" rel="stylesheet">
.fi
.PP

.PP
.PP
.nf
<span class="fi\-icon\-name" title="icon name" aria\-hidden="true"></span>
.fi
.PP
.SS "…on its own"
You can find our default stylesheets in \fRfont/css/open-iconic\&.{css, less, scss, styl}\fP

.PP
.PP
.nf
<link href="/open\-iconic/font/css/open\-iconic\&.css" rel="stylesheet">
.fi
.PP

.PP
.PP
.nf
<span class="oi" data\-glyph="icon\-name" title="icon name" aria\-hidden="true"></span>
.fi
.PP
.SH "License"
.PP
.SS "Icons"
All code (including SVG markup) is under the \fRMIT License\fP\&.
.SS "Fonts"
All fonts are under the \fRSIL Licensed\fP\&. 
