.TH "Source/Tests/TextEditor/Basis/Groups/States Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Tests/TextEditor/Basis/Groups/States Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBTextEditorGroupState\&.ActionsTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBTextEditorGroupState\&.MainTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBTextEditorGroupState\&.ReducerTests\&.cs\fP"
.br
.in -1c
