.TH "Source/Lib/Extensions/Extensions.Website/Facts Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Extensions/Extensions.Website/Facts Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBInitialSolutionFacts\&.BlazorCrudAppWasmCsproj\&.cs\fP"
.br
.ti -1c
.RI "file \fBInitialSolutionFacts\&.BlazorCrudAppWasmProgramCs\&.cs\fP"
.br
.ti -1c
.RI "file \fBInitialSolutionFacts\&.PersonCs\&.cs\fP"
.br
.ti -1c
.RI "file \fBInitialSolutionFacts\&.PersonDisplayRazor\&.cs\fP"
.br
.ti -1c
.RI "file \fBInitialSolutionFacts\&.PersonDisplayRazorCs\&.cs\fP"
.br
.ti -1c
.RI "file \fBInitialSolutionFacts\&.Sln\&.cs\fP"
.br
.in -1c
