.TH "Source/Tests/CompilerServices/Terminal Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Tests/CompilerServices/Terminal Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBGlobalUsings\&.cs\fP"
.br
.ti -1c
.RI "file \fBUnitTest1\&.cs\fP"
.br
.in -1c
