.TH "Docs/Ide Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Docs/Ide Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBFeatures\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Luthetus\&.Ide (Not yet released)"
.PP
.IP "\(bu" 2
A free and open source IDE being written with \&.NET: C#, Blazor UI, and a Photino host\&.
.IP "\(bu" 2
Runs on Linux, Windows, and Mac
.PP

.PP
.SH "Demo:"
.PP
https://luthetus.github.io/Luthetus.Ide/
.SH "Features"
.PP
.SS "Solution Explorer:"
.IP "\(bu" 2
Tracks the file system default namespace\&.
.IP "\(bu" 2
Interpolate file system namespace when creating a templated C# file\&.
.IP "\(bu" 2
Create codebehinds for Blazor components with the 'partial', 'ComponentBase', and 'using' automatically\&.
.IP "\(bu" 2
Display unique icons for unique folders\&. Example: "wwwroot" is a globe, and "Properties" is a settings gear\&.
.IP "\(bu" 2
Context Menu contains: Copy, Cut, Rename, Paste, Delete, "New Empty File", "New Templated File", and "New Directory"\&.
.IP "\(bu" 2
For \&.NET Solutions the Context Menu also gets: "Add New C# Project", and "Add Existing C# Project"
.IP "\(bu" 2
For C# Projects the Context Menu also gets: "Add Project Reference", "Set As Startup Project", and "Remove (no files are deleted)"
.IP "\(bu" 2
Nesting of 'codebehind' like files\&. So nesting "MyComponent\&.razor\&.cs" behind "MyComponent\&.razor"\&.
.PP
.SS "Input File Dialog:"
.IP "\(bu" 2
Traverse the file system in order to select a file\&. This file must satisfy a predicate which is defined by the requester\&. So I can request for a C# Project and the user sees an input file dialog which asks the user to pick a C# Project\&.
.PP
.SS "NuGet Package Manager"
.IP "\(bu" 2
Query "azuresearch-usnc\&.nuget\&.org/"
.IP "\(bu" 2
Pick the Project one wishes to add the NuGet Package reference to\&.
.IP "\(bu" 2
Option for "Include Prerelease"
.IP "\(bu" 2
List out the results of the HTTP request\&.
.IP "\(bu" 2
Allow for picking of the version number foreach of the results individually\&.
.IP "\(bu" 2
Button to add the NuGet Package at the selected version to the chosen Project\&.
.IP "\(bu" 2
The gif for this will be the gif at the start of this file where I showcase its usage as to decrease how large this README is\&.
.PP
.SS "Settings"
.IP "\(bu" 2
Application Settings
.IP "  \(bu" 4
Font-Size
.IP "  \(bu" 4
Font-Family
.IP "  \(bu" 4
Icon-Size
.IP "  \(bu" 4
Theme
.PP

.IP "\(bu" 2
Text Editor Settings
.IP "  \(bu" 4
Font-Size
.IP "  \(bu" 4
Font-Family
.IP "  \(bu" 4
Cursor-Width
.IP "  \(bu" 4
Show Newlines
.IP "  \(bu" 4
Use Monospace Optimizations (you should not turn off monospace optimizations because the non-monospace logic is currently very unoptimized as of 2023-08-16)
.IP "  \(bu" 4
Show Whitespace
.IP "  \(bu" 4
Theme
.IP "  \(bu" 4
Keymap (Default, or Vim) 
.PP

.PP

