.TH "Source/Lib/TextEditor/CompilerServices/Syntax Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/TextEditor/CompilerServices/Syntax Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBNodes\fP"
.br
.ti -1c
.RI "directory \fBSymbols\fP"
.br
.ti -1c
.RI "directory \fBTokens\fP"
.br
.in -1c
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBFunctionHelper\&.cs\fP"
.br
.ti -1c
.RI "file \fBISyntax\&.cs\fP"
.br
.ti -1c
.RI "file \fBISyntaxNode\&.cs\fP"
.br
.ti -1c
.RI "file \fBISyntaxToken\&.cs\fP"
.br
.ti -1c
.RI "file \fBSyntaxKind\&.cs\fP"
.br
.ti -1c
.RI "file \fBSyntaxReader\&.cs\fP"
.br
.ti -1c
.RI "file \fBTokenFactory\&.cs\fP"
.br
.in -1c
