.TH "Source/Lib/Common/Panels/Models Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Common/Panels/Models Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBIPanelTab\&.cs\fP"
.br
.ti -1c
.RI "file \fBPanel\&.cs\fP"
.br
.ti -1c
.RI "file \fBPanelFacts\&.cs\fP"
.br
.ti -1c
.RI "file \fBPanelGroup\&.cs\fP"
.br
.ti -1c
.RI "file \fBPanelGroupDropzone\&.cs\fP"
.br
.in -1c
