.TH "Source/Lib/Common/Resizes/Displays Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Common/Resizes/Displays Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBResizableColumn\&.razor\&.cs\fP"
.br
.ti -1c
.RI "file \fBResizableDisplay\&.razor\&.cs\fP"
.br
.ti -1c
.RI "file \fBResizableRow\&.razor\&.cs\fP"
.br
.in -1c
