.TH "Source/Tests/TextEditor/Basis/Groups/Models Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Tests/TextEditor/Basis/Groups/Models Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBGroupApiTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBTextEditorGroupTests\&.cs\fP"
.br
.in -1c
