.TH "Source/Lib/TextEditor/CompilerServices/GenericLexer/SyntaxObjects Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/TextEditor/CompilerServices/GenericLexer/SyntaxObjects Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBGenericCommentMultiLineSyntax\&.cs\fP"
.br
.ti -1c
.RI "file \fBGenericCommentSingleLineSyntax\&.cs\fP"
.br
.ti -1c
.RI "file \fBGenericDeliminationExtendedSyntax\&.cs\fP"
.br
.ti -1c
.RI "file \fBGenericDocumentSyntax\&.cs\fP"
.br
.ti -1c
.RI "file \fBGenericFunctionSyntax\&.cs\fP"
.br
.ti -1c
.RI "file \fBGenericKeywordSyntax\&.cs\fP"
.br
.ti -1c
.RI "file \fBGenericPreprocessorDirectiveSyntax\&.cs\fP"
.br
.ti -1c
.RI "file \fBGenericStringSyntax\&.cs\fP"
.br
.in -1c
