.TH "Source/Lib/Common/Options/Displays Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Common/Options/Displays Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBInputAppFontFamily\&.razor\&.cs\fP"
.br
.ti -1c
.RI "file \fBInputAppFontSize\&.razor\&.cs\fP"
.br
.ti -1c
.RI "file \fBInputAppIconSize\&.razor\&.cs\fP"
.br
.ti -1c
.RI "file \fBInputAppResizeHandleHeight\&.razor\&.cs\fP"
.br
.ti -1c
.RI "file \fBInputAppResizeHandleWidth\&.razor\&.cs\fP"
.br
.ti -1c
.RI "file \fBInputAppTheme\&.razor\&.cs\fP"
.br
.in -1c
