.TH "Source/Tests/TextEditor/Basis/Virtualizations/Models Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Tests/TextEditor/Basis/Virtualizations/Models Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBVirtualizationBoundaryTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBVirtualizationEntryTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBVirtualizationRequestTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBVirtualizationResultTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBVirtualizationScrollPositionTests\&.cs\fP"
.br
.in -1c
