.TH "Source/Lib/TextEditor/Keymaps/Models/Vims Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/TextEditor/Keymaps/Models/Vims Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBSyntaxModifierVim\&.cs\fP"
.br
.ti -1c
.RI "file \fBSyntaxRepeatVim\&.cs\fP"
.br
.ti -1c
.RI "file \fBSyntaxTextObjectVim\&.cs\fP"
.br
.ti -1c
.RI "file \fBSyntaxVerbVim\&.cs\fP"
.br
.ti -1c
.RI "file \fBTextEditorKeymapVim\&.cs\fP"
.br
.ti -1c
.RI "file \fBTextEditorKeymapVimFacts\&.cs\fP"
.br
.ti -1c
.RI "file \fBVimGrammarKind\&.cs\fP"
.br
.ti -1c
.RI "file \fBVimGrammarToken\&.cs\fP"
.br
.ti -1c
.RI "file \fBVimMode\&.cs\fP"
.br
.ti -1c
.RI "file \fBVimMotionResult\&.cs\fP"
.br
.ti -1c
.RI "file \fBVimSentence\&.cs\fP"
.br
.in -1c
