.TH "Docs/CompilerServices Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Docs/CompilerServices Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Directories"

.in +1c
.ti -1c
.RI "directory \fBFeatures\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Luthetus\&.CompilerServices"
.PP
.SH "Demo:"
.PP
https://luthetus.github.io/Luthetus.Ide/
.SH "Introduction"
.PP
\fI\fB\fBLuthetus\&.CompilerServices\fP\fP\fP is a Text Editor component library using the \fRBlazor UI Framework\fP for \fR\&.NET\fP
.SH "Goal"
.PP
The aim of \fBLuthetus\&.CompilerServices\fP is to replicate the features of the \fRMonaco Editor\fP that powers \fRVisual Studio Code\fP using Blazor\&.

.PP
One can make use of a compiler service by referencing the Nuget Package or cloning the source code and referencing it directly\&.
.SH "Getting started"
.PP
.IP "\(bu" 2
Video format documentation: #TODO video format
.IP "\(bu" 2
First of many markdown tutorials: #TODO markdown tutorials
.PP
.SH "Installation"
.PP
You can download the latest release NuGet packages from the official \fBLuthetus\&.TextEditor\fP NuGet pages\&.

.PP
.IP "\(bu" 2
C#: https://www.nuget.org/packages/Luthetus.CompilerServices.CSharp/
.PP
.SH "Release notes / Changelog"
.PP
See the \fBCHANGELOG\&.md\fP for release history\&.
.SH "Roadmap"
.PP
See the \fBROADMAP\&.md\fP for planned future updates\&.
.SH "Features"
.PP
See the \fBFEATURES\&.md\fP for a list of features\&.
.SH "Licence"
.PP
\fRMIT\fP 
