.TH "Source/Tests/TextEditor/Adhoc Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Tests/TextEditor/Adhoc Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBAdhocTest\&.Data\&.cs\fP"
.br
.ti -1c
.RI "file \fBAdhocTest\&.Main\&.cs\fP"
.br
.ti -1c
.RI "file \fBNewKeybinds\&.cs\fP"
.br
.ti -1c
.RI "file \fBPartitionTests\&.Data\&.cs\fP"
.br
.ti -1c
.RI "file \fBPartitionTests\&.Main\&.cs\fP"
.br
.ti -1c
.RI "file \fBTypeStartFileNonLetter\&.cs\fP"
.br
.in -1c
