.TH "Source/Tests/Extensions/Extensions.DotNet.Tests/Basis/Nugets/Models Directory Reference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Tests/Extensions/Extensions.DotNet.Tests/Basis/Nugets/Models Directory Reference
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBCSharpProjectNugetPackageReferenceTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBLightWeightNugetPackageRecordTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBNugetPackageManagerProviderAzureSearchUsncTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBNugetPackageRecordTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBNugetPackageVersionRecordTests\&.cs\fP"
.br
.ti -1c
.RI "file \fBNugetResponseTests\&.cs\fP"
.br
.in -1c
