.TH "Source/Lib/TextEditor/TextEditors/Models/Category.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/TextEditor/TextEditors/Models/Category.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "record \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Category\fP (string Value)"
.br
.RI "An optional distinction between many \fBTextEditorViewModel\fP(s) which display the same \fBTextEditorModel\fP\&. 
.br
 Example: one might have a 'main' text editor\&. Perhaps this category is named "main"\&. Furthermore one might have a 'peek' window\&. Perhaps this category is named "peek"\&. This results in one being able to have two separate view models, which display the same underlying model, and distinguish between them\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
