.TH "Source/Lib/Common/Options/Models/CommonOptionsJsonDto.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Common/Options/Models/CommonOptionsJsonDto.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\&.Options\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "record \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.CommonOptionsJsonDto\fP (int? FontSizeInPixels, int? IconSizeInPixels, int? ResizeHandleWidthInPixels, int? ResizeHandleHeightInPixels, Key< \fBThemeRecord\fP >? ThemeKey, string? FontFamily)"
.br
.RI "This type needs to exist so the \fBCommonOptions\fP properties can be nullable, as in they were not already in local storage\&. Whereas throughout the app they should never be null\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
