.TH "Source/Lib/Extensions/Extensions.DotNet/CompilerServices/Models/CompilerServiceExplorerViewKind.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Extensions/Extensions.DotNet/CompilerServices/Models/CompilerServiceExplorerViewKind.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Extensions\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Extensions\&.DotNet\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Extensions\&.DotNet\&.CompilerServices\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Extensions\&.DotNet\&.CompilerServices\&.Models\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBLuthetus\&.Extensions\&.DotNet\&.CompilerServices\&.Models\&.CompilerServiceExplorerViewKind\fP { \fBLuthetus\&.Extensions\&.DotNet\&.CompilerServices\&.Models\&.Graphical\fP, \fBLuthetus\&.Extensions\&.DotNet\&.CompilerServices\&.Models\&.TreeView\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
