.TH "Source/Lib/Extensions/Extensions.DotNet/CompilerServices/States/CompilerServiceEditorState.Actions.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Extensions/Extensions.DotNet/CompilerServices/States/CompilerServiceEditorState.Actions.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Extensions\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Extensions\&.DotNet\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Extensions\&.DotNet\&.CompilerServices\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Extensions\&.DotNet\&.CompilerServices\&.States\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "partial record \fBLuthetus\&.Extensions\&.DotNet\&.CompilerServices\&.States\&.CompilerServiceEditorState\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
