.TH "Source/Lib/TextEditor/Edits/Models/CursorDisplacementKind.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/TextEditor/Edits/Models/CursorDisplacementKind.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\&.Edits\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBLuthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.CursorDisplacementKind\fP { \fBLuthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.Left\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.None\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.Right\fP }"
.br
.RI "This enum describes which direction the cursor's column index moves based on the amount of text that was inserted, deleted, or some other form of editing\&. 
.br

.br
\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
