.TH "Source/Lib/Common/Dialogs/Models/DialogViewModel.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Common/Dialogs/Models/DialogViewModel.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\&.Dialogs\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBIDialog\fP \fBLuthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.SetTitle\fP (string \fBtitle\fP)"
.br
.ti -1c
.RI "\fBIDialog\fP \fBLuthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.SetIsMinimized\fP (bool isMinimized)"
.br
.ti -1c
.RI "\fBIDialog\fP \fBLuthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.SetDialogIsMaximized\fP (bool isMaximized)"
.br
.ti -1c
.RI "\fBIDialog\fP \fBLuthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.SetIsResizable\fP (bool \fBisResizable\fP)"
.br
.ti -1c
.RI "\fBIDialog\fP \fBLuthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.SetCssClassString\fP (string cssClassString)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "record \fBLuthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.DialogViewModel\fP"
.br
.ti -1c
.RI "record string \fBLuthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.title\fP"
.br
.ti -1c
.RI "record string Type \fBLuthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.componentType\fP"
.br
.ti -1c
.RI "record string Type? Dictionary< string, object?> \fBLuthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.componentParameterMap\fP"
.br
.ti -1c
.RI "record string Type? Dictionary< string, object?>? string \fBLuthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.cssClass\fP"
.br
.ti -1c
.RI "record string Type? Dictionary< string, object?>? string bool \fBLuthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.isResizable\fP"
.br
.ti -1c
.RI "record string Type? Dictionary< string, object?>? string bool? string \fBLuthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.setFocusOnCloseElementId\fP\fR [set]\fP"
.br
.ti -1c
.RI "Key< \fBIDynamicViewModel\fP > \fBLuthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.DynamicViewModelKey\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBElementDimensions\fP \fBLuthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.DialogElementDimensions\fP = DialogHelper\&.ConstructDefaultElementDimensions()\fR [get, set]\fP"
.br
.ti -1c
.RI "Type \fBLuthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.ComponentType\fP\fR [get]\fP"
.br
.ti -1c
.RI "Dictionary< string, object?>? \fBLuthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.ComponentParameterMap\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBLuthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.Title\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBLuthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.TitleVerbose\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBLuthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.DialogFocusPointHtmlElementId\fP\fR [get]\fP"
.br
.ti -1c
.RI "string? \fBLuthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.DialogCssClass\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string? \fBLuthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.DialogCssStyle\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBLuthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.DialogIsMinimized\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBLuthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.DialogIsMaximized\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBLuthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.DialogIsResizable\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string? \fBLuthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.SetFocusOnCloseElementId\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
