.TH "Source/Lib/Common/Dimensions/Models/DimensionUnitKind.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Common/Dimensions/Models/DimensionUnitKind.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\&.Dimensions\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\&.Dimensions\&.Models\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBLuthetus\&.Common\&.RazorLib\&.Dimensions\&.Models\&.DimensionUnitKind\fP { \fBLuthetus\&.Common\&.RazorLib\&.Dimensions\&.Models\&.Pixels\fP, \fBLuthetus\&.Common\&.RazorLib\&.Dimensions\&.Models\&.ViewportWidth\fP, \fBLuthetus\&.Common\&.RazorLib\&.Dimensions\&.Models\&.ViewportHeight\fP, \fBLuthetus\&.Common\&.RazorLib\&.Dimensions\&.Models\&.Percentage\fP, \fBLuthetus\&.Common\&.RazorLib\&.Dimensions\&.Models\&.RootCharacterWidth\fP, \fBLuthetus\&.Common\&.RazorLib\&.Dimensions\&.Models\&.RootCharacterHeight\fP, \fBLuthetus\&.Common\&.RazorLib\&.Dimensions\&.Models\&.CharacterWidth\fP, \fBLuthetus\&.Common\&.RazorLib\&.Dimensions\&.Models\&.CharacterHeight\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
