.TH "Source/Lib/Extensions/Extensions.DotNet/CommandLines/Models/DotNetCliCommandFormatter.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Extensions/Extensions.DotNet/CommandLines/Models/DotNetCliCommandFormatter.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLuthetus\&.Extensions\&.DotNet\&.CommandLines\&.Models\&.DotNetCliCommandFormatter\fP"
.br
.RI "TODO: The terminal code was rewritten, I think we need to change this code to wrap arguments in quotes? I don't think CliWrap is receiving the arguments the same way as it was when just left it to CliWrap to do the wrapping\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Extensions\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Extensions\&.DotNet\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Extensions\&.DotNet\&.CommandLines\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Extensions\&.DotNet\&.CommandLines\&.Models\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
