.TH "Source/Lib/CompilerServices/DotNetSolution/Models/Project/DotNetProjectKind.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/CompilerServices/DotNetSolution/Models/Project/DotNetProjectKind.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.CompilerServices\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.CompilerServices\&.DotNetSolution\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.DotNetProjectKind\fP { \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.SolutionFolder\fP, \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.CSharpProject\fP }"
.br
.RI "DotNetProjectKind is not to be confused with IDotNetProject\&.ProjectTypeGuid 
.br

.br
 DotNetProjectKind is used by the user interface to determine quickly without type inspection how the tree view node should be rendered in the solution explorer\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
