.TH "Source/Lib/Common/Dimensions/Models/ElementPositionKind.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Common/Dimensions/Models/ElementPositionKind.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\&.Dimensions\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\&.Dimensions\&.Models\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBLuthetus\&.Common\&.RazorLib\&.Dimensions\&.Models\&.ElementPositionKind\fP { \fBLuthetus\&.Common\&.RazorLib\&.Dimensions\&.Models\&.Static\fP, \fBLuthetus\&.Common\&.RazorLib\&.Dimensions\&.Models\&.Absolute\fP, \fBLuthetus\&.Common\&.RazorLib\&.Dimensions\&.Models\&.Fixed\fP, \fBLuthetus\&.Common\&.RazorLib\&.Dimensions\&.Models\&.Inherit\fP, \fBLuthetus\&.Common\&.RazorLib\&.Dimensions\&.Models\&.Relative\fP, \fBLuthetus\&.Common\&.RazorLib\&.Dimensions\&.Models\&.Revert\fP, \fBLuthetus\&.Common\&.RazorLib\&.Dimensions\&.Models\&.Sticky\fP, \fBLuthetus\&.Common\&.RazorLib\&.Dimensions\&.Models\&.Unset\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
