.TH "Source/Lib/Ide/Ide.RazorLib/Shareds/Models/FooterJustifyEndComponent.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Ide/Ide.RazorLib/Shareds/Models/FooterJustifyEndComponent.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Ide\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Ide\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Ide\&.RazorLib\&.Shareds\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Ide\&.RazorLib\&.Shareds\&.Models\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "record \fBLuthetus\&.Ide\&.RazorLib\&.Shareds\&.Models\&.FooterJustifyEndComponent\fP (Key< FooterJustifyEndComponent > Key, Type ComponentType, Dictionary< string, object?>? ComponentParameterMap)"
.br
.RI "A RenderFragment would be more optimized than rendering a DynamicComponent\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
