.TH "Source/Lib/TextEditor/CompilerServices/Syntax/Nodes/FunctionDefinitionNode.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/TextEditor/CompilerServices/Syntax/Nodes/FunctionDefinitionNode.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.FunctionDefinitionNode\fP"
.br
.RI "TODO: Track the open and close braces for the function body\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
