.TH "Source/Lib/Extensions/Extensions.Git/Models/GitDirtyReason.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Extensions/Extensions.Git/Models/GitDirtyReason.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Extensions\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Extensions\&.Git\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Extensions\&.Git\&.Models\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBLuthetus\&.Extensions\&.Git\&.Models\&.GitDirtyReason\fP { \fBLuthetus\&.Extensions\&.Git\&.Models\&.None\fP, \fBLuthetus\&.Extensions\&.Git\&.Models\&.Untracked\fP, \fBLuthetus\&.Extensions\&.Git\&.Models\&.Added\fP, \fBLuthetus\&.Extensions\&.Git\&.Models\&.Modified\fP, \fBLuthetus\&.Extensions\&.Git\&.Models\&.Deleted\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
