.TH "Source/Lib/Extensions/Extensions.Git/States/GitState.Main.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Extensions/Extensions.Git/States/GitState.Main.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Extensions\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Extensions\&.Git\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Extensions\&.Git\&.States\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "partial record \fBLuthetus\&.Extensions\&.Git\&.States\&.GitState\fP (\fBGitRepo\fP? Repo, ImmutableList< \fBGitFile\fP > UntrackedFileList, ImmutableList< \fBGitFile\fP > StagedFileList, ImmutableList< \fBGitFile\fP > UnstagedFileList, ImmutableList< \fBGitFile\fP > SelectedFileList, ImmutableList< \fBGitTask\fP > ActiveTasks, string? Origin, string? Branch, string? Upstream, ImmutableList< string > BranchList, int? BehindByCommitCount, int? AheadByCommitCount)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
