.TH "Source/Tests/BUnit/Luthetus.BUnit.Tests/TextEditors/MutableVirtualizationResult/Ideas.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Tests/BUnit/Luthetus.BUnit.Tests/TextEditors/MutableVirtualizationResult/Ideas.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLuthetus\&.BUnit\&.Tests\&.TextEditors\&.MutableVirtualizationResult\&.Ideas\fP"
.br
.RI "TODO: Delete the file: "Ideas\&.cs"\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.BUnit\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.BUnit\&.Tests\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.BUnit\&.Tests\&.TextEditors\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.BUnit\&.Tests\&.TextEditors\&.MutableVirtualizationResult\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
