.TH "Source/Lib/Ide/Ide.RazorLib/AppDatas/Models/IdeAppData.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Ide/Ide.RazorLib/AppDatas/Models/IdeAppData.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLuthetus\&.Ide\&.RazorLib\&.AppDatas\&.Models\&.IdeAppData\fP"
.br
.RI "TODO: Store the panel tab placement here (i\&.e\&.: is solution explorer on the left panel group or the right panel group)\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Ide\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Ide\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Ide\&.RazorLib\&.AppDatas\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Ide\&.RazorLib\&.AppDatas\&.Models\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
