.TH "Source/Lib/Ide/Ide.RazorLib/Shareds/States/IdeHeaderState.Main.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Ide/Ide.RazorLib/Shareds/States/IdeHeaderState.Main.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Ide\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Ide\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Ide\&.RazorLib\&.Shareds\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Ide\&.RazorLib\&.Shareds\&.States\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "partial record \fBLuthetus\&.Ide\&.RazorLib\&.Shareds\&.States\&.IdeHeaderState\fP (\fBMenuRecord\fP MenuFile, \fBMenuRecord\fP MenuTools, \fBMenuRecord\fP MenuView, \fBMenuRecord\fP MenuRun)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
