.TH "Source/Lib/TextEditor/CompilerServices/Interfaces/IEvaluator.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/TextEditor/CompilerServices/Interfaces/IEvaluator.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IEvaluator\fP"
.br
.RI "The ILuthCompilerService is to only perform static analysis of source code\&. 
.br

.br
 One should never execute the source code which is being analyzed\&. 
.br

.br
 However, for testing purposes it can be useful to see if one's logic for parsing expressions evaluates properly\&. And so, for testing only, the \fBIEvaluator\fP exists\&. 
.br

.br
 Again, the ILuthCompilerService should NEVER execute source code which it is analyzing\&. Only perform static analysis of source code\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
