.TH "Source/Lib/Ide/Ide.RazorLib/ComponentRenderers/Models/IInputFileRendererType.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Ide/Ide.RazorLib/ComponentRenderers/Models/IInputFileRendererType.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBLuthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.IInputFileRendererType\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Ide\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Ide\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Ide\&.RazorLib\&.ComponentRenderers\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
