.TH "Source/Lib/CompilerServices/CSharp/RuntimeAssemblies/IRuntimeAssembliesLoader.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/CompilerServices/CSharp/RuntimeAssemblies/IRuntimeAssembliesLoader.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBLuthetus\&.CompilerServices\&.CSharp\&.RuntimeAssemblies\&.IRuntimeAssembliesLoader\fP"
.br
.RI "https://learn.microsoft.com/en-us/dotnet/standard/assembly/inspect-contents-using-metadataloadcontext br/>
.br
 Purpose:
.br

.br
 Abstract System\&.Reflection\&.MetadataLoadContext usage to a single method invocation\&.
.br

.br
 "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.CompilerServices\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.CompilerServices\&.CSharp\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.CompilerServices\&.CSharp\&.RuntimeAssemblies\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
