.TH "Source/Lib/CompilerServices/Json/Decoration/JsonDecorationKind.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/CompilerServices/Json/Decoration/JsonDecorationKind.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.CompilerServices\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.CompilerServices\&.Json\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.CompilerServices\&.Json\&.Decoration\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBLuthetus\&.CompilerServices\&.Json\&.Decoration\&.JsonDecorationKind\fP { \fBLuthetus\&.CompilerServices\&.Json\&.Decoration\&.None\fP, \fBLuthetus\&.CompilerServices\&.Json\&.Decoration\&.PropertyKey\fP, \fBLuthetus\&.CompilerServices\&.Json\&.Decoration\&.String\fP, \fBLuthetus\&.CompilerServices\&.Json\&.Decoration\&.Number\fP, \fBLuthetus\&.CompilerServices\&.Json\&.Decoration\&.Integer\fP, \fBLuthetus\&.CompilerServices\&.Json\&.Decoration\&.Keyword\fP, \fBLuthetus\&.CompilerServices\&.Json\&.Decoration\&.LineComment\fP, \fBLuthetus\&.CompilerServices\&.Json\&.Decoration\&.BlockComment\fP, \fBLuthetus\&.CompilerServices\&.Json\&.Decoration\&.Document\fP, \fBLuthetus\&.CompilerServices\&.Json\&.Decoration\&.Error\fP, \fBLuthetus\&.CompilerServices\&.Json\&.Decoration\&.Null\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
