.TH "Source/Lib/Common/Keyboards/Models/KeyboardKeyFacts.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Common/Keyboards/Models/KeyboardKeyFacts.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLuthetus\&.Common\&.RazorLib\&.Keyboards\&.Models\&.KeyboardKeyFacts\fP"
.br
.ti -1c
.RI "class \fBLuthetus\&.Common\&.RazorLib\&.Keyboards\&.Models\&.KeyboardKeyFacts\&.MetaKeys\fP"
.br
.ti -1c
.RI "class \fBLuthetus\&.Common\&.RazorLib\&.Keyboards\&.Models\&.KeyboardKeyFacts\&.WhitespaceCharacters\fP"
.br
.ti -1c
.RI "class \fBLuthetus\&.Common\&.RazorLib\&.Keyboards\&.Models\&.KeyboardKeyFacts\&.WhitespaceCodes\fP"
.br
.ti -1c
.RI "class \fBLuthetus\&.Common\&.RazorLib\&.Keyboards\&.Models\&.KeyboardKeyFacts\&.PunctuationCharacters\fP"
.br
.RI "Added characters that were found in https://www.scintilla.org/ScintillaDoc.html source code, CharacterType\&.h:79\&. "
.ti -1c
.RI "class \fBLuthetus\&.Common\&.RazorLib\&.Keyboards\&.Models\&.KeyboardKeyFacts\&.MovementKeys\fP"
.br
.ti -1c
.RI "class \fBLuthetus\&.Common\&.RazorLib\&.Keyboards\&.Models\&.KeyboardKeyFacts\&.MovementCodes\fP"
.br
.ti -1c
.RI "class \fBLuthetus\&.Common\&.RazorLib\&.Keyboards\&.Models\&.KeyboardKeyFacts\&.AlternateMovementKeys\fP"
.br
.ti -1c
.RI "class \fBLuthetus\&.Common\&.RazorLib\&.Keyboards\&.Models\&.KeyboardKeyFacts\&.AlternateMovementCodes\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\&.Keyboards\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\&.Keyboards\&.Models\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
