.TH "Source/Lib/TextEditor/CompilerServices/Implementations/LexerUtils.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/TextEditor/CompilerServices/Implementations/LexerUtils.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.LexerUtils\fP"
.br
.RI "TODO: Rewrite this class such that the lexed token is returned,\&.\&.\&. \&.\&.\&.rather than added to the list of 'syntaxTokens'\&. | It is awkward when one wants to use the 'Lex\&.\&.\&.(\&.\&.\&.)' method, yet afterwards needs to replace the last entry of 'syntaxTokens' with something of a different class, or syntax kind\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
