.TH "Source/Lib/TextEditor/Rows/Models/LineInformation.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/TextEditor/Rows/Models/LineInformation.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\&.Rows\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\&.Rows\&.Models\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "record \fBLuthetus\&.TextEditor\&.RazorLib\&.Rows\&.Models\&.LineInformation\fP (int Index, int StartPositionIndexInclusive, int EndPositionIndexExclusive, \fBLineEnd\fP LowerLineEnd, \fBLineEnd\fP UpperLineEnd)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
