.TH "Luthetus.Ide.RazorLib.InputFiles.Models.InputFilePattern" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.InputFiles.Models.InputFilePattern
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInputFilePattern\fP (string patternName, Func< \fBIAbsolutePath\fP, bool > matchesPatternFunc)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBPatternName\fP\fR [get]\fP"
.br
.ti -1c
.RI "Func< \fBIAbsolutePath\fP, bool > \fBMatchesPatternFunc\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBInputFilePattern\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Ide\&.RazorLib\&.InputFiles\&.Models\&.InputFilePattern\&.InputFilePattern (string patternName, Func< \fBIAbsolutePath\fP, bool > matchesPatternFunc)"

.PP
Definition at line \fB7\fP of file \fBInputFilePattern\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Func<\fBIAbsolutePath\fP, bool> Luthetus\&.Ide\&.RazorLib\&.InputFiles\&.Models\&.InputFilePattern\&.MatchesPatternFunc\fR [get]\fP"

.PP
Definition at line \fB14\fP of file \fBInputFilePattern\&.cs\fP\&.
.SS "string Luthetus\&.Ide\&.RazorLib\&.InputFiles\&.Models\&.InputFilePattern\&.PatternName\fR [get]\fP"

.PP
Definition at line \fB13\fP of file \fBInputFilePattern\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
