.TH "Luthetus.Common.RazorLib.CustomEvents.Models" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.CustomEvents.Models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEventHandlers\fP"
.br
.RI ""onkeydownwithpreventscroll" is used as a custom Blazor event\&.
.br

.br
 The purpose is to conditionally preventDefault on a @onkeydown event\&.
.br

.br
 In specific this will preventDefault on:
.br
 -ContextMenu
.br
 -ArrowLeft
.br
 -ArrowDown
.br
 -ArrowUp
.br
 -ArrowRight
.br
 -Home
.br
 -End
.br
 -Space
.br
 -Enter
.br
 "
.ti -1c
.RI "class \fBEventUtil\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
