.TH "Luthetus.CompilerServices.Python.Facts.PythonLanguageFacts.Preprocessor" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.Python.Facts.PythonLanguageFacts.Preprocessor
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDirectives\fP"
.br
.ti -1c
.RI "class \fBVariables\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBPythonLanguageFacts\&.PreprocessorDirectives\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
