.TH "Luthetus.Ide.Tests.Basis.Terminals.States.TerminalWasModifiedStateMainTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.Tests.Basis.Terminals.States.TerminalWasModifiedStateMainTests \- TerminalWasModifiedState  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "TerminalWasModifiedState(ImmutableDictionary<Key<Terminal>, Key<StateRecord>>, string) 
.br
----
.br
 TerminalWasModifiedState\&.TerminalWasModifiedMap TerminalWasModifiedState\&.EmptyTextHack "
.in -1c
.SH "Detailed Description"
.PP 
TerminalWasModifiedState 
.PP
Definition at line \fB6\fP of file \fBTerminalWasModifiedStateMainTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.Terminals\&.States\&.TerminalWasModifiedStateMainTests\&.Constructor ()"

.PP
TerminalWasModifiedState(ImmutableDictionary<Key<Terminal>, Key<StateRecord>>, string) 
.br
----
.br
 TerminalWasModifiedState\&.TerminalWasModifiedMap TerminalWasModifiedState\&.EmptyTextHack 
.PP
Definition at line \fB15\fP of file \fBTerminalWasModifiedStateMainTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
