.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.ReturnStatementNodeTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.ReturnStatementNodeTests \- \fBReturnStatementNode\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "ReturnStatementNode(KeywordToken, IExpressionNode) 
.br
----
.br
 \fBReturnStatementNode\&.KeywordToken\fP \fBReturnStatementNode\&.ExpressionNode\fP ReturnStatementNode\&.ChildList \fBReturnStatementNode\&.IsFabricated\fP \fBReturnStatementNode\&.SyntaxKind\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBReturnStatementNode\fP 
.PP
Definition at line \fB11\fP of file \fBReturnStatementNodeTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.Syntax\&.SyntaxNodes\&.ReturnStatementNodeTests\&.Constructor ()"

.PP
ReturnStatementNode(KeywordToken, IExpressionNode) 
.br
----
.br
 \fBReturnStatementNode\&.KeywordToken\fP \fBReturnStatementNode\&.ExpressionNode\fP ReturnStatementNode\&.ChildList \fBReturnStatementNode\&.IsFabricated\fP \fBReturnStatementNode\&.SyntaxKind\fP 
.PP
Definition at line \fB23\fP of file \fBReturnStatementNodeTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
