.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxReaderTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxReaderTests \- SyntaxReader  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBGetTextRecursively\fP ()"
.br
.RI "SyntaxReader\&.ConstructTextSpanRecursively(ISyntaxNode) "
.in -1c
.SH "Detailed Description"
.PP 
SyntaxReader 
.PP
Definition at line \fB8\fP of file \fBSyntaxReaderTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.Syntax\&.SyntaxReaderTests\&.GetTextRecursively ()"

.PP
SyntaxReader\&.ConstructTextSpanRecursively(ISyntaxNode) 
.PP
Definition at line \fB14\fP of file \fBSyntaxReaderTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
