.TH "Luthetus.CompilerServices.C.Facts.CLanguageFacts.Punctuation" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.C.Facts.CLanguageFacts.Punctuation
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const char \fBUNDERSCORE_SPECIAL_CASE\fP = '_'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBCLanguageFacts\&.Punctuation\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const char Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Punctuation\&.UNDERSCORE_SPECIAL_CASE = '_'\fR [static]\fP"

.PP
Definition at line \fB7\fP of file \fBCLanguageFacts\&.Punctuation\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
