.TH "Luthetus.TextEditor.Tests.Basis.TextEditors.Models.Internals.TooltipViewModelTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.TextEditors.Models.Internals.TooltipViewModelTests \- \fBTooltipViewModel\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "TooltipViewModel(Type, Dictionary<string, object?>?, RelativeCoordinates, string?, Func<Task>) 
.br
----
.br
 TooltipViewModel\&.RendererType TooltipViewModel\&.ParameterMap TooltipViewModel\&.RelativeCoordinates TooltipViewModel\&.CssClassString TooltipViewModel\&.OnMouseOver "
.in -1c
.SH "Detailed Description"
.PP 
\fBTooltipViewModel\fP 
.PP
Definition at line \fB10\fP of file \fBTooltipViewModelTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.Internals\&.TooltipViewModelTests\&.Constructor ()"

.PP
TooltipViewModel(Type, Dictionary<string, object?>?, RelativeCoordinates, string?, Func<Task>) 
.br
----
.br
 TooltipViewModel\&.RendererType TooltipViewModel\&.ParameterMap TooltipViewModel\&.RelativeCoordinates TooltipViewModel\&.CssClassString TooltipViewModel\&.OnMouseOver 
.PP
Definition at line \fB22\fP of file \fBTooltipViewModelTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
