.TH "Luthetus.Ide.RazorLib.Terminals.Models" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.Terminals.Models
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBInternals\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIdea\fP"
.br
.ti -1c
.RI "interface \fBITerminal\fP"
.br
.RI "input -> CliWrap -> output "
.ti -1c
.RI "interface \fBITerminalInput\fP"
.br
.RI "Input Data\&. "
.ti -1c
.RI "interface \fBITerminalInteractive\fP"
.br
.RI "State (i\&.e\&.: working directory)\&. "
.ti -1c
.RI "interface \fBITerminalOutput\fP"
.br
.RI "Output Data\&. "
.ti -1c
.RI "interface \fBITerminalOutputFormatted\fP"
.br
.ti -1c
.RI "interface \fBITerminalOutputFormatter\fP"
.br
.RI "This is a sort of the built in System\&.Globalization\&.CultureInfo or System\&.IFormatProvider but specifically for the \fBITerminal\fP\&. "
.ti -1c
.RI "class \fBTerminal\fP"
.br
.RI "This implementation of \fBITerminal\fP is a "blank slate"\&. "
.ti -1c
.RI "class \fBTerminalCommandParsed\fP"
.br
.ti -1c
.RI "class \fBTerminalCommandRequest\fP"
.br
.RI "'workingDirectory' is intended to be an absolute path in string form\&. "
.ti -1c
.RI "class \fBTerminalCompilerService\fP"
.br
.ti -1c
.RI "class \fBTerminalDecorationMapper\fP"
.br
.ti -1c
.RI "class \fBTerminalFacts\fP"
.br
.ti -1c
.RI "class \fBTerminalInputStringBuilder\fP"
.br
.ti -1c
.RI "class \fBTerminalIntegrated\fP"
.br
.ti -1c
.RI "class \fBTerminalInteractive\fP"
.br
.ti -1c
.RI "class \fBTerminalOutput\fP"
.br
.ti -1c
.RI "class \fBTerminalOutputFacts\fP"
.br
.ti -1c
.RI "class \fBTerminalOutputFormattedTextEditor\fP"
.br
.ti -1c
.RI "class \fBTerminalOutputFormatterAll\fP"
.br
.ti -1c
.RI "class \fBTerminalOutputFormatterExpand\fP"
.br
.ti -1c
.RI "class \fBTerminalPresentationFacts\fP"
.br
.ti -1c
.RI "class \fBTerminalResource\fP"
.br
.ti -1c
.RI "class \fBTerminalWebsite\fP"
.br
.RI "This implementation of \fBITerminal\fP is for the website demo\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTerminalDecorationKind\fP { \fBNone\fP, \fBComment\fP, \fBKeyword\fP, \fBStringLiteral\fP, \fBTargetFilePath\fP, \fBError\fP, \fBWarning\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalDecorationKind\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BINone \fP
.TP
\f(BIComment \fP
.TP
\f(BIKeyword \fP
.TP
\f(BIStringLiteral \fP
.TP
\f(BITargetFilePath \fP
.TP
\f(BIError \fP
.TP
\f(BIWarning \fP
.PP
Definition at line \fB3\fP of file \fBTerminalDecorationKind\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
