.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.TokenWalkerTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.TokenWalkerTests \- \fBTokenWalker\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "TokenWalker(ImmutableArray<ISyntaxToken>, LuthDiagnosticBag) 
.br
----
.br
 \fBTokenWalker\&.TokenList\fP \fBTokenWalker\&.Current\fP \fBTokenWalker\&.Next\fP \fBTokenWalker\&.Previous\fP \fBTokenWalker\&.IsEof\fP TokenWalker\&.EOF "
.ti -1c
.RI "void \fBPeek\fP ()"
.br
.RI "\fBTokenWalker\&.Peek(int)\fP "
.ti -1c
.RI "void \fBConsume\fP ()"
.br
.RI "\fBTokenWalker\&.Consume()\fP "
.ti -1c
.RI "void \fBBacktrack\fP ()"
.br
.RI "\fBTokenWalker\&.Backtrack()\fP "
.ti -1c
.RI "void \fBMatch\fP ()"
.br
.RI "\fBTokenWalker\&.Match(SyntaxKind)\fP "
.ti -1c
.RI "void \fBMatchRange\fP ()"
.br
.RI "TokenWalker\&.MatchRange(IEnumerable<SyntaxKind>, SyntaxKind) "
.in -1c
.SH "Detailed Description"
.PP 
\fBTokenWalker\fP 
.PP
Definition at line \fB10\fP of file \fBTokenWalkerTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.TokenWalkerTests\&.Backtrack ()"

.PP
\fBTokenWalker\&.Backtrack()\fP 
.PP
Definition at line \fB50\fP of file \fBTokenWalkerTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.TokenWalkerTests\&.Constructor ()"

.PP
TokenWalker(ImmutableArray<ISyntaxToken>, LuthDiagnosticBag) 
.br
----
.br
 \fBTokenWalker\&.TokenList\fP \fBTokenWalker\&.Current\fP \fBTokenWalker\&.Next\fP \fBTokenWalker\&.Previous\fP \fBTokenWalker\&.IsEof\fP TokenWalker\&.EOF 
.PP
Definition at line \fB23\fP of file \fBTokenWalkerTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.TokenWalkerTests\&.Consume ()"

.PP
\fBTokenWalker\&.Consume()\fP 
.PP
Definition at line \fB41\fP of file \fBTokenWalkerTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.TokenWalkerTests\&.Match ()"

.PP
\fBTokenWalker\&.Match(SyntaxKind)\fP 
.PP
Definition at line \fB59\fP of file \fBTokenWalkerTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.TokenWalkerTests\&.MatchRange ()"

.PP
TokenWalker\&.MatchRange(IEnumerable<SyntaxKind>, SyntaxKind) 
.PP
Definition at line \fB68\fP of file \fBTokenWalkerTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.TokenWalkerTests\&.Peek ()"

.PP
\fBTokenWalker\&.Peek(int)\fP 
.PP
Definition at line \fB32\fP of file \fBTokenWalkerTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
