.TH "Luthetus.Common.RazorLib.Options.States" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Options.States
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "partial record \fBAppOptionsState\fP (\fBCommonOptions\fP \fBOptions\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "partial record Luthetus\&.Common\&.RazorLib\&.Options\&.States\&.AppOptionsState (\fBCommonOptions\fP Options)"

.PP
Definition at line \fB8\fP of file \fBAppOptionsState\&.Main\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
