.TH "Luthetus.Extensions.Git.Models.GitTreeViewKeyboardEventHandler" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.Git.Models.GitTreeViewKeyboardEventHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewKeyboardEventHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGitTreeViewKeyboardEventHandler\fP (\fBITreeViewService\fP treeViewService, \fBIBackgroundTaskService\fP backgroundTaskService, IState< \fBGitState\fP > gitStateWrap, IDispatcher dispatcher)"
.br
.in -1c

Public Member Functions inherited from \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewKeyboardEventHandler\fP
.in +1c
.ti -1c
.RI "\fBTreeViewKeyboardEventHandler\fP (\fBITreeViewService\fP treeViewService, \fBIBackgroundTaskService\fP backgroundTaskService)"
.br
.ti -1c
.RI "virtual Task \fBOnKeyDownAsync\fP (\fBTreeViewCommandArgs\fP commandArgs)"
.br
.RI "Invoked, and awaited, as part of the async UI event handler for 'onkeydownwithpreventscroll' events\&.
.br

.br
\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnKeyDown\fP (\fBTreeViewCommandArgs\fP commandArgs)"
.br
.RI "Invoked, and awaited, as part of the synchronous UI event handler for 'onkeydownwithpreventscroll' events\&.
.br

.br
\&. "
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewKeyboardEventHandler\fP
.in +1c
.ti -1c
.RI "readonly \fBITreeViewService\fP \fBTreeViewService\fP"
.br
.ti -1c
.RI "readonly \fBIBackgroundTaskService\fP \fBBackgroundTaskService\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBGitTreeViewKeyboardEventHandler\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Extensions\&.Git\&.Models\&.GitTreeViewKeyboardEventHandler\&.GitTreeViewKeyboardEventHandler (\fBITreeViewService\fP treeViewService, \fBIBackgroundTaskService\fP backgroundTaskService, IState< \fBGitState\fP > gitStateWrap, IDispatcher dispatcher)"

.PP
Definition at line \fB16\fP of file \fBGitTreeViewKeyboardEventHandler\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Luthetus\&.Extensions\&.Git\&.Models\&.GitTreeViewKeyboardEventHandler\&.OnKeyDown (\fBTreeViewCommandArgs\fP commandArgs)\fR [protected]\fP, \fR [virtual]\fP"

.PP
Invoked, and awaited, as part of the synchronous UI event handler for 'onkeydownwithpreventscroll' events\&.
.br

.br
\&. This method is invoked by the async version: 'OnKeyDownAsync(TreeViewCommandArgs)'\&.
.br

.br

.PP
Any overrides of this method are intended to have 'base\&.MethodBeingOverridden()' prior to their code\&.
.br

.br
 
.PP
Reimplemented from \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewKeyboardEventHandler\fP\&.
.PP
Definition at line \fB27\fP of file \fBGitTreeViewKeyboardEventHandler\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
