.TH "Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.Decoration" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.Decoration
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGenericDecorationMapper\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBGenericDecorationKind\fP { \fBNone\fP, \fBKeyword\fP, \fBKeywordControl\fP, \fBCommentSingleLine\fP, \fBCommentMultiLine\fP, \fBError\fP, \fBEscapeCharacter\fP, \fBStringLiteral\fP, \fBVariable\fP, \fBFunction\fP, \fBPreprocessorDirective\fP, \fBDeliminationExtended\fP, \fBType\fP, \fBField\fP, \fBProperty\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.Decoration\&.GenericDecorationKind\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BINone \fP
.TP
\f(BIKeyword \fP
.TP
\f(BIKeywordControl \fP
.TP
\f(BICommentSingleLine \fP
.TP
\f(BICommentMultiLine \fP
.TP
\f(BIError \fP
.TP
\f(BIEscapeCharacter \fP
.TP
\f(BIStringLiteral \fP
.TP
\f(BIVariable \fP
.TP
\f(BIFunction \fP
.TP
\f(BIPreprocessorDirective \fP
.TP
\f(BIDeliminationExtended \fP
.TP
\f(BIType \fP
.TP
\f(BIField \fP
.TP
\f(BIProperty \fP
.PP
Definition at line \fB3\fP of file \fBGenericDecorationKind\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
