.TH "Luthetus.TextEditor.RazorLib.Diffs.Models.ITextEditorDiffApi" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Diffs.Models.ITextEditorDiffApi
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.TextEditorDiffApi\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRegister\fP (Key< \fBTextEditorDiffModel\fP > diffModelKey, Key< \fBTextEditorViewModel\fP > inViewModelKey, Key< \fBTextEditorViewModel\fP > outViewModelKey)"
.br
.ti -1c
.RI "void \fBDispose\fP (Key< \fBTextEditorDiffModel\fP > diffModelKey)"
.br
.ti -1c
.RI "Func< \fBITextEditorEditContext\fP, Task > \fBCalculateFactory\fP (Key< \fBTextEditorDiffModel\fP > diffModelKey, CancellationToken cancellationToken)"
.br
.ti -1c
.RI "\fBTextEditorDiffModel\fP? \fBGetOrDefault\fP (Key< \fBTextEditorDiffModel\fP > diffModelKey)"
.br
.ti -1c
.RI "ImmutableList< \fBTextEditorDiffModel\fP > \fBGetDiffModels\fP ()"
.br
.RI "One should store the result of invoking this method in a variable, then reference that variable\&. If one continually invokes this, there is no guarantee that the data had not changed since the previous invocation\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBITextEditorDiffApi\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "Func< \fBITextEditorEditContext\fP, Task > Luthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.ITextEditorDiffApi\&.CalculateFactory (Key< \fBTextEditorDiffModel\fP > diffModelKey, CancellationToken cancellationToken)"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.TextEditorDiffApi\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.ITextEditorDiffApi\&.Dispose (Key< \fBTextEditorDiffModel\fP > diffModelKey)"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.TextEditorDiffApi\fP\&.
.SS "ImmutableList< \fBTextEditorDiffModel\fP > Luthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.ITextEditorDiffApi\&.GetDiffModels ()"

.PP
One should store the result of invoking this method in a variable, then reference that variable\&. If one continually invokes this, there is no guarantee that the data had not changed since the previous invocation\&. 
.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.TextEditorDiffApi\fP\&.
.SS "\fBTextEditorDiffModel\fP? Luthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.ITextEditorDiffApi\&.GetOrDefault (Key< \fBTextEditorDiffModel\fP > diffModelKey)"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.TextEditorDiffApi\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.ITextEditorDiffApi\&.Register (Key< \fBTextEditorDiffModel\fP > diffModelKey, Key< \fBTextEditorViewModel\fP > inViewModelKey, Key< \fBTextEditorViewModel\fP > outViewModelKey)"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.TextEditorDiffApi\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
