.TH "Luthetus.Extensions.DotNet.ComponentRenderers.Models.DotNetComponentRenderers" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.ComponentRenderers.Models.DotNetComponentRenderers
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Extensions\&.DotNet\&.ComponentRenderers\&.Models\&.IDotNetComponentRenderers\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDotNetComponentRenderers\fP (Type nuGetPackageManagerRendererType, Type removeCSharpProjectFromSolutionRendererType, \fBCompilerServicesTreeViews\fP compilerServicesTreeViews)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Type \fBNuGetPackageManagerRendererType\fP\fR [get]\fP"
.br
.ti -1c
.RI "Type \fBRemoveCSharpProjectFromSolutionRendererType\fP\fR [get]\fP"
.br
.ti -1c
.RI "CompilerServicesTreeViews \fBCompilerServicesTreeViews\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBDotNetComponentRenderers\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Extensions\&.DotNet\&.ComponentRenderers\&.Models\&.DotNetComponentRenderers\&.DotNetComponentRenderers (Type nuGetPackageManagerRendererType, Type removeCSharpProjectFromSolutionRendererType, \fBCompilerServicesTreeViews\fP compilerServicesTreeViews)"

.PP
Definition at line \fB5\fP of file \fBDotNetComponentRenderers\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "CompilerServicesTreeViews Luthetus\&.Extensions\&.DotNet\&.ComponentRenderers\&.Models\&.DotNetComponentRenderers\&.CompilerServicesTreeViews\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Extensions\&.DotNet\&.ComponentRenderers\&.Models\&.IDotNetComponentRenderers\fP\&.
.PP
Definition at line \fB17\fP of file \fBDotNetComponentRenderers\&.cs\fP\&.
.SS "Type Luthetus\&.Extensions\&.DotNet\&.ComponentRenderers\&.Models\&.DotNetComponentRenderers\&.NuGetPackageManagerRendererType\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Extensions\&.DotNet\&.ComponentRenderers\&.Models\&.IDotNetComponentRenderers\fP\&.
.PP
Definition at line \fB15\fP of file \fBDotNetComponentRenderers\&.cs\fP\&.
.SS "Type Luthetus\&.Extensions\&.DotNet\&.ComponentRenderers\&.Models\&.DotNetComponentRenderers\&.RemoveCSharpProjectFromSolutionRendererType\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Extensions\&.DotNet\&.ComponentRenderers\&.Models\&.IDotNetComponentRenderers\fP\&.
.PP
Definition at line \fB16\fP of file \fBDotNetComponentRenderers\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
