.TH "Luthetus.Extensions.Git.Displays.GitInteractiveIconDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.Git.Displays.GitInteractiveIconDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits FluxorComponent\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBCssClassString\fP = string\&.Empty\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBCssStyleString\fP = string\&.Empty\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB16\fP of file \fBGitInteractiveIconDisplay\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Luthetus\&.Extensions\&.Git\&.Displays\&.GitInteractiveIconDisplay\&.CssClassString = string\&.Empty\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB28\fP of file \fBGitInteractiveIconDisplay\&.razor\&.cs\fP\&.
.SS "string Luthetus\&.Extensions\&.Git\&.Displays\&.GitInteractiveIconDisplay\&.CssStyleString = string\&.Empty\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB30\fP of file \fBGitInteractiveIconDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
