.TH "Luthetus.Common.Tests.Basis.Options.States.AppOptionsStateMainTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Options.States.AppOptionsStateMainTests \- \fBAppOptionsState\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "\fBAppOptionsState()\fP "
.ti -1c
.RI "void \fBDefaultCommonOptions\fP ()"
.br
.RI "AppOptionsState\&.DefaultCommonOptions "
.in -1c
.SH "Detailed Description"
.PP 
\fBAppOptionsState\fP 
.PP
Definition at line \fB9\fP of file \fBAppOptionsStateTests\&.Main\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Options\&.States\&.AppOptionsStateMainTests\&.Constructor ()"

.PP
\fBAppOptionsState()\fP 
.PP
Definition at line \fB15\fP of file \fBAppOptionsStateTests\&.Main\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Options\&.States\&.AppOptionsStateMainTests\&.DefaultCommonOptions ()"

.PP
AppOptionsState\&.DefaultCommonOptions 
.PP
Definition at line \fB25\fP of file \fBAppOptionsStateTests\&.Main\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
