.TH "Luthetus.CompilerServices.DotNetSolution.Facts.LexSolutionFacts" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.DotNetSolution.Facts.LexSolutionFacts
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGlobal\fP"
.br
.ti -1c
.RI "class \fBGlobalSection\fP"
.br
.ti -1c
.RI "class \fBGlobalSectionExtensibilityGlobals\fP"
.br
.ti -1c
.RI "class \fBGlobalSectionNestedProjects\fP"
.br
.ti -1c
.RI "class \fBGlobalSectionProjectConfigurationPlatforms\fP"
.br
.ti -1c
.RI "class \fBGlobalSectionSolutionConfigurationPlatforms\fP"
.br
.ti -1c
.RI "class \fBGlobalSectionSolutionProperties\fP"
.br
.ti -1c
.RI "class \fBHeader\fP"
.br
.ti -1c
.RI "class \fBMain\fP"
.br
.ti -1c
.RI "class \fBProject\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBGlobal\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
