.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.ConstraintNodeTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.ConstraintNodeTests \- \fBConstraintNode\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "ConstraintNode(ImmutableArray<ISyntaxToken>) 
.br
----
.br
 \fBConstraintNode\&.InnerTokens\fP ConstraintNode\&.ChildList \fBConstraintNode\&.IsFabricated\fP \fBConstraintNode\&.SyntaxKind\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBConstraintNode\fP 
.PP
Definition at line \fB12\fP of file \fBConstraintNodeTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.Syntax\&.SyntaxNodes\&.ConstraintNodeTests\&.Constructor ()"

.PP
ConstraintNode(ImmutableArray<ISyntaxToken>) 
.br
----
.br
 \fBConstraintNode\&.InnerTokens\fP ConstraintNode\&.ChildList \fBConstraintNode\&.IsFabricated\fP \fBConstraintNode\&.SyntaxKind\fP 
.PP
Definition at line \fB23\fP of file \fBConstraintNodeTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
