.TH "Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUriFacts" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUriFacts
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBTerminal_ReservedResourceUri_Prefix\fP = '__LUTHETUS__/__Terminal__/'"
.br
.ti -1c
.RI "const string \fBGit_ReservedResourceUri_Prefix\fP = '__LUTHETUS__/__Git__/'"
.br
.ti -1c
.RI "const string \fBDiff_ReservedResourceUri_Prefix\fP = '__LUTHETUS__/__Diff__/'"
.br
.ti -1c
.RI "static readonly \fBResourceUri\fP \fBSettingsPreviewTextEditorResourceUri\fP = new('__LUTHETUS__/__TextEditor__/preview\-settings')"
.br
.ti -1c
.RI "static readonly \fBResourceUri\fP \fBTestExplorerDetailsTextEditorResourceUri\fP = new('__LUTHETUS__/__TestExplorer__/details')"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBResourceUriFacts\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const string Luthetus\&.TextEditor\&.RazorLib\&.Lexers\&.Models\&.ResourceUriFacts\&.Diff_ReservedResourceUri_Prefix = '__LUTHETUS__/__Diff__/'\fR [static]\fP"

.PP
Definition at line \fB7\fP of file \fBResourceUriFacts\&.cs\fP\&.
.SS "const string Luthetus\&.TextEditor\&.RazorLib\&.Lexers\&.Models\&.ResourceUriFacts\&.Git_ReservedResourceUri_Prefix = '__LUTHETUS__/__Git__/'\fR [static]\fP"

.PP
Definition at line \fB6\fP of file \fBResourceUriFacts\&.cs\fP\&.
.SS "readonly \fBResourceUri\fP Luthetus\&.TextEditor\&.RazorLib\&.Lexers\&.Models\&.ResourceUriFacts\&.SettingsPreviewTextEditorResourceUri = new('__LUTHETUS__/__TextEditor__/preview\-settings')\fR [static]\fP"

.PP
Definition at line \fB8\fP of file \fBResourceUriFacts\&.cs\fP\&.
.SS "const string Luthetus\&.TextEditor\&.RazorLib\&.Lexers\&.Models\&.ResourceUriFacts\&.Terminal_ReservedResourceUri_Prefix = '__LUTHETUS__/__Terminal__/'\fR [static]\fP"

.PP
Definition at line \fB5\fP of file \fBResourceUriFacts\&.cs\fP\&.
.SS "readonly \fBResourceUri\fP Luthetus\&.TextEditor\&.RazorLib\&.Lexers\&.Models\&.ResourceUriFacts\&.TestExplorerDetailsTextEditorResourceUri = new('__LUTHETUS__/__TestExplorer__/details')\fR [static]\fP"

.PP
Definition at line \fB9\fP of file \fBResourceUriFacts\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
