.TH "Luthetus.CompilerServices.C.Facts.CLanguageFacts" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.C.Facts.CLanguageFacts
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBKeywords\fP"
.br
.ti -1c
.RI "class \fBPreprocessor\fP"
.br
.ti -1c
.RI "class \fBPunctuation\fP"
.br
.ti -1c
.RI "class \fBWhitespace\fP"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const char \fBSTRING_LITERAL_START\fP = '''"
.br
.ti -1c
.RI "const char \fBSTRING_LITERAL_END\fP = '''"
.br
.ti -1c
.RI "const char \fBCOMMENT_SINGLE_LINE_STARTING_CHAR\fP = '/'"
.br
.ti -1c
.RI "const string \fBCOMMENT_SINGLE_LINE_STARTING_SUBSTRING\fP = '//'"
.br
.ti -1c
.RI "const string \fBCOMMENT_MULTI_LINE_STARTING_SUBSTRING\fP = '/*'"
.br
.ti -1c
.RI "const char \fBCOMMENT_MULTI_LINE_ENDING_IDENTIFYING_CHAR\fP = '*'"
.br
.ti -1c
.RI "const string \fBCOMMENT_MULTI_LINE_ENDING_SUBSTRING\fP = '*/'"
.br
.ti -1c
.RI "const char \fBPREPROCESSOR_DIRECTIVE_TRANSITION_CHAR\fP = '#'"
.br
.ti -1c
.RI "const char \fBLIBRARY_REFERENCE_ABSOLUTE_PATH_STARTING_CHAR\fP = '<'"
.br
.ti -1c
.RI "const char \fBLIBRARY_REFERENCE_ABSOLUTE_PATH_ENDING_CHAR\fP = '>'"
.br
.ti -1c
.RI "const char \fBLIBRARY_REFERENCE_RELATIVE_PATH_STARTING_CHAR\fP = '''"
.br
.ti -1c
.RI "const char \fBLIBRARY_REFERENCE_RELATIVE_PATH_ENDING_CHAR\fP = '''"
.br
.ti -1c
.RI "const char \fBSTATEMENT_DELIMITER_CHAR\fP = ';'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const char Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.COMMENT_MULTI_LINE_ENDING_IDENTIFYING_CHAR = '*'\fR [static]\fP"

.PP
Definition at line \fB12\fP of file \fBCLanguageFacts\&.Main\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.COMMENT_MULTI_LINE_ENDING_SUBSTRING = '*/'\fR [static]\fP"

.PP
Definition at line \fB13\fP of file \fBCLanguageFacts\&.Main\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.COMMENT_MULTI_LINE_STARTING_SUBSTRING = '/*'\fR [static]\fP"

.PP
Definition at line \fB11\fP of file \fBCLanguageFacts\&.Main\&.cs\fP\&.
.SS "const char Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.COMMENT_SINGLE_LINE_STARTING_CHAR = '/'\fR [static]\fP"

.PP
Definition at line \fB8\fP of file \fBCLanguageFacts\&.Main\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.COMMENT_SINGLE_LINE_STARTING_SUBSTRING = '//'\fR [static]\fP"

.PP
Definition at line \fB9\fP of file \fBCLanguageFacts\&.Main\&.cs\fP\&.
.SS "const char Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.LIBRARY_REFERENCE_ABSOLUTE_PATH_ENDING_CHAR = '>'\fR [static]\fP"

.PP
Definition at line \fB18\fP of file \fBCLanguageFacts\&.Main\&.cs\fP\&.
.SS "const char Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.LIBRARY_REFERENCE_ABSOLUTE_PATH_STARTING_CHAR = '<'\fR [static]\fP"

.PP
Definition at line \fB17\fP of file \fBCLanguageFacts\&.Main\&.cs\fP\&.
.SS "const char Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.LIBRARY_REFERENCE_RELATIVE_PATH_ENDING_CHAR = '''\fR [static]\fP"

.PP
Definition at line \fB21\fP of file \fBCLanguageFacts\&.Main\&.cs\fP\&.
.SS "const char Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.LIBRARY_REFERENCE_RELATIVE_PATH_STARTING_CHAR = '''\fR [static]\fP"

.PP
Definition at line \fB20\fP of file \fBCLanguageFacts\&.Main\&.cs\fP\&.
.SS "const char Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.PREPROCESSOR_DIRECTIVE_TRANSITION_CHAR = '#'\fR [static]\fP"

.PP
Definition at line \fB15\fP of file \fBCLanguageFacts\&.Main\&.cs\fP\&.
.SS "const char Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.STATEMENT_DELIMITER_CHAR = ';'\fR [static]\fP"

.PP
Definition at line \fB23\fP of file \fBCLanguageFacts\&.Main\&.cs\fP\&.
.SS "const char Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.STRING_LITERAL_END = '''\fR [static]\fP"

.PP
Definition at line \fB6\fP of file \fBCLanguageFacts\&.Main\&.cs\fP\&.
.SS "const char Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.STRING_LITERAL_START = '''\fR [static]\fP"

.PP
Definition at line \fB5\fP of file \fBCLanguageFacts\&.Main\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
