.TH "Luthetus.Common.Tests.Basis.Reflectives.States.ReflectiveStateActionsTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Reflectives.States.ReflectiveStateActionsTests \- \fBReflectiveState\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRegisterAction\fP ()"
.br
.RI "ReflectiveState\&.RegisterAction "
.ti -1c
.RI "void \fBDisposeAction\fP ()"
.br
.RI "ReflectiveState\&.DisposeAction "
.ti -1c
.RI "void \fBWithAction\fP ()"
.br
.RI "ReflectiveState\&.WithAction "
.in -1c
.SH "Detailed Description"
.PP 
\fBReflectiveState\fP 
.PP
Definition at line \fB14\fP of file \fBReflectiveStateActionsTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Reflectives\&.States\&.ReflectiveStateActionsTests\&.DisposeAction ()"

.PP
ReflectiveState\&.DisposeAction 
.PP
Definition at line \fB35\fP of file \fBReflectiveStateActionsTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Reflectives\&.States\&.ReflectiveStateActionsTests\&.RegisterAction ()"

.PP
ReflectiveState\&.RegisterAction 
.PP
Definition at line \fB20\fP of file \fBReflectiveStateActionsTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Reflectives\&.States\&.ReflectiveStateActionsTests\&.WithAction ()"

.PP
ReflectiveState\&.WithAction 
.PP
Definition at line \fB47\fP of file \fBReflectiveStateActionsTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
