.TH "Luthetus.TextEditor.Tests.Basis.Groups.Models.GroupApiTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.Groups.Models.GroupApiTests \- ITextEditorService\&.TextEditorGroupApi  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "ITextEditorService\&.TextEditorGroupApi\&.TextEditorGroupApi(ITextEditorService, IDispatcher) "
.ti -1c
.RI "void \fBSetActiveViewModel\fP ()"
.br
.RI "ITextEditorService\&.TextEditorGroupApi\&.SetActiveViewModel(Key<TextEditorGroup>, Key<TextEditorViewModel>) "
.ti -1c
.RI "void \fBRemoveViewModel\fP ()"
.br
.RI "ITextEditorService\&.TextEditorGroupApi\&.RemoveViewModel(Key<TextEditorGroup>, Key<TextEditorViewModel>) "
.ti -1c
.RI "void \fBRegister\fP ()"
.br
.RI "ITextEditorService\&.TextEditorGroupApi\&.Register(Key<TextEditorGroup>) "
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.RI "ITextEditorService\&.TextEditorGroupApi\&.Dispose(Key<TextEditorGroup>) "
.ti -1c
.RI "void \fBGetOrDefault\fP ()"
.br
.RI "ITextEditorService\&.TextEditorGroupApi\&.GetOrDefault(Key<TextEditorGroup>) "
.ti -1c
.RI "void \fBAddViewModel\fP ()"
.br
.RI "ITextEditorService\&.TextEditorGroupApi\&.AddViewModel(Key<TextEditorGroup>, Key<TextEditorViewModel>) "
.in -1c
.SH "Detailed Description"
.PP 
ITextEditorService\&.TextEditorGroupApi 
.PP
Definition at line \fB11\fP of file \fBGroupApiTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Groups\&.Models\&.GroupApiTests\&.AddViewModel ()"

.PP
ITextEditorService\&.TextEditorGroupApi\&.AddViewModel(Key<TextEditorGroup>, Key<TextEditorViewModel>) 
.PP
Definition at line \fB154\fP of file \fBGroupApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Groups\&.Models\&.GroupApiTests\&.Constructor ()"

.PP
ITextEditorService\&.TextEditorGroupApi\&.TextEditorGroupApi(ITextEditorService, IDispatcher) 
.PP
Definition at line \fB17\fP of file \fBGroupApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Groups\&.Models\&.GroupApiTests\&.Dispose ()"

.PP
ITextEditorService\&.TextEditorGroupApi\&.Dispose(Key<TextEditorGroup>) 
.PP
Definition at line \fB107\fP of file \fBGroupApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Groups\&.Models\&.GroupApiTests\&.GetOrDefault ()"

.PP
ITextEditorService\&.TextEditorGroupApi\&.GetOrDefault(Key<TextEditorGroup>) 
.PP
Definition at line \fB131\fP of file \fBGroupApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Groups\&.Models\&.GroupApiTests\&.Register ()"

.PP
ITextEditorService\&.TextEditorGroupApi\&.Register(Key<TextEditorGroup>) 
.PP
Definition at line \fB84\fP of file \fBGroupApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Groups\&.Models\&.GroupApiTests\&.RemoveViewModel ()"

.PP
ITextEditorService\&.TextEditorGroupApi\&.RemoveViewModel(Key<TextEditorGroup>, Key<TextEditorViewModel>) 
.PP
Definition at line \fB58\fP of file \fBGroupApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Groups\&.Models\&.GroupApiTests\&.SetActiveViewModel ()"

.PP
ITextEditorService\&.TextEditorGroupApi\&.SetActiveViewModel(Key<TextEditorGroup>, Key<TextEditorViewModel>) 
.PP
Definition at line \fB33\fP of file \fBGroupApiTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
