.TH "Luthetus.Extensions.DotNet.DotNetSolutions.Displays.Internals.SolutionVisualizationContextMenu" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.DotNetSolutions.Displays.Internals.SolutionVisualizationContextMenu
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly Key< \fBDropdownRecord\fP > \fBContextMenuEventDropdownKey\fP = Key<\fBDropdownRecord\fP>\&.NewKey()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override async Task \fBOnInitializedAsync\fP ()"
.br
.ti -1c
.RI "override void \fBOnAfterRender\fP (bool firstRender)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBDropdownRecord\fP? \fBDropdown\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "MouseEventArgs \fBMouseEventArgs\fP = null!\fR [get, set]\fP"
.br
.ti -1c
.RI "SolutionVisualizationModel \fBSolutionVisualizationModel\fP = null!\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB13\fP of file \fBSolutionVisualizationContextMenu\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Displays\&.Internals\&.SolutionVisualizationContextMenu\&.OnAfterRender (bool firstRender)\fR [protected]\fP"

.PP
Definition at line \fB46\fP of file \fBSolutionVisualizationContextMenu\&.razor\&.cs\fP\&.
.SS "override async Task Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Displays\&.Internals\&.SolutionVisualizationContextMenu\&.OnInitializedAsync ()\fR [protected]\fP"

.PP
Definition at line \fB35\fP of file \fBSolutionVisualizationContextMenu\&.razor\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly Key<\fBDropdownRecord\fP> Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Displays\&.Internals\&.SolutionVisualizationContextMenu\&.ContextMenuEventDropdownKey = Key<\fBDropdownRecord\fP>\&.NewKey()\fR [static]\fP"

.PP
Definition at line \fB30\fP of file \fBSolutionVisualizationContextMenu\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBDropdownRecord\fP? Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Displays\&.Internals\&.SolutionVisualizationContextMenu\&.Dropdown\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB23\fP of file \fBSolutionVisualizationContextMenu\&.razor\&.cs\fP\&.
.SS "MouseEventArgs Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Displays\&.Internals\&.SolutionVisualizationContextMenu\&.MouseEventArgs = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB26\fP of file \fBSolutionVisualizationContextMenu\&.razor\&.cs\fP\&.
.SS "SolutionVisualizationModel Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Displays\&.Internals\&.SolutionVisualizationContextMenu\&.SolutionVisualizationModel = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB28\fP of file \fBSolutionVisualizationContextMenu\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
