.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.GenericLexer.SyntaxObjects" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.GenericLexer.SyntaxObjects
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGenericCommentMultiLineSyntaxTests\fP"
.br
.RI "\fBGenericCommentMultiLineSyntax\fP "
.ti -1c
.RI "class \fBGenericCommentSingleLineSyntaxTests\fP"
.br
.RI "\fBGenericCommentSingleLineSyntax\fP "
.ti -1c
.RI "class \fBGenericDeliminationExtendedSyntaxTests\fP"
.br
.RI "\fBGenericDeliminationExtendedSyntax\fP "
.ti -1c
.RI "class \fBGenericDocumentSyntaxTests\fP"
.br
.RI "\fBGenericDocumentSyntax\fP "
.ti -1c
.RI "class \fBGenericFunctionSyntaxTests\fP"
.br
.RI "\fBGenericFunctionSyntax\fP "
.ti -1c
.RI "class \fBGenericKeywordSyntaxTests\fP"
.br
.RI "\fBGenericKeywordSyntax\fP "
.ti -1c
.RI "class \fBGenericPreprocessorDirectiveSyntaxTests\fP"
.br
.RI "\fBGenericPreprocessorDirectiveSyntax\fP "
.ti -1c
.RI "class \fBGenericStringSyntaxTests\fP"
.br
.RI "\fBGenericStringSyntax\fP "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
