.TH "Luthetus.TextEditor.RazorLib.Installations.Models.LuthetusTextEditorCustomThemeFacts" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Installations.Models.LuthetusTextEditorCustomThemeFacts
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBThemeRecord\fP \fBLightTheme\fP"
.br
.ti -1c
.RI "static readonly \fBThemeRecord\fP \fBDarkTheme\fP"
.br
.ti -1c
.RI "static readonly ImmutableArray< \fBThemeRecord\fP > \fBAllCustomThemesList\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is an exception to the naming convention, "don't use the word 'Luthetus' in class names"\&.

.PP
Reason for this exception: when one first starts interacting with this project, this type might be one of the first types they interact with\&. So, the redundancy of namespace and type containing '\fBLuthetus\fP' feels reasonable here\&. 
.PP
Definition at line \fB14\fP of file \fBLuthetusTextEditorCustomThemeFacts\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly ImmutableArray<\fBThemeRecord\fP> Luthetus\&.TextEditor\&.RazorLib\&.Installations\&.Models\&.LuthetusTextEditorCustomThemeFacts\&.AllCustomThemesList\fR [static]\fP"
\fBInitial value:\fP
.nf
= new[]
    {
        LightTheme,
        DarkTheme
    }\&.ToImmutableArray()
.PP
.fi

.PP
Definition at line \fB32\fP of file \fBLuthetusTextEditorCustomThemeFacts\&.cs\fP\&.
.SS "readonly \fBThemeRecord\fP Luthetus\&.TextEditor\&.RazorLib\&.Installations\&.Models\&.LuthetusTextEditorCustomThemeFacts\&.DarkTheme\fR [static]\fP"
\fBInitial value:\fP
.nf
= new ThemeRecord(
        new Key<ThemeRecord>(Guid\&.Parse("56d64327\-03c2\-48a3\-b086\-11b101826efb")),
        "Luthetus IDE Dark Theme",
        "luth_dark\-theme",
        ThemeContrastKind\&.Default,
        ThemeColorKind\&.Dark,
        new[] { ThemeScope\&.TextEditor }\&.ToImmutableList())
.PP
.fi

.PP
Definition at line \fB24\fP of file \fBLuthetusTextEditorCustomThemeFacts\&.cs\fP\&.
.SS "readonly \fBThemeRecord\fP Luthetus\&.TextEditor\&.RazorLib\&.Installations\&.Models\&.LuthetusTextEditorCustomThemeFacts\&.LightTheme\fR [static]\fP"
\fBInitial value:\fP
.nf
= new ThemeRecord(
        new Key<ThemeRecord>(Guid\&.Parse("8165209b\-0cea\-45b4\-b6dd\-e5661b319c73")),
        "Luthetus IDE Light Theme",
        "luth_light\-theme",
        ThemeContrastKind\&.Default,
        ThemeColorKind\&.Light,
        new[] { ThemeScope\&.TextEditor }\&.ToImmutableList())
.PP
.fi

.PP
Definition at line \fB16\fP of file \fBLuthetusTextEditorCustomThemeFacts\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
