.TH "Luthetus.Ide.RazorLib.Shareds.Displays.Internals.IdeImportDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.Shareds.Displays.Internals.IdeImportDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase, and IDisposable\&.
.SS "Public Types"

.in +1c
.ti -1c
.RI "enum \fBImportPhase\fP { \fBNone\fP, \fBRequestRepoContents\fP, \fBReadZipArchive\fP, \fBError\fP, \fBFinished\fP }"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBIdeImportDisplay\&.razor\&.cs\fP\&.
.SH "Member Enumeration Documentation"
.PP 
.SS "enum \fBLuthetus\&.Ide\&.RazorLib\&.Shareds\&.Displays\&.Internals\&.IdeImportDisplay\&.ImportPhase\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BINone \fP
.TP
\f(BIRequestRepoContents \fP
.TP
\f(BIReadZipArchive \fP
.TP
\f(BIError \fP
.TP
\f(BIFinished \fP
.PP
Definition at line \fB42\fP of file \fBIdeImportDisplay\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Ide\&.RazorLib\&.Shareds\&.Displays\&.Internals\&.IdeImportDisplay\&.Dispose ()"

.PP
Definition at line \fB208\fP of file \fBIdeImportDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
