.TH "Luthetus.Ide.Tests.Basis.FolderExplorers.Models.FolderExplorerTreeViewMouseEventHandlerTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.Tests.Basis.FolderExplorers.Models.FolderExplorerTreeViewMouseEventHandlerTests \- \fBFolderExplorerTreeViewMouseEventHandler\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "FolderExplorerTreeViewMouseEventHandler(EditorSync, ITreeViewService, IBackgroundTaskService) "
.ti -1c
.RI "void \fBOnDoubleClickAsync\fP ()"
.br
.RI "\fBFolderExplorerTreeViewMouseEventHandler\&.OnDoubleClickAsync(TreeViewCommandArgs)\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBFolderExplorerTreeViewMouseEventHandler\fP 
.PP
Definition at line \fB11\fP of file \fBFolderExplorerTreeViewMouseEventHandlerTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.FolderExplorers\&.Models\&.FolderExplorerTreeViewMouseEventHandlerTests\&.Constructor ()"

.PP
FolderExplorerTreeViewMouseEventHandler(EditorSync, ITreeViewService, IBackgroundTaskService) 
.PP
Definition at line \fB17\fP of file \fBFolderExplorerTreeViewMouseEventHandlerTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.FolderExplorers\&.Models\&.FolderExplorerTreeViewMouseEventHandlerTests\&.OnDoubleClickAsync ()"

.PP
\fBFolderExplorerTreeViewMouseEventHandler\&.OnDoubleClickAsync(TreeViewCommandArgs)\fP 
.PP
Definition at line \fB26\fP of file \fBFolderExplorerTreeViewMouseEventHandlerTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
