.TH "Luthetus.Ide.Tests.Basis.Terminals.States.TerminalStateReducerTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.Tests.Basis.Terminals.States.TerminalStateReducerTests \- TerminalState\&.Reducer  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBReduceRegisterAction\fP ()"
.br
.RI "TerminalState\&.Reducer\&.ReduceRegisterAction(TerminalState, TerminalState\&.RegisterAction) "
.ti -1c
.RI "void \fBReduceNotifyStateChangedAction\fP ()"
.br
.RI "TerminalState\&.Reducer\&.ReduceNotifyStateChangedAction(TerminalState, TerminalState\&.NotifyStateChangedAction) "
.ti -1c
.RI "void \fBReduceDisposeAction\fP ()"
.br
.RI "TerminalState\&.Reducer\&.ReduceDisposeAction(TerminalState, TerminalState\&.DisposeAction) "
.in -1c
.SH "Detailed Description"
.PP 
TerminalState\&.Reducer 
.PP
Definition at line \fB8\fP of file \fBTerminalStateReducerTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.Terminals\&.States\&.TerminalStateReducerTests\&.ReduceDisposeAction ()"

.PP
TerminalState\&.Reducer\&.ReduceDisposeAction(TerminalState, TerminalState\&.DisposeAction) 
.PP
Definition at line \fB32\fP of file \fBTerminalStateReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.Terminals\&.States\&.TerminalStateReducerTests\&.ReduceNotifyStateChangedAction ()"

.PP
TerminalState\&.Reducer\&.ReduceNotifyStateChangedAction(TerminalState, TerminalState\&.NotifyStateChangedAction) 
.PP
Definition at line \fB23\fP of file \fBTerminalStateReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.Terminals\&.States\&.TerminalStateReducerTests\&.ReduceRegisterAction ()"

.PP
TerminalState\&.Reducer\&.ReduceRegisterAction(TerminalState, TerminalState\&.RegisterAction) 
.PP
Definition at line \fB14\fP of file \fBTerminalStateReducerTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
