.TH "Luthetus.TextEditor.Tests.Basis.Diffs.Models.TextEditorDiffResultTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.Diffs.Models.TextEditorDiffResultTests \- \fBTextEditorDiffResult\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "TextEditorDiffResult(string, string, TextEditorDiffCell[,], ValueTuple<int, int, int>, string, ImmutableList<TextEditorTextSpan>, ImmutableList<TextEditorTextSpan>) 
.br
----
.br
 \fBTextEditorDiffResult\&.InText\fP \fBTextEditorDiffResult\&.OutText\fP \fBTextEditorDiffResult\&.DiffMatrix\fP \fBTextEditorDiffResult\&.HighestSourceWeightTuple\fP \fBTextEditorDiffResult\&.LongestCommonSubsequence\fP \fBTextEditorDiffResult\&.InResultTextSpanList\fP \fBTextEditorDiffResult\&.OutResultTextSpanList\fP "
.ti -1c
.RI "void \fBCalculate\fP ()"
.br
.RI "\fBTextEditorDiffResult\&.Calculate(ResourceUri, string, ResourceUri, string)\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBTextEditorDiffResult\fP 
.PP
Definition at line \fB10\fP of file \fBTextEditorDiffResultTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Diffs\&.Models\&.TextEditorDiffResultTests\&.Calculate ()"

.PP
\fBTextEditorDiffResult\&.Calculate(ResourceUri, string, ResourceUri, string)\fP 
.PP
Definition at line \fB33\fP of file \fBTextEditorDiffResultTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Diffs\&.Models\&.TextEditorDiffResultTests\&.Constructor ()"

.PP
TextEditorDiffResult(string, string, TextEditorDiffCell[,], ValueTuple<int, int, int>, string, ImmutableList<TextEditorTextSpan>, ImmutableList<TextEditorTextSpan>) 
.br
----
.br
 \fBTextEditorDiffResult\&.InText\fP \fBTextEditorDiffResult\&.OutText\fP \fBTextEditorDiffResult\&.DiffMatrix\fP \fBTextEditorDiffResult\&.HighestSourceWeightTuple\fP \fBTextEditorDiffResult\&.LongestCommonSubsequence\fP \fBTextEditorDiffResult\&.InResultTextSpanList\fP \fBTextEditorDiffResult\&.OutResultTextSpanList\fP 
.PP
Definition at line \fB24\fP of file \fBTextEditorDiffResultTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
