.TH "Luthetus.CompilerServices.Json.SyntaxObjects.JsonArraySyntax" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.Json.SyntaxObjects.JsonArraySyntax
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.CompilerServices\&.Json\&.IJsonSyntax\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJsonArraySyntax\fP (\fBTextEditorTextSpan\fP textEditorTextSpan, ImmutableArray< \fBJsonObjectSyntax\fP > childJsonObjectSyntaxes)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "TextEditorTextSpan \fBTextEditorTextSpan\fP\fR [get]\fP"
.br
.ti -1c
.RI "ImmutableArray< \fBJsonObjectSyntax\fP > \fBChildJsonObjectSyntaxes\fP\fR [get]\fP"
.br
.ti -1c
.RI "ImmutableArray< \fBIJsonSyntax\fP > \fBChildJsonSyntaxes\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBJsonSyntaxKind\fP \fBJsonSyntaxKind\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBJsonArraySyntax\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.CompilerServices\&.Json\&.SyntaxObjects\&.JsonArraySyntax\&.JsonArraySyntax (\fBTextEditorTextSpan\fP textEditorTextSpan, ImmutableArray< \fBJsonObjectSyntax\fP > childJsonObjectSyntaxes)"

.PP
Definition at line \fB9\fP of file \fBJsonArraySyntax\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "ImmutableArray<\fBJsonObjectSyntax\fP> Luthetus\&.CompilerServices\&.Json\&.SyntaxObjects\&.JsonArraySyntax\&.ChildJsonObjectSyntaxes\fR [get]\fP"

.PP
Definition at line \fB18\fP of file \fBJsonArraySyntax\&.cs\fP\&.
.SS "ImmutableArray<\fBIJsonSyntax\fP> Luthetus\&.CompilerServices\&.Json\&.SyntaxObjects\&.JsonArraySyntax\&.ChildJsonSyntaxes\fR [get]\fP"

.PP
Implements \fBLuthetus\&.CompilerServices\&.Json\&.IJsonSyntax\fP\&.
.PP
Definition at line \fB19\fP of file \fBJsonArraySyntax\&.cs\fP\&.
.SS "\fBJsonSyntaxKind\fP Luthetus\&.CompilerServices\&.Json\&.SyntaxObjects\&.JsonArraySyntax\&.JsonSyntaxKind\fR [get]\fP"

.PP
Implements \fBLuthetus\&.CompilerServices\&.Json\&.IJsonSyntax\fP\&.
.PP
Definition at line \fB25\fP of file \fBJsonArraySyntax\&.cs\fP\&.
.SS "TextEditorTextSpan Luthetus\&.CompilerServices\&.Json\&.SyntaxObjects\&.JsonArraySyntax\&.TextEditorTextSpan\fR [get]\fP"

.PP
Implements \fBLuthetus\&.CompilerServices\&.Json\&.IJsonSyntax\fP\&.
.PP
Definition at line \fB17\fP of file \fBJsonArraySyntax\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
