.TH "Luthetus.Common.Tests.Basis.Dialogs.Models.DialogServiceTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Dialogs.Models.DialogServiceTests \- \fBDialogService\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "DialogService(IDispatcher, IState<RazorLib\&.Dialogs\&.States\&.DialogState>) 
.br
----
.br
 \fBDialogService\&.DialogStateWrap\fP "
.ti -1c
.RI "void \fBRegisterDialogRecord\fP ()"
.br
.RI "DialogService\&.RegisterDialogRecord(DialogRecord) "
.ti -1c
.RI "void \fBSetDialogRecordIsMaximized\fP ()"
.br
.RI "DialogService\&.SetDialogRecordIsMaximized(Key<DialogRecord>, bool) "
.ti -1c
.RI "void \fBDisposeDialogRecord\fP ()"
.br
.RI "DialogService\&.DisposeDialogRecord(Key<DialogRecord>) "
.in -1c
.SH "Detailed Description"
.PP 
\fBDialogService\fP 
.PP
Definition at line \fB13\fP of file \fBDialogServiceTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Dialogs\&.Models\&.DialogServiceTests\&.Constructor ()"

.PP
DialogService(IDispatcher, IState<RazorLib\&.Dialogs\&.States\&.DialogState>) 
.br
----
.br
 \fBDialogService\&.DialogStateWrap\fP 
.PP
Definition at line \fB21\fP of file \fBDialogServiceTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Dialogs\&.Models\&.DialogServiceTests\&.DisposeDialogRecord ()"

.PP
DialogService\&.DisposeDialogRecord(Key<DialogRecord>) 
.PP
Definition at line \fB71\fP of file \fBDialogServiceTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Dialogs\&.Models\&.DialogServiceTests\&.RegisterDialogRecord ()"

.PP
DialogService\&.RegisterDialogRecord(DialogRecord) 
.PP
Definition at line \fB33\fP of file \fBDialogServiceTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Dialogs\&.Models\&.DialogServiceTests\&.SetDialogRecordIsMaximized ()"

.PP
DialogService\&.SetDialogRecordIsMaximized(Key<DialogRecord>, bool) 
.PP
Definition at line \fB49\fP of file \fBDialogServiceTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
