.TH "Luthetus.Ide.Tests.Basis.ComponentRenderers.Models.LuthetusIdeTreeViewsTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.Tests.Basis.ComponentRenderers.Models.LuthetusIdeTreeViewsTests \- LuthetusIdeTreeViews  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "LuthetusIdeTreeViews(Type, Type, Type, Type, Type, Type, Type, Type, Type, Type) 
.br
----
.br
 LuthetusIdeTreeViews\&.TreeViewNamespacePathRendererType LuthetusIdeTreeViews\&.TreeViewSolutionFolderRendererType LuthetusIdeTreeViews\&.TreeViewCSharpProjectDependenciesRendererType LuthetusIdeTreeViews\&.TreeViewCSharpProjectNugetPackageReferencesRendererType LuthetusIdeTreeViews\&.TreeViewCSharpProjectToProjectReferencesRendererType LuthetusIdeTreeViews\&.TreeViewLightWeightNugetPackageRecordRendererType LuthetusIdeTreeViews\&.TreeViewCSharpProjectToProjectReferenceRendererType LuthetusIdeTreeViews\&.TreeViewAbsolutePathRendererType LuthetusIdeTreeViews\&.TreeViewGitFileRendererType LuthetusIdeTreeViews\&.TreeViewCompilerServiceRendererType "
.in -1c
.SH "Detailed Description"
.PP 
LuthetusIdeTreeViews 
.PP
Definition at line \fB6\fP of file \fBLuthetusIdeTreeViewsTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.ComponentRenderers\&.Models\&.LuthetusIdeTreeViewsTests\&.Constructor ()"

.PP
LuthetusIdeTreeViews(Type, Type, Type, Type, Type, Type, Type, Type, Type, Type) 
.br
----
.br
 LuthetusIdeTreeViews\&.TreeViewNamespacePathRendererType LuthetusIdeTreeViews\&.TreeViewSolutionFolderRendererType LuthetusIdeTreeViews\&.TreeViewCSharpProjectDependenciesRendererType LuthetusIdeTreeViews\&.TreeViewCSharpProjectNugetPackageReferencesRendererType LuthetusIdeTreeViews\&.TreeViewCSharpProjectToProjectReferencesRendererType LuthetusIdeTreeViews\&.TreeViewLightWeightNugetPackageRecordRendererType LuthetusIdeTreeViews\&.TreeViewCSharpProjectToProjectReferenceRendererType LuthetusIdeTreeViews\&.TreeViewAbsolutePathRendererType LuthetusIdeTreeViews\&.TreeViewGitFileRendererType LuthetusIdeTreeViews\&.TreeViewCompilerServiceRendererType 
.PP
Definition at line \fB23\fP of file \fBLuthetusIdeTreeViewsTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
