.TH "Luthetus.Common.RazorLib.Dialogs.Models.IDialogService" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Dialogs.Models.IDialogService
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.DialogService\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRegisterDialogRecord\fP (\fBIDialog\fP dialogRecord)"
.br
.ti -1c
.RI "void \fBSetDialogRecordIsMaximized\fP (Key< \fBIDynamicViewModel\fP > dynamicViewModelKey, bool isMaximized)"
.br
.ti -1c
.RI "void \fBDisposeDialogRecord\fP (Key< \fBIDynamicViewModel\fP > dynamicViewModelKey)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IState< \fBDialogState\fP > \fBDialogStateWrap\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBIDialogService\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.IDialogService\&.DisposeDialogRecord (Key< \fBIDynamicViewModel\fP > dynamicViewModelKey)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.DialogService\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.IDialogService\&.RegisterDialogRecord (\fBIDialog\fP dialogRecord)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.DialogService\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.IDialogService\&.SetDialogRecordIsMaximized (Key< \fBIDynamicViewModel\fP > dynamicViewModelKey, bool isMaximized)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.DialogService\fP\&.
.SH "Property Documentation"
.PP 
.SS "IState<\fBDialogState\fP> Luthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.IDialogService\&.DialogStateWrap\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.DialogService\fP\&.
.PP
Definition at line \fB10\fP of file \fBIDialogService\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
