.TH "Luthetus.Common.RazorLib.Menus.Models.MenuOptionCallbacks" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Menus.Models.MenuOptionCallbacks
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMenuOptionCallbacks\fP (Func< Task > hideWidgetAsync, Func< Action, Task > completeWidgetAsync)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Func< Task > \fBHideWidgetAsync\fP\fR [get]\fP"
.br
.RI "No longer display widget but will NOT close the menu\&. "
.ti -1c
.RI "Func< Action, Task > \fBCompleteWidgetAsync\fP\fR [get]\fP"
.br
.RI "No longer display widget, close the menu, and once the menu is closed proceed to invoke the action that was provided\&. 
.br

.br
 This is done to ensure that a widget is only completed once as the completed logic does not run until the widget is no longer rendered\&. 
.br

.br
 Without this it is believed there is a possibility that one might hold the 'Enter' key in the example of submitting a form and submit it many times\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBMenuOptionCallbacks\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Common\&.RazorLib\&.Menus\&.Models\&.MenuOptionCallbacks\&.MenuOptionCallbacks (Func< Task > hideWidgetAsync, Func< Action, Task > completeWidgetAsync)"

.PP
Definition at line \fB5\fP of file \fBMenuOptionCallbacks\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Func<Action, Task> Luthetus\&.Common\&.RazorLib\&.Menus\&.Models\&.MenuOptionCallbacks\&.CompleteWidgetAsync\fR [get]\fP"

.PP
No longer display widget, close the menu, and once the menu is closed proceed to invoke the action that was provided\&. 
.br

.br
 This is done to ensure that a widget is only completed once as the completed logic does not run until the widget is no longer rendered\&. 
.br

.br
 Without this it is believed there is a possibility that one might hold the 'Enter' key in the example of submitting a form and submit it many times\&. 
.PP
Definition at line \fB28\fP of file \fBMenuOptionCallbacks\&.cs\fP\&.
.SS "Func<Task> Luthetus\&.Common\&.RazorLib\&.Menus\&.Models\&.MenuOptionCallbacks\&.HideWidgetAsync\fR [get]\fP"

.PP
No longer display widget but will NOT close the menu\&. 
.PP
Definition at line \fB16\fP of file \fBMenuOptionCallbacks\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
