.TH "Luthetus.Common.RazorLib.Installations.Displays.LuthetusCommonInitializer" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Installations.Displays.LuthetusCommonInitializer
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase, and IDisposable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInitialized\fP ()"
.br
.ti -1c
.RI "override async Task \fBOnAfterRenderAsync\fP (bool firstRender)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static Key< \fBContextSwitchGroup\fP > \fBContextSwitchGroupKey\fP = Key<\fBContextSwitchGroup\fP>\&.NewKey()\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is an exception to the naming convention, "don't use the word 'Luthetus' in class names"\&.

.PP
Reason for this exception: when one first starts interacting with this project, this type might be one of the first types they interact with\&. So, the redundancy of namespace and type containing '\fBLuthetus\fP' feels reasonable here\&. 
.PP
Definition at line \fB28\fP of file \fBLuthetusCommonInitializer\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.RazorLib\&.Installations\&.Displays\&.LuthetusCommonInitializer\&.Dispose ()"

.PP
Definition at line \fB168\fP of file \fBLuthetusCommonInitializer\&.razor\&.cs\fP\&.
.SS "override async Task Luthetus\&.Common\&.RazorLib\&.Installations\&.Displays\&.LuthetusCommonInitializer\&.OnAfterRenderAsync (bool firstRender)\fR [protected]\fP"

.PP
Definition at line \fB160\fP of file \fBLuthetusCommonInitializer\&.razor\&.cs\fP\&.
.SS "override void Luthetus\&.Common\&.RazorLib\&.Installations\&.Displays\&.LuthetusCommonInitializer\&.OnInitialized ()\fR [protected]\fP"

.PP
Definition at line \fB58\fP of file \fBLuthetusCommonInitializer\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Key<\fBContextSwitchGroup\fP> Luthetus\&.Common\&.RazorLib\&.Installations\&.Displays\&.LuthetusCommonInitializer\&.ContextSwitchGroupKey = Key<\fBContextSwitchGroup\fP>\&.NewKey()\fR [static]\fP, \fR [get]\fP"

.PP
Definition at line \fB51\fP of file \fBLuthetusCommonInitializer\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
