.TH "Luthetus.Extensions.DotNet.Nugets.Displays.NuGetPackageManager" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.Nugets.Displays.NuGetPackageManager
.SH SYNOPSIS
.br
.PP
.PP
Inherits FluxorComponent, and \fBLuthetus\&.Extensions\&.DotNet\&.ComponentRenderers\&.Models\&.INuGetPackageManagerRendererType\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBNugetQuery\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIncludePrerelease\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB16\fP of file \fBNuGetPackageManager\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Luthetus\&.Extensions\&.DotNet\&.Nugets\&.Displays\&.NuGetPackageManager\&.IncludePrerelease\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB42\fP of file \fBNuGetPackageManager\&.razor\&.cs\fP\&.
.SS "string Luthetus\&.Extensions\&.DotNet\&.Nugets\&.Displays\&.NuGetPackageManager\&.NugetQuery\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB36\fP of file \fBNuGetPackageManager\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
