.TH "Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Parsers.ExpressionTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Parsers.ExpressionTests
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTest\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBNumeric_Add_BinaryExpressionNode\fP ()"
.br
.ti -1c
.RI "void \fBNumeric_Add_BinaryExpressionNode_More\fP ()"
.br
.ti -1c
.RI "void \fBNumeric_Subtract_BinaryExpressionNode\fP ()"
.br
.ti -1c
.RI "void \fBNumeric_Star_BinaryExpressionNode\fP ()"
.br
.ti -1c
.RI "void \fBNumeric_Division_BinaryExpressionNode\fP ()"
.br
.ti -1c
.RI "void \fBNumeric_EqualsEquals_BinaryExpressionNode\fP ()"
.br
.ti -1c
.RI "void \fBString_BinaryExpressionNode\fP ()"
.br
.ti -1c
.RI "void \fBString_Interpolated\fP ()"
.br
.ti -1c
.RI "void \fBString_Verbatim\fP ()"
.br
.ti -1c
.RI "void \fBString_InterpolatedVerbatim\fP ()"
.br
.ti -1c
.RI "void \fBString_VerbatimInterpolated\fP ()"
.br
.ti -1c
.RI "void \fBChar_BinaryExpressionNode\fP ()"
.br
.ti -1c
.RI "void \fBBool_BinaryExpressionNode\fP ()"
.br
.ti -1c
.RI "void \fBParenthesizedExpressionNode_Test\fP ()"
.br
.ti -1c
.RI "void \fBShortCircuit\fP ()"
.br
.ti -1c
.RI "void \fBExplicitCastNode_IdentifierToken\fP ()"
.br
.ti -1c
.RI "void \fBExplicitCastNode_KeywordToken\fP ()"
.br
.ti -1c
.RI "void \fBFunctionInvocationNode_Basic\fP ()"
.br
.ti -1c
.RI "void \fBFunctionInvocationNode_Parameters\fP ()"
.br
.ti -1c
.RI "void \fBFunctionInvocationNode_Generic\fP ()"
.br
.ti -1c
.RI "void \fBFunctionInvocationNode_Generic_Parameters\fP ()"
.br
.ti -1c
.RI "void \fBConstructorInvocationNode_Basic\fP ()"
.br
.RI "TODO: Why is the new keyword being added as the index 0 node of topCodeBlock?\&.\&.\&. \&.\&.\&.Only the '\fBConstructorInvocationExpressionNode\fP' should be in the 'GetChildList()' of 'topCodeBlock'\&. "
.ti -1c
.RI "void \fBConstructorInvocationNode_Parameters\fP ()"
.br
.RI "TODO: Why is the new keyword being added as the index 0 node of topCodeBlock?\&.\&.\&. \&.\&.\&.Only the '\fBConstructorInvocationExpressionNode\fP' should be in the 'GetChildList()' of 'topCodeBlock'\&. "
.ti -1c
.RI "void \fBConstructorInvocationNode_Generic\fP ()"
.br
.RI "TODO: Why is the new keyword being added as the index 0 node of topCodeBlock?\&.\&.\&. \&.\&.\&.Only the '\fBConstructorInvocationExpressionNode\fP' should be in the 'GetChildList()' of 'topCodeBlock'\&. "
.ti -1c
.RI "void \fBConstructorInvocationNode_Generic_Parameters_MISSING_NumericLiteralToken_A\fP ()"
.br
.ti -1c
.RI "void \fBConstructorInvocationNode_Generic_Parameters_MISSING_NumericLiteralToken_B\fP ()"
.br
.ti -1c
.RI "void \fBConstructorInvocationNode_Generic_Parameters\fP ()"
.br
.RI "TODO: Why is the new keyword being added as the index 0 node of topCodeBlock?\&.\&.\&. \&.\&.\&.Only the '\fBConstructorInvocationExpressionNode\fP' should be in the 'GetChildList()' of 'topCodeBlock'\&. "
.ti -1c
.RI "void \fBConstructorInvocationNode_NoTypeClauseNode\fP ()"
.br
.ti -1c
.RI "void \fBObjectInitializationNode_Parameters_NoTrailingComma\fP ()"
.br
.ti -1c
.RI "void \fBObjectInitializationNode__Parameters_WithTrailingComma\fP ()"
.br
.ti -1c
.RI "void \fBObjectInitializationNode_NoParameters_NoTrailingComma\fP ()"
.br
.ti -1c
.RI "void \fBObjectInitializationNode_NoParameters_WithTrailingComma\fP ()"
.br
.ti -1c
.RI "void \fBObjectInitializationNode_WithParenthesis\fP ()"
.br
.ti -1c
.RI "void \fBCollectionInitializationNode_Parameters_NoTrailingComma\fP ()"
.br
.ti -1c
.RI "void \fBCollectionInitializationNode_Parameters_WithTrailingComma\fP ()"
.br
.ti -1c
.RI "void \fBCollectionInitializationNode_NoParameters_NoTrailingComma\fP ()"
.br
.ti -1c
.RI "void \fBCollectionInitializationNode_NoParameters_WithTrailingComma\fP ()"
.br
.ti -1c
.RI "void \fBCollectionInitializationNode_WithParenthesis\fP ()"
.br
.ti -1c
.RI "void \fBLambdaFunction_Expression_NoParameter\fP ()"
.br
.ti -1c
.RI "void \fBLambdaFunction_Expression_SingleParameter\fP ()"
.br
.ti -1c
.RI "void \fBLambdaFunction_Expression_ManyParameter_Async\fP ()"
.br
.ti -1c
.RI "void \fBLambdaFunction_CodeBlock_NoParameter_Async\fP ()"
.br
.ti -1c
.RI "void \fBLambdaFunction_CodeBlock_SingleParameter_Async\fP ()"
.br
.ti -1c
.RI "void \fBLambdaFunction_CodeBlock_ManyParameter\fP ()"
.br
.ti -1c
.RI "void \fBMethodGroup\fP ()"
.br
.ti -1c
.RI "void \fBAction_ImplicitInvocation_NoParameter\fP ()"
.br
.ti -1c
.RI "void \fBAction_ImplicitInvocation_SingleParameter\fP ()"
.br
.ti -1c
.RI "void \fBAction_ImplicitInvocation_ManyParameter\fP ()"
.br
.ti -1c
.RI "void \fBFunc_ImplicitInvocation_NoParameter\fP ()"
.br
.ti -1c
.RI "void \fBFunc_ImplicitInvocation_SingleParameter\fP ()"
.br
.ti -1c
.RI "void \fBFunc_ImplicitInvocation_ManyParameter\fP ()"
.br
.ti -1c
.RI "void \fBFunctionInvocation_NamedParameters\fP ()"
.br
.ti -1c
.RI "void \fBConstructorInvocation_NamedParameters\fP ()"
.br
.ti -1c
.RI "void \fBRecord_With_Keyword\fP ()"
.br
.ti -1c
.RI "void \fBGetterAndSetterThatAreNotAutoImplemented\fP ()"
.br
.ti -1c
.RI "void \fBMemberAccess\fP ()"
.br
.ti -1c
.RI "void \fBWhileLoop_DoNotBreakScope\fP ()"
.br
.RI "TODO: Repeat this test for all the control keywords\&. "
.ti -1c
.RI "void \fBIfStatement_StopExpressionsCreatingScope\fP ()"
.br
.ti -1c
.RI "void \fBCollectionIndex\fP ()"
.br
.ti -1c
.RI "void \fBAwaitTask\fP ()"
.br
.ti -1c
.RI "void \fBSwitchStatement\fP ()"
.br
.ti -1c
.RI "void \fBSwitchExpression\fP ()"
.br
.ti -1c
.RI "void \fBParenthesized_ExplicitCast\fP ()"
.br
.ti -1c
.RI "void \fBFunctionParameter_OutKeyword\fP ()"
.br
.ti -1c
.RI "void \fBLessThanBinaryOperator\fP ()"
.br
.ti -1c
.RI "void \fBGreaterThanBinaryOperator\fP ()"
.br
.ti -1c
.RI "void \fBLessThanEqualToBinaryOperator\fP ()"
.br
.ti -1c
.RI "void \fBGreaterThanEqualToBinaryOperator\fP ()"
.br
.ti -1c
.RI "void \fBFunctionParameterOptional\fP ()"
.br
.ti -1c
.RI "void \fBConstructorInvokesConstructor\fP ()"
.br
.ti -1c
.RI "void \fBValueTuple\fP ()"
.br
.ti -1c
.RI "void \fBFunctionInvocationExpressionStatement\fP ()"
.br
.RI "This parses incorrectly: 'Func(decimalPercentProgress);'\&. "
.ti -1c
.RI "void \fBTypeClauseNode_Identifier\fP ()"
.br
.ti -1c
.RI "void \fBTypeClauseNode_Keyword\fP ()"
.br
.ti -1c
.RI "void \fBTypeClauseNode_Var\fP ()"
.br
.ti -1c
.RI "void \fBTypeClauseNode_Generic\fP ()"
.br
.ti -1c
.RI "void \fBTypeClauseNode_Nullable_Keyword\fP ()"
.br
.ti -1c
.RI "void \fBTypeClauseNode_Nullable_Identifier\fP ()"
.br
.ti -1c
.RI "void \fBTypeClauseNode_GenericNullable\fP ()"
.br
.ti -1c
.RI "void \fBVariableAssignmentExpressionNode\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB17\fP of file \fBExpressionTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.Action_ImplicitInvocation_ManyParameter ()"

.PP
Definition at line \fB1479\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.Action_ImplicitInvocation_NoParameter ()"

.PP
Definition at line \fB1443\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.Action_ImplicitInvocation_SingleParameter ()"

.PP
Definition at line \fB1461\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.AwaitTask ()"

.PP
Definition at line \fB1711\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.Bool_BinaryExpressionNode ()"

.PP
Definition at line \fB330\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.Char_BinaryExpressionNode ()"

.PP
Definition at line \fB304\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.CollectionIndex ()"

.PP
Definition at line \fB1702\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.CollectionInitializationNode_NoParameters_NoTrailingComma ()"

.PP
Definition at line \fB1081\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.CollectionInitializationNode_NoParameters_WithTrailingComma ()"

.PP
Definition at line \fB1111\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.CollectionInitializationNode_Parameters_NoTrailingComma ()"

.PP
Definition at line \fB927\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.CollectionInitializationNode_Parameters_WithTrailingComma ()"

.PP
Definition at line \fB973\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.CollectionInitializationNode_WithParenthesis ()"

.PP
Definition at line \fB1141\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.ConstructorInvocation_NamedParameters ()"

.PP
Definition at line \fB1569\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.ConstructorInvocationNode_Basic ()"

.PP
TODO: Why is the new keyword being added as the index 0 node of topCodeBlock?\&.\&.\&. \&.\&.\&.Only the '\fBConstructorInvocationExpressionNode\fP' should be in the 'GetChildList()' of 'topCodeBlock'\&. 
.PP
Definition at line \fB534\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.ConstructorInvocationNode_Generic ()"

.PP
TODO: Why is the new keyword being added as the index 0 node of topCodeBlock?\&.\&.\&. \&.\&.\&.Only the '\fBConstructorInvocationExpressionNode\fP' should be in the 'GetChildList()' of 'topCodeBlock'\&. 
.PP
Definition at line \fB594\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.ConstructorInvocationNode_Generic_Parameters ()"

.PP
TODO: Why is the new keyword being added as the index 0 node of topCodeBlock?\&.\&.\&. \&.\&.\&.Only the '\fBConstructorInvocationExpressionNode\fP' should be in the 'GetChildList()' of 'topCodeBlock'\&. 
.PP
Definition at line \fB671\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.ConstructorInvocationNode_Generic_Parameters_MISSING_NumericLiteralToken_A ()"

.PP
Definition at line \fB622\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.ConstructorInvocationNode_Generic_Parameters_MISSING_NumericLiteralToken_B ()"

.PP
Definition at line \fB636\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.ConstructorInvocationNode_NoTypeClauseNode ()"

.PP
Definition at line \fB711\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.ConstructorInvocationNode_Parameters ()"

.PP
TODO: Why is the new keyword being added as the index 0 node of topCodeBlock?\&.\&.\&. \&.\&.\&.Only the '\fBConstructorInvocationExpressionNode\fP' should be in the 'GetChildList()' of 'topCodeBlock'\&. 
.PP
Definition at line \fB562\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.ConstructorInvokesConstructor ()"

.PP
Definition at line \fB1940\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.ExplicitCastNode_IdentifierToken ()"

.PP
Definition at line \fB400\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.ExplicitCastNode_KeywordToken ()"

.PP
Definition at line \fB413\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.Func_ImplicitInvocation_ManyParameter ()"

.PP
Definition at line \fB1533\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.Func_ImplicitInvocation_NoParameter ()"

.PP
Definition at line \fB1497\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.Func_ImplicitInvocation_SingleParameter ()"

.PP
Definition at line \fB1515\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.FunctionInvocation_NamedParameters ()"

.PP
Definition at line \fB1551\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.FunctionInvocationExpressionStatement ()"

.PP
This parses incorrectly: 'Func(decimalPercentProgress);'\&. Whereas this parses fine: 'var x = Func(decimalPercentProgress);'

.PP
The reason is suspected to be the transition from the 'statement' parser loop to the 'expression' parser loop\&.

.PP
It actually seems to be related to 'int decimalPercentProgress;', i\&.e\&.: declaring the variable results in it erroneously being interpreted as a \fBTypeClauseNode\fP, yet if it is undeclared then it comes out to be \fBVariableReferenceNode\fP\&. 
.PP
Definition at line \fB1999\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.FunctionInvocationNode_Basic ()"

.PP
Definition at line \fB424\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.FunctionInvocationNode_Generic ()"

.PP
Definition at line \fB464\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.FunctionInvocationNode_Generic_Parameters ()"

.PP
Definition at line \fB492\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.FunctionInvocationNode_Parameters ()"

.PP
Definition at line \fB440\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.FunctionParameter_OutKeyword ()"

.PP
Definition at line \fB1837\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.FunctionParameterOptional ()"

.PP
Definition at line \fB1890\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.GetterAndSetterThatAreNotAutoImplemented ()"

.PP
Definition at line \fB1596\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.GreaterThanBinaryOperator ()"

.PP
Definition at line \fB1857\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.GreaterThanEqualToBinaryOperator ()"

.PP
Definition at line \fB1879\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.IfStatement_StopExpressionsCreatingScope ()"

.PP
Definition at line \fB1662\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.LambdaFunction_CodeBlock_ManyParameter ()"

.PP
Definition at line \fB1412\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.LambdaFunction_CodeBlock_NoParameter_Async ()"

.PP
Definition at line \fB1386\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.LambdaFunction_CodeBlock_SingleParameter_Async ()"

.PP
Definition at line \fB1399\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.LambdaFunction_Expression_ManyParameter_Async ()"

.PP
Definition at line \fB1354\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.LambdaFunction_Expression_NoParameter ()"

.PP
Definition at line \fB1175\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.LambdaFunction_Expression_SingleParameter ()"

.PP
Definition at line \fB1188\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.LessThanBinaryOperator ()"

.PP
Definition at line \fB1846\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.LessThanEqualToBinaryOperator ()"

.PP
Definition at line \fB1868\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.MemberAccess ()"

.PP
Definition at line \fB1628\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.MethodGroup ()"

.PP
Definition at line \fB1425\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.Numeric_Add_BinaryExpressionNode ()"

.PP
Definition at line \fB39\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.Numeric_Add_BinaryExpressionNode_More ()"

.PP
Definition at line \fB65\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.Numeric_Division_BinaryExpressionNode ()"

.PP
Definition at line \fB178\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.Numeric_EqualsEquals_BinaryExpressionNode ()"

.PP
Definition at line \fB204\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.Numeric_Star_BinaryExpressionNode ()"

.PP
Definition at line \fB152\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.Numeric_Subtract_BinaryExpressionNode ()"

.PP
Definition at line \fB126\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.ObjectInitializationNode__Parameters_WithTrailingComma ()"

.PP
Definition at line \fB786\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.ObjectInitializationNode_NoParameters_NoTrailingComma ()"

.PP
Definition at line \fB834\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.ObjectInitializationNode_NoParameters_WithTrailingComma ()"

.PP
Definition at line \fB864\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.ObjectInitializationNode_Parameters_NoTrailingComma ()"

.PP
Definition at line \fB736\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.ObjectInitializationNode_WithParenthesis ()"

.PP
Definition at line \fB894\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.Parenthesized_ExplicitCast ()"

.PP
Definition at line \fB1828\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.ParenthesizedExpressionNode_Test ()"

.PP
Definition at line \fB356\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.Record_With_Keyword ()"

.PP
Definition at line \fB1587\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.ShortCircuit ()"

.PP
Definition at line \fB375\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.String_BinaryExpressionNode ()"

.PP
Definition at line \fB230\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.String_Interpolated ()"

.PP
Definition at line \fB256\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.String_InterpolatedVerbatim ()"

.PP
Definition at line \fB280\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.String_Verbatim ()"

.PP
Definition at line \fB268\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.String_VerbatimInterpolated ()"

.PP
Definition at line \fB292\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.SwitchExpression ()"

.PP
Definition at line \fB1810\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.SwitchStatement ()"

.PP
Definition at line \fB1720\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.TypeClauseNode_Generic ()"

.PP
Definition at line \fB2067\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.TypeClauseNode_GenericNullable ()"

.PP
Definition at line \fB2103\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.TypeClauseNode_Identifier ()"

.PP
Definition at line \fB2030\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.TypeClauseNode_Keyword ()"

.PP
Definition at line \fB2043\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.TypeClauseNode_Nullable_Identifier ()"

.PP
Definition at line \fB2091\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.TypeClauseNode_Nullable_Keyword ()"

.PP
Definition at line \fB2079\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.TypeClauseNode_Var ()"

.PP
Definition at line \fB2055\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.ValueTuple ()"

.PP
Definition at line \fB1960\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.VariableAssignmentExpressionNode ()"

.PP
Definition at line \fB2115\fP of file \fBExpressionTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionTests\&.WhileLoop_DoNotBreakScope ()"

.PP
TODO: Repeat this test for all the control keywords\&. 
.PP
Definition at line \fB1648\fP of file \fBExpressionTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
