.TH "Luthetus.Extensions.DotNet.ComponentRenderers.Models.IRemoveCSharpProjectFromSolutionRendererType" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.ComponentRenderers.Models.IRemoveCSharpProjectFromSolutionRendererType
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.Extensions\&.DotNet\&.CSharpProjects\&.Displays\&.RemoveCSharpProjectFromSolutionDisplay\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBIAbsolutePath\fP \fBAbsolutePath\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "Func< \fBIAbsolutePath\fP, Task > \fBOnAfterSubmitFunc\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBIRemoveCSharpProjectFromSolutionRendererType\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBIAbsolutePath\fP Luthetus\&.Extensions\&.DotNet\&.ComponentRenderers\&.Models\&.IRemoveCSharpProjectFromSolutionRendererType\&.AbsolutePath\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.Extensions\&.DotNet\&.CSharpProjects\&.Displays\&.RemoveCSharpProjectFromSolutionDisplay\fP\&.
.PP
Definition at line \fB7\fP of file \fBIRemoveCSharpProjectFromSolutionRendererType\&.cs\fP\&.
.SS "Func<\fBIAbsolutePath\fP, Task> Luthetus\&.Extensions\&.DotNet\&.ComponentRenderers\&.Models\&.IRemoveCSharpProjectFromSolutionRendererType\&.OnAfterSubmitFunc\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.Extensions\&.DotNet\&.CSharpProjects\&.Displays\&.RemoveCSharpProjectFromSolutionDisplay\fP\&.
.PP
Definition at line \fB8\fP of file \fBIRemoveCSharpProjectFromSolutionRendererType\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
