.TH "Luthetus.Extensions.DotNet.Websites.ProjectTemplates.Models.RazorClassLibFacts" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.Websites.ProjectTemplates.Models.RazorClassLibFacts
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBGetComponent1RazorContents\fP (string projectName)"
.br
.ti -1c
.RI "static string \fBGetComponent1RazorCssContents\fP (string projectName)"
.br
.ti -1c
.RI "static string \fBGetCsprojContents\fP (string projectName)"
.br
.ti -1c
.RI "static string \fBGetExampleJsInteropCsContents\fP (string projectName)"
.br
.ti -1c
.RI "static string \fBGetExampleJsInteropJsContents\fP (string projectName)"
.br
.ti -1c
.RI "static string \fBGetImportsRazorContents\fP (string projectName)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBCOMPONENT_1_RAZOR_RELATIVE_FILE_PATH\fP = @'Component1\&.razor'"
.br
.ti -1c
.RI "const string \fBCOMPONENT_1_RAZOR_CSS_RELATIVE_FILE_PATH\fP = @'Component1\&.razor\&.css'"
.br
.ti -1c
.RI "const string \fBEXAMPLE_JS_INTEROP_CS_RELATIVE_FILE_PATH\fP = @'ExampleJsInterop\&.cs'"
.br
.ti -1c
.RI "const string \fBEXAMPLE_JS_INTEROP_JS_RELATIVE_FILE_PATH\fP = @'wwwroot/ExampleJsInterop\&.js'"
.br
.ti -1c
.RI "const string \fBIMPORTS_RAZOR_RELATIVE_FILE_PATH\fP = @'_Imports\&.razor'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBRazorClassLibFacts\&.Component1Razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "string Luthetus\&.Extensions\&.DotNet\&.Websites\&.ProjectTemplates\&.Models\&.RazorClassLibFacts\&.GetComponent1RazorContents (string projectName)\fR [static]\fP"

.SS "string Luthetus\&.Extensions\&.DotNet\&.Websites\&.ProjectTemplates\&.Models\&.RazorClassLibFacts\&.GetComponent1RazorCssContents (string projectName)\fR [static]\fP"

.SS "string Luthetus\&.Extensions\&.DotNet\&.Websites\&.ProjectTemplates\&.Models\&.RazorClassLibFacts\&.GetCsprojContents (string projectName)\fR [static]\fP"

.SS "string Luthetus\&.Extensions\&.DotNet\&.Websites\&.ProjectTemplates\&.Models\&.RazorClassLibFacts\&.GetExampleJsInteropCsContents (string projectName)\fR [static]\fP"

.SS "string Luthetus\&.Extensions\&.DotNet\&.Websites\&.ProjectTemplates\&.Models\&.RazorClassLibFacts\&.GetExampleJsInteropJsContents (string projectName)\fR [static]\fP"

.SS "string Luthetus\&.Extensions\&.DotNet\&.Websites\&.ProjectTemplates\&.Models\&.RazorClassLibFacts\&.GetImportsRazorContents (string projectName)\fR [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "const string Luthetus\&.Extensions\&.DotNet\&.Websites\&.ProjectTemplates\&.Models\&.RazorClassLibFacts\&.COMPONENT_1_RAZOR_CSS_RELATIVE_FILE_PATH = @'Component1\&.razor\&.css'\fR [static]\fP"

.PP
Definition at line \fB5\fP of file \fBRazorClassLibFacts\&.Component1RazorCss\&.cs\fP\&.
.SS "const string Luthetus\&.Extensions\&.DotNet\&.Websites\&.ProjectTemplates\&.Models\&.RazorClassLibFacts\&.COMPONENT_1_RAZOR_RELATIVE_FILE_PATH = @'Component1\&.razor'\fR [static]\fP"

.PP
Definition at line \fB5\fP of file \fBRazorClassLibFacts\&.Component1Razor\&.cs\fP\&.
.SS "const string Luthetus\&.Extensions\&.DotNet\&.Websites\&.ProjectTemplates\&.Models\&.RazorClassLibFacts\&.EXAMPLE_JS_INTEROP_CS_RELATIVE_FILE_PATH = @'ExampleJsInterop\&.cs'\fR [static]\fP"

.PP
Definition at line \fB5\fP of file \fBRazorClassLibFacts\&.ExampleJsInteropCs\&.cs\fP\&.
.SS "const string Luthetus\&.Extensions\&.DotNet\&.Websites\&.ProjectTemplates\&.Models\&.RazorClassLibFacts\&.EXAMPLE_JS_INTEROP_JS_RELATIVE_FILE_PATH = @'wwwroot/ExampleJsInterop\&.js'\fR [static]\fP"

.PP
Definition at line \fB5\fP of file \fBRazorClassLibFacts\&.ExampleJsInteropJs\&.cs\fP\&.
.SS "const string Luthetus\&.Extensions\&.DotNet\&.Websites\&.ProjectTemplates\&.Models\&.RazorClassLibFacts\&.IMPORTS_RAZOR_RELATIVE_FILE_PATH = @'_Imports\&.razor'\fR [static]\fP"

.PP
Definition at line \fB5\fP of file \fBRazorClassLibFacts\&.ImportsRazor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
