.TH "Luthetus.Ide.RazorLib.Namespaces.Displays.TreeViewNamespacePathDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.Namespaces.Displays.TreeViewNamespacePathDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase, and \fBLuthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.ITreeViewNamespacePathRendererType\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "int? \fBLuthetusCommonIconWidthOverride\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int? \fBLuthetusCommonIconHeightOverride\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "NamespacePath \fBNamespacePath\fP = null!\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBCssStyleString\fP = string\&.Empty\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBWidthInPixels\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBHeightInPixels\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBTreeViewNamespacePathDisplay\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Luthetus\&.Ide\&.RazorLib\&.Namespaces\&.Displays\&.TreeViewNamespacePathDisplay\&.CssStyleString = string\&.Empty\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB22\fP of file \fBTreeViewNamespacePathDisplay\&.razor\&.cs\fP\&.
.SS "int Luthetus\&.Ide\&.RazorLib\&.Namespaces\&.Displays\&.TreeViewNamespacePathDisplay\&.HeightInPixels\fR [get]\fP"

.PP
Definition at line \fB27\fP of file \fBTreeViewNamespacePathDisplay\&.razor\&.cs\fP\&.
.SS "int? Luthetus\&.Ide\&.RazorLib\&.Namespaces\&.Displays\&.TreeViewNamespacePathDisplay\&.LuthetusCommonIconHeightOverride\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB17\fP of file \fBTreeViewNamespacePathDisplay\&.razor\&.cs\fP\&.
.SS "int? Luthetus\&.Ide\&.RazorLib\&.Namespaces\&.Displays\&.TreeViewNamespacePathDisplay\&.LuthetusCommonIconWidthOverride\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB15\fP of file \fBTreeViewNamespacePathDisplay\&.razor\&.cs\fP\&.
.SS "NamespacePath Luthetus\&.Ide\&.RazorLib\&.Namespaces\&.Displays\&.TreeViewNamespacePathDisplay\&.NamespacePath = null!\fR [get]\fP, \fR [set]\fP"

.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.ITreeViewNamespacePathRendererType\fP\&.
.PP
Definition at line \fB20\fP of file \fBTreeViewNamespacePathDisplay\&.razor\&.cs\fP\&.
.SS "int Luthetus\&.Ide\&.RazorLib\&.Namespaces\&.Displays\&.TreeViewNamespacePathDisplay\&.WidthInPixels\fR [get]\fP"

.PP
Definition at line \fB24\fP of file \fBTreeViewNamespacePathDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
