.TH "Luthetus.Common.Tests.Basis.Reactives.Models.ThrottleEventQueueTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Reactives.Models.ThrottleEventQueueTests \- ThrottleEventQueue  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBEnqueue\fP ()"
.br
.RI "ThrottleEventQueue\&.Enqueue(IBackgroundTask) 
.br
----
.br
 ThrottleEventQueue\&.Count ThrottleEventQueue\&.ThrottleEventList "
.ti -1c
.RI "void \fBDequeueOrDefault\fP ()"
.br
.RI "ThrottleEventQueue\&.DequeueOrDefault() 
.br
----
.br
 ThrottleEventQueue\&.Count ThrottleEventQueue\&.ThrottleEventList "
.in -1c
.SH "Detailed Description"
.PP 
ThrottleEventQueue 
.PP
Definition at line \fB6\fP of file \fBThrottleEventQueueTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Reactives\&.Models\&.ThrottleEventQueueTests\&.DequeueOrDefault ()"

.PP
ThrottleEventQueue\&.DequeueOrDefault() 
.br
----
.br
 ThrottleEventQueue\&.Count ThrottleEventQueue\&.ThrottleEventList 
.PP
Definition at line \fB27\fP of file \fBThrottleEventQueueTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Reactives\&.Models\&.ThrottleEventQueueTests\&.Enqueue ()"

.PP
ThrottleEventQueue\&.Enqueue(IBackgroundTask) 
.br
----
.br
 ThrottleEventQueue\&.Count ThrottleEventQueue\&.ThrottleEventList 
.PP
Definition at line \fB15\fP of file \fBThrottleEventQueueTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
