.TH "Luthetus.Ide.Tests.Basis.CodeSearches.States.CodeSearchStateActionsTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.Tests.Basis.CodeSearches.States.CodeSearchStateActionsTests \- \fBCodeSearchState\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBWithAction\fP ()"
.br
.RI "CodeSearchState\&.WithAction "
.ti -1c
.RI "void \fBAddResultAction\fP ()"
.br
.RI "CodeSearchState\&.AddResultAction "
.ti -1c
.RI "void \fBClearResultListAction\fP ()"
.br
.RI "CodeSearchState\&.ClearResultListAction "
.ti -1c
.RI "void \fBSearchEffect\fP ()"
.br
.RI "CodeSearchState\&.SearchEffect "
.in -1c
.SH "Detailed Description"
.PP 
\fBCodeSearchState\fP 
.PP
Definition at line \fB8\fP of file \fBCodeSearchStateActionsTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.CodeSearches\&.States\&.CodeSearchStateActionsTests\&.AddResultAction ()"

.PP
CodeSearchState\&.AddResultAction 
.PP
Definition at line \fB23\fP of file \fBCodeSearchStateActionsTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.CodeSearches\&.States\&.CodeSearchStateActionsTests\&.ClearResultListAction ()"

.PP
CodeSearchState\&.ClearResultListAction 
.PP
Definition at line \fB32\fP of file \fBCodeSearchStateActionsTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.CodeSearches\&.States\&.CodeSearchStateActionsTests\&.SearchEffect ()"

.PP
CodeSearchState\&.SearchEffect 
.PP
Definition at line \fB41\fP of file \fBCodeSearchStateActionsTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.CodeSearches\&.States\&.CodeSearchStateActionsTests\&.WithAction ()"

.PP
CodeSearchState\&.WithAction 
.PP
Definition at line \fB14\fP of file \fBCodeSearchStateActionsTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
