.TH "Luthetus.Common.Tests.Basis.Panels.Models.PanelTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Panels.Models.PanelTests \- \fBPanel\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "\fBPanel(Key<Panel>, ElementDimensions, ElementDimensions, Type, Type, string)\fP 
.br
----
.br
 Panel\&.IsBeingDragged Panel\&.ContextRecordKey "
.in -1c
.SH "Detailed Description"
.PP 
\fBPanel\fP 
.PP
Definition at line \fB10\fP of file \fBPanelTabTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Panels\&.Models\&.PanelTests\&.Constructor ()"

.PP
\fBPanel(Key<Panel>, ElementDimensions, ElementDimensions, Type, Type, string)\fP 
.br
----
.br
 Panel\&.IsBeingDragged Panel\&.ContextRecordKey 
.PP
Definition at line \fB19\fP of file \fBPanelTabTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
