.TH "Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxEnums" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxEnums
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBGenericSyntaxKind\fP { \fBCommentSingleLine\fP, \fBCommentMultiLine\fP, \fBStringLiteral\fP, \fBKeyword\fP, \fBFunction\fP, \fBDocument\fP, \fBPreprocessorDirective\fP, \fBDeliminationExtended\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxEnums\&.GenericSyntaxKind\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BICommentSingleLine \fP
.TP
\f(BICommentMultiLine \fP
.TP
\f(BIStringLiteral \fP
.TP
\f(BIKeyword \fP
.TP
\f(BIFunction \fP
.TP
\f(BIDocument \fP
.TP
\f(BIPreprocessorDirective \fP
.TP
\f(BIDeliminationExtended \fP
.PP
Definition at line \fB3\fP of file \fBGenericSyntaxKind\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
