.TH "Luthetus.Common.RazorLib.Menus.Models" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Menus.Models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMenuOptionCallbacks\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBMenuOptionKind\fP { \fBCreate\fP, \fBRead\fP, \fBUpdate\fP, \fBDelete\fP, \fBOther\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "record \fBMenuOptionRecord\fP (string DisplayName, \fBMenuOptionKind\fP \fBMenuOptionKind\fP, Func< Task >? OnClickFunc=null, \fBMenuRecord\fP? SubMenu=null, Type? WidgetRendererType=null, Dictionary< string, object?>? WidgetParameterMap=null)"
.br
.ti -1c
.RI "record \fBMenuRecord\fP (ImmutableArray< \fBMenuOptionRecord\fP > MenuOptionList)"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBLuthetus\&.Common\&.RazorLib\&.Menus\&.Models\&.MenuOptionKind\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BICreate \fP
.TP
\f(BIRead \fP
.TP
\f(BIUpdate \fP
.TP
\f(BIDelete \fP
.TP
\f(BIOther \fP
.PP
Definition at line \fB3\fP of file \fBMenuOptionKind\&.cs\fP\&.
.SH "Function Documentation"
.PP 
.SS "record Luthetus\&.Common\&.RazorLib\&.Menus\&.Models\&.MenuOptionRecord (string DisplayName, \fBMenuOptionKind\fP MenuOptionKind, Func< Task >? OnClickFunc = \fRnull\fP, \fBMenuRecord\fP? SubMenu = \fRnull\fP, Type? WidgetRendererType = \fRnull\fP, Dictionary< string, object?>? WidgetParameterMap = \fRnull\fP)"

.SS "record Luthetus\&.Common\&.RazorLib\&.Menus\&.Models\&.MenuRecord (ImmutableArray< \fBMenuOptionRecord\fP > MenuOptionList)"

.PP
Definition at line \fB5\fP of file \fBMenuRecord\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
