.TH "Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.CompilerServices\&.CSharp\&.BinderCase\&.CSharpBinder\fP, and \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Binder\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextEditorTextSpan\fP? \fBGetDefinition\fP (\fBTextEditorTextSpan\fP textSpan, \fBICompilerServiceResource\fP compilerServiceResource)"
.br
.ti -1c
.RI "\fBISyntaxNode\fP? \fBGetSyntaxNode\fP (int positionIndex, \fBCompilationUnit\fP compilationUnit)"
.br
.ti -1c
.RI "\fBIBinderSession\fP \fBStartBinderSession\fP (\fBResourceUri\fP resourceUri)"
.br
.RI "FinalizeBinderSession "
.ti -1c
.RI "void \fBFinalizeBinderSession\fP (\fBIBinderSession\fP binderSession)"
.br
.RI "StartBinderSession "
.ti -1c
.RI "bool \fBTryGetBinderSession\fP (\fBResourceUri\fP resourceUri, out \fBIBinderSession\fP binderSession)"
.br
.ti -1c
.RI "void \fBUpsertBinderSession\fP (\fBIBinderSession\fP binderSession)"
.br
.ti -1c
.RI "bool \fBRemoveBinderSession\fP (\fBResourceUri\fP resourceUri)"
.br
.RI "Returns true if the entry was removed\&. "
.ti -1c
.RI "\fBIScope\fP? \fBGetScope\fP (\fBTextEditorTextSpan\fP textSpan)"
.br
.ti -1c
.RI "\fBIScope\fP? \fBGetScopeByPositionIndex\fP (\fBResourceUri\fP resourceUri, int positionIndex)"
.br
.ti -1c
.RI "\fBIScope\fP? \fBGetScopeByScopeIndexKey\fP (\fBResourceUri\fP resourceUri, int scopeIndexKey)"
.br
.ti -1c
.RI "\fBIScope\fP?[] \fBGetScopeList\fP (\fBResourceUri\fP resourceUri)"
.br
.ti -1c
.RI "\fBTypeDefinitionNode\fP[] \fBGetTypeDefinitionNodesByScope\fP (\fBResourceUri\fP resourceUri, int scopeIndexKey)"
.br
.ti -1c
.RI "bool \fBTryGetTypeDefinitionNodeByScope\fP (\fBResourceUri\fP resourceUri, int scopeIndexKey, string typeIdentifierText, out \fBTypeDefinitionNode\fP typeDefinitionNode)"
.br
.ti -1c
.RI "bool \fBTryAddTypeDefinitionNodeByScope\fP (\fBResourceUri\fP resourceUri, int scopeIndexKey, string typeIdentifierText, \fBTypeDefinitionNode\fP typeDefinitionNode)"
.br
.ti -1c
.RI "void \fBSetTypeDefinitionNodeByScope\fP (\fBResourceUri\fP resourceUri, int scopeIndexKey, string typeIdentifierText, \fBTypeDefinitionNode\fP typeDefinitionNode)"
.br
.ti -1c
.RI "\fBFunctionDefinitionNode\fP[] \fBGetFunctionDefinitionNodesByScope\fP (\fBResourceUri\fP resourceUri, int scopeIndexKey)"
.br
.ti -1c
.RI "bool \fBTryGetFunctionDefinitionNodeByScope\fP (\fBResourceUri\fP resourceUri, int scopeIndexKey, string functionIdentifierText, out \fBFunctionDefinitionNode\fP functionDefinitionNode)"
.br
.ti -1c
.RI "bool \fBTryAddFunctionDefinitionNodeByScope\fP (\fBResourceUri\fP resourceUri, int scopeIndexKey, string functionIdentifierText, \fBFunctionDefinitionNode\fP functionDefinitionNode)"
.br
.ti -1c
.RI "void \fBSetFunctionDefinitionNodeByScope\fP (\fBResourceUri\fP resourceUri, int scopeIndexKey, string functionIdentifierText, \fBFunctionDefinitionNode\fP functionDefinitionNode)"
.br
.ti -1c
.RI "\fBIVariableDeclarationNode\fP[] \fBGetVariableDeclarationNodesByScope\fP (\fBResourceUri\fP resourceUri, int scopeIndexKey)"
.br
.ti -1c
.RI "bool \fBTryGetVariableDeclarationNodeByScope\fP (\fBResourceUri\fP resourceUri, int scopeIndexKey, string variableIdentifierText, out \fBIVariableDeclarationNode\fP variableDeclarationNode)"
.br
.ti -1c
.RI "bool \fBTryAddVariableDeclarationNodeByScope\fP (\fBResourceUri\fP resourceUri, int scopeIndexKey, string variableIdentifierText, \fBIVariableDeclarationNode\fP variableDeclarationNode)"
.br
.ti -1c
.RI "void \fBSetVariableDeclarationNodeByScope\fP (\fBResourceUri\fP resourceUri, int scopeIndexKey, string variableIdentifierText, \fBIVariableDeclarationNode\fP variableDeclarationNode)"
.br
.ti -1c
.RI "\fBTypeClauseNode\fP? \fBGetReturnTypeClauseNodeByScope\fP (\fBResourceUri\fP resourceUri, int scopeIndexKey)"
.br
.ti -1c
.RI "bool \fBTryAddReturnTypeClauseNodeByScope\fP (\fBResourceUri\fP resourceUri, int scopeIndexKey, \fBTypeClauseNode\fP typeClauseNode)"
.br
.ti -1c
.RI "void \fBClearStateByResourceUri\fP (\fBResourceUri\fP resourceUri)"
.br
.ti -1c
.RI "void \fBAddNamespaceToCurrentScope\fP (string namespaceString, \fBIParserModel\fP model)"
.br
.ti -1c
.RI "void \fBBindFunctionOptionalArgument\fP (\fBFunctionArgumentEntryNode\fP functionArgumentEntryNode, \fBIParserModel\fP model)"
.br
.ti -1c
.RI "void \fBBindVariableDeclarationNode\fP (\fBIVariableDeclarationNode\fP variableDeclarationNode, \fBIParserModel\fP model)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "ImmutableArray< \fBTextEditorDiagnostic\fP > \fBDiagnosticsList\fP\fR [get]\fP"
.br
.ti -1c
.RI "ImmutableArray< \fBITextEditorSymbol\fP > \fBSymbolsList\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBIBinder\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IBinder\&.AddNamespaceToCurrentScope (string namespaceString, \fBIParserModel\fP model)"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Binder\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IBinder\&.BindFunctionOptionalArgument (\fBFunctionArgumentEntryNode\fP functionArgumentEntryNode, \fBIParserModel\fP model)"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Binder\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IBinder\&.BindVariableDeclarationNode (\fBIVariableDeclarationNode\fP variableDeclarationNode, \fBIParserModel\fP model)"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Binder\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IBinder\&.ClearStateByResourceUri (\fBResourceUri\fP resourceUri)"

.PP
Implemented in \fBLuthetus\&.CompilerServices\&.CSharp\&.BinderCase\&.CSharpBinder\fP, and \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Binder\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IBinder\&.FinalizeBinderSession (\fBIBinderSession\fP binderSession)"

.PP
StartBinderSession 
.PP
Implemented in \fBLuthetus\&.CompilerServices\&.CSharp\&.BinderCase\&.CSharpBinder\fP, and \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Binder\fP\&.
.SS "\fBTextEditorTextSpan\fP? Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IBinder\&.GetDefinition (\fBTextEditorTextSpan\fP textSpan, \fBICompilerServiceResource\fP compilerServiceResource)"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Binder\fP\&.
.SS "\fBFunctionDefinitionNode\fP[] Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IBinder\&.GetFunctionDefinitionNodesByScope (\fBResourceUri\fP resourceUri, int scopeIndexKey)"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Binder\fP\&.
.SS "\fBTypeClauseNode\fP? Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IBinder\&.GetReturnTypeClauseNodeByScope (\fBResourceUri\fP resourceUri, int scopeIndexKey)"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Binder\fP\&.
.SS "\fBIScope\fP? Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IBinder\&.GetScope (\fBTextEditorTextSpan\fP textSpan)"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Binder\fP\&.
.SS "\fBIScope\fP? Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IBinder\&.GetScopeByPositionIndex (\fBResourceUri\fP resourceUri, int positionIndex)"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Binder\fP\&.
.SS "\fBIScope\fP? Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IBinder\&.GetScopeByScopeIndexKey (\fBResourceUri\fP resourceUri, int scopeIndexKey)"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Binder\fP\&.
.SS "\fBIScope\fP?[] Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IBinder\&.GetScopeList (\fBResourceUri\fP resourceUri)"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Binder\fP\&.
.SS "\fBISyntaxNode\fP? Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IBinder\&.GetSyntaxNode (int positionIndex, \fBCompilationUnit\fP compilationUnit)"

.PP
Implemented in \fBLuthetus\&.CompilerServices\&.CSharp\&.BinderCase\&.CSharpBinder\fP, and \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Binder\fP\&.
.SS "\fBTypeDefinitionNode\fP[] Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IBinder\&.GetTypeDefinitionNodesByScope (\fBResourceUri\fP resourceUri, int scopeIndexKey)"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Binder\fP\&.
.SS "\fBIVariableDeclarationNode\fP[] Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IBinder\&.GetVariableDeclarationNodesByScope (\fBResourceUri\fP resourceUri, int scopeIndexKey)"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Binder\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IBinder\&.RemoveBinderSession (\fBResourceUri\fP resourceUri)"

.PP
Returns true if the entry was removed\&. 
.PP
Implemented in \fBLuthetus\&.CompilerServices\&.CSharp\&.BinderCase\&.CSharpBinder\fP, and \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Binder\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IBinder\&.SetFunctionDefinitionNodeByScope (\fBResourceUri\fP resourceUri, int scopeIndexKey, string functionIdentifierText, \fBFunctionDefinitionNode\fP functionDefinitionNode)"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Binder\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IBinder\&.SetTypeDefinitionNodeByScope (\fBResourceUri\fP resourceUri, int scopeIndexKey, string typeIdentifierText, \fBTypeDefinitionNode\fP typeDefinitionNode)"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Binder\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IBinder\&.SetVariableDeclarationNodeByScope (\fBResourceUri\fP resourceUri, int scopeIndexKey, string variableIdentifierText, \fBIVariableDeclarationNode\fP variableDeclarationNode)"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Binder\fP\&.
.SS "\fBIBinderSession\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IBinder\&.StartBinderSession (\fBResourceUri\fP resourceUri)"

.PP
FinalizeBinderSession 
.PP
Implemented in \fBLuthetus\&.CompilerServices\&.CSharp\&.BinderCase\&.CSharpBinder\fP, and \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Binder\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IBinder\&.TryAddFunctionDefinitionNodeByScope (\fBResourceUri\fP resourceUri, int scopeIndexKey, string functionIdentifierText, \fBFunctionDefinitionNode\fP functionDefinitionNode)"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Binder\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IBinder\&.TryAddReturnTypeClauseNodeByScope (\fBResourceUri\fP resourceUri, int scopeIndexKey, \fBTypeClauseNode\fP typeClauseNode)"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Binder\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IBinder\&.TryAddTypeDefinitionNodeByScope (\fBResourceUri\fP resourceUri, int scopeIndexKey, string typeIdentifierText, \fBTypeDefinitionNode\fP typeDefinitionNode)"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Binder\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IBinder\&.TryAddVariableDeclarationNodeByScope (\fBResourceUri\fP resourceUri, int scopeIndexKey, string variableIdentifierText, \fBIVariableDeclarationNode\fP variableDeclarationNode)"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Binder\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IBinder\&.TryGetBinderSession (\fBResourceUri\fP resourceUri, out \fBIBinderSession\fP binderSession)"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Binder\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IBinder\&.TryGetFunctionDefinitionNodeByScope (\fBResourceUri\fP resourceUri, int scopeIndexKey, string functionIdentifierText, out \fBFunctionDefinitionNode\fP functionDefinitionNode)"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Binder\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IBinder\&.TryGetTypeDefinitionNodeByScope (\fBResourceUri\fP resourceUri, int scopeIndexKey, string typeIdentifierText, out \fBTypeDefinitionNode\fP typeDefinitionNode)"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Binder\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IBinder\&.TryGetVariableDeclarationNodeByScope (\fBResourceUri\fP resourceUri, int scopeIndexKey, string variableIdentifierText, out \fBIVariableDeclarationNode\fP variableDeclarationNode)"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Binder\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IBinder\&.UpsertBinderSession (\fBIBinderSession\fP binderSession)"

.PP
Implemented in \fBLuthetus\&.CompilerServices\&.CSharp\&.BinderCase\&.CSharpBinder\fP, and \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Binder\fP\&.
.SH "Property Documentation"
.PP 
.SS "ImmutableArray<\fBTextEditorDiagnostic\fP> Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IBinder\&.DiagnosticsList\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.CompilerServices\&.CSharp\&.BinderCase\&.CSharpBinder\fP, and \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Binder\fP\&.
.PP
Definition at line \fB12\fP of file \fBIBinder\&.cs\fP\&.
.SS "ImmutableArray<\fBITextEditorSymbol\fP> Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IBinder\&.SymbolsList\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Binder\fP\&.
.PP
Definition at line \fB13\fP of file \fBIBinder\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
