.TH "Luthetus.Extensions.DotNet.TestExplorers.Displays.TestExplorerDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.TestExplorers.Displays.TestExplorerDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits FluxorComponent\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInitialized\fP ()"
.br
.ti -1c
.RI "override async Task \fBOnAfterRenderAsync\fP (bool firstRender)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB24\fP of file \fBTestExplorerDisplay\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override async Task Luthetus\&.Extensions\&.DotNet\&.TestExplorers\&.Displays\&.TestExplorerDisplay\&.OnAfterRenderAsync (bool firstRender)\fR [protected]\fP"

.PP
Definition at line \fB56\fP of file \fBTestExplorerDisplay\&.razor\&.cs\fP\&.
.SS "override void Luthetus\&.Extensions\&.DotNet\&.TestExplorers\&.Displays\&.TestExplorerDisplay\&.OnInitialized ()\fR [protected]\fP"

.PP
Definition at line \fB45\fP of file \fBTestExplorerDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
