.TH "Luthetus.Common.RazorLib.Notifications.Models.INotificationService" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Notifications.Models.INotificationService \- TODO: SphagettiCode - Not all NotificationState Actions are mapped to a public method (2023-09-19) on this service\&. Furthermore, NotificationState itself is sphagetti code\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.Common\&.RazorLib\&.Notifications\&.Models\&.NotificationService\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRegisterNotificationRecord\fP (\fBINotification\fP notification)"
.br
.ti -1c
.RI "void \fBDisposeNotificationRecord\fP (Key< \fBIDynamicViewModel\fP > dynamicViewModelKey)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IState< \fBNotificationState\fP > \fBNotificationStateWrap\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
TODO: SphagettiCode - Not all NotificationState Actions are mapped to a public method (2023-09-19) on this service\&. Furthermore, NotificationState itself is sphagetti code\&. 
.PP
Definition at line \fB12\fP of file \fBINotificationService\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.RazorLib\&.Notifications\&.Models\&.INotificationService\&.DisposeNotificationRecord (Key< \fBIDynamicViewModel\fP > dynamicViewModelKey)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Notifications\&.Models\&.NotificationService\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.Notifications\&.Models\&.INotificationService\&.RegisterNotificationRecord (\fBINotification\fP notification)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Notifications\&.Models\&.NotificationService\fP\&.
.SH "Property Documentation"
.PP 
.SS "IState<\fBNotificationState\fP> Luthetus\&.Common\&.RazorLib\&.Notifications\&.Models\&.INotificationService\&.NotificationStateWrap\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Notifications\&.Models\&.NotificationService\fP\&.
.PP
Definition at line \fB14\fP of file \fBINotificationService\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
