.TH "Luthetus.Common.RazorLib.Dropdowns.Models" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Dropdowns.Models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDropdownHelper\fP"
.br
.ti -1c
.RI "class \fBDropdownService\fP"
.br
.ti -1c
.RI "interface \fBIDropdownService\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBDropdownOrientation\fP { \fBBottom\fP, \fBRight\fP }"
.br
.RI "Right: The dropdown will be rendered such that the left edge of the dropdown is aligned on the right edge of the anchor html element\&.
.br

.br
\&. "
.ti -1c
.RI "enum \fBDropdownPositionKind\fP { \fBVertical\fP, \fBHorizontal\fP, \fBUnset\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBLuthetus\&.Common\&.RazorLib\&.Dropdowns\&.Models\&.DropdownOrientation\fP"

.PP
Right: The dropdown will be rendered such that the left edge of the dropdown is aligned on the right edge of the anchor html element\&.
.br

.br
\&. Bottom: The dropdown will be rendered such that the top edge of the dropdown is aligned on the bottom edge of the anchor html element\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIBottom \fP
.TP
\f(BIRight \fP
.PP
Definition at line \fB10\fP of file \fBDropdownOrientation\&.cs\fP\&.
.SS "enum \fBLuthetus\&.Common\&.RazorLib\&.Dropdowns\&.Models\&.DropdownPositionKind\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIVertical \fP
.TP
\f(BIHorizontal \fP
.TP
\f(BIUnset \fP
.PP
Definition at line \fB3\fP of file \fBDropdownPositionKind\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
