.TH "Luthetus.CompilerServices.Css.SyntaxActors.CssSyntaxWalker" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.Css.SyntaxActors.CssSyntaxWalker
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBVisit\fP (\fBICssSyntax\fP cssSyntax)"
.br
.ti -1c
.RI "virtual void \fBVisitCssIdentifierSyntax\fP (\fBCssIdentifierSyntax\fP cssIdentifierSyntax)"
.br
.ti -1c
.RI "virtual void \fBVisitCssCommentSyntax\fP (\fBCssCommentSyntax\fP cssCommentSyntax)"
.br
.ti -1c
.RI "virtual void \fBVisitCssPropertyNameSyntax\fP (\fBCssPropertyNameSyntax\fP cssPropertyNameSyntax)"
.br
.ti -1c
.RI "virtual void \fBVisitCssPropertyValueSyntax\fP (\fBCssPropertyValueSyntax\fP cssPropertyValueSyntax)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "List< \fBCssIdentifierSyntax\fP > \fBIdentifierSyntaxes\fP = new()\fR [get]\fP"
.br
.ti -1c
.RI "List< \fBCssCommentSyntax\fP > \fBCommentSyntaxes\fP = new()\fR [get]\fP"
.br
.ti -1c
.RI "List< \fBCssPropertyNameSyntax\fP > \fBPropertyNameSyntaxes\fP = new()\fR [get]\fP"
.br
.ti -1c
.RI "List< \fBCssPropertyValueSyntax\fP > \fBPropertyValueSyntaxes\fP = new()\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBCssSyntaxWalker\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.CompilerServices\&.Css\&.SyntaxActors\&.CssSyntaxWalker\&.Visit (\fBICssSyntax\fP cssSyntax)"

.PP
Definition at line \fB13\fP of file \fBCssSyntaxWalker\&.cs\fP\&.
.SS "virtual void Luthetus\&.CompilerServices\&.Css\&.SyntaxActors\&.CssSyntaxWalker\&.VisitCssCommentSyntax (\fBCssCommentSyntax\fP cssCommentSyntax)\fR [virtual]\fP"

.PP
Definition at line \fB40\fP of file \fBCssSyntaxWalker\&.cs\fP\&.
.SS "virtual void Luthetus\&.CompilerServices\&.Css\&.SyntaxActors\&.CssSyntaxWalker\&.VisitCssIdentifierSyntax (\fBCssIdentifierSyntax\fP cssIdentifierSyntax)\fR [virtual]\fP"

.PP
Definition at line \fB35\fP of file \fBCssSyntaxWalker\&.cs\fP\&.
.SS "virtual void Luthetus\&.CompilerServices\&.Css\&.SyntaxActors\&.CssSyntaxWalker\&.VisitCssPropertyNameSyntax (\fBCssPropertyNameSyntax\fP cssPropertyNameSyntax)\fR [virtual]\fP"

.PP
Definition at line \fB45\fP of file \fBCssSyntaxWalker\&.cs\fP\&.
.SS "virtual void Luthetus\&.CompilerServices\&.Css\&.SyntaxActors\&.CssSyntaxWalker\&.VisitCssPropertyValueSyntax (\fBCssPropertyValueSyntax\fP cssPropertyValueSyntax)\fR [virtual]\fP"

.PP
Definition at line \fB50\fP of file \fBCssSyntaxWalker\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "List<\fBCssCommentSyntax\fP> Luthetus\&.CompilerServices\&.Css\&.SyntaxActors\&.CssSyntaxWalker\&.CommentSyntaxes = new()\fR [get]\fP"

.PP
Definition at line \fB9\fP of file \fBCssSyntaxWalker\&.cs\fP\&.
.SS "List<\fBCssIdentifierSyntax\fP> Luthetus\&.CompilerServices\&.Css\&.SyntaxActors\&.CssSyntaxWalker\&.IdentifierSyntaxes = new()\fR [get]\fP"

.PP
Definition at line \fB8\fP of file \fBCssSyntaxWalker\&.cs\fP\&.
.SS "List<\fBCssPropertyNameSyntax\fP> Luthetus\&.CompilerServices\&.Css\&.SyntaxActors\&.CssSyntaxWalker\&.PropertyNameSyntaxes = new()\fR [get]\fP"

.PP
Definition at line \fB10\fP of file \fBCssSyntaxWalker\&.cs\fP\&.
.SS "List<\fBCssPropertyValueSyntax\fP> Luthetus\&.CompilerServices\&.Css\&.SyntaxActors\&.CssSyntaxWalker\&.PropertyValueSyntaxes = new()\fR [get]\fP"

.PP
Definition at line \fB11\fP of file \fBCssSyntaxWalker\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
