.TH "Luthetus.Extensions.DotNet.Outputs.Displays.Internals.OutputDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.Outputs.Displays.Internals.OutputDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase, and IDisposable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDotNetCliOutputParser_StateChanged\fP ()"
.br
.ti -1c
.RI "async void \fBOutputStateWrap_StateChanged\fP (object? sender, EventArgs e)"
.br
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInitialized\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB19\fP of file \fBOutputDisplay\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Extensions\&.DotNet\&.Outputs\&.Displays\&.Internals\&.OutputDisplay\&.Dispose ()"

.PP
Definition at line \fB112\fP of file \fBOutputDisplay\&.razor\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.DotNet\&.Outputs\&.Displays\&.Internals\&.OutputDisplay\&.DotNetCliOutputParser_StateChanged ()"

.PP
Definition at line \fB75\fP of file \fBOutputDisplay\&.razor\&.cs\fP\&.
.SS "override void Luthetus\&.Extensions\&.DotNet\&.Outputs\&.Displays\&.Internals\&.OutputDisplay\&.OnInitialized ()\fR [protected]\fP"

.PP
Definition at line \fB50\fP of file \fBOutputDisplay\&.razor\&.cs\fP\&.
.SS "async void Luthetus\&.Extensions\&.DotNet\&.Outputs\&.Displays\&.Internals\&.OutputDisplay\&.OutputStateWrap_StateChanged (object? sender, EventArgs e)"

.PP
Definition at line \fB87\fP of file \fBOutputDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
