.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.TokenFactoryTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.TokenFactoryTests \- TokenFactory  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBFabricateToken\fP ()"
.br
.RI "TokenFactory\&.FabricateToken(TokenWalker, SyntaxKind) "
.in -1c
.SH "Detailed Description"
.PP 
TokenFactory 
.PP
Definition at line \fB9\fP of file \fBTokenFactoryTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.Syntax\&.TokenFactoryTests\&.FabricateToken ()"

.PP
TokenFactory\&.FabricateToken(TokenWalker, SyntaxKind) 
.PP
Definition at line \fB15\fP of file \fBTokenFactoryTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
