.TH "Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TestConstants" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TestConstants
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBSOURCE_TEXT\fP = 'Hello World!\\n7 Pillows\\n \\n,abc123'"
.br
.RI "This sample text is used for testing\&. 
.br

.br
 It contains separate lines that start with letter, digit, whitespace, and punctuation Similarly, separate lines that end with punctuation, letter, whitespace, digit\&. 
.br

.br
 Note: there is a line which contains only a space character, this note is here to try to avoid confusion if one does not see it\&. 
.br

.br
 Do not use a verbatim string here, it will use operating system dependent line endings, which then cannot be asserted in the unit tests\&. "
.ti -1c
.RI "const int \fBNEGATIVE_ROW_INDEX\fP = \-4"
.br
.ti -1c
.RI "const int \fBFIRST_ROW_INDEX\fP = 0"
.br
.ti -1c
.RI "const int \fBROW_INDEX_WHICH_IS_BETWEEN_FIRST_AND_LAST_ROW\fP = 1"
.br
.ti -1c
.RI "const int \fBLAST_ROW_INDEX\fP = 3"
.br
.ti -1c
.RI "const int \fBLARGE_OUT_OF_BOUNDS_ROW_INDEX\fP = 5"
.br
.ti -1c
.RI "const int \fBROW_COUNT\fP = 4"
.br
.ti -1c
.RI "const int \fBLENGTH_OF_FIRST_ROW\fP = 12"
.br
.ti -1c
.RI "const int \fBLENGTH_OF_ROW_WHICH_IS_BETWEEN_FIRST_AND_LAST_ROW\fP = 9"
.br
.ti -1c
.RI "const int \fBLENGTH_OF_LAST_ROW\fP = 7"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBTestConstants\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const int Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TestConstants\&.FIRST_ROW_INDEX = 0\fR [static]\fP"

.PP
Definition at line \fB20\fP of file \fBTestConstants\&.cs\fP\&.
.SS "const int Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TestConstants\&.LARGE_OUT_OF_BOUNDS_ROW_INDEX = 5\fR [static]\fP"

.PP
Definition at line \fB23\fP of file \fBTestConstants\&.cs\fP\&.
.SS "const int Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TestConstants\&.LAST_ROW_INDEX = 3\fR [static]\fP"

.PP
Definition at line \fB22\fP of file \fBTestConstants\&.cs\fP\&.
.SS "const int Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TestConstants\&.LENGTH_OF_FIRST_ROW = 12\fR [static]\fP"

.PP
Definition at line \fB25\fP of file \fBTestConstants\&.cs\fP\&.
.SS "const int Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TestConstants\&.LENGTH_OF_LAST_ROW = 7\fR [static]\fP"

.PP
Definition at line \fB27\fP of file \fBTestConstants\&.cs\fP\&.
.SS "const int Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TestConstants\&.LENGTH_OF_ROW_WHICH_IS_BETWEEN_FIRST_AND_LAST_ROW = 9\fR [static]\fP"

.PP
Definition at line \fB26\fP of file \fBTestConstants\&.cs\fP\&.
.SS "const int Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TestConstants\&.NEGATIVE_ROW_INDEX = \-4\fR [static]\fP"

.PP
Definition at line \fB19\fP of file \fBTestConstants\&.cs\fP\&.
.SS "const int Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TestConstants\&.ROW_COUNT = 4\fR [static]\fP"

.PP
Definition at line \fB24\fP of file \fBTestConstants\&.cs\fP\&.
.SS "const int Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TestConstants\&.ROW_INDEX_WHICH_IS_BETWEEN_FIRST_AND_LAST_ROW = 1\fR [static]\fP"

.PP
Definition at line \fB21\fP of file \fBTestConstants\&.cs\fP\&.
.SS "const string Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TestConstants\&.SOURCE_TEXT = 'Hello World!\\n7 Pillows\\n \\n,abc123'\fR [static]\fP"

.PP
This sample text is used for testing\&. 
.br

.br
 It contains separate lines that start with letter, digit, whitespace, and punctuation Similarly, separate lines that end with punctuation, letter, whitespace, digit\&. 
.br

.br
 Note: there is a line which contains only a space character, this note is here to try to avoid confusion if one does not see it\&. 
.br

.br
 Do not use a verbatim string here, it will use operating system dependent line endings, which then cannot be asserted in the unit tests\&. 
.PP
Definition at line \fB17\fP of file \fBTestConstants\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
