.TH "Luthetus.Common.RazorLib.Dynamics.Models.IDynamicViewModel" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Dynamics.Models.IDynamicViewModel
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDialog\fP, \fBLuthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDrag\fP, \fBLuthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.INotification\fP, and \fBLuthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.ITab\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly string \fBDefaultSetFocusOnCloseElementId\fP = ContextFacts\&.GlobalContext\&.ContextElementId"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Key< \fBIDynamicViewModel\fP > \fBDynamicViewModelKey\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBTitle\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBTitleVerbose\fP\fR [get]\fP"
.br
.ti -1c
.RI "Type \fBComponentType\fP\fR [get]\fP"
.br
.ti -1c
.RI "Dictionary< string, object?>? \fBComponentParameterMap\fP\fR [get]\fP"
.br
.ti -1c
.RI "string? \fBSetFocusOnCloseElementId\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBIDynamicViewModel\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly string Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDynamicViewModel\&.DefaultSetFocusOnCloseElementId = ContextFacts\&.GlobalContext\&.ContextElementId\fR [static]\fP"

.PP
Definition at line \fB15\fP of file \fBIDynamicViewModel\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Dictionary<string, object?>? Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDynamicViewModel\&.ComponentParameterMap\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Notifications\&.Models\&.NotificationViewModel\fP, and \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.DynamicViewModelAdapterTextEditor\fP\&.
.PP
Definition at line \fB12\fP of file \fBIDynamicViewModel\&.cs\fP\&.
.SS "Type Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDynamicViewModel\&.ComponentType\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Notifications\&.Models\&.NotificationViewModel\fP, and \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.DynamicViewModelAdapterTextEditor\fP\&.
.PP
Definition at line \fB11\fP of file \fBIDynamicViewModel\&.cs\fP\&.
.SS "Key<\fBIDynamicViewModel\fP> Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDynamicViewModel\&.DynamicViewModelKey\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Notifications\&.Models\&.NotificationViewModel\fP, and \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.DynamicViewModelAdapterTextEditor\fP\&.
.PP
Definition at line \fB8\fP of file \fBIDynamicViewModel\&.cs\fP\&.
.SS "string? Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDynamicViewModel\&.SetFocusOnCloseElementId\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Notifications\&.Models\&.NotificationViewModel\fP, and \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.DynamicViewModelAdapterTextEditor\fP\&.
.PP
Definition at line \fB13\fP of file \fBIDynamicViewModel\&.cs\fP\&.
.SS "string Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDynamicViewModel\&.Title\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Notifications\&.Models\&.NotificationViewModel\fP, and \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.DynamicViewModelAdapterTextEditor\fP\&.
.PP
Definition at line \fB9\fP of file \fBIDynamicViewModel\&.cs\fP\&.
.SS "string Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDynamicViewModel\&.TitleVerbose\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Notifications\&.Models\&.NotificationViewModel\fP, and \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.DynamicViewModelAdapterTextEditor\fP\&.
.PP
Definition at line \fB10\fP of file \fBIDynamicViewModel\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
