.TH "Source/Lib/Common/Installations/Models/LuthetusHostingInformation.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Common/Installations/Models/LuthetusHostingInformation.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\&.Installations\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\&.Installations\&.Models\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "record \fBLuthetus\&.Common\&.RazorLib\&.Installations\&.Models\&.LuthetusHostingInformation\fP"
.br
.RI "One use case for \fBLuthetusHostingInformation\fP would be service registration\&.
.br

.br
 If one uses \fBLuthetusHostingKind\&.ServerSide\fP, then services\&.AddHostedService<TService>(\&.\&.\&.); will be invoked\&.
.br

.br
 Whereas, if one uses \fBLuthetusHostingKind\&.Wasm\fP then services\&.AddSingleton<TService>(\&.\&.\&.); will be used\&. Then after the initial render, a Task will be 'fire and forget' invoked to start the service\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
