.TH "Luthetus.TextEditor.RazorLib.FindAlls.Models.FindAllTreeViewMouseEventHandler" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.FindAlls.Models.FindAllTreeViewMouseEventHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewMouseEventHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFindAllTreeViewMouseEventHandler\fP (\fBITextEditorService\fP \fBtextEditorService\fP, \fBLuthetusTextEditorConfig\fP textEditorConfig, IServiceProvider serviceProvider, \fBITreeViewService\fP treeViewService, \fBIBackgroundTaskService\fP backgroundTaskService)"
.br
.ti -1c
.RI "override Task \fBOnDoubleClickAsync\fP (\fBTreeViewCommandArgs\fP commandArgs)"
.br
.RI "Invoked, and awaited, as part of the async UI event handler for 'ondblclick' events\&.
.br

.br
\&. "
.in -1c

Public Member Functions inherited from \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewMouseEventHandler\fP
.in +1c
.ti -1c
.RI "\fBTreeViewMouseEventHandler\fP (\fBITreeViewService\fP treeViewService, \fBIBackgroundTaskService\fP backgroundTaskService)"
.br
.ti -1c
.RI "virtual Task \fBOnClickAsync\fP (\fBTreeViewCommandArgs\fP commandArgs)"
.br
.RI "Invoked, and awaited, as part of the async UI event handler for 'onclick' events\&.
.br

.br
\&. "
.ti -1c
.RI "virtual Task \fBOnMouseDownAsync\fP (\fBTreeViewCommandArgs\fP commandArgs)"
.br
.RI "Invoked, and awaited, as part of the async UI event handler for 'onmousedown' events\&.
.br

.br
\&. "
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewMouseEventHandler\fP
.in +1c
.ti -1c
.RI "virtual void \fBOnClick\fP (\fBTreeViewCommandArgs\fP commandArgs)"
.br
.RI "Invoked, and awaited, as part of the synchronous UI event handler for 'onclick' events\&.
.br

.br
\&. "
.ti -1c
.RI "virtual void \fBOnDoubleClick\fP (\fBTreeViewCommandArgs\fP commandArgs)"
.br
.RI "Invoked, and awaited, as part of the synchronous UI event handler for 'ondblclick' events\&.
.br

.br
\&. "
.ti -1c
.RI "virtual void \fBOnMouseDown\fP (\fBTreeViewCommandArgs\fP commandArgs)"
.br
.RI "Invoked, and awaited, as part of the synchronous UI event handler for 'onmousedown' events\&.
.br

.br
\&. "
.in -1c

Protected Attributes inherited from \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewMouseEventHandler\fP
.in +1c
.ti -1c
.RI "readonly \fBITreeViewService\fP \fBTreeViewService\fP"
.br
.ti -1c
.RI "readonly \fBIBackgroundTaskService\fP \fBBackgroundTaskService\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBFindAllTreeViewMouseEventHandler\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.FindAlls\&.Models\&.FindAllTreeViewMouseEventHandler\&.FindAllTreeViewMouseEventHandler (\fBITextEditorService\fP textEditorService, \fBLuthetusTextEditorConfig\fP textEditorConfig, IServiceProvider serviceProvider, \fBITreeViewService\fP treeViewService, \fBIBackgroundTaskService\fP backgroundTaskService)"

.PP
Definition at line \fB16\fP of file \fBFindAllTreeViewMouseEventHandler\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override Task Luthetus\&.TextEditor\&.RazorLib\&.FindAlls\&.Models\&.FindAllTreeViewMouseEventHandler\&.OnDoubleClickAsync (\fBTreeViewCommandArgs\fP commandArgs)\fR [virtual]\fP"

.PP
Invoked, and awaited, as part of the async UI event handler for 'ondblclick' events\&.
.br

.br
\&. The synchronous version: 'OnDoubleClick(TreeViewCommandArgs)' will be invoked immediately from within this method, to allow the synchronous code to block the UI purposefully\&.

.PP
Any overrides of this method are intended to have 'base\&.MethodBeingOverridden()' prior to their code\&.
.br

.br
 
.PP
Reimplemented from \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewMouseEventHandler\fP\&.
.PP
Definition at line \fB29\fP of file \fBFindAllTreeViewMouseEventHandler\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
