.TH "Luthetus.Extensions.DotNet.Commands.DotNetCommandFactory" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.Commands.DotNetCommandFactory
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Extensions\&.DotNet\&.Commands\&.IDotNetCommandFactory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDotNetCommandFactory\fP (\fBITextEditorService\fP \fBtextEditorService\fP, \fBITreeViewService\fP treeViewService, \fBIEnvironmentProvider\fP environmentProvider, IJSRuntime \fBjsRuntime\fP, IDispatcher \fBdispatcher\fP)"
.br
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB19\fP of file \fBDotNetCommandFactory\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Extensions\&.DotNet\&.Commands\&.DotNetCommandFactory\&.DotNetCommandFactory (\fBITextEditorService\fP textEditorService, \fBITreeViewService\fP treeViewService, \fBIEnvironmentProvider\fP environmentProvider, IJSRuntime jsRuntime, IDispatcher dispatcher)"

.PP
Definition at line \fB27\fP of file \fBDotNetCommandFactory\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Extensions\&.DotNet\&.Commands\&.DotNetCommandFactory\&.Initialize ()"

.PP
Implements \fBLuthetus\&.Extensions\&.DotNet\&.Commands\&.IDotNetCommandFactory\fP\&.
.PP
Definition at line \fB49\fP of file \fBDotNetCommandFactory\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
