.TH "Luthetus.Ide.RazorLib.Terminals.Models.TerminalCommandRequest" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.Terminals.Models.TerminalCommandRequest \- 'workingDirectory' is intended to be an absolute path in string form\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTerminalCommandRequest\fP (string commandText, string? workingDirectory)"
.br
.ti -1c
.RI "\fBTerminalCommandRequest\fP (string commandText, string? workingDirectory, \fBKey\fP< TerminalCommandRequest > key)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Key< \fBTerminalCommandRequest\fP > \fBKey\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBCommandText\fP\fR [get]\fP"
.br
.ti -1c
.RI "string? \fBWorkingDirectory\fP\fR [get]\fP"
.br
.ti -1c
.RI "Func< \fBTerminalCommandParsed\fP, Task > \fBBeginWithFunc\fP\fR [get]\fP"
.br
.RI "Input: the parsed terminal command that is about to begin execution\&. "
.ti -1c
.RI "Func< \fBTerminalCommandParsed\fP, Task > \fBOnOutputFunc\fP\fR [get]\fP"
.br
.RI "Input: the parsed terminal command that is being executed\&. "
.ti -1c
.RI "Func< \fBTerminalCommandParsed\fP, Task > \fBContinueWithFunc\fP\fR [get]\fP"
.br
.RI "Input: the parsed terminal command that just finished\&. "
.in -1c
.SH "Detailed Description"
.PP 
'workingDirectory' is intended to be an absolute path in string form\&. 

If 'workingDirectory' is null, then the WorkingDirectory of the terminal will not be changed\&. 
.PP
Definition at line \fB11\fP of file \fBTerminalCommandRequest\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalCommandRequest\&.TerminalCommandRequest (string commandText, string? workingDirectory)"

.PP

.PP
Definition at line \fB14\fP of file \fBTerminalCommandRequest\&.cs\fP\&.
.SS "Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalCommandRequest\&.TerminalCommandRequest (string commandText, string? workingDirectory, \fBKey\fP< TerminalCommandRequest > key)"

.PP

.PP
Definition at line \fB25\fP of file \fBTerminalCommandRequest\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Func<\fBTerminalCommandParsed\fP, Task> Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalCommandRequest\&.BeginWithFunc\fR [get]\fP"

.PP
Input: the parsed terminal command that is about to begin execution\&. This Func will block the terminal from executing further terminal commands in the queue until it has returned\&. 
.PP
Definition at line \fB48\fP of file \fBTerminalCommandRequest\&.cs\fP\&.
.SS "string Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalCommandRequest\&.CommandText\fR [get]\fP"

.PP
Definition at line \fB37\fP of file \fBTerminalCommandRequest\&.cs\fP\&.
.SS "Func<\fBTerminalCommandParsed\fP, Task> Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalCommandRequest\&.ContinueWithFunc\fR [get]\fP"

.PP
Input: the parsed terminal command that just finished\&. This Func will block the terminal from executing further terminal commands in the queue until it has returned\&. 
.PP
Definition at line \fB70\fP of file \fBTerminalCommandRequest\&.cs\fP\&.
.SS "Key<\fBTerminalCommandRequest\fP> Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalCommandRequest\&.Key\fR [get]\fP"

.PP
Definition at line \fB35\fP of file \fBTerminalCommandRequest\&.cs\fP\&.
.SS "Func<\fBTerminalCommandParsed\fP, Task> Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalCommandRequest\&.OnOutputFunc\fR [get]\fP"

.PP
Input: the parsed terminal command that is being executed\&. This Func will block the terminal from executing further terminal commands in the queue until it has returned\&.

.PP
( it is recommended to use ContinueWithFunc as invoking this Func every line of output might add an undesireable amount of overhead\&. ) 
.PP
Definition at line \fB62\fP of file \fBTerminalCommandRequest\&.cs\fP\&.
.SS "string? Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalCommandRequest\&.WorkingDirectory\fR [get]\fP"

.PP

.PP
Definition at line \fB40\fP of file \fBTerminalCommandRequest\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
