.TH "Luthetus.CompilerServices.CSharp.RuntimeAssemblies" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.CSharp.RuntimeAssemblies
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBIRuntimeAssembliesLoader\fP"
.br
.RI "https://learn.microsoft.com/en-us/dotnet/standard/assembly/inspect-contents-using-metadataloadcontext br/>
.br
 Purpose:
.br

.br
 Abstract System\&.Reflection\&.MetadataLoadContext usage to a single method invocation\&.
.br

.br
 "
.ti -1c
.RI "class \fBRuntimeAssembliesLoaderFactory\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
