.TH "Luthetus.TextEditor.Tests.Basis.Cursors.Models.TextEditorSelectionHelperTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.Cursors.Models.TextEditorSelectionHelperTests \- TextEditorSelectionHelper  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBHasSelectedText_A\fP ()"
.br
.RI "TextEditorSelectionHelper\&.HasSelectedText(TextEditorSelection) "
.ti -1c
.RI "void \fBHasSelectedText_B\fP ()"
.br
.RI "TextEditorSelectionHelper\&.HasSelectedText(ImmutableTextEditorSelection) "
.ti -1c
.RI "void \fBHasSelectedText_C\fP ()"
.br
.RI "TextEditorSelectionHelper\&.HasSelectedText(int?, int) "
.ti -1c
.RI "void \fBGetSelectedText_A\fP ()"
.br
.RI "TextEditorSelectionHelper\&.GetSelectedText(TextEditorSelection, RazorLib\&.TextEditors\&.Models\&.TextEditorModel) "
.ti -1c
.RI "void \fBGetSelectedText_B\fP ()"
.br
.RI "TextEditorSelectionHelper\&.GetSelectedText(ImmutableTextEditorSelection, RazorLib\&.TextEditors\&.Models\&.TextEditorModel) "
.ti -1c
.RI "void \fBGetSelectedText_C\fP ()"
.br
.RI "TextEditorSelectionHelper\&.GetSelectedText(int?, int, RazorLib\&.TextEditors\&.Models\&.TextEditorModel) "
.ti -1c
.RI "void \fBSelectLinesRange\fP ()"
.br
.RI "TextEditorSelectionHelper\&.SelectLinesRange(RazorLib\&.TextEditors\&.Models\&.TextEditorModel, int, int) "
.ti -1c
.RI "void \fBGetSelectionBounds_A\fP ()"
.br
.RI "TextEditorSelectionHelper\&.GetSelectionBounds(TextEditorSelection) "
.ti -1c
.RI "void \fBGetSelectionBounds_B\fP ()"
.br
.RI "TextEditorSelectionHelper\&.GetSelectionBounds(ImmutableTextEditorSelection) "
.ti -1c
.RI "void \fBGetSelectionBounds_C\fP ()"
.br
.RI "TextEditorSelectionHelper\&.GetSelectionBounds(int?, int) "
.ti -1c
.RI "void \fBConvertSelectionOfPositionIndexUnitsToRowIndexUnits\fP ()"
.br
.RI "TextEditorSelectionHelper\&.ConvertSelectionOfPositionIndexUnitsToRowIndexUnits(RazorLib\&.TextEditors\&.Models\&.TextEditorModel, ValueTuple<int, int>) "
.in -1c
.SH "Detailed Description"
.PP 
TextEditorSelectionHelper 
.PP
Definition at line \fB8\fP of file \fBTextEditorSelectionHelperTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Cursors\&.Models\&.TextEditorSelectionHelperTests\&.ConvertSelectionOfPositionIndexUnitsToRowIndexUnits ()"

.PP
TextEditorSelectionHelper\&.ConvertSelectionOfPositionIndexUnitsToRowIndexUnits(RazorLib\&.TextEditors\&.Models\&.TextEditorModel, ValueTuple<int, int>) 
.PP
Definition at line \fB104\fP of file \fBTextEditorSelectionHelperTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Cursors\&.Models\&.TextEditorSelectionHelperTests\&.GetSelectedText_A ()"

.PP
TextEditorSelectionHelper\&.GetSelectedText(TextEditorSelection, RazorLib\&.TextEditors\&.Models\&.TextEditorModel) 
.PP
Definition at line \fB41\fP of file \fBTextEditorSelectionHelperTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Cursors\&.Models\&.TextEditorSelectionHelperTests\&.GetSelectedText_B ()"

.PP
TextEditorSelectionHelper\&.GetSelectedText(ImmutableTextEditorSelection, RazorLib\&.TextEditors\&.Models\&.TextEditorModel) 
.PP
Definition at line \fB50\fP of file \fBTextEditorSelectionHelperTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Cursors\&.Models\&.TextEditorSelectionHelperTests\&.GetSelectedText_C ()"

.PP
TextEditorSelectionHelper\&.GetSelectedText(int?, int, RazorLib\&.TextEditors\&.Models\&.TextEditorModel) 
.PP
Definition at line \fB59\fP of file \fBTextEditorSelectionHelperTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Cursors\&.Models\&.TextEditorSelectionHelperTests\&.GetSelectionBounds_A ()"

.PP
TextEditorSelectionHelper\&.GetSelectionBounds(TextEditorSelection) 
.PP
Definition at line \fB77\fP of file \fBTextEditorSelectionHelperTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Cursors\&.Models\&.TextEditorSelectionHelperTests\&.GetSelectionBounds_B ()"

.PP
TextEditorSelectionHelper\&.GetSelectionBounds(ImmutableTextEditorSelection) 
.PP
Definition at line \fB86\fP of file \fBTextEditorSelectionHelperTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Cursors\&.Models\&.TextEditorSelectionHelperTests\&.GetSelectionBounds_C ()"

.PP
TextEditorSelectionHelper\&.GetSelectionBounds(int?, int) 
.PP
Definition at line \fB95\fP of file \fBTextEditorSelectionHelperTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Cursors\&.Models\&.TextEditorSelectionHelperTests\&.HasSelectedText_A ()"

.PP
TextEditorSelectionHelper\&.HasSelectedText(TextEditorSelection) 
.PP
Definition at line \fB14\fP of file \fBTextEditorSelectionHelperTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Cursors\&.Models\&.TextEditorSelectionHelperTests\&.HasSelectedText_B ()"

.PP
TextEditorSelectionHelper\&.HasSelectedText(ImmutableTextEditorSelection) 
.PP
Definition at line \fB23\fP of file \fBTextEditorSelectionHelperTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Cursors\&.Models\&.TextEditorSelectionHelperTests\&.HasSelectedText_C ()"

.PP
TextEditorSelectionHelper\&.HasSelectedText(int?, int) 
.PP
Definition at line \fB32\fP of file \fBTextEditorSelectionHelperTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Cursors\&.Models\&.TextEditorSelectionHelperTests\&.SelectLinesRange ()"

.PP
TextEditorSelectionHelper\&.SelectLinesRange(RazorLib\&.TextEditors\&.Models\&.TextEditorModel, int, int) 
.PP
Definition at line \fB68\fP of file \fBTextEditorSelectionHelperTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
