.TH "Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests \- \fBTextEditorViewModelApi\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditorTestBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "TextEditorViewModelApi(ITextEditorService, IBackgroundTaskService, IState<TextEditorViewModelState>, IState<TextEditorModelState>, IJSRuntime, IDispatcher, IDialogService) "
.ti -1c
.RI "void \fBCalculateVirtualizationResult\fP ()"
.br
.RI "TextEditorViewModelApi\&.CalculateVirtualizationResult(ResourceUri, Key<TextEditorViewModel>, CancellationToken) "
.ti -1c
.RI "void \fBCursorMovePageTop\fP ()"
.br
.RI "TextEditorViewModelApi\&.CursorMovePageTop(ResourceUri, Key<TextEditorViewModel>) "
.ti -1c
.RI "void \fBCursorMovePageTopUnsafe\fP ()"
.br
.RI "TextEditorViewModelApi\&.CursorMovePageTopUnsafe(ResourceUri, Key<TextEditorViewModel>, TextEditorCursorModifier) "
.ti -1c
.RI "void \fBCursorMovePageBottom\fP ()"
.br
.RI "TextEditorViewModelApi\&.CursorMovePageBottom(ResourceUri, Key<TextEditorViewModel>) "
.ti -1c
.RI "void \fBCursorMovePageBottomUnsafe\fP ()"
.br
.RI "TextEditorViewModelApi\&.CursorMovePageBottomUnsafe(ResourceUri, Key<TextEditorViewModel>, TextEditorCursorModifier) "
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.RI "TextEditorViewModelApi\&.Dispose(Key<TextEditorViewModel>) "
.ti -1c
.RI "void \fBFocusPrimaryCursor\fP ()"
.br
.RI "TextEditorViewModelApi\&.FocusPrimaryCursor(string) "
.ti -1c
.RI "void \fBGetTextEditorMeasurementsAsync\fP ()"
.br
.RI "\fBTextEditorViewModelApi\&.GetTextEditorMeasurementsAsync(string)\fP "
.ti -1c
.RI "void \fBGetModelOrDefault\fP ()"
.br
.RI "TextEditorViewModelApi\&.GetModelOrDefault(Key<TextEditorViewModel>) "
.ti -1c
.RI "void \fBGetAllText\fP ()"
.br
.RI "TextEditorViewModelApi\&.GetAllText(Key<TextEditorViewModel>) "
.ti -1c
.RI "void \fBGetOrDefault\fP ()"
.br
.RI "TextEditorViewModelApi\&.GetOrDefault(Key<TextEditorViewModel>) "
.ti -1c
.RI "void \fBGetViewModels\fP ()"
.br
.RI "\fBTextEditorViewModelApi\&.GetViewModels()\fP "
.ti -1c
.RI "void \fBMutateScrollVerticalPosition\fP ()"
.br
.RI "TextEditorViewModelApi\&.MutateScrollVerticalPosition(string, string, double) "
.ti -1c
.RI "void \fBMutateScrollHorizontalPosition\fP ()"
.br
.RI "TextEditorViewModelApi\&.MutateScrollHorizontalPosition(string, string, double) "
.ti -1c
.RI "void \fBMeasureCharacterWidthAndLineHeightAsync\fP ()"
.br
.RI "\fBTextEditorViewModelApi\&.MeasureCharacterWidthAndLineHeightAsync(string, int)\fP "
.ti -1c
.RI "void \fBMoveCursor\fP ()"
.br
.RI "TextEditorViewModelApi\&.MoveCursor(KeymapArgs, ResourceUri, Key<TextEditorViewModel>) "
.ti -1c
.RI "void \fBMoveCursor_SelectText\fP ()"
.br
.RI "TextEditorViewModelApi\&.MoveCursor(KeymapArgs, ResourceUri, Key<TextEditorViewModel>) "
.ti -1c
.RI "void \fBMoveCursor_SelectText_SmallSelectionAnchorPosition_Then_MoveLeft\fP ()"
.br
.ti -1c
.RI "void \fBMoveCursor_SelectText_SmallSelectionEndingPosition_Then_MoveLeft\fP ()"
.br
.ti -1c
.RI "void \fBMoveCursor_SelectText_SmallSelectionAnchorPosition_Then_MoveDown\fP ()"
.br
.ti -1c
.RI "void \fBMoveCursor_SelectText_SmallSelectionEndingPosition_Then_MoveDown\fP ()"
.br
.ti -1c
.RI "void \fBMoveCursor_SelectText_SmallSelectionAnchorPosition_Then_MoveUp\fP ()"
.br
.ti -1c
.RI "void \fBMoveCursor_SelectText_SmallSelectionEndingPosition_Then_MoveUp\fP ()"
.br
.ti -1c
.RI "void \fBMoveCursor_SelectText_SmallSelectionAnchorPosition_Then_MoveRight\fP ()"
.br
.ti -1c
.RI "void \fBMoveCursor_SelectText_SmallSelectionEndingPosition_Then_MoveRight\fP ()"
.br
.ti -1c
.RI "void \fBMoveCursorUnsafe\fP ()"
.br
.RI "TextEditorViewModelApi\&.MoveCursorUnsafe(KeymapArgs, ResourceUri, Key<TextEditorViewModel>, TextEditorCursorModifier) "
.ti -1c
.RI "void \fBRegister\fP ()"
.br
.RI "TextEditorViewModelApi\&.Register(Key<TextEditorViewModel>, ResourceUri, Category) "
.ti -1c
.RI "void \fBRemeasure\fP ()"
.br
.RI "TextEditorViewModelApi\&.Remeasure(ResourceUri, Key<TextEditorViewModel>, string, int, CancellationToken) "
.ti -1c
.RI "void \fBScrollIntoView_LineIndex_ColumnIndex\fP ()"
.br
.RI "TextEditorViewModelApi\&.ScrollIntoView(string, string, int?, int?) "
.ti -1c
.RI "void \fBScrollIntoView_PositionIndex\fP ()"
.br
.RI "TextEditorViewModelApi\&.ScrollIntoView(string, string, int) "
.ti -1c
.RI "void \fBScrollIntoView_TextSpan\fP ()"
.br
.RI "TextEditorViewModelApi\&.ScrollIntoView(ResourceUri, Key<TextEditorViewModel>, TextEditorTextSpan) "
.ti -1c
.RI "void \fBSetScrollPosition\fP ()"
.br
.RI "TextEditorViewModelApi\&.SetScrollPosition(string, string, double?, double?) "
.ti -1c
.RI "void \fBSetGutterScrollTop\fP ()"
.br
.RI "TextEditorViewModelApi\&.SetGutterScrollTop(string, double) "
.ti -1c
.RI "async Task \fBSetCursorShouldBlink\fP ()"
.br
.RI "\fBTextEditorViewModelApi\&.SetCursorShouldBlink(bool)\fP 
.br
----
.br
 \fBTextEditorViewModelApi\&.CursorShouldBlink\fP \fBTextEditorViewModelApi\&.CursorShouldBlinkChanged\fP "
.ti -1c
.RI "void \fBWithValue\fP ()"
.br
.RI "TextEditorViewModelApi\&.WithValue(Key<TextEditorViewModel>, Func<TextEditorViewModel, TextEditorViewModel>) "
.ti -1c
.RI "void \fBWithTask\fP ()"
.br
.RI "TextEditorViewModelApi\&.WithTask(Key<TextEditorViewModel>, Func<TextEditorViewModel, Task<Func<TextEditorViewModel, TextEditorViewModel>>>) "
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBLuthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditorTestBase\fP
.in +1c
.ti -1c
.RI "\fBBackgroundTaskService\fP \fBContinuousBackgroundTaskWorker\fP IDispatcher \fBITextEditorService\fP \fBtextEditorService\fP \fBInitializeBackgroundTasks\fP ()"
.br
.ti -1c
.RI "\fBTextEditorModel\fP \fBTextEditorModelModifier\fP modelModifier \fBEmptyEditor_TestData_And_PerformPreAssertions\fP (\fBResourceUri\fP \fBresourceUri\fP, DateTime resourceLastWriteTime, string fileExtension, string content, \fBIDecorationMapper\fP? decorationMapper, \fBICompilerService\fP? compilerService, int partitionSize)"
.br
.ti -1c
.RI "\fBTextEditorModel\fP \fBTextEditorModelModifier\fP modelModifier \fBNotEmptyEditor_TestData_And_PerformPreAssertions\fP (\fBResourceUri\fP \fBresourceUri\fP, DateTime resourceLastWriteTime, string fileExtension, string content, \fBIDecorationMapper\fP? decorationMapper, \fBICompilerService\fP? compilerService, int partitionSize)"
.br
.in -1c

Protected Attributes inherited from \fBLuthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditorTestBase\fP
.in +1c
.ti -1c
.RI "\fBBackgroundTaskService\fP \fBbackgroundTaskService\fP"
.br
.ti -1c
.RI "\fBBackgroundTaskService\fP \fBContinuousBackgroundTaskWorker\fP \fBbackgroundTaskWorker\fP"
.br
.ti -1c
.RI "\fBBackgroundTaskService\fP \fBContinuousBackgroundTaskWorker\fP IDispatcher \fBdispatcher\fP"
.br
.ti -1c
.RI "\fBTextEditorModel\fP \fBinModel\fP"
.br
.RI "Text Editor UI result (with show-newlines and show-whitespace; arrow is tab, and dot is space)
.br
 ===================== 
.br
 1 
.br
 
.br
 2 b9\\r 
.br
 3 9B\\r
.br
 
.br
 4 --->$;∙EOF 
.br
\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBTextEditorViewModelApi\fP 
.PP
Definition at line \fB23\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.CalculateVirtualizationResult ()"

.PP
TextEditorViewModelApi\&.CalculateVirtualizationResult(ResourceUri, Key<TextEditorViewModel>, CancellationToken) 
.PP
Definition at line \fB41\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.Constructor ()"

.PP
TextEditorViewModelApi(ITextEditorService, IBackgroundTaskService, IState<TextEditorViewModelState>, IState<TextEditorModelState>, IJSRuntime, IDispatcher, IDialogService) 
.PP
Definition at line \fB29\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.CursorMovePageBottom ()"

.PP
TextEditorViewModelApi\&.CursorMovePageBottom(ResourceUri, Key<TextEditorViewModel>) 
.PP
Definition at line \fB68\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.CursorMovePageBottomUnsafe ()"

.PP
TextEditorViewModelApi\&.CursorMovePageBottomUnsafe(ResourceUri, Key<TextEditorViewModel>, TextEditorCursorModifier) 
.PP
Definition at line \fB77\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.CursorMovePageTop ()"

.PP
TextEditorViewModelApi\&.CursorMovePageTop(ResourceUri, Key<TextEditorViewModel>) 
.PP
Definition at line \fB50\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.CursorMovePageTopUnsafe ()"

.PP
TextEditorViewModelApi\&.CursorMovePageTopUnsafe(ResourceUri, Key<TextEditorViewModel>, TextEditorCursorModifier) 
.PP
Definition at line \fB59\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.Dispose ()"

.PP
TextEditorViewModelApi\&.Dispose(Key<TextEditorViewModel>) 
.PP
Definition at line \fB86\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.FocusPrimaryCursor ()"

.PP
TextEditorViewModelApi\&.FocusPrimaryCursor(string) 
.PP
Definition at line \fB105\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.GetAllText ()"

.PP
TextEditorViewModelApi\&.GetAllText(Key<TextEditorViewModel>) 
.PP
Definition at line \fB144\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.GetModelOrDefault ()"

.PP
TextEditorViewModelApi\&.GetModelOrDefault(Key<TextEditorViewModel>) 
.PP
Definition at line \fB123\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.GetOrDefault ()"

.PP
TextEditorViewModelApi\&.GetOrDefault(Key<TextEditorViewModel>) 
.PP
Definition at line \fB161\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.GetTextEditorMeasurementsAsync ()"

.PP
\fBTextEditorViewModelApi\&.GetTextEditorMeasurementsAsync(string)\fP 
.PP
Definition at line \fB114\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.GetViewModels ()"

.PP
\fBTextEditorViewModelApi\&.GetViewModels()\fP 
.PP
Definition at line \fB178\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.MeasureCharacterWidthAndLineHeightAsync ()"

.PP
\fBTextEditorViewModelApi\&.MeasureCharacterWidthAndLineHeightAsync(string, int)\fP 
.PP
Definition at line \fB205\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.MoveCursor ()"

.PP
TextEditorViewModelApi\&.MoveCursor(KeymapArgs, ResourceUri, Key<TextEditorViewModel>) 
.PP
Definition at line \fB214\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.MoveCursor_SelectText ()"

.PP
TextEditorViewModelApi\&.MoveCursor(KeymapArgs, ResourceUri, Key<TextEditorViewModel>) 
.PP
Definition at line \fB223\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.MoveCursor_SelectText_SmallSelectionAnchorPosition_Then_MoveDown ()"

.SS "TextEditorViewModelApi\&.MoveCursor(KeymapArgs, ResourceUri, Key<TextEditorViewModel>)"
SmallSelectionAnchorPosition refers to the anchor position being smaller than the ending position\&. 
.PP
Definition at line \fB490\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.MoveCursor_SelectText_SmallSelectionAnchorPosition_Then_MoveLeft ()"

.SS "TextEditorViewModelApi\&.MoveCursor(KeymapArgs, ResourceUri, Key<TextEditorViewModel>)"
SmallSelectionAnchorPosition refers to the anchor position being smaller than the ending position\&. 
.PP
Definition at line \fB272\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.MoveCursor_SelectText_SmallSelectionAnchorPosition_Then_MoveRight ()"

.SS "TextEditorViewModelApi\&.MoveCursor(KeymapArgs, ResourceUri, Key<TextEditorViewModel>)"
SmallSelectionAnchorPosition refers to the anchor position being smaller than the ending position\&. 
.PP
Definition at line \fB929\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.MoveCursor_SelectText_SmallSelectionAnchorPosition_Then_MoveUp ()"

.SS "TextEditorViewModelApi\&.MoveCursor(KeymapArgs, ResourceUri, Key<TextEditorViewModel>)"
SmallSelectionAnchorPosition refers to the anchor position being smaller than the ending position\&. 
.PP
Definition at line \fB708\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.MoveCursor_SelectText_SmallSelectionEndingPosition_Then_MoveDown ()"

.SS "TextEditorViewModelApi\&.MoveCursor(KeymapArgs, ResourceUri, Key<TextEditorViewModel>)"
SmallSelectionEndingPosition refers to the ending position being smaller than the anchor\&. 
.PP
Definition at line \fB578\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.MoveCursor_SelectText_SmallSelectionEndingPosition_Then_MoveLeft ()"

.SS "TextEditorViewModelApi\&.MoveCursor(KeymapArgs, ResourceUri, Key<TextEditorViewModel>)"
SmallSelectionEndingPosition refers to the ending position being smaller than the anchor\&. 
.PP
Definition at line \fB360\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.MoveCursor_SelectText_SmallSelectionEndingPosition_Then_MoveRight ()"

.SS "TextEditorViewModelApi\&.MoveCursor(KeymapArgs, ResourceUri, Key<TextEditorViewModel>)"
SmallSelectionEndingPosition refers to the ending position being smaller than the anchor\&. 
.PP
Definition at line \fB1017\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.MoveCursor_SelectText_SmallSelectionEndingPosition_Then_MoveUp ()"

.SS "TextEditorViewModelApi\&.MoveCursor(KeymapArgs, ResourceUri, Key<TextEditorViewModel>)"
SmallSelectionEndingPosition refers to the ending position being smaller than the anchor\&. 
.PP
Definition at line \fB799\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.MoveCursorUnsafe ()"

.PP
TextEditorViewModelApi\&.MoveCursorUnsafe(KeymapArgs, ResourceUri, Key<TextEditorViewModel>, TextEditorCursorModifier) 
.PP
Definition at line \fB1145\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.MutateScrollHorizontalPosition ()"

.PP
TextEditorViewModelApi\&.MutateScrollHorizontalPosition(string, string, double) 
.PP
Definition at line \fB196\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.MutateScrollVerticalPosition ()"

.PP
TextEditorViewModelApi\&.MutateScrollVerticalPosition(string, string, double) 
.PP
Definition at line \fB187\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.Register ()"

.PP
TextEditorViewModelApi\&.Register(Key<TextEditorViewModel>, ResourceUri, Category) 
.PP
Definition at line \fB1154\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.Remeasure ()"

.PP
TextEditorViewModelApi\&.Remeasure(ResourceUri, Key<TextEditorViewModel>, string, int, CancellationToken) 
.PP
Definition at line \fB1176\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.ScrollIntoView_LineIndex_ColumnIndex ()"

.PP
TextEditorViewModelApi\&.ScrollIntoView(string, string, int?, int?) 
.PP
Definition at line \fB1185\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.ScrollIntoView_PositionIndex ()"

.PP
TextEditorViewModelApi\&.ScrollIntoView(string, string, int) 
.PP
Definition at line \fB1194\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.ScrollIntoView_TextSpan ()"

.PP
TextEditorViewModelApi\&.ScrollIntoView(ResourceUri, Key<TextEditorViewModel>, TextEditorTextSpan) 
.PP
Definition at line \fB1203\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "async Task Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.SetCursorShouldBlink ()"

.PP
\fBTextEditorViewModelApi\&.SetCursorShouldBlink(bool)\fP 
.br
----
.br
 \fBTextEditorViewModelApi\&.CursorShouldBlink\fP \fBTextEditorViewModelApi\&.CursorShouldBlinkChanged\fP 
.PP
Definition at line \fB1233\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.SetGutterScrollTop ()"

.PP
TextEditorViewModelApi\&.SetGutterScrollTop(string, double) 
.PP
Definition at line \fB1221\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.SetScrollPosition ()"

.PP
TextEditorViewModelApi\&.SetScrollPosition(string, string, double?, double?) 
.PP
Definition at line \fB1212\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.WithTask ()"

.PP
TextEditorViewModelApi\&.WithTask(Key<TextEditorViewModel>, Func<TextEditorViewModel, Task<Func<TextEditorViewModel, TextEditorViewModel>>>) 
.PP
Definition at line \fB1322\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\&.WithValue ()"

.PP
TextEditorViewModelApi\&.WithValue(Key<TextEditorViewModel>, Func<TextEditorViewModel, TextEditorViewModel>) 
.PP
Definition at line \fB1284\fP of file \fBTextEditorViewModelApiTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
