.TH "Luthetus.Common.Tests.Basis.Themes.States.ThemeStateActionsTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Themes.States.ThemeStateActionsTests \- \fBThemeState\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRegisterAction\fP ()"
.br
.RI "ThemeState\&.RegisterAction "
.ti -1c
.RI "void \fBDisposeAction\fP ()"
.br
.RI "ThemeState\&.DisposeAction "
.in -1c
.SH "Detailed Description"
.PP 
\fBThemeState\fP 
.PP
Definition at line \fB11\fP of file \fBThemeStateTests\&.Actions\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Themes\&.States\&.ThemeStateActionsTests\&.DisposeAction ()"

.PP
ThemeState\&.DisposeAction 
.PP
Definition at line \fB29\fP of file \fBThemeStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Themes\&.States\&.ThemeStateActionsTests\&.RegisterAction ()"

.PP
ThemeState\&.RegisterAction 
.PP
Definition at line \fB17\fP of file \fBThemeStateTests\&.Actions\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
