.TH "Luthetus.Ide.Tests.Basis.InputFiles.States.InputFileStateReducerTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.Tests.Basis.InputFiles.States.InputFileStateReducerTests \- InputFileState\&.Reducer  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBReduceStartInputFileStateFormAction\fP ()"
.br
.RI "InputFileState\&.Reducer\&.ReduceStartInputFileStateFormAction(InputFileState, InputFileState\&.StartInputFileStateFormAction) "
.ti -1c
.RI "void \fBReduceSetSelectedTreeViewModelAction\fP ()"
.br
.RI "InputFileState\&.Reducer\&.ReduceSetSelectedTreeViewModelAction(InputFileState, InputFileState\&.SetSelectedTreeViewModelAction) "
.ti -1c
.RI "void \fBReduceSetOpenedTreeViewModelAction\fP ()"
.br
.RI "InputFileState\&.Reducer\&.ReduceSetOpenedTreeViewModelAction(InputFileState, InputFileState\&.SetOpenedTreeViewModelAction) "
.ti -1c
.RI "void \fBReduceSetSelectedInputFilePatternAction\fP ()"
.br
.RI "InputFileState\&.Reducer\&.ReduceSetSelectedInputFilePatternAction(InputFileState, InputFileState\&.SetSelectedInputFilePatternAction) "
.ti -1c
.RI "void \fBReduceMoveBackwardsInHistoryAction\fP ()"
.br
.RI "InputFileState\&.Reducer\&.ReduceMoveBackwardsInHistoryAction(InputFileState) "
.ti -1c
.RI "void \fBReduceMoveForwardsInHistoryAction\fP ()"
.br
.RI "InputFileState\&.Reducer\&.ReduceMoveForwardsInHistoryAction(InputFileState) "
.ti -1c
.RI "void \fBReduceOpenParentDirectoryAction\fP ()"
.br
.RI "InputFileState\&.Reducer\&.ReduceOpenParentDirectoryAction(InputFileState, InputFileState\&.OpenParentDirectoryAction) "
.ti -1c
.RI "void \fBReduceRefreshCurrentSelectionAction\fP ()"
.br
.RI "InputFileState\&.Reducer\&.ReduceRefreshCurrentSelectionAction(InputFileState, InputFileState\&.RefreshCurrentSelectionAction) "
.ti -1c
.RI "void \fBReduceSetSearchQueryAction\fP ()"
.br
.RI "InputFileState\&.Reducer\&.ReduceSetSearchQueryAction(InputFileState, InputFileState\&.SetSearchQueryAction) "
.in -1c
.SH "Detailed Description"
.PP 
InputFileState\&.Reducer 
.PP
Definition at line \fB8\fP of file \fBInputFileStateReducerTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.InputFiles\&.States\&.InputFileStateReducerTests\&.ReduceMoveBackwardsInHistoryAction ()"

.PP
InputFileState\&.Reducer\&.ReduceMoveBackwardsInHistoryAction(InputFileState) 
.PP
Definition at line \fB51\fP of file \fBInputFileStateReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.InputFiles\&.States\&.InputFileStateReducerTests\&.ReduceMoveForwardsInHistoryAction ()"

.PP
InputFileState\&.Reducer\&.ReduceMoveForwardsInHistoryAction(InputFileState) 
.PP
Definition at line \fB60\fP of file \fBInputFileStateReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.InputFiles\&.States\&.InputFileStateReducerTests\&.ReduceOpenParentDirectoryAction ()"

.PP
InputFileState\&.Reducer\&.ReduceOpenParentDirectoryAction(InputFileState, InputFileState\&.OpenParentDirectoryAction) 
.PP
Definition at line \fB69\fP of file \fBInputFileStateReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.InputFiles\&.States\&.InputFileStateReducerTests\&.ReduceRefreshCurrentSelectionAction ()"

.PP
InputFileState\&.Reducer\&.ReduceRefreshCurrentSelectionAction(InputFileState, InputFileState\&.RefreshCurrentSelectionAction) 
.PP
Definition at line \fB78\fP of file \fBInputFileStateReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.InputFiles\&.States\&.InputFileStateReducerTests\&.ReduceSetOpenedTreeViewModelAction ()"

.PP
InputFileState\&.Reducer\&.ReduceSetOpenedTreeViewModelAction(InputFileState, InputFileState\&.SetOpenedTreeViewModelAction) 
.PP
Definition at line \fB32\fP of file \fBInputFileStateReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.InputFiles\&.States\&.InputFileStateReducerTests\&.ReduceSetSearchQueryAction ()"

.PP
InputFileState\&.Reducer\&.ReduceSetSearchQueryAction(InputFileState, InputFileState\&.SetSearchQueryAction) 
.PP
Definition at line \fB87\fP of file \fBInputFileStateReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.InputFiles\&.States\&.InputFileStateReducerTests\&.ReduceSetSelectedInputFilePatternAction ()"

.PP
InputFileState\&.Reducer\&.ReduceSetSelectedInputFilePatternAction(InputFileState, InputFileState\&.SetSelectedInputFilePatternAction) 
.PP
Definition at line \fB41\fP of file \fBInputFileStateReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.InputFiles\&.States\&.InputFileStateReducerTests\&.ReduceSetSelectedTreeViewModelAction ()"

.PP
InputFileState\&.Reducer\&.ReduceSetSelectedTreeViewModelAction(InputFileState, InputFileState\&.SetSelectedTreeViewModelAction) 
.PP
Definition at line \fB23\fP of file \fBInputFileStateReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.InputFiles\&.States\&.InputFileStateReducerTests\&.ReduceStartInputFileStateFormAction ()"

.PP
InputFileState\&.Reducer\&.ReduceStartInputFileStateFormAction(InputFileState, InputFileState\&.StartInputFileStateFormAction) 
.PP
Definition at line \fB14\fP of file \fBInputFileStateReducerTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
