.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.ConstructorDefinitionNodeTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.ConstructorDefinitionNodeTests \- \fBConstructorDefinitionNode\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "ConstructorDefinitionNode(TypeClauseNode, IdentifierToken, RazorLib\&.CompilerServices\&.Syntax\&.SyntaxNodes\&.GenericArgumentsListingNode?, FunctionArgumentsListingNode, Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.CodeBlockNode?, RazorLib\&.CompilerServices\&.Syntax\&.SyntaxNodes\&.ConstraintNode?) 
.br
----
.br
 \fBConstructorDefinitionNode\&.ReturnTypeClauseNode\fP \fBConstructorDefinitionNode\&.FunctionIdentifier\fP \fBConstructorDefinitionNode\&.GenericArgumentsListingNode\fP \fBConstructorDefinitionNode\&.FunctionArgumentsListingNode\fP ConstructorDefinitionNode\&.FunctionBodyCodeBlockNode \fBConstructorDefinitionNode\&.ConstraintNode\fP ConstructorDefinitionNode\&.ChildList \fBConstructorDefinitionNode\&.IsFabricated\fP \fBConstructorDefinitionNode\&.SyntaxKind\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBConstructorDefinitionNode\fP 
.PP
Definition at line \fB11\fP of file \fBConstructorDefinitionNodeTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.Syntax\&.SyntaxNodes\&.ConstructorDefinitionNodeTests\&.Constructor ()"

.PP
ConstructorDefinitionNode(TypeClauseNode, IdentifierToken, RazorLib\&.CompilerServices\&.Syntax\&.SyntaxNodes\&.GenericArgumentsListingNode?, FunctionArgumentsListingNode, Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.CodeBlockNode?, RazorLib\&.CompilerServices\&.Syntax\&.SyntaxNodes\&.ConstraintNode?) 
.br
----
.br
 \fBConstructorDefinitionNode\&.ReturnTypeClauseNode\fP \fBConstructorDefinitionNode\&.FunctionIdentifier\fP \fBConstructorDefinitionNode\&.GenericArgumentsListingNode\fP \fBConstructorDefinitionNode\&.FunctionArgumentsListingNode\fP ConstructorDefinitionNode\&.FunctionBodyCodeBlockNode \fBConstructorDefinitionNode\&.ConstraintNode\fP ConstructorDefinitionNode\&.ChildList \fBConstructorDefinitionNode\&.IsFabricated\fP \fBConstructorDefinitionNode\&.SyntaxKind\fP 
.PP
Definition at line \fB27\fP of file \fBConstructorDefinitionNodeTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
