.TH "Luthetus.TextEditor.RazorLib.Virtualizations.Displays.VirtualizationDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Virtualizations.Displays.VirtualizationDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase, and IDisposable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async Task \fBOnScrollEventAsync\fP (\fBVirtualizationScrollPosition\fP scrollPosition)"
.br
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInitialized\fP ()"
.br
.ti -1c
.RI "override async Task \fBOnAfterRenderAsync\fP (bool firstRender)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBIVirtualizationResultWithoutTypeMask\fP \fBVirtualizationResultWithoutTypeMask\fP = null!\fR [get, set]\fP"
.br
.ti -1c
.RI "Func< \fBVirtualizationRequest\fP, Task >? \fBItemsProviderFunc\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBUseHorizontalVirtualization\fP = true\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBUseVerticalVirtualization\fP = true\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBUseIntersectionObserver\fP = true\fR [get, set]\fP"
.br
.RI "The Gutter for the \fBTextEditor\fP uses the \fBVirtualizationDisplay\fP\&. I am going to see if adding this property allows me to have the gutter be given 'vertical padding' by means of the virtualization boundaries\&. Yet, not any intersection observer logic\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBVirtualizationDisplay\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Virtualizations\&.Displays\&.VirtualizationDisplay\&.Dispose ()"

.PP
Definition at line \fB112\fP of file \fBVirtualizationDisplay\&.razor\&.cs\fP\&.
.SS "override async Task Luthetus\&.TextEditor\&.RazorLib\&.Virtualizations\&.Displays\&.VirtualizationDisplay\&.OnAfterRenderAsync (bool firstRender)\fR [protected]\fP"

.PP
Definition at line \fB49\fP of file \fBVirtualizationDisplay\&.razor\&.cs\fP\&.
.SS "override void Luthetus\&.TextEditor\&.RazorLib\&.Virtualizations\&.Displays\&.VirtualizationDisplay\&.OnInitialized ()\fR [protected]\fP"

.PP
Definition at line \fB39\fP of file \fBVirtualizationDisplay\&.razor\&.cs\fP\&.
.SS "async Task Luthetus\&.TextEditor\&.RazorLib\&.Virtualizations\&.Displays\&.VirtualizationDisplay\&.OnScrollEventAsync (\fBVirtualizationScrollPosition\fP scrollPosition)"

.PP
Definition at line \fB91\fP of file \fBVirtualizationDisplay\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Func<\fBVirtualizationRequest\fP, Task>? Luthetus\&.TextEditor\&.RazorLib\&.Virtualizations\&.Displays\&.VirtualizationDisplay\&.ItemsProviderFunc\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB17\fP of file \fBVirtualizationDisplay\&.razor\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.Virtualizations\&.Displays\&.VirtualizationDisplay\&.UseHorizontalVirtualization = true\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB20\fP of file \fBVirtualizationDisplay\&.razor\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.Virtualizations\&.Displays\&.VirtualizationDisplay\&.UseIntersectionObserver = true\fR [get]\fP, \fR [set]\fP"

.PP
The Gutter for the \fBTextEditor\fP uses the \fBVirtualizationDisplay\fP\&. I am going to see if adding this property allows me to have the gutter be given 'vertical padding' by means of the virtualization boundaries\&. Yet, not any intersection observer logic\&. 
.PP
Definition at line \fB27\fP of file \fBVirtualizationDisplay\&.razor\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.Virtualizations\&.Displays\&.VirtualizationDisplay\&.UseVerticalVirtualization = true\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB22\fP of file \fBVirtualizationDisplay\&.razor\&.cs\fP\&.
.SS "\fBIVirtualizationResultWithoutTypeMask\fP Luthetus\&.TextEditor\&.RazorLib\&.Virtualizations\&.Displays\&.VirtualizationDisplay\&.VirtualizationResultWithoutTypeMask = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB15\fP of file \fBVirtualizationDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
