.TH "Luthetus.Common.Tests.Basis.TreeViews.Models.TreeViewNoTypeTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.TreeViews.Models.TreeViewNoTypeTests \- \fBTreeViewNoType\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBUntypedItem\fP ()"
.br
.RI "\fBTreeViewNoType\&.UntypedItem\fP \fBTreeViewNoType\&.ItemType\fP \fBTreeViewNoType\&.Parent\fP \fBTreeViewNoType\&.ChildList\fP \fBTreeViewNoType\&.IndexAmongSiblings\fP \fBTreeViewNoType\&.IsRoot\fP \fBTreeViewNoType\&.IsHidden\fP \fBTreeViewNoType\&.IsExpandable\fP \fBTreeViewNoType\&.IsExpanded\fP \fBTreeViewNoType\&.TreeViewChangedKey\fP \fBTreeViewNoType\&.Key\fP \fBTreeViewNoType\&.GetTreeViewRenderer()\fP \fBTreeViewNoType\&.LoadChildListAsync()\fP TreeViewNoType\&.RemoveRelatedFilesFromParent(List<TreeViewNoType>) "
.in -1c
.SH "Detailed Description"
.PP 
\fBTreeViewNoType\fP 
.PP
Definition at line \fB14\fP of file \fBTreeViewNoTypeTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.Models\&.TreeViewNoTypeTests\&.UntypedItem ()"

.PP
\fBTreeViewNoType\&.UntypedItem\fP \fBTreeViewNoType\&.ItemType\fP \fBTreeViewNoType\&.Parent\fP \fBTreeViewNoType\&.ChildList\fP \fBTreeViewNoType\&.IndexAmongSiblings\fP \fBTreeViewNoType\&.IsRoot\fP \fBTreeViewNoType\&.IsHidden\fP \fBTreeViewNoType\&.IsExpandable\fP \fBTreeViewNoType\&.IsExpanded\fP \fBTreeViewNoType\&.TreeViewChangedKey\fP \fBTreeViewNoType\&.Key\fP \fBTreeViewNoType\&.GetTreeViewRenderer()\fP \fBTreeViewNoType\&.LoadChildListAsync()\fP TreeViewNoType\&.RemoveRelatedFilesFromParent(List<TreeViewNoType>) 
.PP
Definition at line \fB33\fP of file \fBTreeViewNoTypeTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
