.TH "Luthetus.Common.RazorLib.Contexts.States" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Contexts.States
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "partial record \fBContextState\fP (ImmutableArray< \fBContextRecord\fP > AllContextsList, \fBContextHeirarchy\fP FocusedContextHeirarchy, \fBContextHeirarchy\fP? InspectedContextHeirarchy, ImmutableArray< \fBInspectableContext\fP > InspectableContextList, bool IsSelectingInspectionTarget)"
.br
.ti -1c
.RI "partial record \fBContextSwitchState\fP (ImmutableList< \fBContextSwitchGroup\fP > ContextSwitchGroupList)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "partial record Luthetus\&.Common\&.RazorLib\&.Contexts\&.States\&.ContextState (ImmutableArray< \fBContextRecord\fP > AllContextsList, \fBContextHeirarchy\fP FocusedContextHeirarchy, \fBContextHeirarchy\fP? InspectedContextHeirarchy, ImmutableArray< \fBInspectableContext\fP > InspectableContextList, bool IsSelectingInspectionTarget)"

.PP
Definition at line \fB9\fP of file \fBContextState\&.Main\&.cs\fP\&.
.SS "partial record Luthetus\&.Common\&.RazorLib\&.Contexts\&.States\&.ContextSwitchState (ImmutableList< \fBContextSwitchGroup\fP > ContextSwitchGroupList)"
After the UI renders, which of the entries in ContextSwitchGroupList should have their 0th menu option set focused first\&.
.PP
Definition at line \fB9\fP of file \fBContextSwitchState\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
