.TH "Luthetus.Extensions.DotNet.Tests.Basis.Nugets.States.NuGetPackageManagerStateActionsTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.Tests.Basis.Nugets.States.NuGetPackageManagerStateActionsTests \- NuGetPackageManagerState  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetSelectedProjectToModifyAction\fP ()"
.br
.RI "NuGetPackageManagerState\&.SetSelectedProjectToModifyAction "
.ti -1c
.RI "void \fBSetNugetQueryAction\fP ()"
.br
.RI "NuGetPackageManagerState\&.SetNugetQueryAction "
.ti -1c
.RI "void \fBSetIncludePrereleaseAction\fP ()"
.br
.RI "NuGetPackageManagerState\&.SetIncludePrereleaseAction "
.ti -1c
.RI "void \fBSetMostRecentQueryResultAction\fP ()"
.br
.RI "NuGetPackageManagerState\&.SetMostRecentQueryResultAction "
.in -1c
.SH "Detailed Description"
.PP 
NuGetPackageManagerState 
.PP
Definition at line \fB6\fP of file \fBNuGetPackageManagerStateActionsTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.Nugets\&.States\&.NuGetPackageManagerStateActionsTests\&.SetIncludePrereleaseAction ()"

.PP
NuGetPackageManagerState\&.SetIncludePrereleaseAction 
.PP
Definition at line \fB30\fP of file \fBNuGetPackageManagerStateActionsTests\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.Nugets\&.States\&.NuGetPackageManagerStateActionsTests\&.SetMostRecentQueryResultAction ()"

.PP
NuGetPackageManagerState\&.SetMostRecentQueryResultAction 
.PP
Definition at line \fB39\fP of file \fBNuGetPackageManagerStateActionsTests\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.Nugets\&.States\&.NuGetPackageManagerStateActionsTests\&.SetNugetQueryAction ()"

.PP
NuGetPackageManagerState\&.SetNugetQueryAction 
.PP
Definition at line \fB21\fP of file \fBNuGetPackageManagerStateActionsTests\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.Nugets\&.States\&.NuGetPackageManagerStateActionsTests\&.SetSelectedProjectToModifyAction ()"

.PP
NuGetPackageManagerState\&.SetSelectedProjectToModifyAction 
.PP
Definition at line \fB12\fP of file \fBNuGetPackageManagerStateActionsTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
