.TH "Luthetus.Ide.RazorLib.Terminals.States" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.Terminals.States
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTerminalGroupState\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "partial record \fBTerminalGroupState\fP (Key< \fBITerminal\fP > ActiveTerminalKey)"
.br
.ti -1c
.RI "partial record \fBTerminalState\fP (ImmutableDictionary< Key< \fBITerminal\fP >, \fBITerminal\fP > TerminalMap)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "partial record Luthetus\&.Ide\&.RazorLib\&.Terminals\&.States\&.TerminalGroupState (Key< \fBITerminal\fP > ActiveTerminalKey)"

.PP
Definition at line \fB10\fP of file \fBTerminalGroupState\&.Main\&.cs\fP\&.
.SS "partial record Luthetus\&.Ide\&.RazorLib\&.Terminals\&.States\&.TerminalState (ImmutableDictionary< Key< \fBITerminal\fP >, \fBITerminal\fP > TerminalMap)"

.PP
Definition at line \fB9\fP of file \fBTerminalState\&.Main\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
