.TH "Luthetus.Common.RazorLib.Htmls.Models" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Htmls.Models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHtmlFacts\fP"
.br
.RI "TODO: SphagettiCode - I don't like this file (2023-09-19) Why does \fBSizeFacts\&.cs\fP, HtmlFacts\&.Button\&.cs, and HtmlFacts\&.Main\&.cs exist? Merge all three of these? "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
