.TH "Luthetus.Common.Tests.Basis.Dropdowns.Models.DropdownServiceTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Dropdowns.Models.DropdownServiceTests \- \fBDropdownService\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "DropdownService(IDispatcher, IState<DropdownState>) 
.br
----
.br
 \fBDropdownService\&.DropdownStateWrap\fP "
.ti -1c
.RI "void \fBAddActiveDropdownKey\fP ()"
.br
.RI "DropdownService\&.AddActiveDropdownKey(Key<DropdownRecord>) "
.ti -1c
.RI "void \fBRemoveActiveDropdownKey\fP ()"
.br
.RI "DropdownService\&.RemoveActiveDropdownKey(Key<DropdownRecord>) "
.ti -1c
.RI "void \fBClearActiveDropdownKeysAction\fP ()"
.br
.RI "DropdownService\&.ClearActiveDropdownKeysAction() "
.in -1c
.SH "Detailed Description"
.PP 
\fBDropdownService\fP 
.PP
Definition at line \fB12\fP of file \fBDropdownServiceTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Dropdowns\&.Models\&.DropdownServiceTests\&.AddActiveDropdownKey ()"

.PP
DropdownService\&.AddActiveDropdownKey(Key<DropdownRecord>) 
.PP
Definition at line \fB32\fP of file \fBDropdownServiceTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Dropdowns\&.Models\&.DropdownServiceTests\&.ClearActiveDropdownKeysAction ()"

.PP
DropdownService\&.ClearActiveDropdownKeysAction() 
.PP
Definition at line \fB54\fP of file \fBDropdownServiceTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Dropdowns\&.Models\&.DropdownServiceTests\&.Constructor ()"

.PP
DropdownService(IDispatcher, IState<DropdownState>) 
.br
----
.br
 \fBDropdownService\&.DropdownStateWrap\fP 
.PP
Definition at line \fB20\fP of file \fBDropdownServiceTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Dropdowns\&.Models\&.DropdownServiceTests\&.RemoveActiveDropdownKey ()"

.PP
DropdownService\&.RemoveActiveDropdownKey(Key<DropdownRecord>) 
.PP
Definition at line \fB43\fP of file \fBDropdownServiceTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
