.TH "Luthetus.Extensions.DotNet.Websites.ProjectTemplates.Models.ConsoleAppFacts" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.Websites.ProjectTemplates.Models.ConsoleAppFacts
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static string \fBGetCsprojContents\fP (string projectName)"
.br
.ti -1c
.RI "static string \fBGetProgramCsContents\fP (string projectName)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBPROGRAM_CS_RELATIVE_FILE_PATH\fP = @'Program\&.cs'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBConsoleAppFacts\&.Csproj\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "string Luthetus\&.Extensions\&.DotNet\&.Websites\&.ProjectTemplates\&.Models\&.ConsoleAppFacts\&.GetCsprojContents (string projectName)\fR [static]\fP"

.SS "string Luthetus\&.Extensions\&.DotNet\&.Websites\&.ProjectTemplates\&.Models\&.ConsoleAppFacts\&.GetProgramCsContents (string projectName)\fR [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "const string Luthetus\&.Extensions\&.DotNet\&.Websites\&.ProjectTemplates\&.Models\&.ConsoleAppFacts\&.PROGRAM_CS_RELATIVE_FILE_PATH = @'Program\&.cs'\fR [static]\fP"

.PP
Definition at line \fB5\fP of file \fBConsoleAppFacts\&.ProgramCs\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
