.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.NamespaceStatementNodeTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.NamespaceStatementNodeTests \- \fBNamespaceStatementNode\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "NamespaceStatementNode(KeywordToken, IdentifierToken, CodeBlockNode) 
.br
----
.br
 \fBNamespaceStatementNode\&.KeywordToken\fP \fBNamespaceStatementNode\&.IdentifierToken\fP NamespaceStatementNode\&.NamespaceEntryNodeList NamespaceStatementNode\&.ChildList \fBNamespaceStatementNode\&.IsFabricated\fP \fBNamespaceStatementNode\&.SyntaxKind\fP "
.ti -1c
.RI "void \fBGetTopLevelTypeDefinitionNodes\fP ()"
.br
.RI "\fBNamespaceStatementNode\&.GetTopLevelTypeDefinitionNodes()\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBNamespaceStatementNode\fP 
.PP
Definition at line \fB9\fP of file \fBNamespaceStatementNodeTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.Syntax\&.SyntaxNodes\&.NamespaceStatementNodeTests\&.Constructor ()"

.PP
NamespaceStatementNode(KeywordToken, IdentifierToken, CodeBlockNode) 
.br
----
.br
 \fBNamespaceStatementNode\&.KeywordToken\fP \fBNamespaceStatementNode\&.IdentifierToken\fP NamespaceStatementNode\&.NamespaceEntryNodeList NamespaceStatementNode\&.ChildList \fBNamespaceStatementNode\&.IsFabricated\fP \fBNamespaceStatementNode\&.SyntaxKind\fP 
.PP
Definition at line \fB22\fP of file \fBNamespaceStatementNodeTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.Syntax\&.SyntaxNodes\&.NamespaceStatementNodeTests\&.GetTopLevelTypeDefinitionNodes ()"

.PP
\fBNamespaceStatementNode\&.GetTopLevelTypeDefinitionNodes()\fP 
.PP
Definition at line \fB31\fP of file \fBNamespaceStatementNodeTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
