.TH "Luthetus.CompilerServices.DotNetSolution.Facts.LexSolutionFacts.Project" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.DotNetSolution.Facts.LexSolutionFacts.Project
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBPROJECT_DEFINITION_START_TOKEN\fP = @'Project'"
.br
.ti -1c
.RI "const string \fBGUID_START_TOKEN\fP = @'{'"
.br
.ti -1c
.RI "const string \fBGUID_END_TOKEN\fP = @'}'"
.br
.ti -1c
.RI "const string \fBVALUE_START_TOKEN\fP = @''''"
.br
.ti -1c
.RI "const string \fBVALUE_END_TOKEN\fP = @''''"
.br
.ti -1c
.RI "const string \fBPROJECT_DEFINITION_END_TOKEN\fP = @'EndProject'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBProject\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const string Luthetus\&.CompilerServices\&.DotNetSolution\&.Facts\&.LexSolutionFacts\&.Project\&.GUID_END_TOKEN = @'}'\fR [static]\fP"

.PP
Definition at line \fB9\fP of file \fBProject\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.DotNetSolution\&.Facts\&.LexSolutionFacts\&.Project\&.GUID_START_TOKEN = @'{'\fR [static]\fP"

.PP
Definition at line \fB8\fP of file \fBProject\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.DotNetSolution\&.Facts\&.LexSolutionFacts\&.Project\&.PROJECT_DEFINITION_END_TOKEN = @'EndProject'\fR [static]\fP"

.PP
Definition at line \fB12\fP of file \fBProject\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.DotNetSolution\&.Facts\&.LexSolutionFacts\&.Project\&.PROJECT_DEFINITION_START_TOKEN = @'Project'\fR [static]\fP"

.PP
Definition at line \fB7\fP of file \fBProject\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.DotNetSolution\&.Facts\&.LexSolutionFacts\&.Project\&.VALUE_END_TOKEN = @''''\fR [static]\fP"

.PP
Definition at line \fB11\fP of file \fBProject\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.DotNetSolution\&.Facts\&.LexSolutionFacts\&.Project\&.VALUE_START_TOKEN = @''''\fR [static]\fP"

.PP
Definition at line \fB10\fP of file \fBProject\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
