.TH "Luthetus.Ide.RazorLib.FileSystems.Models.FileTemplate" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.FileSystems.Models.FileTemplate
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.IFileTemplate\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileTemplate\fP (string displayName, string codeName, \fBFileTemplateKind\fP fileTemplateKind, Func< string, bool > isExactTemplate, Func< string, ImmutableArray< \fBIFileTemplate\fP > > relatedFileTemplatesFunc, bool initialCheckedStateWhenIsRelatedFile, Func< \fBFileTemplateParameter\fP, \fBFileTemplateResult\fP > constructFileContents)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Guid \fBId\fP = Guid\&.NewGuid()\fR [get]\fP"
.br
.ti -1c
.RI "string \fBDisplayName\fP\fR [get]\fP"
.br
.RI "Name displayed to a user\&. "
.ti -1c
.RI "string \fBCodeName\fP\fR [get]\fP"
.br
.RI "Internally used name\&. "
.ti -1c
.RI "\fBFileTemplateKind\fP \fBFileTemplateKind\fP\fR [get]\fP"
.br
.ti -1c
.RI "Func< string, bool > \fBIsExactTemplate\fP\fR [get]\fP"
.br
.RI "Func<string filename, bool isApplicable> 
.br

.br
 Take \&.SingleOrDefault() to find the IsExactTemplate\&. "
.ti -1c
.RI "Func< string, ImmutableArray< \fBIFileTemplate\fP > > \fBRelatedFileTemplatesFunc\fP\fR [get]\fP"
.br
.RI "Func<string filename, bool isApplicable> 
.br

.br
 \fBRelatedFileTemplatesFunc\fP refers to the user making a '\&.razor' file and them being then prompted if they want to make a codebehind as well\&. The codebehind is the related file\&. "
.ti -1c
.RI "bool \fBInitialCheckedStateWhenIsRelatedFile\fP\fR [get]\fP"
.br
.RI "When the user types "\&.razor" is the codebehind template input element checked by default? "
.ti -1c
.RI "Func< \fBFileTemplateParameter\fP, \fBFileTemplateResult\fP > \fBConstructFileContents\fP\fR [get]\fP"
.br
.RI "Func<string filename, NamespacePath parentDirectory, Task writeOutFileTask>\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBFileTemplate\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.FileTemplate\&.FileTemplate (string displayName, string codeName, \fBFileTemplateKind\fP fileTemplateKind, Func< string, bool > isExactTemplate, Func< string, ImmutableArray< \fBIFileTemplate\fP > > relatedFileTemplatesFunc, bool initialCheckedStateWhenIsRelatedFile, Func< \fBFileTemplateParameter\fP, \fBFileTemplateResult\fP > constructFileContents)"

.PP
Definition at line \fB7\fP of file \fBFileTemplate\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.FileTemplate\&.CodeName\fR [get]\fP"

.PP
Internally used name\&. 
.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.IFileTemplate\fP\&.
.PP
Definition at line \fB27\fP of file \fBFileTemplate\&.cs\fP\&.
.SS "Func<\fBFileTemplateParameter\fP, \fBFileTemplateResult\fP> Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.FileTemplate\&.ConstructFileContents\fR [get]\fP"

.PP
Func<string filename, NamespacePath parentDirectory, Task writeOutFileTask>\&. 
.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.IFileTemplate\fP\&.
.PP
Definition at line \fB32\fP of file \fBFileTemplate\&.cs\fP\&.
.SS "string Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.FileTemplate\&.DisplayName\fR [get]\fP"

.PP
Name displayed to a user\&. 
.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.IFileTemplate\fP\&.
.PP
Definition at line \fB26\fP of file \fBFileTemplate\&.cs\fP\&.
.SS "\fBFileTemplateKind\fP Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.FileTemplate\&.FileTemplateKind\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.IFileTemplate\fP\&.
.PP
Definition at line \fB28\fP of file \fBFileTemplate\&.cs\fP\&.
.SS "Guid Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.FileTemplate\&.Id = Guid\&.NewGuid()\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.IFileTemplate\fP\&.
.PP
Definition at line \fB25\fP of file \fBFileTemplate\&.cs\fP\&.
.SS "bool Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.FileTemplate\&.InitialCheckedStateWhenIsRelatedFile\fR [get]\fP"

.PP
When the user types "\&.razor" is the codebehind template input element checked by default? 
.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.IFileTemplate\fP\&.
.PP
Definition at line \fB31\fP of file \fBFileTemplate\&.cs\fP\&.
.SS "Func<string, bool> Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.FileTemplate\&.IsExactTemplate\fR [get]\fP"

.PP
Func<string filename, bool isApplicable> 
.br

.br
 Take \&.SingleOrDefault() to find the IsExactTemplate\&. 
.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.IFileTemplate\fP\&.
.PP
Definition at line \fB29\fP of file \fBFileTemplate\&.cs\fP\&.
.SS "Func<string, ImmutableArray<\fBIFileTemplate\fP> > Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.FileTemplate\&.RelatedFileTemplatesFunc\fR [get]\fP"

.PP
Func<string filename, bool isApplicable> 
.br

.br
 \fBRelatedFileTemplatesFunc\fP refers to the user making a '\&.razor' file and them being then prompted if they want to make a codebehind as well\&. The codebehind is the related file\&. 
.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.IFileTemplate\fP\&.
.PP
Definition at line \fB30\fP of file \fBFileTemplate\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
