.TH "Luthetus.Common.Tests.Basis.Dialogs.States.DialogStateReducerTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Dialogs.States.DialogStateReducerTests \- DialogState\&.Reducer  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBReduceRegisterAction\fP ()"
.br
.RI "DialogState\&.Reducer\&.ReduceRegisterAction(DialogState, DialogState\&.RegisterAction) "
.ti -1c
.RI "void \fBReduceSetIsMaximizedAction\fP ()"
.br
.RI "DialogState\&.Reducer\&.ReduceSetIsMaximizedAction(DialogState, DialogState\&.SetIsMaximizedAction) "
.ti -1c
.RI "void \fBReduceDisposeAction\fP ()"
.br
.RI "DialogState\&.Reducer\&.ReduceDisposeAction(DialogState, DialogState\&.DisposeAction) "
.in -1c
.SH "Detailed Description"
.PP 
DialogState\&.Reducer 
.PP
Definition at line \fB14\fP of file \fBDialogStateTests\&.Reducer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Dialogs\&.States\&.DialogStateReducerTests\&.ReduceDisposeAction ()"

.PP
DialogState\&.Reducer\&.ReduceDisposeAction(DialogState, DialogState\&.DisposeAction) 
.PP
Definition at line \fB60\fP of file \fBDialogStateTests\&.Reducer\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Dialogs\&.States\&.DialogStateReducerTests\&.ReduceRegisterAction ()"

.PP
DialogState\&.Reducer\&.ReduceRegisterAction(DialogState, DialogState\&.RegisterAction) 
.PP
Definition at line \fB20\fP of file \fBDialogStateTests\&.Reducer\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Dialogs\&.States\&.DialogStateReducerTests\&.ReduceSetIsMaximizedAction ()"

.PP
DialogState\&.Reducer\&.ReduceSetIsMaximizedAction(DialogState, DialogState\&.SetIsMaximizedAction) 
.PP
Definition at line \fB37\fP of file \fBDialogStateTests\&.Reducer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
