.TH "Luthetus.Common.Tests.Basis.Clipboards.Models.InMemoryClipboardServiceTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Clipboards.Models.InMemoryClipboardServiceTests \- \fBInMemoryClipboardService\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async Task \fBConstructor\fP ()"
.br
.RI "InMemoryClipboardService() 
.br
----
.br
 \fBInMemoryClipboardService\&.SetClipboard(string)\fP \fBInMemoryClipboardService\&.ReadClipboard()\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBInMemoryClipboardService\fP 
.PP
Definition at line \fB8\fP of file \fBInMemoryClipboardServiceTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "async Task Luthetus\&.Common\&.Tests\&.Basis\&.Clipboards\&.Models\&.InMemoryClipboardServiceTests\&.Constructor ()"

.PP
InMemoryClipboardService() 
.br
----
.br
 \fBInMemoryClipboardService\&.SetClipboard(string)\fP \fBInMemoryClipboardService\&.ReadClipboard()\fP 
.PP
Definition at line \fB17\fP of file \fBInMemoryClipboardServiceTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
