.TH "Luthetus.TextEditor.RazorLib.CompilerServices.Utility.DeferredChildScope" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.CompilerServices.Utility.DeferredChildScope
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDeferredChildScope\fP (int openTokenIndex, int closeTokenIndex, \fBICodeBlockOwner\fP pendingCodeBlockOwner)"
.br
.ti -1c
.RI "void \fBPrepareMainParserLoop\fP (int tokenIndexToRestore, \fBIParserModel\fP model)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBOpenTokenIndex\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBCloseTokenIndex\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBICodeBlockOwner\fP \fBPendingCodeBlockOwner\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBTokenIndexToRestore\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBDeferredChildScope\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Utility\&.DeferredChildScope\&.DeferredChildScope (int openTokenIndex, int closeTokenIndex, \fBICodeBlockOwner\fP pendingCodeBlockOwner)"

.PP
Definition at line \fB9\fP of file \fBDeferredChildScope\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Utility\&.DeferredChildScope\&.PrepareMainParserLoop (int tokenIndexToRestore, \fBIParserModel\fP model)"

.PP
Definition at line \fB25\fP of file \fBDeferredChildScope\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Utility\&.DeferredChildScope\&.CloseTokenIndex\fR [get]\fP"

.PP
Definition at line \fB20\fP of file \fBDeferredChildScope\&.cs\fP\&.
.SS "int Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Utility\&.DeferredChildScope\&.OpenTokenIndex\fR [get]\fP"

.PP
Definition at line \fB19\fP of file \fBDeferredChildScope\&.cs\fP\&.
.SS "\fBICodeBlockOwner\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Utility\&.DeferredChildScope\&.PendingCodeBlockOwner\fR [get]\fP"

.PP
Definition at line \fB21\fP of file \fBDeferredChildScope\&.cs\fP\&.
.SS "int Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Utility\&.DeferredChildScope\&.TokenIndexToRestore\fR [get]\fP"

.PP
Definition at line \fB23\fP of file \fBDeferredChildScope\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
