.TH "Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxWalker" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxWalker
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBVisit\fP (\fBIGenericSyntax\fP node)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "List< \fBGenericStringSyntax\fP > \fBStringSyntaxList\fP = new()\fR [get]\fP"
.br
.ti -1c
.RI "List< \fBGenericCommentSingleLineSyntax\fP > \fBCommentSingleLineSyntaxList\fP = new()\fR [get]\fP"
.br
.ti -1c
.RI "List< \fBGenericCommentMultiLineSyntax\fP > \fBCommentMultiLineSyntaxList\fP = new()\fR [get]\fP"
.br
.ti -1c
.RI "List< \fBGenericKeywordSyntax\fP > \fBKeywordSyntaxList\fP = new()\fR [get]\fP"
.br
.ti -1c
.RI "List< \fBGenericFunctionSyntax\fP > \fBFunctionSyntaxList\fP = new()\fR [get]\fP"
.br
.ti -1c
.RI "List< \fBGenericPreprocessorDirectiveSyntax\fP > \fBPreprocessorDirectiveSyntaxList\fP = new()\fR [get]\fP"
.br
.ti -1c
.RI "List< \fBGenericDeliminationExtendedSyntax\fP > \fBDeliminationExtendedSyntaxList\fP = new()\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBGenericSyntaxWalker\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxActors\&.GenericSyntaxWalker\&.Visit (\fBIGenericSyntax\fP node)"

.PP
Definition at line \fB16\fP of file \fBGenericSyntaxWalker\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "List<\fBGenericCommentMultiLineSyntax\fP> Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxActors\&.GenericSyntaxWalker\&.CommentMultiLineSyntaxList = new()\fR [get]\fP"

.PP
Definition at line \fB10\fP of file \fBGenericSyntaxWalker\&.cs\fP\&.
.SS "List<\fBGenericCommentSingleLineSyntax\fP> Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxActors\&.GenericSyntaxWalker\&.CommentSingleLineSyntaxList = new()\fR [get]\fP"

.PP
Definition at line \fB9\fP of file \fBGenericSyntaxWalker\&.cs\fP\&.
.SS "List<\fBGenericDeliminationExtendedSyntax\fP> Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxActors\&.GenericSyntaxWalker\&.DeliminationExtendedSyntaxList = new()\fR [get]\fP"

.PP
Definition at line \fB14\fP of file \fBGenericSyntaxWalker\&.cs\fP\&.
.SS "List<\fBGenericFunctionSyntax\fP> Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxActors\&.GenericSyntaxWalker\&.FunctionSyntaxList = new()\fR [get]\fP"

.PP
Definition at line \fB12\fP of file \fBGenericSyntaxWalker\&.cs\fP\&.
.SS "List<\fBGenericKeywordSyntax\fP> Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxActors\&.GenericSyntaxWalker\&.KeywordSyntaxList = new()\fR [get]\fP"

.PP
Definition at line \fB11\fP of file \fBGenericSyntaxWalker\&.cs\fP\&.
.SS "List<\fBGenericPreprocessorDirectiveSyntax\fP> Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxActors\&.GenericSyntaxWalker\&.PreprocessorDirectiveSyntaxList = new()\fR [get]\fP"

.PP
Definition at line \fB13\fP of file \fBGenericSyntaxWalker\&.cs\fP\&.
.SS "List<\fBGenericStringSyntax\fP> Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxActors\&.GenericSyntaxWalker\&.StringSyntaxList = new()\fR [get]\fP"

.PP
Definition at line \fB8\fP of file \fBGenericSyntaxWalker\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
