.TH "Luthetus.Common.RazorLib.Options.Models.AppOptionsService" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Options.Models.AppOptionsService
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAppOptionsService\fP (IState< \fBAppOptionsState\fP > appOptionsStateWrap, IState< \fBThemeState\fP > themeStateWrap, IDispatcher dispatcher, \fBIStorageService\fP storageService, \fBCommonBackgroundTaskApi\fP commonBackgroundTaskApi, \fBIBackgroundTaskService\fP backgroundTaskService)"
.br
.ti -1c
.RI "void \fBSetActiveThemeRecordKey\fP (Key< \fBThemeRecord\fP > themeKey, bool updateStorage=true)"
.br
.ti -1c
.RI "void \fBSetTheme\fP (\fBThemeRecord\fP theme, bool updateStorage=true)"
.br
.ti -1c
.RI "void \fBSetFontFamily\fP (string? fontFamily, bool updateStorage=true)"
.br
.ti -1c
.RI "void \fBSetFontSize\fP (int fontSizeInPixels, bool updateStorage=true)"
.br
.ti -1c
.RI "void \fBSetResizeHandleWidth\fP (int resizeHandleWidthInPixels, bool updateStorage=true)"
.br
.ti -1c
.RI "void \fBSetResizeHandleHeight\fP (int resizeHandleHeightInPixels, bool updateStorage=true)"
.br
.ti -1c
.RI "void \fBSetIconSize\fP (int iconSizeInPixels, bool updateStorage=true)"
.br
.ti -1c
.RI "async Task \fBSetFromLocalStorageAsync\fP ()"
.br
.ti -1c
.RI "void \fBWriteToStorage\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IState< \fBAppOptionsState\fP > \fBAppOptionsStateWrap\fP\fR [get]\fP"
.br
.ti -1c
.RI "IState< \fBThemeState\fP > \fBThemeStateWrap\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBStorageKey\fP\fR [get]\fP"
.br
.RI "This is used when interacting with the \fBIStorageService\fP to set and get data\&. "
.ti -1c
.RI "string \fBThemeCssClassString\fP\fR [get]\fP"
.br
.ti -1c
.RI "string? \fBFontFamilyCssStyleString\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBFontSizeCssStyleString\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBShowPanelTitles\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBShowPanelTitlesCssClass\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBColorSchemeCssStyleString\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBAppOptionsService\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\&.AppOptionsService (IState< \fBAppOptionsState\fP > appOptionsStateWrap, IState< \fBThemeState\fP > themeStateWrap, IDispatcher dispatcher, \fBIStorageService\fP storageService, \fBCommonBackgroundTaskApi\fP commonBackgroundTaskApi, \fBIBackgroundTaskService\fP backgroundTaskService)"

.PP
Definition at line \fB21\fP of file \fBAppOptionsService\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\&.SetActiveThemeRecordKey (Key< \fBThemeRecord\fP > themeKey, bool updateStorage = \fRtrue\fP)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\fP\&.
.PP
Definition at line \fB102\fP of file \fBAppOptionsService\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\&.SetFontFamily (string? fontFamily, bool updateStorage = \fRtrue\fP)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\fP\&.
.PP
Definition at line \fB130\fP of file \fBAppOptionsService\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\&.SetFontSize (int fontSizeInPixels, bool updateStorage = \fRtrue\fP)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\fP\&.
.PP
Definition at line \fB144\fP of file \fBAppOptionsService\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\&.SetFromLocalStorageAsync ()"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\fP\&.
.PP
Definition at line \fB200\fP of file \fBAppOptionsService\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\&.SetIconSize (int iconSizeInPixels, bool updateStorage = \fRtrue\fP)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\fP\&.
.PP
Definition at line \fB186\fP of file \fBAppOptionsService\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\&.SetResizeHandleHeight (int resizeHandleHeightInPixels, bool updateStorage = \fRtrue\fP)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\fP\&.
.PP
Definition at line \fB172\fP of file \fBAppOptionsService\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\&.SetResizeHandleWidth (int resizeHandleWidthInPixels, bool updateStorage = \fRtrue\fP)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\fP\&.
.PP
Definition at line \fB158\fP of file \fBAppOptionsService\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\&.SetTheme (\fBThemeRecord\fP theme, bool updateStorage = \fRtrue\fP)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\fP\&.
.PP
Definition at line \fB116\fP of file \fBAppOptionsService\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\&.WriteToStorage ()"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\fP\&.
.PP
Definition at line \fB236\fP of file \fBAppOptionsService\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "IState<\fBAppOptionsState\fP> Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\&.AppOptionsStateWrap\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\fP\&.
.PP
Definition at line \fB37\fP of file \fBAppOptionsService\&.cs\fP\&.
.SS "string Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\&.ColorSchemeCssStyleString\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\fP\&.
.PP
Definition at line \fB79\fP of file \fBAppOptionsService\&.cs\fP\&.
.SS "string? Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\&.FontFamilyCssStyleString\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\fP\&.
.PP
Definition at line \fB51\fP of file \fBAppOptionsService\&.cs\fP\&.
.SS "string Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\&.FontSizeCssStyleString\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\fP\&.
.PP
Definition at line \fB62\fP of file \fBAppOptionsService\&.cs\fP\&.
.SS "bool Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\&.ShowPanelTitles\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\fP\&.
.PP
Definition at line \fB73\fP of file \fBAppOptionsService\&.cs\fP\&.
.SS "string Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\&.ShowPanelTitlesCssClass\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\fP\&.
.PP
Definition at line \fB75\fP of file \fBAppOptionsService\&.cs\fP\&.
.SS "string Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\&.StorageKey\fR [get]\fP"

.PP
This is used when interacting with the \fBIStorageService\fP to set and get data\&. 
.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\fP\&.
.PP
Definition at line \fB43\fP of file \fBAppOptionsService\&.cs\fP\&.
.SS "string Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\&.ThemeCssClassString\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\fP\&.
.PP
Definition at line \fB46\fP of file \fBAppOptionsService\&.cs\fP\&.
.SS "IState<\fBThemeState\fP> Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\&.ThemeStateWrap\fR [get]\fP"

.PP
Definition at line \fB38\fP of file \fBAppOptionsService\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
