.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxWalkerTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxWalkerTests \- \fBGenericSyntaxWalker\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBProperties\fP ()"
.br
.RI "\fBGenericSyntaxWalker\&.StringSyntaxList\fP \fBGenericSyntaxWalker\&.CommentSingleLineSyntaxList\fP \fBGenericSyntaxWalker\&.CommentMultiLineSyntaxList\fP \fBGenericSyntaxWalker\&.KeywordSyntaxList\fP \fBGenericSyntaxWalker\&.FunctionSyntaxList\fP \fBGenericSyntaxWalker\&.PreprocessorDirectiveSyntaxList\fP \fBGenericSyntaxWalker\&.DeliminationExtendedSyntaxList\fP "
.ti -1c
.RI "void \fBVisit\fP ()"
.br
.RI "GenericSyntaxWalker\&.Visit(IGenericSyntax) "
.in -1c
.SH "Detailed Description"
.PP 
\fBGenericSyntaxWalker\fP 
.PP
Definition at line \fB9\fP of file \fBGenericSyntaxWalkerTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.GenericLexer\&.SyntaxActors\&.GenericSyntaxWalkerTests\&.Properties ()"

.PP
\fBGenericSyntaxWalker\&.StringSyntaxList\fP \fBGenericSyntaxWalker\&.CommentSingleLineSyntaxList\fP \fBGenericSyntaxWalker\&.CommentMultiLineSyntaxList\fP \fBGenericSyntaxWalker\&.KeywordSyntaxList\fP \fBGenericSyntaxWalker\&.FunctionSyntaxList\fP \fBGenericSyntaxWalker\&.PreprocessorDirectiveSyntaxList\fP \fBGenericSyntaxWalker\&.DeliminationExtendedSyntaxList\fP 
.PP
Definition at line \fB21\fP of file \fBGenericSyntaxWalkerTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.GenericLexer\&.SyntaxActors\&.GenericSyntaxWalkerTests\&.Visit ()"

.PP
GenericSyntaxWalker\&.Visit(IGenericSyntax) 
.PP
Definition at line \fB30\fP of file \fBGenericSyntaxWalkerTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
