.TH "Luthetus.Extensions.DotNet.CompilerServices.Displays.Internals.SyntaxTextSpanDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.CompilerServices.Displays.Internals.SyntaxTextSpanDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnParametersSet\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "TextEditorTextSpan \fBTextSpan\fP = default!\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB13\fP of file \fBSyntaxTextSpanDisplay\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Luthetus\&.Extensions\&.DotNet\&.CompilerServices\&.Displays\&.Internals\&.SyntaxTextSpanDisplay\&.OnParametersSet ()\fR [protected]\fP"

.PP
Definition at line \fB25\fP of file \fBSyntaxTextSpanDisplay\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "TextEditorTextSpan Luthetus\&.Extensions\&.DotNet\&.CompilerServices\&.Displays\&.Internals\&.SyntaxTextSpanDisplay\&.TextSpan = default!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB19\fP of file \fBSyntaxTextSpanDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
