.TH "Luthetus.Common.Tests.Basis.Storages.Models.DoNothingStorageServiceTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Storages.Models.DoNothingStorageServiceTests \- \fBDoNothingStorageService\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "DoNothingStorageService() "
.ti -1c
.RI "void \fBSetValue\fP ()"
.br
.RI "\fBDoNothingStorageService\&.SetValue(string, object?)\fP "
.ti -1c
.RI "void \fBGetValue\fP ()"
.br
.RI "\fBDoNothingStorageService\&.GetValue(string)\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBDoNothingStorageService\fP 
.PP
Definition at line \fB8\fP of file \fBDoNothingStorageServiceTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Storages\&.Models\&.DoNothingStorageServiceTests\&.Constructor ()"

.PP
DoNothingStorageService() 
.PP
Definition at line \fB17\fP of file \fBDoNothingStorageServiceTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Storages\&.Models\&.DoNothingStorageServiceTests\&.GetValue ()"

.PP
\fBDoNothingStorageService\&.GetValue(string)\fP 
.PP
Definition at line \fB39\fP of file \fBDoNothingStorageServiceTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Storages\&.Models\&.DoNothingStorageServiceTests\&.SetValue ()"

.PP
\fBDoNothingStorageService\&.SetValue(string, object?)\fP 
.PP
Definition at line \fB27\fP of file \fBDoNothingStorageServiceTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
