.TH "Luthetus.Ide.RazorLib.Shareds.Displays.IdeMainLayout" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.Shareds.Displays.IdeMainLayout
.SH SYNOPSIS
.br
.PP
.PP
Inherits LayoutComponentBase, and IDisposable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInitialized\fP ()"
.br
.ti -1c
.RI "override async Task \fBOnAfterRenderAsync\fP (bool firstRender)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB20\fP of file \fBIdeMainLayout\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Ide\&.RazorLib\&.Shareds\&.Displays\&.IdeMainLayout\&.Dispose ()"

.PP
Definition at line \fB131\fP of file \fBIdeMainLayout\&.razor\&.cs\fP\&.
.SS "override async Task Luthetus\&.Ide\&.RazorLib\&.Shareds\&.Displays\&.IdeMainLayout\&.OnAfterRenderAsync (bool firstRender)\fR [protected]\fP"

.PP
Definition at line \fB89\fP of file \fBIdeMainLayout\&.razor\&.cs\fP\&.
.SS "override void Luthetus\&.Ide\&.RazorLib\&.Shareds\&.Displays\&.IdeMainLayout\&.OnInitialized ()\fR [protected]\fP"

.PP
Definition at line \fB55\fP of file \fBIdeMainLayout\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
