.TH "Luthetus.TextEditor.RazorLib.Options.Displays.InputTextEditorFontFamily" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Options.Displays.InputTextEditorFontFamily
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase, and IDisposable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInitialized\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "InputViewModel \fBInputViewModel\fP = \fBInputViewModel\&.Empty\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBFontFamily\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBInputTextEditorFontFamily\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Options\&.Displays\&.InputTextEditorFontFamily\&.Dispose ()"

.PP
Definition at line \fB38\fP of file \fBInputTextEditorFontFamily\&.razor\&.cs\fP\&.
.SS "override void Luthetus\&.TextEditor\&.RazorLib\&.Options\&.Displays\&.InputTextEditorFontFamily\&.OnInitialized ()\fR [protected]\fP"

.PP
Definition at line \fB26\fP of file \fBInputTextEditorFontFamily\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.Options\&.Displays\&.InputTextEditorFontFamily\&.FontFamily\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB14\fP of file \fBInputTextEditorFontFamily\&.razor\&.cs\fP\&.
.SS "InputViewModel Luthetus\&.TextEditor\&.RazorLib\&.Options\&.Displays\&.InputTextEditorFontFamily\&.InputViewModel = \fBInputViewModel\&.Empty\fP\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB12\fP of file \fBInputTextEditorFontFamily\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
