.TH "Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorRenderBatchValidated" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorRenderBatchValidated
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ITextEditorRenderBatch\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextEditorRenderBatchValidated\fP (TextEditorRenderBatchUnsafe textEditorRenderBatchUnsafe)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBTextEditorModel\fP \fBModel\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBTextEditorViewModel\fP \fBViewModel\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBTextEditorOptions\fP \fBOptions\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBFontFamily\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBFontSizeInPixels\fP\fR [get]\fP"
.br
.ti -1c
.RI "ViewModelDisplayOptions \fBViewModelDisplayOptions\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBTextEditorComponentData\fP \fBComponentData\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBFontFamilyCssStyle\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBFontSizeInPixelsCssStyle\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBHeightCssStyle\fP\fR [get]\fP"
.br
.ti -1c
.RI "double \fBGutterWidthInPixels\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsValid\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Attributes inherited from \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ITextEditorRenderBatch\fP
.in +1c
.ti -1c
.RI "const string \fBDEFAULT_FONT_FAMILY\fP = 'monospace'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBTextEditorRenderBatchValidated\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.TextEditorRenderBatchValidated\&.TextEditorRenderBatchValidated (TextEditorRenderBatchUnsafe textEditorRenderBatchUnsafe)"

.PP
Definition at line \fB7\fP of file \fBTextEditorRenderBatchValidated\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBTextEditorComponentData\fP Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.TextEditorRenderBatchValidated\&.ComponentData\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ITextEditorRenderBatch\fP\&.
.PP
Definition at line \fB32\fP of file \fBTextEditorRenderBatchValidated\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.TextEditorRenderBatchValidated\&.FontFamily\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ITextEditorRenderBatch\fP\&.
.PP
Definition at line \fB29\fP of file \fBTextEditorRenderBatchValidated\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.TextEditorRenderBatchValidated\&.FontFamilyCssStyle\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ITextEditorRenderBatch\fP\&.
.PP
Definition at line \fB33\fP of file \fBTextEditorRenderBatchValidated\&.cs\fP\&.
.SS "int Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.TextEditorRenderBatchValidated\&.FontSizeInPixels\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ITextEditorRenderBatch\fP\&.
.PP
Definition at line \fB30\fP of file \fBTextEditorRenderBatchValidated\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.TextEditorRenderBatchValidated\&.FontSizeInPixelsCssStyle\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ITextEditorRenderBatch\fP\&.
.PP
Definition at line \fB34\fP of file \fBTextEditorRenderBatchValidated\&.cs\fP\&.
.SS "double Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.TextEditorRenderBatchValidated\&.GutterWidthInPixels\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ITextEditorRenderBatch\fP\&.
.PP
Definition at line \fB36\fP of file \fBTextEditorRenderBatchValidated\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.TextEditorRenderBatchValidated\&.HeightCssStyle\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ITextEditorRenderBatch\fP\&.
.PP
Definition at line \fB35\fP of file \fBTextEditorRenderBatchValidated\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.TextEditorRenderBatchValidated\&.IsValid\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ITextEditorRenderBatch\fP\&.
.PP
Definition at line \fB37\fP of file \fBTextEditorRenderBatchValidated\&.cs\fP\&.
.SS "\fBTextEditorModel\fP Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.TextEditorRenderBatchValidated\&.Model\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ITextEditorRenderBatch\fP\&.
.PP
Definition at line \fB26\fP of file \fBTextEditorRenderBatchValidated\&.cs\fP\&.
.SS "\fBTextEditorOptions\fP Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.TextEditorRenderBatchValidated\&.Options\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ITextEditorRenderBatch\fP\&.
.PP
Definition at line \fB28\fP of file \fBTextEditorRenderBatchValidated\&.cs\fP\&.
.SS "\fBTextEditorViewModel\fP Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.TextEditorRenderBatchValidated\&.ViewModel\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ITextEditorRenderBatch\fP\&.
.PP
Definition at line \fB27\fP of file \fBTextEditorRenderBatchValidated\&.cs\fP\&.
.SS "ViewModelDisplayOptions Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.TextEditorRenderBatchValidated\&.ViewModelDisplayOptions\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ITextEditorRenderBatch\fP\&.
.PP
Definition at line \fB31\fP of file \fBTextEditorRenderBatchValidated\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
