.TH "Luthetus.Common.RazorLib.BackgroundTasks.Models.BlockingBackgroundTaskWorker" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.BackgroundTasks.Models.BlockingBackgroundTaskWorker \- The \fBBlockingBackgroundTaskWorker\fP should be assumed to never be immediately available, that one always will wait in a queue for a user-noticeable amount of time\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.BackgroundTaskWorker\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBlockingBackgroundTaskWorker\fP (\fBIBackgroundTaskService\fP backgroundTaskService, ILoggerFactory loggerFactory)"
.br
.in -1c

Public Member Functions inherited from \fBLuthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.BackgroundTaskWorker\fP
.in +1c
.ti -1c
.RI "\fBBackgroundTaskWorker\fP (Key< \fBIBackgroundTaskQueue\fP > queueKey, \fBIBackgroundTaskService\fP backgroundTaskService, ILoggerFactory loggerFactory)"
.br
.ti -1c
.RI "async Task \fBFlushAsync\fP (CancellationToken cancellationToken)"
.br
.RI "This method is being created so a unit test can enqueue a background task, and then await its completion\&. "
.ti -1c
.RI "override async Task \fBStopAsync\fP (CancellationToken cancellationToken)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Key< \fBIBackgroundTaskQueue\fP > \fBGetQueueKey\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBQUEUE_DISPLAY_NAME\fP = 'BlockingBackgroundTaskWorker'"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBLuthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.BackgroundTaskWorker\fP
.in +1c
.ti -1c
.RI "async override Task \fBExecuteAsync\fP (CancellationToken cancellationToken)"
.br
.in -1c

Properties inherited from \fBLuthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.BackgroundTaskWorker\fP
.in +1c
.ti -1c
.RI "Key< \fBIBackgroundTaskQueue\fP > \fBQueueKey\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBIBackgroundTaskService\fP \fBBackgroundTaskService\fP\fR [get]\fP"
.br
.ti -1c
.RI "Task? \fBStartAsyncTask\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBBlockingBackgroundTaskWorker\fP should be assumed to never be immediately available, that one always will wait in a queue for a user-noticeable amount of time\&. 
.PP
Definition at line \fB11\fP of file \fBBlockingBackgroundTaskWorker\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.BlockingBackgroundTaskWorker\&.BlockingBackgroundTaskWorker (\fBIBackgroundTaskService\fP backgroundTaskService, ILoggerFactory loggerFactory)"

.PP
Definition at line \fB17\fP of file \fBBlockingBackgroundTaskWorker\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "Key< \fBIBackgroundTaskQueue\fP > Luthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.BlockingBackgroundTaskWorker\&.GetQueueKey ()\fR [static]\fP"

.SH "Member Data Documentation"
.PP 
.SS "const string Luthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.BlockingBackgroundTaskWorker\&.QUEUE_DISPLAY_NAME = 'BlockingBackgroundTaskWorker'\fR [static]\fP"

.PP
Definition at line \fB13\fP of file \fBBlockingBackgroundTaskWorker\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
