.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.GenericLexer.SyntaxObjects.GenericPreprocessorDirectiveSyntaxTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.GenericLexer.SyntaxObjects.GenericPreprocessorDirectiveSyntaxTests \- \fBGenericPreprocessorDirectiveSyntax\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "GenericPreprocessorDirectiveSyntax(TextEditorTextSpan, ImmutableArray<IGenericSyntax>) 
.br
----
.br
 \fBGenericPreprocessorDirectiveSyntax\&.TextSpan\fP \fBGenericPreprocessorDirectiveSyntax\&.ChildList\fP \fBGenericPreprocessorDirectiveSyntax\&.GenericSyntaxKind\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBGenericPreprocessorDirectiveSyntax\fP 
.PP
Definition at line \fB11\fP of file \fBGenericPreprocessorDirectiveSyntaxTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericPreprocessorDirectiveSyntaxTests\&.Constructor ()"

.PP
GenericPreprocessorDirectiveSyntax(TextEditorTextSpan, ImmutableArray<IGenericSyntax>) 
.br
----
.br
 \fBGenericPreprocessorDirectiveSyntax\&.TextSpan\fP \fBGenericPreprocessorDirectiveSyntax\&.ChildList\fP \fBGenericPreprocessorDirectiveSyntax\&.GenericSyntaxKind\fP 
.PP
Definition at line \fB21\fP of file \fBGenericPreprocessorDirectiveSyntaxTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
