.TH "Luthetus.Common.RazorLib.Drags.Models.DragService" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Drags.Models.DragService
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Common\&.RazorLib\&.Drags\&.Models\&.IDragService\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDragService\fP (IDispatcher dispatcher, IState< \fBDragState\fP > dragStateWrap)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IState< \fBDragState\fP > \fBDragStateWrap\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBDragService\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Common\&.RazorLib\&.Drags\&.Models\&.DragService\&.DragService (IDispatcher dispatcher, IState< \fBDragState\fP > dragStateWrap)"

.PP
Definition at line \fB10\fP of file \fBDragService\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "IState<\fBDragState\fP> Luthetus\&.Common\&.RazorLib\&.Drags\&.Models\&.DragService\&.DragStateWrap\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.Drags\&.Models\&.IDragService\fP\&.
.PP
Definition at line \fB18\fP of file \fBDragService\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
