.TH "Luthetus.CompilerServices.DotNetSolution.Models.Project.SolutionFolder" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.DotNetSolution.Models.Project.SolutionFolder
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.IDotNetProject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSolutionFolder\fP (string displayName, Guid projectTypeGuid, string relativePathFromSolutionFileString, Guid projectIdGuid, \fBOpenAssociatedGroupToken\fP openAssociatedGroupToken, \fBCloseAssociatedGroupToken\fP? closeAssociatedGroupToken, \fBIAbsolutePath\fP absolutePath)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly Guid \fBSolutionFolderProjectTypeGuid\fP = Guid\&.Parse('2150E333\-8FDC\-42A3\-9474\-1A3956D46DE8')"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBDisplayName\fP\fR [get]\fP"
.br
.ti -1c
.RI "Guid \fBProjectTypeGuid\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBRelativePathFromSolutionFileString\fP\fR [get]\fP"
.br
.ti -1c
.RI "Guid \fBProjectIdGuid\fP\fR [get]\fP"
.br
.ti -1c
.RI "OpenAssociatedGroupToken \fBOpenAssociatedGroupToken\fP\fR [get, set]\fP"
.br
.RI "TODO: Remove the "set;" hack\&. Added so one can shift text spans when the \&.sln content is modified\&. (2023-10-10))\&. "
.ti -1c
.RI "CloseAssociatedGroupToken? \fBCloseAssociatedGroupToken\fP\fR [get, set]\fP"
.br
.RI "TODO: Remove the "set;" hack\&. Added so one can shift text spans when the \&.sln content is modified\&. (2023-10-10))\&. "
.ti -1c
.RI "\fBIAbsolutePath\fP \fBAbsolutePath\fP\fR [get, set]\fP"
.br
.RI "TODO: Remove the "set;" hack\&. "
.ti -1c
.RI "\fBDotNetProjectKind\fP \fBDotNetProjectKind\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBSolutionFolder\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.SolutionFolder\&.SolutionFolder (string displayName, Guid projectTypeGuid, string relativePathFromSolutionFileString, Guid projectIdGuid, \fBOpenAssociatedGroupToken\fP openAssociatedGroupToken, \fBCloseAssociatedGroupToken\fP? closeAssociatedGroupToken, \fBIAbsolutePath\fP absolutePath)"

.PP
Definition at line \fB10\fP of file \fBSolutionFolder\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly Guid Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.SolutionFolder\&.SolutionFolderProjectTypeGuid = Guid\&.Parse('2150E333\-8FDC\-42A3\-9474\-1A3956D46DE8')\fR [static]\fP"

.PP
Definition at line \fB8\fP of file \fBSolutionFolder\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBIAbsolutePath\fP Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.SolutionFolder\&.AbsolutePath\fR [get]\fP, \fR [set]\fP"

.PP
TODO: Remove the "set;" hack\&. 
.PP
Implements \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.IDotNetProject\fP\&.
.PP
Definition at line \fB34\fP of file \fBSolutionFolder\&.cs\fP\&.
.SS "CloseAssociatedGroupToken? Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.SolutionFolder\&.CloseAssociatedGroupToken\fR [get]\fP, \fR [set]\fP"

.PP
TODO: Remove the "set;" hack\&. Added so one can shift text spans when the \&.sln content is modified\&. (2023-10-10))\&. 
.PP
Implements \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.IDotNetProject\fP\&.
.PP
Definition at line \fB33\fP of file \fBSolutionFolder\&.cs\fP\&.
.SS "string Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.SolutionFolder\&.DisplayName\fR [get]\fP"

.PP
Implements \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.IDotNetProject\fP\&.
.PP
Definition at line \fB28\fP of file \fBSolutionFolder\&.cs\fP\&.
.SS "\fBDotNetProjectKind\fP Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.SolutionFolder\&.DotNetProjectKind\fR [get]\fP"

.PP
Implements \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.IDotNetProject\fP\&.
.PP
Definition at line \fB35\fP of file \fBSolutionFolder\&.cs\fP\&.
.SS "OpenAssociatedGroupToken Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.SolutionFolder\&.OpenAssociatedGroupToken\fR [get]\fP, \fR [set]\fP"

.PP
TODO: Remove the "set;" hack\&. Added so one can shift text spans when the \&.sln content is modified\&. (2023-10-10))\&. 
.PP
Implements \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.IDotNetProject\fP\&.
.PP
Definition at line \fB32\fP of file \fBSolutionFolder\&.cs\fP\&.
.SS "Guid Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.SolutionFolder\&.ProjectIdGuid\fR [get]\fP"

.PP
Implements \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.IDotNetProject\fP\&.
.PP
Definition at line \fB31\fP of file \fBSolutionFolder\&.cs\fP\&.
.SS "Guid Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.SolutionFolder\&.ProjectTypeGuid\fR [get]\fP"

.PP
Implements \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.IDotNetProject\fP\&.
.PP
Definition at line \fB29\fP of file \fBSolutionFolder\&.cs\fP\&.
.SS "string Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.SolutionFolder\&.RelativePathFromSolutionFileString\fR [get]\fP"

.PP
Implements \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.IDotNetProject\fP\&.
.PP
Definition at line \fB30\fP of file \fBSolutionFolder\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
