.TH "Luthetus.Extensions.DotNet.DotNetSolutions.Displays.DotNetSolutionFormDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.DotNetSolutions.Displays.DotNetSolutionFormDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits FluxorComponent\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBHackForWebsite_NEW_SOLUTION_TEMPLATE\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBIDialog\fP \fBDialogRecord\fP = null!\fR [get, set]\fP"
.br
.ti -1c
.RI "Key< \fBTerminalCommandRequest\fP > \fBNewDotNetSolutionTerminalCommandRequestKey\fP = Key<\fBTerminalCommandRequest\fP>\&.NewKey()\fR [get]\fP"
.br
.ti -1c
.RI "CancellationTokenSource \fBNewDotNetSolutionCancellationTokenSource\fP = new()\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB24\fP of file \fBDotNetSolutionFormDisplay\&.razor\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const string Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Displays\&.DotNetSolutionFormDisplay\&.HackForWebsite_NEW_SOLUTION_TEMPLATE\fR [static]\fP"
\fBInitial value:\fP
.nf
= @"
Microsoft Visual Studio Solution File, Format Version 12\&.00
# Visual Studio Version 17
VisualStudioVersion = 17\&.7\&.34018\&.315
MinimumVisualStudioVersion = 10\&.0\&.40219\&.1
Global
    GlobalSection(SolutionConfigurationPlatforms) = preSolution
        Debug|Any CPU = Debug|Any CPU
        Release|Any CPU = Release|Any CPU
    EndGlobalSection
    GlobalSection(ProjectConfigurationPlatforms) = postSolution
        {EC571C96\-8996\-402C\-B44A\-264F84598795}\&.Debug|Any CPU\&.ActiveCfg = Debug|Any CPU
        {EC571C96\-8996\-402C\-B44A\-264F84598795}\&.Debug|Any CPU\&.Build\&.0 = Debug|Any CPU
        {EC571C96\-8996\-402C\-B44A\-264F84598795}\&.Release|Any CPU\&.ActiveCfg = Release|Any CPU
        {EC571C96\-8996\-402C\-B44A\-264F84598795}\&.Release|Any CPU\&.Build\&.0 = Release|Any CPU
    EndGlobalSection
    GlobalSection(SolutionProperties) = preSolution
        HideSolutionNode = FALSE
    EndGlobalSection
    GlobalSection(ExtensibilityGlobals) = postSolution
        SolutionGuid = {CC0E8FC7\-3D42\-4480\-BAF6\-86D1E2F2289E}
    EndGlobalSection
EndGlobal
"
.PP
.fi

.PP
Definition at line \fB184\fP of file \fBDotNetSolutionFormDisplay\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBIDialog\fP Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Displays\&.DotNetSolutionFormDisplay\&.DialogRecord = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB46\fP of file \fBDotNetSolutionFormDisplay\&.razor\&.cs\fP\&.
.SS "CancellationTokenSource Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Displays\&.DotNetSolutionFormDisplay\&.NewDotNetSolutionCancellationTokenSource = new()\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB52\fP of file \fBDotNetSolutionFormDisplay\&.razor\&.cs\fP\&.
.SS "Key<\fBTerminalCommandRequest\fP> Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Displays\&.DotNetSolutionFormDisplay\&.NewDotNetSolutionTerminalCommandRequestKey = Key<\fBTerminalCommandRequest\fP>\&.NewKey()\fR [get]\fP"

.PP
Definition at line \fB51\fP of file \fBDotNetSolutionFormDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
