.TH "Luthetus.Common.Tests.Basis.FileSystems.Models.InMemoryFileHandlerTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.FileSystems.Models.InMemoryFileHandlerTests \- InMemoryFileSystemProvider\&.File  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.ti -1c
.RI "async Task \fBExistsAsync\fP ()"
.br
.ti -1c
.RI "async Task \fBDeleteAsync\fP ()"
.br
.ti -1c
.RI "async Task \fBCopyAsync\fP ()"
.br
.ti -1c
.RI "async Task \fBMoveAsync\fP ()"
.br
.ti -1c
.RI "async Task \fBGetLastWriteTimeAsync\fP ()"
.br
.ti -1c
.RI "async Task \fBReadAllTextAsync\fP ()"
.br
.ti -1c
.RI "async Task \fBWriteAllTextAsync\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
InMemoryFileSystemProvider\&.File 
.PP
Definition at line \fB11\fP of file \fBInMemoryFileHandlerTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.FileSystems\&.Models\&.InMemoryFileHandlerTests\&.Constructor ()"

.PP
Definition at line \fB14\fP of file \fBInMemoryFileHandlerTests\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.Tests\&.Basis\&.FileSystems\&.Models\&.InMemoryFileHandlerTests\&.CopyAsync ()"

.PP
Definition at line \fB73\fP of file \fBInMemoryFileHandlerTests\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.Tests\&.Basis\&.FileSystems\&.Models\&.InMemoryFileHandlerTests\&.DeleteAsync ()"

.PP
Definition at line \fB53\fP of file \fBInMemoryFileHandlerTests\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.Tests\&.Basis\&.FileSystems\&.Models\&.InMemoryFileHandlerTests\&.ExistsAsync ()"

.PP
Definition at line \fB32\fP of file \fBInMemoryFileHandlerTests\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.Tests\&.Basis\&.FileSystems\&.Models\&.InMemoryFileHandlerTests\&.GetLastWriteTimeAsync ()"

.PP
Definition at line \fB143\fP of file \fBInMemoryFileHandlerTests\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.Tests\&.Basis\&.FileSystems\&.Models\&.InMemoryFileHandlerTests\&.MoveAsync ()"

.PP
Definition at line \fB107\fP of file \fBInMemoryFileHandlerTests\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.Tests\&.Basis\&.FileSystems\&.Models\&.InMemoryFileHandlerTests\&.ReadAllTextAsync ()"

.PP
Definition at line \fB164\fP of file \fBInMemoryFileHandlerTests\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.Tests\&.Basis\&.FileSystems\&.Models\&.InMemoryFileHandlerTests\&.WriteAllTextAsync ()"

.PP
Definition at line \fB182\fP of file \fBInMemoryFileHandlerTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
