.TH "Luthetus.CompilerServices.Xml.Html.IHtmlSyntax" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.Xml.Html.IHtmlSyntax
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.IHtmlSyntaxNode\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBHtmlSyntaxKind\fP \fBHtmlSyntaxKind\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBIHtmlSyntax\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBHtmlSyntaxKind\fP Luthetus\&.CompilerServices\&.Xml\&.Html\&.IHtmlSyntax\&.HtmlSyntaxKind\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.AttributeNameNode\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.AttributeNode\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.AttributeValueNode\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.CommentNode\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.InjectedLanguageFragmentNode\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.TagNameNode\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.TagNode\fP, and \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.TextNode\fP\&.
.PP
Definition at line \fB7\fP of file \fBIHtmlSyntax\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
