.TH "Luthetus.TextEditor.RazorLib.Options.Displays.InputTextEditorHeight" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Options.Displays.InputTextEditorHeight
.SH SYNOPSIS
.br
.PP
.PP
Inherits FluxorComponent\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBGetIsDisabledCssClassString\fP (bool globalHeightInPixelsValueIsNull)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBCascadingInputElementCssClass\fP = string\&.Empty\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBTopLevelDivElementCssClassString\fP = string\&.Empty\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBInputElementCssClassString\fP = string\&.Empty\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBLabelElementCssClassString\fP = string\&.Empty\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBCheckboxElementCssClassString\fP = string\&.Empty\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBInputTextEditorHeight\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.Options\&.Displays\&.InputTextEditorHeight\&.GetIsDisabledCssClassString (bool globalHeightInPixelsValueIsNull)"

.PP
Definition at line \fB42\fP of file \fBInputTextEditorHeight\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.Options\&.Displays\&.InputTextEditorHeight\&.CascadingInputElementCssClass = string\&.Empty\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB17\fP of file \fBInputTextEditorHeight\&.razor\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.Options\&.Displays\&.InputTextEditorHeight\&.CheckboxElementCssClassString = string\&.Empty\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB26\fP of file \fBInputTextEditorHeight\&.razor\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.Options\&.Displays\&.InputTextEditorHeight\&.InputElementCssClassString = string\&.Empty\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB22\fP of file \fBInputTextEditorHeight\&.razor\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.Options\&.Displays\&.InputTextEditorHeight\&.LabelElementCssClassString = string\&.Empty\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB24\fP of file \fBInputTextEditorHeight\&.razor\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.Options\&.Displays\&.InputTextEditorHeight\&.TopLevelDivElementCssClassString = string\&.Empty\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB20\fP of file \fBInputTextEditorHeight\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
