.TH "Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IDirectoryHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInMemoryDirectoryHandler\fP (\fBInMemoryFileSystemProvider\fP inMemoryFileSystemProvider, \fBIEnvironmentProvider\fP environmentProvider, \fBICommonComponentRenderers\fP commonComponentRenderers, IDispatcher dispatcher)"
.br
.ti -1c
.RI "Task< bool > \fBExistsAsync\fP (string absolutePathString, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "async Task \fBCreateDirectoryAsync\fP (string absolutePathString, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "async Task \fBDeleteAsync\fP (string absolutePathString, bool recursive, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "async Task \fBCopyAsync\fP (string sourceAbsoluteFileString, string destinationAbsolutePathString, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "async Task \fBMoveAsync\fP (string sourceAbsolutePathString, string destinationAbsolutePathString, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "Task< string[]> \fBGetDirectoriesAsync\fP (string absolutePathString, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "Task< string[]> \fBGetFilesAsync\fP (string absolutePathString, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "async Task< IEnumerable< string > > \fBEnumerateFileSystemEntriesAsync\fP (string absolutePathString, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "Task< bool > \fBUnsafeExistsAsync\fP (string absolutePathString, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "Task \fBUnsafeCreateDirectoryAsync\fP (string absolutePathString, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "async Task \fBUnsafeDeleteAsync\fP (string absolutePathString, bool recursive, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "async Task \fBUnsafeCopyAsync\fP (string sourceAbsolutePathString, string destinationAbsolutePathString, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "async Task \fBUnsafeMoveAsync\fP (string sourceAbsolutePathString, string destinationAbsolutePathString, CancellationToken cancellationToken=default)"
.br
.RI "destinationAbsolutePathString refers to the newly created dir not the parent dir which will contain it "
.ti -1c
.RI "Task< string[]> \fBUnsafeGetDirectoriesAsync\fP (string absolutePathString, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "Task< string[]> \fBUnsafeGetFilesAsync\fP (string absolutePathString, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "async Task< IEnumerable< string > > \fBUnsafeEnumerateFileSystemEntriesAsync\fP (string absolutePathString, CancellationToken cancellationToken=default)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBInMemoryFileSystemProvider\&.DirectoryHandler\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryDirectoryHandler\&.InMemoryDirectoryHandler (\fBInMemoryFileSystemProvider\fP inMemoryFileSystemProvider, \fBIEnvironmentProvider\fP environmentProvider, \fBICommonComponentRenderers\fP commonComponentRenderers, IDispatcher dispatcher)"

.PP
Definition at line \fB18\fP of file \fBInMemoryFileSystemProvider\&.DirectoryHandler\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "async Task Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryDirectoryHandler\&.CopyAsync (string sourceAbsoluteFileString, string destinationAbsolutePathString, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IDirectoryHandler\fP\&.
.PP
Definition at line \fB83\fP of file \fBInMemoryFileSystemProvider\&.DirectoryHandler\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryDirectoryHandler\&.CreateDirectoryAsync (string absolutePathString, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IDirectoryHandler\fP\&.
.PP
Definition at line \fB37\fP of file \fBInMemoryFileSystemProvider\&.DirectoryHandler\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryDirectoryHandler\&.DeleteAsync (string absolutePathString, bool recursive, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IDirectoryHandler\fP\&.
.PP
Definition at line \fB57\fP of file \fBInMemoryFileSystemProvider\&.DirectoryHandler\&.cs\fP\&.
.SS "async Task< IEnumerable< string > > Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryDirectoryHandler\&.EnumerateFileSystemEntriesAsync (string absolutePathString, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IDirectoryHandler\fP\&.
.PP
Definition at line \fB149\fP of file \fBInMemoryFileSystemProvider\&.DirectoryHandler\&.cs\fP\&.
.SS "Task< bool > Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryDirectoryHandler\&.ExistsAsync (string absolutePathString, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IDirectoryHandler\fP\&.
.PP
Definition at line \fB30\fP of file \fBInMemoryFileSystemProvider\&.DirectoryHandler\&.cs\fP\&.
.SS "Task< string[]> Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryDirectoryHandler\&.GetDirectoriesAsync (string absolutePathString, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IDirectoryHandler\fP\&.
.PP
Definition at line \fB135\fP of file \fBInMemoryFileSystemProvider\&.DirectoryHandler\&.cs\fP\&.
.SS "Task< string[]> Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryDirectoryHandler\&.GetFilesAsync (string absolutePathString, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IDirectoryHandler\fP\&.
.PP
Definition at line \fB142\fP of file \fBInMemoryFileSystemProvider\&.DirectoryHandler\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryDirectoryHandler\&.MoveAsync (string sourceAbsolutePathString, string destinationAbsolutePathString, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IDirectoryHandler\fP\&.
.PP
Definition at line \fB109\fP of file \fBInMemoryFileSystemProvider\&.DirectoryHandler\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryDirectoryHandler\&.UnsafeCopyAsync (string sourceAbsolutePathString, string destinationAbsolutePathString, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Definition at line \fB237\fP of file \fBInMemoryFileSystemProvider\&.DirectoryHandler\&.cs\fP\&.
.SS "Task Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryDirectoryHandler\&.UnsafeCreateDirectoryAsync (string absolutePathString, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Definition at line \fB168\fP of file \fBInMemoryFileSystemProvider\&.DirectoryHandler\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryDirectoryHandler\&.UnsafeDeleteAsync (string absolutePathString, bool recursive, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Definition at line \fB196\fP of file \fBInMemoryFileSystemProvider\&.DirectoryHandler\&.cs\fP\&.
.SS "async Task< IEnumerable< string > > Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryDirectoryHandler\&.UnsafeEnumerateFileSystemEntriesAsync (string absolutePathString, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Definition at line \fB399\fP of file \fBInMemoryFileSystemProvider\&.DirectoryHandler\&.cs\fP\&.
.SS "Task< bool > Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryDirectoryHandler\&.UnsafeExistsAsync (string absolutePathString, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Definition at line \fB159\fP of file \fBInMemoryFileSystemProvider\&.DirectoryHandler\&.cs\fP\&.
.SS "Task< string[]> Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryDirectoryHandler\&.UnsafeGetDirectoriesAsync (string absolutePathString, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Definition at line \fB335\fP of file \fBInMemoryFileSystemProvider\&.DirectoryHandler\&.cs\fP\&.
.SS "Task< string[]> Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryDirectoryHandler\&.UnsafeGetFilesAsync (string absolutePathString, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Definition at line \fB368\fP of file \fBInMemoryFileSystemProvider\&.DirectoryHandler\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryDirectoryHandler\&.UnsafeMoveAsync (string sourceAbsolutePathString, string destinationAbsolutePathString, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
destinationAbsolutePathString refers to the newly created dir not the parent dir which will contain it 
.PP
Definition at line \fB314\fP of file \fBInMemoryFileSystemProvider\&.DirectoryHandler\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
