.TH "Luthetus.TextEditor.Tests.Basis.JavaScriptObjects.Models.TextEditorMeasurementsTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.JavaScriptObjects.Models.TextEditorMeasurementsTests \- TextEditorMeasurements  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "TextEditorMeasurements(double, double, double, double, double, double, double, CancellationToken) 
.br
----
.br
 TextEditorMeasurements\&.ScrollLeft TextEditorMeasurements\&.ScrollTop TextEditorMeasurements\&.ScrollWidth TextEditorMeasurements\&.ScrollHeight TextEditorMeasurements\&.MarginScrollHeight TextEditorMeasurements\&.Width TextEditorMeasurements\&.Height TextEditorMeasurements\&.MeasurementsExpiredCancellationToken "
.in -1c
.SH "Detailed Description"
.PP 
TextEditorMeasurements 
.PP
Definition at line \fB8\fP of file \fBTextEditorMeasurementsTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.JavaScriptObjects\&.Models\&.TextEditorMeasurementsTests\&.Constructor ()"

.PP
TextEditorMeasurements(double, double, double, double, double, double, double, CancellationToken) 
.br
----
.br
 TextEditorMeasurements\&.ScrollLeft TextEditorMeasurements\&.ScrollTop TextEditorMeasurements\&.ScrollWidth TextEditorMeasurements\&.ScrollHeight TextEditorMeasurements\&.MarginScrollHeight TextEditorMeasurements\&.Width TextEditorMeasurements\&.Height TextEditorMeasurements\&.MeasurementsExpiredCancellationToken 
.PP
Definition at line \fB23\fP of file \fBTextEditorMeasurementsTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
