.TH "Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSolutionVisualizationModel\fP (\fBIAbsolutePath\fP? solutionAbsolutePath, Action onStateChangedAction)"
.br
.ti -1c
.RI "\fBSolutionVisualizationModel\fP \fBShallowClone\fP ()"
.br
.ti -1c
.RI "\fBSolutionVisualizationModel\fP \fBMakeDrawing\fP (\fBDotNetSolutionCompilerService\fP dotNetSolutionCompilerService, \fBCSharpProjectCompilerService\fP cSharpProjectCompilerService, \fBCSharpCompilerService\fP cSharpCompilerService)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBRENDER_CYCLE_LIST_CONNECTIONS_INDEX\fP = 0"
.br
.ti -1c
.RI "const int \fBRENDER_CYCLE_LIST_SOLUTION_INDEX\fP = 1"
.br
.ti -1c
.RI "const int \fBRENDER_CYCLE_LIST_PROJECTS_INDEX\fP = 2"
.br
.ti -1c
.RI "const int \fBRENDER_CYCLE_LIST_CLASSES_INDEX\fP = 3"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBIAbsolutePath\fP? \fBSolutionAbsolutePath\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBSolutionVisualizationDimensions\fP \fBDimensions\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "List< \fBISolutionVisualizationDrawing\fP > \fBSolutionVisualizationDrawingList\fP = new()\fR [get, set]\fP"
.br
.ti -1c
.RI "List< List< \fBISolutionVisualizationDrawing\fP > > \fBSolutionVisualizationDrawingRenderCycleList\fP = new()\fR [get, set]\fP"
.br
.ti -1c
.RI "Dictionary< string, \fBISolutionVisualizationDrawing\fP > \fBParentMap\fP = new()\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBSolutionVisualizationModel\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.SolutionVisualizationModel\&.SolutionVisualizationModel (\fBIAbsolutePath\fP? solutionAbsolutePath, Action onStateChangedAction)"

.PP
Definition at line \fB19\fP of file \fBSolutionVisualizationModel\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBSolutionVisualizationModel\fP Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.SolutionVisualizationModel\&.MakeDrawing (\fBDotNetSolutionCompilerService\fP dotNetSolutionCompilerService, \fBCSharpProjectCompilerService\fP cSharpProjectCompilerService, \fBCSharpCompilerService\fP cSharpCompilerService)"

.PP
Definition at line \fB43\fP of file \fBSolutionVisualizationModel\&.cs\fP\&.
.SS "\fBSolutionVisualizationModel\fP Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.SolutionVisualizationModel\&.ShallowClone ()"

.PP
Definition at line \fB32\fP of file \fBSolutionVisualizationModel\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const int Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.SolutionVisualizationModel\&.RENDER_CYCLE_LIST_CLASSES_INDEX = 3\fR [static]\fP"

.PP
Definition at line \fB15\fP of file \fBSolutionVisualizationModel\&.cs\fP\&.
.SS "const int Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.SolutionVisualizationModel\&.RENDER_CYCLE_LIST_CONNECTIONS_INDEX = 0\fR [static]\fP"

.PP
Definition at line \fB12\fP of file \fBSolutionVisualizationModel\&.cs\fP\&.
.SS "const int Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.SolutionVisualizationModel\&.RENDER_CYCLE_LIST_PROJECTS_INDEX = 2\fR [static]\fP"

.PP
Definition at line \fB14\fP of file \fBSolutionVisualizationModel\&.cs\fP\&.
.SS "const int Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.SolutionVisualizationModel\&.RENDER_CYCLE_LIST_SOLUTION_INDEX = 1\fR [static]\fP"

.PP
Definition at line \fB13\fP of file \fBSolutionVisualizationModel\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBSolutionVisualizationDimensions\fP Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.SolutionVisualizationModel\&.Dimensions\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB27\fP of file \fBSolutionVisualizationModel\&.cs\fP\&.
.SS "Dictionary<string, \fBISolutionVisualizationDrawing\fP> Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.SolutionVisualizationModel\&.ParentMap = new()\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB30\fP of file \fBSolutionVisualizationModel\&.cs\fP\&.
.SS "\fBIAbsolutePath\fP? Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.SolutionVisualizationModel\&.SolutionAbsolutePath\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB26\fP of file \fBSolutionVisualizationModel\&.cs\fP\&.
.SS "List<\fBISolutionVisualizationDrawing\fP> Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.SolutionVisualizationModel\&.SolutionVisualizationDrawingList = new()\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB28\fP of file \fBSolutionVisualizationModel\&.cs\fP\&.
.SS "List<List<\fBISolutionVisualizationDrawing\fP> > Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.SolutionVisualizationModel\&.SolutionVisualizationDrawingRenderCycleList = new()\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB29\fP of file \fBSolutionVisualizationModel\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
