.TH "Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ReturnStatementNode" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ReturnStatementNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.ISyntaxNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReturnStatementNode\fP (\fBKeywordToken\fP keywordToken, \fBIExpressionNode\fP expressionNode)"
.br
.ti -1c
.RI "\fBISyntax\fP[] \fBGetChildList\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "KeywordToken \fBKeywordToken\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBIExpressionNode\fP \fBExpressionNode\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsFabricated\fP\fR [get]\fP"
.br
.RI "\fBIsFabricated\fP refers to when the ParserSession expected a node to be valid, but it wasn't\&.
.br

.br
For example, a function invocation on an undefined function will construct a BoundFunctionInvocationNode with \fBIsFabricated\fP set to true\&. "
.ti -1c
.RI "\fBSyntaxKind\fP \fBSyntaxKind\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBReturnStatementNode\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.ReturnStatementNode\&.ReturnStatementNode (\fBKeywordToken\fP keywordToken, \fBIExpressionNode\fP expressionNode)"

.PP
Definition at line \fB9\fP of file \fBReturnStatementNode\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBISyntax\fP[] Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.ReturnStatementNode\&.GetChildList ()"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.ISyntaxNode\fP\&.
.PP
Definition at line \fB24\fP of file \fBReturnStatementNode\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBIExpressionNode\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.ReturnStatementNode\&.ExpressionNode\fR [get]\fP"

.PP
Definition at line \fB19\fP of file \fBReturnStatementNode\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.ReturnStatementNode\&.IsFabricated\fR [get]\fP"

.PP
\fBIsFabricated\fP refers to when the ParserSession expected a node to be valid, but it wasn't\&.
.br

.br
For example, a function invocation on an undefined function will construct a BoundFunctionInvocationNode with \fBIsFabricated\fP set to true\&. 
.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.ISyntax\fP\&.
.PP
Definition at line \fB21\fP of file \fBReturnStatementNode\&.cs\fP\&.
.SS "KeywordToken Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.ReturnStatementNode\&.KeywordToken\fR [get]\fP"

.PP
Definition at line \fB18\fP of file \fBReturnStatementNode\&.cs\fP\&.
.SS "\fBSyntaxKind\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.ReturnStatementNode\&.SyntaxKind\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.ISyntax\fP\&.
.PP
Definition at line \fB22\fP of file \fBReturnStatementNode\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
