.TH "Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextEditorPartition\fP (List< \fBRichCharacter\fP > richCharacterList)"
.br
.ti -1c
.RI "\fBTextEditorPartition\fP \fBInsert\fP (int relativePositionIndex, \fBRichCharacter\fP richCharacter)"
.br
.ti -1c
.RI "\fBTextEditorPartition\fP \fBInsertRange\fP (int relativePositionIndex, IEnumerable< \fBRichCharacter\fP > richCharacterList)"
.br
.ti -1c
.RI "\fBTextEditorPartition\fP \fBRemoveAt\fP (int relativePositionIndex)"
.br
.ti -1c
.RI "\fBTextEditorPartition\fP \fBRemoveRange\fP (int relativePositionIndex, int count)"
.br
.ti -1c
.RI "\fBTextEditorPartition\fP \fBAddRange\fP (IEnumerable< \fBRichCharacter\fP > richCharacterList)"
.br
.ti -1c
.RI "\fBTextEditorPartition\fP \fBSetItem\fP (int relativePositionIndex, \fBRichCharacter\fP richCharacter)"
.br
.RI "If either character or decoration byte are 'null', then the respective collection will be left unchanged\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "List< \fBRichCharacter\fP > \fBRichCharacterList\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBCount\fP\fR [get]\fP"
.br
.RI "This is the count of rich characters in THIS particular partition, the TextEditorModel\&.DocumentLength contains the whole count of rich characters across all partitions\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBTextEditorPartition\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.TextEditorPartition\&.TextEditorPartition (List< \fBRichCharacter\fP > richCharacterList)"

.PP
Definition at line \fB7\fP of file \fBTextEditorPartition\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBTextEditorPartition\fP Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.TextEditorPartition\&.AddRange (IEnumerable< \fBRichCharacter\fP > richCharacterList)"

.PP
Definition at line \fB52\fP of file \fBTextEditorPartition\&.cs\fP\&.
.SS "\fBTextEditorPartition\fP Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.TextEditorPartition\&.Insert (int relativePositionIndex, \fBRichCharacter\fP richCharacter)"

.PP
Definition at line \fB20\fP of file \fBTextEditorPartition\&.cs\fP\&.
.SS "\fBTextEditorPartition\fP Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.TextEditorPartition\&.InsertRange (int relativePositionIndex, IEnumerable< \fBRichCharacter\fP > richCharacterList)"

.PP
Definition at line \fB29\fP of file \fBTextEditorPartition\&.cs\fP\&.
.SS "\fBTextEditorPartition\fP Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.TextEditorPartition\&.RemoveAt (int relativePositionIndex)"

.PP
Definition at line \fB38\fP of file \fBTextEditorPartition\&.cs\fP\&.
.SS "\fBTextEditorPartition\fP Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.TextEditorPartition\&.RemoveRange (int relativePositionIndex, int count)"

.PP
Definition at line \fB45\fP of file \fBTextEditorPartition\&.cs\fP\&.
.SS "\fBTextEditorPartition\fP Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.TextEditorPartition\&.SetItem (int relativePositionIndex, \fBRichCharacter\fP richCharacter)"

.PP
If either character or decoration byte are 'null', then the respective collection will be left unchanged\&. i\&.e\&.: to change ONLY a character value invoke this method with decorationByte set to null, and only the CharList will be changed\&. 
.PP
Definition at line \fB64\fP of file \fBTextEditorPartition\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.TextEditorPartition\&.Count\fR [get]\fP"

.PP
This is the count of rich characters in THIS particular partition, the TextEditorModel\&.DocumentLength contains the whole count of rich characters across all partitions\&. 
.PP
Definition at line \fB18\fP of file \fBTextEditorPartition\&.cs\fP\&.
.SS "List<\fBRichCharacter\fP> Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.TextEditorPartition\&.RichCharacterList\fR [get]\fP"

.PP
Definition at line \fB12\fP of file \fBTextEditorPartition\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
