.TH "Luthetus.Common.RazorLib.WatchWindows.Displays.TreeViewMissingRendererFallbackDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.WatchWindows.Displays.TreeViewMissingRendererFallbackDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase, and \fBLuthetus\&.Common\&.RazorLib\&.ComponentRenderers\&.Models\&.ITreeViewMissingRendererFallbackType\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBDisplayText\fP = string\&.Empty\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBTreeViewMissingRendererFallbackDisplay\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Luthetus\&.Common\&.RazorLib\&.WatchWindows\&.Displays\&.TreeViewMissingRendererFallbackDisplay\&.DisplayText = string\&.Empty\fR [get]\fP, \fR [set]\fP"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.ComponentRenderers\&.Models\&.ITreeViewMissingRendererFallbackType\fP\&.
.PP
Definition at line \fB10\fP of file \fBTreeViewMissingRendererFallbackDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
