.TH "Luthetus.CompilerServices.DotNetSolution.Models.Project.CSharpProjectModel" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.DotNetSolution.Models.Project.CSharpProjectModel
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.IDotNetProject\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCSharpProjectModel\fP (string displayName, Guid projectTypeGuid, string relativePathFromSolutionFileString, Guid projectIdGuid, \fBOpenAssociatedGroupToken\fP openAssociatedGroupToken, \fBCloseAssociatedGroupToken\fP? closeAssociatedGroupToken, \fBIAbsolutePath\fP absolutePath)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBDisplayName\fP\fR [get]\fP"
.br
.ti -1c
.RI "Guid \fBProjectTypeGuid\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBRelativePathFromSolutionFileString\fP\fR [get]\fP"
.br
.ti -1c
.RI "Guid \fBProjectIdGuid\fP\fR [get]\fP"
.br
.ti -1c
.RI "OpenAssociatedGroupToken \fBOpenAssociatedGroupToken\fP\fR [get, set]\fP"
.br
.RI "TODO: Remove the "set;" hack\&. Added so one can shift text spans when the \&.sln content is modified\&. (2023-10-10))\&. "
.ti -1c
.RI "CloseAssociatedGroupToken? \fBCloseAssociatedGroupToken\fP\fR [get, set]\fP"
.br
.RI "TODO: Remove the "set;" hack\&. Added so one can shift text spans when the \&.sln content is modified\&. (2023-10-10))\&. "
.ti -1c
.RI "\fBIAbsolutePath\fP \fBAbsolutePath\fP\fR [get, set]\fP"
.br
.RI "TODO: Remove the "set;" hack\&. "
.ti -1c
.RI "\fBDotNetProjectKind\fP \fBDotNetProjectKind\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBCSharpProject\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.CSharpProjectModel\&.CSharpProjectModel (string displayName, Guid projectTypeGuid, string relativePathFromSolutionFileString, Guid projectIdGuid, \fBOpenAssociatedGroupToken\fP openAssociatedGroupToken, \fBCloseAssociatedGroupToken\fP? closeAssociatedGroupToken, \fBIAbsolutePath\fP absolutePath)"

.PP
Definition at line \fB8\fP of file \fBCSharpProject\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBIAbsolutePath\fP Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.CSharpProjectModel\&.AbsolutePath\fR [get]\fP, \fR [set]\fP"

.PP
TODO: Remove the "set;" hack\&. 
.PP
Implements \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.IDotNetProject\fP\&.
.PP
Definition at line \fB32\fP of file \fBCSharpProject\&.cs\fP\&.
.SS "CloseAssociatedGroupToken? Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.CSharpProjectModel\&.CloseAssociatedGroupToken\fR [get]\fP, \fR [set]\fP"

.PP
TODO: Remove the "set;" hack\&. Added so one can shift text spans when the \&.sln content is modified\&. (2023-10-10))\&. 
.PP
Implements \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.IDotNetProject\fP\&.
.PP
Definition at line \fB31\fP of file \fBCSharpProject\&.cs\fP\&.
.SS "string Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.CSharpProjectModel\&.DisplayName\fR [get]\fP"

.PP
Implements \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.IDotNetProject\fP\&.
.PP
Definition at line \fB26\fP of file \fBCSharpProject\&.cs\fP\&.
.SS "\fBDotNetProjectKind\fP Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.CSharpProjectModel\&.DotNetProjectKind\fR [get]\fP"

.PP
Implements \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.IDotNetProject\fP\&.
.PP
Definition at line \fB33\fP of file \fBCSharpProject\&.cs\fP\&.
.SS "OpenAssociatedGroupToken Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.CSharpProjectModel\&.OpenAssociatedGroupToken\fR [get]\fP, \fR [set]\fP"

.PP
TODO: Remove the "set;" hack\&. Added so one can shift text spans when the \&.sln content is modified\&. (2023-10-10))\&. 
.PP
Implements \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.IDotNetProject\fP\&.
.PP
Definition at line \fB30\fP of file \fBCSharpProject\&.cs\fP\&.
.SS "Guid Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.CSharpProjectModel\&.ProjectIdGuid\fR [get]\fP"

.PP
Implements \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.IDotNetProject\fP\&.
.PP
Definition at line \fB29\fP of file \fBCSharpProject\&.cs\fP\&.
.SS "Guid Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.CSharpProjectModel\&.ProjectTypeGuid\fR [get]\fP"

.PP
Implements \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.IDotNetProject\fP\&.
.PP
Definition at line \fB27\fP of file \fBCSharpProject\&.cs\fP\&.
.SS "string Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.CSharpProjectModel\&.RelativePathFromSolutionFileString\fR [get]\fP"

.PP
Implements \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.IDotNetProject\fP\&.
.PP
Definition at line \fB28\fP of file \fBCSharpProject\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
