.TH "Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Namespaces" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Namespaces
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static Dictionary< string, \fBNamespaceGroupNode\fP > \fBGetInitialBoundNamespaceStatementNodes\fP ()"
.br
.RI "TODO: Implement the initial bound namespaces correctly\&. Until then just add the "System" namespace as a nonsensical node\&. "
.ti -1c
.RI "static \fBNamespaceStatementNode\fP \fBGetTopLevelNamespaceStatementNode\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBTopLevelNamespaceIdentifier\fP = 'GetTopLevelNamespaceStatementNode'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBCSharpFacts\&.Namespaces\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "Dictionary< string, \fBNamespaceGroupNode\fP > Luthetus\&.CompilerServices\&.CSharp\&.Facts\&.CSharpFacts\&.Namespaces\&.GetInitialBoundNamespaceStatementNodes ()\fR [static]\fP"

.PP
TODO: Implement the initial bound namespaces correctly\&. Until then just add the "System" namespace as a nonsensical node\&. 
.PP
Definition at line \fB17\fP of file \fBCSharpFacts\&.Namespaces\&.cs\fP\&.
.SS "\fBNamespaceStatementNode\fP Luthetus\&.CompilerServices\&.CSharp\&.Facts\&.CSharpFacts\&.Namespaces\&.GetTopLevelNamespaceStatementNode ()\fR [static]\fP"

.PP
Definition at line \fB35\fP of file \fBCSharpFacts\&.Namespaces\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const string Luthetus\&.CompilerServices\&.CSharp\&.Facts\&.CSharpFacts\&.Namespaces\&.TopLevelNamespaceIdentifier = 'GetTopLevelNamespaceStatementNode'\fR [static]\fP"

.PP
Definition at line \fB14\fP of file \fBCSharpFacts\&.Namespaces\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
