.TH "Luthetus.TextEditor.RazorLib.Options.Displays" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Options.Displays
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInputTextEditorCursorWidth\fP"
.br
.ti -1c
.RI "class \fBInputTextEditorFontFamily\fP"
.br
.ti -1c
.RI "class \fBInputTextEditorFontSize\fP"
.br
.ti -1c
.RI "class \fBInputTextEditorHeight\fP"
.br
.ti -1c
.RI "class \fBInputTextEditorKeymap\fP"
.br
.ti -1c
.RI "class \fBInputTextEditorShowNewLines\fP"
.br
.ti -1c
.RI "class \fBInputTextEditorShowWhitespace\fP"
.br
.ti -1c
.RI "class \fBInputTextEditorTheme\fP"
.br
.ti -1c
.RI "class \fBInputTextEditorUseMonospaceOptimizations\fP"
.br
.ti -1c
.RI "class \fBTextEditorSettings\fP"
.br
.ti -1c
.RI "class \fBTextEditorSettingsPreview\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
