.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.StringLiteralTokenTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.StringLiteralTokenTests \- \fBStringLiteralToken\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "StringLiteralToken(TextEditorTextSpan) 
.br
----
.br
 \fBStringLiteralToken\&.TextSpan\fP \fBStringLiteralToken\&.SyntaxKind\fP \fBStringLiteralToken\&.IsFabricated\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBStringLiteralToken\fP 
.PP
Definition at line \fB10\fP of file \fBStringLiteralTokenTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.Syntax\&.SyntaxTokens\&.StringLiteralTokenTests\&.Constructor ()"

.PP
StringLiteralToken(TextEditorTextSpan) 
.br
----
.br
 \fBStringLiteralToken\&.TextSpan\fP \fBStringLiteralToken\&.SyntaxKind\fP \fBStringLiteralToken\&.IsFabricated\fP 
.PP
Definition at line \fB20\fP of file \fBStringLiteralTokenTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
