.TH "Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBTypeDefinitionNode\fP \fBVoid\fP"
.br
.ti -1c
.RI "static readonly \fBTypeDefinitionNode\fP \fBInt\fP"
.br
.ti -1c
.RI "static readonly \fBTypeDefinitionNode\fP \fBChar\fP"
.br
.ti -1c
.RI "static readonly \fBTypeDefinitionNode\fP \fBString\fP"
.br
.ti -1c
.RI "static readonly \fBTypeDefinitionNode\fP \fBBool\fP"
.br
.ti -1c
.RI "static readonly \fBTypeDefinitionNode\fP \fBVar\fP"
.br
.ti -1c
.RI "static readonly ImmutableArray< \fBTypeDefinitionNode\fP > \fBTypeDefinitionNodes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB12\fP of file \fBCSharpFacts\&.Types\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBTypeDefinitionNode\fP Luthetus\&.CompilerServices\&.CSharp\&.Facts\&.CSharpFacts\&.Types\&.Bool\fR [static]\fP"
\fBInitial value:\fP
.nf
= new(
            AccessModifierKind\&.Public,
            false,
            StorageModifierKind\&.Class,
            new IdentifierToken(new TextEditorTextSpan(0, "bool"\&.Length, (byte)GenericDecorationKind\&.None, ResourceUri\&.Empty, "bool")),
            typeof(bool),
            null,
            null,
            null,
            openBraceToken: default,
            null)
.PP
.fi

.PP
Definition at line \fB62\fP of file \fBCSharpFacts\&.Types\&.cs\fP\&.
.SS "readonly \fBTypeDefinitionNode\fP Luthetus\&.CompilerServices\&.CSharp\&.Facts\&.CSharpFacts\&.Types\&.Char\fR [static]\fP"
\fBInitial value:\fP
.nf
= new(
            AccessModifierKind\&.Public,
            false,
            StorageModifierKind\&.Class,
            new IdentifierToken(new TextEditorTextSpan(0, "char"\&.Length, (byte)GenericDecorationKind\&.None, ResourceUri\&.Empty, "char")),
            typeof(char),
            null,
            null,
            null,
            openBraceToken: default,
            null)
.PP
.fi

.PP
Definition at line \fB38\fP of file \fBCSharpFacts\&.Types\&.cs\fP\&.
.SS "readonly \fBTypeDefinitionNode\fP Luthetus\&.CompilerServices\&.CSharp\&.Facts\&.CSharpFacts\&.Types\&.Int\fR [static]\fP"
\fBInitial value:\fP
.nf
= new(
            AccessModifierKind\&.Public,
            false,
            StorageModifierKind\&.Class,
            new IdentifierToken(new TextEditorTextSpan(0, "int"\&.Length, (byte)GenericDecorationKind\&.None, ResourceUri\&.Empty, "int")),
            typeof(int),
            null,
            null,
            null,
            openBraceToken: default,
            null)
.PP
.fi

.PP
Definition at line \fB26\fP of file \fBCSharpFacts\&.Types\&.cs\fP\&.
.SS "readonly \fBTypeDefinitionNode\fP Luthetus\&.CompilerServices\&.CSharp\&.Facts\&.CSharpFacts\&.Types\&.String\fR [static]\fP"
\fBInitial value:\fP
.nf
= new(
            AccessModifierKind\&.Public,
            false,
            StorageModifierKind\&.Class,
            new IdentifierToken(new TextEditorTextSpan(0, "string"\&.Length, (byte)GenericDecorationKind\&.None, ResourceUri\&.Empty, "string")),
            typeof(string),
            null,
            null,
            null,
            openBraceToken: default,
            null)
.PP
.fi

.PP
Definition at line \fB50\fP of file \fBCSharpFacts\&.Types\&.cs\fP\&.
.SS "readonly ImmutableArray<\fBTypeDefinitionNode\fP> Luthetus\&.CompilerServices\&.CSharp\&.Facts\&.CSharpFacts\&.Types\&.TypeDefinitionNodes\fR [static]\fP"
\fBInitial value:\fP
.nf
= new[]
        {
            Void,
            Int,
            String,
            Bool,
            Var
        }\&.ToImmutableArray()
.PP
.fi

.PP
Definition at line \fB86\fP of file \fBCSharpFacts\&.Types\&.cs\fP\&.
.SS "readonly \fBTypeDefinitionNode\fP Luthetus\&.CompilerServices\&.CSharp\&.Facts\&.CSharpFacts\&.Types\&.Var\fR [static]\fP"
\fBInitial value:\fP
.nf
= new(
            AccessModifierKind\&.Public,
            false,
            StorageModifierKind\&.Class,
            new IdentifierToken(new TextEditorTextSpan(0, "var"\&.Length, (byte)GenericDecorationKind\&.None, ResourceUri\&.Empty, "var")),
            typeof(void),
            null,
            null,
            null,
            openBraceToken: default,
            null)
.PP
.fi

.PP
Definition at line \fB74\fP of file \fBCSharpFacts\&.Types\&.cs\fP\&.
.SS "readonly \fBTypeDefinitionNode\fP Luthetus\&.CompilerServices\&.CSharp\&.Facts\&.CSharpFacts\&.Types\&.Void\fR [static]\fP"
\fBInitial value:\fP
.nf
= new(
            AccessModifierKind\&.Public,
            false,
            StorageModifierKind\&.Class,
            new IdentifierToken(new TextEditorTextSpan(0, "void"\&.Length, (byte)GenericDecorationKind\&.None, ResourceUri\&.Empty, "void")),
            typeof(void),
            null,
            null,
            null,
            openBraceToken: default,
            null)
.PP
.fi

.PP
Definition at line \fB14\fP of file \fBCSharpFacts\&.Types\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
