.TH "Luthetus.Common.RazorLib.ComponentRenderers.Models.ITreeViewMissingRendererFallbackType" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.ComponentRenderers.Models.ITreeViewMissingRendererFallbackType
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.Common\&.RazorLib\&.WatchWindows\&.Displays\&.TreeViewMissingRendererFallbackDisplay\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBDisplayText\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBITreeViewMissingRendererFallbackType\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Luthetus\&.Common\&.RazorLib\&.ComponentRenderers\&.Models\&.ITreeViewMissingRendererFallbackType\&.DisplayText\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.WatchWindows\&.Displays\&.TreeViewMissingRendererFallbackDisplay\fP\&.
.PP
Definition at line \fB5\fP of file \fBITreeViewMissingRendererFallbackType\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
