.TH "Luthetus.Extensions.Git.Displays.TreeViewGitFileDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.Git.Displays.TreeViewGitFileDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase, and \fBLuthetus\&.Extensions\&.Git\&.ComponentRenderers\&.Models\&.ITreeViewGitFileRendererType\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "GitState \fBGitState\fP = null!\fR [get, set]\fP"
.br
.ti -1c
.RI "TreeViewGitFile \fBTreeViewGitFile\fP = null!\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBTreeViewGitFileDisplay\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "GitState Luthetus\&.Extensions\&.Git\&.Displays\&.TreeViewGitFileDisplay\&.GitState = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB17\fP of file \fBTreeViewGitFileDisplay\&.razor\&.cs\fP\&.
.SS "TreeViewGitFile Luthetus\&.Extensions\&.Git\&.Displays\&.TreeViewGitFileDisplay\&.TreeViewGitFile = null!\fR [get]\fP, \fR [set]\fP"

.PP
Implements \fBLuthetus\&.Extensions\&.Git\&.ComponentRenderers\&.Models\&.ITreeViewGitFileRendererType\fP\&.
.PP
Definition at line \fB20\fP of file \fBTreeViewGitFileDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
