.TH "Luthetus.TextEditor.RazorLib.Options.Displays.InputTextEditorShowWhitespace" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Options.Displays.InputTextEditorShowWhitespace
.SH SYNOPSIS
.br
.PP
.PP
Inherits FluxorComponent\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "InputViewModel \fBInputViewModel\fP = \fBInputViewModel\&.Empty\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBGlobalShowWhitespace\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBInputTextEditorShowWhitespace\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.Options\&.Displays\&.InputTextEditorShowWhitespace\&.GlobalShowWhitespace\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB19\fP of file \fBInputTextEditorShowWhitespace\&.razor\&.cs\fP\&.
.SS "InputViewModel Luthetus\&.TextEditor\&.RazorLib\&.Options\&.Displays\&.InputTextEditorShowWhitespace\&.InputViewModel = \fBInputViewModel\&.Empty\fP\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB17\fP of file \fBInputTextEditorShowWhitespace\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
