.TH "Luthetus.Common.Tests.Basis.Reactives.Models.ThrottleAsyncTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Reactives.Models.ThrottleAsyncTests \- \fBThrottleAsync\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor_TimeSpan\fP ()"
.br
.RI "ThrottleAsync(TimeSpan) 
.br
----
.br
 ThrottleAsync\&.ShouldWaitForPreviousWorkItemToComplete \fBThrottleAsync\&.ThrottleTimeSpan\fP "
.ti -1c
.RI "void \fBConstructor_TimeSpan_bool\fP ()"
.br
.RI "ThrottleAsync(TimeSpan, bool) 
.br
----
.br
 ThrottleAsync\&.ShouldWaitForPreviousWorkItemToComplete \fBThrottleAsync\&.ThrottleTimeSpan\fP "
.ti -1c
.RI "async Task \fBPushEvent_One\fP ()"
.br
.RI "ThrottleAsync\&.PushEvent(Func<CancellationToken, Task>) "
.ti -1c
.RI "async Task \fBPushEvent_Two\fP ()"
.br
.RI "ThrottleAsync\&.PushEvent(Func<CancellationToken, Task>) "
.ti -1c
.RI "async Task \fBPushEvent_Three\fP ()"
.br
.RI "ThrottleAsync\&.PushEvent(Func<CancellationToken, Task>) "
.ti -1c
.RI "async Task \fBPushEvent_Four\fP ()"
.br
.RI "ThrottleAsync\&.PushEvent(Func<CancellationToken, Task>) "
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.RI "ThrottleAsync\&.Dispose() "
.in -1c
.SH "Detailed Description"
.PP 
\fBThrottleAsync\fP 
.PP
Definition at line \fB8\fP of file \fBThrottleAsyncTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Reactives\&.Models\&.ThrottleAsyncTests\&.Constructor_TimeSpan ()"

.PP
ThrottleAsync(TimeSpan) 
.br
----
.br
 ThrottleAsync\&.ShouldWaitForPreviousWorkItemToComplete \fBThrottleAsync\&.ThrottleTimeSpan\fP 
.PP
Definition at line \fB17\fP of file \fBThrottleAsyncTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Reactives\&.Models\&.ThrottleAsyncTests\&.Constructor_TimeSpan_bool ()"

.PP
ThrottleAsync(TimeSpan, bool) 
.br
----
.br
 ThrottleAsync\&.ShouldWaitForPreviousWorkItemToComplete \fBThrottleAsync\&.ThrottleTimeSpan\fP 
.PP
Definition at line \fB43\fP of file \fBThrottleAsyncTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Reactives\&.Models\&.ThrottleAsyncTests\&.Dispose ()"

.PP
ThrottleAsync\&.Dispose() 
.PP
Definition at line \fB202\fP of file \fBThrottleAsyncTests\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.Tests\&.Basis\&.Reactives\&.Models\&.ThrottleAsyncTests\&.PushEvent_Four ()"

.PP
ThrottleAsync\&.PushEvent(Func<CancellationToken, Task>) 
.PP
Definition at line \fB173\fP of file \fBThrottleAsyncTests\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.Tests\&.Basis\&.Reactives\&.Models\&.ThrottleAsyncTests\&.PushEvent_One ()"

.PP
ThrottleAsync\&.PushEvent(Func<CancellationToken, Task>) 
.PP
Definition at line \fB92\fP of file \fBThrottleAsyncTests\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.Tests\&.Basis\&.Reactives\&.Models\&.ThrottleAsyncTests\&.PushEvent_Three ()"

.PP
ThrottleAsync\&.PushEvent(Func<CancellationToken, Task>) 
.PP
Definition at line \fB145\fP of file \fBThrottleAsyncTests\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.Tests\&.Basis\&.Reactives\&.Models\&.ThrottleAsyncTests\&.PushEvent_Two ()"

.PP
ThrottleAsync\&.PushEvent(Func<CancellationToken, Task>) 
.PP
Definition at line \fB118\fP of file \fBThrottleAsyncTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
