.TH "Luthetus.CompilerServices.C.Facts.CLanguageFacts.Keywords" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.C.Facts.CLanguageFacts.Keywords
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBAUTO_KEYWORD\fP = 'auto'"
.br
.ti -1c
.RI "const string \fBBREAK_KEYWORD\fP = 'break'"
.br
.ti -1c
.RI "const string \fBCASE_KEYWORD\fP = 'case'"
.br
.ti -1c
.RI "const string \fBCHAR_KEYWORD\fP = 'char'"
.br
.ti -1c
.RI "const string \fBCONST_KEYWORD\fP = 'const'"
.br
.ti -1c
.RI "const string \fBCONTINUE_KEYWORD\fP = 'continue'"
.br
.ti -1c
.RI "const string \fBDEFAULT_KEYWORD\fP = 'default'"
.br
.ti -1c
.RI "const string \fBDO_KEYWORD\fP = 'do'"
.br
.ti -1c
.RI "const string \fBDOUBLE_KEYWORD\fP = 'double'"
.br
.ti -1c
.RI "const string \fBELSE_KEYWORD\fP = 'else'"
.br
.ti -1c
.RI "const string \fBENUM_KEYWORD\fP = 'enum'"
.br
.ti -1c
.RI "const string \fBEXTERN_KEYWORD\fP = 'extern'"
.br
.ti -1c
.RI "const string \fBFLOAT_KEYWORD\fP = 'float'"
.br
.ti -1c
.RI "const string \fBFOR_KEYWORD\fP = 'for'"
.br
.ti -1c
.RI "const string \fBGOTO_KEYWORD\fP = 'goto'"
.br
.ti -1c
.RI "const string \fBIF_KEYWORD\fP = 'if'"
.br
.ti -1c
.RI "const string \fBINT_KEYWORD\fP = 'int'"
.br
.ti -1c
.RI "const string \fBLONG_KEYWORD\fP = 'long'"
.br
.ti -1c
.RI "const string \fBREGISTER_KEYWORD\fP = 'register'"
.br
.ti -1c
.RI "const string \fBRETURN_KEYWORD\fP = 'return'"
.br
.ti -1c
.RI "const string \fBSHORT_KEYWORD\fP = 'short'"
.br
.ti -1c
.RI "const string \fBSIGNED_KEYWORD\fP = 'signed'"
.br
.ti -1c
.RI "const string \fBSIZEOF_KEYWORD\fP = 'sizeof'"
.br
.ti -1c
.RI "const string \fBSTATIC_KEYWORD\fP = 'static'"
.br
.ti -1c
.RI "const string \fBSTRUCT_KEYWORD\fP = 'struct'"
.br
.ti -1c
.RI "const string \fBSWITCH_KEYWORD\fP = 'switch'"
.br
.ti -1c
.RI "const string \fBTYPEDEF_KEYWORD\fP = 'typedef'"
.br
.ti -1c
.RI "const string \fBUNION_KEYWORD\fP = 'union'"
.br
.ti -1c
.RI "const string \fBUNSIGNED_KEYWORD\fP = 'unsigned'"
.br
.ti -1c
.RI "const string \fBVOID_KEYWORD\fP = 'void'"
.br
.ti -1c
.RI "const string \fBVOLATILE_KEYWORD\fP = 'volatile'"
.br
.ti -1c
.RI "const string \fBWHILE_KEYWORD\fP = 'while'"
.br
.ti -1c
.RI "static readonly ImmutableArray< string > \fBALL_LIST\fP"
.br
.ti -1c
.RI "static readonly ImmutableArray< string > \fBCONTROL_KEYWORDS\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly ImmutableArray<string> Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.ALL_LIST\fR [static]\fP"

.PP
Definition at line \fB42\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.AUTO_KEYWORD = 'auto'\fR [static]\fP"

.PP
Definition at line \fB9\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.BREAK_KEYWORD = 'break'\fR [static]\fP"

.PP
Definition at line \fB10\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.CASE_KEYWORD = 'case'\fR [static]\fP"

.PP
Definition at line \fB11\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.CHAR_KEYWORD = 'char'\fR [static]\fP"

.PP
Definition at line \fB12\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.CONST_KEYWORD = 'const'\fR [static]\fP"

.PP
Definition at line \fB13\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.CONTINUE_KEYWORD = 'continue'\fR [static]\fP"

.PP
Definition at line \fB14\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "readonly ImmutableArray<string> Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.CONTROL_KEYWORDS\fR [static]\fP"
\fBInitial value:\fP
.nf
= new[]
        {
            BREAK_KEYWORD,
            CASE_KEYWORD,
            CONTINUE_KEYWORD,
            DO_KEYWORD,
            ELSE_KEYWORD,
            FOR_KEYWORD,
            GOTO_KEYWORD,
            IF_KEYWORD,
            RETURN_KEYWORD,
            SWITCH_KEYWORD,
            WHILE_KEYWORD,
        }\&.ToImmutableArray()
.PP
.fi

.PP
Definition at line \fB78\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.DEFAULT_KEYWORD = 'default'\fR [static]\fP"

.PP
Definition at line \fB15\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.DO_KEYWORD = 'do'\fR [static]\fP"

.PP
Definition at line \fB16\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.DOUBLE_KEYWORD = 'double'\fR [static]\fP"

.PP
Definition at line \fB17\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.ELSE_KEYWORD = 'else'\fR [static]\fP"

.PP
Definition at line \fB18\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.ENUM_KEYWORD = 'enum'\fR [static]\fP"

.PP
Definition at line \fB19\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.EXTERN_KEYWORD = 'extern'\fR [static]\fP"

.PP
Definition at line \fB20\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.FLOAT_KEYWORD = 'float'\fR [static]\fP"

.PP
Definition at line \fB21\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.FOR_KEYWORD = 'for'\fR [static]\fP"

.PP
Definition at line \fB22\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.GOTO_KEYWORD = 'goto'\fR [static]\fP"

.PP
Definition at line \fB23\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.IF_KEYWORD = 'if'\fR [static]\fP"

.PP
Definition at line \fB24\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.INT_KEYWORD = 'int'\fR [static]\fP"

.PP
Definition at line \fB25\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.LONG_KEYWORD = 'long'\fR [static]\fP"

.PP
Definition at line \fB26\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.REGISTER_KEYWORD = 'register'\fR [static]\fP"

.PP
Definition at line \fB27\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.RETURN_KEYWORD = 'return'\fR [static]\fP"

.PP
Definition at line \fB28\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.SHORT_KEYWORD = 'short'\fR [static]\fP"

.PP
Definition at line \fB29\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.SIGNED_KEYWORD = 'signed'\fR [static]\fP"

.PP
Definition at line \fB30\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.SIZEOF_KEYWORD = 'sizeof'\fR [static]\fP"

.PP
Definition at line \fB31\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.STATIC_KEYWORD = 'static'\fR [static]\fP"

.PP
Definition at line \fB32\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.STRUCT_KEYWORD = 'struct'\fR [static]\fP"

.PP
Definition at line \fB33\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.SWITCH_KEYWORD = 'switch'\fR [static]\fP"

.PP
Definition at line \fB34\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.TYPEDEF_KEYWORD = 'typedef'\fR [static]\fP"

.PP
Definition at line \fB35\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.UNION_KEYWORD = 'union'\fR [static]\fP"

.PP
Definition at line \fB36\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.UNSIGNED_KEYWORD = 'unsigned'\fR [static]\fP"

.PP
Definition at line \fB37\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.VOID_KEYWORD = 'void'\fR [static]\fP"

.PP
Definition at line \fB38\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.VOLATILE_KEYWORD = 'volatile'\fR [static]\fP"

.PP
Definition at line \fB39\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.C\&.Facts\&.CLanguageFacts\&.Keywords\&.WHILE_KEYWORD = 'while'\fR [static]\fP"

.PP
Definition at line \fB40\fP of file \fBCLanguageFacts\&.Keywords\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
