.TH "Luthetus.Common.RazorLib.Reflectives.Displays.ReflectiveSetContentDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Reflectives.Displays.ReflectiveSetContentDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly Key< object > \fBTextEditorModelKey\fP = Key<object>\&.NewKey()"
.br
.ti -1c
.RI "static readonly Key< object > \fBTextEditorViewModelKey\fP = Key<object>\&.NewKey()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "ParameterInfo \fBParameterInfo\fP = null!\fR [get, set]\fP"
.br
.ti -1c
.RI "Action< string, object?> \fBOnChangeAction\fP = null!\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBInput\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBReflectiveSetContentDisplay\&.razor\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly Key<object> Luthetus\&.Common\&.RazorLib\&.Reflectives\&.Displays\&.ReflectiveSetContentDisplay\&.TextEditorModelKey = Key<object>\&.NewKey()\fR [static]\fP"

.PP
Definition at line \fB14\fP of file \fBReflectiveSetContentDisplay\&.razor\&.cs\fP\&.
.SS "readonly Key<object> Luthetus\&.Common\&.RazorLib\&.Reflectives\&.Displays\&.ReflectiveSetContentDisplay\&.TextEditorViewModelKey = Key<object>\&.NewKey()\fR [static]\fP"

.PP
Definition at line \fB15\fP of file \fBReflectiveSetContentDisplay\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Luthetus\&.Common\&.RazorLib\&.Reflectives\&.Displays\&.ReflectiveSetContentDisplay\&.Input\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB19\fP of file \fBReflectiveSetContentDisplay\&.razor\&.cs\fP\&.
.SS "Action<string, object?> Luthetus\&.Common\&.RazorLib\&.Reflectives\&.Displays\&.ReflectiveSetContentDisplay\&.OnChangeAction = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB12\fP of file \fBReflectiveSetContentDisplay\&.razor\&.cs\fP\&.
.SS "ParameterInfo Luthetus\&.Common\&.RazorLib\&.Reflectives\&.Displays\&.ReflectiveSetContentDisplay\&.ParameterInfo = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB10\fP of file \fBReflectiveSetContentDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
