.TH "Luthetus.Ide.RazorLib.ComponentRenderers.Models.IFileFormRendererType" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.ComponentRenderers.Models.IFileFormRendererType
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.Ide\&.RazorLib\&.FileSystems\&.Displays\&.FileFormDisplay\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBFileName\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsDirectory\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBCheckForTemplates\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "Func< string, \fBIFileTemplate\fP?, ImmutableArray< \fBIFileTemplate\fP >, Task > \fBOnAfterSubmitFunc\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBIFileFormRendererType\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Luthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.IFileFormRendererType\&.CheckForTemplates\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.FileSystems\&.Displays\&.FileFormDisplay\fP\&.
.PP
Definition at line \fB10\fP of file \fBIFileFormRendererType\&.cs\fP\&.
.SS "string Luthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.IFileFormRendererType\&.FileName\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.FileSystems\&.Displays\&.FileFormDisplay\fP\&.
.PP
Definition at line \fB8\fP of file \fBIFileFormRendererType\&.cs\fP\&.
.SS "bool Luthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.IFileFormRendererType\&.IsDirectory\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.FileSystems\&.Displays\&.FileFormDisplay\fP\&.
.PP
Definition at line \fB9\fP of file \fBIFileFormRendererType\&.cs\fP\&.
.SS "Func<string, \fBIFileTemplate\fP?, ImmutableArray<\fBIFileTemplate\fP>, Task> Luthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.IFileFormRendererType\&.OnAfterSubmitFunc\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.FileSystems\&.Displays\&.FileFormDisplay\fP\&.
.PP
Definition at line \fB11\fP of file \fBIFileFormRendererType\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
