.TH "Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.FooterDriver" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.FooterDriver \- TODO: Move this back into TextEditorDefaultFooter\&. This was made into the Driver idea, then made back into a component\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFooterDriver\fP (\fBTextEditorViewModelDisplay\fP textEditorViewModelDisplay)"
.br
.ti -1c
.RI "void \fBGetRenderFragment\fP (\fBTextEditorRenderBatchValidated\fP renderBatch)"
.br
.ti -1c
.RI "void \fBSelectRowEndingKindOnChange\fP (ChangeEventArgs changeEventArgs)"
.br
.ti -1c
.RI "string \fBStyleMinWidthFromMaxLengthOfValue\fP (int value)"
.br
.ti -1c
.RI "int \fBGetPositionNumber\fP (\fBTextEditorModel\fP model, \fBTextEditorViewModel\fP viewModel)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly \fBTextEditorViewModelDisplay\fP \fB_root\fP"
.br
.ti -1c
.RI "\fBTextEditorRenderBatchValidated\fP \fB_renderBatch\fP"
.br
.ti -1c
.RI "int \fB_previousPositionNumber\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
TODO: Move this back into TextEditorDefaultFooter\&. This was made into the Driver idea, then made back into a component\&. 
.PP
Definition at line \fB12\fP of file \fBFooterDriver\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.FooterDriver\&.FooterDriver (\fBTextEditorViewModelDisplay\fP textEditorViewModelDisplay)"

.PP
Definition at line \fB16\fP of file \fBFooterDriver\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "int Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.FooterDriver\&.GetPositionNumber (\fBTextEditorModel\fP model, \fBTextEditorViewModel\fP viewModel)"

.PP
Definition at line \fB76\fP of file \fBFooterDriver\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.FooterDriver\&.GetRenderFragment (\fBTextEditorRenderBatchValidated\fP renderBatch)"

.PP
Definition at line \fB24\fP of file \fBFooterDriver\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.FooterDriver\&.SelectRowEndingKindOnChange (ChangeEventArgs changeEventArgs)"

.PP
Definition at line \fB32\fP of file \fBFooterDriver\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.FooterDriver\&.StyleMinWidthFromMaxLengthOfValue (int value)"

.PP
Definition at line \fB68\fP of file \fBFooterDriver\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.FooterDriver\&._previousPositionNumber"

.PP
Definition at line \fB30\fP of file \fBFooterDriver\&.cs\fP\&.
.SS "\fBTextEditorRenderBatchValidated\fP Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.FooterDriver\&._renderBatch"

.PP
Definition at line \fB22\fP of file \fBFooterDriver\&.cs\fP\&.
.SS "readonly \fBTextEditorViewModelDisplay\fP Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.FooterDriver\&._root"

.PP
Definition at line \fB14\fP of file \fBFooterDriver\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
