.TH "Luthetus.Extensions.DotNet.TestExplorers.States" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.TestExplorers.States
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTestExplorerScheduler\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "partial record \fBTestExplorerState\fP (string? SolutionFilePath, int TotalTestCount, ImmutableHashSet< string > NotRanTestHashSet, ImmutableHashSet< string > PassedTestHashSet, ImmutableHashSet< string > FailedTestHashSet)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "partial record Luthetus\&.Extensions\&.DotNet\&.TestExplorers\&.States\&.TestExplorerState (string? SolutionFilePath, int TotalTestCount, ImmutableHashSet< string > NotRanTestHashSet, ImmutableHashSet< string > PassedTestHashSet, ImmutableHashSet< string > FailedTestHashSet)"

.PP
Definition at line \fB11\fP of file \fBTestExplorerState\&.Main\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
