.TH "Luthetus.CompilerServices.Razor.Tests.RazorCompilerServiceTestsBase" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.Razor.Tests.RazorCompilerServiceTestsBase
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRazorCompilerServiceTestsBase\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "readonly ServiceProvider \fBServiceProvider\fP"
.br
.ti -1c
.RI "readonly \fBITextEditorService\fP \fBTextEditorService\fP"
.br
.ti -1c
.RI "readonly RazorCompilerService \fBRazorCompilerService\fP"
.br
.ti -1c
.RI "readonly XmlCompilerService \fBXmlCompilerService\fP"
.br
.ti -1c
.RI "readonly CSharpCompilerService \fBCSharpCompilerService\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB19\fP of file \fBRazorCompilerServiceTestsBase\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.CompilerServices\&.Razor\&.Tests\&.RazorCompilerServiceTestsBase\&.RazorCompilerServiceTestsBase ()"

.PP
Definition at line \fB27\fP of file \fBRazorCompilerServiceTestsBase\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly CSharpCompilerService Luthetus\&.CompilerServices\&.Razor\&.Tests\&.RazorCompilerServiceTestsBase\&.CSharpCompilerService\fR [protected]\fP"

.PP
Definition at line \fB25\fP of file \fBRazorCompilerServiceTestsBase\&.cs\fP\&.
.SS "readonly RazorCompilerService Luthetus\&.CompilerServices\&.Razor\&.Tests\&.RazorCompilerServiceTestsBase\&.RazorCompilerService\fR [protected]\fP"

.PP
Definition at line \fB23\fP of file \fBRazorCompilerServiceTestsBase\&.cs\fP\&.
.SS "readonly ServiceProvider Luthetus\&.CompilerServices\&.Razor\&.Tests\&.RazorCompilerServiceTestsBase\&.ServiceProvider\fR [protected]\fP"

.PP
Definition at line \fB21\fP of file \fBRazorCompilerServiceTestsBase\&.cs\fP\&.
.SS "readonly \fBITextEditorService\fP Luthetus\&.CompilerServices\&.Razor\&.Tests\&.RazorCompilerServiceTestsBase\&.TextEditorService\fR [protected]\fP"

.PP
Definition at line \fB22\fP of file \fBRazorCompilerServiceTestsBase\&.cs\fP\&.
.SS "readonly XmlCompilerService Luthetus\&.CompilerServices\&.Razor\&.Tests\&.RazorCompilerServiceTestsBase\&.XmlCompilerService\fR [protected]\fP"

.PP
Definition at line \fB24\fP of file \fBRazorCompilerServiceTestsBase\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
