.TH "Luthetus.TextEditor.RazorLib.Edits.Models.TextEditorEditBackspaceBatch" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Edits.Models.TextEditorEditBackspaceBatch
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.ITextEditorEdit\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextEditorEditBackspaceBatch\fP (int positionIndex, int count, StringBuilder textRemovedBuilder)"
.br
.ti -1c
.RI "void \fBAdd\fP (int count, string textRemoved)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBPositionIndex\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBCount\fP\fR [get]\fP"
.br
.ti -1c
.RI "StringBuilder \fBTextRemovedBuilder\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBTextEditorEditKind\fP \fBEditKind\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBTextEditorEditBackspaceBatch\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.TextEditorEditBackspaceBatch\&.TextEditorEditBackspaceBatch (int positionIndex, int count, StringBuilder textRemovedBuilder)"

.PP
Definition at line \fB7\fP of file \fBTextEditorEditBackspaceBatch\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.TextEditorEditBackspaceBatch\&.Add (int count, string textRemoved)"

.PP
Definition at line \fB20\fP of file \fBTextEditorEditBackspaceBatch\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Luthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.TextEditorEditBackspaceBatch\&.Count\fR [get]\fP"

.PP
Definition at line \fB15\fP of file \fBTextEditorEditBackspaceBatch\&.cs\fP\&.
.SS "\fBTextEditorEditKind\fP Luthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.TextEditorEditBackspaceBatch\&.EditKind\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.ITextEditorEdit\fP\&.
.PP
Definition at line \fB18\fP of file \fBTextEditorEditBackspaceBatch\&.cs\fP\&.
.SS "int Luthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.TextEditorEditBackspaceBatch\&.PositionIndex\fR [get]\fP"

.PP
Definition at line \fB14\fP of file \fBTextEditorEditBackspaceBatch\&.cs\fP\&.
.SS "StringBuilder Luthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.TextEditorEditBackspaceBatch\&.TextRemovedBuilder\fR [get]\fP"

.PP
Definition at line \fB16\fP of file \fBTextEditorEditBackspaceBatch\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
