.TH "Luthetus.Ide.RazorLib.FileSystems.Models.FileTemplateParameter" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.FileSystems.Models.FileTemplateParameter
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileTemplateParameter\fP (string filename, \fBNamespacePath\fP parentDirectory, \fBIEnvironmentProvider\fP environmentProvider)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBFilename\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBNamespacePath\fP \fBParentDirectory\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBIEnvironmentProvider\fP \fBEnvironmentProvider\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBFileTemplateParameter\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.FileTemplateParameter\&.FileTemplateParameter (string filename, \fBNamespacePath\fP parentDirectory, \fBIEnvironmentProvider\fP environmentProvider)"

.PP
Definition at line \fB8\fP of file \fBFileTemplateParameter\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBIEnvironmentProvider\fP Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.FileTemplateParameter\&.EnvironmentProvider\fR [get]\fP"

.PP
Definition at line \fB20\fP of file \fBFileTemplateParameter\&.cs\fP\&.
.SS "string Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.FileTemplateParameter\&.Filename\fR [get]\fP"

.PP
Definition at line \fB18\fP of file \fBFileTemplateParameter\&.cs\fP\&.
.SS "\fBNamespacePath\fP Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.FileTemplateParameter\&.ParentDirectory\fR [get]\fP"

.PP
Definition at line \fB19\fP of file \fBFileTemplateParameter\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
