.TH "Luthetus.TextEditor.RazorLib.TextEditors.Displays" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.TextEditors.Displays
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBInternals\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTextEditorViewModelDisplay\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBKeymapArgsKind\fP { \fBNone\fP, \fBMovement\fP, \fBContextMenu\fP, \fBCommand\fP, \fBText\fP, \fBOther\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.KeymapArgsKind\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BINone \fP
.TP
\f(BIMovement \fP
TODO: Are movements not just commands? 
.TP
\f(BIContextMenu \fP
.TP
\f(BICommand \fP
.TP
\f(BIText \fP
.TP
\f(BIOther \fP
.PP
Definition at line \fB3\fP of file \fBKeymapArgsKind\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
