.TH "Luthetus.CompilerServices.Json.SyntaxActors.JsonSyntaxTree" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.Json.SyntaxActors.JsonSyntaxTree
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBJsonSyntaxUnit\fP \fBParseText\fP (\fBResourceUri\fP resourceUri, string content)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB12\fP of file \fBJsonSyntaxTree\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBJsonSyntaxUnit\fP Luthetus\&.CompilerServices\&.Json\&.SyntaxActors\&.JsonSyntaxTree\&.ParseText (\fBResourceUri\fP resourceUri, string content)\fR [static]\fP"

.PP
Definition at line \fB14\fP of file \fBJsonSyntaxTree\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
