.TH "Luthetus.TextEditor.Tests.Basis.Lexers.Models.TextEditorLexerResultTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.Lexers.Models.TextEditorLexerResultTests \- \fBTextEditorLexerResult\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "\fBTextEditorLexerResult\&.TextSpanList\fP "
.ti -1c
.RI "void \fBResourceUri\fP ()"
.br
.RI "\fBTextEditorLexerResult\&.ResourceUri\fP "
.ti -1c
.RI "void \fBModelRenderStateKey\fP ()"
.br
.RI "\fBTextEditorLexerResult\&.ModelRenderStateKey\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBTextEditorLexerResult\fP 
.PP
Definition at line \fB8\fP of file \fBTextEditorLexerResultTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Lexers\&.Models\&.TextEditorLexerResultTests\&.Constructor ()"

.PP
\fBTextEditorLexerResult\&.TextSpanList\fP 
.PP
Definition at line \fB14\fP of file \fBTextEditorLexerResultTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Lexers\&.Models\&.TextEditorLexerResultTests\&.ModelRenderStateKey ()"

.PP
\fBTextEditorLexerResult\&.ModelRenderStateKey\fP 
.PP
Definition at line \fB32\fP of file \fBTextEditorLexerResultTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Lexers\&.Models\&.TextEditorLexerResultTests\&.ResourceUri ()"

.PP
\fBTextEditorLexerResult\&.ResourceUri\fP 
.PP
Definition at line \fB23\fP of file \fBTextEditorLexerResultTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
