.TH "Luthetus.Ide.RazorLib.Terminals.Models.TerminalInputStringBuilder" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.Terminals.Models.TerminalInputStringBuilder
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.ITerminalInput\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTerminalInputStringBuilder\fP (\fBITerminal\fP terminal)"
.br
.ti -1c
.RI "void \fBSendCommand\fP (string commandText)"
.br
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBTerminalInputStringBuilder\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalInputStringBuilder\&.TerminalInputStringBuilder (\fBITerminal\fP terminal)"

.PP
Definition at line \fB7\fP of file \fBTerminalInputStringBuilder\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalInputStringBuilder\&.Dispose ()"

.PP
Definition at line \fB16\fP of file \fBTerminalInputStringBuilder\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalInputStringBuilder\&.SendCommand (string commandText)"

.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.ITerminalInput\fP\&.
.PP
Definition at line \fB12\fP of file \fBTerminalInputStringBuilder\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
