.TH "Luthetus.TextEditor.Tests.Basis.JavaScriptObjects.Models.CharAndRowMeasurementsTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.JavaScriptObjects.Models.CharAndRowMeasurementsTests \- \fBCharAndLineMeasurements\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "\fBCharAndLineMeasurements(double, double)\fP 
.br
----
.br
 CharAndLineMeasurements\&.CharacterWidth CharAndLineMeasurements\&.LineHeight "
.in -1c
.SH "Detailed Description"
.PP 
\fBCharAndLineMeasurements\fP 
.PP
Definition at line \fB8\fP of file \fBCharAndRowMeasurementsTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.JavaScriptObjects\&.Models\&.CharAndRowMeasurementsTests\&.Constructor ()"

.PP
\fBCharAndLineMeasurements(double, double)\fP 
.br
----
.br
 CharAndLineMeasurements\&.CharacterWidth CharAndLineMeasurements\&.LineHeight 
.PP
Definition at line \fB17\fP of file \fBCharAndRowMeasurementsTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
