.TH "Luthetus.Common.RazorLib.Contexts.Displays.ContextBoundary" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Contexts.Displays.ContextBoundary
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDispatchSetActiveContextStatesAction\fP (List< Key< \fBContextRecord\fP > > contextRecordKeyList)"
.br
.ti -1c
.RI "void \fBHandleOnFocus\fP ()"
.br
.RI "NOTE: 'onfocus' event does not bubble, whereas 'onfocusin' does bubble\&. Usage of both events in this file is intentional\&. "
.ti -1c
.RI "void \fBHandleOnBlur\fP ()"
.br
.ti -1c
.RI "void \fBHandleOnFocusIn\fP ()"
.br
.RI "NOTE: 'onfocus' event does not bubble, whereas 'onfocusin' does bubble\&. Usage of both events in this file is intentional\&. "
.ti -1c
.RI "Task \fBHandleOnKeyDownAsync\fP (KeyboardEventArgs keyboardEventArgs)"
.br
.ti -1c
.RI "async Task \fBHandleKeymapArgumentAsync\fP (\fBKeymapArgs\fP keymapArgs)"
.br
.ti -1c
.RI "ImmutableArray< Key< \fBContextRecord\fP > > \fBGetContextBoundaryHeirarchy\fP (List< Key< \fBContextRecord\fP > > contextRecordKeyList)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBContextBoundary\fP? \fBParentContextBoundary\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "ContextRecord \fBContextRecord\fP = null!\fR [get, set]\fP"
.br
.ti -1c
.RI "RenderFragment \fBChildContent\fP = null!\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBClassCssString\fP = null!\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBStyleCssString\fP = null!\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBTabIndex\fP = \-1\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB13\fP of file \fBContextBoundary\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.RazorLib\&.Contexts\&.Displays\&.ContextBoundary\&.DispatchSetActiveContextStatesAction (List< Key< \fBContextRecord\fP > > contextRecordKeyList)"

.PP
Definition at line \fB42\fP of file \fBContextBoundary\&.razor\&.cs\fP\&.
.SS "ImmutableArray< Key< \fBContextRecord\fP > > Luthetus\&.Common\&.RazorLib\&.Contexts\&.Displays\&.ContextBoundary\&.GetContextBoundaryHeirarchy (List< Key< \fBContextRecord\fP > > contextRecordKeyList)"

.PP
Definition at line \fB99\fP of file \fBContextBoundary\&.razor\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.RazorLib\&.Contexts\&.Displays\&.ContextBoundary\&.HandleKeymapArgumentAsync (\fBKeymapArgs\fP keymapArgs)"

.PP
Definition at line \fB89\fP of file \fBContextBoundary\&.razor\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.Contexts\&.Displays\&.ContextBoundary\&.HandleOnBlur ()"

.PP
Definition at line \fB61\fP of file \fBContextBoundary\&.razor\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.Contexts\&.Displays\&.ContextBoundary\&.HandleOnFocus ()"

.PP
NOTE: 'onfocus' event does not bubble, whereas 'onfocusin' does bubble\&. Usage of both events in this file is intentional\&. 
.PP
Definition at line \fB53\fP of file \fBContextBoundary\&.razor\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.Contexts\&.Displays\&.ContextBoundary\&.HandleOnFocusIn ()"

.PP
NOTE: 'onfocus' event does not bubble, whereas 'onfocusin' does bubble\&. Usage of both events in this file is intentional\&. 
.PP
Definition at line \fB70\fP of file \fBContextBoundary\&.razor\&.cs\fP\&.
.SS "Task Luthetus\&.Common\&.RazorLib\&.Contexts\&.Displays\&.ContextBoundary\&.HandleOnKeyDownAsync (KeyboardEventArgs keyboardEventArgs)"

.PP
Definition at line \fB76\fP of file \fBContextBoundary\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "RenderFragment Luthetus\&.Common\&.RazorLib\&.Contexts\&.Displays\&.ContextBoundary\&.ChildContent = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB33\fP of file \fBContextBoundary\&.razor\&.cs\fP\&.
.SS "string Luthetus\&.Common\&.RazorLib\&.Contexts\&.Displays\&.ContextBoundary\&.ClassCssString = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB36\fP of file \fBContextBoundary\&.razor\&.cs\fP\&.
.SS "ContextRecord Luthetus\&.Common\&.RazorLib\&.Contexts\&.Displays\&.ContextBoundary\&.ContextRecord = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB31\fP of file \fBContextBoundary\&.razor\&.cs\fP\&.
.SS "\fBContextBoundary\fP? Luthetus\&.Common\&.RazorLib\&.Contexts\&.Displays\&.ContextBoundary\&.ParentContextBoundary\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB28\fP of file \fBContextBoundary\&.razor\&.cs\fP\&.
.SS "string Luthetus\&.Common\&.RazorLib\&.Contexts\&.Displays\&.ContextBoundary\&.StyleCssString = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB38\fP of file \fBContextBoundary\&.razor\&.cs\fP\&.
.SS "int Luthetus\&.Common\&.RazorLib\&.Contexts\&.Displays\&.ContextBoundary\&.TabIndex = \-1\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB40\fP of file \fBContextBoundary\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
