.TH "Luthetus.Ide.Tests.Basis.FolderExplorers.Models.FolderExplorerTreeViewKeyboardEventHandlerTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.Tests.Basis.FolderExplorers.Models.FolderExplorerTreeViewKeyboardEventHandlerTests \- \fBFolderExplorerTreeViewKeyboardEventHandler\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "FolderExplorerTreeViewKeyboardEventHandler(EditorSync, IMenuOptionsFactory, ILuthetusCommonComponentRenderers, ITreeViewService, IBackgroundTaskService, IEnvironmentProvider) "
.ti -1c
.RI "void \fBOnKeyDownAsync\fP ()"
.br
.RI "\fBFolderExplorerTreeViewKeyboardEventHandler\&.OnKeyDownAsync(TreeViewCommandArgs)\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBFolderExplorerTreeViewKeyboardEventHandler\fP 
.PP
Definition at line \fB13\fP of file \fBFolderExplorerTreeViewKeyboardEventHandlerTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.FolderExplorers\&.Models\&.FolderExplorerTreeViewKeyboardEventHandlerTests\&.Constructor ()"

.PP
FolderExplorerTreeViewKeyboardEventHandler(EditorSync, IMenuOptionsFactory, ILuthetusCommonComponentRenderers, ITreeViewService, IBackgroundTaskService, IEnvironmentProvider) 
.PP
Definition at line \fB19\fP of file \fBFolderExplorerTreeViewKeyboardEventHandlerTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.FolderExplorers\&.Models\&.FolderExplorerTreeViewKeyboardEventHandlerTests\&.OnKeyDownAsync ()"

.PP
\fBFolderExplorerTreeViewKeyboardEventHandler\&.OnKeyDownAsync(TreeViewCommandArgs)\fP 
.PP
Definition at line \fB28\fP of file \fBFolderExplorerTreeViewKeyboardEventHandlerTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
