.TH "Luthetus.TextEditor.Tests.Basis.Options.States.TextEditorOptionsStateMainTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.Options.States.TextEditorOptionsStateMainTests \- \fBTextEditorOptionsState\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "TextEditorOptionsState() "
.ti -1c
.RI "void \fBOptions\fP ()"
.br
.RI "\fBTextEditorOptionsState\&.Options\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBTextEditorOptionsState\fP 
.PP
Definition at line \fB8\fP of file \fBTextEditorOptionsState\&.MainTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.States\&.TextEditorOptionsStateMainTests\&.Constructor ()"

.PP
TextEditorOptionsState() 
.PP
Definition at line \fB14\fP of file \fBTextEditorOptionsState\&.MainTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.States\&.TextEditorOptionsStateMainTests\&.Options ()"

.PP
\fBTextEditorOptionsState\&.Options\fP 
.PP
Definition at line \fB24\fP of file \fBTextEditorOptionsState\&.MainTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
