.TH "Luthetus.TextEditor.Tests.Basis.Options.States.TextEditorOptionsStateActionsTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.Options.States.TextEditorOptionsStateActionsTests \- \fBTextEditorOptionsState\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetFontFamilyAction\fP ()"
.br
.RI "\fBTextEditorOptionsState\&.SetFontFamilyAction\fP "
.ti -1c
.RI "void \fBSetFontSizeAction\fP ()"
.br
.RI "\fBTextEditorOptionsState\&.SetFontSizeAction\fP "
.ti -1c
.RI "void \fBSetCursorWidthAction\fP ()"
.br
.RI "\fBTextEditorOptionsState\&.SetCursorWidthAction\fP "
.ti -1c
.RI "void \fBSetRenderStateKeyAction\fP ()"
.br
.RI "\fBTextEditorOptionsState\&.SetRenderStateKeyAction\fP "
.ti -1c
.RI "void \fBSetHeightAction\fP ()"
.br
.RI "\fBTextEditorOptionsState\&.SetHeightAction\fP "
.ti -1c
.RI "void \fBSetThemeAction\fP ()"
.br
.RI "\fBTextEditorOptionsState\&.SetThemeAction\fP "
.ti -1c
.RI "void \fBSetKeymapAction\fP ()"
.br
.RI "\fBTextEditorOptionsState\&.SetKeymapAction\fP "
.ti -1c
.RI "void \fBSetShowWhitespaceAction\fP ()"
.br
.RI "\fBTextEditorOptionsState\&.SetShowWhitespaceAction\fP "
.ti -1c
.RI "void \fBSetShowNewlinesAction\fP ()"
.br
.RI "\fBTextEditorOptionsState\&.SetShowNewlinesAction\fP "
.ti -1c
.RI "void \fBSetUseMonospaceOptimizationsAction\fP ()"
.br
.RI "\fBTextEditorOptionsState\&.SetUseMonospaceOptimizationsAction\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBTextEditorOptionsState\fP 
.PP
Definition at line \fB12\fP of file \fBTextEditorOptionsState\&.ActionsTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.States\&.TextEditorOptionsStateActionsTests\&.SetCursorWidthAction ()"

.PP
\fBTextEditorOptionsState\&.SetCursorWidthAction\fP 
.PP
Definition at line \fB40\fP of file \fBTextEditorOptionsState\&.ActionsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.States\&.TextEditorOptionsStateActionsTests\&.SetFontFamilyAction ()"

.PP
\fBTextEditorOptionsState\&.SetFontFamilyAction\fP 
.PP
Definition at line \fB18\fP of file \fBTextEditorOptionsState\&.ActionsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.States\&.TextEditorOptionsStateActionsTests\&.SetFontSizeAction ()"

.PP
\fBTextEditorOptionsState\&.SetFontSizeAction\fP 
.PP
Definition at line \fB29\fP of file \fBTextEditorOptionsState\&.ActionsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.States\&.TextEditorOptionsStateActionsTests\&.SetHeightAction ()"

.PP
\fBTextEditorOptionsState\&.SetHeightAction\fP 
.PP
Definition at line \fB62\fP of file \fBTextEditorOptionsState\&.ActionsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.States\&.TextEditorOptionsStateActionsTests\&.SetKeymapAction ()"

.PP
\fBTextEditorOptionsState\&.SetKeymapAction\fP 
.PP
Definition at line \fB94\fP of file \fBTextEditorOptionsState\&.ActionsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.States\&.TextEditorOptionsStateActionsTests\&.SetRenderStateKeyAction ()"

.PP
\fBTextEditorOptionsState\&.SetRenderStateKeyAction\fP 
.PP
Definition at line \fB51\fP of file \fBTextEditorOptionsState\&.ActionsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.States\&.TextEditorOptionsStateActionsTests\&.SetShowNewlinesAction ()"

.PP
\fBTextEditorOptionsState\&.SetShowNewlinesAction\fP 
.PP
Definition at line \fB126\fP of file \fBTextEditorOptionsState\&.ActionsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.States\&.TextEditorOptionsStateActionsTests\&.SetShowWhitespaceAction ()"

.PP
\fBTextEditorOptionsState\&.SetShowWhitespaceAction\fP 
.PP
Definition at line \fB105\fP of file \fBTextEditorOptionsState\&.ActionsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.States\&.TextEditorOptionsStateActionsTests\&.SetThemeAction ()"

.PP
\fBTextEditorOptionsState\&.SetThemeAction\fP 
.PP
Definition at line \fB83\fP of file \fBTextEditorOptionsState\&.ActionsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.States\&.TextEditorOptionsStateActionsTests\&.SetUseMonospaceOptimizationsAction ()"

.PP
\fBTextEditorOptionsState\&.SetUseMonospaceOptimizationsAction\fP 
.PP
Definition at line \fB147\fP of file \fBTextEditorOptionsState\&.ActionsTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
