.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.CompilationUnitTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.CompilationUnitTests \- \fBCompilationUnit\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "CompilationUnit(CodeBlockNode?, ILuthLexer?, ILuthParser?, ILuthBinder?) 
.br
----
.br
 \fBCompilationUnit\&.RootCodeBlockNode\fP \fBCompilationUnit\&.Lexer\fP \fBCompilationUnit\&.Parser\fP \fBCompilationUnit\&.Binder\fP \fBCompilationUnit\&.SyntaxKind\fP \fBCompilationUnit\&.IsFabricated\fP \fBCompilationUnit\&.DiagnosticsList\fP CompilationUnit\&.ChildList "
.in -1c
.SH "Detailed Description"
.PP 
\fBCompilationUnit\fP 
.PP
Definition at line \fB8\fP of file \fBCompilationUnitTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.CompilationUnitTests\&.Constructor ()"

.PP
CompilationUnit(CodeBlockNode?, ILuthLexer?, ILuthParser?, ILuthBinder?) 
.br
----
.br
 \fBCompilationUnit\&.RootCodeBlockNode\fP \fBCompilationUnit\&.Lexer\fP \fBCompilationUnit\&.Parser\fP \fBCompilationUnit\&.Binder\fP \fBCompilationUnit\&.SyntaxKind\fP \fBCompilationUnit\&.IsFabricated\fP \fBCompilationUnit\&.DiagnosticsList\fP CompilationUnit\&.ChildList 
.PP
Definition at line \fB23\fP of file \fBCompilationUnitTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
