.TH "Luthetus.Extensions.DotNet.Tests.Basis.CommandLines.Models.DotNetCliOutputParserTests.DiagnosticLine" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.Tests.Basis.CommandLines.Models.DotNetCliOutputParserTests.DiagnosticLine
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBDiagnosticTextSpan\fP? \fBFilePathTextSpan\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBDiagnosticTextSpan\fP? \fBLineAndColumnIndicesTextSpan\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBDiagnosticTextSpan\fP? \fBDiagnosticKindTextSpan\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBDiagnosticTextSpan\fP? \fBDiagnosticCodeTextSpan\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBDiagnosticTextSpan\fP? \fBMessageTextSpan\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBDiagnosticTextSpan\fP? \fBProjectTextSpan\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsValid\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB70\fP of file \fBDotNetCliOutputParserTests\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBDiagnosticTextSpan\fP? Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.CommandLines\&.Models\&.DotNetCliOutputParserTests\&.DiagnosticLine\&.DiagnosticCodeTextSpan\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB75\fP of file \fBDotNetCliOutputParserTests\&.cs\fP\&.
.SS "\fBDiagnosticTextSpan\fP? Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.CommandLines\&.Models\&.DotNetCliOutputParserTests\&.DiagnosticLine\&.DiagnosticKindTextSpan\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB74\fP of file \fBDotNetCliOutputParserTests\&.cs\fP\&.
.SS "\fBDiagnosticTextSpan\fP? Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.CommandLines\&.Models\&.DotNetCliOutputParserTests\&.DiagnosticLine\&.FilePathTextSpan\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB72\fP of file \fBDotNetCliOutputParserTests\&.cs\fP\&.
.SS "bool Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.CommandLines\&.Models\&.DotNetCliOutputParserTests\&.DiagnosticLine\&.IsValid\fR [get]\fP"

.PP
Definition at line \fB79\fP of file \fBDotNetCliOutputParserTests\&.cs\fP\&.
.SS "\fBDiagnosticTextSpan\fP? Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.CommandLines\&.Models\&.DotNetCliOutputParserTests\&.DiagnosticLine\&.LineAndColumnIndicesTextSpan\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB73\fP of file \fBDotNetCliOutputParserTests\&.cs\fP\&.
.SS "\fBDiagnosticTextSpan\fP? Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.CommandLines\&.Models\&.DotNetCliOutputParserTests\&.DiagnosticLine\&.MessageTextSpan\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB76\fP of file \fBDotNetCliOutputParserTests\&.cs\fP\&.
.SS "\fBDiagnosticTextSpan\fP? Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.CommandLines\&.Models\&.DotNetCliOutputParserTests\&.DiagnosticLine\&.ProjectTextSpan\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB77\fP of file \fBDotNetCliOutputParserTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
