.TH "Luthetus.TextEditor.RazorLib.Autocompletes.Models" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Autocompletes.Models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAutocompleteEntry\fP"
.br
.ti -1c
.RI "interface \fBIAutocompleteIndexer\fP"
.br
.ti -1c
.RI "interface \fBIAutocompleteService\fP"
.br
.ti -1c
.RI "class \fBWordAutocompleteIndexer\fP"
.br
.ti -1c
.RI "class \fBWordAutocompleteService\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBAutocompleteEntryKind\fP { \fBWord\fP, \fBSnippet\fP, \fBVariable\fP, \fBFunction\fP, \fBType\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBLuthetus\&.TextEditor\&.RazorLib\&.Autocompletes\&.Models\&.AutocompleteEntryKind\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIWord \fP
.TP
\f(BISnippet \fP
.TP
\f(BIVariable \fP
.TP
\f(BIFunction \fP
.TP
\f(BIType \fP
.PP
Definition at line \fB3\fP of file \fBAutocompleteEntryKind\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
