.TH "Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBReducer\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "record \fBSetFontFamilyAction\fP (string? FontFamily)"
.br
.ti -1c
.RI "record \fBSetFontSizeAction\fP (int FontSizeInPixels)"
.br
.ti -1c
.RI "record \fBSetCursorWidthAction\fP (double CursorWidthInPixels)"
.br
.ti -1c
.RI "record \fBSetRenderStateKeyAction\fP (Key< \fBRenderState\fP > RenderStateKey)"
.br
.ti -1c
.RI "record \fBSetHeightAction\fP (int? HeightInPixels)"
.br
.ti -1c
.RI "record \fBSetThemeAction\fP (\fBThemeRecord\fP Theme)"
.br
.RI "This is setting the \fBTextEditor\fP's theme specifically\&. This is not to be confused with the AppOptions Themes which get applied at an application level\&. 
.br

.br
 This allows for a "DarkTheme-Application" that has a "LightTheme-TextEditor"\&. "
.ti -1c
.RI "record \fBSetKeymapAction\fP (\fBKeymap\fP \fBKeymap\fP)"
.br
.ti -1c
.RI "record \fBSetShowWhitespaceAction\fP (bool ShowWhitespace)"
.br
.ti -1c
.RI "record \fBSetShowNewlinesAction\fP (bool ShowNewlines)"
.br
.ti -1c
.RI "record \fBSetUseMonospaceOptimizationsAction\fP (bool UseMonospaceOptimizations)"
.br
.ti -1c
.RI "\fBTextEditorOptionsState\fP ()"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const int \fBDEFAULT_FONT_SIZE_IN_PIXELS\fP = 20"
.br
.ti -1c
.RI "const int \fBDEFAULT_ICON_SIZE_IN_PIXELS\fP = 18"
.br
.ti -1c
.RI "const double \fBDEFAULT_CURSOR_WIDTH_IN_PIXELS\fP = 2\&.5"
.br
.ti -1c
.RI "const int \fBMINIMUM_FONT_SIZE_IN_PIXELS\fP = 5"
.br
.ti -1c
.RI "const int \fBMINIMUM_ICON_SIZE_IN_PIXELS\fP = 5"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBTextEditorOptions\fP \fBOptions\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBTextEditorOptionsState\&.Actions\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.Options\&.States\&.TextEditorOptionsState\&.TextEditorOptionsState ()"

.PP
Definition at line \fB12\fP of file \fBTextEditorOptionsState\&.Main\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "record Luthetus\&.TextEditor\&.RazorLib\&.Options\&.States\&.TextEditorOptionsState\&.SetCursorWidthAction (double CursorWidthInPixels)"

.SS "record Luthetus\&.TextEditor\&.RazorLib\&.Options\&.States\&.TextEditorOptionsState\&.SetFontFamilyAction (string? FontFamily)"

.SS "record Luthetus\&.TextEditor\&.RazorLib\&.Options\&.States\&.TextEditorOptionsState\&.SetFontSizeAction (int FontSizeInPixels)"

.SS "record Luthetus\&.TextEditor\&.RazorLib\&.Options\&.States\&.TextEditorOptionsState\&.SetHeightAction (int? HeightInPixels)"

.SS "record Luthetus\&.TextEditor\&.RazorLib\&.Options\&.States\&.TextEditorOptionsState\&.SetKeymapAction (\fBKeymap\fP Keymap)"

.SS "record Luthetus\&.TextEditor\&.RazorLib\&.Options\&.States\&.TextEditorOptionsState\&.SetRenderStateKeyAction (Key< \fBRenderState\fP > RenderStateKey)"

.SS "record Luthetus\&.TextEditor\&.RazorLib\&.Options\&.States\&.TextEditorOptionsState\&.SetShowNewlinesAction (bool ShowNewlines)"

.SS "record Luthetus\&.TextEditor\&.RazorLib\&.Options\&.States\&.TextEditorOptionsState\&.SetShowWhitespaceAction (bool ShowWhitespace)"

.SS "record Luthetus\&.TextEditor\&.RazorLib\&.Options\&.States\&.TextEditorOptionsState\&.SetThemeAction (\fBThemeRecord\fP Theme)"

.PP
This is setting the \fBTextEditor\fP's theme specifically\&. This is not to be confused with the AppOptions Themes which get applied at an application level\&. 
.br

.br
 This allows for a "DarkTheme-Application" that has a "LightTheme-TextEditor"\&. 
.SS "record Luthetus\&.TextEditor\&.RazorLib\&.Options\&.States\&.TextEditorOptionsState\&.SetUseMonospaceOptimizationsAction (bool UseMonospaceOptimizations)"

.SH "Member Data Documentation"
.PP 
.SS "const double Luthetus\&.TextEditor\&.RazorLib\&.Options\&.States\&.TextEditorOptionsState\&.DEFAULT_CURSOR_WIDTH_IN_PIXELS = 2\&.5\fR [static]\fP"

.PP
Definition at line \fB33\fP of file \fBTextEditorOptionsState\&.Main\&.cs\fP\&.
.SS "const int Luthetus\&.TextEditor\&.RazorLib\&.Options\&.States\&.TextEditorOptionsState\&.DEFAULT_FONT_SIZE_IN_PIXELS = 20\fR [static]\fP"

.PP
Definition at line \fB31\fP of file \fBTextEditorOptionsState\&.Main\&.cs\fP\&.
.SS "const int Luthetus\&.TextEditor\&.RazorLib\&.Options\&.States\&.TextEditorOptionsState\&.DEFAULT_ICON_SIZE_IN_PIXELS = 18\fR [static]\fP"

.PP
Definition at line \fB32\fP of file \fBTextEditorOptionsState\&.Main\&.cs\fP\&.
.SS "const int Luthetus\&.TextEditor\&.RazorLib\&.Options\&.States\&.TextEditorOptionsState\&.MINIMUM_FONT_SIZE_IN_PIXELS = 5\fR [static]\fP"

.PP
Definition at line \fB35\fP of file \fBTextEditorOptionsState\&.Main\&.cs\fP\&.
.SS "const int Luthetus\&.TextEditor\&.RazorLib\&.Options\&.States\&.TextEditorOptionsState\&.MINIMUM_ICON_SIZE_IN_PIXELS = 5\fR [static]\fP"

.PP
Definition at line \fB36\fP of file \fBTextEditorOptionsState\&.Main\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBTextEditorOptions\fP Luthetus\&.TextEditor\&.RazorLib\&.Options\&.States\&.TextEditorOptionsState\&.Options\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB38\fP of file \fBTextEditorOptionsState\&.Main\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
