.TH "Luthetus.Common.RazorLib.Dynamics.Models.IDrag" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Dynamics.Models.IDrag
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDynamicViewModel\fP\&.
.PP
Inherited by \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.DynamicViewModelAdapterTextEditor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Task \fBOnDragStartAsync\fP ()"
.br
.ti -1c
.RI "Task \fBOnDragEndAsync\fP (MouseEventArgs mouseEventArgs, \fBIDropzone\fP? dropzone)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "ImmutableArray< \fBIDropzone\fP > \fBDropzoneList\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "Type \fBDragComponentType\fP\fR [get]\fP"
.br
.ti -1c
.RI "Dictionary< string, object?>? \fBDragComponentParameterMap\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBElementDimensions\fP \fBDragElementDimensions\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string? \fBDragCssClass\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string? \fBDragCssStyle\fP\fR [get, set]\fP"
.br
.in -1c

Properties inherited from \fBLuthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDynamicViewModel\fP
.in +1c
.ti -1c
.RI "Key< \fBIDynamicViewModel\fP > \fBDynamicViewModelKey\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBTitle\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBTitleVerbose\fP\fR [get]\fP"
.br
.ti -1c
.RI "Type \fBComponentType\fP\fR [get]\fP"
.br
.ti -1c
.RI "Dictionary< string, object?>? \fBComponentParameterMap\fP\fR [get]\fP"
.br
.ti -1c
.RI "string? \fBSetFocusOnCloseElementId\fP\fR [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Attributes inherited from \fBLuthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDynamicViewModel\fP
.in +1c
.ti -1c
.RI "static readonly string \fBDefaultSetFocusOnCloseElementId\fP = ContextFacts\&.GlobalContext\&.ContextElementId"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBIDrag\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "Task Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDrag\&.OnDragEndAsync (MouseEventArgs mouseEventArgs, \fBIDropzone\fP? dropzone)"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.DynamicViewModelAdapterTextEditor\fP\&.
.SS "Task Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDrag\&.OnDragStartAsync ()"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.DynamicViewModelAdapterTextEditor\fP\&.
.SH "Property Documentation"
.PP 
.SS "Dictionary<string, object?>? Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDrag\&.DragComponentParameterMap\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.DynamicViewModelAdapterTextEditor\fP\&.
.PP
Definition at line \fB12\fP of file \fBIDrag\&.cs\fP\&.
.SS "Type Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDrag\&.DragComponentType\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.DynamicViewModelAdapterTextEditor\fP\&.
.PP
Definition at line \fB11\fP of file \fBIDrag\&.cs\fP\&.
.SS "string? Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDrag\&.DragCssClass\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.DynamicViewModelAdapterTextEditor\fP\&.
.PP
Definition at line \fB14\fP of file \fBIDrag\&.cs\fP\&.
.SS "string? Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDrag\&.DragCssStyle\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.DynamicViewModelAdapterTextEditor\fP\&.
.PP
Definition at line \fB15\fP of file \fBIDrag\&.cs\fP\&.
.SS "\fBElementDimensions\fP Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDrag\&.DragElementDimensions\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.DynamicViewModelAdapterTextEditor\fP\&.
.PP
Definition at line \fB13\fP of file \fBIDrag\&.cs\fP\&.
.SS "ImmutableArray<\fBIDropzone\fP> Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDrag\&.DropzoneList\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.DynamicViewModelAdapterTextEditor\fP\&.
.PP
Definition at line \fB9\fP of file \fBIDrag\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
