.TH "Luthetus.Common.Tests.Basis.Reflectives.States.ReflectiveStateReducerTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Reflectives.States.ReflectiveStateReducerTests \- ReflectiveState\&.Reducer  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBReduceRegisterAction\fP ()"
.br
.RI "ReflectiveState\&.Reducer\&.ReduceRegisterAction(ReflectiveState, ReflectiveState\&.RegisterAction) "
.ti -1c
.RI "void \fBReduceWithAction\fP ()"
.br
.RI "ReflectiveState\&.Reducer\&.ReduceWithAction(ReflectiveState, ReflectiveState\&.WithAction) "
.ti -1c
.RI "void \fBReduceDisposeAction\fP ()"
.br
.RI "ReflectiveState\&.Reducer\&.ReduceDisposeAction(ReflectiveState, ReflectiveState\&.DisposeAction) "
.in -1c
.SH "Detailed Description"
.PP 
ReflectiveState\&.Reducer 
.PP
Definition at line \fB14\fP of file \fBReflectiveStateReducerTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Reflectives\&.States\&.ReflectiveStateReducerTests\&.ReduceDisposeAction ()"

.PP
ReflectiveState\&.Reducer\&.ReduceDisposeAction(ReflectiveState, ReflectiveState\&.DisposeAction) 
.PP
Definition at line \fB90\fP of file \fBReflectiveStateReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Reflectives\&.States\&.ReflectiveStateReducerTests\&.ReduceRegisterAction ()"

.PP
ReflectiveState\&.Reducer\&.ReduceRegisterAction(ReflectiveState, ReflectiveState\&.RegisterAction) 
.PP
Definition at line \fB20\fP of file \fBReflectiveStateReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Reflectives\&.States\&.ReflectiveStateReducerTests\&.ReduceWithAction ()"

.PP
ReflectiveState\&.Reducer\&.ReduceWithAction(ReflectiveState, ReflectiveState\&.WithAction) 
.PP
Definition at line \fB45\fP of file \fBReflectiveStateReducerTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
