.TH "Luthetus.CompilerServices.JavaScript.JavaScriptResource" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.JavaScript.JavaScriptResource
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.CompilerServiceResource\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJavaScriptResource\fP (\fBResourceUri\fP resourceUri, \fBJavaScriptCompilerService\fP jsCompilerService)"
.br
.in -1c

Public Member Functions inherited from \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.CompilerServiceResource\fP
.in +1c
.ti -1c
.RI "\fBCompilerServiceResource\fP (\fBResourceUri\fP resourceUri, \fBICompilerService\fP compilerService)"
.br
.ti -1c
.RI "virtual ImmutableArray< \fBTextEditorTextSpan\fP > \fBGetTokenTextSpans\fP ()"
.br
.ti -1c
.RI "virtual ImmutableArray< \fBITextEditorSymbol\fP > \fBGetSymbols\fP ()"
.br
.ti -1c
.RI "virtual ImmutableArray< \fBTextEditorDiagnostic\fP > \fBGetDiagnostics\fP ()"
.br
.in -1c
.SS "Additional Inherited Members"


Properties inherited from \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.CompilerServiceResource\fP
.in +1c
.ti -1c
.RI "virtual ResourceUri \fBResourceUri\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual \fBICompilerService\fP \fBCompilerService\fP\fR [get]\fP"
.br
.ti -1c
.RI "virtual ? CompilationUnit \fBCompilationUnit\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "virtual ImmutableArray< \fBISyntaxToken\fP > \fBSyntaxTokenList\fP = ImmutableArray<\fBISyntaxToken\fP>\&.Empty\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBJavaScriptResource\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.CompilerServices\&.JavaScript\&.JavaScriptResource\&.JavaScriptResource (\fBResourceUri\fP resourceUri, \fBJavaScriptCompilerService\fP jsCompilerService)"

.PP
Definition at line \fB8\fP of file \fBJavaScriptResource\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
