.TH "Luthetus.CompilerServices.Xml.Html.SyntaxActors.XmlSyntaxWalker" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.Xml.Html.SyntaxActors.XmlSyntaxWalker
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.CSharpProjectSyntaxWalker\fP, and \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.HtmlSyntaxWalker\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBVisit\fP (\fBIHtmlSyntaxNode\fP node)"
.br
.ti -1c
.RI "virtual void \fBVisitAttributeNameNode\fP (\fBAttributeNameNode\fP node)"
.br
.ti -1c
.RI "virtual void \fBVisitAttributeValueNode\fP (\fBAttributeValueNode\fP node)"
.br
.ti -1c
.RI "virtual void \fBVisitAttributeNode\fP (\fBAttributeNode\fP node)"
.br
.ti -1c
.RI "virtual void \fBVisitCommentNode\fP (\fBCommentNode\fP node)"
.br
.ti -1c
.RI "virtual void \fBVisitInjectedLanguageFragmentNode\fP (\fBInjectedLanguageFragmentNode\fP node)"
.br
.ti -1c
.RI "virtual void \fBVisitTagNameNode\fP (\fBTagNameNode\fP node)"
.br
.ti -1c
.RI "virtual void \fBVisitTextNode\fP (\fBTextNode\fP node)"
.br
.ti -1c
.RI "virtual void \fBVisitTagOpeningNode\fP (\fBTagNode\fP node)"
.br
.ti -1c
.RI "virtual void \fBVisitTagClosingNode\fP (\fBTagNode\fP node)"
.br
.ti -1c
.RI "virtual void \fBVisitTagSelfClosingNode\fP (\fBTagNode\fP node)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBXmlSyntaxWalker\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.XmlSyntaxWalker\&.Visit (\fBIHtmlSyntaxNode\fP node)\fR [virtual]\fP"

.PP
Definition at line \fB8\fP of file \fBXmlSyntaxWalker\&.cs\fP\&.
.SS "virtual void Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.XmlSyntaxWalker\&.VisitAttributeNameNode (\fBAttributeNameNode\fP node)\fR [virtual]\fP"

.PP
Reimplemented in \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.HtmlSyntaxWalker\fP\&.
.PP
Definition at line \fB54\fP of file \fBXmlSyntaxWalker\&.cs\fP\&.
.SS "virtual void Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.XmlSyntaxWalker\&.VisitAttributeNode (\fBAttributeNode\fP node)\fR [virtual]\fP"

.PP
Definition at line \fB64\fP of file \fBXmlSyntaxWalker\&.cs\fP\&.
.SS "virtual void Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.XmlSyntaxWalker\&.VisitAttributeValueNode (\fBAttributeValueNode\fP node)\fR [virtual]\fP"

.PP
Reimplemented in \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.HtmlSyntaxWalker\fP\&.
.PP
Definition at line \fB59\fP of file \fBXmlSyntaxWalker\&.cs\fP\&.
.SS "virtual void Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.XmlSyntaxWalker\&.VisitCommentNode (\fBCommentNode\fP node)\fR [virtual]\fP"

.PP
Reimplemented in \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.HtmlSyntaxWalker\fP\&.
.PP
Definition at line \fB69\fP of file \fBXmlSyntaxWalker\&.cs\fP\&.
.SS "virtual void Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.XmlSyntaxWalker\&.VisitInjectedLanguageFragmentNode (\fBInjectedLanguageFragmentNode\fP node)\fR [virtual]\fP"

.PP
Reimplemented in \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.HtmlSyntaxWalker\fP\&.
.PP
Definition at line \fB74\fP of file \fBXmlSyntaxWalker\&.cs\fP\&.
.SS "virtual void Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.XmlSyntaxWalker\&.VisitTagClosingNode (\fBTagNode\fP node)\fR [virtual]\fP"

.PP
Reimplemented in \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.CSharpProjectSyntaxWalker\fP, and \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.HtmlSyntaxWalker\fP\&.
.PP
Definition at line \fB94\fP of file \fBXmlSyntaxWalker\&.cs\fP\&.
.SS "virtual void Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.XmlSyntaxWalker\&.VisitTagNameNode (\fBTagNameNode\fP node)\fR [virtual]\fP"

.PP
Reimplemented in \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.HtmlSyntaxWalker\fP\&.
.PP
Definition at line \fB79\fP of file \fBXmlSyntaxWalker\&.cs\fP\&.
.SS "virtual void Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.XmlSyntaxWalker\&.VisitTagOpeningNode (\fBTagNode\fP node)\fR [virtual]\fP"

.PP
Reimplemented in \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.CSharpProjectSyntaxWalker\fP, and \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.HtmlSyntaxWalker\fP\&.
.PP
Definition at line \fB89\fP of file \fBXmlSyntaxWalker\&.cs\fP\&.
.SS "virtual void Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.XmlSyntaxWalker\&.VisitTagSelfClosingNode (\fBTagNode\fP node)\fR [virtual]\fP"

.PP
Reimplemented in \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.CSharpProjectSyntaxWalker\fP, and \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.HtmlSyntaxWalker\fP\&.
.PP
Definition at line \fB99\fP of file \fBXmlSyntaxWalker\&.cs\fP\&.
.SS "virtual void Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.XmlSyntaxWalker\&.VisitTextNode (\fBTextNode\fP node)\fR [virtual]\fP"

.PP
Definition at line \fB84\fP of file \fBXmlSyntaxWalker\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
