.TH "Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.IVariableDeclarationNode" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.IVariableDeclarationNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.Interfaces\&.IExpressionNode\fP\&.
.PP
Inherited by \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.VariableDeclarationNode\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "TypeClauseNode \fBTypeClauseNode\fP\fR [get]\fP"
.br
.ti -1c
.RI "IdentifierToken \fBIdentifierToken\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBVariableKind\fP \fBVariableKind\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsInitialized\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBHasGetter\fP\fR [get, set]\fP"
.br
.RI "TODO: Remove the 'set;' on this property\&. "
.ti -1c
.RI "bool \fBGetterIsAutoImplemented\fP\fR [get, set]\fP"
.br
.RI "TODO: Remove the 'set;' on this property\&. "
.ti -1c
.RI "bool \fBHasSetter\fP\fR [get, set]\fP"
.br
.RI "TODO: Remove the 'set;' on this property\&. "
.ti -1c
.RI "bool \fBSetterIsAutoImplemented\fP\fR [get, set]\fP"
.br
.RI "TODO: Remove the 'set;' on this property\&. "
.in -1c

Properties inherited from \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.Interfaces\&.IExpressionNode\fP
.in +1c
.ti -1c
.RI "\fBTypeClauseNode\fP \fBResultTypeClauseNode\fP\fR [get]\fP"
.br
.RI "When parsing an expression, there may be a \fBFunctionInvocationNode\fP with a \fBGenericParametersListingNode\fP\&. "
.in -1c

Properties inherited from \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.ISyntax\fP
.in +1c
.ti -1c
.RI "\fBSyntaxKind\fP \fBSyntaxKind\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsFabricated\fP\fR [get]\fP"
.br
.RI "\fBIsFabricated\fP refers to when the ParserSession expected a node to be valid, but it wasn't\&.
.br

.br
For example, a function invocation on an undefined function will construct a BoundFunctionInvocationNode with \fBIsFabricated\fP set to true\&. "
.in -1c
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.ISyntaxNode\fP
.in +1c
.ti -1c
.RI "\fBISyntax\fP[] \fBGetChildList\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBIVariableDeclarationNode\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.Interfaces\&.IVariableDeclarationNode\&.GetterIsAutoImplemented\fR [get]\fP, \fR [set]\fP"

.PP
TODO: Remove the 'set;' on this property\&. 
.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.VariableDeclarationNode\fP\&.
.PP
Definition at line \fB19\fP of file \fBIVariableDeclarationNode\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.Interfaces\&.IVariableDeclarationNode\&.HasGetter\fR [get]\fP, \fR [set]\fP"

.PP
TODO: Remove the 'set;' on this property\&. 
.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.VariableDeclarationNode\fP\&.
.PP
Definition at line \fB15\fP of file \fBIVariableDeclarationNode\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.Interfaces\&.IVariableDeclarationNode\&.HasSetter\fR [get]\fP, \fR [set]\fP"

.PP
TODO: Remove the 'set;' on this property\&. 
.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.VariableDeclarationNode\fP\&.
.PP
Definition at line \fB23\fP of file \fBIVariableDeclarationNode\&.cs\fP\&.
.SS "IdentifierToken Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.Interfaces\&.IVariableDeclarationNode\&.IdentifierToken\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.VariableDeclarationNode\fP\&.
.PP
Definition at line \fB9\fP of file \fBIVariableDeclarationNode\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.Interfaces\&.IVariableDeclarationNode\&.IsInitialized\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.VariableDeclarationNode\fP\&.
.PP
Definition at line \fB11\fP of file \fBIVariableDeclarationNode\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.Interfaces\&.IVariableDeclarationNode\&.SetterIsAutoImplemented\fR [get]\fP, \fR [set]\fP"

.PP
TODO: Remove the 'set;' on this property\&. 
.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.VariableDeclarationNode\fP\&.
.PP
Definition at line \fB27\fP of file \fBIVariableDeclarationNode\&.cs\fP\&.
.SS "TypeClauseNode Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.Interfaces\&.IVariableDeclarationNode\&.TypeClauseNode\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.VariableDeclarationNode\fP\&.
.PP
Definition at line \fB8\fP of file \fBIVariableDeclarationNode\&.cs\fP\&.
.SS "\fBVariableKind\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.Interfaces\&.IVariableDeclarationNode\&.VariableKind\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.VariableDeclarationNode\fP\&.
.PP
Definition at line \fB10\fP of file \fBIVariableDeclarationNode\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
