.TH "Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.FindOverlayDecorationMapper" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.FindOverlayDecorationMapper \- TODO: I copy and pasted \fBDiffs\&.Models\&.TextEditorDiffDecorationMapper\fP\&.\&.\&. \&.\&.\&.to make this class\&. The decorations need to be made\&. I only implemented the highlighting itself for now, and pick the colors later\&.(2024-02-01)\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.TextEditor\&.RazorLib\&.Decorations\&.Models\&.IDecorationMapper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBMap\fP (byte decorationByte)"
.br
.RI "Maps a decorationByte to a CSS class that is in the form of a string\&. "
.in -1c
.SH "Detailed Description"
.PP 
TODO: I copy and pasted \fBDiffs\&.Models\&.TextEditorDiffDecorationMapper\fP\&.\&.\&. \&.\&.\&.to make this class\&. The decorations need to be made\&. I only implemented the highlighting itself for now, and pick the colors later\&.(2024-02-01)\&. 
.PP
Definition at line \fB10\fP of file \fBFindOverlayDecorationMapper\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.FindOverlayDecorationMapper\&.Map (byte decorationByte)"

.PP
Maps a decorationByte to a CSS class that is in the form of a string\&. 
.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.Decorations\&.Models\&.IDecorationMapper\fP\&.
.PP
Definition at line \fB12\fP of file \fBFindOverlayDecorationMapper\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
