.TH "Luthetus.Common.RazorLib.FileSystems.Models.IFileHandler" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.FileSystems.Models.IFileHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryFileHandler\fP, and \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.LocalFileHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Task< bool > \fBExistsAsync\fP (string absolutePathString, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "Task \fBDeleteAsync\fP (string absolutePathString, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "Task \fBCopyAsync\fP (string sourceAbsolutePathString, string destinationAbsolutePathString, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "Task \fBMoveAsync\fP (string sourceAbsolutePathString, string destinationAbsolutePathString, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "Task< DateTime > \fBGetLastWriteTimeAsync\fP (string absolutePathString, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "Task< string > \fBReadAllTextAsync\fP (string absolutePathString, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "Task \fBWriteAllTextAsync\fP (string absolutePathString, string contents, CancellationToken cancellationToken=default)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBIFileHandler\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "Task Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IFileHandler\&.CopyAsync (string sourceAbsolutePathString, string destinationAbsolutePathString, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryFileHandler\fP, and \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.LocalFileHandler\fP\&.
.SS "Task Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IFileHandler\&.DeleteAsync (string absolutePathString, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryFileHandler\fP, and \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.LocalFileHandler\fP\&.
.SS "Task< bool > Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IFileHandler\&.ExistsAsync (string absolutePathString, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryFileHandler\fP, and \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.LocalFileHandler\fP\&.
.SS "Task< DateTime > Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IFileHandler\&.GetLastWriteTimeAsync (string absolutePathString, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryFileHandler\fP, and \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.LocalFileHandler\fP\&.
.SS "Task Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IFileHandler\&.MoveAsync (string sourceAbsolutePathString, string destinationAbsolutePathString, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryFileHandler\fP, and \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.LocalFileHandler\fP\&.
.SS "Task< string > Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IFileHandler\&.ReadAllTextAsync (string absolutePathString, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryFileHandler\fP, and \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.LocalFileHandler\fP\&.
.SS "Task Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IFileHandler\&.WriteAllTextAsync (string absolutePathString, string contents, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryFileHandler\fP, and \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.LocalFileHandler\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
