.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.OpenAngleBracketTokenTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.OpenAngleBracketTokenTests \- \fBOpenAngleBracketToken\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "OpenAngleBracketToken(TextEditorTextSpan) 
.br
----
.br
 \fBOpenAngleBracketToken\&.TextSpan\fP \fBOpenAngleBracketToken\&.SyntaxKind\fP \fBOpenAngleBracketToken\&.IsFabricated\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBOpenAngleBracketToken\fP 
.PP
Definition at line \fB10\fP of file \fBOpenAngleBracketTokenTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.Syntax\&.SyntaxTokens\&.OpenAngleBracketTokenTests\&.Constructor ()"

.PP
OpenAngleBracketToken(TextEditorTextSpan) 
.br
----
.br
 \fBOpenAngleBracketToken\&.TextSpan\fP \fBOpenAngleBracketToken\&.SyntaxKind\fP \fBOpenAngleBracketToken\&.IsFabricated\fP 
.PP
Definition at line \fB20\fP of file \fBOpenAngleBracketTokenTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
