.TH "Luthetus.TextEditor.Tests.Basis.ServiceTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.ServiceTests \- TextEditorService  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "TextEditorService(IState<RazorLib\&.TextEditors\&.States\&.TextEditorModelState>, IState<RazorLib\&.TextEditors\&.States\&.TextEditorViewModelState>, IState<RazorLib\&.Groups\&.States\&.TextEditorGroupState>, IState<RazorLib\&.Diffs\&.States\&.TextEditorDiffState>, IState<Common\&.RazorLib\&.Themes\&.States\&.ThemeState>, IState<RazorLib\&.Options\&.States\&.TextEditorOptionsState>, IState<RazorLib\&.Finds\&.States\&.TextEditorSearchEngineState>, RazorLib\&.Installations\&.Models\&.LuthetusTextEditorConfig, Common\&.RazorLib\&.Storages\&.Models\&.IStorageService, Microsoft\&.JSInterop\&.IJSRuntime, Common\&.RazorLib\&.Storages\&.States\&.StorageSync, IDispatcher) 
.br
----
.br
 TextEditorService\&.ModelStateWrap TextEditorService\&.ViewModelStateWrap TextEditorService\&.GroupStateWrap TextEditorService\&.DiffStateWrap TextEditorService\&.ThemeStateWrap TextEditorService\&.OptionsStateWrap TextEditorService\&.SearchEngineStateWrap TextEditorService\&.ThemeCssClassString TextEditorService\&.ModelApi TextEditorService\&.ViewModelApi TextEditorService\&.GroupApi TextEditorService\&.DiffApi TextEditorService\&.OptionsApi TextEditorService\&.SearchEngineApi "
.in -1c
.SH "Detailed Description"
.PP 
TextEditorService 
.PP
Definition at line \fB6\fP of file \fBServiceTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.ServiceTests\&.Constructor ()"

.PP
TextEditorService(IState<RazorLib\&.TextEditors\&.States\&.TextEditorModelState>, IState<RazorLib\&.TextEditors\&.States\&.TextEditorViewModelState>, IState<RazorLib\&.Groups\&.States\&.TextEditorGroupState>, IState<RazorLib\&.Diffs\&.States\&.TextEditorDiffState>, IState<Common\&.RazorLib\&.Themes\&.States\&.ThemeState>, IState<RazorLib\&.Options\&.States\&.TextEditorOptionsState>, IState<RazorLib\&.Finds\&.States\&.TextEditorSearchEngineState>, RazorLib\&.Installations\&.Models\&.LuthetusTextEditorConfig, Common\&.RazorLib\&.Storages\&.Models\&.IStorageService, Microsoft\&.JSInterop\&.IJSRuntime, Common\&.RazorLib\&.Storages\&.States\&.StorageSync, IDispatcher) 
.br
----
.br
 TextEditorService\&.ModelStateWrap TextEditorService\&.ViewModelStateWrap TextEditorService\&.GroupStateWrap TextEditorService\&.DiffStateWrap TextEditorService\&.ThemeStateWrap TextEditorService\&.OptionsStateWrap TextEditorService\&.SearchEngineStateWrap TextEditorService\&.ThemeCssClassString TextEditorService\&.ModelApi TextEditorService\&.ViewModelApi TextEditorService\&.GroupApi TextEditorService\&.DiffApi TextEditorService\&.OptionsApi TextEditorService\&.SearchEngineApi 
.PP
Definition at line \fB27\fP of file \fBServiceTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
