.TH "Luthetus.Common.RazorLib.Notifications.Models" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Notifications.Models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBINotificationService\fP"
.br
.RI "TODO: SphagettiCode - Not all NotificationState Actions are mapped to a public method (2023-09-19) on this service\&. Furthermore, NotificationState itself is sphagetti code\&. "
.ti -1c
.RI "class \fBNotificationHelper\fP"
.br
.ti -1c
.RI "class \fBNotificationService\fP"
.br
.ti -1c
.RI "class \fBNotificationViewModel\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBNotificationsViewKind\fP { \fBNotifications\fP, \fBRead\fP, \fBDeleted\fP, \fBArchived\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBLuthetus\&.Common\&.RazorLib\&.Notifications\&.Models\&.NotificationsViewKind\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BINotifications \fP
.TP
\f(BIRead \fP
.TP
\f(BIDeleted \fP
.TP
\f(BIArchived \fP
.PP
Definition at line \fB3\fP of file \fBNotificationsViewKind\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
