.TH "Luthetus.Common.Tests.Basis.Contexts.Models.ContextRecordTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Contexts.Models.ContextRecordTests \- \fBContextRecord\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "ContextRecord(Key<ContextRecord>, string, string, Keymap) 
.br
----
.br
 ContextRecord\&.ContextElementId "
.in -1c
.SH "Detailed Description"
.PP 
\fBContextRecord\fP 
.PP
Definition at line \fB10\fP of file \fBContextRecordTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Contexts\&.Models\&.ContextRecordTests\&.Constructor ()"

.PP
ContextRecord(Key<ContextRecord>, string, string, Keymap) 
.br
----
.br
 ContextRecord\&.ContextElementId 
.PP
Definition at line \fB18\fP of file \fBContextRecordTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
