.TH "Luthetus.Common.Tests.Basis.Drags.Models.DragServiceTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Drags.Models.DragServiceTests \- \fBDragService\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "DragService(IDispatcher, IState<DragState>) 
.br
----
.br
 \fBDragService\&.DragStateWrap\fP "
.ti -1c
.RI "void \fBWithAction\fP ()"
.br
.RI "DragService\&.WithAction(Func<DragState, DragState>) "
.in -1c
.SH "Detailed Description"
.PP 
\fBDragService\fP 
.PP
Definition at line \fB11\fP of file \fBDragServiceTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Drags\&.Models\&.DragServiceTests\&.Constructor ()"

.PP
DragService(IDispatcher, IState<DragState>) 
.br
----
.br
 \fBDragService\&.DragStateWrap\fP 
.PP
Definition at line \fB19\fP of file \fBDragServiceTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Drags\&.Models\&.DragServiceTests\&.WithAction ()"

.PP
DragService\&.WithAction(Func<DragState, DragState>) 
.PP
Definition at line \fB31\fP of file \fBDragServiceTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
