.TH "Luthetus.Common.RazorLib.FileSystems.Models.FileSystemDrive" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.FileSystems.Models.FileSystemDrive
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IFileSystemDrive\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileSystemDrive\fP (string driveNameAsIdentifier, \fBIEnvironmentProvider\fP environmentProvider)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBDriveNameAsIdentifier\fP\fR [get]\fP"
.br
.RI "Given: "C:/Users"
.br
 Then \fBDriveNameAsIdentifier\fP is "C"\&. "
.ti -1c
.RI "string \fBDriveNameAsPath\fP\fR [get]\fP"
.br
.RI "Given: "C:/Users"
.br
 Then \fBDriveNameAsPath\fP is "C:"\&. "
.ti -1c
.RI "\fBIEnvironmentProvider\fP \fBEnvironmentProvider\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBFileSystemDrive\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.FileSystemDrive\&.FileSystemDrive (string driveNameAsIdentifier, \fBIEnvironmentProvider\fP environmentProvider)"

.PP
Definition at line \fB5\fP of file \fBFileSystemDrive\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.FileSystemDrive\&.DriveNameAsIdentifier\fR [get]\fP"

.PP
Given: "C:/Users"
.br
 Then \fBDriveNameAsIdentifier\fP is "C"\&. 
.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IFileSystemDrive\fP\&.
.PP
Definition at line \fB13\fP of file \fBFileSystemDrive\&.cs\fP\&.
.SS "string Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.FileSystemDrive\&.DriveNameAsPath\fR [get]\fP"

.PP
Given: "C:/Users"
.br
 Then \fBDriveNameAsPath\fP is "C:"\&. 
.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IFileSystemDrive\fP\&.
.PP
Definition at line \fB14\fP of file \fBFileSystemDrive\&.cs\fP\&.
.SS "\fBIEnvironmentProvider\fP Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.FileSystemDrive\&.EnvironmentProvider\fR [get]\fP"

.PP
Definition at line \fB15\fP of file \fBFileSystemDrive\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
