.TH "Luthetus.CompilerServices.Xml.Html.HtmlSyntaxUnit.HtmlSyntaxUnitBuilder" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.Xml.Html.HtmlSyntaxUnit.HtmlSyntaxUnitBuilder
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHtmlSyntaxUnitBuilder\fP (\fBTagNode\fP rootTagSyntax, \fBDiagnosticBag\fP diagnosticBag)"
.br
.ti -1c
.RI "\fBHtmlSyntaxUnit\fP \fBBuild\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBTagNode\fP \fBRootTagSyntax\fP\fR [get]\fP"
.br
.ti -1c
.RI "DiagnosticBag \fBDiagnosticBag\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB19\fP of file \fBHtmlSyntaxUnit\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.CompilerServices\&.Xml\&.Html\&.HtmlSyntaxUnit\&.HtmlSyntaxUnitBuilder\&.HtmlSyntaxUnitBuilder (\fBTagNode\fP rootTagSyntax, \fBDiagnosticBag\fP diagnosticBag)"

.PP
Definition at line \fB21\fP of file \fBHtmlSyntaxUnit\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBHtmlSyntaxUnit\fP Luthetus\&.CompilerServices\&.Xml\&.Html\&.HtmlSyntaxUnit\&.HtmlSyntaxUnitBuilder\&.Build ()"

.PP
Definition at line \fB30\fP of file \fBHtmlSyntaxUnit\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "DiagnosticBag Luthetus\&.CompilerServices\&.Xml\&.Html\&.HtmlSyntaxUnit\&.HtmlSyntaxUnitBuilder\&.DiagnosticBag\fR [get]\fP"

.PP
Definition at line \fB28\fP of file \fBHtmlSyntaxUnit\&.cs\fP\&.
.SS "\fBTagNode\fP Luthetus\&.CompilerServices\&.Xml\&.Html\&.HtmlSyntaxUnit\&.HtmlSyntaxUnitBuilder\&.RootTagSyntax\fR [get]\fP"

.PP
Definition at line \fB27\fP of file \fBHtmlSyntaxUnit\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
