.TH "Luthetus.TextEditor.RazorLib.Options.Displays.InputTextEditorFontSize" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Options.Displays.InputTextEditorFontSize
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase, and IDisposable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInitialized\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "InputViewModel \fBInputViewModel\fP = \fBInputViewModel\&.Empty\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBFontSizeInPixels\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBInputTextEditorFontSize\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Options\&.Displays\&.InputTextEditorFontSize\&.Dispose ()"

.PP
Definition at line \fB85\fP of file \fBInputTextEditorFontSize\&.razor\&.cs\fP\&.
.SS "override void Luthetus\&.TextEditor\&.RazorLib\&.Options\&.Displays\&.InputTextEditorFontSize\&.OnInitialized ()\fR [protected]\fP"

.PP
Definition at line \fB40\fP of file \fBInputTextEditorFontSize\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Luthetus\&.TextEditor\&.RazorLib\&.Options\&.Displays\&.InputTextEditorFontSize\&.FontSizeInPixels\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB22\fP of file \fBInputTextEditorFontSize\&.razor\&.cs\fP\&.
.SS "InputViewModel Luthetus\&.TextEditor\&.RazorLib\&.Options\&.Displays\&.InputTextEditorFontSize\&.InputViewModel = \fBInputViewModel\&.Empty\fP\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB14\fP of file \fBInputTextEditorFontSize\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
