.TH "Luthetus.Extensions.DotNet.ComponentRenderers.Models.INuGetPackageManagerRendererType" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.ComponentRenderers.Models.INuGetPackageManagerRendererType
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.Extensions\&.DotNet\&.Nugets\&.Displays\&.NuGetPackageManager\fP\&.
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBINuGetPackageManagerRendererType\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
