.TH "Luthetus.Ide.RazorLib.Commands.ICommandFactory" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.Commands.ICommandFactory
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.Ide\&.RazorLib\&.Commands\&.CommandFactory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBIDialog\fP? \fBCodeSearchDialog\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBICommandFactory\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Ide\&.RazorLib\&.Commands\&.ICommandFactory\&.Initialize ()"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.Commands\&.CommandFactory\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBIDialog\fP? Luthetus\&.Ide\&.RazorLib\&.Commands\&.ICommandFactory\&.CodeSearchDialog\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.Commands\&.CommandFactory\fP\&.
.PP
Definition at line \fB9\fP of file \fBICommandFactory\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
