.TH "Luthetus.Common.RazorLib.ComponentRenderers.Models.CommonComponentRenderers" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.ComponentRenderers.Models.CommonComponentRenderers
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Common\&.RazorLib\&.ComponentRenderers\&.Models\&.ICommonComponentRenderers\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommonComponentRenderers\fP (Type errorNotificationRendererType, Type informativeNotificationRendererType, Type progressNotificationRendererType, \fBCommonTreeViews\fP commonTreeViews)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Type \fBErrorNotificationRendererType\fP\fR [get]\fP"
.br
.ti -1c
.RI "Type \fBInformativeNotificationRendererType\fP\fR [get]\fP"
.br
.ti -1c
.RI "Type \fBProgressNotificationRendererType\fP\fR [get]\fP"
.br
.ti -1c
.RI "CommonTreeViews \fBCommonTreeViews\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBCommonComponentRenderers\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Common\&.RazorLib\&.ComponentRenderers\&.Models\&.CommonComponentRenderers\&.CommonComponentRenderers (Type errorNotificationRendererType, Type informativeNotificationRendererType, Type progressNotificationRendererType, \fBCommonTreeViews\fP commonTreeViews)"

.PP
Definition at line \fB5\fP of file \fBCommonComponentRenderers\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "CommonTreeViews Luthetus\&.Common\&.RazorLib\&.ComponentRenderers\&.Models\&.CommonComponentRenderers\&.CommonTreeViews\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.ComponentRenderers\&.Models\&.ICommonComponentRenderers\fP\&.
.PP
Definition at line \fB20\fP of file \fBCommonComponentRenderers\&.cs\fP\&.
.SS "Type Luthetus\&.Common\&.RazorLib\&.ComponentRenderers\&.Models\&.CommonComponentRenderers\&.ErrorNotificationRendererType\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.ComponentRenderers\&.Models\&.ICommonComponentRenderers\fP\&.
.PP
Definition at line \fB17\fP of file \fBCommonComponentRenderers\&.cs\fP\&.
.SS "Type Luthetus\&.Common\&.RazorLib\&.ComponentRenderers\&.Models\&.CommonComponentRenderers\&.InformativeNotificationRendererType\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.ComponentRenderers\&.Models\&.ICommonComponentRenderers\fP\&.
.PP
Definition at line \fB18\fP of file \fBCommonComponentRenderers\&.cs\fP\&.
.SS "Type Luthetus\&.Common\&.RazorLib\&.ComponentRenderers\&.Models\&.CommonComponentRenderers\&.ProgressNotificationRendererType\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.ComponentRenderers\&.Models\&.ICommonComponentRenderers\fP\&.
.PP
Definition at line \fB19\fP of file \fBCommonComponentRenderers\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
