.TH "Luthetus.Common.RazorLib.Clipboards.Models.IClipboardService" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Clipboards.Models.IClipboardService
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.Common\&.RazorLib\&.Clipboards\&.Models\&.InMemoryClipboardService\fP, and \fBLuthetus\&.Common\&.RazorLib\&.Clipboards\&.Models\&.JavaScriptInteropClipboardService\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Task< string > \fBReadClipboard\fP ()"
.br
.ti -1c
.RI "Task \fBSetClipboard\fP (string value)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBIClipboardService\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "Task< string > Luthetus\&.Common\&.RazorLib\&.Clipboards\&.Models\&.IClipboardService\&.ReadClipboard ()"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Clipboards\&.Models\&.InMemoryClipboardService\fP, and \fBLuthetus\&.Common\&.RazorLib\&.Clipboards\&.Models\&.JavaScriptInteropClipboardService\fP\&.
.SS "Task Luthetus\&.Common\&.RazorLib\&.Clipboards\&.Models\&.IClipboardService\&.SetClipboard (string value)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Clipboards\&.Models\&.InMemoryClipboardService\fP, and \fBLuthetus\&.Common\&.RazorLib\&.Clipboards\&.Models\&.JavaScriptInteropClipboardService\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
