.TH "Luthetus.Common.Tests.Basis.Dialogs.States.DialogStateActionsTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Dialogs.States.DialogStateActionsTests \- \fBDialogState\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRegisterAction\fP ()"
.br
.RI "DialogState\&.RegisterAction "
.ti -1c
.RI "void \fBDisposeAction\fP ()"
.br
.RI "DialogState\&.DisposeAction "
.ti -1c
.RI "void \fBSetIsMaximizedAction\fP ()"
.br
.RI "DialogState\&.SetIsMaximizedAction "
.in -1c
.SH "Detailed Description"
.PP 
\fBDialogState\fP 
.PP
Definition at line \fB12\fP of file \fBDialogStateTests\&.Actions\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Dialogs\&.States\&.DialogStateActionsTests\&.DisposeAction ()"

.PP
DialogState\&.DisposeAction 
.PP
Definition at line \fB30\fP of file \fBDialogStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Dialogs\&.States\&.DialogStateActionsTests\&.RegisterAction ()"

.PP
DialogState\&.RegisterAction 
.PP
Definition at line \fB18\fP of file \fBDialogStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Dialogs\&.States\&.DialogStateActionsTests\&.SetIsMaximizedAction ()"

.PP
DialogState\&.SetIsMaximizedAction 
.PP
Definition at line \fB42\fP of file \fBDialogStateTests\&.Actions\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
