.TH "Luthetus.TextEditor.RazorLib.CompilerServices.LexerKeywords" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.CompilerServices.LexerKeywords
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLexerKeywords\fP (ImmutableArray< string > nonContextualKeywords, ImmutableArray< string > controlKeywords, ImmutableArray< string > contextualKeywords)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBLexerKeywords\fP \fBEmpty\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "ImmutableArray< string > \fBNonContextualKeywords\fP\fR [get]\fP"
.br
.RI "The \fBControlKeywords\fP are INCLUDED within the \fBNonContextualKeywords\fP\&. There is a separate \fBControlKeywords\fP list only to provide a different color to the text\&. "
.ti -1c
.RI "ImmutableArray< string > \fBControlKeywords\fP\fR [get]\fP"
.br
.RI "The \fBControlKeywords\fP are INCLUDED within the \fBNonContextualKeywords\fP\&. There is a separate \fBControlKeywords\fP list only to provide a different color to the text\&. "
.ti -1c
.RI "ImmutableArray< string > \fBContextualKeywords\fP\fR [get]\fP"
.br
.ti -1c
.RI "ImmutableArray< string > \fBAllKeywords\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBLexerKeywords\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.LexerKeywords\&.LexerKeywords (ImmutableArray< string > nonContextualKeywords, ImmutableArray< string > controlKeywords, ImmutableArray< string > contextualKeywords)"

.PP
Definition at line \fB12\fP of file \fBLexerKeywords\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBLexerKeywords\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.LexerKeywords\&.Empty\fR [static]\fP"
\fBInitial value:\fP
.nf
= new LexerKeywords(
        ImmutableArray<string>\&.Empty,
        ImmutableArray<string>\&.Empty,
        ImmutableArray<string>\&.Empty)
.PP
.fi

.PP
Definition at line \fB7\fP of file \fBLexerKeywords\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "ImmutableArray<string> Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.LexerKeywords\&.AllKeywords\fR [get]\fP"

.PP
Definition at line \fB36\fP of file \fBLexerKeywords\&.cs\fP\&.
.SS "ImmutableArray<string> Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.LexerKeywords\&.ContextualKeywords\fR [get]\fP"

.PP
Definition at line \fB34\fP of file \fBLexerKeywords\&.cs\fP\&.
.SS "ImmutableArray<string> Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.LexerKeywords\&.ControlKeywords\fR [get]\fP"

.PP
The \fBControlKeywords\fP are INCLUDED within the \fBNonContextualKeywords\fP\&. There is a separate \fBControlKeywords\fP list only to provide a different color to the text\&. 
.PP
Definition at line \fB33\fP of file \fBLexerKeywords\&.cs\fP\&.
.SS "ImmutableArray<string> Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.LexerKeywords\&.NonContextualKeywords\fR [get]\fP"

.PP
The \fBControlKeywords\fP are INCLUDED within the \fBNonContextualKeywords\fP\&. There is a separate \fBControlKeywords\fP list only to provide a different color to the text\&. 
.PP
Definition at line \fB27\fP of file \fBLexerKeywords\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
