.TH "Luthetus.CompilerServices.Css.SyntaxEnums" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.Css.SyntaxEnums
.SH SYNOPSIS
.br
.PP
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBCssSyntaxKind\fP { \fBComment\fP, \fBDocument\fP, \fBPropertyName\fP, \fBPropertyValue\fP, \fBIdentifier\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBLuthetus\&.CompilerServices\&.Css\&.SyntaxEnums\&.CssSyntaxKind\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIComment \fP
.TP
\f(BIDocument \fP
.TP
\f(BIPropertyName \fP
.TP
\f(BIPropertyValue \fP
.TP
\f(BIIdentifier \fP
.PP
Definition at line \fB3\fP of file \fBTagKind\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
