.TH "Luthetus.Common.Tests.Basis.Dialogs.Models.DialogRecordTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Dialogs.Models.DialogRecordTests \- DialogRecord  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "DialogRecord(Key<DialogRecord>, string, Type, Dictionary<string, object?>?, string?) 
.br
----
.br
 DialogRecord\&.ElementDimensions DialogRecord\&.IsMinimized DialogRecord\&.IsMaximized DialogRecord\&.IsResizable "
.ti -1c
.RI "void \fBConstructDefaultDialogDimensions\fP ()"
.br
.RI "DialogRecord\&.ConstructDefaultDialogDimensions() "
.in -1c
.SH "Detailed Description"
.PP 
DialogRecord 
.PP
Definition at line \fB12\fP of file \fBDialogRecordTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Dialogs\&.Models\&.DialogRecordTests\&.ConstructDefaultDialogDimensions ()"

.PP
DialogRecord\&.ConstructDefaultDialogDimensions() 
.PP
Definition at line \fB103\fP of file \fBDialogRecordTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Dialogs\&.Models\&.DialogRecordTests\&.Constructor ()"

.PP
DialogRecord(Key<DialogRecord>, string, Type, Dictionary<string, object?>?, string?) 
.br
----
.br
 DialogRecord\&.ElementDimensions DialogRecord\&.IsMinimized DialogRecord\&.IsMaximized DialogRecord\&.IsResizable 
.PP
Definition at line \fB23\fP of file \fBDialogRecordTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
