.TH "Luthetus.Extensions.DotNet.Tests.Basis.CompilerServices.States.CompilerServiceEditorStateMainTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.Tests.Basis.CompilerServices.States.CompilerServiceEditorStateMainTests \- CompilerServiceEditorState  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "CompilerServiceEditorState(Key<TextEditorViewModel>) 
.br
----
.br
 CompilerServiceEditorState\&.TextEditorViewModelKey "
.in -1c
.SH "Detailed Description"
.PP 
CompilerServiceEditorState 
.PP
Definition at line \fB6\fP of file \fBCompilerServiceEditorStateMainTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.CompilerServices\&.States\&.CompilerServiceEditorStateMainTests\&.Constructor ()"

.PP
CompilerServiceEditorState(Key<TextEditorViewModel>) 
.br
----
.br
 CompilerServiceEditorState\&.TextEditorViewModelKey 
.PP
Definition at line \fB14\fP of file \fBCompilerServiceEditorStateMainTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
