.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.GenericLexer.SyntaxObjects.GenericCommentMultiLineSyntaxTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.GenericLexer.SyntaxObjects.GenericCommentMultiLineSyntaxTests \- \fBGenericCommentMultiLineSyntax\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "GenericCommentMultiLineSyntax(TextEditorTextSpan) 
.br
----
.br
 \fBGenericCommentMultiLineSyntax\&.TextSpan\fP \fBGenericCommentMultiLineSyntax\&.ChildList\fP \fBGenericCommentMultiLineSyntax\&.GenericSyntaxKind\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBGenericCommentMultiLineSyntax\fP 
.PP
Definition at line \fB9\fP of file \fBGenericCommentMultiLineSyntaxTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericCommentMultiLineSyntaxTests\&.Constructor ()"

.PP
GenericCommentMultiLineSyntax(TextEditorTextSpan) 
.br
----
.br
 \fBGenericCommentMultiLineSyntax\&.TextSpan\fP \fBGenericCommentMultiLineSyntax\&.ChildList\fP \fBGenericCommentMultiLineSyntax\&.GenericSyntaxKind\fP 
.PP
Definition at line \fB19\fP of file \fBGenericCommentMultiLineSyntaxTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
