.TH "Luthetus.Ide.Tests.Basis.Terminals.States" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.Tests.Basis.Terminals.States
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTerminalStateMainTests\fP"
.br
.RI "\fBTerminalState\fP "
.ti -1c
.RI "class \fBTerminalStateReducerTests\fP"
.br
.RI "TerminalState\&.Reducer "
.ti -1c
.RI "class \fBTerminalWasModifiedStateActionsTests\fP"
.br
.RI "TerminalWasModifiedState "
.ti -1c
.RI "class \fBTerminalWasModifiedStateMainTests\fP"
.br
.RI "TerminalWasModifiedState "
.ti -1c
.RI "class \fBWellKnownTerminalStateMainTests\fP"
.br
.RI "WellKnownTerminalState "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
