.TH "Luthetus.Common.RazorLib.Contexts.Displays.ContextBoundaryOverlay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Contexts.Displays.ContextBoundaryOverlay
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "InspectableContext \fBInspectableContext\fP = null!\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBContextBoundaryOverlay\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "InspectableContext Luthetus\&.Common\&.RazorLib\&.Contexts\&.Displays\&.ContextBoundaryOverlay\&.InspectableContext = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB14\fP of file \fBContextBoundaryOverlay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
