.TH "Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.GutterDriver" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.GutterDriver
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGutterDriver\fP (\fBTextEditorViewModelDisplay\fP textEditorViewModelDisplay)"
.br
.ti -1c
.RI "RenderFragment \fBGetRenderFragment\fP (\fBTextEditorRenderBatchValidated\fP renderBatch)"
.br
.ti -1c
.RI "string \fBGetGutterStyleCss\fP (int index)"
.br
.ti -1c
.RI "string \fBGetGutterSectionStyleCss\fP ()"
.br
.ti -1c
.RI "\fBIVirtualizationResultWithoutTypeMask\fP \fBGetVirtualizationResult\fP ()"
.br
.RI "Why does this method exist? (2024-08-09)\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly \fBTextEditorViewModelDisplay\fP \fB_root\fP"
.br
.ti -1c
.RI "\fBTextEditorRenderBatchValidated\fP \fB_renderBatch\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBGutterDriver\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.GutterDriver\&.GutterDriver (\fBTextEditorViewModelDisplay\fP textEditorViewModelDisplay)"

.PP
Definition at line \fB14\fP of file \fBGutterDriver\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.GutterDriver\&.GetGutterSectionStyleCss ()"

.PP
Definition at line \fB55\fP of file \fBGutterDriver\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.GutterDriver\&.GetGutterStyleCss (int index)"

.PP
Definition at line \fB29\fP of file \fBGutterDriver\&.cs\fP\&.
.SS "RenderFragment Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.GutterDriver\&.GetRenderFragment (\fBTextEditorRenderBatchValidated\fP renderBatch)"

.PP
Definition at line \fB22\fP of file \fBGutterDriver\&.cs\fP\&.
.SS "\fBIVirtualizationResultWithoutTypeMask\fP Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.GutterDriver\&.GetVirtualizationResult ()"

.PP
Why does this method exist? (2024-08-09)\&. 
.PP
Definition at line \fB68\fP of file \fBGutterDriver\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBTextEditorRenderBatchValidated\fP Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.GutterDriver\&._renderBatch"

.PP
Definition at line \fB20\fP of file \fBGutterDriver\&.cs\fP\&.
.SS "readonly \fBTextEditorViewModelDisplay\fP Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.GutterDriver\&._root"

.PP
Definition at line \fB12\fP of file \fBGutterDriver\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
