.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.PreprocessorDirectiveTokenTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.PreprocessorDirectiveTokenTests \- \fBPreprocessorDirectiveToken\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "PreprocessorDirectiveToken(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan) 
.br
----
.br
 \fBPreprocessorDirectiveToken\&.TextSpan\fP \fBPreprocessorDirectiveToken\&.SyntaxKind\fP \fBPreprocessorDirectiveToken\&.IsFabricated\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBPreprocessorDirectiveToken\fP 
.PP
Definition at line \fB8\fP of file \fBPreprocessorDirectiveTokenTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.Syntax\&.SyntaxTokens\&.PreprocessorDirectiveTokenTests\&.Constructor ()"

.PP
PreprocessorDirectiveToken(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan) 
.br
----
.br
 \fBPreprocessorDirectiveToken\&.TextSpan\fP \fBPreprocessorDirectiveToken\&.SyntaxKind\fP \fBPreprocessorDirectiveToken\&.IsFabricated\fP 
.PP
Definition at line \fB18\fP of file \fBPreprocessorDirectiveTokenTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
