.TH "Luthetus.Extensions.DotNet.ComponentRenderers.Models.ITreeViewSolutionFolderRendererType" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.ComponentRenderers.Models.ITreeViewSolutionFolderRendererType
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Displays\&.TreeViewSolutionFolderDisplay\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBSolutionFolder\fP \fBDotNetSolutionFolder\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBITreeViewSolutionFolderRendererType\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBSolutionFolder\fP Luthetus\&.Extensions\&.DotNet\&.ComponentRenderers\&.Models\&.ITreeViewSolutionFolderRendererType\&.DotNetSolutionFolder\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Displays\&.TreeViewSolutionFolderDisplay\fP\&.
.PP
Definition at line \fB7\fP of file \fBITreeViewSolutionFolderRendererType\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
