.TH "Luthetus.Ide.RazorLib.JsRuntimes.Models.LuthetusIdeJavaScriptInteropApi" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.JsRuntimes.Models.LuthetusIdeJavaScriptInteropApi
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLuthetusIdeJavaScriptInteropApi\fP (IJSRuntime jsRuntime)"
.br
.ti -1c
.RI "ValueTask \fBPreventDefaultBrowserKeybindings\fP ()"
.br
.RI "This function is intended to only be invoked from C# when the LuthetusHostingKind is \fBPhotino\fP\&.
.br

.br
\&. "
.in -1c
.SH "Detailed Description"
.PP 
This class is an exception to the naming convention, "don't use the word 'Luthetus' in class names"\&.

.PP
Reason for this exception: the 'IJSRuntime' datatype is far more common in code, than some specific type (example: DialogDisplay\&.razor)\&. So, adding '\fBLuthetus\fP' in the class name for redundancy seems meaningful here\&. 
.PP
Definition at line \fB12\fP of file \fBLuthetusIdeJavaScriptInteropApi\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Ide\&.RazorLib\&.JsRuntimes\&.Models\&.LuthetusIdeJavaScriptInteropApi\&.LuthetusIdeJavaScriptInteropApi (IJSRuntime jsRuntime)"

.PP
Definition at line \fB16\fP of file \fBLuthetusIdeJavaScriptInteropApi\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "ValueTask Luthetus\&.Ide\&.RazorLib\&.JsRuntimes\&.Models\&.LuthetusIdeJavaScriptInteropApi\&.PreventDefaultBrowserKeybindings ()"

.PP
This function is intended to only be invoked from C# when the LuthetusHostingKind is \fBPhotino\fP\&.
.br

.br
\&. Because when running the native application, the fact that, for example, 'F5' refreshes the native application is very frustrating\&. 
.PP
Definition at line \fB29\fP of file \fBLuthetusIdeJavaScriptInteropApi\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
