.TH "Luthetus.TextEditor.RazorLib.Options.Displays.TextEditorSettings" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Options.Displays.TextEditorSettings
.SH SYNOPSIS
.br
.PP
.PP
Inherits FluxorComponent\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBInputElementCssClass\fP = string\&.Empty\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBTextEditorSettings\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.Options\&.Displays\&.TextEditorSettings\&.InputElementCssClass = string\&.Empty\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB13\fP of file \fBTextEditorSettings\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
