.TH "Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.ICompilerServiceRegistry" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.ICompilerServiceRegistry
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.Extensions\&.Config\&.CompilerServices\&.CompilerServiceRegistry\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.CompilerServiceRegistryDefault\fP, and \fBLuthetus\&.Tutorials\&.RazorLib\&.CompilerServices\&.CompilerServiceRegistry\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBICompilerService\fP \fBGetCompilerService\fP (string extensionNoPeriod)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "ImmutableList< \fBICompilerService\fP > \fBCompilerServiceList\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBICompilerServiceRegistry\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBICompilerService\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.ICompilerServiceRegistry\&.GetCompilerService (string extensionNoPeriod)"

.PP
Implemented in \fBLuthetus\&.Extensions\&.Config\&.CompilerServices\&.CompilerServiceRegistry\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.CompilerServiceRegistryDefault\fP, and \fBLuthetus\&.Tutorials\&.RazorLib\&.CompilerServices\&.CompilerServiceRegistry\fP\&.
.SH "Property Documentation"
.PP 
.SS "ImmutableList<\fBICompilerService\fP> Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.ICompilerServiceRegistry\&.CompilerServiceList\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.Extensions\&.Config\&.CompilerServices\&.CompilerServiceRegistry\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.CompilerServiceRegistryDefault\fP, and \fBLuthetus\&.Tutorials\&.RazorLib\&.CompilerServices\&.CompilerServiceRegistry\fP\&.
.PP
Definition at line \fB8\fP of file \fBICompilerServiceRegistry\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
