.TH "Luthetus.Common.Tests.Basis.Contexts.States.ContextStateActionsTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Contexts.States.ContextStateActionsTests \- \fBContextState\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetFocusedContextHeirarchyAction\fP ()"
.br
.RI "ContextState\&.SetFocusedContextHeirarchyAction "
.ti -1c
.RI "void \fBToggleSelectInspectedContextHeirarchyAction\fP ()"
.br
.RI "ContextState\&.ToggleSelectInspectedContextHeirarchyAction "
.ti -1c
.RI "void \fBSetSelectInspectedContextHeirarchyAction_True\fP ()"
.br
.RI "ContextState\&.IsSelectingInspectableContextHeirarchyAction "
.ti -1c
.RI "void \fBSetSelectInspectedContextHeirarchyAction_False\fP ()"
.br
.RI "ContextState\&.IsSelectingInspectableContextHeirarchyAction "
.ti -1c
.RI "void \fBSetInspectedContextHeirarchyAction\fP ()"
.br
.RI "ContextState\&.SetInspectedContextHeirarchyAction "
.ti -1c
.RI "void \fBAddInspectableContextAction\fP ()"
.br
.RI "ContextState\&.AddInspectableContextAction "
.ti -1c
.RI "void \fBSetContextKeymapAction\fP ()"
.br
.RI "ContextState\&.SetContextKeymapAction "
.in -1c
.SH "Detailed Description"
.PP 
\fBContextState\fP 
.PP
Definition at line \fB13\fP of file \fBContextStateTests\&.Actions\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Contexts\&.States\&.ContextStateActionsTests\&.AddInspectableContextAction ()"

.PP
ContextState\&.AddInspectableContextAction 
.PP
Definition at line \fB87\fP of file \fBContextStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Contexts\&.States\&.ContextStateActionsTests\&.SetContextKeymapAction ()"

.PP
ContextState\&.SetContextKeymapAction 
.PP
Definition at line \fB110\fP of file \fBContextStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Contexts\&.States\&.ContextStateActionsTests\&.SetFocusedContextHeirarchyAction ()"

.PP
ContextState\&.SetFocusedContextHeirarchyAction 
.PP
Definition at line \fB19\fP of file \fBContextStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Contexts\&.States\&.ContextStateActionsTests\&.SetInspectedContextHeirarchyAction ()"

.PP
ContextState\&.SetInspectedContextHeirarchyAction 
.PP
Definition at line \fB68\fP of file \fBContextStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Contexts\&.States\&.ContextStateActionsTests\&.SetSelectInspectedContextHeirarchyAction_False ()"

.PP
ContextState\&.IsSelectingInspectableContextHeirarchyAction 
.PP
Definition at line \fB58\fP of file \fBContextStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Contexts\&.States\&.ContextStateActionsTests\&.SetSelectInspectedContextHeirarchyAction_True ()"

.PP
ContextState\&.IsSelectingInspectableContextHeirarchyAction 
.PP
Definition at line \fB48\fP of file \fBContextStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Contexts\&.States\&.ContextStateActionsTests\&.ToggleSelectInspectedContextHeirarchyAction ()"

.PP
ContextState\&.ToggleSelectInspectedContextHeirarchyAction 
.PP
Definition at line \fB38\fP of file \fBContextStateTests\&.Actions\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
