.TH "Luthetus.TextEditor.RazorLib.FindAlls.Models.ITextEditorSearchEngine" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.FindAlls.Models.ITextEditorSearchEngine
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.TextEditor\&.RazorLib\&.FindAlls\&.Models\&.SearchEngineFileSystem\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Task \fBSearchAsync\fP (string searchQuery, CancellationToken cancellationToken=default)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Key< \fBITextEditorSearchEngine\fP > \fBKey\fP\fR [get]\fP"
.br
.ti -1c
.RI "Type \fBIconComponentRendererType\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBDisplayName\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBITextEditorSearchEngine\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "Task Luthetus\&.TextEditor\&.RazorLib\&.FindAlls\&.Models\&.ITextEditorSearchEngine\&.SearchAsync (string searchQuery, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.FindAlls\&.Models\&.SearchEngineFileSystem\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.FindAlls\&.Models\&.ITextEditorSearchEngine\&.DisplayName\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.FindAlls\&.Models\&.SearchEngineFileSystem\fP\&.
.PP
Definition at line \fB9\fP of file \fBITextEditorSearchEngine\&.cs\fP\&.
.SS "Type Luthetus\&.TextEditor\&.RazorLib\&.FindAlls\&.Models\&.ITextEditorSearchEngine\&.IconComponentRendererType\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.FindAlls\&.Models\&.SearchEngineFileSystem\fP\&.
.PP
Definition at line \fB8\fP of file \fBITextEditorSearchEngine\&.cs\fP\&.
.SS "Key<\fBITextEditorSearchEngine\fP> Luthetus\&.TextEditor\&.RazorLib\&.FindAlls\&.Models\&.ITextEditorSearchEngine\&.Key\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.FindAlls\&.Models\&.SearchEngineFileSystem\fP\&.
.PP
Definition at line \fB7\fP of file \fBITextEditorSearchEngine\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
