.TH "Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBArraySyntaxToken\fP"
.br
.ti -1c
.RI "struct \fBAssociatedNameToken\fP"
.br
.ti -1c
.RI "struct \fBAssociatedValueToken\fP"
.br
.ti -1c
.RI "struct \fBAtToken\fP"
.br
.ti -1c
.RI "struct \fBBadToken\fP"
.br
.ti -1c
.RI "struct \fBBangToken\fP"
.br
.ti -1c
.RI "struct \fBCharLiteralToken\fP"
.br
.ti -1c
.RI "struct \fBCloseAngleBracketToken\fP"
.br
.ti -1c
.RI "struct \fBCloseAssociatedGroupToken\fP"
.br
.ti -1c
.RI "struct \fBCloseBraceToken\fP"
.br
.ti -1c
.RI "struct \fBCloseParenthesisToken\fP"
.br
.ti -1c
.RI "struct \fBCloseSquareBracketToken\fP"
.br
.ti -1c
.RI "struct \fBColonToken\fP"
.br
.ti -1c
.RI "struct \fBCommaToken\fP"
.br
.ti -1c
.RI "struct \fBCommentMultiLineToken\fP"
.br
.ti -1c
.RI "struct \fBCommentSingleLineToken\fP"
.br
.ti -1c
.RI "struct \fBDivisionToken\fP"
.br
.ti -1c
.RI "struct \fBDollarSignToken\fP"
.br
.ti -1c
.RI "struct \fBEndOfFileToken\fP"
.br
.ti -1c
.RI "struct \fBEqualsEqualsToken\fP"
.br
.ti -1c
.RI "struct \fBEqualsToken\fP"
.br
.ti -1c
.RI "struct \fBIdentifierToken\fP"
.br
.ti -1c
.RI "struct \fBKeywordContextualToken\fP"
.br
.ti -1c
.RI "struct \fBKeywordToken\fP"
.br
.ti -1c
.RI "struct \fBLibraryReferenceToken\fP"
.br
.ti -1c
.RI "struct \fBMemberAccessToken\fP"
.br
.ti -1c
.RI "struct \fBMinusMinusToken\fP"
.br
.ti -1c
.RI "struct \fBMinusToken\fP"
.br
.ti -1c
.RI "struct \fBNumericLiteralToken\fP"
.br
.ti -1c
.RI "struct \fBOpenAngleBracketToken\fP"
.br
.ti -1c
.RI "struct \fBOpenAssociatedGroupToken\fP"
.br
.RI "Making types related to JSON key-value pairs\&. Group is for when the value is a grouping of multiple values\&. "
.ti -1c
.RI "struct \fBOpenBraceToken\fP"
.br
.ti -1c
.RI "struct \fBOpenParenthesisToken\fP"
.br
.ti -1c
.RI "struct \fBOpenSquareBracketToken\fP"
.br
.ti -1c
.RI "struct \fBPlusPlusToken\fP"
.br
.ti -1c
.RI "struct \fBPlusToken\fP"
.br
.ti -1c
.RI "struct \fBPreprocessorDirectiveToken\fP"
.br
.RI "TODO: For C# need to implement: Preprocessor directives must be the first non whitespace character on the line\&. "
.ti -1c
.RI "struct \fBQuestionMarkQuestionMarkToken\fP"
.br
.ti -1c
.RI "struct \fBQuestionMarkToken\fP"
.br
.ti -1c
.RI "struct \fBStarToken\fP"
.br
.ti -1c
.RI "struct \fBStatementDelimiterToken\fP"
.br
.ti -1c
.RI "struct \fBStringLiteralToken\fP"
.br
.ti -1c
.RI "struct \fBTriviaToken\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
