.TH "Luthetus.Common.RazorLib.Reflectives.Models.IReflectiveParameter" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Reflectives.Models.IReflectiveParameter
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.Common\&.RazorLib\&.Reflectives\&.Models\&.ReflectiveParameter\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBReflectiveParameterKind\fP \fBReflectiveParameterKind\fP\fR [get]\fP"
.br
.ti -1c
.RI "ConstructorInfo? \fBChosenConstructorInfo\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "object? \fBValue\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "Type \fBType\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBIReflectiveParameter\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "ConstructorInfo? Luthetus\&.Common\&.RazorLib\&.Reflectives\&.Models\&.IReflectiveParameter\&.ChosenConstructorInfo\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Reflectives\&.Models\&.ReflectiveParameter\fP\&.
.PP
Definition at line \fB8\fP of file \fBIReflectiveParameter\&.cs\fP\&.
.SS "\fBReflectiveParameterKind\fP Luthetus\&.Common\&.RazorLib\&.Reflectives\&.Models\&.IReflectiveParameter\&.ReflectiveParameterKind\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Reflectives\&.Models\&.ReflectiveParameter\fP\&.
.PP
Definition at line \fB7\fP of file \fBIReflectiveParameter\&.cs\fP\&.
.SS "Type Luthetus\&.Common\&.RazorLib\&.Reflectives\&.Models\&.IReflectiveParameter\&.Type\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Reflectives\&.Models\&.ReflectiveParameter\fP\&.
.PP
Definition at line \fB10\fP of file \fBIReflectiveParameter\&.cs\fP\&.
.SS "object? Luthetus\&.Common\&.RazorLib\&.Reflectives\&.Models\&.IReflectiveParameter\&.Value\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Reflectives\&.Models\&.ReflectiveParameter\fP\&.
.PP
Definition at line \fB9\fP of file \fBIReflectiveParameter\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
