.TH "Luthetus.TextEditor.Tests.Basis.Cursors.Models.TextEditorSelectionTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.Cursors.Models.TextEditorSelectionTests \- \fBTextEditorSelection\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "\fBTextEditorSelection(int?, int)\fP 
.br
----
.br
 TextEditorSelection\&.AnchorPositionIndex TextEditorSelection\&.EndingPositionIndex "
.in -1c
.SH "Detailed Description"
.PP 
\fBTextEditorSelection\fP 
.PP
Definition at line \fB8\fP of file \fBTextEditorSelectionTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Cursors\&.Models\&.TextEditorSelectionTests\&.Constructor ()"

.PP
\fBTextEditorSelection(int?, int)\fP 
.br
----
.br
 TextEditorSelection\&.AnchorPositionIndex TextEditorSelection\&.EndingPositionIndex 
.PP
Definition at line \fB17\fP of file \fBTextEditorSelectionTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
