.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.PreprocessorLibraryReferenceStatementNodeTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.PreprocessorLibraryReferenceStatementNodeTests \- \fBPreprocessorLibraryReferenceStatementNode\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "PreprocessorLibraryReferenceStatementNode(ISyntaxToken, ISyntaxToken) 
.br
----
.br
 \fBPreprocessorLibraryReferenceStatementNode\&.IncludeDirectiveSyntaxToken\fP \fBPreprocessorLibraryReferenceStatementNode\&.LibraryReferenceSyntaxToken\fP PreprocessorLibraryReferenceStatementNode\&.ChildList \fBPreprocessorLibraryReferenceStatementNode\&.IsFabricated\fP \fBPreprocessorLibraryReferenceStatementNode\&.SyntaxKind\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBPreprocessorLibraryReferenceStatementNode\fP 
.PP
Definition at line \fB9\fP of file \fBPreprocessorLibraryReferenceStatementNodeTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.Syntax\&.SyntaxNodes\&.PreprocessorLibraryReferenceStatementNodeTests\&.Constructor ()"

.PP
PreprocessorLibraryReferenceStatementNode(ISyntaxToken, ISyntaxToken) 
.br
----
.br
 \fBPreprocessorLibraryReferenceStatementNode\&.IncludeDirectiveSyntaxToken\fP \fBPreprocessorLibraryReferenceStatementNode\&.LibraryReferenceSyntaxToken\fP PreprocessorLibraryReferenceStatementNode\&.ChildList \fBPreprocessorLibraryReferenceStatementNode\&.IsFabricated\fP \fBPreprocessorLibraryReferenceStatementNode\&.SyntaxKind\fP 
.PP
Definition at line \fB21\fP of file \fBPreprocessorLibraryReferenceStatementNodeTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
