.TH "Luthetus.CompilerServices.Json.SyntaxActors.JsonSyntaxWalker" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.Json.SyntaxActors.JsonSyntaxWalker
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBVisit\fP (\fBIJsonSyntax\fP jsonSyntax)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "List< \fBJsonPropertyKeySyntax\fP > \fBPropertyKeySyntaxes\fP = new()\fR [get]\fP"
.br
.ti -1c
.RI "List< \fBJsonBooleanSyntax\fP > \fBBooleanSyntaxes\fP = new()\fR [get]\fP"
.br
.ti -1c
.RI "List< \fBJsonIntegerSyntax\fP > \fBIntegerSyntaxes\fP = new()\fR [get]\fP"
.br
.ti -1c
.RI "List< \fBJsonNullSyntax\fP > \fBNullSyntaxes\fP = new()\fR [get]\fP"
.br
.ti -1c
.RI "List< \fBJsonNumberSyntax\fP > \fBNumberSyntaxes\fP = new()\fR [get]\fP"
.br
.ti -1c
.RI "List< \fBJsonStringSyntax\fP > \fBStringSyntaxes\fP = new()\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBJsonSyntaxWalker\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.CompilerServices\&.Json\&.SyntaxActors\&.JsonSyntaxWalker\&.Visit (\fBIJsonSyntax\fP jsonSyntax)"

.PP
Definition at line \fB15\fP of file \fBJsonSyntaxWalker\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "List<\fBJsonBooleanSyntax\fP> Luthetus\&.CompilerServices\&.Json\&.SyntaxActors\&.JsonSyntaxWalker\&.BooleanSyntaxes = new()\fR [get]\fP"

.PP
Definition at line \fB9\fP of file \fBJsonSyntaxWalker\&.cs\fP\&.
.SS "List<\fBJsonIntegerSyntax\fP> Luthetus\&.CompilerServices\&.Json\&.SyntaxActors\&.JsonSyntaxWalker\&.IntegerSyntaxes = new()\fR [get]\fP"

.PP
Definition at line \fB10\fP of file \fBJsonSyntaxWalker\&.cs\fP\&.
.SS "List<\fBJsonNullSyntax\fP> Luthetus\&.CompilerServices\&.Json\&.SyntaxActors\&.JsonSyntaxWalker\&.NullSyntaxes = new()\fR [get]\fP"

.PP
Definition at line \fB11\fP of file \fBJsonSyntaxWalker\&.cs\fP\&.
.SS "List<\fBJsonNumberSyntax\fP> Luthetus\&.CompilerServices\&.Json\&.SyntaxActors\&.JsonSyntaxWalker\&.NumberSyntaxes = new()\fR [get]\fP"

.PP
Definition at line \fB12\fP of file \fBJsonSyntaxWalker\&.cs\fP\&.
.SS "List<\fBJsonPropertyKeySyntax\fP> Luthetus\&.CompilerServices\&.Json\&.SyntaxActors\&.JsonSyntaxWalker\&.PropertyKeySyntaxes = new()\fR [get]\fP"

.PP
Definition at line \fB8\fP of file \fBJsonSyntaxWalker\&.cs\fP\&.
.SS "List<\fBJsonStringSyntax\fP> Luthetus\&.CompilerServices\&.Json\&.SyntaxActors\&.JsonSyntaxWalker\&.StringSyntaxes = new()\fR [get]\fP"

.PP
Definition at line \fB13\fP of file \fBJsonSyntaxWalker\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
