.TH "Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.TextEditorDefaultFooterDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.TextEditorDefaultFooterDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase, and \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.ITextEditorDependentComponent\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInitialized\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "TextEditorViewModelDisplay \fBTextEditorViewModelDisplay\fP = null!\fR [get, set]\fP"
.br
.RI "When implementing this type, add the Blazor attribute '[Parameter]', and the text editor will provide its instance to the dependent component via this Blazor parameter\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBTextEditorDefaultFooterDisplay\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.TextEditorDefaultFooterDisplay\&.Dispose ()"

.PP
Definition at line \fB44\fP of file \fBTextEditorDefaultFooterDisplay\&.razor\&.cs\fP\&.
.SS "override void Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.TextEditorDefaultFooterDisplay\&.OnInitialized ()\fR [protected]\fP"

.PP
Definition at line \fB24\fP of file \fBTextEditorDefaultFooterDisplay\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "TextEditorViewModelDisplay Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.TextEditorDefaultFooterDisplay\&.TextEditorViewModelDisplay = null!\fR [get]\fP, \fR [set]\fP"

.PP
When implementing this type, add the Blazor attribute '[Parameter]', and the text editor will provide its instance to the dependent component via this Blazor parameter\&. The only way for a dependent component to re-render is via the event: \fBTextEditorViewModelDisplay\&.RenderBatchChanged\fP (i\&.e\&.: the 'StateHasChanged()' for the text editor will not cascade to the dependent component)\&.

.PP
One can subscribe to this event and throttle re-rendering as desired\&. This allows the accessory UI that surrounds the text editor to be rendered at a "lower priority" than the text editor itself\&. 
.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.ITextEditorDependentComponent\fP\&.
.PP
Definition at line \fB15\fP of file \fBTextEditorDefaultFooterDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
