.TH "Luthetus.Ide.RazorLib.AppDatas.Models.IAppDataService" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.AppDatas.Models.IAppDataService
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.Ide\&.RazorLib\&.AppDatas\&.Models\&.DoNothingAppDataService\fP, and \fBLuthetus\&.Ide\&.RazorLib\&.AppDatas\&.Models\&.NativeAppDataService\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Task \fBWriteAppDataAsync< AppData >\fP (AppData appData)"
.br
.ti -1c
.RI "Task< AppData?> \fBReadAppDataAsync< AppData >\fP (string assemblyName, string typeName, string? uniqueIdentifier, bool forceRefreshCache)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBIAppDataService\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "Task< AppData?> Luthetus\&.Ide\&.RazorLib\&.AppDatas\&.Models\&.IAppDataService\&.ReadAppDataAsync< AppData > (string assemblyName, string typeName, string? uniqueIdentifier, bool forceRefreshCache)"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.AppDatas\&.Models\&.DoNothingAppDataService\fP, and \fBLuthetus\&.Ide\&.RazorLib\&.AppDatas\&.Models\&.NativeAppDataService\fP\&.
.PP
\fBType Constraints\fP
.TP
\fIAppData\fP : \fI\fBIAppData\fP\fP
.SS "Task Luthetus\&.Ide\&.RazorLib\&.AppDatas\&.Models\&.IAppDataService\&.WriteAppDataAsync< AppData > (AppData appData)"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.AppDatas\&.Models\&.DoNothingAppDataService\fP, and \fBLuthetus\&.Ide\&.RazorLib\&.AppDatas\&.Models\&.NativeAppDataService\fP\&.
.PP
\fBType Constraints\fP
.TP
\fIAppData\fP : \fI\fBIAppData\fP\fP


.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
