.TH "Luthetus.Extensions.Git.Models" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.Git.Models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBGitCliOutputParser\fP"
.br
.ti -1c
.RI "class \fBGitFacts\fP"
.br
.ti -1c
.RI "class \fBGitIdeApi\fP"
.br
.ti -1c
.RI "class \fBGitTreeViewKeyboardEventHandler\fP"
.br
.ti -1c
.RI "class \fBGitTreeViewMouseEventHandler\fP"
.br
.ti -1c
.RI "class \fBTreeViewGitFile\fP"
.br
.ti -1c
.RI "class \fBTreeViewGitFileGroup\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBGitDirtyReason\fP { \fBNone\fP, \fBUntracked\fP, \fBAdded\fP, \fBModified\fP, \fBDeleted\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "record \fBGitFile\fP (\fBIAbsolutePath\fP AbsolutePath, string RelativePathString, \fBGitDirtyReason\fP \fBGitDirtyReason\fP)"
.br
.ti -1c
.RI "record \fBGitRepo\fP (\fBIAbsolutePath\fP AbsolutePath)"
.br
.RI "TODO: Why am I parsing the CLI output? Can I just look at the '\&.git' folder itself? (2024-05-04)\&. "
.ti -1c
.RI "record \fBGitTask\fP (Guid Id, string DisplayName, CancellationToken CancellationToken)"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBLuthetus\&.Extensions\&.Git\&.Models\&.GitDirtyReason\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BINone \fP
.TP
\f(BIUntracked \fP
.TP
\f(BIAdded \fP
.TP
\f(BIModified \fP
.TP
\f(BIDeleted \fP
.PP
Definition at line \fB3\fP of file \fBGitDirtyReason\&.cs\fP\&.
.SH "Function Documentation"
.PP 
.SS "record Luthetus\&.Extensions\&.Git\&.Models\&.GitFile (\fBIAbsolutePath\fP AbsolutePath, string RelativePathString, \fBGitDirtyReason\fP GitDirtyReason)"

.PP
Definition at line \fB6\fP of file \fBGitFile\&.cs\fP\&.
.SS "record Luthetus\&.Extensions\&.Git\&.Models\&.GitRepo (\fBIAbsolutePath\fP AbsolutePath)"

.PP
TODO: Why am I parsing the CLI output? Can I just look at the '\&.git' folder itself? (2024-05-04)\&. 
.SS "record Luthetus\&.Extensions\&.Git\&.Models\&.GitTask (Guid Id, string DisplayName, CancellationToken CancellationToken)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
