.TH "Luthetus.CompilerServices.CSharp.Facts.CSharpFacts" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.CSharp.Facts.CSharpFacts
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNamespaces\fP"
.br
.ti -1c
.RI "class \fBScopeFacts\fP"
.br
.ti -1c
.RI "class \fBTypes\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBCSharpFacts\&.Namespaces\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
