.TH "Luthetus.Common.Tests.Basis.Reflectives.Models.ReflectiveParameterTests.SampleComplexType" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Reflectives.Models.ReflectiveParameterTests.SampleComplexType
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSampleComplexType\fP (string firstName, string lastName)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBFirstName\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBLastName\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBDisplayName\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB84\fP of file \fBReflectiveParameterTests\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Common\&.Tests\&.Basis\&.Reflectives\&.Models\&.ReflectiveParameterTests\&.SampleComplexType\&.SampleComplexType (string firstName, string lastName)"

.PP
Definition at line \fB86\fP of file \fBReflectiveParameterTests\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Luthetus\&.Common\&.Tests\&.Basis\&.Reflectives\&.Models\&.ReflectiveParameterTests\&.SampleComplexType\&.DisplayName\fR [get]\fP"

.PP
Definition at line \fB95\fP of file \fBReflectiveParameterTests\&.cs\fP\&.
.SS "string Luthetus\&.Common\&.Tests\&.Basis\&.Reflectives\&.Models\&.ReflectiveParameterTests\&.SampleComplexType\&.FirstName\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB92\fP of file \fBReflectiveParameterTests\&.cs\fP\&.
.SS "string Luthetus\&.Common\&.Tests\&.Basis\&.Reflectives\&.Models\&.ReflectiveParameterTests\&.SampleComplexType\&.LastName\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB93\fP of file \fBReflectiveParameterTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
