.TH "Luthetus.Common.Tests.Basis.FileSystems.Models.RelativePathTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.FileSystems.Models.RelativePathTests \- RelativePath  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "RelativePath(string, bool, IEnvironmentProvider) RelativePath\&.PathType RelativePath\&.IsDirectory RelativePath\&.EnvironmentProvider RelativePath\&.AncestorDirectoryList RelativePath\&.NameNoExtension RelativePath\&.ExtensionNoPeriod RelativePath\&.UpDirDirectiveCount RelativePath\&.ExactInput RelativePath\&.Value RelativePath\&.NameWithExtension "
.in -1c
.SH "Detailed Description"
.PP 
RelativePath 
.PP
Definition at line \fB10\fP of file \fBRelativePathTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.FileSystems\&.Models\&.RelativePathTests\&.Constructor ()"

.PP
RelativePath(string, bool, IEnvironmentProvider) RelativePath\&.PathType RelativePath\&.IsDirectory RelativePath\&.EnvironmentProvider RelativePath\&.AncestorDirectoryList RelativePath\&.NameNoExtension RelativePath\&.ExtensionNoPeriod RelativePath\&.UpDirDirectiveCount RelativePath\&.ExactInput RelativePath\&.Value RelativePath\&.NameWithExtension 
.PP
Definition at line \fB26\fP of file \fBRelativePathTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
