.TH "Luthetus.Extensions.DotNet.Tests.Basis.Nugets.Models" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.Tests.Basis.Nugets.Models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCSharpProjectNugetPackageReferenceTests\fP"
.br
.RI "CSharpProjectNugetPackageReference "
.ti -1c
.RI "class \fBLightWeightNugetPackageRecordTests\fP"
.br
.RI "LightWeightNugetPackageRecord "
.ti -1c
.RI "class \fBNugetPackageManagerProviderAzureSearchUsncTests\fP"
.br
.RI "NugetPackageManagerProviderAzureSearchUsnc "
.ti -1c
.RI "class \fBNugetPackageRecordTests\fP"
.br
.RI "NugetPackageRecord "
.ti -1c
.RI "class \fBNugetPackageVersionRecordTests\fP"
.br
.RI "NugetPackageVersionRecord "
.ti -1c
.RI "class \fBNugetResponseTests\fP"
.br
.RI "NugetResponse "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
