.TH "Luthetus.Common.RazorLib.Commands.Models.TreeViewCommand" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Commands.Models.TreeViewCommand
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Common\&.RazorLib\&.Commands\&.Models\&.CommandWithType< T >\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTreeViewCommand\fP (string displayName, string internalIdentifier, bool shouldBubble, Func< \fBICommandArgs\fP, Task > commandFunc)"
.br
.in -1c

Public Member Functions inherited from \fBLuthetus\&.Common\&.RazorLib\&.Commands\&.Models\&.CommandNoType\fP
.in +1c
.ti -1c
.RI "\fBCommandNoType\fP (string displayName, string internalIdentifier, bool shouldBubble, Func< \fBICommandArgs\fP, Task > commandFunc)"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBLuthetus\&.Common\&.RazorLib\&.Commands\&.Models\&.CommandWithType< T >\fP
.in +1c
.ti -1c
.RI "\fBCommandWithType\fP (string displayName, string internalIdentifier, bool shouldBubble, Func< \fBICommandArgs\fP, Task > commandFunc)"
.br
.in -1c

Properties inherited from \fBLuthetus\&.Common\&.RazorLib\&.Commands\&.Models\&.CommandNoType\fP
.in +1c
.ti -1c
.RI "string \fBDisplayName\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBInternalIdentifier\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBShouldBubble\fP\fR [get]\fP"
.br
.ti -1c
.RI "Func< \fBICommandArgs\fP, Task > \fBCommandFunc\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBTreeViewCommand\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Common\&.RazorLib\&.Commands\&.Models\&.TreeViewCommand\&.TreeViewCommand (string displayName, string internalIdentifier, bool shouldBubble, Func< \fBICommandArgs\fP, Task > commandFunc)"

.PP
Definition at line \fB5\fP of file \fBTreeViewCommand\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
