.TH "Luthetus.TextEditor.RazorLib.CompilerServices.EvaluatorResult" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.CompilerServices.EvaluatorResult
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEvaluatorResult\fP (\fBType\fP type, object result)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Type \fBType\fP\fR [get]\fP"
.br
.ti -1c
.RI "object \fBResult\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBEvaluatorResult\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.EvaluatorResult\&.EvaluatorResult (\fBType\fP type, object result)"

.PP
Definition at line \fB5\fP of file \fBEvaluatorResult\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "object Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.EvaluatorResult\&.Result\fR [get]\fP"

.PP
Definition at line \fB12\fP of file \fBEvaluatorResult\&.cs\fP\&.
.SS "Type Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.EvaluatorResult\&.Type\fR [get]\fP"

.PP
Definition at line \fB11\fP of file \fBEvaluatorResult\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
