.TH "Luthetus.Common.RazorLib.Dimensions.States" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Dimensions.States
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "partial record \fBAppDimensionState\fP (int Width, int Height, int Left, int Top)"
.br
.RI "The measurements are in pixels (px)\&. This class is in reference to the "browser", "user agent", "desktop application which is rendering a webview", etc\&.\&.\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "partial record Luthetus\&.Common\&.RazorLib\&.Dimensions\&.States\&.AppDimensionState (int Width, int Height, int Left, int Top)"

.PP
The measurements are in pixels (px)\&. This class is in reference to the "browser", "user agent", "desktop application which is rendering a webview", etc\&.\&.\&. When one resizes the application, then IDispatcher\&.IDispatcher\&.Dispatch the SetAppDimensionStateAction\&.

.PP
Any part of the application can subscribe to this state, and be notified when a SetAppDimensionStateAction was reduced\&.

.PP
\fBParameters\fP
.RS 4
\fIWidth\fP The unit of measurement is Pixels (px)\&. This describes the Width of the application\&. 
.RE
.PP

.PP
\fBParameters\fP
.RS 4
\fIHeight\fP The unit of measurement is Pixels (px)\&. This describes the Height of the application\&. 
.RE
.PP

.PP
\fBParameters\fP
.RS 4
\fILeft\fP The unit of measurement is Pixels (px)\&. This describes the distance the application is from the left side of the "display/monitor"\&. 
.RE
.PP

.PP
\fBParameters\fP
.RS 4
\fITop\fP The unit of measurement is Pixels (px)\&. This describes the distance the application is from the top side of the "display/monitor"\&. 
.RE
.PP

.PP
Definition at line \fB36\fP of file \fBAppDimensionState\&.Main\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
