.TH "Luthetus.CompilerServices.DotNetSolution.Models.DotNetSolutionGlobalSectionBuilder" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.DotNetSolution.Models.DotNetSolutionGlobalSectionBuilder
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDotNetSolutionGlobalSection\fP \fBBuild\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBAssociatedValueToken\fP? \fBGlobalSectionArgument\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBAssociatedValueToken\fP? \fBGlobalSectionOrder\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "AssociatedEntryGroup \fBAssociatedEntryGroup\fP = new(openAssociatedGroupToken: default, ImmutableArray<\fBIAssociatedEntry\fP>\&.Empty, closeAssociatedGroupToken: default)\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBDotNetSolutionGlobalSectionBuilder\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBDotNetSolutionGlobalSection\fP Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.DotNetSolutionGlobalSectionBuilder\&.Build ()"

.PP
Definition at line \fB13\fP of file \fBDotNetSolutionGlobalSectionBuilder\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "AssociatedEntryGroup Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.DotNetSolutionGlobalSectionBuilder\&.AssociatedEntryGroup = new(openAssociatedGroupToken: default, ImmutableArray<\fBIAssociatedEntry\fP>\&.Empty, closeAssociatedGroupToken: default)\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB11\fP of file \fBDotNetSolutionGlobalSectionBuilder\&.cs\fP\&.
.SS "\fBAssociatedValueToken\fP? Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.DotNetSolutionGlobalSectionBuilder\&.GlobalSectionArgument\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB9\fP of file \fBDotNetSolutionGlobalSectionBuilder\&.cs\fP\&.
.SS "\fBAssociatedValueToken\fP? Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.DotNetSolutionGlobalSectionBuilder\&.GlobalSectionOrder\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB10\fP of file \fBDotNetSolutionGlobalSectionBuilder\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
