.TH "Luthetus.Common.Tests.Basis.Notifications.States.NotificationStateActionsTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Notifications.States.NotificationStateActionsTests \- \fBNotificationState\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRegisterAction\fP ()"
.br
.RI "NotificationState\&.RegisterAction "
.ti -1c
.RI "void \fBDisposeAction\fP ()"
.br
.RI "NotificationState\&.DisposeAction "
.ti -1c
.RI "void \fBMakeReadAction\fP ()"
.br
.RI "NotificationState\&.MakeReadAction "
.ti -1c
.RI "void \fBUndoMakeReadAction\fP ()"
.br
.RI "NotificationState\&.UndoMakeReadAction "
.ti -1c
.RI "void \fBMakeDeletedAction\fP ()"
.br
.RI "NotificationState\&.MakeDeletedAction "
.ti -1c
.RI "void \fBUndoMakeDeletedAction\fP ()"
.br
.RI "NotificationState\&.UndoMakeDeletedAction "
.ti -1c
.RI "void \fBMakeArchivedAction\fP ()"
.br
.RI "NotificationState\&.MakeArchivedAction "
.ti -1c
.RI "void \fBUndoMakeArchivedAction\fP ()"
.br
.RI "NotificationState\&.UndoMakeArchivedAction "
.ti -1c
.RI "void \fBClearDefaultAction\fP ()"
.br
.RI "NotificationState\&.ClearDefaultAction "
.ti -1c
.RI "void \fBClearReadAction\fP ()"
.br
.RI "NotificationState\&.ClearReadAction "
.ti -1c
.RI "void \fBClearDeletedAction\fP ()"
.br
.RI "NotificationState\&.ClearDeletedAction "
.ti -1c
.RI "void \fBClearArchivedAction\fP ()"
.br
.RI "NotificationState\&.ClearArchivedAction "
.in -1c
.SH "Detailed Description"
.PP 
\fBNotificationState\fP 
.PP
Definition at line \fB12\fP of file \fBNotificationStateTests\&.Actions\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Notifications\&.States\&.NotificationStateActionsTests\&.ClearArchivedAction ()"

.PP
NotificationState\&.ClearArchivedAction 
.PP
Definition at line \fB150\fP of file \fBNotificationStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Notifications\&.States\&.NotificationStateActionsTests\&.ClearDefaultAction ()"

.PP
NotificationState\&.ClearDefaultAction 
.PP
Definition at line \fB114\fP of file \fBNotificationStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Notifications\&.States\&.NotificationStateActionsTests\&.ClearDeletedAction ()"

.PP
NotificationState\&.ClearDeletedAction 
.PP
Definition at line \fB138\fP of file \fBNotificationStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Notifications\&.States\&.NotificationStateActionsTests\&.ClearReadAction ()"

.PP
NotificationState\&.ClearReadAction 
.PP
Definition at line \fB126\fP of file \fBNotificationStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Notifications\&.States\&.NotificationStateActionsTests\&.DisposeAction ()"

.PP
NotificationState\&.DisposeAction 
.PP
Definition at line \fB30\fP of file \fBNotificationStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Notifications\&.States\&.NotificationStateActionsTests\&.MakeArchivedAction ()"

.PP
NotificationState\&.MakeArchivedAction 
.PP
Definition at line \fB90\fP of file \fBNotificationStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Notifications\&.States\&.NotificationStateActionsTests\&.MakeDeletedAction ()"

.PP
NotificationState\&.MakeDeletedAction 
.PP
Definition at line \fB66\fP of file \fBNotificationStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Notifications\&.States\&.NotificationStateActionsTests\&.MakeReadAction ()"

.PP
NotificationState\&.MakeReadAction 
.PP
Definition at line \fB42\fP of file \fBNotificationStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Notifications\&.States\&.NotificationStateActionsTests\&.RegisterAction ()"

.PP
NotificationState\&.RegisterAction 
.PP
Definition at line \fB18\fP of file \fBNotificationStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Notifications\&.States\&.NotificationStateActionsTests\&.UndoMakeArchivedAction ()"

.PP
NotificationState\&.UndoMakeArchivedAction 
.PP
Definition at line \fB102\fP of file \fBNotificationStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Notifications\&.States\&.NotificationStateActionsTests\&.UndoMakeDeletedAction ()"

.PP
NotificationState\&.UndoMakeDeletedAction 
.PP
Definition at line \fB78\fP of file \fBNotificationStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Notifications\&.States\&.NotificationStateActionsTests\&.UndoMakeReadAction ()"

.PP
NotificationState\&.UndoMakeReadAction 
.PP
Definition at line \fB54\fP of file \fBNotificationStateTests\&.Actions\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
