.TH "Luthetus.Common.RazorLib.Tabs.Displays.TabDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Tabs.Displays.TabDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase, and IDisposable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSubscribeToDragEventForScrolling\fP (\fBIDrag\fP draggable)"
.br
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInitialized\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Func< \fBTabContextMenuEventArgs\fP, Task >? \fBHandleTabButtonOnContextMenu\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBITab\fP \fBTab\fP = null!\fR [get, set]\fP"
.br
.ti -1c
.RI "string? \fBCssClassString\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBShouldDisplayCloseButton\fP = true\fR [get, set]\fP"
.br
.ti -1c
.RI "string? \fBCssStyleString\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsBeingDragged\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB18\fP of file \fBTabDisplay\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.RazorLib\&.Tabs\&.Displays\&.TabDisplay\&.Dispose ()"

.PP
Definition at line \fB316\fP of file \fBTabDisplay\&.razor\&.cs\fP\&.
.SS "override void Luthetus\&.Common\&.RazorLib\&.Tabs\&.Displays\&.TabDisplay\&.OnInitialized ()\fR [protected]\fP"

.PP
Definition at line \fB65\fP of file \fBTabDisplay\&.razor\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.Tabs\&.Displays\&.TabDisplay\&.SubscribeToDragEventForScrolling (\fBIDrag\fP draggable)"

.PP
Definition at line \fB260\fP of file \fBTabDisplay\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string? Luthetus\&.Common\&.RazorLib\&.Tabs\&.Displays\&.TabDisplay\&.CssClassString\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB40\fP of file \fBTabDisplay\&.razor\&.cs\fP\&.
.SS "string? Luthetus\&.Common\&.RazorLib\&.Tabs\&.Displays\&.TabDisplay\&.CssStyleString\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB44\fP of file \fBTabDisplay\&.razor\&.cs\fP\&.
.SS "Func<\fBTabContextMenuEventArgs\fP, Task>? Luthetus\&.Common\&.RazorLib\&.Tabs\&.Displays\&.TabDisplay\&.HandleTabButtonOnContextMenu\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB34\fP of file \fBTabDisplay\&.razor\&.cs\fP\&.
.SS "bool Luthetus\&.Common\&.RazorLib\&.Tabs\&.Displays\&.TabDisplay\&.IsBeingDragged\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB46\fP of file \fBTabDisplay\&.razor\&.cs\fP\&.
.SS "bool Luthetus\&.Common\&.RazorLib\&.Tabs\&.Displays\&.TabDisplay\&.ShouldDisplayCloseButton = true\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB42\fP of file \fBTabDisplay\&.razor\&.cs\fP\&.
.SS "\fBITab\fP Luthetus\&.Common\&.RazorLib\&.Tabs\&.Displays\&.TabDisplay\&.Tab = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB37\fP of file \fBTabDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
