.TH "Luthetus.Ide.Tests.Basis.FolderExplorers.States.FolderExplorerStateReducerTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.Tests.Basis.FolderExplorers.States.FolderExplorerStateReducerTests \- FolderExplorerState\&.Reducer  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBReduceWithAction\fP ()"
.br
.RI "FolderExplorerState\&.Reducer\&.ReduceWithAction "
.in -1c
.SH "Detailed Description"
.PP 
FolderExplorerState\&.Reducer 
.PP
Definition at line \fB8\fP of file \fBFolderExplorerStateReducerTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.FolderExplorers\&.States\&.FolderExplorerStateReducerTests\&.ReduceWithAction ()"

.PP
FolderExplorerState\&.Reducer\&.ReduceWithAction 
.PP
Definition at line \fB14\fP of file \fBFolderExplorerStateReducerTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
