.TH "Luthetus.Ide.RazorLib.CodeSearches.Models" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.CodeSearches.Models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCodeSearchTreeViewKeyboardEventHandler\fP"
.br
.ti -1c
.RI "class \fBCodeSearchTreeViewMouseEventHandler\fP"
.br
.ti -1c
.RI "class \fBTreeViewCodeSearchTextSpan\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBCodeSearchFilterKind\fP { \fBNone\fP, \fBFiles\fP, \fBTypes\fP, \fBMembers\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBLuthetus\&.Ide\&.RazorLib\&.CodeSearches\&.Models\&.CodeSearchFilterKind\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BINone \fP
.TP
\f(BIFiles \fP
.TP
\f(BITypes \fP
.TP
\f(BIMembers \fP
.PP
Definition at line \fB3\fP of file \fBCodeSearchFilterKind\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
