.TH "Luthetus.Ide.RazorLib.CodeSearches.Displays.CodeSearchDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.CodeSearches.Displays.CodeSearchDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits FluxorComponent\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInitialized\fP ()"
.br
.ti -1c
.RI "override void \fBOnAfterRender\fP (bool firstRender)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB23\fP of file \fBCodeSearchDisplay\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Luthetus\&.Ide\&.RazorLib\&.CodeSearches\&.Displays\&.CodeSearchDisplay\&.OnAfterRender (bool firstRender)\fR [protected]\fP"

.PP
Definition at line \fB100\fP of file \fBCodeSearchDisplay\&.razor\&.cs\fP\&.
.SS "override void Luthetus\&.Ide\&.RazorLib\&.CodeSearches\&.Displays\&.CodeSearchDisplay\&.OnInitialized ()\fR [protected]\fP"

.PP
Definition at line \fB77\fP of file \fBCodeSearchDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
