.TH "Luthetus.TextEditor.RazorLib.Edits.Models.ITextEditorEdit" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Edits.Models.ITextEditorEdit
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.TextEditorEditBackspace\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.TextEditorEditBackspaceBatch\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.TextEditorEditConstructor\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.TextEditorEditDelete\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.TextEditorEditDeleteBatch\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.TextEditorEditInsert\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.TextEditorEditInsertBatch\fP, and \fBLuthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.TextEditorEditOther\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBTextEditorEditKind\fP \fBEditKind\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBITextEditorEdit\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBTextEditorEditKind\fP Luthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.ITextEditorEdit\&.EditKind\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.TextEditorEditBackspace\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.TextEditorEditBackspaceBatch\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.TextEditorEditConstructor\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.TextEditorEditDelete\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.TextEditorEditDeleteBatch\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.TextEditorEditInsert\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.TextEditorEditInsertBatch\fP, and \fBLuthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.TextEditorEditOther\fP\&.
.PP
Definition at line \fB5\fP of file \fBITextEditorEdit\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
