.TH "Luthetus.TextEditor.Tests.Basis.Commands.Models.Vims" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.Commands.Models.Vims
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTextEditorCommandVimFactsMotionsTests\fP"
.br
.RI "TextEditorCommandVimFacts\&.Motions "
.ti -1c
.RI "class \fBTextEditorCommandVimFactsVerbsTests\fP"
.br
.RI "TextEditorCommandVimFacts\&.Verbs "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
