.TH "Luthetus.TextEditor.RazorLib.Diffs.States.TextEditorDiffState.Reducer" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Diffs.States.TextEditorDiffState.Reducer
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBTextEditorDiffState\fP \fBReduceDisposeAction\fP (\fBTextEditorDiffState\fP inState, \fBDisposeAction\fP disposeAction)"
.br
.ti -1c
.RI "static \fBTextEditorDiffState\fP \fBReduceRegisterAction\fP (\fBTextEditorDiffState\fP inState, \fBRegisterAction\fP registerAction)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBTextEditorDiffState\&.Reducer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBTextEditorDiffState\fP Luthetus\&.TextEditor\&.RazorLib\&.Diffs\&.States\&.TextEditorDiffState\&.Reducer\&.ReduceDisposeAction (\fBTextEditorDiffState\fP inState, \fBDisposeAction\fP disposeAction)\fR [static]\fP"

.PP
Definition at line \fB11\fP of file \fBTextEditorDiffState\&.Reducer\&.cs\fP\&.
.SS "\fBTextEditorDiffState\fP Luthetus\&.TextEditor\&.RazorLib\&.Diffs\&.States\&.TextEditorDiffState\&.Reducer\&.ReduceRegisterAction (\fBTextEditorDiffState\fP inState, \fBRegisterAction\fP registerAction)\fR [static]\fP"

.PP
Definition at line \fB30\fP of file \fBTextEditorDiffState\&.Reducer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
