.TH "Source/Tests/Ide/Basis/Installations/Models/LuthetusIdeConfigTests.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Tests/Ide/Basis/Installations/Models/LuthetusIdeConfigTests.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Ide\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Ide\&.Tests\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Ide\&.Tests\&.Basis\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Ide\&.Tests\&.Basis\&.Installations\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Ide\&.Tests\&.Basis\&.Installations\&.Models\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "record \fBLuthetus\&.Ide\&.Tests\&.Basis\&.Installations\&.Models\&.LuthetusIdeConfigTests\fP"
.br
.RI "\fBLuthetusIdeConfig\fP "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
