.TH "Luthetus.Extensions.DotNet.CompilerServices.Models.CompilerServiceIdeApi" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.CompilerServices.Models.CompilerServiceIdeApi
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCompilerServiceIdeApi\fP (\fBDotNetBackgroundTaskApi\fP dotNetBackgroundTaskApi, \fBIdeBackgroundTaskApi\fP ideBackgroundTaskApi, \fBIBackgroundTaskService\fP backgroundTaskService, IState< \fBCompilerServiceExplorerState\fP > compilerServiceExplorerStateWrap, \fBICompilerServiceRegistry\fP compilerServiceRegistry, \fBIIdeComponentRenderers\fP ideComponentRenderers, \fBICommonComponentRenderers\fP commonComponentRenderers, \fBITreeViewService\fP treeViewService, IDispatcher \fBdispatcher\fP)"
.br
.ti -1c
.RI "void \fBSetCompilerServiceExplorerTreeView\fP ()"
.br
.RI "TODO: Iterate over _compilerServiceExplorerStateWrap\&.Value\&.CompilerServiceList instead\&.\&.\&. \&.\&.\&.of invoking 'GetCompilerService' with hardcoded values\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB17\fP of file \fBCompilerServiceIdeApi\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Extensions\&.DotNet\&.CompilerServices\&.Models\&.CompilerServiceIdeApi\&.CompilerServiceIdeApi (\fBDotNetBackgroundTaskApi\fP dotNetBackgroundTaskApi, \fBIdeBackgroundTaskApi\fP ideBackgroundTaskApi, \fBIBackgroundTaskService\fP backgroundTaskService, IState< \fBCompilerServiceExplorerState\fP > compilerServiceExplorerStateWrap, \fBICompilerServiceRegistry\fP compilerServiceRegistry, \fBIIdeComponentRenderers\fP ideComponentRenderers, \fBICommonComponentRenderers\fP commonComponentRenderers, \fBITreeViewService\fP treeViewService, IDispatcher dispatcher)"

.PP
Definition at line \fB29\fP of file \fBCompilerServiceIdeApi\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Extensions\&.DotNet\&.CompilerServices\&.Models\&.CompilerServiceIdeApi\&.SetCompilerServiceExplorerTreeView ()"

.PP
TODO: Iterate over _compilerServiceExplorerStateWrap\&.Value\&.CompilerServiceList instead\&.\&.\&. \&.\&.\&.of invoking 'GetCompilerService' with hardcoded values\&. 
.PP
Definition at line \fB55\fP of file \fBCompilerServiceIdeApi\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
