.TH "Luthetus.Common.RazorLib.Dynamics.Models.ITabGroup" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Dynamics.Models.ITabGroup
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBGetIsActive\fP (\fBITab\fP tab)"
.br
.ti -1c
.RI "string \fBGetDynamicCss\fP (\fBITab\fP tab)"
.br
.ti -1c
.RI "Task \fBOnClickAsync\fP (\fBITab\fP tab, MouseEventArgs mouseEventArgs)"
.br
.ti -1c
.RI "Task \fBCloseAsync\fP (\fBITab\fP tab)"
.br
.ti -1c
.RI "Task \fBCloseAllAsync\fP ()"
.br
.ti -1c
.RI "Task \fBCloseOthersAsync\fP (\fBITab\fP tab)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBITabGroup\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "Task Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.ITabGroup\&.CloseAllAsync ()"

.SS "Task Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.ITabGroup\&.CloseAsync (\fBITab\fP tab)"

.SS "Task Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.ITabGroup\&.CloseOthersAsync (\fBITab\fP tab)"

.SS "string Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.ITabGroup\&.GetDynamicCss (\fBITab\fP tab)"

.SS "bool Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.ITabGroup\&.GetIsActive (\fBITab\fP tab)"

.SS "Task Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.ITabGroup\&.OnClickAsync (\fBITab\fP tab, MouseEventArgs mouseEventArgs)"


.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
