.TH "Luthetus.Common.RazorLib.Dynamics.Models.IDialog" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Dynamics.Models.IDialog
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDynamicViewModel\fP\&.
.PP
Inherited by \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.DynamicViewModelAdapterTextEditor\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIDialog\fP \fBSetDialogIsMaximized\fP (bool isMaximized)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBDialogIsMinimized\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBDialogIsMaximized\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBDialogIsResizable\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBDialogFocusPointHtmlElementId\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBElementDimensions\fP \fBDialogElementDimensions\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string? \fBDialogCssClass\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string? \fBDialogCssStyle\fP\fR [get, set]\fP"
.br
.in -1c

Properties inherited from \fBLuthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDynamicViewModel\fP
.in +1c
.ti -1c
.RI "Key< \fBIDynamicViewModel\fP > \fBDynamicViewModelKey\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBTitle\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBTitleVerbose\fP\fR [get]\fP"
.br
.ti -1c
.RI "Type \fBComponentType\fP\fR [get]\fP"
.br
.ti -1c
.RI "Dictionary< string, object?>? \fBComponentParameterMap\fP\fR [get]\fP"
.br
.ti -1c
.RI "string? \fBSetFocusOnCloseElementId\fP\fR [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Attributes inherited from \fBLuthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDynamicViewModel\fP
.in +1c
.ti -1c
.RI "static readonly string \fBDefaultSetFocusOnCloseElementId\fP = ContextFacts\&.GlobalContext\&.ContextElementId"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBIDialog\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBIDialog\fP Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDialog\&.SetDialogIsMaximized (bool isMaximized)"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.DynamicViewModelAdapterTextEditor\fP\&.
.SH "Property Documentation"
.PP 
.SS "string? Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDialog\&.DialogCssClass\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.DynamicViewModelAdapterTextEditor\fP\&.
.PP
Definition at line \fB12\fP of file \fBIDialog\&.cs\fP\&.
.SS "string? Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDialog\&.DialogCssStyle\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.DynamicViewModelAdapterTextEditor\fP\&.
.PP
Definition at line \fB13\fP of file \fBIDialog\&.cs\fP\&.
.SS "\fBElementDimensions\fP Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDialog\&.DialogElementDimensions\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.DynamicViewModelAdapterTextEditor\fP\&.
.PP
Definition at line \fB11\fP of file \fBIDialog\&.cs\fP\&.
.SS "string Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDialog\&.DialogFocusPointHtmlElementId\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.DynamicViewModelAdapterTextEditor\fP\&.
.PP
Definition at line \fB10\fP of file \fBIDialog\&.cs\fP\&.
.SS "bool Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDialog\&.DialogIsMaximized\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.DynamicViewModelAdapterTextEditor\fP\&.
.PP
Definition at line \fB8\fP of file \fBIDialog\&.cs\fP\&.
.SS "bool Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDialog\&.DialogIsMinimized\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.DynamicViewModelAdapterTextEditor\fP\&.
.PP
Definition at line \fB7\fP of file \fBIDialog\&.cs\fP\&.
.SS "bool Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDialog\&.DialogIsResizable\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.DynamicViewModelAdapterTextEditor\fP\&.
.PP
Definition at line \fB9\fP of file \fBIDialog\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
