.TH "Luthetus.Ide.Tests.Basis.Gits.States.GitStateActionsTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.Tests.Basis.Gits.States.GitStateActionsTests \- GitState  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetGitStateWithAction\fP ()"
.br
.RI "GitState\&.WithAction "
.in -1c
.SH "Detailed Description"
.PP 
GitState 
.PP
Definition at line \fB8\fP of file \fBGitStateActionsTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.Gits\&.States\&.GitStateActionsTests\&.SetGitStateWithAction ()"

.PP
GitState\&.WithAction 
.PP
Definition at line \fB14\fP of file \fBGitStateActionsTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
