.TH "Luthetus.Common.RazorLib.Dialogs.Displays.DialogInitializer" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Dialogs.Displays.DialogInitializer
.SH SYNOPSIS
.br
.PP
.PP
Inherits FluxorComponent\&.
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBDialogInitializer\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
