.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.Symbols.FieldSymbolTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.Symbols.FieldSymbolTests \- \fBFieldSymbol\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "FieldSymbol(TextEditorTextSpan) 
.br
----
.br
 \fBFieldSymbol\&.TextSpan\fP \fBFieldSymbol\&.SymbolKindString\fP \fBFieldSymbol\&.SyntaxKind\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBFieldSymbol\fP 
.PP
Definition at line \fB10\fP of file \fBFieldSymbolTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.Syntax\&.Symbols\&.FieldSymbolTests\&.Constructor ()"

.PP
FieldSymbol(TextEditorTextSpan) 
.br
----
.br
 \fBFieldSymbol\&.TextSpan\fP \fBFieldSymbol\&.SymbolKindString\fP \fBFieldSymbol\&.SyntaxKind\fP 
.PP
Definition at line \fB20\fP of file \fBFieldSymbolTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
