.TH "Luthetus.TextEditor.Tests.Basis.Htmls.Models.HtmlHelperTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.Htmls.Models.HtmlHelperTests \- HtmlHelper  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBEscapeHtml_Char\fP ()"
.br
.RI "HtmlHelper\&.EscapeHtml(char) "
.ti -1c
.RI "void \fBEscapeHtml_StringBuilder\fP ()"
.br
.RI "HtmlHelper\&.EscapeHtml(StringBuilder) "
.ti -1c
.RI "void \fBEscapeHtml_String\fP ()"
.br
.RI "HtmlHelper\&.EscapeHtml(string) "
.in -1c
.SH "Detailed Description"
.PP 
HtmlHelper 
.PP
Definition at line \fB9\fP of file \fBHtmlHelperTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Htmls\&.Models\&.HtmlHelperTests\&.EscapeHtml_Char ()"

.PP
HtmlHelper\&.EscapeHtml(char) 
.PP
Definition at line \fB15\fP of file \fBHtmlHelperTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Htmls\&.Models\&.HtmlHelperTests\&.EscapeHtml_String ()"

.PP
HtmlHelper\&.EscapeHtml(string) 
.PP
Definition at line \fB135\fP of file \fBHtmlHelperTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Htmls\&.Models\&.HtmlHelperTests\&.EscapeHtml_StringBuilder ()"

.PP
HtmlHelper\&.EscapeHtml(StringBuilder) 
.PP
Definition at line \fB79\fP of file \fBHtmlHelperTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
