.TH "Luthetus.Extensions.DotNet.CommandLines.Models.DotNetCliOutputParser" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.CommandLines.Models.DotNetCliOutputParser
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNewListModel\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDotNetRunParseResult\fP \fBGetDotNetRunParseResult\fP ()"
.br
.RI "This immutable list is calculated everytime, so if necessary invoke once and then store the result\&. "
.ti -1c
.RI "void \fBParseOutputEntireDotNetRun\fP (string output, string message)"
.br
.RI "The results can be retrieved by invoking GetDiagnosticLineList\&. "
.ti -1c
.RI "List< \fBTextEditorTextSpan\fP > \fBParseOutputLineDotNetNewList\fP (string outputEntire)"
.br
.ti -1c
.RI "List< string > \fBParseOutputLineDotNetTestListTests\fP (string outputEntire)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "List< \fBProjectTemplate\fP >? \fBProjectTemplateList\fP\fR [get]\fP"
.br
.ti -1c
.RI "List< string >? \fBTheFollowingTestsAreAvailableList\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBNewListModel\fP \fBNewListModelSession\fP\fR [get]\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "Action? \fBStateChanged\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBDotNetCliOutputParser\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBDotNetRunParseResult\fP Luthetus\&.Extensions\&.DotNet\&.CommandLines\&.Models\&.DotNetCliOutputParser\&.GetDotNetRunParseResult ()"

.PP
This immutable list is calculated everytime, so if necessary invoke once and then store the result\&. 
.PP
Definition at line \fB21\fP of file \fBDotNetCliOutputParser\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.DotNet\&.CommandLines\&.Models\&.DotNetCliOutputParser\&.ParseOutputEntireDotNetRun (string output, string message)"

.PP
The results can be retrieved by invoking GetDiagnosticLineList\&. 
.PP
Definition at line \fB34\fP of file \fBDotNetCliOutputParser\&.cs\fP\&.
.SS "List< \fBTextEditorTextSpan\fP > Luthetus\&.Extensions\&.DotNet\&.CommandLines\&.Models\&.DotNetCliOutputParser\&.ParseOutputLineDotNetNewList (string outputEntire)"

.SH "(NOTE: this has been fixed but the note is being left here as its a common issue with this code)"
.PP
The following output breaks because the 'Language' for template name of 'dotnet gitignore file' is left empty\&.

.PP
Template Name Short Name Language Tags 
.br
 
.PP
 Console App console [C#],F#,VB Common/Console 
.br
 dotnet gitignore file gitignore,\&.gitignore \fBConfig\fP 
.PP
Definition at line \fB303\fP of file \fBDotNetCliOutputParser\&.cs\fP\&.
.SS "List< string > Luthetus\&.Extensions\&.DotNet\&.CommandLines\&.Models\&.DotNetCliOutputParser\&.ParseOutputLineDotNetTestListTests (string outputEntire)"

.PP
Definition at line \fB501\fP of file \fBDotNetCliOutputParser\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBNewListModel\fP Luthetus\&.Extensions\&.DotNet\&.CommandLines\&.Models\&.DotNetCliOutputParser\&.NewListModelSession\fR [get]\fP"

.PP
Definition at line \fB31\fP of file \fBDotNetCliOutputParser\&.cs\fP\&.
.SS "List<\fBProjectTemplate\fP>? Luthetus\&.Extensions\&.DotNet\&.CommandLines\&.Models\&.DotNetCliOutputParser\&.ProjectTemplateList\fR [get]\fP"

.PP
Definition at line \fB29\fP of file \fBDotNetCliOutputParser\&.cs\fP\&.
.SS "List<string>? Luthetus\&.Extensions\&.DotNet\&.CommandLines\&.Models\&.DotNetCliOutputParser\&.TheFollowingTestsAreAvailableList\fR [get]\fP"

.PP
Definition at line \fB30\fP of file \fBDotNetCliOutputParser\&.cs\fP\&.
.SH "Event Documentation"
.PP 
.SS "Action? Luthetus\&.Extensions\&.DotNet\&.CommandLines\&.Models\&.DotNetCliOutputParser\&.StateChanged"

.PP
Definition at line \fB16\fP of file \fBDotNetCliOutputParser\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
