.TH "Luthetus.Common.RazorLib.Misc.DoNothingJsRuntime" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Misc.DoNothingJsRuntime
.SH SYNOPSIS
.br
.PP
.PP
Inherits IJSRuntime\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "ValueTask< TValue > \fBInvokeAsync< TValue >\fP (string identifier, object?[]? args)"
.br
.ti -1c
.RI "ValueTask< TValue > \fBInvokeAsync< TValue >\fP (string identifier, CancellationToken cancellationToken, object?[]? args)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBDoNothingJsRuntime\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "ValueTask< TValue > Luthetus\&.Common\&.RazorLib\&.Misc\&.DoNothingJsRuntime\&.InvokeAsync< TValue > (string identifier, CancellationToken cancellationToken, object??[] args)"

.PP
Definition at line \fB12\fP of file \fBDoNothingJsRuntime\&.cs\fP\&.
.SS "ValueTask< TValue > Luthetus\&.Common\&.RazorLib\&.Misc\&.DoNothingJsRuntime\&.InvokeAsync< TValue > (string identifier, object??[] args)"

.PP
Definition at line \fB7\fP of file \fBDoNothingJsRuntime\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
