.TH "Luthetus.Extensions.Git.Displays.GitDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.Git.Displays.GitDisplay \- Long term goal is to support any arbitrary version control system\&. For now, implement a \fBGit\fP UI, this lets us get a feel for what the interface should be\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits FluxorComponent\&.
.SH "Detailed Description"
.PP 
Long term goal is to support any arbitrary version control system\&. For now, implement a \fBGit\fP UI, this lets us get a feel for what the interface should be\&. 
.PP
Definition at line \fB30\fP of file \fBGitDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
