.TH "Luthetus.Ide.RazorLib.InputFiles.Displays.InputFileTopNavBar" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.InputFiles.Displays.InputFileTopNavBar
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "Func< \fBIAbsolutePath\fP, Task > \fBSetInputFileContentTreeViewRootFunc\fP = null!\fR [get, set]\fP"
.br
.ti -1c
.RI "InputFileState \fBInputFileState\fP = null!\fR [get, set]\fP"
.br
.ti -1c
.RI "ElementReference? \fBSearchElementReference\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBSearchQuery\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBInputFileTopNavBar\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "InputFileState Luthetus\&.Ide\&.RazorLib\&.InputFiles\&.Displays\&.InputFileTopNavBar\&.InputFileState = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB34\fP of file \fBInputFileTopNavBar\&.razor\&.cs\fP\&.
.SS "ElementReference? Luthetus\&.Ide\&.RazorLib\&.InputFiles\&.Displays\&.InputFileTopNavBar\&.SearchElementReference\fR [get]\fP"

.PP
Definition at line \fB38\fP of file \fBInputFileTopNavBar\&.razor\&.cs\fP\&.
.SS "string Luthetus\&.Ide\&.RazorLib\&.InputFiles\&.Displays\&.InputFileTopNavBar\&.SearchQuery\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB40\fP of file \fBInputFileTopNavBar\&.razor\&.cs\fP\&.
.SS "Func<\fBIAbsolutePath\fP, Task> Luthetus\&.Ide\&.RazorLib\&.InputFiles\&.Displays\&.InputFileTopNavBar\&.SetInputFileContentTreeViewRootFunc = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB32\fP of file \fBInputFileTopNavBar\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
