.TH "Luthetus.TextEditor.RazorLib.ITextEditorService" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.ITextEditorService
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditorService\fP, and \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditorService\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBPostUnique\fP (string name, Func< \fBITextEditorEditContext\fP, Task > textEditorFunc)"
.br
.RI "This method will create an instance of UniqueTextEditorTask, and then invoke \fBPost(ITextEditorWork)\fP
.br

.br
\&. "
.ti -1c
.RI "void \fBPostRedundant\fP (string name, \fBResourceUri\fP \fBresourceUri\fP, Key< \fBTextEditorViewModel\fP > viewModelKey, Func< \fBITextEditorEditContext\fP, Task > textEditorFunc)"
.br
.RI "This method will create an instance of RedundantTextEditorTask, and then invoke \fBPost(ITextEditorWork)\fP
.br

.br
\&. "
.ti -1c
.RI "void \fBPost\fP (\fBITextEditorWork\fP textEditorWork)"
.br
.RI "This method will set the \fBITextEditorWork\&.EditContext\fP property\&. "
.ti -1c
.RI "Task \fBPostAsync\fP (\fBITextEditorWork\fP textEditorWork)"
.br
.RI "This method will set the \fBITextEditorWork\&.EditContext\fP property\&. "
.ti -1c
.RI "Task \fBFinalizePost\fP (\fBITextEditorEditContext\fP editContext)"
.br
.ti -1c
.RI "Task \fBOpenInEditorAsync\fP (string absolutePath, bool shouldSetFocusToEditor, int? cursorPositionIndex, \fBCategory\fP \fBcategory\fP, Key< \fBTextEditorViewModel\fP > preferredViewModelKey)"
.br
.ti -1c
.RI "Task \fBOpenInEditorAsync\fP (string absolutePath, bool shouldSetFocusToEditor, int? lineIndex, int? columnIndex, \fBCategory\fP \fBcategory\fP, Key< \fBTextEditorViewModel\fP > preferredViewModelKey)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBStorageKey\fP\fR [get]\fP"
.br
.RI "This is used when interacting with the \fBIStorageService\fP to set and get data\&. "
.ti -1c
.RI "string \fBThemeCssClassString\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBITextEditorModelApi\fP \fBModelApi\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBITextEditorViewModelApi\fP \fBViewModelApi\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBITextEditorGroupApi\fP \fBGroupApi\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBITextEditorDiffApi\fP \fBDiffApi\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBITextEditorOptionsApi\fP \fBOptionsApi\fP\fR [get]\fP"
.br
.ti -1c
.RI "IState< \fBTextEditorState\fP > \fBTextEditorStateWrap\fP\fR [get]\fP"
.br
.ti -1c
.RI "IState< \fBTextEditorGroupState\fP > \fBGroupStateWrap\fP\fR [get]\fP"
.br
.ti -1c
.RI "IState< \fBTextEditorDiffState\fP > \fBDiffStateWrap\fP\fR [get]\fP"
.br
.ti -1c
.RI "IState< \fBThemeState\fP > \fBThemeStateWrap\fP\fR [get]\fP"
.br
.ti -1c
.RI "IState< \fBTextEditorOptionsState\fP > \fBOptionsStateWrap\fP\fR [get]\fP"
.br
.ti -1c
.RI "IState< \fBTextEditorFindAllState\fP > \fBFindAllStateWrap\fP\fR [get]\fP"
.br
.ti -1c
.RI "IState< \fBAppDimensionState\fP > \fBAppDimensionStateWrap\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBLuthetusTextEditorJavaScriptInteropApi\fP \fBJsRuntimeTextEditorApi\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBLuthetusCommonJavaScriptInteropApi\fP \fBJsRuntimeCommonApi\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBIAutocompleteIndexer\fP \fBAutocompleteIndexer\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBIAutocompleteService\fP \fBAutocompleteService\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBLuthetusTextEditorConfig\fP \fBTextEditorConfig\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB24\fP of file \fBITextEditorService\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "Task Luthetus\&.TextEditor\&.RazorLib\&.ITextEditorService\&.FinalizePost (\fBITextEditorEditContext\fP editContext)"
<summmary> This method writes any mutated data within the \fBITextEditorWork\&.EditContext\fP to the \fBTextEditorState\fP, and afterwards causes a UI render\&. 
.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditorService\fP\&.
.SS "Task Luthetus\&.TextEditor\&.RazorLib\&.ITextEditorService\&.OpenInEditorAsync (string absolutePath, bool shouldSetFocusToEditor, int? cursorPositionIndex, \fBCategory\fP category, Key< \fBTextEditorViewModel\fP > preferredViewModelKey)"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditorService\fP\&.
.SS "Task Luthetus\&.TextEditor\&.RazorLib\&.ITextEditorService\&.OpenInEditorAsync (string absolutePath, bool shouldSetFocusToEditor, int? lineIndex, int? columnIndex, \fBCategory\fP category, Key< \fBTextEditorViewModel\fP > preferredViewModelKey)"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditorService\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.ITextEditorService\&.Post (\fBITextEditorWork\fP textEditorWork)"

.PP
This method will set the \fBITextEditorWork\&.EditContext\fP property\&. Within the method \fBLuthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.IBackgroundTask\&.HandleEvent\fP, invoke \fBFinalizePost\fP to finalize any changes\&. 
.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditorService\fP\&.
.SS "Task Luthetus\&.TextEditor\&.RazorLib\&.ITextEditorService\&.PostAsync (\fBITextEditorWork\fP textEditorWork)"

.PP
This method will set the \fBITextEditorWork\&.EditContext\fP property\&. Within the method \fBLuthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.IBackgroundTask\&.HandleEvent\fP, invoke \fBFinalizePost\fP to finalize any changes\&.

.PP
This async version will block until the background task is completed\&. 
.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditorService\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.ITextEditorService\&.PostRedundant (string name, \fBResourceUri\fP resourceUri, Key< \fBTextEditorViewModel\fP > viewModelKey, Func< \fBITextEditorEditContext\fP, Task > textEditorFunc)"

.PP
This method will create an instance of RedundantTextEditorTask, and then invoke \fBPost(ITextEditorWork)\fP
.br

.br
\&. 
.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditorService\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.ITextEditorService\&.PostUnique (string name, Func< \fBITextEditorEditContext\fP, Task > textEditorFunc)"

.PP
This method will create an instance of UniqueTextEditorTask, and then invoke \fBPost(ITextEditorWork)\fP
.br

.br
\&. 
.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditorService\fP\&.
.SH "Property Documentation"
.PP 
.SS "IState<\fBAppDimensionState\fP> Luthetus\&.TextEditor\&.RazorLib\&.ITextEditorService\&.AppDimensionStateWrap\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditorService\fP\&.
.PP
Definition at line \fB42\fP of file \fBITextEditorService\&.cs\fP\&.
.SS "\fBIAutocompleteIndexer\fP Luthetus\&.TextEditor\&.RazorLib\&.ITextEditorService\&.AutocompleteIndexer\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditorService\fP\&.
.PP
Definition at line \fB46\fP of file \fBITextEditorService\&.cs\fP\&.
.SS "\fBIAutocompleteService\fP Luthetus\&.TextEditor\&.RazorLib\&.ITextEditorService\&.AutocompleteService\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditorService\fP\&.
.PP
Definition at line \fB47\fP of file \fBITextEditorService\&.cs\fP\&.
.SS "\fBITextEditorDiffApi\fP Luthetus\&.TextEditor\&.RazorLib\&.ITextEditorService\&.DiffApi\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditorService\fP\&.
.PP
Definition at line \fB33\fP of file \fBITextEditorService\&.cs\fP\&.
.SS "IState<\fBTextEditorDiffState\fP> Luthetus\&.TextEditor\&.RazorLib\&.ITextEditorService\&.DiffStateWrap\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditorService\fP\&.
.PP
Definition at line \fB38\fP of file \fBITextEditorService\&.cs\fP\&.
.SS "IState<\fBTextEditorFindAllState\fP> Luthetus\&.TextEditor\&.RazorLib\&.ITextEditorService\&.FindAllStateWrap\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditorService\fP\&.
.PP
Definition at line \fB41\fP of file \fBITextEditorService\&.cs\fP\&.
.SS "\fBITextEditorGroupApi\fP Luthetus\&.TextEditor\&.RazorLib\&.ITextEditorService\&.GroupApi\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditorService\fP\&.
.PP
Definition at line \fB32\fP of file \fBITextEditorService\&.cs\fP\&.
.SS "IState<\fBTextEditorGroupState\fP> Luthetus\&.TextEditor\&.RazorLib\&.ITextEditorService\&.GroupStateWrap\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditorService\fP\&.
.PP
Definition at line \fB37\fP of file \fBITextEditorService\&.cs\fP\&.
.SS "\fBLuthetusCommonJavaScriptInteropApi\fP Luthetus\&.TextEditor\&.RazorLib\&.ITextEditorService\&.JsRuntimeCommonApi\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditorService\fP\&.
.PP
Definition at line \fB45\fP of file \fBITextEditorService\&.cs\fP\&.
.SS "\fBLuthetusTextEditorJavaScriptInteropApi\fP Luthetus\&.TextEditor\&.RazorLib\&.ITextEditorService\&.JsRuntimeTextEditorApi\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditorService\fP\&.
.PP
Definition at line \fB44\fP of file \fBITextEditorService\&.cs\fP\&.
.SS "\fBITextEditorModelApi\fP Luthetus\&.TextEditor\&.RazorLib\&.ITextEditorService\&.ModelApi\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditorService\fP\&.
.PP
Definition at line \fB30\fP of file \fBITextEditorService\&.cs\fP\&.
.SS "\fBITextEditorOptionsApi\fP Luthetus\&.TextEditor\&.RazorLib\&.ITextEditorService\&.OptionsApi\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditorService\fP\&.
.PP
Definition at line \fB34\fP of file \fBITextEditorService\&.cs\fP\&.
.SS "IState<\fBTextEditorOptionsState\fP> Luthetus\&.TextEditor\&.RazorLib\&.ITextEditorService\&.OptionsStateWrap\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditorService\fP\&.
.PP
Definition at line \fB40\fP of file \fBITextEditorService\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.ITextEditorService\&.StorageKey\fR [get]\fP"

.PP
This is used when interacting with the \fBIStorageService\fP to set and get data\&. 
.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditorService\fP\&.
.PP
Definition at line \fB27\fP of file \fBITextEditorService\&.cs\fP\&.
.SS "\fBLuthetusTextEditorConfig\fP Luthetus\&.TextEditor\&.RazorLib\&.ITextEditorService\&.TextEditorConfig\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditorService\fP\&.
.PP
Definition at line \fB48\fP of file \fBITextEditorService\&.cs\fP\&.
.SS "IState<\fBTextEditorState\fP> Luthetus\&.TextEditor\&.RazorLib\&.ITextEditorService\&.TextEditorStateWrap\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditorService\fP\&.
.PP
Definition at line \fB36\fP of file \fBITextEditorService\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.ITextEditorService\&.ThemeCssClassString\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditorService\fP\&.
.PP
Definition at line \fB28\fP of file \fBITextEditorService\&.cs\fP\&.
.SS "IState<\fBThemeState\fP> Luthetus\&.TextEditor\&.RazorLib\&.ITextEditorService\&.ThemeStateWrap\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditorService\fP\&.
.PP
Definition at line \fB39\fP of file \fBITextEditorService\&.cs\fP\&.
.SS "\fBITextEditorViewModelApi\fP Luthetus\&.TextEditor\&.RazorLib\&.ITextEditorService\&.ViewModelApi\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditorService\fP\&.
.PP
Definition at line \fB31\fP of file \fBITextEditorService\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
