.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.EmptyExpressionNodeTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.EmptyExpressionNodeTests \- \fBEmptyExpressionNode\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "EmptyExpressionNode(TypeClauseNode) 
.br
----
.br
 \fBEmptyExpressionNode\&.ResultTypeClauseNode\fP EmptyExpressionNode\&.ChildList \fBEmptyExpressionNode\&.IsFabricated\fP \fBEmptyExpressionNode\&.SyntaxKind\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBEmptyExpressionNode\fP 
.PP
Definition at line \fB10\fP of file \fBIdempotentExpressionNodeTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.Syntax\&.SyntaxNodes\&.EmptyExpressionNodeTests\&.Constructor ()"

.PP
EmptyExpressionNode(TypeClauseNode) 
.br
----
.br
 \fBEmptyExpressionNode\&.ResultTypeClauseNode\fP EmptyExpressionNode\&.ChildList \fBEmptyExpressionNode\&.IsFabricated\fP \fBEmptyExpressionNode\&.SyntaxKind\fP 
.PP
Definition at line \fB21\fP of file \fBIdempotentExpressionNodeTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
