.TH "Luthetus.Common.Tests.Basis.BackgroundTasks.Models.BackgroundTaskServiceSynchronousTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.BackgroundTasks.Models.BackgroundTaskServiceSynchronousTests \- \fBBackgroundTaskServiceSynchronous\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBExecutingBackgroundTask\fP ()"
.br
.RI "BackgroundTaskServiceSynchronous\&.ExecutingBackgroundTask 
.br
----
.br
 BackgroundTaskServiceSynchronous\&.ExecutingBackgroundTaskChanged BackgroundTaskServiceSynchronous\&.EnqueueAsync(IBackgroundTask) BackgroundTaskServiceSynchronous\&.SetExecutingBackgroundTask(Key<BackgroundTaskQueue>, IBackgroundTask?) BackgroundTaskServiceSynchronous\&.RegisterQueue(BackgroundTaskQueue) BackgroundTaskServiceSynchronous\&.DequeueAsync(Key<BackgroundTaskQueue>, CancellationToken) "
.ti -1c
.RI "void \fBEnqueueB\fP ()"
.br
.RI "BackgroundTaskServiceSynchronous\&.EnqueueAsync(Key<BackgroundTask>, Key<BackgroundTaskQueue>, string, Func<Task>) "
.in -1c
.SH "Detailed Description"
.PP 
\fBBackgroundTaskServiceSynchronous\fP 
.PP
Definition at line \fB11\fP of file \fBBackgroundTaskServiceSynchronousTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.BackgroundTasks\&.Models\&.BackgroundTaskServiceSynchronousTests\&.EnqueueB ()"

.PP
BackgroundTaskServiceSynchronous\&.EnqueueAsync(Key<BackgroundTask>, Key<BackgroundTaskQueue>, string, Func<Task>) 
.PP
Definition at line \fB79\fP of file \fBBackgroundTaskServiceSynchronousTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.BackgroundTasks\&.Models\&.BackgroundTaskServiceSynchronousTests\&.ExecutingBackgroundTask ()"

.PP
BackgroundTaskServiceSynchronous\&.ExecutingBackgroundTask 
.br
----
.br
 BackgroundTaskServiceSynchronous\&.ExecutingBackgroundTaskChanged BackgroundTaskServiceSynchronous\&.EnqueueAsync(IBackgroundTask) BackgroundTaskServiceSynchronous\&.SetExecutingBackgroundTask(Key<BackgroundTaskQueue>, IBackgroundTask?) BackgroundTaskServiceSynchronous\&.RegisterQueue(BackgroundTaskQueue) BackgroundTaskServiceSynchronous\&.DequeueAsync(Key<BackgroundTaskQueue>, CancellationToken) 
.PP
Definition at line \fB23\fP of file \fBBackgroundTaskServiceSynchronousTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
