.TH "Luthetus.Ide.Tests.Basis.CodeSearches.States.CodeSearchStateReducerTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.Tests.Basis.CodeSearches.States.CodeSearchStateReducerTests \- CodeSearchState\&.Reducer  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBReduceWithAction\fP ()"
.br
.RI "CodeSearchState\&.Reducer\&.ReduceWithAction(CodeSearchState, CodeSearchState\&.WithAction) "
.ti -1c
.RI "void \fBReduceAddResultAction\fP ()"
.br
.RI "CodeSearchState\&.Reducer\&.ReduceAddResultAction(CodeSearchState, CodeSearchState\&.AddResultAction) "
.ti -1c
.RI "void \fBReduceClearResultListAction\fP ()"
.br
.RI "CodeSearchState\&.Reducer\&.ReduceClearResultListAction(CodeSearchState) "
.in -1c
.SH "Detailed Description"
.PP 
CodeSearchState\&.Reducer 
.PP
Definition at line \fB8\fP of file \fBCodeSearchStateReducerTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.CodeSearches\&.States\&.CodeSearchStateReducerTests\&.ReduceAddResultAction ()"

.PP
CodeSearchState\&.Reducer\&.ReduceAddResultAction(CodeSearchState, CodeSearchState\&.AddResultAction) 
.PP
Definition at line \fB23\fP of file \fBCodeSearchStateReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.CodeSearches\&.States\&.CodeSearchStateReducerTests\&.ReduceClearResultListAction ()"

.PP
CodeSearchState\&.Reducer\&.ReduceClearResultListAction(CodeSearchState) 
.PP
Definition at line \fB32\fP of file \fBCodeSearchStateReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.CodeSearches\&.States\&.CodeSearchStateReducerTests\&.ReduceWithAction ()"

.PP
CodeSearchState\&.Reducer\&.ReduceWithAction(CodeSearchState, CodeSearchState\&.WithAction) 
.PP
Definition at line \fB14\fP of file \fBCodeSearchStateReducerTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
