.TH "Luthetus.Ide.RazorLib.ComponentRenderers.Models.IDeleteFileFormRendererType" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.ComponentRenderers.Models.IDeleteFileFormRendererType
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.Ide\&.RazorLib\&.FileSystems\&.Displays\&.DeleteFileFormDisplay\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBIAbsolutePath\fP \fBAbsolutePath\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsDirectory\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "Func< \fBIAbsolutePath\fP, Task > \fBOnAfterSubmitFunc\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBIDeleteFileFormRendererType\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBIAbsolutePath\fP Luthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.IDeleteFileFormRendererType\&.AbsolutePath\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.FileSystems\&.Displays\&.DeleteFileFormDisplay\fP\&.
.PP
Definition at line \fB7\fP of file \fBIDeleteFileFormRendererType\&.cs\fP\&.
.SS "bool Luthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.IDeleteFileFormRendererType\&.IsDirectory\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.FileSystems\&.Displays\&.DeleteFileFormDisplay\fP\&.
.PP
Definition at line \fB8\fP of file \fBIDeleteFileFormRendererType\&.cs\fP\&.
.SS "Func<\fBIAbsolutePath\fP, Task> Luthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.IDeleteFileFormRendererType\&.OnAfterSubmitFunc\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.FileSystems\&.Displays\&.DeleteFileFormDisplay\fP\&.
.PP
Definition at line \fB9\fP of file \fBIDeleteFileFormRendererType\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
