.TH "Luthetus.TextEditor.Tests.Basis.Commands.Models.TextEditorCommandArgsTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.Commands.Models.TextEditorCommandArgsTests \- \fBTextEditorCommandArgs\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "TextEditorCommandArgs(ResourceUri, Key<TextEditorViewModel>, bool, IClipboardService, ITextEditorService, Func<MouseEventArgs, Task>?, IJSRuntime?, Fluxor\&.IDispatcher, Action<ResourceUri>?, Action<ResourceUri>?, Action<Key<TextEditorViewModel>>?) 
.br
----
.br
 \fBTextEditorCommandArgs\&.ModelResourceUri\fP TextEditorCommandArgs\&.PrimaryCursor TextEditorCommandArgs\&.CursorList TextEditorCommandArgs\&.ClipboardService \fBTextEditorCommandArgs\&.TextEditorService\fP \fBTextEditorCommandArgs\&.ViewModelKey\fP TextEditorCommandArgs\&.HandleMouseStoppedMovingEventAsyncFunc TextEditorCommandArgs\&.JsRuntime TextEditorCommandArgs\&.HasTextSelection TextEditorCommandArgs\&.RegisterModelAction TextEditorCommandArgs\&.RegisterViewModelAction TextEditorCommandArgs\&.ShowViewModelAction "
.in -1c
.SH "Detailed Description"
.PP 
\fBTextEditorCommandArgs\fP 
.PP
Definition at line \fB14\fP of file \fBTextEditorCommandArgsTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.TextEditorCommandArgsTests\&.Constructor ()"

.PP
TextEditorCommandArgs(ResourceUri, Key<TextEditorViewModel>, bool, IClipboardService, ITextEditorService, Func<MouseEventArgs, Task>?, IJSRuntime?, Fluxor\&.IDispatcher, Action<ResourceUri>?, Action<ResourceUri>?, Action<Key<TextEditorViewModel>>?) 
.br
----
.br
 \fBTextEditorCommandArgs\&.ModelResourceUri\fP TextEditorCommandArgs\&.PrimaryCursor TextEditorCommandArgs\&.CursorList TextEditorCommandArgs\&.ClipboardService \fBTextEditorCommandArgs\&.TextEditorService\fP \fBTextEditorCommandArgs\&.ViewModelKey\fP TextEditorCommandArgs\&.HandleMouseStoppedMovingEventAsyncFunc TextEditorCommandArgs\&.JsRuntime TextEditorCommandArgs\&.HasTextSelection TextEditorCommandArgs\&.RegisterModelAction TextEditorCommandArgs\&.RegisterViewModelAction TextEditorCommandArgs\&.ShowViewModelAction 
.PP
Definition at line \fB33\fP of file \fBTextEditorCommandArgsTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
