.TH "Luthetus.TextEditor.Tests.Basis.Cursors.Models.TextEditorCursorModifierTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.Cursors.Models.TextEditorCursorModifierTests \- \fBTextEditorCursorModifier\fP 
.br
----
.br
 \fBTextEditorCursorModifier\&.LineIndex\fP \fBTextEditorCursorModifier\&.ColumnIndex\fP \fBTextEditorCursorModifier\&.PreferredColumnIndex\fP \fBTextEditorCursorModifier\&.IsPrimaryCursor\fP \fBTextEditorCursorModifier\&.SelectionAnchorPositionIndex\fP \fBTextEditorCursorModifier\&.SelectionEndingPositionIndex\fP \fBTextEditorCursorModifier\&.Key\fP TextEditorCursorModifier\&.ShouldRevealCursor TextEditorCursorModifier\&.IsIntersecting \fBTextEditorCursorModifier\&.ToCursor()\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "TextEditorCursorModifier(TextEditorCursor) "
.in -1c
.SH "Detailed Description"
.PP 
\fBTextEditorCursorModifier\fP 
.br
----
.br
 \fBTextEditorCursorModifier\&.LineIndex\fP \fBTextEditorCursorModifier\&.ColumnIndex\fP \fBTextEditorCursorModifier\&.PreferredColumnIndex\fP \fBTextEditorCursorModifier\&.IsPrimaryCursor\fP \fBTextEditorCursorModifier\&.SelectionAnchorPositionIndex\fP \fBTextEditorCursorModifier\&.SelectionEndingPositionIndex\fP \fBTextEditorCursorModifier\&.Key\fP TextEditorCursorModifier\&.ShouldRevealCursor TextEditorCursorModifier\&.IsIntersecting \fBTextEditorCursorModifier\&.ToCursor()\fP 
.PP
Definition at line \fB19\fP of file \fBTextEditorCursorModifierTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Cursors\&.Models\&.TextEditorCursorModifierTests\&.Constructor ()"

.PP
TextEditorCursorModifier(TextEditorCursor) 
.PP
Definition at line \fB25\fP of file \fBTextEditorCursorModifierTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
