.TH "Luthetus.Ide.RazorLib.Terminals.Models.TerminalOutputFormattedTextEditor" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.Terminals.Models.TerminalOutputFormattedTextEditor
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.ITerminalOutputFormatted\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTerminalOutputFormattedTextEditor\fP (string text, ImmutableList< \fBTerminalCommandParsed\fP > parsedCommandList, ImmutableList< \fBTextEditorTextSpan\fP > textSpanList, ImmutableList< \fBITextEditorSymbol\fP > symbolList)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBText\fP\fR [get]\fP"
.br
.ti -1c
.RI "ImmutableList< \fBTerminalCommandParsed\fP > \fBParsedCommandList\fP\fR [get]\fP"
.br
.ti -1c
.RI "ImmutableList< \fBTextEditorTextSpan\fP > \fBTextSpanList\fP\fR [get]\fP"
.br
.ti -1c
.RI "ImmutableList< \fBITextEditorSymbol\fP > \fBSymbolList\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBTerminalOutputFormattedTextEditor\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutputFormattedTextEditor\&.TerminalOutputFormattedTextEditor (string text, ImmutableList< \fBTerminalCommandParsed\fP > parsedCommandList, ImmutableList< \fBTextEditorTextSpan\fP > textSpanList, ImmutableList< \fBITextEditorSymbol\fP > symbolList)"

.PP
Definition at line \fB9\fP of file \fBTerminalOutputFormattedTextEditor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "ImmutableList<\fBTerminalCommandParsed\fP> Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutputFormattedTextEditor\&.ParsedCommandList\fR [get]\fP"

.PP
Definition at line \fB22\fP of file \fBTerminalOutputFormattedTextEditor\&.cs\fP\&.
.SS "ImmutableList<\fBITextEditorSymbol\fP> Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutputFormattedTextEditor\&.SymbolList\fR [get]\fP"

.PP
Definition at line \fB24\fP of file \fBTerminalOutputFormattedTextEditor\&.cs\fP\&.
.SS "string Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutputFormattedTextEditor\&.Text\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.ITerminalOutputFormatted\fP\&.
.PP
Definition at line \fB21\fP of file \fBTerminalOutputFormattedTextEditor\&.cs\fP\&.
.SS "ImmutableList<\fBTextEditorTextSpan\fP> Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutputFormattedTextEditor\&.TextSpanList\fR [get]\fP"

.PP
Definition at line \fB23\fP of file \fBTerminalOutputFormattedTextEditor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
