.TH "Luthetus.Common.RazorLib.Storages.Models.IStorageService" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Storages.Models.IStorageService
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.Common\&.RazorLib\&.Storages\&.Models\&.DoNothingStorageService\fP, \fBLuthetus\&.Common\&.RazorLib\&.Storages\&.Models\&.InMemoryStorageService\fP, and \fBLuthetus\&.Common\&.RazorLib\&.Storages\&.Models\&.LocalStorageService\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "ValueTask \fBSetValue\fP (string key, object? value)"
.br
.ti -1c
.RI "ValueTask< object?> \fBGetValue\fP (string key)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBIStorageService\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "ValueTask< object?> Luthetus\&.Common\&.RazorLib\&.Storages\&.Models\&.IStorageService\&.GetValue (string key)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Storages\&.Models\&.DoNothingStorageService\fP, \fBLuthetus\&.Common\&.RazorLib\&.Storages\&.Models\&.InMemoryStorageService\fP, and \fBLuthetus\&.Common\&.RazorLib\&.Storages\&.Models\&.LocalStorageService\fP\&.
.SS "ValueTask Luthetus\&.Common\&.RazorLib\&.Storages\&.Models\&.IStorageService\&.SetValue (string key, object? value)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Storages\&.Models\&.DoNothingStorageService\fP, \fBLuthetus\&.Common\&.RazorLib\&.Storages\&.Models\&.InMemoryStorageService\fP, and \fBLuthetus\&.Common\&.RazorLib\&.Storages\&.Models\&.LocalStorageService\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
