.TH "Luthetus.Extensions.DotNet.Tests.Basis.DotNetSolutions.States.DotNetSolutionStateReducerTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.Tests.Basis.DotNetSolutions.States.DotNetSolutionStateReducerTests \- DotNetSolutionState\&.Reducer  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBReduceRegisterAction\fP ()"
.br
.RI "DotNetSolutionState\&.Reducer\&.ReduceRegisterAction(DotNetSolutionState, DotNetSolutionState\&.RegisterAction) "
.ti -1c
.RI "void \fBReduceDisposeAction\fP ()"
.br
.RI "DotNetSolutionState\&.Reducer\&.ReduceDisposeAction(DotNetSolutionState, DotNetSolutionState\&.DisposeAction) "
.ti -1c
.RI "void \fBReduceWithAction\fP ()"
.br
.RI "DotNetSolutionState\&.Reducer\&.ReduceWithAction(DotNetSolutionState, DotNetSolutionSync\&.IWithAction) "
.in -1c
.SH "Detailed Description"
.PP 
DotNetSolutionState\&.Reducer 
.PP
Definition at line \fB6\fP of file \fBDotNetSolutionStateReducerTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.DotNetSolutions\&.States\&.DotNetSolutionStateReducerTests\&.ReduceDisposeAction ()"

.PP
DotNetSolutionState\&.Reducer\&.ReduceDisposeAction(DotNetSolutionState, DotNetSolutionState\&.DisposeAction) 
.PP
Definition at line \fB21\fP of file \fBDotNetSolutionStateReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.DotNetSolutions\&.States\&.DotNetSolutionStateReducerTests\&.ReduceRegisterAction ()"

.PP
DotNetSolutionState\&.Reducer\&.ReduceRegisterAction(DotNetSolutionState, DotNetSolutionState\&.RegisterAction) 
.PP
Definition at line \fB12\fP of file \fBDotNetSolutionStateReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.DotNetSolutions\&.States\&.DotNetSolutionStateReducerTests\&.ReduceWithAction ()"

.PP
DotNetSolutionState\&.Reducer\&.ReduceWithAction(DotNetSolutionState, DotNetSolutionSync\&.IWithAction) 
.PP
Definition at line \fB30\fP of file \fBDotNetSolutionStateReducerTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
