.TH "Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Reducer" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Reducer
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBTextEditorOptionsState\fP \fBReduceSetFontFamilyAction\fP (\fBTextEditorOptionsState\fP inState, \fBSetFontFamilyAction\fP setFontFamilyAction)"
.br
.ti -1c
.RI "static \fBTextEditorOptionsState\fP \fBReduceSetFontSizeAction\fP (\fBTextEditorOptionsState\fP inState, \fBSetFontSizeAction\fP setFontSizeAction)"
.br
.ti -1c
.RI "static \fBTextEditorOptionsState\fP \fBReduceSetRenderStateKeyAction\fP (\fBTextEditorOptionsState\fP inState, \fBSetRenderStateKeyAction\fP setRenderStateKeyAction)"
.br
.ti -1c
.RI "static \fBTextEditorOptionsState\fP \fBReduceSetCursorWidthAction\fP (\fBTextEditorOptionsState\fP inState, \fBSetCursorWidthAction\fP setCursorWidthAction)"
.br
.ti -1c
.RI "static \fBTextEditorOptionsState\fP \fBReduceSetHeightAction\fP (\fBTextEditorOptionsState\fP inState, \fBSetHeightAction\fP setHeightAction)"
.br
.ti -1c
.RI "static \fBTextEditorOptionsState\fP \fBReduceSetThemeAction\fP (\fBTextEditorOptionsState\fP inState, \fBSetThemeAction\fP setThemeAction)"
.br
.ti -1c
.RI "static \fBTextEditorOptionsState\fP \fBReduceSetKeymapAction\fP (\fBTextEditorOptionsState\fP inState, \fBSetKeymapAction\fP setKeymapAction)"
.br
.ti -1c
.RI "static \fBTextEditorOptionsState\fP \fBReduceSetShowWhitespaceAction\fP (\fBTextEditorOptionsState\fP inState, \fBSetShowWhitespaceAction\fP setShowWhitespaceAction)"
.br
.ti -1c
.RI "static \fBTextEditorOptionsState\fP \fBReduceSetShowNewlinesAction\fP (\fBTextEditorOptionsState\fP inState, \fBSetShowNewlinesAction\fP setShowNewlinesAction)"
.br
.ti -1c
.RI "static \fBTextEditorOptionsState\fP \fBReduceSetUseMonospaceOptimizationsAction\fP (\fBTextEditorOptionsState\fP inState, \fBSetUseMonospaceOptimizationsAction\fP setUseMonospaceOptimizationsAction)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBTextEditorOptionsState\&.Reducer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBTextEditorOptionsState\fP Luthetus\&.TextEditor\&.RazorLib\&.Options\&.States\&.TextEditorOptionsState\&.Reducer\&.ReduceSetCursorWidthAction (\fBTextEditorOptionsState\fP inState, \fBSetCursorWidthAction\fP setCursorWidthAction)\fR [static]\fP"

.PP
Definition at line \fB62\fP of file \fBTextEditorOptionsState\&.Reducer\&.cs\fP\&.
.SS "\fBTextEditorOptionsState\fP Luthetus\&.TextEditor\&.RazorLib\&.Options\&.States\&.TextEditorOptionsState\&.Reducer\&.ReduceSetFontFamilyAction (\fBTextEditorOptionsState\fP inState, \fBSetFontFamilyAction\fP setFontFamilyAction)\fR [static]\fP"

.PP
Definition at line \fB12\fP of file \fBTextEditorOptionsState\&.Reducer\&.cs\fP\&.
.SS "\fBTextEditorOptionsState\fP Luthetus\&.TextEditor\&.RazorLib\&.Options\&.States\&.TextEditorOptionsState\&.Reducer\&.ReduceSetFontSizeAction (\fBTextEditorOptionsState\fP inState, \fBSetFontSizeAction\fP setFontSizeAction)\fR [static]\fP"

.PP
Definition at line \fB30\fP of file \fBTextEditorOptionsState\&.Reducer\&.cs\fP\&.
.SS "\fBTextEditorOptionsState\fP Luthetus\&.TextEditor\&.RazorLib\&.Options\&.States\&.TextEditorOptionsState\&.Reducer\&.ReduceSetHeightAction (\fBTextEditorOptionsState\fP inState, \fBSetHeightAction\fP setHeightAction)\fR [static]\fP"

.PP
Definition at line \fB77\fP of file \fBTextEditorOptionsState\&.Reducer\&.cs\fP\&.
.SS "\fBTextEditorOptionsState\fP Luthetus\&.TextEditor\&.RazorLib\&.Options\&.States\&.TextEditorOptionsState\&.Reducer\&.ReduceSetKeymapAction (\fBTextEditorOptionsState\fP inState, \fBSetKeymapAction\fP setKeymapAction)\fR [static]\fP"

.PP
Definition at line \fB110\fP of file \fBTextEditorOptionsState\&.Reducer\&.cs\fP\&.
.SS "\fBTextEditorOptionsState\fP Luthetus\&.TextEditor\&.RazorLib\&.Options\&.States\&.TextEditorOptionsState\&.Reducer\&.ReduceSetRenderStateKeyAction (\fBTextEditorOptionsState\fP inState, \fBSetRenderStateKeyAction\fP setRenderStateKeyAction)\fR [static]\fP"

.PP
Definition at line \fB48\fP of file \fBTextEditorOptionsState\&.Reducer\&.cs\fP\&.
.SS "\fBTextEditorOptionsState\fP Luthetus\&.TextEditor\&.RazorLib\&.Options\&.States\&.TextEditorOptionsState\&.Reducer\&.ReduceSetShowNewlinesAction (\fBTextEditorOptionsState\fP inState, \fBSetShowNewlinesAction\fP setShowNewlinesAction)\fR [static]\fP"

.PP
Definition at line \fB140\fP of file \fBTextEditorOptionsState\&.Reducer\&.cs\fP\&.
.SS "\fBTextEditorOptionsState\fP Luthetus\&.TextEditor\&.RazorLib\&.Options\&.States\&.TextEditorOptionsState\&.Reducer\&.ReduceSetShowWhitespaceAction (\fBTextEditorOptionsState\fP inState, \fBSetShowWhitespaceAction\fP setShowWhitespaceAction)\fR [static]\fP"

.PP
Definition at line \fB125\fP of file \fBTextEditorOptionsState\&.Reducer\&.cs\fP\&.
.SS "\fBTextEditorOptionsState\fP Luthetus\&.TextEditor\&.RazorLib\&.Options\&.States\&.TextEditorOptionsState\&.Reducer\&.ReduceSetThemeAction (\fBTextEditorOptionsState\fP inState, \fBSetThemeAction\fP setThemeAction)\fR [static]\fP"

.PP
Definition at line \fB92\fP of file \fBTextEditorOptionsState\&.Reducer\&.cs\fP\&.
.SS "\fBTextEditorOptionsState\fP Luthetus\&.TextEditor\&.RazorLib\&.Options\&.States\&.TextEditorOptionsState\&.Reducer\&.ReduceSetUseMonospaceOptimizationsAction (\fBTextEditorOptionsState\fP inState, \fBSetUseMonospaceOptimizationsAction\fP setUseMonospaceOptimizationsAction)\fR [static]\fP"

.PP
Definition at line \fB155\fP of file \fBTextEditorOptionsState\&.Reducer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
