.TH "Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.Parser" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.Parser
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IParser\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParser\fP (\fBILexer\fP lexer)"
.br
.ti -1c
.RI "\fBCompilationUnit\fP \fBParse\fP (\fBIBinder\fP previousBinder, \fBResourceUri\fP resourceUri)"
.br
.RI "This method is used when parsing many files as a single compilation\&. The first binder instance would be passed to the following parsers\&. The resourceUri is passed in so if a file is parsed for a second time, the previous symbols can be deleted so they do not duplicate\&. "
.ti -1c
.RI "virtual \fBCompilationUnit\fP \fBParse\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "ImmutableArray< \fBTextEditorDiagnostic\fP > \fBDiagnosticsList\fP = ImmutableArray<\fBTextEditorDiagnostic\fP>\&.Empty\fR [get]\fP"
.br
.ti -1c
.RI "\fBIBinder\fP \fBBinder\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBIBinderSession\fP \fBBinderSession\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBILexer\fP \fBLexer\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBParser\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.Parser\&.Parser (\fBILexer\fP lexer)"

.PP
Definition at line \fB12\fP of file \fBParser\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual \fBCompilationUnit\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.Parser\&.Parse ()\fR [virtual]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IParser\fP\&.
.PP
Definition at line \fB35\fP of file \fBParser\&.cs\fP\&.
.SS "\fBCompilationUnit\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.Parser\&.Parse (\fBIBinder\fP previousBinder, \fBResourceUri\fP resourceUri)"

.PP
This method is used when parsing many files as a single compilation\&. The first binder instance would be passed to the following parsers\&. The resourceUri is passed in so if a file is parsed for a second time, the previous symbols can be deleted so they do not duplicate\&. 
.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IParser\fP\&.
.PP
Definition at line \fB25\fP of file \fBParser\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBIBinder\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.Parser\&.Binder\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IParser\fP\&.
.PP
Definition at line \fB20\fP of file \fBParser\&.cs\fP\&.
.SS "\fBIBinderSession\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.Parser\&.BinderSession\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IParser\fP\&.
.PP
Definition at line \fB21\fP of file \fBParser\&.cs\fP\&.
.SS "ImmutableArray<\fBTextEditorDiagnostic\fP> Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.Parser\&.DiagnosticsList = ImmutableArray<\fBTextEditorDiagnostic\fP>\&.Empty\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IParser\fP\&.
.PP
Definition at line \fB19\fP of file \fBParser\&.cs\fP\&.
.SS "\fBILexer\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.Parser\&.Lexer\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IParser\fP\&.
.PP
Definition at line \fB22\fP of file \fBParser\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
