.TH "Luthetus.TextEditor.Tests.Basis.TextEditors.Models.RenderBatchTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.TextEditors.Models.RenderBatchTests \- TextEditorRenderBatch  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "TextEditorRenderBatch(TextEditorModel?, TextEditorViewModel?, TextEditorOptions?, string, int) 
.br
----
.br
 TextEditorRenderBatch\&.Model TextEditorRenderBatch\&.ViewModel TextEditorRenderBatch\&.Options TextEditorRenderBatch\&.FontFamily TextEditorRenderBatch\&.FontSizeInPixels TextEditorRenderBatch\&.FontFamilyCssStyle TextEditorRenderBatch\&.FontSizeInPixelsCssStyle TextEditorRenderBatch\&.IsValid "
.in -1c
.SH "Detailed Description"
.PP 
TextEditorRenderBatch 
.PP
Definition at line \fB6\fP of file \fBRenderBatchTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.RenderBatchTests\&.Constructor ()"

.PP
TextEditorRenderBatch(TextEditorModel?, TextEditorViewModel?, TextEditorOptions?, string, int) 
.br
----
.br
 TextEditorRenderBatch\&.Model TextEditorRenderBatch\&.ViewModel TextEditorRenderBatch\&.Options TextEditorRenderBatch\&.FontFamily TextEditorRenderBatch\&.FontSizeInPixels TextEditorRenderBatch\&.FontFamilyCssStyle TextEditorRenderBatch\&.FontSizeInPixelsCssStyle TextEditorRenderBatch\&.IsValid 
.PP
Definition at line \fB21\fP of file \fBRenderBatchTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
