.TH "Luthetus.Common.RazorLib.Reflectives.Models.ReflectiveParameter" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Reflectives.Models.ReflectiveParameter
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Common\&.RazorLib\&.Reflectives\&.Models\&.IReflectiveParameter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBReflectiveParameter\fP (ConstructorInfo? chosenConstructorInfo, Func< object?>? constructValueFunc, object? value, \fBType\fP type)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBReflectiveParameter\fP \fBConstructString\fP ()"
.br
.ti -1c
.RI "static \fBReflectiveParameter\fP \fBConstructInt\fP ()"
.br
.ti -1c
.RI "static \fBReflectiveParameter\fP \fBConstructOther< VariableType >\fP ()"
.br
.ti -1c
.RI "static \fBReflectiveParameter\fP \fBConstructOther\fP (\fBType\fP variableType)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "ConstructorInfo? \fBChosenConstructorInfo\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "Func< object?>? \fBConstructValueFunc\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "object? \fBValue\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "Type \fBType\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBReflectiveParameterKind\fP \fBReflectiveParameterKind\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBReflectiveParameter\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Common\&.RazorLib\&.Reflectives\&.Models\&.ReflectiveParameter\&.ReflectiveParameter (ConstructorInfo? chosenConstructorInfo, Func< object?>? constructValueFunc, object? value, \fBType\fP type)"

.PP
Definition at line \fB7\fP of file \fBReflectiveParameter\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBReflectiveParameter\fP Luthetus\&.Common\&.RazorLib\&.Reflectives\&.Models\&.ReflectiveParameter\&.ConstructInt ()\fR [static]\fP"

.PP
Definition at line \fB39\fP of file \fBReflectiveParameter\&.cs\fP\&.
.SS "\fBReflectiveParameter\fP Luthetus\&.Common\&.RazorLib\&.Reflectives\&.Models\&.ReflectiveParameter\&.ConstructOther (\fBType\fP variableType)\fR [static]\fP"

.PP
Definition at line \fB57\fP of file \fBReflectiveParameter\&.cs\fP\&.
.SS "\fBReflectiveParameter\fP \fBLuthetus\&.Common\&.RazorLib\&.Reflectives\&.Models\&.ReflectiveParameter\&.ConstructOther\fP< VariableType > ()\fR [static]\fP"

.PP
Definition at line \fB48\fP of file \fBReflectiveParameter\&.cs\fP\&.
.SS "\fBReflectiveParameter\fP Luthetus\&.Common\&.RazorLib\&.Reflectives\&.Models\&.ReflectiveParameter\&.ConstructString ()\fR [static]\fP"

.PP
Definition at line \fB30\fP of file \fBReflectiveParameter\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "ConstructorInfo? Luthetus\&.Common\&.RazorLib\&.Reflectives\&.Models\&.ReflectiveParameter\&.ChosenConstructorInfo\fR [get]\fP, \fR [set]\fP"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.Reflectives\&.Models\&.IReflectiveParameter\fP\&.
.PP
Definition at line \fB19\fP of file \fBReflectiveParameter\&.cs\fP\&.
.SS "Func<object?>? Luthetus\&.Common\&.RazorLib\&.Reflectives\&.Models\&.ReflectiveParameter\&.ConstructValueFunc\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB20\fP of file \fBReflectiveParameter\&.cs\fP\&.
.SS "\fBReflectiveParameterKind\fP Luthetus\&.Common\&.RazorLib\&.Reflectives\&.Models\&.ReflectiveParameter\&.ReflectiveParameterKind\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.Reflectives\&.Models\&.IReflectiveParameter\fP\&.
.PP
Definition at line \fB25\fP of file \fBReflectiveParameter\&.cs\fP\&.
.SS "Type Luthetus\&.Common\&.RazorLib\&.Reflectives\&.Models\&.ReflectiveParameter\&.Type\fR [get]\fP, \fR [set]\fP"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.Reflectives\&.Models\&.IReflectiveParameter\fP\&.
.PP
Definition at line \fB23\fP of file \fBReflectiveParameter\&.cs\fP\&.
.SS "object? Luthetus\&.Common\&.RazorLib\&.Reflectives\&.Models\&.ReflectiveParameter\&.Value\fR [get]\fP, \fR [set]\fP"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.Reflectives\&.Models\&.IReflectiveParameter\fP\&.
.PP
Definition at line \fB21\fP of file \fBReflectiveParameter\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
