.TH "Luthetus.TextEditor.Tests.Basis" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBAutocompletes\fP"
.br
.ti -1c
.RI "namespace \fBCharacters\fP"
.br
.ti -1c
.RI "namespace \fBCommands\fP"
.br
.ti -1c
.RI "namespace \fBCompilerServices\fP"
.br
.ti -1c
.RI "namespace \fBComponentRenderers\fP"
.br
.ti -1c
.RI "namespace \fBCursors\fP"
.br
.ti -1c
.RI "namespace \fBDecorations\fP"
.br
.ti -1c
.RI "namespace \fBDiffs\fP"
.br
.ti -1c
.RI "namespace \fBEvents\fP"
.br
.ti -1c
.RI "namespace \fBGroups\fP"
.br
.ti -1c
.RI "namespace \fBHtmls\fP"
.br
.ti -1c
.RI "namespace \fBInstallations\fP"
.br
.ti -1c
.RI "namespace \fBJavaScriptObjects\fP"
.br
.ti -1c
.RI "namespace \fBKeymaps\fP"
.br
.ti -1c
.RI "namespace \fBLexers\fP"
.br
.ti -1c
.RI "namespace \fBLexes\fP"
.br
.ti -1c
.RI "namespace \fBOptions\fP"
.br
.ti -1c
.RI "namespace \fBRows\fP"
.br
.ti -1c
.RI "namespace \fBTextEditors\fP"
.br
.ti -1c
.RI "namespace \fBUnitTesting\fP"
.br
.ti -1c
.RI "namespace \fBVirtualizations\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBServiceTests\fP"
.br
.RI "TextEditorService "
.ti -1c
.RI "class \fBTestsHelper\fP"
.br
.ti -1c
.RI "class \fBTextEditorTestBase\fP"
.br
.RI "It is preferred that each test defines its own test data within the '[Fact]' method itself\&. There however is 100 lines of code at the beginning of every test if one follows this rule\&. To reduce the noise, this method was created\&.
.br

.br
\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
