.TH "Luthetus.Common.Tests.Basis.WatchWindows.Models.TreeViewInterfaceImplementationTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.WatchWindows.Models.TreeViewInterfaceImplementationTests \- \fBTreeViewInterfaceImplementation\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "TreeViewInterfaceImplementation(WatchWindowObject, bool, bool, ILuthetusCommonComponentRenderers) "
.ti -1c
.RI "void \fBGetTreeViewRenderer\fP ()"
.br
.RI "\fBTreeViewInterfaceImplementation\&.GetTreeViewRenderer()\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBTreeViewInterfaceImplementation\fP 
.PP
Definition at line \fB8\fP of file \fBTreeViewInterfaceImplementationTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.WatchWindows\&.Models\&.TreeViewInterfaceImplementationTests\&.Constructor ()"

.PP
TreeViewInterfaceImplementation(WatchWindowObject, bool, bool, ILuthetusCommonComponentRenderers) 
.PP
Definition at line \fB14\fP of file \fBTreeViewInterfaceImplementationTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.WatchWindows\&.Models\&.TreeViewInterfaceImplementationTests\&.GetTreeViewRenderer ()"

.PP
\fBTreeViewInterfaceImplementation\&.GetTreeViewRenderer()\fP 
.PP
Definition at line \fB48\fP of file \fBTreeViewInterfaceImplementationTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
