.TH "Luthetus.Common.Tests.Basis.Contexts.States.ContextStateReducerTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Contexts.States.ContextStateReducerTests \- ContextState\&.Reducer  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBReduceSetFocusedContextHeirarchyAction\fP ()"
.br
.RI "ContextState\&.Reducer\&.ReduceSetFocusedContextHeirarchyAction(ContextState, ContextState\&.SetFocusedContextHeirarchyAction) "
.ti -1c
.RI "void \fBReduceToggleSelectInspectedContextHeirarchyAction\fP ()"
.br
.RI "ContextState\&.Reducer\&.ReduceToggleSelectInspectedContextHeirarchyAction(ContextState) "
.ti -1c
.RI "void \fBReduceIsSelectingInspectableContextHeirarchyAction\fP ()"
.br
.RI "ContextState\&.Reducer\&.ReduceIsSelectingInspectableContextHeirarchyAction(ContextState, ContextState\&.IsSelectingInspectableContextHeirarchyAction) "
.ti -1c
.RI "void \fBReduceSetInspectedContextHeirarchyAction\fP ()"
.br
.RI "ContextState\&.Reducer\&.ReduceSetInspectedContextHeirarchyAction(ContextState, ContextState\&.SetInspectedContextHeirarchyAction) "
.ti -1c
.RI "void \fBReduceAddInspectableContextAction\fP ()"
.br
.RI "ContextState\&.Reducer\&.ReduceAddInspectableContextAction(ContextState, ContextState\&.AddInspectableContextAction) "
.ti -1c
.RI "void \fBReduceSetContextKeymapAction\fP ()"
.br
.RI "ContextState\&.Reducer\&.ReduceSetContextKeymapAction(ContextState, ContextState\&.SetContextKeymapAction) "
.in -1c
.SH "Detailed Description"
.PP 
ContextState\&.Reducer 
.PP
Definition at line \fB16\fP of file \fBContextStateTests\&.Reducer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Contexts\&.States\&.ContextStateReducerTests\&.ReduceAddInspectableContextAction ()"

.PP
ContextState\&.Reducer\&.ReduceAddInspectableContextAction(ContextState, ContextState\&.AddInspectableContextAction) 
.PP
Definition at line \fB124\fP of file \fBContextStateTests\&.Reducer\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Contexts\&.States\&.ContextStateReducerTests\&.ReduceIsSelectingInspectableContextHeirarchyAction ()"

.PP
ContextState\&.Reducer\&.ReduceIsSelectingInspectableContextHeirarchyAction(ContextState, ContextState\&.IsSelectingInspectableContextHeirarchyAction) 
.PP
Definition at line \fB76\fP of file \fBContextStateTests\&.Reducer\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Contexts\&.States\&.ContextStateReducerTests\&.ReduceSetContextKeymapAction ()"

.PP
ContextState\&.Reducer\&.ReduceSetContextKeymapAction(ContextState, ContextState\&.SetContextKeymapAction) 
.PP
Definition at line \fB153\fP of file \fBContextStateTests\&.Reducer\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Contexts\&.States\&.ContextStateReducerTests\&.ReduceSetFocusedContextHeirarchyAction ()"

.PP
ContextState\&.Reducer\&.ReduceSetFocusedContextHeirarchyAction(ContextState, ContextState\&.SetFocusedContextHeirarchyAction) 
.PP
Definition at line \fB22\fP of file \fBContextStateTests\&.Reducer\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Contexts\&.States\&.ContextStateReducerTests\&.ReduceSetInspectedContextHeirarchyAction ()"

.PP
ContextState\&.Reducer\&.ReduceSetInspectedContextHeirarchyAction(ContextState, ContextState\&.SetInspectedContextHeirarchyAction) 
.PP
Definition at line \fB100\fP of file \fBContextStateTests\&.Reducer\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Contexts\&.States\&.ContextStateReducerTests\&.ReduceToggleSelectInspectedContextHeirarchyAction ()"

.PP
ContextState\&.Reducer\&.ReduceToggleSelectInspectedContextHeirarchyAction(ContextState) 
.PP
Definition at line \fB52\fP of file \fBContextStateTests\&.Reducer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
