.TH "Luthetus.TextEditor.RazorLib.Decorations.Models.IDecorationMapper" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Decorations.Models.IDecorationMapper
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.CompilerServices\&.Css\&.Decoration\&.TextEditorCssDecorationMapper\fP, \fBLuthetus\&.CompilerServices\&.Json\&.Decoration\&.TextEditorJsonDecorationMapper\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.Decoration\&.TextEditorHtmlDecorationMapper\fP, \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalDecorationMapper\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.CompilerServiceDiagnosticDecorationMapper\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.Decoration\&.GenericDecorationMapper\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.Decorations\&.Models\&.TextEditorDecorationMapperDefault\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.TextEditorDiffDecorationMapper\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.FindOverlayDecorationMapper\fP, and \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.TextEditorDevToolsDecorationMapper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBMap\fP (byte decorationByte)"
.br
.RI "Maps a decorationByte to a CSS class that is in the form of a string\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBIDecorationMapper\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.Decorations\&.Models\&.IDecorationMapper\&.Map (byte decorationByte)"

.PP
Maps a decorationByte to a CSS class that is in the form of a string\&. 
.PP
Implemented in \fBLuthetus\&.CompilerServices\&.Css\&.Decoration\&.TextEditorCssDecorationMapper\fP, \fBLuthetus\&.CompilerServices\&.Json\&.Decoration\&.TextEditorJsonDecorationMapper\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.Decoration\&.TextEditorHtmlDecorationMapper\fP, \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalDecorationMapper\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.CompilerServiceDiagnosticDecorationMapper\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.Decoration\&.GenericDecorationMapper\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.Decorations\&.Models\&.TextEditorDecorationMapperDefault\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.TextEditorDiffDecorationMapper\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.FindOverlayDecorationMapper\fP, and \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.TextEditorDevToolsDecorationMapper\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
