.TH "Luthetus.Ide.Tests.Basis.Clipboards.Models.ClipboardFactsTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.Tests.Basis.Clipboards.Models.ClipboardFactsTests \- ClipboardFacts  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBTag\fP ()"
.br
.RI "ClipboardFacts\&.Tag "
.ti -1c
.RI "void \fBFieldDelimiter\fP ()"
.br
.RI "ClipboardFacts\&.FieldDelimiter "
.ti -1c
.RI "void \fBCopyCommand\fP ()"
.br
.RI "ClipboardFacts\&.CopyCommand "
.ti -1c
.RI "void \fBCutCommand\fP ()"
.br
.RI "ClipboardFacts\&.CutCommand "
.ti -1c
.RI "void \fBAbsolutePathDataType\fP ()"
.br
.RI "ClipboardFacts\&.AbsolutePathDataType "
.ti -1c
.RI "void \fBFormatPhrase\fP ()"
.br
.RI "ClipboardFacts\&.FormatPhrase(string, string, string) "
.ti -1c
.RI "void \fBTryParseString\fP ()"
.br
.RI "ClipboardFacts\&.TryParseString(string, out ClipboardPhrase?) "
.in -1c
.SH "Detailed Description"
.PP 
ClipboardFacts 
.PP
Definition at line \fB9\fP of file \fBClipboardFactsTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.Clipboards\&.Models\&.ClipboardFactsTests\&.AbsolutePathDataType ()"

.PP
ClipboardFacts\&.AbsolutePathDataType 
.PP
Definition at line \fB52\fP of file \fBClipboardFactsTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.Clipboards\&.Models\&.ClipboardFactsTests\&.CopyCommand ()"

.PP
ClipboardFacts\&.CopyCommand 
.PP
Definition at line \fB34\fP of file \fBClipboardFactsTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.Clipboards\&.Models\&.ClipboardFactsTests\&.CutCommand ()"

.PP
ClipboardFacts\&.CutCommand 
.PP
Definition at line \fB43\fP of file \fBClipboardFactsTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.Clipboards\&.Models\&.ClipboardFactsTests\&.FieldDelimiter ()"

.PP
ClipboardFacts\&.FieldDelimiter 
.PP
Definition at line \fB25\fP of file \fBClipboardFactsTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.Clipboards\&.Models\&.ClipboardFactsTests\&.FormatPhrase ()"

.PP
ClipboardFacts\&.FormatPhrase(string, string, string) 
.PP
Definition at line \fB61\fP of file \fBClipboardFactsTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.Clipboards\&.Models\&.ClipboardFactsTests\&.Tag ()"

.PP
ClipboardFacts\&.Tag 
.PP
Definition at line \fB15\fP of file \fBClipboardFactsTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.Clipboards\&.Models\&.ClipboardFactsTests\&.TryParseString ()"

.PP
ClipboardFacts\&.TryParseString(string, out ClipboardPhrase?) 
.PP
Definition at line \fB91\fP of file \fBClipboardFactsTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
