.TH "Luthetus.TextEditor.RazorLib.Cursors.Models.TextCursorKindFacts" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Cursors.Models.TextCursorKindFacts
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBBeamCssClassString\fP = 'luth_te_cursor\-beam'"
.br
.ti -1c
.RI "const string \fBBlockCssClassString\fP = 'luth_te_cursor\-block'"
.br
.ti -1c
.RI "const string \fBReplaceCssClassString\fP = 'luth_te_cursor\-replace'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBTextCursorKindFacts\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const string Luthetus\&.TextEditor\&.RazorLib\&.Cursors\&.Models\&.TextCursorKindFacts\&.BeamCssClassString = 'luth_te_cursor\-beam'\fR [static]\fP"

.PP
Definition at line \fB5\fP of file \fBTextCursorKindFacts\&.cs\fP\&.
.SS "const string Luthetus\&.TextEditor\&.RazorLib\&.Cursors\&.Models\&.TextCursorKindFacts\&.BlockCssClassString = 'luth_te_cursor\-block'\fR [static]\fP"

.PP
Definition at line \fB6\fP of file \fBTextCursorKindFacts\&.cs\fP\&.
.SS "const string Luthetus\&.TextEditor\&.RazorLib\&.Cursors\&.Models\&.TextCursorKindFacts\&.ReplaceCssClassString = 'luth_te_cursor\-replace'\fR [static]\fP"

.PP
Definition at line \fB7\fP of file \fBTextCursorKindFacts\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
