.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.GenericLexer.SyntaxObjects.GenericCommentSingleLineSyntaxTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.GenericLexer.SyntaxObjects.GenericCommentSingleLineSyntaxTests \- \fBGenericCommentSingleLineSyntax\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "GenericCommentSingleLineSyntax(TextEditorTextSpan) 
.br
----
.br
 \fBGenericCommentSingleLineSyntax\&.TextSpan\fP \fBGenericCommentSingleLineSyntax\&.ChildList\fP \fBGenericCommentSingleLineSyntax\&.GenericSyntaxKind\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBGenericCommentSingleLineSyntax\fP 
.PP
Definition at line \fB9\fP of file \fBGenericCommentSingleLineSyntaxTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericCommentSingleLineSyntaxTests\&.Constructor ()"

.PP
GenericCommentSingleLineSyntax(TextEditorTextSpan) 
.br
----
.br
 \fBGenericCommentSingleLineSyntax\&.TextSpan\fP \fBGenericCommentSingleLineSyntax\&.ChildList\fP \fBGenericCommentSingleLineSyntax\&.GenericSyntaxKind\fP 
.PP
Definition at line \fB19\fP of file \fBGenericCommentSingleLineSyntaxTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
