.TH "Luthetus.Common.RazorLib.Outlines.States" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Outlines.States
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "partial record \fBOutlineState\fP (string? ElementId, \fBMeasuredHtmlElementDimensions\fP? \fBMeasuredHtmlElementDimensions\fP, bool NeedsMeasured)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "partial record Luthetus\&.Common\&.RazorLib\&.Outlines\&.States\&.OutlineState (string? ElementId, \fBMeasuredHtmlElementDimensions\fP? MeasuredHtmlElementDimensions, bool NeedsMeasured)"

.PP
Definition at line \fB7\fP of file \fBOutlineState\&.Main\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
