.TH "Luthetus.Common.RazorLib.TreeViews.Models.TreeViewService" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.TreeViews.Models.TreeViewService
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTreeViewService\fP (IState< TreeViewState > treeViewStateWrap, \fBIBackgroundTaskService\fP backgroundTaskService, IDispatcher dispatcher)"
.br
.ti -1c
.RI "void \fBRegisterTreeViewContainer\fP (\fBTreeViewContainer\fP container)"
.br
.RI "Duplicate keys do NOT throw an exception\&. "
.ti -1c
.RI "void \fBDisposeTreeViewContainer\fP (Key< \fBTreeViewContainer\fP > containerKey)"
.br
.ti -1c
.RI "void \fBReplaceTreeViewContainer\fP (Key< \fBTreeViewContainer\fP > containerKey, \fBTreeViewContainer\fP container)"
.br
.ti -1c
.RI "void \fBSetRoot\fP (Key< \fBTreeViewContainer\fP > containerKey, \fBTreeViewNoType\fP node)"
.br
.ti -1c
.RI "bool \fBTryGetTreeViewContainer\fP (Key< \fBTreeViewContainer\fP > containerKey, out \fBTreeViewContainer\fP? container)"
.br
.ti -1c
.RI "void \fBReRenderNode\fP (Key< \fBTreeViewContainer\fP > containerKey, \fBTreeViewNoType\fP node)"
.br
.ti -1c
.RI "void \fBAddChildNode\fP (Key< \fBTreeViewContainer\fP > containerKey, \fBTreeViewNoType\fP parent, \fBTreeViewNoType\fP child)"
.br
.ti -1c
.RI "void \fBSetActiveNode\fP (Key< \fBTreeViewContainer\fP > containerKey, \fBTreeViewNoType\fP? nextActiveNode, bool addSelectedNodes, bool selectNodesBetweenCurrentAndNextActiveNode)"
.br
.ti -1c
.RI "void \fBMoveLeft\fP (Key< \fBTreeViewContainer\fP > containerKey, bool addSelectedNodes, bool selectNodesBetweenCurrentAndNextActiveNode)"
.br
.ti -1c
.RI "void \fBMoveDown\fP (Key< \fBTreeViewContainer\fP > containerKey, bool addSelectedNodes, bool selectNodesBetweenCurrentAndNextActiveNode)"
.br
.ti -1c
.RI "void \fBMoveUp\fP (Key< \fBTreeViewContainer\fP > containerKey, bool addSelectedNodes, bool selectNodesBetweenCurrentAndNextActiveNode)"
.br
.ti -1c
.RI "void \fBMoveRight\fP (Key< \fBTreeViewContainer\fP > containerKey, bool addSelectedNodes, bool selectNodesBetweenCurrentAndNextActiveNode)"
.br
.ti -1c
.RI "void \fBMoveHome\fP (Key< \fBTreeViewContainer\fP > containerKey, bool addSelectedNodes, bool selectNodesBetweenCurrentAndNextActiveNode)"
.br
.ti -1c
.RI "void \fBMoveEnd\fP (Key< \fBTreeViewContainer\fP > containerKey, bool addSelectedNodes, bool selectNodesBetweenCurrentAndNextActiveNode)"
.br
.ti -1c
.RI "string \fBGetNodeElementId\fP (\fBTreeViewNoType\fP node)"
.br
.ti -1c
.RI "string \fBGetTreeViewContainerElementId\fP (Key< \fBTreeViewContainer\fP > containerKey)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IState< TreeViewState > \fBTreeViewStateWrap\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBTreeViewService\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\&.TreeViewService (IState< TreeViewState > treeViewStateWrap, \fBIBackgroundTaskService\fP backgroundTaskService, IDispatcher dispatcher)"

.PP
Definition at line \fB13\fP of file \fBTreeViewService\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\&.AddChildNode (Key< \fBTreeViewContainer\fP > containerKey, \fBTreeViewNoType\fP parent, \fBTreeViewNoType\fP child)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\fP\&.
.PP
Definition at line \fB66\fP of file \fBTreeViewService\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\&.DisposeTreeViewContainer (Key< \fBTreeViewContainer\fP > containerKey)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\fP\&.
.PP
Definition at line \fB31\fP of file \fBTreeViewService\&.cs\fP\&.
.SS "string Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\&.GetNodeElementId (\fBTreeViewNoType\fP node)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\fP\&.
.PP
Definition at line \fB198\fP of file \fBTreeViewService\&.cs\fP\&.
.SS "string Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\&.GetTreeViewContainerElementId (Key< \fBTreeViewContainer\fP > containerKey)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\fP\&.
.PP
Definition at line \fB203\fP of file \fBTreeViewService\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\&.MoveDown (Key< \fBTreeViewContainer\fP > containerKey, bool addSelectedNodes, bool selectNodesBetweenCurrentAndNextActiveNode)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\fP\&.
.PP
Definition at line \fB106\fP of file \fBTreeViewService\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\&.MoveEnd (Key< \fBTreeViewContainer\fP > containerKey, bool addSelectedNodes, bool selectNodesBetweenCurrentAndNextActiveNode)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\fP\&.
.PP
Definition at line \fB185\fP of file \fBTreeViewService\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\&.MoveHome (Key< \fBTreeViewContainer\fP > containerKey, bool addSelectedNodes, bool selectNodesBetweenCurrentAndNextActiveNode)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\fP\&.
.PP
Definition at line \fB172\fP of file \fBTreeViewService\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\&.MoveLeft (Key< \fBTreeViewContainer\fP > containerKey, bool addSelectedNodes, bool selectNodesBetweenCurrentAndNextActiveNode)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\fP\&.
.PP
Definition at line \fB94\fP of file \fBTreeViewService\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\&.MoveRight (Key< \fBTreeViewContainer\fP > containerKey, bool addSelectedNodes, bool selectNodesBetweenCurrentAndNextActiveNode)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\fP\&.
.PP
Definition at line \fB132\fP of file \fBTreeViewService\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\&.MoveUp (Key< \fBTreeViewContainer\fP > containerKey, bool addSelectedNodes, bool selectNodesBetweenCurrentAndNextActiveNode)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\fP\&.
.PP
Definition at line \fB119\fP of file \fBTreeViewService\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\&.RegisterTreeViewContainer (\fBTreeViewContainer\fP container)"

.PP
Duplicate keys do NOT throw an exception\&. 
.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\fP\&.
.PP
Definition at line \fB25\fP of file \fBTreeViewService\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\&.ReplaceTreeViewContainer (Key< \fBTreeViewContainer\fP > containerKey, \fBTreeViewContainer\fP container)"

.PP
Definition at line \fB37\fP of file \fBTreeViewService\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\&.ReRenderNode (Key< \fBTreeViewContainer\fP > containerKey, \fBTreeViewNoType\fP node)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\fP\&.
.PP
Definition at line \fB60\fP of file \fBTreeViewService\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\&.SetActiveNode (Key< \fBTreeViewContainer\fP > containerKey, \fBTreeViewNoType\fP? nextActiveNode, bool addSelectedNodes, bool selectNodesBetweenCurrentAndNextActiveNode)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\fP\&.
.PP
Definition at line \fB79\fP of file \fBTreeViewService\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\&.SetRoot (Key< \fBTreeViewContainer\fP > containerKey, \fBTreeViewNoType\fP node)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\fP\&.
.PP
Definition at line \fB46\fP of file \fBTreeViewService\&.cs\fP\&.
.SS "bool Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\&.TryGetTreeViewContainer (Key< \fBTreeViewContainer\fP > containerKey, out \fBTreeViewContainer\fP? container)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\fP\&.
.PP
Definition at line \fB52\fP of file \fBTreeViewService\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "IState<TreeViewState> Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\&.TreeViewStateWrap\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\fP\&.
.PP
Definition at line \fB23\fP of file \fBTreeViewService\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
