.TH "Luthetus.CompilerServices.Xml.Html.SyntaxObjects.TagNode" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.Xml.Html.SyntaxObjects.TagNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.IHtmlSyntaxNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTagNode\fP (\fBTagNameNode\fP? openTagNameNode, \fBTagNameNode\fP? closeTagNameNode, ImmutableArray< \fBAttributeNode\fP > attributeNodes, ImmutableArray< \fBIHtmlSyntax\fP > childHtmlSyntaxes, \fBHtmlSyntaxKind\fP htmlSyntaxKind, bool hasSpecialHtmlCharacter=false)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBTagNameNode\fP? \fBOpenTagNameNode\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBTagNameNode\fP? \fBCloseTagNameNode\fP\fR [get]\fP"
.br
.ti -1c
.RI "ImmutableArray< \fBAttributeNode\fP > \fBAttributeNodes\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBHasSpecialHtmlCharacter\fP\fR [get]\fP"
.br
.ti -1c
.RI "ImmutableArray< \fBIHtmlSyntax\fP > \fBChildContent\fP\fR [get]\fP"
.br
.ti -1c
.RI "ImmutableArray< \fBIHtmlSyntax\fP > \fBChildren\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBHtmlSyntaxKind\fP \fBHtmlSyntaxKind\fP\fR [get]\fP"
.br
.ti -1c
.RI "TextEditorTextSpan \fBTextEditorTextSpan\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBTagNode\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.TagNode\&.TagNode (\fBTagNameNode\fP? openTagNameNode, \fBTagNameNode\fP? closeTagNameNode, ImmutableArray< \fBAttributeNode\fP > attributeNodes, ImmutableArray< \fBIHtmlSyntax\fP > childHtmlSyntaxes, \fBHtmlSyntaxKind\fP htmlSyntaxKind, bool hasSpecialHtmlCharacter = \fRfalse\fP)"

.PP
Definition at line \fB10\fP of file \fBTagNode\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "ImmutableArray<\fBAttributeNode\fP> Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.TagNode\&.AttributeNodes\fR [get]\fP"

.PP
Definition at line \fB48\fP of file \fBTagNode\&.cs\fP\&.
.SS "ImmutableArray<\fBIHtmlSyntax\fP> Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.TagNode\&.ChildContent\fR [get]\fP"

.PP
Implements \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.IHtmlSyntaxNode\fP\&.
.PP
Definition at line \fB51\fP of file \fBTagNode\&.cs\fP\&.
.SS "ImmutableArray<\fBIHtmlSyntax\fP> Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.TagNode\&.Children\fR [get]\fP"

.PP
Implements \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.IHtmlSyntaxNode\fP\&.
.PP
Definition at line \fB52\fP of file \fBTagNode\&.cs\fP\&.
.SS "\fBTagNameNode\fP? Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.TagNode\&.CloseTagNameNode\fR [get]\fP"

.PP
Definition at line \fB47\fP of file \fBTagNode\&.cs\fP\&.
.SS "bool Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.TagNode\&.HasSpecialHtmlCharacter\fR [get]\fP"

.PP
Definition at line \fB49\fP of file \fBTagNode\&.cs\fP\&.
.SS "\fBHtmlSyntaxKind\fP Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.TagNode\&.HtmlSyntaxKind\fR [get]\fP"

.PP
Implements \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.IHtmlSyntax\fP\&.
.PP
Definition at line \fB53\fP of file \fBTagNode\&.cs\fP\&.
.SS "\fBTagNameNode\fP? Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.TagNode\&.OpenTagNameNode\fR [get]\fP"

.PP
Definition at line \fB46\fP of file \fBTagNode\&.cs\fP\&.
.SS "TextEditorTextSpan Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.TagNode\&.TextEditorTextSpan\fR [get]\fP"

.PP
Implements \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.IHtmlSyntaxNode\fP\&.
.PP
Definition at line \fB55\fP of file \fBTagNode\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
