.TH "Luthetus.Common.RazorLib.Resizes.Displays.ResizableRow" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Resizes.Displays.ResizableRow
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase, and IDisposable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInitialized\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBElementDimensions\fP \fBTopElementDimensions\fP = null!\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBElementDimensions\fP \fBBottomElementDimensions\fP = null!\fR [get, set]\fP"
.br
.ti -1c
.RI "Func< Task > \fBReRenderFuncAsync\fP = null!\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB12\fP of file \fBResizableRow\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.RazorLib\&.Resizes\&.Displays\&.ResizableRow\&.Dispose ()"

.PP
Definition at line \fB98\fP of file \fBResizableRow\&.razor\&.cs\fP\&.
.SS "override void Luthetus\&.Common\&.RazorLib\&.Resizes\&.Displays\&.ResizableRow\&.OnInitialized ()\fR [protected]\fP"

.PP
Definition at line \fB31\fP of file \fBResizableRow\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBElementDimensions\fP Luthetus\&.Common\&.RazorLib\&.Resizes\&.Displays\&.ResizableRow\&.BottomElementDimensions = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB24\fP of file \fBResizableRow\&.razor\&.cs\fP\&.
.SS "Func<Task> Luthetus\&.Common\&.RazorLib\&.Resizes\&.Displays\&.ResizableRow\&.ReRenderFuncAsync = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB26\fP of file \fBResizableRow\&.razor\&.cs\fP\&.
.SS "\fBElementDimensions\fP Luthetus\&.Common\&.RazorLib\&.Resizes\&.Displays\&.ResizableRow\&.TopElementDimensions = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB22\fP of file \fBResizableRow\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
