.TH "Luthetus.Common.RazorLib.Commands.Models.ICommandArgs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Commands.Models.ICommandArgs
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.Common\&.RazorLib\&.Commands\&.Models\&.CommonCommandArgs\fP, \fBLuthetus\&.Common\&.RazorLib\&.Commands\&.Models\&.TreeViewCommandArgs\fP, \fBLuthetus\&.Common\&.RazorLib\&.Keymaps\&.Models\&.KeymapArgs\fP, and \fBLuthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.TextEditorCommandArgs\fP\&.
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBICommandArgs\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
