.TH "Luthetus.Ide.RazorLib.Editors.Models.EditorIdeApi" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.Editors.Models.EditorIdeApi
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBEditorIdeApi\fP (\fBIdeBackgroundTaskApi\fP ideBackgroundTaskApi, \fBIBackgroundTaskService\fP backgroundTaskService, \fBITextEditorService\fP \fBtextEditorService\fP, \fBICommonComponentRenderers\fP commonComponentRenderers, \fBIIdeComponentRenderers\fP ideComponentRenderers, \fBIFileSystemProvider\fP fileSystemProvider, \fBIEnvironmentProvider\fP environmentProvider, \fBIDecorationMapperRegistry\fP decorationMapperRegistry, \fBICompilerServiceRegistry\fP compilerServiceRegistry, \fBIDialogService\fP \fBdialogService\fP, IDispatcher \fBdispatcher\fP, IJSRuntime \fBjsRuntime\fP, IServiceProvider serviceProvider)"
.br
.ti -1c
.RI "void \fBShowInputFile\fP ()"
.br
.ti -1c
.RI "async Task \fBRegisterModelFunc\fP (\fBRegisterModelArgs\fP registerModelArgs)"
.br
.ti -1c
.RI "Task< Key< \fBTextEditorViewModel\fP > > \fBTryRegisterViewModelFunc\fP (\fBTryRegisterViewModelArgs\fP registerViewModelArgs)"
.br
.ti -1c
.RI "async Task< bool > \fBTryShowViewModelFunc\fP (\fBTryShowViewModelArgs\fP showViewModelArgs)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly Key< TextEditorGroup > \fBEditorTextEditorGroupKey\fP = Key<TextEditorGroup>\&.NewKey()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB31\fP of file \fBEditorIdeApi\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Ide\&.RazorLib\&.Editors\&.Models\&.EditorIdeApi\&.EditorIdeApi (\fBIdeBackgroundTaskApi\fP ideBackgroundTaskApi, \fBIBackgroundTaskService\fP backgroundTaskService, \fBITextEditorService\fP textEditorService, \fBICommonComponentRenderers\fP commonComponentRenderers, \fBIIdeComponentRenderers\fP ideComponentRenderers, \fBIFileSystemProvider\fP fileSystemProvider, \fBIEnvironmentProvider\fP environmentProvider, \fBIDecorationMapperRegistry\fP decorationMapperRegistry, \fBICompilerServiceRegistry\fP compilerServiceRegistry, \fBIDialogService\fP dialogService, IDispatcher dispatcher, IJSRuntime jsRuntime, IServiceProvider serviceProvider)"

.PP
Definition at line \fB49\fP of file \fBEditorIdeApi\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "async Task Luthetus\&.Ide\&.RazorLib\&.Editors\&.Models\&.EditorIdeApi\&.RegisterModelFunc (\fBRegisterModelArgs\fP registerModelArgs)"

.PP
Definition at line \fB105\fP of file \fBEditorIdeApi\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.RazorLib\&.Editors\&.Models\&.EditorIdeApi\&.ShowInputFile ()"

.PP
Definition at line \fB79\fP of file \fBEditorIdeApi\&.cs\fP\&.
.SS "Task< Key< \fBTextEditorViewModel\fP > > Luthetus\&.Ide\&.RazorLib\&.Editors\&.Models\&.EditorIdeApi\&.TryRegisterViewModelFunc (\fBTryRegisterViewModelArgs\fP registerViewModelArgs)"

.PP
Definition at line \fB172\fP of file \fBEditorIdeApi\&.cs\fP\&.
.SS "async Task< bool > Luthetus\&.Ide\&.RazorLib\&.Editors\&.Models\&.EditorIdeApi\&.TryShowViewModelFunc (\fBTryShowViewModelArgs\fP showViewModelArgs)"

.PP
Definition at line \fB276\fP of file \fBEditorIdeApi\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly Key<TextEditorGroup> Luthetus\&.Ide\&.RazorLib\&.Editors\&.Models\&.EditorIdeApi\&.EditorTextEditorGroupKey = Key<TextEditorGroup>\&.NewKey()\fR [static]\fP"

.PP
Definition at line \fB33\fP of file \fBEditorIdeApi\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
