.TH "Luthetus.Common.RazorLib.Dimensions.Models" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Dimensions.Models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBrowserResizeInterop\fP"
.br
.RI "TODO: The way this class will interact with Blazor ServerSide is a current concern (as this class is being written)\&. So, make sure to test out ServerSide, refresh the page, etc\&.\&.\&. "
.ti -1c
.RI "class \fBCssInterpolation\fP"
.br
.RI "This file relates to HTML markup\&. Specifically, when one interpolates a double from C# into a HTML tag's style attribute\&. Depending on where one lives, one might see either, "5\&.2" or "5,2"\&. If one has the comma formatting, the styling will not parse correctly when being rendered\&. 
.br

.br
 So, this file ensures period formatting regardless of localization\&. "
.ti -1c
.RI "class \fBDimensionAttribute\fP"
.br
.ti -1c
.RI "class \fBDimensionOperatorKindExtensions\fP"
.br
.ti -1c
.RI "class \fBDimensionService\fP"
.br
.ti -1c
.RI "class \fBDimensionUnit\fP"
.br
.ti -1c
.RI "class \fBDimensionUnitFacts\fP"
.br
.ti -1c
.RI "class \fBDimensionUnitKindExtensions\fP"
.br
.ti -1c
.RI "class \fBElementDimensions\fP"
.br
.ti -1c
.RI "class \fBSizeFacts\fP"
.br
.RI "TODO: SphagettiCode - I don't like this file (2023-09-19) Why does \fBSizeFacts\&.cs\fP, HtmlFacts\&.Button\&.cs, and HtmlFacts\&.Main\&.cs exist? Merge all three of these? "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBDimensionAttributeKind\fP { \fBWidth\fP, \fBHeight\fP, \fBLeft\fP, \fBRight\fP, \fBTop\fP, \fBBottom\fP }"
.br
.ti -1c
.RI "enum \fBDimensionOperatorKind\fP { \fBAdd\fP, \fBSubtract\fP, \fBMultiply\fP, \fBDivide\fP }"
.br
.ti -1c
.RI "enum \fBDimensionUnitKind\fP { \fBPixels\fP, \fBViewportWidth\fP, \fBViewportHeight\fP, \fBPercentage\fP, \fBRootCharacterWidth\fP, \fBRootCharacterHeight\fP, \fBCharacterWidth\fP, \fBCharacterHeight\fP }"
.br
.ti -1c
.RI "enum \fBElementPositionKind\fP { \fBStatic\fP, \fBAbsolute\fP, \fBFixed\fP, \fBInherit\fP, \fBRelative\fP, \fBRevert\fP, \fBSticky\fP, \fBUnset\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBLuthetus\&.Common\&.RazorLib\&.Dimensions\&.Models\&.DimensionAttributeKind\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIWidth \fP
.TP
\f(BIHeight \fP
.TP
\f(BILeft \fP
.TP
\f(BIRight \fP
.TP
\f(BITop \fP
.TP
\f(BIBottom \fP
.PP
Definition at line \fB3\fP of file \fBDimensionAttributeKind\&.cs\fP\&.
.SS "enum \fBLuthetus\&.Common\&.RazorLib\&.Dimensions\&.Models\&.DimensionOperatorKind\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIAdd \fP
.TP
\f(BISubtract \fP
.TP
\f(BIMultiply \fP
.TP
\f(BIDivide \fP
.PP
Definition at line \fB3\fP of file \fBDimensionOperatorKind\&.cs\fP\&.
.SS "enum \fBLuthetus\&.Common\&.RazorLib\&.Dimensions\&.Models\&.DimensionUnitKind\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIPixels \fP
.TP
\f(BIViewportWidth \fP
.TP
\f(BIViewportHeight \fP
.TP
\f(BIPercentage \fP
.TP
\f(BIRootCharacterWidth \fP
.TP
\f(BIRootCharacterHeight \fP
.TP
\f(BICharacterWidth \fP
.TP
\f(BICharacterHeight \fP
.PP
Definition at line \fB3\fP of file \fBDimensionUnitKind\&.cs\fP\&.
.SS "enum \fBLuthetus\&.Common\&.RazorLib\&.Dimensions\&.Models\&.ElementPositionKind\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIStatic \fP
.TP
\f(BIAbsolute \fP
.TP
\f(BIFixed \fP
.TP
\f(BIInherit \fP
.TP
\f(BIRelative \fP
.TP
\f(BIRevert \fP
.TP
\f(BISticky \fP
.TP
\f(BIUnset \fP
.PP
Definition at line \fB3\fP of file \fBElementPositionKind\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
