.TH "Luthetus.Common.Tests.Basis.TreeViews.States.TreeViewStateActionsTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.TreeViews.States.TreeViewStateActionsTests \- \fBTreeViewState\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRegisterContainerAction\fP ()"
.br
.RI "TreeViewState\&.RegisterContainerAction "
.ti -1c
.RI "void \fBDisposeContainerAction\fP ()"
.br
.RI "TreeViewState\&.DisposeContainerAction "
.ti -1c
.RI "async Task \fBWithRootNodeActionAsync\fP ()"
.br
.RI "WithRootNodeAction "
.ti -1c
.RI "void \fBTryGetContainerAction\fP ()"
.br
.RI "TreeViewState\&.TryGetContainerAction "
.ti -1c
.RI "void \fBReplaceContainerAction\fP ()"
.br
.RI "TreeViewState\&.ReplaceContainerAction "
.ti -1c
.RI "async Task \fBAddChildNodeActionAsync\fP ()"
.br
.RI "AddChildNodeAction "
.ti -1c
.RI "void \fBReRenderNodeAction\fP ()"
.br
.RI "TreeViewState\&.ReRenderNodeAction "
.ti -1c
.RI "void \fBSetActiveNodeAction\fP ()"
.br
.RI "TreeViewState\&.SetActiveNodeAction "
.ti -1c
.RI "void \fBRemoveSelectedNodeAction\fP ()"
.br
.RI "TreeViewState\&.RemoveSelectedNodeAction "
.ti -1c
.RI "void \fBMoveLeftAction\fP ()"
.br
.RI "TreeViewState\&.MoveLeftAction "
.ti -1c
.RI "void \fBMoveDownAction\fP ()"
.br
.RI "TreeViewState\&.MoveDownAction "
.ti -1c
.RI "void \fBMoveUpAction\fP ()"
.br
.RI "TreeViewState\&.MoveUpAction "
.ti -1c
.RI "void \fBMoveRightAction\fP ()"
.br
.RI "TreeViewState\&.MoveRightAction "
.ti -1c
.RI "void \fBMoveHomeAction\fP ()"
.br
.RI "TreeViewState\&.MoveHomeAction "
.ti -1c
.RI "void \fBMoveEndAction\fP ()"
.br
.RI "TreeViewState\&.MoveEndAction "
.ti -1c
.RI "void \fBLoadChildListAction\fP ()"
.br
.RI "TreeViewState\&.LoadChildListAction "
.in -1c
.SH "Detailed Description"
.PP 
\fBTreeViewState\fP 
.PP
Definition at line \fB20\fP of file \fBTreeViewStateTests\&.Actions\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "async Task Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.States\&.TreeViewStateActionsTests\&.AddChildNodeActionAsync ()"

.PP
AddChildNodeAction 
.PP
Definition at line \fB152\fP of file \fBTreeViewStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.States\&.TreeViewStateActionsTests\&.DisposeContainerAction ()"

.PP
TreeViewState\&.DisposeContainerAction 
.PP
Definition at line \fB50\fP of file \fBTreeViewStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.States\&.TreeViewStateActionsTests\&.LoadChildListAction ()"

.PP
TreeViewState\&.LoadChildListAction 
.PP
Definition at line \fB909\fP of file \fBTreeViewStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.States\&.TreeViewStateActionsTests\&.MoveDownAction ()"

.PP
TreeViewState\&.MoveDownAction 
.PP
Definition at line \fB475\fP of file \fBTreeViewStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.States\&.TreeViewStateActionsTests\&.MoveEndAction ()"

.PP
TreeViewState\&.MoveEndAction 
.PP
Definition at line \fB824\fP of file \fBTreeViewStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.States\&.TreeViewStateActionsTests\&.MoveHomeAction ()"

.PP
TreeViewState\&.MoveHomeAction 
.PP
Definition at line \fB739\fP of file \fBTreeViewStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.States\&.TreeViewStateActionsTests\&.MoveLeftAction ()"

.PP
TreeViewState\&.MoveLeftAction 
.PP
Definition at line \fB390\fP of file \fBTreeViewStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.States\&.TreeViewStateActionsTests\&.MoveRightAction ()"

.PP
TreeViewState\&.MoveRightAction 
.PP
Definition at line \fB645\fP of file \fBTreeViewStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.States\&.TreeViewStateActionsTests\&.MoveUpAction ()"

.PP
TreeViewState\&.MoveUpAction 
.PP
Definition at line \fB560\fP of file \fBTreeViewStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.States\&.TreeViewStateActionsTests\&.RegisterContainerAction ()"

.PP
TreeViewState\&.RegisterContainerAction 
.PP
Definition at line \fB26\fP of file \fBTreeViewStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.States\&.TreeViewStateActionsTests\&.RemoveSelectedNodeAction ()"

.PP
TreeViewState\&.RemoveSelectedNodeAction 
.PP
Definition at line \fB364\fP of file \fBTreeViewStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.States\&.TreeViewStateActionsTests\&.ReplaceContainerAction ()"

.PP
TreeViewState\&.ReplaceContainerAction 
.PP
Definition at line \fB126\fP of file \fBTreeViewStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.States\&.TreeViewStateActionsTests\&.ReRenderNodeAction ()"

.PP
TreeViewState\&.ReRenderNodeAction 
.PP
Definition at line \fB182\fP of file \fBTreeViewStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.States\&.TreeViewStateActionsTests\&.SetActiveNodeAction ()"

.PP
TreeViewState\&.SetActiveNodeAction 
.PP
Definition at line \fB208\fP of file \fBTreeViewStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.States\&.TreeViewStateActionsTests\&.TryGetContainerAction ()"

.PP
TreeViewState\&.TryGetContainerAction 
.PP
Definition at line \fB102\fP of file \fBTreeViewStateTests\&.Actions\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.States\&.TreeViewStateActionsTests\&.WithRootNodeActionAsync ()"

.PP
WithRootNodeAction 
.PP
Definition at line \fB74\fP of file \fBTreeViewStateTests\&.Actions\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
