.TH "Luthetus.Extensions.DotNet.Menus.Models.IDotNetMenuOptionsFactory" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.Menus.Models.IDotNetMenuOptionsFactory
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.Extensions\&.DotNet\&.Menus\&.Models\&.DotNetMenuOptionsFactory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMenuOptionRecord\fP \fBRemoveCSharpProjectReferenceFromSolution\fP (\fBTreeViewSolution\fP solutionNode, \fBTreeViewNamespacePath\fP projectNode, \fBITerminal\fP terminal, IDispatcher dispatcher, Func< Task > onAfterCompletion)"
.br
.ti -1c
.RI "\fBMenuOptionRecord\fP \fBAddProjectToProjectReference\fP (\fBTreeViewNamespacePath\fP projectReceivingReference, \fBITerminal\fP terminal, IDispatcher dispatcher, \fBIdeBackgroundTaskApi\fP ideBackgroundTaskApi, Func< Task > onAfterCompletion)"
.br
.ti -1c
.RI "\fBMenuOptionRecord\fP \fBRemoveProjectToProjectReference\fP (\fBTreeViewCSharpProjectToProjectReference\fP treeViewCSharpProjectToProjectReference, \fBITerminal\fP terminal, IDispatcher dispatcher, Func< Task > onAfterCompletion)"
.br
.ti -1c
.RI "\fBMenuOptionRecord\fP \fBMoveProjectToSolutionFolder\fP (\fBTreeViewSolution\fP treeViewSolution, \fBTreeViewNamespacePath\fP treeViewProjectToMove, \fBITerminal\fP terminal, IDispatcher dispatcher, Func< Task > onAfterCompletion)"
.br
.ti -1c
.RI "\fBMenuOptionRecord\fP \fBRemoveNuGetPackageReferenceFromProject\fP (\fBNamespacePath\fP modifyProjectNamespacePath, \fBTreeViewCSharpProjectNugetPackageReference\fP treeViewCSharpProjectNugetPackageReference, \fBITerminal\fP terminal, IDispatcher dispatcher, Func< Task > onAfterCompletion)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB12\fP of file \fBIDotNetMenuOptionsFactory\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBMenuOptionRecord\fP Luthetus\&.Extensions\&.DotNet\&.Menus\&.Models\&.IDotNetMenuOptionsFactory\&.AddProjectToProjectReference (\fBTreeViewNamespacePath\fP projectReceivingReference, \fBITerminal\fP terminal, IDispatcher dispatcher, \fBIdeBackgroundTaskApi\fP ideBackgroundTaskApi, Func< Task > onAfterCompletion)"

.PP
Implemented in \fBLuthetus\&.Extensions\&.DotNet\&.Menus\&.Models\&.DotNetMenuOptionsFactory\fP\&.
.SS "\fBMenuOptionRecord\fP Luthetus\&.Extensions\&.DotNet\&.Menus\&.Models\&.IDotNetMenuOptionsFactory\&.MoveProjectToSolutionFolder (\fBTreeViewSolution\fP treeViewSolution, \fBTreeViewNamespacePath\fP treeViewProjectToMove, \fBITerminal\fP terminal, IDispatcher dispatcher, Func< Task > onAfterCompletion)"

.PP
Implemented in \fBLuthetus\&.Extensions\&.DotNet\&.Menus\&.Models\&.DotNetMenuOptionsFactory\fP\&.
.SS "\fBMenuOptionRecord\fP Luthetus\&.Extensions\&.DotNet\&.Menus\&.Models\&.IDotNetMenuOptionsFactory\&.RemoveCSharpProjectReferenceFromSolution (\fBTreeViewSolution\fP solutionNode, \fBTreeViewNamespacePath\fP projectNode, \fBITerminal\fP terminal, IDispatcher dispatcher, Func< Task > onAfterCompletion)"

.PP
Implemented in \fBLuthetus\&.Extensions\&.DotNet\&.Menus\&.Models\&.DotNetMenuOptionsFactory\fP\&.
.SS "\fBMenuOptionRecord\fP Luthetus\&.Extensions\&.DotNet\&.Menus\&.Models\&.IDotNetMenuOptionsFactory\&.RemoveNuGetPackageReferenceFromProject (\fBNamespacePath\fP modifyProjectNamespacePath, \fBTreeViewCSharpProjectNugetPackageReference\fP treeViewCSharpProjectNugetPackageReference, \fBITerminal\fP terminal, IDispatcher dispatcher, Func< Task > onAfterCompletion)"

.PP
Implemented in \fBLuthetus\&.Extensions\&.DotNet\&.Menus\&.Models\&.DotNetMenuOptionsFactory\fP\&.
.SS "\fBMenuOptionRecord\fP Luthetus\&.Extensions\&.DotNet\&.Menus\&.Models\&.IDotNetMenuOptionsFactory\&.RemoveProjectToProjectReference (\fBTreeViewCSharpProjectToProjectReference\fP treeViewCSharpProjectToProjectReference, \fBITerminal\fP terminal, IDispatcher dispatcher, Func< Task > onAfterCompletion)"

.PP
Implemented in \fBLuthetus\&.Extensions\&.DotNet\&.Menus\&.Models\&.DotNetMenuOptionsFactory\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
