.TH "Luthetus.Ide.RazorLib.FileSystems.Models" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.FileSystems.Models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFileSystemIdeApi\fP"
.br
.ti -1c
.RI "class \fBFileTemplate\fP"
.br
.ti -1c
.RI "class \fBFileTemplateParameter\fP"
.br
.ti -1c
.RI "class \fBFileTemplateProvider\fP"
.br
.ti -1c
.RI "class \fBFileTemplateResult\fP"
.br
.ti -1c
.RI "class \fBHiddenFileFacts\fP"
.br
.ti -1c
.RI "interface \fBIFileTemplate\fP"
.br
.ti -1c
.RI "interface \fBIFileTemplateProvider\fP"
.br
.ti -1c
.RI "class \fBTreeViewAbsolutePath\fP"
.br
.ti -1c
.RI "class \fBTreeViewHelperAbsolutePathDirectory\fP"
.br
.ti -1c
.RI "class \fBUniqueFileFacts\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBFileTemplateKind\fP { \fBEmpty\fP, \fBCSharp\fP, \fBJavaScript\fP, \fBTypeScript\fP, \fBRazor\fP }"
.br
.RI "Use FileTemplateKind to search file templates by language\&. "
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBLuthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.FileTemplateKind\fP"

.PP
Use \fBFileTemplateKind\fP to search file templates by language\&. 
.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIEmpty \fP
.TP
\f(BICSharp \fP
.TP
\f(BIJavaScript \fP
.TP
\f(BITypeScript \fP
.TP
\f(BIRazor \fP
.PP
Definition at line \fB7\fP of file \fBFileTemplateKind\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
