.TH "Luthetus.CompilerServices.Xml.Html.SyntaxActors.HtmlSyntaxWalker" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.Xml.Html.SyntaxActors.HtmlSyntaxWalker
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.XmlSyntaxWalker\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBVisitAttributeNameNode\fP (\fBAttributeNameNode\fP node)"
.br
.ti -1c
.RI "override void \fBVisitAttributeValueNode\fP (\fBAttributeValueNode\fP node)"
.br
.ti -1c
.RI "override void \fBVisitInjectedLanguageFragmentNode\fP (\fBInjectedLanguageFragmentNode\fP node)"
.br
.ti -1c
.RI "override void \fBVisitTagNameNode\fP (\fBTagNameNode\fP node)"
.br
.ti -1c
.RI "override void \fBVisitCommentNode\fP (\fBCommentNode\fP node)"
.br
.ti -1c
.RI "override void \fBVisitTagOpeningNode\fP (\fBTagNode\fP node)"
.br
.ti -1c
.RI "override void \fBVisitTagClosingNode\fP (\fBTagNode\fP node)"
.br
.ti -1c
.RI "override void \fBVisitTagSelfClosingNode\fP (\fBTagNode\fP node)"
.br
.in -1c

Public Member Functions inherited from \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.XmlSyntaxWalker\fP
.in +1c
.ti -1c
.RI "virtual void \fBVisit\fP (\fBIHtmlSyntaxNode\fP node)"
.br
.ti -1c
.RI "virtual void \fBVisitAttributeNode\fP (\fBAttributeNode\fP node)"
.br
.ti -1c
.RI "virtual void \fBVisitTextNode\fP (\fBTextNode\fP node)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "List< \fBAttributeNameNode\fP > \fBAttributeNameNodes\fP = new()\fR [get]\fP"
.br
.ti -1c
.RI "List< \fBAttributeValueNode\fP > \fBAttributeValueNodes\fP = new()\fR [get]\fP"
.br
.ti -1c
.RI "List< \fBInjectedLanguageFragmentNode\fP > \fBInjectedLanguageFragmentNodes\fP = new()\fR [get]\fP"
.br
.ti -1c
.RI "List< \fBTagNameNode\fP > \fBTagNameNodes\fP = new()\fR [get]\fP"
.br
.ti -1c
.RI "List< \fBCommentNode\fP > \fBCommentNodes\fP = new()\fR [get]\fP"
.br
.ti -1c
.RI "List< \fBTagNode\fP > \fBTagOpeningNodes\fP = new()\fR [get]\fP"
.br
.ti -1c
.RI "List< \fBTagNode\fP > \fBTagClosingNodes\fP = new()\fR [get]\fP"
.br
.ti -1c
.RI "List< \fBTagNode\fP > \fBTagSelfClosingNodes\fP = new()\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBHtmlSyntaxWalker\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.HtmlSyntaxWalker\&.VisitAttributeNameNode (\fBAttributeNameNode\fP node)\fR [virtual]\fP"

.PP
Reimplemented from \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.XmlSyntaxWalker\fP\&.
.PP
Definition at line \fB16\fP of file \fBHtmlSyntaxWalker\&.cs\fP\&.
.SS "override void Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.HtmlSyntaxWalker\&.VisitAttributeValueNode (\fBAttributeValueNode\fP node)\fR [virtual]\fP"

.PP
Reimplemented from \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.XmlSyntaxWalker\fP\&.
.PP
Definition at line \fB21\fP of file \fBHtmlSyntaxWalker\&.cs\fP\&.
.SS "override void Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.HtmlSyntaxWalker\&.VisitCommentNode (\fBCommentNode\fP node)\fR [virtual]\fP"

.PP
Reimplemented from \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.XmlSyntaxWalker\fP\&.
.PP
Definition at line \fB36\fP of file \fBHtmlSyntaxWalker\&.cs\fP\&.
.SS "override void Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.HtmlSyntaxWalker\&.VisitInjectedLanguageFragmentNode (\fBInjectedLanguageFragmentNode\fP node)\fR [virtual]\fP"

.PP
Reimplemented from \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.XmlSyntaxWalker\fP\&.
.PP
Definition at line \fB26\fP of file \fBHtmlSyntaxWalker\&.cs\fP\&.
.SS "override void Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.HtmlSyntaxWalker\&.VisitTagClosingNode (\fBTagNode\fP node)\fR [virtual]\fP"

.PP
Reimplemented from \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.XmlSyntaxWalker\fP\&.
.PP
Definition at line \fB46\fP of file \fBHtmlSyntaxWalker\&.cs\fP\&.
.SS "override void Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.HtmlSyntaxWalker\&.VisitTagNameNode (\fBTagNameNode\fP node)\fR [virtual]\fP"

.PP
Reimplemented from \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.XmlSyntaxWalker\fP\&.
.PP
Definition at line \fB31\fP of file \fBHtmlSyntaxWalker\&.cs\fP\&.
.SS "override void Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.HtmlSyntaxWalker\&.VisitTagOpeningNode (\fBTagNode\fP node)\fR [virtual]\fP"

.PP
Reimplemented from \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.XmlSyntaxWalker\fP\&.
.PP
Definition at line \fB41\fP of file \fBHtmlSyntaxWalker\&.cs\fP\&.
.SS "override void Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.HtmlSyntaxWalker\&.VisitTagSelfClosingNode (\fBTagNode\fP node)\fR [virtual]\fP"

.PP
Reimplemented from \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.XmlSyntaxWalker\fP\&.
.PP
Definition at line \fB51\fP of file \fBHtmlSyntaxWalker\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "List<\fBAttributeNameNode\fP> Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.HtmlSyntaxWalker\&.AttributeNameNodes = new()\fR [get]\fP"

.PP
Definition at line \fB7\fP of file \fBHtmlSyntaxWalker\&.cs\fP\&.
.SS "List<\fBAttributeValueNode\fP> Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.HtmlSyntaxWalker\&.AttributeValueNodes = new()\fR [get]\fP"

.PP
Definition at line \fB8\fP of file \fBHtmlSyntaxWalker\&.cs\fP\&.
.SS "List<\fBCommentNode\fP> Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.HtmlSyntaxWalker\&.CommentNodes = new()\fR [get]\fP"

.PP
Definition at line \fB11\fP of file \fBHtmlSyntaxWalker\&.cs\fP\&.
.SS "List<\fBInjectedLanguageFragmentNode\fP> Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.HtmlSyntaxWalker\&.InjectedLanguageFragmentNodes = new()\fR [get]\fP"

.PP
Definition at line \fB9\fP of file \fBHtmlSyntaxWalker\&.cs\fP\&.
.SS "List<\fBTagNode\fP> Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.HtmlSyntaxWalker\&.TagClosingNodes = new()\fR [get]\fP"

.PP
Definition at line \fB13\fP of file \fBHtmlSyntaxWalker\&.cs\fP\&.
.SS "List<\fBTagNameNode\fP> Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.HtmlSyntaxWalker\&.TagNameNodes = new()\fR [get]\fP"

.PP
Definition at line \fB10\fP of file \fBHtmlSyntaxWalker\&.cs\fP\&.
.SS "List<\fBTagNode\fP> Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.HtmlSyntaxWalker\&.TagOpeningNodes = new()\fR [get]\fP"

.PP
Definition at line \fB12\fP of file \fBHtmlSyntaxWalker\&.cs\fP\&.
.SS "List<\fBTagNode\fP> Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.HtmlSyntaxWalker\&.TagSelfClosingNodes = new()\fR [get]\fP"

.PP
Definition at line \fB14\fP of file \fBHtmlSyntaxWalker\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
