.TH "Luthetus.Common.RazorLib.Notifications.Models.NotificationService" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Notifications.Models.NotificationService
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Common\&.RazorLib\&.Notifications\&.Models\&.INotificationService\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNotificationService\fP (IDispatcher dispatcher, IState< \fBNotificationState\fP > notificationState)"
.br
.ti -1c
.RI "void \fBRegisterNotificationRecord\fP (\fBINotification\fP notification)"
.br
.ti -1c
.RI "void \fBDisposeNotificationRecord\fP (Key< \fBIDynamicViewModel\fP > dynamicViewModelKey)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IState< \fBNotificationState\fP > \fBNotificationStateWrap\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBNotificationService\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Common\&.RazorLib\&.Notifications\&.Models\&.NotificationService\&.NotificationService (IDispatcher dispatcher, IState< \fBNotificationState\fP > notificationState)"

.PP
Definition at line \fB12\fP of file \fBNotificationService\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.RazorLib\&.Notifications\&.Models\&.NotificationService\&.DisposeNotificationRecord (Key< \fBIDynamicViewModel\fP > dynamicViewModelKey)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.Notifications\&.Models\&.INotificationService\fP\&.
.PP
Definition at line \fB27\fP of file \fBNotificationService\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.Notifications\&.Models\&.NotificationService\&.RegisterNotificationRecord (\fBINotification\fP notification)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.Notifications\&.Models\&.INotificationService\fP\&.
.PP
Definition at line \fB22\fP of file \fBNotificationService\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "IState<\fBNotificationState\fP> Luthetus\&.Common\&.RazorLib\&.Notifications\&.Models\&.NotificationService\&.NotificationStateWrap\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.Notifications\&.Models\&.INotificationService\fP\&.
.PP
Definition at line \fB20\fP of file \fBNotificationService\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
