.TH "Luthetus.Common.RazorLib.Options.Models.IAppOptionsService" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Options.Models.IAppOptionsService
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetActiveThemeRecordKey\fP (Key< \fBThemeRecord\fP > themeKey, bool updateStorage=true)"
.br
.ti -1c
.RI "void \fBSetTheme\fP (\fBThemeRecord\fP theme, bool updateStorage=true)"
.br
.ti -1c
.RI "void \fBSetFontFamily\fP (string? fontFamily, bool updateStorage=true)"
.br
.ti -1c
.RI "void \fBSetFontSize\fP (int fontSizeInPixels, bool updateStorage=true)"
.br
.ti -1c
.RI "void \fBSetResizeHandleWidth\fP (int resizeHandleWidthInPixels, bool updateStorage=true)"
.br
.ti -1c
.RI "void \fBSetResizeHandleHeight\fP (int resizeHandleHeightInPixels, bool updateStorage=true)"
.br
.ti -1c
.RI "void \fBSetIconSize\fP (int iconSizeInPixels, bool updateStorage=true)"
.br
.ti -1c
.RI "Task \fBSetFromLocalStorageAsync\fP ()"
.br
.ti -1c
.RI "void \fBWriteToStorage\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBStorageKey\fP\fR [get]\fP"
.br
.RI "This is used when interacting with the \fBIStorageService\fP to set and get data\&. "
.ti -1c
.RI "IState< \fBAppOptionsState\fP > \fBAppOptionsStateWrap\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBThemeCssClassString\fP\fR [get]\fP"
.br
.ti -1c
.RI "string? \fBFontFamilyCssStyleString\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBFontSizeCssStyleString\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBColorSchemeCssStyleString\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBShowPanelTitles\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBShowPanelTitlesCssClass\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBIAppOptionsService\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\&.SetActiveThemeRecordKey (Key< \fBThemeRecord\fP > themeKey, bool updateStorage = \fRtrue\fP)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\&.SetFontFamily (string? fontFamily, bool updateStorage = \fRtrue\fP)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\&.SetFontSize (int fontSizeInPixels, bool updateStorage = \fRtrue\fP)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\fP\&.
.SS "Task Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\&.SetFromLocalStorageAsync ()"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\&.SetIconSize (int iconSizeInPixels, bool updateStorage = \fRtrue\fP)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\&.SetResizeHandleHeight (int resizeHandleHeightInPixels, bool updateStorage = \fRtrue\fP)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\&.SetResizeHandleWidth (int resizeHandleWidthInPixels, bool updateStorage = \fRtrue\fP)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\&.SetTheme (\fBThemeRecord\fP theme, bool updateStorage = \fRtrue\fP)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\&.WriteToStorage ()"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\fP\&.
.SH "Property Documentation"
.PP 
.SS "IState<\fBAppOptionsState\fP> Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\&.AppOptionsStateWrap\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\fP\&.
.PP
Definition at line \fB15\fP of file \fBIAppOptionsService\&.cs\fP\&.
.SS "string Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\&.ColorSchemeCssStyleString\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\fP\&.
.PP
Definition at line \fB19\fP of file \fBIAppOptionsService\&.cs\fP\&.
.SS "string? Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\&.FontFamilyCssStyleString\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\fP\&.
.PP
Definition at line \fB17\fP of file \fBIAppOptionsService\&.cs\fP\&.
.SS "string Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\&.FontSizeCssStyleString\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\fP\&.
.PP
Definition at line \fB18\fP of file \fBIAppOptionsService\&.cs\fP\&.
.SS "bool Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\&.ShowPanelTitles\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\fP\&.
.PP
Definition at line \fB20\fP of file \fBIAppOptionsService\&.cs\fP\&.
.SS "string Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\&.ShowPanelTitlesCssClass\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\fP\&.
.PP
Definition at line \fB21\fP of file \fBIAppOptionsService\&.cs\fP\&.
.SS "string Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\&.StorageKey\fR [get]\fP"

.PP
This is used when interacting with the \fBIStorageService\fP to set and get data\&. 
.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\fP\&.
.PP
Definition at line \fB14\fP of file \fBIAppOptionsService\&.cs\fP\&.
.SS "string Luthetus\&.Common\&.RazorLib\&.Options\&.Models\&.IAppOptionsService\&.ThemeCssClassString\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Options\&.Models\&.AppOptionsService\fP\&.
.PP
Definition at line \fB16\fP of file \fBIAppOptionsService\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
