.TH "Luthetus.Ide.RazorLib.Commands.CommandFactory" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.Commands.CommandFactory
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Ide\&.RazorLib\&.Commands\&.ICommandFactory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommandFactory\fP (\fBITextEditorService\fP textEditorService, \fBITreeViewService\fP treeViewService, \fBIEnvironmentProvider\fP environmentProvider, IState< \fBPanelState\fP > panelStateWrap, IState< ContextState > contextStateWrap, IState< \fBContextSwitchState\fP > contextSwitchStateWrap, IDispatcher dispatcher, IJSRuntime jsRuntime)"
.br
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBIDialog\fP? \fBCodeSearchDialog\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB30\fP of file \fBCommandFactory\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Ide\&.RazorLib\&.Commands\&.CommandFactory\&.CommandFactory (\fBITextEditorService\fP textEditorService, \fBITreeViewService\fP treeViewService, \fBIEnvironmentProvider\fP environmentProvider, IState< \fBPanelState\fP > panelStateWrap, IState< ContextState > contextStateWrap, IState< \fBContextSwitchState\fP > contextSwitchStateWrap, IDispatcher dispatcher, IJSRuntime jsRuntime)"

.PP
Definition at line \fB41\fP of file \fBCommandFactory\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Ide\&.RazorLib\&.Commands\&.CommandFactory\&.Initialize ()"

.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.Commands\&.ICommandFactory\fP\&.
.PP
Definition at line \fB71\fP of file \fBCommandFactory\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBIDialog\fP? Luthetus\&.Ide\&.RazorLib\&.Commands\&.CommandFactory\&.CodeSearchDialog\fR [get]\fP, \fR [set]\fP"

.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.Commands\&.ICommandFactory\fP\&.
.PP
Definition at line \fB66\fP of file \fBCommandFactory\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
