.TH "Luthetus.Extensions.DotNet.DotNetSolutions.Displays.SolutionVisualizationDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.DotNetSolutions.Displays.SolutionVisualizationDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase, and IDisposable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInitialized\fP ()"
.br
.ti -1c
.RI "override async Task \fBOnAfterRenderAsync\fP (bool firstRender)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBIDialog\fP \fBDialog\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "Guid \fBIdSalt\fP = Guid\&.NewGuid()\fR [get]\fP"
.br
.ti -1c
.RI "string \fBDivHtmlElementId\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBSvgHtmlElementId\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB22\fP of file \fBSolutionVisualizationDisplay\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Displays\&.SolutionVisualizationDisplay\&.Dispose ()"

.PP
Definition at line \fB186\fP of file \fBSolutionVisualizationDisplay\&.razor\&.cs\fP\&.
.SS "override async Task Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Displays\&.SolutionVisualizationDisplay\&.OnAfterRenderAsync (bool firstRender)\fR [protected]\fP"

.PP
Definition at line \fB68\fP of file \fBSolutionVisualizationDisplay\&.razor\&.cs\fP\&.
.SS "override void Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Displays\&.SolutionVisualizationDisplay\&.OnInitialized ()\fR [protected]\fP"

.PP
Definition at line \fB54\fP of file \fBSolutionVisualizationDisplay\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBIDialog\fP Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Displays\&.SolutionVisualizationDisplay\&.Dialog\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB36\fP of file \fBSolutionVisualizationDisplay\&.razor\&.cs\fP\&.
.SS "string Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Displays\&.SolutionVisualizationDisplay\&.DivHtmlElementId\fR [get]\fP"

.PP
Definition at line \fB50\fP of file \fBSolutionVisualizationDisplay\&.razor\&.cs\fP\&.
.SS "Guid Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Displays\&.SolutionVisualizationDisplay\&.IdSalt = Guid\&.NewGuid()\fR [get]\fP"

.PP
Definition at line \fB48\fP of file \fBSolutionVisualizationDisplay\&.razor\&.cs\fP\&.
.SS "string Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Displays\&.SolutionVisualizationDisplay\&.SvgHtmlElementId\fR [get]\fP"

.PP
Definition at line \fB51\fP of file \fBSolutionVisualizationDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
