.TH "Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursorModifier" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursorModifier
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextEditorCursorModifier\fP (\fBTextEditorCursor\fP cursor)"
.br
.ti -1c
.RI "\fBTextEditorCursor\fP \fBToCursor\fP ()"
.br
.ti -1c
.RI "void \fBSetColumnIndexAndPreferred\fP (int columnIndex)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBLineIndex\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBColumnIndex\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBPreferredColumnIndex\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsPrimaryCursor\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int? \fBSelectionAnchorPositionIndex\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBSelectionEndingPositionIndex\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "Key< \fBTextEditorCursor\fP > \fBKey\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBTextEditorCursorModifier\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.Cursors\&.Models\&.TextEditorCursorModifier\&.TextEditorCursorModifier (\fBTextEditorCursor\fP cursor)"

.PP
Definition at line \fB7\fP of file \fBTextEditorCursorModifier\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Cursors\&.Models\&.TextEditorCursorModifier\&.SetColumnIndexAndPreferred (int columnIndex)"

.PP
Definition at line \fB39\fP of file \fBTextEditorCursorModifier\&.cs\fP\&.
.SS "\fBTextEditorCursor\fP Luthetus\&.TextEditor\&.RazorLib\&.Cursors\&.Models\&.TextEditorCursorModifier\&.ToCursor ()"

.PP
Definition at line \fB26\fP of file \fBTextEditorCursorModifier\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Luthetus\&.TextEditor\&.RazorLib\&.Cursors\&.Models\&.TextEditorCursorModifier\&.ColumnIndex\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB19\fP of file \fBTextEditorCursorModifier\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.Cursors\&.Models\&.TextEditorCursorModifier\&.IsPrimaryCursor\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB21\fP of file \fBTextEditorCursorModifier\&.cs\fP\&.
.SS "Key<\fBTextEditorCursor\fP> Luthetus\&.TextEditor\&.RazorLib\&.Cursors\&.Models\&.TextEditorCursorModifier\&.Key\fR [get]\fP"

.PP
Definition at line \fB24\fP of file \fBTextEditorCursorModifier\&.cs\fP\&.
.SS "int Luthetus\&.TextEditor\&.RazorLib\&.Cursors\&.Models\&.TextEditorCursorModifier\&.LineIndex\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB18\fP of file \fBTextEditorCursorModifier\&.cs\fP\&.
.SS "int Luthetus\&.TextEditor\&.RazorLib\&.Cursors\&.Models\&.TextEditorCursorModifier\&.PreferredColumnIndex\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB20\fP of file \fBTextEditorCursorModifier\&.cs\fP\&.
.SS "int? Luthetus\&.TextEditor\&.RazorLib\&.Cursors\&.Models\&.TextEditorCursorModifier\&.SelectionAnchorPositionIndex\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB22\fP of file \fBTextEditorCursorModifier\&.cs\fP\&.
.SS "int Luthetus\&.TextEditor\&.RazorLib\&.Cursors\&.Models\&.TextEditorCursorModifier\&.SelectionEndingPositionIndex\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB23\fP of file \fBTextEditorCursorModifier\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
