.TH "Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionArgumentEntryNode" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionArgumentEntryNode \- Used when defining a function\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.ISyntaxNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFunctionArgumentEntryNode\fP (\fBVariableDeclarationNode\fP variableDeclarationNode, \fBISyntaxToken\fP? optionalCompileTimeConstantToken, bool isOptional, bool hasParamsKeyword, bool hasOutKeyword, bool hasInKeyword, bool hasRefKeyword)"
.br
.ti -1c
.RI "\fBISyntax\fP[] \fBGetChildList\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "VariableDeclarationNode \fBVariableDeclarationNode\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBISyntaxToken\fP? \fBOptionalCompileTimeConstantToken\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsOptional\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBHasParamsKeyword\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBHasOutKeyword\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBHasInKeyword\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBHasRefKeyword\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsFabricated\fP\fR [get]\fP"
.br
.RI "\fBIsFabricated\fP refers to when the ParserSession expected a node to be valid, but it wasn't\&.
.br

.br
For example, a function invocation on an undefined function will construct a BoundFunctionInvocationNode with \fBIsFabricated\fP set to true\&. "
.ti -1c
.RI "\fBSyntaxKind\fP \fBSyntaxKind\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Used when defining a function\&. 
.PP
Definition at line \fB8\fP of file \fBFunctionArgumentEntryNode\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.FunctionArgumentEntryNode\&.FunctionArgumentEntryNode (\fBVariableDeclarationNode\fP variableDeclarationNode, \fBISyntaxToken\fP? optionalCompileTimeConstantToken, bool isOptional, bool hasParamsKeyword, bool hasOutKeyword, bool hasInKeyword, bool hasRefKeyword)"

.PP
Definition at line \fB10\fP of file \fBFunctionArgumentEntryNode\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBISyntax\fP[] Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.FunctionArgumentEntryNode\&.GetChildList ()"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.ISyntaxNode\fP\&.
.PP
Definition at line \fB42\fP of file \fBFunctionArgumentEntryNode\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.FunctionArgumentEntryNode\&.HasInKeyword\fR [get]\fP"

.PP
Definition at line \fB36\fP of file \fBFunctionArgumentEntryNode\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.FunctionArgumentEntryNode\&.HasOutKeyword\fR [get]\fP"

.PP
Definition at line \fB35\fP of file \fBFunctionArgumentEntryNode\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.FunctionArgumentEntryNode\&.HasParamsKeyword\fR [get]\fP"

.PP
Definition at line \fB34\fP of file \fBFunctionArgumentEntryNode\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.FunctionArgumentEntryNode\&.HasRefKeyword\fR [get]\fP"

.PP
Definition at line \fB37\fP of file \fBFunctionArgumentEntryNode\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.FunctionArgumentEntryNode\&.IsFabricated\fR [get]\fP"

.PP
\fBIsFabricated\fP refers to when the ParserSession expected a node to be valid, but it wasn't\&.
.br

.br
For example, a function invocation on an undefined function will construct a BoundFunctionInvocationNode with \fBIsFabricated\fP set to true\&. 
.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.ISyntax\fP\&.
.PP
Definition at line \fB39\fP of file \fBFunctionArgumentEntryNode\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.FunctionArgumentEntryNode\&.IsOptional\fR [get]\fP"

.PP
Definition at line \fB33\fP of file \fBFunctionArgumentEntryNode\&.cs\fP\&.
.SS "\fBISyntaxToken\fP? Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.FunctionArgumentEntryNode\&.OptionalCompileTimeConstantToken\fR [get]\fP"

.PP
Definition at line \fB32\fP of file \fBFunctionArgumentEntryNode\&.cs\fP\&.
.SS "\fBSyntaxKind\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.FunctionArgumentEntryNode\&.SyntaxKind\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.ISyntax\fP\&.
.PP
Definition at line \fB40\fP of file \fBFunctionArgumentEntryNode\&.cs\fP\&.
.SS "VariableDeclarationNode Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.FunctionArgumentEntryNode\&.VariableDeclarationNode\fR [get]\fP"

.PP
Definition at line \fB31\fP of file \fBFunctionArgumentEntryNode\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
