.TH "Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.ITextEditorRenderBatch" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.ITextEditorRenderBatch
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.TextEditorRenderBatchValidated\fP\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBDEFAULT_FONT_FAMILY\fP = 'monospace'"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBTextEditorModel\fP? \fBModel\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBTextEditorViewModel\fP? \fBViewModel\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBTextEditorOptions\fP? \fBOptions\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBFontFamily\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBFontSizeInPixels\fP\fR [get]\fP"
.br
.ti -1c
.RI "ViewModelDisplayOptions \fBViewModelDisplayOptions\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBTextEditorComponentData\fP \fBComponentData\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBFontFamilyCssStyle\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBFontSizeInPixelsCssStyle\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBHeightCssStyle\fP\fR [get]\fP"
.br
.ti -1c
.RI "double \fBGutterWidthInPixels\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsValid\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBITextEditorRenderBatch\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ITextEditorRenderBatch\&.DEFAULT_FONT_FAMILY = 'monospace'\fR [static]\fP"

.PP
Definition at line \fB7\fP of file \fBITextEditorRenderBatch\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBTextEditorComponentData\fP Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ITextEditorRenderBatch\&.ComponentData\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.TextEditorRenderBatchValidated\fP\&.
.PP
Definition at line \fB15\fP of file \fBITextEditorRenderBatch\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ITextEditorRenderBatch\&.FontFamily\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.TextEditorRenderBatchValidated\fP\&.
.PP
Definition at line \fB12\fP of file \fBITextEditorRenderBatch\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ITextEditorRenderBatch\&.FontFamilyCssStyle\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.TextEditorRenderBatchValidated\fP\&.
.PP
Definition at line \fB16\fP of file \fBITextEditorRenderBatch\&.cs\fP\&.
.SS "int Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ITextEditorRenderBatch\&.FontSizeInPixels\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.TextEditorRenderBatchValidated\fP\&.
.PP
Definition at line \fB13\fP of file \fBITextEditorRenderBatch\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ITextEditorRenderBatch\&.FontSizeInPixelsCssStyle\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.TextEditorRenderBatchValidated\fP\&.
.PP
Definition at line \fB17\fP of file \fBITextEditorRenderBatch\&.cs\fP\&.
.SS "double Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ITextEditorRenderBatch\&.GutterWidthInPixels\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.TextEditorRenderBatchValidated\fP\&.
.PP
Definition at line \fB19\fP of file \fBITextEditorRenderBatch\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ITextEditorRenderBatch\&.HeightCssStyle\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.TextEditorRenderBatchValidated\fP\&.
.PP
Definition at line \fB18\fP of file \fBITextEditorRenderBatch\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ITextEditorRenderBatch\&.IsValid\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.TextEditorRenderBatchValidated\fP\&.
.PP
Definition at line \fB20\fP of file \fBITextEditorRenderBatch\&.cs\fP\&.
.SS "\fBTextEditorModel\fP? Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ITextEditorRenderBatch\&.Model\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.TextEditorRenderBatchValidated\fP\&.
.PP
Definition at line \fB9\fP of file \fBITextEditorRenderBatch\&.cs\fP\&.
.SS "\fBTextEditorOptions\fP? Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ITextEditorRenderBatch\&.Options\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.TextEditorRenderBatchValidated\fP\&.
.PP
Definition at line \fB11\fP of file \fBITextEditorRenderBatch\&.cs\fP\&.
.SS "\fBTextEditorViewModel\fP? Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ITextEditorRenderBatch\&.ViewModel\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.TextEditorRenderBatchValidated\fP\&.
.PP
Definition at line \fB10\fP of file \fBITextEditorRenderBatch\&.cs\fP\&.
.SS "ViewModelDisplayOptions Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ITextEditorRenderBatch\&.ViewModelDisplayOptions\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.TextEditorRenderBatchValidated\fP\&.
.PP
Definition at line \fB14\fP of file \fBITextEditorRenderBatch\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
