.TH "Luthetus.Extensions.DotNet.CompilerServices.Models.CompilerServiceExplorerModel" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.CompilerServices.Models.CompilerServiceExplorerModel
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBIAbsolutePath\fP? \fBAbsolutePath\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsLoadingCompilerServiceExplorer\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBCompilerServiceExplorerModel\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBIAbsolutePath\fP? Luthetus\&.Extensions\&.DotNet\&.CompilerServices\&.Models\&.CompilerServiceExplorerModel\&.AbsolutePath\fR [get]\fP"

.PP
Definition at line \fB7\fP of file \fBCompilerServiceExplorerModel\&.cs\fP\&.
.SS "bool Luthetus\&.Extensions\&.DotNet\&.CompilerServices\&.Models\&.CompilerServiceExplorerModel\&.IsLoadingCompilerServiceExplorer\fR [get]\fP"

.PP
Definition at line \fB8\fP of file \fBCompilerServiceExplorerModel\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
