.TH "Luthetus.Common.RazorLib.WatchWindows.Displays.TreeViewInterfaceImplementationDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.WatchWindows.Displays.TreeViewInterfaceImplementationDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "TreeViewInterfaceImplementation \fBTreeViewInterfaceImplementation\fP = null!\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBTreeViewInterfaceImplementationDisplay\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "TreeViewInterfaceImplementation Luthetus\&.Common\&.RazorLib\&.WatchWindows\&.Displays\&.TreeViewInterfaceImplementationDisplay\&.TreeViewInterfaceImplementation = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB14\fP of file \fBTreeViewInterfaceImplementationDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
