.TH "Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxObjects.GenericDeliminationExtendedSyntax" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxObjects.GenericDeliminationExtendedSyntax
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.IGenericSyntax\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGenericDeliminationExtendedSyntax\fP (\fBTextEditorTextSpan\fP textSpan)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBTextEditorTextSpan\fP \fBTextSpan\fP\fR [get]\fP"
.br
.ti -1c
.RI "ImmutableArray< \fBIGenericSyntax\fP > \fBChildList\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBGenericSyntaxKind\fP \fBGenericSyntaxKind\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBGenericDeliminationExtendedSyntax\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericDeliminationExtendedSyntax\&.GenericDeliminationExtendedSyntax (\fBTextEditorTextSpan\fP textSpan)"

.PP
Definition at line \fB9\fP of file \fBGenericDeliminationExtendedSyntax\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "ImmutableArray<\fBIGenericSyntax\fP> Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericDeliminationExtendedSyntax\&.ChildList\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.IGenericSyntax\fP\&.
.PP
Definition at line \fB15\fP of file \fBGenericDeliminationExtendedSyntax\&.cs\fP\&.
.SS "\fBGenericSyntaxKind\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericDeliminationExtendedSyntax\&.GenericSyntaxKind\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.IGenericSyntax\fP\&.
.PP
Definition at line \fB16\fP of file \fBGenericDeliminationExtendedSyntax\&.cs\fP\&.
.SS "\fBTextEditorTextSpan\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericDeliminationExtendedSyntax\&.TextSpan\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.IGenericSyntax\fP\&.
.PP
Definition at line \fB14\fP of file \fBGenericDeliminationExtendedSyntax\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
