.TH "Luthetus.Common.RazorLib.Contexts.Models" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Contexts.Models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBContextFacts\fP"
.br
.ti -1c
.RI "class \fBContextHelper\fP"
.br
.ti -1c
.RI "class \fBContextSwitchGroup\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "record \fBContextHeirarchy\fP (ImmutableArray< Key< \fBContextRecord\fP > > KeyList)"
.br
.ti -1c
.RI "record \fBContextRecord\fP (Key< ContextRecord > ContextKey, string DisplayNameFriendly, string ContextNameInternal, \fBIKeymap\fP \fBKeymap\fP)"
.br
.ti -1c
.RI "record \fBInspectableContext\fP (\fBContextHeirarchy\fP \fBContextHeirarchy\fP, \fBMeasuredHtmlElementDimensions\fP TargetContextRecordMeasuredHtmlElementDimensions)"
.br
.RI "This logic relates to rendering a blue overlay during the 'inspect element like' action\&. Each InspectContextRecordEntry relates to a single ContextRecord\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "record Luthetus\&.Common\&.RazorLib\&.Contexts\&.Models\&.ContextHeirarchy (ImmutableArray< Key< \fBContextRecord\fP > > KeyList)"

.PP
\fBParameters\fP
.RS 4
\fIKeyList\fP Contains the NearestAncestorKey at index 0, then the immediate parent of target at index 1\&. This pattern follows for 'parent of parent' until there is no parent\&. Each parent getting the next index in list to store their key\&. 
.RE
.PP
The key of the nearest-ancestor \fBDisplays\&.ContextBoundary\fP ContextRecord in question
.PP
Definition at line \fB11\fP of file \fBContextHeirarchy\&.cs\fP\&.
.SS "record Luthetus\&.Common\&.RazorLib\&.Contexts\&.Models\&.ContextRecord (Key< ContextRecord > ContextKey, string DisplayNameFriendly, string ContextNameInternal, \fBIKeymap\fP Keymap)"

.PP
Definition at line \fB6\fP of file \fBContextRecord\&.cs\fP\&.
.SS "record Luthetus\&.Common\&.RazorLib\&.Contexts\&.Models\&.InspectableContext (\fBContextHeirarchy\fP ContextHeirarchy, \fBMeasuredHtmlElementDimensions\fP TargetContextRecordMeasuredHtmlElementDimensions)"

.PP
This logic relates to rendering a blue overlay during the 'inspect element like' action\&. Each InspectContextRecordEntry relates to a single ContextRecord\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
