.TH "Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.VirtualizationDriver" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.VirtualizationDriver
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBVirtualizationDriver\fP (\fBTextEditorViewModelDisplay\fP textEditorViewModelDisplay, bool useHorizontalVirtualization, bool useVerticalVirtualization)"
.br
.ti -1c
.RI "RenderFragment \fBGetRenderFragment\fP (\fBTextEditorRenderBatchValidated\fP renderBatch)"
.br
.ti -1c
.RI "string \fBGetStyleCssString\fP (\fBVirtualizationBoundary\fP virtualizationBoundary)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly \fBTextEditorViewModelDisplay\fP \fB_root\fP"
.br
.ti -1c
.RI "\fBTextEditorRenderBatchValidated\fP \fB_renderBatch\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBUseHorizontalVirtualization\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBUseVerticalVirtualization\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBVirtualizationDriver\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.VirtualizationDriver\&.VirtualizationDriver (\fBTextEditorViewModelDisplay\fP textEditorViewModelDisplay, bool useHorizontalVirtualization, bool useVerticalVirtualization)"

.PP
Definition at line \fB13\fP of file \fBVirtualizationDriver\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "RenderFragment Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.VirtualizationDriver\&.GetRenderFragment (\fBTextEditorRenderBatchValidated\fP renderBatch)"

.PP
Definition at line \fB26\fP of file \fBVirtualizationDriver\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.VirtualizationDriver\&.GetStyleCssString (\fBVirtualizationBoundary\fP virtualizationBoundary)"

.PP
Definition at line \fB36\fP of file \fBVirtualizationDriver\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBTextEditorRenderBatchValidated\fP Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.VirtualizationDriver\&._renderBatch"

.PP
Definition at line \fB24\fP of file \fBVirtualizationDriver\&.cs\fP\&.
.SS "readonly \fBTextEditorViewModelDisplay\fP Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.VirtualizationDriver\&._root"

.PP
Definition at line \fB11\fP of file \fBVirtualizationDriver\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.VirtualizationDriver\&.UseHorizontalVirtualization\fR [get]\fP"

.PP
Definition at line \fB33\fP of file \fBVirtualizationDriver\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.VirtualizationDriver\&.UseVerticalVirtualization\fR [get]\fP"

.PP
Definition at line \fB34\fP of file \fBVirtualizationDriver\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
