.TH "Luthetus.Extensions.DotNet.DotNetSolutions.Displays.SolutionExplorerDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.DotNetSolutions.Displays.SolutionExplorerDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits FluxorComponent\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInitialized\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB27\fP of file \fBSolutionExplorerDisplay\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Displays\&.SolutionExplorerDisplay\&.OnInitialized ()\fR [protected]\fP"

.PP
Definition at line \fB61\fP of file \fBSolutionExplorerDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
