.TH "Luthetus.Common.RazorLib.Outlines.Displays.OutlineInitializer" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Outlines.Displays.OutlineInitializer
.SH SYNOPSIS
.br
.PP
.PP
Inherits FluxorComponent\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBGetStyleCssLeft\fP (\fBOutlineState\fP localOutlineState)"
.br
.ti -1c
.RI "string \fBGetStyleCssRight\fP (\fBOutlineState\fP localOutlineState)"
.br
.ti -1c
.RI "string \fBGetStyleCssTop\fP (\fBOutlineState\fP localOutlineState)"
.br
.ti -1c
.RI "string \fBGetStyleCssBottom\fP (\fBOutlineState\fP localOutlineState)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const double \fBOUTLINE_THICKNESS\fP = 4"
.br
.RI "The unit of measurement is Pixels (px)\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IState< \fBOutlineState\fP > \fBOutlineStateWrap\fP = null!\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBOutlineInitializer\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "string Luthetus\&.Common\&.RazorLib\&.Outlines\&.Displays\&.OutlineInitializer\&.GetStyleCssBottom (\fBOutlineState\fP localOutlineState)"

.PP
Definition at line \fB80\fP of file \fBOutlineInitializer\&.razor\&.cs\fP\&.
.SS "string Luthetus\&.Common\&.RazorLib\&.Outlines\&.Displays\&.OutlineInitializer\&.GetStyleCssLeft (\fBOutlineState\fP localOutlineState)"

.PP
Definition at line \fB18\fP of file \fBOutlineInitializer\&.razor\&.cs\fP\&.
.SS "string Luthetus\&.Common\&.RazorLib\&.Outlines\&.Displays\&.OutlineInitializer\&.GetStyleCssRight (\fBOutlineState\fP localOutlineState)"

.PP
Definition at line \fB38\fP of file \fBOutlineInitializer\&.razor\&.cs\fP\&.
.SS "string Luthetus\&.Common\&.RazorLib\&.Outlines\&.Displays\&.OutlineInitializer\&.GetStyleCssTop (\fBOutlineState\fP localOutlineState)"

.PP
Definition at line \fB60\fP of file \fBOutlineInitializer\&.razor\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const double Luthetus\&.Common\&.RazorLib\&.Outlines\&.Displays\&.OutlineInitializer\&.OUTLINE_THICKNESS = 4\fR [static]\fP"

.PP
The unit of measurement is Pixels (px)\&. 
.PP
Definition at line \fB16\fP of file \fBOutlineInitializer\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "IState<\fBOutlineState\fP> Luthetus\&.Common\&.RazorLib\&.Outlines\&.Displays\&.OutlineInitializer\&.OutlineStateWrap = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB13\fP of file \fBOutlineInitializer\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
