.TH "Luthetus.CompilerServices.Xml.Html.Decoration.TextEditorHtmlDecorationMapper" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.Xml.Html.Decoration.TextEditorHtmlDecorationMapper
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.TextEditor\&.RazorLib\&.Decorations\&.Models\&.IDecorationMapper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBMap\fP (byte decorationByte)"
.br
.RI "Maps a decorationByte to a CSS class that is in the form of a string\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBTextEditorHtmlDecorationMapper\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "string Luthetus\&.CompilerServices\&.Xml\&.Html\&.Decoration\&.TextEditorHtmlDecorationMapper\&.Map (byte decorationByte)"

.PP
Maps a decorationByte to a CSS class that is in the form of a string\&. 
.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.Decorations\&.Models\&.IDecorationMapper\fP\&.
.PP
Definition at line \fB7\fP of file \fBTextEditorHtmlDecorationMapper\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
