.TH "Luthetus.Common.RazorLib.Themes.States" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Themes.States
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "partial record \fBThemeState\fP (ImmutableList< \fBThemeRecord\fP > ThemeList)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "partial record Luthetus\&.Common\&.RazorLib\&.Themes\&.States\&.ThemeState (ImmutableList< \fBThemeRecord\fP > ThemeList)"

.PP
Definition at line \fB8\fP of file \fBThemeState\&.Main\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
