.TH "Luthetus.Common.RazorLib.Commands.Models.CommonCommandArgs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Commands.Models.CommonCommandArgs \- Any command args ought to be a struct? High turnover\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Common\&.RazorLib\&.Commands\&.Models\&.ICommandArgs\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommonCommandArgs\fP (\fBKeymapArgs\fP keymapArgs)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "KeymapArgs \fBKeymapArgs\fP\fR [get]\fP"
.br
.RI "When the command is fired via a keyboard event, there is no mapping done for \fBKeymapArgs\&.Location\fP, and other miscelaneous information\&. "
.in -1c
.SH "Detailed Description"
.PP 
Any command args ought to be a struct? High turnover\&. 
.PP
Definition at line \fB8\fP of file \fBCommonCommandArgs\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Common\&.RazorLib\&.Commands\&.Models\&.CommonCommandArgs\&.CommonCommandArgs (\fBKeymapArgs\fP keymapArgs)"

.PP
Definition at line \fB10\fP of file \fBCommonCommandArgs\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "KeymapArgs Luthetus\&.Common\&.RazorLib\&.Commands\&.Models\&.CommonCommandArgs\&.KeymapArgs\fR [get]\fP"

.PP
When the command is fired via a keyboard event, there is no mapping done for \fBKeymapArgs\&.Location\fP, and other miscelaneous information\&. So, the \fBKeymapArgs\fP is provided here so one can check the miscelaneous information\&. 
.PP
Definition at line \fB23\fP of file \fBCommonCommandArgs\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
