.TH "Luthetus.Extensions.DotNet.Tests.Basis.TreeViewImplementations.Models.TreeViewNamespacePathTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.Tests.Basis.TreeViewImplementations.Models.TreeViewNamespacePathTests \- \fBTreeViewNamespacePath\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.ExtensionsDotNetTestBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "TreeViewNamespacePath(NamespacePath, ILuthetusIdeComponentRenderers, ILuthetusCommonComponentRenderers, IFileSystemProvider, IEnvironmentProvider, bool, bool) 
.br
----
.br
 \fBTreeViewNamespacePath\&.IdeComponentRenderers\fP \fBTreeViewNamespacePath\&.CommonComponentRenderers\fP \fBTreeViewNamespacePath\&.FileSystemProvider\fP \fBTreeViewNamespacePath\&.EnvironmentProvider\fP "
.ti -1c
.RI "void \fBEquals_Test\fP ()"
.br
.RI "\fBTreeViewNamespacePath\&.Equals(object?)\fP "
.ti -1c
.RI "void \fBGetHashCode_Test\fP ()"
.br
.RI "\fBTreeViewNamespacePath\&.GetHashCode()\fP "
.ti -1c
.RI "void \fBGetTreeViewRenderer\fP ()"
.br
.RI "\fBTreeViewNamespacePath\&.GetTreeViewRenderer()\fP "
.ti -1c
.RI "void \fBLoadChildListAsync\fP ()"
.br
.RI "\fBTreeViewNamespacePath\&.LoadChildListAsync()\fP "
.ti -1c
.RI "void \fBRemoveRelatedFilesFromParent\fP ()"
.br
.RI "TreeViewNamespacePath\&.RemoveRelatedFilesFromParent(List<TreeViewNoType>) "
.in -1c
.SS "Additional Inherited Members"


Static Protected Member Functions inherited from \fBLuthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.ExtensionsDotNetTestBase\fP
.in +1c
.ti -1c
.RI "static void \fBTest_RegisterServices\fP (out ServiceProvider serviceProvider)"
.br
.ti -1c
.RI "static void \fBTest_CreateFileSystem\fP (IServiceProvider serviceProvider)"
.br
.RI "The files shown in the 'tree' below will be written to the in-memory filesystem\&. ---------------------------------------------
.br
 Root
.br
 ∙└───Homework
.br
 ∙∙∙∙∙∙├───Math
.br
 ∙∙∙∙∙∙│∙∙∙∙├───addition\&.txt
.br
 ∙∙∙∙∙∙│∙∙∙∙└───subtraction\&.txt
.br
 ∙∙∙∙∙∙│
.br
 ∙∙∙∙∙∙└───Biology
.br
 ∙∙∙∙∙∙∙∙∙∙∙├───nervousSystem\&.txt
.br
 ∙∙∙∙∙∙∙∙∙∙∙└───skeletalSystem\&.txt
.br
\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBTreeViewNamespacePath\fP 
.PP
Definition at line \fB14\fP of file \fBTreeViewNamespacePathTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.TreeViewImplementations\&.Models\&.TreeViewNamespacePathTests\&.Constructor ()"

.PP
TreeViewNamespacePath(NamespacePath, ILuthetusIdeComponentRenderers, ILuthetusCommonComponentRenderers, IFileSystemProvider, IEnvironmentProvider, bool, bool) 
.br
----
.br
 \fBTreeViewNamespacePath\&.IdeComponentRenderers\fP \fBTreeViewNamespacePath\&.CommonComponentRenderers\fP \fBTreeViewNamespacePath\&.FileSystemProvider\fP \fBTreeViewNamespacePath\&.EnvironmentProvider\fP 
.PP
Definition at line \fB25\fP of file \fBTreeViewNamespacePathTests\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.TreeViewImplementations\&.Models\&.TreeViewNamespacePathTests\&.Equals_Test ()"

.PP
\fBTreeViewNamespacePath\&.Equals(object?)\fP 
.PP
Definition at line \fB67\fP of file \fBTreeViewNamespacePathTests\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.TreeViewImplementations\&.Models\&.TreeViewNamespacePathTests\&.GetHashCode_Test ()"

.PP
\fBTreeViewNamespacePath\&.GetHashCode()\fP 
.PP
Definition at line \fB76\fP of file \fBTreeViewNamespacePathTests\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.TreeViewImplementations\&.Models\&.TreeViewNamespacePathTests\&.GetTreeViewRenderer ()"

.PP
\fBTreeViewNamespacePath\&.GetTreeViewRenderer()\fP 
.PP
Definition at line \fB85\fP of file \fBTreeViewNamespacePathTests\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.TreeViewImplementations\&.Models\&.TreeViewNamespacePathTests\&.LoadChildListAsync ()"

.PP
\fBTreeViewNamespacePath\&.LoadChildListAsync()\fP 
.PP
Definition at line \fB94\fP of file \fBTreeViewNamespacePathTests\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.TreeViewImplementations\&.Models\&.TreeViewNamespacePathTests\&.RemoveRelatedFilesFromParent ()"

.PP
TreeViewNamespacePath\&.RemoveRelatedFilesFromParent(List<TreeViewNoType>) 
.PP
Definition at line \fB103\fP of file \fBTreeViewNamespacePathTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
