.TH "Luthetus.Common.Tests.Basis.WatchWindows.Models.TreeViewTextTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.WatchWindows.Models.TreeViewTextTests \- \fBTreeViewText\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "TreeViewText(string, bool, bool, ILuthetusCommonComponentRenderers) "
.ti -1c
.RI "void \fBEquals_Test\fP ()"
.br
.RI "\fBTreeViewText\&.Equals(object?)\fP "
.ti -1c
.RI "void \fBGetHashCode_Test\fP ()"
.br
.RI "\fBTreeViewText\&.GetHashCode()\fP "
.ti -1c
.RI "void \fBGetTreeViewRenderer\fP ()"
.br
.RI "\fBTreeViewText\&.GetTreeViewRenderer()\fP "
.ti -1c
.RI "void \fBLoadChildListAsync\fP ()"
.br
.RI "\fBTreeViewText\&.LoadChildListAsync()\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBTreeViewText\fP 
.PP
Definition at line \fB8\fP of file \fBTreeViewTextTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.WatchWindows\&.Models\&.TreeViewTextTests\&.Constructor ()"

.PP
TreeViewText(string, bool, bool, ILuthetusCommonComponentRenderers) 
.PP
Definition at line \fB14\fP of file \fBTreeViewTextTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.WatchWindows\&.Models\&.TreeViewTextTests\&.Equals_Test ()"

.PP
\fBTreeViewText\&.Equals(object?)\fP 
.PP
Definition at line \fB41\fP of file \fBTreeViewTextTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.WatchWindows\&.Models\&.TreeViewTextTests\&.GetHashCode_Test ()"

.PP
\fBTreeViewText\&.GetHashCode()\fP 
.PP
Definition at line \fB77\fP of file \fBTreeViewTextTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.WatchWindows\&.Models\&.TreeViewTextTests\&.GetTreeViewRenderer ()"

.PP
\fBTreeViewText\&.GetTreeViewRenderer()\fP 
.PP
Definition at line \fB100\fP of file \fBTreeViewTextTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.WatchWindows\&.Models\&.TreeViewTextTests\&.LoadChildListAsync ()"

.PP
\fBTreeViewText\&.LoadChildListAsync()\fP 
.PP
Definition at line \fB132\fP of file \fBTreeViewTextTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
