.TH "Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.LambdaExpressionNode" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.LambdaExpressionNode \- While parsing expression, it is necessary that there exists a node that indicates a lambda expression is being parsed\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.Interfaces\&.IExpressionNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLambdaExpressionNode\fP (\fBTypeClauseNode\fP resultTypeClauseNode)"
.br
.ti -1c
.RI "void \fBAddVariableDeclarationNode\fP (\fBIVariableDeclarationNode\fP variableDeclarationNode)"
.br
.ti -1c
.RI "\fBISyntax\fP[] \fBGetChildList\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBTypeClauseNode\fP \fBResultTypeClauseNode\fP\fR [get]\fP"
.br
.RI "When parsing an expression, there may be a \fBFunctionInvocationNode\fP with a \fBGenericParametersListingNode\fP\&. "
.ti -1c
.RI "bool \fBCodeBlockNodeIsExpression\fP = true\fR [get, set]\fP"
.br
.RI "() => "Abc"; Then this property is true; "
.ti -1c
.RI "bool \fBHasReadParameters\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "List< \fBIVariableDeclarationNode\fP > \fBVariableDeclarationNodeList\fP = new()\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsFabricated\fP\fR [get]\fP"
.br
.RI "\fBIsFabricated\fP refers to when the ParserSession expected a node to be valid, but it wasn't\&.
.br

.br
For example, a function invocation on an undefined function will construct a BoundFunctionInvocationNode with \fBIsFabricated\fP set to true\&. "
.ti -1c
.RI "\fBSyntaxKind\fP \fBSyntaxKind\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
While parsing expression, it is necessary that there exists a node that indicates a lambda expression is being parsed\&. 

This type might be more along the lines of a "builder" type\&. It is meant to be made when starting lambda expression, then the primary expression can be equal to an instae of this type\&.

.PP
This then directs the parser accordingly until the lambda expression is fully parsed\&.

.PP
At this point, it is planned that a \fBFunctionDefinitionNode\fP will be made, and a 'MethodGroupExpressionNode' (this type does not yet exist) will be returned as the primary expression\&. 
.PP
Definition at line \fB25\fP of file \fBLambdaExpressionNode\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.LambdaExpressionNode\&.LambdaExpressionNode (\fBTypeClauseNode\fP resultTypeClauseNode)"

.PP
Definition at line \fB27\fP of file \fBLambdaExpressionNode\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.LambdaExpressionNode\&.AddVariableDeclarationNode (\fBIVariableDeclarationNode\fP variableDeclarationNode)"

.PP
Definition at line \fB51\fP of file \fBLambdaExpressionNode\&.cs\fP\&.
.SS "\fBISyntax\fP[] Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.LambdaExpressionNode\&.GetChildList ()"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.ISyntaxNode\fP\&.
.PP
Definition at line \fB57\fP of file \fBLambdaExpressionNode\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.LambdaExpressionNode\&.CodeBlockNodeIsExpression = true\fR [get]\fP, \fR [set]\fP"

.PP
() => "Abc"; Then this property is true; () => { return "Abc" }; Then this property is false; 
.PP
Definition at line \fB44\fP of file \fBLambdaExpressionNode\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.LambdaExpressionNode\&.HasReadParameters\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB45\fP of file \fBLambdaExpressionNode\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.LambdaExpressionNode\&.IsFabricated\fR [get]\fP"

.PP
\fBIsFabricated\fP refers to when the ParserSession expected a node to be valid, but it wasn't\&.
.br

.br
For example, a function invocation on an undefined function will construct a BoundFunctionInvocationNode with \fBIsFabricated\fP set to true\&. 
.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.ISyntax\fP\&.
.PP
Definition at line \fB48\fP of file \fBLambdaExpressionNode\&.cs\fP\&.
.SS "\fBTypeClauseNode\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.LambdaExpressionNode\&.ResultTypeClauseNode\fR [get]\fP"

.PP
When parsing an expression, there may be a \fBFunctionInvocationNode\fP with a \fBGenericParametersListingNode\fP\&. The expression code works however by passing around an 'IExpression expressionPrimary' and an 'IExpression expressionSeconday'\&.

.PP
This means we cannot add common logic for parsing a \fBGenericParametersListingNode\fP unless the expression parsing code were modified, or maybe a call to a separate function to parse \fBGenericParametersListingNode\fP could be done\&.

.PP
But, for now an experiment with making \fBGenericParametersListingNode\fP into a IExpressionNode is being tried out\&.

.PP
Any IExpressionNode that is part of a complete expression, will have the IExpressionNode\&.ResultTypeClauseNode of Pseudo in order to indicate that the node is part of a expression, but not itself an expression\&.

.PP
Use '\fBTypeClauseNode\fP IExpressionNode\&.ResultTypeClauseNode => TypeClauseNodeFacts\&.Pseudo;' so that some confusion can be avoided since one has to cast it explicitly as an IExpressionNode in order to access the property\&. (i\&.e\&.: \fBGenericParameterEntryNode\&.TypeClauseNode\fP is not equal to IExpressionNode\&.ResultTypeClauseNode)\&. 
.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.Interfaces\&.IExpressionNode\fP\&.
.PP
Definition at line \fB35\fP of file \fBLambdaExpressionNode\&.cs\fP\&.
.SS "\fBSyntaxKind\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.LambdaExpressionNode\&.SyntaxKind\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.ISyntax\fP\&.
.PP
Definition at line \fB49\fP of file \fBLambdaExpressionNode\&.cs\fP\&.
.SS "List<\fBIVariableDeclarationNode\fP> Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.LambdaExpressionNode\&.VariableDeclarationNodeList = new()\fR [get]\fP"

.PP
Definition at line \fB46\fP of file \fBLambdaExpressionNode\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
