.TH "Luthetus.Extensions.DotNet.CompilerServices.Displays.Internals.SyntaxDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.CompilerServices.Displays.Internals.SyntaxDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "CSharpCompilerService \fBCSharpCompilerService\fP = null!\fR [get, set]\fP"
.br
.ti -1c
.RI "CSharpResource \fBCSharpResource\fP = null!\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBISyntax\fP \fBSyntax\fP = null!\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBSyntaxDisplay\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "CSharpCompilerService Luthetus\&.Extensions\&.DotNet\&.CompilerServices\&.Displays\&.Internals\&.SyntaxDisplay\&.CSharpCompilerService = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB15\fP of file \fBSyntaxDisplay\&.razor\&.cs\fP\&.
.SS "CSharpResource Luthetus\&.Extensions\&.DotNet\&.CompilerServices\&.Displays\&.Internals\&.SyntaxDisplay\&.CSharpResource = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB17\fP of file \fBSyntaxDisplay\&.razor\&.cs\fP\&.
.SS "\fBISyntax\fP Luthetus\&.Extensions\&.DotNet\&.CompilerServices\&.Displays\&.Internals\&.SyntaxDisplay\&.Syntax = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB20\fP of file \fBSyntaxDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
