.TH "Luthetus.Common.Tests.Basis.Keyboards.Models.KeyboardKeyFactsTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Keyboards.Models.KeyboardKeyFactsTests \- KeyboardKeyFacts  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBIsMetaKeyA\fP ()"
.br
.RI "IsMetaKey(KeyboardEventArgs) "
.ti -1c
.RI "void \fBIsMetaKeyB\fP ()"
.br
.RI "IsMetaKey(string, string) "
.ti -1c
.RI "void \fBIsWhitespaceCharacter\fP ()"
.br
.RI "KeyboardKeyFacts\&.IsWhitespaceCharacter(char) "
.ti -1c
.RI "void \fBIsPunctuationCharacter\fP ()"
.br
.RI "KeyboardKeyFacts\&.IsPunctuationCharacter(char) "
.ti -1c
.RI "void \fBMatchPunctuationCharacter\fP ()"
.br
.RI "KeyboardKeyFacts\&.MatchPunctuationCharacter(char) "
.ti -1c
.RI "void \fBDirectionToFindMatchMatchingPunctuationCharacter\fP ()"
.br
.RI "KeyboardKeyFacts\&.DirectionToFindMatchingPunctuationCharacter(char) "
.ti -1c
.RI "void \fBIsWhitespaceCode\fP ()"
.br
.RI "KeyboardKeyFacts\&.IsWhitespaceCode(string) "
.ti -1c
.RI "void \fBCheckIsAlternateContextMenuEvent\fP ()"
.br
.RI "KeyboardKeyFacts\&.CheckIsAlternateContextMenuEvent(string, string, bool, bool) "
.ti -1c
.RI "void \fBCheckIsContextMenuEventA\fP ()"
.br
.RI "CheckIsContextMenuEvent(string, string, bool, bool) "
.ti -1c
.RI "void \fBCheckIsContextMenuEventB\fP ()"
.br
.RI "CheckIsContextMenuEvent(KeyboardEventArgs) "
.ti -1c
.RI "void \fBIsMovementKey\fP ()"
.br
.RI "KeyboardKeyFacts\&.IsMovementKey(string) "
.ti -1c
.RI "void \fBConvertWhitespaceCodeToCharacter\fP ()"
.br
.RI "KeyboardKeyFacts\&.ConvertWhitespaceCodeToCharacter(string) "
.ti -1c
.RI "void \fBIsLineEndingCharacter\fP ()"
.br
.RI "KeyboardKeyFacts\&.IsLineEndingCharacter(char) "
.in -1c
.SH "Detailed Description"
.PP 
KeyboardKeyFacts 
.PP
Definition at line \fB10\fP of file \fBKeyboardKeyFactsTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Keyboards\&.Models\&.KeyboardKeyFactsTests\&.CheckIsAlternateContextMenuEvent ()"

.PP
KeyboardKeyFacts\&.CheckIsAlternateContextMenuEvent(string, string, bool, bool) 
.PP
Definition at line \fB187\fP of file \fBKeyboardKeyFactsTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Keyboards\&.Models\&.KeyboardKeyFactsTests\&.CheckIsContextMenuEventA ()"

.PP
CheckIsContextMenuEvent(string, string, bool, bool) 
.PP
Definition at line \fB236\fP of file \fBKeyboardKeyFactsTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Keyboards\&.Models\&.KeyboardKeyFactsTests\&.CheckIsContextMenuEventB ()"

.PP
CheckIsContextMenuEvent(KeyboardEventArgs) 
.PP
Definition at line \fB288\fP of file \fBKeyboardKeyFactsTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Keyboards\&.Models\&.KeyboardKeyFactsTests\&.ConvertWhitespaceCodeToCharacter ()"

.PP
KeyboardKeyFacts\&.ConvertWhitespaceCodeToCharacter(string) 
.PP
Definition at line \fB385\fP of file \fBKeyboardKeyFactsTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Keyboards\&.Models\&.KeyboardKeyFactsTests\&.DirectionToFindMatchMatchingPunctuationCharacter ()"

.PP
KeyboardKeyFacts\&.DirectionToFindMatchingPunctuationCharacter(char) 
.PP
Definition at line \fB126\fP of file \fBKeyboardKeyFactsTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Keyboards\&.Models\&.KeyboardKeyFactsTests\&.IsLineEndingCharacter ()"

.PP
KeyboardKeyFacts\&.IsLineEndingCharacter(char) 
.PP
Definition at line \fB416\fP of file \fBKeyboardKeyFactsTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Keyboards\&.Models\&.KeyboardKeyFactsTests\&.IsMetaKeyA ()"

.PP
IsMetaKey(KeyboardEventArgs) 
.PP
Definition at line \fB16\fP of file \fBKeyboardKeyFactsTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Keyboards\&.Models\&.KeyboardKeyFactsTests\&.IsMetaKeyB ()"

.PP
IsMetaKey(string, string) 
.PP
Definition at line \fB36\fP of file \fBKeyboardKeyFactsTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Keyboards\&.Models\&.KeyboardKeyFactsTests\&.IsMovementKey ()"

.PP
KeyboardKeyFacts\&.IsMovementKey(string) 
.PP
Definition at line \fB352\fP of file \fBKeyboardKeyFactsTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Keyboards\&.Models\&.KeyboardKeyFactsTests\&.IsPunctuationCharacter ()"

.PP
KeyboardKeyFacts\&.IsPunctuationCharacter(char) 
.PP
Definition at line \fB75\fP of file \fBKeyboardKeyFactsTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Keyboards\&.Models\&.KeyboardKeyFactsTests\&.IsWhitespaceCharacter ()"

.PP
KeyboardKeyFacts\&.IsWhitespaceCharacter(char) 
.PP
Definition at line \fB52\fP of file \fBKeyboardKeyFactsTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Keyboards\&.Models\&.KeyboardKeyFactsTests\&.IsWhitespaceCode ()"

.PP
KeyboardKeyFacts\&.IsWhitespaceCode(string) 
.PP
Definition at line \fB154\fP of file \fBKeyboardKeyFactsTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Keyboards\&.Models\&.KeyboardKeyFactsTests\&.MatchPunctuationCharacter ()"

.PP
KeyboardKeyFacts\&.MatchPunctuationCharacter(char) 
.PP
Definition at line \fB98\fP of file \fBKeyboardKeyFactsTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
