.TH "Luthetus.CompilerServices.DotNetSolution.Models.Associated.AssociatedEntryGroupBuilder" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.DotNetSolution.Models.Associated.AssociatedEntryGroupBuilder
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAssociatedEntryGroupBuilder\fP (\fBOpenAssociatedGroupToken\fP openAssociatedGroupToken, Action< \fBAssociatedEntryGroup\fP > onAfterBuildAction)"
.br
.ti -1c
.RI "\fBAssociatedEntryGroup\fP \fBBuild\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Action< \fBAssociatedEntryGroup\fP > \fBOnAfterBuildAction\fP\fR [get]\fP"
.br
.ti -1c
.RI "OpenAssociatedGroupToken \fBOpenAssociatedGroupToken\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "List< \fBIAssociatedEntry\fP > \fBAssociatedEntryList\fP = new()\fR [get]\fP"
.br
.ti -1c
.RI "CloseAssociatedGroupToken \fBCloseAssociatedGroupToken\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBAssociatedEntryGroupBuilder\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Associated\&.AssociatedEntryGroupBuilder\&.AssociatedEntryGroupBuilder (\fBOpenAssociatedGroupToken\fP openAssociatedGroupToken, Action< \fBAssociatedEntryGroup\fP > onAfterBuildAction)"

.PP
Definition at line \fB8\fP of file \fBAssociatedEntryGroupBuilder\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBAssociatedEntryGroup\fP Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Associated\&.AssociatedEntryGroupBuilder\&.Build ()"

.PP
Definition at line \fB21\fP of file \fBAssociatedEntryGroupBuilder\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "List<\fBIAssociatedEntry\fP> Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Associated\&.AssociatedEntryGroupBuilder\&.AssociatedEntryList = new()\fR [get]\fP"

.PP
Definition at line \fB18\fP of file \fBAssociatedEntryGroupBuilder\&.cs\fP\&.
.SS "CloseAssociatedGroupToken Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Associated\&.AssociatedEntryGroupBuilder\&.CloseAssociatedGroupToken\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB19\fP of file \fBAssociatedEntryGroupBuilder\&.cs\fP\&.
.SS "Action<\fBAssociatedEntryGroup\fP> Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Associated\&.AssociatedEntryGroupBuilder\&.OnAfterBuildAction\fR [get]\fP"

.PP
Definition at line \fB16\fP of file \fBAssociatedEntryGroupBuilder\&.cs\fP\&.
.SS "OpenAssociatedGroupToken Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Associated\&.AssociatedEntryGroupBuilder\&.OpenAssociatedGroupToken\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB17\fP of file \fBAssociatedEntryGroupBuilder\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
