.TH "Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Parsers.StatementTests.Test" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Parsers.StatementTests.Test
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTest\fP (string sourceText)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBSourceText\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "ResourceUri \fBResourceUri\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBCSharpLexer\fP \fBLexer\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBCSharpParser\fP \fBParser\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "CompilationUnit \fBCompilationUnit\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB19\fP of file \fBStatementTests\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.StatementTests\&.Test\&.Test (string sourceText)"

.PP
Definition at line \fB21\fP of file \fBStatementTests\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "CompilationUnit Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.StatementTests\&.Test\&.CompilationUnit\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB35\fP of file \fBStatementTests\&.cs\fP\&.
.SS "\fBCSharpLexer\fP Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.StatementTests\&.Test\&.Lexer\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB33\fP of file \fBStatementTests\&.cs\fP\&.
.SS "\fBCSharpParser\fP Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.StatementTests\&.Test\&.Parser\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB34\fP of file \fBStatementTests\&.cs\fP\&.
.SS "ResourceUri Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.StatementTests\&.Test\&.ResourceUri\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB32\fP of file \fBStatementTests\&.cs\fP\&.
.SS "string Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.StatementTests\&.Test\&.SourceText\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB31\fP of file \fBStatementTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
