.TH "Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Common\&.RazorLib\&.Commands\&.Models\&.ICommandArgs\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBKeymapArgs\fP ()"
.br
.ti -1c
.RI "\fBKeymapArgs\fP (KeyboardEventArgs keyboardEventArgs)"
.br
.ti -1c
.RI "override bool \fBEquals\fP (object? obj)"
.br
.ti -1c
.RI "override int \fBGetHashCode\fP ()"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static bool \fBoperator==\fP (\fBKeymapArgs\fP left, \fBKeymapArgs\fP right)"
.br
.ti -1c
.RI "static bool \fBoperator!=\fP (\fBKeymapArgs\fP left, \fBKeymapArgs\fP right)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBKey\fP< \fBKeymapLayer\fP > \fBLayerKey\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string? \fBKey\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string? \fBCode\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "float \fBLocation\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBRepeat\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBCtrlKey\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBShiftKey\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBAltKey\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBMetaKey\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string? \fBType\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Goal: Better Keymap code (2024-08-30)"
.PP
The immediate reason for wanting better keymap code, is that on Linux the 'CapsLock' to 'Escape' setting is returning: event\&.key == Escape BUT event\&.code == CapsLock 
.PP
Definition at line \fB15\fP of file \fBKeymapArgs\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Common\&.RazorLib\&.Keymaps\&.Models\&.KeymapArgs\&.KeymapArgs ()"

.PP
Definition at line \fB17\fP of file \fBKeymapArgs\&.cs\fP\&.
.SS "Luthetus\&.Common\&.RazorLib\&.Keymaps\&.Models\&.KeymapArgs\&.KeymapArgs (KeyboardEventArgs keyboardEventArgs)"

.PP
Definition at line \fB21\fP of file \fBKeymapArgs\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override bool Luthetus\&.Common\&.RazorLib\&.Keymaps\&.Models\&.KeymapArgs\&.Equals (object? obj)"

.PP
Definition at line \fB46\fP of file \fBKeymapArgs\&.cs\fP\&.
.SS "override int Luthetus\&.Common\&.RazorLib\&.Keymaps\&.Models\&.KeymapArgs\&.GetHashCode ()"

.PP
Definition at line \fB62\fP of file \fBKeymapArgs\&.cs\fP\&.
.SS "bool Luthetus\&.Common\&.RazorLib\&.Keymaps\&.Models\&.KeymapArgs\&.operator!= (\fBKeymapArgs\fP left, \fBKeymapArgs\fP right)\fR [static]\fP"

.PP
Definition at line \fB78\fP of file \fBKeymapArgs\&.cs\fP\&.
.SS "bool Luthetus\&.Common\&.RazorLib\&.Keymaps\&.Models\&.KeymapArgs\&.operator== (\fBKeymapArgs\fP left, \fBKeymapArgs\fP right)\fR [static]\fP"

.PP
Definition at line \fB73\fP of file \fBKeymapArgs\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Luthetus\&.Common\&.RazorLib\&.Keymaps\&.Models\&.KeymapArgs\&.AltKey\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB42\fP of file \fBKeymapArgs\&.cs\fP\&.
.SS "string? Luthetus\&.Common\&.RazorLib\&.Keymaps\&.Models\&.KeymapArgs\&.Code\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB37\fP of file \fBKeymapArgs\&.cs\fP\&.
.SS "bool Luthetus\&.Common\&.RazorLib\&.Keymaps\&.Models\&.KeymapArgs\&.CtrlKey\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB40\fP of file \fBKeymapArgs\&.cs\fP\&.
.SS "string? Luthetus\&.Common\&.RazorLib\&.Keymaps\&.Models\&.KeymapArgs\&.Key\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB36\fP of file \fBKeymapArgs\&.cs\fP\&.
.SS "\fBKey\fP<\fBKeymapLayer\fP> Luthetus\&.Common\&.RazorLib\&.Keymaps\&.Models\&.KeymapArgs\&.LayerKey\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB34\fP of file \fBKeymapArgs\&.cs\fP\&.
.SS "float Luthetus\&.Common\&.RazorLib\&.Keymaps\&.Models\&.KeymapArgs\&.Location\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB38\fP of file \fBKeymapArgs\&.cs\fP\&.
.SS "bool Luthetus\&.Common\&.RazorLib\&.Keymaps\&.Models\&.KeymapArgs\&.MetaKey\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB43\fP of file \fBKeymapArgs\&.cs\fP\&.
.SS "bool Luthetus\&.Common\&.RazorLib\&.Keymaps\&.Models\&.KeymapArgs\&.Repeat\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB39\fP of file \fBKeymapArgs\&.cs\fP\&.
.SS "bool Luthetus\&.Common\&.RazorLib\&.Keymaps\&.Models\&.KeymapArgs\&.ShiftKey\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB41\fP of file \fBKeymapArgs\&.cs\fP\&.
.SS "string? Luthetus\&.Common\&.RazorLib\&.Keymaps\&.Models\&.KeymapArgs\&.Type\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB44\fP of file \fBKeymapArgs\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
