.TH "Luthetus.Common.RazorLib.BackgroundTasks.Models.BackgroundTaskServiceSynchronous" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.BackgroundTasks.Models.BackgroundTaskServiceSynchronous
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.IBackgroundTaskService\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBEnqueue\fP (\fBIBackgroundTask\fP backgroundTask)"
.br
.ti -1c
.RI "void \fBEnqueue\fP (Key< \fBIBackgroundTask\fP > taskKey, Key< \fBIBackgroundTaskQueue\fP > queueKey, string name, Func< Task > runFunc)"
.br
.ti -1c
.RI "Task \fBEnqueueAsync\fP (\fBIBackgroundTask\fP backgroundTask)"
.br
.ti -1c
.RI "Task \fBEnqueueAsync\fP (Key< \fBIBackgroundTask\fP > taskKey, Key< \fBIBackgroundTaskQueue\fP > queueKey, string name, Func< Task > runFunc)"
.br
.ti -1c
.RI "void \fBCompleteTaskCompletionSource\fP (Key< \fBIBackgroundTask\fP > taskKey)"
.br
.ti -1c
.RI "\fBIBackgroundTask\fP? \fBDequeue\fP (Key< \fBIBackgroundTaskQueue\fP > queueKey)"
.br
.ti -1c
.RI "Task< \fBIBackgroundTask\fP?> \fBDequeueAsync\fP (Key< \fBIBackgroundTaskQueue\fP > queueKey, CancellationToken cancellationToken)"
.br
.ti -1c
.RI "void \fBRegisterQueue\fP (\fBIBackgroundTaskQueue\fP queue)"
.br
.ti -1c
.RI "void \fBSetExecutingBackgroundTask\fP (Key< \fBIBackgroundTaskQueue\fP > queueKey, \fBIBackgroundTask\fP? backgroundTask)"
.br
.ti -1c
.RI "\fBIBackgroundTaskQueue\fP \fBGetQueue\fP (Key< \fBIBackgroundTaskQueue\fP > queueKey)"
.br
.ti -1c
.RI "async Task \fBStopAsync\fP (CancellationToken cancellationToken)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "ImmutableArray< \fBIBackgroundTaskQueue\fP > \fBQueues\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBBackgroundTaskServiceSynchronous\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.BackgroundTaskServiceSynchronous\&.CompleteTaskCompletionSource (Key< \fBIBackgroundTask\fP > taskKey)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.IBackgroundTaskService\fP\&.
.PP
Definition at line \fB54\fP of file \fBBackgroundTaskServiceSynchronous\&.cs\fP\&.
.SS "\fBIBackgroundTask\fP? Luthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.BackgroundTaskServiceSynchronous\&.Dequeue (Key< \fBIBackgroundTaskQueue\fP > queueKey)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.IBackgroundTaskService\fP\&.
.PP
Definition at line \fB61\fP of file \fBBackgroundTaskServiceSynchronous\&.cs\fP\&.
.SS "Task< \fBIBackgroundTask\fP?> Luthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.BackgroundTaskServiceSynchronous\&.DequeueAsync (Key< \fBIBackgroundTaskQueue\fP > queueKey, CancellationToken cancellationToken)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.IBackgroundTaskService\fP\&.
.PP
Definition at line \fB68\fP of file \fBBackgroundTaskServiceSynchronous\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.BackgroundTaskServiceSynchronous\&.Enqueue (\fBIBackgroundTask\fP backgroundTask)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.IBackgroundTaskService\fP\&.
.PP
Definition at line \fB14\fP of file \fBBackgroundTaskServiceSynchronous\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.BackgroundTaskServiceSynchronous\&.Enqueue (Key< \fBIBackgroundTask\fP > taskKey, Key< \fBIBackgroundTaskQueue\fP > queueKey, string name, Func< Task > runFunc)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.IBackgroundTaskService\fP\&.
.PP
Definition at line \fB38\fP of file \fBBackgroundTaskServiceSynchronous\&.cs\fP\&.
.SS "Task Luthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.BackgroundTaskServiceSynchronous\&.EnqueueAsync (\fBIBackgroundTask\fP backgroundTask)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.IBackgroundTaskService\fP\&.
.PP
Definition at line \fB43\fP of file \fBBackgroundTaskServiceSynchronous\&.cs\fP\&.
.SS "Task Luthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.BackgroundTaskServiceSynchronous\&.EnqueueAsync (Key< \fBIBackgroundTask\fP > taskKey, Key< \fBIBackgroundTaskQueue\fP > queueKey, string name, Func< Task > runFunc)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.IBackgroundTaskService\fP\&.
.PP
Definition at line \fB49\fP of file \fBBackgroundTaskServiceSynchronous\&.cs\fP\&.
.SS "\fBIBackgroundTaskQueue\fP Luthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.BackgroundTaskServiceSynchronous\&.GetQueue (Key< \fBIBackgroundTaskQueue\fP > queueKey)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.IBackgroundTaskService\fP\&.
.PP
Definition at line \fB91\fP of file \fBBackgroundTaskServiceSynchronous\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.BackgroundTaskServiceSynchronous\&.RegisterQueue (\fBIBackgroundTaskQueue\fP queue)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.IBackgroundTaskService\fP\&.
.PP
Definition at line \fB77\fP of file \fBBackgroundTaskServiceSynchronous\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.BackgroundTaskServiceSynchronous\&.SetExecutingBackgroundTask (Key< \fBIBackgroundTaskQueue\fP > queueKey, \fBIBackgroundTask\fP? backgroundTask)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.IBackgroundTaskService\fP\&.
.PP
Definition at line \fB82\fP of file \fBBackgroundTaskServiceSynchronous\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.BackgroundTaskServiceSynchronous\&.StopAsync (CancellationToken cancellationToken)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.IBackgroundTaskService\fP\&.
.PP
Definition at line \fB96\fP of file \fBBackgroundTaskServiceSynchronous\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "ImmutableArray<\fBIBackgroundTaskQueue\fP> Luthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.BackgroundTaskServiceSynchronous\&.Queues\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.IBackgroundTaskService\fP\&.
.PP
Definition at line \fB12\fP of file \fBBackgroundTaskServiceSynchronous\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
