.TH "Luthetus.Ide.RazorLib.FileSystems.Displays.FileTemplatesDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.FileSystems.Displays.FileTemplatesDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInitialized\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBFileName\fP = null!\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBIFileTemplate\fP? \fBExactMatchFileTemplate\fP\fR [get]\fP"
.br
.ti -1c
.RI "ImmutableArray< \fBIFileTemplate\fP >? \fBRelatedMatchFileTemplates\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBFileTemplatesDisplay\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Displays\&.FileTemplatesDisplay\&.OnInitialized ()\fR [protected]\fP"

.PP
Definition at line \fB25\fP of file \fBFileTemplatesDisplay\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBIFileTemplate\fP? Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Displays\&.FileTemplatesDisplay\&.ExactMatchFileTemplate\fR [get]\fP"

.PP
Definition at line \fB18\fP of file \fBFileTemplatesDisplay\&.razor\&.cs\fP\&.
.SS "string Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Displays\&.FileTemplatesDisplay\&.FileName = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB13\fP of file \fBFileTemplatesDisplay\&.razor\&.cs\fP\&.
.SS "ImmutableArray<\fBIFileTemplate\fP>? Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Displays\&.FileTemplatesDisplay\&.RelatedMatchFileTemplates\fR [get]\fP"

.PP
Definition at line \fB20\fP of file \fBFileTemplatesDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
