.TH "Luthetus.Extensions.DotNet.Tests.Basis.CommandLines.Models.DotNetCliOutputParserTests.DiagnosticTextSpan" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.Tests.Basis.CommandLines.Models.DotNetCliOutputParserTests.DiagnosticTextSpan
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDiagnosticTextSpan\fP (int startInclusiveIndex, int endExclusiveIndex, string text)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBStartInclusiveIndex\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBEndExclusiveIndex\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBText\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB53\fP of file \fBDotNetCliOutputParserTests\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.CommandLines\&.Models\&.DotNetCliOutputParserTests\&.DiagnosticTextSpan\&.DiagnosticTextSpan (int startInclusiveIndex, int endExclusiveIndex, string text)"

.PP
Definition at line \fB55\fP of file \fBDotNetCliOutputParserTests\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.CommandLines\&.Models\&.DotNetCliOutputParserTests\&.DiagnosticTextSpan\&.EndExclusiveIndex\fR [get]\fP"

.PP
Definition at line \fB66\fP of file \fBDotNetCliOutputParserTests\&.cs\fP\&.
.SS "int Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.CommandLines\&.Models\&.DotNetCliOutputParserTests\&.DiagnosticTextSpan\&.StartInclusiveIndex\fR [get]\fP"

.PP
Definition at line \fB65\fP of file \fBDotNetCliOutputParserTests\&.cs\fP\&.
.SS "string Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.CommandLines\&.Models\&.DotNetCliOutputParserTests\&.DiagnosticTextSpan\&.Text\fR [get]\fP"

.PP
Definition at line \fB67\fP of file \fBDotNetCliOutputParserTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
