.TH "Luthetus.CompilerServices.CSharp.BinderCase" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.CSharp.BinderCase
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCSharpBinder\fP"
.br
.ti -1c
.RI "class \fBCSharpBinderSession\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "record \fBNamespaceAndTypeIdentifiers\fP (string NamespaceIdentifier, string TypeIdentifier)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "record Luthetus\&.CompilerServices\&.CSharp\&.BinderCase\&.NamespaceAndTypeIdentifiers (string NamespaceIdentifier, string TypeIdentifier)"

.PP
Definition at line \fB3\fP of file \fBNamespaceAndTypeIdentifiers\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
