.TH "Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBHandleAsTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleBaseTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleBoolTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleBreakTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleByteTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleCaseTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleCatchTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleCharTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleCheckedTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleConstTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleContinueTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleDecimalTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleDefaultTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleDelegateTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleDoTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleDoubleTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleElseTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleEnumTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleEventTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleExplicitTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleExternTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleFalseTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleFinallyTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleFixedTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleFloatTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleForTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleForeachTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleGotoTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleImplicitTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleInTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleIntTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleIsTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleLockTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleLongTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleNullTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleObjectTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleOperatorTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleOutTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleParamsTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleProtectedTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleReadonlyTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleRefTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleSbyteTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleShortTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleSizeofTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleStackallocTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleStringTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleStructTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleSwitchTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleThisTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleThrowTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleTrueTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleTryTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleTypeofTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleUintTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleUlongTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleUncheckedTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleUnsafeTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleUshortTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleVoidTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleVolatileTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleWhileTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleUnrecognizedTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleDefault\fP (\fBCSharpParserModel\fP model)"
.br
.RI "The 'Default' of this method name is confusing\&. It seems to refer to the 'default' of switch statement rather than the 'default' keyword itself? "
.ti -1c
.RI "static void \fBHandleTypeIdentifierKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleNewTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandlePublicTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleInternalTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandlePrivateTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleStaticTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleOverrideTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleVirtualTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleAbstractTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleSealedTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleIfTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleUsingTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleInterfaceTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleStorageModifierTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.RI "Example: public class \fBMyClass\fP { } ^\&. "
.ti -1c
.RI "static void \fBHandleClassTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleNamespaceTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.ti -1c
.RI "static void \fBHandleReturnTokenKeyword\fP (\fBCSharpParserModel\fP model)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleAbstractTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB701\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleAsTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB13\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleBaseTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB18\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleBoolTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB23\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleBreakTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB28\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleByteTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB33\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleCaseTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB38\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleCatchTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB45\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleCharTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB89\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleCheckedTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB94\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleClassTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB877\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleConstTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB99\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleContinueTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB104\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleDecimalTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB109\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleDefault (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
The 'Default' of this method name is confusing\&. It seems to refer to the 'default' of switch statement rather than the 'default' keyword itself? 
.PP
Definition at line \fB644\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleDefaultTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB114\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleDelegateTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB123\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleDoTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB128\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleDoubleTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB147\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleElseTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB152\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleEnumTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB157\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleEventTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB166\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleExplicitTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB171\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleExternTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB176\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleFalseTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB181\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleFinallyTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB187\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleFixedTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB228\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleFloatTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB233\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleForeachTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB343\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleForTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB238\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleGotoTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB377\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleIfTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB711\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleImplicitTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB382\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleInterfaceTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB750\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleInternalTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB674\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleInTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB387\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleIntTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB392\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleIsTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB397\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleLockTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB402\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleLongTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB424\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleNamespaceTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB882\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleNewTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB654\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleNullTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB429\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleObjectTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB434\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleOperatorTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB439\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleOutTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB444\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleOverrideTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB691\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleParamsTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB449\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandlePrivateTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB680\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleProtectedTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB454\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandlePublicTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB668\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleReadonlyTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB460\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleRefTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB465\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleReturnTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB907\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleSbyteTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB470\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleSealedTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB706\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleShortTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB475\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleSizeofTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB480\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleStackallocTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB485\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleStaticTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB686\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleStorageModifierTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Example: public class \fBMyClass\fP { } ^\&. Given the example the '\fBMyClass\fP' is the next token upon invocation of this method\&.

.PP
Invocation of this method implies the current token was class, interface, struct, etc\&.\&.\&. 
.PP
Definition at line \fB766\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleStringTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB490\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleStructTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB495\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleSwitchTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB500\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleThisTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB522\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleThrowTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB527\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleTrueTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB532\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleTryTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB538\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleTypeIdentifierKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB649\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleTypeofTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB562\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleUintTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB567\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleUlongTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB572\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleUncheckedTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB577\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleUnrecognizedTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB636\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleUnsafeTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB582\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleUshortTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB587\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleUsingTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB728\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleVirtualTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB696\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleVoidTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB592\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleVolatileTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB597\fP of file \fBParseDefaultKeywords\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.Internals\&.ParseDefaultKeywords\&.HandleWhileTokenKeyword (\fBCSharpParserModel\fP model)\fR [static]\fP"

.PP
Definition at line \fB602\fP of file \fBParseDefaultKeywords\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
