.TH "Luthetus.CompilerServices.Xml.Html.SyntaxObjects.AttributeNode" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.Xml.Html.SyntaxObjects.AttributeNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.IHtmlSyntaxNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAttributeNode\fP (\fBAttributeNameNode\fP attributeNameSyntax, \fBAttributeValueNode\fP attributeValueSyntax)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBAttributeNameNode\fP \fBAttributeNameSyntax\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBAttributeValueNode\fP \fBAttributeValueSyntax\fP\fR [get]\fP"
.br
.ti -1c
.RI "ImmutableArray< \fBIHtmlSyntax\fP > \fBChildContent\fP\fR [get]\fP"
.br
.ti -1c
.RI "ImmutableArray< \fBIHtmlSyntax\fP > \fBChildren\fP\fR [get]\fP"
.br
.ti -1c
.RI "TextEditorTextSpan \fBTextEditorTextSpan\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBHtmlSyntaxKind\fP \fBHtmlSyntaxKind\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBAttributeNode\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.AttributeNode\&.AttributeNode (\fBAttributeNameNode\fP attributeNameSyntax, \fBAttributeValueNode\fP attributeValueSyntax)"

.PP
Definition at line \fB10\fP of file \fBAttributeNode\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBAttributeNameNode\fP Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.AttributeNode\&.AttributeNameSyntax\fR [get]\fP"

.PP
Definition at line \fB26\fP of file \fBAttributeNode\&.cs\fP\&.
.SS "\fBAttributeValueNode\fP Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.AttributeNode\&.AttributeValueSyntax\fR [get]\fP"

.PP
Definition at line \fB27\fP of file \fBAttributeNode\&.cs\fP\&.
.SS "ImmutableArray<\fBIHtmlSyntax\fP> Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.AttributeNode\&.ChildContent\fR [get]\fP"

.PP
Implements \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.IHtmlSyntaxNode\fP\&.
.PP
Definition at line \fB29\fP of file \fBAttributeNode\&.cs\fP\&.
.SS "ImmutableArray<\fBIHtmlSyntax\fP> Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.AttributeNode\&.Children\fR [get]\fP"

.PP
Implements \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.IHtmlSyntaxNode\fP\&.
.PP
Definition at line \fB30\fP of file \fBAttributeNode\&.cs\fP\&.
.SS "\fBHtmlSyntaxKind\fP Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.AttributeNode\&.HtmlSyntaxKind\fR [get]\fP"

.PP
Implements \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.IHtmlSyntax\fP\&.
.PP
Definition at line \fB39\fP of file \fBAttributeNode\&.cs\fP\&.
.SS "TextEditorTextSpan Luthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.AttributeNode\&.TextEditorTextSpan\fR [get]\fP"

.PP
Implements \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.IHtmlSyntaxNode\fP\&.
.PP
Definition at line \fB32\fP of file \fBAttributeNode\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
