.TH "Luthetus.Common.Tests.Basis.BackgroundTasks.Models.BackgroundTaskServiceTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.BackgroundTasks.Models.BackgroundTaskServiceTests \- \fBBackgroundTaskService\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async void \fBEnqueueA\fP ()"
.br
.RI "BackgroundTaskService\&.EnqueueAsync(IBackgroundTask) 
.br
----
.br
 BackgroundTaskService\&.EnqueueAsync(Key<BackgroundTask>, Key<BackgroundTaskQueue>, string, Func<Task>) BackgroundTaskService\&.RegisterQueue(BackgroundTaskQueue) BackgroundTaskService\&.DequeueAsync(Key<BackgroundTaskQueue>, CancellationToken) BackgroundTaskService\&.SetExecutingBackgroundTask(Key<BackgroundTaskQueue>, IBackgroundTask?) "
.in -1c
.SH "Detailed Description"
.PP 
\fBBackgroundTaskService\fP 
.PP
Definition at line \fB13\fP of file \fBBackgroundTaskServiceTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "async void Luthetus\&.Common\&.Tests\&.Basis\&.BackgroundTasks\&.Models\&.BackgroundTaskServiceTests\&.EnqueueA ()"

.PP
BackgroundTaskService\&.EnqueueAsync(IBackgroundTask) 
.br
----
.br
 BackgroundTaskService\&.EnqueueAsync(Key<BackgroundTask>, Key<BackgroundTaskQueue>, string, Func<Task>) BackgroundTaskService\&.RegisterQueue(BackgroundTaskQueue) BackgroundTaskService\&.DequeueAsync(Key<BackgroundTaskQueue>, CancellationToken) BackgroundTaskService\&.SetExecutingBackgroundTask(Key<BackgroundTaskQueue>, IBackgroundTask?) This test is currently an infinite loop (2024-05-08)\&. Therefore this remark is to let it be known that this test was useful, because it previous worked\&. 
.PP
Definition at line \fB30\fP of file \fBBackgroundTaskServiceTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
