.TH "Luthetus.TextEditor.RazorLib.Events.Models.OnWheel" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Events.Models.OnWheel
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.TextEditor\&.RazorLib\&.BackgroundTasks\&.Models\&.ITextEditorWork\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOnWheel\fP (\fBWheelEventArgs\fP wheelEventArgs, \fBTextEditorComponentData\fP componentData, Key< \fBTextEditorViewModel\fP > viewModelKey)"
.br
.ti -1c
.RI "\fBIBackgroundTask\fP? \fBBatchOrDefault\fP (\fBIBackgroundTask\fP oldEvent)"
.br
.RI "Before a throttle event is enqueued, this method is invoked\&. This allows for batching of 'this' throttle event instance, and the last entry of the queue\&.
.br

.br
\&. "
.ti -1c
.RI "async Task \fBHandleEvent\fP (CancellationToken cancellationToken)"
.br
.RI "This method is the actual work item that gets awaited in order to handle the event\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Key< \fBIBackgroundTask\fP > \fBBackgroundTaskKey\fP = Key<\fBIBackgroundTask\fP>\&.NewKey()\fR [get]\fP"
.br
.ti -1c
.RI "Key< \fBIBackgroundTaskQueue\fP > \fBQueueKey\fP = \fBContinuousBackgroundTaskWorker\&.GetQueueKey\fP()\fR [get]\fP"
.br
.ti -1c
.RI "string \fBName\fP = nameof(\fBOnWheel\fP)\fR [get]\fP"
.br
.ti -1c
.RI "WheelEventArgs \fBWheelEventArgs\fP\fR [get]\fP"
.br
.ti -1c
.RI "Key< \fBTextEditorViewModel\fP > \fBViewModelKey\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBTextEditorComponentData\fP \fBComponentData\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBITextEditorEditContext\fP \fBEditContext\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBOnWheel\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.Events\&.Models\&.OnWheel\&.OnWheel (\fBWheelEventArgs\fP wheelEventArgs, \fBTextEditorComponentData\fP componentData, Key< \fBTextEditorViewModel\fP > viewModelKey)"

.PP
Definition at line \fB13\fP of file \fBOnWheel\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBIBackgroundTask\fP? Luthetus\&.TextEditor\&.RazorLib\&.Events\&.Models\&.OnWheel\&.BatchOrDefault (\fBIBackgroundTask\fP oldEvent)"

.PP
Before a throttle event is enqueued, this method is invoked\&. This allows for batching of 'this' throttle event instance, and the last entry of the queue\&.
.br

.br
\&. This method is invoked from within a 'lock(_queue) { \&.\&.\&. }'\&.
.br

.br

.PP
Example use: one reads an entry from the queue, its an event that write out a character\&. Perhaps this throttle event also writes out a character\&. Instead of invoking 'text\&.Insert(character)' two times\&. One might want to invoke 'text\&.InsertRange(bothCharacters)';
.br

.br

.PP
Returning null means enqueue the recentEvent without any batching, (leave the old event as it was within the queue) 
.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.IBackgroundTask\fP\&.
.PP
Definition at line \fB33\fP of file \fBOnWheel\&.cs\fP\&.
.SS "async Task Luthetus\&.TextEditor\&.RazorLib\&.Events\&.Models\&.OnWheel\&.HandleEvent (CancellationToken cancellationToken)"

.PP
This method is the actual work item that gets awaited in order to handle the event\&. 
.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.IBackgroundTask\fP\&.
.PP
Definition at line \fB204\fP of file \fBOnWheel\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Key<\fBIBackgroundTask\fP> Luthetus\&.TextEditor\&.RazorLib\&.Events\&.Models\&.OnWheel\&.BackgroundTaskKey = Key<\fBIBackgroundTask\fP>\&.NewKey()\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.IBackgroundTask\fP\&.
.PP
Definition at line \fB24\fP of file \fBOnWheel\&.cs\fP\&.
.SS "\fBTextEditorComponentData\fP Luthetus\&.TextEditor\&.RazorLib\&.Events\&.Models\&.OnWheel\&.ComponentData\fR [get]\fP"

.PP
Definition at line \fB29\fP of file \fBOnWheel\&.cs\fP\&.
.SS "\fBITextEditorEditContext\fP Luthetus\&.TextEditor\&.RazorLib\&.Events\&.Models\&.OnWheel\&.EditContext\fR [get]\fP, \fR [set]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.BackgroundTasks\&.Models\&.ITextEditorWork\fP\&.
.PP
Definition at line \fB31\fP of file \fBOnWheel\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.Events\&.Models\&.OnWheel\&.Name = nameof(\fBOnWheel\fP)\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.IBackgroundTask\fP\&.
.PP
Definition at line \fB26\fP of file \fBOnWheel\&.cs\fP\&.
.SS "Key<\fBIBackgroundTaskQueue\fP> Luthetus\&.TextEditor\&.RazorLib\&.Events\&.Models\&.OnWheel\&.QueueKey = \fBContinuousBackgroundTaskWorker\&.GetQueueKey\fP()\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.BackgroundTasks\&.Models\&.IBackgroundTask\fP\&.
.PP
Definition at line \fB25\fP of file \fBOnWheel\&.cs\fP\&.
.SS "Key<\fBTextEditorViewModel\fP> Luthetus\&.TextEditor\&.RazorLib\&.Events\&.Models\&.OnWheel\&.ViewModelKey\fR [get]\fP"

.PP
Definition at line \fB28\fP of file \fBOnWheel\&.cs\fP\&.
.SS "WheelEventArgs Luthetus\&.TextEditor\&.RazorLib\&.Events\&.Models\&.OnWheel\&.WheelEventArgs\fR [get]\fP"

.PP
Definition at line \fB27\fP of file \fBOnWheel\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
