.TH "Luthetus.Common.RazorLib.Themes.Models.IThemeService" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Themes.Models.IThemeService
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.Common\&.RazorLib\&.Themes\&.Models\&.ThemeService\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRegisterThemeRecord\fP (\fBThemeRecord\fP themeRecord)"
.br
.ti -1c
.RI "void \fBDisposeThemeRecord\fP (Key< \fBThemeRecord\fP > themeKey)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IState< \fBThemeState\fP > \fBThemeStateWrap\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBIThemeService\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.RazorLib\&.Themes\&.Models\&.IThemeService\&.DisposeThemeRecord (Key< \fBThemeRecord\fP > themeKey)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Themes\&.Models\&.ThemeService\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.Themes\&.Models\&.IThemeService\&.RegisterThemeRecord (\fBThemeRecord\fP themeRecord)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Themes\&.Models\&.ThemeService\fP\&.
.SH "Property Documentation"
.PP 
.SS "IState<\fBThemeState\fP> Luthetus\&.Common\&.RazorLib\&.Themes\&.Models\&.IThemeService\&.ThemeStateWrap\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Themes\&.Models\&.ThemeService\fP\&.
.PP
Definition at line \fB9\fP of file \fBIThemeService\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
