.TH "Luthetus.TextEditor.RazorLib.Edits.States" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Edits.States
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "partial record \fBDirtyResourceUriState\fP (ImmutableList< \fBResourceUri\fP > DirtyResourceUriList)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "partial record Luthetus\&.TextEditor\&.RazorLib\&.Edits\&.States\&.DirtyResourceUriState (ImmutableList< \fBResourceUri\fP > DirtyResourceUriList)"

.PP
Definition at line \fB8\fP of file \fBDirtyResourceUriState\&.Main\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
