.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.CloseSquareBracketTokenTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.CloseSquareBracketTokenTests \- \fBCloseSquareBracketToken\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "CloseSquareBracketToken(TextEditorTextSpan) 
.br
----
.br
 \fBCloseSquareBracketToken\&.TextSpan\fP \fBCloseSquareBracketToken\&.SyntaxKind\fP \fBCloseSquareBracketToken\&.IsFabricated\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBCloseSquareBracketToken\fP 
.PP
Definition at line \fB10\fP of file \fBCloseSquareBracketTokenTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.Syntax\&.SyntaxTokens\&.CloseSquareBracketTokenTests\&.Constructor ()"

.PP
CloseSquareBracketToken(TextEditorTextSpan) 
.br
----
.br
 \fBCloseSquareBracketToken\&.TextSpan\fP \fBCloseSquareBracketToken\&.SyntaxKind\fP \fBCloseSquareBracketToken\&.IsFabricated\fP 
.PP
Definition at line \fB20\fP of file \fBCloseSquareBracketTokenTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
