.TH "Luthetus.Extensions.DotNet.Tests.Basis.DotNetSolutions.States.DotNetSolutionStateActionsTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.Tests.Basis.DotNetSolutions.States.DotNetSolutionStateActionsTests \- DotNetSolutionState  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRegisterAction\fP ()"
.br
.RI "DotNetSolutionState\&.RegisterAction "
.ti -1c
.RI "void \fBDisposeAction\fP ()"
.br
.RI "DotNetSolutionState\&.DisposeAction "
.ti -1c
.RI "void \fBStateHasChanged\fP ()"
.br
.RI "DotNetSolutionState\&.StateHasChanged "
.in -1c
.SH "Detailed Description"
.PP 
DotNetSolutionState 
.PP
Definition at line \fB6\fP of file \fBDotNetSolutionStateActionsTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.DotNetSolutions\&.States\&.DotNetSolutionStateActionsTests\&.DisposeAction ()"

.PP
DotNetSolutionState\&.DisposeAction 
.PP
Definition at line \fB21\fP of file \fBDotNetSolutionStateActionsTests\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.DotNetSolutions\&.States\&.DotNetSolutionStateActionsTests\&.RegisterAction ()"

.PP
DotNetSolutionState\&.RegisterAction 
.PP
Definition at line \fB12\fP of file \fBDotNetSolutionStateActionsTests\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.DotNetSolutions\&.States\&.DotNetSolutionStateActionsTests\&.StateHasChanged ()"

.PP
DotNetSolutionState\&.StateHasChanged 
.PP
Definition at line \fB30\fP of file \fBDotNetSolutionStateActionsTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
