.TH "Luthetus.Extensions.DotNet.Tests.Basis.TestExplorers.Models.TestExplorerRenderBatchValidatedTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.Tests.Basis.TestExplorers.Models.TestExplorerRenderBatchValidatedTests \- TestExplorerRenderBatchValidated  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "TestExplorerRenderBatchValidated(TestExplorerRenderBatch) 
.br
----
.br
 TestExplorerRenderBatchValidated\&.TestExplorerState TestExplorerRenderBatchValidated\&.AppOptionsState TestExplorerRenderBatchValidated\&.TreeViewContainer "
.in -1c
.SH "Detailed Description"
.PP 
TestExplorerRenderBatchValidated 
.PP
Definition at line \fB6\fP of file \fBTestExplorerRenderBatchValidatedTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.TestExplorers\&.Models\&.TestExplorerRenderBatchValidatedTests\&.Constructor ()"

.PP
TestExplorerRenderBatchValidated(TestExplorerRenderBatch) 
.br
----
.br
 TestExplorerRenderBatchValidated\&.TestExplorerState TestExplorerRenderBatchValidated\&.AppOptionsState TestExplorerRenderBatchValidated\&.TreeViewContainer 
.PP
Definition at line \fB16\fP of file \fBTestExplorerRenderBatchValidatedTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
