.TH "Luthetus.Common.RazorLib.Dimensions.Models.DimensionUnit" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Dimensions.Models.DimensionUnit
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "double \fBValue\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "Func< double > \fBValueFunc\fP\fR [get, set]\fP"
.br
.RI "\fBDimensionUnit\fP should use the setter for either the property \fBValue\fP or '{nameof(ValueFunc)}', but not both\&. "
.ti -1c
.RI "\fBDimensionUnitKind\fP \fBDimensionUnitKind\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBDimensionOperatorKind\fP \fBDimensionOperatorKind\fP = \fBDimensionOperatorKind\&.Add\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBPurpose\fP = string\&.Empty\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBDimensionUnit\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBDimensionOperatorKind\fP Luthetus\&.Common\&.RazorLib\&.Dimensions\&.Models\&.DimensionUnit\&.DimensionOperatorKind = \fBDimensionOperatorKind\&.Add\fP\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB42\fP of file \fBDimensionUnit\&.cs\fP\&.
.SS "\fBDimensionUnitKind\fP Luthetus\&.Common\&.RazorLib\&.Dimensions\&.Models\&.DimensionUnit\&.DimensionUnitKind\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB41\fP of file \fBDimensionUnit\&.cs\fP\&.
.SS "string Luthetus\&.Common\&.RazorLib\&.Dimensions\&.Models\&.DimensionUnit\&.Purpose = string\&.Empty\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB43\fP of file \fBDimensionUnit\&.cs\fP\&.
.SS "double Luthetus\&.Common\&.RazorLib\&.Dimensions\&.Models\&.DimensionUnit\&.Value\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB9\fP of file \fBDimensionUnit\&.cs\fP\&.
.SS "Func<double> Luthetus\&.Common\&.RazorLib\&.Dimensions\&.Models\&.DimensionUnit\&.ValueFunc\fR [get]\fP, \fR [set]\fP"

.PP
\fBDimensionUnit\fP should use the setter for either the property \fBValue\fP or '{nameof(ValueFunc)}', but not both\&. TODO: change this implementation as it is a bit hacky\&.\&.\&. \&.\&.\&.The reason for this hacky addition was to support dimensions that are dependent on some other state\&. 
.PP
Definition at line \fB39\fP of file \fBDimensionUnit\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
