.TH "Luthetus.Common.Tests.Basis.Installations.Models.ServiceCollectionExtensionsTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Installations.Models.ServiceCollectionExtensionsTests \- ServiceCollectionExtensions  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAddLuthetusCommonServices\fP ()"
.br
.RI "RazorLib\&.Installations\&.Models\&.ServiceCollectionExtensions\&.AddLuthetusCommonServices(IServiceCollection, LuthetusHostingInformation, Func<LuthetusCommonConfig, LuthetusCommonConfig>?) "
.in -1c
.SH "Detailed Description"
.PP 
ServiceCollectionExtensions 
.PP
Definition at line \fB26\fP of file \fBServiceCollectionExtensionsTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Installations\&.Models\&.ServiceCollectionExtensionsTests\&.AddLuthetusCommonServices ()"

.PP
RazorLib\&.Installations\&.Models\&.ServiceCollectionExtensions\&.AddLuthetusCommonServices(IServiceCollection, LuthetusHostingInformation, Func<LuthetusCommonConfig, LuthetusCommonConfig>?) 
.PP
Definition at line \fB32\fP of file \fBServiceCollectionExtensionsTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
