.TH "Luthetus.Ide.RazorLib.ComponentRenderers.Models.IIdeComponentRenderers" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.ComponentRenderers.Models.IIdeComponentRenderers
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.IdeComponentRenderers\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "Type \fBBooleanPromptOrCancelRendererType\fP\fR [get]\fP"
.br
.ti -1c
.RI "Type \fBFileFormRendererType\fP\fR [get]\fP"
.br
.ti -1c
.RI "Type \fBDeleteFileFormRendererType\fP\fR [get]\fP"
.br
.ti -1c
.RI "Type \fBInputFileRendererType\fP\fR [get]\fP"
.br
.ti -1c
.RI "IdeTreeViews \fBIdeTreeViews\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBIIdeComponentRenderers\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Type Luthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.IIdeComponentRenderers\&.BooleanPromptOrCancelRendererType\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.IdeComponentRenderers\fP\&.
.PP
Definition at line \fB5\fP of file \fBIIdeComponentRenderers\&.cs\fP\&.
.SS "Type Luthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.IIdeComponentRenderers\&.DeleteFileFormRendererType\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.IdeComponentRenderers\fP\&.
.PP
Definition at line \fB7\fP of file \fBIIdeComponentRenderers\&.cs\fP\&.
.SS "Type Luthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.IIdeComponentRenderers\&.FileFormRendererType\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.IdeComponentRenderers\fP\&.
.PP
Definition at line \fB6\fP of file \fBIIdeComponentRenderers\&.cs\fP\&.
.SS "IdeTreeViews Luthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.IIdeComponentRenderers\&.IdeTreeViews\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.IdeComponentRenderers\fP\&.
.PP
Definition at line \fB9\fP of file \fBIIdeComponentRenderers\&.cs\fP\&.
.SS "Type Luthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.IIdeComponentRenderers\&.InputFileRendererType\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.IdeComponentRenderers\fP\&.
.PP
Definition at line \fB8\fP of file \fBIIdeComponentRenderers\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
