.TH "Luthetus.TextEditor.Tests.Basis.Events.BatchScrollEventsTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.Events.BatchScrollEventsTests \- BatchScrollEvents  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBThrottleMutateScrollHorizontalPositionByPixels\fP ()"
.br
.RI "BatchScrollEvents\&.ThrottleMutateScrollHorizontalPositionByPixels "
.ti -1c
.RI "void \fBThrottleMutateScrollVerticalPositionByPixels\fP ()"
.br
.RI "BatchScrollEvents\&.ThrottleMutateScrollVerticalPositionByPixels "
.ti -1c
.RI "void \fBThrottleSetScrollPosition\fP ()"
.br
.RI "BatchScrollEvents\&.ThrottleSetScrollPosition "
.ti -1c
.RI "void \fBMutateScrollHorizontalPositionByPixels\fP ()"
.br
.RI "BatchScrollEvents\&.MutateScrollHorizontalPositionByPixels "
.ti -1c
.RI "void \fBMutateScrollVerticalPositionByPixels\fP ()"
.br
.RI "BatchScrollEvents\&.MutateScrollVerticalPositionByPixels "
.in -1c
.SH "Detailed Description"
.PP 
BatchScrollEvents 
.PP
Definition at line \fB6\fP of file \fBBatchScrollEventsTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Events\&.BatchScrollEventsTests\&.MutateScrollHorizontalPositionByPixels ()"

.PP
BatchScrollEvents\&.MutateScrollHorizontalPositionByPixels 
.PP
Definition at line \fB39\fP of file \fBBatchScrollEventsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Events\&.BatchScrollEventsTests\&.MutateScrollVerticalPositionByPixels ()"

.PP
BatchScrollEvents\&.MutateScrollVerticalPositionByPixels 
.PP
Definition at line \fB48\fP of file \fBBatchScrollEventsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Events\&.BatchScrollEventsTests\&.ThrottleMutateScrollHorizontalPositionByPixels ()"

.PP
BatchScrollEvents\&.ThrottleMutateScrollHorizontalPositionByPixels 
.PP
Definition at line \fB12\fP of file \fBBatchScrollEventsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Events\&.BatchScrollEventsTests\&.ThrottleMutateScrollVerticalPositionByPixels ()"

.PP
BatchScrollEvents\&.ThrottleMutateScrollVerticalPositionByPixels 
.PP
Definition at line \fB21\fP of file \fBBatchScrollEventsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Events\&.BatchScrollEventsTests\&.ThrottleSetScrollPosition ()"

.PP
BatchScrollEvents\&.ThrottleSetScrollPosition 
.PP
Definition at line \fB30\fP of file \fBBatchScrollEventsTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
