.TH "Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Parsers.ExpressionAsStatementTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Parsers.ExpressionAsStatementTests \- Anything parsed starts off as a statement, then goes on to invoke the expression loop if the syntax is deemed an expression\&.  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTest\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBNumeric_Add_BinaryExpressionNode\fP ()"
.br
.ti -1c
.RI "void \fBNumeric_Add_BinaryExpressionNode_More\fP ()"
.br
.ti -1c
.RI "void \fBNumeric_Subtract_BinaryExpressionNode\fP ()"
.br
.ti -1c
.RI "void \fBNumeric_Star_BinaryExpressionNode\fP ()"
.br
.ti -1c
.RI "void \fBNumeric_Division_BinaryExpressionNode\fP ()"
.br
.ti -1c
.RI "void \fBNumeric_EqualsEquals_BinaryExpressionNode\fP ()"
.br
.ti -1c
.RI "void \fBString_BinaryExpressionNode\fP ()"
.br
.ti -1c
.RI "void \fBString_Interpolated\fP ()"
.br
.ti -1c
.RI "void \fBString_Verbatim\fP ()"
.br
.ti -1c
.RI "void \fBString_InterpolatedVerbatim\fP ()"
.br
.ti -1c
.RI "void \fBString_VerbatimInterpolated\fP ()"
.br
.ti -1c
.RI "void \fBChar_BinaryExpressionNode\fP ()"
.br
.ti -1c
.RI "void \fBBool_BinaryExpressionNode\fP ()"
.br
.ti -1c
.RI "void \fBParenthesizedExpressionNode_Test\fP ()"
.br
.ti -1c
.RI "void \fBShortCircuit\fP ()"
.br
.ti -1c
.RI "void \fBExplicitCastNode_IdentifierToken\fP ()"
.br
.ti -1c
.RI "void \fBExplicitCastNode_KeywordToken\fP ()"
.br
.ti -1c
.RI "void \fBFunctionInvocationNode_Basic\fP ()"
.br
.ti -1c
.RI "void \fBFunctionInvocationNode_Parameters\fP ()"
.br
.ti -1c
.RI "void \fBFunctionInvocationNode_Generic\fP ()"
.br
.ti -1c
.RI "void \fBFunctionInvocationNode_Generic_Parameters\fP ()"
.br
.ti -1c
.RI "void \fBConstructorInvocationNode_Basic\fP ()"
.br
.ti -1c
.RI "void \fBConstructorInvocationNode_Parameters\fP ()"
.br
.ti -1c
.RI "void \fBConstructorInvocationNode_Generic\fP ()"
.br
.ti -1c
.RI "void \fBConstructorInvocationNode_Generic_Parameters_MISSING_NumericLiteralToken_A\fP ()"
.br
.ti -1c
.RI "void \fBConstructorInvocationNode_Generic_Parameters_MISSING_NumericLiteralToken_B\fP ()"
.br
.ti -1c
.RI "void \fBConstructorInvocationNode_Generic_Parameters\fP ()"
.br
.ti -1c
.RI "void \fBConstructorInvocationNode_NoTypeClauseNode\fP ()"
.br
.ti -1c
.RI "void \fBObjectInitializationNode_Parameters_NoTrailingComma\fP ()"
.br
.ti -1c
.RI "void \fBObjectInitializationNode__Parameters_WithTrailingComma\fP ()"
.br
.ti -1c
.RI "void \fBObjectInitializationNode_NoParameters_NoTrailingComma\fP ()"
.br
.ti -1c
.RI "void \fBObjectInitializationNode_NoParameters_WithTrailingComma\fP ()"
.br
.ti -1c
.RI "void \fBObjectInitializationNode_WithParenthesis\fP ()"
.br
.ti -1c
.RI "void \fBCollectionInitializationNode_Parameters_NoTrailingComma\fP ()"
.br
.ti -1c
.RI "void \fBCollectionInitializationNode_Parameters_WithTrailingComma\fP ()"
.br
.ti -1c
.RI "void \fBCollectionInitializationNode_NoParameters_NoTrailingComma\fP ()"
.br
.ti -1c
.RI "void \fBCollectionInitializationNode_NoParameters_WithTrailingComma\fP ()"
.br
.ti -1c
.RI "void \fBCollectionInitializationNode_WithParenthesis\fP ()"
.br
.ti -1c
.RI "void \fBLambdaFunction_Expression_NoParameter\fP ()"
.br
.ti -1c
.RI "void \fBLambdaFunction_Expression_SingleParameter\fP ()"
.br
.ti -1c
.RI "void \fBLambdaFunction_Expression_ManyParameter_Async\fP ()"
.br
.ti -1c
.RI "void \fBLambdaFunction_CodeBlock_NoParameter_Async\fP ()"
.br
.ti -1c
.RI "void \fBLambdaFunction_CodeBlock_SingleParameter_Async\fP ()"
.br
.ti -1c
.RI "void \fBLambdaFunction_CodeBlock_ManyParameter\fP ()"
.br
.ti -1c
.RI "void \fBMethodGroup\fP ()"
.br
.ti -1c
.RI "void \fBAction_ImplicitInvocation_NoParameter\fP ()"
.br
.ti -1c
.RI "void \fBAction_ImplicitInvocation_SingleParameter\fP ()"
.br
.ti -1c
.RI "void \fBAction_ImplicitInvocation_ManyParameter\fP ()"
.br
.ti -1c
.RI "void \fBFunc_ImplicitInvocation_NoParameter\fP ()"
.br
.ti -1c
.RI "void \fBFunc_ImplicitInvocation_SingleParameter\fP ()"
.br
.ti -1c
.RI "void \fBFunc_ImplicitInvocation_ManyParameter\fP ()"
.br
.ti -1c
.RI "void \fBFunctionInvocation_NamedParameters\fP ()"
.br
.ti -1c
.RI "void \fBConstructorInvocation_NamedParameters\fP ()"
.br
.ti -1c
.RI "void \fBRecord_With_Keyword\fP ()"
.br
.ti -1c
.RI "void \fBGetterAndSetterThatAreNotAutoImplemented\fP ()"
.br
.ti -1c
.RI "void \fBMemberAccess\fP ()"
.br
.ti -1c
.RI "void \fBWhileLoop_DoNotBreakScope\fP ()"
.br
.RI "TODO: Repeat this test for all the control keywords\&. "
.ti -1c
.RI "void \fBIfStatement_StopExpressionsCreatingScope\fP ()"
.br
.ti -1c
.RI "void \fBCollectionIndex\fP ()"
.br
.ti -1c
.RI "void \fBAwaitTask\fP ()"
.br
.ti -1c
.RI "void \fBSwitchStatement\fP ()"
.br
.ti -1c
.RI "void \fBSwitchExpression\fP ()"
.br
.ti -1c
.RI "void \fBParenthesized_ExplicitCast\fP ()"
.br
.ti -1c
.RI "void \fBFunctionParameter_OutKeyword\fP ()"
.br
.ti -1c
.RI "void \fBLessThanBinaryOperator\fP ()"
.br
.ti -1c
.RI "void \fBGreaterThanBinaryOperator\fP ()"
.br
.ti -1c
.RI "void \fBLessThanEqualToBinaryOperator\fP ()"
.br
.ti -1c
.RI "void \fBGreaterThanEqualToBinaryOperator\fP ()"
.br
.ti -1c
.RI "void \fBFunctionParameterOptional\fP ()"
.br
.ti -1c
.RI "void \fBConstructorInvokesConstructor\fP ()"
.br
.ti -1c
.RI "void \fBValueTuple\fP ()"
.br
.ti -1c
.RI "void \fBFunctionInvocationExpressionStatement\fP ()"
.br
.RI "This parses incorrectly: 'Func(decimalPercentProgress);'\&. "
.ti -1c
.RI "void \fBTypeClauseNode_Identifier\fP ()"
.br
.ti -1c
.RI "void \fBTypeClauseNode_Keyword\fP ()"
.br
.ti -1c
.RI "void \fBTypeClauseNode_Var\fP ()"
.br
.ti -1c
.RI "void \fBTypeClauseNode_Generic\fP ()"
.br
.ti -1c
.RI "void \fBTypeClauseNode_Nullable_Keyword\fP ()"
.br
.ti -1c
.RI "void \fBTypeClauseNode_Nullable_Identifier\fP ()"
.br
.ti -1c
.RI "void \fBTypeClauseNode_GenericNullable\fP ()"
.br
.ti -1c
.RI "void \fBVariableAssignmentExpressionNode\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Anything parsed starts off as a statement, then goes on to invoke the expression loop if the syntax is deemed an expression\&. 

So, every test in \fBExpressionTests\fP needs to be replicated in this file\&.

.PP
And the difference between the tests is that \fBExpressionTests\fP needs to somehow start parsing the input as an expression\&.

.PP
This file parses the inputs as statements first, and goes into the expression loop when it is deemed necessary\&.

.PP
This brings up the question\&.\&.\&. should parsing be "statement first" or "expression first"? As of making this comment the \fBCSharpParser\fP is "statement first"\&. 
.PP
Definition at line \fB33\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.Action_ImplicitInvocation_ManyParameter ()"

.PP
Definition at line \fB1385\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.Action_ImplicitInvocation_NoParameter ()"

.PP
Definition at line \fB1353\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.Action_ImplicitInvocation_SingleParameter ()"

.PP
Definition at line \fB1369\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.AwaitTask ()"

.PP
Definition at line \fB1598\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.Bool_BinaryExpressionNode ()"

.PP
Definition at line \fB322\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.Char_BinaryExpressionNode ()"

.PP
Definition at line \fB298\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.CollectionIndex ()"

.PP
Definition at line \fB1591\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.CollectionInitializationNode_NoParameters_NoTrailingComma ()"

.PP
Definition at line \fB1011\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.CollectionInitializationNode_NoParameters_WithTrailingComma ()"

.PP
Definition at line \fB1039\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.CollectionInitializationNode_Parameters_NoTrailingComma ()"

.PP
Definition at line \fB861\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.CollectionInitializationNode_Parameters_WithTrailingComma ()"

.PP
Definition at line \fB905\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.CollectionInitializationNode_WithParenthesis ()"

.PP
Definition at line \fB1067\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.ConstructorInvocation_NamedParameters ()"

.PP
Definition at line \fB1465\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.ConstructorInvocationNode_Basic ()"

.PP
Definition at line \fB504\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.ConstructorInvocationNode_Generic ()"

.PP
Definition at line \fB552\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.ConstructorInvocationNode_Generic_Parameters ()"

.PP
Definition at line \fB619\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.ConstructorInvocationNode_Generic_Parameters_MISSING_NumericLiteralToken_A ()"

.PP
Definition at line \fB578\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.ConstructorInvocationNode_Generic_Parameters_MISSING_NumericLiteralToken_B ()"

.PP
Definition at line \fB590\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.ConstructorInvocationNode_NoTypeClauseNode ()"

.PP
Definition at line \fB657\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.ConstructorInvocationNode_Parameters ()"

.PP
Definition at line \fB526\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.ConstructorInvokesConstructor ()"

.PP
Definition at line \fB1807\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.ExplicitCastNode_IdentifierToken ()"

.PP
Definition at line \fB386\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.ExplicitCastNode_KeywordToken ()"

.PP
Definition at line \fB397\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.Func_ImplicitInvocation_ManyParameter ()"

.PP
Definition at line \fB1433\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.Func_ImplicitInvocation_NoParameter ()"

.PP
Definition at line \fB1401\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.Func_ImplicitInvocation_SingleParameter ()"

.PP
Definition at line \fB1417\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.FunctionInvocation_NamedParameters ()"

.PP
Definition at line \fB1449\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.FunctionInvocationExpressionStatement ()"

.PP
This parses incorrectly: 'Func(decimalPercentProgress);'\&. Whereas this parses fine: 'var x = Func(decimalPercentProgress);'

.PP
The reason is suspected to be the transition from the 'statement' parser loop to the 'expression' parser loop\&.

.PP
It actually seems to be related to 'int decimalPercentProgress;', i\&.e\&.: declaring the variable results in it erroneously being interpreted as a \fBTypeClauseNode\fP, yet if it is undeclared then it comes out to be \fBVariableReferenceNode\fP\&. 
.PP
Definition at line \fB1862\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.FunctionInvocationNode_Basic ()"

.PP
Definition at line \fB406\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.FunctionInvocationNode_Generic ()"

.PP
Definition at line \fB442\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.FunctionInvocationNode_Generic_Parameters ()"

.PP
Definition at line \fB468\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.FunctionInvocationNode_Parameters ()"

.PP
Definition at line \fB420\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.FunctionParameter_OutKeyword ()"

.PP
Definition at line \fB1716\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.FunctionParameterOptional ()"

.PP
Definition at line \fB1759\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.GetterAndSetterThatAreNotAutoImplemented ()"

.PP
Definition at line \fB1493\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.GreaterThanBinaryOperator ()"

.PP
Definition at line \fB1732\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.GreaterThanEqualToBinaryOperator ()"

.PP
Definition at line \fB1750\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.IfStatement_StopExpressionsCreatingScope ()"

.PP
Definition at line \fB1553\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.LambdaFunction_CodeBlock_ManyParameter ()"

.PP
Definition at line \fB1326\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.LambdaFunction_CodeBlock_NoParameter_Async ()"

.PP
Definition at line \fB1304\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.LambdaFunction_CodeBlock_SingleParameter_Async ()"

.PP
Definition at line \fB1315\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.LambdaFunction_Expression_ManyParameter_Async ()"

.PP
Definition at line \fB1274\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.LambdaFunction_Expression_NoParameter ()"

.PP
Definition at line \fB1099\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.LambdaFunction_Expression_SingleParameter ()"

.PP
Definition at line \fB1110\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.LessThanBinaryOperator ()"

.PP
Definition at line \fB1723\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.LessThanEqualToBinaryOperator ()"

.PP
Definition at line \fB1741\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.MemberAccess ()"

.PP
Definition at line \fB1523\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.MethodGroup ()"

.PP
Definition at line \fB1337\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.Numeric_Add_BinaryExpressionNode ()"

.PP
Definition at line \fB55\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.Numeric_Add_BinaryExpressionNode_More ()"

.PP
Definition at line \fB79\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.Numeric_Division_BinaryExpressionNode ()"

.PP
Definition at line \fB186\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.Numeric_EqualsEquals_BinaryExpressionNode ()"

.PP
Definition at line \fB210\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.Numeric_Star_BinaryExpressionNode ()"

.PP
Definition at line \fB162\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.Numeric_Subtract_BinaryExpressionNode ()"

.PP
Definition at line \fB138\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.ObjectInitializationNode__Parameters_WithTrailingComma ()"

.PP
Definition at line \fB728\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.ObjectInitializationNode_NoParameters_NoTrailingComma ()"

.PP
Definition at line \fB774\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.ObjectInitializationNode_NoParameters_WithTrailingComma ()"

.PP
Definition at line \fB802\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.ObjectInitializationNode_Parameters_NoTrailingComma ()"

.PP
Definition at line \fB680\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.ObjectInitializationNode_WithParenthesis ()"

.PP
Definition at line \fB830\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.Parenthesized_ExplicitCast ()"

.PP
Definition at line \fB1709\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.ParenthesizedExpressionNode_Test ()"

.PP
Definition at line \fB346\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.Record_With_Keyword ()"

.PP
Definition at line \fB1481\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.ShortCircuit ()"

.PP
Definition at line \fB363\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.String_BinaryExpressionNode ()"

.PP
Definition at line \fB234\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.String_Interpolated ()"

.PP
Definition at line \fB258\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.String_InterpolatedVerbatim ()"

.PP
Definition at line \fB278\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.String_Verbatim ()"

.PP
Definition at line \fB268\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.String_VerbatimInterpolated ()"

.PP
Definition at line \fB288\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.SwitchExpression ()"

.PP
Definition at line \fB1693\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.SwitchStatement ()"

.PP
Definition at line \fB1605\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.TypeClauseNode_Generic ()"

.PP
Definition at line \fB1922\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.TypeClauseNode_GenericNullable ()"

.PP
Definition at line \fB1952\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.TypeClauseNode_Identifier ()"

.PP
Definition at line \fB1891\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.TypeClauseNode_Keyword ()"

.PP
Definition at line \fB1902\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.TypeClauseNode_Nullable_Identifier ()"

.PP
Definition at line \fB1942\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.TypeClauseNode_Nullable_Keyword ()"

.PP
Definition at line \fB1932\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.TypeClauseNode_Var ()"

.PP
Definition at line \fB1912\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.ValueTuple ()"

.PP
Definition at line \fB1825\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.VariableAssignmentExpressionNode ()"

.PP
Definition at line \fB1962\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ExpressionAsStatementTests\&.WhileLoop_DoNotBreakScope ()"

.PP
TODO: Repeat this test for all the control keywords\&. 
.PP
Definition at line \fB1541\fP of file \fBExpressionAsStatementTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
