.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.GenericArgumentsListingNodeTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.GenericArgumentsListingNodeTests \- \fBGenericArgumentsListingNode\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "GenericArgumentsListingNode(OpenAngleBracketToken, ImmutableArray<GenericArgumentEntryNode>, CloseAngleBracketToken) 
.br
----
.br
 \fBGenericArgumentsListingNode\&.OpenAngleBracketToken\fP \fBGenericArgumentsListingNode\&.GenericArgumentEntryNodeList\fP \fBGenericArgumentsListingNode\&.CloseAngleBracketToken\fP GenericArgumentsListingNode\&.ChildList \fBGenericArgumentsListingNode\&.IsFabricated\fP \fBGenericArgumentsListingNode\&.SyntaxKind\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBGenericArgumentsListingNode\fP 
.PP
Definition at line \fB11\fP of file \fBGenericArgumentsListingNodeTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.Syntax\&.SyntaxNodes\&.GenericArgumentsListingNodeTests\&.Constructor ()"

.PP
GenericArgumentsListingNode(OpenAngleBracketToken, ImmutableArray<GenericArgumentEntryNode>, CloseAngleBracketToken) 
.br
----
.br
 \fBGenericArgumentsListingNode\&.OpenAngleBracketToken\fP \fBGenericArgumentsListingNode\&.GenericArgumentEntryNodeList\fP \fBGenericArgumentsListingNode\&.CloseAngleBracketToken\fP GenericArgumentsListingNode\&.ChildList \fBGenericArgumentsListingNode\&.IsFabricated\fP \fBGenericArgumentsListingNode\&.SyntaxKind\fP 
.PP
Definition at line \fB24\fP of file \fBGenericArgumentsListingNodeTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
