.TH "Luthetus.Common.RazorLib.ComponentRenderers.Models.CommonTreeViews" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.ComponentRenderers.Models.CommonTreeViews
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommonTreeViews\fP (Type treeViewExceptionRendererType, Type treeViewMissingRendererFallbackType, Type treeViewTextRenderer, Type treeViewReflectionRenderer, Type treeViewPropertiesRenderer, Type treeViewInterfaceImplementationRenderer, Type treeViewFieldsRenderer, Type treeViewExceptionRenderer, Type treeViewEnumerableRenderer)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Type \fBTreeViewExceptionRendererType\fP\fR [get]\fP"
.br
.ti -1c
.RI "Type \fBTreeViewMissingRendererFallbackType\fP\fR [get]\fP"
.br
.ti -1c
.RI "Type \fBTreeViewTextRenderer\fP\fR [get]\fP"
.br
.ti -1c
.RI "Type \fBTreeViewReflectionRenderer\fP\fR [get]\fP"
.br
.ti -1c
.RI "Type \fBTreeViewPropertiesRenderer\fP\fR [get]\fP"
.br
.ti -1c
.RI "Type \fBTreeViewInterfaceImplementationRenderer\fP\fR [get]\fP"
.br
.ti -1c
.RI "Type \fBTreeViewFieldsRenderer\fP\fR [get]\fP"
.br
.ti -1c
.RI "Type \fBTreeViewExceptionRenderer\fP\fR [get]\fP"
.br
.ti -1c
.RI "Type \fBTreeViewEnumerableRenderer\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBCommonTreeViews\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Common\&.RazorLib\&.ComponentRenderers\&.Models\&.CommonTreeViews\&.CommonTreeViews (Type treeViewExceptionRendererType, Type treeViewMissingRendererFallbackType, Type treeViewTextRenderer, Type treeViewReflectionRenderer, Type treeViewPropertiesRenderer, Type treeViewInterfaceImplementationRenderer, Type treeViewFieldsRenderer, Type treeViewExceptionRenderer, Type treeViewEnumerableRenderer)"

.PP
Definition at line \fB5\fP of file \fBCommonTreeViews\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Type Luthetus\&.Common\&.RazorLib\&.ComponentRenderers\&.Models\&.CommonTreeViews\&.TreeViewEnumerableRenderer\fR [get]\fP"

.PP
Definition at line \fB35\fP of file \fBCommonTreeViews\&.cs\fP\&.
.SS "Type Luthetus\&.Common\&.RazorLib\&.ComponentRenderers\&.Models\&.CommonTreeViews\&.TreeViewExceptionRenderer\fR [get]\fP"

.PP
Definition at line \fB34\fP of file \fBCommonTreeViews\&.cs\fP\&.
.SS "Type Luthetus\&.Common\&.RazorLib\&.ComponentRenderers\&.Models\&.CommonTreeViews\&.TreeViewExceptionRendererType\fR [get]\fP"

.PP
Definition at line \fB27\fP of file \fBCommonTreeViews\&.cs\fP\&.
.SS "Type Luthetus\&.Common\&.RazorLib\&.ComponentRenderers\&.Models\&.CommonTreeViews\&.TreeViewFieldsRenderer\fR [get]\fP"

.PP
Definition at line \fB33\fP of file \fBCommonTreeViews\&.cs\fP\&.
.SS "Type Luthetus\&.Common\&.RazorLib\&.ComponentRenderers\&.Models\&.CommonTreeViews\&.TreeViewInterfaceImplementationRenderer\fR [get]\fP"

.PP
Definition at line \fB32\fP of file \fBCommonTreeViews\&.cs\fP\&.
.SS "Type Luthetus\&.Common\&.RazorLib\&.ComponentRenderers\&.Models\&.CommonTreeViews\&.TreeViewMissingRendererFallbackType\fR [get]\fP"

.PP
Definition at line \fB28\fP of file \fBCommonTreeViews\&.cs\fP\&.
.SS "Type Luthetus\&.Common\&.RazorLib\&.ComponentRenderers\&.Models\&.CommonTreeViews\&.TreeViewPropertiesRenderer\fR [get]\fP"

.PP
Definition at line \fB31\fP of file \fBCommonTreeViews\&.cs\fP\&.
.SS "Type Luthetus\&.Common\&.RazorLib\&.ComponentRenderers\&.Models\&.CommonTreeViews\&.TreeViewReflectionRenderer\fR [get]\fP"

.PP
Definition at line \fB30\fP of file \fBCommonTreeViews\&.cs\fP\&.
.SS "Type Luthetus\&.Common\&.RazorLib\&.ComponentRenderers\&.Models\&.CommonTreeViews\&.TreeViewTextRenderer\fR [get]\fP"

.PP
Definition at line \fB29\fP of file \fBCommonTreeViews\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
