.TH "Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Lexers.LexerTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Lexers.LexerTests
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBLEX_ArraySyntaxToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_AssociatedNameToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_AssociatedValueToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_BadToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_BangToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_CloseAngleBracketToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_CloseAssociatedGroupToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_CloseBraceToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_CloseParenthesisToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_CloseSquareBracketToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_ColonToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_CommaToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_CommentMultiLineToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_CommentSingleLineToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_DollarSignToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_EndOfFileToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_EqualsEqualsToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_EqualsToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_IdentifierToken\fP (string sourceText)"
.br
.ti -1c
.RI "void \fBLEX_KeywordContextualToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_KeywordToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_LibraryReferenceToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_MemberAccessToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_MinusMinusToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_MinusToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_NumericLiteralToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_OpenAngleBracketToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_OpenAssociatedGroupToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_OpenBraceToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_OpenParenthesisToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_OpenSquareBracketToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_PlusPlusToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_PlusToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_PreprocessorDirectiveToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_QuestionMarkQuestionMarkToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_QuestionMarkToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_StarToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_StatementDelimiterToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_StringLiteralToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_TriviaToken\fP ()"
.br
.ti -1c
.RI "void \fBLEX_EscapedStrings\fP ()"
.br
.ti -1c
.RI "void \fBLEX_ClassDefinition\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBLexerTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_ArraySyntaxToken ()"

.PP
Definition at line \fB11\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_AssociatedNameToken ()"

.PP
Definition at line \fB17\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_AssociatedValueToken ()"

.PP
Definition at line \fB23\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_BadToken ()"

.PP
Definition at line \fB29\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_BangToken ()"

.PP
Definition at line \fB35\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_ClassDefinition ()"

.PP
Definition at line \fB547\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_CloseAngleBracketToken ()"

.PP
Definition at line \fB50\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_CloseAssociatedGroupToken ()"

.PP
Definition at line \fB65\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_CloseBraceToken ()"

.PP
Definition at line \fB71\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_CloseParenthesisToken ()"

.PP
Definition at line \fB86\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_CloseSquareBracketToken ()"

.PP
Definition at line \fB101\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_ColonToken ()"

.PP
Definition at line \fB116\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_CommaToken ()"

.PP
Definition at line \fB131\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_CommentMultiLineToken ()"

.PP
Definition at line \fB146\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_CommentSingleLineToken ()"

.PP
Definition at line \fB152\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_DollarSignToken ()"

.PP
Definition at line \fB158\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_EndOfFileToken ()"

.PP
Definition at line \fB173\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_EqualsEqualsToken ()"

.PP
Definition at line \fB179\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_EqualsToken ()"

.PP
Definition at line \fB194\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_EscapedStrings ()"

.PP
Definition at line \fB536\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_IdentifierToken (string sourceText)"

.PP
Definition at line \fB261\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_KeywordContextualToken ()"

.PP
Definition at line \fB275\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_KeywordToken ()"

.PP
Definition at line \fB281\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_LibraryReferenceToken ()"

.PP
Definition at line \fB287\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_MemberAccessToken ()"

.PP
Definition at line \fB293\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_MinusMinusToken ()"

.PP
Definition at line \fB308\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_MinusToken ()"

.PP
Definition at line \fB323\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_NumericLiteralToken ()"

.PP
Definition at line \fB338\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_OpenAngleBracketToken ()"

.PP
Definition at line \fB353\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_OpenAssociatedGroupToken ()"

.PP
Definition at line \fB368\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_OpenBraceToken ()"

.PP
Definition at line \fB374\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_OpenParenthesisToken ()"

.PP
Definition at line \fB389\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_OpenSquareBracketToken ()"

.PP
Definition at line \fB404\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_PlusPlusToken ()"

.PP
Definition at line \fB419\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_PlusToken ()"

.PP
Definition at line \fB434\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_PreprocessorDirectiveToken ()"

.PP
Definition at line \fB449\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_QuestionMarkQuestionMarkToken ()"

.PP
Definition at line \fB455\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_QuestionMarkToken ()"

.PP
Definition at line \fB470\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_StarToken ()"

.PP
Definition at line \fB485\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_StatementDelimiterToken ()"

.PP
Definition at line \fB500\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_StringLiteralToken ()"

.PP
Definition at line \fB515\fP of file \fBLexerTests\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Lexers\&.LexerTests\&.LEX_TriviaToken ()"

.PP
Definition at line \fB530\fP of file \fBLexerTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
