.TH "Luthetus.Extensions.Git.States" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.Git.States
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "partial record \fBGitState\fP (\fBGitRepo\fP? Repo, ImmutableList< \fBGitFile\fP > UntrackedFileList, ImmutableList< \fBGitFile\fP > StagedFileList, ImmutableList< \fBGitFile\fP > UnstagedFileList, ImmutableList< \fBGitFile\fP > SelectedFileList, ImmutableList< \fBGitTask\fP > ActiveTasks, string? Origin, string? Branch, string? Upstream, ImmutableList< string > BranchList, int? BehindByCommitCount, int? AheadByCommitCount)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "partial record Luthetus\&.Extensions\&.Git\&.States\&.GitState (\fBGitRepo\fP? Repo, ImmutableList< \fBGitFile\fP > UntrackedFileList, ImmutableList< \fBGitFile\fP > StagedFileList, ImmutableList< \fBGitFile\fP > UnstagedFileList, ImmutableList< \fBGitFile\fP > SelectedFileList, ImmutableList< \fBGitTask\fP > ActiveTasks, string? Origin, string? Branch, string? Upstream, ImmutableList< string > BranchList, int? BehindByCommitCount, int? AheadByCommitCount)"

.PP
Definition at line \fB10\fP of file \fBGitState\&.Main\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
