.TH "Luthetus.CompilerServices.Xml.Html.IHtmlSyntaxNode" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.Xml.Html.IHtmlSyntaxNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.IHtmlSyntax\fP\&.
.PP
Inherited by \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.AttributeNameNode\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.AttributeNode\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.AttributeValueNode\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.CommentNode\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.InjectedLanguageFragmentNode\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.TagNameNode\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.TagNode\fP, and \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.TextNode\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "ImmutableArray< \fBIHtmlSyntax\fP > \fBChildContent\fP\fR [get]\fP"
.br
.ti -1c
.RI "ImmutableArray< \fBIHtmlSyntax\fP > \fBChildren\fP\fR [get]\fP"
.br
.ti -1c
.RI "TextEditorTextSpan \fBTextEditorTextSpan\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.IHtmlSyntax\fP
.in +1c
.ti -1c
.RI "\fBHtmlSyntaxKind\fP \fBHtmlSyntaxKind\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBIHtmlSyntaxNode\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "ImmutableArray<\fBIHtmlSyntax\fP> Luthetus\&.CompilerServices\&.Xml\&.Html\&.IHtmlSyntaxNode\&.ChildContent\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.AttributeNameNode\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.AttributeNode\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.AttributeValueNode\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.CommentNode\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.InjectedLanguageFragmentNode\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.TagNameNode\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.TagNode\fP, and \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.TextNode\fP\&.
.PP
Definition at line \fB8\fP of file \fBIHtmlSyntaxNode\&.cs\fP\&.
.SS "ImmutableArray<\fBIHtmlSyntax\fP> Luthetus\&.CompilerServices\&.Xml\&.Html\&.IHtmlSyntaxNode\&.Children\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.AttributeNameNode\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.AttributeNode\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.AttributeValueNode\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.CommentNode\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.InjectedLanguageFragmentNode\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.TagNameNode\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.TagNode\fP, and \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.TextNode\fP\&.
.PP
Definition at line \fB9\fP of file \fBIHtmlSyntaxNode\&.cs\fP\&.
.SS "TextEditorTextSpan Luthetus\&.CompilerServices\&.Xml\&.Html\&.IHtmlSyntaxNode\&.TextEditorTextSpan\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.AttributeNameNode\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.AttributeNode\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.AttributeValueNode\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.CommentNode\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.InjectedLanguageFragmentNode\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.TagNameNode\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.TagNode\fP, and \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxObjects\&.TextNode\fP\&.
.PP
Definition at line \fB10\fP of file \fBIHtmlSyntaxNode\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
