.TH "Luthetus.TextEditor.Tests.Basis.Diffs.Models.DiffApiTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.Diffs.Models.DiffApiTests \- ITextEditorService\&.TextEditorDiffApi  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "ITextEditorService\&.TextEditorDiffApi\&.TextEditorDiffApi(ITextEditorService, IDispatcher) "
.ti -1c
.RI "void \fBRegister\fP ()"
.br
.RI "ITextEditorService\&.TextEditorDiffApi\&.Register(Key<TextEditorDiffModel>, Key<TextEditorViewModel>, Key<TextEditorViewModel>) "
.ti -1c
.RI "void \fBFindOrDefault\fP ()"
.br
.RI "ITextEditorService\&.TextEditorDiffApi\&.GetOrDefault(Key<TextEditorDiffModel>) "
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.RI "ITextEditorService\&.TextEditorDiffApi\&.Dispose(Key<TextEditorDiffModel>) "
.ti -1c
.RI "void \fBCalculate\fP ()"
.br
.RI "ITextEditorService\&.TextEditorDiffApi\&.Calculate(Key<TextEditorDiffModel>, CancellationToken) "
.in -1c
.SH "Detailed Description"
.PP 
ITextEditorService\&.TextEditorDiffApi 
.PP
Definition at line \fB6\fP of file \fBDiffApiTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Diffs\&.Models\&.DiffApiTests\&.Calculate ()"

.PP
ITextEditorService\&.TextEditorDiffApi\&.Calculate(Key<TextEditorDiffModel>, CancellationToken) 
.PP
Definition at line \fB48\fP of file \fBDiffApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Diffs\&.Models\&.DiffApiTests\&.Constructor ()"

.PP
ITextEditorService\&.TextEditorDiffApi\&.TextEditorDiffApi(ITextEditorService, IDispatcher) 
.PP
Definition at line \fB12\fP of file \fBDiffApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Diffs\&.Models\&.DiffApiTests\&.Dispose ()"

.PP
ITextEditorService\&.TextEditorDiffApi\&.Dispose(Key<TextEditorDiffModel>) 
.PP
Definition at line \fB39\fP of file \fBDiffApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Diffs\&.Models\&.DiffApiTests\&.FindOrDefault ()"

.PP
ITextEditorService\&.TextEditorDiffApi\&.GetOrDefault(Key<TextEditorDiffModel>) 
.PP
Definition at line \fB30\fP of file \fBDiffApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Diffs\&.Models\&.DiffApiTests\&.Register ()"

.PP
ITextEditorService\&.TextEditorDiffApi\&.Register(Key<TextEditorDiffModel>, Key<TextEditorViewModel>, Key<TextEditorViewModel>) 
.PP
Definition at line \fB21\fP of file \fBDiffApiTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
