.TH "Luthetus.Common.Tests.Basis.WatchWindows.Models.TreeViewPropertiesTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.WatchWindows.Models.TreeViewPropertiesTests \- \fBTreeViewProperties\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "TreeViewProperties(WatchWindowObject, bool, bool, ILuthetusCommonComponentRenderers) "
.ti -1c
.RI "void \fBEquals_Test\fP ()"
.br
.RI "\fBTreeViewProperties\&.Equals(object?)\fP "
.ti -1c
.RI "void \fBGetHashCode_Test\fP ()"
.br
.RI "\fBTreeViewProperties\&.GetHashCode()\fP "
.ti -1c
.RI "void \fBGetTreeViewRenderer\fP ()"
.br
.RI "\fBTreeViewProperties\&.GetTreeViewRenderer()\fP "
.ti -1c
.RI "void \fBLoadChildListAsync\fP ()"
.br
.RI "\fBTreeViewProperties\&.LoadChildListAsync()\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBTreeViewProperties\fP 
.PP
Definition at line \fB8\fP of file \fBTreeViewPropertiesTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.WatchWindows\&.Models\&.TreeViewPropertiesTests\&.Constructor ()"

.PP
TreeViewProperties(WatchWindowObject, bool, bool, ILuthetusCommonComponentRenderers) 
.PP
Definition at line \fB14\fP of file \fBTreeViewPropertiesTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.WatchWindows\&.Models\&.TreeViewPropertiesTests\&.Equals_Test ()"

.PP
\fBTreeViewProperties\&.Equals(object?)\fP 
.PP
Definition at line \fB46\fP of file \fBTreeViewPropertiesTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.WatchWindows\&.Models\&.TreeViewPropertiesTests\&.GetHashCode_Test ()"

.PP
\fBTreeViewProperties\&.GetHashCode()\fP 
.PP
Definition at line \fB94\fP of file \fBTreeViewPropertiesTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.WatchWindows\&.Models\&.TreeViewPropertiesTests\&.GetTreeViewRenderer ()"

.PP
\fBTreeViewProperties\&.GetTreeViewRenderer()\fP 
.PP
Definition at line \fB121\fP of file \fBTreeViewPropertiesTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.WatchWindows\&.Models\&.TreeViewPropertiesTests\&.LoadChildListAsync ()"

.PP
\fBTreeViewProperties\&.LoadChildListAsync()\fP 
.PP
Definition at line \fB159\fP of file \fBTreeViewPropertiesTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
