.TH "Luthetus.Ide.RazorLib.Terminals.Models.ITerminalOutput" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.Terminals.Models.ITerminalOutput \- Output Data\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits IDisposable\&.
.PP
Inherited by \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutput\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBWriteOutput\fP (\fBTerminalCommandParsed\fP terminalCommandParsed, CommandEvent commandEvent)"
.br
.ti -1c
.RI "void \fBClearOutput\fP ()"
.br
.RI "Guaranteed to clear the output\&. "
.ti -1c
.RI "void \fBClearOutputExceptMostRecentCommand\fP ()"
.br
.RI "Guaranteed to clear the output, but will keep the most recent command\&. "
.ti -1c
.RI "void \fBClearHistoryWhenExistingOutputTooLong\fP ()"
.br
.RI "Conditionally clear the output\&. "
.ti -1c
.RI "\fBITerminalOutputFormatted\fP \fBGetOutputFormatted\fP (string terminalOutputFormatterName)"
.br
.ti -1c
.RI "\fBTerminalCommandParsed\fP? \fBGetParsedCommandOrDefault\fP (Key< \fBTerminalCommandRequest\fP > terminalCommandRequestKey)"
.br
.ti -1c
.RI "ImmutableList< \fBTerminalCommandParsed\fP > \fBGetParsedCommandList\fP ()"
.br
.ti -1c
.RI "int \fBGetParsedCommandListCount\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "ImmutableList< \fBITerminalOutputFormatter\fP > \fBOutputFormatterList\fP\fR [get]\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "Action? \fBOnWriteOutput\fP"
.br
.RI "TODO: Make this 'Action<Key<TerminalCommandParsed>>?' so one can track the output of a specific command as it is being executed? "
.in -1c
.SH "Detailed Description"
.PP 
Output Data\&. 
.PP
Definition at line \fB8\fP of file \fBITerminalOutput\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.ITerminalOutput\&.ClearHistoryWhenExistingOutputTooLong ()"

.PP
Conditionally clear the output\&. 
.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutput\fP\&.
.SS "void Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.ITerminalOutput\&.ClearOutput ()"

.PP
Guaranteed to clear the output\&. 
.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutput\fP\&.
.SS "void Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.ITerminalOutput\&.ClearOutputExceptMostRecentCommand ()"

.PP
Guaranteed to clear the output, but will keep the most recent command\&. 
.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutput\fP\&.
.SS "\fBITerminalOutputFormatted\fP Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.ITerminalOutput\&.GetOutputFormatted (string terminalOutputFormatterName)"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutput\fP\&.
.SS "ImmutableList< \fBTerminalCommandParsed\fP > Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.ITerminalOutput\&.GetParsedCommandList ()"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutput\fP\&.
.SS "int Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.ITerminalOutput\&.GetParsedCommandListCount ()"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutput\fP\&.
.SS "\fBTerminalCommandParsed\fP? Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.ITerminalOutput\&.GetParsedCommandOrDefault (Key< \fBTerminalCommandRequest\fP > terminalCommandRequestKey)"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutput\fP\&.
.SS "void Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.ITerminalOutput\&.WriteOutput (\fBTerminalCommandParsed\fP terminalCommandParsed, CommandEvent commandEvent)"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutput\fP\&.
.SH "Property Documentation"
.PP 
.SS "ImmutableList<\fBITerminalOutputFormatter\fP> Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.ITerminalOutput\&.OutputFormatterList\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutput\fP\&.
.PP
Definition at line \fB10\fP of file \fBITerminalOutput\&.cs\fP\&.
.SH "Event Documentation"
.PP 
.SS "Action? Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.ITerminalOutput\&.OnWriteOutput"

.PP
TODO: Make this 'Action<Key<TerminalCommandParsed>>?' so one can track the output of a specific command as it is being executed? 
.PP
Definition at line \fB16\fP of file \fBITerminalOutput\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
