.TH "Luthetus.Common.Tests.Basis.TreeViews.Models.TreeViewKeyboardEventHandlerTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.TreeViews.Models.TreeViewKeyboardEventHandlerTests \- \fBTreeViewKeyboardEventHandler\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "TreeViewKeyboardEventHandler(ITreeViewService) "
.ti -1c
.RI "async Task \fBOnKeyDown_MoveLeft\fP ()"
.br
.RI "\fBTreeViewKeyboardEventHandler\&.OnKeyDown(TreeViewCommandArgs)\fP "
.ti -1c
.RI "async Task \fBOnKeyDown_MoveDown\fP ()"
.br
.RI "\fBTreeViewKeyboardEventHandler\&.OnKeyDown(TreeViewCommandArgs)\fP "
.ti -1c
.RI "async Task \fBOnKeyDown_MoveUp\fP ()"
.br
.RI "\fBTreeViewKeyboardEventHandler\&.OnKeyDown(TreeViewCommandArgs)\fP "
.ti -1c
.RI "async Task \fBOnKeyDown_MoveRight_NOT_IsExpandedAsync\fP ()"
.br
.RI "\fBTreeViewKeyboardEventHandler\&.OnKeyDown(TreeViewCommandArgs)\fP "
.ti -1c
.RI "async Task \fBOnKeyDown_MoveRight_IsExpandedAsync\fP ()"
.br
.RI "\fBTreeViewKeyboardEventHandler\&.OnKeyDown(TreeViewCommandArgs)\fP "
.ti -1c
.RI "async Task \fBOnKeyDown_MoveHomeAsync\fP ()"
.br
.RI "\fBTreeViewKeyboardEventHandler\&.OnKeyDown(TreeViewCommandArgs)\fP "
.ti -1c
.RI "async Task \fBOnKeyDown_MoveEndAsync\fP ()"
.br
.RI "\fBTreeViewKeyboardEventHandler\&.OnKeyDown(TreeViewCommandArgs)\fP "
.ti -1c
.RI "void \fBOnKeyDownAsync\fP ()"
.br
.RI "\fBTreeViewKeyboardEventHandler\&.OnKeyDownAsync(TreeViewCommandArgs)\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBTreeViewKeyboardEventHandler\fP 
.PP
Definition at line \fB22\fP of file \fBTreeViewKeyboardEventHandlerTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.Models\&.TreeViewKeyboardEventHandlerTests\&.Constructor ()"

.PP
TreeViewKeyboardEventHandler(ITreeViewService) 
.PP
Definition at line \fB28\fP of file \fBTreeViewKeyboardEventHandlerTests\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.Models\&.TreeViewKeyboardEventHandlerTests\&.OnKeyDown_MoveDown ()"

.PP
\fBTreeViewKeyboardEventHandler\&.OnKeyDown(TreeViewCommandArgs)\fP 
.PP
Definition at line \fB147\fP of file \fBTreeViewKeyboardEventHandlerTests\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.Models\&.TreeViewKeyboardEventHandlerTests\&.OnKeyDown_MoveEndAsync ()"

.PP
\fBTreeViewKeyboardEventHandler\&.OnKeyDown(TreeViewCommandArgs)\fP 
.PP
Definition at line \fB469\fP of file \fBTreeViewKeyboardEventHandlerTests\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.Models\&.TreeViewKeyboardEventHandlerTests\&.OnKeyDown_MoveHomeAsync ()"

.PP
\fBTreeViewKeyboardEventHandler\&.OnKeyDown(TreeViewCommandArgs)\fP 
.PP
Definition at line \fB389\fP of file \fBTreeViewKeyboardEventHandlerTests\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.Models\&.TreeViewKeyboardEventHandlerTests\&.OnKeyDown_MoveLeft ()"

.PP
\fBTreeViewKeyboardEventHandler\&.OnKeyDown(TreeViewCommandArgs)\fP 
.PP
Definition at line \fB50\fP of file \fBTreeViewKeyboardEventHandlerTests\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.Models\&.TreeViewKeyboardEventHandlerTests\&.OnKeyDown_MoveRight_IsExpandedAsync ()"

.PP
\fBTreeViewKeyboardEventHandler\&.OnKeyDown(TreeViewCommandArgs)\fP 
.PP
Definition at line \fB328\fP of file \fBTreeViewKeyboardEventHandlerTests\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.Models\&.TreeViewKeyboardEventHandlerTests\&.OnKeyDown_MoveRight_NOT_IsExpandedAsync ()"

.PP
\fBTreeViewKeyboardEventHandler\&.OnKeyDown(TreeViewCommandArgs)\fP 
.PP
Definition at line \fB287\fP of file \fBTreeViewKeyboardEventHandlerTests\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.Models\&.TreeViewKeyboardEventHandlerTests\&.OnKeyDown_MoveUp ()"

.PP
\fBTreeViewKeyboardEventHandler\&.OnKeyDown(TreeViewCommandArgs)\fP 
.PP
Definition at line \fB207\fP of file \fBTreeViewKeyboardEventHandlerTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.Models\&.TreeViewKeyboardEventHandlerTests\&.OnKeyDownAsync ()"

.PP
\fBTreeViewKeyboardEventHandler\&.OnKeyDownAsync(TreeViewCommandArgs)\fP 
.PP
Definition at line \fB530\fP of file \fBTreeViewKeyboardEventHandlerTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
