.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.UsingStatementNodeTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.UsingStatementNodeTests \- \fBUsingStatementNode\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "UsingStatementNode(KeywordToken, IdentifierToken) 
.br
----
.br
 \fBUsingStatementNode\&.KeywordToken\fP \fBUsingStatementNode\&.NamespaceIdentifier\fP UsingStatementNode\&.ChildList \fBUsingStatementNode\&.IsFabricated\fP \fBUsingStatementNode\&.SyntaxKind\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBUsingStatementNode\fP 
.PP
Definition at line \fB9\fP of file \fBUsingStatementNodeTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.Syntax\&.SyntaxNodes\&.UsingStatementNodeTests\&.Constructor ()"

.PP
UsingStatementNode(KeywordToken, IdentifierToken) 
.br
----
.br
 \fBUsingStatementNode\&.KeywordToken\fP \fBUsingStatementNode\&.NamespaceIdentifier\fP UsingStatementNode\&.ChildList \fBUsingStatementNode\&.IsFabricated\fP \fBUsingStatementNode\&.SyntaxKind\fP 
.PP
Definition at line \fB21\fP of file \fBUsingStatementNodeTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
