.TH "Luthetus.Ide.Tests.Basis.Decorations.DecorationMapperRegistryTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.Tests.Basis.Decorations.DecorationMapperRegistryTests \- DecorationMapperRegistry  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "DecorationMapperRegistry() 
.br
----
.br
 DecorationMapperRegistry\&.Map DecorationMapperRegistry\&.CssDecorationMapper DecorationMapperRegistry\&.JsonDecorationMapper DecorationMapperRegistry\&.GenericDecorationMapper DecorationMapperRegistry\&.HtmlDecorationMapper DecorationMapperRegistry\&.DefaultDecorationMapper "
.ti -1c
.RI "void \fBGetDecorationMapper\fP ()"
.br
.RI "DecorationMapperRegistry\&.GetDecorationMapper(string) "
.in -1c
.SH "Detailed Description"
.PP 
DecorationMapperRegistry 
.PP
Definition at line \fB6\fP of file \fBDecorationMapperRegistryTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.Decorations\&.DecorationMapperRegistryTests\&.Constructor ()"

.PP
DecorationMapperRegistry() 
.br
----
.br
 DecorationMapperRegistry\&.Map DecorationMapperRegistry\&.CssDecorationMapper DecorationMapperRegistry\&.JsonDecorationMapper DecorationMapperRegistry\&.GenericDecorationMapper DecorationMapperRegistry\&.HtmlDecorationMapper DecorationMapperRegistry\&.DefaultDecorationMapper 
.PP
Definition at line \fB19\fP of file \fBDecorationMapperRegistryTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.Decorations\&.DecorationMapperRegistryTests\&.GetDecorationMapper ()"

.PP
DecorationMapperRegistry\&.GetDecorationMapper(string) 
.PP
Definition at line \fB28\fP of file \fBDecorationMapperRegistryTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
