.TH "Luthetus.Ide.RazorLib.FileSystems.Models.FileTemplateProvider" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.FileSystems.Models.FileTemplateProvider
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.IFileTemplateProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFileTemplateProvider\fP ()"
.br
.RI "The order of the entries in _fileTemplatesList is important as the \&.FirstOrDefault(x => \&.\&.\&.true\&.\&.\&.) is used\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "ImmutableArray< \fBIFileTemplate\fP > \fBFileTemplatesList\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBFileTemplateProvider\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.FileTemplateProvider\&.FileTemplateProvider ()"

.PP
The order of the entries in _fileTemplatesList is important as the \&.FirstOrDefault(x => \&.\&.\&.true\&.\&.\&.) is used\&. 
.PP
Definition at line \fB13\fP of file \fBFileTemplateProvider\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "ImmutableArray<\fBIFileTemplate\fP> Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.FileTemplateProvider\&.FileTemplatesList\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.IFileTemplateProvider\fP\&.
.PP
Definition at line \fB20\fP of file \fBFileTemplateProvider\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
