.TH "Luthetus.Common.RazorLib.Notifications.Displays.CommonInformativeNotificationDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Notifications.Displays.CommonInformativeNotificationDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBMessage\fP = null!\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBCommonInformativeNotificationDisplay\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Luthetus\&.Common\&.RazorLib\&.Notifications\&.Displays\&.CommonInformativeNotificationDisplay\&.Message = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB8\fP of file \fBCommonInformativeNotificationDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
