.TH "Luthetus.TextEditor.Tests.Basis.Keymaps.Models.Defaults.TextEditorKeymapDefaultTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.Keymaps.Models.Defaults.TextEditorKeymapDefaultTests \- \fBTextEditorKeymapDefault\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "TextEditorKeymapDefault() "
.ti -1c
.RI "void \fBGetLayer\fP ()"
.br
.RI "\fBTextEditorKeymapDefault\&.GetLayer(bool)\fP "
.ti -1c
.RI "void \fBGetCursorCssClassString\fP ()"
.br
.RI "\fBTextEditorKeymapDefault\&.GetCursorCssClassString()\fP "
.ti -1c
.RI "void \fBGetCursorCssStyleString\fP ()"
.br
.RI "\fBTextEditorKeymapDefault\&.GetCursorCssStyleString(TextEditorModel, TextEditorViewModel, TextEditorOptions)\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBTextEditorKeymapDefault\fP 
.PP
Definition at line \fB10\fP of file \fBTextEditorKeymapDefaultTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Keymaps\&.Models\&.Defaults\&.TextEditorKeymapDefaultTests\&.Constructor ()"

.PP
TextEditorKeymapDefault() 
.PP
Definition at line \fB16\fP of file \fBTextEditorKeymapDefaultTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Keymaps\&.Models\&.Defaults\&.TextEditorKeymapDefaultTests\&.GetCursorCssClassString ()"

.PP
\fBTextEditorKeymapDefault\&.GetCursorCssClassString()\fP 
.PP
Definition at line \fB34\fP of file \fBTextEditorKeymapDefaultTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Keymaps\&.Models\&.Defaults\&.TextEditorKeymapDefaultTests\&.GetCursorCssStyleString ()"

.PP
\fBTextEditorKeymapDefault\&.GetCursorCssStyleString(TextEditorModel, TextEditorViewModel, TextEditorOptions)\fP 
.PP
Definition at line \fB43\fP of file \fBTextEditorKeymapDefaultTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Keymaps\&.Models\&.Defaults\&.TextEditorKeymapDefaultTests\&.GetLayer ()"

.PP
\fBTextEditorKeymapDefault\&.GetLayer(bool)\fP 
.PP
Definition at line \fB25\fP of file \fBTextEditorKeymapDefaultTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
