.TH "Luthetus.Extensions.DotNet.Tests.Basis.ExtensionsDotNetTestBase.Test_WellKnownPaths.Directories" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.Tests.Basis.ExtensionsDotNetTestBase.Test_WellKnownPaths.Directories
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBRoot\fP = '/'"
.br
.ti -1c
.RI "const string \fBHomework\fP = '/Homework/'"
.br
.ti -1c
.RI "const string \fBMath\fP = '/Homework/Math/'"
.br
.ti -1c
.RI "const string \fBBiology\fP = '/Homework/Biology/'"
.br
.ti -1c
.RI "const string \fBNonExistingDirectory\fP = '/Homework/Hamburger/'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB111\fP of file \fBExtensionsDotNetTestBase\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const string Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.ExtensionsDotNetTestBase\&.Test_WellKnownPaths\&.Directories\&.Biology = '/Homework/Biology/'\fR [static]\fP"

.PP
Definition at line \fB116\fP of file \fBExtensionsDotNetTestBase\&.cs\fP\&.
.SS "const string Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.ExtensionsDotNetTestBase\&.Test_WellKnownPaths\&.Directories\&.Homework = '/Homework/'\fR [static]\fP"

.PP
Definition at line \fB114\fP of file \fBExtensionsDotNetTestBase\&.cs\fP\&.
.SS "const string Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.ExtensionsDotNetTestBase\&.Test_WellKnownPaths\&.Directories\&.Math = '/Homework/Math/'\fR [static]\fP"

.PP
Definition at line \fB115\fP of file \fBExtensionsDotNetTestBase\&.cs\fP\&.
.SS "const string Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.ExtensionsDotNetTestBase\&.Test_WellKnownPaths\&.Directories\&.NonExistingDirectory = '/Homework/Hamburger/'\fR [static]\fP"

.PP
Definition at line \fB118\fP of file \fBExtensionsDotNetTestBase\&.cs\fP\&.
.SS "const string Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.ExtensionsDotNetTestBase\&.Test_WellKnownPaths\&.Directories\&.Root = '/'\fR [static]\fP"

.PP
Definition at line \fB113\fP of file \fBExtensionsDotNetTestBase\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
