.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.CloseAngleBracketTokenTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.CloseAngleBracketTokenTests \- \fBCloseAngleBracketToken\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "CloseAngleBracketToken(TextEditorTextSpan) 
.br
----
.br
 \fBCloseAngleBracketToken\&.TextSpan\fP \fBCloseAngleBracketToken\&.SyntaxKind\fP \fBCloseAngleBracketToken\&.IsFabricated\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBCloseAngleBracketToken\fP 
.PP
Definition at line \fB10\fP of file \fBCloseAngleBracketTokenTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.Syntax\&.SyntaxTokens\&.CloseAngleBracketTokenTests\&.Constructor ()"

.PP
CloseAngleBracketToken(TextEditorTextSpan) 
.br
----
.br
 \fBCloseAngleBracketToken\&.TextSpan\fP \fBCloseAngleBracketToken\&.SyntaxKind\fP \fBCloseAngleBracketToken\&.IsFabricated\fP 
.PP
Definition at line \fB20\fP of file \fBCloseAngleBracketTokenTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
