.TH "Luthetus.Extensions.DotNet.Shareds.Displays.Internals.IdePromptOpenSolutionDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.Shareds.Displays.Internals.IdePromptOpenSolutionDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBIAbsolutePath\fP \fBAbsolutePath\fP = null!\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBIdePromptOpenSolutionDisplay\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBIAbsolutePath\fP Luthetus\&.Extensions\&.DotNet\&.Shareds\&.Displays\&.Internals\&.IdePromptOpenSolutionDisplay\&.AbsolutePath = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB13\fP of file \fBIdePromptOpenSolutionDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
