.TH "Luthetus.Common.Tests.Basis.Keymaps.Models.KeymapArgumentTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Keymaps.Models.KeymapArgumentTests \- KeymapArgument  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructorA\fP ()"
.br
.RI "KeymapArgument(string, bool, bool, bool, Key<KeymapLayer>) "
.ti -1c
.RI "void \fBConstructorB\fP ()"
.br
.RI "KeymapArgument(string) "
.in -1c
.SH "Detailed Description"
.PP 
KeymapArgument 
.PP
Definition at line \fB10\fP of file \fBKeymapArgumentTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Keymaps\&.Models\&.KeymapArgumentTests\&.ConstructorA ()"

.PP
KeymapArgument(string, bool, bool, bool, Key<KeymapLayer>) 
.PP
Definition at line \fB16\fP of file \fBKeymapArgumentTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Keymaps\&.Models\&.KeymapArgumentTests\&.ConstructorB ()"

.PP
KeymapArgument(string) 
.PP
Definition at line \fB71\fP of file \fBKeymapArgumentTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
