.TH "Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Parsers.ScopeTests.Test" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Parsers.ScopeTests.Test
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTest\fP (string sourceText)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBSourceText\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "ResourceUri \fBResourceUri\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBCSharpLexer\fP \fBLexer\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBCSharpParser\fP \fBParser\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBIBinder\fP \fBBinder\fP\fR [get]\fP"
.br
.ti -1c
.RI "CompilationUnit \fBCompilationUnit\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB38\fP of file \fBScopeTests\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ScopeTests\&.Test\&.Test (string sourceText)"

.PP
Definition at line \fB40\fP of file \fBScopeTests\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBIBinder\fP Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ScopeTests\&.Test\&.Binder\fR [get]\fP"

.PP
Definition at line \fB54\fP of file \fBScopeTests\&.cs\fP\&.
.SS "CompilationUnit Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ScopeTests\&.Test\&.CompilationUnit\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB55\fP of file \fBScopeTests\&.cs\fP\&.
.SS "\fBCSharpLexer\fP Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ScopeTests\&.Test\&.Lexer\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB52\fP of file \fBScopeTests\&.cs\fP\&.
.SS "\fBCSharpParser\fP Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ScopeTests\&.Test\&.Parser\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB53\fP of file \fBScopeTests\&.cs\fP\&.
.SS "ResourceUri Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ScopeTests\&.Test\&.ResourceUri\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB51\fP of file \fBScopeTests\&.cs\fP\&.
.SS "string Luthetus\&.CompilerServices\&.CSharp\&.Tests\&.SmokeTests\&.Parsers\&.ScopeTests\&.Test\&.SourceText\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB50\fP of file \fBScopeTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
