.TH "Luthetus.Extensions.DotNet.ComponentRenderers.Models.ITreeViewCSharpProjectNugetPackageReferenceRendererType" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.ComponentRenderers.Models.ITreeViewCSharpProjectNugetPackageReferenceRendererType
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.Extensions\&.DotNet\&.CSharpProjects\&.Displays\&.TreeViewCSharpProjectNugetPackageReferenceDisplay\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "CSharpProjectNugetPackageReference \fBCSharpProjectNugetPackageReference\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBITreeViewCSharpProjectNugetPackageReferenceRendererType\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "CSharpProjectNugetPackageReference Luthetus\&.Extensions\&.DotNet\&.ComponentRenderers\&.Models\&.ITreeViewCSharpProjectNugetPackageReferenceRendererType\&.CSharpProjectNugetPackageReference\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.Extensions\&.DotNet\&.CSharpProjects\&.Displays\&.TreeViewCSharpProjectNugetPackageReferenceDisplay\fP\&.
.PP
Definition at line \fB7\fP of file \fBITreeViewCSharpProjectNugetPackageReferenceRendererType\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
