.TH "Luthetus.CompilerServices.DotNetSolution.Facts.LexSolutionFacts.Header" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.DotNetSolution.Facts.LexSolutionFacts.Header
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBFORMAT_VERSION_START_TOKEN\fP"
.br
.ti -1c
.RI "const string \fBHASHTAG_VISUAL_STUDIO_VERSION_START_TOKEN\fP"
.br
.ti -1c
.RI "const string \fBEXACT_VISUAL_STUDIO_VERSION_START_TOKEN\fP"
.br
.ti -1c
.RI "const string \fBMINIMUM_VISUAL_STUDIO_VERSION_START_TOKEN\fP"
.br
.ti -1c
.RI "static readonly ImmutableArray< string > \fBWellKnownAssociatedNamesList\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBHeader\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const string Luthetus\&.CompilerServices\&.DotNetSolution\&.Facts\&.LexSolutionFacts\&.Header\&.EXACT_VISUAL_STUDIO_VERSION_START_TOKEN\fR [static]\fP"
\fBInitial value:\fP
.nf
=
            @"VisualStudioVersion ="
.PP
.fi

.PP
Definition at line \fB15\fP of file \fBHeader\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.DotNetSolution\&.Facts\&.LexSolutionFacts\&.Header\&.FORMAT_VERSION_START_TOKEN\fR [static]\fP"
\fBInitial value:\fP
.nf
=
            @"Microsoft Visual Studio Solution File, Format Version"
.PP
.fi

.PP
Definition at line \fB9\fP of file \fBHeader\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.DotNetSolution\&.Facts\&.LexSolutionFacts\&.Header\&.HASHTAG_VISUAL_STUDIO_VERSION_START_TOKEN\fR [static]\fP"
\fBInitial value:\fP
.nf
=
            @"# Visual Studio Version"
.PP
.fi

.PP
Definition at line \fB12\fP of file \fBHeader\&.cs\fP\&.
.SS "const string Luthetus\&.CompilerServices\&.DotNetSolution\&.Facts\&.LexSolutionFacts\&.Header\&.MINIMUM_VISUAL_STUDIO_VERSION_START_TOKEN\fR [static]\fP"
\fBInitial value:\fP
.nf
=
            @"MinimumVisualStudioVersion ="
.PP
.fi

.PP
Definition at line \fB18\fP of file \fBHeader\&.cs\fP\&.
.SS "readonly ImmutableArray<string> Luthetus\&.CompilerServices\&.DotNetSolution\&.Facts\&.LexSolutionFacts\&.Header\&.WellKnownAssociatedNamesList\fR [static]\fP"
\fBInitial value:\fP
.nf
= new[]
        {
            FORMAT_VERSION_START_TOKEN,
            HASHTAG_VISUAL_STUDIO_VERSION_START_TOKEN,
            EXACT_VISUAL_STUDIO_VERSION_START_TOKEN,
            MINIMUM_VISUAL_STUDIO_VERSION_START_TOKEN,
        }\&.ToImmutableArray()
.PP
.fi

.PP
Definition at line \fB21\fP of file \fBHeader\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
