.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.CommaTokenTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.CommaTokenTests \- \fBCommaToken\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "CommaToken(TextEditorTextSpan) 
.br
----
.br
 \fBCommaToken\&.TextSpan\fP \fBCommaToken\&.SyntaxKind\fP \fBCommaToken\&.IsFabricated\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBCommaToken\fP 
.PP
Definition at line \fB10\fP of file \fBCommaTokenTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.Syntax\&.SyntaxTokens\&.CommaTokenTests\&.Constructor ()"

.PP
CommaToken(TextEditorTextSpan) 
.br
----
.br
 \fBCommaToken\&.TextSpan\fP \fBCommaToken\&.SyntaxKind\fP \fBCommaToken\&.IsFabricated\fP 
.PP
Definition at line \fB20\fP of file \fBCommaTokenTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
