.TH "Luthetus.Ide.RazorLib.Terminals.Models.TerminalOutputFormatterExpand" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.Terminals.Models.TerminalOutputFormatterExpand
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.ITerminalOutputFormatter\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTerminalOutputFormatterExpand\fP (\fBITerminal\fP terminal, \fBITextEditorService\fP \fBtextEditorService\fP, \fBICompilerServiceRegistry\fP compilerServiceRegistry, \fBIDialogService\fP \fBdialogService\fP, IJSRuntime \fBjsRuntime\fP, IDispatcher \fBdispatcher\fP)"
.br
.ti -1c
.RI "\fBITerminalOutputFormatted\fP \fBFormat\fP ()"
.br
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Guid \fBId\fP = Guid\&.NewGuid()\fR [get]\fP"
.br
.ti -1c
.RI "\fBResourceUri\fP \fBTextEditorModelResourceUri\fP\fR [get]\fP"
.br
.ti -1c
.RI "Key< \fBTextEditorViewModel\fP > \fBTextEditorViewModelKey\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBName\fP = nameof(\fBTerminalOutputFormatterExpand\fP)\fR [get]\fP"
.br
.RI "This is used to find the respective formatter within a list that contains the available formatters\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB22\fP of file \fBTerminalOutputFormatterExpand\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutputFormatterExpand\&.TerminalOutputFormatterExpand (\fBITerminal\fP terminal, \fBITextEditorService\fP textEditorService, \fBICompilerServiceRegistry\fP compilerServiceRegistry, \fBIDialogService\fP dialogService, IJSRuntime jsRuntime, IDispatcher dispatcher)"

.PP
Definition at line \fB37\fP of file \fBTerminalOutputFormatterExpand\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutputFormatterExpand\&.Dispose ()"

.PP
Definition at line \fB220\fP of file \fBTerminalOutputFormatterExpand\&.cs\fP\&.
.SS "\fBITerminalOutputFormatted\fP Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutputFormatterExpand\&.Format ()"

.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.ITerminalOutputFormatter\fP\&.
.PP
Definition at line \fB62\fP of file \fBTerminalOutputFormatterExpand\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Guid Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutputFormatterExpand\&.Id = Guid\&.NewGuid()\fR [get]\fP"

.PP
Definition at line \fB24\fP of file \fBTerminalOutputFormatterExpand\&.cs\fP\&.
.SS "string Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutputFormatterExpand\&.Name = nameof(\fBTerminalOutputFormatterExpand\fP)\fR [get]\fP"

.PP
This is used to find the respective formatter within a list that contains the available formatters\&. 
.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.ITerminalOutputFormatter\fP\&.
.PP
Definition at line \fB60\fP of file \fBTerminalOutputFormatterExpand\&.cs\fP\&.
.SS "\fBResourceUri\fP Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutputFormatterExpand\&.TextEditorModelResourceUri\fR [get]\fP"

.PP
Definition at line \fB26\fP of file \fBTerminalOutputFormatterExpand\&.cs\fP\&.
.SS "Key<\fBTextEditorViewModel\fP> Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutputFormatterExpand\&.TextEditorViewModelKey\fR [get]\fP"

.PP
Definition at line \fB28\fP of file \fBTerminalOutputFormatterExpand\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
