.TH "Luthetus.Common.RazorLib.Reflectives.PersonCase" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Reflectives.PersonCase
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBPersonDisplay\fP"
.br
.RI "\fBPersonDisplay\fP is used from within the unit tests, in order to keep around an un-changing component for the \fBReflectives\fP\&. "
.ti -1c
.RI "class \fBPersonModel\fP"
.br
.RI "\fBPersonModel\fP is used from within the unit tests, in order to keep around an un-changing Type for the \fBReflectives\fP\&. "
.ti -1c
.RI "class \fBPersonSimpleDisplay\fP"
.br
.RI "\fBPersonSimpleDisplay\fP is used from within the unit tests, in order to keep around an un-changing component for the \fBReflectives\fP\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
