.TH "Luthetus.Common.Tests.Basis.Menus.Models" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Menus.Models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBMenuOptionCallbacksTests\fP"
.br
.RI "\fBMenuOptionCallbacks\fP "
.ti -1c
.RI "class \fBMenuRecordTests\fP"
.br
.RI "\fBMenuRecord\fP "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
