.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.Symbols.PropertySymbolTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.Symbols.PropertySymbolTests \- \fBPropertySymbol\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "PropertySymbol(TextEditorTextSpan) 
.br
----
.br
 \fBPropertySymbol\&.TextSpan\fP \fBPropertySymbol\&.SymbolKindString\fP \fBPropertySymbol\&.SyntaxKind\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBPropertySymbol\fP 
.PP
Definition at line \fB10\fP of file \fBPropertySymbolTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.Syntax\&.Symbols\&.PropertySymbolTests\&.Constructor ()"

.PP
PropertySymbol(TextEditorTextSpan) 
.br
----
.br
 \fBPropertySymbol\&.TextSpan\fP \fBPropertySymbol\&.SymbolKindString\fP \fBPropertySymbol\&.SyntaxKind\fP 
.PP
Definition at line \fB20\fP of file \fBPropertySymbolTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
