.TH "Luthetus.Common.RazorLib.Menus.Displays.MenuDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Menus.Displays.MenuDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async Task \fBSetFocusToFirstOptionInMenuAsync\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override async Task \fBOnAfterRenderAsync\fP (bool firstRender)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Func< Task >? \fBReturnFocusToParentFuncAsync\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBDropdownRecord\fP? \fBDropdown\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "MenuRecord \fBMenuRecord\fP = null!\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBInitialActiveMenuOptionRecordIndex\fP = \-1\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBGroupByMenuOptionKind\fP = true\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBFocusOnAfterRenderAsync\fP = true\fR [get, set]\fP"
.br
.ti -1c
.RI "RenderFragment< \fBMenuOptionRecord\fP >? \fBIconRenderFragment\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBMenuDisplay\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override async Task Luthetus\&.Common\&.RazorLib\&.Menus\&.Displays\&.MenuDisplay\&.OnAfterRenderAsync (bool firstRender)\fR [protected]\fP"

.PP
Definition at line \fB48\fP of file \fBMenuDisplay\&.razor\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.RazorLib\&.Menus\&.Displays\&.MenuDisplay\&.SetFocusToFirstOptionInMenuAsync ()"

.PP
Definition at line \fB81\fP of file \fBMenuDisplay\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBDropdownRecord\fP? Luthetus\&.Common\&.RazorLib\&.Menus\&.Displays\&.MenuDisplay\&.Dropdown\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB19\fP of file \fBMenuDisplay\&.razor\&.cs\fP\&.
.SS "bool Luthetus\&.Common\&.RazorLib\&.Menus\&.Displays\&.MenuDisplay\&.FocusOnAfterRenderAsync = true\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB29\fP of file \fBMenuDisplay\&.razor\&.cs\fP\&.
.SS "bool Luthetus\&.Common\&.RazorLib\&.Menus\&.Displays\&.MenuDisplay\&.GroupByMenuOptionKind = true\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB27\fP of file \fBMenuDisplay\&.razor\&.cs\fP\&.
.SS "RenderFragment<\fBMenuOptionRecord\fP>? Luthetus\&.Common\&.RazorLib\&.Menus\&.Displays\&.MenuDisplay\&.IconRenderFragment\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB31\fP of file \fBMenuDisplay\&.razor\&.cs\fP\&.
.SS "int Luthetus\&.Common\&.RazorLib\&.Menus\&.Displays\&.MenuDisplay\&.InitialActiveMenuOptionRecordIndex = \-1\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB25\fP of file \fBMenuDisplay\&.razor\&.cs\fP\&.
.SS "MenuRecord Luthetus\&.Common\&.RazorLib\&.Menus\&.Displays\&.MenuDisplay\&.MenuRecord = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB22\fP of file \fBMenuDisplay\&.razor\&.cs\fP\&.
.SS "Func<Task>? Luthetus\&.Common\&.RazorLib\&.Menus\&.Displays\&.MenuDisplay\&.ReturnFocusToParentFuncAsync\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB17\fP of file \fBMenuDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
