.TH "Luthetus.Ide.RazorLib.Shareds.Displays.IdeBody" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.Shareds.Displays.IdeBody
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInitialized\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBElementDimensions\fP \fBBodyElementDimensions\fP = null!\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBIdeBody\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Luthetus\&.Ide\&.RazorLib\&.Shareds\&.Displays\&.IdeBody\&.OnInitialized ()\fR [protected]\fP"

.PP
Definition at line \fB26\fP of file \fBIdeBody\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBElementDimensions\fP Luthetus\&.Ide\&.RazorLib\&.Shareds\&.Displays\&.IdeBody\&.BodyElementDimensions = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB19\fP of file \fBIdeBody\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
