.TH "Luthetus.TextEditor.Tests.Basis.Diffs.States.TextEditorDiffStateReducerTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.Diffs.States.TextEditorDiffStateReducerTests \- \fBTextEditorDiffState\&.Reducer\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBReduceRegisterAction\fP ()"
.br
.RI "TextEditorDiffState\&.Reducer\&.ReduceRegisterAction(TextEditorDiffState, TextEditorDiffState\&.RegisterAction) "
.ti -1c
.RI "void \fBReduceDisposeAction\fP ()"
.br
.RI "TextEditorDiffState\&.Reducer\&.ReduceDisposeAction(TextEditorDiffState, TextEditorDiffState\&.DisposeAction) "
.in -1c
.SH "Detailed Description"
.PP 
\fBTextEditorDiffState\&.Reducer\fP 
.PP
Definition at line \fB14\fP of file \fBTextEditorDiffState\&.ReducerTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Diffs\&.States\&.TextEditorDiffStateReducerTests\&.ReduceDisposeAction ()"

.PP
TextEditorDiffState\&.Reducer\&.ReduceDisposeAction(TextEditorDiffState, TextEditorDiffState\&.DisposeAction) 
.PP
Definition at line \fB74\fP of file \fBTextEditorDiffState\&.ReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Diffs\&.States\&.TextEditorDiffStateReducerTests\&.ReduceRegisterAction ()"

.PP
TextEditorDiffState\&.Reducer\&.ReduceRegisterAction(TextEditorDiffState, TextEditorDiffState\&.RegisterAction) 
.PP
Definition at line \fB20\fP of file \fBTextEditorDiffState\&.ReducerTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
