.TH "Luthetus.Extensions.DotNet.Tests.Basis.Nugets.Models.NugetPackageVersionRecordTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.Tests.Basis.Nugets.Models.NugetPackageVersionRecordTests \- NugetPackageVersionRecord  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBProperties\fP ()"
.br
.RI "NugetPackageVersionRecord\&.Version NugetPackageVersionRecord\&.Downloads NugetPackageVersionRecord\&.AtId "
.in -1c
.SH "Detailed Description"
.PP 
NugetPackageVersionRecord 
.PP
Definition at line \fB6\fP of file \fBNugetPackageVersionRecordTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.Nugets\&.Models\&.NugetPackageVersionRecordTests\&.Properties ()"

.PP
NugetPackageVersionRecord\&.Version NugetPackageVersionRecord\&.Downloads NugetPackageVersionRecord\&.AtId 
.PP
Definition at line \fB14\fP of file \fBNugetPackageVersionRecordTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
