.TH "Luthetus.Common.Tests.Basis.Themes.States.ThemeStateMainTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Themes.States.ThemeStateMainTests \- \fBThemeState\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "\fBThemeState()\fP "
.ti -1c
.RI "void \fBDefaultThemeRecordsList\fP ()"
.br
.RI "ThemeState\&.DefaultThemeRecordsList "
.in -1c
.SH "Detailed Description"
.PP 
\fBThemeState\fP 
.PP
Definition at line \fB11\fP of file \fBThemeStateTests\&.Main\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Themes\&.States\&.ThemeStateMainTests\&.Constructor ()"

.PP
\fBThemeState()\fP 
.PP
Definition at line \fB17\fP of file \fBThemeStateTests\&.Main\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Themes\&.States\&.ThemeStateMainTests\&.DefaultThemeRecordsList ()"

.PP
ThemeState\&.DefaultThemeRecordsList 
.PP
Definition at line \fB27\fP of file \fBThemeStateTests\&.Main\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
