.TH "Luthetus.CompilerServices.Python.Facts.PythonLanguageFacts.Whitespace" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.Python.Facts.PythonLanguageFacts.Whitespace
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const char \fBCARRIAGE_RETURN_CHAR\fP = '\\r'"
.br
.ti -1c
.RI "const char \fBLINE_FEED_CHAR\fP = '\\n'"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBCARRIAGE_RETURN_LINE_FEED_SUBSTRING\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBPythonLanguageFacts\&.Whitespace\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const char Luthetus\&.CompilerServices\&.Python\&.Facts\&.PythonLanguageFacts\&.Whitespace\&.CARRIAGE_RETURN_CHAR = '\\r'\fR [static]\fP"

.PP
Definition at line \fB7\fP of file \fBPythonLanguageFacts\&.Whitespace\&.cs\fP\&.
.SS "const char Luthetus\&.CompilerServices\&.Python\&.Facts\&.PythonLanguageFacts\&.Whitespace\&.LINE_FEED_CHAR = '\\n'\fR [static]\fP"

.PP
Definition at line \fB8\fP of file \fBPythonLanguageFacts\&.Whitespace\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Luthetus\&.CompilerServices\&.Python\&.Facts\&.PythonLanguageFacts\&.Whitespace\&.CARRIAGE_RETURN_LINE_FEED_SUBSTRING\fR [get]\fP"

.PP
Definition at line \fB10\fP of file \fBPythonLanguageFacts\&.Whitespace\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
