.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.GenericParameterEntryNodeTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.GenericParameterEntryNodeTests \- \fBGenericParameterEntryNode\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "GenericParameterEntryNode(TypeClauseNode) 
.br
----
.br
 \fBGenericParameterEntryNode\&.TypeClauseNode\fP GenericParameterEntryNode\&.ChildList \fBGenericParameterEntryNode\&.IsFabricated\fP \fBGenericParameterEntryNode\&.SyntaxKind\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBGenericParameterEntryNode\fP 
.PP
Definition at line \fB10\fP of file \fBGenericParameterEntryNodeTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.Syntax\&.SyntaxNodes\&.GenericParameterEntryNodeTests\&.Constructor ()"

.PP
GenericParameterEntryNode(TypeClauseNode) 
.br
----
.br
 \fBGenericParameterEntryNode\&.TypeClauseNode\fP GenericParameterEntryNode\&.ChildList \fBGenericParameterEntryNode\&.IsFabricated\fP \fBGenericParameterEntryNode\&.SyntaxKind\fP 
.PP
Definition at line \fB21\fP of file \fBGenericParameterEntryNodeTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
