.TH "Luthetus.Extensions.DotNet.Tests.Basis.Nugets.States.NuGetPackageManagerStateReducerTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.Tests.Basis.Nugets.States.NuGetPackageManagerStateReducerTests \- NuGetPackageManagerState\&.Reducer  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBReduceSetSelectedProjectToModifyAction\fP ()"
.br
.RI "NuGetPackageManagerState\&.Reducer\&.ReduceSetSelectedProjectToModifyAction(NuGetPackageManagerState, NuGetPackageManagerState\&.SetSelectedProjectToModifyAction) "
.ti -1c
.RI "void \fBReduceSetNugetQueryAction\fP ()"
.br
.RI "NuGetPackageManagerState\&.Reducer\&.ReduceSetNugetQueryAction(NuGetPackageManagerState, NuGetPackageManagerState\&.SetNugetQueryAction) "
.ti -1c
.RI "void \fBReduceSetIncludePrereleaseAction\fP ()"
.br
.RI "NuGetPackageManagerState\&.Reducer\&.ReduceSetIncludePrereleaseAction(NuGetPackageManagerState, NuGetPackageManagerState\&.SetIncludePrereleaseAction) "
.ti -1c
.RI "void \fBReduceSetMostRecentQueryResultAction\fP ()"
.br
.RI "NuGetPackageManagerState\&.Reducer\&.ReduceSetMostRecentQueryResultAction(NuGetPackageManagerState, NuGetPackageManagerState\&.SetMostRecentQueryResultAction) "
.in -1c
.SH "Detailed Description"
.PP 
NuGetPackageManagerState\&.Reducer 
.PP
Definition at line \fB6\fP of file \fBNuGetPackageManagerStateReducerTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.Nugets\&.States\&.NuGetPackageManagerStateReducerTests\&.ReduceSetIncludePrereleaseAction ()"

.PP
NuGetPackageManagerState\&.Reducer\&.ReduceSetIncludePrereleaseAction(NuGetPackageManagerState, NuGetPackageManagerState\&.SetIncludePrereleaseAction) 
.PP
Definition at line \fB30\fP of file \fBNuGetPackageManagerStateReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.Nugets\&.States\&.NuGetPackageManagerStateReducerTests\&.ReduceSetMostRecentQueryResultAction ()"

.PP
NuGetPackageManagerState\&.Reducer\&.ReduceSetMostRecentQueryResultAction(NuGetPackageManagerState, NuGetPackageManagerState\&.SetMostRecentQueryResultAction) 
.PP
Definition at line \fB39\fP of file \fBNuGetPackageManagerStateReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.Nugets\&.States\&.NuGetPackageManagerStateReducerTests\&.ReduceSetNugetQueryAction ()"

.PP
NuGetPackageManagerState\&.Reducer\&.ReduceSetNugetQueryAction(NuGetPackageManagerState, NuGetPackageManagerState\&.SetNugetQueryAction) 
.PP
Definition at line \fB21\fP of file \fBNuGetPackageManagerStateReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.Nugets\&.States\&.NuGetPackageManagerStateReducerTests\&.ReduceSetSelectedProjectToModifyAction ()"

.PP
NuGetPackageManagerState\&.Reducer\&.ReduceSetSelectedProjectToModifyAction(NuGetPackageManagerState, NuGetPackageManagerState\&.SetSelectedProjectToModifyAction) 
.PP
Definition at line \fB12\fP of file \fBNuGetPackageManagerStateReducerTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
