.TH "Luthetus.TextEditor.RazorLib.ComponentRenderers.Models.ITextEditorSymbolRenderer" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.ComponentRenderers.Models.ITextEditorSymbolRenderer
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.SymbolDisplay\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBITextEditorSymbol\fP \fBSymbol\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBITextEditorSymbolRenderer\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBITextEditorSymbol\fP Luthetus\&.TextEditor\&.RazorLib\&.ComponentRenderers\&.Models\&.ITextEditorSymbolRenderer\&.Symbol\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.SymbolDisplay\fP\&.
.PP
Definition at line \fB7\fP of file \fBITextEditorSymbolRenderer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
