.TH "Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IFileHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBInMemoryFileHandler\fP (\fBInMemoryFileSystemProvider\fP inMemoryFileSystemProvider, \fBIEnvironmentProvider\fP environmentProvider, \fBICommonComponentRenderers\fP commonComponentRenderers, IDispatcher dispatcher)"
.br
.ti -1c
.RI "Task< bool > \fBExistsAsync\fP (string absolutePathString, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "async Task \fBDeleteAsync\fP (string absolutePathString, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "async Task \fBCopyAsync\fP (string sourceAbsolutePathString, string destinationAbsolutePathString, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "async Task \fBMoveAsync\fP (string sourceAbsolutePathString, string destinationAbsolutePathString, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "async Task< DateTime > \fBGetLastWriteTimeAsync\fP (string absolutePathString, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "async Task< string > \fBReadAllTextAsync\fP (string absolutePathString, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "async Task \fBWriteAllTextAsync\fP (string absolutePathString, string contents, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "Task< bool > \fBUnsafeExistsAsync\fP (string absolutePathString, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "Task \fBUnsafeDeleteAsync\fP (string absolutePathString, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "async Task \fBUnsafeCopyAsync\fP (string sourceAbsolutePathString, string destinationAbsolutePathString, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "async Task \fBUnsafeMoveAsync\fP (string sourceAbsolutePathString, string destinationAbsolutePathString, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "Task< DateTime > \fBUnsafeGetLastWriteTimeAsync\fP (string absolutePathString, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "Task< string > \fBUnsafeReadAllTextAsync\fP (string absolutePathString, CancellationToken cancellationToken=default)"
.br
.ti -1c
.RI "Task \fBUnsafeWriteAllTextAsync\fP (string absolutePathString, string contents, CancellationToken cancellationToken=default)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBInMemoryFileSystemProvider\&.FileHandler\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryFileHandler\&.InMemoryFileHandler (\fBInMemoryFileSystemProvider\fP inMemoryFileSystemProvider, \fBIEnvironmentProvider\fP environmentProvider, \fBICommonComponentRenderers\fP commonComponentRenderers, IDispatcher dispatcher)"

.PP
Definition at line \fB20\fP of file \fBInMemoryFileSystemProvider\&.FileHandler\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "async Task Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryFileHandler\&.CopyAsync (string sourceAbsolutePathString, string destinationAbsolutePathString, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IFileHandler\fP\&.
.PP
Definition at line \fB59\fP of file \fBInMemoryFileSystemProvider\&.FileHandler\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryFileHandler\&.DeleteAsync (string absolutePathString, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IFileHandler\fP\&.
.PP
Definition at line \fB39\fP of file \fBInMemoryFileSystemProvider\&.FileHandler\&.cs\fP\&.
.SS "Task< bool > Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryFileHandler\&.ExistsAsync (string absolutePathString, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IFileHandler\fP\&.
.PP
Definition at line \fB32\fP of file \fBInMemoryFileSystemProvider\&.FileHandler\&.cs\fP\&.
.SS "async Task< DateTime > Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryFileHandler\&.GetLastWriteTimeAsync (string absolutePathString, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IFileHandler\fP\&.
.PP
Definition at line \fB111\fP of file \fBInMemoryFileSystemProvider\&.FileHandler\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryFileHandler\&.MoveAsync (string sourceAbsolutePathString, string destinationAbsolutePathString, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IFileHandler\fP\&.
.PP
Definition at line \fB85\fP of file \fBInMemoryFileSystemProvider\&.FileHandler\&.cs\fP\&.
.SS "async Task< string > Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryFileHandler\&.ReadAllTextAsync (string absolutePathString, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IFileHandler\fP\&.
.PP
Definition at line \fB118\fP of file \fBInMemoryFileSystemProvider\&.FileHandler\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryFileHandler\&.UnsafeCopyAsync (string sourceAbsolutePathString, string destinationAbsolutePathString, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Definition at line \fB180\fP of file \fBInMemoryFileSystemProvider\&.FileHandler\&.cs\fP\&.
.SS "Task Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryFileHandler\&.UnsafeDeleteAsync (string absolutePathString, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Definition at line \fB162\fP of file \fBInMemoryFileSystemProvider\&.FileHandler\&.cs\fP\&.
.SS "Task< bool > Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryFileHandler\&.UnsafeExistsAsync (string absolutePathString, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Definition at line \fB151\fP of file \fBInMemoryFileSystemProvider\&.FileHandler\&.cs\fP\&.
.SS "Task< DateTime > Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryFileHandler\&.UnsafeGetLastWriteTimeAsync (string absolutePathString, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Definition at line \fB236\fP of file \fBInMemoryFileSystemProvider\&.FileHandler\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryFileHandler\&.UnsafeMoveAsync (string sourceAbsolutePathString, string destinationAbsolutePathString, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Definition at line \fB217\fP of file \fBInMemoryFileSystemProvider\&.FileHandler\&.cs\fP\&.
.SS "Task< string > Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryFileHandler\&.UnsafeReadAllTextAsync (string absolutePathString, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Definition at line \fB250\fP of file \fBInMemoryFileSystemProvider\&.FileHandler\&.cs\fP\&.
.SS "Task Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryFileHandler\&.UnsafeWriteAllTextAsync (string absolutePathString, string contents, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Definition at line \fB264\fP of file \fBInMemoryFileSystemProvider\&.FileHandler\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.InMemoryFileSystemProvider\&.InMemoryFileHandler\&.WriteAllTextAsync (string absolutePathString, string contents, CancellationToken cancellationToken = \fRdefault\fP)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IFileHandler\fP\&.
.PP
Definition at line \fB125\fP of file \fBInMemoryFileSystemProvider\&.FileHandler\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
