.TH "Luthetus.Common.RazorLib.Options.Displays.InputAppResizeHandleHeight" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Options.Displays.InputAppResizeHandleHeight
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase, and IDisposable\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInitialized\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "InputViewModel \fBInputViewModel\fP = \fBInputViewModel\&.Empty\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBResizeHandleHeightInPixels\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBInputAppResizeHandleHeight\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.RazorLib\&.Options\&.Displays\&.InputAppResizeHandleHeight\&.Dispose ()"

.PP
Definition at line \fB39\fP of file \fBInputAppResizeHandleHeight\&.razor\&.cs\fP\&.
.SS "override void Luthetus\&.Common\&.RazorLib\&.Options\&.Displays\&.InputAppResizeHandleHeight\&.OnInitialized ()\fR [protected]\fP"

.PP
Definition at line \fB27\fP of file \fBInputAppResizeHandleHeight\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "InputViewModel Luthetus\&.Common\&.RazorLib\&.Options\&.Displays\&.InputAppResizeHandleHeight\&.InputViewModel = \fBInputViewModel\&.Empty\fP\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB13\fP of file \fBInputAppResizeHandleHeight\&.razor\&.cs\fP\&.
.SS "int Luthetus\&.Common\&.RazorLib\&.Options\&.Displays\&.InputAppResizeHandleHeight\&.ResizeHandleHeightInPixels\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB15\fP of file \fBInputAppResizeHandleHeight\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
