.TH "Luthetus.Extensions.Git.Displays.GitDiffDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.Git.Displays.GitDiffDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override Task \fBOnAfterRenderAsync\fP (bool firstRender)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "GitFile \fBGitFile\fP = null!\fR [get, set]\fP"
.br
.ti -1c
.RI "Key< \fBTerminalCommandRequest\fP > \fBGitLogTerminalCommandRequestKey\fP = Key<\fBTerminalCommandRequest\fP>\&.NewKey()\fR [get]\fP"
.br
.ti -1c
.RI "static Key< \fBTextEditorViewModel\fP > \fBInViewModelKey\fP = Key<\fBTextEditorViewModel\fP>\&.NewKey()\fR [get]\fP"
.br
.ti -1c
.RI "static Key< \fBTextEditorViewModel\fP > \fBOutViewModelKey\fP = Key<\fBTextEditorViewModel\fP>\&.NewKey()\fR [get]\fP"
.br
.ti -1c
.RI "static ? \fBResourceUri\fP \fBInResourceUri\fP\fR [get, set]\fP"
.br
.RI "This property is bad but I have a plan in mind\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB31\fP of file \fBGitDiffDisplay\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override Task Luthetus\&.Extensions\&.Git\&.Displays\&.GitDiffDisplay\&.OnAfterRenderAsync (bool firstRender)\fR [protected]\fP"

.PP
Definition at line \fB75\fP of file \fBGitDiffDisplay\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "GitFile Luthetus\&.Extensions\&.Git\&.Displays\&.GitDiffDisplay\&.GitFile = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB59\fP of file \fBGitDiffDisplay\&.razor\&.cs\fP\&.
.SS "Key<\fBTerminalCommandRequest\fP> Luthetus\&.Extensions\&.Git\&.Displays\&.GitDiffDisplay\&.GitLogTerminalCommandRequestKey = Key<\fBTerminalCommandRequest\fP>\&.NewKey()\fR [get]\fP"

.PP
Definition at line \fB61\fP of file \fBGitDiffDisplay\&.razor\&.cs\fP\&.
.SS "? \fBResourceUri\fP Luthetus\&.Extensions\&.Git\&.Displays\&.GitDiffDisplay\&.InResourceUri\fR [static]\fP, \fR [get]\fP, \fR [set]\fP"

.PP
This property is bad but I have a plan in mind\&. 
.PP
Definition at line \fB69\fP of file \fBGitDiffDisplay\&.razor\&.cs\fP\&.
.SS "Key<\fBTextEditorViewModel\fP> Luthetus\&.Extensions\&.Git\&.Displays\&.GitDiffDisplay\&.InViewModelKey = Key<\fBTextEditorViewModel\fP>\&.NewKey()\fR [static]\fP, \fR [get]\fP"

.PP
Definition at line \fB65\fP of file \fBGitDiffDisplay\&.razor\&.cs\fP\&.
.SS "Key<\fBTextEditorViewModel\fP> Luthetus\&.Extensions\&.Git\&.Displays\&.GitDiffDisplay\&.OutViewModelKey = Key<\fBTextEditorViewModel\fP>\&.NewKey()\fR [static]\fP, \fR [get]\fP"

.PP
Definition at line \fB66\fP of file \fBGitDiffDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
