.TH "Luthetus.Common.Tests.Basis.Menus.Models.MenuOptionCallbacksTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Menus.Models.MenuOptionCallbacksTests \- \fBMenuOptionCallbacks\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async Task \fBConstructorAsync\fP ()"
.br
.RI "MenuOptionCallbacks(Func<Task>, Func<Action, Task>) 
.br
----
.br
 \fBMenuOptionCallbacks\&.HideWidgetAsync\fP \fBMenuOptionCallbacks\&.CompleteWidgetAsync\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBMenuOptionCallbacks\fP 
.PP
Definition at line \fB8\fP of file \fBMenuOptionCallbacksTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "async Task Luthetus\&.Common\&.Tests\&.Basis\&.Menus\&.Models\&.MenuOptionCallbacksTests\&.ConstructorAsync ()"

.PP
MenuOptionCallbacks(Func<Task>, Func<Action, Task>) 
.br
----
.br
 \fBMenuOptionCallbacks\&.HideWidgetAsync\fP \fBMenuOptionCallbacks\&.CompleteWidgetAsync\fP 
.PP
Definition at line \fB17\fP of file \fBMenuOptionCallbacksTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
