.TH "Luthetus.Common.RazorLib.Reflectives.Models" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Reflectives.Models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBIReflectiveParameter\fP"
.br
.ti -1c
.RI "class \fBReflectiveParameter\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBReflectiveParameterKind\fP { \fBPrimitive\fP, \fBComplex\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "record \fBReflectiveModel\fP (Key< ReflectiveModel > Key, List< Type > ComponentTypeList, Guid ChosenTypeGuid, Guid PreviousTypeGuid, PropertyInfo[] ComponentPropertyInfoList, Dictionary< string, \fBIReflectiveParameter\fP > ReflectiveParameterMap, IDispatcher Dispatcher)"
.br
.ti -1c
.RI "record \fBReflectiveOptions\fP (params Assembly[] AssembliesToScanList)"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBLuthetus\&.Common\&.RazorLib\&.Reflectives\&.Models\&.ReflectiveParameterKind\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIPrimitive \fP
.TP
\f(BIComplex \fP
.PP
Definition at line \fB3\fP of file \fBReflectiveParameterKind\&.cs\fP\&.
.SH "Function Documentation"
.PP 
.SS "record Luthetus\&.Common\&.RazorLib\&.Reflectives\&.Models\&.ReflectiveModel (Key< ReflectiveModel > Key, List< Type > ComponentTypeList, Guid ChosenTypeGuid, Guid PreviousTypeGuid, PropertyInfo[] ComponentPropertyInfoList, Dictionary< string, \fBIReflectiveParameter\fP > ReflectiveParameterMap, IDispatcher Dispatcher)"
TODO: Don't duplicate this logic, it is similar to ConstructBlazorParameters
.PP
Definition at line \fB9\fP of file \fBReflectiveModel\&.cs\fP\&.
.SS "record Luthetus\&.Common\&.RazorLib\&.Reflectives\&.Models\&.ReflectiveOptions (params Assembly[] AssembliesToScanList)"

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
