.TH "Luthetus.Ide.Tests.Basis.IdeTestBase.Test_WellKnownPaths.Directories" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.Tests.Basis.IdeTestBase.Test_WellKnownPaths.Directories
.SH SYNOPSIS
.br
.PP
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "const string \fBRoot\fP = '/'"
.br
.ti -1c
.RI "const string \fBHomework\fP = '/Homework/'"
.br
.ti -1c
.RI "const string \fBMath\fP = '/Homework/Math/'"
.br
.ti -1c
.RI "const string \fBBiology\fP = '/Homework/Biology/'"
.br
.ti -1c
.RI "const string \fBNonExistingDirectory\fP = '/Homework/Hamburger/'"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB102\fP of file \fBIdeTestBase\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "const string Luthetus\&.Ide\&.Tests\&.Basis\&.IdeTestBase\&.Test_WellKnownPaths\&.Directories\&.Biology = '/Homework/Biology/'\fR [static]\fP"

.PP
Definition at line \fB107\fP of file \fBIdeTestBase\&.cs\fP\&.
.SS "const string Luthetus\&.Ide\&.Tests\&.Basis\&.IdeTestBase\&.Test_WellKnownPaths\&.Directories\&.Homework = '/Homework/'\fR [static]\fP"

.PP
Definition at line \fB105\fP of file \fBIdeTestBase\&.cs\fP\&.
.SS "const string Luthetus\&.Ide\&.Tests\&.Basis\&.IdeTestBase\&.Test_WellKnownPaths\&.Directories\&.Math = '/Homework/Math/'\fR [static]\fP"

.PP
Definition at line \fB106\fP of file \fBIdeTestBase\&.cs\fP\&.
.SS "const string Luthetus\&.Ide\&.Tests\&.Basis\&.IdeTestBase\&.Test_WellKnownPaths\&.Directories\&.NonExistingDirectory = '/Homework/Hamburger/'\fR [static]\fP"

.PP
Definition at line \fB109\fP of file \fBIdeTestBase\&.cs\fP\&.
.SS "const string Luthetus\&.Ide\&.Tests\&.Basis\&.IdeTestBase\&.Test_WellKnownPaths\&.Directories\&.Root = '/'\fR [static]\fP"

.PP
Definition at line \fB104\fP of file \fBIdeTestBase\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
