.TH "Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.PreprocessorDirectiveToken" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.PreprocessorDirectiveToken \- TODO: For C# need to implement: Preprocessor directives must be the first non whitespace character on the line\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.ISyntaxToken\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPreprocessorDirectiveToken\fP (\fBTextEditorTextSpan\fP textSpan)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBTextEditorTextSpan\fP \fBTextSpan\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBSyntaxKind\fP \fBSyntaxKind\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsFabricated\fP\fR [get]\fP"
.br
.RI "\fBIsFabricated\fP refers to when the ParserSession expected a node to be valid, but it wasn't\&.
.br

.br
For example, a function invocation on an undefined function will construct a BoundFunctionInvocationNode with \fBIsFabricated\fP set to true\&. "
.ti -1c
.RI "bool \fBConstructorWasInvoked\fP\fR [get]\fP"
.br
.RI "If the struct instance is default, this will be false\&. Otherwise, it will be true\&. "
.in -1c
.SH "Detailed Description"
.PP 
TODO: For C# need to implement: Preprocessor directives must be the first non whitespace character on the line\&. 
.PP
Definition at line \fB8\fP of file \fBPreprocessorDirectiveToken\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Tokens\&.PreprocessorDirectiveToken\&.PreprocessorDirectiveToken (\fBTextEditorTextSpan\fP textSpan)"

.PP
Definition at line \fB10\fP of file \fBPreprocessorDirectiveToken\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Tokens\&.PreprocessorDirectiveToken\&.ConstructorWasInvoked\fR [get]\fP"

.PP
If the struct instance is default, this will be false\&. Otherwise, it will be true\&. 
.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.ISyntaxToken\fP\&.
.PP
Definition at line \fB19\fP of file \fBPreprocessorDirectiveToken\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Tokens\&.PreprocessorDirectiveToken\&.IsFabricated\fR [get]\fP"

.PP
\fBIsFabricated\fP refers to when the ParserSession expected a node to be valid, but it wasn't\&.
.br

.br
For example, a function invocation on an undefined function will construct a BoundFunctionInvocationNode with \fBIsFabricated\fP set to true\&. 
.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.ISyntax\fP\&.
.PP
Definition at line \fB18\fP of file \fBPreprocessorDirectiveToken\&.cs\fP\&.
.SS "\fBSyntaxKind\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Tokens\&.PreprocessorDirectiveToken\&.SyntaxKind\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.ISyntax\fP\&.
.PP
Definition at line \fB17\fP of file \fBPreprocessorDirectiveToken\&.cs\fP\&.
.SS "\fBTextEditorTextSpan\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Tokens\&.PreprocessorDirectiveToken\&.TextSpan\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.ISyntaxToken\fP\&.
.PP
Definition at line \fB16\fP of file \fBPreprocessorDirectiveToken\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
