.TH "Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerServiceOptions" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerServiceOptions
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "Func< \fBResourceUri\fP, \fBICompilerServiceResource\fP >? \fBRegisterResourceFunc\fP\fR [get]\fP"
.br
.ti -1c
.RI "Func< \fBICompilerServiceResource\fP, string, \fBILexer\fP >? \fBGetLexerFunc\fP\fR [get]\fP"
.br
.RI "Takes as arguments the resource uri and the source text\&. "
.ti -1c
.RI "Func< \fBICompilerServiceResource\fP, \fBILexer\fP, \fBIParser\fP >? \fBGetParserFunc\fP\fR [get]\fP"
.br
.ti -1c
.RI "Func< \fBICompilerServiceResource\fP, \fBIParser\fP, \fBIBinder\fP >? \fBGetBinderFunc\fP\fR [get]\fP"
.br
.ti -1c
.RI "Action< \fBICompilerServiceResource\fP, \fBILexer\fP >? \fBOnAfterLexAction\fP\fR [get]\fP"
.br
.RI "Invoke an action which is passed the resource which was just lexed\&. This invocation occurs within a lock(_resourceMapLock) { \&.\&.\&. }\&. "
.ti -1c
.RI "Action< \fBICompilerServiceResource\fP, \fBCompilationUnit\fP?>? \fBOnAfterParseAction\fP\fR [get]\fP"
.br
.RI "Invoke an action which is passed the resource which was just parsed\&. This invocation occurs within a lock(_resourceMapLock) { \&.\&.\&. }\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBCompilerServiceOptions\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Func<\fBICompilerServiceResource\fP, \fBIParser\fP, \fBIBinder\fP>? Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.CompilerServiceOptions\&.GetBinderFunc\fR [get]\fP"

.PP
Definition at line \fB15\fP of file \fBCompilerServiceOptions\&.cs\fP\&.
.SS "Func<\fBICompilerServiceResource\fP, string, \fBILexer\fP>? Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.CompilerServiceOptions\&.GetLexerFunc\fR [get]\fP"

.PP
Takes as arguments the resource uri and the source text\&. 
.PP
Definition at line \fB13\fP of file \fBCompilerServiceOptions\&.cs\fP\&.
.SS "Func<\fBICompilerServiceResource\fP, \fBILexer\fP, \fBIParser\fP>? Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.CompilerServiceOptions\&.GetParserFunc\fR [get]\fP"

.PP
Definition at line \fB14\fP of file \fBCompilerServiceOptions\&.cs\fP\&.
.SS "Action<\fBICompilerServiceResource\fP, \fBILexer\fP>? Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.CompilerServiceOptions\&.OnAfterLexAction\fR [get]\fP"

.PP
Invoke an action which is passed the resource which was just lexed\&. This invocation occurs within a lock(_resourceMapLock) { \&.\&.\&. }\&. 
.PP
Definition at line \fB20\fP of file \fBCompilerServiceOptions\&.cs\fP\&.
.SS "Action<\fBICompilerServiceResource\fP, \fBCompilationUnit\fP?>? Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.CompilerServiceOptions\&.OnAfterParseAction\fR [get]\fP"

.PP
Invoke an action which is passed the resource which was just parsed\&. This invocation occurs within a lock(_resourceMapLock) { \&.\&.\&. }\&. 
.PP
Definition at line \fB25\fP of file \fBCompilerServiceOptions\&.cs\fP\&.
.SS "Func<\fBResourceUri\fP, \fBICompilerServiceResource\fP>? Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.CompilerServiceOptions\&.RegisterResourceFunc\fR [get]\fP"

.PP
Definition at line \fB9\fP of file \fBCompilerServiceOptions\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
