.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.CloseAssociatedGroupTokenTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.CloseAssociatedGroupTokenTests \- \fBCloseAssociatedGroupToken\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "CloseAssociatedGroupToken(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan) 
.br
----
.br
 \fBCloseAssociatedGroupToken\&.TextSpan\fP \fBCloseAssociatedGroupToken\&.IsFabricated\fP \fBCloseAssociatedGroupToken\&.SyntaxKind\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBCloseAssociatedGroupToken\fP 
.PP
Definition at line \fB8\fP of file \fBCloseAssociatedGroupTokenTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.Syntax\&.SyntaxTokens\&.CloseAssociatedGroupTokenTests\&.Constructor ()"

.PP
CloseAssociatedGroupToken(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan) 
.br
----
.br
 \fBCloseAssociatedGroupToken\&.TextSpan\fP \fBCloseAssociatedGroupToken\&.IsFabricated\fP \fBCloseAssociatedGroupToken\&.SyntaxKind\fP 
.PP
Definition at line \fB18\fP of file \fBCloseAssociatedGroupTokenTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
