.TH "Luthetus.Extensions.DotNet.Outputs.States.OutputScheduler" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.Outputs.States.OutputScheduler \-  

.SH SYNOPSIS
.br
.PP
.PP
Inherits IStateScheduler\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBEnqueue_ConstructTreeView\fP ()"
.br
.ti -1c
.RI "\fBOutputScheduler\fP (\fBDotNetBackgroundTaskApi\fP dotNetBackgroundTaskApi, \fBIBackgroundTaskService\fP backgroundTaskService, \fBDotNetCliOutputParser\fP dotNetCliOutputParser, \fBITreeViewService\fP treeViewService, \fBIEnvironmentProvider\fP environmentProvider, IDispatcher dispatcher)"
.br
.ti -1c
.RI "Task \fBTask_ConstructTreeView\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
Definition at line \fB6\fP of file \fBOutputScheduler\&.Enqueue\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Extensions\&.DotNet\&.Outputs\&.States\&.OutputScheduler\&.OutputScheduler (\fBDotNetBackgroundTaskApi\fP dotNetBackgroundTaskApi, \fBIBackgroundTaskService\fP backgroundTaskService, \fBDotNetCliOutputParser\fP dotNetCliOutputParser, \fBITreeViewService\fP treeViewService, \fBIEnvironmentProvider\fP environmentProvider, IDispatcher dispatcher)"

.PP
Definition at line \fB21\fP of file \fBOutputScheduler\&.Main\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Extensions\&.DotNet\&.Outputs\&.States\&.OutputScheduler\&.Enqueue_ConstructTreeView ()"

.PP
Definition at line \fB8\fP of file \fBOutputScheduler\&.Enqueue\&.cs\fP\&.
.SS "Task Luthetus\&.Extensions\&.DotNet\&.Outputs\&.States\&.OutputScheduler\&.Task_ConstructTreeView ()"

.PP
Definition at line \fB13\fP of file \fBOutputScheduler\&.TaskApi\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
