.TH "Luthetus.TextEditor.RazorLib.Decorations.Models.IDecorationMapperRegistry" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Decorations.Models.IDecorationMapperRegistry
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.Extensions\&.Config\&.Decorations\&.DecorationMapperRegistry\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.Decorations\&.Models\&.DecorationMapperRegistryDefault\fP, and \fBLuthetus\&.Tutorials\&.RazorLib\&.Decorations\&.DecorationMapperRegistry\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIDecorationMapper\fP \fBGetDecorationMapper\fP (string extensionNoPeriod)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBIDecorationMapperRegistry\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBIDecorationMapper\fP Luthetus\&.TextEditor\&.RazorLib\&.Decorations\&.Models\&.IDecorationMapperRegistry\&.GetDecorationMapper (string extensionNoPeriod)"

.PP
Implemented in \fBLuthetus\&.Extensions\&.Config\&.Decorations\&.DecorationMapperRegistry\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.Decorations\&.Models\&.DecorationMapperRegistryDefault\fP, and \fBLuthetus\&.Tutorials\&.RazorLib\&.Decorations\&.DecorationMapperRegistry\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
