.TH "Luthetus.TextEditor.Tests.Basis.Commands.Models.Vims.TextEditorCommandVimFactsMotionsTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.Commands.Models.Vims.TextEditorCommandVimFactsMotionsTests \- TextEditorCommandVimFacts\&.Motions  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async Task \fBWord\fP ()"
.br
.RI "TextEditorCommandVimFacts\&.Motions\&.Word "
.ti -1c
.RI "void \fBEnd\fP ()"
.br
.RI "TextEditorCommandVimFacts\&.Motions\&.End "
.ti -1c
.RI "void \fBPerformEnd\fP ()"
.br
.RI "TextEditorCommandVimFacts\&.Motions\&.PerformEnd(TextEditorCommandArgs, bool) "
.ti -1c
.RI "void \fBBack\fP ()"
.br
.RI "TextEditorCommandVimFacts\&.Motions\&.Back "
.ti -1c
.RI "void \fBGetVisual\fP ()"
.br
.RI "TextEditorCommandVimFacts\&.Motions\&.GetVisual(TextEditorCommand, string) "
.ti -1c
.RI "void \fBGetVisualLine\fP ()"
.br
.RI "TextEditorCommandVimFacts\&.Motions\&.GetVisualLineFactory(TextEditorCommand, string) "
.in -1c
.SH "Detailed Description"
.PP 
TextEditorCommandVimFacts\&.Motions 
.PP
Definition at line \fB11\fP of file \fBTextEditorCommandVimFactsMotionsTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Vims\&.TextEditorCommandVimFactsMotionsTests\&.Back ()"

.PP
TextEditorCommandVimFacts\&.Motions\&.Back 
.PP
Definition at line \fB50\fP of file \fBTextEditorCommandVimFactsMotionsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Vims\&.TextEditorCommandVimFactsMotionsTests\&.End ()"

.PP
TextEditorCommandVimFacts\&.Motions\&.End 
.PP
Definition at line \fB32\fP of file \fBTextEditorCommandVimFactsMotionsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Vims\&.TextEditorCommandVimFactsMotionsTests\&.GetVisual ()"

.PP
TextEditorCommandVimFacts\&.Motions\&.GetVisual(TextEditorCommand, string) 
.PP
Definition at line \fB59\fP of file \fBTextEditorCommandVimFactsMotionsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Vims\&.TextEditorCommandVimFactsMotionsTests\&.GetVisualLine ()"

.PP
TextEditorCommandVimFacts\&.Motions\&.GetVisualLineFactory(TextEditorCommand, string) 
.PP
Definition at line \fB68\fP of file \fBTextEditorCommandVimFactsMotionsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Vims\&.TextEditorCommandVimFactsMotionsTests\&.PerformEnd ()"

.PP
TextEditorCommandVimFacts\&.Motions\&.PerformEnd(TextEditorCommandArgs, bool) 
.PP
Definition at line \fB41\fP of file \fBTextEditorCommandVimFactsMotionsTests\&.cs\fP\&.
.SS "async Task Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Vims\&.TextEditorCommandVimFactsMotionsTests\&.Word ()"

.PP
TextEditorCommandVimFacts\&.Motions\&.Word 
.PP
Definition at line \fB17\fP of file \fBTextEditorCommandVimFactsMotionsTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
