.TH "Luthetus.Ide.Tests.Basis.InputFiles.States.InputFileStateActionsTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.Tests.Basis.InputFiles.States.InputFileStateActionsTests \- \fBInputFileState\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBSetSelectedTreeViewModelAction\fP ()"
.br
.RI "InputFileState\&.SetSelectedTreeViewModelAction "
.ti -1c
.RI "void \fBSetSelectedInputFilePatternAction\fP ()"
.br
.RI "InputFileState\&.SetSelectedInputFilePatternAction "
.ti -1c
.RI "void \fBSetSearchQueryAction\fP ()"
.br
.RI "InputFileState\&.SetSearchQueryAction "
.ti -1c
.RI "void \fBRefreshCurrentSelectionAction\fP ()"
.br
.RI "InputFileState\&.RefreshCurrentSelectionAction "
.ti -1c
.RI "void \fBMoveBackwardsInHistoryAction\fP ()"
.br
.RI "InputFileState\&.MoveBackwardsInHistoryAction "
.ti -1c
.RI "void \fBMoveForwardsInHistoryAction\fP ()"
.br
.RI "InputFileState\&.MoveForwardsInHistoryAction "
.ti -1c
.RI "void \fBSetOpenedTreeViewModelAction\fP ()"
.br
.RI "InputFileState\&.SetOpenedTreeViewModelAction "
.ti -1c
.RI "void \fBOpenParentDirectoryAction\fP ()"
.br
.RI "InputFileState\&.OpenParentDirectoryAction "
.ti -1c
.RI "void \fBStartInputFileStateFormAction\fP ()"
.br
.RI "InputFileState\&.StartInputFileStateFormAction "
.in -1c
.SH "Detailed Description"
.PP 
\fBInputFileState\fP 
.PP
Definition at line \fB8\fP of file \fBInputFileStateActionsTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.InputFiles\&.States\&.InputFileStateActionsTests\&.MoveBackwardsInHistoryAction ()"

.PP
InputFileState\&.MoveBackwardsInHistoryAction 
.PP
Definition at line \fB50\fP of file \fBInputFileStateActionsTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.InputFiles\&.States\&.InputFileStateActionsTests\&.MoveForwardsInHistoryAction ()"

.PP
InputFileState\&.MoveForwardsInHistoryAction 
.PP
Definition at line \fB59\fP of file \fBInputFileStateActionsTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.InputFiles\&.States\&.InputFileStateActionsTests\&.OpenParentDirectoryAction ()"

.PP
InputFileState\&.OpenParentDirectoryAction 
.PP
Definition at line \fB77\fP of file \fBInputFileStateActionsTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.InputFiles\&.States\&.InputFileStateActionsTests\&.RefreshCurrentSelectionAction ()"

.PP
InputFileState\&.RefreshCurrentSelectionAction 
.PP
Definition at line \fB41\fP of file \fBInputFileStateActionsTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.InputFiles\&.States\&.InputFileStateActionsTests\&.SetOpenedTreeViewModelAction ()"

.PP
InputFileState\&.SetOpenedTreeViewModelAction 
.PP
Definition at line \fB68\fP of file \fBInputFileStateActionsTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.InputFiles\&.States\&.InputFileStateActionsTests\&.SetSearchQueryAction ()"

.PP
InputFileState\&.SetSearchQueryAction 
.PP
Definition at line \fB32\fP of file \fBInputFileStateActionsTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.InputFiles\&.States\&.InputFileStateActionsTests\&.SetSelectedInputFilePatternAction ()"

.PP
InputFileState\&.SetSelectedInputFilePatternAction 
.PP
Definition at line \fB23\fP of file \fBInputFileStateActionsTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.InputFiles\&.States\&.InputFileStateActionsTests\&.SetSelectedTreeViewModelAction ()"

.PP
InputFileState\&.SetSelectedTreeViewModelAction 
.PP
Definition at line \fB14\fP of file \fBInputFileStateActionsTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.InputFiles\&.States\&.InputFileStateActionsTests\&.StartInputFileStateFormAction ()"

.PP
InputFileState\&.StartInputFileStateFormAction 
.PP
Definition at line \fB86\fP of file \fBInputFileStateActionsTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
