.TH "Luthetus.Ide.RazorLib.Shareds.States" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.Shareds.States
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "partial record \fBIdeHeaderState\fP (\fBMenuRecord\fP MenuFile, \fBMenuRecord\fP MenuTools, \fBMenuRecord\fP MenuView, \fBMenuRecord\fP MenuRun)"
.br
.ti -1c
.RI "record \fBIdeMainLayoutState\fP (ImmutableList< \fBFooterJustifyEndComponent\fP > FooterJustifyEndComponentList)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "partial record Luthetus\&.Ide\&.RazorLib\&.Shareds\&.States\&.IdeHeaderState (\fBMenuRecord\fP MenuFile, \fBMenuRecord\fP MenuTools, \fBMenuRecord\fP MenuView, \fBMenuRecord\fP MenuRun)"

.PP
Definition at line \fB10\fP of file \fBIdeHeaderState\&.Main\&.cs\fP\&.
.SS "record Luthetus\&.Ide\&.RazorLib\&.Shareds\&.States\&.IdeMainLayoutState (ImmutableList< \fBFooterJustifyEndComponent\fP > FooterJustifyEndComponentList)"

.PP
Definition at line \fB8\fP of file \fBIdeMainLayoutState\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
