.TH "Luthetus.Ide.RazorLib.FileSystems.Displays.FileFormDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.FileSystems.Displays.FileFormDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase, and \fBLuthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.IFileFormRendererType\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override Task \fBOnParametersSetAsync\fP ()"
.br
.ti -1c
.RI "override async Task \fBOnAfterRenderAsync\fP (bool firstRender)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "MenuOptionCallbacks? \fBMenuOptionCallbacks\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBFileName\fP = string\&.Empty\fR [get, set]\fP"
.br
.ti -1c
.RI "Func< string, \fBIFileTemplate\fP?, ImmutableArray< \fBIFileTemplate\fP >, Task > \fBOnAfterSubmitFunc\fP = null!\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsDirectory\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBCheckForTemplates\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBInputFileName\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBFileFormDisplay\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override async Task Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Displays\&.FileFormDisplay\&.OnAfterRenderAsync (bool firstRender)\fR [protected]\fP"

.PP
Definition at line \fB45\fP of file \fBFileFormDisplay\&.razor\&.cs\fP\&.
.SS "override Task Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Displays\&.FileFormDisplay\&.OnParametersSetAsync ()\fR [protected]\fP"

.PP
Definition at line \fB34\fP of file \fBFileFormDisplay\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Displays\&.FileFormDisplay\&.CheckForTemplates\fR [get]\fP, \fR [set]\fP"

.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.IFileFormRendererType\fP\&.
.PP
Definition at line \fB24\fP of file \fBFileFormDisplay\&.razor\&.cs\fP\&.
.SS "string Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Displays\&.FileFormDisplay\&.FileName = string\&.Empty\fR [get]\fP, \fR [set]\fP"

.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.IFileFormRendererType\fP\&.
.PP
Definition at line \fB17\fP of file \fBFileFormDisplay\&.razor\&.cs\fP\&.
.SS "string Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Displays\&.FileFormDisplay\&.InputFileName\fR [get]\fP"

.PP
Definition at line \fB32\fP of file \fBFileFormDisplay\&.razor\&.cs\fP\&.
.SS "bool Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Displays\&.FileFormDisplay\&.IsDirectory\fR [get]\fP, \fR [set]\fP"

.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.IFileFormRendererType\fP\&.
.PP
Definition at line \fB22\fP of file \fBFileFormDisplay\&.razor\&.cs\fP\&.
.SS "MenuOptionCallbacks? Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Displays\&.FileFormDisplay\&.MenuOptionCallbacks\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB14\fP of file \fBFileFormDisplay\&.razor\&.cs\fP\&.
.SS "Func<string, \fBIFileTemplate\fP?, ImmutableArray<\fBIFileTemplate\fP>, Task> Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Displays\&.FileFormDisplay\&.OnAfterSubmitFunc = null!\fR [get]\fP, \fR [set]\fP"

.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.IFileFormRendererType\fP\&.
.PP
Definition at line \fB19\fP of file \fBFileFormDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
