.TH "Luthetus.TextEditor.Tests.Basis.Characters.Models.RichCharacterExtensionsTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.Characters.Models.RichCharacterExtensionsTests \- RichCharacterExtensions  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBGetCharacterKind\fP ()"
.br
.RI "RichCharacterExtensions\&.GetCharacterKind(RichCharacter) "
.in -1c
.SH "Detailed Description"
.PP 
RichCharacterExtensions 
.PP
Definition at line \fB9\fP of file \fBRichCharacterExtensionsTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Characters\&.Models\&.RichCharacterExtensionsTests\&.GetCharacterKind ()"

.PP
RichCharacterExtensions\&.GetCharacterKind(RichCharacter) 
.PP
Definition at line \fB15\fP of file \fBRichCharacterExtensionsTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
