.TH "Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.Interfaces\&.IExpressionNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBConstructorInvocationExpressionNode\fP (\fBKeywordToken\fP newKeywordToken, \fBTypeClauseNode\fP typeClauseNode, \fBFunctionParametersListingNode\fP? functionParametersListingNode, \fBObjectInitializationParametersListingNode\fP? objectInitializationParametersListingNode)"
.br
.RI "The \fBGenericParametersListingNode\fP is located on the \fBTypeClauseNode\fP\&. "
.ti -1c
.RI "\fBConstructorInvocationExpressionNode\fP \fBSetTypeClauseNode\fP (\fBTypeClauseNode\fP? resultTypeClauseNode)"
.br
.ti -1c
.RI "\fBConstructorInvocationExpressionNode\fP \fBSetFunctionParametersListingNode\fP (\fBFunctionParametersListingNode\fP? functionParametersListingNode)"
.br
.ti -1c
.RI "\fBConstructorInvocationExpressionNode\fP \fBSetObjectInitializationParametersListingNode\fP (\fBObjectInitializationParametersListingNode\fP? objectInitializationParametersListingNode)"
.br
.ti -1c
.RI "\fBISyntax\fP[] \fBGetChildList\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBKeywordToken\fP \fBNewKeywordToken\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBTypeClauseNode\fP \fBResultTypeClauseNode\fP\fR [get]\fP"
.br
.RI "When parsing an expression, there may be a \fBFunctionInvocationNode\fP with a \fBGenericParametersListingNode\fP\&. "
.ti -1c
.RI "FunctionParametersListingNode? \fBFunctionParametersListingNode\fP\fR [get]\fP"
.br
.ti -1c
.RI "ObjectInitializationParametersListingNode? \fBObjectInitializationParametersListingNode\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBConstructorInvocationStageKind\fP \fBConstructorInvocationStageKind\fP = ConstructorInvocationStageKind\&.Unset\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBIsFabricated\fP\fR [get]\fP"
.br
.RI "\fBIsFabricated\fP refers to when the ParserSession expected a node to be valid, but it wasn't\&.
.br

.br
For example, a function invocation on an undefined function will construct a BoundFunctionInvocationNode with \fBIsFabricated\fP set to true\&. "
.ti -1c
.RI "\fBSyntaxKind\fP \fBSyntaxKind\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBConstructorInvocationExpressionNode\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.ConstructorInvocationExpressionNode\&.ConstructorInvocationExpressionNode (\fBKeywordToken\fP newKeywordToken, \fBTypeClauseNode\fP typeClauseNode, \fBFunctionParametersListingNode\fP? functionParametersListingNode, \fBObjectInitializationParametersListingNode\fP? objectInitializationParametersListingNode)"

.PP
The \fBGenericParametersListingNode\fP is located on the \fBTypeClauseNode\fP\&. 
.PP
Definition at line \fB14\fP of file \fBConstructorInvocationExpressionNode\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBISyntax\fP[] Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.ConstructorInvocationExpressionNode\&.GetChildList ()"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.ISyntaxNode\fP\&.
.PP
Definition at line \fB63\fP of file \fBConstructorInvocationExpressionNode\&.cs\fP\&.
.SS "\fBConstructorInvocationExpressionNode\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.ConstructorInvocationExpressionNode\&.SetFunctionParametersListingNode (\fBFunctionParametersListingNode\fP? functionParametersListingNode)"

.PP
Definition at line \fB47\fP of file \fBConstructorInvocationExpressionNode\&.cs\fP\&.
.SS "\fBConstructorInvocationExpressionNode\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.ConstructorInvocationExpressionNode\&.SetObjectInitializationParametersListingNode (\fBObjectInitializationParametersListingNode\fP? objectInitializationParametersListingNode)"

.PP
Definition at line \fB55\fP of file \fBConstructorInvocationExpressionNode\&.cs\fP\&.
.SS "\fBConstructorInvocationExpressionNode\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.ConstructorInvocationExpressionNode\&.SetTypeClauseNode (\fBTypeClauseNode\fP? resultTypeClauseNode)"

.PP
Definition at line \fB39\fP of file \fBConstructorInvocationExpressionNode\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBConstructorInvocationStageKind\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.ConstructorInvocationExpressionNode\&.ConstructorInvocationStageKind = ConstructorInvocationStageKind\&.Unset\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB34\fP of file \fBConstructorInvocationExpressionNode\&.cs\fP\&.
.SS "FunctionParametersListingNode? Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.ConstructorInvocationExpressionNode\&.FunctionParametersListingNode\fR [get]\fP"

.PP
Definition at line \fB31\fP of file \fBConstructorInvocationExpressionNode\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.ConstructorInvocationExpressionNode\&.IsFabricated\fR [get]\fP"

.PP
\fBIsFabricated\fP refers to when the ParserSession expected a node to be valid, but it wasn't\&.
.br

.br
For example, a function invocation on an undefined function will construct a BoundFunctionInvocationNode with \fBIsFabricated\fP set to true\&. 
.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.ISyntax\fP\&.
.PP
Definition at line \fB36\fP of file \fBConstructorInvocationExpressionNode\&.cs\fP\&.
.SS "\fBKeywordToken\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.ConstructorInvocationExpressionNode\&.NewKeywordToken\fR [get]\fP"

.PP
Definition at line \fB29\fP of file \fBConstructorInvocationExpressionNode\&.cs\fP\&.
.SS "ObjectInitializationParametersListingNode? Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.ConstructorInvocationExpressionNode\&.ObjectInitializationParametersListingNode\fR [get]\fP"

.PP
Definition at line \fB32\fP of file \fBConstructorInvocationExpressionNode\&.cs\fP\&.
.SS "\fBTypeClauseNode\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.ConstructorInvocationExpressionNode\&.ResultTypeClauseNode\fR [get]\fP"

.PP
When parsing an expression, there may be a \fBFunctionInvocationNode\fP with a \fBGenericParametersListingNode\fP\&. The expression code works however by passing around an 'IExpression expressionPrimary' and an 'IExpression expressionSeconday'\&.

.PP
This means we cannot add common logic for parsing a \fBGenericParametersListingNode\fP unless the expression parsing code were modified, or maybe a call to a separate function to parse \fBGenericParametersListingNode\fP could be done\&.

.PP
But, for now an experiment with making \fBGenericParametersListingNode\fP into a IExpressionNode is being tried out\&.

.PP
Any IExpressionNode that is part of a complete expression, will have the IExpressionNode\&.ResultTypeClauseNode of Pseudo in order to indicate that the node is part of a expression, but not itself an expression\&.

.PP
Use '\fBTypeClauseNode\fP IExpressionNode\&.ResultTypeClauseNode => TypeClauseNodeFacts\&.Pseudo;' so that some confusion can be avoided since one has to cast it explicitly as an IExpressionNode in order to access the property\&. (i\&.e\&.: \fBGenericParameterEntryNode\&.TypeClauseNode\fP is not equal to IExpressionNode\&.ResultTypeClauseNode)\&. 
.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.Interfaces\&.IExpressionNode\fP\&.
.PP
Definition at line \fB30\fP of file \fBConstructorInvocationExpressionNode\&.cs\fP\&.
.SS "\fBSyntaxKind\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.ConstructorInvocationExpressionNode\&.SyntaxKind\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.ISyntax\fP\&.
.PP
Definition at line \fB37\fP of file \fBConstructorInvocationExpressionNode\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
