.TH "Luthetus.TextEditor.RazorLib.CompilerServices.Implementations" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.CompilerServices.Implementations
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBBinderSession\fP"
.br
.ti -1c
.RI "class \fBCompilerService\fP"
.br
.ti -1c
.RI "class \fBCompilerServiceDoNothing\fP"
.br
.ti -1c
.RI "class \fBCompilerServiceOptions\fP"
.br
.ti -1c
.RI "class \fBLexer\fP"
.br
.ti -1c
.RI "class \fBLexerUtils\fP"
.br
.RI "TODO: Rewrite this class such that the lexed token is returned,\&.\&.\&. \&.\&.\&.rather than added to the list of 'syntaxTokens'\&. | It is awkward when one wants to use the 'Lex\&.\&.\&.(\&.\&.\&.)' method, yet afterwards needs to replace the last entry of 'syntaxTokens' with something of a different class, or syntax kind\&. "
.ti -1c
.RI "class \fBParser\fP"
.br
.ti -1c
.RI "struct \fBScope\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
