.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.MemberAccessTokenTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.MemberAccessTokenTests \- \fBMemberAccessToken\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "MemberAccessToken(TextEditorTextSpan) 
.br
----
.br
 \fBMemberAccessToken\&.TextSpan\fP \fBMemberAccessToken\&.SyntaxKind\fP \fBMemberAccessToken\&.IsFabricated\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBMemberAccessToken\fP 
.PP
Definition at line \fB10\fP of file \fBMemberAccessTokenTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.Syntax\&.SyntaxTokens\&.MemberAccessTokenTests\&.Constructor ()"

.PP
MemberAccessToken(TextEditorTextSpan) 
.br
----
.br
 \fBMemberAccessToken\&.TextSpan\fP \fBMemberAccessToken\&.SyntaxKind\fP \fBMemberAccessToken\&.IsFabricated\fP 
.PP
Definition at line \fB20\fP of file \fBMemberAccessTokenTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
