.TH "Luthetus.Common.RazorLib.Panels.States" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Panels.States
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "partial record \fBPanelState\fP (ImmutableArray< PanelGroup > PanelGroupList, ImmutableArray< \fBPanel\fP > PanelList)"
.br
.RI "TODO: SphagettiCode - The resizing and hiding/showing is a bit scuffed\&. (2023-09-19)\&. "
.in -1c
.SH "Function Documentation"
.PP 
.SS "partial record Luthetus\&.Common\&.RazorLib\&.Panels\&.States\&.PanelState (ImmutableArray< PanelGroup > PanelGroupList, ImmutableArray< \fBPanel\fP > PanelList)"

.PP
TODO: SphagettiCode - The resizing and hiding/showing is a bit scuffed\&. (2023-09-19)\&. 
.PP
Definition at line \fB14\fP of file \fBPanelState\&.Main\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
