.TH "Luthetus.Common.RazorLib.FileSystems.Models.LocalFileSystemProvider" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.FileSystems.Models.LocalFileSystemProvider
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IFileSystemProvider\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLocalFileSystemProvider\fP (\fBIEnvironmentProvider\fP environmentProvider, \fBICommonComponentRenderers\fP commonComponentRenderers, IDispatcher dispatcher)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBIFileHandler\fP \fBFile\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBIDirectoryHandler\fP \fBDirectory\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBLocalFileSystemProvider\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.LocalFileSystemProvider\&.LocalFileSystemProvider (\fBIEnvironmentProvider\fP environmentProvider, \fBICommonComponentRenderers\fP commonComponentRenderers, IDispatcher dispatcher)"

.PP
Definition at line \fB8\fP of file \fBLocalFileSystemProvider\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBIDirectoryHandler\fP Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.LocalFileSystemProvider\&.Directory\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IFileSystemProvider\fP\&.
.PP
Definition at line \fB18\fP of file \fBLocalFileSystemProvider\&.cs\fP\&.
.SS "\fBIFileHandler\fP Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.LocalFileSystemProvider\&.File\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IFileSystemProvider\fP\&.
.PP
Definition at line \fB17\fP of file \fBLocalFileSystemProvider\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
