.TH "Luthetus.TextEditor.RazorLib.Edits.Models.TextEditorEditInsertBatch" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Edits.Models.TextEditorEditInsertBatch
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.ITextEditorEdit\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextEditorEditInsertBatch\fP (int positionIndex, StringBuilder contentBuilder)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBPositionIndex\fP\fR [get]\fP"
.br
.ti -1c
.RI "StringBuilder \fBContentBuilder\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBTextEditorEditKind\fP \fBEditKind\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBTextEditorEditInsertBatch\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.TextEditorEditInsertBatch\&.TextEditorEditInsertBatch (int positionIndex, StringBuilder contentBuilder)"

.PP
Definition at line \fB7\fP of file \fBTextEditorEditInsertBatch\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "StringBuilder Luthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.TextEditorEditInsertBatch\&.ContentBuilder\fR [get]\fP"

.PP
Definition at line \fB14\fP of file \fBTextEditorEditInsertBatch\&.cs\fP\&.
.SS "\fBTextEditorEditKind\fP Luthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.TextEditorEditInsertBatch\&.EditKind\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.ITextEditorEdit\fP\&.
.PP
Definition at line \fB16\fP of file \fBTextEditorEditInsertBatch\&.cs\fP\&.
.SS "int Luthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.TextEditorEditInsertBatch\&.PositionIndex\fR [get]\fP"

.PP
Definition at line \fB13\fP of file \fBTextEditorEditInsertBatch\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
