.TH "Luthetus.Common.Tests.Basis.Panels.States.PanelStateActionsTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Panels.States.PanelStateActionsTests \- \fBPanelState\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRegisterPanelGroupAction\fP ()"
.br
.RI "PanelState\&.RegisterPanelGroupAction "
.ti -1c
.RI "void \fBDisposePanelGroupAction\fP ()"
.br
.RI "PanelState\&.DisposePanelGroupAction "
.ti -1c
.RI "void \fBRegisterPanelTabAction\fP ()"
.br
.RI "PanelState\&.RegisterPanelTabAction "
.ti -1c
.RI "void \fBDisposePanelTabAction\fP ()"
.br
.RI "PanelState\&.DisposePanelTabAction "
.ti -1c
.RI "void \fBSetActivePanelTabAction\fP ()"
.br
.RI "PanelState\&.SetActivePanelTabAction "
.ti -1c
.RI "void \fBSetPanelTabAsActiveByContextRecordKeyAction\fP ()"
.br
.RI "PanelState\&.SetPanelTabAsActiveByContextRecordKeyAction "
.ti -1c
.RI "void \fBSetDragEventArgsAction\fP ()"
.br
.RI "PanelState\&.SetDragEventArgsAction "
.in -1c
.SH "Detailed Description"
.PP 
\fBPanelState\fP 
.PP
Definition at line \fB23\fP of file \fBPanelStateTests\&.Actions\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Panels\&.States\&.PanelStateActionsTests\&.DisposePanelGroupAction ()"

.PP
PanelState\&.DisposePanelGroupAction 
.PP
Definition at line \fB40\fP of file \fBPanelStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Panels\&.States\&.PanelStateActionsTests\&.DisposePanelTabAction ()"

.PP
PanelState\&.DisposePanelTabAction 
.PP
Definition at line \fB88\fP of file \fBPanelStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Panels\&.States\&.PanelStateActionsTests\&.RegisterPanelGroupAction ()"

.PP
PanelState\&.RegisterPanelGroupAction 
.PP
Definition at line \fB29\fP of file \fBPanelStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Panels\&.States\&.PanelStateActionsTests\&.RegisterPanelTabAction ()"

.PP
PanelState\&.RegisterPanelTabAction 
.PP
Definition at line \fB51\fP of file \fBPanelStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Panels\&.States\&.PanelStateActionsTests\&.SetActivePanelTabAction ()"

.PP
PanelState\&.SetActivePanelTabAction 
.PP
Definition at line \fB104\fP of file \fBPanelStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Panels\&.States\&.PanelStateActionsTests\&.SetDragEventArgsAction ()"

.PP
PanelState\&.SetDragEventArgsAction 
.PP
Definition at line \fB136\fP of file \fBPanelStateTests\&.Actions\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Panels\&.States\&.PanelStateActionsTests\&.SetPanelTabAsActiveByContextRecordKeyAction ()"

.PP
PanelState\&.SetPanelTabAsActiveByContextRecordKeyAction 
.PP
Definition at line \fB120\fP of file \fBPanelStateTests\&.Actions\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
