.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.CommentSingleLineTokenTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.CommentSingleLineTokenTests \- \fBCommentSingleLineToken\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "CommentSingleLineToken(TextEditorTextSpan) 
.br
----
.br
 \fBCommentSingleLineToken\&.TextSpan\fP \fBCommentSingleLineToken\&.SyntaxKind\fP \fBCommentSingleLineToken\&.IsFabricated\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBCommentSingleLineToken\fP 
.PP
Definition at line \fB10\fP of file \fBCommentSingleLineTokenTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.Syntax\&.SyntaxTokens\&.CommentSingleLineTokenTests\&.Constructor ()"

.PP
CommentSingleLineToken(TextEditorTextSpan) 
.br
----
.br
 \fBCommentSingleLineToken\&.TextSpan\fP \fBCommentSingleLineToken\&.SyntaxKind\fP \fBCommentSingleLineToken\&.IsFabricated\fP 
.PP
Definition at line \fB20\fP of file \fBCommentSingleLineTokenTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
