.TH "Luthetus.Common.RazorLib.Dialogs.Models" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Dialogs.Models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDialogFacts\fP"
.br
.ti -1c
.RI "class \fBDialogHelper\fP"
.br
.ti -1c
.RI "class \fBDialogService\fP"
.br
.ti -1c
.RI "interface \fBIDialogService\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "\fBIDialog\fP \fBSetTitle\fP (string \fBtitle\fP)"
.br
.ti -1c
.RI "\fBIDialog\fP \fBSetIsMinimized\fP (bool isMinimized)"
.br
.ti -1c
.RI "\fBIDialog\fP \fBSetDialogIsMaximized\fP (bool isMaximized)"
.br
.ti -1c
.RI "\fBIDialog\fP \fBSetIsResizable\fP (bool \fBisResizable\fP)"
.br
.ti -1c
.RI "\fBIDialog\fP \fBSetCssClassString\fP (string cssClassString)"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "record \fBDialogViewModel\fP"
.br
.ti -1c
.RI "record string \fBtitle\fP"
.br
.ti -1c
.RI "record string Type \fBcomponentType\fP"
.br
.ti -1c
.RI "record string Type? Dictionary< string, object?> \fBcomponentParameterMap\fP"
.br
.ti -1c
.RI "record string Type? Dictionary< string, object?>? string \fBcssClass\fP"
.br
.ti -1c
.RI "record string Type? Dictionary< string, object?>? string bool \fBisResizable\fP"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "\fBIDialog\fP Luthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.SetCssClassString (string cssClassString)"

.PP
Definition at line \fB63\fP of file \fBDialogViewModel\&.cs\fP\&.
.SS "\fBIDialog\fP Luthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.SetDialogIsMaximized (bool isMaximized)"

.PP
Definition at line \fB53\fP of file \fBDialogViewModel\&.cs\fP\&.
.SS "\fBIDialog\fP Luthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.SetIsMinimized (bool isMinimized)"

.PP
Definition at line \fB48\fP of file \fBDialogViewModel\&.cs\fP\&.
.SS "\fBIDialog\fP Luthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.SetIsResizable (bool isResizable)"

.PP
Definition at line \fB58\fP of file \fBDialogViewModel\&.cs\fP\&.
.SS "\fBIDialog\fP Luthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.SetTitle (string title)"

.PP
Definition at line \fB43\fP of file \fBDialogViewModel\&.cs\fP\&.
.SH "Variable Documentation"
.PP 
.SS "record string Type? Dictionary<string, object?> Luthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.componentParameterMap"

.PP
Definition at line \fB13\fP of file \fBDialogViewModel\&.cs\fP\&.
.SS "record string Type Luthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.componentType"

.PP
Definition at line \fB12\fP of file \fBDialogViewModel\&.cs\fP\&.
.SS "record string Type? Dictionary<string, object?>? string Luthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.cssClass"

.PP
Definition at line \fB14\fP of file \fBDialogViewModel\&.cs\fP\&.
.SS "record Luthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.DialogViewModel"

.PP
Definition at line \fB7\fP of file \fBDialogViewModel\&.cs\fP\&.
.SS "record string Type? Dictionary<string, object?>? string bool Luthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.isResizable"

.PP
Definition at line \fB15\fP of file \fBDialogViewModel\&.cs\fP\&.
.SS "record string Luthetus\&.Common\&.RazorLib\&.Dialogs\&.Models\&.title"

.PP
Definition at line \fB11\fP of file \fBDialogViewModel\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
