.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.GenericLexer.GenericPreprocessorDefinitionTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.GenericLexer.GenericPreprocessorDefinitionTests \- \fBGenericPreprocessorDefinition\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "GenericPreprocessorDefinition(string, ImmutableArray<DeliminationExtendedSyntaxDefinition>) 
.br
----
.br
 \fBGenericPreprocessorDefinition\&.TransitionSubstring\fP \fBGenericPreprocessorDefinition\&.DeliminationExtendedSyntaxList\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBGenericPreprocessorDefinition\fP 
.PP
Definition at line \fB9\fP of file \fBGenericPreprocessorDefinitionTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.GenericLexer\&.GenericPreprocessorDefinitionTests\&.Constructor ()"

.PP
GenericPreprocessorDefinition(string, ImmutableArray<DeliminationExtendedSyntaxDefinition>) 
.br
----
.br
 \fBGenericPreprocessorDefinition\&.TransitionSubstring\fP \fBGenericPreprocessorDefinition\&.DeliminationExtendedSyntaxList\fP 
.PP
Definition at line \fB18\fP of file \fBGenericPreprocessorDefinitionTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
