.TH "Luthetus.TextEditor.Tests.Basis.Options.States.TextEditorOptionsStateReducerTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.Options.States.TextEditorOptionsStateReducerTests \- \fBTextEditorOptionsState\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBReduceSetFontFamilyAction\fP ()"
.br
.RI "TextEditorOptionsState\&.Reducer\&.ReduceSetFontFamilyAction(TextEditorOptionsState, TextEditorOptionsState\&.SetFontFamilyAction) "
.ti -1c
.RI "void \fBReduceSetFontSizeAction\fP ()"
.br
.RI "TextEditorOptionsState\&.Reducer\&.ReduceSetFontSizeAction(TextEditorOptionsState, TextEditorOptionsState\&.SetFontSizeAction) "
.ti -1c
.RI "void \fBReduceSetRenderStateKeyAction\fP ()"
.br
.RI "TextEditorOptionsState\&.Reducer\&.ReduceSetRenderStateKeyAction(TextEditorOptionsState, TextEditorOptionsState\&.SetRenderStateKeyAction) "
.ti -1c
.RI "void \fBReduceSetCursorWidthAction\fP ()"
.br
.RI "TextEditorOptionsState\&.Reducer\&.ReduceSetCursorWidthAction(TextEditorOptionsState, TextEditorOptionsState\&.SetCursorWidthAction) "
.ti -1c
.RI "void \fBReduceSetHeightAction\fP ()"
.br
.RI "TextEditorOptionsState\&.Reducer\&.ReduceSetHeightAction(TextEditorOptionsState, TextEditorOptionsState\&.SetHeightAction) "
.ti -1c
.RI "void \fBReduceSetThemeAction\fP ()"
.br
.RI "TextEditorOptionsState\&.Reducer\&.ReduceSetThemeAction(TextEditorOptionsState, TextEditorOptionsState\&.SetThemeAction) "
.ti -1c
.RI "void \fBReduceSetKeymapAction\fP ()"
.br
.RI "TextEditorOptionsState\&.Reducer\&.ReduceSetKeymapAction(TextEditorOptionsState, TextEditorOptionsState\&.SetKeymapAction) "
.ti -1c
.RI "void \fBReduceSetShowWhitespaceAction\fP ()"
.br
.RI "TextEditorOptionsState\&.Reducer\&.ReduceSetShowWhitespaceAction(TextEditorOptionsState, TextEditorOptionsState\&.SetShowWhitespaceAction) "
.ti -1c
.RI "void \fBReduceSetShowNewlinesAction\fP ()"
.br
.RI "TextEditorOptionsState\&.Reducer\&.ReduceSetShowNewlinesAction(TextEditorOptionsState, TextEditorOptionsState\&.SetShowNewlinesAction) "
.ti -1c
.RI "void \fBReduceSetUseMonospaceOptimizationsAction\fP ()"
.br
.RI "TextEditorOptionsState\&.Reducer\&.ReduceSetUseMonospaceOptimizationsAction(TextEditorOptionsState, TextEditorOptionsState\&.SetUseMonospaceOptimizationsAction) "
.in -1c
.SH "Detailed Description"
.PP 
\fBTextEditorOptionsState\fP 
.PP
Definition at line \fB19\fP of file \fBTextEditorOptionsState\&.ReducerTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.States\&.TextEditorOptionsStateReducerTests\&.ReduceSetCursorWidthAction ()"

.PP
TextEditorOptionsState\&.Reducer\&.ReduceSetCursorWidthAction(TextEditorOptionsState, TextEditorOptionsState\&.SetCursorWidthAction) 
.PP
Definition at line \fB103\fP of file \fBTextEditorOptionsState\&.ReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.States\&.TextEditorOptionsStateReducerTests\&.ReduceSetFontFamilyAction ()"

.PP
TextEditorOptionsState\&.Reducer\&.ReduceSetFontFamilyAction(TextEditorOptionsState, TextEditorOptionsState\&.SetFontFamilyAction) 
.PP
Definition at line \fB25\fP of file \fBTextEditorOptionsState\&.ReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.States\&.TextEditorOptionsStateReducerTests\&.ReduceSetFontSizeAction ()"

.PP
TextEditorOptionsState\&.Reducer\&.ReduceSetFontSizeAction(TextEditorOptionsState, TextEditorOptionsState\&.SetFontSizeAction) 
.PP
Definition at line \fB51\fP of file \fBTextEditorOptionsState\&.ReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.States\&.TextEditorOptionsStateReducerTests\&.ReduceSetHeightAction ()"

.PP
TextEditorOptionsState\&.Reducer\&.ReduceSetHeightAction(TextEditorOptionsState, TextEditorOptionsState\&.SetHeightAction) 
.PP
Definition at line \fB129\fP of file \fBTextEditorOptionsState\&.ReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.States\&.TextEditorOptionsStateReducerTests\&.ReduceSetKeymapAction ()"

.PP
TextEditorOptionsState\&.Reducer\&.ReduceSetKeymapAction(TextEditorOptionsState, TextEditorOptionsState\&.SetKeymapAction) 
.PP
Definition at line \fB200\fP of file \fBTextEditorOptionsState\&.ReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.States\&.TextEditorOptionsStateReducerTests\&.ReduceSetRenderStateKeyAction ()"

.PP
TextEditorOptionsState\&.Reducer\&.ReduceSetRenderStateKeyAction(TextEditorOptionsState, TextEditorOptionsState\&.SetRenderStateKeyAction) 
.PP
Definition at line \fB77\fP of file \fBTextEditorOptionsState\&.ReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.States\&.TextEditorOptionsStateReducerTests\&.ReduceSetShowNewlinesAction ()"

.PP
TextEditorOptionsState\&.Reducer\&.ReduceSetShowNewlinesAction(TextEditorOptionsState, TextEditorOptionsState\&.SetShowNewlinesAction) 
.PP
Definition at line \fB271\fP of file \fBTextEditorOptionsState\&.ReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.States\&.TextEditorOptionsStateReducerTests\&.ReduceSetShowWhitespaceAction ()"

.PP
TextEditorOptionsState\&.Reducer\&.ReduceSetShowWhitespaceAction(TextEditorOptionsState, TextEditorOptionsState\&.SetShowWhitespaceAction) 
.PP
Definition at line \fB226\fP of file \fBTextEditorOptionsState\&.ReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.States\&.TextEditorOptionsStateReducerTests\&.ReduceSetThemeAction ()"

.PP
TextEditorOptionsState\&.Reducer\&.ReduceSetThemeAction(TextEditorOptionsState, TextEditorOptionsState\&.SetThemeAction) 
.PP
Definition at line \fB174\fP of file \fBTextEditorOptionsState\&.ReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.States\&.TextEditorOptionsStateReducerTests\&.ReduceSetUseMonospaceOptimizationsAction ()"

.PP
TextEditorOptionsState\&.Reducer\&.ReduceSetUseMonospaceOptimizationsAction(TextEditorOptionsState, TextEditorOptionsState\&.SetUseMonospaceOptimizationsAction) 
.PP
Definition at line \fB316\fP of file \fBTextEditorOptionsState\&.ReducerTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
