.TH "Luthetus.Ide.Tests.Basis.CodeSearches.States.CodeSearchStateEffectorTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.Tests.Basis.CodeSearches.States.CodeSearchStateEffectorTests \- CodeSearchState\&.Effector  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "CodeSearchState\&.Effector\&.Effector(IState<CodeSearchState>, IState<DotNetSolutionState>, IFileSystemProvider) "
.ti -1c
.RI "void \fBHandleSearchEffect\fP ()"
.br
.RI "CodeSearchState\&.Effector\&.HandleSearchEffect(CodeSearchState\&.SearchEffect, IDispatcher) "
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.RI "CodeSearchState\&.Effector\&.Dispose() "
.in -1c
.SH "Detailed Description"
.PP 
CodeSearchState\&.Effector 
.PP
Definition at line \fB10\fP of file \fBCodeSearchStateEffectorTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.CodeSearches\&.States\&.CodeSearchStateEffectorTests\&.Constructor ()"

.PP
CodeSearchState\&.Effector\&.Effector(IState<CodeSearchState>, IState<DotNetSolutionState>, IFileSystemProvider) 
.PP
Definition at line \fB16\fP of file \fBCodeSearchStateEffectorTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.CodeSearches\&.States\&.CodeSearchStateEffectorTests\&.Dispose ()"

.PP
CodeSearchState\&.Effector\&.Dispose() 
.PP
Definition at line \fB34\fP of file \fBCodeSearchStateEffectorTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.CodeSearches\&.States\&.CodeSearchStateEffectorTests\&.HandleSearchEffect ()"

.PP
CodeSearchState\&.Effector\&.HandleSearchEffect(CodeSearchState\&.SearchEffect, IDispatcher) 
.PP
Definition at line \fB25\fP of file \fBCodeSearchStateEffectorTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
