.TH "Luthetus.CompilerServices.DotNetSolution.Models.Project.CSharpProjectSyntaxWalker" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.DotNetSolution.Models.Project.CSharpProjectSyntaxWalker
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.XmlSyntaxWalker\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "override void \fBVisitTagOpeningNode\fP (\fBTagNode\fP node)"
.br
.ti -1c
.RI "override void \fBVisitTagClosingNode\fP (\fBTagNode\fP node)"
.br
.ti -1c
.RI "override void \fBVisitTagSelfClosingNode\fP (\fBTagNode\fP node)"
.br
.in -1c

Public Member Functions inherited from \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.XmlSyntaxWalker\fP
.in +1c
.ti -1c
.RI "virtual void \fBVisit\fP (\fBIHtmlSyntaxNode\fP node)"
.br
.ti -1c
.RI "virtual void \fBVisitAttributeNameNode\fP (\fBAttributeNameNode\fP node)"
.br
.ti -1c
.RI "virtual void \fBVisitAttributeValueNode\fP (\fBAttributeValueNode\fP node)"
.br
.ti -1c
.RI "virtual void \fBVisitAttributeNode\fP (\fBAttributeNode\fP node)"
.br
.ti -1c
.RI "virtual void \fBVisitCommentNode\fP (\fBCommentNode\fP node)"
.br
.ti -1c
.RI "virtual void \fBVisitInjectedLanguageFragmentNode\fP (\fBInjectedLanguageFragmentNode\fP node)"
.br
.ti -1c
.RI "virtual void \fBVisitTagNameNode\fP (\fBTagNameNode\fP node)"
.br
.ti -1c
.RI "virtual void \fBVisitTextNode\fP (\fBTextNode\fP node)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "List< \fBTagNode\fP > \fBTagNodes\fP = new()\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBCSharpProjectSyntaxWalker\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.CSharpProjectSyntaxWalker\&.VisitTagClosingNode (\fBTagNode\fP node)\fR [virtual]\fP"

.PP
Reimplemented from \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.XmlSyntaxWalker\fP\&.
.PP
Definition at line \fB15\fP of file \fBCSharpProjectSyntaxWalker\&.cs\fP\&.
.SS "override void Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.CSharpProjectSyntaxWalker\&.VisitTagOpeningNode (\fBTagNode\fP node)\fR [virtual]\fP"

.PP
Reimplemented from \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.XmlSyntaxWalker\fP\&.
.PP
Definition at line \fB10\fP of file \fBCSharpProjectSyntaxWalker\&.cs\fP\&.
.SS "override void Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.CSharpProjectSyntaxWalker\&.VisitTagSelfClosingNode (\fBTagNode\fP node)\fR [virtual]\fP"

.PP
Reimplemented from \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.XmlSyntaxWalker\fP\&.
.PP
Definition at line \fB20\fP of file \fBCSharpProjectSyntaxWalker\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "List<\fBTagNode\fP> Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Project\&.CSharpProjectSyntaxWalker\&.TagNodes = new()\fR [get]\fP"

.PP
Definition at line \fB8\fP of file \fBCSharpProjectSyntaxWalker\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
