.TH "Luthetus.Extensions.DotNet.Namespaces.Models.TreeViewHelperRazorMarkup" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.Namespaces.Models.TreeViewHelperRazorMarkup
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static async Task< List< \fBTreeViewNoType\fP > > \fBLoadChildrenAsync\fP (\fBTreeViewNamespacePath\fP razorMarkupTreeView)"
.br
.RI "This method is used in order to allow for collapsing and expanding the node to refresh the codebehinds\&. "
.ti -1c
.RI "static void \fBFindRelatedFiles\fP (\fBTreeViewNamespacePath\fP razorMarkupTreeView, List< \fBTreeViewNoType\fP > siblingsAndSelfTreeViews)"
.br
.RI "This method is used in order to remove from the parent node, various siblings which will be moved to be a child node of the '\&.razor' file\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBTreeViewHelperRazorMarkup\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Extensions\&.DotNet\&.Namespaces\&.Models\&.TreeViewHelperRazorMarkup\&.FindRelatedFiles (\fBTreeViewNamespacePath\fP razorMarkupTreeView, List< \fBTreeViewNoType\fP > siblingsAndSelfTreeViews)\fR [static]\fP"

.PP
This method is used in order to remove from the parent node, various siblings which will be moved to be a child node of the '\&.razor' file\&. This is method not the same as LoadChildrenAsync\&. 
.PP
Definition at line \fB55\fP of file \fBTreeViewHelperRazorMarkup\&.cs\fP\&.
.SS "async Task< List< \fBTreeViewNoType\fP > > Luthetus\&.Extensions\&.DotNet\&.Namespaces\&.Models\&.TreeViewHelperRazorMarkup\&.LoadChildrenAsync (\fBTreeViewNamespacePath\fP razorMarkupTreeView)\fR [static]\fP"

.PP
This method is used in order to allow for collapsing and expanding the node to refresh the codebehinds\&. This method is not the same as FindRelatedFiles\&. 
.PP
Definition at line \fB16\fP of file \fBTreeViewHelperRazorMarkup\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
