.TH "Luthetus.Common.RazorLib.Storages.Models.DoNothingStorageService" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Storages.Models.DoNothingStorageService
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Common\&.RazorLib\&.Storages\&.Models\&.IStorageService\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "ValueTask \fBSetValue\fP (string key, object? value)"
.br
.ti -1c
.RI "ValueTask< object?> \fBGetValue\fP (string key)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBDoNothingStorageService\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "ValueTask< object?> Luthetus\&.Common\&.RazorLib\&.Storages\&.Models\&.DoNothingStorageService\&.GetValue (string key)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.Storages\&.Models\&.IStorageService\fP\&.
.PP
Definition at line \fB10\fP of file \fBDoNothingStorageService\&.cs\fP\&.
.SS "ValueTask Luthetus\&.Common\&.RazorLib\&.Storages\&.Models\&.DoNothingStorageService\&.SetValue (string key, object? value)"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.Storages\&.Models\&.IStorageService\fP\&.
.PP
Definition at line \fB5\fP of file \fBDoNothingStorageService\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
