.TH "Luthetus.Ide.RazorLib.InputFiles.Displays.InputFileEditAddress" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.InputFiles.Displays.InputFileEditAddress
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInitialized\fP ()"
.br
.ti -1c
.RI "override async Task \fBOnAfterRenderAsync\fP (bool firstRender)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBInitialInputValue\fP = null!\fR [get, set]\fP"
.br
.ti -1c
.RI "Func< string, Task > \fBOnFocusOutCallbackAsync\fP = null!\fR [get, set]\fP"
.br
.ti -1c
.RI "Func< Task > \fBOnEscapeKeyDownCallbackAsync\fP = null!\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBInputFileEditAddress\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override async Task Luthetus\&.Ide\&.RazorLib\&.InputFiles\&.Displays\&.InputFileEditAddress\&.OnAfterRenderAsync (bool firstRender)\fR [protected]\fP"

.PP
Definition at line \fB27\fP of file \fBInputFileEditAddress\&.razor\&.cs\fP\&.
.SS "override void Luthetus\&.Ide\&.RazorLib\&.InputFiles\&.Displays\&.InputFileEditAddress\&.OnInitialized ()\fR [protected]\fP"

.PP
Definition at line \fB20\fP of file \fBInputFileEditAddress\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Luthetus\&.Ide\&.RazorLib\&.InputFiles\&.Displays\&.InputFileEditAddress\&.InitialInputValue = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB10\fP of file \fBInputFileEditAddress\&.razor\&.cs\fP\&.
.SS "Func<Task> Luthetus\&.Ide\&.RazorLib\&.InputFiles\&.Displays\&.InputFileEditAddress\&.OnEscapeKeyDownCallbackAsync = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB14\fP of file \fBInputFileEditAddress\&.razor\&.cs\fP\&.
.SS "Func<string, Task> Luthetus\&.Ide\&.RazorLib\&.InputFiles\&.Displays\&.InputFileEditAddress\&.OnFocusOutCallbackAsync = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB12\fP of file \fBInputFileEditAddress\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
