.TH "Luthetus.TextEditor.Tests.Basis.TextEditorTestBase" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.TextEditorTestBase \- It is preferred that each test defines its own test data within the '[Fact]' method itself\&. There however is 100 lines of code at the beginning of every test if one follows this rule\&. To reduce the noise, this method was created\&.
.br

.br
\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelExtensionMethodsTests\fP, \fBLuthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelModifierTests\fP, and \fBLuthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorViewModelApiTests\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "\fBBackgroundTaskService\fP \fBContinuousBackgroundTaskWorker\fP IDispatcher \fBITextEditorService\fP \fBtextEditorService\fP \fBInitializeBackgroundTasks\fP ()"
.br
.ti -1c
.RI "\fBTextEditorModel\fP \fBTextEditorModelModifier\fP modelModifier \fBEmptyEditor_TestData_And_PerformPreAssertions\fP (\fBResourceUri\fP \fBresourceUri\fP, DateTime resourceLastWriteTime, string fileExtension, string content, \fBIDecorationMapper\fP? decorationMapper, \fBICompilerService\fP? compilerService, int partitionSize)"
.br
.ti -1c
.RI "\fBTextEditorModel\fP \fBTextEditorModelModifier\fP modelModifier \fBNotEmptyEditor_TestData_And_PerformPreAssertions\fP (\fBResourceUri\fP \fBresourceUri\fP, DateTime resourceLastWriteTime, string fileExtension, string content, \fBIDecorationMapper\fP? decorationMapper, \fBICompilerService\fP? compilerService, int partitionSize)"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "\fBBackgroundTaskService\fP \fBbackgroundTaskService\fP"
.br
.ti -1c
.RI "\fBBackgroundTaskService\fP \fBContinuousBackgroundTaskWorker\fP \fBbackgroundTaskWorker\fP"
.br
.ti -1c
.RI "\fBBackgroundTaskService\fP \fBContinuousBackgroundTaskWorker\fP IDispatcher \fBdispatcher\fP"
.br
.ti -1c
.RI "\fBTextEditorModel\fP \fBinModel\fP"
.br
.RI "Text Editor UI result (with show-newlines and show-whitespace; arrow is tab, and dot is space)
.br
 ===================== 
.br
 1 
.br
 
.br
 2 b9\\r 
.br
 3 9B\\r
.br
 
.br
 4 --->$;∙EOF 
.br
\&. "
.in -1c
.SH "Detailed Description"
.PP 
It is preferred that each test defines its own test data within the '[Fact]' method itself\&. There however is 100 lines of code at the beginning of every test if one follows this rule\&. To reduce the noise, this method was created\&.
.br

.br
\&. 

That being said, it is vital that the test defines its test-data, otherwise some readonly and static data might one day have the source code for its definition change\&. Any dependent tests would then break, and a great deal of confusion would arise, because it would not be clear that the test data was changed\&.
.br

.br

.PP
For this reason, the '[Fact]' method must invoke this method with every parameter needed to construct the test data\&. In this method, the exact same parameters that were passed in will be typed out in the source code for this method\&.
.br

.br

.PP
If the parameters to this method, and the hardcoded local variables of this method match, then the test and this method agree on what the test data is\&. At that point the test data can be constructed, and the pre-assertions can be done from within this method\&.
.br

.br

.PP
Lastly, return the test data\&. 
.PP
Definition at line \fB36\fP of file \fBTextEditorTestBase\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBTextEditorModel\fP \fBTextEditorModelModifier\fP modelModifier Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditorTestBase\&.EmptyEditor_TestData_And_PerformPreAssertions (\fBResourceUri\fP resourceUri, DateTime resourceLastWriteTime, string fileExtension, string content, \fBIDecorationMapper\fP? decorationMapper, \fBICompilerService\fP? compilerService, int partitionSize)\fR [protected]\fP"

.PP
Definition at line \fB72\fP of file \fBTextEditorTestBase\&.cs\fP\&.
.SS "\fBBackgroundTaskService\fP \fBContinuousBackgroundTaskWorker\fP IDispatcher \fBITextEditorService\fP \fBtextEditorService\fP Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditorTestBase\&.InitializeBackgroundTasks ()\fR [protected]\fP"

.PP
Definition at line \fB42\fP of file \fBTextEditorTestBase\&.cs\fP\&.
.SS "\fBTextEditorModel\fP \fBTextEditorModelModifier\fP modelModifier Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditorTestBase\&.NotEmptyEditor_TestData_And_PerformPreAssertions (\fBResourceUri\fP resourceUri, DateTime resourceLastWriteTime, string fileExtension, string content, \fBIDecorationMapper\fP? decorationMapper, \fBICompilerService\fP? compilerService, int partitionSize)\fR [protected]\fP"

.PP
Definition at line \fB203\fP of file \fBTextEditorTestBase\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBBackgroundTaskService\fP Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditorTestBase\&.backgroundTaskService\fR [protected]\fP"

.PP
Definition at line \fB39\fP of file \fBTextEditorTestBase\&.cs\fP\&.
.SS "\fBBackgroundTaskService\fP \fBContinuousBackgroundTaskWorker\fP Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditorTestBase\&.backgroundTaskWorker\fR [protected]\fP"

.PP
Definition at line \fB40\fP of file \fBTextEditorTestBase\&.cs\fP\&.
.SS "\fBBackgroundTaskService\fP \fBContinuousBackgroundTaskWorker\fP IDispatcher Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditorTestBase\&.dispatcher\fR [protected]\fP"

.PP
Definition at line \fB41\fP of file \fBTextEditorTestBase\&.cs\fP\&.
.SS "\fBTextEditorModel\fP Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditorTestBase\&.inModel\fR [protected]\fP"

.PP
Text Editor UI result (with show-newlines and show-whitespace; arrow is tab, and dot is space)
.br
 ===================== 
.br
 1 
.br
 
.br
 2 b9\\r 
.br
 3 9B\\r
.br
 
.br
 4 --->$;∙EOF 
.br
\&. 
.PP
Definition at line \fB72\fP of file \fBTextEditorTestBase\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
