.TH "Luthetus.CompilerServices.Css.SyntaxObjects.CssIdentifierSyntax" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.Css.SyntaxObjects.CssIdentifierSyntax
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.CompilerServices\&.Css\&.ICssSyntax\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCssIdentifierSyntax\fP (\fBTextEditorTextSpan\fP textEditorTextSpan, ImmutableArray< \fBICssSyntax\fP > childCssSyntaxes)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "TextEditorTextSpan \fBTextEditorTextSpan\fP\fR [get]\fP"
.br
.ti -1c
.RI "ImmutableArray< \fBICssSyntax\fP > \fBChildCssSyntaxes\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBCssSyntaxKind\fP \fBCssSyntaxKind\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBCssIdentifierSyntax\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.CompilerServices\&.Css\&.SyntaxObjects\&.CssIdentifierSyntax\&.CssIdentifierSyntax (\fBTextEditorTextSpan\fP textEditorTextSpan, ImmutableArray< \fBICssSyntax\fP > childCssSyntaxes)"

.PP
Definition at line \fB9\fP of file \fBCssIdentifierSyntax\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "ImmutableArray<\fBICssSyntax\fP> Luthetus\&.CompilerServices\&.Css\&.SyntaxObjects\&.CssIdentifierSyntax\&.ChildCssSyntaxes\fR [get]\fP"

.PP
Implements \fBLuthetus\&.CompilerServices\&.Css\&.ICssSyntax\fP\&.
.PP
Definition at line \fB18\fP of file \fBCssIdentifierSyntax\&.cs\fP\&.
.SS "\fBCssSyntaxKind\fP Luthetus\&.CompilerServices\&.Css\&.SyntaxObjects\&.CssIdentifierSyntax\&.CssSyntaxKind\fR [get]\fP"

.PP
Implements \fBLuthetus\&.CompilerServices\&.Css\&.ICssSyntax\fP\&.
.PP
Definition at line \fB20\fP of file \fBCssIdentifierSyntax\&.cs\fP\&.
.SS "TextEditorTextSpan Luthetus\&.CompilerServices\&.Css\&.SyntaxObjects\&.CssIdentifierSyntax\&.TextEditorTextSpan\fR [get]\fP"

.PP
Implements \fBLuthetus\&.CompilerServices\&.Css\&.ICssSyntax\fP\&.
.PP
Definition at line \fB17\fP of file \fBCssIdentifierSyntax\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
