.TH "Luthetus.Ide.Tests.Basis.Terminals.Models.TerminalTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.Tests.Basis.Terminals.Models.TerminalTests \- \fBTerminal\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "Terminal(string, string?, IDispatcher, IBackgroundTaskService, ITextEditorService, ILuthetusCommonComponentRenderers, ICompilerServiceRegistry) 
.br
----
.br
 \fBTerminal\&.Key\fP Terminal\&.WorkingDirectoryAbsolutePathString Terminal\&.ActiveTerminalCommand \fBTerminal\&.HasExecutingProcess\fP Terminal\&.TerminalCommandsHistory Terminal\&.ResourceUri Terminal\&.TextEditorViewModelKey "
.ti -1c
.RI "void \fBEnqueueCommandAsync\fP ()"
.br
.RI "Terminal\&.EnqueueCommandAsync(TerminalCommand) "
.ti -1c
.RI "void \fBClearStandardOut_NO_ARGS\fP ()"
.br
.RI "Terminal\&.ClearStandardOut() "
.ti -1c
.RI "void \fBClearStandardOut_WITH_ARGS\fP ()"
.br
.RI "Terminal\&.ClearStandardOut(Key<TerminalCommand>) "
.ti -1c
.RI "void \fBKillProcess\fP ()"
.br
.RI "\fBTerminal\&.KillProcess()\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBTerminal\fP 
.PP
Definition at line \fB12\fP of file \fBTerminalTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.Terminals\&.Models\&.TerminalTests\&.ClearStandardOut_NO_ARGS ()"

.PP
Terminal\&.ClearStandardOut() 
.PP
Definition at line \fB44\fP of file \fBTerminalTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.Terminals\&.Models\&.TerminalTests\&.ClearStandardOut_WITH_ARGS ()"

.PP
Terminal\&.ClearStandardOut(Key<TerminalCommand>) 
.PP
Definition at line \fB53\fP of file \fBTerminalTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.Terminals\&.Models\&.TerminalTests\&.Constructor ()"

.PP
Terminal(string, string?, IDispatcher, IBackgroundTaskService, ITextEditorService, ILuthetusCommonComponentRenderers, ICompilerServiceRegistry) 
.br
----
.br
 \fBTerminal\&.Key\fP Terminal\&.WorkingDirectoryAbsolutePathString Terminal\&.ActiveTerminalCommand \fBTerminal\&.HasExecutingProcess\fP Terminal\&.TerminalCommandsHistory Terminal\&.ResourceUri Terminal\&.TextEditorViewModelKey 
.PP
Definition at line \fB26\fP of file \fBTerminalTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.Terminals\&.Models\&.TerminalTests\&.EnqueueCommandAsync ()"

.PP
Terminal\&.EnqueueCommandAsync(TerminalCommand) 
.PP
Definition at line \fB35\fP of file \fBTerminalTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.Terminals\&.Models\&.TerminalTests\&.KillProcess ()"

.PP
\fBTerminal\&.KillProcess()\fP 
.PP
Definition at line \fB62\fP of file \fBTerminalTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
