.TH "Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.ICompilerServiceResource" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.ICompilerServiceResource
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.CompilerServiceResource\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "ImmutableArray< \fBTextEditorTextSpan\fP > \fBGetTokenTextSpans\fP ()"
.br
.ti -1c
.RI "ImmutableArray< \fBITextEditorSymbol\fP > \fBGetSymbols\fP ()"
.br
.ti -1c
.RI "ImmutableArray< \fBTextEditorDiagnostic\fP > \fBGetDiagnostics\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "ResourceUri \fBResourceUri\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBICompilerService\fP \fBCompilerService\fP\fR [get]\fP"
.br
.ti -1c
.RI "CompilationUnit? \fBCompilationUnit\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "ImmutableArray< \fBISyntaxToken\fP > \fBSyntaxTokenList\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBICompilerServiceResource\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "ImmutableArray< \fBTextEditorDiagnostic\fP > Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.ICompilerServiceResource\&.GetDiagnostics ()"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.CompilerServiceResource\fP\&.
.SS "ImmutableArray< \fBITextEditorSymbol\fP > Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.ICompilerServiceResource\&.GetSymbols ()"

.PP
Implemented in \fBLuthetus\&.CompilerServices\&.Razor\&.CompilerServiceCase\&.RazorResource\fP, \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalResource\fP, and \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.CompilerServiceResource\fP\&.
.SS "ImmutableArray< \fBTextEditorTextSpan\fP > Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.ICompilerServiceResource\&.GetTokenTextSpans ()"

.PP
Implemented in \fBLuthetus\&.CompilerServices\&.CSharp\&.CompilerServiceCase\&.CSharpResource\fP, \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalResource\fP, and \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.CompilerServiceResource\fP\&.
.SH "Property Documentation"
.PP 
.SS "CompilationUnit? Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.ICompilerServiceResource\&.CompilationUnit\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.CompilerServiceResource\fP\&.
.PP
Definition at line \fB12\fP of file \fBICompilerServiceResource\&.cs\fP\&.
.SS "\fBICompilerService\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.ICompilerServiceResource\&.CompilerService\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.CompilerServiceResource\fP\&.
.PP
Definition at line \fB11\fP of file \fBICompilerServiceResource\&.cs\fP\&.
.SS "ResourceUri Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.ICompilerServiceResource\&.ResourceUri\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.CompilerServiceResource\fP\&.
.PP
Definition at line \fB10\fP of file \fBICompilerServiceResource\&.cs\fP\&.
.SS "ImmutableArray<\fBISyntaxToken\fP> Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.ICompilerServiceResource\&.SyntaxTokenList\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalResource\fP, and \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.CompilerServiceResource\fP\&.
.PP
Definition at line \fB13\fP of file \fBICompilerServiceResource\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
