.TH "Luthetus.Common.RazorLib.Contexts.Displays.ContextDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Contexts.Displays.ContextDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits FluxorComponent\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInitialized\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Key< \fBContextRecord\fP > \fBContextKey\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBContextDisplay\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Luthetus\&.Common\&.RazorLib\&.Contexts\&.Displays\&.ContextDisplay\&.OnInitialized ()\fR [protected]\fP"

.PP
Definition at line \fB23\fP of file \fBContextDisplay\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Key<\fBContextRecord\fP> Luthetus\&.Common\&.RazorLib\&.Contexts\&.Displays\&.ContextDisplay\&.ContextKey\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB19\fP of file \fBContextDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
