.TH "Luthetus.Common.Tests.Basis.TreeViews.Models.TreeViewWithTypeTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.TreeViews.Models.TreeViewWithTypeTests \- \fBTreeViewWithType<T>\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "\fBTreeViewWithType<T>\&.TreeViewWithType(T, bool, bool)\fP "
.ti -1c
.RI "void \fBItem\fP ()"
.br
.RI "\fBTreeViewWithType<T>\&.Item\fP "
.ti -1c
.RI "void \fBUntypedItem\fP ()"
.br
.RI "\fBTreeViewWithType<T>\&.UntypedItem\fP "
.ti -1c
.RI "void \fBItemType\fP ()"
.br
.RI "\fBTreeViewWithType<T>\&.ItemType\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBTreeViewWithType<T>\fP 
.PP
Definition at line \fB8\fP of file \fBTreeViewWithTypeTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.Models\&.TreeViewWithTypeTests\&.Constructor ()"

.PP
\fBTreeViewWithType<T>\&.TreeViewWithType(T, bool, bool)\fP 
.PP
Definition at line \fB14\fP of file \fBTreeViewWithTypeTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.Models\&.TreeViewWithTypeTests\&.Item ()"

.PP
\fBTreeViewWithType<T>\&.Item\fP 
.PP
Definition at line \fB23\fP of file \fBTreeViewWithTypeTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.Models\&.TreeViewWithTypeTests\&.ItemType ()"

.PP
\fBTreeViewWithType<T>\&.ItemType\fP 
.PP
Definition at line \fB41\fP of file \fBTreeViewWithTypeTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.Models\&.TreeViewWithTypeTests\&.UntypedItem ()"

.PP
\fBTreeViewWithType<T>\&.UntypedItem\fP 
.PP
Definition at line \fB32\fP of file \fBTreeViewWithTypeTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
