.TH "Luthetus.TextEditor.Tests.Basis.Virtualizations.Models" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.Virtualizations.Models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBVirtualizationBoundaryTests\fP"
.br
.RI "\fBVirtualizationBoundary\fP "
.ti -1c
.RI "class \fBVirtualizationEntryTests\fP"
.br
.RI "VirtualizationEntry<T> "
.ti -1c
.RI "class \fBVirtualizationRequestTests\fP"
.br
.RI "\fBVirtualizationRequest\fP "
.ti -1c
.RI "class \fBVirtualizationScrollPositionTests\fP"
.br
.RI "\fBVirtualizationScrollPosition\fP "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
