.TH "Luthetus.Common.Tests.Basis.Keymaps.Models.KeymapTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Keymaps.Models.KeymapTests \- \fBKeymap\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructorA\fP ()"
.br
.RI "Keymap(Key<Keymap>, string) 
.br
----
.br
 \fBKeymap\&.Key\fP \fBKeymap\&.DisplayName\fP "
.ti -1c
.RI "void \fBEmpty\fP ()"
.br
.RI "Keymap\&.Empty "
.ti -1c
.RI "void \fBMap\fP ()"
.br
.RI "\fBKeymap\&.MapAll\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBKeymap\fP 
.PP
Definition at line \fB10\fP of file \fBKeymapTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Keymaps\&.Models\&.KeymapTests\&.ConstructorA ()"

.PP
Keymap(Key<Keymap>, string) 
.br
----
.br
 \fBKeymap\&.Key\fP \fBKeymap\&.DisplayName\fP 
.PP
Definition at line \fB19\fP of file \fBKeymapTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Keymaps\&.Models\&.KeymapTests\&.Empty ()"

.PP
Keymap\&.Empty 
.PP
Definition at line \fB34\fP of file \fBKeymapTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Keymaps\&.Models\&.KeymapTests\&.Map ()"

.PP
\fBKeymap\&.MapAll\fP 
.PP
Definition at line \fB44\fP of file \fBKeymapTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
