.TH "Luthetus.TextEditor.Tests.Basis.Commands.Models.Vims.TextEditorCommandVimFactsVerbsTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.Commands.Models.Vims.TextEditorCommandVimFactsVerbsTests \- TextEditorCommandVimFacts\&.Verbs  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBDeleteLine\fP ()"
.br
.RI "TextEditorCommandVimFacts\&.Verbs\&.DeleteLine "
.ti -1c
.RI "void \fBChangeLine\fP ()"
.br
.RI "TextEditorCommandVimFacts\&.Verbs\&.ChangeLineCommand "
.ti -1c
.RI "void \fBGetDeleteMotion\fP ()"
.br
.RI "TextEditorCommandVimFacts\&.Verbs\&.DeleteMotionCommandConstructor(TextEditorCommand) "
.ti -1c
.RI "void \fBGetChangeMotion\fP ()"
.br
.RI "TextEditorCommandVimFacts\&.Verbs\&.ChangeMotionCommandConstructor(TextEditorCommand) "
.ti -1c
.RI "void \fBChangeSelection\fP ()"
.br
.RI "TextEditorCommandVimFacts\&.Verbs\&.ChangeSelectionCommand "
.ti -1c
.RI "void \fBYank\fP ()"
.br
.RI "TextEditorCommandVimFacts\&.Verbs\&.YankCommand "
.ti -1c
.RI "void \fBNewLineBelow\fP ()"
.br
.RI "TextEditorCommandVimFacts\&.Verbs\&.NewLineBelowCommand "
.ti -1c
.RI "void \fBNewLineAbove\fP ()"
.br
.RI "TextEditorCommandVimFacts\&.Verbs\&.NewLineAboveCommand "
.in -1c
.SH "Detailed Description"
.PP 
TextEditorCommandVimFacts\&.Verbs 
.PP
Definition at line \fB9\fP of file \fBTextEditorCommandVimFactsVerbsTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Vims\&.TextEditorCommandVimFactsVerbsTests\&.ChangeLine ()"

.PP
TextEditorCommandVimFacts\&.Verbs\&.ChangeLineCommand 
.PP
Definition at line \fB25\fP of file \fBTextEditorCommandVimFactsVerbsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Vims\&.TextEditorCommandVimFactsVerbsTests\&.ChangeSelection ()"

.PP
TextEditorCommandVimFacts\&.Verbs\&.ChangeSelectionCommand 
.PP
Definition at line \fB52\fP of file \fBTextEditorCommandVimFactsVerbsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Vims\&.TextEditorCommandVimFactsVerbsTests\&.DeleteLine ()"

.PP
TextEditorCommandVimFacts\&.Verbs\&.DeleteLine 
.PP
Definition at line \fB16\fP of file \fBTextEditorCommandVimFactsVerbsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Vims\&.TextEditorCommandVimFactsVerbsTests\&.GetChangeMotion ()"

.PP
TextEditorCommandVimFacts\&.Verbs\&.ChangeMotionCommandConstructor(TextEditorCommand) 
.PP
Definition at line \fB43\fP of file \fBTextEditorCommandVimFactsVerbsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Vims\&.TextEditorCommandVimFactsVerbsTests\&.GetDeleteMotion ()"

.PP
TextEditorCommandVimFacts\&.Verbs\&.DeleteMotionCommandConstructor(TextEditorCommand) 
.PP
Definition at line \fB34\fP of file \fBTextEditorCommandVimFactsVerbsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Vims\&.TextEditorCommandVimFactsVerbsTests\&.NewLineAbove ()"

.PP
TextEditorCommandVimFacts\&.Verbs\&.NewLineAboveCommand 
.PP
Definition at line \fB79\fP of file \fBTextEditorCommandVimFactsVerbsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Vims\&.TextEditorCommandVimFactsVerbsTests\&.NewLineBelow ()"

.PP
TextEditorCommandVimFacts\&.Verbs\&.NewLineBelowCommand 
.PP
Definition at line \fB70\fP of file \fBTextEditorCommandVimFactsVerbsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Vims\&.TextEditorCommandVimFactsVerbsTests\&.Yank ()"

.PP
TextEditorCommandVimFacts\&.Verbs\&.YankCommand 
.PP
Definition at line \fB61\fP of file \fBTextEditorCommandVimFactsVerbsTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
