.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.TextEditorCompilerServicesTestsHelper" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.TextEditorCompilerServicesTestsHelper
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBInitializeTextEditorCompilerServicesTestsHelper\fP (out \fBITextEditorService\fP \fBtextEditorService\fP, out \fBTextEditorModel\fP model, out \fBTextEditorViewModel\fP viewModel, out IServiceProvider serviceProvider)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB19\fP of file \fBTextEditorServicesTestsHelper\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.TextEditorCompilerServicesTestsHelper\&.InitializeTextEditorCompilerServicesTestsHelper (out \fBITextEditorService\fP textEditorService, out \fBTextEditorModel\fP model, out \fBTextEditorViewModel\fP viewModel, out IServiceProvider serviceProvider)\fR [static]\fP"

.PP
Definition at line \fB21\fP of file \fBTextEditorServicesTestsHelper\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
