.TH "Luthetus.CompilerServices.DotNetSolution.Models.Associated" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.DotNetSolution.Models.Associated
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAssociatedEntryGroupBuilder\fP"
.br
.ti -1c
.RI "interface \fBIAssociatedEntry\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBAssociatedEntryKind\fP { \fBGroup\fP, \fBPair\fP }"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "record \fBAssociatedEntryGroup\fP"
.br
.ti -1c
.RI "record ImmutableArray< \fBIAssociatedEntry\fP > \fBassociatedEntryList\fP"
.br
.ti -1c
.RI "record \fBAssociatedEntryPair\fP"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBAssociatedEntryKind\fP \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Associated\&.AssociatedEntryKind\fP\fR [get]\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIGroup \fP
.TP
\f(BIPair \fP
.PP
Definition at line \fB3\fP of file \fBAssociatedEntryKind\&.cs\fP\&.
.SH "Variable Documentation"
.PP 
.SS "record Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Associated\&.AssociatedEntryGroup"

.PP
Definition at line \fB6\fP of file \fBAssociatedEntryGroup\&.cs\fP\&.
.SS "record ImmutableArray<\fBIAssociatedEntry\fP> Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Associated\&.associatedEntryList"

.PP
Definition at line \fB10\fP of file \fBAssociatedEntryGroup\&.cs\fP\&.
.SS "record Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Associated\&.AssociatedEntryPair"

.PP
Definition at line \fB5\fP of file \fBAssociatedEntryPair\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
