.TH "Luthetus.Extensions.Git.Displays.GitChangesTreeViewDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.Git.Displays.GitChangesTreeViewDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInitialized\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "GitState \fBGitState\fP = null!\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBGitChangesTreeViewDisplay\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Luthetus\&.Extensions\&.Git\&.Displays\&.GitChangesTreeViewDisplay\&.OnInitialized ()\fR [protected]\fP"

.PP
Definition at line \fB41\fP of file \fBGitChangesTreeViewDisplay\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "GitState Luthetus\&.Extensions\&.Git\&.Displays\&.GitChangesTreeViewDisplay\&.GitState = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB33\fP of file \fBGitChangesTreeViewDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
