.TH "Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests \- TextEditorModelExtensionMethods  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditorTestBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBGetLengthOfLine\fP ()"
.br
.RI "TextEditorModelExtensionMethods\&.GetLineLength(ITextEditorModel, int, bool) "
.ti -1c
.RI "void \fBGetLineRichCharacterRange\fP ()"
.br
.RI "TextEditorModelExtensionMethods\&.GetLineRichCharacterRange(ITextEditorModel, int, int) "
.ti -1c
.RI "void \fBGetAllText_Equals_GetLines_MadeIntoA_String\fP ()"
.br
.RI "TextEditorModelExtensionMethods\&.GetAllText(ITextEditorModel) equals String(char*) constructor used on TextEditorModelExtensionMethods\&.GetLineRichCharacterRange(ITextEditorModel, int, int) after using \&.SelectMany() to get the values out, and doing \&.ToArray()\&. "
.ti -1c
.RI "void \fBGetTabCountOnSameLineBeforeCursor\fP ()"
.br
.RI "TextEditorModelExtensionMethods\&.GetTabCountOnSameLineBeforeCursor(ITextEditorModel, int, int) "
.ti -1c
.RI "void \fBGetAllText\fP ()"
.br
.RI "TextEditorModelExtensionMethods\&.GetAllText(ITextEditorModel) "
.ti -1c
.RI "void \fBGetPositionIndex_TextEditorCursor\fP ()"
.br
.RI "TextEditorModelExtensionMethods\&.GetPositionIndex(ITextEditorModel, TextEditorCursor) "
.ti -1c
.RI "void \fBGetPositionIndex_TextEditorCursorModifier\fP ()"
.br
.RI "TextEditorModelExtensionMethods\&.GetPositionIndex(ITextEditorModel, TextEditorCursorModifier) "
.ti -1c
.RI "void \fBGetPositionIndex_LineIndex_ColumnIndex\fP ()"
.br
.RI "TextEditorModelExtensionMethods\&.GetPositionIndex(ITextEditorModel, int, int) "
.ti -1c
.RI "void \fBGetLineAndColumnIndicesFromPositionIndex\fP ()"
.br
.RI "TextEditorModelExtensionMethods\&.GetLineAndColumnIndicesFromPositionIndex(ITextEditorModel, int) "
.ti -1c
.RI "void \fBGetCharacter\fP ()"
.br
.RI "TextEditorModelExtensionMethods\&.GetCharacter(ITextEditorModel, int) "
.ti -1c
.RI "void \fBGetString\fP ()"
.br
.RI "TextEditorModelExtensionMethods\&.GetString(ITextEditorModel, int, int) "
.ti -1c
.RI "void \fBGetLineTextRange\fP ()"
.br
.RI "TextEditorModelExtensionMethods\&.GetLineTextRange(ITextEditorModel, int, int) "
.ti -1c
.RI "void \fBGetWordTextSpan\fP ()"
.br
.RI "TextEditorModelExtensionMethods\&.GetWordTextSpan(ITextEditorModel, int) "
.ti -1c
.RI "void \fBFindMatches\fP ()"
.br
.RI "TextEditorModelExtensionMethods\&.FindMatches(ITextEditorModel, string) "
.ti -1c
.RI "void \fBGetLineInformation\fP ()"
.br
.RI "TextEditorModelExtensionMethods\&.GetLineInformation(ITextEditorModel, int) "
.ti -1c
.RI "void \fBGetLineInformationFromPositionIndex\fP ()"
.br
.RI "TextEditorModelExtensionMethods\&.GetLineInformationFromPositionIndex(ITextEditorModel, int) "
.ti -1c
.RI "void \fBGetColumnIndexOfCharacterWithDifferingKind\fP ()"
.br
.RI "TextEditorModelExtensionMethods\&.GetColumnIndexOfCharacterWithDifferingKind(ITextEditorModel, int, int, bool) "
.ti -1c
.RI "void \fBCanUndoEdit\fP ()"
.br
.RI "TextEditorModelExtensionMethods\&.CanUndoEdit(ITextEditorModel) "
.ti -1c
.RI "void \fBCanRedoEdit\fP ()"
.br
.RI "TextEditorModelExtensionMethods\&.CanRedoEdit(ITextEditorModel) "
.ti -1c
.RI "void \fBGetCharacterKind\fP ()"
.br
.RI "TextEditorModelExtensionMethods\&.GetCharacterKind(ITextEditorModel, int) "
.ti -1c
.RI "void \fBReadPreviousWordOrDefault\fP ()"
.br
.RI "TextEditorModelExtensionMethods\&.ReadPreviousWordOrDefault(ITextEditorModel, int, int, bool) "
.ti -1c
.RI "void \fBReadNextWordOrDefault\fP ()"
.br
.RI "TextEditorModelExtensionMethods\&.ReadNextWordOrDefault(ITextEditorModel, int, int) "
.ti -1c
.RI "void \fBGetTextOffsettingCursor\fP ()"
.br
.RI "TextEditorModelExtensionMethods\&.GetTextOffsettingCursor(ITextEditorModel, TextEditorCursor) "
.ti -1c
.RI "void \fBGetLineText\fP ()"
.br
.RI "TextEditorModelExtensionMethods\&.GetLineText(ITextEditorModel, int) "
.in -1c
.SS "Additional Inherited Members"


Protected Member Functions inherited from \fBLuthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditorTestBase\fP
.in +1c
.ti -1c
.RI "\fBBackgroundTaskService\fP \fBContinuousBackgroundTaskWorker\fP IDispatcher \fBITextEditorService\fP \fBtextEditorService\fP \fBInitializeBackgroundTasks\fP ()"
.br
.ti -1c
.RI "\fBTextEditorModel\fP \fBTextEditorModelModifier\fP modelModifier \fBEmptyEditor_TestData_And_PerformPreAssertions\fP (\fBResourceUri\fP \fBresourceUri\fP, DateTime resourceLastWriteTime, string fileExtension, string content, \fBIDecorationMapper\fP? decorationMapper, \fBICompilerService\fP? compilerService, int partitionSize)"
.br
.ti -1c
.RI "\fBTextEditorModel\fP \fBTextEditorModelModifier\fP modelModifier \fBNotEmptyEditor_TestData_And_PerformPreAssertions\fP (\fBResourceUri\fP \fBresourceUri\fP, DateTime resourceLastWriteTime, string fileExtension, string content, \fBIDecorationMapper\fP? decorationMapper, \fBICompilerService\fP? compilerService, int partitionSize)"
.br
.in -1c

Protected Attributes inherited from \fBLuthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditorTestBase\fP
.in +1c
.ti -1c
.RI "\fBBackgroundTaskService\fP \fBbackgroundTaskService\fP"
.br
.ti -1c
.RI "\fBBackgroundTaskService\fP \fBContinuousBackgroundTaskWorker\fP \fBbackgroundTaskWorker\fP"
.br
.ti -1c
.RI "\fBBackgroundTaskService\fP \fBContinuousBackgroundTaskWorker\fP IDispatcher \fBdispatcher\fP"
.br
.ti -1c
.RI "\fBTextEditorModel\fP \fBinModel\fP"
.br
.RI "Text Editor UI result (with show-newlines and show-whitespace; arrow is tab, and dot is space)
.br
 ===================== 
.br
 1 
.br
 
.br
 2 b9\\r 
.br
 3 9B\\r
.br
 
.br
 4 --->$;∙EOF 
.br
\&. "
.in -1c
.SH "Detailed Description"
.PP 
TextEditorModelExtensionMethods 
.PP
Definition at line \fB14\fP of file \fBTextEditorModelExtensionMethodsTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelExtensionMethodsTests\&.CanRedoEdit ()"

.PP
TextEditorModelExtensionMethods\&.CanRedoEdit(ITextEditorModel) 
.PP
Definition at line \fB946\fP of file \fBTextEditorModelExtensionMethodsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelExtensionMethodsTests\&.CanUndoEdit ()"

.PP
TextEditorModelExtensionMethods\&.CanUndoEdit(ITextEditorModel) 
.PP
Definition at line \fB907\fP of file \fBTextEditorModelExtensionMethodsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelExtensionMethodsTests\&.FindMatches ()"

.PP
TextEditorModelExtensionMethods\&.FindMatches(ITextEditorModel, string) 
.PP
Definition at line \fB678\fP of file \fBTextEditorModelExtensionMethodsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelExtensionMethodsTests\&.GetAllText ()"

.PP
TextEditorModelExtensionMethods\&.GetAllText(ITextEditorModel) 
.PP
Definition at line \fB174\fP of file \fBTextEditorModelExtensionMethodsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelExtensionMethodsTests\&.GetAllText_Equals_GetLines_MadeIntoA_String ()"

.PP
TextEditorModelExtensionMethods\&.GetAllText(ITextEditorModel) equals String(char*) constructor used on TextEditorModelExtensionMethods\&.GetLineRichCharacterRange(ITextEditorModel, int, int) after using \&.SelectMany() to get the values out, and doing \&.ToArray()\&. 
.PP
Definition at line \fB82\fP of file \fBTextEditorModelExtensionMethodsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelExtensionMethodsTests\&.GetCharacter ()"

.PP
TextEditorModelExtensionMethods\&.GetCharacter(ITextEditorModel, int) 
.PP
Definition at line \fB468\fP of file \fBTextEditorModelExtensionMethodsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelExtensionMethodsTests\&.GetCharacterKind ()"

.PP
TextEditorModelExtensionMethods\&.GetCharacterKind(ITextEditorModel, int) 
.PP
Definition at line \fB992\fP of file \fBTextEditorModelExtensionMethodsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelExtensionMethodsTests\&.GetColumnIndexOfCharacterWithDifferingKind ()"

.PP
TextEditorModelExtensionMethods\&.GetColumnIndexOfCharacterWithDifferingKind(ITextEditorModel, int, int, bool) 
.PP
Definition at line \fB868\fP of file \fBTextEditorModelExtensionMethodsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelExtensionMethodsTests\&.GetLengthOfLine ()"

.PP
TextEditorModelExtensionMethods\&.GetLineLength(ITextEditorModel, int, bool) 
.PP
Definition at line \fB20\fP of file \fBTextEditorModelExtensionMethodsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelExtensionMethodsTests\&.GetLineAndColumnIndicesFromPositionIndex ()"

.PP
TextEditorModelExtensionMethods\&.GetLineAndColumnIndicesFromPositionIndex(ITextEditorModel, int) 
.PP
Definition at line \fB413\fP of file \fBTextEditorModelExtensionMethodsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelExtensionMethodsTests\&.GetLineInformation ()"

.PP
TextEditorModelExtensionMethods\&.GetLineInformation(ITextEditorModel, int) 
.PP
Definition at line \fB737\fP of file \fBTextEditorModelExtensionMethodsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelExtensionMethodsTests\&.GetLineInformationFromPositionIndex ()"

.PP
TextEditorModelExtensionMethods\&.GetLineInformationFromPositionIndex(ITextEditorModel, int) 
.PP
Definition at line \fB800\fP of file \fBTextEditorModelExtensionMethodsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelExtensionMethodsTests\&.GetLineRichCharacterRange ()"

.PP
TextEditorModelExtensionMethods\&.GetLineRichCharacterRange(ITextEditorModel, int, int) 
.PP
Definition at line \fB52\fP of file \fBTextEditorModelExtensionMethodsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelExtensionMethodsTests\&.GetLineText ()"

.PP
TextEditorModelExtensionMethods\&.GetLineText(ITextEditorModel, int) 
.PP
Definition at line \fB1306\fP of file \fBTextEditorModelExtensionMethodsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelExtensionMethodsTests\&.GetLineTextRange ()"

.PP
TextEditorModelExtensionMethods\&.GetLineTextRange(ITextEditorModel, int, int) 
.PP
Definition at line \fB577\fP of file \fBTextEditorModelExtensionMethodsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelExtensionMethodsTests\&.GetPositionIndex_LineIndex_ColumnIndex ()"

.PP
TextEditorModelExtensionMethods\&.GetPositionIndex(ITextEditorModel, int, int) 
.PP
Definition at line \fB340\fP of file \fBTextEditorModelExtensionMethodsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelExtensionMethodsTests\&.GetPositionIndex_TextEditorCursor ()"

.PP
TextEditorModelExtensionMethods\&.GetPositionIndex(ITextEditorModel, TextEditorCursor) 
.PP
Definition at line \fB194\fP of file \fBTextEditorModelExtensionMethodsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelExtensionMethodsTests\&.GetPositionIndex_TextEditorCursorModifier ()"

.PP
TextEditorModelExtensionMethods\&.GetPositionIndex(ITextEditorModel, TextEditorCursorModifier) 
.PP
Definition at line \fB267\fP of file \fBTextEditorModelExtensionMethodsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelExtensionMethodsTests\&.GetString ()"

.PP
TextEditorModelExtensionMethods\&.GetString(ITextEditorModel, int, int) 
.PP
Definition at line \fB523\fP of file \fBTextEditorModelExtensionMethodsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelExtensionMethodsTests\&.GetTabCountOnSameLineBeforeCursor ()"

.PP
TextEditorModelExtensionMethods\&.GetTabCountOnSameLineBeforeCursor(ITextEditorModel, int, int) 
.PP
Definition at line \fB108\fP of file \fBTextEditorModelExtensionMethodsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelExtensionMethodsTests\&.GetTextOffsettingCursor ()"

.PP
TextEditorModelExtensionMethods\&.GetTextOffsettingCursor(ITextEditorModel, TextEditorCursor) 
.PP
Definition at line \fB1217\fP of file \fBTextEditorModelExtensionMethodsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelExtensionMethodsTests\&.GetWordTextSpan ()"

.PP
TextEditorModelExtensionMethods\&.GetWordTextSpan(ITextEditorModel, int) 
.PP
Definition at line \fB622\fP of file \fBTextEditorModelExtensionMethodsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelExtensionMethodsTests\&.ReadNextWordOrDefault ()"

.PP
TextEditorModelExtensionMethods\&.ReadNextWordOrDefault(ITextEditorModel, int, int) 
.PP
Definition at line \fB1141\fP of file \fBTextEditorModelExtensionMethodsTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelExtensionMethodsTests\&.ReadPreviousWordOrDefault ()"

.PP
TextEditorModelExtensionMethods\&.ReadPreviousWordOrDefault(ITextEditorModel, int, int, bool) 
.PP
Definition at line \fB1065\fP of file \fBTextEditorModelExtensionMethodsTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
