.TH "Luthetus.TextEditor.RazorLib.ComponentRenderers.Models.ITextEditorDiagnosticRenderer" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.ComponentRenderers.Models.ITextEditorDiagnosticRenderer
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.DiagnosticDisplay\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBTextEditorDiagnostic\fP \fBDiagnostic\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBITextEditorDiagnosticRenderer\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBTextEditorDiagnostic\fP Luthetus\&.TextEditor\&.RazorLib\&.ComponentRenderers\&.Models\&.ITextEditorDiagnosticRenderer\&.Diagnostic\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.DiagnosticDisplay\fP\&.
.PP
Definition at line \fB7\fP of file \fBITextEditorDiagnosticRenderer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
