.TH "Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Symbols.SymbolReference" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Symbols.SymbolReference
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSymbolReference\fP (\fBISymbol\fP symbol, int scopeIndexKey)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBISymbol\fP \fBSymbol\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBScopeIndexKey\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBSymbolReference\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Symbols\&.SymbolReference\&.SymbolReference (\fBISymbol\fP symbol, int scopeIndexKey)"

.PP
Definition at line \fB8\fP of file \fBSymbolReference\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Symbols\&.SymbolReference\&.ScopeIndexKey\fR [get]\fP"

.PP
Definition at line \fB15\fP of file \fBSymbolReference\&.cs\fP\&.
.SS "\fBISymbol\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Symbols\&.SymbolReference\&.Symbol\fR [get]\fP"

.PP
Definition at line \fB14\fP of file \fBSymbolReference\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
