.TH "Luthetus.Ide.Tests.Basis.Commands.CommandFactoryTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.Tests.Basis.Commands.CommandFactoryTests \- \fBCommandFactory\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "CommandFactory(ITextEditorService, ITreeViewService, IEnvironmentProvider, IState<PanelState>, IDispatcher, IJSRuntime) 
.br
----
.br
 \fBCommandFactory\&.CodeSearchDialog\fP "
.ti -1c
.RI "void \fBInitialize\fP ()"
.br
.RI "\fBCommandFactory\&.Initialize()\fP "
.ti -1c
.RI "void \fBConstructFocusContextElementCommand\fP ()"
.br
.RI "CommandFactory\&.ConstructFocusContextElementCommand(ContextRecord, string, string) "
.in -1c
.SH "Detailed Description"
.PP 
\fBCommandFactory\fP 
.PP
Definition at line \fB14\fP of file \fBCommandFactoryTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.Commands\&.CommandFactoryTests\&.ConstructFocusContextElementCommand ()"

.PP
CommandFactory\&.ConstructFocusContextElementCommand(ContextRecord, string, string) 
.PP
Definition at line \fB40\fP of file \fBCommandFactoryTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.Commands\&.CommandFactoryTests\&.Constructor ()"

.PP
CommandFactory(ITextEditorService, ITreeViewService, IEnvironmentProvider, IState<PanelState>, IDispatcher, IJSRuntime) 
.br
----
.br
 \fBCommandFactory\&.CodeSearchDialog\fP 
.PP
Definition at line \fB22\fP of file \fBCommandFactoryTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.Commands\&.CommandFactoryTests\&.Initialize ()"

.PP
\fBCommandFactory\&.Initialize()\fP 
.PP
Definition at line \fB31\fP of file \fBCommandFactoryTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
