.TH "Luthetus.Common.Tests.Basis.Dimensions.Models.DimensionUnitKindExtensionsTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Dimensions.Models.DimensionUnitKindExtensionsTests \- DimensionUnitKindExtensions  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBGetStyleString\fP ()"
.br
.RI "DimensionUnitKindExtensions\&.GetStyleString(DimensionUnitKind) "
.in -1c
.SH "Detailed Description"
.PP 
DimensionUnitKindExtensions 
.PP
Definition at line \fB8\fP of file \fBDimensionUnitKindExtensionsTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Dimensions\&.Models\&.DimensionUnitKindExtensionsTests\&.GetStyleString ()"

.PP
DimensionUnitKindExtensions\&.GetStyleString(DimensionUnitKind) 
.PP
Definition at line \fB14\fP of file \fBDimensionUnitKindExtensionsTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
