.TH "Luthetus.Extensions.DotNet.Tests.Basis.TreeViewImplementations.Models.TreeViewCompilerServiceTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.Tests.Basis.TreeViewImplementations.Models.TreeViewCompilerServiceTests \- \fBTreeViewCompilerService\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.ExtensionsDotNetTestBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "TreeViewCompilerService(ILuthCompilerService, ILuthetusIdeComponentRenderers, ILuthetusCommonComponentRenderers, bool, bool) 
.br
----
.br
 \fBTreeViewCompilerService\&.IdeComponentRenderers\fP \fBTreeViewCompilerService\&.CommonComponentRenderers\fP "
.ti -1c
.RI "void \fBEquals_Test\fP ()"
.br
.RI "\fBTreeViewCompilerService\&.Equals(object?)\fP "
.ti -1c
.RI "void \fBGetHashCode_Test\fP ()"
.br
.RI "\fBTreeViewCompilerService\&.GetHashCode()\fP "
.ti -1c
.RI "void \fBGetTreeViewRenderer\fP ()"
.br
.RI "\fBTreeViewCompilerService\&.GetTreeViewRenderer()\fP "
.ti -1c
.RI "void \fBLoadChildListAsync\fP ()"
.br
.RI "\fBTreeViewCompilerService\&.LoadChildListAsync()\fP "
.in -1c
.SS "Additional Inherited Members"


Static Protected Member Functions inherited from \fBLuthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.ExtensionsDotNetTestBase\fP
.in +1c
.ti -1c
.RI "static void \fBTest_RegisterServices\fP (out ServiceProvider serviceProvider)"
.br
.ti -1c
.RI "static void \fBTest_CreateFileSystem\fP (IServiceProvider serviceProvider)"
.br
.RI "The files shown in the 'tree' below will be written to the in-memory filesystem\&. ---------------------------------------------
.br
 Root
.br
 ∙└───Homework
.br
 ∙∙∙∙∙∙├───Math
.br
 ∙∙∙∙∙∙│∙∙∙∙├───addition\&.txt
.br
 ∙∙∙∙∙∙│∙∙∙∙└───subtraction\&.txt
.br
 ∙∙∙∙∙∙│
.br
 ∙∙∙∙∙∙└───Biology
.br
 ∙∙∙∙∙∙∙∙∙∙∙├───nervousSystem\&.txt
.br
 ∙∙∙∙∙∙∙∙∙∙∙└───skeletalSystem\&.txt
.br
\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBTreeViewCompilerService\fP 
.PP
Definition at line \fB15\fP of file \fBTreeViewCompilerServiceTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.TreeViewImplementations\&.Models\&.TreeViewCompilerServiceTests\&.Constructor ()"

.PP
TreeViewCompilerService(ILuthCompilerService, ILuthetusIdeComponentRenderers, ILuthetusCommonComponentRenderers, bool, bool) 
.br
----
.br
 \fBTreeViewCompilerService\&.IdeComponentRenderers\fP \fBTreeViewCompilerService\&.CommonComponentRenderers\fP 
.PP
Definition at line \fB24\fP of file \fBTreeViewCompilerServiceTests\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.TreeViewImplementations\&.Models\&.TreeViewCompilerServiceTests\&.Equals_Test ()"

.PP
\fBTreeViewCompilerService\&.Equals(object?)\fP 
.PP
Definition at line \fB61\fP of file \fBTreeViewCompilerServiceTests\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.TreeViewImplementations\&.Models\&.TreeViewCompilerServiceTests\&.GetHashCode_Test ()"

.PP
\fBTreeViewCompilerService\&.GetHashCode()\fP 
.PP
Definition at line \fB70\fP of file \fBTreeViewCompilerServiceTests\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.TreeViewImplementations\&.Models\&.TreeViewCompilerServiceTests\&.GetTreeViewRenderer ()"

.PP
\fBTreeViewCompilerService\&.GetTreeViewRenderer()\fP 
.PP
Definition at line \fB79\fP of file \fBTreeViewCompilerServiceTests\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.TreeViewImplementations\&.Models\&.TreeViewCompilerServiceTests\&.LoadChildListAsync ()"

.PP
\fBTreeViewCompilerService\&.LoadChildListAsync()\fP 
.PP
Definition at line \fB88\fP of file \fBTreeViewCompilerServiceTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
