.TH "Luthetus.CompilerServices.DotNetSolution.Models.IDotNetSolution" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.DotNetSolution.Models.IDotNetSolution
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "Key< \fBDotNetSolutionModel\fP > \fBKey\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBIAbsolutePath\fP \fBAbsolutePath\fP\fR [get]\fP"
.br
.ti -1c
.RI "DotNetSolutionHeader \fBDotNetSolutionHeader\fP\fR [get]\fP"
.br
.ti -1c
.RI "ImmutableArray< \fBIDotNetProject\fP > \fBDotNetProjectList\fP\fR [get]\fP"
.br
.ti -1c
.RI "ImmutableArray< \fBSolutionFolder\fP > \fBSolutionFolderList\fP\fR [get]\fP"
.br
.ti -1c
.RI "ImmutableArray< \fBNestedProjectEntry\fP > \fBNestedProjectEntryList\fP\fR [get]\fP"
.br
.ti -1c
.RI "DotNetSolutionGlobal \fBDotNetSolutionGlobal\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBSolutionFileContents\fP\fR [get]\fP"
.br
.ti -1c
.RI "NamespacePath \fBNamespacePath\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBIDotNetSolution\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBIAbsolutePath\fP Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.IDotNetSolution\&.AbsolutePath\fR [get]\fP"

.PP
Definition at line \fB12\fP of file \fBIDotNetSolution\&.cs\fP\&.
.SS "ImmutableArray<\fBIDotNetProject\fP> Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.IDotNetSolution\&.DotNetProjectList\fR [get]\fP"

.PP
Definition at line \fB14\fP of file \fBIDotNetSolution\&.cs\fP\&.
.SS "DotNetSolutionGlobal Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.IDotNetSolution\&.DotNetSolutionGlobal\fR [get]\fP"

.PP
Definition at line \fB17\fP of file \fBIDotNetSolution\&.cs\fP\&.
.SS "DotNetSolutionHeader Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.IDotNetSolution\&.DotNetSolutionHeader\fR [get]\fP"

.PP
Definition at line \fB13\fP of file \fBIDotNetSolution\&.cs\fP\&.
.SS "Key<\fBDotNetSolutionModel\fP> Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.IDotNetSolution\&.Key\fR [get]\fP"

.PP
Definition at line \fB11\fP of file \fBIDotNetSolution\&.cs\fP\&.
.SS "NamespacePath Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.IDotNetSolution\&.NamespacePath\fR [get]\fP"

.PP
Definition at line \fB20\fP of file \fBIDotNetSolution\&.cs\fP\&.
.SS "ImmutableArray<\fBNestedProjectEntry\fP> Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.IDotNetSolution\&.NestedProjectEntryList\fR [get]\fP"

.PP
Definition at line \fB16\fP of file \fBIDotNetSolution\&.cs\fP\&.
.SS "string Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.IDotNetSolution\&.SolutionFileContents\fR [get]\fP"

.PP
Definition at line \fB18\fP of file \fBIDotNetSolution\&.cs\fP\&.
.SS "ImmutableArray<\fBSolutionFolder\fP> Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.IDotNetSolution\&.SolutionFolderList\fR [get]\fP"

.PP
Definition at line \fB15\fP of file \fBIDotNetSolution\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
