.TH "Luthetus.CompilerServices.C.CLexer" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.C.CLexer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.Lexer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCLexer\fP (\fBResourceUri\fP resourceUri, string sourceText)"
.br
.ti -1c
.RI "override void \fBLex\fP ()"
.br
.in -1c

Public Member Functions inherited from \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.Lexer\fP
.in +1c
.ti -1c
.RI "\fBLexer\fP (\fBResourceUri\fP resourceUri, string sourceText, \fBLexerKeywords\fP lexerKeywords)"
.br
.in -1c
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly \fBGenericPreprocessorDefinition\fP \fBCPreprocessorDefinition\fP"
.br
.ti -1c
.RI "static readonly \fBGenericLanguageDefinition\fP \fBCLanguageDefinition\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Key< \fBRenderState\fP > \fBModelRenderStateKey\fP = Key<\fBRenderState\fP>\&.Empty\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.Lexer\fP
.in +1c
.ti -1c
.RI "ResourceUri \fBResourceUri\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBSourceText\fP\fR [get]\fP"
.br
.ti -1c
.RI "LexerKeywords \fBLexerKeywords\fP\fR [get]\fP"
.br
.ti -1c
.RI "ImmutableArray< \fBISyntaxToken\fP > \fBSyntaxTokenList\fP\fR [get]\fP"
.br
.ti -1c
.RI "ImmutableArray< \fBTextEditorDiagnostic\fP > \fBDiagnosticList\fP\fR [get]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.Lexer\fP
.in +1c
.ti -1c
.RI "readonly \fBStringWalker\fP \fB_stringWalker\fP"
.br
.ti -1c
.RI "readonly List< \fBISyntaxToken\fP > \fB_syntaxTokenList\fP = new()"
.br
.ti -1c
.RI "readonly \fBDiagnosticBag\fP \fB_diagnosticBag\fP = new()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB16\fP of file \fBCLexer\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.CompilerServices\&.C\&.CLexer\&.CLexer (\fBResourceUri\fP resourceUri, string sourceText)"

.PP
Definition at line \fB18\fP of file \fBCLexer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Luthetus\&.CompilerServices\&.C\&.CLexer\&.Lex ()\fR [virtual]\fP"

.PP
Reimplemented from \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.Lexer\fP\&.
.PP
Definition at line \fB52\fP of file \fBCLexer\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBGenericLanguageDefinition\fP Luthetus\&.CompilerServices\&.C\&.CLexer\&.CLanguageDefinition\fR [static]\fP"
\fBInitial value:\fP
.nf
= new GenericLanguageDefinition(
        "\\"",
        "\\"",
        "(",
        ")",
        "\&.",
        "//",
        new[]
        {
            WhitespaceFacts\&.CARRIAGE_RETURN\&.ToString(),
            WhitespaceFacts\&.LINE_FEED\&.ToString()
        }\&.ToImmutableArray(),
        "/*",
        "*/",
        CLanguageFacts\&.Keywords\&.ALL_LIST,
        CPreprocessorDefinition)
.PP
.fi

.PP
Definition at line \fB31\fP of file \fBCLexer\&.cs\fP\&.
.SS "readonly \fBGenericPreprocessorDefinition\fP Luthetus\&.CompilerServices\&.C\&.CLexer\&.CPreprocessorDefinition\fR [static]\fP"
\fBInitial value:\fP
.nf
= new(
        "#",
        ImmutableArray<DeliminationExtendedSyntaxDefinition>\&.Empty)
.PP
.fi

.PP
Definition at line \fB27\fP of file \fBCLexer\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Key<\fBRenderState\fP> Luthetus\&.CompilerServices\&.C\&.CLexer\&.ModelRenderStateKey = Key<\fBRenderState\fP>\&.Empty\fR [get]\fP"

.PP
Definition at line \fB50\fP of file \fBCLexer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
