.TH "Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAutocompleteMenu\fP"
.br
.ti -1c
.RI "class \fBBodyDriver\fP"
.br
.ti -1c
.RI "class \fBCommandBarDisplay\fP"
.br
.ti -1c
.RI "class \fBContextMenu\fP"
.br
.ti -1c
.RI "class \fBCursorDriver\fP"
.br
.ti -1c
.RI "class \fBDiagnosticDisplay\fP"
.br
.ti -1c
.RI "class \fBFindOverlayDisplay\fP"
.br
.ti -1c
.RI "class \fBFooterDriver\fP"
.br
.RI "TODO: Move this back into TextEditorDefaultFooter\&. This was made into the Driver idea, then made back into a component\&. "
.ti -1c
.RI "class \fBGutterDriver\fP"
.br
.ti -1c
.RI "class \fBHeaderDriver\fP"
.br
.RI "The header has @onclick events in the UI and as such could not be made into a RenderFragment\&. Instead, the UI was inlined into the \fBTextEditorViewModelDisplay\fP\&. "
.ti -1c
.RI "class \fBLabelWidgetInlineDisplay\fP"
.br
.ti -1c
.RI "class \fBPresentationAndSelectionDriver\fP"
.br
.ti -1c
.RI "class \fBScrollbarSection\fP"
.br
.ti -1c
.RI "class \fBSymbolDisplay\fP"
.br
.RI "TODO: protect against exceptions that are thrown when rendering the symbol\&. One happened while hovering a lambda expression on (2024-11-09)\&. "
.ti -1c
.RI "class \fBTextEditorDefaultFooterDisplay\fP"
.br
.ti -1c
.RI "class \fBTextEditorDefaultHeaderDisplay\fP"
.br
.ti -1c
.RI "class \fBTextEditorDevToolsAnchorDisplay\fP"
.br
.ti -1c
.RI "class \fBTextEditorDevToolsDisplay\fP"
.br
.RI "TODO: Debounce this instead of throttling\&. "
.ti -1c
.RI "class \fBTooltipDisplay\fP"
.br
.ti -1c
.RI "class \fBVirtualizationDriver\fP"
.br
.ti -1c
.RI "class \fBWidgetLayerDisplay\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
