.TH "Luthetus.Extensions.Git.ComponentRenderers.Models.ITreeViewGitFileRendererType" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.Git.ComponentRenderers.Models.ITreeViewGitFileRendererType
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.Extensions\&.Git\&.Displays\&.TreeViewGitFileDisplay\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "TreeViewGitFile \fBTreeViewGitFile\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBITreeViewGitFileRendererType\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "TreeViewGitFile Luthetus\&.Extensions\&.Git\&.ComponentRenderers\&.Models\&.ITreeViewGitFileRendererType\&.TreeViewGitFile\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.Extensions\&.Git\&.Displays\&.TreeViewGitFileDisplay\fP\&.
.PP
Definition at line \fB7\fP of file \fBITreeViewGitFileRendererType\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
