.TH "Luthetus.Ide.RazorLib.FileSystems.Models.IFileTemplate" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.FileSystems.Models.IFileTemplate
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.FileTemplate\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "Guid \fBId\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBDisplayName\fP\fR [get]\fP"
.br
.RI "Name displayed to a user\&. "
.ti -1c
.RI "string \fBCodeName\fP\fR [get]\fP"
.br
.RI "Internally used name\&. "
.ti -1c
.RI "\fBFileTemplateKind\fP \fBFileTemplateKind\fP\fR [get]\fP"
.br
.ti -1c
.RI "Func< string, bool > \fBIsExactTemplate\fP\fR [get]\fP"
.br
.RI "Func<string filename, bool isApplicable> 
.br

.br
 Take \&.SingleOrDefault() to find the IsExactTemplate\&. "
.ti -1c
.RI "Func< string, ImmutableArray< \fBIFileTemplate\fP > > \fBRelatedFileTemplatesFunc\fP\fR [get]\fP"
.br
.RI "Func<string filename, bool isApplicable> 
.br

.br
 \fBRelatedFileTemplatesFunc\fP refers to the user making a '\&.razor' file and them being then prompted if they want to make a codebehind as well\&. The codebehind is the related file\&. "
.ti -1c
.RI "bool \fBInitialCheckedStateWhenIsRelatedFile\fP\fR [get]\fP"
.br
.RI "When the user types "\&.razor" is the codebehind template input element checked by default? "
.ti -1c
.RI "Func< \fBFileTemplateParameter\fP, \fBFileTemplateResult\fP > \fBConstructFileContents\fP\fR [get]\fP"
.br
.RI "Func<string filename, NamespacePath parentDirectory, Task writeOutFileTask>\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBIFileTemplate\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.IFileTemplate\&.CodeName\fR [get]\fP"

.PP
Internally used name\&. 
.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.FileTemplate\fP\&.
.PP
Definition at line \fB15\fP of file \fBIFileTemplate\&.cs\fP\&.
.SS "Func<\fBFileTemplateParameter\fP, \fBFileTemplateResult\fP> Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.IFileTemplate\&.ConstructFileContents\fR [get]\fP"

.PP
Func<string filename, NamespacePath parentDirectory, Task writeOutFileTask>\&. 
.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.FileTemplate\fP\&.
.PP
Definition at line \fB39\fP of file \fBIFileTemplate\&.cs\fP\&.
.SS "string Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.IFileTemplate\&.DisplayName\fR [get]\fP"

.PP
Name displayed to a user\&. 
.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.FileTemplate\fP\&.
.PP
Definition at line \fB11\fP of file \fBIFileTemplate\&.cs\fP\&.
.SS "\fBFileTemplateKind\fP Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.IFileTemplate\&.FileTemplateKind\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.FileTemplate\fP\&.
.PP
Definition at line \fB16\fP of file \fBIFileTemplate\&.cs\fP\&.
.SS "Guid Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.IFileTemplate\&.Id\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.FileTemplate\fP\&.
.PP
Definition at line \fB7\fP of file \fBIFileTemplate\&.cs\fP\&.
.SS "bool Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.IFileTemplate\&.InitialCheckedStateWhenIsRelatedFile\fR [get]\fP"

.PP
When the user types "\&.razor" is the codebehind template input element checked by default? 
.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.FileTemplate\fP\&.
.PP
Definition at line \fB35\fP of file \fBIFileTemplate\&.cs\fP\&.
.SS "Func<string, bool> Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.IFileTemplate\&.IsExactTemplate\fR [get]\fP"

.PP
Func<string filename, bool isApplicable> 
.br

.br
 Take \&.SingleOrDefault() to find the IsExactTemplate\&. 
.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.FileTemplate\fP\&.
.PP
Definition at line \fB22\fP of file \fBIFileTemplate\&.cs\fP\&.
.SS "Func<string, ImmutableArray<\fBIFileTemplate\fP> > Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.IFileTemplate\&.RelatedFileTemplatesFunc\fR [get]\fP"

.PP
Func<string filename, bool isApplicable> 
.br

.br
 \fBRelatedFileTemplatesFunc\fP refers to the user making a '\&.razor' file and them being then prompted if they want to make a codebehind as well\&. The codebehind is the related file\&. 
.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.FileSystems\&.Models\&.FileTemplate\fP\&.
.PP
Definition at line \fB30\fP of file \fBIFileTemplate\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
