.TH "Luthetus.TextEditor.Tests.Basis.Keymaps.Models.Vims.VimSentenceTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.Keymaps.Models.Vims.VimSentenceTests \- \fBVimSentence\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBPendingSentenceList\fP ()"
.br
.RI "\fBVimSentence\&.PendingSentenceList\fP "
.ti -1c
.RI "void \fBTryLex\fP ()"
.br
.RI "VimSentence\&.TryLex(TextEditorKeymapVim, Common\&.RazorLib\&.Keymaps\&.Models\&.KeymapArgument, bool, out RazorLib\&.Commands\&.Models\&.TextEditorCommand?) "
.ti -1c
.RI "void \fBTryParseNextToken\fP ()"
.br
.RI "VimSentence\&.TryParseNextToken(TextEditorKeymapVim, System\&.Collections\&.Immutable\&.ImmutableArray<VimGrammarToken>, int, Common\&.RazorLib\&.Keymaps\&.Models\&.KeymapArgument, bool, out RazorLib\&.Commands\&.Models\&.TextEditorCommand?) "
.in -1c
.SH "Detailed Description"
.PP 
\fBVimSentence\fP 
.PP
Definition at line \fB8\fP of file \fBVimSentenceTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Keymaps\&.Models\&.Vims\&.VimSentenceTests\&.PendingSentenceList ()"

.PP
\fBVimSentence\&.PendingSentenceList\fP 
.PP
Definition at line \fB14\fP of file \fBVimSentenceTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Keymaps\&.Models\&.Vims\&.VimSentenceTests\&.TryLex ()"

.PP
VimSentence\&.TryLex(TextEditorKeymapVim, Common\&.RazorLib\&.Keymaps\&.Models\&.KeymapArgument, bool, out RazorLib\&.Commands\&.Models\&.TextEditorCommand?) 
.PP
Definition at line \fB23\fP of file \fBVimSentenceTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Keymaps\&.Models\&.Vims\&.VimSentenceTests\&.TryParseNextToken ()"

.PP
VimSentence\&.TryParseNextToken(TextEditorKeymapVim, System\&.Collections\&.Immutable\&.ImmutableArray<VimGrammarToken>, int, Common\&.RazorLib\&.Keymaps\&.Models\&.KeymapArgument, bool, out RazorLib\&.Commands\&.Models\&.TextEditorCommand?) 
.PP
Definition at line \fB32\fP of file \fBVimSentenceTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
