.TH "Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationDimensions" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationDimensions
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBSolutionVisualizationDimensions\fP (Action onStateChangedAction)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBSvgWidth\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBSvgHeight\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBViewBoxMinX\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBViewBoxMinY\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBViewBoxWidth\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBViewBoxHeight\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBHorizontalPadding\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBVerticalPadding\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBMeasuredHtmlElementDimensions\fP \fBDivBoundingClientRect\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBMeasuredHtmlElementDimensions\fP \fBSvgBoundingClientRect\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "double \fBScaleX\fP\fR [get]\fP"
.br
.ti -1c
.RI "double \fBScaleY\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBSolutionVisualizationDimensions\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.SolutionVisualizationDimensions\&.SolutionVisualizationDimensions (Action onStateChangedAction)"

.PP
Definition at line \fB9\fP of file \fBSolutionVisualizationDimensions\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBMeasuredHtmlElementDimensions\fP Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.SolutionVisualizationDimensions\&.DivBoundingClientRect\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB104\fP of file \fBSolutionVisualizationDimensions\&.cs\fP\&.
.SS "int Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.SolutionVisualizationDimensions\&.HorizontalPadding\fR [get]\fP, \fR [set]\fP, \fR [add]\fP"

.PP
Definition at line \fB84\fP of file \fBSolutionVisualizationDimensions\&.cs\fP\&.
.SS "double Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.SolutionVisualizationDimensions\&.ScaleX\fR [get]\fP"

.PP
Definition at line \fB107\fP of file \fBSolutionVisualizationDimensions\&.cs\fP\&.
.SS "double Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.SolutionVisualizationDimensions\&.ScaleY\fR [get]\fP"

.PP
Definition at line \fB108\fP of file \fBSolutionVisualizationDimensions\&.cs\fP\&.
.SS "\fBMeasuredHtmlElementDimensions\fP Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.SolutionVisualizationDimensions\&.SvgBoundingClientRect\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB105\fP of file \fBSolutionVisualizationDimensions\&.cs\fP\&.
.SS "int Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.SolutionVisualizationDimensions\&.SvgHeight\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB34\fP of file \fBSolutionVisualizationDimensions\&.cs\fP\&.
.SS "int Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.SolutionVisualizationDimensions\&.SvgWidth\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB23\fP of file \fBSolutionVisualizationDimensions\&.cs\fP\&.
.SS "int Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.SolutionVisualizationDimensions\&.VerticalPadding\fR [get]\fP, \fR [set]\fP, \fR [add]\fP"

.PP
Definition at line \fB94\fP of file \fBSolutionVisualizationDimensions\&.cs\fP\&.
.SS "int Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.SolutionVisualizationDimensions\&.ViewBoxHeight\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB74\fP of file \fBSolutionVisualizationDimensions\&.cs\fP\&.
.SS "int Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.SolutionVisualizationDimensions\&.ViewBoxMinX\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB44\fP of file \fBSolutionVisualizationDimensions\&.cs\fP\&.
.SS "int Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.SolutionVisualizationDimensions\&.ViewBoxMinY\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB54\fP of file \fBSolutionVisualizationDimensions\&.cs\fP\&.
.SS "int Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.SolutionVisualizationDimensions\&.ViewBoxWidth\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB64\fP of file \fBSolutionVisualizationDimensions\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
