.TH "Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StatementBuilder" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StatementBuilder
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "bool \fBTryPeek\fP (out \fBISyntax\fP syntax)"
.br
.RI "Invokes the other overload with index: ^1\&. "
.ti -1c
.RI "bool \fBTryPeek\fP (Index index, out \fBISyntax\fP syntax)"
.br
.RI "^1 gives the last entry "
.ti -1c
.RI "\fBISyntax\fP \fBPop\fP ()"
.br
.ti -1c
.RI "void \fBFinishStatement\fP (\fBIParserModel\fP model)"
.br
.RI "If 'StatementDelimiterToken', 'OpenBraceToken', or 'CloseBraceToken' are parsed by the main loop,\&. "
.ti -1c
.RI "void \fBWriteToConsole\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "List< \fBISyntax\fP > \fBChildList\fP = new()\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBStatementBuilder\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Utility\&.StatementBuilder\&.FinishStatement (\fBIParserModel\fP model)"

.PP
If 'StatementDelimiterToken', 'OpenBraceToken', or 'CloseBraceToken' are parsed by the main loop,\&. Then check that the last item in the \fBStatementBuilder\&.ChildList\fP has been added to the model\&.CurrentCodeBlockBuilder\&.ChildList\&.

.PP
If it was not yet added, then add it\&.

.PP
Lastly, clear the \fBStatementBuilder\&.ChildList\fP\&. 
.PP
Definition at line \fB48\fP of file \fBStatementBuilder\&.cs\fP\&.
.SS "\fBISyntax\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Utility\&.StatementBuilder\&.Pop ()"

.PP
Definition at line \fB30\fP of file \fBStatementBuilder\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Utility\&.StatementBuilder\&.TryPeek (Index index, out \fBISyntax\fP syntax)"

.PP
^1 gives the last entry 
.PP
Definition at line \fB18\fP of file \fBStatementBuilder\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Utility\&.StatementBuilder\&.TryPeek (out \fBISyntax\fP syntax)"

.PP
Invokes the other overload with index: ^1\&. 
.PP
Definition at line \fB12\fP of file \fBStatementBuilder\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Utility\&.StatementBuilder\&.WriteToConsole ()"

.PP
Definition at line \fB68\fP of file \fBStatementBuilder\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "List<\fBISyntax\fP> Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Utility\&.StatementBuilder\&.ChildList = new()\fR [get]\fP"

.PP
Definition at line \fB9\fP of file \fBStatementBuilder\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
