.TH "Luthetus.Common.RazorLib.TreeViews.Models.ITreeViewService" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.TreeViews.Models.ITreeViewService
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBRegisterTreeViewContainer\fP (\fBTreeViewContainer\fP container)"
.br
.RI "Duplicate keys do NOT throw an exception\&. "
.ti -1c
.RI "void \fBDisposeTreeViewContainer\fP (Key< \fBTreeViewContainer\fP > containerKey)"
.br
.ti -1c
.RI "void \fBSetRoot\fP (Key< \fBTreeViewContainer\fP > containerKey, \fBTreeViewNoType\fP node)"
.br
.ti -1c
.RI "bool \fBTryGetTreeViewContainer\fP (Key< \fBTreeViewContainer\fP > containerKey, out \fBTreeViewContainer\fP? container)"
.br
.ti -1c
.RI "void \fBReRenderNode\fP (Key< \fBTreeViewContainer\fP > containerKey, \fBTreeViewNoType\fP node)"
.br
.ti -1c
.RI "void \fBAddChildNode\fP (Key< \fBTreeViewContainer\fP > containerKey, \fBTreeViewNoType\fP parent, \fBTreeViewNoType\fP child)"
.br
.ti -1c
.RI "void \fBSetActiveNode\fP (Key< \fBTreeViewContainer\fP > containerKey, \fBTreeViewNoType\fP? nextActiveNode, bool addSelectedNodes, bool selectNodesBetweenCurrentAndNextActiveNode)"
.br
.ti -1c
.RI "void \fBMoveLeft\fP (Key< \fBTreeViewContainer\fP > containerKey, bool addSelectedNodes, bool selectNodesBetweenCurrentAndNextActiveNode)"
.br
.ti -1c
.RI "void \fBMoveDown\fP (Key< \fBTreeViewContainer\fP > containerKey, bool addSelectedNodes, bool selectNodesBetweenCurrentAndNextActiveNode)"
.br
.ti -1c
.RI "void \fBMoveUp\fP (Key< \fBTreeViewContainer\fP > containerKey, bool addSelectedNodes, bool selectNodesBetweenCurrentAndNextActiveNode)"
.br
.ti -1c
.RI "void \fBMoveRight\fP (Key< \fBTreeViewContainer\fP > containerKey, bool addSelectedNodes, bool selectNodesBetweenCurrentAndNextActiveNode)"
.br
.ti -1c
.RI "void \fBMoveHome\fP (Key< \fBTreeViewContainer\fP > containerKey, bool addSelectedNodes, bool selectNodesBetweenCurrentAndNextActiveNode)"
.br
.ti -1c
.RI "void \fBMoveEnd\fP (Key< \fBTreeViewContainer\fP > containerKey, bool addSelectedNodes, bool selectNodesBetweenCurrentAndNextActiveNode)"
.br
.ti -1c
.RI "string \fBGetNodeElementId\fP (\fBTreeViewNoType\fP node)"
.br
.ti -1c
.RI "string \fBGetTreeViewContainerElementId\fP (Key< \fBTreeViewContainer\fP > containerKey)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IState< TreeViewState > \fBTreeViewStateWrap\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBITreeViewService\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\&.AddChildNode (Key< \fBTreeViewContainer\fP > containerKey, \fBTreeViewNoType\fP parent, \fBTreeViewNoType\fP child)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\&.DisposeTreeViewContainer (Key< \fBTreeViewContainer\fP > containerKey)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\fP\&.
.SS "string Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\&.GetNodeElementId (\fBTreeViewNoType\fP node)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\fP\&.
.SS "string Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\&.GetTreeViewContainerElementId (Key< \fBTreeViewContainer\fP > containerKey)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\&.MoveDown (Key< \fBTreeViewContainer\fP > containerKey, bool addSelectedNodes, bool selectNodesBetweenCurrentAndNextActiveNode)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\&.MoveEnd (Key< \fBTreeViewContainer\fP > containerKey, bool addSelectedNodes, bool selectNodesBetweenCurrentAndNextActiveNode)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\&.MoveHome (Key< \fBTreeViewContainer\fP > containerKey, bool addSelectedNodes, bool selectNodesBetweenCurrentAndNextActiveNode)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\&.MoveLeft (Key< \fBTreeViewContainer\fP > containerKey, bool addSelectedNodes, bool selectNodesBetweenCurrentAndNextActiveNode)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\&.MoveRight (Key< \fBTreeViewContainer\fP > containerKey, bool addSelectedNodes, bool selectNodesBetweenCurrentAndNextActiveNode)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\&.MoveUp (Key< \fBTreeViewContainer\fP > containerKey, bool addSelectedNodes, bool selectNodesBetweenCurrentAndNextActiveNode)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\&.RegisterTreeViewContainer (\fBTreeViewContainer\fP container)"

.PP
Duplicate keys do NOT throw an exception\&. 
.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\&.ReRenderNode (Key< \fBTreeViewContainer\fP > containerKey, \fBTreeViewNoType\fP node)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\&.SetActiveNode (Key< \fBTreeViewContainer\fP > containerKey, \fBTreeViewNoType\fP? nextActiveNode, bool addSelectedNodes, bool selectNodesBetweenCurrentAndNextActiveNode)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\fP\&.
.SS "void Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\&.SetRoot (Key< \fBTreeViewContainer\fP > containerKey, \fBTreeViewNoType\fP node)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\fP\&.
.SS "bool Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\&.TryGetTreeViewContainer (Key< \fBTreeViewContainer\fP > containerKey, out \fBTreeViewContainer\fP? container)"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\fP\&.
.SH "Property Documentation"
.PP 
.SS "IState<TreeViewState> Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.ITreeViewService\&.TreeViewStateWrap\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewService\fP\&.
.PP
Definition at line \fB9\fP of file \fBITreeViewService\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
