.TH "Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.ILexer" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.ILexer
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.Lexer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBLex\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "ImmutableArray< \fBTextEditorDiagnostic\fP > \fBDiagnosticList\fP\fR [get]\fP"
.br
.ti -1c
.RI "ImmutableArray< \fBISyntaxToken\fP > \fBSyntaxTokenList\fP\fR [get]\fP"
.br
.ti -1c
.RI "ResourceUri \fBResourceUri\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBSourceText\fP\fR [get]\fP"
.br
.ti -1c
.RI "LexerKeywords \fBLexerKeywords\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBILexer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.ILexer\&.Lex ()"

.PP
Implemented in \fBLuthetus\&.CompilerServices\&.C\&.CLexer\fP, \fBLuthetus\&.CompilerServices\&.CSharp\&.LexerCase\&.CSharpLexer\fP, \fBLuthetus\&.CompilerServices\&.Css\&.SyntaxActors\&.TextEditorCssLexer\fP, \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.SyntaxActors\&.DotNetSolutionLexer\fP, \fBLuthetus\&.CompilerServices\&.FSharp\&.SyntaxActors\&.TextEditorFSharpLexer\fP, \fBLuthetus\&.CompilerServices\&.JavaScript\&.SyntaxActors\&.TextEditorJavaScriptLexer\fP, \fBLuthetus\&.CompilerServices\&.Json\&.SyntaxActors\&.TextEditorJsonLexer\fP, \fBLuthetus\&.CompilerServices\&.Python\&.PythonLexer\fP, \fBLuthetus\&.CompilerServices\&.Razor\&.RazorLexer\fP, \fBLuthetus\&.CompilerServices\&.TypeScript\&.SyntaxActors\&.TextEditorTypeScriptLexer\fP, \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.TextEditorXmlLexer\fP, and \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.Lexer\fP\&.
.SH "Property Documentation"
.PP 
.SS "ImmutableArray<\fBTextEditorDiagnostic\fP> Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.ILexer\&.DiagnosticList\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.Lexer\fP\&.
.PP
Definition at line \fB9\fP of file \fBILexer\&.cs\fP\&.
.SS "LexerKeywords Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.ILexer\&.LexerKeywords\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.Lexer\fP\&.
.PP
Definition at line \fB13\fP of file \fBILexer\&.cs\fP\&.
.SS "ResourceUri Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.ILexer\&.ResourceUri\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.Lexer\fP\&.
.PP
Definition at line \fB11\fP of file \fBILexer\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.ILexer\&.SourceText\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.Lexer\fP\&.
.PP
Definition at line \fB12\fP of file \fBILexer\&.cs\fP\&.
.SS "ImmutableArray<\fBISyntaxToken\fP> Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.ILexer\&.SyntaxTokenList\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.Lexer\fP\&.
.PP
Definition at line \fB10\fP of file \fBILexer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
