.TH "Luthetus.CompilerServices.Css.CssSyntaxUnit" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.Css.CssSyntaxUnit
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCssSyntaxUnit\fP (\fBCssDocumentSyntax\fP cssDocumentSyntax, \fBDiagnosticBag\fP \fBdiagnosticBag\fP)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "CssDocumentSyntax \fBCssDocumentSyntax\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBDiagnosticBag\fP \fBdiagnosticBag\fP\fR [get]\fP"
.br
.RI "TODO: Why is this named "diagnosticBag" and in the constructor "this\&.diagnosticBag is used"\&.\&.\&. \&.\&.\&.(am seeing this on 2024-07-12, I presume about a year after it was written)\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBCssSyntaxUnit\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.CompilerServices\&.Css\&.CssSyntaxUnit\&.CssSyntaxUnit (\fBCssDocumentSyntax\fP cssDocumentSyntax, \fBDiagnosticBag\fP diagnosticBag)"

.PP
Definition at line \fB8\fP of file \fBCssSyntaxUnit\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "CssDocumentSyntax Luthetus\&.CompilerServices\&.Css\&.CssSyntaxUnit\&.CssDocumentSyntax\fR [get]\fP"

.PP
Definition at line \fB16\fP of file \fBCssSyntaxUnit\&.cs\fP\&.
.SS "\fBDiagnosticBag\fP Luthetus\&.CompilerServices\&.Css\&.CssSyntaxUnit\&.diagnosticBag\fR [get]\fP"

.PP
TODO: Why is this named "diagnosticBag" and in the constructor "this\&.diagnosticBag is used"\&.\&.\&. \&.\&.\&.(am seeing this on 2024-07-12, I presume about a year after it was written)\&. 
.PP
Definition at line \fB21\fP of file \fBCssSyntaxUnit\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
