.TH "Luthetus.CompilerServices.Css.SyntaxActors.CssSyntaxTree" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.Css.SyntaxActors.CssSyntaxTree
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBCssSyntaxUnit\fP \fBParseText\fP (\fBResourceUri\fP resourceUri, string sourceText)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBCssSyntaxTree\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBCssSyntaxUnit\fP Luthetus\&.CompilerServices\&.Css\&.SyntaxActors\&.CssSyntaxTree\&.ParseText (\fBResourceUri\fP resourceUri, string sourceText)\fR [static]\fP"

.PP
Definition at line \fB16\fP of file \fBCssSyntaxTree\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
