.TH "Luthetus.Extensions.DotNet.TestExplorers.Displays.Internals.TestExplorerDetailsDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.TestExplorers.Displays.Internals.TestExplorerDetailsDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly Key< \fBTextEditorViewModel\fP > \fBDetailsTextEditorViewModelKey\fP = Key<\fBTextEditorViewModel\fP>\&.NewKey()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnParametersSet\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBTestExplorerRenderBatchValidated\fP \fBRenderBatch\fP = null!\fR [get, set]\fP"
.br
.ti -1c
.RI "ElementDimensions \fBElementDimensions\fP = null!\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB19\fP of file \fBTestExplorerDetailsDisplay\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Luthetus\&.Extensions\&.DotNet\&.TestExplorers\&.Displays\&.Internals\&.TestExplorerDetailsDisplay\&.OnParametersSet ()\fR [protected]\fP"

.PP
Definition at line \fB47\fP of file \fBTestExplorerDetailsDisplay\&.razor\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly Key<\fBTextEditorViewModel\fP> Luthetus\&.Extensions\&.DotNet\&.TestExplorers\&.Displays\&.Internals\&.TestExplorerDetailsDisplay\&.DetailsTextEditorViewModelKey = Key<\fBTextEditorViewModel\fP>\&.NewKey()\fR [static]\fP"

.PP
Definition at line \fB34\fP of file \fBTestExplorerDetailsDisplay\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "ElementDimensions Luthetus\&.Extensions\&.DotNet\&.TestExplorers\&.Displays\&.Internals\&.TestExplorerDetailsDisplay\&.ElementDimensions = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB32\fP of file \fBTestExplorerDetailsDisplay\&.razor\&.cs\fP\&.
.SS "\fBTestExplorerRenderBatchValidated\fP Luthetus\&.Extensions\&.DotNet\&.TestExplorers\&.Displays\&.Internals\&.TestExplorerDetailsDisplay\&.RenderBatch = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB29\fP of file \fBTestExplorerDetailsDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
