.TH "Luthetus.Common.RazorLib.Namespaces.Models.NamespacePath" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Namespaces.Models.NamespacePath \- TODO: Move this type somehere else\&. This type currently exists in 'Luthetus\&.Common\&.csproj'\&.\&.\&. \&.\&.\&.because the 'Luthetus\&.CompilerServices\&.DotNetSolution\&.csproj' needed to reference the type\&.
.br
 |
.br
 And with it having originally been in 'Luthetus\&.Ide\&.csproj', this meant a circular reference and it had to be moved here for now\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNamespacePath\fP (string namespaceString, \fBIAbsolutePath\fP absolutePath)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBNamespace\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBIAbsolutePath\fP \fBAbsolutePath\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
TODO: Move this type somehere else\&. This type currently exists in 'Luthetus\&.Common\&.csproj'\&.\&.\&. \&.\&.\&.because the 'Luthetus\&.CompilerServices\&.DotNetSolution\&.csproj' needed to reference the type\&.
.br
 |
.br
 And with it having originally been in 'Luthetus\&.Ide\&.csproj', this meant a circular reference and it had to be moved here for now\&. 
.PP
Definition at line \fB12\fP of file \fBNamespacePath\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Common\&.RazorLib\&.Namespaces\&.Models\&.NamespacePath\&.NamespacePath (string namespaceString, \fBIAbsolutePath\fP absolutePath)"

.PP
Definition at line \fB14\fP of file \fBNamespacePath\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBIAbsolutePath\fP Luthetus\&.Common\&.RazorLib\&.Namespaces\&.Models\&.NamespacePath\&.AbsolutePath\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB21\fP of file \fBNamespacePath\&.cs\fP\&.
.SS "string Luthetus\&.Common\&.RazorLib\&.Namespaces\&.Models\&.NamespacePath\&.Namespace\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB20\fP of file \fBNamespacePath\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
