.TH "Luthetus.CompilerServices.DotNetSolution.SyntaxActors.DotNetSolutionParser" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.DotNetSolution.SyntaxActors.DotNetSolutionParser
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IParser\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDotNetSolutionParser\fP (\fBDotNetSolutionLexer\fP lexer)"
.br
.ti -1c
.RI "\fBCompilationUnit\fP \fBParse\fP ()"
.br
.ti -1c
.RI "void \fBParseAssociatedNameToken\fP (\fBAssociatedNameToken\fP associatedNameToken)"
.br
.ti -1c
.RI "void \fBParseAssociatedValueToken\fP (\fBAssociatedValueToken\fP \fBassociatedValueToken\fP)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "ImmutableArray< \fBTextEditorDiagnostic\fP > \fBDiagnosticsList\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBDotNetSolutionLexer\fP \fBLexer\fP\fR [get]\fP"
.br
.ti -1c
.RI "DotNetSolutionHeader \fBDotNetSolutionHeader\fP\fR [get]\fP"
.br
.ti -1c
.RI "DotNetSolutionGlobal \fBDotNetSolutionGlobal\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBAssociatedEntryGroup\fP? \fBNoParentHavingAssociatedEntryGroup\fP\fR [get]\fP"
.br
.ti -1c
.RI "List< \fBIDotNetProject\fP > \fBDotNetProjectList\fP\fR [get]\fP"
.br
.ti -1c
.RI "List< \fBNestedProjectEntry\fP > \fBNestedProjectEntryList\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB16\fP of file \fBDotNetSolutionParser\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.CompilerServices\&.DotNetSolution\&.SyntaxActors\&.DotNetSolutionParser\&.DotNetSolutionParser (\fBDotNetSolutionLexer\fP lexer)"

.PP
Definition at line \fB29\fP of file \fBDotNetSolutionParser\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBCompilationUnit\fP Luthetus\&.CompilerServices\&.DotNetSolution\&.SyntaxActors\&.DotNetSolutionParser\&.Parse ()"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IParser\fP\&.
.PP
Definition at line \fB50\fP of file \fBDotNetSolutionParser\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.DotNetSolution\&.SyntaxActors\&.DotNetSolutionParser\&.ParseAssociatedNameToken (\fBAssociatedNameToken\fP associatedNameToken)"

.PP
Definition at line \fB121\fP of file \fBDotNetSolutionParser\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.DotNetSolution\&.SyntaxActors\&.DotNetSolutionParser\&.ParseAssociatedValueToken (\fBAssociatedValueToken\fP associatedValueToken)"

.PP
Definition at line \fB174\fP of file \fBDotNetSolutionParser\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "ImmutableArray<\fBTextEditorDiagnostic\fP> Luthetus\&.CompilerServices\&.DotNetSolution\&.SyntaxActors\&.DotNetSolutionParser\&.DiagnosticsList\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IParser\fP\&.
.PP
Definition at line \fB35\fP of file \fBDotNetSolutionParser\&.cs\fP\&.
.SS "List<\fBIDotNetProject\fP> Luthetus\&.CompilerServices\&.DotNetSolution\&.SyntaxActors\&.DotNetSolutionParser\&.DotNetProjectList\fR [get]\fP"

.PP
Definition at line \fB41\fP of file \fBDotNetSolutionParser\&.cs\fP\&.
.SS "DotNetSolutionGlobal Luthetus\&.CompilerServices\&.DotNetSolution\&.SyntaxActors\&.DotNetSolutionParser\&.DotNetSolutionGlobal\fR [get]\fP"

.PP
Definition at line \fB39\fP of file \fBDotNetSolutionParser\&.cs\fP\&.
.SS "DotNetSolutionHeader Luthetus\&.CompilerServices\&.DotNetSolution\&.SyntaxActors\&.DotNetSolutionParser\&.DotNetSolutionHeader\fR [get]\fP"

.PP
Definition at line \fB38\fP of file \fBDotNetSolutionParser\&.cs\fP\&.
.SS "\fBDotNetSolutionLexer\fP Luthetus\&.CompilerServices\&.DotNetSolution\&.SyntaxActors\&.DotNetSolutionParser\&.Lexer\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.IParser\fP\&.
.PP
Definition at line \fB36\fP of file \fBDotNetSolutionParser\&.cs\fP\&.
.SS "List<\fBNestedProjectEntry\fP> Luthetus\&.CompilerServices\&.DotNetSolution\&.SyntaxActors\&.DotNetSolutionParser\&.NestedProjectEntryList\fR [get]\fP"

.PP
Definition at line \fB42\fP of file \fBDotNetSolutionParser\&.cs\fP\&.
.SS "\fBAssociatedEntryGroup\fP? Luthetus\&.CompilerServices\&.DotNetSolution\&.SyntaxActors\&.DotNetSolutionParser\&.NoParentHavingAssociatedEntryGroup\fR [get]\fP"

.PP
Definition at line \fB40\fP of file \fBDotNetSolutionParser\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
