.TH "Luthetus.Extensions.DotNet.TestExplorers.Models.TestExplorerRenderBatch" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.TestExplorers.Models.TestExplorerRenderBatch
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Extensions\&.DotNet\&.TestExplorers\&.Models\&.ITestExplorerRenderBatch\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTestExplorerRenderBatch\fP (\fBTestExplorerState\fP testExplorerState, \fBAppOptionsState\fP appOptionsState, \fBTreeViewContainer\fP? treeViewContainer)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "TestExplorerState \fBTestExplorerState\fP\fR [get]\fP"
.br
.ti -1c
.RI "AppOptionsState \fBAppOptionsState\fP\fR [get]\fP"
.br
.ti -1c
.RI "TreeViewContainer? \fBTreeViewContainer\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBTestExplorerRenderBatch\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Extensions\&.DotNet\&.TestExplorers\&.Models\&.TestExplorerRenderBatch\&.TestExplorerRenderBatch (\fBTestExplorerState\fP testExplorerState, \fBAppOptionsState\fP appOptionsState, \fBTreeViewContainer\fP? treeViewContainer)"

.PP
Definition at line \fB9\fP of file \fBTestExplorerRenderBatch\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "AppOptionsState Luthetus\&.Extensions\&.DotNet\&.TestExplorers\&.Models\&.TestExplorerRenderBatch\&.AppOptionsState\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Extensions\&.DotNet\&.TestExplorers\&.Models\&.ITestExplorerRenderBatch\fP\&.
.PP
Definition at line \fB20\fP of file \fBTestExplorerRenderBatch\&.cs\fP\&.
.SS "TestExplorerState Luthetus\&.Extensions\&.DotNet\&.TestExplorers\&.Models\&.TestExplorerRenderBatch\&.TestExplorerState\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Extensions\&.DotNet\&.TestExplorers\&.Models\&.ITestExplorerRenderBatch\fP\&.
.PP
Definition at line \fB19\fP of file \fBTestExplorerRenderBatch\&.cs\fP\&.
.SS "TreeViewContainer? Luthetus\&.Extensions\&.DotNet\&.TestExplorers\&.Models\&.TestExplorerRenderBatch\&.TreeViewContainer\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Extensions\&.DotNet\&.TestExplorers\&.Models\&.ITestExplorerRenderBatch\fP\&.
.PP
Definition at line \fB21\fP of file \fBTestExplorerRenderBatch\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
