.TH "Luthetus.TextEditor.RazorLib.Installations.Models.TryRegisterViewModelArgs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Installations.Models.TryRegisterViewModelArgs
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTryRegisterViewModelArgs\fP (Key< \fBTextEditorViewModel\fP > viewModelKey, \fBResourceUri\fP \fBresourceUri\fP, \fBCategory\fP \fBcategory\fP, bool shouldSetFocusToEditor, IServiceProvider serviceProvider)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Key< \fBTextEditorViewModel\fP > \fBViewModelKey\fP\fR [get]\fP"
.br
.RI "One can use Key<T>\&.NewKey() if they have no preference for the key value\&. 
.br

.br
 The identifier for the view model which is used by most of the API in TextEditors\&.Models\&.TextEditorServices\&.ITextEditorService\&. "
.ti -1c
.RI "ResourceUri \fBResourceUri\fP\fR [get]\fP"
.br
.RI "The unique identifier for the \fBTextEditorModel\fP which is providing the underlying data to be rendered by this view model\&. "
.ti -1c
.RI "Category \fBCategory\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBShouldSetFocusToEditor\fP\fR [get]\fP"
.br
.RI "When this view model next gets rendered should browser focus be set to the text editor\&. "
.ti -1c
.RI "IServiceProvider \fBServiceProvider\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBTryRegisterViewModelArgs\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.Installations\&.Models\&.TryRegisterViewModelArgs\&.TryRegisterViewModelArgs (Key< \fBTextEditorViewModel\fP > viewModelKey, \fBResourceUri\fP resourceUri, \fBCategory\fP category, bool shouldSetFocusToEditor, IServiceProvider serviceProvider)"

.PP
Definition at line \fB9\fP of file \fBTryRegisterViewModelArgs\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Category Luthetus\&.TextEditor\&.RazorLib\&.Installations\&.Models\&.TryRegisterViewModelArgs\&.Category\fR [get]\fP"

.PP

.PP
Definition at line \fB38\fP of file \fBTryRegisterViewModelArgs\&.cs\fP\&.
.SS "ResourceUri Luthetus\&.TextEditor\&.RazorLib\&.Installations\&.Models\&.TryRegisterViewModelArgs\&.ResourceUri\fR [get]\fP"

.PP
The unique identifier for the \fBTextEditorModel\fP which is providing the underlying data to be rendered by this view model\&. 
.PP
Definition at line \fB34\fP of file \fBTryRegisterViewModelArgs\&.cs\fP\&.
.SS "IServiceProvider Luthetus\&.TextEditor\&.RazorLib\&.Installations\&.Models\&.TryRegisterViewModelArgs\&.ServiceProvider\fR [get]\fP"

.PP
Definition at line \fB43\fP of file \fBTryRegisterViewModelArgs\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.Installations\&.Models\&.TryRegisterViewModelArgs\&.ShouldSetFocusToEditor\fR [get]\fP"

.PP
When this view model next gets rendered should browser focus be set to the text editor\&. 
.PP
Definition at line \fB42\fP of file \fBTryRegisterViewModelArgs\&.cs\fP\&.
.SS "Key<\fBTextEditorViewModel\fP> Luthetus\&.TextEditor\&.RazorLib\&.Installations\&.Models\&.TryRegisterViewModelArgs\&.ViewModelKey\fR [get]\fP"

.PP
One can use Key<T>\&.NewKey() if they have no preference for the key value\&. 
.br

.br
 The identifier for the view model which is used by most of the API in TextEditors\&.Models\&.TextEditorServices\&.ITextEditorService\&. 
.PP
Definition at line \fB29\fP of file \fBTryRegisterViewModelArgs\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
