.TH "Luthetus.Common.RazorLib.UnitTesting.CommonUnitTestHelper" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.UnitTesting.CommonUnitTestHelper
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCommonUnitTestHelper\fP (IServiceProvider serviceProvider)"
.br
.RI "To create an instance of \fBCommonUnitTestHelper\fP, one should invoke \fBAddLuthetusCommonServicesUnitTesting(IServiceCollection, LuthetusHostingInformation)\fP, then build the IServiceProvider, and provide the built serviceProvider to this constructor\&. "
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static IServiceCollection \fBAddLuthetusCommonServicesUnitTesting\fP (IServiceCollection services, \fBLuthetusHostingInformation\fP \fBhostingInformation\fP)"
.br
.RI "This method is not an extension method due to its niche nature\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBIEnvironmentProvider\fP \fBEnvironmentProvider\fP\fR [get]\fP"
.br
.RI "Implementation is intended to be \fBInMemoryEnvironmentProvider\fP\&. "
.ti -1c
.RI "\fBIFileSystemProvider\fP \fBFileSystemProvider\fP\fR [get]\fP"
.br
.RI "Implementation is intended to be \fBInMemoryFileSystemProvider\fP\&. "
.ti -1c
.RI "\fBIAppOptionsService\fP \fBAppOptionsService\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBIDialogService\fP \fBDialogService\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBIStorageService\fP \fBStorageService\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBIDragService\fP \fBDragService\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBIDropdownService\fP \fBDropdownService\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBIClipboardService\fP \fBClipboardService\fP\fR [get]\fP"
.br
.RI "Implementation is intended to be \fBInMemoryClipboardService\fP\&. "
.ti -1c
.RI "\fBINotificationService\fP \fBNotificationService\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBIThemeService\fP \fBThemeService\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBITreeViewService\fP \fBTreeViewService\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB17\fP of file \fBCommonUnitTestHelper\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Common\&.RazorLib\&.UnitTesting\&.CommonUnitTestHelper\&.CommonUnitTestHelper (IServiceProvider serviceProvider)"

.PP
To create an instance of \fBCommonUnitTestHelper\fP, one should invoke \fBAddLuthetusCommonServicesUnitTesting(IServiceCollection, LuthetusHostingInformation)\fP, then build the IServiceProvider, and provide the built serviceProvider to this constructor\&. 
.PP
Definition at line \fB24\fP of file \fBCommonUnitTestHelper\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "IServiceCollection Luthetus\&.Common\&.RazorLib\&.UnitTesting\&.CommonUnitTestHelper\&.AddLuthetusCommonServicesUnitTesting (IServiceCollection services, \fBLuthetusHostingInformation\fP hostingInformation)\fR [static]\fP"

.PP
This method is not an extension method due to its niche nature\&. 
.PP
Definition at line \fB63\fP of file \fBCommonUnitTestHelper\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBIAppOptionsService\fP Luthetus\&.Common\&.RazorLib\&.UnitTesting\&.CommonUnitTestHelper\&.AppOptionsService\fR [get]\fP"

.PP
Definition at line \fB49\fP of file \fBCommonUnitTestHelper\&.cs\fP\&.
.SS "\fBIClipboardService\fP Luthetus\&.Common\&.RazorLib\&.UnitTesting\&.CommonUnitTestHelper\&.ClipboardService\fR [get]\fP"

.PP
Implementation is intended to be \fBInMemoryClipboardService\fP\&. 
.PP
Definition at line \fB57\fP of file \fBCommonUnitTestHelper\&.cs\fP\&.
.SS "\fBIDialogService\fP Luthetus\&.Common\&.RazorLib\&.UnitTesting\&.CommonUnitTestHelper\&.DialogService\fR [get]\fP"

.PP
Definition at line \fB50\fP of file \fBCommonUnitTestHelper\&.cs\fP\&.
.SS "\fBIDragService\fP Luthetus\&.Common\&.RazorLib\&.UnitTesting\&.CommonUnitTestHelper\&.DragService\fR [get]\fP"

.PP
Definition at line \fB52\fP of file \fBCommonUnitTestHelper\&.cs\fP\&.
.SS "\fBIDropdownService\fP Luthetus\&.Common\&.RazorLib\&.UnitTesting\&.CommonUnitTestHelper\&.DropdownService\fR [get]\fP"

.PP
Definition at line \fB53\fP of file \fBCommonUnitTestHelper\&.cs\fP\&.
.SS "\fBIEnvironmentProvider\fP Luthetus\&.Common\&.RazorLib\&.UnitTesting\&.CommonUnitTestHelper\&.EnvironmentProvider\fR [get]\fP"

.PP
Implementation is intended to be \fBInMemoryEnvironmentProvider\fP\&. 
.PP
Definition at line \fB44\fP of file \fBCommonUnitTestHelper\&.cs\fP\&.
.SS "\fBIFileSystemProvider\fP Luthetus\&.Common\&.RazorLib\&.UnitTesting\&.CommonUnitTestHelper\&.FileSystemProvider\fR [get]\fP"

.PP
Implementation is intended to be \fBInMemoryFileSystemProvider\fP\&. 
.PP
Definition at line \fB48\fP of file \fBCommonUnitTestHelper\&.cs\fP\&.
.SS "\fBINotificationService\fP Luthetus\&.Common\&.RazorLib\&.UnitTesting\&.CommonUnitTestHelper\&.NotificationService\fR [get]\fP"

.PP
Definition at line \fB58\fP of file \fBCommonUnitTestHelper\&.cs\fP\&.
.SS "\fBIStorageService\fP Luthetus\&.Common\&.RazorLib\&.UnitTesting\&.CommonUnitTestHelper\&.StorageService\fR [get]\fP"

.PP
Definition at line \fB51\fP of file \fBCommonUnitTestHelper\&.cs\fP\&.
.SS "\fBIThemeService\fP Luthetus\&.Common\&.RazorLib\&.UnitTesting\&.CommonUnitTestHelper\&.ThemeService\fR [get]\fP"

.PP
Definition at line \fB59\fP of file \fBCommonUnitTestHelper\&.cs\fP\&.
.SS "\fBITreeViewService\fP Luthetus\&.Common\&.RazorLib\&.UnitTesting\&.CommonUnitTestHelper\&.TreeViewService\fR [get]\fP"

.PP
Definition at line \fB60\fP of file \fBCommonUnitTestHelper\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
