.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.StringWalkerTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.StringWalkerTests \- \fBStringWalker\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "StringWalker(ResourceUri, string) 
.br
----
.br
 \fBStringWalker\&.PositionIndex\fP \fBStringWalker\&.ResourceUri\fP \fBStringWalker\&.SourceText\fP \fBStringWalker\&.CurrentCharacter\fP \fBStringWalker\&.NextCharacter\fP \fBStringWalker\&.RemainingText\fP \fBStringWalker\&.IsEof\fP \fBStringWalker\&.ReadCharacter()\fP \fBStringWalker\&.PeekCharacter(int)\fP \fBStringWalker\&.BacktrackCharacter()\fP \fBStringWalker\&.ReadRange(int)\fP \fBStringWalker\&.PeekRange(int, int)\fP \fBStringWalker\&.BacktrackRange(int)\fP \fBStringWalker\&.PeekNextWord()\fP \fBStringWalker\&.PeekForSubstring(string)\fP StringWalker\&.PeekForSubstringRange(ImmutableArray<string>, out string?) \fBStringWalker\&.ReadWhitespace(IEnumerable<char>?)\fP \fBStringWalker\&.ReadUnsignedNumericLiteral()\fP \fBStringWalker\&.ReadUntil(char)\fP \fBStringWalker\&.ReadLine()\fP StringWalker\&.ReadWordTuple(ImmutableArray<char>?) "
.ti -1c
.RI "void \fBReadUnsignedNumericLiteral\fP ()"
.br
.RI "\fBStringWalker\&.ReadUnsignedNumericLiteral()\fP "
.ti -1c
.RI "void \fBReadWhitespace\fP ()"
.br
.RI "\fBStringWalker\&.ReadWhitespace(IEnumerable<char>?)\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBStringWalker\fP 
.PP
Definition at line \fB13\fP of file \fBStringWalkerTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.StringWalkerTests\&.Constructor ()"

.PP
StringWalker(ResourceUri, string) 
.br
----
.br
 \fBStringWalker\&.PositionIndex\fP \fBStringWalker\&.ResourceUri\fP \fBStringWalker\&.SourceText\fP \fBStringWalker\&.CurrentCharacter\fP \fBStringWalker\&.NextCharacter\fP \fBStringWalker\&.RemainingText\fP \fBStringWalker\&.IsEof\fP \fBStringWalker\&.ReadCharacter()\fP \fBStringWalker\&.PeekCharacter(int)\fP \fBStringWalker\&.BacktrackCharacter()\fP \fBStringWalker\&.ReadRange(int)\fP \fBStringWalker\&.PeekRange(int, int)\fP \fBStringWalker\&.BacktrackRange(int)\fP \fBStringWalker\&.PeekNextWord()\fP \fBStringWalker\&.PeekForSubstring(string)\fP StringWalker\&.PeekForSubstringRange(ImmutableArray<string>, out string?) \fBStringWalker\&.ReadWhitespace(IEnumerable<char>?)\fP \fBStringWalker\&.ReadUnsignedNumericLiteral()\fP \fBStringWalker\&.ReadUntil(char)\fP \fBStringWalker\&.ReadLine()\fP StringWalker\&.ReadWordTuple(ImmutableArray<char>?) 
.PP
Definition at line \fB41\fP of file \fBStringWalkerTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.StringWalkerTests\&.ReadUnsignedNumericLiteral ()"

.PP
\fBStringWalker\&.ReadUnsignedNumericLiteral()\fP 
.PP
Definition at line \fB307\fP of file \fBStringWalkerTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.StringWalkerTests\&.ReadWhitespace ()"

.PP
\fBStringWalker\&.ReadWhitespace(IEnumerable<char>?)\fP 
.PP
Definition at line \fB353\fP of file \fBStringWalkerTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
