.TH "Luthetus.Common.RazorLib.Commands.Models.TreeViewCommandArgs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Commands.Models.TreeViewCommandArgs
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Common\&.RazorLib\&.Commands\&.Models\&.ICommandArgs\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTreeViewCommandArgs\fP (\fBITreeViewService\fP treeViewService, \fBTreeViewContainer\fP treeViewContainer, \fBTreeViewNoType\fP? nodeThatReceivedMouseEvent, Func< Task > restoreFocusToTreeView, \fBContextMenuFixedPosition\fP? contextMenuFixedPosition, \fBMouseEventArgs\fP? mouseEventArgs, \fBKeyboardEventArgs\fP? keyboardEventArgs)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBITreeViewService\fP \fBTreeViewService\fP\fR [get]\fP"
.br
.ti -1c
.RI "TreeViewContainer \fBTreeViewContainer\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBTreeViewNoType\fP? \fBNodeThatReceivedMouseEvent\fP\fR [get]\fP"
.br
.ti -1c
.RI "Func< Task > \fBRestoreFocusToTreeView\fP\fR [get]\fP"
.br
.ti -1c
.RI "ContextMenuFixedPosition? \fBContextMenuFixedPosition\fP\fR [get]\fP"
.br
.ti -1c
.RI "MouseEventArgs? \fBMouseEventArgs\fP\fR [get]\fP"
.br
.ti -1c
.RI "KeyboardEventArgs? \fBKeyboardEventArgs\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBTreeViewCommandArgs\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Common\&.RazorLib\&.Commands\&.Models\&.TreeViewCommandArgs\&.TreeViewCommandArgs (\fBITreeViewService\fP treeViewService, \fBTreeViewContainer\fP treeViewContainer, \fBTreeViewNoType\fP? nodeThatReceivedMouseEvent, Func< Task > restoreFocusToTreeView, \fBContextMenuFixedPosition\fP? contextMenuFixedPosition, \fBMouseEventArgs\fP? mouseEventArgs, \fBKeyboardEventArgs\fP? keyboardEventArgs)"

.PP
Definition at line \fB9\fP of file \fBTreeViewCommandArgs\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "ContextMenuFixedPosition? Luthetus\&.Common\&.RazorLib\&.Commands\&.Models\&.TreeViewCommandArgs\&.ContextMenuFixedPosition\fR [get]\fP"

.PP
Definition at line \fB31\fP of file \fBTreeViewCommandArgs\&.cs\fP\&.
.SS "KeyboardEventArgs? Luthetus\&.Common\&.RazorLib\&.Commands\&.Models\&.TreeViewCommandArgs\&.KeyboardEventArgs\fR [get]\fP"

.PP
Definition at line \fB33\fP of file \fBTreeViewCommandArgs\&.cs\fP\&.
.SS "MouseEventArgs? Luthetus\&.Common\&.RazorLib\&.Commands\&.Models\&.TreeViewCommandArgs\&.MouseEventArgs\fR [get]\fP"

.PP
Definition at line \fB32\fP of file \fBTreeViewCommandArgs\&.cs\fP\&.
.SS "\fBTreeViewNoType\fP? Luthetus\&.Common\&.RazorLib\&.Commands\&.Models\&.TreeViewCommandArgs\&.NodeThatReceivedMouseEvent\fR [get]\fP"

.PP
Definition at line \fB29\fP of file \fBTreeViewCommandArgs\&.cs\fP\&.
.SS "Func<Task> Luthetus\&.Common\&.RazorLib\&.Commands\&.Models\&.TreeViewCommandArgs\&.RestoreFocusToTreeView\fR [get]\fP"

.PP
Definition at line \fB30\fP of file \fBTreeViewCommandArgs\&.cs\fP\&.
.SS "TreeViewContainer Luthetus\&.Common\&.RazorLib\&.Commands\&.Models\&.TreeViewCommandArgs\&.TreeViewContainer\fR [get]\fP"

.PP
Definition at line \fB28\fP of file \fBTreeViewCommandArgs\&.cs\fP\&.
.SS "\fBITreeViewService\fP Luthetus\&.Common\&.RazorLib\&.Commands\&.Models\&.TreeViewCommandArgs\&.TreeViewService\fR [get]\fP"

.PP
Definition at line \fB27\fP of file \fBTreeViewCommandArgs\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
