.TH "Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.ViewModelDisplayOptions" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.ViewModelDisplayOptions
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBWrapperStyleCssString\fP = string\&.Empty\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBWrapperClassCssString\fP = string\&.Empty\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBTextEditorStyleCssString\fP = string\&.Empty\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBTextEditorClassCssString\fP = string\&.Empty\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBTabIndex\fP = \-1\fR [get, set]\fP"
.br
.RI "TabIndex is used for the html attribute named: 'tabindex'\&. "
.ti -1c
.RI "RenderFragment< \fBTextEditorRenderBatchValidated\fP >? \fBContextMenuRenderFragmentOverride\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "RenderFragment< \fBTextEditorRenderBatchValidated\fP >? \fBAutoCompleteMenuRenderFragmentOverride\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "Func< \fBITextEditorEditContext\fP, \fBTextEditorModelModifier\fP, \fBTextEditorViewModelModifier\fP, \fBCursorModifierBagTextEditor\fP, \fBKeymapArgs\fP, \fBTextEditorComponentData\fP, Task >? \fBAfterOnKeyDownAsync\fP\fR [get, set]\fP"
.br
.RI "If left null, the default HandleAfterOnKeyDownAsync will be used\&. "
.ti -1c
.RI "Func< \fBITextEditorEditContext\fP, \fBTextEditorModelModifier\fP, \fBTextEditorViewModelModifier\fP, \fBCursorModifierBagTextEditor\fP, \fBKeymapArgs\fP[], int, \fBTextEditorComponentData\fP, Task >? \fBAfterOnKeyDownRangeAsync\fP\fR [get, set]\fP"
.br
.RI "If left null, the default HandleAfterOnKeyDownRangeAsync will be used\&. "
.ti -1c
.RI "Type? \fBHeaderComponentType\fP = typeof(\fBTextEditorDefaultHeaderDisplay\fP)\fR [get, set]\fP"
.br
.RI "If set to null then no header will render\&. "
.ti -1c
.RI "ImmutableArray< \fBHeaderButtonKind\fP >? \fBHeaderButtonKinds\fP\fR [get, set]\fP"
.br
.RI "HeaderButtonKinds contains the enum value that represents a button displayed in the optional component: TextEditorHeader\&. "
.ti -1c
.RI "Type? \fBFooterComponentType\fP = typeof(\fBTextEditorDefaultFooterDisplay\fP)\fR [get, set]\fP"
.br
.RI "If set to null then no footer will render\&. "
.ti -1c
.RI "bool \fBIncludeGutterComponent\fP = true\fR [get, set]\fP"
.br
.RI "If set to false: the Displays\&.Internals\&.GutterSection will NOT render\&. (i\&.e\&. line numbers will not render)\&. "
.ti -1c
.RI "bool \fBIncludeContextMenuHelperComponent\fP = true\fR [get, set]\fP"
.br
.ti -1c
.RI "ContextRecord \fBContextRecord\fP = ContextFacts\&.TextEditorContext\fR [get, set]\fP"
.br
.ti -1c
.RI "\fBKeymap\fP? \fBKeymapOverride\fP\fR [get, set]\fP"
.br
.RI "The integrated terminal logic needs a keymap, separate to that of the 'global' keymap used by other text editors\&. Therefore, this property is used to provide the Keymaps\&.Models\&.Terminals\&.TextEditorKeymapTerminal to the integrated terminal\&.
.br

.br
\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBViewModelDisplayOptions\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Func< \fBITextEditorEditContext\fP, \fBTextEditorModelModifier\fP, \fBTextEditorViewModelModifier\fP, \fBCursorModifierBagTextEditor\fP, \fBKeymapArgs\fP, \fBTextEditorComponentData\fP, Task>? Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ViewModelDisplayOptions\&.AfterOnKeyDownAsync\fR [get]\fP, \fR [set]\fP"

.PP
If left null, the default HandleAfterOnKeyDownAsync will be used\&. 
.PP
Definition at line \fB35\fP of file \fBViewModelDisplayOptions\&.cs\fP\&.
.SS "Func< \fBITextEditorEditContext\fP, \fBTextEditorModelModifier\fP, \fBTextEditorViewModelModifier\fP, \fBCursorModifierBagTextEditor\fP, \fBKeymapArgs\fP[], int, \fBTextEditorComponentData\fP, Task>? Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ViewModelDisplayOptions\&.AfterOnKeyDownRangeAsync\fR [get]\fP, \fR [set]\fP"

.PP
If left null, the default HandleAfterOnKeyDownRangeAsync will be used\&. If a batch handling of KeyboardEventArgs is performed, then this method will be invoked as opposed to AfterOnKeyDownAsyncFactory, and a list of KeyboardEventArgs will be provided, sorted such that the first index represents the first event fired, and the last index represents the last event fired\&. 
.PP
Definition at line \fB54\fP of file \fBViewModelDisplayOptions\&.cs\fP\&.
.SS "RenderFragment<\fBTextEditorRenderBatchValidated\fP>? Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ViewModelDisplayOptions\&.AutoCompleteMenuRenderFragmentOverride\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB22\fP of file \fBViewModelDisplayOptions\&.cs\fP\&.
.SS "RenderFragment<\fBTextEditorRenderBatchValidated\fP>? Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ViewModelDisplayOptions\&.ContextMenuRenderFragmentOverride\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB21\fP of file \fBViewModelDisplayOptions\&.cs\fP\&.
.SS "ContextRecord Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ViewModelDisplayOptions\&.ContextRecord = ContextFacts\&.TextEditorContext\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB84\fP of file \fBViewModelDisplayOptions\&.cs\fP\&.
.SS "Type? Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ViewModelDisplayOptions\&.FooterComponentType = typeof(\fBTextEditorDefaultFooterDisplay\fP)\fR [get]\fP, \fR [set]\fP"

.PP
If set to null then no footer will render\&. If overriden to non-null, the component is expected to have CSS style attribute height="var(--luth_te_text-editor-footer-height)" 
.PP
Definition at line \fB75\fP of file \fBViewModelDisplayOptions\&.cs\fP\&.
.SS "ImmutableArray<\fBHeaderButtonKind\fP>? Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ViewModelDisplayOptions\&.HeaderButtonKinds\fR [get]\fP, \fR [set]\fP"

.PP
HeaderButtonKinds contains the enum value that represents a button displayed in the optional component: TextEditorHeader\&. 
.PP
Definition at line \fB67\fP of file \fBViewModelDisplayOptions\&.cs\fP\&.
.SS "Type? Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ViewModelDisplayOptions\&.HeaderComponentType = typeof(\fBTextEditorDefaultHeaderDisplay\fP)\fR [get]\fP, \fR [set]\fP"

.PP
If set to null then no header will render\&. If overriden to non-null, the component is expected to have CSS style attribute height="var(--luth_te_text-editor-header-height)" 
.PP
Definition at line \fB62\fP of file \fBViewModelDisplayOptions\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ViewModelDisplayOptions\&.IncludeContextMenuHelperComponent = true\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB82\fP of file \fBViewModelDisplayOptions\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ViewModelDisplayOptions\&.IncludeGutterComponent = true\fR [get]\fP, \fR [set]\fP"

.PP
If set to false: the Displays\&.Internals\&.GutterSection will NOT render\&. (i\&.e\&. line numbers will not render)\&. 
.PP
Definition at line \fB80\fP of file \fBViewModelDisplayOptions\&.cs\fP\&.
.SS "\fBKeymap\fP? Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ViewModelDisplayOptions\&.KeymapOverride\fR [get]\fP, \fR [set]\fP"

.PP
The integrated terminal logic needs a keymap, separate to that of the 'global' keymap used by other text editors\&. Therefore, this property is used to provide the Keymaps\&.Models\&.Terminals\&.TextEditorKeymapTerminal to the integrated terminal\&.
.br

.br
\&. This property is not intended for use in any other scenario\&. 
.PP
Definition at line \fB93\fP of file \fBViewModelDisplayOptions\&.cs\fP\&.
.SS "int Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ViewModelDisplayOptions\&.TabIndex = \-1\fR [get]\fP, \fR [set]\fP"

.PP
TabIndex is used for the html attribute named: 'tabindex'\&. 
.PP
Definition at line \fB20\fP of file \fBViewModelDisplayOptions\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ViewModelDisplayOptions\&.TextEditorClassCssString = string\&.Empty\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB15\fP of file \fBViewModelDisplayOptions\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ViewModelDisplayOptions\&.TextEditorStyleCssString = string\&.Empty\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB14\fP of file \fBViewModelDisplayOptions\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ViewModelDisplayOptions\&.WrapperClassCssString = string\&.Empty\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB13\fP of file \fBViewModelDisplayOptions\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ViewModelDisplayOptions\&.WrapperStyleCssString = string\&.Empty\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB12\fP of file \fBViewModelDisplayOptions\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
