.TH "Luthetus.TextEditor.Tests.Basis.Groups.States.TextEditorGroupStateReducerTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.Groups.States.TextEditorGroupStateReducerTests \- \fBTextEditorGroupState\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBReduceRegisterAction\fP ()"
.br
.RI "TextEditorGroupState\&.Reducer\&.ReduceRegisterAction(TextEditorGroupState, TextEditorGroupState\&.RegisterAction) "
.ti -1c
.RI "void \fBReduceAddViewModelToGroupAction\fP ()"
.br
.RI "TextEditorGroupState\&.Reducer\&.ReduceAddViewModelToGroupAction(TextEditorGroupState, TextEditorGroupState\&.AddViewModelToGroupAction) "
.ti -1c
.RI "void \fBReduceRemoveViewModelFromGroupAction\fP ()"
.br
.RI "TextEditorGroupState\&.Reducer\&.ReduceRemoveViewModelFromGroupAction(TextEditorGroupState, TextEditorGroupState\&.RemoveViewModelFromGroupAction) "
.ti -1c
.RI "void \fBReduceSetActiveViewModelOfGroupAction\fP ()"
.br
.RI "TextEditorGroupState\&.Reducer\&.ReduceSetActiveViewModelOfGroupAction(TextEditorGroupState, TextEditorGroupState\&.SetActiveViewModelOfGroupAction) "
.ti -1c
.RI "void \fBReduceDisposeAction\fP ()"
.br
.RI "TextEditorGroupState\&.Reducer\&.ReduceDisposeAction(TextEditorGroupState, TextEditorGroupState\&.DisposeAction) "
.in -1c
.SH "Detailed Description"
.PP 
\fBTextEditorGroupState\fP 
.PP
Definition at line \fB8\fP of file \fBTextEditorGroupState\&.ReducerTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Groups\&.States\&.TextEditorGroupStateReducerTests\&.ReduceAddViewModelToGroupAction ()"

.PP
TextEditorGroupState\&.Reducer\&.ReduceAddViewModelToGroupAction(TextEditorGroupState, TextEditorGroupState\&.AddViewModelToGroupAction) 
.PP
Definition at line \fB23\fP of file \fBTextEditorGroupState\&.ReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Groups\&.States\&.TextEditorGroupStateReducerTests\&.ReduceDisposeAction ()"

.PP
TextEditorGroupState\&.Reducer\&.ReduceDisposeAction(TextEditorGroupState, TextEditorGroupState\&.DisposeAction) 
.PP
Definition at line \fB50\fP of file \fBTextEditorGroupState\&.ReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Groups\&.States\&.TextEditorGroupStateReducerTests\&.ReduceRegisterAction ()"

.PP
TextEditorGroupState\&.Reducer\&.ReduceRegisterAction(TextEditorGroupState, TextEditorGroupState\&.RegisterAction) 
.PP
Definition at line \fB14\fP of file \fBTextEditorGroupState\&.ReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Groups\&.States\&.TextEditorGroupStateReducerTests\&.ReduceRemoveViewModelFromGroupAction ()"

.PP
TextEditorGroupState\&.Reducer\&.ReduceRemoveViewModelFromGroupAction(TextEditorGroupState, TextEditorGroupState\&.RemoveViewModelFromGroupAction) 
.PP
Definition at line \fB32\fP of file \fBTextEditorGroupState\&.ReducerTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Groups\&.States\&.TextEditorGroupStateReducerTests\&.ReduceSetActiveViewModelOfGroupAction ()"

.PP
TextEditorGroupState\&.Reducer\&.ReduceSetActiveViewModelOfGroupAction(TextEditorGroupState, TextEditorGroupState\&.SetActiveViewModelOfGroupAction) 
.PP
Definition at line \fB41\fP of file \fBTextEditorGroupState\&.ReducerTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
