.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.AttributeNodeTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.AttributeNodeTests \- \fBAttributeNode\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "AttributeNode(OpenSquareBracketToken, CloseSquareBracketToken) 
.br
----
.br
 \fBAttributeNode\&.OpenSquareBracketToken\fP \fBAttributeNode\&.CloseSquareBracketToken\fP AttributeNode\&.ChildList \fBAttributeNode\&.IsFabricated\fP \fBAttributeNode\&.SyntaxKind\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBAttributeNode\fP 
.PP
Definition at line \fB10\fP of file \fBAttributeNodeTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.Syntax\&.SyntaxNodes\&.AttributeNodeTests\&.Constructor ()"

.PP
AttributeNode(OpenSquareBracketToken, CloseSquareBracketToken) 
.br
----
.br
 \fBAttributeNode\&.OpenSquareBracketToken\fP \fBAttributeNode\&.CloseSquareBracketToken\fP AttributeNode\&.ChildList \fBAttributeNode\&.IsFabricated\fP \fBAttributeNode\&.SyntaxKind\fP 
.PP
Definition at line \fB22\fP of file \fBAttributeNodeTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
