.TH "Luthetus.Ide.RazorLib.InputFiles.Displays.InputFileDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.InputFiles.Displays.InputFileDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits FluxorComponent, and \fBLuthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.IInputFileRendererType\fP\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInitialized\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "RenderFragment< \fBIAbsolutePath\fP?>? \fBHeaderRenderFragment\fP\fR [get, set]\fP"
.br
.RI "Receives the _selectedAbsolutePath as a parameter to the RenderFragment\&. "
.ti -1c
.RI "RenderFragment< \fBIAbsolutePath\fP?>? \fBFooterRenderFragment\fP\fR [get, set]\fP"
.br
.RI "Receives the _selectedAbsolutePath as a parameter to the RenderFragment\&. "
.ti -1c
.RI "string \fBBodyClassCssString\fP = null!\fR [get, set]\fP"
.br
.RI "One would likely use BodyClassCssString in the case where either HeaderRenderFragment or FooterRenderFragment are being used\&. 
.br

.br
 This is due to one likely wanting to set a fixed height for the HeaderRenderFragment and a fixed height for the FooterRenderFragment and lastly the body gets a fixed height of calc(100% - HeightForHeaderRenderFragment - HeightForFooterRenderFragment);\&. "
.ti -1c
.RI "string \fBBodyStyleCssString\fP = null!\fR [get, set]\fP"
.br
.RI "One would likely use BodyStyleCssString in the case where either HeaderRenderFragment or FooterRenderFragment are being used\&. 
.br

.br
 This is due to one likely wanting to set a fixed height for the HeaderRenderFragment and a fixed height for the FooterRenderFragment and lastly the body gets a fixed height of calc(100% - HeightForHeaderRenderFragment - HeightForFooterRenderFragment);\&. "
.ti -1c
.RI "ElementReference? \fBSearchElementReference\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB20\fP of file \fBInputFileDisplay\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Luthetus\&.Ide\&.RazorLib\&.InputFiles\&.Displays\&.InputFileDisplay\&.OnInitialized ()\fR [protected]\fP"

.PP
Definition at line \fB96\fP of file \fBInputFileDisplay\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Luthetus\&.Ide\&.RazorLib\&.InputFiles\&.Displays\&.InputFileDisplay\&.BodyClassCssString = null!\fR [get]\fP, \fR [set]\fP"

.PP
One would likely use BodyClassCssString in the case where either HeaderRenderFragment or FooterRenderFragment are being used\&. 
.br

.br
 This is due to one likely wanting to set a fixed height for the HeaderRenderFragment and a fixed height for the FooterRenderFragment and lastly the body gets a fixed height of calc(100% - HeightForHeaderRenderFragment - HeightForFooterRenderFragment);\&. 
.PP
Definition at line \fB63\fP of file \fBInputFileDisplay\&.razor\&.cs\fP\&.
.SS "string Luthetus\&.Ide\&.RazorLib\&.InputFiles\&.Displays\&.InputFileDisplay\&.BodyStyleCssString = null!\fR [get]\fP, \fR [set]\fP"

.PP
One would likely use BodyStyleCssString in the case where either HeaderRenderFragment or FooterRenderFragment are being used\&. 
.br

.br
 This is due to one likely wanting to set a fixed height for the HeaderRenderFragment and a fixed height for the FooterRenderFragment and lastly the body gets a fixed height of calc(100% - HeightForHeaderRenderFragment - HeightForFooterRenderFragment);\&. 
.PP
Definition at line \fB74\fP of file \fBInputFileDisplay\&.razor\&.cs\fP\&.
.SS "RenderFragment<\fBIAbsolutePath\fP?>? Luthetus\&.Ide\&.RazorLib\&.InputFiles\&.Displays\&.InputFileDisplay\&.FooterRenderFragment\fR [get]\fP, \fR [set]\fP"

.PP
Receives the _selectedAbsolutePath as a parameter to the RenderFragment\&. 
.PP
Definition at line \fB52\fP of file \fBInputFileDisplay\&.razor\&.cs\fP\&.
.SS "RenderFragment<\fBIAbsolutePath\fP?>? Luthetus\&.Ide\&.RazorLib\&.InputFiles\&.Displays\&.InputFileDisplay\&.HeaderRenderFragment\fR [get]\fP, \fR [set]\fP"

.PP
Receives the _selectedAbsolutePath as a parameter to the RenderFragment\&. 
.PP
Definition at line \fB46\fP of file \fBInputFileDisplay\&.razor\&.cs\fP\&.
.SS "ElementReference? Luthetus\&.Ide\&.RazorLib\&.InputFiles\&.Displays\&.InputFileDisplay\&.SearchElementReference\fR [get]\fP"

.PP
Definition at line \fB94\fP of file \fBInputFileDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
