.TH "Luthetus.TextEditor.RazorLib.Commands.Models.TextEditorCommandArgs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Commands.Models.TextEditorCommandArgs
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Common\&.RazorLib\&.Commands\&.Models\&.ICommandArgs\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextEditorCommandArgs\fP (\fBResourceUri\fP modelResourceUri, Key< \fBTextEditorViewModel\fP > viewModelKey, \fBTextEditorComponentData\fP componentData, \fBITextEditorService\fP \fBtextEditorService\fP, IServiceProvider serviceProvider, \fBITextEditorEditContext\fP editContext)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBResourceUri\fP \fBModelResourceUri\fP\fR [get]\fP"
.br
.ti -1c
.RI "Key< \fBTextEditorViewModel\fP > \fBViewModelKey\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBTextEditorComponentData\fP \fBComponentData\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBITextEditorService\fP \fBTextEditorService\fP\fR [get]\fP"
.br
.ti -1c
.RI "IServiceProvider \fBServiceProvider\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBITextEditorEditContext\fP \fBEditContext\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBShouldSelectText\fP\fR [get, set]\fP"
.br
.RI "Hack for Defaults\&.TextEditorCommandDefaultFacts\&.GoToMatchingCharacterFactory(bool) to be able to select text\&. (2023-12-15)\&. "
.ti -1c
.RI "\fBTextEditorCommand\fP \fBInnerCommand\fP\fR [get, set]\fP"
.br
.RI "Hack for Vims\&.TextEditorCommandVimFacts\&.Motions\&.GetVisual(TextEditorCommand, string) to be able to select text\&. (2023-12-15)\&. "
.ti -1c
.RI "string \fBDisplayName\fP\fR [get, set]\fP"
.br
.RI "Hack for Vims\&.TextEditorCommandVimFacts\&.Motions\&.GetVisual(TextEditorCommand, string) to be able to select text\&. (2023-12-15)\&. "
.ti -1c
.RI "bool \fBShiftKey\fP\fR [get, set]\fP"
.br
.RI "true if the shift key was down when the event was fired\&. false otherwise\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBTextEditorCommandArgs\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.TextEditorCommandArgs\&.TextEditorCommandArgs (\fBResourceUri\fP modelResourceUri, Key< \fBTextEditorViewModel\fP > viewModelKey, \fBTextEditorComponentData\fP componentData, \fBITextEditorService\fP textEditorService, IServiceProvider serviceProvider, \fBITextEditorEditContext\fP editContext)"

.PP
Definition at line \fB11\fP of file \fBTextEditorCommandArgs\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBTextEditorComponentData\fP Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.TextEditorCommandArgs\&.ComponentData\fR [get]\fP"

.PP
Definition at line \fB29\fP of file \fBTextEditorCommandArgs\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.TextEditorCommandArgs\&.DisplayName\fR [get]\fP, \fR [set]\fP"

.PP
Hack for Vims\&.TextEditorCommandVimFacts\&.Motions\&.GetVisual(TextEditorCommand, string) to be able to select text\&. (2023-12-15)\&. 
.PP
Definition at line \fB48\fP of file \fBTextEditorCommandArgs\&.cs\fP\&.
.SS "\fBITextEditorEditContext\fP Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.TextEditorCommandArgs\&.EditContext\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB32\fP of file \fBTextEditorCommandArgs\&.cs\fP\&.
.SS "\fBTextEditorCommand\fP Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.TextEditorCommandArgs\&.InnerCommand\fR [get]\fP, \fR [set]\fP"

.PP
Hack for Vims\&.TextEditorCommandVimFacts\&.Motions\&.GetVisual(TextEditorCommand, string) to be able to select text\&. (2023-12-15)\&. 
.PP
Definition at line \fB43\fP of file \fBTextEditorCommandArgs\&.cs\fP\&.
.SS "\fBResourceUri\fP Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.TextEditorCommandArgs\&.ModelResourceUri\fR [get]\fP"

.PP
Definition at line \fB27\fP of file \fBTextEditorCommandArgs\&.cs\fP\&.
.SS "IServiceProvider Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.TextEditorCommandArgs\&.ServiceProvider\fR [get]\fP"

.PP
Definition at line \fB31\fP of file \fBTextEditorCommandArgs\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.TextEditorCommandArgs\&.ShiftKey\fR [get]\fP, \fR [set]\fP"

.PP
true if the shift key was down when the event was fired\&. false otherwise\&. 
.PP
Definition at line \fB52\fP of file \fBTextEditorCommandArgs\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.TextEditorCommandArgs\&.ShouldSelectText\fR [get]\fP, \fR [set]\fP"

.PP
Hack for Defaults\&.TextEditorCommandDefaultFacts\&.GoToMatchingCharacterFactory(bool) to be able to select text\&. (2023-12-15)\&. 
.PP
Definition at line \fB38\fP of file \fBTextEditorCommandArgs\&.cs\fP\&.
.SS "\fBITextEditorService\fP Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.TextEditorCommandArgs\&.TextEditorService\fR [get]\fP"

.PP
Definition at line \fB30\fP of file \fBTextEditorCommandArgs\&.cs\fP\&.
.SS "Key<\fBTextEditorViewModel\fP> Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.TextEditorCommandArgs\&.ViewModelKey\fR [get]\fP"

.PP
Definition at line \fB28\fP of file \fBTextEditorCommandArgs\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
