.TH "Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.PreprocessorLibraryReferenceStatementNode" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.PreprocessorLibraryReferenceStatementNode
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.Interfaces\&.IStatementNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPreprocessorLibraryReferenceStatementNode\fP (\fBISyntaxToken\fP includeDirectiveSyntaxToken, \fBISyntaxToken\fP libraryReferenceSyntaxToken)"
.br
.ti -1c
.RI "\fBISyntax\fP[] \fBGetChildList\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBISyntaxToken\fP \fBIncludeDirectiveSyntaxToken\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBISyntaxToken\fP \fBLibraryReferenceSyntaxToken\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsFabricated\fP\fR [get]\fP"
.br
.RI "\fBIsFabricated\fP refers to when the ParserSession expected a node to be valid, but it wasn't\&.
.br

.br
For example, a function invocation on an undefined function will construct a BoundFunctionInvocationNode with \fBIsFabricated\fP set to true\&. "
.ti -1c
.RI "\fBSyntaxKind\fP \fBSyntaxKind\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBPreprocessorLibraryReferenceStatementNode\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.PreprocessorLibraryReferenceStatementNode\&.PreprocessorLibraryReferenceStatementNode (\fBISyntaxToken\fP includeDirectiveSyntaxToken, \fBISyntaxToken\fP libraryReferenceSyntaxToken)"

.PP
Definition at line \fB8\fP of file \fBPreprocessorLibraryReferenceStatementNode\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBISyntax\fP[] Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.PreprocessorLibraryReferenceStatementNode\&.GetChildList ()"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.ISyntaxNode\fP\&.
.PP
Definition at line \fB25\fP of file \fBPreprocessorLibraryReferenceStatementNode\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBISyntaxToken\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.PreprocessorLibraryReferenceStatementNode\&.IncludeDirectiveSyntaxToken\fR [get]\fP"

.PP
Definition at line \fB19\fP of file \fBPreprocessorLibraryReferenceStatementNode\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.PreprocessorLibraryReferenceStatementNode\&.IsFabricated\fR [get]\fP"

.PP
\fBIsFabricated\fP refers to when the ParserSession expected a node to be valid, but it wasn't\&.
.br

.br
For example, a function invocation on an undefined function will construct a BoundFunctionInvocationNode with \fBIsFabricated\fP set to true\&. 
.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.ISyntax\fP\&.
.PP
Definition at line \fB22\fP of file \fBPreprocessorLibraryReferenceStatementNode\&.cs\fP\&.
.SS "\fBISyntaxToken\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.PreprocessorLibraryReferenceStatementNode\&.LibraryReferenceSyntaxToken\fR [get]\fP"

.PP
Definition at line \fB20\fP of file \fBPreprocessorLibraryReferenceStatementNode\&.cs\fP\&.
.SS "\fBSyntaxKind\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.PreprocessorLibraryReferenceStatementNode\&.SyntaxKind\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.ISyntax\fP\&.
.PP
Definition at line \fB23\fP of file \fBPreprocessorLibraryReferenceStatementNode\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
