.TH "Luthetus.TextEditor.RazorLib.Diffs.Models" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Diffs.Models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDiffPresentationFacts\fP"
.br
.ti -1c
.RI "interface \fBITextEditorDiffApi\fP"
.br
.ti -1c
.RI "class \fBTextEditorDiffApi\fP"
.br
.ti -1c
.RI "class \fBTextEditorDiffCell\fP"
.br
.ti -1c
.RI "class \fBTextEditorDiffDecorationMapper\fP"
.br
.ti -1c
.RI "class \fBTextEditorDiffModelModifier\fP"
.br
.ti -1c
.RI "class \fBTextEditorDiffResult\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBTextEditorDiffDecorationKind\fP { \fBNone\fP, \fBLongestCommonSubsequence\fP, \fBInsertion\fP, \fBInsertionLine\fP, \fBDeletion\fP, \fBModification\fP }"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "record \fBTextEditorDiffModel\fP (Key< TextEditorDiffModel > DiffKey, Key< \fBTextEditorViewModel\fP > InViewModelKey, Key< \fBTextEditorViewModel\fP > OutViewModelKey)"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBLuthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.TextEditorDiffDecorationKind\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BINone \fP
.TP
\f(BILongestCommonSubsequence \fP
.TP
\f(BIInsertion \fP
.TP
\f(BIInsertionLine \fP
.TP
\f(BIDeletion \fP
.TP
\f(BIModification \fP
.PP
Definition at line \fB3\fP of file \fBTextEditorDiffDecorationKind\&.cs\fP\&.
.SH "Function Documentation"
.PP 
.SS "record Luthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.TextEditorDiffModel (Key< TextEditorDiffModel > DiffKey, Key< \fBTextEditorViewModel\fP > InViewModelKey, Key< \fBTextEditorViewModel\fP > OutViewModelKey)"

.PP
Definition at line \fB7\fP of file \fBTextEditorDiffModel\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
