.TH "Luthetus.Common.Tests.Basis.FileSystems.FileSystemsTestsHelper.WellKnownPaths" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.FileSystems.FileSystemsTestsHelper.WellKnownPaths
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDirectories\fP"
.br
.ti -1c
.RI "class \fBFiles\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB105\fP of file \fBFileSystemsTestsHelper\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
