.TH "Luthetus.TextEditor.RazorLib.Options.Displays.TextEditorSettingsPreview" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Options.Displays.TextEditorSettingsPreview
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase\&.
.SS "Static Public Attributes"

.in +1c
.ti -1c
.RI "static readonly Key< \fBTextEditorViewModel\fP > \fBSettingsPreviewTextEditorViewModelKey\fP = Key<\fBTextEditorViewModel\fP>\&.NewKey()"
.br
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override async Task \fBOnAfterRenderAsync\fP (bool firstRender)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBTopLevelDivElementCssClassString\fP = string\&.Empty\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBInputElementCssClassString\fP = string\&.Empty\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBLabelElementCssClassString\fP = string\&.Empty\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBPreviewElementCssClassString\fP = string\&.Empty\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBTextEditorSettingsPreview\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override async Task Luthetus\&.TextEditor\&.RazorLib\&.Options\&.Displays\&.TextEditorSettingsPreview\&.OnAfterRenderAsync (bool firstRender)\fR [protected]\fP"

.PP
Definition at line \fB34\fP of file \fBTextEditorSettingsPreview\&.razor\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly Key<\fBTextEditorViewModel\fP> Luthetus\&.TextEditor\&.RazorLib\&.Options\&.Displays\&.TextEditorSettingsPreview\&.SettingsPreviewTextEditorViewModelKey = Key<\fBTextEditorViewModel\fP>\&.NewKey()\fR [static]\fP"

.PP
Definition at line \fB23\fP of file \fBTextEditorSettingsPreview\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.Options\&.Displays\&.TextEditorSettingsPreview\&.InputElementCssClassString = string\&.Empty\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB17\fP of file \fBTextEditorSettingsPreview\&.razor\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.Options\&.Displays\&.TextEditorSettingsPreview\&.LabelElementCssClassString = string\&.Empty\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB19\fP of file \fBTextEditorSettingsPreview\&.razor\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.Options\&.Displays\&.TextEditorSettingsPreview\&.PreviewElementCssClassString = string\&.Empty\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB21\fP of file \fBTextEditorSettingsPreview\&.razor\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.Options\&.Displays\&.TextEditorSettingsPreview\&.TopLevelDivElementCssClassString = string\&.Empty\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB15\fP of file \fBTextEditorSettingsPreview\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
