.TH "Luthetus.Extensions.DotNet.DotNetSolutions.States" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.DotNetSolutions.States
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "partial record \fBDotNetSolutionState\fP (\fBKey\fP< \fBDotNetSolutionModel\fP >? DotNetSolutionModelKey, int IsExecutingAsyncTaskLinks)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "partial record Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.States\&.DotNetSolutionState (\fBKey\fP< \fBDotNetSolutionModel\fP >? DotNetSolutionModelKey, int IsExecutingAsyncTaskLinks)"

.PP
Definition at line \fB14\fP of file \fBDotNetSolutionState\&.Main\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
