.TH "Luthetus.Ide.RazorLib.FileSystems.Displays.TreeViewAbsolutePathDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.FileSystems.Displays.TreeViewAbsolutePathDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase, and \fBLuthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.ITreeViewAbsolutePathRendererType\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBTreeViewContainer\fP \fBTreeViewState\fP = null!\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBSearchQuery\fP = string\&.Empty\fR [get, set]\fP"
.br
.ti -1c
.RI "List<(Key< \fBTreeViewContainer\fP > treeViewStateKey, \fBTreeViewAbsolutePath\fP treeViewAbsolutePath)>? \fBSearchMatchTuples\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "TreeViewAbsolutePath \fBTreeViewAbsolutePath\fP = null!\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBTreeViewAbsolutePathDisplay\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "List<(Key<\fBTreeViewContainer\fP> treeViewStateKey, \fBTreeViewAbsolutePath\fP treeViewAbsolutePath)>? Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Displays\&.TreeViewAbsolutePathDisplay\&.SearchMatchTuples\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB16\fP of file \fBTreeViewAbsolutePathDisplay\&.razor\&.cs\fP\&.
.SS "string Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Displays\&.TreeViewAbsolutePathDisplay\&.SearchQuery = string\&.Empty\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB14\fP of file \fBTreeViewAbsolutePathDisplay\&.razor\&.cs\fP\&.
.SS "TreeViewAbsolutePath Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Displays\&.TreeViewAbsolutePathDisplay\&.TreeViewAbsolutePath = null!\fR [get]\fP, \fR [set]\fP"

.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.ITreeViewAbsolutePathRendererType\fP\&.
.PP
Definition at line \fB19\fP of file \fBTreeViewAbsolutePathDisplay\&.razor\&.cs\fP\&.
.SS "\fBTreeViewContainer\fP Luthetus\&.Ide\&.RazorLib\&.FileSystems\&.Displays\&.TreeViewAbsolutePathDisplay\&.TreeViewState = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB12\fP of file \fBTreeViewAbsolutePathDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
