.TH "Luthetus.Ide.RazorLib.Menus.Models.IMenuOptionsFactory" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.Menus.Models.IMenuOptionsFactory
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.MenuOptionsFactory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMenuOptionRecord\fP \fBNewEmptyFile\fP (\fBIAbsolutePath\fP parentDirectory, Func< Task > onAfterCompletion)"
.br
.ti -1c
.RI "\fBMenuOptionRecord\fP \fBNewTemplatedFile\fP (\fBNamespacePath\fP parentDirectory, Func< Task > onAfterCompletion)"
.br
.ti -1c
.RI "\fBMenuOptionRecord\fP \fBNewDirectory\fP (\fBIAbsolutePath\fP parentDirectory, Func< Task > onAfterCompletion)"
.br
.ti -1c
.RI "\fBMenuOptionRecord\fP \fBDeleteFile\fP (\fBIAbsolutePath\fP absolutePath, Func< Task > onAfterCompletion)"
.br
.ti -1c
.RI "\fBMenuOptionRecord\fP \fBCopyFile\fP (\fBIAbsolutePath\fP absolutePath, Func< Task > onAfterCompletion)"
.br
.ti -1c
.RI "\fBMenuOptionRecord\fP \fBCutFile\fP (\fBIAbsolutePath\fP absolutePath, Func< Task > onAfterCompletion)"
.br
.ti -1c
.RI "\fBMenuOptionRecord\fP \fBRenameFile\fP (\fBIAbsolutePath\fP sourceAbsolutePath, IDispatcher dispatcher, Func< Task > onAfterCompletion)"
.br
.ti -1c
.RI "\fBMenuOptionRecord\fP \fBPasteClipboard\fP (\fBIAbsolutePath\fP directoryAbsolutePath, Func< Task > onAfterCompletion)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBIMenuOptionsFactory\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBMenuOptionRecord\fP Luthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.IMenuOptionsFactory\&.CopyFile (\fBIAbsolutePath\fP absolutePath, Func< Task > onAfterCompletion)"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.MenuOptionsFactory\fP\&.
.SS "\fBMenuOptionRecord\fP Luthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.IMenuOptionsFactory\&.CutFile (\fBIAbsolutePath\fP absolutePath, Func< Task > onAfterCompletion)"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.MenuOptionsFactory\fP\&.
.SS "\fBMenuOptionRecord\fP Luthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.IMenuOptionsFactory\&.DeleteFile (\fBIAbsolutePath\fP absolutePath, Func< Task > onAfterCompletion)"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.MenuOptionsFactory\fP\&.
.SS "\fBMenuOptionRecord\fP Luthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.IMenuOptionsFactory\&.NewDirectory (\fBIAbsolutePath\fP parentDirectory, Func< Task > onAfterCompletion)"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.MenuOptionsFactory\fP\&.
.SS "\fBMenuOptionRecord\fP Luthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.IMenuOptionsFactory\&.NewEmptyFile (\fBIAbsolutePath\fP parentDirectory, Func< Task > onAfterCompletion)"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.MenuOptionsFactory\fP\&.
.SS "\fBMenuOptionRecord\fP Luthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.IMenuOptionsFactory\&.NewTemplatedFile (\fBNamespacePath\fP parentDirectory, Func< Task > onAfterCompletion)"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.MenuOptionsFactory\fP\&.
.SS "\fBMenuOptionRecord\fP Luthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.IMenuOptionsFactory\&.PasteClipboard (\fBIAbsolutePath\fP directoryAbsolutePath, Func< Task > onAfterCompletion)"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.MenuOptionsFactory\fP\&.
.SS "\fBMenuOptionRecord\fP Luthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.IMenuOptionsFactory\&.RenameFile (\fBIAbsolutePath\fP sourceAbsolutePath, IDispatcher dispatcher, Func< Task > onAfterCompletion)"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.MenuOptionsFactory\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
