.TH "Luthetus.Common.Tests.Basis.TreeViews.States.TreeViewStateReducerTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.TreeViews.States.TreeViewStateReducerTests \- TreeViewState\&.Reducer  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBReduceRegisterContainerAction\fP ()"
.br
.RI "TreeViewState\&.Reducer\&.ReduceRegisterContainerAction(TreeViewState, TreeViewState\&.RegisterContainerAction) "
.ti -1c
.RI "void \fBReduceDisposeContainerAction\fP ()"
.br
.RI "TreeViewState\&.Reducer\&.ReduceDisposeContainerAction(TreeViewState, TreeViewState\&.DisposeContainerAction) "
.ti -1c
.RI "void \fBReduceWithRootNodeAction\fP ()"
.br
.RI "TreeViewState\&.Reducer\&.ReduceWithRootNodeAction(TreeViewState, TreeViewState\&.WithRootNodeAction) "
.ti -1c
.RI "void \fBReduceAddChildNodeAction\fP ()"
.br
.RI "TreeViewState\&.Reducer\&.ReduceAddChildNodeAction(TreeViewState, TreeViewState\&.AddChildNodeAction) "
.ti -1c
.RI "void \fBReduceReRenderNodeAction\fP ()"
.br
.RI "TreeViewState\&.Reducer\&.ReduceReRenderNodeAction(TreeViewState, TreeViewState\&.ReRenderNodeAction) "
.ti -1c
.RI "void \fBReduceSetActiveNodeAction\fP ()"
.br
.RI "TreeViewState\&.Reducer\&.ReduceSetActiveNodeAction(TreeViewState, TreeViewState\&.SetActiveNodeAction) "
.ti -1c
.RI "void \fBReduceAddSelectedNodeAction\fP ()"
.br
.RI "TreeViewState\&.Reducer\&.ReduceAddSelectedNodeAction(TreeViewState, TreeViewState\&.AddSelectedNodeAction) "
.ti -1c
.RI "void \fBReduceRemoveSelectedNodeAction\fP ()"
.br
.RI "TreeViewState\&.Reducer\&.ReduceRemoveSelectedNodeAction(TreeViewState, TreeViewState\&.RemoveSelectedNodeAction) "
.ti -1c
.RI "void \fBReduceClearSelectedNodeListAction\fP ()"
.br
.RI "TreeViewState\&.Reducer\&.ReduceClearSelectedNodeListAction(TreeViewState, TreeViewState\&.ClearSelectedNodeListAction) "
.ti -1c
.RI "void \fBReduceMoveLeftAction\fP ()"
.br
.RI "TreeViewState\&.Reducer\&.ReduceMoveLeftAction(TreeViewState, TreeViewState\&.MoveLeftAction) "
.ti -1c
.RI "void \fBReduceMoveDownAction\fP ()"
.br
.RI "TreeViewState\&.Reducer\&.ReduceMoveDownAction(TreeViewState, TreeViewState\&.MoveDownAction) "
.ti -1c
.RI "void \fBReduceMoveUpAction\fP ()"
.br
.RI "TreeViewState\&.Reducer\&.ReduceMoveUpAction(TreeViewState, TreeViewState\&.MoveUpAction) "
.ti -1c
.RI "void \fBReduceMoveRightAction\fP ()"
.br
.RI "TreeViewState\&.Reducer\&.ReduceMoveRightAction(TreeViewState, TreeViewState\&.MoveRightAction) "
.ti -1c
.RI "void \fBReduceMoveHomeAction\fP ()"
.br
.RI "TreeViewState\&.Reducer\&.ReduceMoveHomeAction(TreeViewState, TreeViewState\&.MoveHomeAction) "
.ti -1c
.RI "void \fBReduceMoveEndAction\fP ()"
.br
.RI "TreeViewState\&.Reducer\&.ReduceMoveEndAction(TreeViewState, TreeViewState\&.MoveEndAction) "
.in -1c
.SH "Detailed Description"
.PP 
TreeViewState\&.Reducer 
.PP
Definition at line \fB8\fP of file \fBTreeViewStateTests\&.Reducer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.States\&.TreeViewStateReducerTests\&.ReduceAddChildNodeAction ()"

.PP
TreeViewState\&.Reducer\&.ReduceAddChildNodeAction(TreeViewState, TreeViewState\&.AddChildNodeAction) 
.PP
Definition at line \fB41\fP of file \fBTreeViewStateTests\&.Reducer\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.States\&.TreeViewStateReducerTests\&.ReduceAddSelectedNodeAction ()"

.PP
TreeViewState\&.Reducer\&.ReduceAddSelectedNodeAction(TreeViewState, TreeViewState\&.AddSelectedNodeAction) 
.PP
Definition at line \fB68\fP of file \fBTreeViewStateTests\&.Reducer\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.States\&.TreeViewStateReducerTests\&.ReduceClearSelectedNodeListAction ()"

.PP
TreeViewState\&.Reducer\&.ReduceClearSelectedNodeListAction(TreeViewState, TreeViewState\&.ClearSelectedNodeListAction) 
.PP
Definition at line \fB86\fP of file \fBTreeViewStateTests\&.Reducer\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.States\&.TreeViewStateReducerTests\&.ReduceDisposeContainerAction ()"

.PP
TreeViewState\&.Reducer\&.ReduceDisposeContainerAction(TreeViewState, TreeViewState\&.DisposeContainerAction) 
.PP
Definition at line \fB23\fP of file \fBTreeViewStateTests\&.Reducer\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.States\&.TreeViewStateReducerTests\&.ReduceMoveDownAction ()"

.PP
TreeViewState\&.Reducer\&.ReduceMoveDownAction(TreeViewState, TreeViewState\&.MoveDownAction) 
.PP
Definition at line \fB104\fP of file \fBTreeViewStateTests\&.Reducer\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.States\&.TreeViewStateReducerTests\&.ReduceMoveEndAction ()"

.PP
TreeViewState\&.Reducer\&.ReduceMoveEndAction(TreeViewState, TreeViewState\&.MoveEndAction) 
.PP
Definition at line \fB140\fP of file \fBTreeViewStateTests\&.Reducer\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.States\&.TreeViewStateReducerTests\&.ReduceMoveHomeAction ()"

.PP
TreeViewState\&.Reducer\&.ReduceMoveHomeAction(TreeViewState, TreeViewState\&.MoveHomeAction) 
.PP
Definition at line \fB131\fP of file \fBTreeViewStateTests\&.Reducer\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.States\&.TreeViewStateReducerTests\&.ReduceMoveLeftAction ()"

.PP
TreeViewState\&.Reducer\&.ReduceMoveLeftAction(TreeViewState, TreeViewState\&.MoveLeftAction) 
.PP
Definition at line \fB95\fP of file \fBTreeViewStateTests\&.Reducer\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.States\&.TreeViewStateReducerTests\&.ReduceMoveRightAction ()"

.PP
TreeViewState\&.Reducer\&.ReduceMoveRightAction(TreeViewState, TreeViewState\&.MoveRightAction) 
.PP
Definition at line \fB122\fP of file \fBTreeViewStateTests\&.Reducer\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.States\&.TreeViewStateReducerTests\&.ReduceMoveUpAction ()"

.PP
TreeViewState\&.Reducer\&.ReduceMoveUpAction(TreeViewState, TreeViewState\&.MoveUpAction) 
.PP
Definition at line \fB113\fP of file \fBTreeViewStateTests\&.Reducer\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.States\&.TreeViewStateReducerTests\&.ReduceRegisterContainerAction ()"

.PP
TreeViewState\&.Reducer\&.ReduceRegisterContainerAction(TreeViewState, TreeViewState\&.RegisterContainerAction) 
.PP
Definition at line \fB14\fP of file \fBTreeViewStateTests\&.Reducer\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.States\&.TreeViewStateReducerTests\&.ReduceRemoveSelectedNodeAction ()"

.PP
TreeViewState\&.Reducer\&.ReduceRemoveSelectedNodeAction(TreeViewState, TreeViewState\&.RemoveSelectedNodeAction) 
.PP
Definition at line \fB77\fP of file \fBTreeViewStateTests\&.Reducer\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.States\&.TreeViewStateReducerTests\&.ReduceReRenderNodeAction ()"

.PP
TreeViewState\&.Reducer\&.ReduceReRenderNodeAction(TreeViewState, TreeViewState\&.ReRenderNodeAction) 
.PP
Definition at line \fB50\fP of file \fBTreeViewStateTests\&.Reducer\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.States\&.TreeViewStateReducerTests\&.ReduceSetActiveNodeAction ()"

.PP
TreeViewState\&.Reducer\&.ReduceSetActiveNodeAction(TreeViewState, TreeViewState\&.SetActiveNodeAction) 
.PP
Definition at line \fB59\fP of file \fBTreeViewStateTests\&.Reducer\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.TreeViews\&.States\&.TreeViewStateReducerTests\&.ReduceWithRootNodeAction ()"

.PP
TreeViewState\&.Reducer\&.ReduceWithRootNodeAction(TreeViewState, TreeViewState\&.WithRootNodeAction) 
.PP
Definition at line \fB32\fP of file \fBTreeViewStateTests\&.Reducer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
