.TH "Luthetus.TextEditor.RazorLib.FindAlls.States" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.FindAlls.States
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "partial record \fBTextEditorFindAllState\fP (string SearchQuery, string StartingDirectoryPath, ImmutableList< \fBTextEditorTextSpan\fP > SearchResultList, \fBProgressBarModel\fP? \fBProgressBarModel\fP)"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "partial record Luthetus\&.TextEditor\&.RazorLib\&.FindAlls\&.States\&.TextEditorFindAllState (string SearchQuery, string StartingDirectoryPath, ImmutableList< \fBTextEditorTextSpan\fP > SearchResultList, \fBProgressBarModel\fP? ProgressBarModel)"
Each instance of the state will share this because the 'with' keyword will copy any private members too\&. This allows us to pause the searching while flushing (as to render the UI)\&.

.PP
Each instance of the state will share this cancellation token source because the 'with' keyword will copy any private members too, and CancellationTokenSource is a reference type\&.
.PP
Definition at line \fB11\fP of file \fBTextEditorFindAllState\&.Main\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
