.TH "Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static void \fBDoNothingDiscard\fP ()"
.br
.ti -1c
.RI "static async Task \fBCopyAsync\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBIClipboardService\fP clipboardService)"
.br
.ti -1c
.RI "static async Task \fBCutAsync\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBIClipboardService\fP clipboardService)"
.br
.ti -1c
.RI "static async Task \fBPasteAsync\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBIClipboardService\fP clipboardService)"
.br
.ti -1c
.RI "static void \fBTriggerSave\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)"
.br
.ti -1c
.RI "static void \fBSelectAll\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)"
.br
.ti -1c
.RI "static void \fBUndo\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)"
.br
.ti -1c
.RI "static void \fBRedo\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)"
.br
.ti -1c
.RI "static void \fBTriggerRemeasure\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBTextEditorCommandArgs\fP commandArgs)"
.br
.ti -1c
.RI "static void \fBScrollLineDown\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)"
.br
.ti -1c
.RI "static void \fBScrollLineUp\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)"
.br
.ti -1c
.RI "static void \fBScrollPageDown\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)"
.br
.ti -1c
.RI "static void \fBScrollPageUp\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)"
.br
.ti -1c
.RI "static void \fBCursorMovePageBottom\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)"
.br
.ti -1c
.RI "static void \fBCursorMovePageTop\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)"
.br
.ti -1c
.RI "static void \fBDuplicate\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)"
.br
.ti -1c
.RI "static void \fBIndentMore\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)"
.br
.ti -1c
.RI "static void \fBIndentLess\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)"
.br
.ti -1c
.RI "static void \fBClearTextSelection\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)"
.br
.ti -1c
.RI "static void \fBNewLineBelow\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)"
.br
.ti -1c
.RI "static void \fBNewLineAbove\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)"
.br
.ti -1c
.RI "static void \fBMoveLineDown\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)"
.br
.ti -1c
.RI "static void \fBMoveLineUp\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)"
.br
.ti -1c
.RI "static void \fBGoToMatchingCharacter\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)"
.br
.ti -1c
.RI "static async Task \fBRelatedFilesQuickPick\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)"
.br
.ti -1c
.RI "static async Task \fBQuickActionsSlashRefactor\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)"
.br
.ti -1c
.RI "static void \fBGoToDefinition\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)"
.br
.ti -1c
.RI "static void \fBShowFindAllDialog\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)"
.br
.ti -1c
.RI "static async Task \fBShowTooltipByCursorPositionAsync\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)"
.br
.ti -1c
.RI "static async Task \fBHandleAfterOnKeyDownAsync\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBKeymapArgs\fP keymapArgs, \fBTextEditorComponentData\fP componentData)"
.br
.RI "The default AfterOnKeyDownAsync will provide syntax highlighting, and autocomplete\&.
.br

.br
The syntax highlighting occurs on ';', whitespace, paste, undo, redo
.br

.br
The autocomplete occurs on LetterOrDigit typed or { Ctrl + Space }\&. Furthermore, the autocomplete is done via IAutocompleteService and the one can provide their own implementation when registering the \fBLuthetus\&.TextEditor\fP services using LuthetusTextEditorConfig\&.AutocompleteServiceFactory\&. "
.ti -1c
.RI "static async Task \fBHandleAfterOnKeyDownRangeAsync\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBKeymapArgs\fP[] batchKeymapArgsList, int batchKeymapArgsListLength, \fBTextEditorComponentData\fP componentData, \fBViewModelDisplayOptions\fP viewModelDisplayOptions)"
.br
.RI "This method was being used in the 'OnKeyDownBatch\&.cs' class, which no longer exists\&. The replacement for 'OnKeyDownBatch\&.cs' is '\fBOnKeyDownLateBatching\&.cs\fP'\&. "
.ti -1c
.RI "static async Task \fBHandleMouseStoppedMovingEventAsync\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, MouseEventArgs mouseEventArgs, \fBTextEditorComponentData\fP componentData, \fBILuthetusTextEditorComponentRenderers\fP textEditorComponentRenderers, \fBResourceUri\fP \fBresourceUri\fP)"
.br
.ti -1c
.RI "static void \fBShowDropdown\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCursorModifier\fP primaryCursor, IDispatcher \fBdispatcher\fP, double? leftOffset, double? topOffset, Type componentType, Dictionary< string, object?>? componentParameters)"
.br
.RI "If left or top is left as null, it will be set to whatever the primary cursor's left or top is respectively\&. The left and top values are offsets from the text editor's bounding client rect\&. "
.ti -1c
.RI "static void \fBRemoveDropdown\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorViewModelModifier\fP viewModelModifier, IDispatcher \fBdispatcher\fP)"
.br
.ti -1c
.RI "static void \fBShowContextMenu\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCursorModifier\fP primaryCursor, IDispatcher \fBdispatcher\fP, \fBTextEditorComponentData\fP componentData)"
.br
.ti -1c
.RI "static void \fBShowAutocompleteMenu\fP (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCursorModifier\fP primaryCursor, IDispatcher \fBdispatcher\fP, \fBTextEditorComponentData\fP componentData)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB37\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.ClearTextSelection (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)\fR [static]\fP"

.PP
Definition at line \fB436\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "async Task Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.CopyAsync (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBIClipboardService\fP clipboardService)\fR [static]\fP"

.PP
Definition at line \fB44\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.CursorMovePageBottom (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)\fR [static]\fP"

.PP
Definition at line \fB220\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.CursorMovePageTop (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)\fR [static]\fP"

.PP
Definition at line \fB239\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "async Task Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.CutAsync (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBIClipboardService\fP clipboardService)\fR [static]\fP"

.PP
Definition at line \fB60\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.DoNothingDiscard ()\fR [static]\fP"

.PP
Definition at line \fB39\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.Duplicate (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)\fR [static]\fP"

.PP
Definition at line \fB257\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.GoToDefinition (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)\fR [static]\fP"

.PP
Definition at line \fB1027\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.GoToMatchingCharacter (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)\fR [static]\fP"

.PP
Definition at line \fB655\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "async Task Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.HandleAfterOnKeyDownAsync (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBKeymapArgs\fP keymapArgs, \fBTextEditorComponentData\fP componentData)\fR [static]\fP"

.PP
The default AfterOnKeyDownAsync will provide syntax highlighting, and autocomplete\&.
.br

.br
The syntax highlighting occurs on ';', whitespace, paste, undo, redo
.br

.br
The autocomplete occurs on LetterOrDigit typed or { Ctrl + Space }\&. Furthermore, the autocomplete is done via IAutocompleteService and the one can provide their own implementation when registering the \fBLuthetus\&.TextEditor\fP services using LuthetusTextEditorConfig\&.AutocompleteServiceFactory\&. 
.PP
Definition at line \fB1166\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "async Task Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.HandleAfterOnKeyDownRangeAsync (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBKeymapArgs\fP[] batchKeymapArgsList, int batchKeymapArgsListLength, \fBTextEditorComponentData\fP componentData, \fBViewModelDisplayOptions\fP viewModelDisplayOptions)\fR [static]\fP"

.PP
This method was being used in the 'OnKeyDownBatch\&.cs' class, which no longer exists\&. The replacement for 'OnKeyDownBatch\&.cs' is '\fBOnKeyDownLateBatching\&.cs\fP'\&. But, during the replacement process, this method was overlooked\&.

.PP
One would likely want to use this method when appropriate because it permits every batched keyboard event to individually be given a chance to trigger 'HandleAfterOnKeyDownAsyncFactory(\&.\&.\&.)'

.PP
Example: a 'space' keyboard event, batched with the letter 'a' keyboard event\&. Depending on what '\fBOnKeyDownLateBatching\&.cs\fP' does, perhaps it takes the last keyboard event and uses that to fire 'HandleAfterOnKeyDownAsyncFactory(\&.\&.\&.)'\&.

.PP
Well, a 'space' keyboard event would have trigger syntax highlighting to be refreshed\&. Whereas, the letter 'a' keyboard event won't do anything beyond inserting the letter\&. Therefore, the syntax highlighting was erroneously not refreshed due to batching\&. This method is intended to solve this problem, but it was forgotten at some point\&. 
.PP
Definition at line \fB1243\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "async Task Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.HandleMouseStoppedMovingEventAsync (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, MouseEventArgs mouseEventArgs, \fBTextEditorComponentData\fP componentData, \fBILuthetusTextEditorComponentRenderers\fP textEditorComponentRenderers, \fBResourceUri\fP resourceUri)\fR [static]\fP"

.PP
Definition at line \fB1326\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.IndentLess (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)\fR [static]\fP"

.PP
Definition at line \fB348\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.IndentMore (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)\fR [static]\fP"

.PP
Definition at line \fB295\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.MoveLineDown (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)\fR [static]\fP"

.PP
Definition at line \fB544\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.MoveLineUp (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)\fR [static]\fP"

.PP
Definition at line \fB599\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.NewLineAbove (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)\fR [static]\fP"

.PP
Definition at line \fB491\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.NewLineBelow (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)\fR [static]\fP"

.PP
Definition at line \fB447\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "async Task Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.PasteAsync (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBIClipboardService\fP clipboardService)\fR [static]\fP"

.PP
Definition at line \fB89\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "async Task Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.QuickActionsSlashRefactor (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)\fR [static]\fP"

.PP
Definition at line \fB878\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.Redo (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)\fR [static]\fP"

.PP
Definition at line \fB150\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "async Task Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.RelatedFilesQuickPick (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)\fR [static]\fP"

.PP
Definition at line \fB765\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.RemoveDropdown (\fBITextEditorEditContext\fP editContext, \fBTextEditorViewModelModifier\fP viewModelModifier, IDispatcher dispatcher)\fR [static]\fP"

.PP
Definition at line \fB1492\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.ScrollLineDown (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)\fR [static]\fP"

.PP
Definition at line \fB168\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.ScrollLineUp (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)\fR [static]\fP"

.PP
Definition at line \fB181\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.ScrollPageDown (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)\fR [static]\fP"

.PP
Definition at line \fB194\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.ScrollPageUp (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)\fR [static]\fP"

.PP
Definition at line \fB207\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.SelectAll (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)\fR [static]\fP"

.PP
Definition at line \fB127\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.ShowAutocompleteMenu (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCursorModifier\fP primaryCursor, IDispatcher dispatcher, \fBTextEditorComponentData\fP componentData)\fR [static]\fP"

.PP
Definition at line \fB1539\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.ShowContextMenu (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCursorModifier\fP primaryCursor, IDispatcher dispatcher, \fBTextEditorComponentData\fP componentData)\fR [static]\fP"

.PP
Definition at line \fB1506\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.ShowDropdown (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCursorModifier\fP primaryCursor, IDispatcher dispatcher, double? leftOffset, double? topOffset, Type componentType, Dictionary< string, object?>? componentParameters)\fR [static]\fP"

.PP
If left or top is left as null, it will be set to whatever the primary cursor's left or top is respectively\&. The left and top values are offsets from the text editor's bounding client rect\&. Use the method RemoveDropdown to un-render the dropdown programmatically\&. 
.PP
Definition at line \fB1441\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.ShowFindAllDialog (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)\fR [static]\fP"

.PP
Definition at line \fB1123\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "async Task Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.ShowTooltipByCursorPositionAsync (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)\fR [static]\fP"

.PP
Definition at line \fB1133\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.TriggerRemeasure (\fBITextEditorEditContext\fP editContext, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBTextEditorCommandArgs\fP commandArgs)\fR [static]\fP"

.PP
Definition at line \fB160\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.TriggerSave (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)\fR [static]\fP"

.PP
Definition at line \fB102\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFunctions\&.Undo (\fBITextEditorEditContext\fP editContext, \fBTextEditorModelModifier\fP modelModifier, \fBTextEditorViewModelModifier\fP viewModelModifier, \fBCursorModifierBagTextEditor\fP cursorModifierBag, \fBTextEditorCommandArgs\fP commandArgs)\fR [static]\fP"

.PP
Definition at line \fB140\fP of file \fBTextEditorCommandDefaultFunctions\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
