.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.LuthetusDiagnosticBagTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.LuthetusDiagnosticBagTests \- LuthDiagnosticBag  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBGetEnumerator_ClassDefinedMethod\fP ()"
.br
.RI "LuthDiagnosticBag\&.GetEnumerator() "
.ti -1c
.RI "void \fBGetEnumerator_ExplicitInterfaceImplementation\fP ()"
.br
.RI "LuthDiagnosticBag\&.GetEnumerator() "
.ti -1c
.RI "void \fBReportEndOfFileUnexpected\fP ()"
.br
.RI "LuthDiagnosticBag\&.ReportEndOfFileUnexpected(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan) "
.ti -1c
.RI "void \fBReportUnexpectedToken_A\fP ()"
.br
.RI "LuthDiagnosticBag\&.ReportUnexpectedToken(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan, string, string) "
.ti -1c
.RI "void \fBReportUnexpectedToken_B\fP ()"
.br
.RI "LuthDiagnosticBag\&.ReportUnexpectedToken(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan, string) "
.ti -1c
.RI "void \fBReportUndefinedClass\fP ()"
.br
.RI "LuthDiagnosticBag\&.ReportUndefinedClass(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan, string) "
.ti -1c
.RI "void \fBReportUndefinedTypeOrNamespace\fP ()"
.br
.RI "LuthDiagnosticBag\&.ReportUndefinedTypeOrNamespace(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan, string) "
.ti -1c
.RI "void \fBReportAlreadyDefinedType\fP ()"
.br
.RI "LuthDiagnosticBag\&.ReportAlreadyDefinedType(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan, string) "
.ti -1c
.RI "void \fBReportUndefinedVariable\fP ()"
.br
.RI "LuthDiagnosticBag\&.ReportUndefinedVariable(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan, string) "
.ti -1c
.RI "void \fBReportAlreadyDefinedVariable\fP ()"
.br
.RI "LuthDiagnosticBag\&.ReportAlreadyDefinedVariable(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan, string) "
.ti -1c
.RI "void \fBReportAlreadyDefinedProperty\fP ()"
.br
.RI "LuthDiagnosticBag\&.ReportAlreadyDefinedProperty(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan, string) "
.ti -1c
.RI "void \fBReportUndefinedFunction\fP ()"
.br
.RI "LuthDiagnosticBag\&.ReportUndefinedFunction(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan, string) "
.ti -1c
.RI "void \fBReportAlreadyDefinedFunction\fP ()"
.br
.RI "LuthDiagnosticBag\&.ReportAlreadyDefinedFunction(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan, string) "
.ti -1c
.RI "void \fBReportBadFunctionOptionalArgumentDueToMismatchInType\fP ()"
.br
.RI "LuthDiagnosticBag\&.ReportBadFunctionOptionalArgumentDueToMismatchInType(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan, string, string, string) "
.ti -1c
.RI "void \fBReportReturnStatementsAreStillBeingImplemented\fP ()"
.br
.RI "LuthDiagnosticBag\&.ReportReturnStatementsAreStillBeingImplemented(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan) "
.ti -1c
.RI "void \fBReportTagNameMissing\fP ()"
.br
.RI "LuthDiagnosticBag\&.ReportTagNameMissing(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan) "
.ti -1c
.RI "void \fBReportOpenTagWithUnMatchedCloseTag\fP ()"
.br
.RI "LuthDiagnosticBag\&.ReportOpenTagWithUnMatchedCloseTag(string, string, RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan) "
.ti -1c
.RI "void \fBReportRazorExplicitExpressionPredicateWasExpected\fP ()"
.br
.RI "LuthDiagnosticBag\&.ReportRazorExplicitExpressionPredicateWasExpected(string, string, RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan) "
.ti -1c
.RI "void \fBReportRazorCodeBlockWasExpectedToFollowRazorKeyword\fP ()"
.br
.RI "LuthDiagnosticBag\&.ReportRazorCodeBlockWasExpectedToFollowRazorKeyword(string, string, RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan) "
.ti -1c
.RI "void \fBReportRazorWhitespaceImmediatelyFollowingTransitionCharacterIsUnexpected\fP ()"
.br
.RI "LuthDiagnosticBag\&.ReportRazorWhitespaceImmediatelyFollowingTransitionCharacterIsUnexpected(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan) "
.ti -1c
.RI "void \fBReportConstructorsNeedToBeWithinTypeDefinition\fP ()"
.br
.RI "LuthDiagnosticBag\&.ReportConstructorsNeedToBeWithinTypeDefinition(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan) "
.ti -1c
.RI "void \fBReportTodoException\fP ()"
.br
.RI "LuthDiagnosticBag\&.ReportTodoException(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan, string) "
.ti -1c
.RI "void \fBClearByResourceUri\fP ()"
.br
.RI "LuthDiagnosticBag\&.ClearByResourceUri(RazorLib\&.Lexes\&.Models\&.ResourceUri) "
.in -1c
.SH "Detailed Description"
.PP 
LuthDiagnosticBag 
.PP
Definition at line \fB6\fP of file \fBLuthetusDiagnosticBagTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.LuthetusDiagnosticBagTests\&.ClearByResourceUri ()"

.PP
LuthDiagnosticBag\&.ClearByResourceUri(RazorLib\&.Lexes\&.Models\&.ResourceUri) 
.PP
Definition at line \fB212\fP of file \fBLuthetusDiagnosticBagTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.LuthetusDiagnosticBagTests\&.GetEnumerator_ClassDefinedMethod ()"

.PP
LuthDiagnosticBag\&.GetEnumerator() 
.PP
Definition at line \fB12\fP of file \fBLuthetusDiagnosticBagTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.LuthetusDiagnosticBagTests\&.GetEnumerator_ExplicitInterfaceImplementation ()"

.PP
LuthDiagnosticBag\&.GetEnumerator() 
.PP
Definition at line \fB22\fP of file \fBLuthetusDiagnosticBagTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.LuthetusDiagnosticBagTests\&.ReportAlreadyDefinedFunction ()"

.PP
LuthDiagnosticBag\&.ReportAlreadyDefinedFunction(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan, string) 
.PP
Definition at line \fB122\fP of file \fBLuthetusDiagnosticBagTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.LuthetusDiagnosticBagTests\&.ReportAlreadyDefinedProperty ()"

.PP
LuthDiagnosticBag\&.ReportAlreadyDefinedProperty(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan, string) 
.PP
Definition at line \fB104\fP of file \fBLuthetusDiagnosticBagTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.LuthetusDiagnosticBagTests\&.ReportAlreadyDefinedType ()"

.PP
LuthDiagnosticBag\&.ReportAlreadyDefinedType(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan, string) 
.PP
Definition at line \fB77\fP of file \fBLuthetusDiagnosticBagTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.LuthetusDiagnosticBagTests\&.ReportAlreadyDefinedVariable ()"

.PP
LuthDiagnosticBag\&.ReportAlreadyDefinedVariable(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan, string) 
.PP
Definition at line \fB95\fP of file \fBLuthetusDiagnosticBagTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.LuthetusDiagnosticBagTests\&.ReportBadFunctionOptionalArgumentDueToMismatchInType ()"

.PP
LuthDiagnosticBag\&.ReportBadFunctionOptionalArgumentDueToMismatchInType(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan, string, string, string) 
.PP
Definition at line \fB131\fP of file \fBLuthetusDiagnosticBagTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.LuthetusDiagnosticBagTests\&.ReportConstructorsNeedToBeWithinTypeDefinition ()"

.PP
LuthDiagnosticBag\&.ReportConstructorsNeedToBeWithinTypeDefinition(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan) 
.PP
Definition at line \fB194\fP of file \fBLuthetusDiagnosticBagTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.LuthetusDiagnosticBagTests\&.ReportEndOfFileUnexpected ()"

.PP
LuthDiagnosticBag\&.ReportEndOfFileUnexpected(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan) 
.PP
Definition at line \fB32\fP of file \fBLuthetusDiagnosticBagTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.LuthetusDiagnosticBagTests\&.ReportOpenTagWithUnMatchedCloseTag ()"

.PP
LuthDiagnosticBag\&.ReportOpenTagWithUnMatchedCloseTag(string, string, RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan) 
.PP
Definition at line \fB158\fP of file \fBLuthetusDiagnosticBagTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.LuthetusDiagnosticBagTests\&.ReportRazorCodeBlockWasExpectedToFollowRazorKeyword ()"

.PP
LuthDiagnosticBag\&.ReportRazorCodeBlockWasExpectedToFollowRazorKeyword(string, string, RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan) 
.PP
Definition at line \fB176\fP of file \fBLuthetusDiagnosticBagTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.LuthetusDiagnosticBagTests\&.ReportRazorExplicitExpressionPredicateWasExpected ()"

.PP
LuthDiagnosticBag\&.ReportRazorExplicitExpressionPredicateWasExpected(string, string, RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan) 
.PP
Definition at line \fB167\fP of file \fBLuthetusDiagnosticBagTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.LuthetusDiagnosticBagTests\&.ReportRazorWhitespaceImmediatelyFollowingTransitionCharacterIsUnexpected ()"

.PP
LuthDiagnosticBag\&.ReportRazorWhitespaceImmediatelyFollowingTransitionCharacterIsUnexpected(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan) 
.PP
Definition at line \fB185\fP of file \fBLuthetusDiagnosticBagTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.LuthetusDiagnosticBagTests\&.ReportReturnStatementsAreStillBeingImplemented ()"

.PP
LuthDiagnosticBag\&.ReportReturnStatementsAreStillBeingImplemented(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan) 
.PP
Definition at line \fB140\fP of file \fBLuthetusDiagnosticBagTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.LuthetusDiagnosticBagTests\&.ReportTagNameMissing ()"

.PP
LuthDiagnosticBag\&.ReportTagNameMissing(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan) 
.PP
Definition at line \fB149\fP of file \fBLuthetusDiagnosticBagTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.LuthetusDiagnosticBagTests\&.ReportTodoException ()"

.PP
LuthDiagnosticBag\&.ReportTodoException(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan, string) 
.PP
Definition at line \fB203\fP of file \fBLuthetusDiagnosticBagTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.LuthetusDiagnosticBagTests\&.ReportUndefinedClass ()"

.PP
LuthDiagnosticBag\&.ReportUndefinedClass(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan, string) 
.PP
Definition at line \fB59\fP of file \fBLuthetusDiagnosticBagTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.LuthetusDiagnosticBagTests\&.ReportUndefinedFunction ()"

.PP
LuthDiagnosticBag\&.ReportUndefinedFunction(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan, string) 
.PP
Definition at line \fB113\fP of file \fBLuthetusDiagnosticBagTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.LuthetusDiagnosticBagTests\&.ReportUndefinedTypeOrNamespace ()"

.PP
LuthDiagnosticBag\&.ReportUndefinedTypeOrNamespace(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan, string) 
.PP
Definition at line \fB68\fP of file \fBLuthetusDiagnosticBagTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.LuthetusDiagnosticBagTests\&.ReportUndefinedVariable ()"

.PP
LuthDiagnosticBag\&.ReportUndefinedVariable(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan, string) 
.PP
Definition at line \fB86\fP of file \fBLuthetusDiagnosticBagTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.LuthetusDiagnosticBagTests\&.ReportUnexpectedToken_A ()"

.PP
LuthDiagnosticBag\&.ReportUnexpectedToken(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan, string, string) 
.PP
Definition at line \fB41\fP of file \fBLuthetusDiagnosticBagTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.LuthetusDiagnosticBagTests\&.ReportUnexpectedToken_B ()"

.PP
LuthDiagnosticBag\&.ReportUnexpectedToken(RazorLib\&.Lexes\&.Models\&.TextEditorTextSpan, string) 
.PP
Definition at line \fB50\fP of file \fBLuthetusDiagnosticBagTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
