.TH "Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.IGenericSyntax" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.IGenericSyntax
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericCommentMultiLineSyntax\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericCommentSingleLineSyntax\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericDeliminationExtendedSyntax\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericDocumentSyntax\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericFunctionSyntax\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericKeywordSyntax\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericPreprocessorDirectiveSyntax\fP, and \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericStringSyntax\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBTextEditorTextSpan\fP \fBTextSpan\fP\fR [get]\fP"
.br
.ti -1c
.RI "ImmutableArray< \fBIGenericSyntax\fP > \fBChildList\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBGenericSyntaxKind\fP \fBGenericSyntaxKind\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBIGenericSyntax\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "ImmutableArray<\fBIGenericSyntax\fP> Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.IGenericSyntax\&.ChildList\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericCommentMultiLineSyntax\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericCommentSingleLineSyntax\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericDeliminationExtendedSyntax\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericDocumentSyntax\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericFunctionSyntax\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericKeywordSyntax\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericPreprocessorDirectiveSyntax\fP, and \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericStringSyntax\fP\&.
.PP
Definition at line \fB10\fP of file \fBIGenericSyntax\&.cs\fP\&.
.SS "\fBGenericSyntaxKind\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.IGenericSyntax\&.GenericSyntaxKind\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericCommentMultiLineSyntax\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericCommentSingleLineSyntax\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericDeliminationExtendedSyntax\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericDocumentSyntax\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericFunctionSyntax\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericKeywordSyntax\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericPreprocessorDirectiveSyntax\fP, and \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericStringSyntax\fP\&.
.PP
Definition at line \fB11\fP of file \fBIGenericSyntax\&.cs\fP\&.
.SS "\fBTextEditorTextSpan\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.IGenericSyntax\&.TextSpan\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericCommentMultiLineSyntax\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericCommentSingleLineSyntax\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericDeliminationExtendedSyntax\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericDocumentSyntax\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericFunctionSyntax\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericKeywordSyntax\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericPreprocessorDirectiveSyntax\fP, and \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.SyntaxObjects\&.GenericStringSyntax\fP\&.
.PP
Definition at line \fB9\fP of file \fBIGenericSyntax\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
