.TH "Luthetus.Common.Tests.Basis.Options.Models.AppOptionsServiceTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Options.Models.AppOptionsServiceTests \- \fBAppOptionsService\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "AppOptionsService(IState<AppOptionsState>, IState<ThemeState>, IDispatcher, IStorageService, StorageSync) 
.br
----
.br
 \fBAppOptionsService\&.AppOptionsStateWrap\fP \fBAppOptionsService\&.StorageKey\fP \fBAppOptionsService\&.ThemeCssClassString\fP \fBAppOptionsService\&.FontSizeCssStyleString\fP "
.ti -1c
.RI "void \fBSetActiveThemeRecordKey\fP ()"
.br
.RI "AppOptionsService\&.SetActiveThemeRecordKey(Key<ThemeRecord>, bool) "
.ti -1c
.RI "void \fBSetTheme\fP ()"
.br
.RI "\fBAppOptionsService\&.SetTheme(ThemeRecord, bool)\fP "
.ti -1c
.RI "void \fBSetFontFamily\fP ()"
.br
.RI "\fBAppOptionsService\&.SetFontFamily(string?, bool)\fP "
.ti -1c
.RI "void \fBSetFontSize\fP ()"
.br
.RI "\fBAppOptionsService\&.SetFontSize(int, bool)\fP "
.ti -1c
.RI "void \fBSetIconSize\fP ()"
.br
.RI "\fBAppOptionsService\&.SetIconSize(int, bool)\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBAppOptionsService\fP 
.PP
Definition at line \fB16\fP of file \fBAppOptionsServiceTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Options\&.Models\&.AppOptionsServiceTests\&.Constructor ()"

.PP
AppOptionsService(IState<AppOptionsState>, IState<ThemeState>, IDispatcher, IStorageService, StorageSync) 
.br
----
.br
 \fBAppOptionsService\&.AppOptionsStateWrap\fP \fBAppOptionsService\&.StorageKey\fP \fBAppOptionsService\&.ThemeCssClassString\fP \fBAppOptionsService\&.FontSizeCssStyleString\fP 
.PP
Definition at line \fB27\fP of file \fBAppOptionsServiceTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Options\&.Models\&.AppOptionsServiceTests\&.SetActiveThemeRecordKey ()"

.PP
AppOptionsService\&.SetActiveThemeRecordKey(Key<ThemeRecord>, bool) 
.PP
Definition at line \fB42\fP of file \fBAppOptionsServiceTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Options\&.Models\&.AppOptionsServiceTests\&.SetFontFamily ()"

.PP
\fBAppOptionsService\&.SetFontFamily(string?, bool)\fP 
.PP
Definition at line \fB90\fP of file \fBAppOptionsServiceTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Options\&.Models\&.AppOptionsServiceTests\&.SetFontSize ()"

.PP
\fBAppOptionsService\&.SetFontSize(int, bool)\fP 
.PP
Definition at line \fB107\fP of file \fBAppOptionsServiceTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Options\&.Models\&.AppOptionsServiceTests\&.SetIconSize ()"

.PP
\fBAppOptionsService\&.SetIconSize(int, bool)\fP 
.PP
Definition at line \fB122\fP of file \fBAppOptionsServiceTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Options\&.Models\&.AppOptionsServiceTests\&.SetTheme ()"

.PP
\fBAppOptionsService\&.SetTheme(ThemeRecord, bool)\fP 
.PP
Definition at line \fB66\fP of file \fBAppOptionsServiceTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
