.TH "Luthetus.TextEditor.RazorLib.Options.Displays.InputTextEditorTheme" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Options.Displays.InputTextEditorTheme
.SH SYNOPSIS
.br
.PP
.PP
Inherits FluxorComponent\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "InputViewModel \fBInputViewModel\fP = \fBInputViewModel\&.Empty\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB12\fP of file \fBInputTextEditorTheme\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "InputViewModel Luthetus\&.TextEditor\&.RazorLib\&.Options\&.Displays\&.InputTextEditorTheme\&.InputViewModel = \fBInputViewModel\&.Empty\fP\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB22\fP of file \fBInputTextEditorTheme\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
