.TH "Luthetus.Extensions.Git.Models.GitTreeViewMouseEventHandler" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.Git.Models.GitTreeViewMouseEventHandler
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewMouseEventHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGitTreeViewMouseEventHandler\fP (\fBITreeViewService\fP treeViewService, \fBIBackgroundTaskService\fP backgroundTaskService, IState< \fBGitState\fP > gitStateWrap, IDispatcher dispatcher)"
.br
.in -1c

Public Member Functions inherited from \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewMouseEventHandler\fP
.in +1c
.ti -1c
.RI "\fBTreeViewMouseEventHandler\fP (\fBITreeViewService\fP treeViewService, \fBIBackgroundTaskService\fP backgroundTaskService)"
.br
.ti -1c
.RI "virtual Task \fBOnClickAsync\fP (\fBTreeViewCommandArgs\fP commandArgs)"
.br
.RI "Invoked, and awaited, as part of the async UI event handler for 'onclick' events\&.
.br

.br
\&. "
.ti -1c
.RI "virtual Task \fBOnDoubleClickAsync\fP (\fBTreeViewCommandArgs\fP commandArgs)"
.br
.RI "Invoked, and awaited, as part of the async UI event handler for 'ondblclick' events\&.
.br

.br
\&. "
.ti -1c
.RI "virtual Task \fBOnMouseDownAsync\fP (\fBTreeViewCommandArgs\fP commandArgs)"
.br
.RI "Invoked, and awaited, as part of the async UI event handler for 'onmousedown' events\&.
.br

.br
\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnDoubleClick\fP (\fBTreeViewCommandArgs\fP commandArgs)"
.br
.RI "Invoked, and awaited, as part of the synchronous UI event handler for 'ondblclick' events\&.
.br

.br
\&. "
.in -1c

Protected Member Functions inherited from \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewMouseEventHandler\fP
.in +1c
.ti -1c
.RI "virtual void \fBOnClick\fP (\fBTreeViewCommandArgs\fP commandArgs)"
.br
.RI "Invoked, and awaited, as part of the synchronous UI event handler for 'onclick' events\&.
.br

.br
\&. "
.ti -1c
.RI "virtual void \fBOnMouseDown\fP (\fBTreeViewCommandArgs\fP commandArgs)"
.br
.RI "Invoked, and awaited, as part of the synchronous UI event handler for 'onmousedown' events\&.
.br

.br
\&. "
.in -1c
.SS "Additional Inherited Members"


Protected Attributes inherited from \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewMouseEventHandler\fP
.in +1c
.ti -1c
.RI "readonly \fBITreeViewService\fP \fBTreeViewService\fP"
.br
.ti -1c
.RI "readonly \fBIBackgroundTaskService\fP \fBBackgroundTaskService\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB15\fP of file \fBGitTreeViewMouseEventHandler\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Extensions\&.Git\&.Models\&.GitTreeViewMouseEventHandler\&.GitTreeViewMouseEventHandler (\fBITreeViewService\fP treeViewService, \fBIBackgroundTaskService\fP backgroundTaskService, IState< \fBGitState\fP > gitStateWrap, IDispatcher dispatcher)"

.PP
Definition at line \fB20\fP of file \fBGitTreeViewMouseEventHandler\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Luthetus\&.Extensions\&.Git\&.Models\&.GitTreeViewMouseEventHandler\&.OnDoubleClick (\fBTreeViewCommandArgs\fP commandArgs)\fR [protected]\fP, \fR [virtual]\fP"

.PP
Invoked, and awaited, as part of the synchronous UI event handler for 'ondblclick' events\&.
.br

.br
\&. This method is invoked by the async version: 'OnDoubleClickAsync(TreeViewCommandArgs)'\&.
.br

.br

.PP
Any overrides of this method are intended to have 'base\&.MethodBeingOverridden()' prior to their code, but for this method it makes no difference if one puts it after their code\&.
.br

.br
 
.PP
Reimplemented from \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewMouseEventHandler\fP\&.
.PP
Definition at line \fB31\fP of file \fBGitTreeViewMouseEventHandler\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
