.TH "Luthetus.Common.RazorLib.Dynamics.Models.INotification" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Dynamics.Models.INotification
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDynamicViewModel\fP\&.
.PP
Inherited by \fBLuthetus\&.Common\&.RazorLib\&.Notifications\&.Models\&.NotificationViewModel\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string? \fBNotificationCssClass\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string? \fBNotificationCssStyle\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "TimeSpan? \fBNotificationOverlayLifespan\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBDeleteNotificationAfterOverlayIsDismissed\fP\fR [get]\fP"
.br
.in -1c

Properties inherited from \fBLuthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDynamicViewModel\fP
.in +1c
.ti -1c
.RI "Key< \fBIDynamicViewModel\fP > \fBDynamicViewModelKey\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBTitle\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBTitleVerbose\fP\fR [get]\fP"
.br
.ti -1c
.RI "Type \fBComponentType\fP\fR [get]\fP"
.br
.ti -1c
.RI "Dictionary< string, object?>? \fBComponentParameterMap\fP\fR [get]\fP"
.br
.ti -1c
.RI "string? \fBSetFocusOnCloseElementId\fP\fR [get, set]\fP"
.br
.in -1c
.SS "Additional Inherited Members"


Static Public Attributes inherited from \fBLuthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDynamicViewModel\fP
.in +1c
.ti -1c
.RI "static readonly string \fBDefaultSetFocusOnCloseElementId\fP = ContextFacts\&.GlobalContext\&.ContextElementId"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBINotification\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.INotification\&.DeleteNotificationAfterOverlayIsDismissed\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Notifications\&.Models\&.NotificationViewModel\fP\&.
.PP
Definition at line \fB8\fP of file \fBINotification\&.cs\fP\&.
.SS "string? Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.INotification\&.NotificationCssClass\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Notifications\&.Models\&.NotificationViewModel\fP\&.
.PP
Definition at line \fB5\fP of file \fBINotification\&.cs\fP\&.
.SS "string? Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.INotification\&.NotificationCssStyle\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Notifications\&.Models\&.NotificationViewModel\fP\&.
.PP
Definition at line \fB6\fP of file \fBINotification\&.cs\fP\&.
.SS "TimeSpan? Luthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.INotification\&.NotificationOverlayLifespan\fR [get]\fP"

.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.Notifications\&.Models\&.NotificationViewModel\fP\&.
.PP
Definition at line \fB7\fP of file \fBINotification\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
