.TH "Luthetus.Extensions.DotNet.DotNetSolutions.Models.DotNetSolutionIdeApi" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.DotNetSolutions.Models.DotNetSolutionIdeApi
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBIWithAction\fP"
.br
.RI "Don't have the implementation WithAction as public scope\&. "
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDotNetSolutionIdeApi\fP (\fBIdeBackgroundTaskApi\fP ideBackgroundTaskApi, \fBIBackgroundTaskService\fP backgroundTaskService, \fBIStorageService\fP storageService, \fBIAppDataService\fP appDataService, IState< \fBCompilerServiceExplorerState\fP > compilerServiceExplorerStateWrap, \fBIDotNetComponentRenderers\fP dotNetComponentRenderers, \fBIIdeComponentRenderers\fP ideComponentRenderers, \fBICommonComponentRenderers\fP commonComponentRenderers, \fBITreeViewService\fP treeViewService, IDispatcher \fBdispatcher\fP, \fBIEnvironmentProvider\fP environmentProvider, IState< \fBDotNetSolutionState\fP > dotNetSolutionStateWrap, \fBIFileSystemProvider\fP fileSystemProvider, \fBITextEditorService\fP \fBtextEditorService\fP, \fBICompilerServiceRegistry\fP compilerServiceRegistry, IState< \fBTerminalState\fP > terminalStateWrap, \fBDotNetCliOutputParser\fP dotNetCliOutputParser, IServiceProvider serviceProvider)"
.br
.ti -1c
.RI "void \fBSetDotNetSolution\fP (\fBIAbsolutePath\fP inSolutionAbsolutePath)"
.br
.ti -1c
.RI "void \fBSetDotNetSolutionTreeView\fP (\fBKey\fP< \fBDotNetSolutionModel\fP > dotNetSolutionModelKey)"
.br
.ti -1c
.RI "void \fBWebsite_AddExistingProjectToSolution\fP (\fBKey\fP< \fBDotNetSolutionModel\fP > dotNetSolutionModelKey, string projectTemplateShortName, string cSharpProjectName, \fBIAbsolutePath\fP cSharpProjectAbsolutePath)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "record WithAction(Func< \fBDotNetSolutionState\fP, \fBDotNetSolutionState\fP > WithFunc) static \fBIWithAction\fP \fBConstructModelReplacement\fP (\fBKey\fP< \fBDotNetSolutionModel\fP > dotNetSolutionModelKey, \fBDotNetSolutionModel\fP outDotNetSolutionModel)"
.br
.RI "Don't have WithAction itself as public scope\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB41\fP of file \fBDotNetSolutionIdeApi\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.DotNetSolutionIdeApi\&.DotNetSolutionIdeApi (\fBIdeBackgroundTaskApi\fP ideBackgroundTaskApi, \fBIBackgroundTaskService\fP backgroundTaskService, \fBIStorageService\fP storageService, \fBIAppDataService\fP appDataService, IState< \fBCompilerServiceExplorerState\fP > compilerServiceExplorerStateWrap, \fBIDotNetComponentRenderers\fP dotNetComponentRenderers, \fBIIdeComponentRenderers\fP ideComponentRenderers, \fBICommonComponentRenderers\fP commonComponentRenderers, \fBITreeViewService\fP treeViewService, IDispatcher dispatcher, \fBIEnvironmentProvider\fP environmentProvider, IState< \fBDotNetSolutionState\fP > dotNetSolutionStateWrap, \fBIFileSystemProvider\fP fileSystemProvider, \fBITextEditorService\fP textEditorService, \fBICompilerServiceRegistry\fP compilerServiceRegistry, IState< \fBTerminalState\fP > terminalStateWrap, \fBDotNetCliOutputParser\fP dotNetCliOutputParser, IServiceProvider serviceProvider)"

.PP
Definition at line \fB65\fP of file \fBDotNetSolutionIdeApi\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "record WithAction(Func< \fBDotNetSolutionState\fP, \fBDotNetSolutionState\fP > WithFunc) static \fBIWithAction\fP Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.DotNetSolutionIdeApi\&.ConstructModelReplacement (\fBKey\fP< \fBDotNetSolutionModel\fP > dotNetSolutionModelKey, \fBDotNetSolutionModel\fP outDotNetSolutionModel)\fR [static]\fP"

.PP
Don't have WithAction itself as public scope\&. 
.PP
Definition at line \fB782\fP of file \fBDotNetSolutionIdeApi\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.DotNetSolutionIdeApi\&.SetDotNetSolution (\fBIAbsolutePath\fP inSolutionAbsolutePath)"

.PP
Definition at line \fB106\fP of file \fBDotNetSolutionIdeApi\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.DotNetSolutionIdeApi\&.SetDotNetSolutionTreeView (\fBKey\fP< \fBDotNetSolutionModel\fP > dotNetSolutionModelKey)"

.PP
Definition at line \fB557\fP of file \fBDotNetSolutionIdeApi\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.DotNetSolutionIdeApi\&.Website_AddExistingProjectToSolution (\fBKey\fP< \fBDotNetSolutionModel\fP > dotNetSolutionModelKey, string projectTemplateShortName, string cSharpProjectName, \fBIAbsolutePath\fP cSharpProjectAbsolutePath)"

.PP
Definition at line \fB683\fP of file \fBDotNetSolutionIdeApi\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
