.TH "Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.PresentationAndSelectionDriver" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.PresentationAndSelectionDriver
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBPresentationAndSelectionDriver\fP (\fBTextEditorViewModelDisplay\fP textEditorViewModelDisplay)"
.br
.ti -1c
.RI "RenderFragment \fBGetRenderFragment\fP (\fBTextEditorRenderBatchValidated\fP renderBatch)"
.br
.ti -1c
.RI "List< \fBTextEditorPresentationModel\fP > \fBGetTextEditorPresentationModels\fP (ImmutableList< Key< \fBTextEditorPresentationModel\fP > > textEditorPresentationKeys)"
.br
.ti -1c
.RI "string \fBPresentationGetCssStyleString\fP (int lowerPositionIndexInclusive, int upperPositionIndexExclusive, int rowIndex)"
.br
.ti -1c
.RI "string \fBPresentationGetCssClass\fP (\fBTextEditorPresentationModel\fP presentationModel, byte decorationByte)"
.br
.ti -1c
.RI "ImmutableArray< \fBTextEditorTextSpan\fP > \fBPresentationVirtualizeAndShiftTextSpans\fP (\fBTextEditorTextModification\fP[] textModifications, ImmutableArray< \fBTextEditorTextSpan\fP > inTextSpanList)"
.br
.ti -1c
.RI "int int LastRowToSelectDataExclusive \fBPresentationGetBoundsInRowIndexUnits\fP (\fBTextEditorModel\fP model,(int StartingIndexInclusive, int EndingIndexExclusive) boundsInPositionIndexUnits)"
.br
.ti -1c
.RI "string \fBGetTextSelectionStyleCss\fP (int lowerPositionIndexInclusive, int upperPositionIndexExclusive, int rowIndex)"
.br
.ti -1c
.RI "int int upperRowIndexExclusive \fBGetSelectionBoundsInRowIndexUnits\fP ((int lowerPositionIndexInclusive, int upperPositionIndexExclusive) selectionBoundsInPositionIndexUnits)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly \fBTextEditorViewModelDisplay\fP \fB_root\fP"
.br
.ti -1c
.RI "\fBTextEditorRenderBatchValidated\fP \fB_renderBatch\fP"
.br
.ti -1c
.RI "int \fBFirstRowToSelectDataInclusive\fP"
.br
.ti -1c
.RI "int \fBlowerRowIndexInclusive\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBPresentationAndSelectionDriver\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.PresentationAndSelectionDriver\&.PresentationAndSelectionDriver (\fBTextEditorViewModelDisplay\fP textEditorViewModelDisplay)"

.PP
Definition at line \fB18\fP of file \fBPresentationAndSelectionDriver\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "RenderFragment Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.PresentationAndSelectionDriver\&.GetRenderFragment (\fBTextEditorRenderBatchValidated\fP renderBatch)"

.PP
Definition at line \fB26\fP of file \fBPresentationAndSelectionDriver\&.cs\fP\&.
.SS "int int upperRowIndexExclusive Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.PresentationAndSelectionDriver\&.GetSelectionBoundsInRowIndexUnits ((int lowerPositionIndexInclusive, int upperPositionIndexExclusive) selectionBoundsInPositionIndexUnits)"

.PP
Definition at line \fB376\fP of file \fBPresentationAndSelectionDriver\&.cs\fP\&.
.SS "List< \fBTextEditorPresentationModel\fP > Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.PresentationAndSelectionDriver\&.GetTextEditorPresentationModels (ImmutableList< Key< \fBTextEditorPresentationModel\fP > > textEditorPresentationKeys)"

.PP
Definition at line \fB33\fP of file \fBPresentationAndSelectionDriver\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.PresentationAndSelectionDriver\&.GetTextSelectionStyleCss (int lowerPositionIndexInclusive, int upperPositionIndexExclusive, int rowIndex)"

.PP
Definition at line \fB265\fP of file \fBPresentationAndSelectionDriver\&.cs\fP\&.
.SS "int int LastRowToSelectDataExclusive Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.PresentationAndSelectionDriver\&.PresentationGetBoundsInRowIndexUnits (\fBTextEditorModel\fP model, (int StartingIndexInclusive, int EndingIndexExclusive) boundsInPositionIndexUnits)"

.PP
Definition at line \fB240\fP of file \fBPresentationAndSelectionDriver\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.PresentationAndSelectionDriver\&.PresentationGetCssClass (\fBTextEditorPresentationModel\fP presentationModel, byte decorationByte)"

.PP
Definition at line \fB156\fP of file \fBPresentationAndSelectionDriver\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.PresentationAndSelectionDriver\&.PresentationGetCssStyleString (int lowerPositionIndexInclusive, int upperPositionIndexExclusive, int rowIndex)"

.PP
Definition at line \fB54\fP of file \fBPresentationAndSelectionDriver\&.cs\fP\&.
.SS "ImmutableArray< \fBTextEditorTextSpan\fP > Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.PresentationAndSelectionDriver\&.PresentationVirtualizeAndShiftTextSpans (\fBTextEditorTextModification\fP[] textModifications, ImmutableArray< \fBTextEditorTextSpan\fP > inTextSpanList)"

.PP
Definition at line \fB161\fP of file \fBPresentationAndSelectionDriver\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBTextEditorRenderBatchValidated\fP Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.PresentationAndSelectionDriver\&._renderBatch"

.PP
Definition at line \fB24\fP of file \fBPresentationAndSelectionDriver\&.cs\fP\&.
.SS "readonly \fBTextEditorViewModelDisplay\fP Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.PresentationAndSelectionDriver\&._root"

.PP
Definition at line \fB16\fP of file \fBPresentationAndSelectionDriver\&.cs\fP\&.
.SS "int Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.PresentationAndSelectionDriver\&.FirstRowToSelectDataInclusive"

.PP
Definition at line \fB240\fP of file \fBPresentationAndSelectionDriver\&.cs\fP\&.
.SS "int Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.PresentationAndSelectionDriver\&.lowerRowIndexInclusive"

.PP
Definition at line \fB376\fP of file \fBPresentationAndSelectionDriver\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
