.TH "Luthetus.Ide.RazorLib.BackgroundTasks.Models.IdeBackgroundTaskApi" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.BackgroundTasks.Models.IdeBackgroundTaskApi
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBIdeBackgroundTaskApi\fP (\fBIBackgroundTaskService\fP backgroundTaskService, \fBIStorageService\fP storageService, \fBICompilerServiceRegistry\fP compilerServiceRegistry, \fBIIdeComponentRenderers\fP ideComponentRenderers, \fBICommonComponentRenderers\fP commonComponentRenderers, \fBITreeViewService\fP treeViewService, IDispatcher dispatcher, \fBIEnvironmentProvider\fP environmentProvider, \fBIFileSystemProvider\fP fileSystemProvider, \fBITextEditorService\fP textEditorService, IState< \fBTerminalState\fP > terminalStateWrap, \fBIDecorationMapperRegistry\fP decorationMapperRegistry, \fBIDialogService\fP dialogService, IJSRuntime jsRuntime, IServiceProvider serviceProvider)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBEditorIdeApi\fP \fBEditor\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBFileSystemIdeApi\fP \fBFileSystem\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBFolderExplorerIdeApi\fP \fBFolderExplorer\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBInputFileIdeApi\fP \fBInputFile\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB21\fP of file \fBIdeBackgroundTaskApi\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Ide\&.RazorLib\&.BackgroundTasks\&.Models\&.IdeBackgroundTaskApi\&.IdeBackgroundTaskApi (\fBIBackgroundTaskService\fP backgroundTaskService, \fBIStorageService\fP storageService, \fBICompilerServiceRegistry\fP compilerServiceRegistry, \fBIIdeComponentRenderers\fP ideComponentRenderers, \fBICommonComponentRenderers\fP commonComponentRenderers, \fBITreeViewService\fP treeViewService, IDispatcher dispatcher, \fBIEnvironmentProvider\fP environmentProvider, \fBIFileSystemProvider\fP fileSystemProvider, \fBITextEditorService\fP textEditorService, IState< \fBTerminalState\fP > terminalStateWrap, \fBIDecorationMapperRegistry\fP decorationMapperRegistry, \fBIDialogService\fP dialogService, IJSRuntime jsRuntime, IServiceProvider serviceProvider)"

.PP
Definition at line \fB38\fP of file \fBIdeBackgroundTaskApi\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBEditorIdeApi\fP Luthetus\&.Ide\&.RazorLib\&.BackgroundTasks\&.Models\&.IdeBackgroundTaskApi\&.Editor\fR [get]\fP"

.PP
Definition at line \fB109\fP of file \fBIdeBackgroundTaskApi\&.cs\fP\&.
.SS "\fBFileSystemIdeApi\fP Luthetus\&.Ide\&.RazorLib\&.BackgroundTasks\&.Models\&.IdeBackgroundTaskApi\&.FileSystem\fR [get]\fP"

.PP
Definition at line \fB110\fP of file \fBIdeBackgroundTaskApi\&.cs\fP\&.
.SS "\fBFolderExplorerIdeApi\fP Luthetus\&.Ide\&.RazorLib\&.BackgroundTasks\&.Models\&.IdeBackgroundTaskApi\&.FolderExplorer\fR [get]\fP"

.PP
Definition at line \fB111\fP of file \fBIdeBackgroundTaskApi\&.cs\fP\&.
.SS "\fBInputFileIdeApi\fP Luthetus\&.Ide\&.RazorLib\&.BackgroundTasks\&.Models\&.IdeBackgroundTaskApi\&.InputFile\fR [get]\fP"

.PP
Definition at line \fB112\fP of file \fBIdeBackgroundTaskApi\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
