.TH "Luthetus.TextEditor.RazorLib.Diffs.Models.TextEditorDiffModelModifier" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Diffs.Models.TextEditorDiffModelModifier
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextEditorDiffModelModifier\fP (\fBTextEditorDiffModel\fP diffModel)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBTextEditorDiffModel\fP \fBDiffModel\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBWasModified\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBTextEditorDiffModelModifier\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.TextEditorDiffModelModifier\&.TextEditorDiffModelModifier (\fBTextEditorDiffModel\fP diffModel)"

.PP
Definition at line \fB5\fP of file \fBTextEditorDiffModelModifier\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBTextEditorDiffModel\fP Luthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.TextEditorDiffModelModifier\&.DiffModel\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB10\fP of file \fBTextEditorDiffModelModifier\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.TextEditorDiffModelModifier\&.WasModified\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB11\fP of file \fBTextEditorDiffModelModifier\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
