.TH "Luthetus.Ide.RazorLib.Terminals.Models.TerminalOutput" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.Terminals.Models.TerminalOutput
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.ITerminalOutput\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTerminalOutput\fP (\fBITerminal\fP terminal)"
.br
.ti -1c
.RI "\fBTerminalOutput\fP (\fBITerminal\fP terminal, \fBITerminalOutputFormatter\fP outputFormatter)"
.br
.ti -1c
.RI "\fBTerminalOutput\fP (\fBITerminal\fP terminal, ImmutableList< \fBITerminalOutputFormatter\fP > outputFormatterList)"
.br
.ti -1c
.RI "\fBITerminalOutputFormatted\fP? \fBGetOutputFormatted\fP (string terminalOutputFormatterName)"
.br
.ti -1c
.RI "\fBTerminalCommandParsed\fP? \fBGetParsedCommandOrDefault\fP (Key< \fBTerminalCommandRequest\fP > terminalCommandRequestKey)"
.br
.ti -1c
.RI "ImmutableList< \fBTerminalCommandParsed\fP > \fBGetParsedCommandList\fP ()"
.br
.ti -1c
.RI "int \fBGetParsedCommandListCount\fP ()"
.br
.ti -1c
.RI "void \fBRegisterOutputFormatterCustom\fP (\fBITerminalOutputFormatter\fP outputFormatter)"
.br
.ti -1c
.RI "void \fBWriteOutput\fP (\fBTerminalCommandParsed\fP terminalCommandParsed, CommandEvent commandEvent)"
.br
.ti -1c
.RI "void \fBClearOutput\fP ()"
.br
.RI "Guaranteed to clear the output\&. "
.ti -1c
.RI "void \fBClearOutputExceptMostRecentCommand\fP ()"
.br
.RI "Guaranteed to clear the output, but will keep the most recent command\&. "
.ti -1c
.RI "void \fBClearHistoryWhenExistingOutputTooLong\fP ()"
.br
.RI "Conditionally clear the output\&. "
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "ImmutableList< \fBITerminalOutputFormatter\fP > \fBOutputFormatterList\fP\fR [get]\fP"
.br
.in -1c
.SS "Events"

.in +1c
.ti -1c
.RI "Action? \fBOnWriteOutput\fP"
.br
.in -1c

Events inherited from \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.ITerminalOutput\fP
.in +1c
.ti -1c
.RI "Action? \fBOnWriteOutput\fP"
.br
.RI "TODO: Make this 'Action<Key<TerminalCommandParsed>>?' so one can track the output of a specific command as it is being executed? "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBTerminalOutput\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutput\&.TerminalOutput (\fBITerminal\fP terminal)"

.PP
Definition at line \fB20\fP of file \fBTerminalOutput\&.cs\fP\&.
.SS "Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutput\&.TerminalOutput (\fBITerminal\fP terminal, \fBITerminalOutputFormatter\fP outputFormatter)"

.PP
Definition at line \fB25\fP of file \fBTerminalOutput\&.cs\fP\&.
.SS "Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutput\&.TerminalOutput (\fBITerminal\fP terminal, ImmutableList< \fBITerminalOutputFormatter\fP > outputFormatterList)"

.PP
Definition at line \fB36\fP of file \fBTerminalOutput\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutput\&.ClearHistoryWhenExistingOutputTooLong ()"

.PP
Conditionally clear the output\&. 
.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.ITerminalOutput\fP\&.
.PP
Definition at line \fB155\fP of file \fBTerminalOutput\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutput\&.ClearOutput ()"

.PP
Guaranteed to clear the output\&. 
.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.ITerminalOutput\fP\&.
.PP
Definition at line \fB127\fP of file \fBTerminalOutput\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutput\&.ClearOutputExceptMostRecentCommand ()"

.PP
Guaranteed to clear the output, but will keep the most recent command\&. 
.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.ITerminalOutput\fP\&.
.PP
Definition at line \fB137\fP of file \fBTerminalOutput\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutput\&.Dispose ()"

.PP
Definition at line \fB184\fP of file \fBTerminalOutput\&.cs\fP\&.
.SS "\fBITerminalOutputFormatted\fP? Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutput\&.GetOutputFormatted (string terminalOutputFormatterName)"

.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.ITerminalOutput\fP\&.
.PP
Definition at line \fB48\fP of file \fBTerminalOutput\&.cs\fP\&.
.SS "ImmutableList< \fBTerminalCommandParsed\fP > Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutput\&.GetParsedCommandList ()"

.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.ITerminalOutput\fP\&.
.PP
Definition at line \fB68\fP of file \fBTerminalOutput\&.cs\fP\&.
.SS "int Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutput\&.GetParsedCommandListCount ()"

.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.ITerminalOutput\fP\&.
.PP
Definition at line \fB76\fP of file \fBTerminalOutput\&.cs\fP\&.
.SS "\fBTerminalCommandParsed\fP? Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutput\&.GetParsedCommandOrDefault (Key< \fBTerminalCommandRequest\fP > terminalCommandRequestKey)"

.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.ITerminalOutput\fP\&.
.PP
Definition at line \fB59\fP of file \fBTerminalOutput\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutput\&.RegisterOutputFormatterCustom (\fBITerminalOutputFormatter\fP outputFormatter)"

.PP
Definition at line \fB84\fP of file \fBTerminalOutput\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutput\&.WriteOutput (\fBTerminalCommandParsed\fP terminalCommandParsed, CommandEvent commandEvent)"

.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.ITerminalOutput\fP\&.
.PP
Definition at line \fB92\fP of file \fBTerminalOutput\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "ImmutableList<\fBITerminalOutputFormatter\fP> Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutput\&.OutputFormatterList\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.ITerminalOutput\fP\&.
.PP
Definition at line \fB44\fP of file \fBTerminalOutput\&.cs\fP\&.
.SH "Event Documentation"
.PP 
.SS "Action? Luthetus\&.Ide\&.RazorLib\&.Terminals\&.Models\&.TerminalOutput\&.OnWriteOutput"

.PP
Definition at line \fB46\fP of file \fBTerminalOutput\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
