.TH "Luthetus.Common.RazorLib.Reflectives.PersonCase.PersonDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Reflectives.PersonCase.PersonDisplay \- \fBPersonDisplay\fP is used from within the unit tests, in order to keep around an un-changing component for the \fBReflectives\fP\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "PersonModel \fBPersonModel\fP = null!\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
\fBPersonDisplay\fP is used from within the unit tests, in order to keep around an un-changing component for the \fBReflectives\fP\&. 
.PP
Definition at line \fB9\fP of file \fBPersonDisplay\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "PersonModel Luthetus\&.Common\&.RazorLib\&.Reflectives\&.PersonCase\&.PersonDisplay\&.PersonModel = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB12\fP of file \fBPersonDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
