.TH "Luthetus.Extensions.Git.Displays.GitOriginDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.Git.Displays.GitOriginDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "Key< \fBTerminalCommandRequest\fP > \fBGitSetOriginTerminalCommandRequestKey\fP = Key<\fBTerminalCommandRequest\fP>\&.NewKey()\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB16\fP of file \fBGitOriginDisplay\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Key<\fBTerminalCommandRequest\fP> Luthetus\&.Extensions\&.Git\&.Displays\&.GitOriginDisplay\&.GitSetOriginTerminalCommandRequestKey = Key<\fBTerminalCommandRequest\fP>\&.NewKey()\fR [get]\fP"

.PP
Definition at line \fB35\fP of file \fBGitOriginDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
