.TH "Luthetus.Extensions.DotNet.DotNetSolutions.Displays.TreeViewSolutionFolderDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.DotNetSolutions.Displays.TreeViewSolutionFolderDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase, and \fBLuthetus\&.Extensions\&.DotNet\&.ComponentRenderers\&.Models\&.ITreeViewSolutionFolderRendererType\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBSolutionFolder\fP \fBDotNetSolutionFolder\fP = null!\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBTreeViewSolutionFolderDisplay\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBSolutionFolder\fP Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Displays\&.TreeViewSolutionFolderDisplay\&.DotNetSolutionFolder = null!\fR [get]\fP, \fR [set]\fP"

.PP
Implements \fBLuthetus\&.Extensions\&.DotNet\&.ComponentRenderers\&.Models\&.ITreeViewSolutionFolderRendererType\fP\&.
.PP
Definition at line \fB15\fP of file \fBTreeViewSolutionFolderDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
