.TH "Luthetus.TextEditor.RazorLib.Diffs.States.TextEditorDiffState" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Diffs.States.TextEditorDiffState
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBReducer\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "record \fBRegisterAction\fP (Key< \fBTextEditorDiffModel\fP > DiffKey, Key< \fBTextEditorViewModel\fP > InViewModelKey, Key< \fBTextEditorViewModel\fP > OutViewModelKey)"
.br
.ti -1c
.RI "record \fBDisposeAction\fP (Key< \fBTextEditorDiffModel\fP > DiffKey)"
.br
.ti -1c
.RI "\fBTextEditorDiffState\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "ImmutableList< \fBTextEditorDiffModel\fP > \fBDiffModelList\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBTextEditorDiffState\&.Actions\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.Diffs\&.States\&.TextEditorDiffState\&.TextEditorDiffState ()"

.PP
Definition at line \fB10\fP of file \fBTextEditorDiffState\&.Main\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "record Luthetus\&.TextEditor\&.RazorLib\&.Diffs\&.States\&.TextEditorDiffState\&.DisposeAction (Key< \fBTextEditorDiffModel\fP > DiffKey)"

.SS "record Luthetus\&.TextEditor\&.RazorLib\&.Diffs\&.States\&.TextEditorDiffState\&.RegisterAction (Key< \fBTextEditorDiffModel\fP > DiffKey, Key< \fBTextEditorViewModel\fP > InViewModelKey, Key< \fBTextEditorViewModel\fP > OutViewModelKey)"

.SH "Property Documentation"
.PP 
.SS "ImmutableList<\fBTextEditorDiffModel\fP> Luthetus\&.TextEditor\&.RazorLib\&.Diffs\&.States\&.TextEditorDiffState\&.DiffModelList\fR [get]\fP"

.PP
Definition at line \fB15\fP of file \fBTextEditorDiffState\&.Main\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
