.TH "Luthetus.Extensions.DotNet.CompilerServices.Models" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.CompilerServices.Models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBCompilerServiceExplorerModel\fP"
.br
.ti -1c
.RI "class \fBCompilerServiceExplorerTreeViewKeyboardEventHandler\fP"
.br
.ti -1c
.RI "class \fBCompilerServiceExplorerTreeViewMouseEventHandler\fP"
.br
.ti -1c
.RI "class \fBCompilerServiceIdeApi\fP"
.br
.ti -1c
.RI "class \fBTreeViewCompilerService\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBCompilerServiceExplorerViewKind\fP { \fBGraphical\fP, \fBTreeView\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBLuthetus\&.Extensions\&.DotNet\&.CompilerServices\&.Models\&.CompilerServiceExplorerViewKind\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BIGraphical \fP
.TP
\f(BITreeView \fP
.PP
Definition at line \fB3\fP of file \fBCompilerServiceExplorerViewKind\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
