.TH "Luthetus.TextEditor.RazorLib.Edits.Models.TextEditorEditInsert" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Edits.Models.TextEditorEditInsert
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.ITextEditorEdit\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextEditorEditInsert\fP (int positionIndex, string content)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBPositionIndex\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBContent\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBTextEditorEditKind\fP \fBEditKind\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBTextEditorEditInsert\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.TextEditorEditInsert\&.TextEditorEditInsert (int positionIndex, string content)"

.PP
Definition at line \fB5\fP of file \fBTextEditorEditInsert\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.TextEditorEditInsert\&.Content\fR [get]\fP"

.PP
Definition at line \fB12\fP of file \fBTextEditorEditInsert\&.cs\fP\&.
.SS "\fBTextEditorEditKind\fP Luthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.TextEditorEditInsert\&.EditKind\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.ITextEditorEdit\fP\&.
.PP
Definition at line \fB14\fP of file \fBTextEditorEditInsert\&.cs\fP\&.
.SS "int Luthetus\&.TextEditor\&.RazorLib\&.Edits\&.Models\&.TextEditorEditInsert\&.PositionIndex\fR [get]\fP"

.PP
Definition at line \fB11\fP of file \fBTextEditorEditInsert\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
