.TH "Luthetus.Common.Tests.Basis.Commands.Models.TreeViewCommandArgsTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Commands.Models.TreeViewCommandArgsTests \- \fBTreeViewCommandArgs\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "TreeViewCommandArgs(ITreeViewService, TreeViewContainer, RazorLib\&.TreeViews\&.Models\&.TreeViewNoType?, Func<Task>, RazorLib\&.JavaScriptObjects\&.Models\&.ContextMenuFixedPosition?, Microsoft\&.AspNetCore\&.Components\&.Web\&.MouseEventArgs?, Microsoft\&.AspNetCore\&.Components\&.Web\&.KeyboardEventArgs?) 
.br
----
.br
 \fBTreeViewCommandArgs\&.TreeViewService\fP \fBTreeViewCommandArgs\&.TreeViewContainer\fP \fBTreeViewCommandArgs\&.NodeThatReceivedMouseEvent\fP \fBTreeViewCommandArgs\&.RestoreFocusToTreeView\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBTreeViewCommandArgs\fP 
.PP
Definition at line \fB16\fP of file \fBTreeViewCommandArgsTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Commands\&.Models\&.TreeViewCommandArgsTests\&.Constructor ()"

.PP
TreeViewCommandArgs(ITreeViewService, TreeViewContainer, RazorLib\&.TreeViews\&.Models\&.TreeViewNoType?, Func<Task>, RazorLib\&.JavaScriptObjects\&.Models\&.ContextMenuFixedPosition?, Microsoft\&.AspNetCore\&.Components\&.Web\&.MouseEventArgs?, Microsoft\&.AspNetCore\&.Components\&.Web\&.KeyboardEventArgs?) 
.br
----
.br
 \fBTreeViewCommandArgs\&.TreeViewService\fP \fBTreeViewCommandArgs\&.TreeViewContainer\fP \fBTreeViewCommandArgs\&.NodeThatReceivedMouseEvent\fP \fBTreeViewCommandArgs\&.RestoreFocusToTreeView\fP 
.PP
Definition at line \fB27\fP of file \fBTreeViewCommandArgsTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
