.TH "Luthetus.Common.RazorLib.JsRuntimes.Models.LuthetusCommonJavaScriptInteropApi" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.JsRuntimes.Models.LuthetusCommonJavaScriptInteropApi
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLuthetusCommonJavaScriptInteropApi\fP (IJSRuntime jsRuntime)"
.br
.ti -1c
.RI "ValueTask \fBSubscribeWindowSizeChanged\fP (DotNetObjectReference< \fBBrowserResizeInterop\fP > browserResizeInteropDotNetObjectReference)"
.br
.ti -1c
.RI "ValueTask \fBDisposeWindowSizeChanged\fP ()"
.br
.ti -1c
.RI "ValueTask \fBFocusHtmlElementById\fP (string elementId, bool preventScroll=false)"
.br
.ti -1c
.RI "ValueTask< bool > \fBTryFocusHtmlElementById\fP (string elementId)"
.br
.ti -1c
.RI "ValueTask< \fBMeasuredHtmlElementDimensions\fP > \fBMeasureElementById\fP (string elementId)"
.br
.ti -1c
.RI "ValueTask \fBLocalStorageSetItem\fP (string key, object? value)"
.br
.ti -1c
.RI "ValueTask< string?> \fBLocalStorageGetItem\fP (string key)"
.br
.ti -1c
.RI "ValueTask< string > \fBReadClipboard\fP ()"
.br
.ti -1c
.RI "ValueTask \fBSetClipboard\fP (string value)"
.br
.ti -1c
.RI "ValueTask< \fBContextMenuFixedPosition\fP > \fBGetTreeViewContextMenuFixedPosition\fP (string nodeElementId)"
.br
.in -1c
.SH "Detailed Description"
.PP 
This class is an exception to the naming convention, "don't use the word 'Luthetus' in class names"\&.

.PP
Reason for this exception: the 'IJSRuntime' datatype is far more common in code, than some specific type (example: DialogDisplay\&.razor)\&. So, adding '\fBLuthetus\fP' in the class name for redundancy seems meaningful here\&. 
.PP
Definition at line \fB14\fP of file \fBLuthetusCommonJavaScriptInteropApi\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Common\&.RazorLib\&.JsRuntimes\&.Models\&.LuthetusCommonJavaScriptInteropApi\&.LuthetusCommonJavaScriptInteropApi (IJSRuntime jsRuntime)"

.PP
Definition at line \fB18\fP of file \fBLuthetusCommonJavaScriptInteropApi\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "ValueTask Luthetus\&.Common\&.RazorLib\&.JsRuntimes\&.Models\&.LuthetusCommonJavaScriptInteropApi\&.DisposeWindowSizeChanged ()"

.PP
Definition at line \fB30\fP of file \fBLuthetusCommonJavaScriptInteropApi\&.cs\fP\&.
.SS "ValueTask Luthetus\&.Common\&.RazorLib\&.JsRuntimes\&.Models\&.LuthetusCommonJavaScriptInteropApi\&.FocusHtmlElementById (string elementId, bool preventScroll = \fRfalse\fP)"

.PP
Definition at line \fB36\fP of file \fBLuthetusCommonJavaScriptInteropApi\&.cs\fP\&.
.SS "ValueTask< \fBContextMenuFixedPosition\fP > Luthetus\&.Common\&.RazorLib\&.JsRuntimes\&.Models\&.LuthetusCommonJavaScriptInteropApi\&.GetTreeViewContextMenuFixedPosition (string nodeElementId)"

.PP
Definition at line \fB86\fP of file \fBLuthetusCommonJavaScriptInteropApi\&.cs\fP\&.
.SS "ValueTask< string?> Luthetus\&.Common\&.RazorLib\&.JsRuntimes\&.Models\&.LuthetusCommonJavaScriptInteropApi\&.LocalStorageGetItem (string key)"

.PP
Definition at line \fB66\fP of file \fBLuthetusCommonJavaScriptInteropApi\&.cs\fP\&.
.SS "ValueTask Luthetus\&.Common\&.RazorLib\&.JsRuntimes\&.Models\&.LuthetusCommonJavaScriptInteropApi\&.LocalStorageSetItem (string key, object? value)"

.PP
Definition at line \fB58\fP of file \fBLuthetusCommonJavaScriptInteropApi\&.cs\fP\&.
.SS "ValueTask< \fBMeasuredHtmlElementDimensions\fP > Luthetus\&.Common\&.RazorLib\&.JsRuntimes\&.Models\&.LuthetusCommonJavaScriptInteropApi\&.MeasureElementById (string elementId)"

.PP
Definition at line \fB51\fP of file \fBLuthetusCommonJavaScriptInteropApi\&.cs\fP\&.
.SS "ValueTask< string > Luthetus\&.Common\&.RazorLib\&.JsRuntimes\&.Models\&.LuthetusCommonJavaScriptInteropApi\&.ReadClipboard ()"

.PP
Definition at line \fB73\fP of file \fBLuthetusCommonJavaScriptInteropApi\&.cs\fP\&.
.SS "ValueTask Luthetus\&.Common\&.RazorLib\&.JsRuntimes\&.Models\&.LuthetusCommonJavaScriptInteropApi\&.SetClipboard (string value)"

.PP
Definition at line \fB79\fP of file \fBLuthetusCommonJavaScriptInteropApi\&.cs\fP\&.
.SS "ValueTask Luthetus\&.Common\&.RazorLib\&.JsRuntimes\&.Models\&.LuthetusCommonJavaScriptInteropApi\&.SubscribeWindowSizeChanged (DotNetObjectReference< \fBBrowserResizeInterop\fP > browserResizeInteropDotNetObjectReference)"

.PP
Definition at line \fB23\fP of file \fBLuthetusCommonJavaScriptInteropApi\&.cs\fP\&.
.SS "ValueTask< bool > Luthetus\&.Common\&.RazorLib\&.JsRuntimes\&.Models\&.LuthetusCommonJavaScriptInteropApi\&.TryFocusHtmlElementById (string elementId)"

.PP
Definition at line \fB44\fP of file \fBLuthetusCommonJavaScriptInteropApi\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
