.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.GenericLexer" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.GenericLexer
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBDecoration\fP"
.br
.ti -1c
.RI "namespace \fBSyntaxActors\fP"
.br
.ti -1c
.RI "namespace \fBSyntaxObjects\fP"
.br
.in -1c
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBDeliminationExtendedSyntaxDefinitionTests\fP"
.br
.RI "\fBDeliminationExtendedSyntaxDefinition\fP "
.ti -1c
.RI "class \fBGenericLanguageDefinitionTests\fP"
.br
.RI "\fBGenericLanguageDefinition\fP "
.ti -1c
.RI "class \fBGenericPreprocessorDefinitionTests\fP"
.br
.RI "\fBGenericPreprocessorDefinition\fP "
.ti -1c
.RI "class \fBGenericSyntaxUnitTests\fP"
.br
.RI "\fBGenericSyntaxUnit\fP "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
