.TH "Luthetus.Common.RazorLib.FileSystems.Models.IRelativePath" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.FileSystems.Models.IRelativePath \- Given an \fBIRelativePath\fP then \fBAncestorDirectoryList\fP refers to the "\&.\&./Todos/" in "\&.\&./Todos/myFile\&.cs"\&. In this example there is 1 ancestor directory\&.
.br

.br
\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IPath\fP\&.
.PP
Inherited by \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IEnvironmentProvider\&.RelativePath\fP\&.
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static \fBIRelativePath\fP \fBFactory\fP (string path, bool isDirectory, \fBIEnvironmentProvider\fP environmentProvider)"
.br
.RI "One might prefer \fBIEnvironmentProvider\&.RelativePathFactory(string, bool)\fP instead of this method\&.
.br

.br
\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBUpDirDirectiveCount\fP\fR [get]\fP"
.br
.RI "\fBUpDirDirectiveCount\fP refers to the "\&.\&." in "\&.\&./Todos/myFile\&.cs"\&. In this example the count is 1\&. 
.br

.br
 Given "\&./Folder/file\&.txt"\&. The count is 0\&. 
.br

.br
 Given "\&.\&./\&.\&./\&.\&./Homework/math\&.txt"\&. The count is 3\&. "
.in -1c

Properties inherited from \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IPath\fP
.in +1c
.ti -1c
.RI "\fBPathType\fP \fBPathType\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsDirectory\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBNameNoExtension\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBNameWithExtension\fP\fR [get]\fP"
.br
.RI "Given: { "somePath\&.txt", NOT_DIRECTORY }
.br
 Then: \fBNameWithExtension\fP is "somePath\&.txt" 
.br

.br
 Given: { "somePath\&.txt", IS_DIRECTORY }
.br
 Then: \fBNameWithExtension\fP is "somePath\&.txt/" 
.br

.br
 Given: { "somePath", NOT_DIRECTORY }
.br
 Then: \fBNameWithExtension\fP is "somePath" 
.br

.br
 Given: { "somePath", IS_DIRECTORY }
.br
 Then: \fBNameWithExtension\fP is "somePath/" 
.br

.br
 Given: { "somePath/", NOT_DIRECTORY }
.br
 Then: throw new Exception('File names cannot contain directory separators'); 
.br

.br
 Given: { "somePath/", IS_DIRECTORY }
.br
 Then: \fBNameWithExtension\fP is "somePath/"\&. "
.ti -1c
.RI "string \fBExtensionNoPeriod\fP\fR [get]\fP"
.br
.ti -1c
.RI "string? \fBExactInput\fP\fR [get]\fP"
.br
.RI "Given: "/Repos\\\\BlazorCrudApp\\\\"<br/>
Then: <see cref="ExactInput"/> is "/Repos\\BlazorCrudApp\\"<br/><br/>Given: "\\Repos/BlazorCrudApp/"<br/>Then: <see cref="ExactInput"/> is "\\Repos/BlazorCrudApp/"<br/><br/>Overall reasoning: <see cref="ExactInput"/> is to return the user input exactly as they gave it originally\&. "
.ti -1c
.RI "string \fBValue\fP\fR [get]\fP"
.br
.RI "\fBValue\fP is the path as a string, but with all directory separating characters having been standardized to be \fBIEnvironmentProvider\&.DirectorySeparatorChar\fP\&. "
.ti -1c
.RI "\fBAncestorDirectory\fP? \fBParentDirectory\fP\fR [get]\fP"
.br
.ti -1c
.RI "List< \fBAncestorDirectory\fP > \fBAncestorDirectoryList\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBIEnvironmentProvider\fP \fBEnvironmentProvider\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Given an \fBIRelativePath\fP then \fBAncestorDirectoryList\fP refers to the "\&.\&./Todos/" in "\&.\&./Todos/myFile\&.cs"\&. In this example there is 1 ancestor directory\&.
.br

.br
\&. 
.PP
Definition at line \fB7\fP of file \fBIRelativePath\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBIRelativePath\fP Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IRelativePath\&.Factory (string path, bool isDirectory, \fBIEnvironmentProvider\fP environmentProvider)\fR [static]\fP"

.PP
One might prefer \fBIEnvironmentProvider\&.RelativePathFactory(string, bool)\fP instead of this method\&.
.br

.br
\&. This version adds an extra function invocation for no reason\&. To use \fBIEnvironmentProvider\&.RelativePathFactory(string, bool)\fP may be a negligible optimization however\&.
.br

.br

.PP
Keep this method here, it provides more clear documentation on how to create an instance of \fBIRelativePath\fP\&. Having to invoke a method on the \fBIEnvironmentProvider\fP is a bit hard to find\&. 
.PP
Definition at line \fB31\fP of file \fBIRelativePath\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IRelativePath\&.UpDirDirectiveCount\fR [get]\fP"

.PP
\fBUpDirDirectiveCount\fP refers to the "\&.\&." in "\&.\&./Todos/myFile\&.cs"\&. In this example the count is 1\&. 
.br

.br
 Given "\&./Folder/file\&.txt"\&. The count is 0\&. 
.br

.br
 Given "\&.\&./\&.\&./\&.\&./Homework/math\&.txt"\&. The count is 3\&. 
.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IEnvironmentProvider\&.RelativePath\fP\&.
.PP
Definition at line \fB17\fP of file \fBIRelativePath\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
