.TH "Luthetus.CompilerServices.CSharp.ParserCase.ExpressionSession" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.CSharp.ParserCase.ExpressionSession
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBExpressionSession\fP (List< \fBISyntaxToken\fP > tokenList, Stack< \fBISyntax\fP > expressionStack)"
.br
.ti -1c
.RI "void \fBAddShortCircuit\fP ((\fBSyntaxKind\fP DelimiterSyntaxKind, \fBIExpressionNode\fP ExpressionNode) shortCircuit)"
.br
.ti -1c
.RI "void \fBRemoveRangeShortCircuit\fP (int index, int count)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "IReadOnlyList<(\fBSyntaxKind\fP DelimiterSyntaxKind, \fBIExpressionNode\fP ExpressionNode)> \fBShortCircuitList\fP\fR [get]\fP"
.br
.ti -1c
.RI "List< \fBISyntaxToken\fP > \fBTokenList\fP\fR [get]\fP"
.br
.ti -1c
.RI "Stack< \fBISyntax\fP > \fBExpressionStack\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBPosition\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBShortCircuitListStringified\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB13\fP of file \fBExpressionSession\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.ExpressionSession\&.ExpressionSession (List< \fBISyntaxToken\fP > tokenList, Stack< \fBISyntax\fP > expressionStack)"

.PP
Definition at line \fB17\fP of file \fBExpressionSession\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.ExpressionSession\&.AddShortCircuit ((\fBSyntaxKind\fP DelimiterSyntaxKind, \fBIExpressionNode\fP ExpressionNode) shortCircuit)"

.PP
Definition at line \fB49\fP of file \fBExpressionSession\&.cs\fP\&.
.SS "void Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.ExpressionSession\&.RemoveRangeShortCircuit (int index, int count)"

.PP
Definition at line \fB55\fP of file \fBExpressionSession\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Stack<\fBISyntax\fP> Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.ExpressionSession\&.ExpressionStack\fR [get]\fP"

.PP
Definition at line \fB31\fP of file \fBExpressionSession\&.cs\fP\&.
.SS "int Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.ExpressionSession\&.Position\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB32\fP of file \fBExpressionSession\&.cs\fP\&.
.SS "IReadOnlyList<(\fBSyntaxKind\fP DelimiterSyntaxKind, \fBIExpressionNode\fP ExpressionNode)> Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.ExpressionSession\&.ShortCircuitList\fR [get]\fP"

.PP
Definition at line \fB28\fP of file \fBExpressionSession\&.cs\fP\&.
.SS "string Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.ExpressionSession\&.ShortCircuitListStringified\fR [get]\fP"

.PP
Definition at line \fB34\fP of file \fBExpressionSession\&.cs\fP\&.
.SS "List<\fBISyntaxToken\fP> Luthetus\&.CompilerServices\&.CSharp\&.ParserCase\&.ExpressionSession\&.TokenList\fR [get]\fP"

.PP
Definition at line \fB30\fP of file \fBExpressionSession\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
