.TH "Luthetus.Extensions.DotNet.Outputs.Displays.OutputPanelDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.Outputs.Displays.OutputPanelDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase\&.
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBOutputPanelDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
