.TH "Luthetus.TextEditor.RazorLib.Groups.Models.TextEditorGroupApi" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Groups.Models.TextEditorGroupApi
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.TextEditor\&.RazorLib\&.Groups\&.Models\&.ITextEditorGroupApi\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextEditorGroupApi\fP (\fBITextEditorService\fP \fBtextEditorService\fP, IDispatcher \fBdispatcher\fP, \fBIDialogService\fP \fBdialogService\fP, IJSRuntime \fBjsRuntime\fP)"
.br
.ti -1c
.RI "void \fBSetActiveViewModel\fP (Key< TextEditorGroup > textEditorGroupKey, Key< \fBTextEditorViewModel\fP > textEditorViewModelKey)"
.br
.ti -1c
.RI "void \fBRemoveViewModel\fP (Key< TextEditorGroup > textEditorGroupKey, Key< \fBTextEditorViewModel\fP > textEditorViewModelKey)"
.br
.ti -1c
.RI "void \fBRegister\fP (Key< TextEditorGroup > textEditorGroupKey, \fBCategory\fP? \fBcategory\fP=null)"
.br
.ti -1c
.RI "void \fBDispose\fP (Key< TextEditorGroup > textEditorGroupKey)"
.br
.ti -1c
.RI "TextEditorGroup? \fBGetOrDefault\fP (Key< TextEditorGroup > textEditorGroupKey)"
.br
.ti -1c
.RI "void \fBAddViewModel\fP (Key< TextEditorGroup > textEditorGroupKey, Key< \fBTextEditorViewModel\fP > textEditorViewModelKey)"
.br
.ti -1c
.RI "ImmutableList< TextEditorGroup > \fBGetGroups\fP ()"
.br
.RI "One should store the result of invoking this method in a variable, then reference that variable\&. If one continually invokes this, there is no guarantee that the data had not changed since the previous invocation\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBTextEditorGroupApi\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.Groups\&.Models\&.TextEditorGroupApi\&.TextEditorGroupApi (\fBITextEditorService\fP textEditorService, IDispatcher dispatcher, \fBIDialogService\fP dialogService, IJSRuntime jsRuntime)"

.PP
Definition at line \fB18\fP of file \fBTextEditorGroupApi\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Groups\&.Models\&.TextEditorGroupApi\&.AddViewModel (Key< TextEditorGroup > textEditorGroupKey, Key< \fBTextEditorViewModel\fP > textEditorViewModelKey)"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.Groups\&.Models\&.ITextEditorGroupApi\fP\&.
.PP
Definition at line \fB72\fP of file \fBTextEditorGroupApi\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Groups\&.Models\&.TextEditorGroupApi\&.Dispose (Key< TextEditorGroup > textEditorGroupKey)"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.Groups\&.Models\&.ITextEditorGroupApi\fP\&.
.PP
Definition at line \fB61\fP of file \fBTextEditorGroupApi\&.cs\fP\&.
.SS "ImmutableList< TextEditorGroup > Luthetus\&.TextEditor\&.RazorLib\&.Groups\&.Models\&.TextEditorGroupApi\&.GetGroups ()"

.PP
One should store the result of invoking this method in a variable, then reference that variable\&. If one continually invokes this, there is no guarantee that the data had not changed since the previous invocation\&. 
.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.Groups\&.Models\&.ITextEditorGroupApi\fP\&.
.PP
Definition at line \fB79\fP of file \fBTextEditorGroupApi\&.cs\fP\&.
.SS "TextEditorGroup? Luthetus\&.TextEditor\&.RazorLib\&.Groups\&.Models\&.TextEditorGroupApi\&.GetOrDefault (Key< TextEditorGroup > textEditorGroupKey)"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.Groups\&.Models\&.ITextEditorGroupApi\fP\&.
.PP
Definition at line \fB66\fP of file \fBTextEditorGroupApi\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Groups\&.Models\&.TextEditorGroupApi\&.Register (Key< TextEditorGroup > textEditorGroupKey, \fBCategory\fP? category = \fRnull\fP)"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.Groups\&.Models\&.ITextEditorGroupApi\fP\&.
.PP
Definition at line \fB44\fP of file \fBTextEditorGroupApi\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Groups\&.Models\&.TextEditorGroupApi\&.RemoveViewModel (Key< TextEditorGroup > textEditorGroupKey, Key< \fBTextEditorViewModel\fP > textEditorViewModelKey)"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.Groups\&.Models\&.ITextEditorGroupApi\fP\&.
.PP
Definition at line \fB37\fP of file \fBTextEditorGroupApi\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Groups\&.Models\&.TextEditorGroupApi\&.SetActiveViewModel (Key< TextEditorGroup > textEditorGroupKey, Key< \fBTextEditorViewModel\fP > textEditorViewModelKey)"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.Groups\&.Models\&.ITextEditorGroupApi\fP\&.
.PP
Definition at line \fB30\fP of file \fBTextEditorGroupApi\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
