.TH "Luthetus.TextEditor.RazorLib.Installations.Models.FindAllDialogConfig" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Installations.Models.FindAllDialogConfig
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "Type \fBComponentRendererType\fP = typeof(\fBFindAllDisplay\fP)\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBComponentIsResizable\fP = true\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBFindAllDialogConfig\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.Installations\&.Models\&.FindAllDialogConfig\&.ComponentIsResizable = true\fR [get]\fP"

.PP
Definition at line \fB8\fP of file \fBFindAllDialogConfig\&.cs\fP\&.
.SS "Type Luthetus\&.TextEditor\&.RazorLib\&.Installations\&.Models\&.FindAllDialogConfig\&.ComponentRendererType = typeof(\fBFindAllDisplay\fP)\fR [get]\fP"

.PP
Definition at line \fB7\fP of file \fBFindAllDialogConfig\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
