.TH "Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.Lexer" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.Lexer
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.ILexer\fP\&.
.PP
Inherited by \fBLuthetus\&.CompilerServices\&.C\&.CLexer\fP, \fBLuthetus\&.CompilerServices\&.CSharp\&.LexerCase\&.CSharpLexer\fP, \fBLuthetus\&.CompilerServices\&.Css\&.SyntaxActors\&.TextEditorCssLexer\fP, \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.SyntaxActors\&.DotNetSolutionLexer\fP, \fBLuthetus\&.CompilerServices\&.FSharp\&.SyntaxActors\&.TextEditorFSharpLexer\fP, \fBLuthetus\&.CompilerServices\&.JavaScript\&.SyntaxActors\&.TextEditorJavaScriptLexer\fP, \fBLuthetus\&.CompilerServices\&.Json\&.SyntaxActors\&.TextEditorJsonLexer\fP, \fBLuthetus\&.CompilerServices\&.Python\&.PythonLexer\fP, \fBLuthetus\&.CompilerServices\&.Razor\&.RazorLexer\fP, \fBLuthetus\&.CompilerServices\&.TypeScript\&.SyntaxActors\&.TextEditorTypeScriptLexer\fP, and \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.TextEditorXmlLexer\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBLexer\fP (\fBResourceUri\fP resourceUri, string sourceText, \fBLexerKeywords\fP lexerKeywords)"
.br
.ti -1c
.RI "virtual void \fBLex\fP ()"
.br
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "readonly \fBStringWalker\fP \fB_stringWalker\fP"
.br
.ti -1c
.RI "readonly List< \fBISyntaxToken\fP > \fB_syntaxTokenList\fP = new()"
.br
.ti -1c
.RI "readonly \fBDiagnosticBag\fP \fB_diagnosticBag\fP = new()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "ResourceUri \fBResourceUri\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBSourceText\fP\fR [get]\fP"
.br
.ti -1c
.RI "LexerKeywords \fBLexerKeywords\fP\fR [get]\fP"
.br
.ti -1c
.RI "ImmutableArray< \fBISyntaxToken\fP > \fBSyntaxTokenList\fP\fR [get]\fP"
.br
.ti -1c
.RI "ImmutableArray< \fBTextEditorDiagnostic\fP > \fBDiagnosticList\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBLexer\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.Lexer\&.Lexer (\fBResourceUri\fP resourceUri, string sourceText, \fBLexerKeywords\fP lexerKeywords)"

.PP
Definition at line \fB15\fP of file \fBLexer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.Lexer\&.Lex ()\fR [virtual]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.ILexer\fP\&.
.PP
Reimplemented in \fBLuthetus\&.CompilerServices\&.C\&.CLexer\fP, \fBLuthetus\&.CompilerServices\&.CSharp\&.LexerCase\&.CSharpLexer\fP, \fBLuthetus\&.CompilerServices\&.Css\&.SyntaxActors\&.TextEditorCssLexer\fP, \fBLuthetus\&.CompilerServices\&.DotNetSolution\&.SyntaxActors\&.DotNetSolutionLexer\fP, \fBLuthetus\&.CompilerServices\&.FSharp\&.SyntaxActors\&.TextEditorFSharpLexer\fP, \fBLuthetus\&.CompilerServices\&.JavaScript\&.SyntaxActors\&.TextEditorJavaScriptLexer\fP, \fBLuthetus\&.CompilerServices\&.Json\&.SyntaxActors\&.TextEditorJsonLexer\fP, \fBLuthetus\&.CompilerServices\&.Python\&.PythonLexer\fP, \fBLuthetus\&.CompilerServices\&.Razor\&.RazorLexer\fP, \fBLuthetus\&.CompilerServices\&.TypeScript\&.SyntaxActors\&.TextEditorTypeScriptLexer\fP, and \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.SyntaxActors\&.TextEditorXmlLexer\fP\&.
.PP
Definition at line \fB34\fP of file \fBLexer\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBDiagnosticBag\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.Lexer\&._diagnosticBag = new()\fR [protected]\fP"

.PP
Definition at line \fB13\fP of file \fBLexer\&.cs\fP\&.
.SS "readonly \fBStringWalker\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.Lexer\&._stringWalker\fR [protected]\fP"

.PP
Definition at line \fB11\fP of file \fBLexer\&.cs\fP\&.
.SS "readonly List<\fBISyntaxToken\fP> Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.Lexer\&._syntaxTokenList = new()\fR [protected]\fP"

.PP
Definition at line \fB12\fP of file \fBLexer\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "ImmutableArray<\fBTextEditorDiagnostic\fP> Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.Lexer\&.DiagnosticList\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.ILexer\fP\&.
.PP
Definition at line \fB32\fP of file \fBLexer\&.cs\fP\&.
.SS "LexerKeywords Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.Lexer\&.LexerKeywords\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.ILexer\fP\&.
.PP
Definition at line \fB29\fP of file \fBLexer\&.cs\fP\&.
.SS "ResourceUri Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.Lexer\&.ResourceUri\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.ILexer\fP\&.
.PP
Definition at line \fB27\fP of file \fBLexer\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.Lexer\&.SourceText\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.ILexer\fP\&.
.PP
Definition at line \fB28\fP of file \fBLexer\&.cs\fP\&.
.SS "ImmutableArray<\fBISyntaxToken\fP> Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Implementations\&.Lexer\&.SyntaxTokenList\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.ILexer\fP\&.
.PP
Definition at line \fB31\fP of file \fBLexer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
