.TH "Luthetus.Common.RazorLib.Icons.Models" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Icons.Models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBIconBase\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBIconBadgeHorizontalPositionKind\fP { \fBLeft\fP, \fBRight\fP }"
.br
.ti -1c
.RI "enum \fBIconBadgeVerticalPositionKind\fP { \fBTop\fP, \fBBottom\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBLuthetus\&.Common\&.RazorLib\&.Icons\&.Models\&.IconBadgeHorizontalPositionKind\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BILeft \fP
.TP
\f(BIRight \fP
.PP
Definition at line \fB3\fP of file \fBIconBadgeHorizontalPositionKind\&.cs\fP\&.
.SS "enum \fBLuthetus\&.Common\&.RazorLib\&.Icons\&.Models\&.IconBadgeVerticalPositionKind\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BITop \fP
.TP
\f(BIBottom \fP
.PP
Definition at line \fB3\fP of file \fBIconBadgeVerticalPositionKind\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
