.TH "Luthetus.TextEditor.RazorLib.Diffs.Models.TextEditorDiffApi" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Diffs.Models.TextEditorDiffApi
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.ITextEditorDiffApi\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextEditorDiffApi\fP (\fBITextEditorService\fP \fBtextEditorService\fP, IDispatcher \fBdispatcher\fP)"
.br
.ti -1c
.RI "void \fBRegister\fP (Key< \fBTextEditorDiffModel\fP > diffModelKey, Key< \fBTextEditorViewModel\fP > inViewModelKey, Key< \fBTextEditorViewModel\fP > outViewModelKey)"
.br
.ti -1c
.RI "\fBTextEditorDiffModel\fP? \fBGetOrDefault\fP (Key< \fBTextEditorDiffModel\fP > diffModelKey)"
.br
.ti -1c
.RI "void \fBDispose\fP (Key< \fBTextEditorDiffModel\fP > diffModelKey)"
.br
.ti -1c
.RI "Func< \fBITextEditorEditContext\fP, Task > \fBCalculateFactory\fP (Key< \fBTextEditorDiffModel\fP > diffModelKey, CancellationToken cancellationToken)"
.br
.ti -1c
.RI "ImmutableList< \fBTextEditorDiffModel\fP > \fBGetDiffModels\fP ()"
.br
.RI "One should store the result of invoking this method in a variable, then reference that variable\&. If one continually invokes this, there is no guarantee that the data had not changed since the previous invocation\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB9\fP of file \fBTextEditorDiffApi\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.TextEditorDiffApi\&.TextEditorDiffApi (\fBITextEditorService\fP textEditorService, IDispatcher dispatcher)"

.PP
Definition at line \fB14\fP of file \fBTextEditorDiffApi\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "Func< \fBITextEditorEditContext\fP, Task > Luthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.TextEditorDiffApi\&.CalculateFactory (Key< \fBTextEditorDiffModel\fP > diffModelKey, CancellationToken cancellationToken)"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.ITextEditorDiffApi\fP\&.
.PP
Definition at line \fB42\fP of file \fBTextEditorDiffApi\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.TextEditorDiffApi\&.Dispose (Key< \fBTextEditorDiffModel\fP > diffModelKey)"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.ITextEditorDiffApi\fP\&.
.PP
Definition at line \fB37\fP of file \fBTextEditorDiffApi\&.cs\fP\&.
.SS "ImmutableList< \fBTextEditorDiffModel\fP > Luthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.TextEditorDiffApi\&.GetDiffModels ()"

.PP
One should store the result of invoking this method in a variable, then reference that variable\&. If one continually invokes this, there is no guarantee that the data had not changed since the previous invocation\&. 
.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.ITextEditorDiffApi\fP\&.
.PP
Definition at line \fB112\fP of file \fBTextEditorDiffApi\&.cs\fP\&.
.SS "\fBTextEditorDiffModel\fP? Luthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.TextEditorDiffApi\&.GetOrDefault (Key< \fBTextEditorDiffModel\fP > diffModelKey)"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.ITextEditorDiffApi\fP\&.
.PP
Definition at line \fB31\fP of file \fBTextEditorDiffApi\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.TextEditorDiffApi\&.Register (Key< \fBTextEditorDiffModel\fP > diffModelKey, Key< \fBTextEditorViewModel\fP > inViewModelKey, Key< \fBTextEditorViewModel\fP > outViewModelKey)"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.ITextEditorDiffApi\fP\&.
.PP
Definition at line \fB20\fP of file \fBTextEditorDiffApi\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
