.TH "Luthetus.TextEditor.Tests.Basis.Diffs.States.TextEditorDiffStateMainTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.Diffs.States.TextEditorDiffStateMainTests \- \fBTextEditorDiffState\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "TextEditorDiffState() "
.ti -1c
.RI "void \fBDiffModelList\fP ()"
.br
.RI "\fBTextEditorDiffState\&.DiffModelList\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBTextEditorDiffState\fP 
.PP
Definition at line \fB12\fP of file \fBTextEditorDiffState\&.MainTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Diffs\&.States\&.TextEditorDiffStateMainTests\&.Constructor ()"

.PP
TextEditorDiffState() 
.PP
Definition at line \fB18\fP of file \fBTextEditorDiffState\&.MainTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Diffs\&.States\&.TextEditorDiffStateMainTests\&.DiffModelList ()"

.PP
\fBTextEditorDiffState\&.DiffModelList\fP 
.PP
Definition at line \fB28\fP of file \fBTextEditorDiffState\&.MainTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
