.TH "Luthetus.Ide.Tests.Basis.Gits.Models.GitFileTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.Tests.Basis.Gits.Models.GitFileTests \- GitFile  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBAbsolutePath\fP ()"
.br
.RI "GitFile\&.AbsolutePath "
.ti -1c
.RI "void \fBGitDirtyReason\fP ()"
.br
.RI "GitFile\&.GitDirtyReason "
.ti -1c
.RI "void \fBIsDirty\fP ()"
.br
.RI "GitFile\&.IsDirty "
.ti -1c
.RI "void \fBUnixFileSystemShouldParseProperly\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
GitFile 
.PP
Definition at line \fB8\fP of file \fBGitFileTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.Gits\&.Models\&.GitFileTests\&.AbsolutePath ()"

.PP
GitFile\&.AbsolutePath 
.PP
Definition at line \fB14\fP of file \fBGitFileTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.Gits\&.Models\&.GitFileTests\&.GitDirtyReason ()"

.PP
GitFile\&.GitDirtyReason 
.PP
Definition at line \fB23\fP of file \fBGitFileTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.Gits\&.Models\&.GitFileTests\&.IsDirty ()"

.PP
GitFile\&.IsDirty 
.PP
Definition at line \fB32\fP of file \fBGitFileTests\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.Gits\&.Models\&.GitFileTests\&.UnixFileSystemShouldParseProperly ()"

.PP
Definition at line \fB38\fP of file \fBGitFileTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
