.TH "Luthetus.Ide.Tests.Basis.IdeTestBase" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.Tests.Basis.IdeTestBase
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.Ide\&.Tests\&.Basis\&.TreeViewImplementations\&.Models\&.TreeViewAbsolutePathTests\fP, \fBLuthetus\&.Ide\&.Tests\&.Basis\&.TreeViewImplementations\&.Models\&.TreeViewGitFileTests\fP, \fBLuthetus\&.Ide\&.Tests\&.Basis\&.TreeViewImplementations\&.Models\&.TreeViewMarkupStringTests\fP, and \fBLuthetus\&.Ide\&.Tests\&.Basis\&.TreeViewImplementations\&.Models\&.TreeViewSpinnerTests\fP\&.
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTest_WellKnownPaths\fP"
.br
.in -1c
.SS "Static Protected Member Functions"

.in +1c
.ti -1c
.RI "static void \fBTest_RegisterServices\fP (out ServiceProvider serviceProvider)"
.br
.ti -1c
.RI "static void \fBTest_CreateFileSystem\fP (IServiceProvider serviceProvider)"
.br
.RI "The files shown in the 'tree' below will be written to the in-memory filesystem\&. ---------------------------------------------
.br
 Root
.br
 ∙└───Homework
.br
 ∙∙∙∙∙∙├───Math
.br
 ∙∙∙∙∙∙│∙∙∙∙├───addition\&.txt
.br
 ∙∙∙∙∙∙│∙∙∙∙└───subtraction\&.txt
.br
 ∙∙∙∙∙∙│
.br
 ∙∙∙∙∙∙└───Biology
.br
 ∙∙∙∙∙∙∙∙∙∙∙├───nervousSystem\&.txt
.br
 ∙∙∙∙∙∙∙∙∙∙∙└───skeletalSystem\&.txt
.br
\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB14\fP of file \fBIdeTestBase\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.IdeTestBase\&.Test_CreateFileSystem (IServiceProvider serviceProvider)\fR [static]\fP, \fR [protected]\fP"

.PP
The files shown in the 'tree' below will be written to the in-memory filesystem\&. ---------------------------------------------
.br
 Root
.br
 ∙└───Homework
.br
 ∙∙∙∙∙∙├───Math
.br
 ∙∙∙∙∙∙│∙∙∙∙├───addition\&.txt
.br
 ∙∙∙∙∙∙│∙∙∙∙└───subtraction\&.txt
.br
 ∙∙∙∙∙∙│
.br
 ∙∙∙∙∙∙└───Biology
.br
 ∙∙∙∙∙∙∙∙∙∙∙├───nervousSystem\&.txt
.br
 ∙∙∙∙∙∙∙∙∙∙∙└───skeletalSystem\&.txt
.br
\&. 
.PP
Definition at line \fB62\fP of file \fBIdeTestBase\&.cs\fP\&.
.SS "void Luthetus\&.Ide\&.Tests\&.Basis\&.IdeTestBase\&.Test_RegisterServices (out ServiceProvider serviceProvider)\fR [static]\fP, \fR [protected]\fP"

.PP
Definition at line \fB16\fP of file \fBIdeTestBase\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
