.TH "Luthetus.Tutorials.RazorLib.CompilerServices.CompilerServiceRegistry" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Tutorials.RazorLib.CompilerServices.CompilerServiceRegistry
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.ICompilerServiceRegistry\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCompilerServiceRegistry\fP (\fBITextEditorService\fP \fBtextEditorService\fP)"
.br
.ti -1c
.RI "\fBICompilerService\fP \fBGetCompilerService\fP (string extensionNoPeriod)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "ImmutableDictionary< string, \fBICompilerService\fP > \fBMap\fP\fR [get]\fP"
.br
.ti -1c
.RI "ImmutableList< \fBICompilerService\fP > \fBCompilerServiceList\fP\fR [get]\fP"
.br
.ti -1c
.RI "CSharpCompilerService \fBCSharpCompilerService\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBCompilerService\fP \fBDefaultCompilerService\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB12\fP of file \fBCompilerServiceRegistry\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Tutorials\&.RazorLib\&.CompilerServices\&.CompilerServiceRegistry\&.CompilerServiceRegistry (\fBITextEditorService\fP textEditorService)"

.PP
Definition at line \fB19\fP of file \fBCompilerServiceRegistry\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBICompilerService\fP Luthetus\&.Tutorials\&.RazorLib\&.CompilerServices\&.CompilerServiceRegistry\&.GetCompilerService (string extensionNoPeriod)"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.ICompilerServiceRegistry\fP\&.
.PP
Definition at line \fB30\fP of file \fBCompilerServiceRegistry\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "ImmutableList<\fBICompilerService\fP> Luthetus\&.Tutorials\&.RazorLib\&.CompilerServices\&.CompilerServiceRegistry\&.CompilerServiceList\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Interfaces\&.ICompilerServiceRegistry\fP\&.
.PP
Definition at line \fB17\fP of file \fBCompilerServiceRegistry\&.cs\fP\&.
.SS "CSharpCompilerService Luthetus\&.Tutorials\&.RazorLib\&.CompilerServices\&.CompilerServiceRegistry\&.CSharpCompilerService\fR [get]\fP"

.PP
Definition at line \fB27\fP of file \fBCompilerServiceRegistry\&.cs\fP\&.
.SS "\fBCompilerService\fP Luthetus\&.Tutorials\&.RazorLib\&.CompilerServices\&.CompilerServiceRegistry\&.DefaultCompilerService\fR [get]\fP"

.PP
Definition at line \fB28\fP of file \fBCompilerServiceRegistry\&.cs\fP\&.
.SS "ImmutableDictionary<string, \fBICompilerService\fP> Luthetus\&.Tutorials\&.RazorLib\&.CompilerServices\&.CompilerServiceRegistry\&.Map\fR [get]\fP"

.PP
Definition at line \fB16\fP of file \fBCompilerServiceRegistry\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
