.TH "Luthetus.Common.RazorLib.FileSystems.Models.IFileSystemDrive" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.FileSystems.Models.IFileSystemDrive
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.FileSystemDrive\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBDriveNameAsIdentifier\fP\fR [get]\fP"
.br
.RI "Given: "C:/Users"
.br
 Then \fBDriveNameAsIdentifier\fP is "C"\&. "
.ti -1c
.RI "string \fBDriveNameAsPath\fP\fR [get]\fP"
.br
.RI "Given: "C:/Users"
.br
 Then \fBDriveNameAsPath\fP is "C:"\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBIFileSystemDrive\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IFileSystemDrive\&.DriveNameAsIdentifier\fR [get]\fP"

.PP
Given: "C:/Users"
.br
 Then \fBDriveNameAsIdentifier\fP is "C"\&. 
.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.FileSystemDrive\fP\&.
.PP
Definition at line \fB9\fP of file \fBIFileSystemDrive\&.cs\fP\&.
.SS "string Luthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.IFileSystemDrive\&.DriveNameAsPath\fR [get]\fP"

.PP
Given: "C:/Users"
.br
 Then \fBDriveNameAsPath\fP is "C:"\&. 
.PP
Implemented in \fBLuthetus\&.Common\&.RazorLib\&.FileSystems\&.Models\&.FileSystemDrive\fP\&.
.PP
Definition at line \fB14\fP of file \fBIFileSystemDrive\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
