.TH "Luthetus.TextEditor.Tests.Basis.Commands.Models.Defaults.TextEditorCommandDefaultFactsTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.Commands.Models.Defaults.TextEditorCommandDefaultFactsTests \- TextEditorCommandDefaultFacts  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "async Task \fBDoNothingDiscard\fP ()"
.br
.RI "TextEditorCommandDefaultFacts\&.DoNothingDiscard "
.ti -1c
.RI "async Task \fBCopy\fP ()"
.br
.RI "TextEditorCommandDefaultFacts\&.Copy "
.ti -1c
.RI "async Task \fBCut\fP ()"
.br
.RI "TextEditorCommandDefaultFacts\&.Cut "
.ti -1c
.RI "async Task \fBPaste\fP ()"
.br
.RI "TextEditorCommandDefaultFacts\&.PasteCommand "
.ti -1c
.RI "async Task \fBSave\fP ()"
.br
.RI "TextEditorCommandDefaultFacts\&.Save "
.ti -1c
.RI "async Task \fBSelectAll\fP ()"
.br
.RI "TextEditorCommandDefaultFacts\&.SelectAll "
.ti -1c
.RI "async Task \fBUndo\fP ()"
.br
.RI "TextEditorCommandDefaultFacts\&.Undo "
.ti -1c
.RI "Task \fBRedo\fP ()"
.br
.RI "TextEditorCommandDefaultFacts\&.Redo "
.ti -1c
.RI "Task \fBDuplicate\fP ()"
.br
.RI "TextEditorCommandDefaultFacts\&.Duplicate "
.ti -1c
.RI "async Task \fBIndentMore\fP ()"
.br
.RI "TextEditorCommandDefaultFacts\&.IndentMore "
.ti -1c
.RI "async Task \fBIndentLess\fP ()"
.br
.RI "TextEditorCommandDefaultFacts\&.IndentLess "
.ti -1c
.RI "async Task \fBClearTextSelection\fP ()"
.br
.RI "TextEditorCommandDefaultFacts\&.ClearTextSelection "
.ti -1c
.RI "Task \fBNewLineBelow\fP ()"
.br
.RI "TextEditorCommandDefaultFacts\&.NewLineBelow "
.ti -1c
.RI "Task \fBNewLineAbove\fP ()"
.br
.RI "TextEditorCommandDefaultFacts\&.NewLineAbove "
.ti -1c
.RI "async Task \fBGoToMatchingCharacter\fP ()"
.br
.RI "TextEditorCommandDefaultFacts\&.GoToMatchingCharacter(bool) "
.ti -1c
.RI "Task \fBGoToDefinition\fP ()"
.br
.RI "TextEditorCommandDefaultFacts\&.GoToDefinition "
.ti -1c
.RI "Task \fBShowFindDialog\fP ()"
.br
.RI "TextEditorCommandDefaultFacts\&.ShowFindAllDialog "
.ti -1c
.RI "Task \fBRemeasure\fP ()"
.br
.RI "TextEditorCommandDefaultFacts\&.Remeasure "
.ti -1c
.RI "Task \fBShowTooltipByCursorPosition\fP ()"
.br
.RI "TextEditorCommandDefaultFacts\&.ShowTooltipByCursorPosition "
.ti -1c
.RI "Task \fBScrollLineDown\fP ()"
.br
.RI "TextEditorCommandDefaultFacts\&.ScrollLineDown "
.ti -1c
.RI "Task \fBScrollLineUp\fP ()"
.br
.RI "TextEditorCommandDefaultFacts\&.ScrollLineUp "
.ti -1c
.RI "Task \fBScrollPageDown\fP ()"
.br
.RI "TextEditorCommandDefaultFacts\&.ScrollPageDown "
.ti -1c
.RI "Task \fBScrollPageUp\fP ()"
.br
.RI "TextEditorCommandDefaultFacts\&.ScrollPageUp "
.ti -1c
.RI "Task \fBCursorMovePageBottom\fP ()"
.br
.RI "TextEditorCommandDefaultFacts\&.CursorMovePageBottom "
.ti -1c
.RI "Task \fBCursorMovePageTop\fP ()"
.br
.RI "TextEditorCommandDefaultFacts\&.CursorMovePageTop "
.in -1c
.SH "Detailed Description"
.PP 
TextEditorCommandDefaultFacts 
.PP
Definition at line \fB16\fP of file \fBTextEditorCommandDefaultFactsTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "async Task Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFactsTests\&.ClearTextSelection ()"

.PP
TextEditorCommandDefaultFacts\&.ClearTextSelection 
.PP
Definition at line \fB1197\fP of file \fBTextEditorCommandDefaultFactsTests\&.cs\fP\&.
.SS "async Task Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFactsTests\&.Copy ()"

.PP
TextEditorCommandDefaultFacts\&.Copy 
.PP
Definition at line \fB36\fP of file \fBTextEditorCommandDefaultFactsTests\&.cs\fP\&.
.SS "Task Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFactsTests\&.CursorMovePageBottom ()"

.PP
TextEditorCommandDefaultFacts\&.CursorMovePageBottom 
.PP
Definition at line \fB1699\fP of file \fBTextEditorCommandDefaultFactsTests\&.cs\fP\&.
.SS "Task Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFactsTests\&.CursorMovePageTop ()"

.PP
TextEditorCommandDefaultFacts\&.CursorMovePageTop 
.PP
Definition at line \fB1708\fP of file \fBTextEditorCommandDefaultFactsTests\&.cs\fP\&.
.SS "async Task Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFactsTests\&.Cut ()"

.PP
TextEditorCommandDefaultFacts\&.Cut 
.PP
Definition at line \fB94\fP of file \fBTextEditorCommandDefaultFactsTests\&.cs\fP\&.
.SS "async Task Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFactsTests\&.DoNothingDiscard ()"

.PP
TextEditorCommandDefaultFacts\&.DoNothingDiscard 
.PP
Definition at line \fB22\fP of file \fBTextEditorCommandDefaultFactsTests\&.cs\fP\&.
.SS "Task Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFactsTests\&.Duplicate ()"

.PP
TextEditorCommandDefaultFacts\&.Duplicate 
.PP
Definition at line \fB584\fP of file \fBTextEditorCommandDefaultFactsTests\&.cs\fP\&.
.SS "Task Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFactsTests\&.GoToDefinition ()"

.PP
TextEditorCommandDefaultFacts\&.GoToDefinition 
.PP
Definition at line \fB1627\fP of file \fBTextEditorCommandDefaultFactsTests\&.cs\fP\&.
.SS "async Task Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFactsTests\&.GoToMatchingCharacter ()"

.PP
TextEditorCommandDefaultFacts\&.GoToMatchingCharacter(bool) 
.PP
Definition at line \fB1478\fP of file \fBTextEditorCommandDefaultFactsTests\&.cs\fP\&.
.SS "async Task Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFactsTests\&.IndentLess ()"

.PP
TextEditorCommandDefaultFacts\&.IndentLess 
.PP
Definition at line \fB983\fP of file \fBTextEditorCommandDefaultFactsTests\&.cs\fP\&.
.SS "async Task Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFactsTests\&.IndentMore ()"

.PP
TextEditorCommandDefaultFacts\&.IndentMore 
.PP
Definition at line \fB644\fP of file \fBTextEditorCommandDefaultFactsTests\&.cs\fP\&.
.SS "Task Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFactsTests\&.NewLineAbove ()"

.PP
TextEditorCommandDefaultFacts\&.NewLineAbove 
.PP
Definition at line \fB1373\fP of file \fBTextEditorCommandDefaultFactsTests\&.cs\fP\&.
.SS "Task Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFactsTests\&.NewLineBelow ()"

.PP
TextEditorCommandDefaultFacts\&.NewLineBelow 
.PP
Definition at line \fB1268\fP of file \fBTextEditorCommandDefaultFactsTests\&.cs\fP\&.
.SS "async Task Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFactsTests\&.Paste ()"

.PP
TextEditorCommandDefaultFacts\&.PasteCommand 
.PP
Definition at line \fB178\fP of file \fBTextEditorCommandDefaultFactsTests\&.cs\fP\&.
.SS "Task Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFactsTests\&.Redo ()"

.PP
TextEditorCommandDefaultFacts\&.Redo 
.PP
Definition at line \fB500\fP of file \fBTextEditorCommandDefaultFactsTests\&.cs\fP\&.
.SS "Task Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFactsTests\&.Remeasure ()"

.PP
TextEditorCommandDefaultFacts\&.Remeasure 
.PP
Definition at line \fB1645\fP of file \fBTextEditorCommandDefaultFactsTests\&.cs\fP\&.
.SS "async Task Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFactsTests\&.Save ()"

.PP
TextEditorCommandDefaultFacts\&.Save 
.PP
Definition at line \fB275\fP of file \fBTextEditorCommandDefaultFactsTests\&.cs\fP\&.
.SS "Task Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFactsTests\&.ScrollLineDown ()"

.PP
TextEditorCommandDefaultFacts\&.ScrollLineDown 
.PP
Definition at line \fB1663\fP of file \fBTextEditorCommandDefaultFactsTests\&.cs\fP\&.
.SS "Task Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFactsTests\&.ScrollLineUp ()"

.PP
TextEditorCommandDefaultFacts\&.ScrollLineUp 
.PP
Definition at line \fB1672\fP of file \fBTextEditorCommandDefaultFactsTests\&.cs\fP\&.
.SS "Task Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFactsTests\&.ScrollPageDown ()"

.PP
TextEditorCommandDefaultFacts\&.ScrollPageDown 
.PP
Definition at line \fB1681\fP of file \fBTextEditorCommandDefaultFactsTests\&.cs\fP\&.
.SS "Task Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFactsTests\&.ScrollPageUp ()"

.PP
TextEditorCommandDefaultFacts\&.ScrollPageUp 
.PP
Definition at line \fB1690\fP of file \fBTextEditorCommandDefaultFactsTests\&.cs\fP\&.
.SS "async Task Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFactsTests\&.SelectAll ()"

.PP
TextEditorCommandDefaultFacts\&.SelectAll 
.PP
Definition at line \fB342\fP of file \fBTextEditorCommandDefaultFactsTests\&.cs\fP\&.
.SS "Task Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFactsTests\&.ShowFindDialog ()"

.PP
TextEditorCommandDefaultFacts\&.ShowFindAllDialog 
.PP
Definition at line \fB1636\fP of file \fBTextEditorCommandDefaultFactsTests\&.cs\fP\&.
.SS "Task Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFactsTests\&.ShowTooltipByCursorPosition ()"

.PP
TextEditorCommandDefaultFacts\&.ShowTooltipByCursorPosition 
.PP
Definition at line \fB1654\fP of file \fBTextEditorCommandDefaultFactsTests\&.cs\fP\&.
.SS "async Task Luthetus\&.TextEditor\&.Tests\&.Basis\&.Commands\&.Models\&.Defaults\&.TextEditorCommandDefaultFactsTests\&.Undo ()"

.PP
TextEditorCommandDefaultFacts\&.Undo 
.PP
Definition at line \fB411\fP of file \fBTextEditorCommandDefaultFactsTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
