.TH "Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Parsers" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Parsers
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBExpressionAsStatementTests\fP"
.br
.RI "Anything parsed starts off as a statement, then goes on to invoke the expression loop if the syntax is deemed an expression\&. "
.ti -1c
.RI "class \fBExpressionTests\fP"
.br
.ti -1c
.RI "class \fBScopeTests\fP"
.br
.RI "Scope being incorrectly parsed is an error that cascades further errors in large throughout the rest of the file\&. "
.ti -1c
.RI "class \fBStatementTests\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
