.TH "Luthetus.CompilerServices.DotNetSolution.Models.Associated.IAssociatedEntry" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.DotNetSolution.Models.Associated.IAssociatedEntry
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBAssociatedEntryKind\fP \fBAssociatedEntryKind\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBIAssociatedEntry\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBAssociatedEntryKind\fP Luthetus\&.CompilerServices\&.DotNetSolution\&.Models\&.Associated\&.IAssociatedEntry\&.AssociatedEntryKind\fR [get]\fP"

.PP
Definition at line \fB5\fP of file \fBIAssociatedEntry\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
