.TH "Luthetus.Extensions.DotNet.Tests.Basis.TestExplorers.Models.ProjectTestModelTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.Tests.Basis.TestExplorers.Models.ProjectTestModelTests \- ProjectTestModel  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "ProjectTestModel(Guid, IAbsolutePath, Func<Func<Dictionary<string, StringFragment>, Task>, Task>, Action<TreeViewNoType>) 
.br
----
.br
 ProjectTestModel\&.TestNameFullyQualifiedList ProjectTestModel\&.EnqueueDiscoverTestsFunc ProjectTestModel\&.RootStringFragmentMap ProjectTestModel\&.ProjectIdGuid ProjectTestModel\&.AbsolutePath ProjectTestModel\&.DotNetTestListTestsTerminalCommandKey ProjectTestModel\&.ReRenderNodeAction ProjectTestModel\&.DirectoryNameForTestDiscovery "
.in -1c
.SH "Detailed Description"
.PP 
ProjectTestModel 
.PP
Definition at line \fB6\fP of file \fBProjectTestModelTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.TestExplorers\&.Models\&.ProjectTestModelTests\&.Constructor ()"

.PP
ProjectTestModel(Guid, IAbsolutePath, Func<Func<Dictionary<string, StringFragment>, Task>, Task>, Action<TreeViewNoType>) 
.br
----
.br
 ProjectTestModel\&.TestNameFullyQualifiedList ProjectTestModel\&.EnqueueDiscoverTestsFunc ProjectTestModel\&.RootStringFragmentMap ProjectTestModel\&.ProjectIdGuid ProjectTestModel\&.AbsolutePath ProjectTestModel\&.DotNetTestListTestsTerminalCommandKey ProjectTestModel\&.ReRenderNodeAction ProjectTestModel\&.DirectoryNameForTestDiscovery 
.PP
Definition at line \fB21\fP of file \fBProjectTestModelTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
