.TH "Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.DeliminationExtendedSyntaxDefinition" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.DeliminationExtendedSyntaxDefinition \- An example of usage would be for the C language's preprocessor\&. Given "#include &lt;stdlib\&.h&gt;" one would syntax highlight "&lt;stdlib\&.h&gt;" as if it were a string\&.  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDeliminationExtendedSyntaxDefinition\fP (string syntaxStart, string syntaxEnd, \fBGenericDecorationKind\fP genericDecorationKind)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBSyntaxStart\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBSyntaxEnd\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBGenericDecorationKind\fP \fBGenericDecorationKind\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
An example of usage would be for the C language's preprocessor\&. Given "#include &lt;stdlib\&.h&gt;" one would syntax highlight "&lt;stdlib\&.h&gt;" as if it were a string\&. 
.PP
Definition at line \fB10\fP of file \fBDeliminationExtendedSyntaxDefinition\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.DeliminationExtendedSyntaxDefinition\&.DeliminationExtendedSyntaxDefinition (string syntaxStart, string syntaxEnd, \fBGenericDecorationKind\fP genericDecorationKind)"

.PP
Definition at line \fB12\fP of file \fBDeliminationExtendedSyntaxDefinition\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBGenericDecorationKind\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.DeliminationExtendedSyntaxDefinition\&.GenericDecorationKind\fR [get]\fP"

.PP
Definition at line \fB24\fP of file \fBDeliminationExtendedSyntaxDefinition\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.DeliminationExtendedSyntaxDefinition\&.SyntaxEnd\fR [get]\fP"

.PP
Definition at line \fB23\fP of file \fBDeliminationExtendedSyntaxDefinition\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.GenericLexer\&.DeliminationExtendedSyntaxDefinition\&.SyntaxStart\fR [get]\fP"

.PP
Definition at line \fB22\fP of file \fBDeliminationExtendedSyntaxDefinition\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
