.TH "Luthetus.Extensions.DotNet.CommandLines.Models.DotNetCliOutputParser.NewListModel" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.CommandLines.Models.DotNetCliOutputParser.NewListModel
.SH SYNOPSIS
.br
.PP
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBShouldLocateKeywordTags\fP = true\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBShouldCountDashes\fP = true\fR [get, set]\fP"
.br
.ti -1c
.RI "bool \fBShouldLocateDashes\fP = true\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBDashCounter\fP = 0\fR [get, set]\fP"
.br
.ti -1c
.RI "int? \fBLengthOfTemplateNameColumn\fP = null\fR [get, set]\fP"
.br
.ti -1c
.RI "int? \fBLengthOfShortNameColumn\fP = null\fR [get, set]\fP"
.br
.ti -1c
.RI "int? \fBLengthOfLanguageColumn\fP = null\fR [get, set]\fP"
.br
.ti -1c
.RI "int? \fBLengthOfTagsColumn\fP = null\fR [get, set]\fP"
.br
.ti -1c
.RI "StringBuilder \fBColumnBuilder\fP = new StringBuilder()\fR [get, set]\fP"
.br
.ti -1c
.RI "int? \fBColumnLength\fP = null\fR [get, set]\fP"
.br
.ti -1c
.RI "ProjectTemplate \fBProjectTemplate\fP = new ProjectTemplate(null, null, null, null)\fR [get, set]\fP"
.br
.ti -1c
.RI "List< \fBProjectTemplate\fP > \fBProjectTemplateList\fP = new List<\fBProjectTemplate\fP>()\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB629\fP of file \fBDotNetCliOutputParser\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "StringBuilder Luthetus\&.Extensions\&.DotNet\&.CommandLines\&.Models\&.DotNetCliOutputParser\&.NewListModel\&.ColumnBuilder = new StringBuilder()\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB639\fP of file \fBDotNetCliOutputParser\&.cs\fP\&.
.SS "int? Luthetus\&.Extensions\&.DotNet\&.CommandLines\&.Models\&.DotNetCliOutputParser\&.NewListModel\&.ColumnLength = null\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB640\fP of file \fBDotNetCliOutputParser\&.cs\fP\&.
.SS "int Luthetus\&.Extensions\&.DotNet\&.CommandLines\&.Models\&.DotNetCliOutputParser\&.NewListModel\&.DashCounter = 0\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB634\fP of file \fBDotNetCliOutputParser\&.cs\fP\&.
.SS "int? Luthetus\&.Extensions\&.DotNet\&.CommandLines\&.Models\&.DotNetCliOutputParser\&.NewListModel\&.LengthOfLanguageColumn = null\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB637\fP of file \fBDotNetCliOutputParser\&.cs\fP\&.
.SS "int? Luthetus\&.Extensions\&.DotNet\&.CommandLines\&.Models\&.DotNetCliOutputParser\&.NewListModel\&.LengthOfShortNameColumn = null\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB636\fP of file \fBDotNetCliOutputParser\&.cs\fP\&.
.SS "int? Luthetus\&.Extensions\&.DotNet\&.CommandLines\&.Models\&.DotNetCliOutputParser\&.NewListModel\&.LengthOfTagsColumn = null\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB638\fP of file \fBDotNetCliOutputParser\&.cs\fP\&.
.SS "int? Luthetus\&.Extensions\&.DotNet\&.CommandLines\&.Models\&.DotNetCliOutputParser\&.NewListModel\&.LengthOfTemplateNameColumn = null\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB635\fP of file \fBDotNetCliOutputParser\&.cs\fP\&.
.SS "ProjectTemplate Luthetus\&.Extensions\&.DotNet\&.CommandLines\&.Models\&.DotNetCliOutputParser\&.NewListModel\&.ProjectTemplate = new ProjectTemplate(null, null, null, null)\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB641\fP of file \fBDotNetCliOutputParser\&.cs\fP\&.
.SS "List<\fBProjectTemplate\fP> Luthetus\&.Extensions\&.DotNet\&.CommandLines\&.Models\&.DotNetCliOutputParser\&.NewListModel\&.ProjectTemplateList = new List<\fBProjectTemplate\fP>()\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB642\fP of file \fBDotNetCliOutputParser\&.cs\fP\&.
.SS "bool Luthetus\&.Extensions\&.DotNet\&.CommandLines\&.Models\&.DotNetCliOutputParser\&.NewListModel\&.ShouldCountDashes = true\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB632\fP of file \fBDotNetCliOutputParser\&.cs\fP\&.
.SS "bool Luthetus\&.Extensions\&.DotNet\&.CommandLines\&.Models\&.DotNetCliOutputParser\&.NewListModel\&.ShouldLocateDashes = true\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB633\fP of file \fBDotNetCliOutputParser\&.cs\fP\&.
.SS "bool Luthetus\&.Extensions\&.DotNet\&.CommandLines\&.Models\&.DotNetCliOutputParser\&.NewListModel\&.ShouldLocateKeywordTags = true\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB631\fP of file \fBDotNetCliOutputParser\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
