.TH "Luthetus.Common.Tests.Basis.Notifications.States.NotificationStateTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Notifications.States.NotificationStateTests \- \fBNotificationState\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "\fBNotificationState()\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBNotificationState\fP 
.PP
Definition at line \fB10\fP of file \fBNotificationStateTests\&.Main\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Notifications\&.States\&.NotificationStateTests\&.Constructor ()"

.PP
\fBNotificationState()\fP 
.PP
Definition at line \fB16\fP of file \fBNotificationStateTests\&.Main\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
