.TH "Luthetus.TextEditor.Tests.Basis.Virtualizations.Models.VirtualizationRequestTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.Virtualizations.Models.VirtualizationRequestTests \- \fBVirtualizationRequest\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "\fBVirtualizationRequest(VirtualizationScrollPosition, CancellationToken)\fP 
.br
----
.br
 VirtualizationRequest\&.ScrollPosition VirtualizationRequest\&.CancellationToken "
.in -1c
.SH "Detailed Description"
.PP 
\fBVirtualizationRequest\fP 
.PP
Definition at line \fB8\fP of file \fBVirtualizationRequestTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Virtualizations\&.Models\&.VirtualizationRequestTests\&.Constructor ()"

.PP
\fBVirtualizationRequest(VirtualizationScrollPosition, CancellationToken)\fP 
.br
----
.br
 VirtualizationRequest\&.ScrollPosition VirtualizationRequest\&.CancellationToken 
.PP
Definition at line \fB17\fP of file \fBVirtualizationRequestTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
