.TH "Luthetus.Extensions.DotNet.Tests.Basis.CompilerServices.States.CompilerServiceExplorerStateMainTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.Tests.Basis.CompilerServices.States.CompilerServiceExplorerStateMainTests \- CompilerServiceExplorerState  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor_NO_ARGS\fP ()"
.br
.RI "CompilerServiceExplorerState() 
.br
----
.br
 CompilerServiceExplorerState\&.TreeViewCompilerServiceExplorerContentStateKey CompilerServiceExplorerState\&.Model "
.ti -1c
.RI "void \fBConstructor_CompilerServiceExplorerModel\fP ()"
.br
.RI "CompilerServiceExplorerState(CompilerServiceExplorerModel) 
.br
----
.br
 CompilerServiceExplorerState\&.TreeViewCompilerServiceExplorerContentStateKey CompilerServiceExplorerState\&.Model "
.in -1c
.SH "Detailed Description"
.PP 
CompilerServiceExplorerState 
.PP
Definition at line \fB6\fP of file \fBCompilerServiceExplorerStateMainTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.CompilerServices\&.States\&.CompilerServiceExplorerStateMainTests\&.Constructor_CompilerServiceExplorerModel ()"

.PP
CompilerServiceExplorerState(CompilerServiceExplorerModel) 
.br
----
.br
 CompilerServiceExplorerState\&.TreeViewCompilerServiceExplorerContentStateKey CompilerServiceExplorerState\&.Model 
.PP
Definition at line \fB27\fP of file \fBCompilerServiceExplorerStateMainTests\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.CompilerServices\&.States\&.CompilerServiceExplorerStateMainTests\&.Constructor_NO_ARGS ()"

.PP
CompilerServiceExplorerState() 
.br
----
.br
 CompilerServiceExplorerState\&.TreeViewCompilerServiceExplorerContentStateKey CompilerServiceExplorerState\&.Model 
.PP
Definition at line \fB15\fP of file \fBCompilerServiceExplorerStateMainTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
