.TH "Luthetus.TextEditor.RazorLib.Groups.Models.TextEditorGroupDropzone" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Groups.Models.TextEditorGroupDropzone
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDropzone\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTextEditorGroupDropzone\fP (\fBMeasuredHtmlElementDimensions\fP measuredHtmlElementDimensions, Key< TextEditorGroup > textEditorGroupKey, \fBElementDimensions\fP elementDimensions)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "MeasuredHtmlElementDimensions \fBMeasuredHtmlElementDimensions\fP\fR [get]\fP"
.br
.ti -1c
.RI "Key< TextEditorGroup > \fBTextEditorGroupKey\fP\fR [get]\fP"
.br
.ti -1c
.RI "Key< \fBIDropzone\fP > \fBDropzoneKey\fP\fR [get]\fP"
.br
.ti -1c
.RI "ElementDimensions \fBElementDimensions\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBCssClass\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBCssStyle\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBTextEditorGroupDropzone\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.Groups\&.Models\&.TextEditorGroupDropzone\&.TextEditorGroupDropzone (\fBMeasuredHtmlElementDimensions\fP measuredHtmlElementDimensions, Key< TextEditorGroup > textEditorGroupKey, \fBElementDimensions\fP elementDimensions)"

.PP
Definition at line \fB10\fP of file \fBTextEditorGroupDropzone\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.Groups\&.Models\&.TextEditorGroupDropzone\&.CssClass\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDropzone\fP\&.
.PP
Definition at line \fB24\fP of file \fBTextEditorGroupDropzone\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.Groups\&.Models\&.TextEditorGroupDropzone\&.CssStyle\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDropzone\fP\&.
.PP
Definition at line \fB25\fP of file \fBTextEditorGroupDropzone\&.cs\fP\&.
.SS "Key<\fBIDropzone\fP> Luthetus\&.TextEditor\&.RazorLib\&.Groups\&.Models\&.TextEditorGroupDropzone\&.DropzoneKey\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDropzone\fP\&.
.PP
Definition at line \fB22\fP of file \fBTextEditorGroupDropzone\&.cs\fP\&.
.SS "ElementDimensions Luthetus\&.TextEditor\&.RazorLib\&.Groups\&.Models\&.TextEditorGroupDropzone\&.ElementDimensions\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDropzone\fP\&.
.PP
Definition at line \fB23\fP of file \fBTextEditorGroupDropzone\&.cs\fP\&.
.SS "MeasuredHtmlElementDimensions Luthetus\&.TextEditor\&.RazorLib\&.Groups\&.Models\&.TextEditorGroupDropzone\&.MeasuredHtmlElementDimensions\fR [get]\fP"

.PP
Implements \fBLuthetus\&.Common\&.RazorLib\&.Dynamics\&.Models\&.IDropzone\fP\&.
.PP
Definition at line \fB20\fP of file \fBTextEditorGroupDropzone\&.cs\fP\&.
.SS "Key<TextEditorGroup> Luthetus\&.TextEditor\&.RazorLib\&.Groups\&.Models\&.TextEditorGroupDropzone\&.TextEditorGroupKey\fR [get]\fP"

.PP
Definition at line \fB21\fP of file \fBTextEditorGroupDropzone\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
