.TH "Luthetus.Extensions.Git.Models.GitIdeApi" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.Git.Models.GitIdeApi
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBGitIdeApi\fP (\fBGitBackgroundTaskApi\fP gitBackgroundTaskApi, \fBIdeBackgroundTaskApi\fP ideBackgroundTaskApi, IState< \fBTerminalState\fP > terminalStateWrap, IState< \fBGitState\fP > gitStateWrap, \fBGitCliOutputParser\fP gitCliOutputParser, \fBIEnvironmentProvider\fP environmentProvider, \fBIBackgroundTaskService\fP backgroundTaskService, \fBICommonComponentRenderers\fP commonComponentRenderers, IDispatcher dispatcher)"
.br
.ti -1c
.RI "void \fBStatusEnqueue\fP ()"
.br
.ti -1c
.RI "void \fBRefreshEnqueue\fP (\fBGitRepo\fP repoAtTimeOfRequest)"
.br
.ti -1c
.RI "void \fBGetActiveBranchNameEnqueue\fP (\fBGitRepo\fP repoAtTimeOfRequest)"
.br
.ti -1c
.RI "void \fBGetOriginNameEnqueue\fP (\fBGitRepo\fP repoAtTimeOfRequest)"
.br
.ti -1c
.RI "void \fBAddEnqueue\fP (\fBGitRepo\fP repoAtTimeOfRequest)"
.br
.ti -1c
.RI "void \fBUnstageEnqueue\fP (\fBGitRepo\fP repoAtTimeOfRequest)"
.br
.ti -1c
.RI "void \fBCommitEnqueue\fP (\fBGitRepo\fP repoAtTimeOfRequest, string commitSummary)"
.br
.ti -1c
.RI "void \fBBranchNewEnqueue\fP (\fBGitRepo\fP repoAtTimeOfRequest, string branchName)"
.br
.ti -1c
.RI "void \fBBranchGetAllEnqueue\fP (\fBGitRepo\fP repoAtTimeOfRequest)"
.br
.ti -1c
.RI "void \fBBranchSetEnqueue\fP (\fBGitRepo\fP repoAtTimeOfRequest, string branchName)"
.br
.ti -1c
.RI "void \fBPushToOriginWithTrackingEnqueue\fP (\fBGitRepo\fP repoAtTimeOfRequest)"
.br
.ti -1c
.RI "void \fBPullEnqueue\fP (\fBGitRepo\fP repoAtTimeOfRequest)"
.br
.ti -1c
.RI "void \fBFetchEnqueue\fP (\fBGitRepo\fP repoAtTimeOfRequest)"
.br
.ti -1c
.RI "void \fBLogFileEnqueue\fP (\fBGitRepo\fP repoAtTimeOfRequest, string relativePathToFile, Func< \fBGitCliOutputParser\fP, string, Task > callback)"
.br
.ti -1c
.RI "void \fBShowFileEnqueue\fP (\fBGitRepo\fP repoAtTimeOfRequest, string relativePathToFile, Func< \fBGitCliOutputParser\fP, string, Task > callback)"
.br
.ti -1c
.RI "void \fBDiffFileEnqueue\fP (\fBGitRepo\fP repoAtTimeOfRequest, string relativePathToFile, Func< \fBGitCliOutputParser\fP, string, List< int >, Task > callback)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "Key< \fBTerminalCommandRequest\fP > \fBGitTerminalCommandRequestKey\fP = Key<\fBTerminalCommandRequest\fP>\&.NewKey()\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB22\fP of file \fBGitIdeApi\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Extensions\&.Git\&.Models\&.GitIdeApi\&.GitIdeApi (\fBGitBackgroundTaskApi\fP gitBackgroundTaskApi, \fBIdeBackgroundTaskApi\fP ideBackgroundTaskApi, IState< \fBTerminalState\fP > terminalStateWrap, IState< \fBGitState\fP > gitStateWrap, \fBGitCliOutputParser\fP gitCliOutputParser, \fBIEnvironmentProvider\fP environmentProvider, \fBIBackgroundTaskService\fP backgroundTaskService, \fBICommonComponentRenderers\fP commonComponentRenderers, IDispatcher dispatcher)"

.PP
Definition at line \fB34\fP of file \fBGitIdeApi\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Extensions\&.Git\&.Models\&.GitIdeApi\&.AddEnqueue (\fBGitRepo\fP repoAtTimeOfRequest)"

.PP
Definition at line \fB191\fP of file \fBGitIdeApi\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.Git\&.Models\&.GitIdeApi\&.BranchGetAllEnqueue (\fBGitRepo\fP repoAtTimeOfRequest)"

.PP
Definition at line \fB396\fP of file \fBGitIdeApi\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.Git\&.Models\&.GitIdeApi\&.BranchNewEnqueue (\fBGitRepo\fP repoAtTimeOfRequest, string branchName)"

.PP
Definition at line \fB355\fP of file \fBGitIdeApi\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.Git\&.Models\&.GitIdeApi\&.BranchSetEnqueue (\fBGitRepo\fP repoAtTimeOfRequest, string branchName)"

.PP
Definition at line \fB438\fP of file \fBGitIdeApi\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.Git\&.Models\&.GitIdeApi\&.CommitEnqueue (\fBGitRepo\fP repoAtTimeOfRequest, string commitSummary)"

.PP
Definition at line \fB309\fP of file \fBGitIdeApi\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.Git\&.Models\&.GitIdeApi\&.DiffFileEnqueue (\fBGitRepo\fP repoAtTimeOfRequest, string relativePathToFile, Func< \fBGitCliOutputParser\fP, string, List< int >, Task > callback)"

.PP
Definition at line \fB781\fP of file \fBGitIdeApi\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.Git\&.Models\&.GitIdeApi\&.FetchEnqueue (\fBGitRepo\fP repoAtTimeOfRequest)"

.PP
Definition at line \fB557\fP of file \fBGitIdeApi\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.Git\&.Models\&.GitIdeApi\&.GetActiveBranchNameEnqueue (\fBGitRepo\fP repoAtTimeOfRequest)"

.PP
Definition at line \fB109\fP of file \fBGitIdeApi\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.Git\&.Models\&.GitIdeApi\&.GetOriginNameEnqueue (\fBGitRepo\fP repoAtTimeOfRequest)"

.PP
Definition at line \fB150\fP of file \fBGitIdeApi\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.Git\&.Models\&.GitIdeApi\&.LogFileEnqueue (\fBGitRepo\fP repoAtTimeOfRequest, string relativePathToFile, Func< \fBGitCliOutputParser\fP, string, Task > callback)"

.PP
Definition at line \fB596\fP of file \fBGitIdeApi\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.Git\&.Models\&.GitIdeApi\&.PullEnqueue (\fBGitRepo\fP repoAtTimeOfRequest)"

.PP
Definition at line \fB518\fP of file \fBGitIdeApi\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.Git\&.Models\&.GitIdeApi\&.PushToOriginWithTrackingEnqueue (\fBGitRepo\fP repoAtTimeOfRequest)"

.PP
Definition at line \fB477\fP of file \fBGitIdeApi\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.Git\&.Models\&.GitIdeApi\&.RefreshEnqueue (\fBGitRepo\fP repoAtTimeOfRequest)"

.PP
Definition at line \fB101\fP of file \fBGitIdeApi\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.Git\&.Models\&.GitIdeApi\&.ShowFileEnqueue (\fBGitRepo\fP repoAtTimeOfRequest, string relativePathToFile, Func< \fBGitCliOutputParser\fP, string, Task > callback)"

.PP
Definition at line \fB638\fP of file \fBGitIdeApi\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.Git\&.Models\&.GitIdeApi\&.StatusEnqueue ()"

.PP
Definition at line \fB58\fP of file \fBGitIdeApi\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.Git\&.Models\&.GitIdeApi\&.UnstageEnqueue (\fBGitRepo\fP repoAtTimeOfRequest)"

.PP
Definition at line \fB250\fP of file \fBGitIdeApi\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "Key<\fBTerminalCommandRequest\fP> Luthetus\&.Extensions\&.Git\&.Models\&.GitIdeApi\&.GitTerminalCommandRequestKey = Key<\fBTerminalCommandRequest\fP>\&.NewKey()\fR [get]\fP"

.PP
Definition at line \fB56\fP of file \fBGitIdeApi\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
