.TH "Luthetus.Extensions.DotNet.Tests.Basis.TreeViewImplementations.Models.TreeViewStringFragmentTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.Tests.Basis.TreeViewImplementations.Models.TreeViewStringFragmentTests \- \fBTreeViewStringFragment\fP  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.ExtensionsDotNetTestBase\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "TreeViewStringFragment(StringFragment, ILuthetusCommonComponentRenderers, bool, bool) 
.br
----
.br
 \fBTreeViewStringFragment\&.CommonComponentRenderers\fP "
.ti -1c
.RI "void \fBEquals_Test\fP ()"
.br
.RI "\fBTreeViewStringFragment\&.Equals(object?)\fP "
.ti -1c
.RI "void \fBGetHashCode_Test\fP ()"
.br
.RI "\fBTreeViewStringFragment\&.GetHashCode()\fP "
.ti -1c
.RI "void \fBGetTreeViewRenderer\fP ()"
.br
.RI "\fBTreeViewStringFragment\&.GetTreeViewRenderer()\fP "
.ti -1c
.RI "void \fBLoadChildListAsync\fP ()"
.br
.RI "\fBTreeViewStringFragment\&.LoadChildListAsync()\fP "
.ti -1c
.RI "void \fBRemoveRelatedFilesFromParent\fP ()"
.br
.RI "TreeViewStringFragment\&.RemoveRelatedFilesFromParent(List<TreeViewNoType>) "
.in -1c
.SS "Additional Inherited Members"


Static Protected Member Functions inherited from \fBLuthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.ExtensionsDotNetTestBase\fP
.in +1c
.ti -1c
.RI "static void \fBTest_RegisterServices\fP (out ServiceProvider serviceProvider)"
.br
.ti -1c
.RI "static void \fBTest_CreateFileSystem\fP (IServiceProvider serviceProvider)"
.br
.RI "The files shown in the 'tree' below will be written to the in-memory filesystem\&. ---------------------------------------------
.br
 Root
.br
 ∙└───Homework
.br
 ∙∙∙∙∙∙├───Math
.br
 ∙∙∙∙∙∙│∙∙∙∙├───addition\&.txt
.br
 ∙∙∙∙∙∙│∙∙∙∙└───subtraction\&.txt
.br
 ∙∙∙∙∙∙│
.br
 ∙∙∙∙∙∙└───Biology
.br
 ∙∙∙∙∙∙∙∙∙∙∙├───nervousSystem\&.txt
.br
 ∙∙∙∙∙∙∙∙∙∙∙└───skeletalSystem\&.txt
.br
\&. "
.in -1c
.SH "Detailed Description"
.PP 
\fBTreeViewStringFragment\fP 
.PP
Definition at line \fB12\fP of file \fBTreeViewStringFragmentTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.TreeViewImplementations\&.Models\&.TreeViewStringFragmentTests\&.Constructor ()"

.PP
TreeViewStringFragment(StringFragment, ILuthetusCommonComponentRenderers, bool, bool) 
.br
----
.br
 \fBTreeViewStringFragment\&.CommonComponentRenderers\fP 
.PP
Definition at line \fB20\fP of file \fBTreeViewStringFragmentTests\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.TreeViewImplementations\&.Models\&.TreeViewStringFragmentTests\&.Equals_Test ()"

.PP
\fBTreeViewStringFragment\&.Equals(object?)\fP 
.PP
Definition at line \fB51\fP of file \fBTreeViewStringFragmentTests\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.TreeViewImplementations\&.Models\&.TreeViewStringFragmentTests\&.GetHashCode_Test ()"

.PP
\fBTreeViewStringFragment\&.GetHashCode()\fP 
.PP
Definition at line \fB60\fP of file \fBTreeViewStringFragmentTests\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.TreeViewImplementations\&.Models\&.TreeViewStringFragmentTests\&.GetTreeViewRenderer ()"

.PP
\fBTreeViewStringFragment\&.GetTreeViewRenderer()\fP 
.PP
Definition at line \fB69\fP of file \fBTreeViewStringFragmentTests\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.TreeViewImplementations\&.Models\&.TreeViewStringFragmentTests\&.LoadChildListAsync ()"

.PP
\fBTreeViewStringFragment\&.LoadChildListAsync()\fP 
.PP
Definition at line \fB78\fP of file \fBTreeViewStringFragmentTests\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.TreeViewImplementations\&.Models\&.TreeViewStringFragmentTests\&.RemoveRelatedFilesFromParent ()"

.PP
TreeViewStringFragment\&.RemoveRelatedFilesFromParent(List<TreeViewNoType>) 
.PP
Definition at line \fB87\fP of file \fBTreeViewStringFragmentTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
