.TH "Luthetus.Extensions.DotNet.DotNetSolutions.Displays.Internals.SolutionVisualizationSettingsDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.DotNetSolutions.Displays.Internals.SolutionVisualizationSettingsDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "SolutionVisualizationModel \fBSolutionVisualizationModel\fP = null!\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBSolutionVisualizationSettingsDisplay\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "SolutionVisualizationModel Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Displays\&.Internals\&.SolutionVisualizationSettingsDisplay\&.SolutionVisualizationModel = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB9\fP of file \fBSolutionVisualizationSettingsDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
