.TH "Luthetus.CompilerServices.Json.SyntaxObjects.JsonObjectSyntax" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.Json.SyntaxObjects.JsonObjectSyntax
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.CompilerServices\&.Json\&.IJsonSyntax\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJsonObjectSyntax\fP (\fBTextEditorTextSpan\fP textEditorTextSpan, ImmutableArray< \fBJsonPropertySyntax\fP > jsonPropertySyntaxes)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "TextEditorTextSpan \fBTextEditorTextSpan\fP\fR [get]\fP"
.br
.ti -1c
.RI "ImmutableArray< \fBIJsonSyntax\fP > \fBJsonPropertySyntaxes\fP\fR [get]\fP"
.br
.ti -1c
.RI "ImmutableArray< \fBIJsonSyntax\fP > \fBChildJsonSyntaxes\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBJsonSyntaxKind\fP \fBJsonSyntaxKind\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBJsonObjectSyntax\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.CompilerServices\&.Json\&.SyntaxObjects\&.JsonObjectSyntax\&.JsonObjectSyntax (\fBTextEditorTextSpan\fP textEditorTextSpan, ImmutableArray< \fBJsonPropertySyntax\fP > jsonPropertySyntaxes)"

.PP
Definition at line \fB9\fP of file \fBJsonObjectSyntax\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "ImmutableArray<\fBIJsonSyntax\fP> Luthetus\&.CompilerServices\&.Json\&.SyntaxObjects\&.JsonObjectSyntax\&.ChildJsonSyntaxes\fR [get]\fP"

.PP
Implements \fBLuthetus\&.CompilerServices\&.Json\&.IJsonSyntax\fP\&.
.PP
Definition at line \fB25\fP of file \fBJsonObjectSyntax\&.cs\fP\&.
.SS "ImmutableArray<\fBIJsonSyntax\fP> Luthetus\&.CompilerServices\&.Json\&.SyntaxObjects\&.JsonObjectSyntax\&.JsonPropertySyntaxes\fR [get]\fP"

.PP
Definition at line \fB24\fP of file \fBJsonObjectSyntax\&.cs\fP\&.
.SS "\fBJsonSyntaxKind\fP Luthetus\&.CompilerServices\&.Json\&.SyntaxObjects\&.JsonObjectSyntax\&.JsonSyntaxKind\fR [get]\fP"

.PP
Implements \fBLuthetus\&.CompilerServices\&.Json\&.IJsonSyntax\fP\&.
.PP
Definition at line \fB27\fP of file \fBJsonObjectSyntax\&.cs\fP\&.
.SS "TextEditorTextSpan Luthetus\&.CompilerServices\&.Json\&.SyntaxObjects\&.JsonObjectSyntax\&.TextEditorTextSpan\fR [get]\fP"

.PP
Implements \fBLuthetus\&.CompilerServices\&.Json\&.IJsonSyntax\fP\&.
.PP
Definition at line \fB23\fP of file \fBJsonObjectSyntax\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
