.TH "Luthetus.TextEditor.RazorLib.Events.Models" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Events.Models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEventUtils\fP"
.br
.ti -1c
.RI "struct \fBOnDoubleClick\fP"
.br
.ti -1c
.RI "struct \fBOnKeyDownLateBatching\fP"
.br
.RI "Use an array with a fixed size to optimize this, usually there are only about 3-5 events that end up batched\&. To construct a non-struct collection is probably a massive performance hit considering the extremely rapid turn over of this type while holding down a keyboard key\&. "
.ti -1c
.RI "struct \fBOnMouseDown\fP"
.br
.ti -1c
.RI "struct \fBOnMouseMove\fP"
.br
.ti -1c
.RI "struct \fBOnScrollHorizontal\fP"
.br
.ti -1c
.RI "struct \fBOnScrollVertical\fP"
.br
.ti -1c
.RI "struct \fBOnWheel\fP"
.br
.ti -1c
.RI "struct \fBOnWheelBatch\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
