.TH "Luthetus.Ide.RazorLib.Editors.Displays.EditorDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.Editors.Displays.EditorDisplay
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInitialized\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBElementDimensions\fP \fBEditorElementDimensions\fP = null!\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB10\fP of file \fBEditorDisplay\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Luthetus\&.Ide\&.RazorLib\&.Editors\&.Displays\&.EditorDisplay\&.OnInitialized ()\fR [protected]\fP"

.PP
Definition at line \fB25\fP of file \fBEditorDisplay\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBElementDimensions\fP Luthetus\&.Ide\&.RazorLib\&.Editors\&.Displays\&.EditorDisplay\&.EditorElementDimensions = null!\fR [get]\fP, \fR [set]\fP"

.PP
Definition at line \fB16\fP of file \fBEditorDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
