.TH "Luthetus.Common.Tests.Basis.Panels.States.PanelStateReducerTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Panels.States.PanelStateReducerTests \- PanelState\&.Reducer  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBReduceRegisterPanelGroupAction\fP ()"
.br
.RI "PanelState\&.Reducer\&.ReduceRegisterPanelGroupAction(PanelState, PanelState\&.RegisterPanelGroupAction) "
.ti -1c
.RI "void \fBReduceDisposePanelGroupAction\fP ()"
.br
.RI "PanelState\&.Reducer\&.ReduceDisposePanelGroupAction(PanelState, PanelState\&.DisposePanelGroupAction) "
.ti -1c
.RI "void \fBReduceRegisterPanelTabAction\fP ()"
.br
.RI "PanelState\&.Reducer\&.ReduceRegisterPanelTabAction(PanelState, PanelState\&.RegisterPanelTabAction) "
.ti -1c
.RI "void \fBReduceDisposePanelTabAction\fP ()"
.br
.RI "PanelState\&.Reducer\&.ReduceDisposePanelTabAction(PanelState, PanelState\&.DisposePanelTabAction) "
.ti -1c
.RI "void \fBReduceSetActivePanelTabAction\fP ()"
.br
.RI "PanelState\&.Reducer\&.ReduceSetActivePanelTabAction(PanelState, PanelState\&.SetActivePanelTabAction) "
.ti -1c
.RI "void \fBReduceSetPanelTabAsActiveByContextRecordKeyAction\fP ()"
.br
.RI "PanelState\&.Reducer\&.ReduceSetPanelTabAsActiveByContextRecordKeyAction(PanelState, PanelState\&.SetPanelTabAsActiveByContextRecordKeyAction) "
.ti -1c
.RI "void \fBReduceSetDragEventArgsAction\fP ()"
.br
.RI "PanelState\&.Reducer\&.ReduceSetDragEventArgsAction(PanelState, PanelState\&.SetDragEventArgsAction) "
.in -1c
.SH "Detailed Description"
.PP 
PanelState\&.Reducer 
.PP
Definition at line \fB23\fP of file \fBPanelStateTests\&.Reducer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Panels\&.States\&.PanelStateReducerTests\&.ReduceDisposePanelGroupAction ()"

.PP
PanelState\&.Reducer\&.ReduceDisposePanelGroupAction(PanelState, PanelState\&.DisposePanelGroupAction) 
.PP
Definition at line \fB49\fP of file \fBPanelStateTests\&.Reducer\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Panels\&.States\&.PanelStateReducerTests\&.ReduceDisposePanelTabAction ()"

.PP
PanelState\&.Reducer\&.ReduceDisposePanelTabAction(PanelState, PanelState\&.DisposePanelTabAction) 
.PP
Definition at line \fB152\fP of file \fBPanelStateTests\&.Reducer\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Panels\&.States\&.PanelStateReducerTests\&.ReduceRegisterPanelGroupAction ()"

.PP
PanelState\&.Reducer\&.ReduceRegisterPanelGroupAction(PanelState, PanelState\&.RegisterPanelGroupAction) 
.PP
Definition at line \fB29\fP of file \fBPanelStateTests\&.Reducer\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Panels\&.States\&.PanelStateReducerTests\&.ReduceRegisterPanelTabAction ()"

.PP
PanelState\&.Reducer\&.ReduceRegisterPanelTabAction(PanelState, PanelState\&.RegisterPanelTabAction) 
.PP
Definition at line \fB71\fP of file \fBPanelStateTests\&.Reducer\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Panels\&.States\&.PanelStateReducerTests\&.ReduceSetActivePanelTabAction ()"

.PP
PanelState\&.Reducer\&.ReduceSetActivePanelTabAction(PanelState, PanelState\&.SetActivePanelTabAction) 
.PP
Definition at line \fB188\fP of file \fBPanelStateTests\&.Reducer\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Panels\&.States\&.PanelStateReducerTests\&.ReduceSetDragEventArgsAction ()"

.PP
PanelState\&.Reducer\&.ReduceSetDragEventArgsAction(PanelState, PanelState\&.SetDragEventArgsAction) 
.PP
Definition at line \fB281\fP of file \fBPanelStateTests\&.Reducer\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Panels\&.States\&.PanelStateReducerTests\&.ReduceSetPanelTabAsActiveByContextRecordKeyAction ()"

.PP
PanelState\&.Reducer\&.ReduceSetPanelTabAsActiveByContextRecordKeyAction(PanelState, PanelState\&.SetPanelTabAsActiveByContextRecordKeyAction) 
.PP
Definition at line \fB225\fP of file \fBPanelStateTests\&.Reducer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
