.TH "Luthetus.TextEditor.Tests.Basis.Options.Models.OptionsApiTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.Options.Models.OptionsApiTests \- \fBTextEditorOptionsApi\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "TextEditorOptionsApi(ITextEditorService, LuthetusTextEditorConfig, IStorageService, StorageSync, IDispatcher) "
.ti -1c
.RI "void \fBSetTheme\fP ()"
.br
.RI "TextEditorOptionsApi\&.SetTheme(ThemeRecord) "
.ti -1c
.RI "void \fBSetShowWhitespace\fP ()"
.br
.RI "TextEditorOptionsApi\&.SetShowWhitespace(bool) "
.ti -1c
.RI "void \fBSetUseMonospaceOptimizations\fP ()"
.br
.RI "TextEditorOptionsApi\&.SetUseMonospaceOptimizations(bool) "
.ti -1c
.RI "void \fBSetShowNewlines\fP ()"
.br
.RI "TextEditorOptionsApi\&.SetShowNewlines(bool) "
.ti -1c
.RI "void \fBSetKeymap\fP ()"
.br
.RI "TextEditorOptionsApi\&.SetKeymap(Keymap) "
.ti -1c
.RI "void \fBSetHeight\fP ()"
.br
.RI "TextEditorOptionsApi\&.SetHeight(int?) "
.ti -1c
.RI "void \fBSetFontSize\fP ()"
.br
.RI "TextEditorOptionsApi\&.SetFontSize(int) "
.ti -1c
.RI "void \fBSetFontFamily\fP ()"
.br
.RI "TextEditorOptionsApi\&.SetFontFamily(string?) "
.ti -1c
.RI "void \fBSetCursorWidth\fP ()"
.br
.RI "TextEditorOptionsApi\&.SetCursorWidth(double) "
.ti -1c
.RI "void \fBSetRenderStateKey\fP ()"
.br
.RI "TextEditorOptionsApi\&.SetRenderStateKey(Key<RenderState>) "
.ti -1c
.RI "void \fBSetFromLocalStorageAsync\fP ()"
.br
.RI "\fBTextEditorOptionsApi\&.SetFromLocalStorageAsync()\fP "
.ti -1c
.RI "void \fBWriteToStorage\fP ()"
.br
.RI "\fBTextEditorOptionsApi\&.WriteToStorage()\fP "
.ti -1c
.RI "void \fBShowSettingsDialog\fP ()"
.br
.RI "\fBTextEditorOptionsApi\&.ShowSettingsDialog(bool?, string?)\fP "
.ti -1c
.RI "void \fBShowFindDialog\fP ()"
.br
.RI "\fBTextEditorOptionsApi\&.ShowFindAllDialog(bool?, string?)\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBTextEditorOptionsApi\fP 
.PP
Definition at line \fB24\fP of file \fBOptionsApiTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.Models\&.OptionsApiTests\&.Constructor ()"

.PP
TextEditorOptionsApi(ITextEditorService, LuthetusTextEditorConfig, IStorageService, StorageSync, IDispatcher) 
.PP
Definition at line \fB30\fP of file \fBOptionsApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.Models\&.OptionsApiTests\&.SetCursorWidth ()"

.PP
TextEditorOptionsApi\&.SetCursorWidth(double) 
.PP
Definition at line \fB204\fP of file \fBOptionsApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.Models\&.OptionsApiTests\&.SetFontFamily ()"

.PP
TextEditorOptionsApi\&.SetFontFamily(string?) 
.PP
Definition at line \fB182\fP of file \fBOptionsApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.Models\&.OptionsApiTests\&.SetFontSize ()"

.PP
TextEditorOptionsApi\&.SetFontSize(int) 
.PP
Definition at line \fB158\fP of file \fBOptionsApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.Models\&.OptionsApiTests\&.SetFromLocalStorageAsync ()"

.PP
\fBTextEditorOptionsApi\&.SetFromLocalStorageAsync()\fP 
.PP
Definition at line \fB252\fP of file \fBOptionsApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.Models\&.OptionsApiTests\&.SetHeight ()"

.PP
TextEditorOptionsApi\&.SetHeight(int?) 
.PP
Definition at line \fB136\fP of file \fBOptionsApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.Models\&.OptionsApiTests\&.SetKeymap ()"

.PP
TextEditorOptionsApi\&.SetKeymap(Keymap) 
.PP
Definition at line \fB114\fP of file \fBOptionsApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.Models\&.OptionsApiTests\&.SetRenderStateKey ()"

.PP
TextEditorOptionsApi\&.SetRenderStateKey(Key<RenderState>) 
.PP
Definition at line \fB228\fP of file \fBOptionsApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.Models\&.OptionsApiTests\&.SetShowNewlines ()"

.PP
TextEditorOptionsApi\&.SetShowNewlines(bool) 
.PP
Definition at line \fB98\fP of file \fBOptionsApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.Models\&.OptionsApiTests\&.SetShowWhitespace ()"

.PP
TextEditorOptionsApi\&.SetShowWhitespace(bool) 
.PP
Definition at line \fB66\fP of file \fBOptionsApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.Models\&.OptionsApiTests\&.SetTheme ()"

.PP
TextEditorOptionsApi\&.SetTheme(ThemeRecord) 
.PP
Definition at line \fB44\fP of file \fBOptionsApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.Models\&.OptionsApiTests\&.SetUseMonospaceOptimizations ()"

.PP
TextEditorOptionsApi\&.SetUseMonospaceOptimizations(bool) 
.PP
Definition at line \fB82\fP of file \fBOptionsApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.Models\&.OptionsApiTests\&.ShowFindDialog ()"

.PP
\fBTextEditorOptionsApi\&.ShowFindAllDialog(bool?, string?)\fP 
.PP
Definition at line \fB294\fP of file \fBOptionsApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.Models\&.OptionsApiTests\&.ShowSettingsDialog ()"

.PP
\fBTextEditorOptionsApi\&.ShowSettingsDialog(bool?, string?)\fP 
.PP
Definition at line \fB280\fP of file \fBOptionsApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Options\&.Models\&.OptionsApiTests\&.WriteToStorage ()"

.PP
\fBTextEditorOptionsApi\&.WriteToStorage()\fP 
.PP
Definition at line \fB266\fP of file \fBOptionsApiTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
