.TH "Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests \- \fBTextEditorModelApi\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "TextEditorModelApi(ITextEditorService, IDecorationMapperRegistry, ICompilerServiceRegistry, IBackgroundTaskService, IDispatcher) "
.ti -1c
.RI "void \fBUndoEdit\fP ()"
.br
.RI "TextEditorModelApi\&.UndoEdit(ResourceUri) "
.ti -1c
.RI "void \fBSetUsingRowEndingKind\fP ()"
.br
.RI "TextEditorModelApi\&.SetUsingLineEndKind(ResourceUri, LineEndKind) "
.ti -1c
.RI "void \fBSetResourceData\fP ()"
.br
.RI "TextEditorModelApi\&.SetResourceData(ResourceUri, DateTime) "
.ti -1c
.RI "void \fBReload\fP ()"
.br
.RI "TextEditorModelApi\&.Reload(ResourceUri, string, DateTime) "
.ti -1c
.RI "void \fBRegisterCustom\fP ()"
.br
.RI "TextEditorModelApi\&.RegisterCustom(TextEditorModel) "
.ti -1c
.RI "void \fBRegisterTemplated\fP ()"
.br
.RI "\fBTextEditorModelApi\&.RegisterTemplated(string, ResourceUri, DateTime, string, string?)\fP "
.ti -1c
.RI "void \fBRedoEditEnqueue\fP ()"
.br
.RI "TextEditorModelApi\&.RedoEdit(ResourceUri) "
.ti -1c
.RI "void \fBInsertTextEnqueue\fP ()"
.br
.RI "TextEditorModelApi\&.InsertText(ResourceUri, Key<TextEditorViewModel>, string, CancellationToken) "
.ti -1c
.RI "void \fBHandleKeyboardEventEnqueue\fP ()"
.br
.RI "TextEditorModelApi\&.HandleKeyboardEvent(ResourceUri, Key<TextEditorViewModel>, KeymapArgs, CancellationToken) "
.ti -1c
.RI "void \fBGetViewModelsOrEmpty\fP ()"
.br
.RI "\fBTextEditorModelApi\&.GetViewModelsOrEmpty(ResourceUri)\fP "
.ti -1c
.RI "void \fBGetAllText\fP ()"
.br
.RI "\fBTextEditorModelApi\&.GetAllText(ResourceUri)\fP "
.ti -1c
.RI "void \fBGetOrDefault\fP ()"
.br
.RI "\fBTextEditorModelApi\&.GetOrDefault(ResourceUri)\fP "
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.RI "\fBTextEditorModelApi\&.Dispose(ResourceUri)\fP "
.ti -1c
.RI "void \fBDeleteTextByRangeEnqueue\fP ()"
.br
.RI "TextEditorModelApi\&.DeleteTextByRange(ResourceUri, Key<TextEditorViewModel>, int, CancellationToken) "
.ti -1c
.RI "void \fBDeleteTextByMotionEnqueue_Backspace\fP ()"
.br
.RI "TextEditorModelApi\&.DeleteTextByMotion(ResourceUri, Key<TextEditorViewModel>, MotionKind, CancellationToken) "
.ti -1c
.RI "void \fBRegisterPresentationModel\fP ()"
.br
.RI "TextEditorModelApi\&.AddPresentationModel(ResourceUri, TextEditorPresentationModel) "
.in -1c
.SH "Detailed Description"
.PP 
\fBTextEditorModelApi\fP 
.PP
Definition at line \fB27\fP of file \fBTextEditorModelApiTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelApiTests\&.Constructor ()"

.PP
TextEditorModelApi(ITextEditorService, IDecorationMapperRegistry, ICompilerServiceRegistry, IBackgroundTaskService, IDispatcher) 
.PP
Definition at line \fB33\fP of file \fBTextEditorModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelApiTests\&.DeleteTextByMotionEnqueue_Backspace ()"

.PP
TextEditorModelApi\&.DeleteTextByMotion(ResourceUri, Key<TextEditorViewModel>, MotionKind, CancellationToken) 
.PP
Definition at line \fB618\fP of file \fBTextEditorModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelApiTests\&.DeleteTextByRangeEnqueue ()"

.PP
TextEditorModelApi\&.DeleteTextByRange(ResourceUri, Key<TextEditorViewModel>, int, CancellationToken) 
.PP
Definition at line \fB574\fP of file \fBTextEditorModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelApiTests\&.Dispose ()"

.PP
\fBTextEditorModelApi\&.Dispose(ResourceUri)\fP 
.PP
Definition at line \fB556\fP of file \fBTextEditorModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelApiTests\&.GetAllText ()"

.PP
\fBTextEditorModelApi\&.GetAllText(ResourceUri)\fP 
.PP
Definition at line \fB511\fP of file \fBTextEditorModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelApiTests\&.GetOrDefault ()"

.PP
\fBTextEditorModelApi\&.GetOrDefault(ResourceUri)\fP 
.PP
Definition at line \fB540\fP of file \fBTextEditorModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelApiTests\&.GetViewModelsOrEmpty ()"

.PP
\fBTextEditorModelApi\&.GetViewModelsOrEmpty(ResourceUri)\fP 
.PP
Definition at line \fB487\fP of file \fBTextEditorModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelApiTests\&.HandleKeyboardEventEnqueue ()"

.PP
TextEditorModelApi\&.HandleKeyboardEvent(ResourceUri, Key<TextEditorViewModel>, KeymapArgs, CancellationToken) 
.PP
Definition at line \fB439\fP of file \fBTextEditorModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelApiTests\&.InsertTextEnqueue ()"

.PP
TextEditorModelApi\&.InsertText(ResourceUri, Key<TextEditorViewModel>, string, CancellationToken) 
.PP
Definition at line \fB396\fP of file \fBTextEditorModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelApiTests\&.RedoEditEnqueue ()"

.PP
TextEditorModelApi\&.RedoEdit(ResourceUri) 
.PP
Definition at line \fB317\fP of file \fBTextEditorModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelApiTests\&.RegisterCustom ()"

.PP
TextEditorModelApi\&.RegisterCustom(TextEditorModel) 
.PP
Definition at line \fB239\fP of file \fBTextEditorModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelApiTests\&.RegisterPresentationModel ()"

.PP
TextEditorModelApi\&.AddPresentationModel(ResourceUri, TextEditorPresentationModel) 
.PP
Definition at line \fB663\fP of file \fBTextEditorModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelApiTests\&.RegisterTemplated ()"

.PP
\fBTextEditorModelApi\&.RegisterTemplated(string, ResourceUri, DateTime, string, string?)\fP 
.PP
Definition at line \fB282\fP of file \fBTextEditorModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelApiTests\&.Reload ()"

.PP
TextEditorModelApi\&.Reload(ResourceUri, string, DateTime) 
.PP
Definition at line \fB197\fP of file \fBTextEditorModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelApiTests\&.SetResourceData ()"

.PP
TextEditorModelApi\&.SetResourceData(ResourceUri, DateTime) 
.PP
Definition at line \fB156\fP of file \fBTextEditorModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelApiTests\&.SetUsingRowEndingKind ()"

.PP
TextEditorModelApi\&.SetUsingLineEndKind(ResourceUri, LineEndKind) 
.PP
Definition at line \fB115\fP of file \fBTextEditorModelApiTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.TextEditorModelApiTests\&.UndoEdit ()"

.PP
TextEditorModelApi\&.UndoEdit(ResourceUri) 
.PP
Definition at line \fB50\fP of file \fBTextEditorModelApiTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
