.TH "Luthetus.TextEditor.RazorLib.CompilerServices.CompilerServiceDiagnosticDecorationMapper" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.CompilerServices.CompilerServiceDiagnosticDecorationMapper
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.TextEditor\&.RazorLib\&.Decorations\&.Models\&.IDecorationMapper\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "string \fBMap\fP (byte decorationByte)"
.br
.RI "Maps a decorationByte to a CSS class that is in the form of a string\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBCompilerServiceDiagnosticDecorationMapper\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.CompilerServiceDiagnosticDecorationMapper\&.Map (byte decorationByte)"

.PP
Maps a decorationByte to a CSS class that is in the form of a string\&. 
.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.Decorations\&.Models\&.IDecorationMapper\fP\&.
.PP
Definition at line \fB8\fP of file \fBCompilerServiceDiagnosticDecorationMapper\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
