.TH "Luthetus.TextEditor.Tests.Basis.TextEditors.Models.DisplayTrackerTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.TextEditors.Models.DisplayTrackerTests \- \fBDisplayTracker\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "\fBDisplayTracker(ITextEditorService, Func<TextEditorViewModel?>, Func<TextEditorModel?>)\fP 
.br
----
.br
 DisplayTracker\&.GetViewModelFunc DisplayTracker\&.GetModelFunc \fBDisplayTracker\&.Links\fP \fBDisplayTracker\&.IsFirstDisplay\fP "
.ti -1c
.RI "void \fBIncrementLinks\fP ()"
.br
.RI "DisplayTracker\&.IncrementLinks(IState<TextEditorModelState>) "
.ti -1c
.RI "void \fBDecrementLinks\fP ()"
.br
.RI "DisplayTracker\&.DecrementLinks(IState<TextEditorModelState>) "
.ti -1c
.RI "void \fBConsumeIsFirstDisplay\fP ()"
.br
.RI "\fBDisplayTracker\&.ConsumeIsFirstDisplay()\fP "
.ti -1c
.RI "void \fBDispose\fP ()"
.br
.RI "\fBDisplayTracker\&.Dispose()\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBDisplayTracker\fP 
.PP
Definition at line \fB11\fP of file \fBDisplayTrackerTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.DisplayTrackerTests\&.Constructor ()"

.PP
\fBDisplayTracker(ITextEditorService, Func<TextEditorViewModel?>, Func<TextEditorModel?>)\fP 
.br
----
.br
 DisplayTracker\&.GetViewModelFunc DisplayTracker\&.GetModelFunc \fBDisplayTracker\&.Links\fP \fBDisplayTracker\&.IsFirstDisplay\fP 
.PP
Definition at line \fB22\fP of file \fBDisplayTrackerTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.DisplayTrackerTests\&.ConsumeIsFirstDisplay ()"

.PP
\fBDisplayTracker\&.ConsumeIsFirstDisplay()\fP 
.PP
Definition at line \fB49\fP of file \fBDisplayTrackerTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.DisplayTrackerTests\&.DecrementLinks ()"

.PP
DisplayTracker\&.DecrementLinks(IState<TextEditorModelState>) 
.PP
Definition at line \fB40\fP of file \fBDisplayTrackerTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.DisplayTrackerTests\&.Dispose ()"

.PP
\fBDisplayTracker\&.Dispose()\fP 
.PP
Definition at line \fB58\fP of file \fBDisplayTrackerTests\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.TextEditors\&.Models\&.DisplayTrackerTests\&.IncrementLinks ()"

.PP
DisplayTracker\&.IncrementLinks(IState<TextEditorModelState>) 
.PP
Definition at line \fB31\fP of file \fBDisplayTrackerTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
