.TH "Luthetus.Common.RazorLib.Panels.Models" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Panels.Models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBIPanelTab\fP"
.br
.ti -1c
.RI "class \fBPanelFacts\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "record \fBPanel\fP"
.br
.ti -1c
.RI "record \fBIDialog\fP"
.br
.in -1c
.SH "Variable Documentation"
.PP 
.SS "record Luthetus\&.Common\&.RazorLib\&.Panels\&.Models\&.IDialog"

.PP
Definition at line \fB17\fP of file \fBPanel\&.cs\fP\&.
.SS "record Luthetus\&.Common\&.RazorLib\&.Panels\&.Models\&.Panel"

.PP
Definition at line \fB17\fP of file \fBPanel\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
