.TH "Luthetus.CompilerServices.CSharp.AllCSharpSyntaxUntouched" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.CSharp.AllCSharpSyntaxUntouched
.SH SYNOPSIS
.br
.PP
.SH "Detailed Description"
.PP 
Definition at line \fB4\fP of file \fBAllCSharpSyntax_Untouched\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
