.TH "Luthetus.TextEditor.Tests.Basis.Characters.Models.RichCharacterTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.Characters.Models.RichCharacterTests \- \fBRichCharacter\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBValue\fP ()"
.br
.RI "\fBRichCharacter\&.Value\fP 
.br
----
.br
 \fBRichCharacter\&.DecorationByte\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBRichCharacter\fP 
.PP
Definition at line \fB9\fP of file \fBRichCharacterTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.Characters\&.Models\&.RichCharacterTests\&.Value ()"

.PP
\fBRichCharacter\&.Value\fP 
.br
----
.br
 \fBRichCharacter\&.DecorationByte\fP 
.PP
Definition at line \fB17\fP of file \fBRichCharacterTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
