.TH "Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.CodeBlockNode" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.CodeBlockNode \- The \fBCodeBlockNode\fP is used for storing a sequence of statements (or a single expression-statement)\&.
.br

.br
 Perhaps one might use \fBCodeBlockNode\fP for the body of a class definition, for example\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.ISyntaxNode\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCodeBlockNode\fP (ImmutableArray< \fBISyntax\fP > childList)"
.br
.ti -1c
.RI "\fBCodeBlockNode\fP (ImmutableArray< \fBISyntax\fP > childList, ImmutableArray< \fBTextEditorDiagnostic\fP > diagnostics)"
.br
.ti -1c
.RI "\fBISyntax\fP[] \fBGetChildList\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "ImmutableArray< \fBTextEditorDiagnostic\fP > \fBDiagnosticsList\fP\fR [get]\fP"
.br
.ti -1c
.RI "bool \fBIsFabricated\fP\fR [get]\fP"
.br
.RI "\fBIsFabricated\fP refers to when the ParserSession expected a node to be valid, but it wasn't\&.
.br

.br
For example, a function invocation on an undefined function will construct a BoundFunctionInvocationNode with \fBIsFabricated\fP set to true\&. "
.ti -1c
.RI "\fBSyntaxKind\fP \fBSyntaxKind\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
The \fBCodeBlockNode\fP is used for storing a sequence of statements (or a single expression-statement)\&.
.br

.br
 Perhaps one might use \fBCodeBlockNode\fP for the body of a class definition, for example\&. 
.PP
Definition at line \fB10\fP of file \fBCodeBlockNode\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.CodeBlockNode\&.CodeBlockNode (ImmutableArray< \fBISyntax\fP > childList)"

.PP
Definition at line \fB12\fP of file \fBCodeBlockNode\&.cs\fP\&.
.SS "Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.CodeBlockNode\&.CodeBlockNode (ImmutableArray< \fBISyntax\fP > childList, ImmutableArray< \fBTextEditorDiagnostic\fP > diagnostics)"

.PP
Definition at line \fB19\fP of file \fBCodeBlockNode\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBISyntax\fP[] Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.CodeBlockNode\&.GetChildList ()"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.ISyntaxNode\fP\&.
.PP
Definition at line \fB35\fP of file \fBCodeBlockNode\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "ImmutableArray<\fBTextEditorDiagnostic\fP> Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.CodeBlockNode\&.DiagnosticsList\fR [get]\fP"

.PP
Definition at line \fB30\fP of file \fBCodeBlockNode\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.CodeBlockNode\&.IsFabricated\fR [get]\fP"

.PP
\fBIsFabricated\fP refers to when the ParserSession expected a node to be valid, but it wasn't\&.
.br

.br
For example, a function invocation on an undefined function will construct a BoundFunctionInvocationNode with \fBIsFabricated\fP set to true\&. 
.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.ISyntax\fP\&.
.PP
Definition at line \fB32\fP of file \fBCodeBlockNode\&.cs\fP\&.
.SS "\fBSyntaxKind\fP Luthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.Nodes\&.CodeBlockNode\&.SyntaxKind\fR [get]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Syntax\&.ISyntax\fP\&.
.PP
Definition at line \fB33\fP of file \fBCodeBlockNode\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
