.TH "Luthetus.Ide.RazorLib.ComponentRenderers.Models.IGitDisplayRendererType" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.ComponentRenderers.Models.IGitDisplayRendererType
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.Extensions\&.Git\&.Displays\&.GitChangesDisplay\fP\&.
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBIGitDisplayRendererType\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
