.TH "Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.ISolutionVisualizationDrawingCircle" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.ISolutionVisualizationDrawingCircle
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.ISolutionVisualizationDrawing\fP\&.
.PP
Inherited by \fBLuthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.SolutionVisualizationDrawingCircle< TItem >\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBCenterX\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBCenterY\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBRadius\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBFill\fP\fR [get, set]\fP"
.br
.in -1c

Properties inherited from \fBLuthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.ISolutionVisualizationDrawing\fP
.in +1c
.ti -1c
.RI "object \fBItem\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBSolutionVisualizationDrawingKind\fP \fBSolutionVisualizationDrawingKind\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBSolutionVisualizationItemKind\fP \fBSolutionVisualizationItemKind\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "int \fBRenderCycle\fP\fR [get, set]\fP"
.br
.RI "Macro-filter for the order that things render\&. 0 is the first "render cycle", and anything with that value will render first\&. "
.ti -1c
.RI "int \fBRenderCycleSequence\fP\fR [get, set]\fP"
.br
.RI "Micro-filter for the order that things render\&. 0 is the first "render cycle sequence", and anything with that value would have been the first in a given render cycle to have rendered\&. "
.in -1c
.SS "Additional Inherited Members"


Public Member Functions inherited from \fBLuthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.ISolutionVisualizationDrawing\fP
.in +1c
.ti -1c
.RI "\fBMenuOptionRecord\fP \fBGetMenuOptionRecord\fP (\fBSolutionVisualizationModel\fP localSolutionVisualizationModel, \fBIEnvironmentProvider\fP environmentProvider, \fBLuthetusTextEditorConfig\fP textEditorConfig, IServiceProvider serviceProvider)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBISolutionVisualizationDrawingCircle\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.ISolutionVisualizationDrawingCircle\&.CenterX\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.SolutionVisualizationDrawingCircle< TItem >\fP\&.
.PP
Definition at line \fB5\fP of file \fBISolutionVisualizationDrawingCircle\&.cs\fP\&.
.SS "int Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.ISolutionVisualizationDrawingCircle\&.CenterY\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.SolutionVisualizationDrawingCircle< TItem >\fP\&.
.PP
Definition at line \fB6\fP of file \fBISolutionVisualizationDrawingCircle\&.cs\fP\&.
.SS "string Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.ISolutionVisualizationDrawingCircle\&.Fill\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.SolutionVisualizationDrawingCircle< TItem >\fP\&.
.PP
Definition at line \fB8\fP of file \fBISolutionVisualizationDrawingCircle\&.cs\fP\&.
.SS "int Luthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.ISolutionVisualizationDrawingCircle\&.Radius\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.Internals\&.SolutionVisualizationDrawingCircle< TItem >\fP\&.
.PP
Definition at line \fB7\fP of file \fBISolutionVisualizationDrawingCircle\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
