.TH "Luthetus.TextEditor.Tests.Basis.CompilerServices.EvaluatorResultTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.Tests.Basis.CompilerServices.EvaluatorResultTests \- \fBEvaluatorResult\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "EvaluatorResult(Type, object) 
.br
----
.br
 \fBEvaluatorResult\&.Type\fP \fBEvaluatorResult\&.Result\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBEvaluatorResult\fP 
.PP
Definition at line \fB8\fP of file \fBEvaluatorResultTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.TextEditor\&.Tests\&.Basis\&.CompilerServices\&.EvaluatorResultTests\&.Constructor ()"

.PP
EvaluatorResult(Type, object) 
.br
----
.br
 \fBEvaluatorResult\&.Type\fP \fBEvaluatorResult\&.Result\fP 
.PP
Definition at line \fB17\fP of file \fBEvaluatorResultTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
