.TH "Luthetus.Extensions.DotNet.Installations.Displays.LuthetusExtensionsDotNetInitializer" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.Installations.Displays.LuthetusExtensionsDotNetInitializer
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInitialized\fP ()"
.br
.ti -1c
.RI "override void \fBOnAfterRender\fP (bool firstRender)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB38\fP of file \fBLuthetusExtensionsDotNetInitializer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Luthetus\&.Extensions\&.DotNet\&.Installations\&.Displays\&.LuthetusExtensionsDotNetInitializer\&.OnAfterRender (bool firstRender)\fR [protected]\fP"

.PP
Definition at line \fB96\fP of file \fBLuthetusExtensionsDotNetInitializer\&.cs\fP\&.
.SS "override void Luthetus\&.Extensions\&.DotNet\&.Installations\&.Displays\&.LuthetusExtensionsDotNetInitializer\&.OnInitialized ()\fR [protected]\fP"

.PP
Definition at line \fB78\fP of file \fBLuthetusExtensionsDotNetInitializer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
