.TH "Luthetus.Common.RazorLib.TreeViews.Models.TreeViewMouseEventHandler" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.TreeViews.Models.TreeViewMouseEventHandler \- To implement custom MouseEvent handling logic one should inherit \fBTreeViewMouseEventHandler\fP and override the corresponding method\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.Extensions\&.DotNet\&.CompilerServices\&.Models\&.CompilerServiceExplorerTreeViewMouseEventHandler\fP, \fBLuthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.SolutionExplorerTreeViewMouseEventHandler\fP, \fBLuthetus\&.Extensions\&.DotNet\&.Outputs\&.Models\&.OutputTreeViewMouseEventHandler\fP, \fBLuthetus\&.Extensions\&.DotNet\&.TestExplorers\&.Models\&.TestExplorerTreeViewMouseEventHandler\fP, \fBLuthetus\&.Extensions\&.Git\&.Models\&.GitTreeViewMouseEventHandler\fP, \fBLuthetus\&.Ide\&.RazorLib\&.CodeSearches\&.Models\&.CodeSearchTreeViewMouseEventHandler\fP, \fBLuthetus\&.Ide\&.RazorLib\&.FolderExplorers\&.Models\&.FolderExplorerTreeViewMouseEventHandler\fP, \fBLuthetus\&.Ide\&.RazorLib\&.InputFiles\&.Models\&.InputFileTreeViewMouseEventHandler\fP, and \fBLuthetus\&.TextEditor\&.RazorLib\&.FindAlls\&.Models\&.FindAllTreeViewMouseEventHandler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTreeViewMouseEventHandler\fP (\fBITreeViewService\fP treeViewService, \fBIBackgroundTaskService\fP backgroundTaskService)"
.br
.ti -1c
.RI "virtual Task \fBOnClickAsync\fP (\fBTreeViewCommandArgs\fP commandArgs)"
.br
.RI "Invoked, and awaited, as part of the async UI event handler for 'onclick' events\&.
.br

.br
\&. "
.ti -1c
.RI "virtual Task \fBOnDoubleClickAsync\fP (\fBTreeViewCommandArgs\fP commandArgs)"
.br
.RI "Invoked, and awaited, as part of the async UI event handler for 'ondblclick' events\&.
.br

.br
\&. "
.ti -1c
.RI "virtual Task \fBOnMouseDownAsync\fP (\fBTreeViewCommandArgs\fP commandArgs)"
.br
.RI "Invoked, and awaited, as part of the async UI event handler for 'onmousedown' events\&.
.br

.br
\&. "
.in -1c
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "virtual void \fBOnClick\fP (\fBTreeViewCommandArgs\fP commandArgs)"
.br
.RI "Invoked, and awaited, as part of the synchronous UI event handler for 'onclick' events\&.
.br

.br
\&. "
.ti -1c
.RI "virtual void \fBOnDoubleClick\fP (\fBTreeViewCommandArgs\fP commandArgs)"
.br
.RI "Invoked, and awaited, as part of the synchronous UI event handler for 'ondblclick' events\&.
.br

.br
\&. "
.ti -1c
.RI "virtual void \fBOnMouseDown\fP (\fBTreeViewCommandArgs\fP commandArgs)"
.br
.RI "Invoked, and awaited, as part of the synchronous UI event handler for 'onmousedown' events\&.
.br

.br
\&. "
.in -1c
.SS "Protected Attributes"

.in +1c
.ti -1c
.RI "readonly \fBITreeViewService\fP \fBTreeViewService\fP"
.br
.ti -1c
.RI "readonly \fBIBackgroundTaskService\fP \fBBackgroundTaskService\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
To implement custom MouseEvent handling logic one should inherit \fBTreeViewMouseEventHandler\fP and override the corresponding method\&. 
.PP
Definition at line \fB10\fP of file \fBTreeViewMouseEventHandler\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewMouseEventHandler\&.TreeViewMouseEventHandler (\fBITreeViewService\fP treeViewService, \fBIBackgroundTaskService\fP backgroundTaskService)"

.PP
Definition at line \fB15\fP of file \fBTreeViewMouseEventHandler\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "virtual void Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewMouseEventHandler\&.OnClick (\fBTreeViewCommandArgs\fP commandArgs)\fR [protected]\fP, \fR [virtual]\fP"

.PP
Invoked, and awaited, as part of the synchronous UI event handler for 'onclick' events\&.
.br

.br
\&. This method is invoked by the async version: 'OnMouseDownAsync(TreeViewCommandArgs)'\&.
.br

.br

.PP
Any overrides of this method are intended to have 'base\&.MethodBeingOverridden()' prior to their code, but for this method it makes no difference if one puts it after their code\&.
.br

.br
 
.PP
Reimplemented in \fBLuthetus\&.Ide\&.RazorLib\&.InputFiles\&.Models\&.InputFileTreeViewMouseEventHandler\fP\&.
.PP
Definition at line \fB76\fP of file \fBTreeViewMouseEventHandler\&.cs\fP\&.
.SS "virtual Task Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewMouseEventHandler\&.OnClickAsync (\fBTreeViewCommandArgs\fP commandArgs)\fR [virtual]\fP"

.PP
Invoked, and awaited, as part of the async UI event handler for 'onclick' events\&.
.br

.br
\&. The synchronous version: 'OnClick(TreeViewCommandArgs)' will be invoked immediately from within this method, to allow the synchronous code to block the UI purposefully\&.

.PP
Any overrides of this method are intended to have 'base\&.MethodBeingOverridden()' prior to their code\&.
.br

.br
 
.PP
Definition at line \fB31\fP of file \fBTreeViewMouseEventHandler\&.cs\fP\&.
.SS "virtual void Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewMouseEventHandler\&.OnDoubleClick (\fBTreeViewCommandArgs\fP commandArgs)\fR [protected]\fP, \fR [virtual]\fP"

.PP
Invoked, and awaited, as part of the synchronous UI event handler for 'ondblclick' events\&.
.br

.br
\&. This method is invoked by the async version: 'OnDoubleClickAsync(TreeViewCommandArgs)'\&.
.br

.br

.PP
Any overrides of this method are intended to have 'base\&.MethodBeingOverridden()' prior to their code, but for this method it makes no difference if one puts it after their code\&.
.br

.br
 
.PP
Reimplemented in \fBLuthetus\&.Extensions\&.Git\&.Models\&.GitTreeViewMouseEventHandler\fP\&.
.PP
Definition at line \fB89\fP of file \fBTreeViewMouseEventHandler\&.cs\fP\&.
.SS "virtual Task Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewMouseEventHandler\&.OnDoubleClickAsync (\fBTreeViewCommandArgs\fP commandArgs)\fR [virtual]\fP"

.PP
Invoked, and awaited, as part of the async UI event handler for 'ondblclick' events\&.
.br

.br
\&. The synchronous version: 'OnDoubleClick(TreeViewCommandArgs)' will be invoked immediately from within this method, to allow the synchronous code to block the UI purposefully\&.

.PP
Any overrides of this method are intended to have 'base\&.MethodBeingOverridden()' prior to their code\&.
.br

.br
 
.PP
Reimplemented in \fBLuthetus\&.Extensions\&.DotNet\&.CompilerServices\&.Models\&.CompilerServiceExplorerTreeViewMouseEventHandler\fP, \fBLuthetus\&.Extensions\&.DotNet\&.DotNetSolutions\&.Models\&.SolutionExplorerTreeViewMouseEventHandler\fP, \fBLuthetus\&.Extensions\&.DotNet\&.Outputs\&.Models\&.OutputTreeViewMouseEventHandler\fP, \fBLuthetus\&.Extensions\&.DotNet\&.TestExplorers\&.Models\&.TestExplorerTreeViewMouseEventHandler\fP, \fBLuthetus\&.Ide\&.RazorLib\&.CodeSearches\&.Models\&.CodeSearchTreeViewMouseEventHandler\fP, \fBLuthetus\&.Ide\&.RazorLib\&.FolderExplorers\&.Models\&.FolderExplorerTreeViewMouseEventHandler\fP, \fBLuthetus\&.Ide\&.RazorLib\&.InputFiles\&.Models\&.InputFileTreeViewMouseEventHandler\fP, and \fBLuthetus\&.TextEditor\&.RazorLib\&.FindAlls\&.Models\&.FindAllTreeViewMouseEventHandler\fP\&.
.PP
Definition at line \fB46\fP of file \fBTreeViewMouseEventHandler\&.cs\fP\&.
.SS "virtual void Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewMouseEventHandler\&.OnMouseDown (\fBTreeViewCommandArgs\fP commandArgs)\fR [protected]\fP, \fR [virtual]\fP"

.PP
Invoked, and awaited, as part of the synchronous UI event handler for 'onmousedown' events\&.
.br

.br
\&. This method is invoked by the async version: 'OnMouseDownAsync(TreeViewCommandArgs)'\&.
.br

.br

.PP
Any overrides of this method are intended to have 'base\&.MethodBeingOverridden()' prior to their code\&.
.br

.br
 
.PP
Definition at line \fB101\fP of file \fBTreeViewMouseEventHandler\&.cs\fP\&.
.SS "virtual Task Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewMouseEventHandler\&.OnMouseDownAsync (\fBTreeViewCommandArgs\fP commandArgs)\fR [virtual]\fP"

.PP
Invoked, and awaited, as part of the async UI event handler for 'onmousedown' events\&.
.br

.br
\&. The synchronous version: 'OnMouseDown(TreeViewCommandArgs)' will be invoked immediately from within this method, to allow the synchronous code to block the UI purposefully\&.
.br

.br

.PP
Any overrides of this method are intended to have 'base\&.MethodBeingOverridden()' prior to their code\&.
.br

.br
 
.PP
Definition at line \fB61\fP of file \fBTreeViewMouseEventHandler\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "readonly \fBIBackgroundTaskService\fP Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewMouseEventHandler\&.BackgroundTaskService\fR [protected]\fP"

.PP
Definition at line \fB13\fP of file \fBTreeViewMouseEventHandler\&.cs\fP\&.
.SS "readonly \fBITreeViewService\fP Luthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewMouseEventHandler\&.TreeViewService\fR [protected]\fP"

.PP
Definition at line \fB12\fP of file \fBTreeViewMouseEventHandler\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
