.TH "Luthetus.Extensions.DotNet.Tests.Basis.CompilerServices.Models.CompilerServiceExplorerTreeViewMouseEventHandlerTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.Tests.Basis.CompilerServices.Models.CompilerServiceExplorerTreeViewMouseEventHandlerTests \- CompilerServiceExplorerTreeViewMouseEventHandler  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "CompilerServiceExplorerTreeViewMouseEventHandler(EditorSync, ITreeViewService, IBackgroundTaskService) "
.ti -1c
.RI "void \fBOnDoubleClickAsync\fP ()"
.br
.RI "CompilerServiceExplorerTreeViewMouseEventHandler\&.OnDoubleClickAsync(TreeViewCommandArgs) "
.in -1c
.SH "Detailed Description"
.PP 
CompilerServiceExplorerTreeViewMouseEventHandler 
.PP
Definition at line \fB6\fP of file \fBCompilerServiceExplorerTreeViewMouseEventHandlerTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.CompilerServices\&.Models\&.CompilerServiceExplorerTreeViewMouseEventHandlerTests\&.Constructor ()"

.PP
CompilerServiceExplorerTreeViewMouseEventHandler(EditorSync, ITreeViewService, IBackgroundTaskService) 
.PP
Definition at line \fB12\fP of file \fBCompilerServiceExplorerTreeViewMouseEventHandlerTests\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.CompilerServices\&.Models\&.CompilerServiceExplorerTreeViewMouseEventHandlerTests\&.OnDoubleClickAsync ()"

.PP
CompilerServiceExplorerTreeViewMouseEventHandler\&.OnDoubleClickAsync(TreeViewCommandArgs) 
.PP
Definition at line \fB21\fP of file \fBCompilerServiceExplorerTreeViewMouseEventHandlerTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
