.TH "Luthetus.Ide.RazorLib.CommandLines.Models.FormattedCommand" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.CommandLines.Models.FormattedCommand
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBFormattedCommand\fP (string targetFileName, IEnumerable< string > argumentsList)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBTargetFileName\fP\fR [get]\fP"
.br
.ti -1c
.RI "IEnumerable< string > \fBArgumentsList\fP\fR [get]\fP"
.br
.ti -1c
.RI "string? \fBHACK_ArgumentsString\fP\fR [get, set]\fP"
.br
.RI "This property is being used tentatively during the development of an integrated terminal\&.
.br

.br
\&. "
.ti -1c
.RI "string \fBTag\fP = string\&.Empty\fR [get, set]\fP"
.br
.RI "It is uncertain whether this tag property is a good idea\&. It allows one to easily re-use an Terminals\&.Models\&.IOutputParser\&.
.br

.br
\&. "
.ti -1c
.RI "string \fBValue\fP\fR [get]\fP"
.br
.RI "The command in string form\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB5\fP of file \fBFormattedCommand\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Ide\&.RazorLib\&.CommandLines\&.Models\&.FormattedCommand\&.FormattedCommand (string targetFileName, IEnumerable< string > argumentsList)"

.PP
Definition at line \fB7\fP of file \fBFormattedCommand\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "IEnumerable<string> Luthetus\&.Ide\&.RazorLib\&.CommandLines\&.Models\&.FormattedCommand\&.ArgumentsList\fR [get]\fP"

.PP
Definition at line \fB14\fP of file \fBFormattedCommand\&.cs\fP\&.
.SS "string? Luthetus\&.Ide\&.RazorLib\&.CommandLines\&.Models\&.FormattedCommand\&.HACK_ArgumentsString\fR [get]\fP, \fR [set]\fP"

.PP
This property is being used tentatively during the development of an integrated terminal\&.
.br

.br
\&. This allows for the terminal to be usable without lexing the arguments individually, but instead as just a raw string that is passed along\&.
.br

.br

.PP
(2024-04-07) 
.PP
Definition at line \fB25\fP of file \fBFormattedCommand\&.cs\fP\&.
.SS "string Luthetus\&.Ide\&.RazorLib\&.CommandLines\&.Models\&.FormattedCommand\&.Tag = string\&.Empty\fR [get]\fP, \fR [set]\fP"

.PP
It is uncertain whether this tag property is a good idea\&. It allows one to easily re-use an Terminals\&.Models\&.IOutputParser\&.
.br

.br
\&. By, the output parser being provided the Terminals\&.Models\&.TerminalCommand which caused the output\&.
.br

.br

.PP
But, determining the command that was ran would require parsing the \fBHACK_ArgumentsString\fP, because even though \fBTargetFileName\fP would be for example "git", one still doesn't know if it was "git add" or "git commit" etc\&.\&.\&.
.br

.br

.PP
Therefore this \fBTag\fP can be used to identify more specifically what command was ran, allowing the Terminals\&.Models\&.IOutputParser to parse accordingly\&.
.br

.br

.PP
(2024-05-20) 
.PP
Definition at line \fB42\fP of file \fBFormattedCommand\&.cs\fP\&.
.SS "string Luthetus\&.Ide\&.RazorLib\&.CommandLines\&.Models\&.FormattedCommand\&.TargetFileName\fR [get]\fP"

.PP
Definition at line \fB13\fP of file \fBFormattedCommand\&.cs\fP\&.
.SS "string Luthetus\&.Ide\&.RazorLib\&.CommandLines\&.Models\&.FormattedCommand\&.Value\fR [get]\fP"

.PP
The command in string form\&. 
.PP
Definition at line \fB45\fP of file \fBFormattedCommand\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
