.TH "Luthetus.CompilerServices.Xml.Html.Decoration" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.Xml.Html.Decoration
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBTextEditorHtmlDecorationMapper\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBHtmlDecorationKind\fP { \fBNone\fP, \fBAttributeName\fP, \fBAttributeValue\fP, \fBComment\fP, \fBCustomTagName\fP, \fBEntityReference\fP, \fBHtmlCode\fP, \fBInjectedLanguageFragment\fP, \fBInjectedLanguageComponent\fP, \fBTagName\fP, \fBTag\fP, \fBError\fP, \fBInjectedLanguageCodeBlock\fP, \fBInjectedLanguageCodeBlockTag\fP, \fBInjectedLanguageKeyword\fP, \fBInjectedLanguageTagHelperAttribute\fP, \fBInjectedLanguageTagHelperElement\fP, \fBInjectedLanguageMethod\fP, \fBInjectedLanguageVariable\fP, \fBInjectedLanguageType\fP, \fBInjectedLanguageStringLiteral\fP }"
.br
.in -1c
.SH "Enumeration Type Documentation"
.PP 
.SS "enum \fBLuthetus\&.CompilerServices\&.Xml\&.Html\&.Decoration\&.HtmlDecorationKind\fP"

.PP
\fBEnumerator\fP
.in +1c
.TP
\f(BINone \fP
.TP
\f(BIAttributeName \fP
.TP
\f(BIAttributeValue \fP
.TP
\f(BIComment \fP
.TP
\f(BICustomTagName \fP
.TP
\f(BIEntityReference \fP
.TP
\f(BIHtmlCode \fP
.TP
\f(BIInjectedLanguageFragment \fP
.TP
\f(BIInjectedLanguageComponent \fP
.TP
\f(BITagName \fP
.TP
\f(BITag \fP
.TP
\f(BIError \fP
.TP
\f(BIInjectedLanguageCodeBlock \fP
.TP
\f(BIInjectedLanguageCodeBlockTag \fP
.TP
\f(BIInjectedLanguageKeyword \fP
.TP
\f(BIInjectedLanguageTagHelperAttribute \fP
.TP
\f(BIInjectedLanguageTagHelperElement \fP
.TP
\f(BIInjectedLanguageMethod \fP
.TP
\f(BIInjectedLanguageVariable \fP
.TP
\f(BIInjectedLanguageType \fP
.TP
\f(BIInjectedLanguageStringLiteral \fP
.PP
Definition at line \fB3\fP of file \fBHtmlDecorationKind\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
