.TH "Luthetus.Extensions.DotNet.CommandLines.Models.DiagnosticTextSpan" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.CommandLines.Models.DiagnosticTextSpan
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDiagnosticTextSpan\fP (int startInclusiveIndex, int endExclusiveIndex, string sourceText)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "int \fBStartInclusiveIndex\fP\fR [get]\fP"
.br
.ti -1c
.RI "int \fBEndExclusiveIndex\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBText\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBDiagnosticTextSpan\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Extensions\&.DotNet\&.CommandLines\&.Models\&.DiagnosticTextSpan\&.DiagnosticTextSpan (int startInclusiveIndex, int endExclusiveIndex, string sourceText)"

.PP
Definition at line \fB5\fP of file \fBDiagnosticTextSpan\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "int Luthetus\&.Extensions\&.DotNet\&.CommandLines\&.Models\&.DiagnosticTextSpan\&.EndExclusiveIndex\fR [get]\fP"

.PP
Definition at line \fB19\fP of file \fBDiagnosticTextSpan\&.cs\fP\&.
.SS "int Luthetus\&.Extensions\&.DotNet\&.CommandLines\&.Models\&.DiagnosticTextSpan\&.StartInclusiveIndex\fR [get]\fP"

.PP
Definition at line \fB18\fP of file \fBDiagnosticTextSpan\&.cs\fP\&.
.SS "string Luthetus\&.Extensions\&.DotNet\&.CommandLines\&.Models\&.DiagnosticTextSpan\&.Text\fR [get]\fP"

.PP
Definition at line \fB20\fP of file \fBDiagnosticTextSpan\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
