.TH "Luthetus.Ide.RazorLib.Menus.Models.MenuOptionsFactory" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.Menus.Models.MenuOptionsFactory
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.IMenuOptionsFactory\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBMenuOptionsFactory\fP (\fBIIdeComponentRenderers\fP ideComponentRenderers, \fBICommonComponentRenderers\fP commonComponentRenderers, \fBIFileSystemProvider\fP fileSystemProvider, \fBIEnvironmentProvider\fP environmentProvider, \fBIClipboardService\fP clipboardService, \fBIBackgroundTaskService\fP backgroundTaskService)"
.br
.ti -1c
.RI "\fBMenuOptionRecord\fP \fBNewEmptyFile\fP (\fBIAbsolutePath\fP parentDirectory, Func< Task > onAfterCompletion)"
.br
.ti -1c
.RI "\fBMenuOptionRecord\fP \fBNewTemplatedFile\fP (\fBNamespacePath\fP parentDirectory, Func< Task > onAfterCompletion)"
.br
.ti -1c
.RI "\fBMenuOptionRecord\fP \fBNewDirectory\fP (\fBIAbsolutePath\fP parentDirectory, Func< Task > onAfterCompletion)"
.br
.ti -1c
.RI "\fBMenuOptionRecord\fP \fBDeleteFile\fP (\fBIAbsolutePath\fP absolutePath, Func< Task > onAfterCompletion)"
.br
.ti -1c
.RI "\fBMenuOptionRecord\fP \fBRenameFile\fP (\fBIAbsolutePath\fP sourceAbsolutePath, IDispatcher dispatcher, Func< Task > onAfterCompletion)"
.br
.ti -1c
.RI "\fBMenuOptionRecord\fP \fBCopyFile\fP (\fBIAbsolutePath\fP absolutePath, Func< Task > onAfterCompletion)"
.br
.ti -1c
.RI "\fBMenuOptionRecord\fP \fBCutFile\fP (\fBIAbsolutePath\fP absolutePath, Func< Task > onAfterCompletion)"
.br
.ti -1c
.RI "\fBMenuOptionRecord\fP \fBPasteClipboard\fP (\fBIAbsolutePath\fP directoryAbsolutePath, Func< Task > onAfterCompletion)"
.br
.in -1c
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static DirectoryInfo \fBCopyFilesRecursively\fP (DirectoryInfo source, DirectoryInfo target)"
.br
.RI "Looking into copying and pasting a directory https://stackoverflow.com/questions/58744/copy-the-entire-contents-of-a-directory-in-c-sharp\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB17\fP of file \fBMenuOptionsFactory\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.MenuOptionsFactory\&.MenuOptionsFactory (\fBIIdeComponentRenderers\fP ideComponentRenderers, \fBICommonComponentRenderers\fP commonComponentRenderers, \fBIFileSystemProvider\fP fileSystemProvider, \fBIEnvironmentProvider\fP environmentProvider, \fBIClipboardService\fP clipboardService, \fBIBackgroundTaskService\fP backgroundTaskService)"

.PP
Definition at line \fB26\fP of file \fBMenuOptionsFactory\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBMenuOptionRecord\fP Luthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.MenuOptionsFactory\&.CopyFile (\fBIAbsolutePath\fP absolutePath, Func< Task > onAfterCompletion)"

.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.IMenuOptionsFactory\fP\&.
.PP
Definition at line \fB158\fP of file \fBMenuOptionsFactory\&.cs\fP\&.
.SS "DirectoryInfo Luthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.MenuOptionsFactory\&.CopyFilesRecursively (DirectoryInfo source, DirectoryInfo target)\fR [static]\fP"

.PP
Looking into copying and pasting a directory https://stackoverflow.com/questions/58744/copy-the-entire-contents-of-a-directory-in-c-sharp\&. 
.PP
Definition at line \fB454\fP of file \fBMenuOptionsFactory\&.cs\fP\&.
.SS "\fBMenuOptionRecord\fP Luthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.MenuOptionsFactory\&.CutFile (\fBIAbsolutePath\fP absolutePath, Func< Task > onAfterCompletion)"

.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.IMenuOptionsFactory\fP\&.
.PP
Definition at line \fB168\fP of file \fBMenuOptionsFactory\&.cs\fP\&.
.SS "\fBMenuOptionRecord\fP Luthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.MenuOptionsFactory\&.DeleteFile (\fBIAbsolutePath\fP absolutePath, Func< Task > onAfterCompletion)"

.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.IMenuOptionsFactory\fP\&.
.PP
Definition at line \fB114\fP of file \fBMenuOptionsFactory\&.cs\fP\&.
.SS "\fBMenuOptionRecord\fP Luthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.MenuOptionsFactory\&.NewDirectory (\fBIAbsolutePath\fP parentDirectory, Func< Task > onAfterCompletion)"

.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.IMenuOptionsFactory\fP\&.
.PP
Definition at line \fB94\fP of file \fBMenuOptionsFactory\&.cs\fP\&.
.SS "\fBMenuOptionRecord\fP Luthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.MenuOptionsFactory\&.NewEmptyFile (\fBIAbsolutePath\fP parentDirectory, Func< Task > onAfterCompletion)"

.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.IMenuOptionsFactory\fP\&.
.PP
Definition at line \fB42\fP of file \fBMenuOptionsFactory\&.cs\fP\&.
.SS "\fBMenuOptionRecord\fP Luthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.MenuOptionsFactory\&.NewTemplatedFile (\fBNamespacePath\fP parentDirectory, Func< Task > onAfterCompletion)"

.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.IMenuOptionsFactory\fP\&.
.PP
Definition at line \fB68\fP of file \fBMenuOptionsFactory\&.cs\fP\&.
.SS "\fBMenuOptionRecord\fP Luthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.MenuOptionsFactory\&.PasteClipboard (\fBIAbsolutePath\fP directoryAbsolutePath, Func< Task > onAfterCompletion)"

.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.IMenuOptionsFactory\fP\&.
.PP
Definition at line \fB178\fP of file \fBMenuOptionsFactory\&.cs\fP\&.
.SS "\fBMenuOptionRecord\fP Luthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.MenuOptionsFactory\&.RenameFile (\fBIAbsolutePath\fP sourceAbsolutePath, IDispatcher dispatcher, Func< Task > onAfterCompletion)"

.PP
Implements \fBLuthetus\&.Ide\&.RazorLib\&.Menus\&.Models\&.IMenuOptionsFactory\fP\&.
.PP
Definition at line \fB134\fP of file \fBMenuOptionsFactory\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
