.TH "Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.BodyDriver" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.BodyDriver
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBodyDriver\fP (\fBTextEditorViewModelDisplay\fP textEditorViewModelDisplay)"
.br
.ti -1c
.RI "void \fBGetRenderFragment\fP (\fBTextEditorRenderBatchValidated\fP renderBatch)"
.br
.ti -1c
.RI "string \fBGetBodyStyleCss\fP (\fBTextEditorRenderBatchValidated\fP renderBatchLocal)"
.br
.ti -1c
.RI "string \fBRowSection_GetRowStyleCss\fP (\fBTextEditorRenderBatchValidated\fP renderBatchLocal, int index, double? virtualizedRowLeftInPixels)"
.br
.ti -1c
.RI "string \fBRowSection_GetCssClass\fP (\fBTextEditorRenderBatchValidated\fP renderBatchLocal, byte decorationByte)"
.br
.ti -1c
.RI "void \fBRowSection_AppendTextEscaped\fP (\fBTextEditorRenderBatchValidated\fP renderBatchLocal, StringBuilder spanBuilder, \fBRichCharacter\fP richCharacter, string tabKeyOutput, string spaceKeyOutput)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "readonly \fBTextEditorViewModelDisplay\fP \fB_root\fP"
.br
.ti -1c
.RI "\fBTextEditorRenderBatchValidated\fP \fB_renderBatch\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBGlobalShowNewlines\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBBodyDriver\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.BodyDriver\&.BodyDriver (\fBTextEditorViewModelDisplay\fP textEditorViewModelDisplay)"

.PP
Definition at line \fB12\fP of file \fBBodyDriver\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.BodyDriver\&.GetBodyStyleCss (\fBTextEditorRenderBatchValidated\fP renderBatchLocal)"

.PP
Definition at line \fB31\fP of file \fBBodyDriver\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.BodyDriver\&.GetRenderFragment (\fBTextEditorRenderBatchValidated\fP renderBatch)"

.PP
Definition at line \fB20\fP of file \fBBodyDriver\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.BodyDriver\&.RowSection_AppendTextEscaped (\fBTextEditorRenderBatchValidated\fP renderBatchLocal, StringBuilder spanBuilder, \fBRichCharacter\fP richCharacter, string tabKeyOutput, string spaceKeyOutput)"

.PP
Definition at line \fB63\fP of file \fBBodyDriver\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.BodyDriver\&.RowSection_GetCssClass (\fBTextEditorRenderBatchValidated\fP renderBatchLocal, byte decorationByte)"

.PP
Definition at line \fB58\fP of file \fBBodyDriver\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.BodyDriver\&.RowSection_GetRowStyleCss (\fBTextEditorRenderBatchValidated\fP renderBatchLocal, int index, double? virtualizedRowLeftInPixels)"

.PP
Definition at line \fB42\fP of file \fBBodyDriver\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "\fBTextEditorRenderBatchValidated\fP Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.BodyDriver\&._renderBatch"

.PP
Definition at line \fB18\fP of file \fBBodyDriver\&.cs\fP\&.
.SS "readonly \fBTextEditorViewModelDisplay\fP Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.BodyDriver\&._root"

.PP
Definition at line \fB10\fP of file \fBBodyDriver\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.BodyDriver\&.GlobalShowNewlines\fR [get]\fP"

.PP
Definition at line \fB27\fP of file \fBBodyDriver\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
