.TH "Luthetus.Common.Tests.Basis.FileSystems.Models.PathHelperTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.FileSystems.Models.PathHelperTests \- PathHelper  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBGetAbsoluteFromAbsoluteAndRelative\fP ()"
.br
.RI "PathHelper\&.GetAbsoluteFromAbsoluteAndRelative(IAbsolutePath, string, IEnvironmentProvider) ---------------------------------------------
.br
 Root
.br
 ∙└───Homework
.br
 ∙∙∙∙∙∙├───Math
.br
 ∙∙∙∙∙∙│∙∙∙∙├───addition\&.txt
.br
 ∙∙∙∙∙∙│∙∙∙∙└───subtraction\&.txt
.br
 ∙∙∙∙∙∙│
.br
 ∙∙∙∙∙∙└───Biology
.br
 ∙∙∙∙∙∙∙∙∙∙∙├───nervousSystem\&.txt
.br
 ∙∙∙∙∙∙∙∙∙∙∙└───skeletalSystem\&.txt
.br
 "
.ti -1c
.RI "void \fBGetRelativeFromTwoAbsolutes\fP ()"
.br
.RI "PathHelper\&.GetRelativeFromTwoAbsolutes(IAbsolutePath, IAbsolutePath, IEnvironmentProvider) "
.ti -1c
.RI "void \fBCalculateNameWithExtension\fP ()"
.br
.RI "PathHelper\&.CalculateNameWithExtension(string, string, bool) "
.in -1c
.SH "Detailed Description"
.PP 
PathHelper 
.PP
Definition at line \fB10\fP of file \fBPathHelperTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.FileSystems\&.Models\&.PathHelperTests\&.CalculateNameWithExtension ()"

.PP
PathHelper\&.CalculateNameWithExtension(string, string, bool) 
.PP
Definition at line \fB240\fP of file \fBPathHelperTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.FileSystems\&.Models\&.PathHelperTests\&.GetAbsoluteFromAbsoluteAndRelative ()"

.PP
PathHelper\&.GetAbsoluteFromAbsoluteAndRelative(IAbsolutePath, string, IEnvironmentProvider) ---------------------------------------------
.br
 Root
.br
 ∙└───Homework
.br
 ∙∙∙∙∙∙├───Math
.br
 ∙∙∙∙∙∙│∙∙∙∙├───addition\&.txt
.br
 ∙∙∙∙∙∙│∙∙∙∙└───subtraction\&.txt
.br
 ∙∙∙∙∙∙│
.br
 ∙∙∙∙∙∙└───Biology
.br
 ∙∙∙∙∙∙∙∙∙∙∙├───nervousSystem\&.txt
.br
 ∙∙∙∙∙∙∙∙∙∙∙└───skeletalSystem\&.txt
.br
 
.PP
Definition at line \fB26\fP of file \fBPathHelperTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.FileSystems\&.Models\&.PathHelperTests\&.GetRelativeFromTwoAbsolutes ()"

.PP
PathHelper\&.GetRelativeFromTwoAbsolutes(IAbsolutePath, IAbsolutePath, IEnvironmentProvider) 
.PP
Definition at line \fB148\fP of file \fBPathHelperTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
