.TH "Luthetus.Common.Tests.Basis.Reflectives.Models.ReflectiveParameterTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Reflectives.Models.ReflectiveParameterTests \- \fBReflectiveParameter\fP  

.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBSampleComplexType\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor_WITH_PrimitiveType\fP ()"
.br
.RI "ReflectiveParameter(ConstructorInfo?, Func<object?>?, object?, Type) 
.br
----
.br
 \fBReflectiveParameter\&.ChosenConstructorInfo\fP \fBReflectiveParameter\&.ConstructValueFunc\fP \fBReflectiveParameter\&.Value\fP \fBReflectiveParameter\&.Type\fP \fBReflectiveParameter\&.ReflectiveParameterKind\fP "
.ti -1c
.RI "void \fBConstructor_WITH_ComplexType\fP ()"
.br
.RI "ReflectiveParameter(System\&.Reflection\&.ConstructorInfo?, Func<object?>?, object?, Type) 
.br
----
.br
 \fBReflectiveParameter\&.ChosenConstructorInfo\fP \fBReflectiveParameter\&.ConstructValueFunc\fP \fBReflectiveParameter\&.Value\fP \fBReflectiveParameter\&.Type\fP \fBReflectiveParameter\&.ReflectiveParameterKind\fP "
.in -1c
.SH "Detailed Description"
.PP 
\fBReflectiveParameter\fP 
.PP
Definition at line \fB9\fP of file \fBReflectiveParameterTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Reflectives\&.Models\&.ReflectiveParameterTests\&.Constructor_WITH_ComplexType ()"

.PP
ReflectiveParameter(System\&.Reflection\&.ConstructorInfo?, Func<object?>?, object?, Type) 
.br
----
.br
 \fBReflectiveParameter\&.ChosenConstructorInfo\fP \fBReflectiveParameter\&.ConstructValueFunc\fP \fBReflectiveParameter\&.Value\fP \fBReflectiveParameter\&.Type\fP \fBReflectiveParameter\&.ReflectiveParameterKind\fP 
.PP
Definition at line \fB56\fP of file \fBReflectiveParameterTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Reflectives\&.Models\&.ReflectiveParameterTests\&.Constructor_WITH_PrimitiveType ()"

.PP
ReflectiveParameter(ConstructorInfo?, Func<object?>?, object?, Type) 
.br
----
.br
 \fBReflectiveParameter\&.ChosenConstructorInfo\fP \fBReflectiveParameter\&.ConstructValueFunc\fP \fBReflectiveParameter\&.Value\fP \fBReflectiveParameter\&.Type\fP \fBReflectiveParameter\&.ReflectiveParameterKind\fP 
.PP
Definition at line \fB21\fP of file \fBReflectiveParameterTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
