.TH "Luthetus.Tutorials.RazorLib.Pages.Index" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Tutorials.RazorLib.Pages.Index
.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase\&.
.SS "Protected Member Functions"

.in +1c
.ti -1c
.RI "override void \fBOnInitialized\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "static ResourceUri \fBResourceUri\fP = new('/index\&.txt')\fR [get]\fP"
.br
.ti -1c
.RI "static Key< \fBTextEditorViewModel\fP > \fBViewModelKey\fP = Key<\fBTextEditorViewModel\fP>\&.NewKey()\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBIndex\&.razor\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "override void Luthetus\&.Tutorials\&.RazorLib\&.Pages\&.Index\&.OnInitialized ()\fR [protected]\fP"

.PP
Definition at line \fB23\fP of file \fBIndex\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "ResourceUri Luthetus\&.Tutorials\&.RazorLib\&.Pages\&.Index\&.ResourceUri = new('/index\&.txt')\fR [static]\fP, \fR [get]\fP"

.PP
Definition at line \fB20\fP of file \fBIndex\&.razor\&.cs\fP\&.
.SS "Key<\fBTextEditorViewModel\fP> Luthetus\&.Tutorials\&.RazorLib\&.Pages\&.Index\&.ViewModelKey = Key<\fBTextEditorViewModel\fP>\&.NewKey()\fR [static]\fP, \fR [get]\fP"

.PP
Definition at line \fB21\fP of file \fBIndex\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
