.TH "Luthetus.Common.RazorLib.Tabs.Models.TabContextMenuEventArgs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Tabs.Models.TabContextMenuEventArgs
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBTabContextMenuEventArgs\fP (\fBMouseEventArgs\fP mouseEventArgs, \fBITab\fP tab, Func< Task > restoreFocusFunc)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "MouseEventArgs \fBMouseEventArgs\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBITab\fP \fBTab\fP\fR [get]\fP"
.br
.ti -1c
.RI "Func< Task > \fBRestoreFocusFunc\fP\fR [get]\fP"
.br
.RI "An async Func that will return focus to the tab button once the context menu is eventually closed\&. "
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB6\fP of file \fBTabContextMenuEventArgs\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Common\&.RazorLib\&.Tabs\&.Models\&.TabContextMenuEventArgs\&.TabContextMenuEventArgs (\fBMouseEventArgs\fP mouseEventArgs, \fBITab\fP tab, Func< Task > restoreFocusFunc)"

.PP
Definition at line \fB8\fP of file \fBTabContextMenuEventArgs\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "MouseEventArgs Luthetus\&.Common\&.RazorLib\&.Tabs\&.Models\&.TabContextMenuEventArgs\&.MouseEventArgs\fR [get]\fP"

.PP
Definition at line \fB15\fP of file \fBTabContextMenuEventArgs\&.cs\fP\&.
.SS "Func<Task> Luthetus\&.Common\&.RazorLib\&.Tabs\&.Models\&.TabContextMenuEventArgs\&.RestoreFocusFunc\fR [get]\fP"

.PP
An async Func that will return focus to the tab button once the context menu is eventually closed\&. 
.PP
Definition at line \fB22\fP of file \fBTabContextMenuEventArgs\&.cs\fP\&.
.SS "\fBITab\fP Luthetus\&.Common\&.RazorLib\&.Tabs\&.Models\&.TabContextMenuEventArgs\&.Tab\fR [get]\fP"

.PP
Definition at line \fB16\fP of file \fBTabContextMenuEventArgs\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
