.TH "Luthetus.Common.Tests.Basis.Notifications.Models.NotificationServiceTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.Notifications.Models.NotificationServiceTests \- \fBNotificationService\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "NotificationService(IDispatcher, IState<NotificationState>) "
.ti -1c
.RI "void \fBNotificationStateWrap\fP ()"
.br
.RI "\fBNotificationService\&.NotificationStateWrap\fP "
.ti -1c
.RI "void \fBRegisterNotificationRecord\fP ()"
.br
.RI "NotificationService\&.RegisterNotificationRecord(NotificationRecord) "
.ti -1c
.RI "void \fBDisposeNotificationRecord\fP ()"
.br
.RI "NotificationService\&.DisposeNotificationRecord(Key<NotificationRecord>) "
.in -1c
.SH "Detailed Description"
.PP 
\fBNotificationService\fP 
.PP
Definition at line \fB14\fP of file \fBNotificationServiceTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Notifications\&.Models\&.NotificationServiceTests\&.Constructor ()"

.PP
NotificationService(IDispatcher, IState<NotificationState>) 
.PP
Definition at line \fB20\fP of file \fBNotificationServiceTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Notifications\&.Models\&.NotificationServiceTests\&.DisposeNotificationRecord ()"

.PP
NotificationService\&.DisposeNotificationRecord(Key<NotificationRecord>) 
.PP
Definition at line \fB102\fP of file \fBNotificationServiceTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Notifications\&.Models\&.NotificationServiceTests\&.NotificationStateWrap ()"

.PP
\fBNotificationService\&.NotificationStateWrap\fP 
.PP
Definition at line \fB40\fP of file \fBNotificationServiceTests\&.cs\fP\&.
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.Notifications\&.Models\&.NotificationServiceTests\&.RegisterNotificationRecord ()"

.PP
NotificationService\&.RegisterNotificationRecord(NotificationRecord) 
.PP
Definition at line \fB60\fP of file \fBNotificationServiceTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
