.TH "Luthetus.Extensions.DotNet.Tests.Basis.Nugets.States.NuGetPackageManagerStateMainTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.Tests.Basis.Nugets.States.NuGetPackageManagerStateMainTests \- NuGetPackageManagerState  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "NuGetPackageManagerState(IDotNetProject?, string, bool, ImmutableArray<NugetPackageRecord>) 
.br
----
.br
 NuGetPackageManagerState\&.SelectedProjectToModify NuGetPackageManagerState\&.NugetQuery NuGetPackageManagerState\&.IncludePrerelease NuGetPackageManagerState\&.QueryResultList "
.in -1c
.SH "Detailed Description"
.PP 
NuGetPackageManagerState 
.PP
Definition at line \fB6\fP of file \fBNuGetPackageManagerStateMainTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Extensions\&.DotNet\&.Tests\&.Basis\&.Nugets\&.States\&.NuGetPackageManagerStateMainTests\&.Constructor ()"

.PP
NuGetPackageManagerState(IDotNetProject?, string, bool, ImmutableArray<NugetPackageRecord>) 
.br
----
.br
 NuGetPackageManagerState\&.SelectedProjectToModify NuGetPackageManagerState\&.NugetQuery NuGetPackageManagerState\&.IncludePrerelease NuGetPackageManagerState\&.QueryResultList 
.PP
Definition at line \fB17\fP of file \fBNuGetPackageManagerStateMainTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
