.TH "Luthetus.Extensions.DotNet.CompilerServices.States.CompilerServiceExplorerState.Reducer" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.CompilerServices.States.CompilerServiceExplorerState.Reducer
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCompilerServiceExplorerState\fP \fBReduceNewAction\fP (\fBCompilerServiceExplorerState\fP inCompilerServiceExplorerState, \fBNewAction\fP newAction)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBCompilerServiceExplorerState\&.Reducer\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "\fBCompilerServiceExplorerState\fP Luthetus\&.Extensions\&.DotNet\&.CompilerServices\&.States\&.CompilerServiceExplorerState\&.Reducer\&.ReduceNewAction (\fBCompilerServiceExplorerState\fP inCompilerServiceExplorerState, \fBNewAction\fP newAction)"

.PP
Definition at line \fB10\fP of file \fBCompilerServiceExplorerState\&.Reducer\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
