.TH "Source/Lib/Common/Installations/Models/LuthetusPurposeKind.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Common/Installations/Models/LuthetusPurposeKind.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\&.Installations\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\&.Installations\&.Models\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBLuthetus\&.Common\&.RazorLib\&.Installations\&.Models\&.LuthetusPurposeKind\fP { \fBLuthetus\&.Common\&.RazorLib\&.Installations\&.Models\&.Common\fP, \fBLuthetus\&.Common\&.RazorLib\&.Installations\&.Models\&.TextEditor\fP, \fBLuthetus\&.Common\&.RazorLib\&.Installations\&.Models\&.Ide\fP }"
.br
.RI "Common and TextEditor only require 1 background thread\&. Whereas the Ide requires 2 background threads\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
