.TH "Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.CursorDriver" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.CursorDriver
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBCursorDriver\fP (\fBTextEditorViewModelDisplay\fP textEditorViewModelDisplay)"
.br
.ti -1c
.RI "void \fBGetRenderFragment\fP (\fBTextEditorRenderBatchValidated\fP renderBatch)"
.br
.ti -1c
.RI "bool \fBGetIncludeContextMenuHelperComponent\fP (\fBTextEditorRenderBatchValidated\fP renderBatchLocal)"
.br
.ti -1c
.RI "string \fBGetScrollableContainerId\fP (\fBTextEditorRenderBatchValidated\fP renderBatchLocal)"
.br
.ti -1c
.RI "string \fBGetCursorDisplayId\fP (\fBTextEditorRenderBatchValidated\fP renderBatchLocal)"
.br
.ti -1c
.RI "string \fBGetCursorStyleCss\fP ()"
.br
.ti -1c
.RI "string \fBGetCaretRowStyleCss\fP ()"
.br
.ti -1c
.RI "string \fBGetMenuStyleCss\fP ()"
.br
.ti -1c
.RI "async Task \fBFocusAsync\fP ()"
.br
.ti -1c
.RI "void \fBHandleOnKeyDown\fP ()"
.br
.ti -1c
.RI "async Task \fBSetFocusToActiveMenuAsync\fP ()"
.br
.ti -1c
.RI "bool \fBTextEditorMenuShouldTakeFocus\fP ()"
.br
.ti -1c
.RI "int \fBGetTabIndex\fP (\fBTextEditorRenderBatchValidated\fP renderBatchLocal)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBTextEditorRenderBatchValidated\fP \fB_renderBatch\fP"
.br
.ti -1c
.RI "readonly Guid \fB_intersectionObserverMapKey\fP = Guid\&.NewGuid()"
.br
.ti -1c
.RI "readonly \fBThrottle\fP \fB_throttleShouldRevealCursor\fP = new(TimeSpan\&.FromMilliseconds(333))"
.br
.ti -1c
.RI "ElementReference? \fB_cursorDisplayElementReference\fP"
.br
.ti -1c
.RI "int \fB_menuShouldGetFocusRequestCount\fP"
.br
.ti -1c
.RI "string \fB_previousGetCursorStyleCss\fP = string\&.Empty"
.br
.ti -1c
.RI "string \fB_previousGetCaretRowStyleCss\fP = string\&.Empty"
.br
.ti -1c
.RI "string \fB_previousGetMenuStyleCss\fP = string\&.Empty"
.br
.ti -1c
.RI "string \fB_previouslyObservedCursorDisplayId\fP = string\&.Empty"
.br
.ti -1c
.RI "double \fB_leftRelativeToParentInPixels\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIsFocusTarget\fP\fR [get]\fP"
.br
.RI "This property will need to be used when multi-cursor is added\&. "
.ti -1c
.RI "string \fBBlinkAnimationCssClass\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB11\fP of file \fBCursorDriver\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.CursorDriver\&.CursorDriver (\fBTextEditorViewModelDisplay\fP textEditorViewModelDisplay)"

.PP
Definition at line \fB15\fP of file \fBCursorDriver\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "async Task Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.CursorDriver\&.FocusAsync ()"

.PP
Definition at line \fB228\fP of file \fBCursorDriver\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.CursorDriver\&.GetCaretRowStyleCss ()"

.PP
Definition at line \fB130\fP of file \fBCursorDriver\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.CursorDriver\&.GetCursorDisplayId (\fBTextEditorRenderBatchValidated\fP renderBatchLocal)"

.PP
Definition at line \fB55\fP of file \fBCursorDriver\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.CursorDriver\&.GetCursorStyleCss ()"

.PP
Definition at line \fB66\fP of file \fBCursorDriver\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.CursorDriver\&.GetIncludeContextMenuHelperComponent (\fBTextEditorRenderBatchValidated\fP renderBatchLocal)"

.PP
Definition at line \fB45\fP of file \fBCursorDriver\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.CursorDriver\&.GetMenuStyleCss ()"

.PP
Definition at line \fB170\fP of file \fBCursorDriver\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.CursorDriver\&.GetRenderFragment (\fBTextEditorRenderBatchValidated\fP renderBatch)"

.PP
Definition at line \fB23\fP of file \fBCursorDriver\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.CursorDriver\&.GetScrollableContainerId (\fBTextEditorRenderBatchValidated\fP renderBatchLocal)"

.PP
Definition at line \fB50\fP of file \fBCursorDriver\&.cs\fP\&.
.SS "int Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.CursorDriver\&.GetTabIndex (\fBTextEditorRenderBatchValidated\fP renderBatchLocal)"

.PP
Definition at line \fB270\fP of file \fBCursorDriver\&.cs\fP\&.
.SS "void Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.CursorDriver\&.HandleOnKeyDown ()"

.PP
Definition at line \fB248\fP of file \fBCursorDriver\&.cs\fP\&.
.SS "async Task Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.CursorDriver\&.SetFocusToActiveMenuAsync ()"

.PP
Definition at line \fB253\fP of file \fBCursorDriver\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.CursorDriver\&.TextEditorMenuShouldTakeFocus ()"

.PP
Definition at line \fB259\fP of file \fBCursorDriver\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "ElementReference? Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.CursorDriver\&._cursorDisplayElementReference"

.PP
Definition at line \fB36\fP of file \fBCursorDriver\&.cs\fP\&.
.SS "readonly Guid Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.CursorDriver\&._intersectionObserverMapKey = Guid\&.NewGuid()"

.PP
Definition at line \fB33\fP of file \fBCursorDriver\&.cs\fP\&.
.SS "double Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.CursorDriver\&._leftRelativeToParentInPixels"

.PP
Definition at line \fB43\fP of file \fBCursorDriver\&.cs\fP\&.
.SS "int Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.CursorDriver\&._menuShouldGetFocusRequestCount"

.PP
Definition at line \fB37\fP of file \fBCursorDriver\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.CursorDriver\&._previousGetCaretRowStyleCss = string\&.Empty"

.PP
Definition at line \fB39\fP of file \fBCursorDriver\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.CursorDriver\&._previousGetCursorStyleCss = string\&.Empty"

.PP
Definition at line \fB38\fP of file \fBCursorDriver\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.CursorDriver\&._previousGetMenuStyleCss = string\&.Empty"

.PP
Definition at line \fB40\fP of file \fBCursorDriver\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.CursorDriver\&._previouslyObservedCursorDisplayId = string\&.Empty"

.PP
Definition at line \fB42\fP of file \fBCursorDriver\&.cs\fP\&.
.SS "\fBTextEditorRenderBatchValidated\fP Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.CursorDriver\&._renderBatch"

.PP
Definition at line \fB21\fP of file \fBCursorDriver\&.cs\fP\&.
.SS "readonly \fBThrottle\fP Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.CursorDriver\&._throttleShouldRevealCursor = new(TimeSpan\&.FromMilliseconds(333))"

.PP
Definition at line \fB34\fP of file \fBCursorDriver\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.CursorDriver\&.BlinkAnimationCssClass\fR [get]\fP"

.PP
Definition at line \fB62\fP of file \fBCursorDriver\&.cs\fP\&.
.SS "bool Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.CursorDriver\&.IsFocusTarget\fR [get]\fP"

.PP
This property will need to be used when multi-cursor is added\&. 
.PP
Definition at line \fB31\fP of file \fBCursorDriver\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
