.TH "Luthetus.Common.Tests.Basis.BackgroundTasks.Models.BackgroundTaskTests" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.Tests.Basis.BackgroundTasks.Models.BackgroundTaskTests \- \fBBackgroundTask\fP  

.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBConstructor\fP ()"
.br
.RI "BackgroundTask(Key<BackgroundTask>, Key<BackgroundTaskQueue>, string, Func<Task>) 
.br
----
.br
 \fBBackgroundTask\&.BackgroundTaskKey\fP \fBBackgroundTask\&.QueueKey\fP \fBBackgroundTask\&.Name\fP "
.ti -1c
.RI "async Task \fBInvokeWorkItem\fP ()"
.br
.RI "BackgroundTask\&.InvokeWorkItem(CancellationToken) 
.br
----
.br
 BackgroundTask\&.WorkProgress "
.in -1c
.SH "Detailed Description"
.PP 
\fBBackgroundTask\fP 
.PP
Definition at line \fB9\fP of file \fBBackgroundTaskTests\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Common\&.Tests\&.Basis\&.BackgroundTasks\&.Models\&.BackgroundTaskTests\&.Constructor ()"

.PP
BackgroundTask(Key<BackgroundTask>, Key<BackgroundTaskQueue>, string, Func<Task>) 
.br
----
.br
 \fBBackgroundTask\&.BackgroundTaskKey\fP \fBBackgroundTask\&.QueueKey\fP \fBBackgroundTask\&.Name\fP 
.PP
Definition at line \fB19\fP of file \fBBackgroundTaskTests\&.cs\fP\&.
.SS "async Task Luthetus\&.Common\&.Tests\&.Basis\&.BackgroundTasks\&.Models\&.BackgroundTaskTests\&.InvokeWorkItem ()"

.PP
BackgroundTask\&.InvokeWorkItem(CancellationToken) 
.br
----
.br
 BackgroundTask\&.WorkProgress 
.PP
Definition at line \fB46\fP of file \fBBackgroundTaskTests\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
