.TH "Luthetus.Ide.RazorLib.ComponentRenderers.Models.IBooleanPromptOrCancelRendererType" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Ide.RazorLib.ComponentRenderers.Models.IBooleanPromptOrCancelRendererType
.SH SYNOPSIS
.br
.PP
.PP
Inherited by \fBLuthetus\&.Ide\&.RazorLib\&.FormsGenerics\&.Displays\&.BooleanPromptOrCancelDisplay\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "bool \fBIncludeCancelOption\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string \fBMessage\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string? \fBAcceptOptionTextOverride\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "string? \fBDeclineOptionTextOverride\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "Func< Task > \fBOnAfterAcceptFunc\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "Func< Task > \fBOnAfterDeclineFunc\fP\fR [get, set]\fP"
.br
.ti -1c
.RI "Func< Task > \fBOnAfterCancelFunc\fP\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB3\fP of file \fBIBooleanPromptOrCancelRendererType\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "string? Luthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.IBooleanPromptOrCancelRendererType\&.AcceptOptionTextOverride\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.FormsGenerics\&.Displays\&.BooleanPromptOrCancelDisplay\fP\&.
.PP
Definition at line \fB7\fP of file \fBIBooleanPromptOrCancelRendererType\&.cs\fP\&.
.SS "string? Luthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.IBooleanPromptOrCancelRendererType\&.DeclineOptionTextOverride\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.FormsGenerics\&.Displays\&.BooleanPromptOrCancelDisplay\fP\&.
.PP
Definition at line \fB8\fP of file \fBIBooleanPromptOrCancelRendererType\&.cs\fP\&.
.SS "bool Luthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.IBooleanPromptOrCancelRendererType\&.IncludeCancelOption\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.FormsGenerics\&.Displays\&.BooleanPromptOrCancelDisplay\fP\&.
.PP
Definition at line \fB5\fP of file \fBIBooleanPromptOrCancelRendererType\&.cs\fP\&.
.SS "string Luthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.IBooleanPromptOrCancelRendererType\&.Message\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.FormsGenerics\&.Displays\&.BooleanPromptOrCancelDisplay\fP\&.
.PP
Definition at line \fB6\fP of file \fBIBooleanPromptOrCancelRendererType\&.cs\fP\&.
.SS "Func<Task> Luthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.IBooleanPromptOrCancelRendererType\&.OnAfterAcceptFunc\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.FormsGenerics\&.Displays\&.BooleanPromptOrCancelDisplay\fP\&.
.PP
Definition at line \fB9\fP of file \fBIBooleanPromptOrCancelRendererType\&.cs\fP\&.
.SS "Func<Task> Luthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.IBooleanPromptOrCancelRendererType\&.OnAfterCancelFunc\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.FormsGenerics\&.Displays\&.BooleanPromptOrCancelDisplay\fP\&.
.PP
Definition at line \fB11\fP of file \fBIBooleanPromptOrCancelRendererType\&.cs\fP\&.
.SS "Func<Task> Luthetus\&.Ide\&.RazorLib\&.ComponentRenderers\&.Models\&.IBooleanPromptOrCancelRendererType\&.OnAfterDeclineFunc\fR [get]\fP, \fR [set]\fP"

.PP
Implemented in \fBLuthetus\&.Ide\&.RazorLib\&.FormsGenerics\&.Displays\&.BooleanPromptOrCancelDisplay\fP\&.
.PP
Definition at line \fB10\fP of file \fBIBooleanPromptOrCancelRendererType\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
