.TH "Luthetus.Common.RazorLib.Namespaces.Models" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Common.RazorLib.Namespaces.Models
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBNamespacePath\fP"
.br
.RI "TODO: Move this type somehere else\&. This type currently exists in 'Luthetus\&.Common\&.csproj'\&.\&.\&. \&.\&.\&.because the 'Luthetus\&.CompilerServices\&.DotNetSolution\&.csproj' needed to reference the type\&.
.br
 |
.br
 And with it having originally been in 'Luthetus\&.Ide\&.csproj', this meant a circular reference and it had to be moved here for now\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
