.TH "Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.SymbolDisplay" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.SymbolDisplay \- TODO: protect against exceptions that are thrown when rendering the symbol\&. One happened while hovering a lambda expression on (2024-11-09)\&.  

.SH SYNOPSIS
.br
.PP
.PP
Inherits ComponentBase, and \fBLuthetus\&.TextEditor\&.RazorLib\&.ComponentRenderers\&.Models\&.ITextEditorSymbolRenderer\fP\&.
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBITextEditorSymbol\fP \fBSymbol\fP = null!\fR [get, set]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
TODO: protect against exceptions that are thrown when rendering the symbol\&. One happened while hovering a lambda expression on (2024-11-09)\&. 
.PP
Definition at line \fB11\fP of file \fBSymbolDisplay\&.razor\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBITextEditorSymbol\fP Luthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Displays\&.Internals\&.SymbolDisplay\&.Symbol = null!\fR [get]\fP, \fR [set]\fP"

.PP
Implements \fBLuthetus\&.TextEditor\&.RazorLib\&.ComponentRenderers\&.Models\&.ITextEditorSymbolRenderer\fP\&.
.PP
Definition at line \fB21\fP of file \fBSymbolDisplay\&.razor\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
