.TH "Luthetus.CompilerServices.Json.SyntaxObjects.JsonIntegerSyntax" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.CompilerServices.Json.SyntaxObjects.JsonIntegerSyntax
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.CompilerServices\&.Json\&.IJsonSyntax\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBJsonIntegerSyntax\fP (\fBTextEditorTextSpan\fP textEditorTextSpan)"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "TextEditorTextSpan \fBTextEditorTextSpan\fP\fR [get]\fP"
.br
.ti -1c
.RI "ImmutableArray< \fBIJsonSyntax\fP > \fBChildJsonSyntaxes\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBJsonSyntaxKind\fP \fBJsonSyntaxKind\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBJsonIntegerSyntax\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.CompilerServices\&.Json\&.SyntaxObjects\&.JsonIntegerSyntax\&.JsonIntegerSyntax (\fBTextEditorTextSpan\fP textEditorTextSpan)"

.PP
Definition at line \fB9\fP of file \fBJsonIntegerSyntax\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "ImmutableArray<\fBIJsonSyntax\fP> Luthetus\&.CompilerServices\&.Json\&.SyntaxObjects\&.JsonIntegerSyntax\&.ChildJsonSyntaxes\fR [get]\fP"

.PP
Implements \fBLuthetus\&.CompilerServices\&.Json\&.IJsonSyntax\fP\&.
.PP
Definition at line \fB16\fP of file \fBJsonIntegerSyntax\&.cs\fP\&.
.SS "\fBJsonSyntaxKind\fP Luthetus\&.CompilerServices\&.Json\&.SyntaxObjects\&.JsonIntegerSyntax\&.JsonSyntaxKind\fR [get]\fP"

.PP
Implements \fBLuthetus\&.CompilerServices\&.Json\&.IJsonSyntax\fP\&.
.PP
Definition at line \fB18\fP of file \fBJsonIntegerSyntax\&.cs\fP\&.
.SS "TextEditorTextSpan Luthetus\&.CompilerServices\&.Json\&.SyntaxObjects\&.JsonIntegerSyntax\&.TextEditorTextSpan\fR [get]\fP"

.PP
Implements \fBLuthetus\&.CompilerServices\&.Json\&.IJsonSyntax\fP\&.
.PP
Definition at line \fB15\fP of file \fBJsonIntegerSyntax\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
