.TH "Luthetus.TextEditor.RazorLib.Groups.States.TextEditorGroupState" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Groups.States.TextEditorGroupState
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBEffector\fP"
.br
.ti -1c
.RI "class \fBReducer\fP"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "record \fBRegisterAction\fP (TextEditorGroup Group)"
.br
.ti -1c
.RI "record \fBDisposeAction\fP (Key< TextEditorGroup > GroupKey)"
.br
.ti -1c
.RI "record \fBAddViewModelToGroupAction\fP (Key< TextEditorGroup > GroupKey, Key< \fBTextEditorViewModel\fP > \fBViewModelKey\fP)"
.br
.ti -1c
.RI "record \fBRemoveViewModelFromGroupAction\fP (Key< TextEditorGroup > GroupKey, Key< \fBTextEditorViewModel\fP > \fBViewModelKey\fP)"
.br
.ti -1c
.RI "record \fBSetActiveViewModelOfGroupAction\fP (Key< TextEditorGroup > GroupKey, Key< \fBTextEditorViewModel\fP > \fBViewModelKey\fP)"
.br
.ti -1c
.RI "\fBTextEditorGroupState\fP ()"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "ImmutableList< TextEditorGroup > \fBGroupList\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB7\fP of file \fBTextEditorGroupState\&.Actions\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.TextEditor\&.RazorLib\&.Groups\&.States\&.TextEditorGroupState\&.TextEditorGroupState ()"

.PP
Definition at line \fB10\fP of file \fBTextEditorGroupState\&.Main\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "record Luthetus\&.TextEditor\&.RazorLib\&.Groups\&.States\&.TextEditorGroupState\&.AddViewModelToGroupAction (Key< TextEditorGroup > GroupKey, Key< \fBTextEditorViewModel\fP > ViewModelKey)"

.SS "record Luthetus\&.TextEditor\&.RazorLib\&.Groups\&.States\&.TextEditorGroupState\&.DisposeAction (Key< TextEditorGroup > GroupKey)"

.SS "record Luthetus\&.TextEditor\&.RazorLib\&.Groups\&.States\&.TextEditorGroupState\&.RegisterAction (TextEditorGroup Group)"

.SS "record Luthetus\&.TextEditor\&.RazorLib\&.Groups\&.States\&.TextEditorGroupState\&.RemoveViewModelFromGroupAction (Key< TextEditorGroup > GroupKey, Key< \fBTextEditorViewModel\fP > ViewModelKey)"

.SS "record Luthetus\&.TextEditor\&.RazorLib\&.Groups\&.States\&.TextEditorGroupState\&.SetActiveViewModelOfGroupAction (Key< TextEditorGroup > GroupKey, Key< \fBTextEditorViewModel\fP > ViewModelKey)"

.SH "Property Documentation"
.PP 
.SS "ImmutableList<TextEditorGroup> Luthetus\&.TextEditor\&.RazorLib\&.Groups\&.States\&.TextEditorGroupState\&.GroupList\fR [get]\fP"

.PP
Definition at line \fB15\fP of file \fBTextEditorGroupState\&.Main\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
