.TH "Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler \-  

.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBLuthetus\&.Common\&.RazorLib\&.Reactives\&.Models\&.IStateScheduler\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "void \fBEnqueue_ConstructTreeView\fP ()"
.br
.ti -1c
.RI "\fBTestExplorerScheduler\fP (\fBDotNetBackgroundTaskApi\fP dotNetBackgroundTaskApi, \fBIdeBackgroundTaskApi\fP ideBackgroundTaskApi, \fBICommonComponentRenderers\fP commonComponentRenderers, \fBITreeViewService\fP treeViewService, \fBITextEditorService\fP textEditorService, \fBIBackgroundTaskService\fP backgroundTaskService, \fBIFileSystemProvider\fP fileSystemProvider, \fBDotNetCliOutputParser\fP dotNetCliOutputParser, IState< \fBDotNetSolutionState\fP > dotNetSolutionStateWrap, IState< \fBTerminalState\fP > terminalStateWrap, IState< \fBTestExplorerState\fP > testExplorerStateWrap, IDispatcher dispatcher)"
.br
.ti -1c
.RI "async Task \fBTask_ConstructTreeView\fP ()"
.br
.ti -1c
.RI "Task \fBTask_DiscoverTests\fP ()"
.br
.ti -1c
.RI "Task \fBTask_SumEachProjectTestCount\fP ()"
.br
.ti -1c
.RI "void \fBMoveNodeToCorrectBranch\fP (\fBTreeViewProjectTestModel\fP treeViewProjectTestModel)"
.br
.RI "This is strategic spaghetti code that is part of my master plan\&. Don't @ me on teams; I won't respond\&. "
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "\fBTreeViewGroup\fP \fBContainsTestsTreeViewGroup\fP = new('Have tests', true, true)\fR [get]\fP"
.br
.ti -1c
.RI "\fBTreeViewGroup\fP \fBNoTestsTreeViewGroup\fP = new('No tests (but still a \fBtest\fP\-project)', true, true)\fR [get]\fP"
.br
.ti -1c
.RI "\fBTreeViewGroup\fP \fBThrewAnExceptionTreeViewGroup\fP = new('Projects that threw an exception during discovery', true, true)\fR [get]\fP"
.br
.ti -1c
.RI "\fBTreeViewGroup\fP \fBNotValidProjectForUnitTestTreeViewGroup\fP = new('Not a \fBtest\fP\-project', true, true)\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
Definition at line \fB6\fP of file \fBTestExplorerScheduler\&.EnqueueApi\&.cs\fP\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "Luthetus\&.Extensions\&.DotNet\&.TestExplorers\&.States\&.TestExplorerScheduler\&.TestExplorerScheduler (\fBDotNetBackgroundTaskApi\fP dotNetBackgroundTaskApi, \fBIdeBackgroundTaskApi\fP ideBackgroundTaskApi, \fBICommonComponentRenderers\fP commonComponentRenderers, \fBITreeViewService\fP treeViewService, \fBITextEditorService\fP textEditorService, \fBIBackgroundTaskService\fP backgroundTaskService, \fBIFileSystemProvider\fP fileSystemProvider, \fBDotNetCliOutputParser\fP dotNetCliOutputParser, IState< \fBDotNetSolutionState\fP > dotNetSolutionStateWrap, IState< \fBTerminalState\fP > terminalStateWrap, IState< \fBTestExplorerState\fP > testExplorerStateWrap, IDispatcher dispatcher)"

.PP
Definition at line \fB36\fP of file \fBTestExplorerScheduler\&.Main\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "void Luthetus\&.Extensions\&.DotNet\&.TestExplorers\&.States\&.TestExplorerScheduler\&.Enqueue_ConstructTreeView ()"

.PP
Definition at line \fB8\fP of file \fBTestExplorerScheduler\&.EnqueueApi\&.cs\fP\&.
.SS "void Luthetus\&.Extensions\&.DotNet\&.TestExplorers\&.States\&.TestExplorerScheduler\&.MoveNodeToCorrectBranch (\fBTreeViewProjectTestModel\fP treeViewProjectTestModel)"

.PP
This is strategic spaghetti code that is part of my master plan\&. Don't @ me on teams; I won't respond\&. 
.PP
Definition at line \fB364\fP of file \fBTestExplorerScheduler\&.TaskApi\&.cs\fP\&.
.SS "async Task Luthetus\&.Extensions\&.DotNet\&.TestExplorers\&.States\&.TestExplorerScheduler\&.Task_ConstructTreeView ()"

.PP
Definition at line \fB15\fP of file \fBTestExplorerScheduler\&.TaskApi\&.cs\fP\&.
.SS "Task Luthetus\&.Extensions\&.DotNet\&.TestExplorers\&.States\&.TestExplorerScheduler\&.Task_DiscoverTests ()"

.PP
Definition at line \fB175\fP of file \fBTestExplorerScheduler\&.TaskApi\&.cs\fP\&.
.SS "Task Luthetus\&.Extensions\&.DotNet\&.TestExplorers\&.States\&.TestExplorerScheduler\&.Task_SumEachProjectTestCount ()"

.PP
Definition at line \fB275\fP of file \fBTestExplorerScheduler\&.TaskApi\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBTreeViewGroup\fP Luthetus\&.Extensions\&.DotNet\&.TestExplorers\&.States\&.TestExplorerScheduler\&.ContainsTestsTreeViewGroup = new('Have tests', true, true)\fR [get]\fP"

.PP
Definition at line \fB64\fP of file \fBTestExplorerScheduler\&.Main\&.cs\fP\&.
.SS "\fBTreeViewGroup\fP Luthetus\&.Extensions\&.DotNet\&.TestExplorers\&.States\&.TestExplorerScheduler\&.NoTestsTreeViewGroup = new('No tests (but still a \fBtest\fP\-project)', true, true)\fR [get]\fP"

.PP
Definition at line \fB65\fP of file \fBTestExplorerScheduler\&.Main\&.cs\fP\&.
.SS "\fBTreeViewGroup\fP Luthetus\&.Extensions\&.DotNet\&.TestExplorers\&.States\&.TestExplorerScheduler\&.NotValidProjectForUnitTestTreeViewGroup = new('Not a \fBtest\fP\-project', true, true)\fR [get]\fP"

.PP
Definition at line \fB67\fP of file \fBTestExplorerScheduler\&.Main\&.cs\fP\&.
.SS "\fBTreeViewGroup\fP Luthetus\&.Extensions\&.DotNet\&.TestExplorers\&.States\&.TestExplorerScheduler\&.ThrewAnExceptionTreeViewGroup = new('Projects that threw an exception during discovery', true, true)\fR [get]\fP"

.PP
Definition at line \fB66\fP of file \fBTestExplorerScheduler\&.Main\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
