.TH "Luthetus.TextEditor.RazorLib.Diffs.Models.TextEditorDiffResult" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Luthetus.TextEditor.RazorLib.Diffs.Models.TextEditorDiffResult
.SH SYNOPSIS
.br
.PP
.SS "Static Public Member Functions"

.in +1c
.ti -1c
.RI "static TextEditorDiffResult \fBCalculate\fP (\fBResourceUri\fP inResourceUri, string inText, \fBResourceUri\fP outResourceUri, string outText)"
.br
.RI "This method aims to implement the "An O(ND) Difference Algorithm" 
.br

.br
 Watching https://www.youtube.com/watch?v=9n8jI2267MM\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBsourceWeight\fP"
.br
.ti -1c
.RI "int int \fBbeforeIndex\fP"
.br
.in -1c
.SS "Properties"

.in +1c
.ti -1c
.RI "string \fBInText\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBOutText\fP\fR [get]\fP"
.br
.ti -1c
.RI "\fBTextEditorDiffCell\fP[,] \fBDiffMatrix\fP\fR [get]\fP"
.br
.ti -1c
.RI "int int int afterIndex \fBHighestSourceWeightTuple\fP\fR [get]\fP"
.br
.ti -1c
.RI "string \fBLongestCommonSubsequence\fP\fR [get]\fP"
.br
.ti -1c
.RI "ImmutableList< \fBTextEditorTextSpan\fP > \fBInResultTextSpanList\fP\fR [get]\fP"
.br
.ti -1c
.RI "ImmutableList< \fBTextEditorTextSpan\fP > \fBOutResultTextSpanList\fP\fR [get]\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line \fB8\fP of file \fBTextEditorDiffResult\&.cs\fP\&.
.SH "Member Function Documentation"
.PP 
.SS "TextEditorDiffResult Luthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.TextEditorDiffResult\&.Calculate (\fBResourceUri\fP inResourceUri, string inText, \fBResourceUri\fP outResourceUri, string outText)\fR [static]\fP"

.PP
This method aims to implement the "An O(ND) Difference Algorithm" 
.br

.br
 Watching https://www.youtube.com/watch?v=9n8jI2267MM\&. 
.PP
Definition at line \fB41\fP of file \fBTextEditorDiffResult\&.cs\fP\&.
.SH "Member Data Documentation"
.PP 
.SS "int int Luthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.TextEditorDiffResult\&.beforeIndex"

.PP
Definition at line \fB31\fP of file \fBTextEditorDiffResult\&.cs\fP\&.
.SS "int Luthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.TextEditorDiffResult\&.sourceWeight"

.PP
Definition at line \fB31\fP of file \fBTextEditorDiffResult\&.cs\fP\&.
.SH "Property Documentation"
.PP 
.SS "\fBTextEditorDiffCell\fP [,] Luthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.TextEditorDiffResult\&.DiffMatrix\fR [get]\fP"

.PP
Definition at line \fB30\fP of file \fBTextEditorDiffResult\&.cs\fP\&.
.SS "int int int afterIndex Luthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.TextEditorDiffResult\&.HighestSourceWeightTuple\fR [get]\fP"

.PP
Definition at line \fB31\fP of file \fBTextEditorDiffResult\&.cs\fP\&.
.SS "ImmutableList<\fBTextEditorTextSpan\fP> Luthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.TextEditorDiffResult\&.InResultTextSpanList\fR [get]\fP"

.PP
Definition at line \fB33\fP of file \fBTextEditorDiffResult\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.TextEditorDiffResult\&.InText\fR [get]\fP"

.PP
Definition at line \fB28\fP of file \fBTextEditorDiffResult\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.TextEditorDiffResult\&.LongestCommonSubsequence\fR [get]\fP"

.PP
Definition at line \fB32\fP of file \fBTextEditorDiffResult\&.cs\fP\&.
.SS "ImmutableList<\fBTextEditorTextSpan\fP> Luthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.TextEditorDiffResult\&.OutResultTextSpanList\fR [get]\fP"

.PP
Definition at line \fB34\fP of file \fBTextEditorDiffResult\&.cs\fP\&.
.SS "string Luthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.TextEditorDiffResult\&.OutText\fR [get]\fP"

.PP
Definition at line \fB29\fP of file \fBTextEditorDiffResult\&.cs\fP\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
