.TH "md__docs_2_common_2changelog" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__docs_2_common_2changelog \- Change Log 
.PP


.PP
All notable changes to the "Luthetus\&.Common" repository will be documented in this file\&.

.PP
The format is based on \fRKeep a Changelog\fP, and this project adheres to \fRSemantic Versioning\fP\&.
.SH "[1\&.1\&.0] - 2023-08-17"
.PP
\fBClick to show changes\fP
.PP
.PP
.RS 4


.PP
.RE
.PP
.SS "Fixed"
.IP "\(bu" 2
Register \fRIThemeRecordsCollectionService\fP from within \fR\fBLuthetus\&.Common\fP\fP\&. 
.PP

.PP
.PP
.SH "[1\&.0\&.0] - 2023-08-17"
.PP
\fBClick to show changes\fP
.PP
.PP
.RS 4


.PP
.RE
.PP
.SS "Added"
.IP "\(bu" 2
NuGet Package was uploaded\&. 
.PP

