.TH "md__docs_2_text_editor_2_features_2_command-_show_find_dialog___text_editor" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__docs_2_text_editor_2_features_2_command-_show_find_dialog___text_editor \- Command-ShowFindDialog_TextEditor 
.PP
Command-ShowFindDialog | \fBLuthetus\&.TextEditor\fP | Features

.PP
.PP

.PP
 
