.TH "Source/Lib/Common/JavaScriptObjects/Models/MeasuredHtmlElementDimensions.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Common/JavaScriptObjects/Models/MeasuredHtmlElementDimensions.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\&.JavaScriptObjects\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\&.JavaScriptObjects\&.Models\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "record \fBLuthetus\&.Common\&.RazorLib\&.JavaScriptObjects\&.Models\&.MeasuredHtmlElementDimensions\fP (double WidthInPixels, double HeightInPixels, double LeftInPixels, double TopInPixels, double ZIndex)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
