.TH "Source/Lib/TextEditor/TextEditors/Models/Internals/MenuKind.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/TextEditor/TextEditors/Models/Internals/MenuKind.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.MenuKind\fP { \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.None\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.ContextMenu\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.Internals\&.AutoCompleteMenu\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
