.TH "Source/Lib/Common/Menus/Models/MenuOptionKind.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Common/Menus/Models/MenuOptionKind.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\&.Menus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\&.Menus\&.Models\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBLuthetus\&.Common\&.RazorLib\&.Menus\&.Models\&.MenuOptionKind\fP { \fBLuthetus\&.Common\&.RazorLib\&.Menus\&.Models\&.Create\fP, \fBLuthetus\&.Common\&.RazorLib\&.Menus\&.Models\&.Read\fP, \fBLuthetus\&.Common\&.RazorLib\&.Menus\&.Models\&.Update\fP, \fBLuthetus\&.Common\&.RazorLib\&.Menus\&.Models\&.Delete\fP, \fBLuthetus\&.Common\&.RazorLib\&.Menus\&.Models\&.Other\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
