.TH "Source/Lib/Common/Namespaces/Models/NamespacePath.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Common/Namespaces/Models/NamespacePath.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLuthetus\&.Common\&.RazorLib\&.Namespaces\&.Models\&.NamespacePath\fP"
.br
.RI "TODO: Move this type somehere else\&. This type currently exists in 'Luthetus\&.Common\&.csproj'\&.\&.\&. \&.\&.\&.because the 'Luthetus\&.CompilerServices\&.DotNetSolution\&.csproj' needed to reference the type\&.
.br
 |
.br
 And with it having originally been in 'Luthetus\&.Ide\&.csproj', this meant a circular reference and it had to be moved here for now\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\&.Namespaces\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\&.Namespaces\&.Models\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
