.TH "Source/Lib/Common/Notifications/States/NotificationState.Main.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Common/Notifications/States/NotificationState.Main.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\&.Notifications\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\&.Notifications\&.States\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "partial record \fBLuthetus\&.Common\&.RazorLib\&.Notifications\&.States\&.NotificationState\fP (ImmutableList< \fBINotification\fP > DefaultList, ImmutableList< \fBINotification\fP > ReadList, ImmutableList< \fBINotification\fP > ArchivedList, ImmutableList< \fBINotification\fP > DeletedList)"
.br
.RI "TODO: SphagettiCode - The NotificationState is written such that there are (2023-09-19) 4 lists\&. One foreach filter option\&. And the NotificationRecord gets shuffled around\&. This is odd\&. Perhaps use one list and filter it? "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
