.TH "Source/Lib/TextEditor/Events/Models/OnKeyDownLateBatching.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/TextEditor/Events/Models/OnKeyDownLateBatching.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBLuthetus\&.TextEditor\&.RazorLib\&.Events\&.Models\&.OnKeyDownLateBatching\fP"
.br
.RI "Use an array with a fixed size to optimize this, usually there are only about 3-5 events that end up batched\&. To construct a non-struct collection is probably a massive performance hit considering the extremely rapid turn over of this type while holding down a keyboard key\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\&.Events\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\&.Events\&.Models\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
