.TH "Source/Lib/Common/Reflectives/PersonCase/PersonSimpleDisplay.razor.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Common/Reflectives/PersonCase/PersonSimpleDisplay.razor.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLuthetus\&.Common\&.RazorLib\&.Reflectives\&.PersonCase\&.PersonSimpleDisplay\fP"
.br
.RI "\fBPersonSimpleDisplay\fP is used from within the unit tests, in order to keep around an un-changing component for the \fBReflectives\fP\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\&.Reflectives\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\&.Reflectives\&.PersonCase\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
