.TH "Source/Tutorials/Wasm/Program.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Tutorials/Wasm/Program.cs
.SH SYNOPSIS
.br
.PP
.SS "Functions"

.in +1c
.ti -1c
.RI "builder\&.RootComponents\&. \fBAdd< App >\fP ('#app')"
.br
.ti -1c
.RI "builder\&.RootComponents\&. \fBAdd< HeadOutlet >\fP ('head::after')"
.br
.ti -1c
.RI "builder\&.Services\&. \fBAddScoped\fP (sp=> new HttpClient { BaseAddress=new Uri(builder\&.HostEnvironment\&.BaseAddress) })"
.br
.ti -1c
.RI "builder\&.Services\&. \fBAddLuthetusTutorialsRazorLibServices\fP (\fBhostingInformation\fP)"
.br
.ti -1c
.RI "hostingInformation\&. \fBStartBackgroundTaskWorkers\fP (host\&.Services)"
.br
.ti -1c
.RI "await host\&. \fBRunAsync\fP ()"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "var \fBbuilder\fP = WebAssemblyHostBuilder\&.CreateDefault(args)"
.br
.ti -1c
.RI "var \fBhostingInformation\fP"
.br
.ti -1c
.RI "var \fBhost\fP = builder\&.Build()"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "builder\&.RootComponents\&. Add< App > ('#app' )"

.SS "builder\&.RootComponents\&. Add< HeadOutlet > ('head\&.after' )"

.SS "builder\&.Services\&. AddLuthetusTutorialsRazorLibServices (\fBhostingInformation\fP )"

.SS "builder\&.Services\&. AddScoped (sp , new HttpClient { BaseAddress=new Uri(builder\&.HostEnvironment\&.BaseAddress) } )"

.SS "await host\&. RunAsync ()"

.SS "hostingInformation\&. StartBackgroundTaskWorkers (host\&. Services)"

.SH "Variable Documentation"
.PP 
.SS "var builder = WebAssemblyHostBuilder\&.CreateDefault(args)"

.PP
Definition at line \fB8\fP of file \fBProgram\&.cs\fP\&.
.SS "var host = builder\&.Build()"

.PP
Definition at line \fB21\fP of file \fBProgram\&.cs\fP\&.
.SS "var hostingInformation"
\fBInitial value:\fP
.nf
= new LuthetusHostingInformation(
    LuthetusHostingKind\&.Wasm,
    LuthetusPurposeKind\&.TextEditor,
    new BackgroundTaskService())
.PP
.fi

.PP
Definition at line \fB14\fP of file \fBProgram\&.cs\fP\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
