.TH "Source/Lib/Extensions/Extensions.DotNet/Websites/ProjectTemplates/Models/ProjectTemplate.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Extensions/Extensions.DotNet/Websites/ProjectTemplates/Models/ProjectTemplate.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Extensions\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Extensions\&.DotNet\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Extensions\&.DotNet\&.Websites\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Extensions\&.DotNet\&.Websites\&.ProjectTemplates\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Extensions\&.DotNet\&.Websites\&.ProjectTemplates\&.Models\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "record \fBLuthetus\&.Extensions\&.DotNet\&.Websites\&.ProjectTemplates\&.Models\&.ProjectTemplate\fP (string? TemplateName, string? ShortName, string? Language, string? Tags)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
