.TH "Source/Lib/TextEditor/BackgroundTasks/Models/RedundantTextEditorWork.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/TextEditor/BackgroundTasks/Models/RedundantTextEditorWork.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "struct \fBLuthetus\&.TextEditor\&.RazorLib\&.BackgroundTasks\&.Models\&.RedundantTextEditorWork\fP"
.br
.RI "Given two contiguous background tasks\&. If both of the tasks are of this type, then compare their Name, \fBResourceUri\fP, and \fBViewModelKey\fP against eachother\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\&.BackgroundTasks\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\&.BackgroundTasks\&.Models\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
