.TH "Source/Lib/Common/Reflectives/Models/ReflectiveParameterKind.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Common/Reflectives/Models/ReflectiveParameterKind.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\&.Reflectives\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\&.Reflectives\&.Models\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBLuthetus\&.Common\&.RazorLib\&.Reflectives\&.Models\&.ReflectiveParameterKind\fP { \fBLuthetus\&.Common\&.RazorLib\&.Reflectives\&.Models\&.Primitive\fP, \fBLuthetus\&.Common\&.RazorLib\&.Reflectives\&.Models\&.Complex\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
