.TH "Source/Lib/Ide/Ide.RazorLib/StartupControls/States/StartupControlState.Actions.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Ide/Ide.RazorLib/StartupControls/States/StartupControlState.Actions.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Ide\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Ide\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Ide\&.RazorLib\&.StartupControls\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Ide\&.RazorLib\&.StartupControls\&.States\fP"
.br
.in -1c
.SS "Variables"

.in +1c
.ti -1c
.RI "partial record \fBLuthetus\&.Ide\&.RazorLib\&.StartupControls\&.States\&.StartupControlState\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
