.TH "Source/Tests/Ide/Basis/Terminals/States/TerminalWasModifiedStateActionsTests.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Tests/Ide/Basis/Terminals/States/TerminalWasModifiedStateActionsTests.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLuthetus\&.Ide\&.Tests\&.Basis\&.Terminals\&.States\&.TerminalWasModifiedStateActionsTests\fP"
.br
.RI "TerminalWasModifiedState "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Ide\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Ide\&.Tests\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Ide\&.Tests\&.Basis\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Ide\&.Tests\&.Basis\&.Terminals\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Ide\&.Tests\&.Basis\&.Terminals\&.States\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
