.TH "Source/Lib/Extensions/Extensions.DotNet/TestExplorers/States/TestExplorerState.Main.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Extensions/Extensions.DotNet/TestExplorers/States/TestExplorerState.Main.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Extensions\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Extensions\&.DotNet\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Extensions\&.DotNet\&.TestExplorers\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Extensions\&.DotNet\&.TestExplorers\&.States\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "partial record \fBLuthetus\&.Extensions\&.DotNet\&.TestExplorers\&.States\&.TestExplorerState\fP (string? SolutionFilePath, int TotalTestCount, ImmutableHashSet< string > NotRanTestHashSet, ImmutableHashSet< string > PassedTestHashSet, ImmutableHashSet< string > FailedTestHashSet)"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
