.TH "Source/Lib/TextEditor/Cursors/Models/TextEditorSelection.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/TextEditor/Cursors/Models/TextEditorSelection.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\&.Cursors\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\&.Cursors\&.Models\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "record \fBLuthetus\&.TextEditor\&.RazorLib\&.Cursors\&.Models\&.TextEditorSelection\fP (int? AnchorPositionIndex, int EndingPositionIndex)"
.br
.RI "To select the first character in a \fBTextEditor\fP one would set AnchorPositionIndex = 0 and set EndingPositionIndex = 1 
.br

.br
 The AnchorPositionIndex does not select any text by itself\&. One must visualize that the user's cursor is rendered with \fBTextCursorKindFacts\&.BeamCssClassString\fP mode\&. 
.br

.br
 The EndingPositionIndex can then be set\&. If EndingPositionIndex is less than AnchorPositionIndex then EndingPositionIndex will be INCLUSIVE in respect to selecting the character at that PositionIndex and AnchorPositionIndex will be EXCLUSIVE\&. 
.br

.br
 If EndingPositionIndex is greater than AnchorPositionIndex then EndingPositionIndex will be EXCLUSIVE in respect to selecting the character at that PositionIndex and AnchorPositionIndex will be INCLUSIVE\&. 
.br

.br
 If EndingPositionIndex is equal to AnchorPositionIndex then no selection is active\&. 
.br

.br
 If AnchorPositionIndex is null then no selection is active\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
