.TH "Source/Lib/TextEditor/CompilerServices/Enums/TextEditorDiagnosticLevel.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/TextEditor/CompilerServices/Enums/TextEditorDiagnosticLevel.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Enums\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Enums\&.TextEditorDiagnosticLevel\fP { \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Enums\&.Hint\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Enums\&.Suggestion\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Enums\&.Warning\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Enums\&.Error\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.CompilerServices\&.Enums\&.Other\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
