.TH "Source/Tests/TextEditor/Basis/Lexes/Models/TextEditorLexerResultTests.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Tests/TextEditor/Basis/Lexes/Models/TextEditorLexerResultTests.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "interface \fBLuthetus\&.TextEditor\&.Tests\&.Basis\&.Lexers\&.Models\&.TextEditorLexerResultTests\fP"
.br
.RI "\fBTextEditorLexerResult\fP "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.Tests\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.Tests\&.Basis\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.Tests\&.Basis\&.Lexers\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.Tests\&.Basis\&.Lexers\&.Models\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
