.TH "Source/Tests/TextEditor/UserStories/TextEditors/Models/TextEditorModels/TEXT_EDITOR_SHOULD_WORK_WITH_LARGE_FILES.Main.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Tests/TextEditor/UserStories/TextEditors/Models/TextEditorModels/TEXT_EDITOR_SHOULD_WORK_WITH_LARGE_FILES.Main.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLuthetus\&.TextEditor\&.Tests\&.UserStories\&.TextEditors\&.Models\&.TEXT_EDITOR_SHOULD_WORK_WITH_LARGE_FILES\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.Tests\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.Tests\&.UserStories\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.Tests\&.UserStories\&.TextEditors\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.Tests\&.UserStories\&.TextEditors\&.Models\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
