.TH "Source/Lib/CompilerServices/JavaScript/SyntaxActors/TextEditorJavaScriptLexer.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/CompilerServices/JavaScript/SyntaxActors/TextEditorJavaScriptLexer.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLuthetus\&.CompilerServices\&.JavaScript\&.SyntaxActors\&.TextEditorJavaScriptLexer\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.CompilerServices\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.CompilerServices\&.JavaScript\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.CompilerServices\&.JavaScript\&.SyntaxActors\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
