.TH "Source/Lib/TextEditor/Diffs/Models/TextEditorDiffDecorationKind.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/TextEditor/Diffs/Models/TextEditorDiffDecorationKind.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\&.Diffs\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\fP"
.br
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum \fBLuthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.TextEditorDiffDecorationKind\fP { \fBLuthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.None\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.LongestCommonSubsequence\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.Insertion\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.InsertionLine\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.Deletion\fP, \fBLuthetus\&.TextEditor\&.RazorLib\&.Diffs\&.Models\&.Modification\fP }"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
