.TH "Source/Lib/TextEditor/TextEditors/Models/TextEditorModelModifier.EditMethods.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/TextEditor/TextEditors/Models/TextEditorModelModifier.EditMethods.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.TextEditorModelModifier\fP"
.br
.RI "(2024-06-08) I belive there are too many ways to edit a text editor\&. There should only be 'Insert(\&.\&.\&.)' and 'Remove(\&.\&.\&.)' methods\&. Any code I currently have in 'TextEditorModelModifier\&.cs' that I deem as technical debt or a bad idea will be put in this file\&. Then, once organized I hope to make sense of what the "lean" solution is\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
