.TH "Source/Lib/Common/TreeViews/Models/TreeViewWithType.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Common/TreeViews/Models/TreeViewWithType.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewWithType< T >\fP"
.br
.RI "Implement the abstract class \fBTreeViewWithType<T>\fP in order to make a TreeView\&.
.br

.br
 An abstract class is used because a good deal of customization is required on a per TreeView basis depending on what data type one displays in that TreeView\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
