.TH "Source/Lib/Common/TreeViews/Models/TreeViewNoType.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/Common/TreeViews/Models/TreeViewNoType.cs
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\&.TreeViewNoType\fP"
.br
.RI "Without this datatype one cannot for example hold all their \fBTreeViewWithType<T>\fP in a List<T> unless all implementation instances share the same generic argument type\&. "
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.Common\&.RazorLib\&.TreeViews\&.Models\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
