.TH "Source/Lib/TextEditor/TextEditors/Models/WidgetInline.cs" 3 "Version 1.0.0" "Luthetus.Ide" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Source/Lib/TextEditor/TextEditors/Models/WidgetInline.cs
.SH SYNOPSIS
.br
.PP
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBLuthetus\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\fP"
.br
.ti -1c
.RI "namespace \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "record \fBLuthetus\&.TextEditor\&.RazorLib\&.TextEditors\&.Models\&.WidgetInline\fP (Key< WidgetInline > Key, string Title, string HtmlElementId, Type ComponentType, Dictionary< string, object?>? ComponentParameterMap)"
.br
.RI "This type takes up some amount of width of a text editor row, and therefore shifts any the left position of any columns that follow\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for Luthetus\&.Ide from the source code\&.
