Program.cs
var builder
var hostingInformation
var host
Referenced by RunAsync, StartBackgroundTaskWorkers.
builder.RootComponents. Add< App >("#app")
References builder.
builder.RootComponents. Add< HeadOutlet >("head::after")
References builder.
builder.Services. AddScoped(sp=> new HttpClient { BaseAddress=new Uri(builder.HostEnvironment.BaseAddress) })
References builder.
Referenced by Luthetus.Common.Tests.Basis.Installations.Models.ServiceCollectionExtensionsTests.AddLuthetusCommonServices, Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.InitializeBackgroundTasks, Luthetus.Common.Tests.Basis.FileSystems.FileSystemsTestsHelper.InitializeFileSystemsTests, Luthetus.TextEditor.Tests.Basis.CompilerServices.TextEditorCompilerServicesTestsHelper.InitializeTextEditorCompilerServicesTestsHelper, Luthetus.TextEditor.Tests.Basis.TestsHelper.InitializeTextEditorServicesTestsHelper, Luthetus.CompilerServices.Razor.Tests.RazorCompilerServiceTestsBase.RazorCompilerServiceTestsBase, Luthetus.TextEditor.Tests.Adhoc.PartitionTests.TestInitialize.
builder.Services. AddLuthetusWebsiteServices(hostingInformation)
References builder, hostingInformation.
hostingInformation. StartBackgroundTaskWorkers(host.Services)
References host, hostingInformation.
await host. RunAsync()
References host.