Luthetus::Common::RazorLib::Keymaps::Models::Keymap
readonly object Luthetus.Common.RazorLib.Keymaps.Models.Keymap._syncRoot
Referenced by Luthetus.Common.RazorLib.Keymaps.Models.Keymap.GetCodeKeyValuePairList, Luthetus.Common.RazorLib.Keymaps.Models.Keymap.GetKeyKeyValuePairList, Luthetus.Common.RazorLib.Keymaps.Models.Keymap.GetKeyValuePairList, Luthetus.Common.RazorLib.Keymaps.Models.Keymap.MapFirstOrDefault, Luthetus.Common.RazorLib.Keymaps.Models.Keymap.TryRegister.
readonly Dictionary<string, List<Keybind> > Luthetus.Common.RazorLib.Keymaps.Models.Keymap._mapKey
Referenced by Luthetus.Common.RazorLib.Keymaps.Models.Keymap.MapFirstOrDefault, Luthetus.Common.RazorLib.Keymaps.Models.Keymap.TryRegister.
readonly Dictionary<string, List<Keybind> > Luthetus.Common.RazorLib.Keymaps.Models.Keymap._mapCode
Referenced by Luthetus.Common.RazorLib.Keymaps.Models.Keymap.TryRegister.
Key<Keymap> Luthetus.Common.RazorLib.Keymaps.Models.Keymap.Key
Unique identifier for the keymap.
Referenced by Luthetus.TextEditor.RazorLib.Keymaps.Models.Defaults.TextEditorKeymapDefault.GetLayer, Luthetus.TextEditor.RazorLib.Keymaps.Models.Vims.TextEditorKeymapVim.GetLayer, Luthetus.Common.RazorLib.Keymaps.Models.Keymap.Keymap, Luthetus.TextEditor.RazorLib.Keymaps.Models.Defaults.TextEditorKeymapDefault.TextEditorKeymapDefault, Luthetus.TextEditor.RazorLib.Keymaps.Models.Vims.TextEditorKeymapVim.TextEditorKeymapVim.
string Luthetus.Common.RazorLib.Keymaps.Models.Keymap.DisplayName
User facing name for the keymap.
Referenced by Luthetus.Common.RazorLib.Keymaps.Models.Keymap.Keymap.
List<Keybind>? Luthetus.Common.RazorLib.Keymaps.Models.Keymap.keyMatchList
Referenced by Luthetus.Common.RazorLib.Keymaps.Models.Keymap.MapFirstOrDefault.
Luthetus.Common.RazorLib.Keymaps.Models.Keymap.Keymap(Key< Keymap > key, string displayName)
References Luthetus.Common.RazorLib.Keymaps.Models.Keymap.DisplayName, Luthetus.Common.RazorLib.Keymaps.Models.Keymap.Key.
Referenced by Luthetus.TextEditor.RazorLib.Keymaps.Models.Defaults.TextEditorKeymapDefault.TextEditorKeymapDefault, Luthetus.TextEditor.RazorLib.Keymaps.Models.Vims.TextEditorKeymapVim.TextEditorKeymapVim.
bool Luthetus.Common.RazorLib.Keymaps.Models.Keymap.TryRegister(KeymapArgs args, CommandNoType command)
References Luthetus.Common.RazorLib.Keymaps.Models.Keymap._mapCode, Luthetus.Common.RazorLib.Keymaps.Models.Keymap._mapKey, Luthetus.Common.RazorLib.Keymaps.Models.Keymap._syncRoot, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.Code, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.Key.
List< Keybind >?? List< Keybind > codeMatchList Luthetus.Common.RazorLib.Keymaps.Models.Keymap.MapAll(KeymapArgs args)
bool Luthetus.Common.RazorLib.Keymaps.Models.Keymap.MapFirstOrDefault(KeymapArgs args, out CommandNoType? command)
References Luthetus.Common.RazorLib.Keymaps.Models.Keymap._mapKey, Luthetus.Common.RazorLib.Keymaps.Models.Keymap._syncRoot, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.Code, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.Key, Luthetus.Common.RazorLib.Keymaps.Models.Keymap.keyMatchList.
Referenced by Luthetus.TextEditor.RazorLib.Keymaps.Models.Defaults.TextEditorKeymapDefault.TryMap.
List< KeyValuePair< KeymapArgs, CommandNoType > > Luthetus.Common.RazorLib.Keymaps.Models.Keymap.GetKeyValuePairList()
References Luthetus.Common.RazorLib.Keymaps.Models.Keymap._syncRoot.
List< KeyValuePair< KeymapArgs, CommandNoType > > Luthetus.Common.RazorLib.Keymaps.Models.Keymap.GetKeyKeyValuePairList()
References Luthetus.Common.RazorLib.Keymaps.Models.Keymap._syncRoot.
List< KeyValuePair< KeymapArgs, CommandNoType > > Luthetus.Common.RazorLib.Keymaps.Models.Keymap.GetCodeKeyValuePairList()
References Luthetus.Common.RazorLib.Keymaps.Models.Keymap._syncRoot.