Luthetus::CompilerServices::DotNetSolution::SyntaxActors::DotNetSolutionLexer
Luthetus.CompilerServices.DotNetSolution.SyntaxActors.DotNetSolutionLexer.DotNetSolutionLexer(ResourceUri resourceUri, string sourceText)
References Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.Lexer.LexerKeywords, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.Lexer.ResourceUri.
override void Luthetus.CompilerServices.DotNetSolution.SyntaxActors.DotNetSolutionLexer.Lex()
References Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.Lexer._stringWalker, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.Lexer._syntaxTokenList, Luthetus.CompilerServices.DotNetSolution.Facts.LexSolutionFacts.Header.EXACT_VISUAL_STUDIO_VERSION_START_TOKEN, Luthetus.CompilerServices.DotNetSolution.Facts.LexSolutionFacts.Header.FORMAT_VERSION_START_TOKEN, Luthetus.CompilerServices.DotNetSolution.Facts.LexSolutionFacts.Header.HASHTAG_VISUAL_STUDIO_VERSION_START_TOKEN, Luthetus.CompilerServices.DotNetSolution.SyntaxActors.DotNetSolutionLexer.LexGlobal, Luthetus.CompilerServices.DotNetSolution.SyntaxActors.DotNetSolutionLexer.LexProjectDefinitionEntry, Luthetus.CompilerServices.DotNetSolution.Facts.LexSolutionFacts.Header.MINIMUM_VISUAL_STUDIO_VERSION_START_TOKEN, Luthetus.CompilerServices.DotNetSolution.Facts.LexSolutionFacts.Project.PROJECT_DEFINITION_START_TOKEN, Luthetus.CompilerServices.DotNetSolution.Facts.LexSolutionFacts.Global.START_TOKEN, Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
void Luthetus.CompilerServices.DotNetSolution.SyntaxActors.DotNetSolutionLexer.LexProjectDefinitionEntry()
References Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.Lexer._stringWalker, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.Lexer._syntaxTokenList, Luthetus.CompilerServices.DotNetSolution.SyntaxActors.DotNetSolutionLexer.LexGuid, Luthetus.CompilerServices.DotNetSolution.SyntaxActors.DotNetSolutionLexer.LexString, Luthetus.CompilerServices.DotNetSolution.Facts.LexSolutionFacts.Project.PROJECT_DEFINITION_END_TOKEN, Luthetus.CompilerServices.DotNetSolution.Facts.LexSolutionFacts.Project.PROJECT_DEFINITION_START_TOKEN, Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
Referenced by Luthetus.CompilerServices.DotNetSolution.SyntaxActors.DotNetSolutionLexer.Lex.
void Luthetus.CompilerServices.DotNetSolution.SyntaxActors.DotNetSolutionLexer.LexGuid()
References Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.Lexer._stringWalker, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.Lexer._syntaxTokenList, Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
Referenced by Luthetus.CompilerServices.DotNetSolution.SyntaxActors.DotNetSolutionLexer.LexProjectDefinitionEntry.
void Luthetus.CompilerServices.DotNetSolution.SyntaxActors.DotNetSolutionLexer.LexString()
References Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.Lexer._stringWalker, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.Lexer._syntaxTokenList, Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
Referenced by Luthetus.CompilerServices.DotNetSolution.SyntaxActors.DotNetSolutionLexer.LexProjectDefinitionEntry.
void Luthetus.CompilerServices.DotNetSolution.SyntaxActors.DotNetSolutionLexer.LexGlobal()
References Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.Lexer._stringWalker, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.Lexer._syntaxTokenList, Luthetus.CompilerServices.DotNetSolution.Facts.LexSolutionFacts.Global.END_TOKEN, Luthetus.CompilerServices.DotNetSolution.SyntaxActors.DotNetSolutionLexer.LexGlobalSection, Luthetus.CompilerServices.DotNetSolution.Facts.LexSolutionFacts.Global.START_TOKEN, Luthetus.CompilerServices.DotNetSolution.Facts.LexSolutionFacts.GlobalSection.START_TOKEN, Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
Referenced by Luthetus.CompilerServices.DotNetSolution.SyntaxActors.DotNetSolutionLexer.Lex.
void Luthetus.CompilerServices.DotNetSolution.SyntaxActors.DotNetSolutionLexer.LexGlobalSection(Func< bool > outerLoopBreakPredicate)
References Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.Lexer._stringWalker, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.Lexer._syntaxTokenList, Luthetus.CompilerServices.DotNetSolution.Facts.LexSolutionFacts.GlobalSection.END_TOKEN, Luthetus.CompilerServices.DotNetSolution.Facts.LexSolutionFacts.GlobalSection.START_TOKEN, Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
Referenced by Luthetus.CompilerServices.DotNetSolution.SyntaxActors.DotNetSolutionLexer.LexGlobal.
void Luthetus.CompilerServices.DotNetSolution.SyntaxActors.DotNetSolutionLexer.LexHeaderFormatVersion()
void Luthetus.CompilerServices.DotNetSolution.SyntaxActors.DotNetSolutionLexer.LexHashtagVisualStudioVersion()
void Luthetus.CompilerServices.DotNetSolution.SyntaxActors.DotNetSolutionLexer.LexExactVisualStudioVersion()
void Luthetus.CompilerServices.DotNetSolution.SyntaxActors.DotNetSolutionLexer.LexMinimumVisualStudioVersion()
void Luthetus.CompilerServices.DotNetSolution.SyntaxActors.DotNetSolutionLexer.LexPropertyNameAndValuePairs(Func< bool > outerLoopBreakPredicate)