Luthetus::TextEditor::Tests::Adhoc::PartitionTests
const string Luthetus.TextEditor.Tests.Adhoc.PartitionTests.SAMPLE_CASE_THAT_HAS_LINE_ENDINGS_BREAK_BUG
To recreate the bug: Short description: delete the body of the class definition by seleting it, and hitting enter. Long description:
Locate the open curly brace, of the class definition. Place cursor at the EndExclusiveIndex of the curly brace character (immediately after it, and the cursor is still touching the curly brace, but after it. Select the text from the previously described position to the end curly brace of the class definition. Note: for the end curly brace you are placing the cursor immediately BEFORE it. This will then select all the text within the class definition's body if a deletion occurred. "Press" the 'Enter' key. This should delete all of the text in the class definition's body, and then insert a new line. But, the result is wrong, a lot of text is deleted yes, but there's seemingly "random" gibberish where the text used to be. The hundreds of lines of text that was deleted is reduced down to about 4 lines, but again, its just gibberish.
Referenced by Luthetus.TextEditor.Tests.Adhoc.PartitionTests.Another_Large_Throughput_Test_Backspace, Luthetus.TextEditor.Tests.Adhoc.PartitionTests.Another_Large_Throughput_Test_Delete, Luthetus.TextEditor.Tests.Adhoc.PartitionTests.Another_Large_Throughput_Test_Insert.
async Task Luthetus.TextEditor.Tests.Adhoc.PartitionTests.TwoPartitionEdit_Delete()
Its thought that line ending only text is best to be using for these tests. Since in specific, here we are testing why the line ending tracking is breaking.
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.Tests.Adhoc.PartitionTests.TestInitialize, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor.
async Task Luthetus.TextEditor.Tests.Adhoc.PartitionTests.TwoPartitionEdit_Backspace()
Its thought that line ending only text is best to be using for these tests. Since in specific, here we are testing why the line ending tracking is breaking.
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.Tests.Adhoc.PartitionTests.TestInitialize, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor.
async Task Luthetus.TextEditor.Tests.Adhoc.PartitionTests.TwoPartitionEdit_Insert()
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.Tests.Adhoc.PartitionTests.TestInitialize, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor.
async Task Luthetus.TextEditor.Tests.Adhoc.PartitionTests.ThreePartitionEdit_Delete()
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.Tests.Adhoc.PartitionTests.TestInitialize, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor.
async Task Luthetus.TextEditor.Tests.Adhoc.PartitionTests.Large_Throughput_Test()
This test isn't the most useful thing for determining errors. But it is quite interesting to see the different partition sizes and when it fails.
Then drill into a more specific unit test once an issue is found here is the way I'd look at this unit test if its ever even used.
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.Tests.Adhoc.PartitionTests.TestInitialize, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor.
async Task Luthetus.TextEditor.Tests.Adhoc.PartitionTests.Another_Large_Throughput_Test_Delete()
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.Tests.Adhoc.PartitionTests.SAMPLE_CASE_THAT_HAS_LINE_ENDINGS_BREAK_BUG, Luthetus.TextEditor.Tests.Adhoc.PartitionTests.TestInitialize, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor.
async Task Luthetus.TextEditor.Tests.Adhoc.PartitionTests.Another_Large_Throughput_Test_Backspace()
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.Tests.Adhoc.PartitionTests.SAMPLE_CASE_THAT_HAS_LINE_ENDINGS_BREAK_BUG, Luthetus.TextEditor.Tests.Adhoc.PartitionTests.TestInitialize, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor.
async Task Luthetus.TextEditor.Tests.Adhoc.PartitionTests.Another_Large_Throughput_Test_Insert()
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.Tests.Adhoc.PartitionTests.SAMPLE_CASE_THAT_HAS_LINE_ENDINGS_BREAK_BUG, Luthetus.TextEditor.Tests.Adhoc.PartitionTests.TestInitialize, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor.
TestContext Luthetus.TextEditor.Tests.Adhoc.PartitionTests.TestInitialize()
References AddScoped, hostingInformation, Luthetus.Common.RazorLib.Installations.Models.LuthetusCommonConfig, Luthetus.Common.RazorLib.Installations.Models.LuthetusHostingInformation, Luthetus.TextEditor.RazorLib.Installations.Models.LuthetusTextEditorConfig.
Referenced by Luthetus.TextEditor.Tests.Adhoc.PartitionTests.Another_Large_Throughput_Test_Backspace, Luthetus.TextEditor.Tests.Adhoc.PartitionTests.Another_Large_Throughput_Test_Delete, Luthetus.TextEditor.Tests.Adhoc.PartitionTests.Another_Large_Throughput_Test_Insert, Luthetus.TextEditor.Tests.Adhoc.PartitionTests.Large_Throughput_Test, Luthetus.TextEditor.Tests.Adhoc.PartitionTests.ThreePartitionEdit_Delete, Luthetus.TextEditor.Tests.Adhoc.PartitionTests.TwoPartitionEdit_Backspace, Luthetus.TextEditor.Tests.Adhoc.PartitionTests.TwoPartitionEdit_Delete, Luthetus.TextEditor.Tests.Adhoc.PartitionTests.TwoPartitionEdit_Insert.
void Luthetus.TextEditor.Tests.Adhoc.PartitionTests.LogAndNonScientificallyAssertPartitionList(ITextEditorModel model, string expectedVisualizationText)
I can wrap my head around my unit test much easier if I type the partitions out like:
Given: PartitionSize: = 4 Input text: "\r\n\r\n\r\n" Then: "[\r\n][\r\n\r\n]" , is how am visualizing the partition. So if I can assert my visualization it makes creation of good tests easier, then if my visualization introduces inaccuracies I can add a more 1 to 1 assertion by iterating over the partitions and asserting the richCharacter.Value.