Luthetus::TextEditor::RazorLib::CompilerServices::Utility::StringWalker
int Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.PositionIndex
The character index within the SourceText.
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.BacktrackCharacter, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.BacktrackRange, Luthetus.CompilerServices.Razor.RazorSyntaxTree.ParseAttributeName, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseCommentMultiLine, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseCommentSingleLine, Luthetus.CompilerServices.Razor.RazorSyntaxTree.ParseInjectedLanguageFragment, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseString, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.PeekCharacter, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadCharacter, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadUnsignedNumericLiteral, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadWordTuple, Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
ResourceUri Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ResourceUri
The file that the SourceText came from.
Referenced by Luthetus.CompilerServices.Razor.RazorSyntaxTree.ParseAttributeName, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseCommentMultiLine, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseCommentSingleLine, Luthetus.CompilerServices.Razor.RazorSyntaxTree.ParseInjectedLanguageFragment, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseString, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadWordTuple, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.StringWalker, Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
string Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.SourceText
The text which is to be stepped through.
Referenced by Luthetus.CompilerServices.Razor.RazorSyntaxTree.ParseAttributeName, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseCommentMultiLine, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseCommentSingleLine, Luthetus.CompilerServices.Razor.RazorSyntaxTree.ParseInjectedLanguageFragment, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseString, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.PeekCharacter, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadCharacter, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadWordTuple, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.StringWalker, Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
char Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.CurrentCharacter
Returns PeekCharacter invoked with the value of zero.
Referenced by Luthetus.CompilerServices.Razor.RazorSyntaxTree.ParseAttributeName, Luthetus.CompilerServices.Razor.RazorSyntaxTree.ParseInjectedLanguageFragment, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadLine, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadUnsignedNumericLiteral, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadUntil, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadWhitespace, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadWordTuple.
char Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.NextCharacter
Returns PeekCharacter invoked with the value of one.
string Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.RemainingText
Starting with PeekCharacter evaluated at 0 return that and the rest of the SourceText RemainingText => SourceText.Substring(PositionIndex);.
bool Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.IsEof
Returns if the current character is the end of file character.
Referenced by Luthetus.CompilerServices.Razor.RazorSyntaxTree.ParseAttributeName, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseCommentMultiLine, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseCommentSingleLine, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseString, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadLine, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadUnsignedNumericLiteral, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadUntil, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadWordTuple.
TextEditorTextSpan Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.textSpan
This method will return immediately upon encountering whitespace. Returns a text span with its TextEditorTextSpan.StartingIndexInclusive equal to '-1' if no word was found.
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadWordTuple.
Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.StringWalker(ResourceUri resourceUri, string sourceText)
Pass in the ResourceUri of a file, and its text. One can pass in string.Empty for the ResourceUri if they are only working with the text itself.
References Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ResourceUri, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.SourceText.
Referenced by Luthetus.CompilerServices.Razor.RazorSyntaxTree.ParseCodebehind.
char Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadCharacter()
If PositionIndex is within bounds of the SourceText. Then the character within the string SourceText at index of PositionIndex is returned and PositionIndex is incremented by one. Otherwise, ParserFacts.END_OF_FILE is returned and the value of PositionIndex is unchanged.
References Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.PositionIndex, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.SourceText.
Referenced by Luthetus.CompilerServices.Razor.RazorSyntaxTree.ParseAttributeName, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseCommentMultiLine, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseCommentSingleLine, Luthetus.CompilerServices.Razor.RazorSyntaxTree.ParseInjectedLanguageFragment, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseString, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadLine, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadRange, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadUnsignedNumericLiteral, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadUntil, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadWhitespace, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadWordTuple.
char Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.PeekCharacter(int offset)
If (PositionIndex + offset) is within bounds of the SourceText. Then the character within the string SourceText at index of (PositionIndex + offset) is returned and PositionIndex is unchanged. Otherwise, ParserFacts.END_OF_FILE is returned and the value of PositionIndex is unchanged. offset must be > -1.
References Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.PositionIndex, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.SourceText.
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.BacktrackCharacter, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.PeekNextWord, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.PeekRange.
char Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.BacktrackCharacter()
If PositionIndex being decremented by 1 would result in PositionIndex being less than 0. Then ParserFacts.END_OF_FILE will be returned and PositionIndex will be left unchanged. Otherwise, PositionIndex will be decremented by one and the character within the string SourceText at index of PositionIndex is returned.
References Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.PeekCharacter, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.PositionIndex.
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.BacktrackRange.
string Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadRange(int length)
Iterates a counter from 0 until the counter is equal to length. Each iteration ReadCharacter will be invoked. If an iteration's invocation of ReadCharacter returned ParserFacts.END_OF_FILE then the method will short circuit and return regardless of whether it finished iterating to length or not.
References Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadCharacter.
string Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.PeekRange(int offset, int length)
Iterates a counter from 0 until the counter is equal to length. Each iteration PeekCharacter will be invoked using the (offset + counter). If an iteration's invocation of PeekCharacter returned ParserFacts.END_OF_FILE then the method will short circuit and return regardless of whether it finished iterating to length or not.
References Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.PeekCharacter.
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.PeekForSubstring.
string Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.BacktrackRange(int length)
Iterates a counter from 0 until the counter is equal to length. Each iteration BacktrackCharacter will be invoked using the. If an iteration's invocation of BacktrackCharacter returned ParserFacts.END_OF_FILE then the method will short circuit and return regardless of whether it finished iterating to length or not.
References Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.BacktrackCharacter, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.PositionIndex.
string Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.PeekNextWord()
References Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.PeekCharacter.
Referenced by Luthetus.CompilerServices.Razor.RazorSyntaxTree.ParseInjectedLanguageFragment.
bool Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.PeekForSubstring(string substring)
Form a substring of the SourceText that starts inclusively at the index PositionIndex and has a maximum length of substring.Length. This method uses PeekRange internally and therefore will return a string that ends with ParserFacts.END_OF_FILE if an index out of bounds read was performed on SourceText.
References Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.PeekRange.
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseCommentMultiLine, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseString, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.PeekForSubstringRange.
bool Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.PeekForSubstringRange(ImmutableArray< string > substringsList, out string? matchedOn)
References Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.PeekForSubstring.
Referenced by Luthetus.CompilerServices.Razor.RazorSyntaxTree.ParseAttributeName, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseCommentSingleLine.
string Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadWhitespace(IEnumerable< char >? whitespaceOverrideList=null)
Provide whitespaceOverrideList to override the default of what qualifies as whitespace. The default whitespace chars are: WhitespaceFacts.ALL_LIST.
References Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.CurrentCharacter, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadCharacter.
NumericLiteralToken Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadUnsignedNumericLiteral()
Ex: '1.73', positive only. { 0, ..., 1, ..., 2, ...}
References Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.CurrentCharacter, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.IsEof, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.PositionIndex, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadCharacter, Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
string Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadUntil(char deliminator)
References Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.CurrentCharacter, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.IsEof, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadCharacter.
string Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadLine()
The line ending is NOT included in the returned string.
References Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.CurrentCharacter, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.IsEof, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadCharacter.
TextEditorTextSpan string value Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadWordTuple(ImmutableArray< char >? additionalCharactersToBreakOnList=null)
References Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.CurrentCharacter, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.IsEof, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.PositionIndex, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadCharacter, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ResourceUri, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.SourceText, Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.textSpan.