Luthetus::TextEditor::RazorLib::CompilerServices::Syntax::Nodes::GenericParametersListingNode
ISyntax [] Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode._childList
bool Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode._childListIsDirty
OpenAngleBracketToken Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode.OpenAngleBracketToken
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode.GenericParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode.GetChildList.
List<GenericParameterEntryNode> Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode.GenericParameterEntryNodeList
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GenericParametersListingMergeExpression, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode.GenericParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode.GetChildList.
CloseAngleBracketToken Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode.CloseAngleBracketToken
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AmbiguousIdentifierMergeExpression, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode.GenericParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode.GetChildList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode.SetCloseAngleBracketToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TypeClauseMergeExpression.
TypeClauseNode IExpressionNode. Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode.ResultTypeClauseNode
When parsing an expression, there may be a FunctionInvocationNode with a GenericParametersListingNode.
The expression code works however by passing around an 'IExpression expressionPrimary' and an 'IExpression expressionSeconday'. This means we cannot add common logic for parsing a GenericParametersListingNode unless the expression parsing code were modified, or maybe a call to a separate function to parse GenericParametersListingNode could be done. But, for now an experiment with making GenericParametersListingNode into a IExpressionNode is being tried out. Any IExpressionNode that is part of a complete expression, will have the IExpressionNode.ResultTypeClauseNode of Pseudo in order to indicate that the node is part of a expression, but not itself an expression. Use 'TypeClauseNode IExpressionNode.ResultTypeClauseNode => TypeClauseNodeFacts.Pseudo;' so that some confusion can be avoided since one has to cast it explicitly as an IExpressionNode in order to access the property. (i.e.: GenericParameterEntryNode.TypeClauseNode is not equal to IExpressionNode.ResultTypeClauseNode).
bool Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode.IsFabricated
IsFabricated refers to when the ParserSession expected a node to be valid, but it wasn't. For example, a function invocation on an undefined function will construct a BoundFunctionInvocationNode with IsFabricated set to true.
SyntaxKind Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode.SyntaxKind
Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode.GenericParametersListingNode(OpenAngleBracketToken openAngleBracketToken, List< GenericParameterEntryNode > genericParameterEntryNodeList, CloseAngleBracketToken closeAngleBracketToken)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode.CloseAngleBracketToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode.GenericParameterEntryNodeList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode.OpenAngleBracketToken.
Referenced by Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.FunctionInvocationNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.TypeClauseNodeTests.Constructor, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode.SetCloseAngleBracketToken.
GenericParametersListingNode Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode.SetCloseAngleBracketToken(CloseAngleBracketToken closeAngleBracketToken)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode.CloseAngleBracketToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode.GenericParametersListingNode.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AmbiguousIdentifierMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ConstructorInvocationMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TypeClauseMergeToken.
ISyntax[] Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode.GetChildList()
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode.CloseAngleBracketToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode.GenericParameterEntryNodeList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode.OpenAngleBracketToken.