Luthetus::TextEditor::RazorLib::Diffs::States::TextEditorDiffState
ImmutableList<TextEditorDiffModel> Luthetus.TextEditor.RazorLib.Diffs.States.TextEditorDiffState.DiffModelList
Referenced by Luthetus.TextEditor.RazorLib.Diffs.States.TextEditorDiffState.Reducer.ReduceDisposeAction, Luthetus.TextEditor.RazorLib.Diffs.States.TextEditorDiffState.Reducer.ReduceRegisterAction, Luthetus.TextEditor.RazorLib.Diffs.States.TextEditorDiffState.TextEditorDiffState.
record Luthetus.TextEditor.RazorLib.Diffs.States.TextEditorDiffState.RegisterAction(Key< TextEditorDiffModel > DiffKey, Key< TextEditorViewModel > InViewModelKey, Key< TextEditorViewModel > OutViewModelKey)
Referenced by Luthetus.TextEditor.Tests.Basis.Diffs.States.TextEditorDiffStateReducerTests.ReduceDisposeAction, Luthetus.TextEditor.RazorLib.Diffs.States.TextEditorDiffState.Reducer.ReduceRegisterAction, Luthetus.TextEditor.Tests.Basis.Diffs.States.TextEditorDiffStateReducerTests.ReduceRegisterAction, Luthetus.TextEditor.RazorLib.Diffs.Models.TextEditorDiffApi.Register, Luthetus.TextEditor.Tests.Basis.Diffs.States.TextEditorDiffStateActionsTests.RegisterAction.
record Luthetus.TextEditor.RazorLib.Diffs.States.TextEditorDiffState.DisposeAction(Key< TextEditorDiffModel > DiffKey)
Referenced by Luthetus.TextEditor.RazorLib.Diffs.Models.TextEditorDiffApi.Dispose, Luthetus.TextEditor.Tests.Basis.Diffs.States.TextEditorDiffStateActionsTests.DisposeAction, Luthetus.TextEditor.RazorLib.Diffs.States.TextEditorDiffState.Reducer.ReduceDisposeAction, Luthetus.TextEditor.Tests.Basis.Diffs.States.TextEditorDiffStateReducerTests.ReduceDisposeAction.
Luthetus.TextEditor.RazorLib.Diffs.States.TextEditorDiffState.TextEditorDiffState()
References Luthetus.TextEditor.RazorLib.Diffs.States.TextEditorDiffState.DiffModelList.
Referenced by Luthetus.TextEditor.RazorLib.Diffs.States.TextEditorDiffState.Reducer.ReduceDisposeAction, Luthetus.TextEditor.RazorLib.Diffs.States.TextEditorDiffState.Reducer.ReduceRegisterAction.