Luthetus::TextEditor::RazorLib::CompilerServices::Implementations::CompilerService
readonly Dictionary<ResourceUri, ICompilerServiceResource> Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService._resourceMap
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.DisposeResource, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.GetCompilerServiceResourceFor, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.GetDiagnosticsFor, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.GetSymbolsFor, Luthetus.Ide.RazorLib.Terminals.Models.TerminalCompilerService.GetTokenTextSpansFor, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.GetTokenTextSpansFor, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.ParseAsync, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.RegisterResource.
readonly object Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService._resourceMapLock
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.DisposeResource, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.GetCompilerServiceResourceFor, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.GetDiagnosticsFor, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.GetSymbolsFor, Luthetus.Ide.RazorLib.Terminals.Models.TerminalCompilerService.GetTokenTextSpansFor, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.GetTokenTextSpansFor, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.ParseAsync, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.RegisterResource.
readonly ITextEditorService Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService._textEditorService
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.CompilerService, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.GetCompilerServiceResourceFor, Luthetus.Ide.RazorLib.Terminals.Models.TerminalCompilerService.GetTokenTextSpansFor, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.ParseAsync, Luthetus.CompilerServices.Razor.CompilerServiceCase.RazorCompilerService.RazorCompilerService, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.ResourceWasModified.
CompilerServiceOptions Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService._compilerServiceOptions
Referenced by Luthetus.CompilerServices.C.CCompilerService.CCompilerService, Luthetus.CompilerServices.CSharp.CompilerServiceCase.CSharpCompilerService.CSharpCompilerService, Luthetus.CompilerServices.CSharpProject.CompilerServiceCase.CSharpProjectCompilerService.CSharpProjectCompilerService, Luthetus.CompilerServices.Css.CssCompilerService.CssCompilerService, Luthetus.CompilerServices.DotNetSolution.CompilerServiceCase.DotNetSolutionCompilerService.DotNetSolutionCompilerService, Luthetus.CompilerServices.FSharp.FSharpCompilerService.FSharpCompilerService, Luthetus.CompilerServices.JavaScript.JavaScriptCompilerService.JavaScriptCompilerService, Luthetus.CompilerServices.Json.JsonCompilerService.JsonCompilerService, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.ParseAsync, Luthetus.CompilerServices.Python.PythonCompilerService.PythonCompilerService, Luthetus.CompilerServices.Razor.CompilerServiceCase.RazorCompilerService.RazorCompilerService, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.RegisterResource, Luthetus.Ide.RazorLib.Terminals.Models.TerminalCompilerService.TerminalCompilerService, Luthetus.CompilerServices.TypeScript.TypeScriptCompilerService.TypeScriptCompilerService, Luthetus.CompilerServices.Xml.XmlCompilerService.XmlCompilerService.
Action? Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.ResourceRegistered
Derived types can invoke OnResourceRegistered to fire this event.
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.OnResourceRegistered, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.RegisterResource.
Action? Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.ResourceParsed
Derived types can invoke OnResourceParsed to fire this event.
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.OnResourceParsed.
Action? Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.ResourceDisposed
Derived types can invoke OnResourceDisposed to fire this event.
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.OnResourceDisposed.
virtual IBinder Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.Binder
Referenced by Luthetus.CompilerServices.C.CCompilerService.CCompilerService, Luthetus.CompilerServices.CSharp.CompilerServiceCase.CSharpCompilerService.CSharpCompilerService, Luthetus.CompilerServices.CSharpProject.CompilerServiceCase.CSharpProjectCompilerService.CSharpProjectCompilerService, Luthetus.CompilerServices.Css.CssCompilerService.CssCompilerService, Luthetus.CompilerServices.DotNetSolution.CompilerServiceCase.DotNetSolutionCompilerService.DotNetSolutionCompilerService, Luthetus.CompilerServices.FSharp.FSharpCompilerService.FSharpCompilerService, Luthetus.CompilerServices.JavaScript.JavaScriptCompilerService.JavaScriptCompilerService, Luthetus.CompilerServices.Json.JsonCompilerService.JsonCompilerService, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.ParseAsync, Luthetus.CompilerServices.Python.PythonCompilerService.PythonCompilerService, Luthetus.CompilerServices.TypeScript.TypeScriptCompilerService.TypeScriptCompilerService, Luthetus.CompilerServices.Xml.XmlCompilerService.XmlCompilerService.
virtual ImmutableArray<ICompilerServiceResource> Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.CompilerServiceResources
Referenced by Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.MakeDrawing.
Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.CompilerService(ITextEditorService textEditorService)
getLexerFunc Takes as arguments the resource uri and the source text.
References Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService._textEditorService, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.ResourceWasModified.
virtual void Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.RegisterResource(ResourceUri resourceUri, bool shouldTriggerResourceWasModified)
Expected to be concurrency safe with DisposeResource.
References Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService._compilerServiceOptions, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService._resourceMap, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService._resourceMapLock, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.ResourceRegistered, Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.ResourceWasModified.
virtual ? ICompilerServiceResource Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.GetCompilerServiceResourceFor(ResourceUri resourceUri)
References Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService._resourceMap, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService._resourceMapLock, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService._textEditorService, Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri.
virtual ImmutableArray< TextEditorTextSpan > Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.GetTokenTextSpansFor(ResourceUri resourceUri)
Provides syntax highlighting from the lexing result. This method is invoked, and applied, before GetSymbolsFor.
References Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService._resourceMap, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService._resourceMapLock, Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri.
virtual ImmutableArray< ITextEditorSymbol > Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.GetSymbolsFor(ResourceUri resourceUri)
Provides syntax highlighting that cannot be determined by lexing alone. This method is invoked, and applied, after GetTokenTextSpansFor.
References Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService._resourceMap, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService._resourceMapLock, Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri.
virtual ImmutableArray< TextEditorDiagnostic > Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.GetDiagnosticsFor(ResourceUri resourceUri)
Provides 'squigglies' which when hovered over display a message, along with a serverity level.
References Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService._resourceMap, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService._resourceMapLock, Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri.
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.ParseAsync.
virtual void Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.ResourceWasModified(ResourceUri resourceUri, ImmutableArray< TextEditorTextSpan > editTextSpansList)
Expected to be an Microsoft.Extensions.Hosting.IHostedService (or anything which performs background task work).
References Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService._textEditorService, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.CompilerService, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.ParseAsync, Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri.
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.RegisterResource.
virtual void Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.CursorWasModified(ResourceUri resourceUri, TextEditorCursor cursor)
(2024-01-28) Goal: track the cursor's position within the compilation unit as it moves.
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor.
virtual ImmutableArray< AutocompleteEntry > Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.GetAutocompleteEntries(string word, TextEditorTextSpan textSpan)
When a user types a period ('.') or hits the keybind: { 'Ctrl' + 'Space' } this method is invoked to populate the autocomplete menu.
References Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
virtual Task Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.ParseAsync(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier)
References Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService._compilerServiceOptions, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService._resourceMap, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService._resourceMapLock, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService._textEditorService, Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorModelApi.ApplySyntaxHighlighting, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.Binder, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.CompletePendingCalculatePresentationModel, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.GetDiagnosticsFor, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.ILexer.Lex, Luthetus.TextEditor.RazorLib.ITextEditorService.ModelApi, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.OnResourceParsed, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IParser.Parse, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.PresentationModelList, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ResourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.ILexer.SyntaxTokenList, Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.TextEditorService.
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.ResourceWasModified.
virtual void Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.DisposeResource(ResourceUri resourceUri)
Expected to be concurrency safe with RegisterResource.
References Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService._resourceMap, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService._resourceMapLock, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.OnResourceDisposed, Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri.
virtual void Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.OnResourceRegistered()
A method wrapper for ResourceRegistered as to allow dervied types to invoke the event.
References Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.ResourceRegistered.
virtual void Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.OnResourceParsed()
A method wrapper for ResourceParsed as to allow dervied types to invoke the event.
References Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.ResourceParsed.
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.ParseAsync.
virtual void Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.OnResourceDisposed()
A method wrapper for ResourceDisposed as to allow derived types to invoke the event.
References Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.ResourceDisposed.
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.DisposeResource.