Luthetus::CompilerServices::CSharp::ParserCase::Internals::ParseDefaultKeywords
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleAsTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleBaseTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleBoolTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleTypeIdentifierKeyword.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleBreakTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleByteTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleTypeIdentifierKeyword.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleCaseTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.ExpressionList, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleCatchTokenKeyword(CSharpParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TryStatementNode.SetTryStatementCatchNode, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.SyntaxStack, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.TryStatementCatchNode.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleCharTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleTypeIdentifierKeyword.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleCheckedTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleConstTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleContinueTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleDecimalTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleTypeIdentifierKeyword.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleDefaultTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleDelegateTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleTypeIdentifierKeyword.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleDoTokenKeyword(CSharpParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.DoWhileStatementNode, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.SyntaxStack, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleDoubleTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleTypeIdentifierKeyword.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleElseTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleEnumTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleStorageModifierTokenKeyword.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleEventTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleExplicitTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleExternTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleFalseTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleFinallyTokenKeyword(CSharpParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TryStatementNode.SetTryStatementFinallyNode, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.SyntaxStack, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.TryStatementFinallyNode.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleFixedTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleFloatTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleTypeIdentifierKeyword.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleForTokenKeyword(CSharpParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.EmptyExpressionNode, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.ExpressionList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ForStatementNode, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.SyntaxStack, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ToTypeClause, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Void.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleForeachTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.ExpressionList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ForeachStatementNode, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.SyntaxStack, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.VariableDeclarationNode.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleGotoTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleImplicitTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleInTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleIntTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleTypeIdentifierKeyword.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleIsTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleLockTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.ExpressionList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.LockStatementNode, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.SyntaxStack, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleLongTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleTypeIdentifierKeyword.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleNullTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleTypeIdentifierKeyword.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleObjectTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleTypeIdentifierKeyword.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleOperatorTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleOutTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleParamsTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleProtectedTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleReadonlyTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleRefTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleSbyteTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleTypeIdentifierKeyword.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleShortTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleTypeIdentifierKeyword.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleSizeofTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleStackallocTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleStringTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleTypeIdentifierKeyword.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleStructTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleStorageModifierTokenKeyword.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleSwitchTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.ExpressionList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.SwitchStatementNode, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.SyntaxStack, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleThisTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleThrowTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleTrueTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleTryTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.CurrentCodeBlockBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.SyntaxStack, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.TryStatementNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.TryStatementTryNode.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleTypeofTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleUintTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleTypeIdentifierKeyword.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleUlongTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleTypeIdentifierKeyword.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleUncheckedTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleUnsafeTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleUshortTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleTypeIdentifierKeyword.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleVoidTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleTypeIdentifierKeyword.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleVolatileTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleWhileTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.ExpressionList, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.SyntaxStack, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.WhileStatementNode.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleUnrecognizedTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleDefault(CSharpParserModel model)
The 'Default' of this method name is confusing. It seems to refer to the 'default' of switch statement rather than the 'default' keyword itself?
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleTypeIdentifierKeyword(CSharpParserModel model)
Referenced by Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleBoolTokenKeyword, Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleByteTokenKeyword, Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleCharTokenKeyword, Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleDecimalTokenKeyword, Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleDelegateTokenKeyword, Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleDoubleTokenKeyword, Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleFloatTokenKeyword, Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleIntTokenKeyword, Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleLongTokenKeyword, Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleNullTokenKeyword, Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleObjectTokenKeyword, Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleSbyteTokenKeyword, Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleShortTokenKeyword, Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleStringTokenKeyword, Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleUintTokenKeyword, Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleUlongTokenKeyword, Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleUshortTokenKeyword, Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleVoidTokenKeyword.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleNewTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandlePublicTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleInternalTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandlePrivateTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleStaticTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleOverrideTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleVirtualTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleAbstractTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleSealedTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleIfTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.Binder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.ExpressionList, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.SyntaxStack, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleUsingTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.Binder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.DiagnosticBag, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.UsingStatementNode.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleInterfaceTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleStorageModifierTokenKeyword(CSharpParserModel model)
Example: public class MyClass { } ^.
Given the example the 'MyClass' is the next token upon invocation of this method. Invocation of this method implies the current token was class, interface, struct, etc...
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.Binder, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.IdentifierToken, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.SyntaxStack, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.TypeDefinitionNode.
Referenced by Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleClassTokenKeyword, Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleEnumTokenKeyword, Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseContextualKeywords.HandleRecordTokenContextualKeyword, Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleStructTokenKeyword.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleClassTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleStorageModifierTokenKeyword.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleNamespaceTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.Binder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.DiagnosticBag, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.NamespaceStatementNode, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.SyntaxStack, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.
static void Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleReturnTokenKeyword(CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.StatementBuilder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker.