Luthetus::Extensions::DotNet::Namespaces::Models::TreeViewHelperRazorMarkup
static async Task< List< TreeViewNoType > > Luthetus.Extensions.DotNet.Namespaces.Models.TreeViewHelperRazorMarkup.LoadChildrenAsync(TreeViewNamespacePath razorMarkupTreeView)
This method is used in order to allow for collapsing and expanding the node to refresh the codebehinds.
This method is not the same as FindRelatedFiles.
References Luthetus.Common.RazorLib.TreeViews.Models.TreeViewNoType.ChildList, Luthetus.Extensions.DotNet.Namespaces.Models.TreeViewNamespacePath.CommonComponentRenderers, Luthetus.Extensions.DotNet.Namespaces.Models.TreeViewNamespacePath.DotNetComponentRenderers, Luthetus.Extensions.DotNet.Namespaces.Models.TreeViewNamespacePath.EnvironmentProvider, Luthetus.Extensions.DotNet.Namespaces.Models.TreeViewNamespacePath.FileSystemProvider, Luthetus.Extensions.DotNet.Namespaces.Models.TreeViewHelperRazorMarkup.FindRelatedFiles, Luthetus.Extensions.DotNet.Namespaces.Models.TreeViewNamespacePath.IdeComponentRenderers, Luthetus.Common.RazorLib.TreeViews.Models.TreeViewWithType< T >.Item.
Referenced by Luthetus.Extensions.DotNet.Namespaces.Models.TreeViewNamespacePath.LoadChildListAsync.
static void Luthetus.Extensions.DotNet.Namespaces.Models.TreeViewHelperRazorMarkup.FindRelatedFiles(TreeViewNamespacePath razorMarkupTreeView, List< TreeViewNoType > siblingsAndSelfTreeViews)
This method is used in order to remove from the parent node, various siblings which will be moved to be a child node of the '.razor' file.
This is method not the same as LoadChildrenAsync.
References Luthetus.Common.RazorLib.TreeViews.Models.TreeViewNoType.ChildList.
Referenced by Luthetus.Extensions.DotNet.Namespaces.Models.TreeViewHelperRazorMarkup.LoadChildrenAsync, Luthetus.Extensions.DotNet.Namespaces.Models.TreeViewNamespacePath.RemoveRelatedFilesFromParent.