Luthetus::Extensions::DotNet::DotNetSolutions::Models::Internals::SolutionVisualizationModel
const int Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.RENDER_CYCLE_LIST_CONNECTIONS_INDEX
const int Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.RENDER_CYCLE_LIST_SOLUTION_INDEX
const int Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.RENDER_CYCLE_LIST_PROJECTS_INDEX
const int Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.RENDER_CYCLE_LIST_CLASSES_INDEX
readonly Action Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel._onStateChangedAction
IAbsolutePath? Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.SolutionAbsolutePath
Referenced by Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.MakeDrawing, Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.ShallowClone, Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.SolutionVisualizationModel.
SolutionVisualizationDimensions Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.Dimensions
Referenced by Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.ShallowClone, Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.SolutionVisualizationModel.
List<ISolutionVisualizationDrawing> Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.SolutionVisualizationDrawingList
Referenced by Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.ShallowClone.
List<List<ISolutionVisualizationDrawing> > Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.SolutionVisualizationDrawingRenderCycleList
Referenced by Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.ShallowClone.
Dictionary<string, ISolutionVisualizationDrawing> Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.ParentMap
Referenced by Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.ShallowClone.
Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.SolutionVisualizationModel(IAbsolutePath? solutionAbsolutePath, Action onStateChangedAction)
References Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.Dimensions, Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.SolutionAbsolutePath.
Referenced by Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.MakeDrawing, Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.ShallowClone.
SolutionVisualizationModel Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.ShallowClone()
References Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.Dimensions, Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.ParentMap, Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.SolutionAbsolutePath, Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.SolutionVisualizationDrawingList, Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.SolutionVisualizationDrawingRenderCycleList, Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.SolutionVisualizationModel.
Referenced by Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.MakeDrawing.
SolutionVisualizationModel Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.MakeDrawing(DotNetSolutionCompilerService dotNetSolutionCompilerService, CSharpProjectCompilerService cSharpProjectCompilerService, CSharpCompilerService cSharpCompilerService)
References Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.CompilerServiceResources, Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.ShallowClone, Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.SolutionAbsolutePath, Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.SolutionVisualizationModel.
void Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.DrawSolution(ICompilerServiceResource dotNetSolutionResource, SolutionVisualizationModel localSolutionVisualizationModel, int radius, int centerX, int centerY, int rowIndex, int columnIndex, int renderCycleIndex)
void Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.DrawProjects(ImmutableArray< ICompilerServiceResource > cSharpProjectResourceList, SolutionVisualizationModel localSolutionVisualizationModel, int radius, int centerX, int centerY, int rowIndex, int columnIndex, int renderCycleIndex)
void Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.DrawClasses(ImmutableArray< ICompilerServiceResource > cSharpResourceList, SolutionVisualizationModel localSolutionVisualizationModel, int radius, int centerX, int centerY, int rowIndex, int columnIndex, int renderCycleIndex)
void Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationModel.DrawConnections(SolutionVisualizationModel localSolutionVisualizationModel, int renderCycleIndex)