Luthetus::TextEditor::RazorLib::CompilerServices::Syntax::Nodes::ConstructorInvocationExpressionNode
ISyntax [] Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode._childList
bool Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode._childListIsDirty
KeywordToken Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.NewKeywordToken
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.ConstructorInvocationExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.GetChildList.
TypeClauseNode Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.ResultTypeClauseNode
When parsing an expression, there may be a FunctionInvocationNode with a GenericParametersListingNode.
The expression code works however by passing around an 'IExpression expressionPrimary' and an 'IExpression expressionSeconday'. This means we cannot add common logic for parsing a GenericParametersListingNode unless the expression parsing code were modified, or maybe a call to a separate function to parse GenericParametersListingNode could be done. But, for now an experiment with making GenericParametersListingNode into a IExpressionNode is being tried out. Any IExpressionNode that is part of a complete expression, will have the IExpressionNode.ResultTypeClauseNode of Pseudo in order to indicate that the node is part of a expression, but not itself an expression. Use 'TypeClauseNode IExpressionNode.ResultTypeClauseNode => TypeClauseNodeFacts.Pseudo;' so that some confusion can be avoided since one has to cast it explicitly as an IExpressionNode in order to access the property. (i.e.: GenericParameterEntryNode.TypeClauseNode is not equal to IExpressionNode.ResultTypeClauseNode).
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.ConstructorInvocationExpressionNode, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ConstructorInvocationMergeExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ConstructorInvocationMergeToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.GetChildList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.SetTypeClauseNode.
FunctionParametersListingNode? Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.FunctionParametersListingNode
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.ConstructorInvocationExpressionNode, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ConstructorInvocationMergeExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ConstructorInvocationMergeToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.GetChildList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.SetFunctionParametersListingNode.
ObjectInitializationParametersListingNode? Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.ObjectInitializationParametersListingNode
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.ConstructorInvocationExpressionNode, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ConstructorInvocationMergeExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ConstructorInvocationMergeToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.GetChildList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.SetObjectInitializationParametersListingNode.
ConstructorInvocationStageKind Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.ConstructorInvocationStageKind
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ConstructorInvocationMergeExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ConstructorInvocationMergeToken.
bool Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.IsFabricated
IsFabricated refers to when the ParserSession expected a node to be valid, but it wasn't. For example, a function invocation on an undefined function will construct a BoundFunctionInvocationNode with IsFabricated set to true.
SyntaxKind Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.SyntaxKind
Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.ConstructorInvocationExpressionNode(KeywordToken newKeywordToken, TypeClauseNode typeClauseNode, FunctionParametersListingNode? functionParametersListingNode, ObjectInitializationParametersListingNode? objectInitializationParametersListingNode)
The GenericParametersListingNode is located on the TypeClauseNode.
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.FunctionParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.NewKeywordToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.ObjectInitializationParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.ResultTypeClauseNode.
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.SetFunctionParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.SetObjectInitializationParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.SetTypeClauseNode.
ConstructorInvocationExpressionNode Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.SetTypeClauseNode(TypeClauseNode? resultTypeClauseNode)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.ConstructorInvocationExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.ResultTypeClauseNode.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ConstructorInvocationMergeToken.
ConstructorInvocationExpressionNode Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.SetFunctionParametersListingNode(FunctionParametersListingNode? functionParametersListingNode)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.ConstructorInvocationExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.FunctionParametersListingNode.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ConstructorInvocationMergeToken.
ConstructorInvocationExpressionNode Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.SetObjectInitializationParametersListingNode(ObjectInitializationParametersListingNode? objectInitializationParametersListingNode)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.ConstructorInvocationExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.ObjectInitializationParametersListingNode.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ConstructorInvocationMergeToken.
ISyntax[] Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.GetChildList()
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.FunctionParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.NewKeywordToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.ObjectInitializationParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.ResultTypeClauseNode.