Luthetus::TextEditor::Tests::Basis::TextEditorTestBase
BackgroundTaskService Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.backgroundTaskService
Referenced by Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.InitializeBackgroundTasks.
BackgroundTaskService ContinuousBackgroundTaskWorker Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.backgroundTaskWorker
Referenced by Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.InitializeBackgroundTasks.
BackgroundTaskService ContinuousBackgroundTaskWorker IDispatcher Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.dispatcher
TextEditorModel Luthetus.TextEditor.Tests.Basis.TextEditorTestBase::inModel
Text Editor UI result (with show-newlines and show-whitespace; arrow is tab, and dot is space) ===================== 1 2 b9\r 3 9B\r 4 --->$;∙EOF .
Referenced by Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.CanRedoEdit, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.CanUndoEdit, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.ClearContent, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.ClearOnlyRowEndingKind, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Constructor, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_Between_0_And_DocumentLength_Exclusive_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_Between_0_And_DocumentLength_Exclusive_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_Between_0_And_DocumentLength_Exclusive_ExpandWord_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_Between_0_And_DocumentLength_Exclusive_ExpandWord_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_EqualTo_DocumentLength_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_EqualTo_DocumentLength_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_EqualTo_NegativeOne_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_EqualTo_NegativeOne_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_EqualTo_OnePlusDocumentLength_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_EqualTo_OnePlusDocumentLength_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_EqualTo_Zero_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_EqualTo_Zero_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_Causes_DecreaseCounters_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_Causes_DecreaseCounters_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_Causes_MaintainCounters_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_Causes_MaintainCounters_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_EmptyEditor_At_PositionIndex_EqualTo_DocumentLength_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_EmptyEditor_At_PositionIndex_EqualTo_DocumentLength_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_EmptyEditor_At_PositionIndex_EqualTo_NegativeOne_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_EmptyEditor_At_PositionIndex_EqualTo_NegativeOne_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_EmptyEditor_At_PositionIndex_EqualTo_OnePlusDocumentLength_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_EmptyEditor_At_PositionIndex_EqualTo_OnePlusDocumentLength_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_EmptyEditor_At_PositionIndex_EqualTo_Zero_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_EmptyEditor_At_PositionIndex_EqualTo_Zero_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_Between_0_And_DocumentLength_Exclusive_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_Between_0_And_DocumentLength_Exclusive_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_Between_0_And_DocumentLength_Exclusive_ExpandWord_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_Between_0_And_DocumentLength_Exclusive_ExpandWord_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_EqualTo_DocumentLength_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_EqualTo_DocumentLength_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_EqualTo_NegativeOne_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_EqualTo_NegativeOne_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_EqualTo_OnePlusDocumentLength_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_EqualTo_OnePlusDocumentLength_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_EqualTo_Zero_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_EqualTo_Zero_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_Causes_DecreaseCounters_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_Causes_DecreaseCounters_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_Causes_MaintainCounters_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_Causes_MaintainCounters_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.Dispose, Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.EmptyEditor_TestData_And_PerformPreAssertions, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Enter_Enter_Backspace_CarriageReturn, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Enter_Enter_Backspace_CarriageReturnLineFeed, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Enter_Enter_Backspace_LineFeed, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.FindMatches, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetAllText, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.GetAllText, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetAllText_Equals_GetLines_MadeIntoA_String, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetCharacter, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetCharacterKind, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetColumnIndexOfCharacterWithDifferingKind, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetLengthOfLine, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetLineAndColumnIndicesFromPositionIndex, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetLineInformation, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetLineInformationFromPositionIndex, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetLineRichCharacterRange, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetLineText, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetLineTextRange, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.GetModelOrDefault, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.GetOrDefault, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetPositionIndex_LineIndex_ColumnIndex, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetPositionIndex_TextEditorCursor, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetPositionIndex_TextEditorCursorModifier, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetString, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetTabCountOnSameLineBeforeCursor, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetTextOffsettingCursor, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetWordTextSpan, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.HandleKeyboardEvent, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_EmptyEditor_At_Position_One_Plus_DocumentLength, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_EmptyEditor_At_PositionIndex_DocumentLength, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_EmptyEditor_At_PositionIndex_Negative_One, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_EmptyEditor_At_PositionIndex_Zero, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_EmptyEditor_Empty_String, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_EmptyEditor_Null_String, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_NotEmptyEditor_At_Position_One_Plus_DocumentLength, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_NotEmptyEditor_At_PositionIndex_Between_0_And_DocumentLength_Exclusive, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_NotEmptyEditor_At_PositionIndex_Between_0_And_DocumentLength_Exclusive_With_Selection, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_NotEmptyEditor_At_PositionIndex_DocumentLength, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_NotEmptyEditor_At_PositionIndex_Negative_One, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_NotEmptyEditor_At_PositionIndex_Zero, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_NotEmptyEditor_Empty_String, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_NotEmptyEditor_Null_String, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.ModifyResourceData, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.ModifyUsingRowEndingKind, Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.NotEmptyEditor_TestData_And_PerformPreAssertions, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.ReadNextWordOrDefault, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.ReadPreviousWordOrDefault, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.Register, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.SetContent_DecreaseCounters, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.SetContent_IncreaseCounters, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.SetContent_MaintainCounters, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.WithValue.
BackgroundTaskService ContinuousBackgroundTaskWorker IDispatcher ITextEditorService textEditorService Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.InitializeBackgroundTasks()
References AddScoped, Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.backgroundTaskService, Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.backgroundTaskWorker, hostingInformation, Luthetus.Common.RazorLib.Installations.Models.LuthetusCommonConfig, Luthetus.Common.RazorLib.Installations.Models.LuthetusHostingInformation, Luthetus.TextEditor.RazorLib.Installations.Models.LuthetusTextEditorConfig, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
TextEditorModel TextEditorModelModifier modelModifier Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.EmptyEditor_TestData_And_PerformPreAssertions(ResourceUri resourceUri, DateTime resourceLastWriteTime, string fileExtension, string content, IDecorationMapper? decorationMapper, ICompilerService? compilerService, int partitionSize)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.CharCount, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.FileExtension, Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.inModel, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.LineEndKindCountList, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.LineEndList, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.PartitionList, Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.TabKeyPositionList.
Referenced by Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_EmptyEditor_At_PositionIndex_EqualTo_DocumentLength_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_EmptyEditor_At_PositionIndex_EqualTo_DocumentLength_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_EmptyEditor_At_PositionIndex_EqualTo_NegativeOne_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_EmptyEditor_At_PositionIndex_EqualTo_NegativeOne_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_EmptyEditor_At_PositionIndex_EqualTo_OnePlusDocumentLength_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_EmptyEditor_At_PositionIndex_EqualTo_OnePlusDocumentLength_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_EmptyEditor_At_PositionIndex_EqualTo_Zero_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_EmptyEditor_At_PositionIndex_EqualTo_Zero_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Enter_Enter_Backspace_CarriageReturn, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Enter_Enter_Backspace_CarriageReturnLineFeed, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Enter_Enter_Backspace_LineFeed, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_EmptyEditor_At_Position_One_Plus_DocumentLength, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_EmptyEditor_At_PositionIndex_DocumentLength, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_EmptyEditor_At_PositionIndex_Negative_One, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_EmptyEditor_At_PositionIndex_Zero, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_EmptyEditor_Empty_String, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_EmptyEditor_Null_String.
TextEditorModel TextEditorModelModifier modelModifier Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.NotEmptyEditor_TestData_And_PerformPreAssertions(ResourceUri resourceUri, DateTime resourceLastWriteTime, string fileExtension, string content, IDecorationMapper? decorationMapper, ICompilerService? compilerService, int partitionSize)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.CharCount, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.FileExtension, Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.inModel, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.LineEndKindCountList, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.LineEndList, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.PartitionList, Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.TabKeyPositionList.
Referenced by Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.CanRedoEdit, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.CanUndoEdit, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_Between_0_And_DocumentLength_Exclusive_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_Between_0_And_DocumentLength_Exclusive_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_Between_0_And_DocumentLength_Exclusive_ExpandWord_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_Between_0_And_DocumentLength_Exclusive_ExpandWord_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_EqualTo_DocumentLength_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_EqualTo_DocumentLength_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_EqualTo_NegativeOne_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_EqualTo_NegativeOne_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_EqualTo_OnePlusDocumentLength_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_EqualTo_OnePlusDocumentLength_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_EqualTo_Zero_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_EqualTo_Zero_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_Causes_DecreaseCounters_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_Causes_DecreaseCounters_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_Causes_MaintainCounters_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_Causes_MaintainCounters_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_Between_0_And_DocumentLength_Exclusive_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_Between_0_And_DocumentLength_Exclusive_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_Between_0_And_DocumentLength_Exclusive_ExpandWord_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_Between_0_And_DocumentLength_Exclusive_ExpandWord_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_EqualTo_DocumentLength_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_EqualTo_DocumentLength_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_EqualTo_NegativeOne_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_EqualTo_NegativeOne_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_EqualTo_OnePlusDocumentLength_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_EqualTo_OnePlusDocumentLength_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_EqualTo_Zero_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_EqualTo_Zero_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_Causes_DecreaseCounters_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_Causes_DecreaseCounters_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_Causes_MaintainCounters_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_Causes_MaintainCounters_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.FindMatches, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetAllText, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetAllText_Equals_GetLines_MadeIntoA_String, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetCharacter, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetCharacterKind, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetColumnIndexOfCharacterWithDifferingKind, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetLengthOfLine, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetLineAndColumnIndicesFromPositionIndex, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetLineInformation, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetLineInformationFromPositionIndex, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetLineRichCharacterRange, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetLineText, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetLineTextRange, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetPositionIndex_LineIndex_ColumnIndex, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetPositionIndex_TextEditorCursor, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetPositionIndex_TextEditorCursorModifier, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetString, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetTabCountOnSameLineBeforeCursor, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetTextOffsettingCursor, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetWordTextSpan, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_NotEmptyEditor_At_Position_One_Plus_DocumentLength, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_NotEmptyEditor_At_PositionIndex_Between_0_And_DocumentLength_Exclusive, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_NotEmptyEditor_At_PositionIndex_Between_0_And_DocumentLength_Exclusive_With_Selection, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_NotEmptyEditor_At_PositionIndex_DocumentLength, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_NotEmptyEditor_At_PositionIndex_Negative_One, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_NotEmptyEditor_At_PositionIndex_Zero, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_NotEmptyEditor_Empty_String, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_NotEmptyEditor_Null_String, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.ReadNextWordOrDefault, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.ReadPreviousWordOrDefault, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.SetContent_DecreaseCounters, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.SetContent_IncreaseCounters, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.SetContent_MaintainCounters.