Luthetus::Common::RazorLib::FileSystems::Models::InMemoryFileSystemProvider::InMemoryFileHandler
const bool Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.IS_DIRECTORY_RESPONSE
readonly InMemoryFileSystemProvider Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler._inMemoryFileSystemProvider
readonly IEnvironmentProvider Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler._environmentProvider
readonly ICommonComponentRenderers Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler._commonComponentRenderers
readonly IDispatcher Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler._dispatcher
Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.InMemoryFileHandler(InMemoryFileSystemProvider inMemoryFileSystemProvider, IEnvironmentProvider environmentProvider, ICommonComponentRenderers commonComponentRenderers, IDispatcher dispatcher)
References Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileSystemProvider.
Task< bool > Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.ExistsAsync(string absolutePathString, CancellationToken cancellationToken=default)
References Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.UnsafeExistsAsync.
Referenced by Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.UnsafeMoveAsync.
async Task Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.DeleteAsync(string absolutePathString, CancellationToken cancellationToken=default)
References Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.UnsafeDeleteAsync.
async Task Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.CopyAsync(string sourceAbsolutePathString, string destinationAbsolutePathString, CancellationToken cancellationToken=default)
References Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.UnsafeCopyAsync.
async Task Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.MoveAsync(string sourceAbsolutePathString, string destinationAbsolutePathString, CancellationToken cancellationToken=default)
References Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.UnsafeMoveAsync.
async Task< DateTime > Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.GetLastWriteTimeAsync(string absolutePathString, CancellationToken cancellationToken=default)
References Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.UnsafeGetLastWriteTimeAsync.
async Task< string > Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.ReadAllTextAsync(string absolutePathString, CancellationToken cancellationToken=default)
References Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.UnsafeReadAllTextAsync.
async Task Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.WriteAllTextAsync(string absolutePathString, string contents, CancellationToken cancellationToken=default)
References Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.UnsafeWriteAllTextAsync.
Task< bool > Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.UnsafeExistsAsync(string absolutePathString, CancellationToken cancellationToken=default)
Referenced by Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.ExistsAsync.
Task Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.UnsafeDeleteAsync(string absolutePathString, CancellationToken cancellationToken=default)
Referenced by Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.DeleteAsync, Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.UnsafeMoveAsync.
async Task Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.UnsafeCopyAsync(string sourceAbsolutePathString, string destinationAbsolutePathString, CancellationToken cancellationToken=default)
References Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.UnsafeReadAllTextAsync, Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.UnsafeWriteAllTextAsync.
Referenced by Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.CopyAsync, Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.UnsafeMoveAsync.
async Task Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.UnsafeMoveAsync(string sourceAbsolutePathString, string destinationAbsolutePathString, CancellationToken cancellationToken=default)
References Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.ExistsAsync, Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.UnsafeCopyAsync, Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.UnsafeDeleteAsync.
Referenced by Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.MoveAsync.
Task< DateTime > Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.UnsafeGetLastWriteTimeAsync(string absolutePathString, CancellationToken cancellationToken=default)
Referenced by Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.GetLastWriteTimeAsync.
Task< string > Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.UnsafeReadAllTextAsync(string absolutePathString, CancellationToken cancellationToken=default)
Referenced by Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.ReadAllTextAsync, Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.UnsafeCopyAsync.
Task Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.UnsafeWriteAllTextAsync(string absolutePathString, string contents, CancellationToken cancellationToken=default)
References Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFile, Luthetus.Common.RazorLib.FileSystems.Models.SimplePath.
Referenced by Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.UnsafeCopyAsync, Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.WriteAllTextAsync.
void Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.NotifyUserOfException(Exception exception)