Luthetus::TextEditor::RazorLib::CompilerServices::Syntax::Nodes::ParenthesizedExpressionNode
ISyntax [] Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode._childList
bool Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode._childListIsDirty
OpenParenthesisToken Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.OpenParenthesisToken
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.GetChildList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.ParenthesizedExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.ParenthesizedExpressionNode, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ParenthesizedMergeExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ParenthesizedMergeToken.
IExpressionNode Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.InnerExpression
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.GetChildList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.ParenthesizedExpressionNode, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ParenthesizedMergeExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ParenthesizedMergeToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.SetInnerExpression.
CloseParenthesisToken Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.CloseParenthesisToken
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.GetChildList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.ParenthesizedExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.SetCloseParenthesisToken.
TypeClauseNode Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.ResultTypeClauseNode
When parsing an expression, there may be a FunctionInvocationNode with a GenericParametersListingNode.
The expression code works however by passing around an 'IExpression expressionPrimary' and an 'IExpression expressionSeconday'. This means we cannot add common logic for parsing a GenericParametersListingNode unless the expression parsing code were modified, or maybe a call to a separate function to parse GenericParametersListingNode could be done. But, for now an experiment with making GenericParametersListingNode into a IExpressionNode is being tried out. Any IExpressionNode that is part of a complete expression, will have the IExpressionNode.ResultTypeClauseNode of Pseudo in order to indicate that the node is part of a expression, but not itself an expression. Use 'TypeClauseNode IExpressionNode.ResultTypeClauseNode => TypeClauseNodeFacts.Pseudo;' so that some confusion can be avoided since one has to cast it explicitly as an IExpressionNode in order to access the property. (i.e.: GenericParameterEntryNode.TypeClauseNode is not equal to IExpressionNode.ResultTypeClauseNode).
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.GetChildList.
bool Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.IsFabricated
IsFabricated refers to when the ParserSession expected a node to be valid, but it wasn't. For example, a function invocation on an undefined function will construct a BoundFunctionInvocationNode with IsFabricated set to true.
SyntaxKind Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.SyntaxKind
Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.ParenthesizedExpressionNode(OpenParenthesisToken openParenthesisToken, IExpressionNode innerExpression, CloseParenthesisToken closeParenthesisToken)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.CloseParenthesisToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.InnerExpression, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.OpenParenthesisToken.
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.SetCloseParenthesisToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.SetInnerExpression.
Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.ParenthesizedExpressionNode(OpenParenthesisToken openParenthesisToken, TypeClauseNode typeClauseNode)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.OpenParenthesisToken.
ParenthesizedExpressionNode Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.SetCloseParenthesisToken(CloseParenthesisToken closeParenthesisToken)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.CloseParenthesisToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.ParenthesizedExpressionNode.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ParenthesizedMergeToken.
ParenthesizedExpressionNode Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.SetInnerExpression(IExpressionNode innerExpression)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.InnerExpression, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.ParenthesizedExpressionNode.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ParenthesizedMergeExpression.
ISyntax[] Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.GetChildList()
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.CloseParenthesisToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.InnerExpression, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.OpenParenthesisToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.ResultTypeClauseNode.