Luthetus::TextEditor::RazorLib::TextEditors::Models::TextEditorPartition
List<RichCharacter> Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.RichCharacterList
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.Insert, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.InsertRange, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.RemoveAt, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.RemoveRange, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.SetItem, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.TextEditorPartition.
int Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.Count
This is the count of rich characters in THIS particular partition, the TextEditorModel.DocumentLength contains the whole count of rich characters across all partitions.
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.__Insert, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.__InsertRange, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.__RemoveAt, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.__SetDecorationByte, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.__SetItem, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.AddRange.
Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.TextEditorPartition(List< RichCharacter > richCharacterList)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.RichCharacterList.
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.AddRange, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.Insert, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.InsertRange, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.RemoveAt, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.RemoveRange, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.SetItem.
TextEditorPartition Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.Insert(int relativePositionIndex, RichCharacter richCharacter)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.RichCharacterList, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.TextEditorPartition.
TextEditorPartition Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.InsertRange(int relativePositionIndex, IEnumerable< RichCharacter > richCharacterList)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.RichCharacterList, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.TextEditorPartition.
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.AddRange.
TextEditorPartition Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.RemoveAt(int relativePositionIndex)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.RichCharacterList, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.TextEditorPartition.
TextEditorPartition Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.RemoveRange(int relativePositionIndex, int count)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.RichCharacterList, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.TextEditorPartition.
TextEditorPartition Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.AddRange(IEnumerable< RichCharacter > richCharacterList)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.Count, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.InsertRange, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.TextEditorPartition.
TextEditorPartition Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.SetItem(int relativePositionIndex, RichCharacter richCharacter)
If either character or decoration byte are 'null', then the respective collection will be left unchanged.
i.e.: to change ONLY a character value invoke this method with decorationByte set to null, and only the CharList will be changed.
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.RichCharacterList, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.TextEditorPartition.