Luthetus::Common::RazorLib::TreeViews::Models::TreeViewMouseEventHandler
readonly ITreeViewService Luthetus.Common.RazorLib.TreeViews.Models.TreeViewMouseEventHandler.TreeViewService
Referenced by Luthetus.Common.RazorLib.TreeViews.Models.TreeViewMouseEventHandler.OnMouseDown, Luthetus.Common.RazorLib.TreeViews.Models.TreeViewMouseEventHandler.TreeViewMouseEventHandler.
readonly IBackgroundTaskService Luthetus.Common.RazorLib.TreeViews.Models.TreeViewMouseEventHandler.BackgroundTaskService
Referenced by Luthetus.Common.RazorLib.TreeViews.Models.TreeViewMouseEventHandler.TreeViewMouseEventHandler.
Luthetus.Common.RazorLib.TreeViews.Models.TreeViewMouseEventHandler.TreeViewMouseEventHandler(ITreeViewService treeViewService, IBackgroundTaskService backgroundTaskService)
References Luthetus.Common.RazorLib.TreeViews.Models.TreeViewMouseEventHandler.BackgroundTaskService, Luthetus.Common.RazorLib.TreeViews.Models.TreeViewMouseEventHandler.TreeViewService.
virtual Task Luthetus.Common.RazorLib.TreeViews.Models.TreeViewMouseEventHandler.OnClickAsync(TreeViewCommandArgs commandArgs)
Invoked, and awaited, as part of the async UI event handler for 'onclick' events. .
The synchronous version: 'OnClick(TreeViewCommandArgs)' will be invoked immediately from within this method, to allow the synchronous code to block the UI purposefully. Any overrides of this method are intended to have 'base.MethodBeingOverridden()' prior to their code.
References Luthetus.Common.RazorLib.TreeViews.Models.TreeViewMouseEventHandler.OnClick.
virtual Task Luthetus.Common.RazorLib.TreeViews.Models.TreeViewMouseEventHandler.OnDoubleClickAsync(TreeViewCommandArgs commandArgs)
Invoked, and awaited, as part of the async UI event handler for 'ondblclick' events. .
The synchronous version: 'OnDoubleClick(TreeViewCommandArgs)' will be invoked immediately from within this method, to allow the synchronous code to block the UI purposefully. Any overrides of this method are intended to have 'base.MethodBeingOverridden()' prior to their code.
References Luthetus.Common.RazorLib.TreeViews.Models.TreeViewMouseEventHandler.OnDoubleClick.
virtual Task Luthetus.Common.RazorLib.TreeViews.Models.TreeViewMouseEventHandler.OnMouseDownAsync(TreeViewCommandArgs commandArgs)
Invoked, and awaited, as part of the async UI event handler for 'onmousedown' events. .
The synchronous version: 'OnMouseDown(TreeViewCommandArgs)' will be invoked immediately from within this method, to allow the synchronous code to block the UI purposefully. Any overrides of this method are intended to have 'base.MethodBeingOverridden()' prior to their code.
References Luthetus.Common.RazorLib.TreeViews.Models.TreeViewMouseEventHandler.OnMouseDown.
virtual void Luthetus.Common.RazorLib.TreeViews.Models.TreeViewMouseEventHandler.OnClick(TreeViewCommandArgs commandArgs)
Invoked, and awaited, as part of the synchronous UI event handler for 'onclick' events. .
This method is invoked by the async version: 'OnMouseDownAsync(TreeViewCommandArgs)'. Any overrides of this method are intended to have 'base.MethodBeingOverridden()' prior to their code, but for this method it makes no difference if one puts it after their code.
Referenced by Luthetus.Common.RazorLib.TreeViews.Models.TreeViewMouseEventHandler.OnClickAsync.
virtual void Luthetus.Common.RazorLib.TreeViews.Models.TreeViewMouseEventHandler.OnDoubleClick(TreeViewCommandArgs commandArgs)
Invoked, and awaited, as part of the synchronous UI event handler for 'ondblclick' events. .
This method is invoked by the async version: 'OnDoubleClickAsync(TreeViewCommandArgs)'. Any overrides of this method are intended to have 'base.MethodBeingOverridden()' prior to their code, but for this method it makes no difference if one puts it after their code.
Referenced by Luthetus.Common.RazorLib.TreeViews.Models.TreeViewMouseEventHandler.OnDoubleClickAsync.
virtual void Luthetus.Common.RazorLib.TreeViews.Models.TreeViewMouseEventHandler.OnMouseDown(TreeViewCommandArgs commandArgs)
Invoked, and awaited, as part of the synchronous UI event handler for 'onmousedown' events. .
This method is invoked by the async version: 'OnMouseDownAsync(TreeViewCommandArgs)'. Any overrides of this method are intended to have 'base.MethodBeingOverridden()' prior to their code.
References Luthetus.Common.RazorLib.Commands.Models.TreeViewCommandArgs.MouseEventArgs, Luthetus.Common.RazorLib.Commands.Models.TreeViewCommandArgs.NodeThatReceivedMouseEvent, Luthetus.Common.RazorLib.Commands.Models.TreeViewCommandArgs.TreeViewContainer, Luthetus.Common.RazorLib.TreeViews.Models.TreeViewMouseEventHandler.TreeViewService.
Referenced by Luthetus.Common.RazorLib.TreeViews.Models.TreeViewMouseEventHandler.OnMouseDownAsync.