Luthetus::Common::RazorLib::BackgroundTasks::Models::BackgroundTaskServiceSynchronous
readonly Dictionary<Key<IBackgroundTaskQueue>, BackgroundTaskQueue> Luthetus.Common.RazorLib.BackgroundTasks.Models.BackgroundTaskServiceSynchronous._queueMap
bool Luthetus.Common.RazorLib.BackgroundTasks.Models.BackgroundTaskServiceSynchronous._enqueuesAreDisabled
ImmutableArray<IBackgroundTaskQueue> Luthetus.Common.RazorLib.BackgroundTasks.Models.BackgroundTaskServiceSynchronous.Queues
void Luthetus.Common.RazorLib.BackgroundTasks.Models.BackgroundTaskServiceSynchronous.Enqueue(IBackgroundTask backgroundTask)
References Luthetus.Common.RazorLib.BackgroundTasks.Models.IBackgroundTask.HandleEvent, Luthetus.Common.RazorLib.BackgroundTasks.Models.IBackgroundTask.QueueKey, Luthetus.Common.RazorLib.BackgroundTasks.Models.BackgroundTaskServiceSynchronous.SetExecutingBackgroundTask.
Referenced by Luthetus.Common.RazorLib.BackgroundTasks.Models.BackgroundTaskServiceSynchronous.Enqueue, Luthetus.Common.RazorLib.BackgroundTasks.Models.BackgroundTaskServiceSynchronous.EnqueueAsync.
void Luthetus.Common.RazorLib.BackgroundTasks.Models.BackgroundTaskServiceSynchronous.Enqueue(Key< IBackgroundTask > taskKey, Key< IBackgroundTaskQueue > queueKey, string name, Func< Task > runFunc)
References Luthetus.Common.RazorLib.BackgroundTasks.Models.BackgroundTaskServiceSynchronous.Enqueue.
Task Luthetus.Common.RazorLib.BackgroundTasks.Models.BackgroundTaskServiceSynchronous.EnqueueAsync(IBackgroundTask backgroundTask)
References Luthetus.Common.RazorLib.BackgroundTasks.Models.BackgroundTaskServiceSynchronous.Enqueue.
Referenced by Luthetus.Common.RazorLib.BackgroundTasks.Models.BackgroundTaskServiceSynchronous.EnqueueAsync.
Task Luthetus.Common.RazorLib.BackgroundTasks.Models.BackgroundTaskServiceSynchronous.EnqueueAsync(Key< IBackgroundTask > taskKey, Key< IBackgroundTaskQueue > queueKey, string name, Func< Task > runFunc)
References Luthetus.Common.RazorLib.BackgroundTasks.Models.BackgroundTaskServiceSynchronous.EnqueueAsync.
void Luthetus.Common.RazorLib.BackgroundTasks.Models.BackgroundTaskServiceSynchronous.CompleteTaskCompletionSource(Key< IBackgroundTask > taskKey)
IBackgroundTask? Luthetus.Common.RazorLib.BackgroundTasks.Models.BackgroundTaskServiceSynchronous.Dequeue(Key< IBackgroundTaskQueue > queueKey)
Task< IBackgroundTask?> Luthetus.Common.RazorLib.BackgroundTasks.Models.BackgroundTaskServiceSynchronous.DequeueAsync(Key< IBackgroundTaskQueue > queueKey, CancellationToken cancellationToken)
void Luthetus.Common.RazorLib.BackgroundTasks.Models.BackgroundTaskServiceSynchronous.RegisterQueue(IBackgroundTaskQueue queue)
References Luthetus.Common.RazorLib.BackgroundTasks.Models.IBackgroundTaskQueue.Key.
void Luthetus.Common.RazorLib.BackgroundTasks.Models.BackgroundTaskServiceSynchronous.SetExecutingBackgroundTask(Key< IBackgroundTaskQueue > queueKey, IBackgroundTask? backgroundTask)
Referenced by Luthetus.Common.RazorLib.BackgroundTasks.Models.BackgroundTaskServiceSynchronous.Enqueue.
IBackgroundTaskQueue Luthetus.Common.RazorLib.BackgroundTasks.Models.BackgroundTaskServiceSynchronous.GetQueue(Key< IBackgroundTaskQueue > queueKey)
async Task Luthetus.Common.RazorLib.BackgroundTasks.Models.BackgroundTaskServiceSynchronous.StopAsync(CancellationToken cancellationToken)
References Luthetus.Common.RazorLib.BackgroundTasks.Models.IBackgroundTaskQueue.BackgroundTaskList.