Luthetus::TextEditor::RazorLib::CompilerServices::Syntax::Nodes::TypeClauseNode
ISyntax [] Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode._childList
bool Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode._childListIsDirty
ISyntaxToken Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.TypeIdentifierToken
Given: 'int x = 2;' Then: 'int' is the TypeIdentifierToken And: GenericParametersListingNode would be null.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BinaryMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindInheritanceStatementNode, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindTypeClauseNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.GetChildList, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TypeClauseMergeToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.TypeClauseNode.
Type? Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.ValueType
Given: 'int x = 2;' Then: 'typeof(int)' is the ValueType And: GenericParametersListingNode would be null br/> In short, ValueType is non-null when the TypeIdentifierToken maps to a C# primitive type.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindBinaryOperatorNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.SetValueType, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.TypeClauseNode.
GenericParametersListingNode? Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.GenericParametersListingNode
Given: 'int[] x = 2;' Then: 'Array<T>' is the TypeIdentifierToken And: '<int>' is the GenericParametersListingNode.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ConstructorInvocationMergeExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ConstructorInvocationMergeToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.GetChildList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.SetGenericParametersListingNode, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TypeClauseMergeExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TypeClauseMergeToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.TypeClauseNode.
TypeClauseNode IExpressionNode. Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.ResultTypeClauseNode
When parsing an expression, there may be a FunctionInvocationNode with a GenericParametersListingNode.
The expression code works however by passing around an 'IExpression expressionPrimary' and an 'IExpression expressionSeconday'. This means we cannot add common logic for parsing a GenericParametersListingNode unless the expression parsing code were modified, or maybe a call to a separate function to parse GenericParametersListingNode could be done. But, for now an experiment with making GenericParametersListingNode into a IExpressionNode is being tried out. Any IExpressionNode that is part of a complete expression, will have the IExpressionNode.ResultTypeClauseNode of Pseudo in order to indicate that the node is part of a expression, but not itself an expression. Use 'TypeClauseNode IExpressionNode.ResultTypeClauseNode => TypeClauseNodeFacts.Pseudo;' so that some confusion can be avoided since one has to cast it explicitly as an IExpressionNode in order to access the property. (i.e.: GenericParameterEntryNode.TypeClauseNode is not equal to IExpressionNode.ResultTypeClauseNode).
bool Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.HasQuestionMark
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TypeClauseMergeToken.
AttributeNode Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.AttributeNode
TODO: Change this attribute node property.
bool Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.IsFabricated
IsFabricated refers to when the ParserSession expected a node to be valid, but it wasn't. For example, a function invocation on an undefined function will construct a BoundFunctionInvocationNode with IsFabricated set to true.
SyntaxKind Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.SyntaxKind
Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.TypeClauseNode(ISyntaxToken typeIdentifier, Type? valueType, GenericParametersListingNode? genericParametersListingNode)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.GenericParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.TypeIdentifierToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.ValueType.
Referenced by Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.GenericArgumentEntryNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.GenericParameterEntryNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.VariableDeclarationNodeTests.Constructor, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.SetGenericParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.SetValueType.
TypeClauseNode Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.SetGenericParametersListingNode(GenericParametersListingNode genericParametersListingNode)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.GenericParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.TypeClauseNode.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ConstructorInvocationMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TypeClauseMergeToken.
TypeClauseNode Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.SetValueType(Type? valueType)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.TypeClauseNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.ValueType.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindTypeClauseNode.
ISyntax[] Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.GetChildList()
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.GenericParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.TypeIdentifierToken.