Luthetus::TextEditor::RazorLib::Commands::Models::Defaults::TextEditorCommandDefaultFunctions
static void Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.DoNothingDiscard()
static async Task Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.CopyAsync(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, IClipboardService clipboardService)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetPrimaryCursorModifier, Luthetus.Common.RazorLib.Clipboards.Models.IClipboardService.SetClipboard, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelModifier.ViewModel.
static async Task Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.CutAsync(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, IClipboardService clipboardService)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetPrimaryCursorModifier, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.HandleKeyboardEvent, Luthetus.Common.RazorLib.Clipboards.Models.IClipboardService.SetClipboard, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelModifier.ViewModel.
static async Task Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.PasteAsync(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, IClipboardService clipboardService)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetPrimaryCursorModifier, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.Insert, Luthetus.Common.RazorLib.Clipboards.Models.IClipboardService.ReadClipboard.
static void Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.TriggerSave(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCommandArgs commandArgs)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetPrimaryCursorModifier, Luthetus.TextEditor.RazorLib.Commands.Models.TextEditorCommandArgs.ServiceProvider, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.SetIsDirtyFalse, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.TriggerSave, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelModifier.ViewModel.
Referenced by Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.TriggerSave.
static void Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.SelectAll(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCommandArgs commandArgs)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.CharCount, Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetPrimaryCursorModifier.
static void Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.Undo(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCommandArgs commandArgs)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.UndoEdit.
static void Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.Redo(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCommandArgs commandArgs)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.RedoEdit.
static void Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.TriggerRemeasure(ITextEditorEditContext editContext, TextEditorViewModelModifier viewModelModifier, TextEditorCommandArgs commandArgs)
References Luthetus.TextEditor.RazorLib.ITextEditorService.OptionsApi, Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.TextEditorService.
static void Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.ScrollLineDown(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCommandArgs commandArgs)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.MutateScrollVerticalPosition, Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.TextEditorService, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelModifier.ViewModel, Luthetus.TextEditor.RazorLib.ITextEditorService.ViewModelApi.
static void Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.ScrollLineUp(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCommandArgs commandArgs)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.MutateScrollVerticalPosition, Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.TextEditorService, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelModifier.ViewModel, Luthetus.TextEditor.RazorLib.ITextEditorService.ViewModelApi.
static void Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.ScrollPageDown(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCommandArgs commandArgs)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.MutateScrollVerticalPosition, Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.TextEditorService, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelModifier.ViewModel, Luthetus.TextEditor.RazorLib.ITextEditorService.ViewModelApi.
static void Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.ScrollPageUp(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCommandArgs commandArgs)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.MutateScrollVerticalPosition, Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.TextEditorService, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelModifier.ViewModel, Luthetus.TextEditor.RazorLib.ITextEditorService.ViewModelApi.
static void Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.CursorMovePageBottom(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCommandArgs commandArgs)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetPrimaryCursorModifier, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelModifier.ViewModel.
static void Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.CursorMovePageTop(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCommandArgs commandArgs)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetPrimaryCursorModifier, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelModifier.ViewModel.
static void Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.Duplicate(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCommandArgs commandArgs)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetPrimaryCursorModifier, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.Insert, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor.
static void Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.IndentMore(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCommandArgs commandArgs)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetPrimaryCursorModifier, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.Insert, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursorModifier.SetColumnIndexAndPreferred, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor.
static void Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.IndentLess(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCommandArgs commandArgs)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.DeleteByRange, Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetPrimaryCursorModifier, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModel.TAB_WIDTH, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor.
static void Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.ClearTextSelection(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCommandArgs commandArgs)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetPrimaryCursorModifier.
static void Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.NewLineBelow(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCommandArgs commandArgs)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetPrimaryCursorModifier, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.Insert, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.RichCharacterList, Luthetus.TextEditor.RazorLib.Characters.Models.RichCharacter.Value.
static void Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.NewLineAbove(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCommandArgs commandArgs)
References Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursorModifier.ColumnIndex, Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetPrimaryCursorModifier, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.Insert, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.RichCharacterList, Luthetus.TextEditor.RazorLib.Characters.Models.RichCharacter.Value.
static void Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.MoveLineDown(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCommandArgs commandArgs)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.Delete, Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetPrimaryCursorModifier, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.Insert, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursorModifier.LineIndex.
static void Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.MoveLineUp(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCommandArgs commandArgs)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.Delete, Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetPrimaryCursorModifier, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.Insert, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursorModifier.LineIndex.
static void Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.GoToMatchingCharacter(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCommandArgs commandArgs)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.CharCount, Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetPrimaryCursorModifier, Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.MoveCursorUnsafe, Luthetus.TextEditor.RazorLib.Commands.Models.TextEditorCommandArgs.ShouldSelectText, Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.TextEditorService, Luthetus.TextEditor.RazorLib.ITextEditorService.ViewModelApi.
static async Task Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.RelatedFilesQuickPick(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCommandArgs commandArgs)
References Luthetus.Common.RazorLib.FileSystems.Models.IEnvironmentProvider.AbsolutePathFactory, Luthetus.TextEditor.RazorLib.TextEditors.Models.Category, Luthetus.TextEditor.RazorLib.TextEditors.Models.dispatcher, Luthetus.Common.RazorLib.Dropdowns.Models.DropdownRecord, Luthetus.Common.RazorLib.Dropdowns.States.DropdownState, Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.GetOrDefault, Luthetus.TextEditor.RazorLib.ITextEditorService.GroupStateWrap, Luthetus.Common.RazorLib.Menus.Displays.MenuDisplay.InitialActiveMenuOptionRecordIndex, Luthetus.TextEditor.RazorLib.TextEditors.Models.jsRuntime, Luthetus.Common.RazorLib.Menus.Models.MenuOptionRecord, Luthetus.Common.RazorLib.Menus.Displays.MenuDisplay.MenuRecord, Luthetus.Common.RazorLib.Menus.Models.MenuRecord, Luthetus.TextEditor.RazorLib.ITextEditorService.OpenInEditorAsync, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ResourceUri, Luthetus.TextEditor.RazorLib.Commands.Models.TextEditorCommandArgs.ServiceProvider, Luthetus.TextEditor.RazorLib.Commands.Models.TextEditorCommandArgs.TextEditorService, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelModifier.ViewModel, Luthetus.TextEditor.RazorLib.ITextEditorService.ViewModelApi.
static async Task Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.QuickActionsSlashRefactor(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCommandArgs commandArgs)
References Luthetus.Common.RazorLib.FileSystems.Models.IEnvironmentProvider.AbsolutePathFactory, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.CompilerService, Luthetus.TextEditor.RazorLib.TextEditors.Models.dispatcher, Luthetus.Common.RazorLib.Dropdowns.Models.DropdownRecord, Luthetus.Common.RazorLib.Dropdowns.States.DropdownState, Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.GetOrDefault, Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetPrimaryCursorModifier, Luthetus.TextEditor.RazorLib.ITextEditorService.GroupStateWrap, Luthetus.TextEditor.RazorLib.TextEditors.Models.jsRuntime, Luthetus.Common.RazorLib.Menus.Models.MenuOptionRecord, Luthetus.Common.RazorLib.Menus.Displays.MenuDisplay.MenuRecord, Luthetus.Common.RazorLib.Menus.Models.MenuRecord, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ResourceUri, Luthetus.TextEditor.RazorLib.Commands.Models.TextEditorCommandArgs.ServiceProvider, Luthetus.TextEditor.RazorLib.Commands.Models.TextEditorCommandArgs.TextEditorService, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelModifier.ViewModel, Luthetus.TextEditor.RazorLib.ITextEditorService.ViewModelApi.
static void Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.GoToDefinition(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCommandArgs commandArgs)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.Category, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.CompilerService, Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetCursorModifierBag, Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetModelModifier, Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorModelApi.GetOrDefault, Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetPrimaryCursorModifier, Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetViewModelModifier, Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorModelApi.GetViewModelsOrEmpty, Luthetus.TextEditor.RazorLib.ITextEditorService.ModelApi, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ResourceUri, Luthetus.TextEditor.RazorLib.Commands.Models.TextEditorCommandArgs.ServiceProvider, Luthetus.TextEditor.RazorLib.ITextEditorService.TextEditorConfig, Luthetus.TextEditor.RazorLib.Commands.Models.TextEditorCommandArgs.TextEditorService.
static void Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.ShowFindAllDialog(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCommandArgs commandArgs)
References Luthetus.TextEditor.RazorLib.ITextEditorService.OptionsApi, Luthetus.TextEditor.RazorLib.Commands.Models.TextEditorCommandArgs.TextEditorService.
static async Task Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.ShowTooltipByCursorPositionAsync(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCommandArgs commandArgs)
References Luthetus.TextEditor.RazorLib.Commands.Models.TextEditorCommandArgs.ComponentData, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.HandleMouseStoppedMovingEventAsync, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ResourceUri, Luthetus.TextEditor.RazorLib.Commands.Models.TextEditorCommandArgs.ServiceProvider, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelModifier.ViewModel.
static async Task Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.HandleAfterOnKeyDownAsync(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, KeymapArgs keymapArgs, TextEditorComponentData componentData)
The default AfterOnKeyDownAsync will provide syntax highlighting, and autocomplete. The syntax highlighting occurs on ';', whitespace, paste, undo, redo The autocomplete occurs on LetterOrDigit typed or { Ctrl + Space }. Furthermore, the autocomplete is done via IAutocompleteService and the one can provide their own implementation when registering the Luthetus.TextEditor services using LuthetusTextEditorConfig.AutocompleteServiceFactory.
References Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.Dispatcher, Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetPrimaryCursorModifier, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.ShowAutocompleteMenu, Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.ThrottleApplySyntaxHighlighting.
Referenced by Luthetus.TextEditor.RazorLib.Events.Models.OnKeyDownLateBatching.HandleEvent.
static async Task Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.HandleAfterOnKeyDownRangeAsync(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, KeymapArgs[] batchKeymapArgsList, int batchKeymapArgsListLength, TextEditorComponentData componentData, ViewModelDisplayOptions viewModelDisplayOptions)
This method was being used in the 'OnKeyDownBatch.cs' class, which no longer exists. The replacement for 'OnKeyDownBatch.cs' is 'OnKeyDownLateBatching.cs'.
But, during the replacement process, this method was overlooked. One would likely want to use this method when appropriate because it permits every batched keyboard event to individually be given a chance to trigger 'HandleAfterOnKeyDownAsyncFactory(...)' Example: a 'space' keyboard event, batched with the letter 'a' keyboard event. Depending on what 'OnKeyDownLateBatching.cs' does, perhaps it takes the last keyboard event and uses that to fire 'HandleAfterOnKeyDownAsyncFactory(...)'. Well, a 'space' keyboard event would have trigger syntax highlighting to be refreshed. Whereas, the letter 'a' keyboard event won't do anything beyond inserting the letter. Therefore, the syntax highlighting was erroneously not refreshed due to batching. This method is intended to solve this problem, but it was forgotten at some point.
References Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.ViewModelDisplayOptions.AfterOnKeyDownRangeAsync, Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.Dispatcher, Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetPrimaryCursorModifier, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.ShowAutocompleteMenu, Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.ThrottleApplySyntaxHighlighting.
static async Task Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.HandleMouseStoppedMovingEventAsync(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, MouseEventArgs mouseEventArgs, TextEditorComponentData componentData, ILuthetusTextEditorComponentRenderers textEditorComponentRenderers, ResourceUri resourceUri)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.CompilerService, Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.ContinueRenderingTooltipAsync, Luthetus.TextEditor.RazorLib.ComponentRenderers.Models.ITextEditorDiagnosticRenderer.Diagnostic, Luthetus.TextEditor.RazorLib.ComponentRenderers.Models.ILuthetusTextEditorComponentRenderers.DiagnosticRendererType, Luthetus.Common.RazorLib.JavaScriptObjects.Models.RelativeCoordinates, Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ResourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.scrollbarDimensions, Luthetus.TextEditor.RazorLib.ComponentRenderers.Models.ITextEditorSymbolRenderer.Symbol, Luthetus.TextEditor.RazorLib.ComponentRenderers.Models.ILuthetusTextEditorComponentRenderers.SymbolRendererType, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorDimensions, Luthetus.TextEditor.RazorLib.TextEditors.Models.TooltipViewModel, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelModifier.ViewModel.
Referenced by Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.ShowTooltipByCursorPositionAsync.
static void Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.ShowDropdown(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCursorModifier primaryCursor, IDispatcher dispatcher, double? leftOffset, double? topOffset, Type componentType, Dictionary< string, object?>? componentParameters)
If left or top is left as null, it will be set to whatever the primary cursor's left or top is respectively. The left and top values are offsets from the text editor's bounding client rect.
Use the method RemoveDropdown to un-render the dropdown programmatically.
References Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursorModifier.ColumnIndex, Luthetus.TextEditor.RazorLib.TextEditors.Models.dispatcher, Luthetus.Common.RazorLib.Dropdowns.Models.DropdownRecord, Luthetus.Common.RazorLib.Dropdowns.States.DropdownState, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursorModifier.LineIndex, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModel.TAB_WIDTH, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelModifier.ViewModel.
Referenced by Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.ShowAutocompleteMenu, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.ShowContextMenu.
static void Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.RemoveDropdown(ITextEditorEditContext editContext, TextEditorViewModelModifier viewModelModifier, IDispatcher dispatcher)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.dispatcher, Luthetus.Common.RazorLib.Dropdowns.States.DropdownState, Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.None, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelModifier.ViewModel.
Referenced by Luthetus.TextEditor.RazorLib.Events.Models.OnKeyDownLateBatching.HandleEvent, Luthetus.TextEditor.RazorLib.Events.Models.OnMouseDown.HandleEvent.
static void Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.ShowContextMenu(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCursorModifier primaryCursor, IDispatcher dispatcher, TextEditorComponentData componentData)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.ContextMenu, Luthetus.TextEditor.RazorLib.TextEditors.Models.dispatcher, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.ShowDropdown.
Referenced by Luthetus.TextEditor.RazorLib.Events.Models.OnKeyDownLateBatching.HandleEvent.
static void Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.ShowAutocompleteMenu(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCursorModifier primaryCursor, IDispatcher dispatcher, TextEditorComponentData componentData)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.AutoCompleteMenu, Luthetus.TextEditor.RazorLib.TextEditors.Models.dispatcher, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.ShowDropdown.
Referenced by Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.HandleAfterOnKeyDownAsync, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.HandleAfterOnKeyDownRangeAsync.