Luthetus::Common::RazorLib::BackgroundTasks::Models::ContinuousBackgroundTaskWorker
const string Luthetus.Common.RazorLib.BackgroundTasks.Models.ContinuousBackgroundTaskWorker.QUEUE_DISPLAY_NAME
Referenced by Luthetus.TextEditor.Tests.Basis.CompilerServices.TextEditorCompilerServicesTestsHelper.InitializeTextEditorCompilerServicesTestsHelper, Luthetus.TextEditor.Tests.Basis.TestsHelper.InitializeTextEditorServicesTestsHelper.
readonly Key<IBackgroundTaskQueue> Luthetus.Common.RazorLib.BackgroundTasks.Models.ContinuousBackgroundTaskWorker._queueKey
Luthetus.Common.RazorLib.BackgroundTasks.Models.ContinuousBackgroundTaskWorker.ContinuousBackgroundTaskWorker(IBackgroundTaskService backgroundTaskService, ILoggerFactory loggerFactory)
static Key< IBackgroundTaskQueue > Luthetus.Common.RazorLib.BackgroundTasks.Models.ContinuousBackgroundTaskWorker.GetQueueKey()
Referenced by Luthetus.Extensions.Git.Models.GitIdeApi.AddEnqueue, Luthetus.Common.Tests.Basis.Installations.Models.ServiceCollectionExtensionsTests.AddLuthetusCommonServices, Luthetus.Extensions.Git.Models.GitIdeApi.BranchGetAllEnqueue, Luthetus.Extensions.Git.Models.GitIdeApi.BranchNewEnqueue, Luthetus.Extensions.Git.Models.GitIdeApi.BranchSetEnqueue, Luthetus.Extensions.Git.Models.GitIdeApi.CommitEnqueue, Luthetus.Common.Tests.Basis.BackgroundTasks.Models.BackgroundTaskWorkerTests.Constructor, Luthetus.Common.RazorLib.Reactives.Models.ThrottleEventQueueAsync.DequeueOrDefaultAsync, Luthetus.Extensions.Git.Models.GitIdeApi.DiffFileEnqueue, Luthetus.Extensions.DotNet.Outputs.States.OutputScheduler.Enqueue_ConstructTreeView, Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.Enqueue_ConstructTreeView, Luthetus.Extensions.Git.Models.GitIdeApi.FetchEnqueue, Luthetus.Extensions.Git.Models.GitIdeApi.GetActiveBranchNameEnqueue, Luthetus.Extensions.Git.Models.GitIdeApi.GetOriginNameEnqueue, Luthetus.TextEditor.Tests.Basis.CompilerServices.TextEditorCompilerServicesTestsHelper.InitializeTextEditorCompilerServicesTestsHelper, Luthetus.TextEditor.Tests.Basis.TestsHelper.InitializeTextEditorServicesTestsHelper, Luthetus.Common.Tests.Basis.BackgroundTasks.Models.BackgroundTaskTests.InvokeWorkItem, Luthetus.Extensions.Git.Models.GitIdeApi.LogFileEnqueue, Luthetus.Common.RazorLib.TreeViews.Models.TreeViewService.MoveRight, Luthetus.Extensions.DotNet.Installations.Displays.LuthetusExtensionsDotNetInitializer.OnAfterRender, Luthetus.Common.RazorLib.Installations.Displays.LuthetusCommonInitializer.OnInitialized, Luthetus.Extensions.Config.Installations.Displays.LuthetusConfigInitializer.OnInitialized, Luthetus.Extensions.DotNet.Installations.Displays.LuthetusExtensionsDotNetInitializer.OnInitialized, Luthetus.Extensions.Git.Installations.Displays.LuthetusExtensionsGitInitializer.OnInitialized, Luthetus.Ide.RazorLib.Installations.Displays.LuthetusIdeInitializer.OnInitialized, Luthetus.Ide.RazorLib.Shareds.Displays.IdeHeader.OnInitialized, Luthetus.Ide.RazorLib.Shareds.Displays.Internals.BackgroundTaskDialogDisplay.OnInitialized, Luthetus.TextEditor.RazorLib.Installations.Displays.LuthetusTextEditorInitializer.OnInitialized, Luthetus.Extensions.DotNet.Menus.Models.DotNetMenuOptionsFactory.PerformMoveProjectToSolutionFolder, Luthetus.Extensions.DotNet.Menus.Models.DotNetMenuOptionsFactory.PerformRemoveNuGetPackageReferenceFromProject, Luthetus.Extensions.DotNet.Menus.Models.DotNetMenuOptionsFactory.PerformRemoveProjectToProjectReference, Luthetus.Extensions.Git.Models.GitIdeApi.PullEnqueue, Luthetus.Extensions.Git.Models.GitIdeApi.PushToOriginWithTrackingEnqueue, Luthetus.Ide.RazorLib.InputFiles.Models.InputFileIdeApi.RequestInputFileStateForm, Luthetus.Ide.RazorLib.FileSystems.Models.FileSystemIdeApi.SaveFile, Luthetus.Extensions.DotNet.CompilerServices.Models.CompilerServiceIdeApi.SetCompilerServiceExplorerTreeView, Luthetus.Extensions.DotNet.DotNetSolutions.Models.DotNetSolutionIdeApi.SetDotNetSolution, Luthetus.Ide.RazorLib.FolderExplorers.Models.FolderExplorerIdeApi.SetFolderExplorerState, Luthetus.Ide.RazorLib.FolderExplorers.Models.FolderExplorerIdeApi.SetFolderExplorerTreeView, Luthetus.Extensions.Git.Models.GitIdeApi.ShowFileEnqueue, Luthetus.Extensions.Git.Models.GitIdeApi.StatusEnqueue, Luthetus.Extensions.Git.Models.GitIdeApi.UnstageEnqueue, Luthetus.Common.RazorLib.Storages.Models.StorageCommonApi.WriteToLocalStorage.