Luthetus::Common::RazorLib::Reflectives::Models::ReflectiveParameter
ConstructorInfo? Luthetus.Common.RazorLib.Reflectives.Models.ReflectiveParameter.ChosenConstructorInfo
Referenced by Luthetus.Common.RazorLib.Reflectives.Models.ReflectiveParameter.ReflectiveParameter.
Func<object?>? Luthetus.Common.RazorLib.Reflectives.Models.ReflectiveParameter.ConstructValueFunc
Referenced by Luthetus.Common.RazorLib.Reflectives.Models.ReflectiveParameter.ReflectiveParameter.
object? Luthetus.Common.RazorLib.Reflectives.Models.ReflectiveParameter.Value
Referenced by Luthetus.Common.RazorLib.Reflectives.Models.ReflectiveParameter.ReflectiveParameter.
Type Luthetus.Common.RazorLib.Reflectives.Models.ReflectiveParameter.Type
Referenced by Luthetus.Common.RazorLib.Reflectives.Models.ReflectiveParameter.ConstructOther, Luthetus.Common.RazorLib.Reflectives.Models.ReflectiveParameter.ReflectiveParameter.
ReflectiveParameterKind Luthetus.Common.RazorLib.Reflectives.Models.ReflectiveParameter.ReflectiveParameterKind
Luthetus.Common.RazorLib.Reflectives.Models.ReflectiveParameter.ReflectiveParameter(ConstructorInfo? chosenConstructorInfo, Func< object?>? constructValueFunc, object? value, Type type)
References Luthetus.Common.RazorLib.Reflectives.Models.ReflectiveParameter.ChosenConstructorInfo, Luthetus.Common.RazorLib.Reflectives.Models.ReflectiveParameter.ConstructValueFunc, Luthetus.Common.RazorLib.Reflectives.Models.ReflectiveParameter.Type, Luthetus.Common.RazorLib.Reflectives.Models.ReflectiveParameter.Value.
Referenced by Luthetus.Common.RazorLib.Reflectives.Models.ReflectiveParameter.ConstructInt, Luthetus.Common.RazorLib.Reflectives.Models.ReflectiveParameter.ConstructOther, Luthetus.Common.RazorLib.Reflectives.Models.ReflectiveParameter.ConstructOther< VariableType >, Luthetus.Common.RazorLib.Reflectives.Models.ReflectiveParameter.ConstructString.
static ReflectiveParameter Luthetus.Common.RazorLib.Reflectives.Models.ReflectiveParameter.ConstructString()
References Luthetus.Common.RazorLib.Reflectives.Models.ReflectiveParameter.ReflectiveParameter.
static ReflectiveParameter Luthetus.Common.RazorLib.Reflectives.Models.ReflectiveParameter.ConstructInt()
References Luthetus.Common.RazorLib.Reflectives.Models.ReflectiveParameter.ReflectiveParameter.
static ReflectiveParameter Luthetus.Common.RazorLib.Reflectives.Models.ReflectiveParameter.ConstructOther< VariableType >()
References Luthetus.Common.RazorLib.Reflectives.Models.ReflectiveParameter.ReflectiveParameter.
static ReflectiveParameter Luthetus.Common.RazorLib.Reflectives.Models.ReflectiveParameter.ConstructOther(Type variableType)
References Luthetus.Common.RazorLib.Reflectives.Models.ReflectiveParameter.ReflectiveParameter, Luthetus.Common.RazorLib.Reflectives.Models.ReflectiveParameter.Type.
Referenced by Luthetus.Common.Tests.Basis.Reflectives.Models.ReflectiveModelTests.ConstructBlazorParameters.