Luthetus::TextEditor::Tests::Basis::Cursors::Models::TextEditorCursorTests
void Luthetus.TextEditor.Tests.Basis.Cursors.Models.TextEditorCursorTests.ConstructorA()
TextEditorCursor(int, int, int, bool, TextEditorSelection) - TextEditorCursor.LineIndex TextEditorCursor.ColumnIndex TextEditorCursor.PreferredColumnIndex TextEditorCursor.IsPrimaryCursor TextEditorCursor.Selection TextEditorCursor.Key
References Luthetus.TextEditor.Tests.Basis.Cursors.Models.TextEditorCursorTests.Empty, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorSelection.
void Luthetus.TextEditor.Tests.Basis.Cursors.Models.TextEditorCursorTests.ConstructorB()
TextEditorCursor(bool) - TextEditorCursor.LineIndex TextEditorCursor.ColumnIndex TextEditorCursor.PreferredColumnIndex TextEditorCursor.IsPrimaryCursor TextEditorCursor.Selection TextEditorCursor.Key
References Luthetus.TextEditor.Tests.Basis.Cursors.Models.TextEditorCursorTests.Empty, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorSelection.
void Luthetus.TextEditor.Tests.Basis.Cursors.Models.TextEditorCursorTests.ConstructorC()
TextEditorCursor(int, int, bool) - TextEditorCursor.LineIndex TextEditorCursor.ColumnIndex TextEditorCursor.PreferredColumnIndex TextEditorCursor.IsPrimaryCursor TextEditorCursor.Selection TextEditorCursor.Key
References Luthetus.TextEditor.Tests.Basis.Cursors.Models.TextEditorCursorTests.Empty, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorSelection.
void Luthetus.TextEditor.Tests.Basis.Cursors.Models.TextEditorCursorTests.With()
TextEditorCursor(TextEditorCursor)
References Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorSelection.
void Luthetus.TextEditor.Tests.Basis.Cursors.Models.TextEditorCursorTests.Empty()
TextEditorCursor.Empty
References Luthetus.TextEditor.Tests.Basis.Cursors.Models.TextEditorCursorTests.Empty, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorSelection.
Referenced by Luthetus.TextEditor.Tests.Basis.Cursors.Models.TextEditorCursorTests.ConstructorA, Luthetus.TextEditor.Tests.Basis.Cursors.Models.TextEditorCursorTests.ConstructorB, Luthetus.TextEditor.Tests.Basis.Cursors.Models.TextEditorCursorTests.ConstructorC, Luthetus.TextEditor.Tests.Basis.Cursors.Models.TextEditorCursorTests.Empty.