Luthetus::Common::RazorLib::TreeViews::Models::TreeViewAdhoc
Luthetus.Common.RazorLib.TreeViews.Models.TreeViewAdhoc.TreeViewAdhoc(byte value)
Referenced by Luthetus.Common.RazorLib.TreeViews.Models.TreeViewAdhoc.ConstructTreeViewAdhoc, Luthetus.Common.RazorLib.TreeViews.Models.TreeViewAdhoc.ConstructTreeViewAdhoc, Luthetus.Common.RazorLib.TreeViews.Models.TreeViewAdhoc.Equals.
override bool Luthetus.Common.RazorLib.TreeViews.Models.TreeViewAdhoc.Equals(object? obj)
References Luthetus.Common.RazorLib.TreeViews.Models.TreeViewNoType.Key, Luthetus.Common.RazorLib.TreeViews.Models.TreeViewAdhoc.TreeViewAdhoc.
override int Luthetus.Common.RazorLib.TreeViews.Models.TreeViewAdhoc.GetHashCode()
References Luthetus.Common.RazorLib.TreeViews.Models.TreeViewNoType.Key.
override TreeViewRenderer Luthetus.Common.RazorLib.TreeViews.Models.TreeViewAdhoc.GetTreeViewRenderer()
References Luthetus.Common.RazorLib.TreeViews.Displays.Utils.TreeViewAdhocDisplay.TreeViewNoTypeAdhoc, Luthetus.Common.RazorLib.TreeViews.Models.TreeViewRenderer.
Referenced by Luthetus.Common.Tests.Basis.TreeViews.Models.TreeViewAdhocTests.GetTreeViewRenderer.
override Task Luthetus.Common.RazorLib.TreeViews.Models.TreeViewAdhoc.LoadChildListAsync()
Referenced by Luthetus.Common.Tests.Basis.TreeViews.Models.TreeViewAdhocTests.LoadChildListAsync, Luthetus.Extensions.DotNet.CompilerServices.Models.CompilerServiceIdeApi.SetCompilerServiceExplorerTreeView.
override void Luthetus.Common.RazorLib.TreeViews.Models.TreeViewAdhoc.RemoveRelatedFilesFromParent(List< TreeViewNoType > siblingsAndSelfTreeViews)
RemoveRelatedFilesFromParent is used for showing codebehinds such that a file on the filesystem can be displayed as having children in the TreeView. In the case of a directory loading its children. After the directory loads all its children it will loop through the children invoking RemoveRelatedFilesFromParent on each of the children. For example: if a directory has the children { 'Component.razor', 'Component.razor.cs' } then 'Component.razor' will remove 'Component.razor.cs' from the parent directories children and mark itself as expandable as it saw a related file in its parent.
Referenced by Luthetus.Common.Tests.Basis.TreeViews.Models.TreeViewAdhocTests.RemoveRelatedFilesFromParent.
static TreeViewAdhoc Luthetus.Common.RazorLib.TreeViews.Models.TreeViewAdhoc.ConstructTreeViewAdhoc()
References Luthetus.Common.RazorLib.TreeViews.Models.TreeViewNoType.IndexAmongSiblings, Luthetus.Common.RazorLib.TreeViews.Models.TreeViewNoType.IsExpandable, Luthetus.Common.RazorLib.TreeViews.Models.TreeViewNoType.IsExpanded, Luthetus.Common.RazorLib.TreeViews.Models.TreeViewNoType.IsHidden, Luthetus.Common.RazorLib.TreeViews.Models.TreeViewNoType.IsRoot, Luthetus.Common.RazorLib.TreeViews.Models.TreeViewNoType.Key, Luthetus.Common.RazorLib.TreeViews.Models.TreeViewNoType.Parent, Luthetus.Common.RazorLib.TreeViews.Models.TreeViewAdhoc.TreeViewAdhoc, Luthetus.Common.RazorLib.TreeViews.Models.TreeViewNoType.TreeViewChangedKey.
Referenced by Luthetus.Common.RazorLib.TreeViews.Models.TreeViewAdhoc.ConstructTreeViewAdhoc, Luthetus.Common.Tests.Basis.TreeViews.Models.TreeViewAdhocTests.ConstructTreeViewAdhocA, Luthetus.Common.Tests.Basis.TreeViews.Models.TreeViewAdhocTests.ConstructTreeViewAdhocB, Luthetus.Common.Tests.Basis.TreeViews.Models.TreeViewAdhocTests.GetTreeViewRenderer, Luthetus.Common.Tests.Basis.TreeViews.Models.TreeViewAdhocTests.LoadChildListAsync, Luthetus.Ide.RazorLib.InputFiles.Displays.InputFileSidebar.OnAfterRenderAsync, Luthetus.Common.Tests.Basis.TreeViews.Models.TreeViewAdhocTests.RemoveRelatedFilesFromParent, Luthetus.Extensions.DotNet.CompilerServices.Models.CompilerServiceIdeApi.SetCompilerServiceExplorerTreeView, Luthetus.Extensions.DotNet.Outputs.States.OutputScheduler.Task_ConstructTreeView, Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.Task_ConstructTreeView, Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.Task_SumEachProjectTestCount.
static TreeViewAdhoc Luthetus.Common.RazorLib.TreeViews.Models.TreeViewAdhoc.ConstructTreeViewAdhoc(params TreeViewNoType[] treeViewList)
References Luthetus.Common.RazorLib.TreeViews.Models.TreeViewAdhoc.ConstructTreeViewAdhoc, Luthetus.Common.RazorLib.TreeViews.Models.TreeViewAdhoc.TreeViewAdhoc.