Luthetus::TextEditor::RazorLib::TextEditors::Models::TextEditorModelModifier
DeleteKind
int Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.positionIndex
The text editor sees "\r\n" as 1 character, even though that is made up of 2 char values. The TextEditorPartition however, sees "\r\n" as 2 char values. .
This different means, to delete "\r\n" one tells the text editor to delete 1 character, where as one tells the TextEditorPartition to delete 2 char values. This method returns the 'int charValueCount', so that it can be used in the DeleteValue(int, int, CancellationToken) method.
readonly TextEditorModel Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier._textEditorModel
ImmutableList<TextEditorPartition> Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier._partitionList
TODO: Awkward naming convention is being used here. This is an expression bound property,... ...with the naming conventions of a private field. | The reason for breaking convention here is that every other purpose of this type is done through a private field. | Need to revisit naming this.
List<ITextEditorEdit>? Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier._editBlocksList
List<LineEnd>? Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier._lineEndList
List<(LineEndKind lineEndKind, int count)>? Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier._lineEndKindCountList
List<TextEditorPresentationModel>? Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier._presentationModelsList
List<int>? Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier._tabKeyPositionsList
LineEndKind? Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier._onlyLineEndKind
bool Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier._onlyLineEndKindWasModified
Awkward special case here: _onlyLineEndKind is allowed to be null. So, the design of this class where null means unmodified, doesn't work well here.
LineEndKind? Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier._usingLineEndKind
ResourceUri? Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier._resourceUri
DateTime? Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier._resourceLastWriteTime
string? Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier._fileExtension
IDecorationMapper? Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier._decorationMapper
ICompilerService? Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier._compilerService
SaveFileHelper? Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier._textEditorSaveFileHelper
int? Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier._editBlockIndex
bool Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier._isDirty
int Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.rowIndex
int int? rowLength Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier._mostCharactersOnASingleLineTuple
Key<RenderState>? Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier._renderStateKey
string? Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier._allText
const int Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.MINIMUM_PARTITION_SIZE
__SplitIntoTwoPartitions(int) will divide by 2 and give the first split the remainder, then add 1 to the first split if there is a multibyte scenario. Therefore partition size of 3 would infinitely try to split itself.
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.TextEditorModelModifier.
RichCharacter [] Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.RichCharacterList
Changed this property to an array from an ImmutableList (2024-08-13).The motivation for this change comes from calculating the virtualization result. The storage for the underlying data of a 'ImmutableList' is believed to be more of a 'tree' structure than a contiguous array. And therefore, when we virtualize vertically, and then horizontally after, this is an incredible amount of overhead if performed on a 'tree'-like structure. A contiguous array is expected to be a dramatic improvement in performance when calculating the virtualization result. A side note on this change: could .NET internally more easily leverage caching with this now being a contiguous array, rather than a 'tree'? A worry: I'm not quite certain on the details of the idea in my head. It is something along lines of an array being treated as a struct and that this could cause a mess somehow? | Copying the entire list of rich characters versus just passing around a pointer kind of thing. | But, this array is located on an object, the text editor model, and it is the model that is being passed around in the code base. So this shouldn't be an issue. Quite non-scientifically I simply took note of the memory usage that the Task Manager on windows reported for the IDE while this used to be an ImmutableList, before I made the change. | It was 1,744 MB of memory pre change. It is 1,568 MB of memory after change. There is 0 control of variables going on here so the change of 200 MB perhaps is completely meaningless. More so, I took a simple note of memory usage incase I see that the memory usage doubled or something absurd. Would the app's memory go up, or would the so called ".NET Host" have its memory go up? I'm seeing in task manager a process called ".NET Host", separate to that of "Luthetus.Ide.Photino". I'm now seeing 643 MB of memory usage after changing RichCharacter to a struct from a class
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelApi.ApplyDecorationRange, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.HandleKeyboardEvent, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.MoveCursorUnsafe, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.NewLineAbove, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.NewLineBelow.
ImmutableList<TextEditorPartition> Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.PartitionList
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.__RemoveRange, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.ClearContent, Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.EmptyEditor_TestData_And_PerformPreAssertions, Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.NotEmptyEditor_TestData_And_PerformPreAssertions.
IList<ITextEditorEdit> Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.EditBlockList
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ClearEditBlocks.
IList<LineEnd> Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.LineEndList
Convert an index for a LineEnd to a LineInformation, use the method: TextEditorModelExtensionMethods.GetLineInformation(ITextEditorModel, int).
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.CalculateVirtualizationResult, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.ClearContent, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.Delete, Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.EmptyEditor_TestData_And_PerformPreAssertions, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.Insert, Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.NotEmptyEditor_TestData_And_PerformPreAssertions, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.SetContent.
IList<(LineEndKind lineEndKind, int count)> Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.LineEndKindCountList
Referenced by Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.ClearContent, Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.EmptyEditor_TestData_And_PerformPreAssertions, Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.NotEmptyEditor_TestData_And_PerformPreAssertions.
IList<TextEditorPresentationModel> Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.PresentationModelList
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.CompletePendingCalculatePresentationModel, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.ParseAsync, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.PerformRegisterPresentationModelAction, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.StartPendingCalculatePresentationModel.
IList<int> Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.TabKeyPositionList
Provides exact position index of a tab character.
Referenced by Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.ClearContent, Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.EmptyEditor_TestData_And_PerformPreAssertions, Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.NotEmptyEditor_TestData_And_PerformPreAssertions, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.SetContent.
LineEndKind? Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.OnlyLineEndKind
If there is a mixture of -Carriage Return -Linefeed -CRLF Then this will be null. If there are no line endings then this will be null.
LineEndKind Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.LineEndKindPreference
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.HandleKeyboardEvent.
ResourceUri Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ResourceUri
TODO: On (2023-10-02) Key<TextEditorModel> was removed, because it felt redundant... ...given only 1 TextEditorModel can exist for a given ResourceUri. This change however creates an issue regarding 'fake' resource uri's that are used for in-memory files. For example, Options.Displays.TextEditorSettingsPreview now has the resource URI of "__LUTHETUS_SETTINGS_PREVIEW__". This is an issue because could a user have on their filesystem the file "__LUTHETUS_SETTINGS_PREVIEW__"? (at that exact resource uri).
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelApi.ApplySyntaxHighlighting, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.GoToDefinition, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.HandleMouseStoppedMovingEventAsync, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.ParseAsync, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.QuickActionsSlashRefactor, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.RelatedFilesQuickPick, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelApi.Reload, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.RevealCursor, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelApi.SetResourceData, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.SetResourceData, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.ShowTooltipByCursorPositionAsync, Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.ThrottleApplySyntaxHighlighting.
DateTime Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ResourceLastWriteTime
string Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.FileExtension
This is displayed within theDisplays.Internals.TextEditorFooter.
Referenced by Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.ClearContent, Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.EmptyEditor_TestData_And_PerformPreAssertions, Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.NotEmptyEditor_TestData_And_PerformPreAssertions.
IDecorationMapper Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.DecorationMapper
ICompilerService Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.CompilerService
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelApi.ApplySyntaxHighlighting, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.GoToDefinition, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.HandleMouseStoppedMovingEventAsync, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.QuickActionsSlashRefactor, Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.ThrottleApplySyntaxHighlighting.
SaveFileHelper Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.TextEditorSaveFileHelper
int Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.EditBlockIndex
bool Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.IsDirty
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ToModel.
int int lineLength Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.MostCharactersOnASingleLineTuple
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.CalculateVirtualizationResult, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.SetContent.
int int lineLength Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.PreviousMostCharactersOnASingleLineTuple
Key<RenderState> Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.RenderStateKey
int Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.LineCount
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.CalculateVirtualizationResult, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.MoveCursorUnsafe.
int Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.PreviousLineCount
int Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.CharCount
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.__Add, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.__RemoveAt, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.ClearContent, Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.EmptyEditor_TestData_And_PerformPreAssertions, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.GoToMatchingCharacter, Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.NotEmptyEditor_TestData_And_PerformPreAssertions, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.SelectAll.
Stack<TextEditorEditOther> Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.OtherEditStack
The TextEditorEditOther works by invoking 'Open' then when finished invoking 'Close'.
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.CloseOtherEdit, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.OpenOtherEdit.
RichCharacter [] Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier._richCharacterList
TODO: Awkward naming convention is being used here. This is an expression bound property,... ...with the naming conventions of a private field. | The reason for breaking convention here is that every other purpose of this type is done through a private field. | Need to revisit naming this.
bool Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.WasDirty
This property optimizes the dirty state tracking. If _wasDirty != _isDirty then track the state change. This involves writing to dependency injectable state, then triggering a re-render in the Edits.Displays.DirtyResourceUriInteractiveIconDisplay.
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.TextEditorModelModifier.
int Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.PartitionSize
bool Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.WasModified
This property decides whether or not to replace the existing model in IState<TextEditorState> with the instance that comes from this modifier.
bool Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ShouldReloadVirtualizationResult
This property decides whether or not to re-calculate the virtualization result that gets displayed on the UI.
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.Delete, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.Insert, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.SetContent.
string Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.AllText
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ToModel.
int Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier::lineIndex
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.Delete.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ClearContent()
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModel.MOST_CHARACTERS_ON_A_SINGLE_ROW_MARGIN, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.SetIsDirtyTrue.
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ClearAllStatesButKeepEditHistory, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.ClearContent.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.HandleKeyboardEvent(KeymapArgs keymapArgs, CursorModifierBagTextEditor cursorModifierBag, CancellationToken cancellationToken)
References Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.Code, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.CtrlKey, Luthetus.TextEditor.RazorLib.Edits.Models.Delete, Luthetus.TextEditor.RazorLib.Edits.Models.Insert, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.Key, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.LineEndKindPreference, Luthetus.TextEditor.RazorLib.TextEditors.Models.CursorModifierBagTextEditor.List, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.RichCharacterList, Luthetus.TextEditor.RazorLib.TextEditors.Models.CursorModifierBagTextEditor.ViewModelKey.
Referenced by Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.CutAsync, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.DeleteByRange, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.DeleteTextByMotion, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelApi.HandleKeyboardEvent, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelApi.HandleKeyboardEventUnsafe.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.DeleteTextByMotion(MotionKind motionKind, CursorModifierBagTextEditor cursorModifierBag, CancellationToken cancellationToken)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.Backspace, Luthetus.TextEditor.RazorLib.TextEditors.Models.Delete, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.HandleKeyboardEvent.
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelApi.DeleteTextByMotion, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelApi.DeleteTextByMotionUnsafe.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.DeleteByRange(int count, CursorModifierBagTextEditor cursorModifierBag, CancellationToken cancellationToken)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.HandleKeyboardEvent, Luthetus.TextEditor.RazorLib.TextEditors.Models.CursorModifierBagTextEditor.List, Luthetus.TextEditor.RazorLib.TextEditors.Models.CursorModifierBagTextEditor.ViewModelKey.
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelApi.DeleteTextByRange, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelApi.DeleteTextByRangeUnsafe, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.IndentLess.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.SetContent(string content)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.__InsertRange, Luthetus.TextEditor.RazorLib.Rows.Models.CarriageReturnLineFeed, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ClearAllStatesButKeepEditHistory, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.LineEndList, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModel.MOST_CHARACTERS_ON_A_SINGLE_ROW_MARGIN, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.MostCharactersOnASingleLineTuple, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.SetIsDirtyTrue, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ShouldReloadVirtualizationResult, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.TabKeyPositionList.
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelApi.Reload.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ClearEditBlocks()
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.EditBlockList.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.OpenOtherEdit(TextEditorEditOther editOther)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.OtherEditStack.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.CloseOtherEdit(string predictedTag)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.OtherEditStack.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.UndoEdit()
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.UndoEdit.
Referenced by Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.Undo, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelApi.UndoEdit, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.UndoEdit.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.RedoEdit()
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.RedoEdit.
Referenced by Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.Redo, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelApi.RedoEdit, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.RedoEdit.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ClearOnlyRowEndingKind()
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ClearAllStatesButKeepEditHistory.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.SetLineEndKindPreference(LineEndKind rowEndingKind)
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ClearAllStatesButKeepEditHistory, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelApi.SetUsingLineEndKind.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.SetResourceData(ResourceUri resourceUri, DateTime resourceLastWriteTime)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ResourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri.
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelApi.Reload, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelApi.SetResourceData.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.SetDecorationMapper(IDecorationMapper decorationMapper)
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.SetCompilerService(ICompilerService compilerService)
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.SetTextEditorSaveFileHelper(SaveFileHelper textEditorSaveFileHelper)
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ClearAllStatesButKeepEditHistory()
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ClearContent, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ClearOnlyRowEndingKind, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.SetLineEndKindPreference.
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.SetContent.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.SetIsDirtyTrue()
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ClearContent, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.Delete, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.Insert, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.SetContent.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.SetIsDirtyFalse()
Referenced by Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.TriggerSave.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.PerformRegisterPresentationModelAction(TextEditorPresentationModel presentationModel)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.PresentationModelList, Luthetus.TextEditor.RazorLib.Decorations.Models.TextEditorPresentationModel.
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelApi.AddPresentationModel, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.CompletePendingCalculatePresentationModel, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.StartPendingCalculatePresentationModel.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.StartPendingCalculatePresentationModel(Key< TextEditorPresentationModel > presentationKey, TextEditorPresentationModel emptyPresentationModel)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.PerformRegisterPresentationModelAction, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.PresentationModelList, Luthetus.TextEditor.RazorLib.Decorations.Models.TextEditorPresentationModel.
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelApi.StartPendingCalculatePresentationModel.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.CompletePendingCalculatePresentationModel(Key< TextEditorPresentationModel > presentationKey, TextEditorPresentationModel emptyPresentationModel, ImmutableArray< TextEditorTextSpan > calculatedTextSpans)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.PerformRegisterPresentationModelAction, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.PresentationModelList, Luthetus.TextEditor.RazorLib.Decorations.Models.TextEditorPresentationModel.
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelApi.CompletePendingCalculatePresentationModel, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.ParseAsync.
TextEditorModel Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ForceRerenderAction()
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ToModel.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.Insert(string value, CursorModifierBagTextEditor cursorModifierBag, bool useLineEndKindPreference=true, CancellationToken cancellationToken=default, bool shouldCreateEditHistory=true)
useLineEndKindPreference If false, then the string will be inserted as is. If true, then the string will have its line endings replaced with the LineEndKindPreference
References Luthetus.TextEditor.RazorLib.Edits.Models.Delete, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.LineEndList, Luthetus.TextEditor.RazorLib.TextEditors.Models.CursorModifierBagTextEditor.List, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModel.MOST_CHARACTERS_ON_A_SINGLE_ROW_MARGIN, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.SetIsDirtyTrue, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ShouldReloadVirtualizationResult.
Referenced by Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.Duplicate, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.IndentMore, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelApi.InsertText, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelApi.InsertTextUnsafe, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.MoveLineDown, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.MoveLineUp, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.NewLineAbove, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.NewLineBelow, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.PasteAsync.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.Delete(CursorModifierBagTextEditor cursorModifierBag, int columnCount, bool expandWord, DeleteKind deleteKind, CancellationToken cancellationToken=default, bool shouldCreateEditHistory=true)
This method allows for a "RemoveRange" like operation on the text editor's contents. Any meta-data will automatically be updated (e.g. ITextEditorModel.LineEndKindCountList.
cursorModifierBag The list of cursors that indicate the positionIndex to start a "RemoveRange" operation. The cursors are iterated backwards, with each cursor being its own "RemoveRange" operation. columnCount The amount of columns to delete. If a the value of a column is of 2-char length (e.g. "\r\n"), then internally this columnCount will be converted to a 'charCount' of the corrected length. expandWord Applied after moving by the 'count' parameter. Ex: count of 1, and expandWord of true; will move 1 char-value from the initialPositionIndex. Afterwards, if expandWord is true, then the cursor is checked to be within a word, or at the start or end of one. If the cursor is at the start or end of one, then the selection to delete is expanded such that it contains the entire word that the cursor ended at. cancellationToken deleteKind The default DeleteKind.Delete will do logic similar to a "RemoveRange" like operation on a collection type. If one has keyboard input from a user, one might want to have the user's backspace key pass in the DeleteKind.Backspace parameter. Then, for a user's delete key, pass in DeleteKind.Delete.
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.LineEndList, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.lineIndex, Luthetus.TextEditor.RazorLib.TextEditors.Models.CursorModifierBagTextEditor.List, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModel.MOST_CHARACTERS_ON_A_SINGLE_ROW_MARGIN, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.SetIsDirtyTrue, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ShouldReloadVirtualizationResult.
Referenced by Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.MoveLineDown, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.MoveLineUp.
Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.TextEditorModelModifier(TextEditorModel model)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModel.IsDirty, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.MINIMUM_PARTITION_SIZE, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModel.PartitionList, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModel.PartitionSize, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.WasDirty.
TextEditorModel Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ToModel()
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.AllText, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.IsDirty.
Referenced by Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.ClearContent, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ForceRerenderAction.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.__Insert(int globalPositionIndex, RichCharacter richCharacter)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.Count.
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.__Add.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.__SetItem(int globalPositionIndex, RichCharacter richCharacter)
If either character or decoration byte are 'null', then the respective collection will be left unchanged.
i.e.: to change ONLY a character value invoke this method with decorationByte set to null, and only the CharList will be changed.
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.Count.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.__SetDecorationByte(int globalPositionIndex, byte decorationByte)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.Count.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.__RemoveAt(int globalPositionIndex)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.CharCount, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.Count.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.__InsertRange(int globalPositionIndex, IEnumerable< RichCharacter > richCharacterList)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorPartition.Count.
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.SetContent.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.__RemoveRange(int targetGlobalPositionIndex, int targetDeleteCount)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.PartitionList.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.__Add(RichCharacter richCharacter)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.__Insert, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.CharCount.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.PerformInsert(int positionIndex, string content)
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.PerformBackspace(int positionIndex, int count)
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.PerformDelete(int positionIndex, int count)
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.EnsureUndoPoint(ITextEditorEdit newEdit)
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.MutateLineEndKindCount(LineEndKind rowEndingKind, int changeBy)
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.CheckRowEndingPositions(bool setUsingRowEndingKind)
string Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.InsertMetadata(string value, TextEditorCursorModifier cursorModifier, bool useLineEndKindPreference, CancellationToken cancellationToken)
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.InsertValue(string value, int cursorPositionIndex, bool useLineEndKindPreference, CancellationToken cancellationToken)
int int? charCount Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.DeleteMetadata(int columnCount, TextEditorCursorModifier cursorModifier, bool expandWord, DeleteKind deleteKind, CancellationToken cancellationToken)
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.DeleteValue(int positionIndex, int count, CancellationToken cancellationToken)
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.__InsertNewPartition(int partitionIndex)
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.__SplitIntoTwoPartitions(int partitionIndex)