Luthetus::TextEditor::RazorLib::CompilerServices::Syntax::Nodes::FunctionParametersListingNode
ISyntax [] Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionParametersListingNode._childList
bool Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionParametersListingNode._childListIsDirty
OpenParenthesisToken Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionParametersListingNode.OpenParenthesisToken
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionParametersListingNode.FunctionParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionParametersListingNode.GetChildList.
List<FunctionParameterEntryNode> Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionParametersListingNode.FunctionParameterEntryNodeList
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.FunctionParametersListingMergeExpression, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionParametersListingNode.FunctionParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionParametersListingNode.GetChildList.
CloseParenthesisToken Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionParametersListingNode.CloseParenthesisToken
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionParametersListingNode.FunctionParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionParametersListingNode.GetChildList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionParametersListingNode.SetCloseParenthesisToken.
TypeClauseNode IExpressionNode. Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionParametersListingNode.ResultTypeClauseNode
When parsing an expression, there may be a FunctionInvocationNode with a GenericParametersListingNode.
The expression code works however by passing around an 'IExpression expressionPrimary' and an 'IExpression expressionSeconday'. This means we cannot add common logic for parsing a GenericParametersListingNode unless the expression parsing code were modified, or maybe a call to a separate function to parse GenericParametersListingNode could be done. But, for now an experiment with making GenericParametersListingNode into a IExpressionNode is being tried out. Any IExpressionNode that is part of a complete expression, will have the IExpressionNode.ResultTypeClauseNode of Pseudo in order to indicate that the node is part of a expression, but not itself an expression. Use 'TypeClauseNode IExpressionNode.ResultTypeClauseNode => TypeClauseNodeFacts.Pseudo;' so that some confusion can be avoided since one has to cast it explicitly as an IExpressionNode in order to access the property. (i.e.: GenericParameterEntryNode.TypeClauseNode is not equal to IExpressionNode.ResultTypeClauseNode).
bool Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionParametersListingNode.IsFabricated
IsFabricated refers to when the ParserSession expected a node to be valid, but it wasn't. For example, a function invocation on an undefined function will construct a BoundFunctionInvocationNode with IsFabricated set to true.
SyntaxKind Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionParametersListingNode.SyntaxKind
Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionParametersListingNode.FunctionParametersListingNode(OpenParenthesisToken openParenthesisToken, List< FunctionParameterEntryNode > functionParameterEntryNodeList, CloseParenthesisToken closeParenthesisToken)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionParametersListingNode.CloseParenthesisToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionParametersListingNode.FunctionParameterEntryNodeList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionParametersListingNode.OpenParenthesisToken.
Referenced by Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.FunctionInvocationNodeTests.Constructor, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionParametersListingNode.SetCloseParenthesisToken.
FunctionParametersListingNode Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionParametersListingNode.SetCloseParenthesisToken(CloseParenthesisToken closeParenthesisToken)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionParametersListingNode.CloseParenthesisToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionParametersListingNode.FunctionParametersListingNode.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ConstructorInvocationMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.FunctionInvocationMergeToken.
ISyntax[] Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionParametersListingNode.GetChildList()
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionParametersListingNode.CloseParenthesisToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionParametersListingNode.FunctionParameterEntryNodeList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionParametersListingNode.OpenParenthesisToken.