Luthetus::Common::RazorLib::Resizes::Models::ResizeHelper
static void Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.ResizeNorth(ElementDimensions elementDimensions, MouseEventArgs firstMouseEventArgs, MouseEventArgs secondMouseEventArgs)
References Luthetus.Common.RazorLib.Dimensions.Models.ElementDimensions.DimensionAttributeList, Luthetus.Common.RazorLib.Dimensions.Models.Pixels.
Referenced by Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.ResizeNorth, Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.ResizeNorthEast, Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.ResizeNorthWest.
static void Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.ResizeEast(ElementDimensions elementDimensions, MouseEventArgs firstMouseEventArgs, MouseEventArgs secondMouseEventArgs)
References Luthetus.Common.RazorLib.Dimensions.Models.ElementDimensions.DimensionAttributeList, Luthetus.Common.RazorLib.Dimensions.Models.Pixels.
Referenced by Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.ResizeEast, Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.ResizeNorthEast, Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.ResizeSouthEast.
static void Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.ResizeSouth(ElementDimensions elementDimensions, MouseEventArgs firstMouseEventArgs, MouseEventArgs secondMouseEventArgs)
References Luthetus.Common.RazorLib.Dimensions.Models.ElementDimensions.DimensionAttributeList, Luthetus.Common.RazorLib.Dimensions.Models.Pixels.
Referenced by Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.ResizeSouth, Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.ResizeSouthEast, Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.ResizeSouthWest.
static void Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.ResizeWest(ElementDimensions elementDimensions, MouseEventArgs firstMouseEventArgs, MouseEventArgs secondMouseEventArgs)
References Luthetus.Common.RazorLib.Dimensions.Models.ElementDimensions.DimensionAttributeList, Luthetus.Common.RazorLib.Dimensions.Models.Pixels.
Referenced by Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.ResizeNorthWest, Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.ResizeSouthWest, Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.ResizeWest.
static void Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.ResizeNorthEast(ElementDimensions elementDimensions, MouseEventArgs firstMouseEventArgs, MouseEventArgs secondMouseEventArgs)
References Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.ResizeEast, Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.ResizeNorth.
Referenced by Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.ResizeNorthEast.
static void Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.ResizeSouthEast(ElementDimensions elementDimensions, MouseEventArgs firstMouseEventArgs, MouseEventArgs secondMouseEventArgs)
References Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.ResizeEast, Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.ResizeSouth.
Referenced by Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.ResizeSouthEast.
static void Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.ResizeSouthWest(ElementDimensions elementDimensions, MouseEventArgs firstMouseEventArgs, MouseEventArgs secondMouseEventArgs)
References Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.ResizeSouth, Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.ResizeWest.
Referenced by Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.ResizeSouthWest.
static void Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.ResizeNorthWest(ElementDimensions elementDimensions, MouseEventArgs firstMouseEventArgs, MouseEventArgs secondMouseEventArgs)
References Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.ResizeNorth, Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.ResizeWest.
Referenced by Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.ResizeNorthWest.
static void Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.Move(ElementDimensions elementDimensions, MouseEventArgs firstMouseEventArgs, MouseEventArgs secondMouseEventArgs)
References Luthetus.Common.RazorLib.Dimensions.Models.ElementDimensions.DimensionAttributeList, Luthetus.Common.RazorLib.Dimensions.Models.Pixels.
Referenced by Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.Move.