Luthetus::Extensions::DotNet::Tests::Basis::ExtensionsDotNetTestBase
static void Luthetus.Extensions.DotNet.Tests.Basis.ExtensionsDotNetTestBase.Test_RegisterServices(out ServiceProvider serviceProvider)
References hostingInformation, Luthetus.Common.RazorLib.Installations.Models.LuthetusCommonConfig, Luthetus.Common.RazorLib.Installations.Models.LuthetusHostingInformation, Luthetus.Ide.RazorLib.Installations.Models.LuthetusIdeConfig, Luthetus.TextEditor.RazorLib.Installations.Models.LuthetusTextEditorConfig.
Referenced by Luthetus.Extensions.DotNet.Tests.Basis.TreeViewImplementations.Models.TreeViewCompilerServiceTests.Constructor, Luthetus.Extensions.DotNet.Tests.Basis.TreeViewImplementations.Models.TreeViewCSharpProjectDependenciesTests.Constructor, Luthetus.Extensions.DotNet.Tests.Basis.TreeViewImplementations.Models.TreeViewCSharpProjectNugetPackageReferencesTests.Constructor, Luthetus.Extensions.DotNet.Tests.Basis.TreeViewImplementations.Models.TreeViewCSharpProjectNugetPackageReferenceTests.Constructor, Luthetus.Extensions.DotNet.Tests.Basis.TreeViewImplementations.Models.TreeViewCSharpProjectToProjectReferencesTests.Constructor, Luthetus.Extensions.DotNet.Tests.Basis.TreeViewImplementations.Models.TreeViewCSharpProjectToProjectReferenceTests.Constructor, Luthetus.Extensions.DotNet.Tests.Basis.TreeViewImplementations.Models.TreeViewNamespacePathTests.Constructor, Luthetus.Extensions.DotNet.Tests.Basis.TreeViewImplementations.Models.TreeViewProjectTestModelTests.Constructor, Luthetus.Extensions.DotNet.Tests.Basis.TreeViewImplementations.Models.TreeViewSolutionFolderTests.Constructor, Luthetus.Extensions.DotNet.Tests.Basis.TreeViewImplementations.Models.TreeViewSolutionTests.Constructor, Luthetus.Extensions.DotNet.Tests.Basis.TreeViewImplementations.Models.TreeViewStringFragmentTests.Constructor.
static void Luthetus.Extensions.DotNet.Tests.Basis.ExtensionsDotNetTestBase.Test_CreateFileSystem(IServiceProvider serviceProvider)
The files shown in the 'tree' below will be written to the in-memory filesystem. ------------------------------------------ Root ∙└───Homework ∙∙∙∙∙∙├───Math ∙∙∙∙∙∙│∙∙∙∙├───addition.txt ∙∙∙∙∙∙│∙∙∙∙└───subtraction.txt ∙∙∙∙∙∙│ ∙∙∙∙∙∙└───Biology ∙∙∙∙∙∙∙∙∙∙∙├───nervousSystem.txt ∙∙∙∙∙∙∙∙∙∙∙└───skeletalSystem.txt .
Referenced by Luthetus.Extensions.DotNet.Tests.Basis.TreeViewImplementations.Models.TreeViewCompilerServiceTests.Constructor, Luthetus.Extensions.DotNet.Tests.Basis.TreeViewImplementations.Models.TreeViewCSharpProjectDependenciesTests.Constructor, Luthetus.Extensions.DotNet.Tests.Basis.TreeViewImplementations.Models.TreeViewCSharpProjectNugetPackageReferencesTests.Constructor, Luthetus.Extensions.DotNet.Tests.Basis.TreeViewImplementations.Models.TreeViewCSharpProjectNugetPackageReferenceTests.Constructor, Luthetus.Extensions.DotNet.Tests.Basis.TreeViewImplementations.Models.TreeViewCSharpProjectToProjectReferencesTests.Constructor, Luthetus.Extensions.DotNet.Tests.Basis.TreeViewImplementations.Models.TreeViewCSharpProjectToProjectReferenceTests.Constructor, Luthetus.Extensions.DotNet.Tests.Basis.TreeViewImplementations.Models.TreeViewNamespacePathTests.Constructor, Luthetus.Extensions.DotNet.Tests.Basis.TreeViewImplementations.Models.TreeViewProjectTestModelTests.Constructor, Luthetus.Extensions.DotNet.Tests.Basis.TreeViewImplementations.Models.TreeViewSolutionFolderTests.Constructor, Luthetus.Extensions.DotNet.Tests.Basis.TreeViewImplementations.Models.TreeViewSolutionTests.Constructor, Luthetus.Extensions.DotNet.Tests.Basis.TreeViewImplementations.Models.TreeViewStringFragmentTests.Constructor.
static void Luthetus.Extensions.DotNet.Tests.Basis.ExtensionsDotNetTestBase.WriteToInMemoryFileSystem(InMemoryEnvironmentProvider inMemoryEnvironmentProvider, InMemoryFileSystemProvider inMemoryFileSystemProvider)