Luthetus::TextEditor::RazorLib::CompilerServices::DiagnosticBag
readonly List<TextEditorDiagnostic> Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag._diagnosticsBag
IEnumerator< TextEditorDiagnostic > Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.GetEnumerator()
void Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportEndOfFileUnexpected(TextEditorTextSpan textSpan)
References Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseCommentMultiLine, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseCommentSingleLine, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseString.
void Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportUnexpectedToken(TextEditorTextSpan textSpan, string unexpectedToken, string expectedToken)
References Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
void Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportUnexpectedToken(TextEditorTextSpan textSpan, string unexpectedToken)
References Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
void Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportUndefinedClass(TextEditorTextSpan textSpan, string undefinedClassIdentifier)
References Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
void Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportImplicitlyTypedVariablesMustBeInitialized(TextEditorTextSpan textSpan)
References Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
void Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportUndefinedTypeOrNamespace(TextEditorTextSpan textSpan, string undefinedTypeOrNamespaceIdentifier)
References Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
void Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportAlreadyDefinedType(TextEditorTextSpan textSpan, string alreadyDefinedTypeIdentifier)
References Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
void Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportUndefinedVariable(TextEditorTextSpan textSpan, string undefinedVariableIdentifier)
References Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
void Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportNotDefinedInContext(TextEditorTextSpan textSpan, string contextString)
References Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
void Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.TheNameDoesNotExistInTheCurrentContext(TextEditorTextSpan textSpan, string name)
References Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
void Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportAlreadyDefinedVariable(TextEditorTextSpan textSpan, string alreadyDefinedVariableIdentifier)
References Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
void Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportAlreadyDefinedProperty(TextEditorTextSpan textSpan, string alreadyDefinedPropertyIdentifier)
References Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
void Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportUndefinedFunction(TextEditorTextSpan textSpan, string undefinedFunctionIdentifier)
References Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
void Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportAlreadyDefinedFunction(TextEditorTextSpan textSpan, string alreadyDefinedFunctionIdentifier)
References Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
void Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportBadFunctionOptionalArgumentDueToMismatchInType(TextEditorTextSpan optionalArgumentTextSpan, string optionalArgumentVariableIdentifier, string typeExpectedIdentifierString, string typeActualIdentifierString)
References Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
void Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportReturnStatementsAreStillBeingImplemented(TextEditorTextSpan textSpan)
References Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
void Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportTagNameMissing(TextEditorTextSpan textSpan)
References Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
void Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportOpenTagWithUnMatchedCloseTag(string openTagName, string closeTagName, TextEditorTextSpan textSpan)
References Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
void Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportRazorExplicitExpressionPredicateWasExpected(string transitionSubstring, string keywordText, TextEditorTextSpan textSpan)
References Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
void Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportRazorCodeBlockWasExpectedToFollowRazorKeyword(string transitionSubstring, string keywordText, TextEditorTextSpan textSpan)
References Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
void Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportRazorWhitespaceImmediatelyFollowingTransitionCharacterIsUnexpected(TextEditorTextSpan textSpan)
References Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
Referenced by Luthetus.CompilerServices.Razor.RazorSyntaxTree.ParseInjectedLanguageFragment.
void Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportConstructorsNeedToBeWithinTypeDefinition(TextEditorTextSpan textSpan)
References Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
void Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportTodoException(TextEditorTextSpan textSpan, string message)
The text "TODO: " is pre-pended to the provided message. Used when the C# Parser has not yet implemented the functionality that one would expect given the situation. // TODO: Find all references to this method and fix them. Keep this comment so one can search // TODO: and arrive here.
References Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AmbiguousIdentifierMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindBinaryOperatorNode, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindInheritanceStatementNode, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindLiteralExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.ICodeBlockOwner.ThrowAlreadyAssignedCodeBlockNodeException, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.ICodeBlockOwner.ThrowMultipleScopeDelimiterException.
void Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ClearByResourceUri(ResourceUri resourceUri)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
IEnumerator IEnumerable. Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.GetEnumerator()
void Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.Report(TextEditorDiagnosticLevel diagnosticLevel, string message, TextEditorTextSpan textSpan, Guid diagnosticId)