Luthetus::TextEditor::RazorLib::Options::States::TextEditorOptionsState
const int Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.DEFAULT_FONT_SIZE_IN_PIXELS
Referenced by Luthetus.TextEditor.Tests.Basis.Options.Models.TextEditorOptionsTests.Constructor, Luthetus.TextEditor.Tests.Basis.Options.States.TextEditorOptionsStateReducerTests.ReduceSetFontSizeAction, Luthetus.TextEditor.Tests.Basis.Options.States.TextEditorOptionsStateActionsTests.SetFontSizeAction, Luthetus.TextEditor.Tests.Basis.Options.Models.TextEditorOptionsJsonDtoTests.TextEditorOptionsJsonDto_C, Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.TextEditorOptionsState.
const int Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.DEFAULT_ICON_SIZE_IN_PIXELS
Referenced by Luthetus.TextEditor.Tests.Basis.Options.Models.TextEditorOptionsTests.Constructor, Luthetus.TextEditor.Tests.Basis.Options.Models.TextEditorOptionsJsonDtoTests.TextEditorOptionsJsonDto_C, Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.TextEditorOptionsState.
const double Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.DEFAULT_CURSOR_WIDTH_IN_PIXELS
Referenced by Luthetus.TextEditor.Tests.Basis.Options.States.TextEditorOptionsStateReducerTests.ReduceSetCursorWidthAction, Luthetus.TextEditor.Tests.Basis.Options.Models.OptionsApiTests.SetCursorWidth, Luthetus.TextEditor.Tests.Basis.Options.States.TextEditorOptionsStateActionsTests.SetCursorWidthAction, Luthetus.TextEditor.Tests.Basis.Options.Models.TextEditorOptionsJsonDtoTests.TextEditorOptionsJsonDto_C, Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.TextEditorOptionsState.
const int Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.MINIMUM_FONT_SIZE_IN_PIXELS
const int Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.MINIMUM_ICON_SIZE_IN_PIXELS
TextEditorOptions Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Options
Referenced by Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Reducer.ReduceSetCursorWidthAction, Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Reducer.ReduceSetFontFamilyAction, Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Reducer.ReduceSetFontSizeAction, Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Reducer.ReduceSetHeightAction, Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Reducer.ReduceSetKeymapAction, Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Reducer.ReduceSetRenderStateKeyAction, Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Reducer.ReduceSetShowNewlinesAction, Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Reducer.ReduceSetShowWhitespaceAction, Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Reducer.ReduceSetThemeAction, Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Reducer.ReduceSetUseMonospaceOptimizationsAction, Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.TextEditorOptionsState.
record Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.SetFontFamilyAction(string? FontFamily)
Referenced by Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Reducer.ReduceSetFontFamilyAction, Luthetus.TextEditor.Tests.Basis.Options.States.TextEditorOptionsStateReducerTests.ReduceSetFontFamilyAction, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetFontFamily, Luthetus.TextEditor.Tests.Basis.Options.States.TextEditorOptionsStateActionsTests.SetFontFamilyAction.
record Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.SetFontSizeAction(int FontSizeInPixels)
Referenced by Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Reducer.ReduceSetFontSizeAction, Luthetus.TextEditor.Tests.Basis.Options.States.TextEditorOptionsStateReducerTests.ReduceSetFontSizeAction, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetFontSize, Luthetus.TextEditor.Tests.Basis.Options.States.TextEditorOptionsStateActionsTests.SetFontSizeAction.
record Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.SetCursorWidthAction(double CursorWidthInPixels)
Referenced by Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Reducer.ReduceSetCursorWidthAction, Luthetus.TextEditor.Tests.Basis.Options.States.TextEditorOptionsStateReducerTests.ReduceSetCursorWidthAction, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetCursorWidth, Luthetus.TextEditor.Tests.Basis.Options.States.TextEditorOptionsStateActionsTests.SetCursorWidthAction.
record Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.SetRenderStateKeyAction(Key< RenderState > RenderStateKey)
Referenced by Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Reducer.ReduceSetRenderStateKeyAction, Luthetus.TextEditor.Tests.Basis.Options.States.TextEditorOptionsStateReducerTests.ReduceSetRenderStateKeyAction, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetRenderStateKey, Luthetus.TextEditor.Tests.Basis.Options.States.TextEditorOptionsStateActionsTests.SetRenderStateKeyAction.
record Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.SetHeightAction(int? HeightInPixels)
Referenced by Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Reducer.ReduceSetHeightAction, Luthetus.TextEditor.Tests.Basis.Options.States.TextEditorOptionsStateReducerTests.ReduceSetHeightAction, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetHeight, Luthetus.TextEditor.Tests.Basis.Options.States.TextEditorOptionsStateActionsTests.SetHeightAction.
record Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.SetThemeAction(ThemeRecord Theme)
This is setting the TextEditor's theme specifically. This is not to be confused with the AppOptions Themes which get applied at an application level. This allows for a "DarkTheme-Application" that has a "LightTheme-TextEditor".
References Luthetus.Common.RazorLib.Themes.Models.ThemeRecord.
Referenced by Luthetus.TextEditor.RazorLib.Installations.Displays.LuthetusTextEditorInitializer.OnInitialized, Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Reducer.ReduceSetThemeAction, Luthetus.TextEditor.Tests.Basis.Options.States.TextEditorOptionsStateReducerTests.ReduceSetThemeAction, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetTheme, Luthetus.TextEditor.Tests.Basis.Options.States.TextEditorOptionsStateActionsTests.SetThemeAction.
record Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.SetKeymapAction(Keymap Keymap)
Referenced by Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Reducer.ReduceSetKeymapAction, Luthetus.TextEditor.Tests.Basis.Options.States.TextEditorOptionsStateReducerTests.ReduceSetKeymapAction, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetKeymap, Luthetus.TextEditor.Tests.Basis.Options.States.TextEditorOptionsStateActionsTests.SetKeymapAction.
record Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.SetShowWhitespaceAction(bool ShowWhitespace)
Referenced by Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Reducer.ReduceSetShowWhitespaceAction, Luthetus.TextEditor.Tests.Basis.Options.States.TextEditorOptionsStateReducerTests.ReduceSetShowWhitespaceAction, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetShowWhitespace, Luthetus.TextEditor.Tests.Basis.Options.States.TextEditorOptionsStateActionsTests.SetShowWhitespaceAction.
record Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.SetShowNewlinesAction(bool ShowNewlines)
Referenced by Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Reducer.ReduceSetShowNewlinesAction, Luthetus.TextEditor.Tests.Basis.Options.States.TextEditorOptionsStateReducerTests.ReduceSetShowNewlinesAction, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetShowNewlines, Luthetus.TextEditor.Tests.Basis.Options.States.TextEditorOptionsStateActionsTests.SetShowNewlinesAction.
record Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.SetUseMonospaceOptimizationsAction(bool UseMonospaceOptimizations)
Referenced by Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Reducer.ReduceSetUseMonospaceOptimizationsAction, Luthetus.TextEditor.Tests.Basis.Options.States.TextEditorOptionsStateReducerTests.ReduceSetUseMonospaceOptimizationsAction, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetUseMonospaceOptimizations, Luthetus.TextEditor.Tests.Basis.Options.States.TextEditorOptionsStateActionsTests.SetUseMonospaceOptimizationsAction.
Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.TextEditorOptionsState()
References Luthetus.Common.RazorLib.Options.Models.CommonOptions, Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.DEFAULT_CURSOR_WIDTH_IN_PIXELS, Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.DEFAULT_FONT_SIZE_IN_PIXELS, Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.DEFAULT_ICON_SIZE_IN_PIXELS, Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Options, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptions.
Referenced by Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Reducer.ReduceSetCursorWidthAction, Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Reducer.ReduceSetFontFamilyAction, Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Reducer.ReduceSetFontSizeAction, Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Reducer.ReduceSetHeightAction, Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Reducer.ReduceSetKeymapAction, Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Reducer.ReduceSetRenderStateKeyAction, Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Reducer.ReduceSetShowNewlinesAction, Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Reducer.ReduceSetShowWhitespaceAction, Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Reducer.ReduceSetThemeAction, Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.Reducer.ReduceSetUseMonospaceOptimizationsAction.