Luthetus::Common::RazorLib::FileSystems::Models::InMemoryFileSystemProvider::InMemoryDirectoryHandler
const bool Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.IS_DIRECTORY_RESPONSE
readonly InMemoryFileSystemProvider Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler._inMemoryFileSystemProvider
readonly IEnvironmentProvider Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler._environmentProvider
readonly ICommonComponentRenderers Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler._commonComponentRenderers
readonly IDispatcher Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler._dispatcher
Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.InMemoryDirectoryHandler(InMemoryFileSystemProvider inMemoryFileSystemProvider, IEnvironmentProvider environmentProvider, ICommonComponentRenderers commonComponentRenderers, IDispatcher dispatcher)
References Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileSystemProvider.
Task< bool > Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.ExistsAsync(string absolutePathString, CancellationToken cancellationToken=default)
References Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.UnsafeExistsAsync.
Referenced by Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.UnsafeMoveAsync.
async Task Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.CreateDirectoryAsync(string absolutePathString, CancellationToken cancellationToken=default)
References Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.UnsafeCreateDirectoryAsync.
async Task Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.DeleteAsync(string absolutePathString, bool recursive, CancellationToken cancellationToken=default)
References Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.UnsafeDeleteAsync.
async Task Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.CopyAsync(string sourceAbsoluteFileString, string destinationAbsolutePathString, CancellationToken cancellationToken=default)
References Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.UnsafeCopyAsync.
async Task Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.MoveAsync(string sourceAbsolutePathString, string destinationAbsolutePathString, CancellationToken cancellationToken=default)
References Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.UnsafeMoveAsync.
Task< string[]> Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.GetDirectoriesAsync(string absolutePathString, CancellationToken cancellationToken=default)
References Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.UnsafeGetDirectoriesAsync.
Referenced by Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.UnsafeCopyAsync.
Task< string[]> Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.GetFilesAsync(string absolutePathString, CancellationToken cancellationToken=default)
References Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.UnsafeGetFilesAsync.
Referenced by Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.UnsafeCopyAsync.
async Task< IEnumerable< string > > Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.EnumerateFileSystemEntriesAsync(string absolutePathString, CancellationToken cancellationToken=default)
References Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.UnsafeEnumerateFileSystemEntriesAsync.
Task< bool > Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.UnsafeExistsAsync(string absolutePathString, CancellationToken cancellationToken=default)
Referenced by Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.ExistsAsync, Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.UnsafeCopyAsync.
Task Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.UnsafeCreateDirectoryAsync(string absolutePathString, CancellationToken cancellationToken=default)
References Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFile, Luthetus.Common.RazorLib.FileSystems.Models.SimplePath.
Referenced by Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.CreateDirectoryAsync.
async Task Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.UnsafeDeleteAsync(string absolutePathString, bool recursive, CancellationToken cancellationToken=default)
Referenced by Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.DeleteAsync, Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.UnsafeMoveAsync.
async Task Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.UnsafeCopyAsync(string sourceAbsolutePathString, string destinationAbsolutePathString, CancellationToken cancellationToken=default)
References Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.GetDirectoriesAsync, Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.GetFilesAsync, Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFile, Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.UnsafeExistsAsync.
Referenced by Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.CopyAsync, Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.UnsafeMoveAsync.
async Task Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.UnsafeMoveAsync(string sourceAbsolutePathString, string destinationAbsolutePathString, CancellationToken cancellationToken=default)
destinationAbsolutePathString refers to the newly created dir not the parent dir which will contain it
References Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.ExistsAsync, Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.UnsafeCopyAsync, Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.UnsafeDeleteAsync.
Referenced by Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.MoveAsync.
Task< string[]> Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.UnsafeGetDirectoriesAsync(string absolutePathString, CancellationToken cancellationToken=default)
Referenced by Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.GetDirectoriesAsync, Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.UnsafeEnumerateFileSystemEntriesAsync.
Task< string[]> Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.UnsafeGetFilesAsync(string absolutePathString, CancellationToken cancellationToken=default)
Referenced by Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.GetFilesAsync, Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.UnsafeEnumerateFileSystemEntriesAsync.
async Task< IEnumerable< string > > Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.UnsafeEnumerateFileSystemEntriesAsync(string absolutePathString, CancellationToken cancellationToken=default)
References Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.UnsafeGetDirectoriesAsync, Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.UnsafeGetFilesAsync.
Referenced by Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.EnumerateFileSystemEntriesAsync.
void Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.NotifyUserOfException(Exception exception)