Luthetus::TextEditor::RazorLib::TextEditorService
record Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorEditContext
readonly IBackgroundTaskService Luthetus.TextEditor.RazorLib.TextEditorService._backgroundTaskService
readonly IDispatcher Luthetus.TextEditor.RazorLib.TextEditorService._dispatcher
readonly IDialogService Luthetus.TextEditor.RazorLib.TextEditorService._dialogService
readonly ITextEditorRegistryWrap Luthetus.TextEditor.RazorLib.TextEditorService._textEditorRegistryWrap
readonly IStorageService Luthetus.TextEditor.RazorLib.TextEditorService._storageService
readonly IJSRuntime Luthetus.TextEditor.RazorLib.TextEditorService._jsRuntime
readonly CommonBackgroundTaskApi Luthetus.TextEditor.RazorLib.TextEditorService._commonBackgroundTaskApi
readonly IServiceProvider Luthetus.TextEditor.RazorLib.TextEditorService._serviceProvider
record? TextEditorModelModifier Luthetus.TextEditor.RazorLib.TextEditorService.ModelCache
Dictionary<Key<TextEditorViewModel>, ResourceUri?> Luthetus.TextEditor.RazorLib.TextEditorService.ViewModelToModelResourceUriCache
Referenced by Luthetus.TextEditor.RazorLib.TextEditorService.GetModelModifierByViewModelKey.
Dictionary<Key<TextEditorViewModel>, TextEditorViewModelModifier?> Luthetus.TextEditor.RazorLib.TextEditorService.ViewModelCache
Referenced by Luthetus.TextEditor.RazorLib.TextEditorService.GetViewModelModifier.
Dictionary<Key<TextEditorViewModel>, CursorModifierBagTextEditor?> Luthetus.TextEditor.RazorLib.TextEditorService.CursorModifierBagCache
Referenced by Luthetus.TextEditor.RazorLib.TextEditorService.GetCursorModifierBag.
Dictionary<Key<TextEditorDiffModel>, TextEditorDiffModelModifier?> Luthetus.TextEditor.RazorLib.TextEditorService.DiffModelCache
Referenced by Luthetus.TextEditor.RazorLib.TextEditorService.GetDiffModelModifier.
ITextEditorService Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorService
References Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorService.
Referenced by Luthetus.TextEditor.RazorLib.TextEditorService.GetDiffModelModifier, Luthetus.TextEditor.RazorLib.TextEditorService.GetModelModifier, Luthetus.TextEditor.RazorLib.TextEditorService.GetModelModifierByViewModelKey, Luthetus.TextEditor.RazorLib.TextEditorService.GetViewModelModifier, Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorEditContext, Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorService.
Key<TextEditorAuthenticatedAction> Luthetus.TextEditor.RazorLib.TextEditorService.AuthenticatedActionKey
Referenced by Luthetus.TextEditor.RazorLib.TextEditorService.Post, Luthetus.TextEditor.RazorLib.TextEditorService.PostAsync, Luthetus.TextEditor.Tests.Basis.TextEditors.States.TextEditorStateReducerTests.ReduceRegisterAction, Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorEditContext.
IState<TextEditorState> Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorStateWrap
Referenced by Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorService.
IState<TextEditorGroupState> Luthetus.TextEditor.RazorLib.TextEditorService.GroupStateWrap
Referenced by Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorService.
IState<TextEditorDiffState> Luthetus.TextEditor.RazorLib.TextEditorService.DiffStateWrap
Referenced by Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorService.
IState<ThemeState> Luthetus.TextEditor.RazorLib.TextEditorService.ThemeStateWrap
Referenced by Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorService.
IState<TextEditorOptionsState> Luthetus.TextEditor.RazorLib.TextEditorService.OptionsStateWrap
Referenced by Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorService.
IState<TextEditorFindAllState> Luthetus.TextEditor.RazorLib.TextEditorService.FindAllStateWrap
Referenced by Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorService.
IState<AppDimensionState> Luthetus.TextEditor.RazorLib.TextEditorService.AppDimensionStateWrap
Referenced by Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorService.
LuthetusTextEditorJavaScriptInteropApi Luthetus.TextEditor.RazorLib.TextEditorService.JsRuntimeTextEditorApi
Referenced by Luthetus.TextEditor.RazorLib.TextEditorService.FinalizePost, Luthetus.TextEditor.RazorLib.TextEditors.Displays.TextEditorViewModelDisplay.OnAfterRenderAsync, Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorService.
LuthetusCommonJavaScriptInteropApi Luthetus.TextEditor.RazorLib.TextEditorService.JsRuntimeCommonApi
Referenced by Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorService.
IAutocompleteIndexer Luthetus.TextEditor.RazorLib.TextEditorService.AutocompleteIndexer
Referenced by Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorService.
IAutocompleteService Luthetus.TextEditor.RazorLib.TextEditorService.AutocompleteService
Referenced by Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorService.
LuthetusTextEditorConfig Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorConfig
Referenced by Luthetus.TextEditor.RazorLib.TextEditorService.OpenInEditorAsync, Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorService.
string Luthetus.TextEditor.RazorLib.TextEditorService.StorageKey
This is used when interacting with the IStorageService to set and get data.
string Luthetus.TextEditor.RazorLib.TextEditorService.ThemeCssClassString
ITextEditorModelApi Luthetus.TextEditor.RazorLib.TextEditorService.ModelApi
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.FooterDriver.SelectRowEndingKindOnChange, Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorService.
ITextEditorViewModelApi Luthetus.TextEditor.RazorLib.TextEditorService.ViewModelApi
Referenced by Luthetus.TextEditor.RazorLib.TextEditorService.FinalizePost, Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorService.
ITextEditorGroupApi Luthetus.TextEditor.RazorLib.TextEditorService.GroupApi
Referenced by Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorService.
ITextEditorDiffApi Luthetus.TextEditor.RazorLib.TextEditorService.DiffApi
Referenced by Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorService.
ITextEditorOptionsApi Luthetus.TextEditor.RazorLib.TextEditorService.OptionsApi
Referenced by Luthetus.Ide.RazorLib.Shareds.Displays.IdeMainLayout.OnAfterRenderAsync, Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorService.
readonly Key<TextEditorAuthenticatedAction> Luthetus.TextEditor.RazorLib.TextEditorService.AuthenticatedActionKey
See explanation of this field at: TextEditorAuthenticatedAction.
Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorEditContext(ITextEditorService textEditorService, Key< TextEditorAuthenticatedAction > authenticatedActionKey)
References Luthetus.TextEditor.RazorLib.TextEditorService.AuthenticatedActionKey, Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorService, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
TextEditorModelModifier? Luthetus.TextEditor.RazorLib.TextEditorService.GetModelModifier(ResourceUri modelResourceUri, bool isReadonly=false)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorService.
Referenced by Luthetus.TextEditor.RazorLib.TextEditorService.GetModelModifierByViewModelKey.
TextEditorModelModifier? Luthetus.TextEditor.RazorLib.TextEditorService.GetModelModifierByViewModelKey(Key< TextEditorViewModel > viewModelKey, bool isReadonly=false)
References Luthetus.TextEditor.RazorLib.TextEditorService.GetModelModifier, Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorService, Luthetus.TextEditor.RazorLib.TextEditorService.ViewModelToModelResourceUriCache.
TextEditorViewModelModifier? Luthetus.TextEditor.RazorLib.TextEditorService.GetViewModelModifier(Key< TextEditorViewModel > viewModelKey, bool isReadonly=false)
References Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorService, Luthetus.TextEditor.RazorLib.TextEditorService.ViewModelCache.
CursorModifierBagTextEditor? Luthetus.TextEditor.RazorLib.TextEditorService.GetCursorModifierBag(TextEditorViewModel? viewModel)
References Luthetus.TextEditor.RazorLib.TextEditorService.CursorModifierBagCache, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModel.
TextEditorCursorModifier? Luthetus.TextEditor.RazorLib.TextEditorService.GetPrimaryCursorModifier(CursorModifierBagTextEditor? cursorModifierBag)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.CursorModifierBagTextEditor.List.
TextEditorDiffModelModifier? Luthetus.TextEditor.RazorLib.TextEditorService.GetDiffModelModifier(Key< TextEditorDiffModel > diffModelKey, bool isReadonly=false)
References Luthetus.TextEditor.RazorLib.TextEditorService.DiffModelCache, Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorService.
Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorService(IState< TextEditorState > textEditorStateWrap, IState< TextEditorGroupState > groupStateWrap, IState< TextEditorDiffState > diffStateWrap, IState< ThemeState > themeStateWrap, IState< TextEditorOptionsState > optionsStateWrap, IState< TextEditorFindAllState > findAllStateWrap, IBackgroundTaskService backgroundTaskService, LuthetusTextEditorConfig textEditorConfig, ITextEditorRegistryWrap textEditorRegistryWrap, IStorageService storageService, IJSRuntime jsRuntime, CommonBackgroundTaskApi commonBackgroundTaskApi, IDispatcher dispatcher, IDialogService dialogService, IAutocompleteIndexer autocompleteIndexer, IAutocompleteService autocompleteService, IState< AppDimensionState > appDimensionStateWrap, IServiceProvider serviceProvider)
References Luthetus.TextEditor.RazorLib.TextEditorService.AppDimensionStateWrap, Luthetus.TextEditor.RazorLib.TextEditorService.AutocompleteIndexer, Luthetus.TextEditor.RazorLib.TextEditorService.AutocompleteService, Luthetus.TextEditor.RazorLib.TextEditors.Models.dialogService, Luthetus.TextEditor.RazorLib.TextEditorService.DiffApi, Luthetus.TextEditor.RazorLib.TextEditorService.DiffStateWrap, Luthetus.TextEditor.RazorLib.TextEditors.Models.dispatcher, Luthetus.TextEditor.RazorLib.TextEditorService.FindAllStateWrap, Luthetus.TextEditor.RazorLib.TextEditorService.GroupApi, Luthetus.TextEditor.RazorLib.TextEditorService.GroupStateWrap, Luthetus.TextEditor.RazorLib.TextEditors.Models.jsRuntime, Luthetus.TextEditor.RazorLib.TextEditorService.JsRuntimeCommonApi, Luthetus.TextEditor.RazorLib.TextEditorService.JsRuntimeTextEditorApi, Luthetus.TextEditor.RazorLib.Installations.Models.LuthetusTextEditorConfig, Luthetus.TextEditor.RazorLib.TextEditorService.ModelApi, Luthetus.TextEditor.RazorLib.TextEditorService.OptionsApi, Luthetus.TextEditor.RazorLib.TextEditorService.OptionsStateWrap, Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorConfig, Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorStateWrap, Luthetus.TextEditor.RazorLib.TextEditorService.ThemeStateWrap, Luthetus.TextEditor.RazorLib.TextEditorService.ViewModelApi.
void Luthetus.TextEditor.RazorLib.TextEditorService.PostUnique(string name, Func< ITextEditorEditContext, Task > textEditorFunc)
This method will create an instance of UniqueTextEditorTask, and then invoke Post(ITextEditorWork) .
References Luthetus.TextEditor.RazorLib.TextEditorService.Post.
Referenced by Luthetus.TextEditor.RazorLib.TextEditorService.OpenInEditorAsync, Luthetus.TextEditor.RazorLib.TextEditorService.OpenInEditorAsync.
void Luthetus.TextEditor.RazorLib.TextEditorService.PostRedundant(string name, ResourceUri resourceUri, Key< TextEditorViewModel > viewModelKey, Func< ITextEditorEditContext, Task > textEditorFunc)
This method will create an instance of RedundantTextEditorTask, and then invoke Post(ITextEditorWork) .
References Luthetus.TextEditor.RazorLib.TextEditorService.Post, Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri.
void Luthetus.TextEditor.RazorLib.TextEditorService.Post(ITextEditorWork work)
This method will set the ITextEditorWork.EditContext property.
Within the method Luthetus.Common.RazorLib.BackgroundTasks.Models.IBackgroundTask.HandleEvent, invoke FinalizePost to finalize any changes.
References Luthetus.TextEditor.RazorLib.TextEditorService.AuthenticatedActionKey.
Referenced by Luthetus.TextEditor.RazorLib.TextEditorService.PostRedundant, Luthetus.TextEditor.RazorLib.TextEditorService.PostUnique.
Task Luthetus.TextEditor.RazorLib.TextEditorService.PostAsync(ITextEditorWork work)
This method will set the ITextEditorWork.EditContext property.
Within the method Luthetus.Common.RazorLib.BackgroundTasks.Models.IBackgroundTask.HandleEvent, invoke FinalizePost to finalize any changes. This async version will block until the background task is completed.
References Luthetus.TextEditor.RazorLib.TextEditorService.AuthenticatedActionKey.
async Task Luthetus.TextEditor.RazorLib.TextEditorService.FinalizePost(ITextEditorEditContext editContext)
<summmary> This method writes any mutated data within the ITextEditorWork.EditContext to the TextEditorState, and afterwards causes a UI render.
References Luthetus.TextEditor.RazorLib.TextEditors.Models.CursorList, Luthetus.TextEditor.RazorLib.Edits.States.DirtyResourceUriState, Luthetus.TextEditor.RazorLib.TextEditorService.JsRuntimeTextEditorApi, Luthetus.TextEditor.RazorLib.TextEditors.States.TextEditorState, Luthetus.TextEditor.RazorLib.TextEditorService.ValidateMaximumScrollLeftAndScrollTop, Luthetus.TextEditor.RazorLib.TextEditorService.ViewModelApi.
void Luthetus.TextEditor.RazorLib.TextEditorService.ValidateMaximumScrollLeftAndScrollTop(ITextEditorEditContext editContext, TextEditorViewModelModifier viewModelModifier, bool textEditorDimensionsChanged)
The argument 'bool textEditorDimensionsChanged' was added on (2024-09-20).
The issue is that this method was originally written for fixing the scrollLeft or scrollTop when the scrollWidth or scrollHeight changed to a smaller value. The if statements therefore check that the originalScrollWidth was higher, because some invokers of this method won't need to take time doing this calculation. For example, a pure insertion of text won't need to run this method. So the if statements allow for a quick exit. But, it was discovered that this same logic is needed when the text editor width changes. The text editor width changing results in a very specific event firing. So if we could just have a bool here to say, "I'm that specific event" then we can know that the width changed. Because we cannot track the before and after of the width from this method since it already was changed. We need the specific event to instead tell us that it had changed. So, the bool is a bit hacky.
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetModelModifier, Luthetus.TextEditor.RazorLib.TextEditors.Models.ScrollbarDimensions, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModel.TAB_WIDTH, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelModifier.ViewModel.
Referenced by Luthetus.TextEditor.RazorLib.TextEditorService.FinalizePost.
async Task Luthetus.TextEditor.RazorLib.TextEditorService.OpenInEditorAsync(string absolutePath, bool shouldSetFocusToEditor, int? cursorPositionIndex, Category category, Key< TextEditorViewModel > preferredViewModelKey)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.Category, Luthetus.TextEditor.RazorLib.TextEditors.Models.category, Luthetus.TextEditor.RazorLib.TextEditorService.OpenInEditorAsync, Luthetus.TextEditor.RazorLib.TextEditorService.PostUnique, Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri.
Referenced by Luthetus.TextEditor.RazorLib.TextEditorService.OpenInEditorAsync, Luthetus.TextEditor.RazorLib.TextEditorService.OpenInEditorAsync.
async Task Luthetus.TextEditor.RazorLib.TextEditorService.OpenInEditorAsync(string absolutePath, bool shouldSetFocusToEditor, int? lineIndex, int? columnIndex, Category category, Key< TextEditorViewModel > preferredViewModelKey)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.Category, Luthetus.TextEditor.RazorLib.TextEditors.Models.category, Luthetus.TextEditor.RazorLib.TextEditorService.OpenInEditorAsync, Luthetus.TextEditor.RazorLib.TextEditorService.PostUnique, Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri, Luthetus.TextEditor.RazorLib.TextEditorService.TextEditorConfig.
async Task< Key< TextEditorViewModel > > Luthetus.TextEditor.RazorLib.TextEditorService.CommonLogic_OpenInEditorAsync(ResourceUri resourceUri, bool shouldSetFocusToEditor, Category category, Key< TextEditorViewModel > preferredViewModelKey)
Returns Key<TextEditorViewModel>.Empty if it failed to open in editor. Returns the ViewModel's key (non Key<TextEditorViewModel>.Empty value) if it successfully opened in editor.