Luthetus::TextEditor::RazorLib::CompilerServices::Utility::TokenWalker
readonly ImmutableArray<ISyntaxToken> Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker._tokenList
readonly DiagnosticBag Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker._diagnosticBag
int Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker._index
int Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.openTokenIndex
int int Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.closeTokenIndex
int int int? tokenIndexToRestore Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker._deferredParsingTuple
int Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.ConsumeCounter
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.Backtrack, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.Consume, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.ConsumeCounterReset, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.DeferredParsing.
ImmutableArray<ISyntaxToken> Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.TokenList
ISyntaxToken Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.Current
ISyntaxToken Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.Next
ISyntaxToken Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.Previous
bool Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.IsEof
int Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.Index
ISyntaxToken Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.EOF
If there are any tokens, then assume the final token is the end of file token. Otherwise, fabricate an end of file token.
Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.TokenWalker(ImmutableArray< ISyntaxToken > tokenList, DiagnosticBag diagnosticBag)
ISyntaxToken Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.Peek(int offset)
The input to this method can be positive OR negative. Returns BadToken when an index out of bounds error would've occurred.
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.Backtrack, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.Match, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.MatchRange.
ISyntaxToken Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.Consume()
References Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.ConsumeCounter.
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.Match, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.MatchRange.
ISyntaxToken Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.Backtrack()
References Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.ConsumeCounter, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.Peek.
ISyntaxToken Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.Match(SyntaxKind expectedSyntaxKind)
If the syntaxKind passed in does not match the current token, then a syntax token with that syntax kind will be fabricated and then returned instead.
References Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.Consume, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.IdentifierToken, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.Peek.
ISyntaxToken Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.MatchRange(IEnumerable< SyntaxKind > validSyntaxKinds, SyntaxKind fabricationKind)
If the syntaxKind passed in does not match the current token, then a syntax token with that syntax kind will be fabricated and then returned instead.
References Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.Consume, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.Peek.
void Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.DeferredParsing(int openTokenIndex, int closeTokenIndex, int tokenIndexToRestore)
TODO: This method is being added to support breadth first parsing... ...Having this be a public method is a bit hacky, preferably deferring the parsing of a child scope would be done entirely from this class, so the _index cannot be changed externally (2024-06-18).
References Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.ConsumeCounter.
void Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.ConsumeCounterReset()
References Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.ConsumeCounter.
BadToken Luthetus.TextEditor.RazorLib.CompilerServices.Utility.TokenWalker.GetBadToken()