Luthetus::Ide::Tests::Basis::IdeTestBase
static void Luthetus.Ide.Tests.Basis.IdeTestBase.Test_RegisterServices(out ServiceProvider serviceProvider)
References Luthetus.Common.RazorLib.Installations.Models.LuthetusCommonConfig, Luthetus.Common.RazorLib.Installations.Models.LuthetusHostingInformation, Luthetus.Ide.RazorLib.Installations.Models.LuthetusIdeConfig, Luthetus.TextEditor.RazorLib.Installations.Models.LuthetusTextEditorConfig.
Referenced by Luthetus.Ide.Tests.Basis.TreeViewImplementations.Models.TreeViewAbsolutePathTests.Constructor, Luthetus.Ide.Tests.Basis.TreeViewImplementations.Models.TreeViewGitFileTests.Constructor, Luthetus.Ide.Tests.Basis.TreeViewImplementations.Models.TreeViewMarkupStringTests.Constructor, Luthetus.Ide.Tests.Basis.TreeViewImplementations.Models.TreeViewSpinnerTests.Constructor.
static void Luthetus.Ide.Tests.Basis.IdeTestBase.Test_CreateFileSystem(IServiceProvider serviceProvider)
The files shown in the 'tree' below will be written to the in-memory filesystem. ------------------------------------------ Root ∙└───Homework ∙∙∙∙∙∙├───Math ∙∙∙∙∙∙│∙∙∙∙├───addition.txt ∙∙∙∙∙∙│∙∙∙∙└───subtraction.txt ∙∙∙∙∙∙│ ∙∙∙∙∙∙└───Biology ∙∙∙∙∙∙∙∙∙∙∙├───nervousSystem.txt ∙∙∙∙∙∙∙∙∙∙∙└───skeletalSystem.txt .
Referenced by Luthetus.Ide.Tests.Basis.TreeViewImplementations.Models.TreeViewAbsolutePathTests.Constructor, Luthetus.Ide.Tests.Basis.TreeViewImplementations.Models.TreeViewGitFileTests.Constructor, Luthetus.Ide.Tests.Basis.TreeViewImplementations.Models.TreeViewMarkupStringTests.Constructor, Luthetus.Ide.Tests.Basis.TreeViewImplementations.Models.TreeViewSpinnerTests.Constructor.
static void Luthetus.Ide.Tests.Basis.IdeTestBase.WriteToInMemoryFileSystem(InMemoryEnvironmentProvider inMemoryEnvironmentProvider, InMemoryFileSystemProvider inMemoryFileSystemProvider)