Luthetus::CompilerServices::CSharp::BinderCase::CSharpBinder
readonly Dictionary<ResourceUri, IBinderSession> Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder._binderSessionMap
readonly Dictionary<string, SymbolDefinition> Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder._symbolDefinitions
The key for _symbolDefinitions is calculated by ISymbol.GetSymbolDefinitionId.
readonly Dictionary<string, NamespaceGroupNode> Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder._namespaceGroupNodeMap
readonly Dictionary<NamespaceAndTypeIdentifiers, TypeDefinitionNode> Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder._allTypeDefinitions
All of the type definitions should be maintainted in this dictionary as they are found via parsing. Then, when one types an ambiguous identifier, perhaps they wanted a type, and a lookup in this map can be done, and a using statement inserted for the user if they decide to use that autocomplete option.
readonly IScope Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder._globalScope
readonly NamespaceStatementNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder._topLevelNamespaceStatementNode
ImmutableDictionary<string, NamespaceGroupNode> Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.NamespaceGroupNodes
ImmutableArray<ISymbol> Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.Symbols
Dictionary<string, SymbolDefinition> Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.SymbolDefinitions
ImmutableDictionary<NamespaceAndTypeIdentifiers, TypeDefinitionNode> Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AllTypeDefinitions
ImmutableArray<TextEditorDiagnostic> Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.DiagnosticsList
ImmutableArray<ITextEditorSymbol> IBinder. Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.SymbolsList
IExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeToken(IExpressionNode expressionPrimary, ISyntaxToken token, IParserModel model)
Returns the new primary expression which will be the passed in 'expressionPrimary' if the parameters were not mergeable.
References Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AmbiguousIdentifierMergeToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.BadExpressionNode, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BadMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BinaryMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.CommaSeparatedMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ConstructorInvocationMergeToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.EmptyExpressionNode.Empty, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.EmptyExpressionNode.EmptyFollowsMemberAccessToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.EmptyMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ExplicitCastMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ForceDecisionAmbiguousIdentifier, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.FunctionArgumentsListingMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.FunctionInvocationMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.FunctionParametersListingMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GenericParametersListingMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.LambdaMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.LiteralMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ParenthesizedMergeToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntax.SyntaxKind, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ToTypeClause, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TypeClauseMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.VariableAssignmentMergeToken, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Void.
IExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeExpression(IExpressionNode expressionPrimary, IExpressionNode expressionSecondary, IParserModel model)
Returns the new primary expression which will be the passed in 'expressionPrimary' if the parameters were not mergeable.
References Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AmbiguousIdentifierMergeExpression, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.BadExpressionNode, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BadMergeExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.CommaSeparatedMergeExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ConstructorInvocationMergeExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.FunctionArgumentsListingMergeExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.FunctionInvocationMergeExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.FunctionParametersListingMergeExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GenericParametersListingMergeExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.LambdaMergeExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ParenthesizedMergeExpression, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntax.SyntaxKind, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ToTypeClause, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TypeClauseMergeExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.VariableAssignmentMergeExpression, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Void.
IExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AmbiguousIdentifierMergeToken(AmbiguousIdentifierExpressionNode ambiguousIdentifierExpressionNode, ISyntaxToken token, IParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.BadExpressionNode, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindFunctionInvocationNode, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IParserModel.DiagnosticBag, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.EmptyExpressionNode.Empty, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.ExpressionList, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IParserModel.ExpressionList, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ForceDecisionAmbiguousIdentifier, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.FunctionInvocationNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.FunctionParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.AmbiguousIdentifierExpressionNode.GenericParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.GenericParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.LambdaExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportTodoException, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode.SetCloseAngleBracketToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.AmbiguousIdentifierExpressionNode.SetGenericParametersListingNode, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.SetLambdaExpressionNodeVariableDeclarationNodeList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntax.SyntaxKind, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.AmbiguousIdentifierExpressionNode.Token, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IParserModel.TokenWalker, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ToTypeClause, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.VariableAssignmentExpressionNode, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Void, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.WithExpressionNode.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeToken.
IExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AmbiguousIdentifierMergeExpression(AmbiguousIdentifierExpressionNode ambiguousIdentifierExpressionNode, IExpressionNode expressionSecondary, IParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.BadExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode.CloseAngleBracketToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.CloseAngleBracketToken.ConstructorWasInvoked, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.AmbiguousIdentifierExpressionNode.GenericParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ToTypeClause, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Void.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeExpression.
IExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ForceDecisionAmbiguousIdentifier(IExpressionNode expressionPrimary, AmbiguousIdentifierExpressionNode ambiguousIdentifierExpressionNode, IParserModel model, bool forceVariableReferenceNode=false)
References Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IParserModel.BinderSession, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindTypeClauseNode, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ConstructAndBindVariableReferenceNode, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinderSession.CurrentScopeIndexKey, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.AmbiguousIdentifierExpressionNode.FollowsMemberAccessToken, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinderSession.ResourceUri, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntax.SyntaxKind, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntaxToken.TextSpan, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.AmbiguousIdentifierExpressionNode.Token, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryGetTypeDefinitionHierarchically, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryGetVariableDeclarationHierarchically.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AmbiguousIdentifierMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ConstructorInvocationMergeExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.EmptyMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.FunctionArgumentsListingMergeExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.FunctionInvocationMergeExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.FunctionParametersListingMergeExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ParenthesizedMergeExpression.
IExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BadMergeToken(BadExpressionNode badExpressionNode, ISyntaxToken token, IParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.BadExpressionNode.SyntaxList.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeToken.
IExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BadMergeExpression(BadExpressionNode badExpressionNode, IExpressionNode expressionSecondary, IParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.BadExpressionNode.SyntaxList.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeExpression.
IExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BinaryMergeToken(BinaryExpressionNode binaryExpressionNode, ISyntaxToken token, IParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.BadExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.BinaryExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.BinaryOperatorNode, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Bool, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Char, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.EmptyExpressionNode, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Int, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.BinaryExpressionNode.LeftExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.LiteralExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.BinaryExpressionNode.ResultTypeClauseNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.IExpressionNode.ResultTypeClauseNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.BinaryExpressionNode.RightExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.BinaryExpressionNode.SetRightExpressionNode, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.String, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntax.SyntaxKind, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntaxToken.TextSpan, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ToTypeClause, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.TypeIdentifierToken, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Void.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeToken.
IExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.CommaSeparatedMergeToken(CommaSeparatedExpressionNode commaSeparatedExpressionNode, ISyntaxToken token, IParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.BadExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.CommaSeparatedExpressionNode.CloseParenthesisToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.CloseParenthesisToken.ConstructorWasInvoked, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.EmptyExpressionNode.Empty, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IParserModel.ExpressionList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntax.SyntaxKind, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ToTypeClause, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Void.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeToken.
IExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.CommaSeparatedMergeExpression(CommaSeparatedExpressionNode commaSeparatedExpressionNode, IExpressionNode expressionSecondary, IParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.CommaSeparatedExpressionNode.AddInnerExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.BadExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IParserModel.TokenWalker, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ToTypeClause, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Void.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeExpression.
IExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ConstructorInvocationMergeToken(ConstructorInvocationExpressionNode constructorInvocationExpressionNode, ISyntaxToken token, IParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.BadExpressionNode, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindTypeClauseNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.ConstructorInvocationStageKind, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.EmptyExpressionNode.Empty, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IParserModel.ExpressionList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.FunctionParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.FunctionParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.GenericParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.GenericParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ObjectInitializationParametersListingNode.ObjectInitializationParameterEntryNodeList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.ObjectInitializationParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ObjectInitializationParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.ResultTypeClauseNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode.SetCloseAngleBracketToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ObjectInitializationParametersListingNode.SetCloseBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionParametersListingNode.SetCloseParenthesisToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.SetFunctionParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.SetGenericParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.SetObjectInitializationParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.SetTypeClauseNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntax.SyntaxKind, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ToTypeClause, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.TypeClauseNode, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Void.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeToken.
IExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ConstructorInvocationMergeExpression(ConstructorInvocationExpressionNode constructorInvocationExpressionNode, IExpressionNode expressionSecondary, IParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.BadExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.ConstructorInvocationStageKind, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.EqualsToken.ConstructorWasInvoked, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.IdentifierToken.ConstructorWasInvoked, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.EmptyExpressionNode.Empty, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ObjectInitializationParameterEntryNode.EqualsToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ObjectInitializationParameterEntryNode.ExpressionNode, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ForceDecisionAmbiguousIdentifier, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.FunctionParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.GenericParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ObjectInitializationParameterEntryNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ObjectInitializationParametersListingNode.ObjectInitializationParameterEntryNodeList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.ObjectInitializationParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ObjectInitializationParameterEntryNode.PropertyIdentifierToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorInvocationExpressionNode.ResultTypeClauseNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntax.SyntaxKind, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ToTypeClause, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Void.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeExpression.
IExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.EmptyMergeToken(EmptyExpressionNode emptyExpressionNode, ISyntaxToken token, IParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.AmbiguousIdentifierExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.BadExpressionNode, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindStringInterpolationExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindStringVerbatimExpression, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Bool, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Char, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ConstructorInvocationExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.EmptyExpressionNode.Empty, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.ExpressionList, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IParserModel.ExpressionList, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ForceDecisionAmbiguousIdentifier, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.GenericParametersListingNode, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Int, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.LambdaExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.LiteralExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ParenthesizedExpressionNode, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.String, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntax.SyntaxKind, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IParserModel.TokenWalker, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ToTypeClause, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IParserModel.TryParseExpressionSyntaxKindList, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Void.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeToken.
IExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ExplicitCastMergeToken(ExplicitCastNode explicitCastNode, ISyntaxToken token, IParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.AmbiguousIdentifierExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.BadExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ExplicitCastNode.SetCloseParenthesisToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntax.SyntaxKind, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ToTypeClause, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Void.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ParenthesizedMergeToken.
IExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GenericParametersListingMergeToken(GenericParametersListingNode genericParametersListingNode, ISyntaxToken token, IParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.BadExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.EmptyExpressionNode.Empty, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IParserModel.ExpressionList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntax.SyntaxKind, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ToTypeClause, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Void.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeToken.
IExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GenericParametersListingMergeExpression(GenericParametersListingNode genericParametersListingNode, IExpressionNode expressionSecondary, IParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.BadExpressionNode, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindTypeClauseNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.GenericParameterEntryNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode.GenericParameterEntryNodeList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntax.SyntaxKind, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ToTypeClause, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.TypeClauseNode, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Void.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeExpression.
IExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.FunctionParametersListingMergeToken(FunctionParametersListingNode functionParametersListingNode, ISyntaxToken token, IParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.BadExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.EmptyExpressionNode.Empty, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IParserModel.ExpressionList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntax.SyntaxKind, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ToTypeClause, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Void.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeToken.
IExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.FunctionParametersListingMergeExpression(FunctionParametersListingNode functionParametersListingNode, IExpressionNode expressionSecondary, IParserModel model)
References Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ForceDecisionAmbiguousIdentifier, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.FunctionParameterEntryNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionParametersListingNode.FunctionParameterEntryNodeList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntax.SyntaxKind.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeExpression.
IExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.FunctionArgumentsListingMergeToken(FunctionArgumentsListingNode functionArgumentsListingNode, ISyntaxToken token, IParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.BadExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.EmptyExpressionNode.Empty, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IParserModel.ExpressionList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntax.SyntaxKind, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ToTypeClause, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Void.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeToken.
IExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.FunctionArgumentsListingMergeExpression(FunctionArgumentsListingNode functionArgumentsListingNode, IExpressionNode expressionSecondary, IParserModel model)
References Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ForceDecisionAmbiguousIdentifier, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.FunctionArgumentEntryNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionArgumentsListingNode.FunctionArgumentEntryNodeList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntax.SyntaxKind.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeExpression.
IExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.LambdaMergeToken(LambdaExpressionNode lambdaExpressionNode, ISyntaxToken token, IParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.BadExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IParserModel.Binder, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.LambdaExpressionNode.CodeBlockNodeIsExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.CSharpBinder, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.EmptyExpressionNode.Empty, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.ExpressionList, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IParserModel.ExpressionList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.LambdaExpressionNode.HasReadParameters, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.LambdaSymbol, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntax.SyntaxKind, Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntaxToken.TextSpan, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.TokenWalker, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IParserModel.TokenWalker, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ToTypeClause, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Void.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeToken.
IExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.LambdaMergeExpression(LambdaExpressionNode lambdaExpressionNode, IExpressionNode expressionSecondary, IParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntax.SyntaxKind.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeExpression.
IExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.LiteralMergeToken(LiteralExpressionNode literalExpressionNode, ISyntaxToken token, IParserModel model)
I am not evaluating anything when parsing for the IDE, so for now I'm going to ignore the precedence, and just track the start and end of the expression more or less.
Reason for this being: object initialization and collection initialization currently will at times break the Parser for an entire file, and therefore they are much higher priority.
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.BadExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.BinaryExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.BinaryOperatorNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.LiteralExpressionNode.ResultTypeClauseNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntax.SyntaxKind, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ToTypeClause, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Void.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeToken.
IExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ParenthesizedMergeToken(ParenthesizedExpressionNode parenthesizedExpressionNode, ISyntaxToken token, IParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.BadExpressionNode, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ExplicitCastMergeToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ExplicitCastNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.InnerExpression, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.LambdaExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.OpenParenthesisToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.SetCloseParenthesisToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.SetLambdaExpressionNodeVariableDeclarationNodeList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntax.SyntaxKind, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IParserModel.TokenWalker, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ToTypeClause, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Void.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeToken.
IExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ParenthesizedMergeExpression(ParenthesizedExpressionNode parenthesizedExpressionNode, IExpressionNode expressionSecondary, IParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.BadExpressionNode, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindTypeClauseNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.CommaSeparatedExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ExplicitCastNode, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IParserModel.ExpressionList, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ForceDecisionAmbiguousIdentifier, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.InnerExpression, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.LambdaExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.OpenParenthesisToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ParenthesizedExpressionNode.SetInnerExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.SetLambdaExpressionNodeVariableDeclarationNodeList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntax.SyntaxKind, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IParserModel.TokenWalker, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ToTypeClause, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.TypeClauseNode, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Void.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeExpression.
IExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TypeClauseMergeToken(TypeClauseNode typeClauseNode, ISyntaxToken token, IParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.BadExpressionNode, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindFunctionInvocationNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.EmptyExpressionNode.Empty, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.ExpressionList, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IParserModel.ExpressionList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.FunctionInvocationNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.FunctionParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.GenericParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.GenericParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.HasQuestionMark, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode.SetCloseAngleBracketToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.SetGenericParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntax.SyntaxKind, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ToTypeClause, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.TypeIdentifierToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.VariableDeclarationNode, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Void.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeToken.
IExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TypeClauseMergeExpression(TypeClauseNode typeClauseNode, IExpressionNode expressionSecondary, IParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.BadExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericParametersListingNode.CloseAngleBracketToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.CloseAngleBracketToken.ConstructorWasInvoked, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.GenericParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntax.SyntaxKind, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ToTypeClause, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Void.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeExpression.
IExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.VariableAssignmentMergeToken(VariableAssignmentExpressionNode variableAssignmentNode, ISyntaxToken token, IParserModel model)
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeToken.
IExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.VariableAssignmentMergeExpression(VariableAssignmentExpressionNode variableAssignmentNode, IExpressionNode expressionSecondary, IParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.BadExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.EmptyExpressionNode.Empty, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.VariableAssignmentExpressionNode.ExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.VariableAssignmentExpressionNode.SetExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ToTypeClause, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Void.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeExpression.
IExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.FunctionInvocationMergeToken(FunctionInvocationNode functionInvocationNode, ISyntaxToken token, IParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.BadExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionInvocationNode.FunctionParametersListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionParametersListingNode.SetCloseParenthesisToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntax.SyntaxKind, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ToTypeClause, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Void.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeToken.
IExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.FunctionInvocationMergeExpression(FunctionInvocationNode functionInvocationNode, IExpressionNode expressionSecondary, IParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.BadExpressionNode, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ForceDecisionAmbiguousIdentifier, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntax.SyntaxKind, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ToTypeClause, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Void.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeExpression.
IExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.SetLambdaExpressionNodeVariableDeclarationNodeList(LambdaExpressionNode lambdaExpressionNode, IExpressionNode expressionNode, IParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.LambdaExpressionNode.AddVariableDeclarationNode, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindTypeClauseNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntax.SyntaxKind, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.TypeClauseNode.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AmbiguousIdentifierMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ParenthesizedMergeExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ParenthesizedMergeToken.
void Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ClearFromExpressionList(IExpressionNode expressionNode, IParserModel model)
A ParenthesizedExpressionNode expression will "become" a CommaSeparatedExpressionNode upon encounter a CommaToken within its parentheses.
An issue arises however, because the model.ExpressionList still says to "short circuit" when the CloseParenthesisToken is encountered, and to at this point make the ParenthesizedExpressionNode the primary expression. Well, the ParenthesizedExpressionNode should no longer exist, it was deemed to be more accurately described by a CommaSeparatedExpressionNode. So, this method will remove any entries in the model.ExpressionList that have the 'ParenthesizedExpressionNode' as the to-be primary expression.
References Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IParserModel.ExpressionList.
Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.CSharpBinder()
References Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.FinalizeBinderSession, Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.StartBinderSession.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.LambdaMergeToken.
IBinderSession Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.StartBinderSession(ResourceUri resourceUri)
FinalizeBinderSession
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.NamespaceGroupNode, Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.CSharpBinder.
void Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.FinalizeBinderSession(IBinderSession binderSession)
StartBinderSession
References Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.UpsertBinderSession.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.CSharpBinder.
LiteralExpressionNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindLiteralExpressionNode(LiteralExpressionNode literalExpressionNode, CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Char, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.DiagnosticBag, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Int, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.LiteralExpressionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.LiteralExpressionNode.LiteralSyntaxToken, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportTodoException, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.String, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntax.SyntaxKind, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntaxToken.TextSpan, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ToTypeClause, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Void.
BinaryOperatorNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindBinaryOperatorNode(IExpressionNode leftExpressionNode, ISyntaxToken operatorToken, IExpressionNode rightExpressionNode, CSharpParserModel parserModel)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.BinaryOperatorNode, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.DiagnosticBag, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Int, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportTodoException, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.IExpressionNode.ResultTypeClauseNode, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.String, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntax.SyntaxKind, Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ToTypeClause, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.ValueType, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Void.
void Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindStringInterpolationExpression(DollarSignToken dollarSignToken, CSharpParserModel model)
TODO: Construct a BoundStringInterpolationExpressionNode and identify the expressions within the string literal. For now I am just making the dollar sign the same color as a string literal.
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.StringInterpolationSymbol, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.DollarSignToken.TextSpan.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.EmptyMergeToken.
void Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindStringVerbatimExpression(AtToken atToken, CSharpParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.StringVerbatimSymbol, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.AtToken.TextSpan.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.EmptyMergeToken.
void Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindFunctionDefinitionNode(FunctionDefinitionNode functionDefinitionNode, CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.BinderSession, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionDefinitionNode.FunctionIdentifierToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.FunctionSymbol, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.IdentifierToken.TextSpan.
void Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindFunctionOptionalArgument(FunctionArgumentEntryNode functionArgumentEntryNode, CSharpParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.VariableDeclarationNode.TypeClauseNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionArgumentEntryNode.VariableDeclarationNode.
ReturnStatementNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindReturnStatementNode(KeywordToken keywordToken, IExpressionNode expressionNode)
TODO: Validate that the returned bound expression node has the same result type as the enclosing scope.
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ReturnStatementNode.
IfStatementNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindIfStatementNode(KeywordToken ifKeywordToken, IExpressionNode expressionNode)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.IfStatementNode.
void Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.SetCurrentNamespaceStatementNode(NamespaceStatementNode namespaceStatementNode, CSharpParserModel model)
void Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindNamespaceStatementNode(NamespaceStatementNode namespaceStatementNode, CSharpParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.NamespaceStatementNode.IdentifierToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.NamespaceGroupNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.NamespaceSymbol, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.IdentifierToken.TextSpan.
void Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindConstructorInvocationNode()
InheritanceStatementNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindInheritanceStatementNode(TypeClauseNode typeClauseNode, CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.DiagnosticBag, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.InheritanceStatementNode, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportTodoException, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntaxToken.TextSpan, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.TypeIdentifierToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.TypeSymbol.
void Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindVariableDeclarationNode(IVariableDeclarationNode variableDeclarationNode, CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.BinderSession, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.CreateVariableSymbol, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.IVariableDeclarationNode.IdentifierToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.IdentifierToken.TextSpan, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.IVariableDeclarationNode.VariableKind.
VariableReferenceNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ConstructAndBindVariableReferenceNode(IdentifierToken variableIdentifierToken, CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.BinderSession, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.CreateVariableSymbol, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.IdentifierToken.TextSpan, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ToTypeClause, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryGetVariableDeclarationHierarchically, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.Var, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.VariableDeclarationNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.VariableReferenceNode.VariableIdentifierToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.VariableReferenceNode.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ForceDecisionAmbiguousIdentifier.
void Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindVariableAssignmentExpressionNode(VariableAssignmentExpressionNode variableAssignmentExpressionNode, CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.BinderSession, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.CreateVariableSymbol, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.IdentifierToken.TextSpan, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryGetVariableDeclarationHierarchically, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.VariableAssignmentExpressionNode.VariableIdentifierToken.
void Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindConstructorDefinitionIdentifierToken(IdentifierToken identifierToken, CSharpParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ConstructorSymbol, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.IdentifierToken.TextSpan.
void Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindFunctionInvocationNode(FunctionInvocationNode functionInvocationNode, CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.BinderSession, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionInvocationNode.FunctionInvocationIdentifierToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.FunctionSymbol, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.IdentifierToken.TextSpan, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryGetFunctionHierarchically.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AmbiguousIdentifierMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TypeClauseMergeToken.
void Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindNamespaceReference(IdentifierToken namespaceIdentifierToken, CSharpParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.NamespaceSymbol, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.IdentifierToken.TextSpan.
void Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindTypeClauseNode(TypeClauseNode typeClauseNode, CSharpParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.SetValueType, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntax.SyntaxKind, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntaxToken.TextSpan, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Types.TypeDefinitionNodes, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeClauseNode.TypeIdentifierToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.TypeSymbol.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ConstructorInvocationMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ForceDecisionAmbiguousIdentifier, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GenericParametersListingMergeExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ParenthesizedMergeExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.SetLambdaExpressionNodeVariableDeclarationNodeList.
void Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindTypeIdentifier(IdentifierToken identifierToken, CSharpParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.IdentifierToken.SyntaxKind, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.IdentifierToken.TextSpan, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.TypeSymbol.
void Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindUsingStatementNode(UsingStatementNode usingStatementNode, CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.BinderSession, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.UsingStatementNode.NamespaceIdentifier, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.NamespaceSymbol, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.IdentifierToken.TextSpan.
AttributeNode Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindAttributeNode(OpenSquareBracketToken openSquareBracketToken, List< ISyntaxToken > innerTokens, CloseSquareBracketToken closeSquareBracketToken, CSharpParserModel model)
TODO: Correctly implement this method. For now going to skip until the attribute closing square bracket.
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.AttributeNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.OpenSquareBracketToken.TextSpan, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.TypeSymbol.
void Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.OpenScope(ICodeBlockOwner codeBlockOwner, TypeClauseNode? scopeReturnTypeClauseNode, TextEditorTextSpan textSpan, CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.BinderSession, Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
void Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AddNamespaceToCurrentScope(string namespaceString, CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.BinderSession.
void Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.CloseScope(TextEditorTextSpan textSpan, CSharpParserModel model)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.Binder, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.BinderSession, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.CurrentCodeBlockBuilder, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.NamespaceStatementNode.SyntaxKind, Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
void Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindTypeDefinitionNode(TypeDefinitionNode typeDefinitionNode, CSharpParserModel model, bool shouldOverwrite=false)
References Luthetus.CompilerServices.CSharp.ParserCase.CSharpParserModel.BinderSession, Luthetus.CompilerServices.CSharp.BinderCase.NamespaceAndTypeIdentifiers, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.IdentifierToken.TextSpan, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.TypeIdentifierToken.
void Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.CreateVariableSymbol(IdentifierToken identifierToken, VariableKind variableKind, CSharpParserModel model)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.FieldSymbol, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.PropertySymbol, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.IdentifierToken.TextSpan, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.VariableSymbol.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindVariableAssignmentExpressionNode, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindVariableDeclarationNode, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ConstructAndBindVariableReferenceNode.
void Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ClearStateByResourceUri(ResourceUri resourceUri)
Do not invoke this when re-parsing the same file.
Instead, only invoke this when the file is deleted, and should no longer be included in the binder.
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.NamespaceGroupNode, Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
bool Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryGetFunctionHierarchically(IParserModel? parserModel, ResourceUri resourceUri, int initialScopeIndexKey, string identifierText, out FunctionDefinitionNode? functionDefinitionNode)
Search hierarchically through all the scopes, starting at the initialScope. If a match is found, then set the out parameter to it and return true. If none of the searched scopes contained a match then set the out parameter to null and return false.
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindFunctionInvocationNode, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GetDefinition.
bool Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryGetTypeDefinitionHierarchically(IParserModel? parserModel, ResourceUri resourceUri, int initialScopeIndexKey, string identifierText, out TypeDefinitionNode? typeDefinitionNode)
Search hierarchically through all the scopes, starting at the initialScope. If a match is found, then set the out parameter to it and return true. If none of the searched scopes contained a match then set the out parameter to null and return false.
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ForceDecisionAmbiguousIdentifier, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GetDefinition.
bool Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryGetVariableDeclarationHierarchically(IParserModel? parserModel, ResourceUri resourceUri, int initialScopeIndexKey, string identifierText, out IVariableDeclarationNode? variableDeclarationStatementNode)
Search hierarchically through all the scopes, starting at the _currentScope. If a match is found, then set the out parameter to it and return true. If none of the searched scopes contained a match then set the out parameter to null and return false.
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindVariableAssignmentExpressionNode, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ConstructAndBindVariableReferenceNode, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ForceDecisionAmbiguousIdentifier, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GetDefinition.
IScope? Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GetScope(IParserModel? model, TextEditorTextSpan textSpan)
References Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
IScope? Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GetScopeByPositionIndex(IParserModel? model, ResourceUri resourceUri, int positionIndex)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
IScope? Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GetScopeByScopeIndexKey(IParserModel? model, ResourceUri resourceUri, int scopeIndexKey)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
IScope?[] Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GetScopeList(IParserModel? model, ResourceUri resourceUri)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
bool Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryGetBinderSession(IParserModel? parserModel, ResourceUri resourceUri, out IBinderSession binderSession)
If the resourceUri is the in progress BinderSession's ResourceUri, then the in progress instance should be returned via the out variable.
TODO: This is quite confusingly written at the moment.
References Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IParserModel.BinderSession, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinderSession.ResourceUri, Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
void Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.UpsertBinderSession(IBinderSession binderSession)
References Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinderSession.ResourceUri.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.FinalizeBinderSession.
bool Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.RemoveBinderSession(ResourceUri resourceUri)
Returns true if the entry was removed.
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
TypeDefinitionNode[] Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GetTypeDefinitionNodesByScope(IParserModel? model, ResourceUri resourceUri, int scopeIndexKey)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
bool Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryGetTypeDefinitionNodeByScope(IParserModel? model, ResourceUri resourceUri, int scopeIndexKey, string typeIdentifierText, out TypeDefinitionNode typeDefinitionNode)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri, Luthetus.TextEditor.RazorLib.CompilerServices.ScopeKeyAndIdentifierText.
bool Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryAddTypeDefinitionNodeByScope(IParserModel? model, ResourceUri resourceUri, int scopeIndexKey, string typeIdentifierText, TypeDefinitionNode typeDefinitionNode)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri, Luthetus.TextEditor.RazorLib.CompilerServices.ScopeKeyAndIdentifierText.
void Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.SetTypeDefinitionNodeByScope(IParserModel? model, ResourceUri resourceUri, int scopeIndexKey, string typeIdentifierText, TypeDefinitionNode typeDefinitionNode)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri, Luthetus.TextEditor.RazorLib.CompilerServices.ScopeKeyAndIdentifierText.
FunctionDefinitionNode[] Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GetFunctionDefinitionNodesByScope(IParserModel? model, ResourceUri resourceUri, int scopeIndexKey)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
bool Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryGetFunctionDefinitionNodeByScope(IParserModel? model, ResourceUri resourceUri, int scopeIndexKey, string functionIdentifierText, out FunctionDefinitionNode functionDefinitionNode)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri, Luthetus.TextEditor.RazorLib.CompilerServices.ScopeKeyAndIdentifierText.
bool Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryAddFunctionDefinitionNodeByScope(IParserModel? model, ResourceUri resourceUri, int scopeIndexKey, string functionIdentifierText, FunctionDefinitionNode functionDefinitionNode)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri, Luthetus.TextEditor.RazorLib.CompilerServices.ScopeKeyAndIdentifierText.
void Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.SetFunctionDefinitionNodeByScope(IParserModel? model, ResourceUri resourceUri, int scopeIndexKey, string functionIdentifierText, FunctionDefinitionNode functionDefinitionNode)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri, Luthetus.TextEditor.RazorLib.CompilerServices.ScopeKeyAndIdentifierText.
IVariableDeclarationNode[] Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GetVariableDeclarationNodesByScope(IParserModel? model, ResourceUri resourceUri, int scopeIndexKey)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
bool Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryGetVariableDeclarationNodeByScope(IParserModel? model, ResourceUri resourceUri, int scopeIndexKey, string variableIdentifierText, out IVariableDeclarationNode variableDeclarationNode)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri, Luthetus.TextEditor.RazorLib.CompilerServices.ScopeKeyAndIdentifierText.
bool Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryAddVariableDeclarationNodeByScope(IParserModel? model, ResourceUri resourceUri, int scopeIndexKey, string variableIdentifierText, IVariableDeclarationNode variableDeclarationNode)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri, Luthetus.TextEditor.RazorLib.CompilerServices.ScopeKeyAndIdentifierText.
void Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.SetVariableDeclarationNodeByScope(IParserModel? model, ResourceUri resourceUri, int scopeIndexKey, string variableIdentifierText, IVariableDeclarationNode variableDeclarationNode)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri, Luthetus.TextEditor.RazorLib.CompilerServices.ScopeKeyAndIdentifierText.
TypeClauseNode? Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GetReturnTypeClauseNodeByScope(IParserModel? model, ResourceUri resourceUri, int scopeIndexKey)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
bool Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryAddReturnTypeClauseNodeByScope(IParserModel? model, ResourceUri resourceUri, int scopeIndexKey, TypeClauseNode typeClauseNode)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
TextEditorTextSpan? Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GetDefinition(IParserModel? model, TextEditorTextSpan textSpan, ICompilerServiceResource compilerServiceResource)
References Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.ICompilerServiceResource.CompilationUnit, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.ICompilerServiceResource.GetSymbols, Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryGetFunctionHierarchically, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryGetTypeDefinitionHierarchically, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryGetVariableDeclarationHierarchically.
ISyntaxNode? Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GetSyntaxNode(int positionIndex, CompilationUnit compilationUnit)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.ISyntaxNode.GetChildList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.CompilationUnit.RootCodeBlockNode.
void IBinder. Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindFunctionOptionalArgument(FunctionArgumentEntryNode functionArgumentEntryNode, IParserModel model)
void IBinder. Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindVariableDeclarationNode(IVariableDeclarationNode variableDeclarationNode, IParserModel model)
void IBinder. Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AddNamespaceToCurrentScope(string namespaceString, IParserModel model)
void Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AddSymbolDefinition(ISymbol symbol, CSharpParserModel model)
This method will handle the SymbolDefinition, but also invoke AddSymbolReference because each definition is being treated as a reference itself.
void Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AddSymbolReference(ISymbol symbol, CSharpParserModel model)
IScope? IBinder. Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GetScope(TextEditorTextSpan textSpan)
IScope? IBinder. Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GetScopeByPositionIndex(ResourceUri resourceUri, int positionIndex)
IScope? IBinder. Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GetScopeByScopeIndexKey(ResourceUri resourceUri, int scopeIndexKey)
IScope?[] IBinder. Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GetScopeList(ResourceUri resourceUri)
bool IBinder. Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryGetBinderSession(ResourceUri resourceUri, out IBinderSession binderSession)
TypeDefinitionNode[] IBinder. Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GetTypeDefinitionNodesByScope(ResourceUri resourceUri, int scopeIndexKey)
bool IBinder. Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryGetTypeDefinitionNodeByScope(ResourceUri resourceUri, int scopeIndexKey, string typeIdentifierText, out TypeDefinitionNode typeDefinitionNode)
bool IBinder. Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryAddTypeDefinitionNodeByScope(ResourceUri resourceUri, int scopeIndexKey, string typeIdentifierText, TypeDefinitionNode typeDefinitionNode)
void IBinder. Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.SetTypeDefinitionNodeByScope(ResourceUri resourceUri, int scopeIndexKey, string typeIdentifierText, TypeDefinitionNode typeDefinitionNode)
FunctionDefinitionNode[] IBinder. Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GetFunctionDefinitionNodesByScope(ResourceUri resourceUri, int scopeIndexKey)
bool IBinder. Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryGetFunctionDefinitionNodeByScope(ResourceUri resourceUri, int scopeIndexKey, string functionIdentifierText, out FunctionDefinitionNode functionDefinitionNode)
bool IBinder. Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryAddFunctionDefinitionNodeByScope(ResourceUri resourceUri, int scopeIndexKey, string functionIdentifierText, FunctionDefinitionNode functionDefinitionNode)
void IBinder. Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.SetFunctionDefinitionNodeByScope(ResourceUri resourceUri, int scopeIndexKey, string functionIdentifierText, FunctionDefinitionNode functionDefinitionNode)
IVariableDeclarationNode[] IBinder. Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GetVariableDeclarationNodesByScope(ResourceUri resourceUri, int scopeIndexKey)
bool IBinder. Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryGetVariableDeclarationNodeByScope(ResourceUri resourceUri, int scopeIndexKey, string variableIdentifierText, out IVariableDeclarationNode variableDeclarationNode)
bool IBinder. Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryAddVariableDeclarationNodeByScope(ResourceUri resourceUri, int scopeIndexKey, string variableIdentifierText, IVariableDeclarationNode variableDeclarationNode)
void IBinder. Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.SetVariableDeclarationNodeByScope(ResourceUri resourceUri, int scopeIndexKey, string variableIdentifierText, IVariableDeclarationNode variableDeclarationNode)
TypeClauseNode? IBinder. Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GetReturnTypeClauseNodeByScope(ResourceUri resourceUri, int scopeIndexKey)
bool IBinder. Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryAddReturnTypeClauseNodeByScope(ResourceUri resourceUri, int scopeIndexKey, TypeClauseNode typeClauseNode)
TextEditorTextSpan? IBinder. Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GetDefinition(TextEditorTextSpan textSpan, ICompilerServiceResource compilerServiceResource)