Luthetus::TextEditor::Tests::Basis::TextEditors::Models::TextEditorModelApiTests
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.Constructor()
TextEditorModelApi(ITextEditorService, IDecorationMapperRegistry, ICompilerServiceRegistry, IBackgroundTaskService, IDispatcher)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.dispatcher, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.UndoEdit()
TextEditorModelApi.UndoEdit(ResourceUri)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.dispatcher, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorSelection, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.SetUsingRowEndingKind()
TextEditorModelApi.SetUsingLineEndKind(ResourceUri, LineEndKind)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.dispatcher, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.SetResourceData()
TextEditorModelApi.SetResourceData(ResourceUri, DateTime)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.dispatcher, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.Reload()
TextEditorModelApi.Reload(ResourceUri, string, DateTime)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.dispatcher, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.GetAllText, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.RegisterCustom()
TextEditorModelApi.RegisterCustom(TextEditorModel)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.dispatcher, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.ICompilerServiceRegistry.GetCompilerService, Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.RegisterTemplated()
TextEditorModelApi.RegisterTemplated(string, ResourceUri, DateTime, string, string?)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.dispatcher, Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.RedoEditEnqueue()
TextEditorModelApi.RedoEdit(ResourceUri)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.dispatcher, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorSelection, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.InsertTextEnqueue()
TextEditorModelApi.InsertText(ResourceUri, Key<TextEditorViewModel>, string, CancellationToken)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.dispatcher, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorSelection, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.HandleKeyboardEventEnqueue()
TextEditorModelApi.HandleKeyboardEvent(ResourceUri, Key<TextEditorViewModel>, KeymapArgs, CancellationToken)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.dispatcher, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorSelection, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.GetViewModelsOrEmpty()
TextEditorModelApi.GetViewModelsOrEmpty(ResourceUri)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.Category, Luthetus.TextEditor.RazorLib.TextEditors.Models.dispatcher, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.GetAllText()
TextEditorModelApi.GetAllText(ResourceUri)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.dispatcher, Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
Referenced by Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.DeleteTextByMotionEnqueue_Backspace, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.DeleteTextByRangeEnqueue, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.Reload.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.GetOrDefault()
TextEditorModelApi.GetOrDefault(ResourceUri)
References Luthetus.TextEditor.Tests.Basis.TestsHelper.InitializeTextEditorServicesTestsHelper, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.Dispose()
TextEditorModelApi.Dispose(ResourceUri)
References Luthetus.TextEditor.Tests.Basis.TestsHelper.InitializeTextEditorServicesTestsHelper, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.DeleteTextByRangeEnqueue()
TextEditorModelApi.DeleteTextByRange(ResourceUri, Key<TextEditorViewModel>, int, CancellationToken)
References Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.GetAllText, Luthetus.TextEditor.Tests.Basis.TestsHelper.InitializeTextEditorServicesTestsHelper, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorSelection, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.DeleteTextByMotionEnqueue_Backspace()
TextEditorModelApi.DeleteTextByMotion(ResourceUri, Key<TextEditorViewModel>, MotionKind, CancellationToken)
References Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.GetAllText, Luthetus.TextEditor.Tests.Basis.TestsHelper.InitializeTextEditorServicesTestsHelper, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorSelection, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.RegisterPresentationModel()
TextEditorModelApi.AddPresentationModel(ResourceUri, TextEditorPresentationModel)
References Luthetus.TextEditor.Tests.Basis.TestsHelper.InitializeTextEditorServicesTestsHelper, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.InitializeTextEditorModelApiTests(out TextEditorModel model, out TextEditorViewModel viewModel, out ITextEditorService textEditorService, out IState< TextEditorOptionsState > textEditorOptionsState, out IDispatcher dispatcher, out ServiceProvider serviceProvider)