Luthetus::TextEditor::RazorLib::CompilerServices::Syntax::Nodes::GenericArgumentsListingNode
ISyntax [] Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericArgumentsListingNode._childList
bool Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericArgumentsListingNode._childListIsDirty
OpenAngleBracketToken Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericArgumentsListingNode.OpenAngleBracketToken
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericArgumentsListingNode.GenericArgumentsListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericArgumentsListingNode.GetChildList.
ImmutableArray<GenericArgumentEntryNode> Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericArgumentsListingNode.GenericArgumentEntryNodeList
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericArgumentsListingNode.GenericArgumentsListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericArgumentsListingNode.GetChildList.
CloseAngleBracketToken Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericArgumentsListingNode.CloseAngleBracketToken
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericArgumentsListingNode.GenericArgumentsListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericArgumentsListingNode.GetChildList.
bool Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericArgumentsListingNode.IsFabricated
IsFabricated refers to when the ParserSession expected a node to be valid, but it wasn't. For example, a function invocation on an undefined function will construct a BoundFunctionInvocationNode with IsFabricated set to true.
SyntaxKind Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericArgumentsListingNode.SyntaxKind
Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericArgumentsListingNode.GenericArgumentsListingNode(OpenAngleBracketToken openAngleBracketToken, ImmutableArray< GenericArgumentEntryNode > genericArgumentEntryNodeList, CloseAngleBracketToken closeAngleBracketToken)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericArgumentsListingNode.CloseAngleBracketToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericArgumentsListingNode.GenericArgumentEntryNodeList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericArgumentsListingNode.OpenAngleBracketToken.
Referenced by Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.ConstructorDefinitionNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.FunctionDefinitionNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.TypeDefinitionNodeTests.Constructor.
ISyntax[] Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericArgumentsListingNode.GetChildList()
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericArgumentsListingNode.CloseAngleBracketToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericArgumentsListingNode.GenericArgumentEntryNodeList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.GenericArgumentsListingNode.OpenAngleBracketToken.