Luthetus::TextEditor::RazorLib::Groups::States::TextEditorGroupState
ImmutableList<TextEditorGroup> Luthetus.TextEditor.RazorLib.Groups.States.TextEditorGroupState.GroupList
Referenced by Luthetus.TextEditor.RazorLib.Groups.States.TextEditorGroupState.Reducer.ReduceAddViewModelToGroupAction, Luthetus.TextEditor.RazorLib.Groups.States.TextEditorGroupState.Reducer.ReduceDisposeAction, Luthetus.TextEditor.RazorLib.Groups.States.TextEditorGroupState.Reducer.ReduceRegisterAction, Luthetus.TextEditor.RazorLib.Groups.States.TextEditorGroupState.Reducer.ReduceRemoveViewModelFromGroupAction, Luthetus.TextEditor.RazorLib.Groups.States.TextEditorGroupState.Reducer.ReduceSetActiveViewModelOfGroupAction, Luthetus.TextEditor.RazorLib.Groups.States.TextEditorGroupState.TextEditorGroupState.
record Luthetus.TextEditor.RazorLib.Groups.States.TextEditorGroupState.RegisterAction(TextEditorGroup Group)
Referenced by Luthetus.TextEditor.RazorLib.Groups.States.TextEditorGroupState.Reducer.ReduceRegisterAction, Luthetus.TextEditor.RazorLib.Groups.Models.TextEditorGroupApi.Register.
record Luthetus.TextEditor.RazorLib.Groups.States.TextEditorGroupState.DisposeAction(Key< TextEditorGroup > GroupKey)
Referenced by Luthetus.TextEditor.RazorLib.Groups.Models.TextEditorGroupApi.Dispose, Luthetus.TextEditor.RazorLib.Groups.States.TextEditorGroupState.Reducer.ReduceDisposeAction.
record Luthetus.TextEditor.RazorLib.Groups.States.TextEditorGroupState.AddViewModelToGroupAction(Key< TextEditorGroup > GroupKey, Key< TextEditorViewModel > ViewModelKey)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ViewModelKey.
Referenced by Luthetus.TextEditor.RazorLib.Groups.Models.TextEditorGroupApi.AddViewModel, Luthetus.TextEditor.RazorLib.Groups.States.TextEditorGroupState.Effector.HandleAddViewModelToGroupAction, Luthetus.TextEditor.RazorLib.Groups.States.TextEditorGroupState.Reducer.ReduceAddViewModelToGroupAction.
record Luthetus.TextEditor.RazorLib.Groups.States.TextEditorGroupState.RemoveViewModelFromGroupAction(Key< TextEditorGroup > GroupKey, Key< TextEditorViewModel > ViewModelKey)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ViewModelKey.
Referenced by Luthetus.TextEditor.RazorLib.Groups.States.TextEditorGroupState.Effector.HandleRemoveViewModelFromGroupAction, Luthetus.TextEditor.RazorLib.Groups.States.TextEditorGroupState.Reducer.ReduceRemoveViewModelFromGroupAction, Luthetus.TextEditor.RazorLib.Groups.Models.TextEditorGroupApi.RemoveViewModel.
record Luthetus.TextEditor.RazorLib.Groups.States.TextEditorGroupState.SetActiveViewModelOfGroupAction(Key< TextEditorGroup > GroupKey, Key< TextEditorViewModel > ViewModelKey)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ViewModelKey.
Referenced by Luthetus.TextEditor.RazorLib.Groups.States.TextEditorGroupState.Effector.HandleSetActiveViewModelOfGroupAction, Luthetus.TextEditor.RazorLib.Groups.States.TextEditorGroupState.Reducer.ReduceSetActiveViewModelOfGroupAction, Luthetus.TextEditor.RazorLib.Groups.Models.TextEditorGroupApi.SetActiveViewModel.
Luthetus.TextEditor.RazorLib.Groups.States.TextEditorGroupState.TextEditorGroupState()
References Luthetus.TextEditor.RazorLib.Groups.States.TextEditorGroupState.GroupList.
Referenced by Luthetus.TextEditor.RazorLib.Groups.States.TextEditorGroupState.Reducer.ReduceAddViewModelToGroupAction, Luthetus.TextEditor.RazorLib.Groups.States.TextEditorGroupState.Reducer.ReduceDisposeAction, Luthetus.TextEditor.RazorLib.Groups.States.TextEditorGroupState.Reducer.ReduceRegisterAction, Luthetus.TextEditor.RazorLib.Groups.States.TextEditorGroupState.Reducer.ReduceRemoveViewModelFromGroupAction, Luthetus.TextEditor.RazorLib.Groups.States.TextEditorGroupState.Reducer.ReduceSetActiveViewModelOfGroupAction.