Luthetus::TextEditor::Tests::Basis::TextEditors::Models::TextEditorViewModelApiTests
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.Constructor()
TextEditorViewModelApi(ITextEditorService, IBackgroundTaskService, IState<TextEditorViewModelState>, IState<TextEditorModelState>, IJSRuntime, IDispatcher, IDialogService)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.CalculateVirtualizationResult()
TextEditorViewModelApi.CalculateVirtualizationResult(ResourceUri, Key<TextEditorViewModel>, CancellationToken)
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.CursorMovePageTop()
TextEditorViewModelApi.CursorMovePageTop(ResourceUri, Key<TextEditorViewModel>)
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.CursorMovePageTopUnsafe()
TextEditorViewModelApi.CursorMovePageTopUnsafe(ResourceUri, Key<TextEditorViewModel>, TextEditorCursorModifier)
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.CursorMovePageBottom()
TextEditorViewModelApi.CursorMovePageBottom(ResourceUri, Key<TextEditorViewModel>)
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.CursorMovePageBottomUnsafe()
TextEditorViewModelApi.CursorMovePageBottomUnsafe(ResourceUri, Key<TextEditorViewModel>, TextEditorCursorModifier)
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.Dispose()
TextEditorViewModelApi.Dispose(Key<TextEditorViewModel>)
References Luthetus.TextEditor.Tests.Basis.TestsHelper.InitializeTextEditorServicesTestsHelper, Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.inModel, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.FocusPrimaryCursor()
TextEditorViewModelApi.FocusPrimaryCursor(string)
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.GetTextEditorMeasurementsAsync()
TextEditorViewModelApi.GetTextEditorMeasurementsAsync(string)
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.GetModelOrDefault()
TextEditorViewModelApi.GetModelOrDefault(Key<TextEditorViewModel>)
References Luthetus.TextEditor.Tests.Basis.TestsHelper.InitializeTextEditorServicesTestsHelper, Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.inModel, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.GetAllText()
TextEditorViewModelApi.GetAllText(Key<TextEditorViewModel>)
References Luthetus.TextEditor.Tests.Basis.TestsHelper.InitializeTextEditorServicesTestsHelper, Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.inModel, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.GetOrDefault()
TextEditorViewModelApi.GetOrDefault(Key<TextEditorViewModel>)
References Luthetus.TextEditor.Tests.Basis.TestsHelper.InitializeTextEditorServicesTestsHelper, Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.inModel, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.GetViewModels()
TextEditorViewModelApi.GetViewModels()
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.MutateScrollVerticalPosition()
TextEditorViewModelApi.MutateScrollVerticalPosition(string, string, double)
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.MutateScrollHorizontalPosition()
TextEditorViewModelApi.MutateScrollHorizontalPosition(string, string, double)
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.MeasureCharacterWidthAndLineHeightAsync()
TextEditorViewModelApi.MeasureCharacterWidthAndLineHeightAsync(string, int)
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.MoveCursor()
TextEditorViewModelApi.MoveCursor(KeymapArgs, ResourceUri, Key<TextEditorViewModel>)
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.MoveCursor_SelectText()
TextEditorViewModelApi.MoveCursor(KeymapArgs, ResourceUri, Key<TextEditorViewModel>)
References Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.MoveCursor_SelectText, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
Referenced by Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.MoveCursor_SelectText, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.MoveCursor_SelectText_SmallSelectionAnchorPosition_Then_MoveDown, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.MoveCursor_SelectText_SmallSelectionAnchorPosition_Then_MoveLeft, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.MoveCursor_SelectText_SmallSelectionAnchorPosition_Then_MoveRight, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.MoveCursor_SelectText_SmallSelectionAnchorPosition_Then_MoveUp, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.MoveCursor_SelectText_SmallSelectionEndingPosition_Then_MoveDown, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.MoveCursor_SelectText_SmallSelectionEndingPosition_Then_MoveLeft, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.MoveCursor_SelectText_SmallSelectionEndingPosition_Then_MoveRight, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.MoveCursor_SelectText_SmallSelectionEndingPosition_Then_MoveUp.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.MoveCursor_SelectText_SmallSelectionAnchorPosition_Then_MoveLeft()
TextEditorViewModelApi.MoveCursor(KeymapArgs, ResourceUri, Key<TextEditorViewModel>)SmallSelectionAnchorPosition refers to the anchor position being smaller than the ending position.
References Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.MoveCursor_SelectText, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.MoveCursor_SelectText_SmallSelectionEndingPosition_Then_MoveLeft()
TextEditorViewModelApi.MoveCursor(KeymapArgs, ResourceUri, Key<TextEditorViewModel>)SmallSelectionEndingPosition refers to the ending position being smaller than the anchor.
References Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.MoveCursor_SelectText, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.MoveCursor_SelectText_SmallSelectionAnchorPosition_Then_MoveDown()
TextEditorViewModelApi.MoveCursor(KeymapArgs, ResourceUri, Key<TextEditorViewModel>)SmallSelectionAnchorPosition refers to the anchor position being smaller than the ending position.
References Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.MoveCursor_SelectText, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.MoveCursor_SelectText_SmallSelectionEndingPosition_Then_MoveDown()
TextEditorViewModelApi.MoveCursor(KeymapArgs, ResourceUri, Key<TextEditorViewModel>)SmallSelectionEndingPosition refers to the ending position being smaller than the anchor.
References Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.MoveCursor_SelectText, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.MoveCursor_SelectText_SmallSelectionAnchorPosition_Then_MoveUp()
TextEditorViewModelApi.MoveCursor(KeymapArgs, ResourceUri, Key<TextEditorViewModel>)SmallSelectionAnchorPosition refers to the anchor position being smaller than the ending position.
References Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.MoveCursor_SelectText, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.MoveCursor_SelectText_SmallSelectionEndingPosition_Then_MoveUp()
TextEditorViewModelApi.MoveCursor(KeymapArgs, ResourceUri, Key<TextEditorViewModel>)SmallSelectionEndingPosition refers to the ending position being smaller than the anchor.
References Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.MoveCursor_SelectText, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.MoveCursor_SelectText_SmallSelectionAnchorPosition_Then_MoveRight()
TextEditorViewModelApi.MoveCursor(KeymapArgs, ResourceUri, Key<TextEditorViewModel>)SmallSelectionAnchorPosition refers to the anchor position being smaller than the ending position.
References Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.MoveCursor_SelectText, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.MoveCursor_SelectText_SmallSelectionEndingPosition_Then_MoveRight()
TextEditorViewModelApi.MoveCursor(KeymapArgs, ResourceUri, Key<TextEditorViewModel>)SmallSelectionEndingPosition refers to the ending position being smaller than the anchor.
References Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.MoveCursor_SelectText, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.MoveCursorUnsafe()
TextEditorViewModelApi.MoveCursorUnsafe(KeymapArgs, ResourceUri, Key<TextEditorViewModel>, TextEditorCursorModifier)
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.Register()
TextEditorViewModelApi.Register(Key<TextEditorViewModel>, ResourceUri, Category)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.Category, Luthetus.TextEditor.Tests.Basis.TestsHelper.InitializeTextEditorServicesTestsHelper, Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.inModel, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.Remeasure()
TextEditorViewModelApi.Remeasure(ResourceUri, Key<TextEditorViewModel>, string, int, CancellationToken)
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.ScrollIntoView_LineIndex_ColumnIndex()
TextEditorViewModelApi.ScrollIntoView(string, string, int?, int?)
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.ScrollIntoView_PositionIndex()
TextEditorViewModelApi.ScrollIntoView(string, string, int)
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.ScrollIntoView_TextSpan()
TextEditorViewModelApi.ScrollIntoView(ResourceUri, Key<TextEditorViewModel>, TextEditorTextSpan)
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.SetScrollPosition()
TextEditorViewModelApi.SetScrollPosition(string, string, double?, double?)
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.SetGutterScrollTop()
TextEditorViewModelApi.SetGutterScrollTop(string, double)
async Task Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.SetCursorShouldBlink()
TextEditorViewModelApi.SetCursorShouldBlink(bool) - TextEditorViewModelApi.CursorShouldBlink TextEditorViewModelApi.CursorShouldBlinkChanged
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.WithValue()
TextEditorViewModelApi.WithValue(Key<TextEditorViewModel>, Func<TextEditorViewModel, TextEditorViewModel>)
References Luthetus.TextEditor.Tests.Basis.TestsHelper.InitializeTextEditorServicesTestsHelper, Luthetus.TextEditor.Tests.Basis.TextEditorTestBase.inModel, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService, Luthetus.TextEditor.RazorLib.TextEditors.Models.UnsafeState, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.WithValue.
Referenced by Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.WithValue.
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.WithTask()
TextEditorViewModelApi.WithTask(Key<TextEditorViewModel>, Func<TextEditorViewModel, Task<Func<TextEditorViewModel, TextEditorViewModel>>>)
void Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.InitializeTextEditorViewModelApiTests(out ResourceUri resourceUri, out Key< TextEditorViewModel > viewModelKey, out ITextEditorService textEditorService, out IServiceProvider serviceProvider)