Luthetus::Extensions::DotNet::CompilerServices::States::CompilerServiceExplorerState
readonly Key<TreeViewContainer> Luthetus.Extensions.DotNet.CompilerServices.States.CompilerServiceExplorerState.TreeViewCompilerServiceExplorerContentStateKey
Referenced by Luthetus.Extensions.DotNet.CompilerServices.Models.CompilerServiceIdeApi.SetCompilerServiceExplorerTreeView.
CompilerServiceExplorerModel Luthetus.Extensions.DotNet.CompilerServices.States.CompilerServiceExplorerState.Model
Referenced by Luthetus.Extensions.DotNet.CompilerServices.States.CompilerServiceExplorerState.CompilerServiceExplorerState, Luthetus.Extensions.DotNet.CompilerServices.States.CompilerServiceExplorerState.CompilerServiceExplorerState.
record Luthetus.Extensions.DotNet.CompilerServices.States.CompilerServiceExplorerState.NewAction(Func< CompilerServiceExplorerState, CompilerServiceExplorerState > NewFunc)
Referenced by Luthetus.Extensions.DotNet.CompilerServices.States.CompilerServiceExplorerState.Reducer.ReduceNewAction, Luthetus.Extensions.DotNet.CompilerServices.Models.CompilerServiceIdeApi.SetCompilerServiceExplorerTreeView.
Luthetus.Extensions.DotNet.CompilerServices.States.CompilerServiceExplorerState.CompilerServiceExplorerState()
References Luthetus.Extensions.DotNet.CompilerServices.States.CompilerServiceExplorerState.Model.
Referenced by Luthetus.Extensions.DotNet.CompilerServices.States.CompilerServiceExplorerState.Reducer.ReduceNewAction.
Luthetus.Extensions.DotNet.CompilerServices.States.CompilerServiceExplorerState.CompilerServiceExplorerState(CompilerServiceExplorerModel model)
References Luthetus.Extensions.DotNet.CompilerServices.States.CompilerServiceExplorerState.Model.