Luthetus::TextEditor::RazorLib::Options::Models::TextEditorOptionsApi
readonly ITextEditorService Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi._textEditorService
readonly LuthetusTextEditorConfig Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi._textEditorConfig
readonly IStorageService Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi._storageService
readonly CommonBackgroundTaskApi Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi._commonBackgroundTaskApi
readonly IDispatcher Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi._dispatcher
IDialog? Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi._findAllDialog
Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.TextEditorOptionsApi(ITextEditorService textEditorService, LuthetusTextEditorConfig textEditorConfig, IStorageService storageService, CommonBackgroundTaskApi commonBackgroundTaskApi, IDispatcher dispatcher)
References Luthetus.TextEditor.RazorLib.Installations.Models.LuthetusTextEditorConfig.
TextEditorOptions Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.GetOptions()
One should store the result of invoking this method in a variable, then reference that variable. If one continually invokes this, there is no guarantee that the data had not changed since the previous invocation.
References Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptions.
void Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.ShowSettingsDialog(bool? isResizableOverride=null, string? cssClassString=null)
References Luthetus.Common.RazorLib.Dialogs.States.DialogState, Luthetus.Common.RazorLib.Dialogs.Models.DialogViewModel.
void Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.ShowFindAllDialog(bool? isResizableOverride=null, string? cssClassString=null)
References Luthetus.Common.RazorLib.Dialogs.States.DialogState, Luthetus.Common.RazorLib.Dialogs.Models.DialogViewModel.
void Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetTheme(ThemeRecord theme, bool updateStorage=true)
This is setting the TextEditor's theme specifically. This is not to be confused with the AppOptions Themes which get applied at an application level. This allows for a "DarkTheme-Application" that has a "LightTheme-TextEditor".
References Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.SetThemeAction, Luthetus.Common.RazorLib.Themes.Models.ThemeRecord, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.WriteToStorage.
Referenced by Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetFromLocalStorageAsync.
void Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetShowWhitespace(bool showWhitespace, bool updateStorage=true)
References Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.SetShowWhitespaceAction, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.WriteToStorage.
Referenced by Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetFromLocalStorageAsync.
void Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetUseMonospaceOptimizations(bool useMonospaceOptimizations, bool updateStorage=true)
References Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.SetUseMonospaceOptimizationsAction, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.WriteToStorage.
void Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetShowNewlines(bool showNewlines, bool updateStorage=true)
References Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.SetShowNewlinesAction, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.WriteToStorage.
Referenced by Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetFromLocalStorageAsync.
void Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetKeymap(Keymap keymap, bool updateStorage=true)
References Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.SetKeymapAction, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.WriteToStorage.
Referenced by Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetFromLocalStorageAsync.
void Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetHeight(int? heightInPixels, bool updateStorage=true)
References Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.SetHeightAction, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.WriteToStorage.
Referenced by Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetFromLocalStorageAsync.
void Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetFontSize(int fontSizeInPixels, bool updateStorage=true)
References Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.SetFontSizeAction, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.WriteToStorage.
Referenced by Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetFromLocalStorageAsync.
void Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetFontFamily(string? fontFamily, bool updateStorage=true)
References Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.SetFontFamilyAction, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.WriteToStorage.
void Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetCursorWidth(double cursorWidthInPixels, bool updateStorage=true)
References Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.SetCursorWidthAction, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.WriteToStorage.
Referenced by Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetFromLocalStorageAsync.
void Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetRenderStateKey(Key< RenderState > renderStateKey)
References Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.SetRenderStateKeyAction.
void Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.WriteToStorage()
References Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsJsonDto.
Referenced by Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetCursorWidth, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetFontFamily, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetFontSize, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetHeight, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetKeymap, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetShowNewlines, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetShowWhitespace, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetTheme, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetUseMonospaceOptimizations.
async Task Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetFromLocalStorageAsync()
References Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetCursorWidth, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetFontSize, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetHeight, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetKeymap, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetShowNewlines, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetShowWhitespace, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetTheme, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsJsonDto.