Luthetus::Common::RazorLib::Options::Models::AppOptionsService
readonly IDispatcher Luthetus.Common.RazorLib.Options.Models.AppOptionsService._dispatcher
readonly IStorageService Luthetus.Common.RazorLib.Options.Models.AppOptionsService._storageService
readonly CommonBackgroundTaskApi Luthetus.Common.RazorLib.Options.Models.AppOptionsService._commonBackgroundTaskApi
readonly IBackgroundTaskService Luthetus.Common.RazorLib.Options.Models.AppOptionsService._backgroundTaskService
IState<AppOptionsState> Luthetus.Common.RazorLib.Options.Models.AppOptionsService.AppOptionsStateWrap
Referenced by Luthetus.Common.RazorLib.Options.Models.AppOptionsService.AppOptionsService, Luthetus.Common.RazorLib.Options.Models.AppOptionsService.WriteToStorage.
IState<ThemeState> Luthetus.Common.RazorLib.Options.Models.AppOptionsService.ThemeStateWrap
Referenced by Luthetus.Common.RazorLib.Options.Models.AppOptionsService.AppOptionsService, Luthetus.Common.RazorLib.Options.Models.AppOptionsService.SetFromLocalStorageAsync.
string Luthetus.Common.RazorLib.Options.Models.AppOptionsService.StorageKey
This is used when interacting with the IStorageService to set and get data.
Referenced by Luthetus.Common.RazorLib.Options.Models.AppOptionsService.SetFromLocalStorageAsync, Luthetus.Common.RazorLib.Options.Models.AppOptionsService.WriteToStorage.
string Luthetus.Common.RazorLib.Options.Models.AppOptionsService.ThemeCssClassString
string? Luthetus.Common.RazorLib.Options.Models.AppOptionsService.FontFamilyCssStyleString
string Luthetus.Common.RazorLib.Options.Models.AppOptionsService.FontSizeCssStyleString
bool Luthetus.Common.RazorLib.Options.Models.AppOptionsService.ShowPanelTitles
string Luthetus.Common.RazorLib.Options.Models.AppOptionsService.ShowPanelTitlesCssClass
string Luthetus.Common.RazorLib.Options.Models.AppOptionsService.ColorSchemeCssStyleString
Luthetus.Common.RazorLib.Options.Models.AppOptionsService.AppOptionsService(IState< AppOptionsState > appOptionsStateWrap, IState< ThemeState > themeStateWrap, IDispatcher dispatcher, IStorageService storageService, CommonBackgroundTaskApi commonBackgroundTaskApi, IBackgroundTaskService backgroundTaskService)
References Luthetus.Common.RazorLib.Options.Models.AppOptionsService.AppOptionsStateWrap, Luthetus.Common.RazorLib.Options.Models.AppOptionsService.ThemeStateWrap.
void Luthetus.Common.RazorLib.Options.Models.AppOptionsService.SetActiveThemeRecordKey(Key< ThemeRecord > themeKey, bool updateStorage=true)
References Luthetus.Common.RazorLib.Options.States.AppOptionsState.
void Luthetus.Common.RazorLib.Options.Models.AppOptionsService.SetTheme(ThemeRecord theme, bool updateStorage=true)
References Luthetus.Common.RazorLib.Options.States.AppOptionsState, Luthetus.Common.RazorLib.Themes.Models.ThemeRecord.
Referenced by Luthetus.Common.RazorLib.Options.Models.AppOptionsService.SetFromLocalStorageAsync.
void Luthetus.Common.RazorLib.Options.Models.AppOptionsService.SetFontFamily(string? fontFamily, bool updateStorage=true)
References Luthetus.Common.RazorLib.Options.States.AppOptionsState.
Referenced by Luthetus.Common.RazorLib.Options.Models.AppOptionsService.SetFromLocalStorageAsync.
void Luthetus.Common.RazorLib.Options.Models.AppOptionsService.SetFontSize(int fontSizeInPixels, bool updateStorage=true)
References Luthetus.Common.RazorLib.Options.States.AppOptionsState.
Referenced by Luthetus.Common.RazorLib.Options.Models.AppOptionsService.SetFromLocalStorageAsync.
void Luthetus.Common.RazorLib.Options.Models.AppOptionsService.SetResizeHandleWidth(int resizeHandleWidthInPixels, bool updateStorage=true)
References Luthetus.Common.RazorLib.Options.States.AppOptionsState.
Referenced by Luthetus.Common.RazorLib.Options.Models.AppOptionsService.SetFromLocalStorageAsync.
void Luthetus.Common.RazorLib.Options.Models.AppOptionsService.SetResizeHandleHeight(int resizeHandleHeightInPixels, bool updateStorage=true)
References Luthetus.Common.RazorLib.Options.States.AppOptionsState.
Referenced by Luthetus.Common.RazorLib.Options.Models.AppOptionsService.SetFromLocalStorageAsync.
void Luthetus.Common.RazorLib.Options.Models.AppOptionsService.SetIconSize(int iconSizeInPixels, bool updateStorage=true)
References Luthetus.Common.RazorLib.Options.States.AppOptionsState.
Referenced by Luthetus.Common.RazorLib.Options.Models.AppOptionsService.SetFromLocalStorageAsync.
async Task Luthetus.Common.RazorLib.Options.Models.AppOptionsService.SetFromLocalStorageAsync()
References Luthetus.Common.RazorLib.Options.Models.CommonOptionsJsonDto, Luthetus.Common.RazorLib.Options.Models.AppOptionsService.SetFontFamily, Luthetus.Common.RazorLib.Options.Models.AppOptionsService.SetFontSize, Luthetus.Common.RazorLib.Options.Models.AppOptionsService.SetIconSize, Luthetus.Common.RazorLib.Options.Models.AppOptionsService.SetResizeHandleHeight, Luthetus.Common.RazorLib.Options.Models.AppOptionsService.SetResizeHandleWidth, Luthetus.Common.RazorLib.Options.Models.AppOptionsService.SetTheme, Luthetus.Common.RazorLib.Options.Models.AppOptionsService.StorageKey, Luthetus.Common.RazorLib.Options.Models.AppOptionsService.ThemeStateWrap.
void Luthetus.Common.RazorLib.Options.Models.AppOptionsService.WriteToStorage()
References Luthetus.Common.RazorLib.Options.Models.AppOptionsService.AppOptionsStateWrap, Luthetus.Common.RazorLib.Options.Models.CommonOptionsJsonDto, Luthetus.Common.RazorLib.Options.Models.AppOptionsService.StorageKey.