Luthetus::Extensions::DotNet::TestExplorers::States::TestExplorerScheduler
readonly DotNetBackgroundTaskApi Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler._dotNetBackgroundTaskApi
readonly IdeBackgroundTaskApi Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler._ideBackgroundTaskApi
readonly ICommonComponentRenderers Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler._commonComponentRenderers
readonly ITreeViewService Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler._treeViewService
readonly ITextEditorService Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler._textEditorService
readonly IBackgroundTaskService Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler._backgroundTaskService
readonly IFileSystemProvider Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler._fileSystemProvider
readonly IState<TerminalState> Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler._terminalStateWrap
readonly IState<TestExplorerState> Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler._testExplorerStateWrap
readonly IState<DotNetSolutionState> Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler._dotNetSolutionStateWrap
readonly DotNetCliOutputParser Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler._dotNetCliOutputParser
readonly IDispatcher Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler._dispatcher
readonly ThrottleAsync Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler._throttleDiscoverTests
TreeViewGroup Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.ContainsTestsTreeViewGroup
Referenced by Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.Task_ConstructTreeView, Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.Task_SumEachProjectTestCount.
TreeViewGroup Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.NoTestsTreeViewGroup
Referenced by Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.Task_ConstructTreeView, Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.Task_DiscoverTests, Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.Task_SumEachProjectTestCount.
TreeViewGroup Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.ThrewAnExceptionTreeViewGroup
Referenced by Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.Task_ConstructTreeView, Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.Task_SumEachProjectTestCount.
TreeViewGroup Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.NotValidProjectForUnitTestTreeViewGroup
Referenced by Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.Task_ConstructTreeView, Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.Task_SumEachProjectTestCount.
void Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.Enqueue_ConstructTreeView()
References Luthetus.Common.RazorLib.BackgroundTasks.Models.ContinuousBackgroundTaskWorker.GetQueueKey, Luthetus.CompilerServices.DotNetSolution.Models.Key, Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.Task_ConstructTreeView.
Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.TestExplorerScheduler(DotNetBackgroundTaskApi dotNetBackgroundTaskApi, IdeBackgroundTaskApi ideBackgroundTaskApi, ICommonComponentRenderers commonComponentRenderers, ITreeViewService treeViewService, ITextEditorService textEditorService, IBackgroundTaskService backgroundTaskService, IFileSystemProvider fileSystemProvider, DotNetCliOutputParser dotNetCliOutputParser, IState< DotNetSolutionState > dotNetSolutionStateWrap, IState< TerminalState > terminalStateWrap, IState< TestExplorerState > testExplorerStateWrap, IDispatcher dispatcher)
async Task Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.Task_ConstructTreeView()
References Luthetus.Common.RazorLib.TreeViews.Models.TreeViewAdhoc.ConstructTreeViewAdhoc, Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.ContainsTestsTreeViewGroup, Luthetus.Common.RazorLib.TreeViews.Models.TreeViewNoType.LinkChildren, Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.NoTestsTreeViewGroup, Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.NotValidProjectForUnitTestTreeViewGroup, Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerState, Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.ThrewAnExceptionTreeViewGroup, Luthetus.Common.RazorLib.TreeViews.Models.TreeViewContainer.
Referenced by Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.Enqueue_ConstructTreeView.
Task Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.Task_DiscoverTests()
References Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.NoTestsTreeViewGroup, Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.Task_SumEachProjectTestCount, Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerState.
Task Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.Task_SumEachProjectTestCount()
References Luthetus.Common.RazorLib.TreeViews.Models.TreeViewAdhoc.ConstructTreeViewAdhoc, Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.ContainsTestsTreeViewGroup, Luthetus.Common.RazorLib.TreeViews.Models.TreeViewNoType.LinkChildren, Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.MoveNodeToCorrectBranch, Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.NoTestsTreeViewGroup, Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.NotValidProjectForUnitTestTreeViewGroup, Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerState, Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.ThrewAnExceptionTreeViewGroup.
Referenced by Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.Task_DiscoverTests.
void Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.MoveNodeToCorrectBranch(TreeViewProjectTestModel treeViewProjectTestModel)
This is strategic spaghetti code that is part of my master plan. Don't @ me on teams; I won't respond.
References Luthetus.Common.RazorLib.TreeViews.Models.TreeViewNoType.ChildList, Luthetus.Common.RazorLib.TreeViews.Models.TreeViewWithType< T >.Item, Luthetus.Common.RazorLib.TreeViews.Models.TreeViewNoType.LinkChildren, Luthetus.Common.RazorLib.TreeViews.Models.TreeViewNoType.Parent, Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerState.
Referenced by Luthetus.Extensions.DotNet.TestExplorers.States.TestExplorerScheduler.Task_SumEachProjectTestCount.