Luthetus::TextEditor::RazorLib::CompilerServices::Syntax::Nodes::TypeDefinitionNode
ISyntax [] Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode._childList
bool Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode._childListIsDirty
TypeClauseNode? Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode._toTypeClauseNodeResult
AccessModifierKind Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.AccessModifierKind
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.TypeDefinitionNode.
bool Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.HasPartialModifier
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.TypeDefinitionNode.
StorageModifierKind Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.StorageModifierKind
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.TypeDefinitionNode.
IdentifierToken Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.TypeIdentifierToken
Given: 'public class Person { /* class definition here */ }' Then: 'Person' is the TypeIdentifierToken And: GenericArgumentsListingNode would be null.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindTypeDefinitionNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.GetChildList, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.ScopeFacts.GetInitialGlobalScope, Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseFunctions.HandleConstructorDefinition, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ToTypeClause, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.TypeDefinitionNode.
Type? Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ValueType
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ToTypeClause, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.TypeDefinitionNode.
GenericArgumentsListingNode? Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.GenericArgumentsListingNode
Given: 'public struct Array<T> { /* struct definition here */ }' Then: 'Array<T>' is the TypeIdentifierToken And: '<T>' is the GenericArgumentsListingNode.
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.GetChildList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.TypeDefinitionNode.
FunctionArgumentsListingNode? Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.PrimaryConstructorFunctionArgumentsListingNode
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.OnBoundScopeCreatedAndSetAsCurrent, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.SetPrimaryConstructorFunctionArgumentsListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.TypeDefinitionNode.
OpenBraceToken Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.OpenBraceToken
The open brace for the body code block node.
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.SetOpenBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.SetStatementDelimiterToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.TypeDefinitionNode.
TypeClauseNode? Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.InheritedTypeClauseNode
Given: public class Person : IPerson { ... } Then: 'IPerson' is the InheritedTypeClauseNode.
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.GetChildList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.SetInheritedTypeClauseNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.TypeDefinitionNode.
CodeBlockNode? Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.CodeBlockNode
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.GetChildList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.GetFunctionDefinitionNodes, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.SetCodeBlockNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.TypeDefinitionNode.
bool Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.IsInterface
Referenced by Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseFunctions.HandleFunctionDefinition.
CloseBraceToken Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.CloseBraceToken
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.SetCloseBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.SetStatementDelimiterToken.
StatementDelimiterToken Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.StatementDelimiterToken
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.SetCloseBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.SetOpenBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.SetStatementDelimiterToken.
bool Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.IsSingleStatementBody
ScopeDirectionKind Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ScopeDirectionKind
bool Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.IsFabricated
IsFabricated refers to when the ParserSession expected a node to be valid, but it wasn't. For example, a function invocation on an undefined function will construct a BoundFunctionInvocationNode with IsFabricated set to true.
SyntaxKind Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.SyntaxKind
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.GetFunctionDefinitionNodes.
string Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.EncompassingNamespaceIdentifierString
Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.TypeDefinitionNode(AccessModifierKind accessModifierKind, bool hasPartialModifier, StorageModifierKind storageModifierKind, IdentifierToken typeIdentifier, Type? valueType, GenericArgumentsListingNode? genericArgumentsListingNode, FunctionArgumentsListingNode? primaryConstructorFunctionArgumentsListingNode, TypeClauseNode? inheritedTypeClauseNode, OpenBraceToken openBraceToken, CodeBlockNode? codeBlockNode)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.AccessModifierKind, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.CodeBlockNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.GenericArgumentsListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.HasPartialModifier, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.InheritedTypeClauseNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.OpenBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.PrimaryConstructorFunctionArgumentsListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.StorageModifierKind, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.TypeIdentifierToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ValueType.
ImmutableArray< FunctionDefinitionNode > Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.GetFunctionDefinitionNodes()
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.CodeBlockNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.SyntaxKind.
TypeClauseNode Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ToTypeClause()
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.TypeClauseNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.TypeIdentifierToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.ValueType.
Referenced by Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AmbiguousIdentifierMergeExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AmbiguousIdentifierMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.AnyMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BinaryMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindBinaryOperatorNode, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindLiteralExpressionNode, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.CommaSeparatedMergeExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.CommaSeparatedMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ConstructAndBindVariableReferenceNode, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.FunctionInvocationNodeTests.Constructor, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ConstructorInvocationMergeExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ConstructorInvocationMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.EmptyMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ExplicitCastMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.FunctionArgumentsListingMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.FunctionInvocationMergeExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.FunctionInvocationMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.FunctionParametersListingMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GenericParametersListingMergeExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GenericParametersListingMergeToken, Luthetus.CompilerServices.CSharp.ParserCase.Internals.ParseDefaultKeywords.HandleForTokenKeyword, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.LambdaMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.LiteralMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ParenthesizedMergeExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ParenthesizedMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TypeClauseMergeExpression, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TypeClauseMergeToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.VariableAssignmentMergeExpression.
TypeClauseNode? Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.GetReturnTypeClauseNode()
ICodeBlockOwner Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.SetOpenBraceToken(OpenBraceToken openBraceToken, IParserModel parserModel)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.OpenBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.StatementDelimiterToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.ICodeBlockOwner.ThrowMultipleScopeDelimiterException.
ICodeBlockOwner Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.SetCloseBraceToken(CloseBraceToken closeBraceToken, IParserModel parserModel)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.CloseBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.StatementDelimiterToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.ICodeBlockOwner.ThrowMultipleScopeDelimiterException.
ICodeBlockOwner Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.SetStatementDelimiterToken(StatementDelimiterToken statementDelimiterToken, IParserModel parserModel)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.CloseBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.OpenBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.StatementDelimiterToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.ICodeBlockOwner.ThrowMultipleScopeDelimiterException.
ICodeBlockOwner Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.SetCodeBlockNode(CodeBlockNode codeBlockNode, IParserModel parserModel)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.CodeBlockNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.ICodeBlockOwner.ThrowAlreadyAssignedCodeBlockNodeException.
void Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.OnBoundScopeCreatedAndSetAsCurrent(IParserModel parserModel)
Once the code block owner's scope has been constructed, this method gives them an opportunity to pull any variables into scope that ought to be there. As well, the current code block builder will have been updated.
(i.e.: a function definition's arguments)
References Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IParserModel.Binder, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.BindVariableDeclarationNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.PrimaryConstructorFunctionArgumentsListingNode.
ICodeBlockOwner Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.SetPrimaryConstructorFunctionArgumentsListingNode(FunctionArgumentsListingNode functionArgumentsListingNode)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.PrimaryConstructorFunctionArgumentsListingNode.
ICodeBlockOwner Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.SetInheritedTypeClauseNode(TypeClauseNode typeClauseNode)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.InheritedTypeClauseNode.
ISyntax[] Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.GetChildList()
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.CodeBlockNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.GenericArgumentsListingNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.InheritedTypeClauseNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.TypeIdentifierToken.