Luthetus::Extensions::Git::Models::GitIdeApi
readonly GitBackgroundTaskApi Luthetus.Extensions.Git.Models.GitIdeApi._gitBackgroundTaskApi
readonly IdeBackgroundTaskApi Luthetus.Extensions.Git.Models.GitIdeApi._ideBackgroundTaskApi
readonly IState<TerminalState> Luthetus.Extensions.Git.Models.GitIdeApi._terminalStateWrap
readonly IState<GitState> Luthetus.Extensions.Git.Models.GitIdeApi._gitStateWrap
readonly GitCliOutputParser Luthetus.Extensions.Git.Models.GitIdeApi._gitCliOutputParser
readonly IEnvironmentProvider Luthetus.Extensions.Git.Models.GitIdeApi._environmentProvider
readonly IBackgroundTaskService Luthetus.Extensions.Git.Models.GitIdeApi._backgroundTaskService
readonly ICommonComponentRenderers Luthetus.Extensions.Git.Models.GitIdeApi._commonComponentRenderers
readonly IDispatcher Luthetus.Extensions.Git.Models.GitIdeApi._dispatcher
Key<TerminalCommandRequest> Luthetus.Extensions.Git.Models.GitIdeApi.GitTerminalCommandRequestKey
Luthetus.Extensions.Git.Models.GitIdeApi.GitIdeApi(GitBackgroundTaskApi gitBackgroundTaskApi, IdeBackgroundTaskApi ideBackgroundTaskApi, IState< TerminalState > terminalStateWrap, IState< GitState > gitStateWrap, GitCliOutputParser gitCliOutputParser, IEnvironmentProvider environmentProvider, IBackgroundTaskService backgroundTaskService, ICommonComponentRenderers commonComponentRenderers, IDispatcher dispatcher)
void Luthetus.Extensions.Git.Models.GitIdeApi.StatusEnqueue()
References Luthetus.Common.RazorLib.BackgroundTasks.Models.ContinuousBackgroundTaskWorker.GetQueueKey.
Referenced by Luthetus.Extensions.Git.Models.GitIdeApi.CommitEnqueue, Luthetus.Extensions.Git.Models.GitIdeApi.RefreshEnqueue.
void Luthetus.Extensions.Git.Models.GitIdeApi.RefreshEnqueue(GitRepo repoAtTimeOfRequest)
References Luthetus.Extensions.Git.Models.GitIdeApi.BranchGetAllEnqueue, Luthetus.Extensions.Git.Models.GitIdeApi.GetActiveBranchNameEnqueue, Luthetus.Extensions.Git.Models.GitIdeApi.GetOriginNameEnqueue, Luthetus.Extensions.Git.Models.GitRepo, Luthetus.Extensions.Git.Models.GitIdeApi.StatusEnqueue.
Referenced by Luthetus.Extensions.Git.Models.GitIdeApi.BranchNewEnqueue, Luthetus.Extensions.Git.Models.GitIdeApi.BranchSetEnqueue, Luthetus.Extensions.Git.Models.GitIdeApi.FetchEnqueue, Luthetus.Extensions.Git.Models.GitIdeApi.PullEnqueue, Luthetus.Extensions.Git.Models.GitIdeApi.PushToOriginWithTrackingEnqueue.
void Luthetus.Extensions.Git.Models.GitIdeApi.GetActiveBranchNameEnqueue(GitRepo repoAtTimeOfRequest)
References Luthetus.Common.RazorLib.BackgroundTasks.Models.ContinuousBackgroundTaskWorker.GetQueueKey, Luthetus.Extensions.Git.Models.GitRepo.
Referenced by Luthetus.Extensions.Git.Models.GitIdeApi.RefreshEnqueue.
void Luthetus.Extensions.Git.Models.GitIdeApi.GetOriginNameEnqueue(GitRepo repoAtTimeOfRequest)
References Luthetus.Common.RazorLib.BackgroundTasks.Models.ContinuousBackgroundTaskWorker.GetQueueKey, Luthetus.Extensions.Git.Models.GitRepo.
Referenced by Luthetus.Extensions.Git.Models.GitIdeApi.RefreshEnqueue.
void Luthetus.Extensions.Git.Models.GitIdeApi.AddEnqueue(GitRepo repoAtTimeOfRequest)
References Luthetus.Common.RazorLib.BackgroundTasks.Models.ContinuousBackgroundTaskWorker.GetQueueKey, Luthetus.Extensions.Git.Models.GitRepo.
void Luthetus.Extensions.Git.Models.GitIdeApi.UnstageEnqueue(GitRepo repoAtTimeOfRequest)
References Luthetus.Common.RazorLib.BackgroundTasks.Models.ContinuousBackgroundTaskWorker.GetQueueKey, Luthetus.Extensions.Git.Models.GitRepo.
void Luthetus.Extensions.Git.Models.GitIdeApi.CommitEnqueue(GitRepo repoAtTimeOfRequest, string commitSummary)
References Luthetus.Common.RazorLib.BackgroundTasks.Models.ContinuousBackgroundTaskWorker.GetQueueKey, Luthetus.Extensions.Git.Models.GitRepo, Luthetus.Extensions.Git.Models.GitIdeApi.StatusEnqueue.
void Luthetus.Extensions.Git.Models.GitIdeApi.BranchNewEnqueue(GitRepo repoAtTimeOfRequest, string branchName)
References Luthetus.Extensions.Git.Models.GitIdeApi.BranchNewEnqueue, Luthetus.Common.RazorLib.BackgroundTasks.Models.ContinuousBackgroundTaskWorker.GetQueueKey, Luthetus.Extensions.Git.Models.GitRepo, Luthetus.Extensions.Git.Models.GitIdeApi.RefreshEnqueue.
Referenced by Luthetus.Extensions.Git.Models.GitIdeApi.BranchNewEnqueue.
void Luthetus.Extensions.Git.Models.GitIdeApi.BranchGetAllEnqueue(GitRepo repoAtTimeOfRequest)
References Luthetus.Common.RazorLib.BackgroundTasks.Models.ContinuousBackgroundTaskWorker.GetQueueKey, Luthetus.Extensions.Git.Models.GitRepo.
Referenced by Luthetus.Extensions.Git.Models.GitIdeApi.RefreshEnqueue.
void Luthetus.Extensions.Git.Models.GitIdeApi.BranchSetEnqueue(GitRepo repoAtTimeOfRequest, string branchName)
References Luthetus.Common.RazorLib.BackgroundTasks.Models.ContinuousBackgroundTaskWorker.GetQueueKey, Luthetus.Extensions.Git.Models.GitRepo, Luthetus.Extensions.Git.Models.GitIdeApi.RefreshEnqueue.
void Luthetus.Extensions.Git.Models.GitIdeApi.PushToOriginWithTrackingEnqueue(GitRepo repoAtTimeOfRequest)
References Luthetus.Common.RazorLib.BackgroundTasks.Models.ContinuousBackgroundTaskWorker.GetQueueKey, Luthetus.Extensions.Git.Models.GitRepo, Luthetus.Extensions.Git.Models.GitIdeApi.RefreshEnqueue.
void Luthetus.Extensions.Git.Models.GitIdeApi.PullEnqueue(GitRepo repoAtTimeOfRequest)
References Luthetus.Common.RazorLib.BackgroundTasks.Models.ContinuousBackgroundTaskWorker.GetQueueKey, Luthetus.Extensions.Git.Models.GitRepo, Luthetus.Extensions.Git.Models.GitIdeApi.RefreshEnqueue.
void Luthetus.Extensions.Git.Models.GitIdeApi.FetchEnqueue(GitRepo repoAtTimeOfRequest)
References Luthetus.Common.RazorLib.BackgroundTasks.Models.ContinuousBackgroundTaskWorker.GetQueueKey, Luthetus.Extensions.Git.Models.GitRepo, Luthetus.Extensions.Git.Models.GitIdeApi.RefreshEnqueue.
void Luthetus.Extensions.Git.Models.GitIdeApi.LogFileEnqueue(GitRepo repoAtTimeOfRequest, string relativePathToFile, Func< GitCliOutputParser, string, Task > callback)
References Luthetus.Common.RazorLib.BackgroundTasks.Models.ContinuousBackgroundTaskWorker.GetQueueKey, Luthetus.Extensions.Git.Models.GitRepo.
void Luthetus.Extensions.Git.Models.GitIdeApi.ShowFileEnqueue(GitRepo repoAtTimeOfRequest, string relativePathToFile, Func< GitCliOutputParser, string, Task > callback)
References Luthetus.Common.RazorLib.BackgroundTasks.Models.ContinuousBackgroundTaskWorker.GetQueueKey, Luthetus.Extensions.Git.Models.GitRepo.
void Luthetus.Extensions.Git.Models.GitIdeApi.DiffFileEnqueue(GitRepo repoAtTimeOfRequest, string relativePathToFile, Func< GitCliOutputParser, string, List< int >, Task > callback)
References Luthetus.Common.RazorLib.BackgroundTasks.Models.ContinuousBackgroundTaskWorker.GetQueueKey, Luthetus.Extensions.Git.Models.GitRepo.
List< int > Luthetus.Extensions.Git.Models.GitIdeApi.GetPlusMarkedLineIndexList(string gitLogDashPOutput)