Luthetus::TextEditor::Tests::Basis::TestsHelper
static void Luthetus.TextEditor.Tests.Basis.TestsHelper.InitializeTextEditorServicesTestsHelper(out ITextEditorService textEditorService, out TextEditorModel model, out TextEditorViewModel viewModel, out IServiceProvider serviceProvider)
References AddScoped, Luthetus.TextEditor.RazorLib.TextEditors.Models.Category, Luthetus.Common.RazorLib.BackgroundTasks.Models.BlockingBackgroundTaskWorker.GetQueueKey, Luthetus.Common.RazorLib.BackgroundTasks.Models.ContinuousBackgroundTaskWorker.GetQueueKey, Luthetus.Common.RazorLib.Installations.Models.LuthetusCommonConfig, Luthetus.TextEditor.RazorLib.Installations.Models.LuthetusTextEditorConfig, Luthetus.Common.RazorLib.BackgroundTasks.Models.BlockingBackgroundTaskWorker.QUEUE_DISPLAY_NAME, Luthetus.Common.RazorLib.BackgroundTasks.Models.ContinuousBackgroundTaskWorker.QUEUE_DISPLAY_NAME, Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModel.
Referenced by Luthetus.TextEditor.Tests.Basis.Autocompletes.Models.WordAutocompleteIndexerTests.Constructor, Luthetus.TextEditor.Tests.Basis.ServiceTests.Constructor, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.DeleteTextByMotionEnqueue_Backspace, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.DeleteTextByRangeEnqueue, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.Dispose, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.Dispose, Luthetus.TextEditor.Tests.Basis.Diffs.States.TextEditorDiffStateActionsTests.DisposeAction, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.GetAllText, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.GetModelOrDefault, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.GetOrDefault, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.GetOrDefault, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelTests.Properties, Luthetus.TextEditor.Tests.Basis.Diffs.States.TextEditorDiffStateReducerTests.ReduceDisposeAction, Luthetus.TextEditor.Tests.Basis.Diffs.States.TextEditorDiffStateReducerTests.ReduceRegisterAction, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.Register, Luthetus.TextEditor.Tests.Basis.Diffs.States.TextEditorDiffStateActionsTests.RegisterAction, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.RegisterPresentationModel, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorViewModelApiTests.WithValue.
static void Luthetus.TextEditor.Tests.Basis.TestsHelper.ConstructTestTextEditorModel(out TextEditorModel model)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TestConstants.SOURCE_TEXT.
Referenced by Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.ClearOnlyRowEndingKind, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Constructor, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.HandleKeyboardEvent, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.ModifyResourceData, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.ModifyUsingRowEndingKind.
static void Luthetus.TextEditor.Tests.Basis.TestsHelper.InBounds_StartOfRow(out TextEditorModel model, out TextEditorCursor cursor)
Start of a row && !start_of_document.
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TestConstants.SOURCE_TEXT, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor.
static void Luthetus.TextEditor.Tests.Basis.TestsHelper.InBounds_NOT_StartOfRow_AND_NOT_EndOfRow(out TextEditorModel model, out TextEditorCursor cursor)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TestConstants.SOURCE_TEXT, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor.
static void Luthetus.TextEditor.Tests.Basis.TestsHelper.InBounds_EndOfRow(out TextEditorModel model, out TextEditorCursor cursor)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TestConstants.SOURCE_TEXT, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor.
static void Luthetus.TextEditor.Tests.Basis.TestsHelper.InBounds_StartOfDocument(out TextEditorModel model, out TextEditorCursor cursor)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TestConstants.SOURCE_TEXT, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor.
static void Luthetus.TextEditor.Tests.Basis.TestsHelper.InBounds_EndOfDocument(out TextEditorModel model, out TextEditorCursor cursor)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TestConstants.SOURCE_TEXT, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor.
static void Luthetus.TextEditor.Tests.Basis.TestsHelper.OutOfBounds_PositionIndex_LESS_THAN_Zero(out TextEditorModel model, out TextEditorCursor cursor)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TestConstants.SOURCE_TEXT, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor.
static void Luthetus.TextEditor.Tests.Basis.TestsHelper.OutOfBounds_PositionIndex_GREATER_THAN_DocumentLength_PLUS_One(out TextEditorModel model, out TextEditorCursor cursor)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TestConstants.SOURCE_TEXT, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor.