Luthetus::Common::Tests::Basis::FileSystems::FileSystemsTestsHelper
static void Luthetus.Common.Tests.Basis.FileSystems.FileSystemsTestsHelper.InitializeFileSystemsTests(out InMemoryEnvironmentProvider inMemoryEnvironmentProvider, out InMemoryFileSystemProvider inMemoryFileSystemProvider, out ServiceProvider serviceProvider)
The files shown in the 'tree' below will be written to the in-memory filesystem. ------------------------------------------ Root ∙└───Homework ∙∙∙∙∙∙├───Math ∙∙∙∙∙∙│∙∙∙∙├───addition.txt ∙∙∙∙∙∙│∙∙∙∙└───subtraction.txt ∙∙∙∙∙∙│ ∙∙∙∙∙∙└───Biology ∙∙∙∙∙∙∙∙∙∙∙├───nervousSystem.txt ∙∙∙∙∙∙∙∙∙∙∙└───skeletalSystem.txt .
inMemoryEnvironmentProvider Register IEnvironmentProvider service to be InMemoryEnvironmentProvider, but keep the out variable with the concrete type. This provides clarity that the unit test won't create side effects in one's true filesystem, while still allowing the use of the dependency injected interface. inMemoryFileSystemProvider Register IFileSystemProvider service to be InMemoryFileSystemProvider, but keep the out variable with the concrete type. This provides clarity that the unit test won't create side effects in one's true filesystem, while still allowing the use of the dependency injected interface.
References AddScoped.
Referenced by Luthetus.Common.Tests.Basis.FileSystems.Models.AbsolutePathTests.Aaa, Luthetus.Common.Tests.Basis.FileSystems.Models.AbsolutePathTests.Constructor, Luthetus.Common.Tests.Basis.FileSystems.Models.FileSystemDriveTests.Constructor.
static void Luthetus.Common.Tests.Basis.FileSystems.FileSystemsTestsHelper.WriteToInMemoryFileSystem(InMemoryEnvironmentProvider inMemoryEnvironmentProvider, InMemoryFileSystemProvider inMemoryFileSystemProvider)