Luthetus::TextEditor::RazorLib::CompilerServices::GenericLexer::SyntaxActors::GenericSyntaxTree
GenericLanguageDefinition Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.GenericLanguageDefinition
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.GenericSyntaxTree, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseCommentMultiLine, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseCommentSingleLine, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseString, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseText.
Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.GenericSyntaxTree(GenericLanguageDefinition genericLanguageDefinition)
References Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.GenericLanguageDefinition.
virtual GenericSyntaxUnit Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseText(ResourceUri resourceUri, string content)
References Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.GenericLanguageDefinition, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseCommentMultiLine, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseCommentSingleLine, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseString, Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri, Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
virtual GenericCommentSingleLineSyntax Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseCommentSingleLine(StringWalker stringWalker, DiagnosticBag diagnosticBag)
References Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.GenericLanguageDefinition, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.IsEof, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.PeekForSubstringRange, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.PositionIndex, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadCharacter, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportEndOfFileUnexpected, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ResourceUri, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.SourceText, Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseText.
virtual GenericCommentMultiLineSyntax Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseCommentMultiLine(StringWalker stringWalker, DiagnosticBag diagnosticBag)
References Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.GenericLanguageDefinition, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.IsEof, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.PeekForSubstring, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.PositionIndex, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadCharacter, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportEndOfFileUnexpected, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ResourceUri, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.SourceText, Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseText.
virtual GenericStringSyntax Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseString(StringWalker stringWalker, DiagnosticBag diagnosticBag)
References Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.GenericLanguageDefinition, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.IsEof, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.PeekForSubstring, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.PositionIndex, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadCharacter, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportEndOfFileUnexpected, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ResourceUri, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.SourceText, Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseText.
bool Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.TryParseKeyword(StringWalker stringWalker, DiagnosticBag diagnosticBag, out GenericKeywordSyntax? genericKeywordSyntax)
currentCharacterIn: -Any CurrentCharacter value is valid as this method is 'try'
bool Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.TryParseFunctionIdentifier(StringWalker stringWalker, DiagnosticBag diagnosticBag, out GenericFunctionSyntax? genericFunctionSyntax)
GenericPreprocessorDirectiveSyntax Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParsePreprocessorDirective(StringWalker stringWalker, DiagnosticBag diagnosticBag)
bool Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.TryParsePreprocessorDirectiveDeliminationExtendedSyntaxes(StringWalker stringWalker, DiagnosticBag diagnosticBag, out IGenericSyntax? genericSyntax)