Luthetus::Common::RazorLib::BackgroundTasks::Models::BlockingBackgroundTaskWorker
const string Luthetus.Common.RazorLib.BackgroundTasks.Models.BlockingBackgroundTaskWorker.QUEUE_DISPLAY_NAME
Referenced by Luthetus.TextEditor.Tests.Basis.CompilerServices.TextEditorCompilerServicesTestsHelper.InitializeTextEditorCompilerServicesTestsHelper, Luthetus.TextEditor.Tests.Basis.TestsHelper.InitializeTextEditorServicesTestsHelper.
readonly Key<IBackgroundTaskQueue> Luthetus.Common.RazorLib.BackgroundTasks.Models.BlockingBackgroundTaskWorker._queueKey
Luthetus.Common.RazorLib.BackgroundTasks.Models.BlockingBackgroundTaskWorker.BlockingBackgroundTaskWorker(IBackgroundTaskService backgroundTaskService, ILoggerFactory loggerFactory)
static Key< IBackgroundTaskQueue > Luthetus.Common.RazorLib.BackgroundTasks.Models.BlockingBackgroundTaskWorker.GetQueueKey()
Referenced by Luthetus.Common.Tests.Basis.Installations.Models.ServiceCollectionExtensionsTests.AddLuthetusCommonServices, Luthetus.Common.Tests.Basis.BackgroundTasks.Models.BlockingBackgroundTaskWorkerTests.Constructor, Luthetus.Common.Tests.Basis.BackgroundTasks.Models.ContinuousBackgroundTaskWorkerTests.Constructor, Luthetus.Ide.RazorLib.Terminals.Models.Terminal.EnqueueCommand, Luthetus.Ide.RazorLib.Terminals.Models.TerminalIntegrated.EnqueueCommand, Luthetus.Ide.RazorLib.Terminals.Models.TerminalWebsite.EnqueueCommand, Luthetus.Ide.RazorLib.Terminals.Models.Terminal.EnqueueCommandAsync, Luthetus.Ide.RazorLib.Terminals.Models.TerminalIntegrated.EnqueueCommandAsync, Luthetus.Ide.RazorLib.Terminals.Models.TerminalWebsite.EnqueueCommandAsync, Luthetus.TextEditor.Tests.Basis.CompilerServices.TextEditorCompilerServicesTestsHelper.InitializeTextEditorCompilerServicesTestsHelper, Luthetus.TextEditor.Tests.Basis.TestsHelper.InitializeTextEditorServicesTestsHelper.