Luthetus::TextEditor::RazorLib::TextEditors::Displays::Internals::HeaderDriver
readonly TextEditorViewModelDisplay Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver._root
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.ConstructCommandArgs, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoCopyOnClick, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoCutOnClick, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoPasteOnClick, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoRedoOnClick, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoRefreshOnClick, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoReloadOnClick, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoRemeasureOnClick, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoSaveOnClick, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoSelectAllOnClick, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoUndoOnClick, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.HeaderDriver, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.ShowWatchWindowDisplayDialogOnClick.
TextEditorRenderBatchValidated Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver._renderBatch
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoCopyOnClick, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoCutOnClick, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoPasteOnClick, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoRedoOnClick, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoRefreshOnClick, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoReloadOnClick, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoRemeasureOnClick, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoSaveOnClick, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoSelectAllOnClick, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoUndoOnClick, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.GetRedoDisabledAttribute, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.GetRenderFragment, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.GetUndoDisabledAttribute, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.ShowWatchWindowDisplayDialogOnClick.
string Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver._reloadButtonHtmlElementId
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoReloadOnClick.
Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.HeaderDriver(TextEditorViewModelDisplay textEditorViewModelDisplay)
References Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver._root.
void Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.GetRenderFragment(TextEditorRenderBatchValidated renderBatch)
References Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver._renderBatch.
TextEditorCommandArgs Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.ConstructCommandArgs(TextEditorRenderBatchValidated renderBatchLocal)
References Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver._root, Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorRenderBatchValidated.ComponentData, Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorRenderBatchValidated.Model, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModel.ResourceUri, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor, Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorRenderBatchValidated.ViewModel.
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoCopyOnClick, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoCutOnClick, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoPasteOnClick, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoRedoOnClick, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoRefreshOnClick, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoReloadOnClick, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoRemeasureOnClick, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoSaveOnClick, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoSelectAllOnClick, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoUndoOnClick.
Task Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoCopyOnClick(MouseEventArgs arg)
References Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver._renderBatch, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver._root, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.ConstructCommandArgs.
Task Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoCutOnClick(MouseEventArgs arg)
References Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver._renderBatch, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver._root, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.ConstructCommandArgs.
Task Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoPasteOnClick(MouseEventArgs arg)
References Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver._renderBatch, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver._root, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.ConstructCommandArgs.
Task Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoRedoOnClick(MouseEventArgs arg)
References Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver._renderBatch, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver._root, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.ConstructCommandArgs.
Task Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoSaveOnClick(MouseEventArgs arg)
References Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver._renderBatch, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver._root, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.ConstructCommandArgs.
Task Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoUndoOnClick(MouseEventArgs arg)
References Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver._renderBatch, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver._root, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.ConstructCommandArgs.
Task Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoSelectAllOnClick(MouseEventArgs arg)
References Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver._renderBatch, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver._root, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.ConstructCommandArgs.
Task Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoRemeasureOnClick(MouseEventArgs arg)
References Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver._renderBatch, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver._root, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.ConstructCommandArgs.
async Task Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoReloadOnClick(MouseEventArgs arg)
References Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver._reloadButtonHtmlElementId, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver._renderBatch, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver._root, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.ConstructCommandArgs, Luthetus.Common.RazorLib.Menus.Models.MenuOptionRecord.
void Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.ShowWatchWindowDisplayDialogOnClick()
References Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver._renderBatch, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver._root, Luthetus.Common.RazorLib.Dialogs.Models.DialogViewModel, Luthetus.Common.RazorLib.WatchWindows.Displays.WatchWindowDisplay.WatchWindowObject.
Task Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoRefreshOnClick()
References Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver._renderBatch, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver._root, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.ConstructCommandArgs.
bool Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.GetUndoDisabledAttribute()
disabled=@GetUndoDisabledAttribute() will toggle the attribute disabled="@GetUndoDisabledAttribute()" will toggle the value of the attribute
References Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver._renderBatch.
bool Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.GetRedoDisabledAttribute()
disabled=@GetRedoDisabledAttribute() will toggle the attribute disabled="@GetRedoDisabledAttribute()" will toggle the value of the attribute
References Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver._renderBatch.