Luthetus::TextEditor::RazorLib::TextEditors::Models::Internals::TextEditorComponentData
readonly Throttle Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData._throttleApplySyntaxHighlighting
TimeSpan Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.ThrottleDelayDefault
TimeSpan Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.OnMouseOutTooltipDelay
TimeSpan Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.MouseStoppedMovingDelay
TextEditorOptions Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.Options
This property contains the global options, with an extra step of overriding any specified options for a specific text editor. The current implementation of this is quite hacky and not obvious when reading the code.
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.TextEditorComponentData, Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.TextEditorComponentData.
Guid Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.TextEditorHtmlElementId
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.TextEditorComponentData, Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.TextEditorComponentData.
ViewModelDisplayOptions Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.ViewModelDisplayOptions
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.TextEditorComponentData, Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.TextEditorComponentData.
TextEditorViewModelDisplay Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.TextEditorViewModelDisplay
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.TextEditorComponentData, Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.TextEditorComponentData.
IDispatcher Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.Dispatcher
Referenced by Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.HandleAfterOnKeyDownAsync, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.HandleAfterOnKeyDownRangeAsync, Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.TextEditorComponentData, Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.TextEditorComponentData.
IServiceProvider Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.ServiceProvider
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.TextEditorComponentData, Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.TextEditorComponentData.
Task Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.MouseStoppedMovingTask
Task Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.MouseNoLongerOverTooltipTask
CancellationTokenSource Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.MouseNoLongerOverTooltipCancellationTokenSource
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.ContinueRenderingTooltipAsync.
CancellationTokenSource Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.MouseStoppedMovingCancellationTokenSource
bool Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.ThinksLeftMouseButtonIsDown
This accounts for one who might hold down Left Mouse Button from outside the TextEditorDisplay's content div then move their mouse over the content div while holding the Left Mouse Button down.
bool Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.MenuShouldTakeFocus
Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.TextEditorComponentData(Guid textEditorHtmlElementId, ViewModelDisplayOptions viewModelDisplayOptions, TextEditorOptions options, TextEditorViewModelDisplay textEditorViewModelDisplay, IDispatcher dispatcher, IServiceProvider serviceProvider)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.Dispatcher, Luthetus.TextEditor.RazorLib.TextEditors.Models.dispatcher, Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.Options, Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.ServiceProvider, Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.TextEditorHtmlElementId, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptions, Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.TextEditorViewModelDisplay, Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.ViewModelDisplayOptions.
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.TextEditorComponentData.
Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.TextEditorComponentData(TextEditorComponentData otherComponentData, Keymap keymap)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.Dispatcher, Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.Options, Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.ServiceProvider, Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.TextEditorComponentData, Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.TextEditorHtmlElementId, Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.TextEditorViewModelDisplay, Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.ViewModelDisplayOptions.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.ThrottleApplySyntaxHighlighting(TextEditorModelModifier modelModifier)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.CompilerService, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ResourceUri.
Referenced by Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.HandleAfterOnKeyDownAsync, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.HandleAfterOnKeyDownRangeAsync.
Task Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.ContinueRenderingTooltipAsync()
References Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.MouseNoLongerOverTooltipCancellationTokenSource.
Referenced by Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.HandleMouseStoppedMovingEventAsync.