Luthetus::Common::Tests::Basis::Resizes::Models::ResizeHelperTests
double Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.width
Referenced by Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.GetPixelMeasurementsTuple.
double double Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.height
Referenced by Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.GetPixelMeasurementsTuple.
double double double Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.left
Referenced by Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.GetPixelMeasurementsTuple.
void Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.ResizeNorth()
ResizeHelper.ResizeNorth(ElementDimensions, MouseEventArgs, MouseEventArgs)
References Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.GetPixelMeasurementsTuple, Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.ResizeNorth.
void Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.ResizeEast()
ResizeHelper.ResizeEast(ElementDimensions, MouseEventArgs, MouseEventArgs)
References Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.GetPixelMeasurementsTuple, Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.ResizeEast.
void Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.ResizeSouth()
ResizeHelper.ResizeSouth(ElementDimensions, MouseEventArgs, MouseEventArgs)
References Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.GetPixelMeasurementsTuple, Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.ResizeSouth.
void Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.ResizeWest()
ResizeHelper.ResizeWest(ElementDimensions, MouseEventArgs, MouseEventArgs)
References Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.GetPixelMeasurementsTuple, Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.ResizeWest.
void Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.ResizeNorthEast()
ResizeHelper.ResizeNorthEast(ElementDimensions, MouseEventArgs, MouseEventArgs)
References Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.GetPixelMeasurementsTuple, Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.ResizeNorthEast.
void Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.ResizeSouthEast()
ResizeHelper.ResizeSouthEast(ElementDimensions, MouseEventArgs, MouseEventArgs)
References Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.GetPixelMeasurementsTuple, Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.ResizeSouthEast.
void Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.ResizeSouthWest()
ResizeHelper.ResizeSouthWest(ElementDimensions, MouseEventArgs, MouseEventArgs)
References Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.GetPixelMeasurementsTuple, Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.ResizeSouthWest.
void Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.ResizeNorthWest()
ResizeHelper.ResizeNorthWest(ElementDimensions, MouseEventArgs, MouseEventArgs)
References Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.GetPixelMeasurementsTuple, Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.ResizeNorthWest.
void Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.Move()
ResizeHelper.Move(ElementDimensions, MouseEventArgs, MouseEventArgs)
References Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.GetPixelMeasurementsTuple, Luthetus.Common.RazorLib.Resizes.Models.ResizeHelper.Move.
double double double double top Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.GetPixelMeasurementsTuple(ElementDimensions elementDimensions)
References Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.height, Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.left, Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.width.
Referenced by Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.Move, Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.ResizeEast, Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.ResizeNorth, Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.ResizeNorthEast, Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.ResizeNorthWest, Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.ResizeSouth, Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.ResizeSouthEast, Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.ResizeSouthWest, Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.ResizeWest.
void Luthetus.Common.Tests.Basis.Resizes.Models.ResizeHelperTests.InitializeResizeHelperTests(out ElementDimensions elementDimensions)