Luthetus::TextEditor::RazorLib::TextEditors::Models::TextEditorViewModelApi
readonly ITextEditorService Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi._textEditorService
readonly IBackgroundTaskService Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi._backgroundTaskService
readonly IState<TextEditorState> Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi._textEditorStateWrap
readonly IDispatcher Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi._dispatcher
readonly IDialogService Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi._dialogService
readonly IJSRuntime Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi._jsRuntime
Task Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi._cursorShouldBlinkTask
CancellationTokenSource Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi._cursorShouldBlinkCancellationTokenSource
TimeSpan Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi._blinkingCursorTaskDelay
bool Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.CursorShouldBlink
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.SetCursorShouldBlink.
Action? Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.CursorShouldBlinkChanged
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.SetCursorShouldBlink.
Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.TextEditorViewModelApi(ITextEditorService textEditorService, IBackgroundTaskService backgroundTaskService, IState< TextEditorState > textEditorStateWrap, IJSRuntime jsRuntime, IDispatcher dispatcher, IDialogService dialogService)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.dialogService, Luthetus.TextEditor.RazorLib.TextEditors.Models.dispatcher, Luthetus.TextEditor.RazorLib.TextEditors.Models.jsRuntime, Luthetus.TextEditor.RazorLib.TextEditors.Models.textEditorService.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.SetCursorShouldBlink(bool cursorShouldBlink)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.CursorShouldBlink, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.CursorShouldBlinkChanged.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.Register(Key< TextEditorViewModel > viewModelKey, ResourceUri resourceUri, Category category)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.Category, Luthetus.TextEditor.RazorLib.TextEditors.Models.category, Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri, Luthetus.TextEditor.RazorLib.TextEditors.States.TextEditorState.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.Register(TextEditorViewModel viewModel)
References Luthetus.TextEditor.RazorLib.TextEditors.States.TextEditorState, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModel.
TextEditorViewModel? Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.GetOrDefault(Key< TextEditorViewModel > viewModelKey)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModel.
Dictionary< Key< TextEditorViewModel >, TextEditorViewModel > Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.GetViewModels()
Returns a shallow copy.
One should store the result of invoking this method in a variable, then reference that variable. If one continually invokes this, there is no guarantee that the data had not changed since the previous invocation.
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModel.
TextEditorModel? Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.GetModelOrDefault(Key< TextEditorViewModel > viewModelKey)
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.GetAllText.
string? Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.GetAllText(Key< TextEditorViewModel > viewModelKey)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.GetModelOrDefault.
async Task< TextEditorDimensions > Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.GetTextEditorMeasurementsAsync(string elementId)
async Task< CharAndLineMeasurements > Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.MeasureCharacterWidthAndLineHeightAsync(string measureCharacterWidthAndLineHeightElementId, int countOfTestCharacters)
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.SetScrollPosition(ITextEditorEditContext editContext, TextEditorViewModelModifier viewModelModifier, double? scrollLeftInPixels, double? scrollTopInPixels)
If a parameter is null the JavaScript will not modify that value.
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ScrollbarDimensions, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelModifier.ViewModel.
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.ScrollIntoView.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.MutateScrollVerticalPosition(ITextEditorEditContext editContext, TextEditorViewModelModifier viewModelModifier, double pixels)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ScrollbarDimensions, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelModifier.ViewModel.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.MutateScrollHorizontalPosition(ITextEditorEditContext editContext, TextEditorViewModelModifier viewModelModifier, double pixels)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ScrollbarDimensions, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelModifier.ViewModel.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.ScrollIntoView(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, TextEditorTextSpan textSpan)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.SetScrollPosition, Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelModifier.ViewModel.
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.RevealCursor.
async Task Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.FocusPrimaryCursorAsync(string primaryCursorContentId)
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.MoveCursor(KeymapArgs keymapArgs, ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetPrimaryCursorModifier, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.MoveCursorUnsafe.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.MoveCursorUnsafe(KeymapArgs keymapArgs, ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCursorModifier cursorModifier)
If one wants to guarantee that the state is up to date use MoveCursor instead of this method. This is because, the ITextEditorService will provide you the latest instance of the given TextEditorCursor. As opposed to whatever instance of the TextEditorCursorModifier you have at time of enqueueing. This method is needed however, because if one wants to arbitrarily create a cursor that does not map to the view model's cursors, then one would use this method. Since an attempt to map the cursor key would come back as the cursor not existing.
References Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.AltKey, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursorModifier.ColumnIndex, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.CtrlKey, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.Key, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.LineCount, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursorModifier.LineIndex, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursorModifier.PreferredColumnIndex, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.RichCharacterList, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursorModifier.SelectionAnchorPositionIndex, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursorModifier.SelectionEndingPositionIndex, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursorModifier.SetColumnIndexAndPreferred, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.ShiftKey, Luthetus.TextEditor.RazorLib.Characters.Models.RichCharacter.Value.
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.MoveCursor.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.CursorMovePageTop(ITextEditorEditContext editContext, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.CursorMovePageTopUnsafe, Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetPrimaryCursorModifier.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.CursorMovePageTopUnsafe(ITextEditorEditContext editContext, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCursorModifier cursorModifier)
If one wants to guarantee that the state is up to date use CursorMovePageTopFactory instead of this method. This is because, the ITextEditorService will provide you the latest instance of the given TextEditorCursor. As opposed to whatever instance of the TextEditorCursorModifier you have at time of enqueueing. This method is needed however, because if one wants to arbitrarily create a cursor that does not map to the view model's cursors, then one would use this method. Since an attempt to map the cursor key would come back as the cursor not existing.
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelModifier.ViewModel.
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.CursorMovePageTop.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.CursorMovePageBottom(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.CursorMovePageBottomUnsafe, Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetPrimaryCursorModifier.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.CursorMovePageBottomUnsafe(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCursorModifier cursorModifier)
If one wants to guarantee that the state is up to date use CursorMovePageBottomFactory instead of this method. This is because, the ITextEditorService will provide you the latest instance of the given TextEditorCursor. As opposed to whatever instance of the TextEditorCursorModifier you have at time of enqueueing. This method is needed however, because if one wants to arbitrarily create a cursor that does not map to the view model's cursors, then one would use this method. Since an attempt to map the cursor key would come back as the cursor not existing.
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelModifier.ViewModel.
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.CursorMovePageBottom.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.RevealCursor(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCursorModifier cursorModifier)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.ResourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.ScrollIntoView, Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelModifier.ViewModel.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.CalculateVirtualizationResult(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CancellationToken cancellationToken)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetCursorModifierBag, Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetPrimaryCursorModifier, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.LineCount, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.LineEndList, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.MostCharactersOnASingleLineTuple, Luthetus.TextEditor.RazorLib.TextEditors.Models.ScrollbarDimensions, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModel.TAB_WIDTH, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelModifier.ViewModel, Luthetus.TextEditor.RazorLib.Virtualizations.Models.VirtualizationBoundary, Luthetus.TextEditor.RazorLib.TextEditors.Models.VirtualizationResult, Luthetus.TextEditor.RazorLib.TextEditors.Models.virtualizationResult.
async Task Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.RemeasureAsync(ITextEditorEditContext editContext, TextEditorViewModelModifier viewModelModifier, string measureCharacterWidthAndLineHeightElementId, int countOfTestCharacters, CancellationToken cancellationToken)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.CharAndLineMeasurements, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorDimensions, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelModifier.ViewModel.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.ForceRender(ITextEditorEditContext editContext, TextEditorViewModelModifier viewModelModifier, CancellationToken cancellationToken)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetViewModelModifier, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelModifier.ViewModel.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.Dispose(Key< TextEditorViewModel > viewModelKey)
References Luthetus.TextEditor.RazorLib.TextEditors.States.TextEditorState.