Luthetus::Common::RazorLib::FileSystems::Models::IEnvironmentProvider
IAbsolutePath Luthetus.Common.RazorLib.FileSystems.Models.IEnvironmentProvider.HomeDirectoryAbsolutePath
IAbsolutePath Luthetus.Common.RazorLib.FileSystems.Models.IEnvironmentProvider.RootDirectoryAbsolutePath
IAbsolutePath Luthetus.Common.RazorLib.FileSystems.Models.IEnvironmentProvider.SafeRoamingApplicationDataDirectoryAbsolutePath
The ActualRoamingApplicationDataDirectoryAbsolutePath but with "/Luthetus/" appended.
IAbsolutePath Luthetus.Common.RazorLib.FileSystems.Models.IEnvironmentProvider.SafeLocalApplicationDataDirectoryAbsolutePath
The ActualLocalApplicationDataDirectoryAbsolutePath but with "/Luthetus/" appended.
IAbsolutePath Luthetus.Common.RazorLib.FileSystems.Models.IEnvironmentProvider.ActualRoamingApplicationDataDirectoryAbsolutePath
IAbsolutePath Luthetus.Common.RazorLib.FileSystems.Models.IEnvironmentProvider.ActualLocalApplicationDataDirectoryAbsolutePath
string Luthetus.Common.RazorLib.FileSystems.Models.IEnvironmentProvider.DriveExecutingFromNoDirectorySeparator
If one is executing the program from the absolute path "C:\Programs\..." then this is "C:". This property is needed in order to disambiguate when given: "\Homework\math.txt" versus "C:\Homework\math.txt". .
Consider the creation of a text editor model. This property allows the previous example of ambiguous paths to map to the same TextEditorModel.
char Luthetus.Common.RazorLib.FileSystems.Models.IEnvironmentProvider.DirectorySeparatorChar
Referenced by Luthetus.Extensions.DotNet.Websites.WebsiteDotNetCliHelper.StartNewCSharpProjectCommand.
char Luthetus.Common.RazorLib.FileSystems.Models.IEnvironmentProvider.AltDirectorySeparatorChar
ImmutableHashSet<SimplePath> Luthetus.Common.RazorLib.FileSystems.Models.IEnvironmentProvider.DeletionPermittedPathList
Any operation which would delete a file system entry, is to first check these paths for if that file is allowed to be deleted. This will be done via the IFileSystemProvider, IFileHandler, and IDirectoryHandler. Limitations of this approach: the .NET API for deleting a directory could be invoked instead of IDirectoryHandler.DeleteAsync(string, bool, CancellationToken). In this case, the interface cannot check if the path is allowed to be deleted, since a different API entirely was used. Another limitiation is that the implementor of a given IFileSystemProvider, IFileHandler, or IDirectoryHandler can do as they'd like with the given implementation details. If an interface can be swapped at runtime, could this a security concern of some sort? Requirements for all to go as planned: only vetted interface implementation should be permitted. TODO: how can one ensure the vetted interface implementation isn't at runtime swapped for an unsafe one? Remark: I intend for these paths to be simple. I don't want to try and be 'smart' and interpret what your path means. That is to say, these are just strings. I intent to do a simple '==' check or, a '.StartsWith()' of sorts. If a directory is provided, then that directory, and any sub filesystem-entries are permitted for deletion. If a file is provided, then that file only becomes permitted for deletion. Should one open a solution, I plan to implement that, the folder which encompasses that solution file becomes permitted for deletion. Even this though I wonder, might one want to open a solution 'read-only'?
ImmutableHashSet<SimplePath> Luthetus.Common.RazorLib.FileSystems.Models.IEnvironmentProvider.ProtectedPathList
bool Luthetus.Common.RazorLib.FileSystems.Models.IEnvironmentProvider.IsDirectorySeparator(char input)
string Luthetus.Common.RazorLib.FileSystems.Models.IEnvironmentProvider.GetRandomFileName()
IAbsolutePath Luthetus.Common.RazorLib.FileSystems.Models.IEnvironmentProvider.AbsolutePathFactory(string path, bool isDirectory)
Referenced by Luthetus.Ide.Tests.Basis.TreeViewImplementations.Models.TreeViewAbsolutePathTests.Constructor, Luthetus.Common.RazorLib.FileSystems.Models.IAbsolutePath.Factory, Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationDrawingCircle< TItem >.GetMenuOptionRecord, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.QuickActionsSlashRefactor, Luthetus.CompilerServices.Razor.RazorSyntaxTree.RazorSyntaxTree, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.RelatedFilesQuickPick, Luthetus.Extensions.DotNet.Websites.WebsiteDotNetCliHelper.StartNewCSharpProjectCommand.
IRelativePath Luthetus.Common.RazorLib.FileSystems.Models.IEnvironmentProvider.RelativePathFactory(string path, bool isDirectory)
Referenced by Luthetus.Common.RazorLib.FileSystems.Models.IRelativePath.Factory.
string Luthetus.Common.RazorLib.FileSystems.Models.IEnvironmentProvider.JoinPaths(string pathOne, string pathTwo)
Takes two absolute file path strings and makes one singular string with the DirectorySeparatorChar between the two.
Referenced by Luthetus.Extensions.DotNet.Websites.WebsiteDotNetCliHelper.StartNewCSharpProjectCommand.
void Luthetus.Common.RazorLib.FileSystems.Models.IEnvironmentProvider.AssertDeletionPermitted(string path, bool isDirectory)
void Luthetus.Common.RazorLib.FileSystems.Models.IEnvironmentProvider.DeletionPermittedRegister(SimplePath simplePath)
The parameters to this method are deliberately SimplePath, whereas the parameters to AssertDeletionPermitted(string, bool) are string, and bool. This method uses the wording 'Register' in its name instead of a more natural 'Add' wording deliberately. These steps were taken in order to reduce the chance that one accidentally uses one method, when meant the other.
References Luthetus.Common.RazorLib.FileSystems.Models.SimplePath.
void Luthetus.Common.RazorLib.FileSystems.Models.IEnvironmentProvider.DeletionPermittedDispose(SimplePath simplePath)
References Luthetus.Common.RazorLib.FileSystems.Models.SimplePath.
void Luthetus.Common.RazorLib.FileSystems.Models.IEnvironmentProvider.ProtectedPathsRegister(SimplePath simplePath)
References Luthetus.Common.RazorLib.FileSystems.Models.SimplePath.
void Luthetus.Common.RazorLib.FileSystems.Models.IEnvironmentProvider.ProtectedPathsDispose(SimplePath simplePath)
References Luthetus.Common.RazorLib.FileSystems.Models.SimplePath.