Luthetus::Ide::RazorLib::Terminals::Models::ITerminal
Key<ITerminal> Luthetus.Ide.RazorLib.Terminals.Models.ITerminal.Key
string Luthetus.Ide.RazorLib.Terminals.Models.ITerminal.DisplayName
ITerminalInteractive Luthetus.Ide.RazorLib.Terminals.Models.ITerminal.TerminalInteractive
ITerminalInput Luthetus.Ide.RazorLib.Terminals.Models.ITerminal.TerminalInput
ITerminalOutput Luthetus.Ide.RazorLib.Terminals.Models.ITerminal.TerminalOutput
bool Luthetus.Ide.RazorLib.Terminals.Models.ITerminal.HasExecutingProcess
void Luthetus.Ide.RazorLib.Terminals.Models.ITerminal.EnqueueCommand(TerminalCommandRequest terminalCommandRequest)
Referenced by Luthetus.Extensions.DotNet.Menus.Models.DotNetMenuOptionsFactory.PerformAddProjectToProjectReference, Luthetus.Extensions.DotNet.Menus.Models.DotNetMenuOptionsFactory.PerformMoveProjectToSolutionFolder, Luthetus.Extensions.DotNet.Menus.Models.DotNetMenuOptionsFactory.PerformRemoveNuGetPackageReferenceFromProject, Luthetus.Extensions.DotNet.Menus.Models.DotNetMenuOptionsFactory.PerformRemoveProjectToProjectReference.
Task Luthetus.Ide.RazorLib.Terminals.Models.ITerminal.EnqueueCommandAsync(TerminalCommandRequest terminalCommandRequest)
void Luthetus.Ide.RazorLib.Terminals.Models.ITerminal.ClearEnqueue()
This will enqueue the command with text "clear". Thus, it will only execute when it is its turn in the queue.
void Luthetus.Ide.RazorLib.Terminals.Models.ITerminal.ClearFireAndForget()
This will invoke the ITerminalOutput.ClearOutput method, by using '_ = Task.Run(...)'.
This will execute EVEN IF a command in the queue is currently being executed. The fire and forget is because the terminal ITerminalOutput wraps any state mutation in a 'lock(...) { }'. So, the fire and forget is to avoid freezing the UI.
void Luthetus.Ide.RazorLib.Terminals.Models.ITerminal.KillProcess()