Luthetus::Common::RazorLib::BackgroundTasks::Models::IBackgroundTask
Key<IBackgroundTask> Luthetus.Common.RazorLib.BackgroundTasks.Models.IBackgroundTask.BackgroundTaskKey
Referenced by Luthetus.Common.RazorLib.BackgroundTasks.Models.BackgroundTaskService.EnqueueAsync.
Key<IBackgroundTaskQueue> Luthetus.Common.RazorLib.BackgroundTasks.Models.IBackgroundTask.QueueKey
Referenced by Luthetus.Common.RazorLib.BackgroundTasks.Models.BackgroundTaskService.Enqueue, Luthetus.Common.RazorLib.BackgroundTasks.Models.BackgroundTaskServiceSynchronous.Enqueue, Luthetus.Common.RazorLib.BackgroundTasks.Models.BackgroundTaskService.EnqueueAsync.
string Luthetus.Common.RazorLib.BackgroundTasks.Models.IBackgroundTask.Name
IBackgroundTask? Luthetus.Common.RazorLib.BackgroundTasks.Models.IBackgroundTask.BatchOrDefault(IBackgroundTask oldEvent)
Before a throttle event is enqueued, this method is invoked. This allows for batching of 'this' throttle event instance, and the last entry of the queue. .
This method is invoked from within a 'lock(_queue) { ... }'. Example use: one reads an entry from the queue, its an event that write out a character. Perhaps this throttle event also writes out a character. Instead of invoking 'text.Insert(character)' two times. One might want to invoke 'text.InsertRange(bothCharacters)'; Returning null means enqueue the recentEvent without any batching, (leave the old event as it was within the queue)
Referenced by Luthetus.Common.RazorLib.BackgroundTasks.Models.BackgroundTaskQueue.Enqueue, Luthetus.Common.RazorLib.Reactives.Models.ThrottleEventQueueAsync.EnqueueAsync.
Task Luthetus.Common.RazorLib.BackgroundTasks.Models.IBackgroundTask.HandleEvent(CancellationToken cancellationToken)
This method is the actual work item that gets awaited in order to handle the event.
Referenced by Luthetus.Common.RazorLib.BackgroundTasks.Models.BackgroundTaskServiceSynchronous.Enqueue.