Luthetus::TextEditor::RazorLib::TextEditors::Models::ITextEditorModelApi
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorModelApi.RegisterCustom(TextEditorModel model)
It is recommended to use the RegisterTemplated method as it will internally reference the ITextEditorLexer and IDecorationMapper that correspond to the desired text editor.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorModelApi.RegisterTemplated(string extensionNoPeriod, ResourceUri resourceUri, DateTime resourceLastWriteTime, string initialContent, string? overrideDisplayTextForFileExtension=null)
Plain Text Editor: one would pass in an extensionNoPeriod of "txt" or the constant varible: ExtensionNoPeriodFacts.TXT. .
C# Text Editor: one would pass in an extensionNoPeriod of "cs" or the constant varible: ExtensionNoPeriodFacts.C_SHARP_CLASS; NOTE: One must first install the Luthetus.CompilerServices.CSharp NuGet package.
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri.
Dictionary< ResourceUri, TextEditorModel > Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorModelApi.GetModels()
Returns a shallow copy.
One should store the result of invoking this method in a variable, then reference that variable. If one continually invokes this, there is no guarantee that the data had not changed since the previous invocation.
int Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorModelApi.GetModelsCount()
TextEditorModel? Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorModelApi.GetOrDefault(ResourceUri resourceUri)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri.
Referenced by Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.GoToDefinition.
ImmutableArray< TextEditorViewModel > Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorModelApi.GetViewModelsOrEmpty(ResourceUri resourceUri)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri.
Referenced by Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.GoToDefinition.
string? Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorModelApi.GetAllText(ResourceUri resourceUri)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorModelApi.UndoEdit(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier)
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorModelApi.SetUsingLineEndKind(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, LineEndKind lineEndKind)
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.FooterDriver.SelectRowEndingKindOnChange.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorModelApi.SetResourceData(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, DateTime resourceLastWriteTime)
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorModelApi.Reload(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, string content, DateTime resourceLastWriteTime)
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorModelApi.RedoEdit(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier)
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorModelApi.InsertText(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, CursorModifierBagTextEditor cursorModifierBag, string content, CancellationToken cancellationToken)
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorModelApi.InsertTextUnsafe(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, CursorModifierBagTextEditor cursorModifierBag, string content, CancellationToken cancellationToken)
If one wants to guarantee that the state is up to date use InsertTextFactory instead of this method. This is because, the ITextEditorService will provide you the latest instance of the given TextEditorCursor. As opposed to whatever instance of the TextEditorCursorModifier you have at time of enqueueing. This method is needed however, because if one wants to arbitrarily create a cursor that does not map to the view model's cursors, then one would use this method. Since an attempt to map the cursor key would come back as the cursor not existing.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorModelApi.HandleKeyboardEvent(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, CursorModifierBagTextEditor cursorModifierBag, KeymapArgs keymapArgs, CancellationToken cancellationToken)
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorModelApi.HandleKeyboardEventUnsafe(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, CursorModifierBagTextEditor cursorModifierBag, KeymapArgs keymapArgs, CancellationToken cancellationToken)
If one wants to guarantee that the state is up to date use HandleKeyboardEvent instead of this method. This is because, the ITextEditorService will provide you the latest instance of the given TextEditorCursor. As opposed to whatever instance of the TextEditorCursorModifier you have at time of enqueueing. This method is needed however, because if one wants to arbitrarily create a cursor that does not map to the view model's cursors, then one would use this method. Since an attempt to map the cursor key would come back as the cursor not existing.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorModelApi.DeleteTextByRange(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, CursorModifierBagTextEditor cursorModifierBag, int count, CancellationToken cancellationToken)
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorModelApi.DeleteTextByRangeUnsafe(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, CursorModifierBagTextEditor cursorModifierBag, int count, CancellationToken cancellationToken)
If one wants to guarantee that the state is up to date use DeleteTextByRangeFactory instead of this method. This is because, the ITextEditorService will provide you the latest instance of the given TextEditorCursor. As opposed to whatever instance of the TextEditorCursorModifier you have at time of enqueueing. This method is needed however, because if one wants to arbitrarily create a cursor that does not map to the view model's cursors, then one would use this method. Since an attempt to map the cursor key would come back as the cursor not existing.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorModelApi.DeleteTextByMotion(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, CursorModifierBagTextEditor cursorModifierBag, MotionKind motionKind, CancellationToken cancellationToken)
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorModelApi.DeleteTextByMotionUnsafe(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, CursorModifierBagTextEditor cursorModifierBag, MotionKind motionKind, CancellationToken cancellationToken)
If one wants to guarantee that the state is up to date use DeleteTextByMotionFactory instead of this method. This is because, the ITextEditorService will provide you the latest instance of the given TextEditorCursor. As opposed to whatever instance of the TextEditorCursorModifier you have at time of enqueueing. This method is needed however, because if one wants to arbitrarily create a cursor that does not map to the view model's cursors, then one would use this method. Since an attempt to map the cursor key would come back as the cursor not existing.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorModelApi.AddPresentationModel(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorPresentationModel emptyPresentationModel)
References Luthetus.TextEditor.RazorLib.Decorations.Models.TextEditorPresentationModel.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorModelApi.StartPendingCalculatePresentationModel(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, Key< TextEditorPresentationModel > presentationKey, TextEditorPresentationModel emptyPresentationModel)
emptyPresentationModel If the presentation model was not found, the empty presentation model will be registered.
References Luthetus.TextEditor.RazorLib.Decorations.Models.TextEditorPresentationModel.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorModelApi.CompletePendingCalculatePresentationModel(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, Key< TextEditorPresentationModel > presentationKey, TextEditorPresentationModel emptyPresentationModel, ImmutableArray< TextEditorTextSpan > calculatedTextSpans)
emptyPresentationModel If the presentation model was not found, the empty presentation model will be registered.
References Luthetus.TextEditor.RazorLib.Decorations.Models.TextEditorPresentationModel.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorModelApi.ApplyDecorationRange(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, IEnumerable< TextEditorTextSpan > textSpans)
If applying syntax highlighting it may be preferred to use ApplySyntaxHighlightingAsync. It is effectively just invoking the lexer and then ApplyDecorationRange.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorModelApi.ApplySyntaxHighlighting(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier)
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.ParseAsync.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorModelApi.Dispose(ResourceUri resourceUri)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri.