Luthetus::TextEditor::RazorLib::TextEditors::Models::ITextEditorEditContext
Dictionary<ResourceUri, TextEditorModelModifier?> Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.ModelCache
Dictionary<Key<TextEditorViewModel>, ResourceUri?> Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.ViewModelToModelResourceUriCache
Dictionary<Key<TextEditorViewModel>, TextEditorViewModelModifier?> Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.ViewModelCache
Dictionary<Key<TextEditorViewModel>, CursorModifierBagTextEditor?> Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.CursorModifierBagCache
ITextEditorService Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.TextEditorService
Referenced by Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.GoToMatchingCharacter, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.ParseAsync, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.ScrollLineDown, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.ScrollLineUp, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.ScrollPageDown, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.ScrollPageUp, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.TriggerRemeasure.
Key<TextEditorAuthenticatedAction> Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.AuthenticatedActionKey
TextEditorModelModifier? Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetModelModifier(ResourceUri modelResourceUri, bool isReadonly=false)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri.
Referenced by Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.GoToDefinition, Luthetus.TextEditor.RazorLib.TextEditorService.ValidateMaximumScrollLeftAndScrollTop.
TextEditorModelModifier? Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetModelModifierByViewModelKey(Key< TextEditorViewModel > viewModelKey, bool isReadonly=false)
TextEditorViewModelModifier? Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetViewModelModifier(Key< TextEditorViewModel > viewModelKey, bool isReadonly=false)
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.ForceRender, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.GoToDefinition.
CursorModifierBagTextEditor? Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetCursorModifierBag(TextEditorViewModel? viewModel)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModel.
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.CalculateVirtualizationResult, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.GoToDefinition.
TextEditorCursorModifier? Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetPrimaryCursorModifier(CursorModifierBagTextEditor? cursorModifierBag)
TODO: Caching for this method? .
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.CalculateVirtualizationResult, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.ClearTextSelection, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.CopyAsync, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.CursorMovePageBottom, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.CursorMovePageBottom, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.CursorMovePageTop, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.CursorMovePageTop, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.CutAsync, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.Duplicate, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.GoToDefinition, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.GoToMatchingCharacter, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.HandleAfterOnKeyDownAsync, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.HandleAfterOnKeyDownRangeAsync, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.IndentLess, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.IndentMore, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.MoveCursor, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.MoveLineDown, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.MoveLineUp, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.NewLineAbove, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.NewLineBelow, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.PasteAsync, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.QuickActionsSlashRefactor, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.SelectAll, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.TriggerSave.
TextEditorDiffModelModifier? Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorEditContext.GetDiffModelModifier(Key< TextEditorDiffModel > diffModelKey, bool isReadonly=false)