Luthetus::TextEditor::RazorLib::CompilerServices::Syntax::Nodes::Interfaces::ICodeBlockOwner
ScopeDirectionKind Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.ICodeBlockOwner.ScopeDirectionKind
OpenBraceToken Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.ICodeBlockOwner.OpenBraceToken
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.ICodeBlockOwner.SetOpenBraceToken.
CloseBraceToken Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.ICodeBlockOwner.CloseBraceToken
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.ICodeBlockOwner.SetCloseBraceToken.
StatementDelimiterToken Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.ICodeBlockOwner.StatementDelimiterToken
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.ICodeBlockOwner.SetStatementDelimiterToken.
CodeBlockNode? Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.ICodeBlockOwner.CodeBlockNode
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.ICodeBlockOwner.SetCodeBlockNode.
bool Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.ICodeBlockOwner.IsSingleStatementBody
TypeClauseNode? Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.ICodeBlockOwner.GetReturnTypeClauseNode()
ICodeBlockOwner Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.ICodeBlockOwner.SetOpenBraceToken(OpenBraceToken openBraceToken, IParserModel parserModel)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.ICodeBlockOwner.OpenBraceToken.
ICodeBlockOwner Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.ICodeBlockOwner.SetCloseBraceToken(CloseBraceToken closeBraceToken, IParserModel parserModel)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.ICodeBlockOwner.CloseBraceToken.
ICodeBlockOwner Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.ICodeBlockOwner.SetStatementDelimiterToken(StatementDelimiterToken statementDelimiterToken, IParserModel parserModel)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.ICodeBlockOwner.StatementDelimiterToken.
ICodeBlockOwner Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.ICodeBlockOwner.SetCodeBlockNode(CodeBlockNode codeBlockNode, IParserModel parserModel)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.ICodeBlockOwner.CodeBlockNode.
void Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.ICodeBlockOwner.OnBoundScopeCreatedAndSetAsCurrent(IParserModel parserModel)
Once the code block owner's scope has been constructed, this method gives them an opportunity to pull any variables into scope that ought to be there. As well, the current code block builder will have been updated.
(i.e.: a function definition's arguments)
static void Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.ICodeBlockOwner.ThrowMultipleScopeDelimiterException(IParserModel parserModel)
References Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IParserModel.DiagnosticBag, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportTodoException, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IParserModel.TokenWalker.
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ArbitraryCodeBlockNode.SetCloseBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorDefinitionNode.SetCloseBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.DoWhileStatementNode.SetCloseBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ForeachStatementNode.SetCloseBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ForStatementNode.SetCloseBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionDefinitionNode.SetCloseBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.IfStatementNode.SetCloseBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.LockStatementNode.SetCloseBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.NamespaceStatementNode.SetCloseBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.SwitchExpressionNode.SetCloseBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.SwitchStatementNode.SetCloseBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TryStatementCatchNode.SetCloseBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TryStatementFinallyNode.SetCloseBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TryStatementTryNode.SetCloseBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.SetCloseBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.WhileStatementNode.SetCloseBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ArbitraryCodeBlockNode.SetOpenBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorDefinitionNode.SetOpenBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.DoWhileStatementNode.SetOpenBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ForeachStatementNode.SetOpenBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ForStatementNode.SetOpenBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionDefinitionNode.SetOpenBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.IfStatementNode.SetOpenBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.LockStatementNode.SetOpenBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.NamespaceStatementNode.SetOpenBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.SwitchExpressionNode.SetOpenBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.SwitchStatementNode.SetOpenBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TryStatementCatchNode.SetOpenBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TryStatementFinallyNode.SetOpenBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TryStatementTryNode.SetOpenBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.SetOpenBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.WhileStatementNode.SetOpenBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ArbitraryCodeBlockNode.SetStatementDelimiterToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorDefinitionNode.SetStatementDelimiterToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.DoWhileStatementNode.SetStatementDelimiterToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ForeachStatementNode.SetStatementDelimiterToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ForStatementNode.SetStatementDelimiterToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionDefinitionNode.SetStatementDelimiterToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.IfStatementNode.SetStatementDelimiterToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.LockStatementNode.SetStatementDelimiterToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.NamespaceStatementNode.SetStatementDelimiterToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.SwitchExpressionNode.SetStatementDelimiterToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.SwitchStatementNode.SetStatementDelimiterToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TryStatementCatchNode.SetStatementDelimiterToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TryStatementFinallyNode.SetStatementDelimiterToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TryStatementTryNode.SetStatementDelimiterToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.SetStatementDelimiterToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.WhileStatementNode.SetStatementDelimiterToken.
static void Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.Interfaces.ICodeBlockOwner.ThrowAlreadyAssignedCodeBlockNodeException(IParserModel parserModel)
References Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IParserModel.DiagnosticBag, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportTodoException, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IParserModel.TokenWalker.
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ArbitraryCodeBlockNode.SetCodeBlockNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ConstructorDefinitionNode.SetCodeBlockNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.DoWhileStatementNode.SetCodeBlockNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ForeachStatementNode.SetCodeBlockNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ForStatementNode.SetCodeBlockNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.FunctionDefinitionNode.SetCodeBlockNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.IfStatementNode.SetCodeBlockNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.LockStatementNode.SetCodeBlockNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.NamespaceStatementNode.SetCodeBlockNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.SwitchExpressionNode.SetCodeBlockNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.SwitchStatementNode.SetCodeBlockNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TryStatementCatchNode.SetCodeBlockNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TryStatementFinallyNode.SetCodeBlockNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TryStatementTryNode.SetCodeBlockNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.SetCodeBlockNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.WhileStatementNode.SetCodeBlockNode.