Luthetus::Common::RazorLib::Clipboards::Models::IClipboardService
Task< string > Luthetus.Common.RazorLib.Clipboards.Models.IClipboardService.ReadClipboard()
Referenced by Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.PasteAsync.
Task Luthetus.Common.RazorLib.Clipboards.Models.IClipboardService.SetClipboard(string value)
Referenced by Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.CopyAsync, Luthetus.TextEditor.Tests.Basis.Commands.Models.Defaults.TextEditorCommandDefaultFactsTests.Cut, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.CutAsync.