Luthetus::TextEditor::RazorLib::Options::Models::ITextEditorOptionsApi
void Luthetus.TextEditor.RazorLib.Options.Models.ITextEditorOptionsApi.ShowSettingsDialog(bool? isResizableOverride=null, string? cssClassString=null)
void Luthetus.TextEditor.RazorLib.Options.Models.ITextEditorOptionsApi.ShowFindAllDialog(bool? isResizableOverride=null, string? cssClassString=null)
void Luthetus.TextEditor.RazorLib.Options.Models.ITextEditorOptionsApi.SetCursorWidth(double cursorWidthInPixels, bool updateStorage=true)
Referenced by Luthetus.TextEditor.Tests.Basis.Options.Models.OptionsApiTests.SetCursorWidth.
void Luthetus.TextEditor.RazorLib.Options.Models.ITextEditorOptionsApi.SetFontFamily(string? fontFamily, bool updateStorage=true)
Referenced by Luthetus.TextEditor.Tests.Basis.Options.Models.OptionsApiTests.SetFontFamily.
void Luthetus.TextEditor.RazorLib.Options.Models.ITextEditorOptionsApi.SetFontSize(int fontSizeInPixels, bool updateStorage=true)
Referenced by Luthetus.TextEditor.Tests.Basis.Options.Models.OptionsApiTests.SetFontSize.
void Luthetus.TextEditor.RazorLib.Options.Models.ITextEditorOptionsApi.SetHeight(int? heightInPixels, bool updateStorage=true)
Referenced by Luthetus.TextEditor.Tests.Basis.Options.Models.OptionsApiTests.SetHeight.
void Luthetus.TextEditor.RazorLib.Options.Models.ITextEditorOptionsApi.SetKeymap(Keymap keymap, bool updateStorage=true)
Referenced by Luthetus.TextEditor.Tests.Basis.Options.Models.OptionsApiTests.SetKeymap.
void Luthetus.TextEditor.RazorLib.Options.Models.ITextEditorOptionsApi.SetShowNewlines(bool showNewlines, bool updateStorage=true)
Referenced by Luthetus.TextEditor.Tests.Basis.Options.Models.OptionsApiTests.SetShowNewlines.
void Luthetus.TextEditor.RazorLib.Options.Models.ITextEditorOptionsApi.SetUseMonospaceOptimizations(bool useMonospaceOptimizations, bool updateStorage=true)
Referenced by Luthetus.TextEditor.Tests.Basis.Options.Models.OptionsApiTests.SetUseMonospaceOptimizations.
void Luthetus.TextEditor.RazorLib.Options.Models.ITextEditorOptionsApi.SetShowWhitespace(bool showWhitespace, bool updateStorage=true)
Referenced by Luthetus.TextEditor.Tests.Basis.Options.Models.OptionsApiTests.SetShowWhitespace.
void Luthetus.TextEditor.RazorLib.Options.Models.ITextEditorOptionsApi.SetTheme(ThemeRecord theme, bool updateStorage=true)
This is setting the TextEditor's theme specifically. This is not to be confused with the AppOptions Themes which get applied at an application level. This allows for a "DarkTheme-Application" that has a "LightTheme-TextEditor".
References Luthetus.Common.RazorLib.Themes.Models.ThemeRecord.
Referenced by Luthetus.TextEditor.Tests.Basis.Options.Models.OptionsApiTests.SetTheme.
void Luthetus.TextEditor.RazorLib.Options.Models.ITextEditorOptionsApi.SetRenderStateKey(Key< RenderState > renderStateKey)
Referenced by Luthetus.TextEditor.Tests.Basis.Options.Models.OptionsApiTests.SetRenderStateKey.
Task Luthetus.TextEditor.RazorLib.Options.Models.ITextEditorOptionsApi.SetFromLocalStorageAsync()
void Luthetus.TextEditor.RazorLib.Options.Models.ITextEditorOptionsApi.WriteToStorage()
TextEditorOptions Luthetus.TextEditor.RazorLib.Options.Models.ITextEditorOptionsApi.GetOptions()
One should store the result of invoking this method in a variable, then reference that variable. If one continually invokes this, there is no guarantee that the data had not changed since the previous invocation.
References Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptions.
Referenced by Luthetus.TextEditor.Tests.Basis.Options.Models.OptionsApiTests.SetCursorWidth, Luthetus.TextEditor.Tests.Basis.Options.Models.OptionsApiTests.SetFontFamily, Luthetus.TextEditor.Tests.Basis.Options.Models.OptionsApiTests.SetFontSize, Luthetus.TextEditor.Tests.Basis.Options.Models.OptionsApiTests.SetHeight, Luthetus.TextEditor.Tests.Basis.Options.Models.OptionsApiTests.SetKeymap, Luthetus.TextEditor.Tests.Basis.Options.Models.OptionsApiTests.SetRenderStateKey, Luthetus.TextEditor.Tests.Basis.Options.Models.OptionsApiTests.SetShowNewlines, Luthetus.TextEditor.Tests.Basis.Options.Models.OptionsApiTests.SetShowWhitespace, Luthetus.TextEditor.Tests.Basis.Options.Models.OptionsApiTests.SetTheme, Luthetus.TextEditor.Tests.Basis.Options.Models.OptionsApiTests.SetUseMonospaceOptimizations.