Luthetus::TextEditor::RazorLib::TextEditors::Models::ITextEditorViewModelApi
bool Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.CursorShouldBlink
Action? Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.CursorShouldBlinkChanged
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.Register(Key< TextEditorViewModel > textEditorViewModelKey, ResourceUri resourceUri, Category category)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.Category, Luthetus.TextEditor.RazorLib.TextEditors.Models.category, Luthetus.TextEditor.RazorLib.TextEditors.Models.ResourceUri, Luthetus.TextEditor.RazorLib.TextEditors.Models.resourceUri.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.Register(TextEditorViewModel viewModel)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModel.
Dictionary< Key< TextEditorViewModel >, TextEditorViewModel > Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.GetViewModels()
Returns a shallow copy.
One should store the result of invoking this method in a variable, then reference that variable. If one continually invokes this, there is no guarantee that the data had not changed since the previous invocation.
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModel.
TextEditorModel? Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.GetModelOrDefault(Key< TextEditorViewModel > viewModelKey)
Task< TextEditorDimensions > Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.GetTextEditorMeasurementsAsync(string elementId)
Task< CharAndLineMeasurements > Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.MeasureCharacterWidthAndLineHeightAsync(string measureCharacterWidthAndLineHeightElementId, int countOfTestCharacters)
TextEditorViewModel? Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.GetOrDefault(Key< TextEditorViewModel > viewModelKey)
References Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModel.
Referenced by Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.QuickActionsSlashRefactor, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.RelatedFilesQuickPick.
string? Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.GetAllText(Key< TextEditorViewModel > viewModelKey)
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.SetCursorShouldBlink(bool cursorShouldBlink)
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.SetScrollPosition(ITextEditorEditContext editContext, TextEditorViewModelModifier viewModelModifier, double? scrollLeftInPixels, double? scrollTopInPixels)
If a parameter is null the JavaScript will not modify that value.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.ScrollIntoView(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, TextEditorTextSpan textSpan)
References Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.MutateScrollVerticalPosition(ITextEditorEditContext editContext, TextEditorViewModelModifier viewModelModifier, double pixels)
Referenced by Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.ScrollLineDown, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.ScrollLineUp, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.ScrollPageDown, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.ScrollPageUp.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.MutateScrollHorizontalPosition(ITextEditorEditContext editContext, TextEditorViewModelModifier viewModelModifier, double pixels)
Task Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.FocusPrimaryCursorAsync(string primaryCursorContentId)
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.MoveCursor(KeymapArgs keymapArgs, ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag)
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.MoveCursorUnsafe(KeymapArgs keymapArgs, ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCursorModifier primaryCursor)
If one wants to guarantee that the state is up to date use MoveCursor instead of this method. This is because, the ITextEditorService will provide you the latest instance of the given TextEditorCursor. As opposed to whatever instance of the TextEditorCursorModifier you have at time of enqueueing. This method is needed however, because if one wants to arbitrarily create a cursor that does not map to the view model's cursors, then one would use this method. Since an attempt to map the cursor key would come back as the cursor not existing.
Referenced by Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.GoToMatchingCharacter.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.CursorMovePageTop(ITextEditorEditContext editContext, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag)
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.CursorMovePageTopUnsafe(ITextEditorEditContext editContext, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCursorModifier primaryCursor)
If one wants to guarantee that the state is up to date use CursorMovePageTopFactory instead of this method. This is because, the ITextEditorService will provide you the latest instance of the given TextEditorCursor. As opposed to whatever instance of the TextEditorCursorModifier you have at time of enqueueing. This method is needed however, because if one wants to arbitrarily create a cursor that does not map to the view model's cursors, then one would use this method. Since an attempt to map the cursor key would come back as the cursor not existing.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.CursorMovePageBottom(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag)
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.CursorMovePageBottomUnsafe(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCursorModifier cursorModifier)
If one wants to guarantee that the state is up to date use CursorMovePageBottomFactory instead of this method. This is because, the ITextEditorService will provide you the latest instance of the given TextEditorCursor. As opposed to whatever instance of the TextEditorCursorModifier you have at time of enqueueing. This method is needed however, because if one wants to arbitrarily create a cursor that does not map to the view model's cursors, then one would use this method. Since an attempt to map the cursor key would come back as the cursor not existing.
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.RevealCursor(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CursorModifierBagTextEditor cursorModifierBag, TextEditorCursorModifier cursorModifier)
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.CalculateVirtualizationResult(ITextEditorEditContext editContext, TextEditorModelModifier modelModifier, TextEditorViewModelModifier viewModelModifier, CancellationToken cancellationToken)
Task Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.RemeasureAsync(ITextEditorEditContext editContext, TextEditorViewModelModifier viewModelModifier, string measureCharacterWidthAndLineHeightElementId, int countOfTestCharacters, CancellationToken cancellationToken)
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.ForceRender(ITextEditorEditContext editContext, TextEditorViewModelModifier viewModelModifier, CancellationToken cancellationToken)
void Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.Dispose(Key< TextEditorViewModel > viewModelKey)