Luthetus::TextEditor::RazorLib::CompilerServices::Interfaces::IBinder
ImmutableArray<TextEditorDiagnostic> Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.DiagnosticsList
ImmutableArray<ITextEditorSymbol> Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.SymbolsList
TextEditorTextSpan? Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.GetDefinition(TextEditorTextSpan textSpan, ICompilerServiceResource compilerServiceResource)
References Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
ISyntaxNode? Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.GetSyntaxNode(int positionIndex, CompilationUnit compilationUnit)
IBinderSession Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.StartBinderSession(ResourceUri resourceUri)
FinalizeBinderSession
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
void Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.FinalizeBinderSession(IBinderSession binderSession)
StartBinderSession
bool Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.TryGetBinderSession(ResourceUri resourceUri, out IBinderSession binderSession)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
void Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.UpsertBinderSession(IBinderSession binderSession)
bool Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.RemoveBinderSession(ResourceUri resourceUri)
Returns true if the entry was removed.
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
IScope? Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.GetScope(TextEditorTextSpan textSpan)
References Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
IScope? Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.GetScopeByPositionIndex(ResourceUri resourceUri, int positionIndex)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
IScope? Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.GetScopeByScopeIndexKey(ResourceUri resourceUri, int scopeIndexKey)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
IScope?[] Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.GetScopeList(ResourceUri resourceUri)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
TypeDefinitionNode[] Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.GetTypeDefinitionNodesByScope(ResourceUri resourceUri, int scopeIndexKey)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
bool Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.TryGetTypeDefinitionNodeByScope(ResourceUri resourceUri, int scopeIndexKey, string typeIdentifierText, out TypeDefinitionNode typeDefinitionNode)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
bool Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.TryAddTypeDefinitionNodeByScope(ResourceUri resourceUri, int scopeIndexKey, string typeIdentifierText, TypeDefinitionNode typeDefinitionNode)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
void Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.SetTypeDefinitionNodeByScope(ResourceUri resourceUri, int scopeIndexKey, string typeIdentifierText, TypeDefinitionNode typeDefinitionNode)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
FunctionDefinitionNode[] Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.GetFunctionDefinitionNodesByScope(ResourceUri resourceUri, int scopeIndexKey)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
bool Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.TryGetFunctionDefinitionNodeByScope(ResourceUri resourceUri, int scopeIndexKey, string functionIdentifierText, out FunctionDefinitionNode functionDefinitionNode)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
bool Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.TryAddFunctionDefinitionNodeByScope(ResourceUri resourceUri, int scopeIndexKey, string functionIdentifierText, FunctionDefinitionNode functionDefinitionNode)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
void Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.SetFunctionDefinitionNodeByScope(ResourceUri resourceUri, int scopeIndexKey, string functionIdentifierText, FunctionDefinitionNode functionDefinitionNode)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
IVariableDeclarationNode[] Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.GetVariableDeclarationNodesByScope(ResourceUri resourceUri, int scopeIndexKey)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
bool Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.TryGetVariableDeclarationNodeByScope(ResourceUri resourceUri, int scopeIndexKey, string variableIdentifierText, out IVariableDeclarationNode variableDeclarationNode)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
bool Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.TryAddVariableDeclarationNodeByScope(ResourceUri resourceUri, int scopeIndexKey, string variableIdentifierText, IVariableDeclarationNode variableDeclarationNode)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
void Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.SetVariableDeclarationNodeByScope(ResourceUri resourceUri, int scopeIndexKey, string variableIdentifierText, IVariableDeclarationNode variableDeclarationNode)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
TypeClauseNode? Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.GetReturnTypeClauseNodeByScope(ResourceUri resourceUri, int scopeIndexKey)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
bool Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.TryAddReturnTypeClauseNodeByScope(ResourceUri resourceUri, int scopeIndexKey, TypeClauseNode typeClauseNode)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
void Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.ClearStateByResourceUri(ResourceUri resourceUri)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
void Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.AddNamespaceToCurrentScope(string namespaceString, IParserModel model)
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.NamespaceStatementNode.OnBoundScopeCreatedAndSetAsCurrent.
void Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.BindFunctionOptionalArgument(FunctionArgumentEntryNode functionArgumentEntryNode, IParserModel model)
void Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.BindVariableDeclarationNode(IVariableDeclarationNode variableDeclarationNode, IParserModel model)
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.ForeachStatementNode.OnBoundScopeCreatedAndSetAsCurrent, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.TypeDefinitionNode.OnBoundScopeCreatedAndSetAsCurrent.