Luthetus::Common::RazorLib::JavaScriptObjects::Models
record Luthetus.Common.RazorLib.JavaScriptObjects.Models.ContextMenuFixedPosition(bool OccurredDueToMouseEvent, double LeftPositionInPixels, double TopPositionInPixels)
If the context menu event occurred due to a "RightClick" event then LeftPositionInPixels == MouseEventArgs.ClientX TopPositionInPixels == MouseEventArgs.ClientY If the context menu event occurred due to a "keyboard" event then LeftPositionInPixels == element.getBoundingClientRect().left TopPositionInPixels == element.getBoundingClientRect().top + element.getBoundingClientRect().height.
Referenced by Luthetus.Common.RazorLib.JsRuntimes.Models.LuthetusCommonJavaScriptInteropApi.GetTreeViewContextMenuFixedPosition.
record Luthetus.Common.RazorLib.JavaScriptObjects.Models.ElementPositionInPixels(double Left, double Top)
Referenced by Luthetus.TextEditor.RazorLib.JsRuntimes.Models.LuthetusTextEditorJavaScriptInteropApi.GetBoundingClientRect.
record Luthetus.Common.RazorLib.JavaScriptObjects.Models.MeasuredHtmlElementDimensions(double WidthInPixels, double HeightInPixels, double LeftInPixels, double TopInPixels, double ZIndex)
Referenced by Luthetus.Common.Tests.Basis.Contexts.States.ContextStateActionsTests.AddInspectableContextAction, Luthetus.Common.RazorLib.Contexts.Models.InspectableContext, Luthetus.Common.RazorLib.JsRuntimes.Models.LuthetusCommonJavaScriptInteropApi.MeasureElementById, Luthetus.Common.RazorLib.Outlines.States.OutlineState, Luthetus.Common.Tests.Basis.Contexts.States.ContextStateReducerTests.ReduceAddInspectableContextAction.
record Luthetus.Common.RazorLib.JavaScriptObjects.Models.RelativeCoordinates(double RelativeX, double RelativeY, double RelativeScrollLeft, double RelativeScrollTop)
Referenced by Luthetus.TextEditor.Tests.Basis.TextEditors.Models.Internals.TooltipViewModelTests.Constructor, Luthetus.TextEditor.RazorLib.JsRuntimes.Models.LuthetusTextEditorJavaScriptInteropApi.GetRelativePosition, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.HandleMouseStoppedMovingEventAsync, Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TooltipViewModel.