Luthetus::Common::RazorLib::Keymaps::Models
record struct Luthetus.Common.RazorLib.Keymaps.Models.KeymapLayer(Key< KeymapLayer > Key, string DisplayName, string InternalName)
References Luthetus.Common.RazorLib.Keymaps.Models.KeymapLayer.
Referenced by Luthetus.Common.Tests.Basis.Keymaps.Models.KeymapLayerTests.ConstructorA, Luthetus.Common.Tests.Basis.Keymaps.Models.KeymapLayerTests.ConstructorB, Luthetus.Common.RazorLib.Keymaps.Models.KeymapLayer, Luthetus.Common.RazorLib.Keymaps.States.KeymapState.