Luthetus::Common::RazorLib::Themes::Models
ThemeColorKind
ThemeContrastKind
ThemeScope
record Luthetus.Common.RazorLib.Themes.Models.ThemeRecord(Key< ThemeRecord > Key, string DisplayName, string CssClassString, ThemeContrastKind ThemeContrastKind, ThemeColorKind ThemeColorKind, ImmutableList< ThemeScope > ThemeScopeList)
Referenced by Luthetus.Common.Tests.Basis.Themes.States.ThemeStateMainTests.DefaultThemeRecordsList, Luthetus.Common.RazorLib.Themes.Models.IThemeService.RegisterThemeRecord, Luthetus.Common.RazorLib.Themes.Models.ThemeService.RegisterThemeRecord, Luthetus.Common.RazorLib.Options.Models.AppOptionsService.SetTheme, Luthetus.Common.RazorLib.Options.Models.IAppOptionsService.SetTheme, Luthetus.TextEditor.RazorLib.Options.Models.ITextEditorOptionsApi.SetTheme, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetTheme, Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.SetThemeAction.