Luthetus::Common::RazorLib::Contexts::States
partial record Luthetus.Common.RazorLib.Contexts.States.ContextState(ImmutableArray< ContextRecord > AllContextsList, ContextHeirarchy FocusedContextHeirarchy, ContextHeirarchy? InspectedContextHeirarchy, ImmutableArray< InspectableContext > InspectableContextList, bool IsSelectingInspectionTarget)
References Luthetus.Common.RazorLib.Contexts.Models.ContextHeirarchy, Luthetus.Common.RazorLib.Contexts.States.ContextState.
partial record Luthetus.Common.RazorLib.Contexts.States.ContextSwitchState(ImmutableList< ContextSwitchGroup > ContextSwitchGroupList)
References Luthetus.Common.RazorLib.Contexts.States.ContextSwitchState.
Referenced by Luthetus.Common.RazorLib.Contexts.States.ContextSwitchState, Luthetus.Common.RazorLib.Installations.Displays.LuthetusCommonInitializer.OnInitialized, Luthetus.TextEditor.RazorLib.Installations.Displays.LuthetusTextEditorInitializer.OnInitialized.