Luthetus::Extensions::Git::Models
GitDirtyReason
record Luthetus.Extensions.Git.Models.GitFile(IAbsolutePath AbsolutePath, string RelativePathString, GitDirtyReason GitDirtyReason)
References Luthetus.Extensions.Git.Models.Added, Luthetus.Extensions.Git.Models.Deleted, Luthetus.Extensions.Git.Models.Modified, Luthetus.Extensions.Git.Models.None, Luthetus.Extensions.Git.Models.Untracked.
Referenced by Luthetus.Extensions.Git.Models.GitCliOutputParser.StatusParseEntire, Luthetus.Extensions.Git.Models.TreeViewGitFile.TreeViewGitFile.
record Luthetus.Extensions.Git.Models.GitRepo(IAbsolutePath AbsolutePath)
TODO: Why am I parsing the CLI output? Can I just look at the '.git' folder itself? (2024-05-04).
Referenced by Luthetus.Extensions.Git.Models.GitIdeApi.AddEnqueue, Luthetus.Extensions.Git.Models.GitIdeApi.BranchGetAllEnqueue, Luthetus.Extensions.Git.Models.GitIdeApi.BranchNewEnqueue, Luthetus.Extensions.Git.Models.GitIdeApi.BranchSetEnqueue, Luthetus.Extensions.Git.Models.GitIdeApi.CommitEnqueue, Luthetus.Extensions.Git.Models.GitIdeApi.DiffFileEnqueue, Luthetus.Extensions.Git.Models.GitIdeApi.FetchEnqueue, Luthetus.Extensions.Git.Models.GitIdeApi.GetActiveBranchNameEnqueue, Luthetus.Extensions.Git.Models.GitIdeApi.GetOriginNameEnqueue, Luthetus.Extensions.Git.States.GitState, Luthetus.Extensions.Git.Models.GitIdeApi.LogFileEnqueue, Luthetus.Extensions.Git.Models.GitIdeApi.PullEnqueue, Luthetus.Extensions.Git.Models.GitIdeApi.PushToOriginWithTrackingEnqueue, Luthetus.Extensions.Git.Models.GitIdeApi.RefreshEnqueue, Luthetus.Extensions.Git.Models.GitIdeApi.ShowFileEnqueue, Luthetus.Extensions.Git.Models.GitIdeApi.UnstageEnqueue.
record Luthetus.Extensions.Git.Models.GitTask(Guid Id, string DisplayName, CancellationToken CancellationToken)