Luthetus::Common::RazorLib::Contexts::Models
record Luthetus.Common.RazorLib.Contexts.Models.ContextHeirarchy(ImmutableArray< Key< ContextRecord > > KeyList)
KeyList Contains the NearestAncestorKey at index 0, then the immediate parent of target at index 1. This pattern follows for 'parent of parent' until there is no parent. Each parent getting the next index in list to store their key.
Referenced by Luthetus.Common.Tests.Basis.Contexts.States.ContextStateActionsTests.AddInspectableContextAction, Luthetus.Common.Tests.Basis.Contexts.States.ContextStateTests.Constructor, Luthetus.Common.RazorLib.Contexts.States.ContextState, Luthetus.Common.RazorLib.Contexts.Models.InspectableContext, Luthetus.Common.Tests.Basis.Contexts.States.ContextStateActionsTests.SetFocusedContextHeirarchyAction, Luthetus.Common.Tests.Basis.Contexts.States.ContextStateActionsTests.SetInspectedContextHeirarchyAction, Luthetus.Common.Tests.Basis.Contexts.Models.ContextRecordKeyHeirarchyTests.TargetKey.
record Luthetus.Common.RazorLib.Contexts.Models.ContextRecord(Key< ContextRecord > ContextKey, string DisplayNameFriendly, string ContextNameInternal, IKeymap Keymap)
Referenced by Luthetus.Common.Tests.Basis.Contexts.Models.ContextRecordTests.Constructor, Luthetus.Common.Tests.Basis.Panels.States.PanelStateReducerTests.ReduceSetPanelTabAsActiveByContextRecordKeyAction.
record Luthetus.Common.RazorLib.Contexts.Models.InspectableContext(ContextHeirarchy ContextHeirarchy, MeasuredHtmlElementDimensions TargetContextRecordMeasuredHtmlElementDimensions)
This logic relates to rendering a blue overlay during the 'inspect element like' action. Each InspectContextRecordEntry relates to a single ContextRecord.
References Luthetus.Common.RazorLib.Contexts.Models.ContextHeirarchy, Luthetus.Common.RazorLib.JavaScriptObjects.Models.MeasuredHtmlElementDimensions.
Referenced by Luthetus.Common.Tests.Basis.Contexts.States.ContextStateActionsTests.AddInspectableContextAction, Luthetus.Common.RazorLib.Contexts.Displays.ContextBoundaryMeasurer.OnAfterRenderAsync, Luthetus.Common.Tests.Basis.Contexts.States.ContextStateReducerTests.ReduceAddInspectableContextAction.