Luthetus::TextEditor::RazorLib::Decorations::Models
record Luthetus.TextEditor.RazorLib.Decorations.Models.TextEditorPresentationModel(Key< TextEditorPresentationModel > TextEditorPresentationKey, int Rank, string CssClassString, IDecorationMapper DecorationMapper)
TextEditorPresentationKey Unique Identifier. Perhaps one wants to repaint the Diff presentation only. They use this to identify the Diff presentation Rank The order the presentations get rendered. A given a ranks of [ 7, -3, 1, 2 ] the rendering order is ascending therefore it will be reordered as [ -3, 1, 2, 7 ] when iterating over the containing presentation layer CssClassString A div is rendered with this css class. Inside this div are the divs gotten from the text spans. One likely only will use this css class as an identifier while viewing the browser's debugging tools. DecorationMapper The decoration mapper that is responsible for converting a decoration byte to a css class TextEditorTextSpans The list of position indices that are to painted with certain decoration bytes.
References Luthetus.TextEditor.RazorLib.Decorations.Models.TextEditorPresentationModelCalculation.
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorModelApi.AddPresentationModel, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelApi.AddPresentationModel, Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorModelApi.CompletePendingCalculatePresentationModel, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelApi.CompletePendingCalculatePresentationModel, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.CompletePendingCalculatePresentationModel, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.PerformRegisterPresentationModelAction, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.PresentationAndSelectionDriver.PresentationGetCssClass, Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorModelApi.StartPendingCalculatePresentationModel, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelApi.StartPendingCalculatePresentationModel, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.StartPendingCalculatePresentationModel.
record Luthetus.TextEditor.RazorLib.Decorations.Models.TextEditorPresentationModelCalculation(string ContentAtRequest)
In a concurrent safe manner, get the content from the TextEditorModel such that no insertions or deletions can occur during the setting of this property.
Referenced by Luthetus.TextEditor.RazorLib.Decorations.Models.TextEditorPresentationModel.
record Luthetus.TextEditor.RazorLib.Decorations.Models.TextEditorTextModification(bool WasInsertion, TextEditorTextSpan TextEditorTextSpan)
References Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.PresentationAndSelectionDriver.PresentationVirtualizeAndShiftTextSpans.