Luthetus::Common::RazorLib::Menus::Models
MenuOptionKind
record Luthetus.Common.RazorLib.Menus.Models.MenuOptionRecord(string DisplayName, MenuOptionKind MenuOptionKind, Func< Task >? OnClickFunc=null, MenuRecord? SubMenu=null, Type? WidgetRendererType=null, Dictionary< string, object?>? WidgetParameterMap=null)
References Luthetus.Common.RazorLib.Menus.Models.MenuRecord.
Referenced by Luthetus.Extensions.DotNet.Menus.Models.DotNetMenuOptionsFactory.AddProjectToProjectReference, Luthetus.Extensions.DotNet.Menus.Models.IDotNetMenuOptionsFactory.AddProjectToProjectReference, Luthetus.Ide.RazorLib.Menus.Models.IMenuOptionsFactory.CopyFile, Luthetus.Ide.RazorLib.Menus.Models.MenuOptionsFactory.CopyFile, Luthetus.Ide.RazorLib.Menus.Models.IMenuOptionsFactory.CutFile, Luthetus.Ide.RazorLib.Menus.Models.MenuOptionsFactory.CutFile, Luthetus.Ide.RazorLib.Menus.Models.IMenuOptionsFactory.DeleteFile, Luthetus.Ide.RazorLib.Menus.Models.MenuOptionsFactory.DeleteFile, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.DoReloadOnClick, Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.ISolutionVisualizationDrawing.GetMenuOptionRecord, Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationDrawingCircle< TItem >.GetMenuOptionRecord, Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationDrawingLine< TItem >.GetMenuOptionRecord, Luthetus.Ide.RazorLib.Commands.CommandFactory.Initialize, Luthetus.Common.RazorLib.Menus.Models.MenuRecord, Luthetus.Extensions.DotNet.Menus.Models.DotNetMenuOptionsFactory.MoveProjectToSolutionFolder, Luthetus.Extensions.DotNet.Menus.Models.IDotNetMenuOptionsFactory.MoveProjectToSolutionFolder, Luthetus.Ide.RazorLib.Menus.Models.IMenuOptionsFactory.NewDirectory, Luthetus.Ide.RazorLib.Menus.Models.MenuOptionsFactory.NewDirectory, Luthetus.Ide.RazorLib.Menus.Models.IMenuOptionsFactory.NewEmptyFile, Luthetus.Ide.RazorLib.Menus.Models.MenuOptionsFactory.NewEmptyFile, Luthetus.Ide.RazorLib.Menus.Models.IMenuOptionsFactory.NewTemplatedFile, Luthetus.Ide.RazorLib.Menus.Models.MenuOptionsFactory.NewTemplatedFile, Luthetus.Extensions.DotNet.Installations.Displays.LuthetusExtensionsDotNetInitializer.OnAfterRender, Luthetus.Common.RazorLib.Installations.Displays.LuthetusCommonInitializer.OnInitialized, Luthetus.TextEditor.RazorLib.Installations.Displays.LuthetusTextEditorInitializer.OnInitialized, Luthetus.Ide.RazorLib.Menus.Models.IMenuOptionsFactory.PasteClipboard, Luthetus.Ide.RazorLib.Menus.Models.MenuOptionsFactory.PasteClipboard, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.QuickActionsSlashRefactor, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.RelatedFilesQuickPick, Luthetus.Extensions.DotNet.Menus.Models.DotNetMenuOptionsFactory.RemoveCSharpProjectReferenceFromSolution, Luthetus.Extensions.DotNet.Menus.Models.IDotNetMenuOptionsFactory.RemoveCSharpProjectReferenceFromSolution, Luthetus.Extensions.DotNet.Menus.Models.DotNetMenuOptionsFactory.RemoveNuGetPackageReferenceFromProject, Luthetus.Extensions.DotNet.Menus.Models.IDotNetMenuOptionsFactory.RemoveNuGetPackageReferenceFromProject, Luthetus.Extensions.DotNet.Menus.Models.DotNetMenuOptionsFactory.RemoveProjectToProjectReference, Luthetus.Extensions.DotNet.Menus.Models.IDotNetMenuOptionsFactory.RemoveProjectToProjectReference, Luthetus.Ide.RazorLib.Menus.Models.IMenuOptionsFactory.RenameFile, Luthetus.Ide.RazorLib.Menus.Models.MenuOptionsFactory.RenameFile.
record Luthetus.Common.RazorLib.Menus.Models.MenuRecord(ImmutableArray< MenuOptionRecord > MenuOptionList)
References Luthetus.Common.RazorLib.Menus.Models.MenuOptionRecord, Luthetus.Common.RazorLib.Menus.Models.MenuRecord.
Referenced by Luthetus.Common.Tests.Basis.Menus.Models.MenuRecordTests.Empty, Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationDrawingCircle< TItem >.GetMenuOptionRecord, Luthetus.Extensions.DotNet.DotNetSolutions.Models.Internals.SolutionVisualizationDrawingLine< TItem >.GetMenuOptionRecord, Luthetus.Ide.RazorLib.Shareds.States.IdeHeaderState, Luthetus.Ide.RazorLib.Commands.CommandFactory.Initialize, Luthetus.Common.RazorLib.Menus.Models.MenuOptionRecord, Luthetus.Common.RazorLib.Menus.Models.MenuRecord, Luthetus.Extensions.DotNet.Installations.Displays.LuthetusExtensionsDotNetInitializer.OnAfterRender, Luthetus.Common.RazorLib.Installations.Displays.LuthetusCommonInitializer.OnInitialized, Luthetus.TextEditor.RazorLib.Installations.Displays.LuthetusTextEditorInitializer.OnInitialized, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.QuickActionsSlashRefactor, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.RelatedFilesQuickPick.