Luthetus::TextEditor::RazorLib::Options::Models
record Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptions(CommonOptions CommonOptions, bool ShowWhitespace, bool ShowNewlines, int? TextEditorHeightInPixels, double CursorWidthInPixels, Keymap Keymap, bool UseMonospaceOptimizations)
References Luthetus.Common.RazorLib.Options.Models.CommonOptions.
Referenced by Luthetus.TextEditor.Tests.Basis.Options.Models.TextEditorOptionsTests.Constructor, Luthetus.TextEditor.RazorLib.Keymaps.Models.Defaults.TextEditorKeymapDefault.GetCursorCssStyleString, Luthetus.TextEditor.RazorLib.Keymaps.Models.ITextEditorKeymap.GetCursorCssStyleString, Luthetus.TextEditor.RazorLib.Keymaps.Models.Vims.TextEditorKeymapVim.GetCursorCssStyleString, Luthetus.TextEditor.RazorLib.Options.Models.ITextEditorOptionsApi.GetOptions, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.GetOptions, Luthetus.TextEditor.RazorLib.TextEditors.Models.Internals.TextEditorComponentData.TextEditorComponentData, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsJsonDto, Luthetus.TextEditor.Tests.Basis.Options.Models.TextEditorOptionsJsonDtoTests.TextEditorOptionsJsonDto_C, Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.TextEditorOptionsState.
record Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsJsonDto(CommonOptionsJsonDto? CommonOptionsJsonDto, bool? ShowWhitespace, bool? ShowNewlines, int? TextEditorHeightInPixels, double? CursorWidthInPixels, Keymap? Keymap, bool? UseMonospaceOptimizations)
This type needs to exist so the TextEditorOptions properties can be nullable, as in they were not already in local storage. Whereas throughout the app they should never be null.
References Luthetus.Common.RazorLib.Options.Models.CommonOptionsJsonDto, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptions, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsJsonDto.
Referenced by Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.SetFromLocalStorageAsync, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsJsonDto, Luthetus.TextEditor.Tests.Basis.Options.Models.TextEditorOptionsJsonDtoTests.TextEditorOptionsJsonDto_A, Luthetus.TextEditor.Tests.Basis.Options.Models.TextEditorOptionsJsonDtoTests.TextEditorOptionsJsonDto_B, Luthetus.TextEditor.Tests.Basis.Options.Models.TextEditorOptionsJsonDtoTests.TextEditorOptionsJsonDto_C, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsApi.WriteToStorage.