Luthetus::Common::RazorLib::Options::Models
record Luthetus.Common.RazorLib.Options.Models.CommonOptions(int FontSizeInPixels, int IconSizeInPixels, int ResizeHandleWidthInPixels, int ResizeHandleHeightInPixels, Key< ThemeRecord > ThemeKey, string? FontFamily, bool ShowPanelTitles)
Referenced by Luthetus.Common.RazorLib.Options.States.AppOptionsState, Luthetus.Common.RazorLib.Options.Models.CommonOptionsJsonDto, Luthetus.TextEditor.Tests.Basis.Options.Models.TextEditorOptionsTests.Constructor, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptions, Luthetus.TextEditor.Tests.Basis.Options.Models.TextEditorOptionsJsonDtoTests.TextEditorOptionsJsonDto_C, Luthetus.TextEditor.RazorLib.Options.States.TextEditorOptionsState.TextEditorOptionsState.
record Luthetus.Common.RazorLib.Options.Models.CommonOptionsJsonDto(int? FontSizeInPixels, int? IconSizeInPixels, int? ResizeHandleWidthInPixels, int? ResizeHandleHeightInPixels, Key< ThemeRecord >? ThemeKey, string? FontFamily)
This type needs to exist so the CommonOptions properties can be nullable, as in they were not already in local storage. Whereas throughout the app they should never be null.
References Luthetus.Common.RazorLib.Options.Models.CommonOptions, Luthetus.Common.RazorLib.Options.Models.CommonOptionsJsonDto.
Referenced by Luthetus.Common.RazorLib.Options.Models.CommonOptionsJsonDto, Luthetus.Common.Tests.Basis.Options.Models.CommonOptionsJsonDtoTests.ConstructorA, Luthetus.Common.Tests.Basis.Options.Models.CommonOptionsJsonDtoTests.ConstructorB, Luthetus.Common.Tests.Basis.Options.Models.CommonOptionsJsonDtoTests.ConstructorC, Luthetus.Common.RazorLib.Options.Models.AppOptionsService.SetFromLocalStorageAsync, Luthetus.TextEditor.RazorLib.Options.Models.TextEditorOptionsJsonDto, Luthetus.TextEditor.Tests.Basis.Options.Models.TextEditorOptionsJsonDtoTests.TextEditorOptionsJsonDto_A, Luthetus.Common.RazorLib.Options.Models.AppOptionsService.WriteToStorage.