Luthetus::TextEditor::RazorLib::Virtualizations::Models
record Luthetus::TextEditor::RazorLib::Virtualizations::Models.VirtualizationResult< T >
record VirtualizationBoundary Luthetus::TextEditor::RazorLib::Virtualizations::Models.leftVirtualizationBoundary
record VirtualizationBoundary VirtualizationBoundary Luthetus::TextEditor::RazorLib::Virtualizations::Models.rightVirtualizationBoundary
record VirtualizationBoundary VirtualizationBoundary VirtualizationBoundary Luthetus::TextEditor::RazorLib::Virtualizations::Models.topVirtualizationBoundary
record Luthetus.TextEditor.RazorLib.Virtualizations.Models.VirtualizationBoundary(double? WidthInPixels, double? HeightInPixels, double? LeftInPixels, double? TopInPixels)
Referenced by Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.CalculateVirtualizationResult, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.VirtualizationDriver.GetStyleCssString.
record Luthetus.TextEditor.RazorLib.Virtualizations.Models.VirtualizationEntry< T >(int Index, T Item, double? WidthInPixels, double? HeightInPixels, double? LeftInPixels, double? TopInPixels)
record Luthetus.TextEditor.RazorLib.Virtualizations.Models.VirtualizationRequest(VirtualizationScrollPosition ScrollPosition, CancellationToken CancellationToken)
References Luthetus.TextEditor.RazorLib.Virtualizations.Models.VirtualizationScrollPosition.
Referenced by Luthetus.TextEditor.RazorLib.Virtualizations.Displays.VirtualizationDisplay.OnScrollEventAsync.
static VirtualizationResult< RichCharacter[]> Luthetus.TextEditor.RazorLib.Virtualizations.Models.GetEmptyRichCharacters()
record Luthetus.TextEditor.RazorLib.Virtualizations.Models.VirtualizationScrollPosition(double ScrollLeftInPixels, double ScrollTopInPixels, double ScrollWidthInPixels, double ScrollHeightInPixels)
ScrollWidthInPixels may represent either the JavaScript value of checking scrollWidth on a scrollable element. OR ScrollWidthInPixels may represent the maximum width of a faked scrollbar (overflow: hidden for example) ALSO The comment about ScrollWidthInPixels also applies to the height for ScrollHeightInPixels
Referenced by Luthetus.TextEditor.RazorLib.Virtualizations.Displays.VirtualizationDisplay.OnInitialized, Luthetus.TextEditor.RazorLib.Virtualizations.Displays.VirtualizationDisplay.OnScrollEventAsync, Luthetus.TextEditor.RazorLib.Virtualizations.Models.VirtualizationRequest.