Luthetus::Extensions::DotNet::Nugets::Models
record Luthetus.Extensions.DotNet.Nugets.Models.CSharpProjectNugetPackageReference(string CSharpProjectAbsolutePathString, LightWeightNugetPackageRecord LightWeightNugetPackageRecord)
References Luthetus.Extensions.DotNet.Nugets.Models.LightWeightNugetPackageRecord.
Referenced by Luthetus.Extensions.DotNet.Tests.Basis.TreeViewImplementations.Models.TreeViewCSharpProjectNugetPackageReferenceTests.Constructor, Luthetus.Extensions.DotNet.CSharpProjects.Models.TreeViewCSharpProjectNugetPackageReference.TreeViewCSharpProjectNugetPackageReference.
record Luthetus.Extensions.DotNet.Nugets.Models.LightWeightNugetPackageRecord(string Id, string Title, string Version)
Referenced by Luthetus.Extensions.DotNet.Tests.Basis.TreeViewImplementations.Models.TreeViewCSharpProjectNugetPackageReferenceTests.Constructor, Luthetus.Extensions.DotNet.Nugets.Models.CSharpProjectNugetPackageReference, Luthetus.Extensions.DotNet.CSharpProjects.Models.TreeViewCSharpProjectNugetPackageReferences.LoadChildListAsync.
record Luthetus.Extensions.DotNet.Nugets.Models.NugetPackageRecord(string Type, string Registration, string Id, string Version, string Description, string Summary, string Title, string IconUrl, string LicenseUrl, string ProjectUrl, ImmutableArray< string > Tags, ImmutableArray< string > Authors, ImmutableArray< string > Owners, long TotalDownloads, bool Verified, ImmutableArray< NugetPackageVersionRecord > Versions)
When reading response Nuget returns AtId as a member named "@id".
Referenced by Luthetus.Extensions.DotNet.Nugets.Models.NugetResponse.
record Luthetus.Extensions.DotNet.Nugets.Models.NugetPackageVersionRecord(string Version, long Downloads)
When reading response Nuget returns AtId as a member named "@id".
record Luthetus.Extensions.DotNet.Nugets.Models.NugetResponse(int TotalHits, NugetPackageRecord[] Data)
References Luthetus.Extensions.DotNet.Nugets.Models.NugetPackageRecord.
Referenced by Luthetus.Extensions.DotNet.Nugets.Models.NugetPackageManagerProviderAzureSearchUsnc.QueryForNugetPackagesAsync.