Luthetus::TextEditor::RazorLib::Cursors::Models
record Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor(int LineIndex, int ColumnIndex, int PreferredColumnIndex, bool IsPrimaryCursor, TextEditorSelection Selection)
References Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorSelection.
Referenced by Luthetus.TextEditor.Tests.Adhoc.TypeStartFileNonLetter.Aaa, Luthetus.TextEditor.Tests.Adhoc.NewKeybinds.AltPlusUp_THEN_MoveLineUp, Luthetus.TextEditor.Tests.Adhoc.PartitionTests.Another_Large_Throughput_Test_Backspace, Luthetus.TextEditor.Tests.Adhoc.PartitionTests.Another_Large_Throughput_Test_Delete, Luthetus.TextEditor.Tests.Adhoc.PartitionTests.Another_Large_Throughput_Test_Insert, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.CanRedoEdit, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.CanUndoEdit, Luthetus.TextEditor.RazorLib.TextEditors.Displays.Internals.HeaderDriver.ConstructCommandArgs, Luthetus.TextEditor.Tests.Basis.Cursors.Models.TextEditorCursorModifierTests.Constructor, Luthetus.TextEditor.Tests.Basis.Cursors.Models.TextEditorCursorTests.ConstructorA, Luthetus.TextEditor.Tests.Basis.Cursors.Models.TextEditorCursorTests.ConstructorB, Luthetus.TextEditor.Tests.Basis.Cursors.Models.TextEditorCursorTests.ConstructorC, Luthetus.TextEditor.Tests.Adhoc.NewKeybinds.CtrlPlusAltPlusArrowLeftOrArrowRight_THEN_MoveCamelCase, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.CursorWasModified, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.ICompilerService.CursorWasModified, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_Between_0_And_DocumentLength_Exclusive_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_Between_0_And_DocumentLength_Exclusive_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_Between_0_And_DocumentLength_Exclusive_ExpandWord_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_Between_0_And_DocumentLength_Exclusive_ExpandWord_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_EqualTo_DocumentLength_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_EqualTo_DocumentLength_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_EqualTo_NegativeOne_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_EqualTo_NegativeOne_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_EqualTo_OnePlusDocumentLength_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_EqualTo_OnePlusDocumentLength_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_EqualTo_Zero_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_EqualTo_Zero_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_Causes_DecreaseCounters_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_Causes_DecreaseCounters_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_Causes_MaintainCounters_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_Causes_MaintainCounters_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_EmptyEditor_At_PositionIndex_EqualTo_DocumentLength_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_EmptyEditor_At_PositionIndex_EqualTo_DocumentLength_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_EmptyEditor_At_PositionIndex_EqualTo_NegativeOne_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_EmptyEditor_At_PositionIndex_EqualTo_NegativeOne_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_EmptyEditor_At_PositionIndex_EqualTo_OnePlusDocumentLength_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_EmptyEditor_At_PositionIndex_EqualTo_OnePlusDocumentLength_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_EmptyEditor_At_PositionIndex_EqualTo_Zero_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_EmptyEditor_At_PositionIndex_EqualTo_Zero_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_Between_0_And_DocumentLength_Exclusive_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_Between_0_And_DocumentLength_Exclusive_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_Between_0_And_DocumentLength_Exclusive_ExpandWord_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_Between_0_And_DocumentLength_Exclusive_ExpandWord_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_EqualTo_DocumentLength_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_EqualTo_DocumentLength_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_EqualTo_NegativeOne_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_EqualTo_NegativeOne_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_EqualTo_OnePlusDocumentLength_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_EqualTo_OnePlusDocumentLength_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_EqualTo_Zero_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_At_PositionIndex_EqualTo_Zero_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_Causes_DecreaseCounters_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_Causes_DecreaseCounters_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_Causes_MaintainCounters_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_NotEmptyEditor_Causes_MaintainCounters_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.DeleteTextByMotionEnqueue_Backspace, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.DeleteTextByRangeEnqueue, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.Duplicate, Luthetus.TextEditor.Tests.Basis.Cursors.Models.TextEditorCursorTests.Empty, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Enter_Enter_Backspace_CarriageReturn, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Enter_Enter_Backspace_CarriageReturnLineFeed, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Enter_Enter_Backspace_LineFeed, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetPositionIndex_TextEditorCursor, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelExtensionMethodsTests.GetTextOffsettingCursor, Luthetus.TextEditor.RazorLib.Events.Models.OnMouseDown.HandleEvent, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.HandleKeyboardEvent, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.HandleKeyboardEventEnqueue, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.HandleMouseStoppedMovingEventAsync, Luthetus.TextEditor.Tests.Adhoc.NewKeybinds.Home_THEN_MoreFunctionality, Luthetus.TextEditor.Tests.Basis.TestsHelper.InBounds_EndOfDocument, Luthetus.TextEditor.Tests.Basis.TestsHelper.InBounds_EndOfRow, Luthetus.TextEditor.Tests.Basis.TestsHelper.InBounds_NOT_StartOfRow_AND_NOT_EndOfRow, Luthetus.TextEditor.Tests.Basis.TestsHelper.InBounds_StartOfDocument, Luthetus.TextEditor.Tests.Basis.TestsHelper.InBounds_StartOfRow, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.IndentLess, Luthetus.TextEditor.Tests.Basis.Commands.Models.Defaults.TextEditorCommandDefaultFactsTests.IndentLess, Luthetus.TextEditor.RazorLib.Commands.Models.Defaults.TextEditorCommandDefaultFunctions.IndentMore, Luthetus.TextEditor.Tests.Adhoc.AdhocTest.Insert_Into_Empty_Model_A_CarriageReturn, Luthetus.TextEditor.Tests.Adhoc.AdhocTest.Insert_Into_Empty_Model_A_CarriageReturnNewLine, Luthetus.TextEditor.Tests.Adhoc.AdhocTest.Insert_Into_Empty_Model_A_LetterOrDigit, Luthetus.TextEditor.Tests.Adhoc.AdhocTest.Insert_Into_Empty_Model_A_LineFeed, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_EmptyEditor_At_Position_One_Plus_DocumentLength, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_EmptyEditor_At_PositionIndex_DocumentLength, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_EmptyEditor_At_PositionIndex_Negative_One, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_EmptyEditor_At_PositionIndex_Zero, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_EmptyEditor_Empty_String, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_EmptyEditor_Null_String, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_NotEmptyEditor_At_Position_One_Plus_DocumentLength, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_NotEmptyEditor_At_PositionIndex_Between_0_And_DocumentLength_Exclusive, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_NotEmptyEditor_At_PositionIndex_Between_0_And_DocumentLength_Exclusive_With_Selection, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_NotEmptyEditor_At_PositionIndex_DocumentLength, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_NotEmptyEditor_At_PositionIndex_Negative_One, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_NotEmptyEditor_At_PositionIndex_Zero, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_NotEmptyEditor_Empty_String, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_NotEmptyEditor_Null_String, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.InsertTextEnqueue, Luthetus.TextEditor.Tests.Adhoc.PartitionTests.Large_Throughput_Test, Luthetus.TextEditor.Tests.Adhoc.NewKeybinds.NoSelectionPlusShiftPlusTabPlusCursorAtIndentation_THEN_IndentLess, Luthetus.TextEditor.Tests.Basis.TestsHelper.OutOfBounds_PositionIndex_GREATER_THAN_DocumentLength_PLUS_One, Luthetus.TextEditor.Tests.Basis.TestsHelper.OutOfBounds_PositionIndex_LESS_THAN_Zero, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.RedoEditEnqueue, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursorModifier.TextEditorCursorModifier, Luthetus.TextEditor.Tests.Adhoc.PartitionTests.ThreePartitionEdit_Delete, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursorModifier.ToCursor, Luthetus.TextEditor.Tests.Adhoc.PartitionTests.TwoPartitionEdit_Backspace, Luthetus.TextEditor.Tests.Adhoc.PartitionTests.TwoPartitionEdit_Delete, Luthetus.TextEditor.Tests.Adhoc.PartitionTests.TwoPartitionEdit_Insert, Luthetus.TextEditor.Tests.Basis.Commands.Models.Defaults.TextEditorCommandDefaultFactsTests.Undo, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.UndoEdit, Luthetus.TextEditor.RazorLib.Keymaps.Models.Vims.VimMotionResult, Luthetus.TextEditor.Tests.Basis.Cursors.Models.TextEditorCursorTests.With.
record Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorSelection(int? AnchorPositionIndex, int EndingPositionIndex)
To select the first character in a TextEditor one would set AnchorPositionIndex = 0 and set EndingPositionIndex = 1 The AnchorPositionIndex does not select any text by itself. One must visualize that the user's cursor is rendered with TextCursorKindFacts.BeamCssClassString mode. The EndingPositionIndex can then be set. If EndingPositionIndex is less than AnchorPositionIndex then EndingPositionIndex will be INCLUSIVE in respect to selecting the character at that PositionIndex and AnchorPositionIndex will be EXCLUSIVE. If EndingPositionIndex is greater than AnchorPositionIndex then EndingPositionIndex will be EXCLUSIVE in respect to selecting the character at that PositionIndex and AnchorPositionIndex will be INCLUSIVE. If EndingPositionIndex is equal to AnchorPositionIndex then no selection is active. If AnchorPositionIndex is null then no selection is active.
References Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorSelection.
Referenced by Luthetus.TextEditor.Tests.Basis.Cursors.Models.TextEditorCursorModifierTests.Constructor, Luthetus.TextEditor.Tests.Basis.Cursors.Models.TextEditorSelectionTests.Constructor, Luthetus.TextEditor.Tests.Basis.Cursors.Models.TextEditorCursorTests.ConstructorA, Luthetus.TextEditor.Tests.Basis.Cursors.Models.TextEditorCursorTests.ConstructorB, Luthetus.TextEditor.Tests.Basis.Cursors.Models.TextEditorCursorTests.ConstructorC, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_Between_0_And_DocumentLength_Exclusive_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_Between_0_And_DocumentLength_Exclusive_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_Between_0_And_DocumentLength_Exclusive_ExpandWord_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_Between_0_And_DocumentLength_Exclusive_ExpandWord_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_EqualTo_DocumentLength_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_EqualTo_DocumentLength_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_EqualTo_NegativeOne_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_EqualTo_NegativeOne_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_EqualTo_OnePlusDocumentLength_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_EqualTo_OnePlusDocumentLength_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_EqualTo_Zero_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_At_PositionIndex_EqualTo_Zero_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_Causes_DecreaseCounters_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_Causes_DecreaseCounters_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_Causes_MaintainCounters_BackspaceEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Delete_From_CursorSelection_Causes_MaintainCounters_DeleteEnum, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.DeleteTextByMotionEnqueue_Backspace, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.DeleteTextByRangeEnqueue, Luthetus.TextEditor.Tests.Basis.Cursors.Models.TextEditorCursorTests.Empty, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.HandleKeyboardEventEnqueue, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelModifierTests.Insert_Into_NotEmptyEditor_At_PositionIndex_Between_0_And_DocumentLength_Exclusive_With_Selection, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.InsertTextEnqueue, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.RedoEditEnqueue, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursor, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorSelection, Luthetus.TextEditor.RazorLib.Cursors.Models.TextEditorCursorModifier.ToCursor, Luthetus.TextEditor.Tests.Basis.TextEditors.Models.TextEditorModelApiTests.UndoEdit, Luthetus.TextEditor.Tests.Basis.Cursors.Models.TextEditorCursorTests.With.