Luthetus::Common::RazorLib::FileSystems::Models
PathType
record Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFile(string Data, IAbsolutePath AbsolutePath, DateTime LastModifiedDateTime, bool IsDirectory)
Referenced by Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.UnsafeCopyAsync, Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryDirectoryHandler.UnsafeCreateDirectoryAsync, Luthetus.Common.RazorLib.FileSystems.Models.InMemoryFileSystemProvider.InMemoryFileHandler.UnsafeWriteAllTextAsync.