Luthetus::TextEditor::RazorLib::Lexers::Models
record struct Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri(string Value)
References Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri.
Referenced by Luthetus.Ide.Tests.Basis.Gits.Models.GitIdeApiTests.Aaa, Luthetus.TextEditor.RazorLib.Diffs.Models.TextEditorDiffResult.Calculate, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ClearByResourceUri, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.ClearStateByResourceUri, Luthetus.TextEditor.RazorLib.CompilerServices.Binder.ClearStateByResourceUri, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.ClearStateByResourceUri, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Nodes.CompilationUnit.CompilationUnit, Luthetus.TextEditor.Tests.Basis.CompilerServices.StringWalkerTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.Symbols.SymbolDefinitionTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.Symbols.SymbolReferenceTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.AmbiguousIdentifierNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.AttributeNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.BinaryExpressionNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.BinaryOperatorNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.ConstraintNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.ConstructorDefinitionNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.FunctionArgumentEntryNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.FunctionArgumentsListingNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.FunctionDefinitionNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.FunctionInvocationNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.FunctionParameterEntryNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.FunctionParametersListingNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.GenericArgumentEntryNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.GenericArgumentsListingNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.GenericParameterEntryNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.GenericParametersListingNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.IfStatementNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.LiteralExpressionNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.ParenthesizedExpressionNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.ReturnStatementNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.TypeDefinitionNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.VariableAssignmentExpressionNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.VariableDeclarationNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.VariableReferenceNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.ArraySyntaxTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.BangTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.CloseAngleBracketTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.CloseBraceTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.CloseParenthesisTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.CloseSquareBracketTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.ColonTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.CommaTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.CommentSingleLineTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.DivisionTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.DollarSignTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.EndOfFileTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.EqualsEqualsTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.EqualsTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.IdentifierTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.KeywordContextualTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.KeywordTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.MemberAccessTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.MinusTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.OpenAngleBracketTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.OpenBraceTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.OpenParenthesisTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.OpenSquareBracketTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.PlusPlusTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.PlusTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.QuestionMarkTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.StarTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.StatementDelimiterTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.StringLiteralTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.TextEditorDiagnosticTests.Constructor, Luthetus.TextEditor.Tests.Basis.Lexes.Models.TextEditorTextSpanTests.Constructor_A, Luthetus.TextEditor.Tests.Basis.Lexes.Models.TextEditorTextSpanTests.Constructor_B, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.CSharpBinder, Luthetus.TextEditor.Tests.Basis.CompilerServices.TextEditorDefaultParserTests.DiagnosticsList, Luthetus.Extensions.Git.Models.GitCliOutputParser.GetBranchListEntire, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GetFunctionDefinitionNodesByScope, Luthetus.TextEditor.RazorLib.CompilerServices.Binder.GetFunctionDefinitionNodesByScope, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.GetFunctionDefinitionNodesByScope, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Namespaces.GetInitialBoundNamespaceStatementNodes, Luthetus.CompilerServices.Json.SyntaxObjects.JsonPropertyValueSyntax.GetInvalidJsonPropertyValueSyntax, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GetReturnTypeClauseNodeByScope, Luthetus.TextEditor.RazorLib.CompilerServices.Binder.GetReturnTypeClauseNodeByScope, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.GetReturnTypeClauseNodeByScope, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GetScopeByPositionIndex, Luthetus.TextEditor.RazorLib.CompilerServices.Binder.GetScopeByPositionIndex, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.GetScopeByPositionIndex, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GetScopeByScopeIndexKey, Luthetus.TextEditor.RazorLib.CompilerServices.Binder.GetScopeByScopeIndexKey, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.GetScopeByScopeIndexKey, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GetScopeList, Luthetus.TextEditor.RazorLib.CompilerServices.Binder.GetScopeList, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.GetScopeList, Luthetus.Ide.RazorLib.Terminals.Models.TerminalCompilerService.GetTokenTextSpansFor, Luthetus.CompilerServices.CSharp.Facts.CSharpFacts.Namespaces.GetTopLevelNamespaceStatementNode, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GetTypeDefinitionNodesByScope, Luthetus.TextEditor.RazorLib.CompilerServices.Binder.GetTypeDefinitionNodesByScope, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.GetTypeDefinitionNodesByScope, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GetVariableDeclarationNodesByScope, Luthetus.TextEditor.RazorLib.CompilerServices.Binder.GetVariableDeclarationNodesByScope, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.GetVariableDeclarationNodesByScope, Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Lexers.LexerTests.LEX_BangToken, Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Lexers.LexerTests.LEX_ClassDefinition, Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Lexers.LexerTests.LEX_CloseAngleBracketToken, Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Lexers.LexerTests.LEX_CloseBraceToken, Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Lexers.LexerTests.LEX_CloseParenthesisToken, Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Lexers.LexerTests.LEX_CloseSquareBracketToken, Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Lexers.LexerTests.LEX_ColonToken, Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Lexers.LexerTests.LEX_CommaToken, Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Lexers.LexerTests.LEX_DollarSignToken, Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Lexers.LexerTests.LEX_EqualsEqualsToken, Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Lexers.LexerTests.LEX_EqualsToken, Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Lexers.LexerTests.LEX_EscapedStrings, Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Lexers.LexerTests.LEX_IdentifierToken, Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Lexers.LexerTests.LEX_MemberAccessToken, Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Lexers.LexerTests.LEX_MinusMinusToken, Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Lexers.LexerTests.LEX_MinusToken, Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Lexers.LexerTests.LEX_NumericLiteralToken, Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Lexers.LexerTests.LEX_OpenAngleBracketToken, Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Lexers.LexerTests.LEX_OpenBraceToken, Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Lexers.LexerTests.LEX_OpenParenthesisToken, Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Lexers.LexerTests.LEX_OpenSquareBracketToken, Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Lexers.LexerTests.LEX_PlusPlusToken, Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Lexers.LexerTests.LEX_PlusToken, Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Lexers.LexerTests.LEX_QuestionMarkQuestionMarkToken, Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Lexers.LexerTests.LEX_QuestionMarkToken, Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Lexers.LexerTests.LEX_StarToken, Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Lexers.LexerTests.LEX_StatementDelimiterToken, Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Lexers.LexerTests.LEX_StringLiteralToken, Luthetus.CompilerServices.CSharp.ParserCase.CSharpParser.Parse, Luthetus.Extensions.DotNet.Tests.Basis.CommandLines.Models.DotNetCliOutputParserTests.DotNetCliOutputParser.Parse, Luthetus.Ide.RazorLib.Terminals.Models.TerminalInteractive.Parse, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.Parser.Parse, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IParser.Parse, Luthetus.Extensions.DotNet.CommandLines.Models.DotNetCliOutputParser.ParseOutputEntireDotNetRun, Luthetus.Extensions.DotNet.CommandLines.Models.DotNetCliOutputParser.ParseOutputLineDotNetNewList, Luthetus.CompilerServices.Css.SyntaxActors.CssSyntaxTree.ParseText, Luthetus.CompilerServices.Json.SyntaxActors.JsonSyntaxTree.ParseText, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseText, Luthetus.CompilerServices.Razor.RazorSyntaxTree.RazorSyntaxTree, Luthetus.TextEditor.Tests.Basis.CompilerServices.StringWalkerTests.ReadUnsignedNumericLiteral, Luthetus.TextEditor.Tests.Basis.CompilerServices.StringWalkerTests.ReadWhitespace, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.RemoveBinderSession, Luthetus.TextEditor.RazorLib.CompilerServices.Binder.RemoveBinderSession, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.RemoveBinderSession, Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.SetFunctionDefinitionNodeByScope, Luthetus.TextEditor.RazorLib.CompilerServices.Binder.SetFunctionDefinitionNodeByScope, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.SetFunctionDefinitionNodeByScope, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.SetTypeDefinitionNodeByScope, Luthetus.TextEditor.RazorLib.CompilerServices.Binder.SetTypeDefinitionNodeByScope, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.SetTypeDefinitionNodeByScope, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.SetVariableDeclarationNodeByScope, Luthetus.TextEditor.RazorLib.CompilerServices.Binder.SetVariableDeclarationNodeByScope, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.SetVariableDeclarationNodeByScope, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.StartBinderSession, Luthetus.TextEditor.RazorLib.CompilerServices.Binder.StartBinderSession, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.StartBinderSession, Luthetus.Extensions.Git.Models.GitCliOutputParser.StatusParseEntire, Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Parsers.ExpressionAsStatementTests.Test.Test, Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Parsers.ExpressionTests.Test.Test, Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Parsers.ScopeTests.Test.Test, Luthetus.CompilerServices.CSharp.Tests.SmokeTests.Parsers.StatementTests.Test.Test, Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryAddFunctionDefinitionNodeByScope, Luthetus.TextEditor.RazorLib.CompilerServices.Binder.TryAddFunctionDefinitionNodeByScope, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.TryAddFunctionDefinitionNodeByScope, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryAddReturnTypeClauseNodeByScope, Luthetus.TextEditor.RazorLib.CompilerServices.Binder.TryAddReturnTypeClauseNodeByScope, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.TryAddReturnTypeClauseNodeByScope, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryAddTypeDefinitionNodeByScope, Luthetus.TextEditor.RazorLib.CompilerServices.Binder.TryAddTypeDefinitionNodeByScope, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.TryAddTypeDefinitionNodeByScope, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryAddVariableDeclarationNodeByScope, Luthetus.TextEditor.RazorLib.CompilerServices.Binder.TryAddVariableDeclarationNodeByScope, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.TryAddVariableDeclarationNodeByScope, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryGetBinderSession, Luthetus.TextEditor.RazorLib.CompilerServices.Binder.TryGetBinderSession, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.TryGetBinderSession, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryGetFunctionDefinitionNodeByScope, Luthetus.TextEditor.RazorLib.CompilerServices.Binder.TryGetFunctionDefinitionNodeByScope, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.TryGetFunctionDefinitionNodeByScope, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryGetFunctionHierarchically, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryGetTypeDefinitionHierarchically, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryGetTypeDefinitionNodeByScope, Luthetus.TextEditor.RazorLib.CompilerServices.Binder.TryGetTypeDefinitionNodeByScope, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.TryGetTypeDefinitionNodeByScope, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryGetVariableDeclarationHierarchically, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryGetVariableDeclarationNodeByScope, Luthetus.TextEditor.RazorLib.CompilerServices.Binder.TryGetVariableDeclarationNodeByScope, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.TryGetVariableDeclarationNodeByScope.
record struct Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan(int StartingIndexInclusive, int EndingIndexExclusive, byte DecorationByte, ResourceUri ResourceUri, string SourceText)
TODO: I have a suspicion that this type takes an absurd amount of memory... ... the initial way of implementing this type was to store the text at the time of constructing the text span. | But, it was thought that preferably one would only only create the substring when asked for it. | This means one has to store the entirety of the source text. Well, the source text is just a reference not a copy of the value. So this seemed fine enough. | But, because the text editor is immutable. The source text is constantly needing to be reconstructed as a string value. | As a result, the old string values that pertain to previous iterations of the text editor must be held in memory, because any TextEditorTextSpan that is not garbage collected, would have a reference to the old string value. | I'm thinking of using Span<char> or something along the lines. But, wouldn't Span<char> still need to maintain the previous string in its entirety? | If Span<T> will somehow track what section of the previous string I have a reference to, and only free the resources pertaining to the sections of the string that don't have a Span<T> referencing them then that would be amazing. | But then again, why am I not just letting the text span capture the substring upon construction? | I also wonder, what about a Func<string>? Does this somehow hide the previous string values of the text editor and permit the resources to be free'd? (2024-07-27).
Changed to a record-struct (was previously just a record) This type is not a 1 instance per file scenario. The type is instantiated many times for each file, and then again instantiated each time the file is re-parsed. So the instantiation/lifecycle of this type is lending it to being a struct. (2024-010-02)
References Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.PositionIndex, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ResourceUri, Luthetus.TextEditor.RazorLib.Lexers.Models.ResourceUri, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.SourceText, Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.ArraySyntaxToken.ArraySyntaxToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.AssociatedNameToken.AssociatedNameToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.AssociatedValueToken.AssociatedValueToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.AtToken.AtToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.BadToken.BadToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.BangToken.BangToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.BindBinaryOperatorNode, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.CharLiteralToken.CharLiteralToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.CloseAngleBracketToken.CloseAngleBracketToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.CloseAssociatedGroupToken.CloseAssociatedGroupToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.CloseBraceToken.CloseBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.CloseParenthesisToken.CloseParenthesisToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.CloseScope, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.CloseSquareBracketToken.CloseSquareBracketToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.ColonToken.ColonToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.CommaToken.CommaToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.CommentMultiLineToken.CommentMultiLineToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.CommentSingleLineToken.CommentSingleLineToken, Luthetus.Extensions.DotNet.Tests.Basis.TreeViewImplementations.Models.TreeViewSolutionFolderTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.CodeBlockBuilderTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.CodeBlockNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.StringWalkerTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.Symbols.ConstructorSymbolTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.Symbols.FieldSymbolTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.Symbols.FunctionSymbolTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.Symbols.InjectedLanguageComponentSymbolTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.Symbols.NamespaceSymbolTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.Symbols.PropertySymbolTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.Symbols.StringInterpolationSymbolTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.Symbols.SymbolDefinitionTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.Symbols.SymbolReferenceTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.Symbols.TypeSymbolTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.Symbols.VariableSymbolTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.AmbiguousIdentifierNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.AttributeNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.BinaryExpressionNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.BinaryOperatorNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.ConstraintNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.ConstructorDefinitionNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.EmptyExpressionNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.FunctionArgumentEntryNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.FunctionArgumentsListingNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.FunctionDefinitionNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.FunctionInvocationNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.FunctionParameterEntryNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.FunctionParametersListingNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.GenericArgumentEntryNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.GenericArgumentsListingNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.GenericParameterEntryNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.GenericParametersListingNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.IfStatementNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.InheritanceStatementNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.LiteralExpressionNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.ParenthesizedExpressionNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.ReturnStatementNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.TypeClauseNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.TypeDefinitionNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.VariableAssignmentExpressionNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.VariableDeclarationNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.VariableReferenceNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.ArraySyntaxTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.BangTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.CloseAngleBracketTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.CloseBraceTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.CloseParenthesisTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.CloseSquareBracketTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.ColonTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.CommaTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.CommentSingleLineTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.DivisionTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.DollarSignTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.EndOfFileTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.EqualsEqualsTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.EqualsTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.IdentifierTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.KeywordContextualTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.KeywordTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.MemberAccessTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.MinusTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.OpenAngleBracketTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.OpenBraceTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.OpenParenthesisTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.OpenSquareBracketTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.PlusPlusTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.PlusTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.QuestionMarkTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.StarTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.StatementDelimiterTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxTokens.StringLiteralTokenTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.TextEditorDiagnosticTests.Constructor, Luthetus.TextEditor.Tests.Basis.Lexes.Models.TextEditorTextSpanTests.Constructor_A, Luthetus.TextEditor.Tests.Basis.Lexes.Models.TextEditorTextSpanTests.Constructor_B, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Symbols.ConstructorSymbol.ConstructorSymbol, Luthetus.TextEditor.Tests.Basis.CompilerServices.TextEditorDefaultBinderTests.DiagnosticsList, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.DivisionToken.DivisionToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.DollarSignToken.DollarSignToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.EndOfFileToken.EndOfFileToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.EqualsEqualsToken.EqualsEqualsToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.EqualsToken.EqualsToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Symbols.FieldSymbol.FieldSymbol, Luthetus.Ide.RazorLib.Terminals.Models.TerminalOutputFormatterExpand.Format, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Symbols.FunctionSymbol.FunctionSymbol, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxObjects.GenericCommentMultiLineSyntax.GenericCommentMultiLineSyntax, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxObjects.GenericCommentSingleLineSyntax.GenericCommentSingleLineSyntax, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxObjects.GenericDeliminationExtendedSyntax.GenericDeliminationExtendedSyntax, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxObjects.GenericDocumentSyntax.GenericDocumentSyntax, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxObjects.GenericFunctionSyntax.GenericFunctionSyntax, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxObjects.GenericKeywordSyntax.GenericKeywordSyntax, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxObjects.GenericPreprocessorDirectiveSyntax.GenericPreprocessorDirectiveSyntax, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxObjects.GenericStringSyntax.GenericStringSyntax, Luthetus.CompilerServices.CSharp.CompilerServiceCase.CSharpCompilerService.GetAutocompleteEntries, Luthetus.TextEditor.RazorLib.CompilerServices.Implementations.CompilerService.GetAutocompleteEntries, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.ICompilerService.GetAutocompleteEntries, Luthetus.Extensions.Git.Models.GitCliOutputParser.GetBranchListEntire, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GetDefinition, Luthetus.TextEditor.RazorLib.CompilerServices.Binder.GetDefinition, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.GetDefinition, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.GetScope, Luthetus.TextEditor.RazorLib.CompilerServices.Binder.GetScope, Luthetus.TextEditor.RazorLib.CompilerServices.Interfaces.IBinder.GetScope, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.IdentifierToken.IdentifierToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Symbols.InjectedLanguageComponentSymbol.InjectedLanguageComponentSymbol, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.KeywordContextualToken.KeywordContextualToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.KeywordToken.KeywordToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.LambdaMergeToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Symbols.LambdaSymbol.LambdaSymbol, Luthetus.CompilerServices.CSharp.LexerCase.CSharpLexer.Lex, Luthetus.CompilerServices.DotNetSolution.SyntaxActors.DotNetSolutionLexer.Lex, Luthetus.CompilerServices.Xml.Html.SyntaxActors.TextEditorXmlLexer.Lex, Luthetus.CompilerServices.DotNetSolution.SyntaxActors.DotNetSolutionLexer.LexGlobal, Luthetus.CompilerServices.DotNetSolution.SyntaxActors.DotNetSolutionLexer.LexGlobalSection, Luthetus.CompilerServices.DotNetSolution.SyntaxActors.DotNetSolutionLexer.LexGuid, Luthetus.CompilerServices.DotNetSolution.SyntaxActors.DotNetSolutionLexer.LexProjectDefinitionEntry, Luthetus.CompilerServices.DotNetSolution.SyntaxActors.DotNetSolutionLexer.LexString, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.LibraryReferenceToken.LibraryReferenceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.MemberAccessToken.MemberAccessToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.MinusMinusToken.MinusMinusToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.MinusToken.MinusToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Symbols.NamespaceSymbol.NamespaceSymbol, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.NumericLiteralToken.NumericLiteralToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Symbols.OnClickSymbol.OnClickSymbol, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.OpenAngleBracketToken.OpenAngleBracketToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.OpenAssociatedGroupToken.OpenAssociatedGroupToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.OpenBraceToken.OpenBraceToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.OpenParenthesisToken.OpenParenthesisToken, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.OpenScope, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.OpenSquareBracketToken.OpenSquareBracketToken, Luthetus.CompilerServices.DotNetSolution.SyntaxActors.DotNetSolutionParser.ParseAssociatedValueToken, Luthetus.CompilerServices.Razor.RazorSyntaxTree.ParseAttributeName, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseCommentMultiLine, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseCommentSingleLine, Luthetus.CompilerServices.Razor.RazorSyntaxTree.ParseInjectedLanguageFragment, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseString, Luthetus.CompilerServices.Razor.RazorSyntaxTree.ParseTagName, Luthetus.CompilerServices.Css.SyntaxActors.CssSyntaxTree.ParseText, Luthetus.CompilerServices.Json.SyntaxActors.JsonSyntaxTree.ParseText, Luthetus.TextEditor.RazorLib.CompilerServices.GenericLexer.SyntaxActors.GenericSyntaxTree.ParseText, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.PlusPlusToken.PlusPlusToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.PlusToken.PlusToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.PreprocessorDirectiveToken.PreprocessorDirectiveToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Symbols.PropertySymbol.PropertySymbol, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.QuestionMarkQuestionMarkToken.QuestionMarkQuestionMarkToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.QuestionMarkToken.QuestionMarkToken, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadUnsignedNumericLiteral, Luthetus.TextEditor.RazorLib.CompilerServices.Utility.StringWalker.ReadWordTuple, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportAlreadyDefinedFunction, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportAlreadyDefinedProperty, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportAlreadyDefinedType, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportAlreadyDefinedVariable, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportBadFunctionOptionalArgumentDueToMismatchInType, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportConstructorsNeedToBeWithinTypeDefinition, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportEndOfFileUnexpected, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportImplicitlyTypedVariablesMustBeInitialized, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportNotDefinedInContext, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportOpenTagWithUnMatchedCloseTag, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportRazorCodeBlockWasExpectedToFollowRazorKeyword, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportRazorExplicitExpressionPredicateWasExpected, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportRazorWhitespaceImmediatelyFollowingTransitionCharacterIsUnexpected, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportReturnStatementsAreStillBeingImplemented, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportTagNameMissing, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportTodoException, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportUndefinedClass, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportUndefinedFunction, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportUndefinedTypeOrNamespace, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportUndefinedVariable, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportUnexpectedToken, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.ReportUnexpectedToken, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.RevealCursor, Luthetus.TextEditor.RazorLib.TextEditors.Models.ITextEditorViewModelApi.ScrollIntoView, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.ScrollIntoView, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Symbols.SourceFileSymbol.SourceFileSymbol, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.StarToken.StarToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.StatementDelimiterToken.StatementDelimiterToken, Luthetus.Extensions.Git.Models.GitCliOutputParser.StatusParseEntire, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Symbols.StringInterpolationSymbol.StringInterpolationSymbol, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.StringLiteralToken.StringLiteralToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Symbols.StringVerbatimSymbol.StringVerbatimSymbol, Luthetus.TextEditor.RazorLib.CompilerServices.TextEditorDiagnostic, Luthetus.TextEditor.RazorLib.Decorations.Models.TextEditorTextModification, Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan, Luthetus.TextEditor.RazorLib.CompilerServices.DiagnosticBag.TheNameDoesNotExistInTheCurrentContext, Luthetus.Ide.RazorLib.CodeSearches.Models.TreeViewCodeSearchTextSpan.TreeViewCodeSearchTextSpan, Luthetus.TextEditor.RazorLib.FindAlls.Models.TreeViewFindAllTextSpan.TreeViewFindAllTextSpan, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.TriviaToken.TriviaToken, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Symbols.TypeSymbol.TypeSymbol, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Symbols.VariableSymbol.VariableSymbol.