Luthetus::TextEditor::RazorLib::Diffs::Models
TextEditorDiffDecorationKind
record Luthetus.TextEditor.RazorLib.Diffs.Models.TextEditorDiffModel(Key< TextEditorDiffModel > DiffKey, Key< TextEditorViewModel > InViewModelKey, Key< TextEditorViewModel > OutViewModelKey)
Referenced by Luthetus.TextEditor.Tests.Basis.Diffs.States.TextEditorDiffStateMainTests.DiffModelList, Luthetus.TextEditor.RazorLib.Diffs.Models.ITextEditorDiffApi.GetOrDefault, Luthetus.TextEditor.RazorLib.Diffs.Models.TextEditorDiffApi.GetOrDefault, Luthetus.TextEditor.RazorLib.Diffs.States.TextEditorDiffState.Reducer.ReduceRegisterAction, Luthetus.TextEditor.RazorLib.Diffs.Models.TextEditorDiffModelModifier.TextEditorDiffModelModifier.