Luthetus::TextEditor::RazorLib::CompilerServices
record struct Luthetus.TextEditor.RazorLib.CompilerServices.ScopeKeyAndIdentifierText(int ScopeIndexKey, string IdentifierText)
References Luthetus.TextEditor.RazorLib.CompilerServices.ScopeKeyAndIdentifierText.
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.ScopeKeyAndIdentifierText, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.SetFunctionDefinitionNodeByScope, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.SetTypeDefinitionNodeByScope, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.SetVariableDeclarationNodeByScope, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryAddFunctionDefinitionNodeByScope, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryAddTypeDefinitionNodeByScope, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryAddVariableDeclarationNodeByScope, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryGetFunctionDefinitionNodeByScope, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryGetTypeDefinitionNodeByScope, Luthetus.CompilerServices.CSharp.BinderCase.CSharpBinder.TryGetVariableDeclarationNodeByScope.
record Luthetus.TextEditor.RazorLib.CompilerServices.TextEditorDiagnostic(TextEditorDiagnosticLevel DiagnosticLevel, string Message, TextEditorTextSpan TextSpan, Guid Id)
Use the Id to determine if two diagnostics are reporting the same diagnostic but perhaps with differing messages due to variable interpolation into the string.
References Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan.
Referenced by Luthetus.TextEditor.Tests.Basis.CompilerServices.CodeBlockBuilderTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.CodeBlockNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.TextEditorDiagnosticTests.Constructor.