Luthetus::TextEditor::RazorLib::CompilerServices::Syntax::Tokens::OpenParenthesisToken
TextEditorTextSpan Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.OpenParenthesisToken.TextSpan
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.OpenParenthesisToken.OpenParenthesisToken.
SyntaxKind Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.OpenParenthesisToken.SyntaxKind
bool Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.OpenParenthesisToken.IsFabricated
IsFabricated refers to when the ParserSession expected a node to be valid, but it wasn't. For example, a function invocation on an undefined function will construct a BoundFunctionInvocationNode with IsFabricated set to true.
bool Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.OpenParenthesisToken.ConstructorWasInvoked
If the struct instance is default, this will be false. Otherwise, it will be true.
Referenced by Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.OpenParenthesisToken.OpenParenthesisToken.
Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.OpenParenthesisToken.OpenParenthesisToken(TextEditorTextSpan textSpan)
References Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.OpenParenthesisToken.ConstructorWasInvoked, Luthetus.TextEditor.RazorLib.Lexers.Models.TextEditorTextSpan, Luthetus.TextEditor.RazorLib.CompilerServices.Syntax.Tokens.OpenParenthesisToken.TextSpan.
Referenced by Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.FunctionArgumentsListingNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.FunctionParametersListingNodeTests.Constructor, Luthetus.TextEditor.Tests.Basis.CompilerServices.Syntax.SyntaxNodes.ParenthesizedExpressionNodeTests.Constructor.