Luthetus::Common::RazorLib::Keymaps::Models::KeymapArgs
Key<KeymapLayer> Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.LayerKey
Referenced by Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.Equals.
string? Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.Key
Referenced by Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.Equals, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.GetHashCode, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.HandleKeyboardEvent, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.KeymapArgs, Luthetus.Common.RazorLib.Keymaps.Models.Keymap.MapFirstOrDefault, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.MoveCursorUnsafe, Luthetus.Common.RazorLib.Keymaps.Models.Keymap.TryRegister.
string? Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.Code
Referenced by Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.Equals, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.GetHashCode, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.HandleKeyboardEvent, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.KeymapArgs, Luthetus.Common.RazorLib.Keymaps.Models.Keymap.MapFirstOrDefault, Luthetus.Common.RazorLib.Keymaps.Models.Keymap.TryRegister.
float Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.Location
Referenced by Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.KeymapArgs.
bool Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.Repeat
Referenced by Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.KeymapArgs.
bool Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.CtrlKey
Referenced by Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.Equals, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorModelModifier.HandleKeyboardEvent, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.KeymapArgs, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.MoveCursorUnsafe.
bool Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.ShiftKey
Referenced by Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.Equals, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.KeymapArgs, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.MoveCursorUnsafe.
bool Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.AltKey
Referenced by Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.Equals, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.KeymapArgs, Luthetus.TextEditor.RazorLib.TextEditors.Models.TextEditorViewModelApi.MoveCursorUnsafe.
bool Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.MetaKey
Referenced by Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.Equals, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.KeymapArgs.
string? Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.Type
Referenced by Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.KeymapArgs.
Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.KeymapArgs()
Referenced by Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.Equals, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.operator!=, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.operator==.
Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.KeymapArgs(KeyboardEventArgs keyboardEventArgs)
References Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.AltKey, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.Code, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.CtrlKey, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.Key, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.Location, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.MetaKey, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.Repeat, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.ShiftKey, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.Type.
override bool Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.Equals(object? obj)
References Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.AltKey, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.Code, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.CtrlKey, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.Key, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.KeymapArgs, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.LayerKey, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.MetaKey, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.ShiftKey.
Referenced by Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.operator==.
override int Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.GetHashCode()
References Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.Code, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.Key.
static bool Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.operator==(KeymapArgs left, KeymapArgs right)
References Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.Equals, Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.KeymapArgs.
static bool Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.operator!=(KeymapArgs left, KeymapArgs right)
References Luthetus.Common.RazorLib.Keymaps.Models.KeymapArgs.KeymapArgs.